### ISSUE TITLE
Add active window's title in the filename as option

### ISSUE THREAD

**Issue by 4goodapp** [flameshot-org/flameshot#100]
It'd be nice to have an option to add the currently active windows title in the filename. Something like this:

![2018-01-21_01 59 45](https://user-images.githubusercontent.com/6249230/35190025-c32d93a8-fe4f-11e7-83b8-a063590b4b4a.png)

**Comment by ZetaoYang** [comment]
Getting the active window title:
for Windows: can achieve this on Windows using the WinAPI.
for X11: use [xdotool](https://github.com/jordansissel/xdotool): `xdotool getwindowfocus getwindowname`
Also can get windows position and size, `xdotool getactivewindow getwindowgeometry --shell`

http://amin-ahmadi.com/2016/06/21/how-to-get-the-topmost-window-title-using-qtc-in-linux/
https://forum.qt.io/topic/7761/getting-the-window-title-of-a-non-qt-application/2

**Comment by guktib** [comment]
It would be really great to have the option to capture also the window title in(to) the filename.
Like in Spectacle -> "%T: Window title"

![screenshot_20200801_120546_spectacle](https://user-images.githubusercontent.com/66076942/89099492-f805de00-d3ef-11ea-8a88-053bf148af23.png)

(maybe also the possibility for  Sequential numbering ...)

**Comment by borgmanJeremy** [comment]
This will not be added due to the complexity of supporting it on all platforms and DE's.
