### ISSUE TITLE
Flameshot notification on Windows uses "flameshot.exe" as app name

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1000]
**Flameshot version**
(all versions)

**Describe the bug**
On Windows, the notification sent by flameshot has "flameshot.exe" as title.
Ideally it should be "Flameshot" or localized name of "Flameshot".

This is a minor bug though.

**To Reproduce**
Make a screenshot using flameshot and copy to clipboard. Check the notification popped up.

![图片](https://user-images.githubusercontent.com/8443926/94443910-bb4a2f00-0173-11eb-8a40-31dd4e172b8b.png)

**Expected behavior**
The title of notification should be localized name of "Flameshot" instead of literal "flameshot.exe".

**System Information**
Windows 10 19041

**Comment by borgmanJeremy** [comment]
Was this installed via the .msi installer or .zip folder?

**Comment by hosiet** [comment]
Both .msi installer or .zip standalone version all have the same result.

**Comment by ZetaoYang** [comment]
enhanced https://github.com/flameshot-org/flameshot/pull/1014
