### ISSUE TITLE
Add optional buttons to increase / decrease toolsize for tablets etc.

### ISSUE THREAD

**Issue by Martin-Eckleben** [flameshot-org/flameshot#1003]
Forked from #782 as its a different issue I think.
Almost done with it. Created + / - Icons in B&W. Created the tools. Made them default configured tools. etc. etc.
Just needs one more evening with a coffee which should be 30.09.2020 UTC+2 :)

**Comment by borgmanJeremy** [comment]
For tablets do gestures work ? I think the zoom gesture will adjust size.

**Comment by Martin-Eckleben** [comment]
Ooh that would be even better UX!
Good idea why didn't I think of it :)

Can someone with a tablet confirm?

**Comment by mmahmoudian** [comment]
@Martin-Eckleben it seems your code works fine according to [a kind user](https://github.com/flameshot-org/flameshot/issues/792#issuecomment-700629582). Can we consider it as "final stage" and add this to 0.9?

**Comment by borgmanJeremy** [comment]
We need to make sure we wait until after the namecheap merge is complete since it completely reworked hotkeys.

**Comment by Martin-Eckleben** [comment]
The Shortcuts should be an individual issue.
I'd wait for users to ask for them again after all the improvements.

**Comment by AlexP11223** [comment]
> I think the zoom gesture will adjust size.

This may be not intuitive because it's more suitable for zoom of the whole image.

**Comment by mmahmoudian** [comment]
@Martin-Eckleben @borgmanJeremy should this be closed?

**Comment by mmahmoudian** [comment]
@Martin-Eckleben I believe it was done by (or based on) your own code (#1131) as we have these two items already in v.0.10.1 😉 

![image](https://user-images.githubusercontent.com/390889/127976533-b68a5385-322d-41c9-82d5-94df0fe5684a.png)

**Comment by mmahmoudian** [comment]
@borgmanJeremy @veracioux @Martin-Eckleben Shall we close this?

**Comment by Martin-Eckleben** [comment]
I think it should be closed.
Thank you for your enduring work despite my sudden disappearance :D
