### ISSUE TITLE
[Feature request] Pin tool Enhance: copy pinned picture

### ISSUE THREAD

**Issue by vio1etus** [flameshot-org/flameshot#1007]
**Is your feature request related to a problem?**
I'm always frustrated when I want to copy the pinned image.

add the copy pinned picture function

**Comment by borgmanJeremy** [comment]
Related to #954

**Comment by toofar** [comment]
This was implemented in #2519 via a context menu so I think this issue can be closed now!

Also I think the top post of #954 could be edited to cross out the item about this functionality and link to the merged PR.

(As an aside, that's kind of a grab bag issue, but out of everything discussed in it it seems the only thing discussed there that doesn't have its own PR is "improve the usability/discoverability/UX of pinned image".)

**Comment by mmahmoudian** [comment]
@toofar thanks for pointing these out
