### ISSUE TITLE
text disapperas after image saved

### ISSUE THREAD

**Issue by soundsbeard** [flameshot-org/flameshot#1008]
**Flameshot version**
0.6.0
compiled with qt 5.14.1

**Describe the bug**
text, written with text tool, doesn't save while saving an image to hard drive.
its fine while uploading to imgur tho
https://i.imgur.com/KZ0v5Oh.mp4

**To Reproduce**
- launch flameshot
- select part of the screen
- select text tool and write some text
- ctrl + s to save an image
- no text on saved image

**Expected behavior**
the text is saved on an image

**System Information**
tested on 2 systems:
https://pastebin.com/vVYLjhDR
https://pastebin.com/k9ZPHncw

**Comment by borgmanJeremy** [comment]
Please update to 0.8.3, this should be resolved.
