### ISSUE TITLE
The icon does not appear in the GNOME bar

### ISSUE THREAD

**Issue by ejsc1** [flameshot-org/flameshot#1009]
**Open bug in launchpad.net**
https://bugs.launchpad.net/bugs/1897754

**Flameshot version**
Package: flameshot 0.8.1-1

**Describe the bug**
When upgrading from gnome-shell-extension-appindicator_33-3_all.deb to gnome-shell-extension-appindicator_34-1_all.deb the icon does not appear in the GNOME toolbar.

**To Reproduce**
Update from gnome-shell-extension-appindicator_33-3_all.deb to gnome-shell-extension-appindicator_34-1_all.deb

**Expected behavior**
Bring the icon to the GNOME bar

**System Information**
DistroRelease: Ubuntu 20.10

**Comment by borgmanJeremy** [comment]
Is this actually an issue with flameshot or the updated gnome shell indicator?

**Comment by hosiet** [comment]
I doubt this is an issue specific to flameshot. After rebooting your system, if you open other applications with a tray icon, will that icon show as well?

**Comment by ejsc1** [comment]
> Is this actually an issue with flameshot or the updated gnome shell indicator?

The problem only occurs with flameshot, all other icons from other programs are seen in the GNOME bar.

**Comment by ejsc1** [comment]
When I switch from gnome-shell-extension-appindicator_34-1_all.deb to gnome-shell-extension-appindicator_33-3_all.deb It works again.

**Comment by ejsc1** [comment]
I just installed this extension: https://extensions.gnome.org/extension/1503/tray-icons/ and after this, the flameshot icon appears immediately.

References:
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/250
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/251

**Comment by borgmanJeremy** [comment]
Okay thanks for letting us know. I will leave this issue open until we add something to the readme.

**Comment by mmahmoudian** [comment]
Gnome removing systray was a big thing back in the day:
https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray

I agree that we should update the README to reflect that "the icon will appear if and only if you have a systray installed. I'll try to put something together and make PR.

**Comment by gerhardbeck** [comment]
In my case also the Nextcloud icon disappeared.
I could solve the problem in downgrading to 33-1, then it worked again

**Comment by jose1711** [comment]
No icon on Arch/Gnome, using `gnome-shell-extension-appindicator`. One can still rightclick the flameshot icon and start capture from a context menu.

**Comment by w3roman** [comment]
> I just installed this extension: https://extensions.gnome.org/extension/1503/tray-icons/ and after this, the flameshot icon appears immediately.
> 
> References: [ubuntu/gnome-shell-extension-appindicator#250](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/250) [ubuntu/gnome-shell-extension-appindicator#251](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/251)

Incompatible now

![Image](https://github.com/user-attachments/assets/8e16114e-c419-4d3e-b4c2-27b554031777)

**Comment by borgmanJeremy** [comment]
@w3roman  This is the extension I use for testing Flameshot on gnome: https://extensions.gnome.org/extension/615/appindicator-support/
