### ISSUE TITLE
Update the OpenSuse Software Repository

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1011]
The latest available version in [OpenSuse Software Repository](https://software.opensuse.org//download.html?project=home%3AVitzy&package=flameshot) is 0.6.0-0 and it needs to be updated.

**Comment by borgmanJeremy** [comment]
This should be filled against the distro not flameshot.

**Comment by mmahmoudian** [comment]
My understanding is that this repository is similar to Arch's AUR and maintained by users. That is why you can also download .deb from the website as well.

For instance I know that [Albert launcher](https://albertlauncher.github.io/docs/installing/) is maintained by the main dev:
https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert

(Note the `home:manuelschneid3r`)

**Comment by trochdewei** [comment]
There is 0.8.1 in tumbleweed already https://software.opensuse.org/package/flameshot

**Comment by borgmanJeremy** [comment]
We also do not maintain the AUR. I really only want to support snap installation but thanks to the help of @ZetaoYang we support .deb, .rpm, .Appimage, and .flatpak.I really don't want to sign up to also support AUR and the OpenSuse software repository. IMO software packaging should be handled by distro's not upstream projects.

**Comment by mmahmoudian** [comment]
@borgmanJeremy then we should update the README and remove the part about this (line 255).
We can create a section on the website (flameshot.js.org) about unofficial repos and include AUR and this opensuse repo there.

**Comment by borgmanJeremy** [comment]
I think it is okay to still have them listed, they just need to be maintained by the community. We can file a ticket with whoever maintains the package for a given distro.

**Comment by ZetaoYang** [comment]
I maintain that openSUSE build service for flameshot.

**Comment by mmahmoudian** [comment]
@ZetaoYang is there any way to automate that?

**Comment by ZetaoYang** [comment]
@mmahmoudian I'm not going to continue to maintain it, because all packages are already built with GitHub Actions CI now.
So I suggest remove that OpenSuse Software Repository link from README.md.
