### ISSUE TITLE
Kvantum support broken with version 0.8.3-1 on Arch Linux/ArcoLinux

### ISSUE THREAD

**Issue by erikdubois** [flameshot-org/flameshot#1012]
**Flameshot version**
0.8.3-1
https://www.archlinux.org/packages/community/x86_64/flameshot/

**Describe the bug**
We had the possibility to theme the right mouse click menu on the system panel icon to follow the arc dark theme with kvantum manager. This is version 0.8.1

![before](https://user-images.githubusercontent.com/10594806/94676377-8b3d9000-031b-11eb-81dd-dae267a7921e.png)

Today we get version 0.8.3 in and we see that our theme is not applied..

![after](https://user-images.githubusercontent.com/10594806/94676400-942e6180-031b-11eb-8c53-eb42f923284e.png)

Could you investigate what part of the code is responsible for that?

Downgrading the package fixes the color scheme set by kvantum.

**Comment by borgmanJeremy** [comment]
I think this will be fixed in #1013. Are you able to test it?
