### ISSUE TITLE
Flameshot expects presence of Legacy Tray in Gnome

### ISSUE THREAD

**Issue by heis2201** [flameshot-org/flameshot#1021]
**Flameshot version**
0.8.3

**Describe the bug**
Flameshot expects support of Legacy Tray in Gnome, which is not the case unless user install a third-party extension. However, users are not informed that the extension is required, so the program simply doesn't start

**To Reproduce**
Install Fedora 33 workstation, install flameshot, run flameshot, see nothing 

**Expected behavior**
Install Fedora 33 workstation, install flameshot, run flameshot, see flameshot

**System Information**
This is a F33 test system, but should be equal on all current distros featuring Gnome.

**Workaround**
start flameshot using `flameshot gui`

**Comment by borgmanJeremy** [comment]
We recently updated the docs to to mention this: https://github.com/flameshot-org/flameshot#tray-icon

Do other applicaion icons appear by "default" in the new fedora? I can take a look at what they did.

**Comment by xvitaly** [comment]
Fedora maintainer here.

> Do other applicaion icons appear by "default" in the new fedora? I can take a look at what they did.

Most of applications with system tray icon support cannot show it in Gnome Shell without legacy tray extension support.

**Comment by borgmanJeremy** [comment]
Thanks for chiming in. Is there anything I need to do to better integrate? Or this is just how new stock gnome behaves and users will eventually learn?

**Comment by heis2201** [comment]
The system tray had been removed in Gnome 3.26 (released 2017). Ever since then a user requires an extension that brings back the functionality of the tray. Whoever does not have the extension is locked out. In my opinion, on Gnome, the app could just run as `flameshot gui`.

**Comment by borgmanJeremy** [comment]
After reviewing this design guide I do not think we will be making any changes. I prefer the default behavior to have a status icon which integrates well into other DE's. Gnome users have the following options:

1. Install a systray
1. Edit desktop file to launch 'flameshot gui'. This should not be the default for most DE's
1. Distro maintainers that make a gnome release can modify our package to better integrate with gnome
