### ISSUE TITLE
0.8.3: HiDPI issues

### ISSUE THREAD

**Issue by k0ste** [flameshot-org/flameshot#1023]
**Flameshot version**
0.8.3

**Describe the bug**
Flameshot thinks that my screen need to be multiplied on scaling factor?

**To Reproduce**
Run "Take a screenshot"

**Expected behavior**
Flameshot use "like a human see" screen picture size.

**System Information**
ArchLinux, Gnome, Wayland.
Screen resolution: 2160p, scaling 300%

How my screen actually look:
![IMG_3217](https://user-images.githubusercontent.com/7759548/94831901-76561f00-0437-11eb-9067-34c3dc308ccc.jpg)

How it look when "Take a screenshot"
![IMG_3216](https://user-images.githubusercontent.com/7759548/94832088-ae5d6200-0437-11eb-867d-d16c09546fbf.jpg)

**Comment by ZetaoYang** [comment]
this‘s the same as https://github.com/flameshot-org/flameshot/issues/933

**Comment by borgmanJeremy** [comment]
Closing as duplicate.
