### ISSUE TITLE
How to update to version 8 on Ubuntu 20.04?

### ISSUE THREAD

**Issue by asafm7** [flameshot-org/flameshot#1029]
Hi,

I'm using Flameshot 6.0 on Ubuntu 20.04 and not seeing available update both using the Ubuntu Software and the terminal.

On the terminal I'm getting:
flameshot is already the newest version (0.6.0+git20191001-2).

Thanks,
Asaf

**Comment by borgmanJeremy** [comment]
We currently have a snap in the snap store you can use. Or you may download a .deb from our release page.

**Comment by asafm7** [comment]
Thanks
