### ISSUE TITLE
Start Screenshot With Print Screen On Windows

### ISSUE THREAD

**Issue by drakhavik** [flameshot-org/flameshot#1032]
**Flameshot version**
0.8.0 and 0.8.3 tested

**Describe the bug**
Print Screen doesn't launch gui / start taking a screen shot. 

**To Reproduce**
Press print screen

**Expected behavior**
According to #988 Print Screen should open the GUI

**System Information**
Windows 10 Pro 2004

I checked the read-me and the Windows tag, didn't see an issue for this... sorry if duplicate or information on how to get this working is already available.

**Comment by borgmanJeremy** [comment]
This works by default for me on Windows. I have only tested the .exe not msi installer.

**Comment by drakhavik** [comment]
Neither the .exe or the .msi are working for me. I've run both as admin and not.

**Comment by borgmanJeremy** [comment]
Is the application running before you press print screen? Ie can you see the icon in the tray?

**Comment by drakhavik** [comment]
Figured it out - had to disable Settings > Ease of access > (Interaction) Keyboard > Print Screen shortcut and reboot. The built in Snip & Sketch app was getting run instead.

**Comment by borgmanJeremy** [comment]
Awesome thanks for posting the fix...it will help future users.
