### ISSUE TITLE
[Bug] QString::arg: Argument missing: ] flameshot + flameshot gui not launching

### ISSUE THREAD

**Issue by CircuitRCAY** [flameshot-org/flameshot#1038]
**Flameshot version**
Literally any version from v0.6, including the latest version.

**Describe the bug**

Flameshot does not display `flameshot -h` properly, `flameshot gui` does not launch, exits with error code 0 immediately.

![flameshot help](https://circ.x3.pm/i/c2es.png)
![flameshot exiting immediately](https://circ.x3.pm/i/g1v4.png)

**To Reproduce**

Build v0.8.1/master from source or install it through `sudo pacman -S flameshot`

**Expected behavior**

* `flameshot gui` launching without exiting straight away.
* CLI arguments parsing correctly.

**System Information**

![system information](https://circ.x3.pm/i/1dy1.png)

**Comment by mmahmoudian** [comment]
@CircuitRCAY would you please try the following and report back:
1. How about the `flameshot-git` AUR ?
2. Does the AppImage work (some general instructions [here](https://flameshot.js.org/#/data/appimage-snap-flatpak))

**Comment by CircuitRCAY** [comment]
1) Yes, I have tried the `flameshot-git` AUR, prior to manually building the source.

2) I will try the AppImage and edit this comment once I attempt to reproduce the error.

**Comment by borgmanJeremy** [comment]
I think there are two different issues here.

**Issue 1:** arguments not parsing properly. I am able to replicate the issue where the "-h" tag says there is a missing ']'. This should be fixed in our arg parsing re-write

**Issue 2:** flameshot gui does not launch for you. I am not able to reproduce this issue. I suspect this is a typically issue with a non functional DBUS installation or no notification daemon, especially given you are using i3.

**Comment by CircuitRCAY** [comment]
I agree there are two different issues here, just didn't want to spam the page.

> Issue 1: arguments not parsing properly. I am able to replicate the issue where the "-h" tag says there is a missing ']'. This should be fixed in our arg parsing re-write
Thank you, that issue is covered.

> Issue 2: flameshot gui does not launch for you. I am not able to reproduce this issue. I suspect this is a typical issue with a non functional DBUS installation or no notification daemon, especially given you are using i3.
There is a notification daemon on my installation (`dunst`), we could rule it down to the non-functional DBUS installation, though I do not know how to test/check for that.

**Comment by CircuitRCAY** [comment]
I did find the commannd `dbus-test-tool` and it's not even recognising spam method calls.
![dbus spam](https://circ.x3.pm/i/wkvn.png)

**Comment by borgmanJeremy** [comment]
@CircuitRCAY Checkout the tips in this thread and let me know if it helps: https://github.com/flameshot-org/flameshot/issues/879

**Comment by CircuitRCAY** [comment]
`dbus-launch i3` && `flameshot gui` works, thanks!

**Comment by borgmanJeremy** [comment]
awesome! We will get the arg parising issue resolve as part of #945
