### ISSUE TITLE
Pixelate tool behaves differently horizontally and vertically

### ISSUE THREAD

**Issue by sersorrel** [flameshot-org/flameshot#1039]
**Flameshot version**
0.8.3

**Describe the bug**
If you use the pixelate tool on a tall, thin area, the blocks are very small, even if you set the thickness to 100. But if you pixelate a wide area, the blocks grow closer to the proper size.

For example, both the areas here were pixelated with the same thickness (100), but because the lower area was less wide, the blocks are smaller:

![image](https://user-images.githubusercontent.com/9433472/95636748-d415e700-0a87-11eb-8b54-2940a86ccc1d.png)

**To Reproduce**
- set the thickness reasonably high
- pixelate an area

**Expected behavior**
The size of the blocks shouldn't depend on how wide the area to pixelate is. (Obviously they have to depend _slightly_ on the width, in the same way that they vary in height slightly to evenly divide the height of the area, but in general a wide area should be pixelated roughly the same amount as a tall area.)

**System Information**
Ubuntu 18.04

**Comment by borgmanJeremy** [comment]
This is actually the intended behavior. In the 0.8Beta, the thickness represented the actual pixel size, but this lead to confusion. The issue was if you set the thickness to 100, the minimum size required was 100pixels by 100pixels. 

This new behavior was selected so the selection size was always consistent.

**Comment by sersorrel** [comment]
It makes sense to allow arbitrarily-sized areas, but at the moment it's kind of difficult to properly censor anything that's less than a certain width, because the pixelation is so weak at small widths.

If I apply this patch, the pixelate tool seems to behaves how I expect it to:

```patch
--- a/src/tools/pixelate/pixelatetool.cpp
+++ b/src/tools/pixelate/pixelatetool.cpp
@@ -89,7 +89,7 @@ void PixelateTool::process(QPainter& painter,
         int width = selection.width() * (0.5 / qMax(1, m_thickness));

         QPixmap t = pixmap.copy(selection);
-        t = t.scaledToWidth(qMax(width, 10), Qt::SmoothTransformation);
+        t = t.scaledToWidth(qMax(width, 1), Qt::SmoothTransformation);
         t = t.scaledToWidth(selection.width());
         painter.drawImage(selection, t.toImage());
     }
```

You can still pixelate any size area you like, but the blocks you end up with will always be (approximately) the thickness in pixels. (so if you set the thickness very high, you'll have to select a large area before you see multiple blocks, but that seems correct?)

**Comment by borgmanJeremy** [comment]
Ahh ok, I understand what you are saying now. This patch looks good to me and still lets users select an arbitrary size. Want to submit a PR or want me to?

**Comment by sersorrel** [comment]
Submitted as #1041!

as mentioned there, I realised that it doesn't actually solve the issue, it just hides it a bit better. I'll try and find some time over the next week to take a look at solving it properly.
