### ISSUE TITLE
CI Issue on 18.04

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1045]
With the CI updates Ubuntu 18.04 is failing: 
https://github.com/flameshot-org/flameshot/pull/1043/checks?check_run_id=1235942416

**Comment by borgmanJeremy** [comment]
The issue seems to be on PR's it only looks for the branch name in the local repo.

**Comment by ZetaoYang** [comment]
I think this fixed by https://github.com/flameshot-org/flameshot/pull/1044.
