### ISSUE TITLE
Version mismatch in snap package

### ISSUE THREAD

**Issue by mystiquewolf** [flameshot-org/flameshot#1046]
**Flameshot version**

v 0.8.3 according to snap store, 0.8.1 according to "About" window
**Describe the bug**

![image](https://user-images.githubusercontent.com/16529989/95663814-e147da00-0b4a-11eb-8e37-ea1744c143a0.png)

![image](https://user-images.githubusercontent.com/16529989/95663830-076d7a00-0b4b-11eb-9abb-603cf7dd0006.png)

**To Reproduce**

Install flameshot from snaprcaft via Ubuntu Software
Run flameshot and open "About" window from the tray icon menu
Check the version mismatch
**Expected behavior**

Versions should match
**System Information**

Ubuntu 20.04.1

**Comment by borgmanJeremy** [comment]
Thanks for reporting this. Will get this fixed soon.

**Comment by borgmanJeremy** [comment]
Just published 0.8.4 to fix this and other bugs. Thanks for reporting!
