### ISSUE TITLE
[Feature Request] optimize the png with a tool like pngquant

### ISSUE THREAD

**Issue by bbigras** [flameshot-org/flameshot#1047]
It could be nice to be able to optimize the png when saving or pushing it to the clipboard.

Most of my screenshot are sent to people over the internet and are probably often received on mobile devices.

A quick test with pngquant: 115k -> 40k

**Comment by borgmanJeremy** [comment]
We are working a feature that lets you change the clipboard to jpeg. Would that work for you ?

**Comment by bbigras** [comment]
Yeah, I guess a jpeg must be pretty similar to a lossy png.

**Comment by borgmanJeremy** [comment]
Okay thanks, #496 is the issue where we are tracking the progress / discussing the new feature.
