### ISSUE TITLE
Monochrome Icon

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1050]
**Flameshot version**
0.8.4

The name of the icon is 0.8.4 was changed to org.flameshot.Flameshot.xxx to properly integrate with Flathub. This has broken the monochrome icon on KDE. Since we do not actually ship a monochrome icon, and pick it up from the system, this isn't exactly a bug against flameshot, but we need to notify the downstream icon sets of the name change.

I could use help finding the githubs / gitlabs of the applicable icon projects.

**Comment by ZetaoYang** [comment]
I think we just need to add the two images `flameshot.png` and `flameshot.svg` as well.

**Comment by hosiet** [comment]
What I saw is that the change of image name has become a regression for v0.8.4 release and we will have to make a v0.8.5 release to deal with the regression.

It should be okay to use the name org.flameshot.Flameshot.svg/.png. However I doubt whether it's reasonable to ask downstream icon pack projects to rename the icons as well. This breaks forward compatibility and backward compatibility. Why not just make the source code loads "flameshot.svg/png" and ship the "flameshot.png/svg" as symlink to org.flameshot.Flameshot.png/svg? In this case, we do not require changes from downstream projects. We also do not ship duplicated flameshot images under different names.

**Comment by borgmanJeremy** [comment]
@hosiet thats a great suggestion...I'll do a quick release to fix it .

**Comment by borgmanJeremy** [comment]
Ok will get a release with #1051 once we agree it actually works....My expertise is in c++, but I have learned more about linux packaging than I ever wanted to :)
