### ISSUE TITLE
Flameshot v0.8.4 not working on Fedora 32

### ISSUE THREAD

**Issue by merrcury** [flameshot-org/flameshot#1052]
**Flameshot version**
0.8.4

**Describe the bug**
Flameshot is not starting up and leaving behind `QSocketNotifier: Can only be used with threads started with QThread`

**To Reproduce**
Simply Start Flameshot through Activities or bash. 

**Expected behavior**
It should start and appear in the notification tray. 

**System Information**
Fedora 32(Workstation Edition)

**Comment by borgmanJeremy** [comment]
If you start it through bash, does it crash, or just sit and wait after showing that warning?

**Comment by borgmanJeremy** [comment]
I tested this in a VM and it works okay. Make sure you have sys tray configured: https://github.com/flameshot-org/flameshot#tray-icon

**Comment by merrcury** [comment]
+ As soon as I start it through bash it throws `QSocketNotifier: Can only be used with threads started with QThread`
+ My system tray is configured as you can see the slack icon is up there. 


See the below screenshot proving both points. 
![Screenshot from 2020-10-12 23-58-33](https://user-images.githubusercontent.com/35988194/95779066-fc4f5100-0ce6-11eb-80a2-0f3c0b2301d8.png)

**Comment by borgmanJeremy** [comment]
This is probably a duplicate of #646 can you try running the application under xwayland?

**Comment by merrcury** [comment]
Ya, It seems to work with X11. I am closing this.

**Comment by hosiet** [comment]
@borgmanJeremy I am not sure whether we should keep an issue open that flameshot does not work under pure Wayland. After all, we claim that flameshot has experimental GNOME + Wayland support but that is not the case.

**Comment by borgmanJeremy** [comment]
@hosiet lets track it on #646...some preliminary googling makes this seems easy to solve. https://forum.qt.io/topic/29587/solved-qsocketnotifier-can-only-be-used-with-threads-started-with-qthread/8

I can pause working on plugins and look at this.

**Comment by borgmanJeremy** [comment]
@hosiet / @merrcury I think this is just an icon issue at its root. I did a clean VM install of fedora 33 and fedora32, fedora33 at least runs wayland by default. I *do* get the QThread warning but the program also works okay for me as long as I install the proper gnome extensions: 
![image](https://user-images.githubusercontent.com/46930769/95794855-816a4400-0cae-11eb-88db-edfc07fd09bb.png)
