### ISSUE TITLE
Flameshot configuration not opening anything

### ISSUE THREAD

**Issue by zahirimob** [flameshot-org/flameshot#1053]
**Flameshot version**

**Describe the bug**

when open flamshot it sticky on topbar then try to click on configuration it does nothing.

**To Reproduce**

**Expected behavior**

It should be open configuration setting popup box.

**System Information**

ubuntu 20.4

**Comment by borgmanJeremy** [comment]
Was this installed via apt or snap?

**Comment by zahirimob** [comment]
> Was this installed via apt or snap?

it was installed using apt

**Comment by borgmanJeremy** [comment]
Can you try the snap install on Ubuntu?

**Comment by zahirimob** [comment]
> Can you try the snap install on Ubuntu?

tried with snap store but no luck same issue again

**Comment by borgmanJeremy** [comment]
Have you made any changes to your desktop environment? It works for me on a fresh install in a VM: 
![image](https://user-images.githubusercontent.com/46930769/95758999-c2daff00-0c6e-11eb-9685-92fef666dc44.png)

**Comment by zahirimob** [comment]
No i didn't made any change in desktop it was updated from 18.04 to 20.04 recently and setting is untouched.

**Comment by mmahmoudian** [comment]
@borgmanJeremy can it be DBUS issue again?

@zahirimob can you use the following in a terminal and report back
```
( flameshot &; ) && ( sleep 0.5s && flameshot gui )
```

**Comment by zahirimob** [comment]
> ( flameshot &; ) && ( sleep 0.5s && flameshot gui )
Here i think `;` was giving error.so removed and here is the output
![image](https://user-images.githubusercontent.com/68015220/95769785-09177900-0cd6-11eb-80f0-c515847bde47.png)

**Comment by borgmanJeremy** [comment]
ahhh this is the locale issue. https://github.com/flameshot-org/flameshot/issues/805

Can you make sure your locales are set?

**Comment by zahirimob** [comment]
Here is locale resulte how do i set it?
![image](https://user-images.githubusercontent.com/68015220/95770245-bdb19a80-0cd6-11eb-8eaa-6af27bdddea9.png)

**Comment by borgmanJeremy** [comment]
This seems similar...be sure to change from en_US.UTF-8 to the locale you want.

https://forum.sinusbot.com/kb/i-get-an-error-like-what-locale-facet-_s_create_c_locale-name-not-valid-what-do-i-do.23

**Comment by mmahmoudian** [comment]
Also this might give you a better understanding on how the locale should be set in general:
https://stackoverflow.com/a/43953994/1613005

**Comment by zahirimob** [comment]
Great thanks for constant helping.

Have just run below command and it's working fine now.
`Code:
$ apt-get install locales
$ locale-gen en_US.UTF-8
$ update-locale LANG=en_US.UTF-8
$ reboot`

**Comment by borgmanJeremy** [comment]
Running that exact command will change your locale from i
