### ISSUE TITLE
Windows Keyboard Shortcut

### ISSUE THREAD

**Issue by VijayStroup** [flameshot-org/flameshot#1054]
So under Linux, it's all great to just make keyboard shortcut to run the terminal command to take a screen shot, however on Windows, the application launches a tray icon that you have to press to take a screen shot.  On Windows, we can make keyboard shortcuts on applications like this:

![Image of shortcut](https://i.imgur.com/43GwouH.png)

I couldn't find the tray icon executable to map to a keyboard shortcut so I've been resorting to having to click the tray icon and then click on the Flameshot icon.

**Comment by borgmanJeremy** [comment]
On windows if I am running flameshot in the tray, pressing printscreen automatically starts a capture.
