### ISSUE TITLE
Number Button is missing.

### ISSUE THREAD

**Issue by tomtok9** [flameshot-org/flameshot#1056]
**Flameshot version**
Flameshot 0.6.0+git2019001-2(Debian)

**Describe the bug**
The Button to add numbers in the screenshot is not available or is missing.
![image](https://user-images.githubusercontent.com/2410695/95837228-a9a28300-0d40-11eb-9d6c-1330250268c0.png)
It is also not available in the settings menu.
![image](https://user-images.githubusercontent.com/2410695/95837714-33525080-0d41-11eb-85b9-2a46e24ebe33.png)

**To Reproduce**
Install the Version available in Ubuntu 20.04 Software Store

**Expected behavior**
This button should be available.

**System Information**
Xubuntu 20.04

**Comment by ZetaoYang** [comment]
That 'Countertool' feature comes from 0.8.0 Countertool  https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0
