### ISSUE TITLE
unable to set shortcut in KDE DE

### ISSUE THREAD

**Issue by ikelvinwoo** [flameshot-org/flameshot#1060]
since i updated to the lastest version, i am not able to set global shortcut under KDE DE.
![2020-10-14_10-19](https://user-images.githubusercontent.com/32406016/95935840-c608f300-0e06-11eb-9d18-a5560496ab45.png)

you can see as there is not option to set screenshot shortcut for flameshot.

please advise?

**Comment by borgmanJeremy** [comment]
@ikelvinwoo Can you try this from the README: https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop

**Comment by ikelvinwoo** [comment]
> @ikelvinwoo Can you try this from the README: https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop

Yes I definitely did. But on step 3
> Go to System Settings → Shortcuts → Custom Shortcuts.
and step 5
> Click Edit → Import..., navigate to the Desktop folder (or wherever you saved the configuration file) and open the configuration file.

there is no way to import following theses steps.

could you please advice?

**Comment by mmahmoudian** [comment]
@ikelvinwoo Does these help?

![image](https://user-images.githubusercontent.com/390889/96006108-cecce980-0e45-11eb-99d2-cd804abae62f.png)

![image](https://user-images.githubusercontent.com/390889/96006333-0b004a00-0e46-11eb-9c36-7a5a4ab5da7e.png)

**Comment by ikelvinwoo** [comment]
> @ikelvinwoo Does these help?
> 
> ![image](https://user-images.githubusercontent.com/390889/96006108-cecce980-0e45-11eb-99d2-cd804abae62f.png)
> 
> ![image](https://user-images.githubusercontent.com/390889/96006333-0b004a00-0e46-11eb-9c36-7a5a4ab5da7e.png)

Thank you very much for your help. This is very clear.

I think I did not install some packages, since i do not have global/standard/custom shortcut options.

![2020-10-15_09-14](https://user-images.githubusercontent.com/32406016/96061943-02038d00-0ec7-11eb-9ffd-689fdd3a3560.png)

**Comment by ikelvinwoo** [comment]
> @ikelvinwoo Does these help?
> 
> ![image](https://user-images.githubusercontent.com/390889/96006108-cecce980-0e45-11eb-99d2-cd804abae62f.png)
> 
> ![image](https://user-images.githubusercontent.com/390889/96006333-0b004a00-0e46-11eb-9c36-7a5a4ab5da7e.png)

I found solutions, I did not have khotkeys packages installed. I tried to install the package and got the problem solved. Thank you very much!!!

**Comment by mmahmoudian** [comment]
@ikelvinwoo would you please post here the package (s) you installed so that others can use this thread as a guide.
