### ISSUE TITLE
Flameshot snap fails to run

### ISSUE THREAD

**Issue by alculete** [flameshot-org/flameshot#1067]
**Flameshot version**
v0.8.4+git0.81c68c0

**Describe the bug**
Flameshot snap failing with `Qt: Session management error: None of the authentication protocols specified are supported`

**To Reproduce**
snap run flameshot

**Expected behavior**
open flameshot

**System Information**
ubuntu 20.04

**Comment by borgmanJeremy** [comment]
Can you double check that you have the proper sys tray support: https://github.com/flameshot-org/flameshot#tray-icon

That qt warning is likely irrelevant.

**Comment by borgmanJeremy** [comment]
Closing for lack of info / follow up.
