### ISSUE TITLE
Windows CI has deprecations warning

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1069]
The windows CI is showing this warning:
```
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by ZetaoYang** [comment]
Github Actions docs:
- [GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
- [Environment Files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
