### ISSUE TITLE
Automatic resize of taken screenshot (also when in clipboard?)

### ISSUE THREAD

**Issue by marcxm** [flameshot-org/flameshot#1077]
Would it be possible to add option to - say - auto-resize all taken screenshots (also when they are still in clipboard) to - say - 800xSOMETHING (configurable) pixel size (taken proportion into account)?

Thanks! awesome work.

**Comment by mmahmoudian** [comment]
I personally think this is a very specific use-case amd it is not related to screenshot taking, as it is more of a post-processing step. Of course it can be discussed by the community and added.

I suggest writing a small script and either tell Flameshot to open the taken screenshot through that script/app or have the script running in the background and it checks if the object in the clipboard is an image, it resize it.

Solutions provided [in this Stackoverflow](https://askubuntu.com/a/954580) might come handy to put together a script quickly.

**Comment by borgmanJeremy** [comment]
@marcxm Could you help explain the problem you are trying to solve? I tend to agree with @mmahmoudian but maybe there is a better solution once I understand the actual problem.

**Comment by marcxm** [comment]
I think it might be a meaningful addition to the program.
My workflow is:
1. make a screenshot and do something on it on-the-fly [annotate, use some arrows, rectangle selection to show something to the customer]
2. paste it directly to - say - Google Docs document.

Second step - with HiDPi displays - usually pastes huge screenshot file selection. It would be nice if I could configure Flameshot to always resize / shring all images to given ratio [in my case the expectation from the customers is NOT to exceed 800xSOMETHING size, as for now this is a standard in communication when sharing something as a PDF, etc].

Thank you!

**Comment by borgmanJeremy** [comment]
Ok I think for now we will leave the behavior as is. This can be achieved either with "open with exernal app" or from the cmd line you can use the "raw" option which will pipe the raw image to the terminal. You could pipe this into imagemagick or some other external tool to do the resize.
