### ISSUE TITLE
please make tray icon colorful again

### ISSUE THREAD

**Issue by dextarr** [flameshot-org/flameshot#1078]
Hi,

I recently upgraded kde neon to 20.04 and noticed that the colorful tray icon went away. Is it possible to return it somehow? I would prefer not to look at another boring transparent black-and-white icon, there are already too many there :(
maybe make it customizable which icon appears?

thanks for considering,

dextarr

**Comment by borgmanJeremy** [comment]
Hello,

The flameshot icon is still actually the same colorful icon but we now comply with desktop system themes. This mean if the icon pack you are currently using provides a flameshot icon, we allow it to override our icon. The easiest way to go back to the old icon is to either change your icon pack to on that does not override our icon (or just delete the monochrome icon from your current icon pack). https://askubuntu.com/questions/1210141/how-do-i-remove-the-customized-icon-from-only-one-or-maybe-more-app
