### ISSUE TITLE
Using the Color Picker to Find a Color's Hex Code

### ISSUE THREAD

**Issue by jetrosut** [flameshot-org/flameshot#1079]
**Is your feature request related to a problem?**

I use the app frequently as a color picker. I, for example, see a color I like or I need to use immediately, I capture it with Flameshot but as an extra step I have to upload it to a website like imagecolorpicker to actually get the hex code of the color.

**Comment by borgmanJeremy** [comment]
Hello, Thanks for the idea. The best way to make traction on this issue is to work with us on submitting an RFC. This provides a great way for the dev's to aggregate feedback from the community before spending time working on a new feature.

**Comment by jetrosut** [comment]
@borgmanJeremy RFC apparently stands for Request for Comments but I do not know how to submit one. Can you please help me?

**Comment by borgmanJeremy** [comment]
Sure! 
Here is our document explaining the process: https://github.com/flameshot-org/flameshot/blob/master/docs/RFC.md
Here is a sample RFC: https://github.com/flameshot-org/flameshot/pull/955

The purpose of this is not just to create extra work, but often with new features developers just sit down and spend hours and hours coding a feature only to find it was not exactly what the community wanted. The goal of the RFC process  is to send effort up front on the design to make sure the feature is great when the work starts. 

I'd be happy to help you work on it or answer any questions on on this thread or on our slack. https://flameshotworkspace.slack.com

**Comment by borgmanJeremy** [comment]
This is now merged in thanks to @veracioux
