### ISSUE TITLE
Flameshot freezes after copy a region, willing to fix it

### ISSUE THREAD

**Issue by PinyaColada** [flameshot-org/flameshot#1084]
v0.8.1
Explanation: Flameshot freezes after copy a region and after 2 minuts it closes (but the screenshot has been made)
Reproduce: If you don't have a way to do a notification telling "flameshot info capture saving to clipboard" it freezes
Partial solution: If you download dunst in manjaro it works, but I shouldn't download dunst to make it work, I would be glad to fix this issue, where could I start with?
Linux manjaro

**Comment by borgmanJeremy** [comment]
That said, I am willing to accept a PR that changes DBUS and notifications to a compile time flag Then people on minimal arch installs could recompile without desktop integration.

**Comment by borgmanJeremy** [comment]
Closing this to continue discussion on #90 or #635 (duplicates of this).
