### ISSUE TITLE
Improve the marker for highlighting text

### ISSUE THREAD

**Issue by PrSunflower** [flameshot-org/flameshot#1085]
Hi, I really like Flameshot, thanks to all the developers who have worked on it!

## Suggestion

I use the **marker** to highlight text and it looks very pale, to compensate I often have to highlight multiple times which is annoying. The best highlighter I know is from Windows's **Snip & Sketch** so I did a comparison below:

### Black text on light background

**Flameshot:**
![Flameshot_WHITE](https://user-images.githubusercontent.com/59576952/96623357-8c0a8600-130b-11eb-82e9-05ebbd95a7d9.png)

**Snip & Sketch:**
![Snip_and_Sketch_WHITE](https://user-images.githubusercontent.com/59576952/96623397-9a58a200-130b-11eb-9d27-9a85f4fad504.png)

<br>

### White text on dark background

**Flameshot:**
![Flameshot_BLACK](https://user-images.githubusercontent.com/59576952/96623470-b8260700-130b-11eb-88ff-ff34ea69294c.png)

**Snip & Sketch:**
![Snip_and_Sketch_BLACK](https://user-images.githubusercontent.com/59576952/96623478-bbb98e00-130b-11eb-9e26-59f72cc936a4.png)

<br>

## More details

Flameshot does a good job at keeping the text visible so this is not linked to my request:

![image](https://user-images.githubusercontent.com/59576952/96624043-806b8f00-130c-11eb-9eb3-ce01d19234df.png)

![image](https://user-images.githubusercontent.com/59576952/96624227-bf99e000-130c-11eb-92e7-d9c6087f110c.png)

<br>

My request is to improve the **opacity of the Marker tool** in order to make the highlighting of text more visible.

**Comment by mmahmoudian** [comment]
Perhaps we can add a slider in the Tool Settings so that users can adjust the opacity from that menu.

**Comment by PrSunflower** [comment]
@mmahmoudian That would be really nice!

**Comment by borgmanJeremy** [comment]
Also a duplicate of #249. If we add it to Tool settings it would likely be global opacity. Is this okay? Maybe we should get RFC feedback so we only need to implement it once.

**Comment by PrSunflower** [comment]
@borgmanJeremy Oh right, I haven't stumbled upon this issue before creating mine.

I agree with the global opacity setting. If I understand well this opacity slider will also influence the pencil, rectangle, circle etc. and I agree with that.

Thanks for replying, now closing this issue.
