### ISSUE TITLE
Imgur uploads broken on master

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1087]
We are aware that imgur uploads are broken on master branch. This portion of the code is being completely reworked and is not stable on master. On any 0.8.x release it is okay.

**Comment by simonbcn** [comment]
It also does not work in versions 0.8.4 and 0.8.5. #1055

**Comment by borgmanJeremy** [comment]
@simonbcn This is referring to a separate issue on master. The issue you are having with 0.8.4 is unrelated to this issue on master.
