### ISSUE TITLE
Document new Hotkey system

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1088]
Add documentation to readme for new hotkey system.

**Comment by DbDibyendu** [comment]
Can I work on this issue?

**Comment by borgmanJeremy** [comment]
@DbDibyendu Absolutely! Thanks for the help. 

The best way to document the feature would be to run the code from the master branch. One really easy way to do this is to download the app image generated by our CI system: https://we.tl/t-DxtNfSZMtm

https://github.com/flameshot-org/flameshot/runs/1295339193?check_suite_focus=true

Then if you click the tray icon and go to configuration you should see the new hotkey system. We just need the README updated to explain how to use the new feature.

**Comment by DbDibyendu** [comment]
I have fixed the issue, can u guide me to a new issue according to my level in this library.

**Comment by borgmanJeremy** [comment]
@DbDibyendu Great Thanks! Perhaps this issue would be good? https://github.com/flameshot-org/flameshot/issues/496
