### ISSUE TITLE
Flameshot problem with save folder

### ISSUE THREAD

**Issue by simonbcn** [flameshot-org/flameshot#1089]
```
Flameshot v0.8.5
Compiled with Qt 5.15.1
Operating System: Arch Linux
KDE Plasma Version: 5.20.1
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Display Server Protocol: Xorg
```
```
$ cat .config/flameshot/flameshot.ini
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x13\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe)
closeAfterScreenshot=true
copyAndCloseAfterUpload=true
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=0
filenamePattern=screenshot_%F_%T
saveAfterCopy=true
saveAfterCopyPath=/tmp
savePath=/tmp
startupLaunch=false

$ locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```

**When I try to save a capture I get: `Error trying to save as Pictures/Screenshots/screenshot_2020-10-22_10-16-54.png`.**

The first thing is that that folder do not exist because my locales are not English and therefore the `Pictures` folder is actually called `Imágenes` (_Spanish_):
```
$ xdg-user-dir PICTURES
/home/juan/Imágenes
```
The second thing is that it also does not respect its own configuration because in it I indicate that the save folder is `/tmp`.

Honestly this was my favorite program to take screenshots but since the last version there are several errors that make it impossible for me to use it. The other is #1055.

**Comment by borgmanJeremy** [comment]
@simon04 I am sorry you are experiencing these issues. One option is to rollback to a version that works for you.

I am actively looking into these issues but have not been able to replicate any of them yet. My next step is to build out an Endeavor VM with es_ES locales and see if that is able to replicate it. 

I just tried this latest issue and I can save to /tmp/tmp fine

**Comment by simonbcn** [comment]
Sorry, this error was caused when importing this file: https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde
