### ISSUE TITLE
Fedora27 does not work

### ISSUE THREAD

**Issue by waltLiZoom** [flameshot-org/flameshot#109]
I have follow your instruction for compilation and 'dnf install' neither of them works.
The command of 'flameshot gui' shows nothing.
What should I do?

**Comment by lupoDharkael** [comment]
Does the program launch? if it does, what happens when you click the tray icon?

**Comment by waltLiZoom** [comment]
No, the progress exits with no hint. The Gnome' version is 3.26.1.

**Comment by kondor6c** [comment]
I believe that Gnome on Fedora defaults to run on Wayland, can you confirm this?

**Comment by lupoDharkael** [comment]
@jlozadad Launch Flameshot just starts the process. I think I should rename it to "Start Process" or something similar. Some people wanted to have that launcher to use it at startup.

@waltLiZoom what's your desktop environment?

**Comment by waltLiZoom** [comment]
@kondor6c @lupoDharkael  yes, Wayland is default session type.

**Comment by waltLiZoom** [comment]
> No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
@lupoDharkael Output info may help you.

**Comment by lupoDharkael** [comment]
@waltLiZoom interesting.
I'll investigate it. Thanks for the information.

**Comment by SavoyRoad** [comment]
I've begun to receive a similar error after upgrading from Debian 9 to 10 (testing). Spoke to the Debian maintainer for the package and they couldn't find a way to reproduce it on their system.

[Bug report in question with system details](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902866)

**Comment by borgmanJeremy** [comment]
Can you please retest this on version 0.8? I think many of these issues will be resolved.

**Comment by CmdrNorthpaw** [comment]
Oh gosh, this is so old. I don't even run Fedora anymore. Flameshot is working great on my Arch Linux install though :)

**Comment by borgmanJeremy** [comment]
No problem. If you have any other issues let me know :)
