### ISSUE TITLE
"Close after capture" close the program before finishing the upload

### ISSUE THREAD

**Issue by simonbcn** [flameshot-org/flameshot#1095]
```
Arch Linux
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

If I activate "_Close after capture_", when I take a screenshot and click on the upload button, the program closes before the end of the upload or at least does not show me the notification or copy the URL to the clipboard.

**Comment by borgmanJeremy** [comment]
This is merged to master and the 0.8.x maintenance branch. I will get a release out soon.

**Comment by simonbcn** [comment]
Does this mean that the program will remain resident in memory forever?

**Comment by borgmanJeremy** [comment]
If you rightclick the tray icon and hit quit, it will close and not reside in memory.
