### ISSUE TITLE
flameshot does not work with Ubuntu20.10

### ISSUE THREAD

**Issue by llywei** [flameshot-org/flameshot#1098]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.12.8

**Describe the bug**
just can not be started

**To Reproduce**
click the flameshot icon
or in terminal type flameshot and click enter

**Expected behavior**
work well with Ubuntu20.10

**System Information**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**Comment by borgmanJeremy** [comment]
Could you please provide more details as to how it does not work?

Are you running the snap?

Does the tray icon appear?

**Comment by lucasvbeek** [comment]
It looks like gnome-shell-extension-appindicator doesn't work with gnome 3.38 properly. The tray icon doesn't appear when running `flameshot`, `flameshot gui` still works though.

**Comment by CCWTech** [comment]
Same issue here.

**Comment by borgmanJeremy** [comment]
As pointed out by @lucasvbeek this should be filed with either gnome or gnome-shell-extension-appindicator

**Comment by llywei** [comment]
> As pointed out by @lucasvbeek this should be filed with either gnome or gnome-shell-extension-appindicator

then there is nothing we can do with this problem?

**Comment by borgmanJeremy** [comment]
No it needs to be addressed by the extension. Someone has already opened an issue. Gnome decided a while back that it's a better design to not have a sys tray shipped with the DE.

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/255

**Comment by borgmanJeremy** [comment]
Or maybe try this extension? https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by lucasvbeek** [comment]
That's the same extension, the installation fails when using Gnome 3.38.

**Comment by borgmanJeremy** [comment]
Ahh sorry on mobile. Yeah just need to help them fix it or wait.

**Comment by lucasvbeek** [comment]
I just got it working with this extension: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

**Comment by ZetaoYang** [comment]
> I just got it working with this extension: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

Its only works with Xorg and XWayland

**Comment by e-m-m-a** [comment]
I can run flameshot by right clicking it but the tray icon does not appear in popos 20.10

**Comment by Bashar** [comment]
i just upgraded my ubuntu from 18.04 to 20.04 and then installed flameshot from ubuntu software and it was not working too with the error `Qt: Session management error: None of the authentication protocols specified are supported` 

I wanted to share the solution I did by running `snap refresh flameshot --edge` which installed `flameshot (edge) v0.8.5+git264.95d8920 from Jeremy Borgman (borgman-jeremy) refreshed` and worked just fine
