### ISSUE TITLE
"Unable to capture screen" on Debian 10 with Gnome

### ISSUE THREAD

**Issue by PrSunflower** [flameshot-org/flameshot#1104]
**Flameshot version**
v0.8.5

**Description**
Hi! I had previously installed Flameshot 0.8.5 on my system and it worked well but I purged many programs to do a cleanup. Since then Flameshot (GUI) opens but when trying to take a screenshot it shows "Flameshot info: Unable to capture screen".

**System Information**
Debian 10 Buster 64-bit with Gnome 3.30.2

Is there a needed dependency that I have purged?

**Additional info**

From the official Debian repositories I installed 0.6.0-11 and it can take screenshots correctly.

**Comment by ZetaoYang** [comment]
@PrSunflower Is your Debian 10 Gnome in Wayland?

**Comment by mmahmoudian** [comment]
@PrSunflower you can find the information @ZetaoYang asked by the instructions the following page:
https://flameshot.js.org/#/data/issue-reporting?id=display-server-protocol

**Comment by borgmanJeremy** [comment]
@mmahmoudian @675 is a different issue. Currently for wayland we only support screenshots through the Gnome and KDE API's. If we want to support Sway we need to investigate what the Sway API looks like for screenshots.

**Comment by PrSunflower** [comment]
Hi! Thanks for replying.

@ZetaoYang Yes my Debian 10 Gnome is on Wayland, I didn't know about it and found out thanks to @mmahmoudian 's instructions.

**Comment by PrSunflower** [comment]
If you are working on a fix I can help you by testing Flameshot on my computer and telling you how it behaves. 😊

**Comment by borgmanJeremy** [comment]
I haven't really looked into this yet since it sounded like it was working until you removed some dependencies. Do you know if it works in a clean install of debian 10? I can test in a VM if you don't have any easy way to test it.

**Comment by PrSunflower** [comment]
Thanks for replying, no I am not planning to re-install or install Debian 10 on a new computer any time soon 😕. If you have the time to test it on a VM that would be cool!

Otherwise I can do it, I may have some spare time this week. Please just tell me what to do when installing Flameshot on the VM.

**Comment by borgmanJeremy** [comment]
Can you try this: https://github.com/flameshot-org/flameshot/issues/675#issuecomment-568874847

It worked for me in a debian10 VM

**Comment by PrSunflower** [comment]
Hi @borgmanJeremy ! Sorry for the delay.

I uninstalled my previous version of Flameshot then installed **v0.8.5**, I added `export QT_QPA_PLATFORM=xcb` to the file `/etc/profile`  but I still get the message "**Flameshot info: Unable to capture screen**".

Did I do something wrong?

**Comment by PrSunflower** [comment]
**_Side note:_** I can't access https://flameshot.js.org/, my browser says `Hmm. We’re having trouble finding that site.`

**Comment by mmahmoudian** [comment]
@PrSunflower we migrated to Flameshot.org as you can see from [the repo of the website](https://github.com/flameshot-org/flameshot-org.github.io)

**Comment by PrSunflower** [comment]
@mmahmoudian Oh right thanks! I asked because I didn't see `https://flameshot.org/` mentionned on https://github.com/flameshot-org/flameshot/

**Comment by borgmanJeremy** [comment]
I'm going to close this since we cannot replicate it in a VM.

**Comment by PrSunflower** [comment]
Hello everyone, little update:

### Recap

Even though the install was correct I couldn't take screenshots with Flameshot v0.8.5 on my Debian 10 computer (GNOME 3.30.2 on Wayland).

### Update

Yesterday I upgraded from Debian 10 'Buster' **_stable_** to Debian 11 'Bullseye' **_unstable ('sid')_**.

The **_unstable_** repos do have the latest version of Flameshot and it works very well 😁:

![temp](https://user-images.githubusercontent.com/59576952/115994096-a7ba5600-a5e6-11eb-8f11-39fee51f9747.png)

<br>

I just checked and I am using X11 now, not Wayland:

```
user@PC:~$ loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
x11
```

And that's all. Although it doesn't solve the issue for Wayland users I still wanted to share this with you.

Cheers everyone!

**Comment by PrSunflower** [comment]
Hello @borgmanJeremy and @mmahmoudian  , hope you are well 🙂

I updated my system as usual and for some reason I am now running Flameshot **on Wayland**.  And well... you guessed it... 😅  I cannot take screenshots anymore 😅😅😅

## Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-3-amd64
debian: unknown

## Installation Type 

I have tried both **Flatpak from Flathub** and package manager **apt for Debian**.

##  Operating System type and version 

Debian GNU/Linux bookworm/sid,  64-bit,  GNOME 41.2


## Description

(As the Flatpak and the Debian versions have the same behaviour, the following description is for both)

- I can see Flameshot's tray icon properly and click on it.
- **Latest uploads**, **Configuration**, **About** and **Quit** work.
- **Take new screenshot** and **Open launcher** don't do anything.

- I have tried [borgmanJeremy's suggestion](https://github.com/flameshot-org/flameshot/issues/1104#issuecomment-736652299) , added a line in `/etc/profile` and rebooted several times but it didn't do anything.

<br>

Do we re-open this issue?

**Comment by PrSunflower** [comment]
@mmahmoudian  I've just seen your post [here](https://github.com/flameshot-org/flameshot/issues/1622#issuecomment-863761206) . What a good summary!

So if it's a Wayland bug/error/lack of something, we can't do anything but wait?

**Comment by mmahmoudian** [comment]
@PrSunflower I don't think I'm the best person to answer your question, but from time to time there **might** be some workaround for some of the issues, but tbh they are usually extra burden on devs as we should implement them and then remove them when Qt or Wayland get improved.

Let's hope this issue is something that we can handle without jumping through weird hoops. 😉
