### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Skyrim-police** [flameshot-org/flameshot#1105]
how can I translate your program into another language?

**Comment by borgmanJeremy** [comment]
Here are the instructions. If you have any questions please let me know: https://github.com/flameshot-org/translation-instruction

**Comment by mmahmoudian** [comment]
@Skyrim-police if your question is resolved by the provided link please let us know to close this issue.

**Comment by Skyrim-police** [comment]
Yes, issue is resolved
