### ISSUE TITLE
how can install this on windows ?

### ISSUE THREAD

**Issue by KumarShrawan** [flameshot-org/flameshot#1113]
Flameshot can be installed on Linux and Microsoft Windows currently.   - But I do not see any executable or an easy procedure to install this on windows

**Comment by fireFerry** [comment]
in releases you can download it for windows.

[32-bit](https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win32.msi)
[64-bit](https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win64.msi)

**Comment by mmahmoudian** [comment]
And for 0.8.5:

![image](https://user-images.githubusercontent.com/390889/97546146-b4157b80-19d4-11eb-8bec-0a9f344bc2d3.png)

**Comment by fireFerry** [comment]
Yep, and working perfect for me on windows, except I can't upload to Imgur, but #1031 is for that.

**Comment by mmahmoudian** [comment]
I close this as it is not an issue and more of a miscommunication.
