### ISSUE TITLE
debian10 设置开机启动无法启动

### ISSUE THREAD

**Issue by gnay321** [flameshot-org/flameshot#1117]
debian10 设置开机启动无法启动，之后手动启动也无效，需要去掉开机启动重启电脑才正常

**Comment by borgmanJeremy** [comment]
Hello,

I translated this using google translate to:

```
The debian10 setting can’t be started after booting, and then manual booting is also invalid. You need to remove the boot and restart the computer to be normal
```

However, I don't quite follow the problem. Could you please submit this issue in more detail using the issue template?

**Comment by lianghongzhuo** [comment]
The google translation was wrong, I can help translate briefly:
@gnay321 is using debian10 and check the `launch at startup` in the application cannot start the app at launch time.
The rest part (之后手动启动也无效，需要去掉开机启动重启电脑才正常) I cannot understand either.

**Comment by borgmanJeremy** [comment]
@lianghongzhuo  Thanks for translating!!

**Comment by Bekcpear** [comment]
> The google translation was wrong, I can help translate briefly:
> @gnay321 is using debian10 and check the `launch at startup` in the application, but cannot start the app at launch time.
> The rest part (之后手动启动也无效，需要去掉开机启动重启电脑才正常) I cannot understand either. Need more information from @gnay321

"The rest part" means, he can't start flameshot manually when `launch at startup` checked unless uncheck this setting and reboot the computer.

**Comment by lianghongzhuo** [comment]
@Bekcpear I can literally understand it, what I can't understand is, if he cannot launch flamshot, how he uncheck the setting. :)
