### ISSUE TITLE
Shortcut option for Win10?

### ISSUE THREAD

**Issue by lxwulf** [flameshot-org/flameshot#1118]
**Is your feature request related to a problem?**
→ NO

I can't set up a shortcut on Windows or I don't know how. Maybe someone can help.

Greets

LxWulf

**Comment by mmahmoudian** [comment]
I'm not a Windows user, but the following is the first link in Google and the content seems to be correct:
https://www.laptopmag.com/articles/create-keyboard-shortcuts-windows-10

**Comment by fireFerry** [comment]
It's also bindend to `PrtScr` by default.

**Comment by mmahmoudian** [comment]
@lxwulf can you double check if the <kbd>PrntScr</kbd> does work by default as @fireFerry suggested?

**Comment by lxwulf** [comment]
Thank you @mmahmoudian I would try out this

@fireFerry @mmahmoudian sadly it doesn't work...

**Comment by fireFerry** [comment]
Do you have any other programs using the `PrtScr` button? Lightshot, OneDrive, etc. then they could be using it

**Comment by lxwulf** [comment]
No I have no other program so far I know but I would check it again. On my home PC it works with print screen as intended but I have a new "bug" which appears when you have a monitor vertical it shows a gray layout as would the screen be landscape.

**Comment by mmahmoudian** [comment]
@lxwulf Please report the newly observed bug in a new issue and also please add a picture as I didn't quite understand what exactly is the issue.

Regarding this current issue though, it is clear that <kbd>PrntScr</kbd> is mapped to another software. Did you manage to try the methods mentioned in the link I suggested?

**Comment by lxwulf** [comment]
Yes I will do it and sorry for my bad English 👉👈

Not yet, but I found out what the problem was - ShareX was installed and I didn't know that with `PrntScr` it works fine now.

**Comment by mmahmoudian** [comment]
@lxwulf Don't worry about the language, majority of the world are not native English including myself. Your text was clear enough that we could point you to to the right direction 👍

About another key binding for Flameshot, you can definitely use the first method mentioned in the link I suggested. setting it up would take less than 2 minutes.

**Comment by arnovdk** [comment]
Sorry for being late to the party, but I may have something helpful to add. In my case, the PrtScr key didn't work as expected either, though I hadn't installed any other 3rd party tools with which to take screenshots. As it turned out, in my case Windows 10 had configured the new Screen Snipping tool to respond to a press of the PrtScr key:
![image](https://user-images.githubusercontent.com/11163755/177133476-f9aa7e18-fb18-4b84-9fcb-7bbfeeca8103.png)

After turning this setting off and restarting Flameshot, everything was working as expected. Mind you, this was a fresly installed Windows 10 21H2, so it seems that by default this might become a problem for new Flameshot users...

**Comment by koppor** [comment]
Note that flameshot displays "Print Screen" in gray and one cannot modify it

![image](https://github.com/flameshot-org/flameshot/assets/1366654/2085c6b4-fa5b-4b84-b7ee-ed1ea44eac4e)

**Comment by koppor** [comment]
> As it turned out, in my case Windows 10 had configured the new Screen Snipping tool to respond to a press of the PrtScr key:

This setting is hidden in the "Ease of Access" settings. Section "Interaction": "Keyboard".

1. Press <kbd>Win</kbd>+<kbd>I</kbd>
2. Search for "Ease of Access"
3. Select "Ease of Access keyboard settings"
4. Scroll down to "Print Screen shortcut"
5. Disable ("off")

**Comment by RazSofer** [comment]
> Note that flameshot displays "Print Screen" in gray and one cannot modify it
> 
> ![image](https://private-user-images.githubusercontent.com/1366654/291602521-2085c6b4-fa5b-4b84-b7ee-ed1ea44eac4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTA0NDgsIm5iZiI6MTcxOTYxMDE0OCwicGF0aCI6Ii8xMzY2NjU0LzI5MTYwMjUyMS0yMDg1YzZiNC1mYTViLTRiODQtYjdlZS1lZDFlYTQ0ZWFjNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMjEyOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg5ODRlZDFiZDY2OWEzZjc4NTY2YmNhMjZhYTA0ZGFhZjE0YTY1NmU3NDAwOGYzZTJkYTE0MGE3YzZhZDMyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I6reTGF_35rw-A-rm1iIfKh5TlU-97sUYj_gTqgu21A)

Any solution for this, or is it just not supported?
