### ISSUE TITLE
0.8.4 Windows version works OK but in dual-monitors setup the overlay is off

### ISSUE THREAD

**Issue by darkguy2008** [flameshot-org/flameshot#1123]
**Flameshot version**

0.8.4-win64 ZIP release

**Describe the bug**

All features work but the overlay is off and the app only works when you click inside the overlay. The upper part of my display is displayed in the Y=0 part of the overlay, so I cannot do anything on the lower part of the screen.

![image](https://user-images.githubusercontent.com/6304136/97735813-72520700-1aa0-11eb-86f3-c4cd5908c4ff.png)

**To Reproduce**

Have two monitors with different Y coordinates. Hit print-screen.
![image](https://user-images.githubusercontent.com/6304136/97735503-08d1f880-1aa0-11eb-9461-aee4ae960dd2.png)

This is one issue, depending on how far the Y coordinate of the left display is off against the right display, there will be a black region shown on the left display. THEN, it seems that Flameshot takes the size of the smallest monitor. Since I have 1440x900 and 1920x1080, I'm missing 180 vertical pixels, always from the top of the screen.

**Expected behavior**

Both monitors should be overlayed

**System Information**

Windwos 10 LTSC
Microsoft Windows [Version 10.0.17763.316]

**Comment by borgmanJeremy** [comment]
Actually check out the binaries from #1126 

Looks like someone had a PR while the project was stale. I fixed the merge conflicts and pushed the PR. If it works for you I will get it merged.

**Comment by darkguy2008** [comment]
> Actually check out the binaries from #1126
> 
> Looks like someone had a PR while the project was stale. I fixed the merge conflicts and pushed the PR. If it works for you I will get it merged.

Hey, thanks for the quick reply! This is amazing, **it works perfectly!!**, it definitely can be merged. I tried the ZIP version for x64, works awesome!

Thanks!!

**Comment by borgmanJeremy** [comment]
Great to hear :) I will get it merged. Our master branch is fairly unstable but we are due for a 0.8.x maintenance release. I will make sure to backport this fix.
