### ISSUE TITLE
Dual monitors not displayed properly.

### ISSUE THREAD

**Issue by uBadRequest** [flameshot-org/flameshot#1124]
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.1
Installed via Flatpak
![image](https://user-images.githubusercontent.com/47282747/97757711-a7c41800-1ad3-11eb-96d4-6ed764165ab5.png)

**Describe the bug**

Taking a screenshot with 2 monitors does not display monitors properly. This is the view of just my main monitor, its cutting off half of the screen.
![image](https://user-images.githubusercontent.com/47282747/97757019-4ea7b480-1ad2-11eb-9c58-af293fe55b9b.png)

**To Reproduce**

Installed Flameshot via Flatpak. Installed Nvidia driver. Attempt capture rectangular region and experienced issue.

**Expected behavior**

Self explanatory.
 
**System Information**

I'm on Clear Linux.
![image](https://user-images.githubusercontent.com/47282747/97757374-f8874100-1ad2-11eb-991a-bf13e80880d3.png)

**Comment by borgmanJeremy** [comment]
Doe you have fractional scaling enabled?

**Comment by uBadRequest** [comment]
> fractional scaling

You know I actually thought it might have had something to do with the scale, but its set to 150%.
![image](https://user-images.githubusercontent.com/47282747/97765510-bc5edb00-1ae8-11eb-89e5-b17397e23857.png)

**Comment by borgmanJeremy** [comment]
Yup, I suspect you are on X11. With X11 scaling we have an issue. Tracking it here: #748 and #564  I started actively working on it this week.

Will close this as a duplicate but feel free to chime in on those issues.
