### ISSUE TITLE
Cannot save captures or configure flameshot without sudo

### ISSUE THREAD

**Issue by ayushbindlish** [flameshot-org/flameshot#1138]
**Flameshot version**
0.8.5-1

**Describe the bug**
After I launch flameshot as a normal user, I am not able to save the captures or configure flameshot. I tried both the ways, from cli as well as from the toolbar widget drop down menu. Whereas I can take screenshots and copy and paste them.

Both of the options work once I use it with sudo.  

**To Reproduce**
$flameshot config
Does not open anything

$sudo flameshot config 
Opens a configuration box

**Expected behavior**
After taking the screenshot and pressing the save button a dialog box should open to specify the path where the file should be saved. 
From the toolbar widget dropdown menu I should be able to click on config and a configuration box should open.  

**System Information**
5.8.0-kali3-amd64 #1 SMP Debian 5.8.14-1kali1 (2020-10-13) x86_64 GNU/Linux

**Strace output with sudo and without sudo**

[straceWithoutSudo.txt](https://github.com/flameshot-org/flameshot/files/5480165/straceWithoutSudo.txt)
[straceWithSudo.txt](https://github.com/flameshot-org/flameshot/files/5480166/straceWithSudo.txt)

**Comment by kpcee** [comment]
Never start a graphical application with sudo! To fix the problem, if you have installed it via the package manager and no Snap/Flatpak/AppImage, you must repair the file permissions in your $HOME folder and reset the owner of the files from root to your user.

**Comment by ayushbindlish** [comment]
@kpcee I just did that but still the same. Any other thing that I should be looking for?

**Comment by ayushbindlish** [comment]
I also tried installing it using snap and then it gives me a "cannot set locale" warning and does not work using keyboard shortcuts.

**Comment by ayushbindlish** [comment]
### The following Solved it for me!!

As I am using KDE Plasma my LC_TIME is en_IN.UTF-8 which is different from LANG.

_The Following shows you the locales needed:_ 
`cat ~/.config/plasma-localerc `

![image](https://user-images.githubusercontent.com/36608380/98216986-d75d9f00-1f6f-11eb-99c4-58602d9cd51d.png)


Uncomment all the required locales here:
`sudo vim /etc/locale.gen`

And then generate all the locales:
`sudo locale-gen `
