### ISSUE TITLE
Flameshot does not work on plasma 5.20 with wayland.

### ISSUE THREAD

**Issue by cossonleo** [flameshot-org/flameshot#1141]
**Flameshot version**
0.8.5

**Describe the bug**
Flameshot does not work on plasma 5.20 with wayland.

**System Information**
Archlinux/plasma 5.20 wayland

**Comment by borgmanJeremy** [comment]
Can you please describe in more detail what "does not work" means?

**Comment by cossonleo** [comment]
Nothing happened whenever click icon or exec flameshot gui. No error and No capture

**Comment by borgmanJeremy** [comment]
If you start it from the terminal does it print any helpful information?

**Comment by cossonleo** [comment]
Nothing is printed

**Comment by mmahmoudian** [comment]
@cossonleo I would be thankful if you fill the bug report for completely and provide all requested information. This is vital and help us to reproduce the issue and be able to solve the issue fast.

Now, regarding the matter in hand, please follow these steps:
0. open two terminals size-by-side
1. in the first terminal run `flameshot`. This will run the Flameshot in the background
2. in the second terminal, run `flameshot gui`
3. copy the output in the first terminal and paste it in a comment in this Github issue

![image](https://user-images.githubusercontent.com/390889/98360562-b27e3000-2032-11eb-957d-f14966029522.png)

**Comment by cossonleo** [comment]
![Screenshot_20201110_101459](https://user-images.githubusercontent.com/20379044/98619227-c4671800-233d-11eb-8a7b-273c79305994.png)
@mmahmoudian

**Comment by mmahmoudian** [comment]
@borgmanJeremy & @ZetaoYang do you have any idea about this?

**Comment by ZetaoYang** [comment]
This bug can be circumvented by using the xcb backend instead of the wayland backend.
```
QT_QPA_PLATFORM=xcb flameshot
```
