### ISSUE TITLE
Spam in syslog releated to QPainter

### ISSUE THREAD

**Issue by staticssleever668** [flameshot-org/flameshot#1145]
**Flameshot version**
From main repository: 
```
Flameshot v0.8.5
Compiled with Qt 5.15.1
```
From AUR:
```
r1009.eef2b75
```

**Describe the bug**
When you launch `flameshot gui` spam in syslog appears:
```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

**To Reproduce**
Launch `flameshot gui`, press \<Escape\>, then go the bottom of `journalctl -b -p 4` output (only works in distributions using systemd as init system)

**Expected behavior**
Do not make these warnings

**System Information**
Distribution: `Arch Linux`

**Comment by borgmanJeremy** [comment]
We are not making these warnings, Qt is making them. I think fixing them will be significant effort for little reward so unless someone else helps I don't think they will get fixed soon.

**Comment by ZetaoYang** [comment]
There is a way to use `QT_LOGGING_RULES="*.warning=false" flameshot`. This will hide all warnings however, including the useful ones.`

### reference
- https://zren.github.io/2020/06/19/qml-connections-onfoo-warnings-will-get-logging-category-in-qt-5151

**Comment by borgmanJeremy** [comment]
I am going to close this since as @ZetaoYang points out you can start flameshot in a way that will hide the warnings.
