### ISSUE TITLE
add path to preferred application to "OPEN WITH" option

### ISSUE THREAD

**Issue by pleabargain** [flameshot-org/flameshot#1147]
I use FS nearly every day. Thank you! 

I would like to add an application to the OPEN WITH option. Specifically, I would like to add an OCR tool like Tesseract as a target app for the screenshot.

I tried adding the app path e.g.
/var/snap/tesseract
but no joy.

see attached gif

How do I modify the list of available applications that FS uses/sees?

thank you,
Dennis

![flames Peek 2020-11-09 11-26](https://user-images.githubusercontent.com/640846/98523536-b4d4ca00-227e-11eb-82ad-c5e915bcd571.gif)

**Comment by borgmanJeremy** [comment]
I believe the application must install a .desktop file to be found.

**Comment by mmahmoudian** [comment]
@pleabargain Create a `.desktop` file in one of the following paths:
* if you want it system-wide: `/usr/share/applications`
* if you want it for your user only: `~/.local/share/applications`

For the content of the file, you can check other files in those folders. I can also suggest you to read the Arch wiki:
https://wiki.archlinux.org/index.php/desktop_entries

**Comment by pleabargain** [comment]
Here is my desktop file:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Tesseract
GenericName=OCR
X-GNOME-FullName=Tesseract
Exec=/usr/bin/tesseract %F
Categories=Graphics;2DGraphics;RasterGraphics;GTK;
Icon=/home/dgd/Pictures/ocr1.png
Terminal=false

```

However, FS is not seeing the tesseract.desktop option. I've copied an existing desktop file that FS does see but it doesn't see the tesseract desktop. I've stopped and restarted FS but still no joy.

Any help is appreciated.

**Comment by mmahmoudian** [comment]
Try changing the `Exec` to the following:

```
Exec=bash -c "/usr/bin/tesseract %F"
```

Also double check that the tesseract exists in the path you provided.

**Comment by pleabargain** [comment]
Here is the full .desktop file
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Tesseract
GenericName=OCR
X-GNOME-FullName=Tesseract
#Exec=/usr/bin/tesseract %F
#tesseract expects an output file but using '>' didn't work as I had hoped
#Exec=bash -c "/usr/bin/tesseract %F" > /home/dgd/Desktop/texttest.txt
#this didn't work :(
Exec=bash -c "/usr/bin/tesseract %F" 
Categories=Graphics;2DGraphics;RasterGraphics;GTK;

Icon=/home/dgd/Pictures/ocr1.png
Terminal=false

```

I tested your suggested changes but didn't get any new behavior.

here is the video
https://youtu.be/xGfc21-DVjQ

I will happily share a write up on how to get tesseract working with FS is you can help! 

thank you
Dennis

**Comment by mmahmoudian** [comment]
Well, I've never used Tesseract (looks like an easy-to-use tool).
 This is what the man file says:

```
TESSERACT(1)                                                      TESSERACT(1)

NAME
       tesseract - command-line OCR engine

SYNOPSIS
       tesseract FILE OUTPUTBASE [OPTIONS]... [CONFIGFILE]...

DESCRIPTION
       tesseract(1) is a commercial quality OCR engine originally developed at
       HP between 1985 and 1995. In 1995, this engine was among the top 3
       evaluated by UNLV. It was open-sourced by HP and UNLV in 2005, and has
       been developed at Google since then.
```

I concluded that the first argument is expected to be the image file and the second argument is expected to be the output file. So here is what I wrote:

```
[Desktop Entry]
Encoding=UTF-8
Name=Tesseract OCR
Comment=OCR tool
Exec=bash -c "tesseract %F ${HOME}/Downloads/tesseract_output"
Type=Application
Terminal=true
Categories=Graphics
```

and it simply works 😉 and put the output to `~/Downloads/tesseract_output.txt`.

**Comment by pleabargain** [comment]
Thank you very much!

It works! 

:+1:

**Comment by mmahmoudian** [comment]
@zigpot first do a manual run. Take a photo, store in a file and run the tesseract on that file and see if it works, then try to automate it. Also make sure your softwares are updated.

**Comment by zigpot** [comment]
I actually did and it worked fine. 
1. took a screenshot of a text and saved it as _screen_input.png_
2. run:
`tesseract screen_input.png tess_out`
3. opened _tess_out.txt_ and had the texts.

I tried to make another .desktop file using the [xdg-open](https://linux.die.net/man/1/xdg-open) (a CLI image viewer) shown below:
```
[Desktop Entry]
Encoding=UTF-8
Name=xdg-open cli
Comment=testing purpose
Exec=bash -c "xdg-open %F"
Type=Application
Terminal=true
Categories=Graphics
```
And saved it as `/usr/share/applications/xdg-open.desktop`

The xdg-open cli app appears in the flameshot, but upon clicking, exactly the same reaction as tesseract

**Comment by mmahmoudian** [comment]
@zigpot Well, before anything else, no xdg-open is not an image viewer, it just openes the default application based on the MIME or extension of the file. You might want to use `feh` or `sxiv` for opening pictures although they don't open in terminal. For terminal you should try something like `tiv` (terminal image viewer).

Now, about your issue, although it gets off-topic, try the following:
1. Take a screenshot that contains some text and save it to a file (e.g `/tmp/temp_file.png`)
2. Open a terminal 
3. Run `bash -c "tesseract / tmp/temp_file.png /tmp/tesseract_output"`
4. Do you get any error from step 3?
5. Check if the text file is created `ls -al /tmp/tesseract_output`

**Comment by zigpot** [comment]
That one works fine. the output is `tesseract_output.txt`
