### ISSUE TITLE
tray icon keeps loading indefinetly in snap in ubuntu 20.04

### ISSUE THREAD

**Issue by javierfolcini** [flameshot-org/flameshot#1150]
title says it all, it's just the three dots of when an icon is loading

**Comment by mmahmoudian** [comment]
@javierfolcini Thank you for putting the efforts and reporting this issue, but I'm affraid the title does not completely paint the picture we need to attempt to understand the situation. Please specify the following:
- Flameshot version
- the Desktop Environment you use

**Comment by javierfolcini** [comment]
0.85
ubuntu 20.04 with gnome, fresh install

**Comment by borgmanJeremy** [comment]
Thanks, I have seen this issue as well and have been looking into it on the side. I am not 100% sure if it is a gnome issue or flameshot issue.

The reason is the icon from the snap is clearly found (you can see the proper icon on the gnome activity bar), it only does not display in the sys tray. I also have hardcoded the tray icon to a really simple path in the snap package and the tray still does not pick up the proper icon. 

I will continue investigation.

**Comment by borgmanJeremy** [comment]
I posted for help here: https://forum.snapcraft.io/t/help-with-flameshot-icon/21134

**Comment by borgmanJeremy** [comment]
This issue was fixed for me in PopOS with a clean 20.10 install which makes me think its not a flameshot issue, I'll see if I can figure out what changed.

**Comment by borgmanJeremy** [comment]
@javierfolcini Can you post any gnome extensions you are using and their versions?

**Comment by javierfolcini** [comment]
it got fixed by updating some packages:
Upgrade: whoopsie:amd64 (0.2.69ubuntu0.1, 0.2.69ubuntu0.2), gnome-desktop3-data:amd64 (3.36.3.1-0ubuntu1, 3.36.8-0ubuntu1), libwhoopsie0:amd64 (0.2.69ubuntu0.1, 0.2.69ubuntu0.2), gir1.2-gnomedesktop-3.0:amd64 (3.36.3.1-0ubuntu1, 3.36.8-0ubuntu1), apport:amd64 (2.20.11-0ubuntu27.13, 2.20.11-0ubuntu27.14), libinput-bin:amd64 (1.15.5-1ubuntu0.1, 1.15.5-1ubuntu0.2), libgnome-desktop-3-19:amd64 (3.36.3.1-0ubuntu1, 3.36.8-0ubuntu1), python3-apport:amd64 (2.20.11-0ubuntu27.13, 2.20.11-0ubuntu27.14), gnome-shell-extension-appindicator:amd64 (33-1, 33.1-0ubuntu0.20.04.1), apport-gtk:amd64 (2.20.11-0ubuntu27.13, 2.20.11-0ubuntu27.14), python3-problem-report:amd64 (2.20.11-0ubuntu27.13, 2.20.11-0ubuntu27.14), libinput10:amd64 (1.15.5-1ubuntu0.1, 1.15.5-1ubuntu0.2), libevdev2:amd64 (1.9.0+dfsg-1, 1.9.0+dfsg-1ubuntu0.1)

![imagen](https://user-images.githubusercontent.com/54267441/102189644-40adc780-3eb7-11eb-8ef4-0b5a12f530e2.png)
