### ISSUE TITLE
Keyboard shortcuts not working as expected (arch linux i3wm) 

### ISSUE THREAD

**Issue by pdales** [flameshot-org/flameshot#1151]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
I am launching flameshot selection tool with:
bindsym Print exec flameshot gui -p ~/Pictures

After making my selection I press enter and the selection window closes. But on your github documentation is says "Return" Uploads the selection to imgur. Nothing pops up and no imgur link is copied so I assume that enter is not actually uploaded to imgur. When i click the gui button upload to imgur it makes another popup and correctly uploads to imgur.

My issue is I am taking sensitivte images which i DO NOT want uploaded to imgur. How can I be sure that when I press enter (also saves images to local directory) that I am not uploading to imgur. I was hoping to check this by viewing screenshot history (shift + prinst screen) but this shortcut is also broken (nothing happens).

Also, is there anyway to change the default keyboard shortcuts?

**System Information**
Linux 5.9.3-arch1-1 x86_64
i3wm

**Comment by borgmanJeremy** [comment]
On our master branch we have a new feature that allows custom hot keys. There are some other issues on master that prevent us from releasing a stable release but you can experiment with it. 

The Upload History feature is also only on master (but currently is not working). 

If you go to the 0.8.5 tag on our github page you will find the documentation that matches the version you have installed.
