### ISSUE TITLE
Custom keyboard shortcuts not working after a clean install on Kubuntu 20.04

### ISSUE THREAD

**Issue by hcombee** [flameshot-org/flameshot#1153]
I am running Kubuntu 20.04 and installed the shortcuts file. After pressing the printscreen key nothing happens and this error pops up in .xsession-errors:

D-Bus call: "org.flameshot.Flameshot" : "/" : "graphicCapture" : ("Pictures/Screenshots", "0", "0")
Cannot find '.graphicCapture' in object / at org.flameshot.Flameshot

flameshot -v
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Comment by borgmanJeremy** [comment]
Hello,

Version 0.6.0 is no longer supported, I recommend updating either via our snap package (since you are on ubuntu) or manually downloading a new .deb file.

The reason you are having an issue is because or DBUS org name changed during the flameshot reorganization.

**Comment by hcombee** [comment]
Thank you for the fast response, I installed the latest .deb and it works like a charm again.
