### ISSUE TITLE
Being able to upload with custom comand

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1154]
**Is your feature request related to a problem?**
nope
**What I want**
I want being able to upload my pictures to a custom site instead of imgur,like with this fork (https://github.com/33kk/flameshot).
I don't want to use that fork cause I always want the newest flameshot features and stability.
What I would prefer would be if there would be extra boxes for Website,if it will be uploaded  publicly or private and fpr password of the site.

**Comment by borgmanJeremy** [comment]
We are working on this per #955. The current plan is to support the ShareX plugin format.

I've put this on hold a bit as I try to fix some bugs.

**Comment by Toadfield** [comment]
ok
