### ISSUE TITLE
Colorpicker in the gui after creating a screenshot

### ISSUE THREAD

**Issue by pagdot** [flameshot-org/flameshot#1157]
Would it be possible to add a color picker to the paint-tool after creating the screenshot? It would be nice to change the color on the fly :)

**Comment by mmahmoudian** [comment]
Just to make sure I understand your suggestion correctly, doesn't the right-click and hold solves the issue by showing the color circle?

**Comment by pagdot** [comment]
Somehow didn't see this feature :facepalm:

**Comment by mmahmoudian** [comment]
@pagdot we are working one a welcome screen to showcase some of these features. It would be nice if you can watch the following GIF and let me know if there is anything that you don't know how to do:

![](https://flameshot.org/media/animatedUsage.gif)


Few things that are not presented in the GIF:
1. press spacebar to see the configuration sidebar
2. mouse scroll to change the size (even while you are typing or drawing)

**Comment by pagdot** [comment]
Maybe show a icon/icon animation for mouse right click, space bar and similar features so it is clear how you do it. Else the gif gives a good overview. Very nice :)
e.g. 
![](http://clipart-library.com/img/1774476.png)

or a animation with a flashing right mouse button

**Comment by pvonmoradi** [comment]
@mmahmoudian Can that color pallet be customized in any way? Usually black or white is used for blocking info but none if present in that group of 9 colors.

**Comment by mmahmoudian** [comment]
@pvonmoradi That had been already asked/discussed (e.g #1202) and you will find a way to add your custom colors [here](https://github.com/flameshot-org/flameshot/issues/1202#issuecomment-754166292)

As Jeremy said in that post, any PR is most welcome especially for the documentation as devs might not fully realize what is missing from documentations 😉
