### ISSUE TITLE
KDE D-bus namespace is different (at least for me)

### ISSUE THREAD

**Issue by neoscopio** [flameshot-org/flameshot#1159]
Recently after updating my flameshot shortcuts stop working on KDE (Kubuntu), Plasma version 5.18.5

Found out that my d-bus for flameshot was : 
**org.dharkael.Flameshot**
and not
org.flameshot.Flameshot

After editing the "remote application" on the shortcut action section, it started working again.

**Comment by borgmanJeremy** [comment]
I suspect your distro is packaging an old version of flameshot.

**Comment by Dantenerosas** [comment]
Seems like issue with KDE Neon. At the very least just encountered it using Neon and it seems like packaged version is 0.6. I've just installed .deb from repo to solve it

**Comment by borgmanJeremy** [comment]
Yup, the name changed in the .8 series as we reorganized.
