### ISSUE TITLE
text can't move

### ISSUE THREAD

**Issue by aohanhongzhi** [flameshot-org/flameshot#1161]
text can't move 文字不能移动。

![image](https://user-images.githubusercontent.com/37319319/99880946-980e9e00-2c51-11eb-9da3-61f34cb8997e.png)

**Comment by borgmanJeremy** [comment]
Correct, currently we do not support moving any drawings after they are drawn. We have a seperate feature request to add this in the future.

**Comment by Kiridmit** [comment]
this is a very useful feature

**Comment by mmahmoudian** [comment]
@Kiridmit This is already implemented. Make sure you have installed the latest version.
