### ISSUE TITLE
Flamshot doesn't capture fullscreen properly

### ISSUE THREAD

**Issue by alkaris2** [flameshot-org/flameshot#1164]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
When trying to take a screenshot of my entire desktop screens, flameshot doesn't properly take a screenshot and instead creates a blank grey image the size of my entire screen.

![2020-11-22_14-20](https://user-images.githubusercontent.com/73155407/99893297-33ddef80-2cce-11eb-98a1-f1f491c62c85.png)

Also typing for help information for flameshot also produces errors about QString and missing arguments. Stuff that shouldn't be appearing in the help menu when you want to call `-h, --help` with the command to see their options and stuff.

![image](https://user-images.githubusercontent.com/73155407/99893326-83242000-2cce-11eb-8c3d-2d00ae946be8.png)

**To Reproduce**
Take fullscreen screenshot with hotkey; ie <kbd>Print</kbd> or just doing it from terminal with;

```
$ flameshot screen -p /path/to/directory
```

**Expected behavior**
Take screenshot of screens

**System Information**
Manjaro Linux

**Comment by mmahmoudian** [comment]
@alkaris2 You didn't provide the minimum information of your system that we asked. please completely report your system's information so that we can investigate this further. you can use the guides in following page:
https://flameshot.org/issue-reporting/

At least the following info are necessary imho:
- Display Server Protocol
- Monitor(s) information
- Desktop Environment

**Comment by mmahmoudian** [comment]
Closed after 1 months of inactivity. Please open this if you still have the issue and provide the requested information.

**Comment by tsundokul** [comment]
I'm having the same issue
```bash
🔥 flameshot --version
Flameshot v0.8.5-2(Debian)
Compiled with Qt 5.15.2
🔥 inxi --width 80 --system --graphics
System:
  Host: kali Kernel: 5.10.0-kali3-amd64 x86_64 bits: 64 Desktop: bspwm 0.9.10 
  Distro: Kali GNU/Linux 2021.1 
Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel 
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo 
  Display: x11 server: X.Org 1.20.10 driver: loaded: intel 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.3.4 
🔥 loginctl show-session 4 -p Type --value
x11
🔥 xrandr | grep -v ' disconnected '
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.06*+  59.93  
   1680x1050     59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.81    59.91  
   1152x864      60.00  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
🔥 lspci | grep -i 'vga\|3d\|2d'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
🔥 lshw -class display
  *-display
       description: VGA compatible controller
       product: HD Graphics 5500
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:47 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:3000(size=64) memory:c0000-dffff
🔥 uname -a
Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux

```

**Comment by mmahmoudian** [comment]
@tsundokul how have you installed Flameshot? Would be possible to try the AppImage from the 0.8.5 and then RC2 and let us know if the issue happens in both of them or not?

**Comment by tsundokul** [comment]
Hi, I can confirm that version 0.9.0 works (installed via Kali's repo)
```
Flameshot v0.9.0
Compiled with Qt 5.15.2
```
thanks 😊

**Comment by p-himik** [comment]
I still see the same issue on 0.9.0. Tried all packages that can be run on Ubuntu except for snap because it fails while complaining about missing charmaps.
One peculiarity of my system - I'm using KDE but I'm running Awesome WM in it while having a few KDE services disabled. But I'm not sure whether it could possibly interfere with screenshot taking functionality in any way.
```bash
$ flameshot --version  
Flameshot v0.9.0
Compiled with Qt 5.11.3

$ lsb_release -a                 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ inxi --width 80 --system --graphics
System:
  Host: p-himik-pc Kernel: 5.4.0-77-generic x86_64 bits: 64 
  Desktop: KDE Plasma 5.18.5 Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2070 SUPER] driver: nvidia v: 460.80 
  Display: x11 server: X.Org 1.20.9 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 2560x1440~144Hz 
  OpenGL: renderer: GeForce RTX 2070 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA 460.80

$ loginctl show-session 3 -p Type --value
x11

$ xrandr | grep -v ' disconnected '
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 697mm x 392mm
   2560x1440    144.00*+ 120.00    99.95    59.95  
   [...]

**Comment by mmahmoudian** [comment]
@p-himik flameshot should always be running in the background for the Flameshot subcommands to work. This is because Flameshot uses dbus.

The AwesomeWM+KDE should not make any difference as I myself am using that exact combination. But you might want to read the trouble shooting in this page:

https://wiki.archlinux.org/title/Flameshot#Option_1:_Use_dbus-launch

**Comment by p-himik** [comment]
Thanks!
The thing is, when I was experimenting with some earlier version (0.8?), flameshot would start automatically with `flameshot screen -c` command. But it's been some time, so I might be misremembering things.
