### ISSUE TITLE
Flameshot Windows shortcut

### ISSUE THREAD

**Issue by CDFN** [flameshot-org/flameshot#1168]
Hey,
I just moved from Ubuntu where I got very used to Flameshot. Is it possible to set shortcut for screenshoting? In Ubuntu it was just binding shorctut to `flameshot gui` command using desktop environment, but in Windows I have no idea how to do that. Are there any other ways?  
Thanks for making great software!

**Comment by borgmanJeremy** [comment]
On windows10 I did not need to map printscreen manually, it just worked out of the box provided flameshot was already running in the background.

**Comment by CDFN** [comment]
Thanks for quick response! Unfortunately, it doesn't work out of the box for me ;( I have to click on the tray icon - then screenshot menu pops up.

**Comment by borgmanJeremy** [comment]
Does anything in this thread help you out? https://github.com/flameshot-org/flameshot/issues/1118

Possible Print Screen is bound to something else like greenshot or sharex?

**Comment by CDFN** [comment]
Oh.. I had ShareX installed before, but uninstalled it (didn't reboot since then). After computer restart PrtScr works. Sorry for duplicating the issue, should put more effort into searching! Have a good day and thanks for quick responses.

**Comment by borgmanJeremy** [comment]
No Problem :)
