### ISSUE TITLE
Taking screenshot causes external display to go black  

### ISSUE THREAD

**Issue by aw632** [flameshot-org/flameshot#1169]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Describe the bug**
I set up a hotkey for flameshot and it is working fine on my laptop display. However if I use the same hotkey (or if I use the "Take Screenshot" button in GUI) on my external monitor display, it will for some reason disconnect the monitor and the monitor will go black. 

The display server protocol is X11 

Monitors: 1
 0: +*DP-2 3424/597x1926/336+0+0  DP-2

**System Information**
Ubuntu 20.04

**Comment by borgmanJeremy** [comment]
Can you retest using a new version of flameshot? Since you are on ubuntu I recommend downloading the snap package but you can also manually download the .deb from our release page.

**Comment by aw632** [comment]
Yep, that seems to have worked! Thank you
