### ISSUE TITLE
Flameshot GUI won't launch if right click context menu is open

### ISSUE THREAD

**Issue by avinashrocks1990** [flameshot-org/flameshot#1172]
OS : Manjaro (unstable)
DE : KDE Plasma
Flameshot  v0.8.5
Compiled with QT 5.15.2

I want to report a KDE right click menu bug but i'm not able to launch flameshot to take the screenshot.If the right click menu is not opened flameshot works fine.

**Comment by mmahmoudian** [comment]
You can use peek to record the screen if that helps.

**Comment by avinashrocks1990** [comment]
> You can use peek to record the screen if that helps.

KDE issue i have already reported but other issue that is related to flameshot.
flameshot won't launch if the right click menu is open, i can understand there may be conflict around capture a specific area require mouse action and but fullscreen capture should work.

**Comment by mmahmoudian** [comment]
You are right, I could reproduce it by right-clicking on the desktop wallpaper and then pressing <kbd>prntscrn</kbd>. I'm not sure if this is a bug or intended behaviour, but I personally would like to be able to take a screenshot while the right-click menu is open. @borgmanJeremy @ZetaoYang do you have any ideas id this is intended behaviour?

@avinashrocks1990 There is of course a workaround for this: using delay. Just right-click on the tray icon of Flameshot, select "Open Launcher" and in that, define the delay amount. You can then press "Take new screenshot" and then do the right-clicking and wait for the Flameshot timer to finish.

**Comment by ZetaoYang** [comment]
@mmahmoudian Sorry, I'm not very familiar with the KDE environment. My usual desktop environments are Gnome and i3. But I think this is a bug related to KDE.

**Comment by mmahmoudian** [comment]
@ZetaoYang so this doesn't happen in Gnome?

**Comment by ZetaoYang** [comment]
> @ZetaoYang so this doesn't happen in Gnome?

No, it happens in the gnome environment as well. I just tested a scenario like this as well,
by right-clicking on the desktop, then trigger the screenshot with a custom shortcut key, flameshot won't pop-up the capture widget.

**Comment by borgmanJeremy** [comment]
I dont think this is a flameshot issue because the printscreen hotkey is handled by the DE.

**Comment by ScriptyChris** [comment]
> @avinashrocks1990 There is of course a workaround for this: using delay. Just right-click on the tray icon of Flameshot, select "Open Launcher" and in that, define the delay amount. You can then press "Take new screenshot" and then do the right-clicking and wait for the Flameshot timer to finish.

Just wanted to share that i had similar problem and found even simpler way by using custom shortcut assignment (at least it works in Linux Mint Cinnamon 19.3). Inspired by [this](https://www.cyberciti.biz/faq/what-does-the-sleep-command-do-in-linux/) and [that](https://flameshot.org/advanced/command-line-options/#usage:~:text=open%20GUI%20with%20a%20delay%20of%202%20seconds):

1. Open `Keyboard` app
2. Go to "Shortcuts" tab
3. Choose "Custom Shortcuts"
4. Press "Add custom shortcut"
5. Name it as you want (i took "Flameshot") and type `flameshot gui -d X` inside `Command` field, where `X` is time in ms (for me `500` is ok)
6. Bind the shortcut with preferable key (for me the `Print[Screen]`)

**Comment by JetpackYoshi** [comment]
> > [@avinashrocks1990](https://github.com/avinashrocks1990) There is of course a workaround for this: using delay. Just right-click on the tray icon of Flameshot, select "Open Launcher" and in that, define the delay amount. You can then press "Take new screenshot" and then do the right-clicking and wait for the Flameshot timer to finish.
> 
> Just wanted to share that i had similar problem and found even simpler way by using custom shortcut assignment (at least it works in Linux Mint Cinnamon 19.3). Inspired by [this](https://www.cyberciti.biz/faq/what-does-the-sleep-command-do-in-linux/) and [that](https://flameshot.org/advanced/command-line-options/#usage:~:text=open%20GUI%20with%20a%20delay%20of%202%20seconds):
> 
> 1. Open `Keyboard` app
> 2. Go to "Shortcuts" tab
> 3. Choose "Custom Shortcuts"
> 4. Press "Add custom shortcut"
> 5. Name it as you want (i took "Flameshot") and type `flameshot gui -d X` inside `Command` field, where `X` is time in ms (for me `500` is ok)
> 6. Bind the shortcut with preferable key (for me the `Print[Screen]`)

For all those coming from google, so far this is the easiest work-around I have found. Thanks!
