### ISSUE TITLE
Change Ctrl-C Keyboard Shortcut

### ISSUE THREAD

**Issue by curi0usJack** [flameshot-org/flameshot#1176]
All I want to do is change the Ctrl-C keyboard shortcut to something else as it conflicts with the copy option in my terminal. I'm sure this has already been answered, but I can't seem to find it as it doesn't appear to be an option in the ini file, and I don't see any option to do so from the GUI or Settings.

 I'm using flameshot on Ubuntu 20.04.

Thanks for making a great tool. I use and depend on it heavily for my daily work. Much appreciated!

**Comment by borgmanJeremy** [comment]
Hello,

We have merged custom shortcuts to the master branch, but this is not yet part of a release. It will be part of the 0.9 release once other bug fixes are ready. 

![image](https://user-images.githubusercontent.com/46930769/100636434-56d45900-32f7-11eb-8594-ed38c02c9715.png)
