### ISSUE TITLE
Area selection square not visible

### ISSUE THREAD

**Issue by lanosz** [flameshot-org/flameshot#1178]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
When running flameshot gui, the area selection screen pops up, but when i press down the mouse button and try to select an area, no selection square shows up. By hovering the cursor over the area where its supposed to be and looking at the changing cursor modes I can tell that the area is selected but the selection seems to be invisible. (the cursor turns into the resizing cursor at the edges of the invisible square).

**Expected behavior**
The area selection screen pops up -> I select an area -> The selected area gets indicated by a rectangle and becomes editable.

**System Information**
Artix Linux - Openrc
Cinnamon 4.8.0

**PS**
When I initially installed it three weeks ago it seemed to be a hit or miss, sometimes the selection showed up, sometimes it didnt, not it just completely stopped. 

**PPS**
I tried to record my screen with ffmpeg, because im not sure if i clearly articulated myself and the issue doesnt show up in the footage, which is really weird. The selection shows up completely normal and everything looks like its in order. I tried to record it with 
```bash
ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0+100,200 output.mp4
```

**Comment by borgmanJeremy** [comment]
Out of curiousity has this issue resolved it self on its own? It sounds like an issue with cinnamon or something in your specific setup.

**Comment by melodrom** [comment]
Well no idea actually, I switched distros in the meantime and dont have the issue anymore but well, its a different setup now.
