### ISSUE TITLE
When drawing the initial point is always the last point from the previous draw

### ISSUE THREAD

**Issue by sandygk** [flameshot-org/flameshot#1185]
**Flameshot version**
![image](https://user-images.githubusercontent.com/6596836/102247482-03a0ff80-3ece-11eb-8127-2b39021135c3.png)
![image](https://user-images.githubusercontent.com/6596836/102247916-96da3500-3ece-11eb-8ee4-db35fb42c248.png)

**Describe the bug**
After I select a region from the screen, if I want to draw anything (a rectangle, a circle, etc) the first point is always the bottom right corner, (instead of whenever I clicked) and the last point is whenever I clicked, If I want to continue drawing, the first point is always the last position I clicked instead of whenever I want to start

**Screenshot**
![image](https://user-images.githubusercontent.com/6596836/102248062-bec99880-3ece-11eb-91f9-e7ba7501ea8a.png)

notice in the image how each square was forced to start where the previous one ended

**To Reproduce**
Select a region from the screen and start drawing squares, notice that you don't have control of where to start the drawing (this was working before)

**Expected behavior**
The user should be able to select where the drawing starts and ends

**System Information**
![image](https://user-images.githubusercontent.com/6596836/102247980-a9546e80-3ece-11eb-81a1-af51a731684d.png)

**Comment by mmahmoudian** [comment]
Out of curiosity, does it glitch the same way when you have the tiling mode as floating?

**Comment by sandygk** [comment]
Actually it seems to be resolved now. Not what fixed it, I am on the same version still

**Comment by sandygk** [comment]
Actually it seems to be resolved now. Not what fixed it, I am on the same version still

**Comment by mmahmoudian** [comment]
I'm glad that it was resolved, but not super happy about the miraculous resolution 😉 
Please re-open this if you face this issue and add your full system information.
