### ISSUE TITLE
Upload to Lutim

### ISSUE THREAD

**Issue by locness3** [flameshot-org/flameshot#1190]
[Lutim](https://lut.im/) is an open-source self-hostable image sharing service. Would love to see support for it in Flameshot.

**Comment by itsTyrion** [comment]
IMO we should not add one specific service, but an "upload to" setting like in ShareX.

(Method (GET/POST/PUT/PATCH/DELETE), URL, something for the response (XML/JSON), maybe URL parameter (a user key for example?))

**Comment by borgmanJeremy** [comment]
We are tracking changes to the upload tool on #955 . My current thinking is to literally support the shareX "plugins".
