### ISSUE TITLE
Shortcut T "Add text to your capture" not work in Ubuntu20.4

### ISSUE THREAD

**Issue by ugirc** [flameshot-org/flameshot#1192]
**Flameshot version**

Flameshot 0.6.0+git20191001-2(Debian)
![image](https://user-images.githubusercontent.com/46078304/102572076-1c0b5700-4126-11eb-91be-a4690b1c975b.png)

**Describe the bug**

I use `flameshot gui` to start shot, and I try to use key `T` to add text to my capture.

But it not work!

I can only use mouse to click the menu `T`, then I can add text.

**To Reproduce**

**Expected behavior**

Can I just use a key to add text to my capture?

**System Information**

Ubuntu 20.4

**Comment by ZetaoYang** [comment]
The following shortcuts do not work properly in version 0.8.5 too. Test on Ubuntu 20.04 i3 X11. 
![image](https://user-images.githubusercontent.com/10769951/102676208-6b5d9000-41d7-11eb-88fb-cac38d88e609.png)

**Comment by borgmanJeremy** [comment]
@ZetaoYang The issue is these are only available on main and have not in a tagged release yet. We need to fixup some issues on main and then get another release out probably.
