### ISSUE TITLE
MacOS bundle

### ISSUE THREAD

**Issue by chux0519** [flameshot-org/flameshot#1193]
I've been using my macbookpro recently, and found out I can only use flameshot from command line.

so I wrote a simple script to generate an app bundle.

0. build flameshot, and make sure there is `build/src/flame` binary.
1. use any svg editor to export a 1024x1024 png file from `data/img/app/flameshot.svg`, name it as `flameshotx1024.png`
2. run the following script

[bundle.sh](https://gist.github.com/chux0519/492b68a56c32d9cd08f07c136666d214)

I think it can be done by using `MACOSX_BUNDLE` of cmake, but did not try it yet. Maybe I will take a look at this issue later, and file a PR once I managed to bundle the app with cmake.

**Comment by thepurple** [comment]
I'm working on MacOS support now and have fixed a number of issues, soon I will create a PR with a number of fixes and CI for MacOS.

**Comment by chux0519** [comment]
> I'm working on MacOS support now and have fixed a number of issues, soon I will create a PR with a number of fixes and CI for MacOS.

cool! looking forward

**Comment by borgmanJeremy** [comment]
Should be merged now.
