### ISSUE TITLE
icon not showing up in systray on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by CaptainJack42** [flameshot-org/flameshot#1198]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

The icon from flameshot isn't showing up in my systray. I recently reinstalled my Ubuntu 20.04 LTS and wanted to reinstall flameshot again as well, it has worked perfectly fine previously. But the icon in the system tray isn't showing up for me, it works if via 'flameshot gui' in terminal and i have tried purging and reinstalling multiple times, also checked the 'flameshot config' and activated or deactivated and activated the checkmark for show Tray icon multiple times, but it won't show. 

**To Reproduce**
No idea, sry. It has worked previously on the same laptop with the same OS, but since i put on a fresh install of the OS it doesn't anymore.

**System Information**
Ubuntu 20.04.1 LTS

**Comment by mmahmoudian** [comment]
Im so puzzled about the bug reports of Ubuntu 20.x users where they have still version 0.6.x ! The latest version of Flameshot is 0.8.5 and in Ubuntu apt repository the available version is 0.8.3 .

Regardless, please try the 0.8.3 or 0.8.5 version and then report back. Make sure to remove the old version before installing the new one.

**Comment by borgmanJeremy** [comment]
Almost every time there is a reported systray issue it's due to a missing or buggy gnome extension.

**Comment by CaptainJack42** [comment]
> Im so puzzled about the bug reports of Ubuntu 20.x users where they have still version 0.6.x (e.g #1197) ! The latest version of Flameshot is 0.8.5 and in Ubuntu apt repository the available version is 0.8.3 .
> 
> Regardless, please try the 0.8.3 or 0.8.5 version and then report back. Make sure to remove the old version before installing the new one.
> 
> There are few options to install the latest version which I explained in details in the following link:
> 
> [#1197 (comment)](https://github.com/flameshot-org/flameshot/issues/1197#issuecomment-750243652)

Just downloaded it with snap and it worked perfectly, got version 0.8.5 now and the icon is showing up in my systray again. Thx a lot for the help and the quick response, didn't check which version i had since i assumed i'd get the latest one from apt..
