### ISSUE TITLE
how to show a pinned item without the purple border around it?

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#1199]
![image](https://user-images.githubusercontent.com/1093841/103035556-40c15d80-4570-11eb-9f3f-1caf01f923ff.png)

**Comment by borgmanJeremy** [comment]
Right now this is not possible, but we are tracking potential changes to the pin tool on #954

**Comment by elad2109** [comment]
How can I know when is this public?

**Comment by borgmanJeremy** [comment]
You can set notifications for new releases on GitHub.
