### ISSUE TITLE
tray icon monochrome on ubuntu 20.04 with gnome-shell

### ISSUE THREAD

**Issue by MrAnon-dev** [flameshot-org/flameshot#1201]
Hi, 

I managed to change the icon to a custom one using Dash to panel gnome-shell extension (/usr/share/icons/Yaru/24x24/panel/flameshot-tray.png) but no with default installation. 

where should the icon be placed for ubuntu 20.04¿?

thanks!!

**Comment by borgmanJeremy** [comment]
This depends on if you installed the software with snap, apt, or flatpak. How did you install it and what version?

**Comment by MrAnon-dev** [comment]
Hi, 

sorry, I forgot that info

flameshot-0.8.5-1.ubuntu-20.04.amd64.deb

thanks in advance!

**Comment by borgmanJeremy** [comment]
Not sure if you were able to figure this out, but I am not 100% certain where gnome requires the icon to be placed. After some more thinking it might be best to ask this on the Ask Ubuntu forum.  I expect you will get a better answer since it is not really related to flameshot specifically.
