### ISSUE TITLE
Bold Text option and like black color addition when taking a screen shot

### ISSUE THREAD

**Issue by WalkonATYCLB** [flameshot-org/flameshot#1202]
**Is your feature request related to a problem?** yes, I would like to make bold text a option and have the option to make my color black.  Black is currently not available.

**Comment by borgmanJeremy** [comment]
If you hit spacebar or click the left side of the screen it will open another launcher that will let you customize the color to anything (including black), and select bold. 

Let me know if that does not work for you.

**Comment by SirNapkin1334** [comment]
> If you hit spacebar or click the left side of the screen it will open another launcher that will let you customize the color to anything (including black), and select bold.
> 
> Let me know if that does not work for you.

While this is nice, I feel like white and black are common enough colors that it is worth it to add them to the color wheel, or to replace other less common ones (like aqua, dark green, or maroon).

**Comment by borgmanJeremy** [comment]
This is actually supported with a poorly documented feature:

![image](https://user-images.githubusercontent.com/46930769/103571069-df628e00-4e8f-11eb-8fb8-45e19fce8c7d.png)

**Comment by SirNapkin1334** [comment]
Flameshot has a config file? I was completely unaware! Where?

**Comment by borgmanJeremy** [comment]
~/.config/flameshot/flameshot.IMO
