### ISSUE TITLE
How to install flameshot on windows?

### ISSUE THREAD

**Issue by Crucizer** [flameshot-org/flameshot#1204]
In the installation section, it was written that flameshot is available for windows but I can't find any `.exe` file or something like that to install this on windows? 

It would be really helpful if someone can help me install this on windows.

**Comment by fireFerry** [comment]
The latest version available for windows can be downloaded [here](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.4). The Windows binaries aren't signed yet for version 0.8.5, once they are the files will be added to that release.

**Comment by Crucizer** [comment]
Thanks! I'm able to use flameshot now. But there was only an application file there, so there is no way to install it on my system?

**Comment by borgmanJeremy** [comment]
There is also an msi file in the releases: https://github.com/flameshot-org/flameshot/releases/tag/v0.8.4

**Comment by devious21sf** [comment]
Is there a default keyboard shortcut to take screenshot on Windows? Or is there an elegant way to configure one?

**Comment by mmahmoudian** [comment]
@devious21sf the PrintScreen button on your keyboard should work:
![image](https://user-images.githubusercontent.com/390889/103410497-17a65b80-4b74-11eb-9b3a-ebf87049a83d.png)
