### ISSUE TITLE
Dissapear icon in task bar Ubuntu 20

### ISSUE THREAD

**Issue by bazhil** [flameshot-org/flameshot#1206]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Describe the bug**
After update dissapear flameshot icon from task bar. Work only from terminal (flameshot gui).

**To Reproduce**
May be install Ubuntu 20.04 LTS and update Flameshot.

**Expected behavior**
Flameshot runs with system start and it icon shows in task bar. All works correctly.

**System Information**
Ubuntu 20.04.1 LTS 64-bit, GNOME 3.36.8

**Comment by borgmanJeremy** [comment]
Can you please install a version from the 0.8.x series? It is available via snap on Ubuntu.

**Comment by bazhil** [comment]
@borgmanJeremy thanks, it helps
