### ISSUE TITLE
Signed Windows Binaries for 0.8.5

### ISSUE THREAD

**Issue by dezren39** [flameshot-org/flameshot#1207]
**Flameshot version**
0.8.5

**Describe the bug**
Needs signed Windows Binary.

**System Information**
Win10

**Comment by dezren39** [comment]
I don't have time to compile an unsigned version, but I suppose personally I wouldn't mind that either. 😅

**Comment by borgmanJeremy** [comment]
We are tracking this on #939 so I am going to close this as a duplicate. We have a couple of items to merge into our 0.8.x branch and then will cut a new release.
