### ISSUE TITLE
[Feature Request] Being able to screenshot windows that are to "high"

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1209]
I don't really know how to explain it,but if you open some spedific things,then you can't make a screenshot.
For example,if you go into Dolphin file manager and right click something like "Home" then you can't make a screenshot,cause the window (not really window,but I don't know the proper name of that) that is "higher" appears.

**Comment by borgmanJeremy** [comment]
Sorry I do not quite understand the issue. If you are not able to take a picture of the problem could you sketch it out? 

If I go into dolphin and right click "Home" I have no issues.

**Comment by Toadfield** [comment]
If you go in Dolphin,right click on Home and then press your shortcut to make a flameshot screenshot,then does it work for you?
Cause if I open a little menu like by right clicking home and then try to make a screenshot,it doesn't work (only if that little menu is open,when it is not open,it works).

**Comment by borgmanJeremy** [comment]
Ohh I see what you mean.

As a work around you can use a delay.

**Comment by borgmanJeremy** [comment]
This might a bug in KDE itself. It seems like its not registering the hotkey when the menu is active.

**Comment by Toadfield** [comment]
> As a work around you can use a delay

What delay?
Do you mean a option in flameshot?
> This might a bug in KDE itself.

I will make a kde bug report later,if it's really a kde bug.

**Comment by borgmanJeremy** [comment]
Right click the tray icon and hit "Open Launcher" Then adjust the delay:
![image](https://user-images.githubusercontent.com/46930769/103449403-96cb8a80-4c6d-11eb-864f-19b6418fa123.png)

![image](https://user-images.githubusercontent.com/46930769/103449392-6e439080-4c6d-11eb-9d72-eb1bfdf97d33.png)

**Comment by Toadfield** [comment]
> This might a bug in KDE itself. It seems like its not registering the hotkey when the menu is active.

Yeah,I tested it with another shortcut from another application,and the same issue,I [reported it to Kde](https://bugs.kde.org/show_bug.cgi?id=431046)
And I hope they fix it fast,cause that workaround obviously won't work for non Flameshot programs.
I will also close this issue,cause it has nothing to do with Flameshot itself.
