### ISSUE TITLE
Allow installing on PC, Mac and Android

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#1218]

**Comment by mmahmoudian** [comment]
If by PC you mean Micr🔒$🔒ft Window$, then the .exe and .msi files can be downloaded from [Releases page](https://github.com/flameshot-org/flameshot/releases/)

About OSX, there are some contributors working on it.

Regarding Android, I'm not sure if that is a feasible move. Perhaps @borgmanJeremy and @ZetaoYang can give a more accurate and better answer on why it can or cannot happen.

**Comment by elad2109** [comment]
I don't see .exe on that page (I have tried ctrl+F):

https://github.com/flameshot-org/flameshot/releases/

**Comment by mmahmoudian** [comment]
The windows version is not available for v0.8.5 but for v0.8.4 you can download it:

https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win64.msi

**Comment by borgmanJeremy** [comment]
Getting this running on Android is just not technically feasible. It would require a 100% rewrite. As you say, we fully support Linux, and are continuing to improve Windows and MacOs support.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flameshot-org/flameshot/issues/1218#issuecomment-754158809

@borgmanJeremy, what architectural decisions prevent it being ported?

**Comment by borgmanJeremy** [comment]
It's built using Qt Desktop toolkit (not Qt for Android)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flameshot-org/flameshot/issues/1218#issuecomment-2833602530

As in, `QtWidgets` rather than `QtQuick` (if you don't mind me probing)?

**Comment by borgmanJeremy** [comment]
I thought Qt had a specific android toolkit. I don't really know anything about Android which is another good reason to not add it haha

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flameshot-org/flameshot/issues/1218#issuecomment-2833615806

@borgmanJeremy, that is a good reason not to! Though, you might be pleasantly surprised by how portable Qt, of all toolkits, is. My lay man's understandint of your codebase is that it's more likely that the underlying logic would be the pain point.
