### ISSUE TITLE
[REQUEST] Customizable screenshot resolution

### ISSUE THREAD

**Issue by SirNapkin1334** [flameshot-org/flameshot#1219]
**Is your feature request related to a problem?**  
No.

It would be amazing if we could increase the resolution at which screenshots are captured. I have a 4k display, and the 1080p images that are captures can be pretty hard to read for people that I send them to, as I'm able to have the text fairly small since I am on 4k. Even 1440p would be nice. I'm not sure how it would work for custom-size screenshots, though. 

I hope this isn't a duplicate (sorry if it is), but a bit of searching doesn't seem to turn anything up.

**Comment by borgmanJeremy** [comment]
If your resolution is being downsampled I consider that a bug and would like to fix it.

**Comment by SirNapkin1334** [comment]
For unknown reasons, it now appears to work, after having redone all of my keyboard shortcuts and setting up a system to upload. I suspect my previous keyboard shortcut setup (which I took from the pre-made ones for KDE Plasma and tweaked slightly) were the cause.
