### ISSUE TITLE
[Feature Request] arg for exact output filename override

### ISSUE THREAD

**Issue by bidlocode** [flameshot-org/flameshot#1224]
`-o --output <filename>` for exact output filename one-time override
or/and cmd arg for opening output file in another program after capture.

It will be very useful when used in scripts and in combinations with other programs
```
flameshot gui --output out.png
othercmd1 -i out.png
othercmd2 -i out.png
...
```

**Comment by bidlocode** [comment]
Also i think it would be very beneficial for this use case if other options like 'Close after capture' should be overridable from cmd.

**Comment by bidlocode** [comment]
i found a solution for this
```
flameshot gui -r > out.png
```
but i think other options (like upload, close after capute, etc) should be overridable from cmd
it makes it more convenient to use in scripts

**Comment by lervag** [comment]
I agree. This feature is more or less the only thing I miss after switching from `scrot`.
