### ISSUE TITLE
Pass screenshot to command

### ISSUE THREAD

**Issue by Qwerty-Space** [flameshot-org/flameshot#1229]
**Is your feature request related to a problem?**
Flameshot currently allows passing the image to an application, and you guys are working on a way to upload to custom uploaders,  however there is another more Linuxy way (in my opinion) to do this and more, and it doesn't have to be mutually exclusive with the custom uploader framework you're working on.  And that would be passing it to a command via the gui

**Comment by borgmanJeremy** [comment]
Have you looked at using the --raw cli option?

**Comment by Qwerty-Space** [comment]
That's not on the website or in the help

**Comment by borgmanJeremy** [comment]
Feel free to improve the docs with a pull request. We try to keep it up to date but stuff can get missed.

**Comment by bidlocode** [comment]
Same as #1224 
Sure, `flameshot gui -r > out.png` is good, but it's far from perfect solution.
It will write any output to file including any output messages, errors, etc ? 
So you can get `out.png` that it's not actually an image.

**Comment by Qwerty-Space** [comment]
@bidlocode I don't think that's the same

**Comment by borgmanJeremy** [comment]
@Qwerty-Space why does the raw option not work for your use case?

**Comment by Qwerty-Space** [comment]
It'll probably be fine
