### ISSUE TITLE
[Feature Request] Being able to make a shortcut to take a screenshot

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1230]
If I go to the kde shortcut settings and make a shortcut for flameshot,then it doesn't take a screenshot with that,but starts flameshot itself.
I know that I can do it in custom shortcuts,but there is a bug right now that prevents doing that and it would be cooler in the normal shortcut settings anyway.

**Comment by mmahmoudian** [comment]
I removed my custom shortcut and created a shortcut through the "Shortcuts" and took this screenshot with it through a single press of <kbd>prntscrn</kbd> : 

![image](https://user-images.githubusercontent.com/390889/104450452-cc933c00-55a8-11eb-87c1-33868054c45a.png)

The flameshot I have installed at the moment is 0.8.3, but there shouldn't be any differences for your issue. Shall we consider this issue closed?

**Comment by mmahmoudian** [comment]
I just tried with 0.8.5 and it still works fine.

**Comment by Toadfield** [comment]
I don't see "take screenshot"
![image](https://user-images.githubusercontent.com/68649672/104453568-ec286580-55a4-11eb-90a5-b70325e24a73.png)

**Comment by mmahmoudian** [comment]
Can you provide your system information and Flameshot version.

**Comment by Toadfield** [comment]
![image](https://user-images.githubusercontent.com/68649672/104462073-64e0ef00-55b0-11eb-9c8c-00725ff7e449.png)
Flameshot 0.8.5-1

**Comment by mmahmoudian** [comment]
@Toadfield that KDE bug that was preventing the user to define the shortcut key was fixed earlier this week (it was affecting my work computer as well).

Do you think this feature request still has some merit or you think it can be closed?

**Comment by Toadfield** [comment]
Oh thanks,now it works.
