### ISSUE TITLE
Build error: error: expected nested-name-specifier before ‘app_t’

### ISSUE THREAD

**Issue by skywoodsz** [flameshot-org/flameshot#1231]
**Flameshot version**

**Describe the bug**
When I was building the source to install, I met the error as follow:
"/flameshot/build/external/singleapplication/SingleApplication_autogen/EWIEGA46WW/../../../../../external/singleapplication/singleapplication.h:46:11: error: expected nested-name-specifier before ‘app_t’"
     using app_t = QAPPLICATION_CLASS;

I don't know how to solve this problem, can you help me?

**To Reproduce**

**Expected behavior**

**System Information**
My system is Ubuntu 16.04 and gcc is 5.4.0.

**Comment by borgmanJeremy** [comment]
I suspect our single application dependency requires a newer version of gcc https://github.com/itay-grudev/SingleApplication

Our minimum support version is ubuntu 18.04.

**Comment by borgmanJeremy** [comment]
Yeah I just confimred that version of gcc does not support type alias's from c++ 11:

https://godbolt.org/z/6YaMYK

https://en.cppreference.com/w/cpp/language/type_alias

**Comment by skywoodsz** [comment]
> Yeah I just confimred that version of gcc does not support type alias's from c++ 11:
> 
> https://godbolt.org/z/6YaMYK
> 
> https://en.cppreference.com/w/cpp/language/type_alias

That means I can not use  flameshot on the Ubuntu1604?

**Comment by borgmanJeremy** [comment]
Not the latest version. We are not supporting anything older than 18.04. 16.04 is end of life in April anyway.

It's possible to manually install a newer version of gcc if you must build from source.

Or you could use our snap, appimage, or flatpak.

**Comment by skywoodsz** [comment]
> Not the latest version. We are not supporting anything older than 18.04. 16.04 is end of life in April anyway.
> 
> It's possible to manually install a newer version of gcc if you must build from source.
> 
> Or you could use our snap, appimage, or flatpak.

Ok, I get it. Thanks for your reply, I would continue to support this project.

**Comment by snjjay** [comment]
I found this article useful for the issue https://kodlogs.net/214/error-expected-nested-name-specifier-before-namespace-fixed
