### ISSUE TITLE
Typed text is missing if "save into file" functionality is invoked using Ctrl+S hotkey combination

### ISSUE THREAD

**Issue by mikkovedru** [flameshot-org/flameshot#1234]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian) (the latest for my distribution)
Compiled with Qt 5.12.5

**Describe the bug**
Typed text is missing if "save into file" functionality is invoked using Ctrl+S hotkey combination.

**To Reproduce**
1. Invoke `flameshot gui` and select an area
2. Select Text mode
3. Click with left mouse key somewhere on the screen and type "Test1"
4. Click somewhere else on the screen (this will "freeze" the text)
5. Click yet another time on another place on the screen
6. Type "Test2"
7. Press Ctrl+S and save the file
8. Bug: See that the saved file is lacking the "Test2" text in it.

**Expected behavior**
It is expected that all the text would be saved in the screenshot, even if the text was written in the text mode that was enabled at the time of pressing Ctrl+S. 

The text is saved if I press the "Save the capture" button with my mouse. Now this just needs to be made consistent with invoking the saving via Ctrl+S hotkey.

**System Information**
Linux Mint 20 Cinnamon (Based on Ubuntu 20.04)

**Comment by mmahmoudian** [comment]
Can you confirm if the behaviour persists even if you change the tool from text to something else (e.g arrow) before Ctrl+s

**Comment by borgmanJeremy** [comment]
This should be solved in 0.8.3

**Comment by mmahmoudian** [comment]
@borgmanJeremy nice catching, I didn't see the version number 🤦‍♂
