### ISSUE TITLE
Donation support

### ISSUE THREAD

**Issue by thureos** [flameshot-org/flameshot#1235]
I started using FS not long ago but it is a must have in each of my new pc installs. I would like to thank the team with a small donation but I haven't found a way of doing it. If you don't need the money, please have my appreciation!

Thank you guys!

**Comment by mmahmoudian** [comment]
I'm glad that you have also found Flameshot useful. The topic of donations has been brought up few times already, but for the time being there is no major costs. For now, I will mark this as "needs discussion" just in case the devs who actually do the coding have any ideas.

In my humble opinion, the best donation would be your time. If you can, help with the code or if you, like me, don't know the C++, help us making the documentation better (there is a separate repository for the website) or help answering some of the questions in the issues (usually labelled with "question") or help us confirm and reproduce some bugs (labelled "unconfirmed bug"). Even spreading the word would about Flameshot and suggesting it to friends and colleagues would be amazing.

**Comment by thureos** [comment]
Thank you, 

How about a [bounty source](https://www.bountysource.com) account where you can put sponsors/coders to work together on a issue/feature?

**Comment by mmahmoudian** [comment]
I've never heard of this bountysource. Perhaps it can be discussed with the community. Use the following link to join our community Slack channel:

https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg

**Comment by borgmanJeremy** [comment]
Im good with bounty source. That fits our model much better where we got lots of short contributions from many people.

**Comment by mmahmoudian** [comment]
**Update:** I finally managed to act upon this as it will help people to directly invest in the codebase transparently. I went to create the "team" there for Flameshot and I realized it already exists, so I applied to claim the management and maintenance of it. I will update here when the rights were transferred and I completely setup the Flameshot team there.
![image](https://user-images.githubusercontent.com/390889/122368638-2f2ca180-cf66-11eb-8514-2181eab4ba15.png)


In the meanwhile, I updates some of the texts and links.

**Comment by ianwijma** [comment]
I personally don't have time to spare and would love to chuck a few bucks to this project because its my defacto screenshotting tool helping me on my personal machines, but also with work it empowers me to make screenshots without needing to pull out and editor to add arrows and overlay screenshots. To I don't mind supporting this project and its maintainers financially a bit once in a while.

**Comment by mmahmoudian** [comment]
Unfortunately the BountySource hasn't replied back in spite if multiple messages from us (I wish people cared more for their business). [We are considering Rysolv](https://flameshotworkspace.slack.com/archives/C019W6EPYMN/p1625741085023000) but there are few questions that we should find answer to.

**Comment by ZetaoYang** [comment]
@mmahmoudian Is this a legacy? https://opencollective.com/flameshot

**Comment by mmahmoudian** [comment]
@ZetaoYang interesting! It never came up in my searches. It is definitely a legacy account and we should close it. As I have also mentioned on Slack, I have opened an account for Flameshot on Rysolv and we are testing it. The idea is to use donations to directly improve the software and to reduce some of load from the main devs.

https://rysolv.com/repos/detail/2ce10839-c350-47b1-89a4-2ee9cf0e0678

I also already put a bounty/reward on one of the issues.


If we agree to go with Rysolv, then we should make a public announcement.

**Comment by CyrusZei** [comment]
Add a github sponsor button. Love this app !! Thank you for this

**Comment by mmahmoudian** [comment]
@CyrusZei please consider using Rysolv:

https://rysolv.com/repos/detail/2ce10839-c350-47b1-89a4-2ee9cf0e0678

This way your donations directly turns into features and bug fixes in a transparent way.

**Comment by mmahmoudian** [comment]
**Update:** I contacted OpenCollective and after some discussions they said that they will close [the Flameshot pledge in OpenCollective](https://opencollective.com/flameshot). Although at the time of writing this message it is already over 22 hours that they confirmed they will delete it and yet is not removed nor frozen.

The general idea is to bring all the peripheral accounts under the same umbrella of administration so that we can keep track of things.

Our current stance regarding donation is now available on our website (https://flameshot.org/donate/) and it will get updated if/when the consensus collective decision was changed. Also, if/when that changed, there will be posts on [Flameshot social media account](https://fosstodon.org/@flameshot) to inform everyone accordingly.

**Comment by tyleris-irish** [comment]
> Add a github sponsor button. Love this app !! Thank you for this

Rysolv is still down after a few months and it seems that alternative code bounty programs are hard to find. Have you guys considered GitHub Sponsors again? It seems to be well received by other repositories

**Comment by mmahmoudian** [comment]
@tyleris-irish 
Thanks for your comment. I updated the donation page on our website few months back to reflect that Rysolv issue and I wrote that we are looking for an alternative and we are open to suggestions:

https://flameshot.org/donate/

As for Github sponsor, previously the idea was to have code bounty to avoid tax issues. Of course that discussion happened some years ago and we can have the discussion again, especially if @borgmanJeremy is willing to take the bite and get the sponsorship 😊 I personally cannot accept donations for various reasons including the tax and also the fact that majority of the work is done by @borgmanJeremy and not me.

I believe if this is discussed again and we move towards a donation scheme, OpenCollective is a better choice, as it would leave the room for potential future maintainers in the team. But again, by not accepting financial contribution, we are automatically protected against many regulations.

**Comment by borgmanJeremy** [comment]
I also can't really accept the donations for a variety of reasons. Part of which is I am only one person doing the coding. We accept lots of community contributions and I don't want to manage the guilt of equitably sharing the money. I also don't think the dollar amount in practice would be high enough to take on all the extra work of managing finances.
