### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1236]
Add a feature that lets flameshot query the github release API to determine if it has the latest version. Useful for windows and Linux.

@mmahmoudian I discovered the team at namecheap(@thepurple) added this feature already. Do you see any privacy concerns with this? I am not sure if I should leave it in during the merge or pull it out. I think it will be pretty nice for appimage, MacOs, and Linux but I know some people hate anything that can phone home.

**Comment by ZetaoYang** [comment]
Duplicated with https://github.com/flameshot-org/flameshot/issues/1237.
