### ISSUE TITLE
Take screenshot after x seconds

### ISSUE THREAD

**Issue by Mondane** [flameshot-org/flameshot#124]
Sometimes, I need to take a screenshot from a submenu or a hover state in a site. This can be achieved by setting a timer before the screenshot is taken. Based on the amount of time, I would have time enough to move the mouse and interact with the screen.

**Comment by lupoDharkael** [comment]
You could configure a shortcut as `flameshot gui -d 1000`( or another value in milliseconds to achieve a delay) from the configuration panel of your desktop environment.

**Comment by Mondane** [comment]
Good to know this workaround. Will you add it as a GUI toolicon too?

**Comment by lupoDharkael** [comment]
The version 0.6 will have a graphical panel where you will be able to launch screenshots with some controls over configuration similar to the concepto of the widget of Spectacle.
Here is how it looks the panel of Spectacle: ![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Flamiradadelreplicante.com%2Fwp-content%2Fuploads%2F2015%2F12%2Fspectacle.jpg&f=1)

**Comment by MichaelTunnell** [comment]
Spectacle is what I prefer to use solely for the delay option, if Flameshot adds that then it is likely to become my go to. :)

**Comment by AlexWayfer** [comment]
> The version 0.6 will have a graphical panel where you will be able to launch screenshots with some controls over configuration similar to the concepto of the widget of Spectacle.

Sorry, but I have version 0.6 and don't see it. Are there any new plans?

**Comment by lupoDharkael** [comment]
The launcher is almost done, you can test it in the branch `launcher`, there is a problem. When you take the screenshot the panel doesn't hide in time because some desktops use animations.
I could release a new version with the panel not hiding when you take the capture and fix it later.

**Comment by luzpaz** [comment]
any progress on the `launcher` branch ?

**Comment by kevinsmia1939** [comment]
GUI delay functionality is really useful feature, this is what keep me using spectacle. Hopefully this will come soon.

**Comment by danilomagrini** [comment]
it would be a great improvement

**Comment by MichaelTunnell** [comment]
I really like Flameshot but the ability to have a delay is very important most of the time. I use Flameshot at this point only if I need to use arrows or quick edits on top just because getting the command is longer than using Spectacle. However, I suppose I could just make a shortcut for the delay but then the time will be locked to whatever I put there. Overall, Flameshot is fantastic but having a easy access delay would be so awesome.

I would be totally happy if the option wasn't in a popup GUI too. It could be in the context menu of the entry in the system tray. If you could configure the time of delay in the settings and then have an entry for that in the context menu that would be perfect! If there were multiple timed options in that it would be even better. :sunglasses: 

![2019-04-19_08-25](https://user-images.githubusercontent.com/1056731/56426129-b09c2280-627c-11e9-9bba-df661a46c0a7.png)

**Comment by vogella** [comment]
Please add this to the UI

flameshot gui -d 5000 is fine to use but would be  nicer to have it in the GUI

**Comment by cipricus** [comment]
Associating main commands makes Flareshot my choice for screen-shooting:

`flameshot gui` associated with Print key

`flameshot gui -d 7000` associated with Ctrl+Print

**Comment by MichaelTunnell** [comment]
@cipricus 
> Associating main commands to shortkeys makes Flameshot my choice for screen-shooting

These are what I do as well but the lack of a GUI option is just bad for general usage.

**Comment by MurzNN** [comment]
@MichaelTunnell as alternative you can try https://github.com/ksnip/ksnip program, that have classic UI

**Comment by AlexWayfer** [comment]
> @MichaelTunnell as alternative you can try https://github.com/ksnip/ksnip program, that have classic GUI

That's really nice alternative, thank you.

**Comment by razvan-flavius-panda** [comment]
Has the branch for the GUI version of flameshot been released? Does it work from tray like other similar programs or how?

**Comment by benwinding** [comment]
Yay, this is now possible in the UI, just follow these steps

![image](https://user-images.githubusercontent.com/11782590/80438181-b245ff00-8942-11ea-9c9f-afb9538cef19.png)

![image](https://user-images.githubusercontent.com/11782590/80438317-0fda4b80-8943-11ea-9e33-4a0e41563154.png)

**Comment by luzpaz** [comment]
Can confirm! I guess this issue can be closed.  
Thank you!

**Comment by Moini** [comment]
Cool - which release will this be in?

**Comment by AndydeCleyre** [comment]
Any reason this can't be available via the sidebar from `flameshot gui`? So we can always start flameshot with the same shortcut for `flameshot gui -p <...>`, and then if we want to alter behavior, we then hit space to configure, before taking the shot?

**Comment by borgmanJeremy** [comment]
The tool gui?

**Comment by AndydeCleyre** [comment]
> The tool gui?

I suppose so, yeah. The help message/instructions that popup when launching with `flameshot gui` calls it "the side panel" so I didn't realize its scope is really targeted at tools. It is available before taking the screenshot (so before any tools are accessible), so there is potential to use the space for pre-screenshot settings as well.

**Comment by borgmanJeremy** [comment]
This will be in the 0.8 release this weekend.

**Comment by Moini** [comment]
Could someone explain how I can now do timed screenshots via GUI? I can't seem to find a setting for 'make a shot in x seconds'.

**Comment by borgmanJeremy** [comment]
If you right click the icon, hit "open launcher" This brings up a gui that lets you set the delay.

**Comment by AlexWayfer** [comment]
> If you right click the icon, hit "open launcher" This brings up a gui that lets you set the delay.

Also there is `flameshot launcher` command for those who interested in CLI or shortcuts.

**Comment by Moini** [comment]
Thanks! I think 'open launcher' is maybe not the best way to advertise this feature (I thought the launcher was what I get when I right-click on the icon in the status bar), but I'll find it now.

**Comment by mmahmoudian** [comment]
@Moini The launcher is not just for the delay screenshots, you can also specify what type of screenshot you want. Perhaps in future other features will be also added to launcher.

![image](https://user-images.githubusercontent.com/390889/94182548-d5e98300-fea9-11ea-88e3-6dee5b861d00.png)

**Comment by thepisu** [comment]
Yes, very useful! I set hotkeys PRTSCR for "flameshot gui" and SHIFT+PRTSCR
for "flameshot launcher".

Stefano Bagnatica

Il gio 24 set 2020, 20:07 Mehrad Mahmoudian <notifications@github.com> ha
scritto:
