### ISSUE TITLE
error in arch linux 

### ISSUE THREAD

**Issue by peidrao** [flameshot-org/flameshot#1241]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**

$> flameshot

(process:13655): Gtk-WARNING **: 10:20:02.326: Locale not supported by C library.
	Using the fallback 'C' locale.
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 418, resource id: 0, major code: 20 (GetProperty), minor code: 0
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

**System Information**
Arch Linux

**Comment by borgmanJeremy** [comment]
Check out #1146 and let me know if that doesn't work.

**Comment by peidrao** [comment]
> Check out #1146 and let me know if that doesn't work.

Goood

Thank you man!
