### ISSUE TITLE
Deploy flameshot on cloud based host and use it remotely.

### ISSUE THREAD

**Issue by hongyi-zhao** [flameshot-org/flameshot#1242]
Can I deploy flameshot on cloud based host and use it remotely?

Regards,
HY

**Comment by borgmanJeremy** [comment]
As long as the remote server has an active desktop environment or window manager it should work.

**Comment by hongyi-zhao** [comment]
By saying *use it remotely*, I mean use it on the local side instead of logging into the remote side where flameshot is deployed and use it there. Is this possible?

**Comment by borgmanJeremy** [comment]
No we don't have any feature lie that.
