### ISSUE TITLE
JPG for clipboard

### ISSUE THREAD

**Issue by dd1303** [flameshot-org/flameshot#1243]
Hi,

is it already possible to save the screenshot as JPG to clipboard instead of PNG? If not already available ... would it be possible to plan it for a future release?

This would save a lot of space in my emails. For example a 50%-quality JPG takes 1/20 of the size compared to PNG

Of course I found the save button (floppy disk symbol) which can save as PNG, BMP and JPG. But that way includes too mayn steps later to include it into my emails and documents.

I use flameshot v0.8.5 on Lubuntu 18.04 only since recently and I'm really happy otherwise about the features, ease of use and stability of flameshot.

Best regards,
Dietrich

**Comment by borgmanJeremy** [comment]
This is a good idea. I think we could add an option for this.

**Comment by sonulohani** [comment]
Hi @borgmanJeremy I want to work on this issue. Could you please assign this issue to me. Thanks.

**Comment by borgmanJeremy** [comment]
@sonulohani  Sure, let me know if you want any help or direction. Either can leave comments here or hit me up on our slack: https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg

**Comment by sonulohani** [comment]
@borgmanJeremy Thanks for the directions. I will sure connect with you if I would have any problem.

**Comment by dd1303** [comment]
Hi Jeremy, Hi Sonu Lohani,

first of all - thank you very much for accepting and implementing my
issue in such a short time :o)

Of course I wanted to use the new feature, but I failed. Probably I'm
doing something wrong.

I'm new to github and I'm not sure how handle my question to you. Just
an email like this? Or is there a better way, like a forum or opening a
new issue or opening the old issue?

The problem:

I still only see PNG on the clipboard. I can see PNG with

a) Commpose a Thunderbird email and look a the email source with Control U
b) Inspect Clipboard with Qcopy




What I did ...

I followed you compilation readme:

pkill flameshot

cd ~didi
mkdir -p git/repo
cd git/repo
git clone https://github.com/flameshot-org/flameshot

LANG=C # only for git infos
$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

$ git log
...
commit a944860d12bf0dab925433ef5a039cf969bd1244
Author: Sonu Lohani <sonulohani@gmail.com>
Date:   Sat Jan 30 10:01:14 2021 +0530

     Add config for jpg/png when copy

commit b121c6c72b44990992e71b432e8d995ae938308c
Author: Sonu Lohani <sonulohani@gmail.com>
Date:   Fri Jan 29 19:24:02 2021 +0530

     Fix clang format

commit 8f058f98f3ba288d95f65ae22f9945a44c4c0146
Author: Sonu Lohani <sonulohani@gmail.com>
Date:   Fri Jan 29 19:17:48 2021 +0530

     JPG for clipboard
...
LANG=de_DE.UTF-8

mkdir build
cd build
cmake ../
make

sudo cp -p /usr/bin/flameshot /usr/bin//flameshot-`date +%F-%X`
sudo ln -sf `pwd`/src/flameshot /usr/bin/flameshot

$ flameshot -de_DE.UTF-8-version
Flameshot v0.8.5
Compiled with Qt 5.9.5


I removed ~/.config/flameshot/flameshot.ini and created a new one:

[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x13\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\xe\0\0\0\f\0\0\0\x11)
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
filenamePattern=flameshot-%Y%m%d-%T
saveAfterCopy=true
saveAfterCopyPath=/home/didi/Bilder
savePath=/home/didi/Screenshots
savePathFixed=false
startupLaunch=false
useJpgForClipboard=true
useJpgInsteadPngWhenCopy=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z

In a 2nd step I added "useJpgInsteadPngWhenCopy=true" just as a naive
act of desperation ... flameshot didn't copy the picture as jpg with and
without that line


Best regards,
Dietrich


Am 03.02.21 um 02:39 schrieb borgmanJeremy:

**Comment by borgmanJeremy** [comment]
@dd1303 Good catch, I also seem the content type says png in thunderbird but it also looks like the image has plenty of jpeg artifacting.

@sonulohani Do you know if we need to explicitly set something in the mime date to say it is a jpeg image?

**Comment by borgmanJeremy** [comment]
For more reference https://forum.qt.io/topic/83879/how-to-control-the-quality-filesize-of-images-copied-to-the-clipboard

**Comment by borgmanJeremy** [comment]
@dd1303 I merged a fix here: #1285 

Thanks for reporting the issue. If you still see an issue let me know but local testing looks good. I copy and pasted into thunderbird and inspected the types the same way to did.

**Comment by Alaskra** [comment]
![image](https://user-images.githubusercontent.com/49367127/175780881-9de86257-8254-42c5-a4ea-2f9d100a773d.png)
Is this feature really take effort? I have set this option and then take the screenshot and upload to this comment as the above picture show, but it is still png other than jpg. And it also cause the problem #2650. My system is Manjaro KDE.

**Comment by Alaskra** [comment]
Is this feature really take effort? Although it can take effort in thunderbird, but it also not work in many case. For example, if set this option, copy screenshot and press `ctrl-v` in typora or github comment, nothing will happen.
And it also cause the problem https://github.com/flameshot-org/flameshot/issues/2650. My system is Manjaro KDE.
