### ISSUE TITLE
Can not install on Window 10

### ISSUE THREAD

**Issue by SergeyPirogov** [flameshot-org/flameshot#1244]
**Flameshot version**

I've got install from appveyor https://ci.appveyor.com/project/lupoDharkael/flameshot/builds/34725191

**Describe the bug**

Trying to run the installer but getting ERROR Qt5Widgets.dll is missing

**To Reproduce**

**Expected behavior**

**System Information**

**Comment by borgmanJeremy** [comment]
Can you try downloading a build from our release page?
