### ISSUE TITLE
flameshot 'copy the selection into the clipboard' function in Fedora 33

### ISSUE THREAD

**Issue by inoton** [flameshot-org/flameshot#1245]
**1. Copy the selection into the clipboard.**
<img src="https://raw.githubusercontent.com/inoton/Temp/main/222.jpg" width="50%">

**2. Paste into GIMP or Telegram , the image show like:**
<img src="https://raw.githubusercontent.com/inoton/Temp/main/111.jpg" width="50%">

**3.  The `Copy the selection into the clipboard` function is available after removing the 'qt5-qtwayland' package.**

- **Flameshot version**
```
$ flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

- **Describe the bug**
Not a bug, maybe need to specify an environment variable to re-render or something.

- **To Reproduce**
```
sudo dnf install qt5-qtwayland
sudo dnf remove qt5-qtwayland
After removing  qt5-qtwayland, the pasted image looks correct.
```

- **System Information**
OS Name: Fedora 33 64-bit
GNOME Version 3.38.2
Windows System Wayland
kernel-5.10.8-200.fc33.x86_64

Thanks!

**Comment by Philippe-M** [comment]
Hello,

I've the same problem

```
flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

**Comment by borgmanJeremy** [comment]
Here is a very detailed debugging session the team at ksnip did. I plan to copy thier fix: https://github.com/ksnip/ksnip/issues/416
