### ISSUE TITLE
When launched with arguments, doesn't take the system theme.

### ISSUE THREAD

**Issue by MR-Diamond** [flameshot-org/flameshot#1246]
**Flameshot version**
`0.8.5`

**Describe the bug**
Is not exactly a bug; when I launch it from a terminal window or using a bash script, in this particular case `flameshot gui` (to have it launched directly with screen selection tool) it doesn't respect the system theme which I set globally; but if launch it without any argument (in bash scripts or via its .desktop file), is using the system theme as expected.

**Expected behavior**
When launched with any argument
```
Arguments:
  gui            Start a manual capture in GUI mode.
  screen         Capture a single screen.
  full           Capture the entire desktop.
  launcher       Open the capture launcher.
  config         Configure flameshot.
```
Should be shown with the system theme.

**Current behavior**
When launched with any argument, doesn't apply the system theme (which instead occurs when launched without arguments)

**Two images which shown what I mean:**
- Launched without arguments:

<img src="https://user-images.githubusercontent.com/32249442/105040005-97339600-5a61-11eb-9045-ff37686edc4b.png" width="391" height="238">

- Launched with arguments:
<img src="https://user-images.githubusercontent.com/32249442/105040300-f5f90f80-5a61-11eb-96b7-fd24a2cbd151.png" width="391" height="238">

Such behaviour occurs as well for the flameshot's tray icon: when is using the theme, the tray icon is show themed like all others tray icons; when not themed shows the default icon.

I also tried by indicating the theme (`export GTK_THEME="Sweet-Darker"`) in the command line, but doesn't works.

**System Information**
Manjaro Xfce 64 bit.

**Comment by borgmanJeremy** [comment]
Is this installed through pacman or flatpak?

**Comment by MR-Diamond** [comment]
Is installed through pacman.
However I also tried by using the appimage; in such way is worse: is not themed at all.
Do you have some idea about the fact because when launched with arguments is not themed?
Is like if when executed with arguments it ignore system settings and environments.

**Comment by borgmanJeremy** [comment]
Im also on arch, but using KDE and cannot replicate this. Maybe its an issue with GTK or XFCE?

**Comment by mmahmoudian** [comment]
I tried on Manjaro XFCE in VM and I could reproduce this. (Installed via pacman).

**Comment by MR-Diamond** [comment]
That's possible.
However: flameshot is using qt5 as backend, and other applications which are using qt5 as backend doesn't shows such behaviour (like, eg, VLC or QBittorrent).
When flameshot exhibit such behaviour is like started with the "`-style Fusion`" flag, to tell to qt application to use this Qt theme.

**Comment by MR-Diamond** [comment]
I also tried by executing it by using `export QT_QPA_PLATFORMTHEME="gtk3"` and also  `export QT_QPA_PLATFORMTHEME="gtk2"` but unsuccesfully.

**Comment by MR-Diamond** [comment]
I have a very good news.

While I was tweaking with GTK3 settings, to get rid of many effects, I edited `~/.config/gtk-3.0/settings.ini`
In such way:

```
[Settings]
gtk-enable-animations=0
```

And guess what?
The described issue, is no longer here.
But please wait to close this ticket.
This ain't a solution, is a workaround, an however I'd like to test it for more time.

**Comment by borgmanJeremy** [comment]
Just coming back to this now. Is there more for flameshot to do here? It seems like an upstream gtk issue.

**Comment by MR-Diamond** [comment]
I'm puzzled: such issue is back despite the modification of `~/.config/gtk-3.0/settings.ini`
I don't know if is a GTK issue, because as I've stated previously:

> However: flameshot is using qt5 as backend, and other applications which are using qt5 as backend doesn't shows such behaviour (like, eg, VLC or QBittorrent).

**Comment by veracioux** [comment]
Hey, can you please check if the newest master (233c765b1fa82a2bfd92cfd7bfbb324464165efb) helps with this issue. You can compile it or download from [here](https://flameshot.org/docs/installation/development-build).

**Comment by MR-Diamond** [comment]
The issue is gone, but now the icon on the system tray no longer appears and so I can no longer access to settings; furthermore the setting file (`~/.config/flameshot/flameshot.ini`) is empty (0 byte).
I can only access to the settings by executing `flameshot config` in a Terminal window.

**Comment by snide** [comment]
Came across this issue. Can confirm that building from master resolves the issue and uses the correct theme. Can also confirm that building from master does not show the tray icon as it used to.

TY for building such a wonderful program.

**Comment by veracioux** [comment]
@snide Can you post your config?

**Comment by mmahmoudian** [comment]
@snide @veracioux the tray icon not showing is probably because the `flameshot gui` have been used without having the daemon running, so Flameshot opens and do what it does and then its process terminates.

**Comment by veracioux** [comment]
@MR-Diamond @snide To elaborate further on what @mmahmoudian said, the recent versions of flameshot (including the v11 beta that's currently up) don't need the daemon to run in order to take screenshots. Therefore `flameshot gui` will not auto-launch the daemon, because it doesn't have to. The daemon will only be launched if you:
1. pin a screenshot to the screen (because it must persist somehow even after the `flameshot gui` command exits)
2. copy the screenshot to the clipboard on Linux using X11, because the clipboard must be hosted by a running application or otherwise it will be gone

Of course, you can manually run the daemon if you prefer to interact with flameshot via the systray icon or for whatever reason :D

The `autoCloseIdleDaemon` option is useful if you want the daemon to be running only if it is necessary for the above two actions to work, and to be auto-closed otherwise.

**Comment by snide** [comment]
Yep. Confirmed. It works perfectly fine without the tray, and folks can still get to settings from the settings overlay that shows when you take a screenshot. Mostly just figured I'd comment on the issue so you can close it.

I'm using arch with gtk3, setting qt5 with `export QT_QPA_PLATFORMTHEME="gtk2"`

Again, ty for building / contributing to such a fantastic lib.

**Comment by MR-Diamond** [comment]
> The daemon will only be launched if you:
> 
>     1. pin a screenshot to the screen (because it must persist somehow even after the `flameshot gui` command exits)
> 
>     2. copy the screenshot to the clipboard on Linux using X11, because the clipboard must be hosted by a running application or otherwise it will be gone

I'm fine with this behaviour; so this ticket can be closed 👍️

**Comment by mmahmoudian** [comment]
@snide @MR-Diamond I myself load the daemon on startup as I like to have the icon in the tray area. The good thing is now users can choose and have it according to their preference.

Let us know if you have any suggestions for the improvement of the software.
