### ISSUE TITLE
[Feature Request] Being able to add programs as icons and if you click them it opens the selected area in that program

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1250]
So what I mean is that you can add a program,then the icon of the program will be displayed in a purple circle and if you press that,the selected area will be opened in that program.
I also want that you can add multiple programs.
That would be handy if you wanna open a photo directly in gimp or your printing program or whatever.

**Comment by borgmanJeremy** [comment]
Since we already have the button for "open with" I don't think we will be adding this.

**Comment by Toadfield** [comment]
What does that button?
I mean can I add programs to there?

**Comment by borgmanJeremy** [comment]
Yeah it should see all programs with a .desktop entry. The programs it brings up are not hard coded.

**Comment by borgmanJeremy** [comment]
![Peek 2021-02-18 19-35](https://user-images.githubusercontent.com/46930769/108444609-963c8280-7220-11eb-9f21-9d09ad540127.gif)

**Comment by Toadfield** [comment]
ok
