### ISSUE TITLE
shortcuts to select pencil, rectangle and others not working

### ISSUE THREAD

**Issue by zhangfuwen** [flameshot-org/flameshot#1252]
**Flameshot version**

v0.8.5

**Describe the bug**

In the ReadMe file, there is a shortcut table which says that a user can press P to select pencil and D to set line as paint tool. When I captured an area and press P or D, nothing happens.

**To Reproduce**

start capure, select an area, press P or shift P

**Expected behavior**

press P than  I should be able to draw on the capture area. 
but the cursor remains a hand drag shape and when I click and move, dragging happens instead of drawing .

**System Information**

Ubuntu 20.04.1 LTS with Budge Desktop.

**Comment by borgmanJeremy** [comment]
Sorry for the confusion, those new hot keys are only available on master branch and will be released in the 0.9 series.
