### ISSUE TITLE
"Unable to capture screen" error when attempting to screenshot on SwayWM (with Wayland).

### ISSUE THREAD

**Issue by LiterallyJohnny** [flameshot-org/flameshot#1254]
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.1
**Describe the bug**

I used to use i3wm, and I decided to give Sway and Wayland a shot today. I copied most of my i3wm config to the Sway config.

Whenever I attempt to take a screenshot, I get an error saying "Unable to capture screen" as a Dunst notification. I would provide a screenshot, but... You know.
**To Reproduce**

1. Switch to Sway/Wayland.
2. Copy i3wm config file to Sway config file.
3. Attempt to take a screenshot by pressing `Print`.

**Expected behavior**

The GUI should open and I should be able to take a screenshot, just like on i3wm.

**System Information**

- I am using Arch Linux (Rolling release).
- I am using SwayWM and Wayland, coming from i3wm and Xorg.

- [i3wm config file](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/i3/config)
- [Sway config file](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/sway/config)
- [Flameshot config file](https://github.com/LiterallyJohnny/Dotfiles/blob/main/configs/flameshot/flameshot.ini)

**Comment by borgmanJeremy** [comment]
Sway is not currently supported. There is no "standard" Wayland API for getting raw screen contents. Therefore we need to add a special hook for every Wayland implementation.  See this section of the code: https://github.com/flameshot-org/flameshot/blob/97c195452293fb16a3015eb4f4dd44e80893f5dd/src/utils/screengrabber.cpp#L52

BTW if you do more research it will appear that wayland has a standard screenshot API, but see #446  for why this doesnt work for our use case. 

It's not currently on my queue of work, but if you implement it and test it I'll merge a PR.

**Comment by LiterallyJohnny** [comment]
Ah, alright. I unfortunately know how to implement it, so I'll be switching to a different screenshot program for now. However, I'll look into it to see if I can implement it here, since I enjoyed using Flameshot on X.

**Comment by tmccombs** [comment]
> It's not currently on my queue of work, but if you implement it and test it I'll merge a PR.

I have a little bit of familiarity with wlroots, I could take a stab at implementing this.

**Comment by borgmanJeremy** [comment]
Someone else actually just merged it so it's available on master.
