### ISSUE TITLE
Calculation feature doesn't work (or I don't know how to use it)

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#1255]
Flameshot version
Flameshot v0.8.5-1(Debian)
Compiled with Qt 5.14.2

loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11

Describe the bug
Nothing happens when I click on "measure" icon.

To Reproduce
Click on "measure" icon.

Expected behavior
?

System Information
5.7.17-1rodete4-amd64 #1 SMP Debian 5.7.17-1rodete4 (2020-10-01) x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/1093841/105579141-47b8d700-5d8d-11eb-892e-84d495f5a12c.png)

**Comment by borgmanJeremy** [comment]
It's a little bit confusing, but the numbers shown (407x259) are the current dimensions.

**Comment by elad2109** [comment]
it doesn't measure length between two points on the screen? (roller)
