### ISSUE TITLE
Questions and ideas

### ISSUE THREAD

**Issue by ttamttam** [flameshot-org/flameshot#1256]
Hello,

I have several suggestions for flameshot:

- I sometime have to start it from command line with a delay in order to give myself a delay to preset the screen in the configuration I want to capture: it would be nice if the delay would be a config parameter that could also be set from the side panel
- I sometime perform several screenshots on the same rectangular area: would be nice if the custom rectangle could be specified as a cli command line option as a first step, and as a configuration in the side panel? It would allow to speed up a lot those series of screenshot (for those kind of captures, I currently have to switch to ksnip).

Great simple tool!

**Comment by borgmanJeremy** [comment]
>I sometime have to start it from command line with a delay in order to give myself a delay to preset the screen in the configuration I want to capture: it would be nice if the delay would be a config parameter that could also be set from the side panel.

Instead of the side panel if you click the tray icon to bring the menu up you can select "Open Launcher". This has an option for a delay. 

> I sometime perform several screenshots on the same rectangular area: would be nice if the custom rectangle could be specified as a cli command line option as a first step, and as a configuration in the side panel? It would allow to speed up a lot those series of screenshot (for those kind of captures, I currently have to switch to ksnip).

I think this one is a duplicate of #1137. 

Let me know if you those two things close this issue. Thanks for the great feedback.

**Comment by ttamttam** [comment]
Thanks for your kind answer.

About point 1: thanks for the information. Sorry for the noise: I don’t have yet this option, because I’m using version Flameshot 0.6.0-11(Debian). I’ll give it a try.

About point 2: it is *not a duplicate* of #1137. The idea is not really multi-shot (but I’m not 100% sure about that: maybe the two features can be merged into one). It would be a "perform a new shot with the same rectangular area".

Best regards.

**Comment by mmahmoudian** [comment]
I believe the second point is more related to #479 and #558

Regarding your first point, imho adding the delay in config is not a good idea as everything that goes into config is supposed to be a permanent behavioural change, meaning the user almost always wants to use that setting. I myself use the delay screenshot frequently (either through the launcher or `sleep 5; flameshot gui`) but I still think it is a setting that should be set temporarily and therefore should be done without changing the config.

**Comment by ttamttam** [comment]
Thanks for pointing those. Closing this one, which is more noise than helping. Sorry for that.

**Comment by mmahmoudian** [comment]
We don't think of issues as "noise" or disturbing thing. I actually am glad that you posted these. I cannot speak on others behalf, but every time such ideas and questions are posted they make me think which part of the documentation is not clear of what features are more requested.

If either or both of those issues I mentioned are addressing your feature request, please give them a thumbs up so that we know they are popular, also if you have anything to add to that idea, just leave a comment there.

Thanks for spending your time and contributing 👍🏼
