### ISSUE TITLE
"Copy URL after upload" is missing in 0.8.5

### ISSUE THREAD

**Issue by adem4ik** [flameshot-org/flameshot#1264]
**Flameshot version**
0.8.5 from here https://github.com/flameshot-org/flameshot/actions/runs/521056406

**Describe the bug**

"Copy URL after upload" option is missing in Configuration. 
![image](https://user-images.githubusercontent.com/4707112/106316916-f033d300-6286-11eb-842b-c16c7ae4e456.png)

**To Reproduce**

- Start Flameshot
- Open Configuration/General

**Expected behavior**

"Copy URL after upload" option is available

**System Information**

Windows 10 x64 20H2

**Comment by sonulohani** [comment]
This is removed. Alternatively you can use **Upload selection to imgur** . Please refer the screenshot

![image](https://user-images.githubusercontent.com/2958681/106549023-234fbe00-6536-11eb-92bc-50ae4e0cc93e.png)

**Comment by adem4ik** [comment]
Thanks for reply. I'll stick to 0.8.4 then.

I like that "Copy URL after upload" in 0.8.4 - it makes my work faster. In 0.8.5 it needs one more mouse click to get URL copied into clipboard.
