### ISSUE TITLE
1-click selection area border

### ISSUE THREAD

**Issue by daftada** [flameshot-org/flameshot#1265]
The ability to quickly add a border to the area selection, to allow delineation when pasting the selection to a document of the same colour.

**Comment by mmahmoudian** [comment]
Possible duplicate of #690

**Comment by daftada** [comment]
Sorry for the tardy reply. Yes, this is the same.

**Comment by mmahmoudian** [comment]
@daftada no worries, then I mark it as duplicate of #690.
