### ISSUE TITLE
Flameshot doesn't open after installing from flathub on Clear Linux

### ISSUE THREAD

**Issue by alaasalama** [flameshot-org/flameshot#1266]
**Flameshot version**
0.8.5

**Describe the bug**

I just followed the official guide here: 
https://clearlinux.org/software/flathub/flameshot

And I got that result after trying to run the app:
```
Gtk-Message: 00:25:40.215: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:25:40.215: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
```

**System Information**

Clear Linux OS; Build ID: 34220

**Comment by borgmanJeremy** [comment]
I suspect the issue is a missing gnome extension: https://github.com/flameshot-org/flameshot#tray-icon

**Comment by alaasalama** [comment]
@borgmanJeremy you are right, I've just installed this extension:
https://extensions.gnome.org/extension/1503/tray-icons/

And Flameshot worked! I'm going to close this issue, thank you!

**Comment by rafakwolf** [comment]
seeing this issue on ZorinOS 16.3
and I have the tray icons extension installed

```
❯ flatpak run org.flameshot.Flameshot      
Gtk-Message: 12:12:59.049: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:12:59.049: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
```
