### ISSUE TITLE
Move tool to move text added in screenshot

### ISSUE THREAD

**Issue by sonulohani** [flameshot-org/flameshot#1267]
**Is your feature request related to a problem?**

Sometimes I would want to move text around to some pixel which is difficult/impossible as tool doesn't support the moving of the text. I would like move action(by using mouse) to be added for the text area when it is in focus.

**Comment by sonulohani** [comment]
I am working on this enhancement. Thank you.

**Comment by sonulohani** [comment]
This feature is supported in flameshot, hence closing this issue. 

![move_support](https://user-images.githubusercontent.com/2958681/107869573-a6b5cb80-6eb5-11eb-898b-f6cb74f023f4.gif)

**Comment by mmahmoudian** [comment]
Related to #272

**Comment by prof7bit** [comment]
Somehow I fail to see that any text is moved in the above screencast :-/
