### ISSUE TITLE
Need spin box for active thickness for text

### ISSUE THREAD

**Issue by sonulohani** [flameshot-org/flameshot#1268]
**Is your feature request related to a problem?**

Currently **active thickness** for text is controlled by using QSlider. However QSlider is ineffective as if I want to increase the text size to only 1-2 pixels that is very difficult due to precision and the current implementation of slider which is very small and even a single slide makes text very small/big and with the use of touch-pad, it is near to impossible. I would like to suggest adding QSpinBox as well for precision.

**Comment by sonulohani** [comment]
I could use mouse wheel though for precise adjustment though there is an issue with mouse scroll (https://github.com/flameshot-org/flameshot/issues/1270). But the issue with touchpad use still there. I think this functionality could be optional.

**Comment by mmahmoudian** [comment]
There has been some suggestions (#1003 & #792) to add +/- buttons to the tools in order to facilitate this for users that cannot use scroll (e.g tablet users). As far as I can remember, the final decision was that the +/- buttons should be disabled by default but the user should be able to toggle them on via settings. And based on #1003 we have a working prototype.

**Comment by borgmanJeremy** [comment]
Is this an issue on the master branch? Or just 0.8.5? 

I think I merged in some content from the namecheap fork recently that is supposed to help with touch-pad.

**Comment by sonulohani** [comment]
Actually with two finger scroll on touch-pad, I could able to adjust the **active thickness**. You may close this issue. 

> Is this an issue on the master branch? Or just 0.8.5?
> 
> I think I merged in some content from the namecheap fork recently that is supposed to help with touch-pad.

Nope, the spinbox is not available in the master for **active thickness**.
