### ISSUE TITLE
Scrolling through QSlider doesn't update the value

### ISSUE THREAD

**Issue by sonulohani** [flameshot-org/flameshot#1270]
**Flameshot version**
0.8.5

**Describe the bug**
If I change the value of **Active thickness** using mouse scroll. the value doesn't get updated. Only by moving the slider through mouse click is working. After thorough testing, I see the problem is with all sliders. 

**To Reproduce**
Please see the below gif:
![bug](https://user-images.githubusercontent.com/2958681/106412158-08654700-646d-11eb-9730-2a611a07efa0.gif)

**Expected behavior**
The **active thickness** value should get changed.

**System Information**
Linux mint 20.1

**Comment by sonulohani** [comment]
Could you please assign this issue to me, if you agree that this is the issue in the tool.

**Comment by mmahmoudian** [comment]
I cannot assign this to you as your account doesn't show up in the list. It is either because I use the GitHub phone app or because your account is not listed as a developer in the repo. This is something that I should check with desktop, but regardless of this, you can investigate this and create a PullRequest if/when you find the solution.

Consider this issue as assigned to you, unless @borgmanJeremy and @Martin-Eckleben who have already investigated this in #1003 have some idea/suggestion.

**Comment by sonulohani** [comment]
> I'm not sure if i understood what the bug is. Doesn't the scroll work in general or it only doesn't work when you are hovering your mouse on the slider on the sidebar? I should check it out on my desktop, but for me the scroll works fine in Manjaro KDE.
> 
> I cannot assign this to you as your account doesn't show up in the list. It is either because I use the GitHub phone app or because your account is not listed as a developer in the repo. This is something that I should check with desktop, but regardless of this, you can investigate this and create a PullRequest if/when you find the solution.
> 
> Consider this issue as assigned to you, unless @borgmanJeremy and @Martin-Eckleben who have already investigated this in #1003 have some idea/suggestion.
> 
> 
> 
> 
> 

Just do mouse scroll while hovering over the slider and increase/decrease the value of the slider, you will not see any update on the thickness.

**Comment by mmahmoudian** [comment]
@sonulohani I just checked on KDE, you are right, nice catch 👍🏼 , normal scrolling works but scrolling over the slider do move the slider but does not apply the new value to the text. This is not specific to text tool though, it is universal. I think that part is not yet implemented. In case you want to implement this, please create a PR and reference this issue in your PR description.
