### ISSUE TITLE
base64 images for embedding

### ISSUE THREAD

**Issue by kaihendry** [flameshot-org/flameshot#1274]
Be cool to take a screenshot and have the option to turn it into a base64 encoded string.

    <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

**Comment by borgmanJeremy** [comment]
Can you generate this using the "raw" cli option?

```
flameshot gui -r | base64
```
