### ISSUE TITLE
Support Uguu instances alongside Imgur

### ISSUE THREAD

**Issue by btdmaster** [flameshot-org/flameshot#1275]
Support configurable use of [Uguu](https://github.com/nokonoko/Uguu) [instances](https://status.uguu.se/clones.html) instead of Imgur to allow for less privacy issues when sharing images (not requiring JavaScript, more user-centric Terms of Service).
General syntax to upload is documented in the [API](https://github.com/nokonoko/Uguu#api), but what is most important is being able to pick any instance and parsing the URL to provide it to the user.

**Comment by borgmanJeremy** [comment]
On #955 we are discussing the best API for this. We will likely implement something similar to ShareX.
