### ISSUE TITLE
Arch Linux package not up-to-date.

### ISSUE THREAD

**Issue by LiterallyJohnny** [flameshot-org/flameshot#1276]
**Is your feature request related to a problem?**

The Flameshot package on the Arch Linux official repo doesn't have the latest update, the one that has Sway/Wayland support. Is it possible to get the latest package on the Arch Linux repos?

**Comment by borgmanJeremy** [comment]
You will need to open this request with the Arch Linux maintainers. They likely will not update the main flameshot package until we tag a new release.

In the meantime you can use the flameshot-git package from the AUR. It may not be up to date with the latest github commit, but you can bug the maintainer to update it or manually edit the PKGCONFIG.
