### ISSUE TITLE
Flameshot crash when copy to clipboard with gui editor

### ISSUE THREAD

**Issue by shoshtari** [flameshot-org/flameshot#1277]
**Describe the bug**

Hi
i try use flameshot to copy to clipboard but it freeze and i can't do anything! so i kill it from another tty and try to do it one more time but there was no change. i can work with the terminal commands and this command: `flameshot full -c` executed without any problem

**System Information**
`flameshot --version`
Flameshot v0.8.5
Compiled with Qt 5.15.1
`lsb_release -a`
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

and using i3

**Comment by mmahmoudian** [comment]
@shoshtari make sure you have notification manager (e.g `dunst`) installed.

One way to check is to do `notify-send "Hello World"`

**Comment by shoshtari** [comment]
when i use kde the `notify-send` command work properly and also i not have this problem. 
but in i3, the command executed without any error but there is no output too.
how can i get it to work in i3?

**Comment by mmahmoudian** [comment]
KDE has its own notification manager. In tiling window manager you usually need to install yours. Install [`dunst`](https://wiki.archlinux.org/index.php/Dunst)
