### ISSUE TITLE
Flameshot does not show in Task Bar in Ubuntu 20.10

### ISSUE THREAD

**Issue by jamshaid120** [flameshot-org/flameshot#1280]
Monitors: 1
 0: +*eDP-1 1920/344x1080/193+0+0  eDP-1

Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.01*+  60.01    59.97    59.96    59.93    47.10  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32 

**Flameshot version**
Flameshot v0.8.3-2(Debian)
Compiled with Qt 5.14.2

**To Reproduce**
Install it on Ubuntu 20.10, it does not show the icon in the taskbar

**System Information**
Linux jamshaid 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by borgmanJeremy** [comment]
Please make sure you have the correct gnome extensions: https://github.com/flameshot-org/flameshot#tray-icon

**Comment by jamshaid120** [comment]
I run the following commands and reinstalled flameshot from apt. But the problem still presist.
`# Compile-time
apt install g++ cmake build-essential qt5-default qttools5-dev-tools libqt5svg5-dev qttools5-dev

# Run-time
apt install libqt5dbus5 libqt5network5 libqt5core5a libqt5widgets5 libqt5gui5 libqt5svg5`

**Comment by theonlydoo** [comment]
@jamshaid120 like mentionned in https://github.com/flameshot-org/flameshot/issues/1280#issuecomment-774221295 do you have the correct extension?

**Comment by jamshaid120** [comment]
> @jamshaid120 like mentionned in [#1280 (comment)](https://github.com/flameshot-org/flameshot/issues/1280#issuecomment-774221295) do you have the correct extension?
I am having the following versions. Which meets the requirements
`jamoo@jamshaid:~$ qmake --version
QMake version 3.1
Using Qt version 5.14.2 in /usr/lib/x86_64-linux-gnu
jamoo@jamshaid:~$ gcc -version 
gcc: error: unrecognized command-line option ‘-version’
gcc: fatal error: no input files
compilation terminated.
jamoo@jamshaid:~$ gcc --version 
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jamoo@jamshaid:~$ cmake --version 
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
`

**Comment by theonlydoo** [comment]
i think there was a misunderstanding; we were asking about "gnome extension" :-) check out the comment: https://github.com/flameshot-org/flameshot/issues/1280#issuecomment-774221295

**Comment by jamshaid120** [comment]
> i think there was a misunderstanding; we were asking about "gnome extension" :-) check out the comment: [#1280 (comment)](https://github.com/flameshot-org/flameshot/issues/1280#issuecomment-774221295)


sudo apt install gnome-shell-extension-appindicator
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    gnome-shell-extension-appindicator is already the newest version (34-1).
    gnome-shell-extension-appindicator set to manually installed.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by theonlydoo** [comment]
As a matter of fact, you should not use your distro's version of those packages, [as they are sometimes outdated](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases), [try to use this one instead](https://extensions.gnome.org/extension/615/appindicator-support/). Maybe try to remove `gnome-shell-extension-appindicator` package, and try to install the one provided by gnome itself. 

side note: You maybe should also consider using words, phrases and politeness when reporting a bug on a **free** and opensource software.

Feel free to ask again for help if needed.

**Comment by jamshaid120** [comment]
> As a matter of fact, you should not use your distro's version of those packages, [as they are sometimes outdated](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases), [try to use this one instead](https://extensions.gnome.org/extension/615/appindicator-support/). Maybe try to remove `gnome-shell-extension-appindicator` package, and try to install the one provided by gnome itself.
> 
> side note: You maybe should also consider using words, phrases and politeness when reporting a bug on a **free** and opensource software.
> 
> Feel free to ask again for help if needed.

![image](https://user-images.githubusercontent.com/30922803/107359506-93da7a00-6af6-11eb-94aa-fe621314ffbb.png)

I installed it but it shows like this

**Comment by theonlydoo** [comment]
do you even have icons then? you should have something like this: 
![image](https://user-images.githubusercontent.com/1903124/107364878-4f41e500-6adc-11eb-92dd-4805f1805af5.png)

**Comment by jamshaid120** [comment]
> do you even have icons then? you should have something like this:
> ![image](https://user-images.githubusercontent.com/1903124/107364878-4f41e500-6adc-11eb-92dd-4805f1805af5.png)

Yes. I have my icons here. 
![image](https://user-images.githubusercontent.com/30922803/107366081-84136380-6aff-11eb-8718-d390e982f815.png)

**Comment by mmahmoudian** [comment]
@jamshaid120 did you took the screenshot of your Gnome tray icons using Flameshot? The reason I'm asking this to know/make sure you are also running Flameshot as if you don't you should not see the tray icon.

**Comment by jamshaid120** [comment]
> @jamshaid120 did you took the screenshot of your Gnome tray icons using Flameshot? The reason I'm asking this to know/make sure you are also running Flameshot as if you don't you should not see the tray icon.

The flameshot is running as well. I took this screenshot using another tool. Here is the screenshot with Flameshot.
![image](https://user-images.githubusercontent.com/30922803/107507375-4a0a9600-6bc1-11eb-96a0-77a06ac4d38d.png)

**Comment by borgmanJeremy** [comment]
Can you post your config file from ~/.config/flameshot

**Comment by jamshaid120** [comment]
> Can you post your config file from ~/.config/flameshot



> Can you post your config file from ~/.config/flameshot

`[General]
copyAndCloseAfterUpload=true
disabledTrayIcon=false
drawColor=#725d9c
drawThickness=9
saveAfterCopy=false
saveAfterCopyPath=/home/jamoo/Pictures
savePath=/home/jamoo/Desktop/Shared/screenshots
startupLaunch=true`

**Comment by sliddjur** [comment]
I have Ubuntu 20.04 and Gnome. 
I also dont see a tray icon. I tried apt-version `Version: 0.6.0+git20191001-2` and snap version `v0.8.5+git10.376a6f2`

But none of them gets the tray icon any more.
Currently I have snap version, and these are my settings: (`~/.config/flameshot` doesn't exist`)

![image](https://user-images.githubusercontent.com/10002057/108044618-cb8b7980-7042-11eb-8340-dec0e1ba1588.png)

- I can launch flameshot via `flameshot gui`, or settings via `flameshot config` but still no tray icon.
- I see `/snap/flameshot/6/usr/bin/flameshot` process is running with my $USER
- I have tray icons from other apps 
- ![image](https://user-images.githubusercontent.com/10002057/108044858-13aa9c00-7043-11eb-8cef-eedb38e3c483.png)
- When logging into my session, I get this in dmesg
`[301880.902721] audit: type=1400 audit(1613467092.512:253): apparmor="DENIED" operation="exec" profile="snap.flameshot.flameshot" name="/usr/bin/whoami" pid=794009 comm="flameshot" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0`

**Comment by mmahmoudian** [comment]
@sliddjur would you please try the AppImage as well:


```sh
# make sure no instance of flameshot is running
pkill flameshot

# download the AppImage
wget https://github.com/flameshot-org/flameshot/releases/download/v0.8.5/Flameshot-0.8.5.x86_64.AppImage

# make the AppImage executable
chmod +x Flameshot-0.8.5.x86_64.AppImage

# run the AppImage
./Flameshot-0.8.5.x86_64.AppImage 
```

**Comment by borgmanJeremy** [comment]
I just tested in a clean 20.10 virtual machine with a snap install and I see the icon fine. I suggest comparing your setup to a clean 20.10 install. There must be some extension or alteration you made that is affecting it.

![image](https://user-images.githubusercontent.com/46930769/108078436-4c427980-7033-11eb-854f-99a6f455f0f5.png)

**Comment by sliddjur** [comment]
> @sliddjur would you please try the AppImage as well:
> 
> ```shell
> # make sure no instance of flameshot is running
> pkill flameshot
> 
> # download the AppImage
> wget https://github.com/flameshot-org/flameshot/releases/download/v0.8.5/Flameshot-0.8.5.x86_64.AppImage
> 
> # make the AppImage executable
> chmod +x Flameshot-0.8.5.x86_64.AppImage
> 
> # run the AppImage
> ./Flameshot-0.8.5.x86_64.AppImage 
> ```

Yes, I started appimage, and now it is running in in menu bar, until I press ctrl+c to kill process.

**Comment by mmahmoudian** [comment]
@borgmanJeremy considering [what @ZetaoYang mentioned on Slack](https://flameshotworkspace.slack.com/archives/C019W6EPYMN/p1613643688034100), is it possible that because the icon image is not getting found, the gnome extension is refusing to show the icon?

**Comment by jamshaid120** [comment]
I installed the snap version and it worked. Why didn't it work with apt version?

**Comment by mmahmoudian** [comment]
Glad it was resolved, even miraculously!

**Comment by sliddjur** [comment]
@mmahmoudian I installed `flameshot  v0.9.0.rc2+git20.2b0184a ` from snap edge channel, and now I get task bar icon in gnome again on ubuntu login.
