### ISSUE TITLE
Extra warning displayed when invoking "flameshot -h" or "--help"

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1286]
**Flameshot version**
Git HEAD: https://github.com/flameshot-org/flameshot/commit/c63b161025d5640f0a9b1adf70ae288f492d0652

**Describe the bug**

```
% ./src/flameshot --help
QString::arg: Argument missing: ] ./src/flameshot

, flameshot
QString::arg: Argument missing: ] ./src/flameshot

, [arguments]
Usage: %1 [%2-options] ./src/flameshot

Per default runs Flameshot in the background and adds a tray icon for configuration.

Options:
  -h, --help     Displays this help
  -v, --version  Displays version information

Arguments:
  gui            Start a manual capture in GUI mode.
  screen         Capture a single screen.
  full           Capture the entire desktop.
  launcher       Open the capture launcher.
  config         Configure flameshot.
```

Obviously all output before the "Usage: " line should now show up.

* * *

Downstream bug: https://bugs.debian.org/972720

**Comment by ZetaoYang** [comment]
I confirmed that there are problems with both parameters `flameshot -h` and `flameshot --help` in Ubuntu 20.04 v0.8.5,
![image](https://user-images.githubusercontent.com/10769951/107164394-cd718f00-69e9-11eb-8fb0-958df0ac2d9b.png)
![image](https://user-images.githubusercontent.com/10769951/107164402-d5c9ca00-69e9-11eb-84ce-38322914d352.png)
![image](https://user-images.githubusercontent.com/10769951/107164416-e37f4f80-69e9-11eb-964e-7eaca0731577.png)
