### ISSUE TITLE
Upload targets

### ISSUE THREAD

**Issue by theonlydoo** [flameshot-org/flameshot#1288]
# This feature request is not related to a problem

Related to https://github.com/flameshot-org/flameshot/issues/45, it'd be nice to have "more than imgur/nextcloud", like dropbox/googledrive/sftp

# Secondary request
Also, an url shortener like bitly/yourls would be nice to make URLs nice again :-)

**Comment by borgmanJeremy** [comment]
Close as duplicate of #955
