### ISSUE TITLE
Question: how would put flags on the executable for MacOS

### ISSUE THREAD

**Issue by dat-insanity** [flameshot-org/flameshot#1292]
I would like to pass the -r flag to the application. For example, how would i perform `flameshot gui -r | python3 file.py` to the flameshot app in MacOS.

Thanks in advance!

**Comment by mmahmoudian** [comment]
I think I don't understand the question, because these work for me:

```sh
# for ImageMagic
flameshot gui -r | display

# for feh
flameshot gui -r | feh -
```

**Comment by borgmanJeremy** [comment]
Closed due to no response.

I believe on mac this should just work on the terminal the same as linux.

**Comment by hosiet** [comment]
@borgmanJeremy  I don't have a macOS environment but this issue might should be reopened.

See:

https://github.com/flameshot-org/flameshot/blob/ebdb3743dd6a8e82f4393df3f3dda4210ce4d2d8/src/main.cpp#L127-L130

It seems that the command line arguments are not parsed on macOS at all. Again I don't have any environment for testing but it seems to be the case from code logic.

**Comment by mmahmoudian** [comment]
@hosiet nice catch 👍🏼 I also thought that on OSX it should work.

**Comment by erickhavel** [comment]
Subscribing... I wanted to try this out on MacOS but haven't figured out a way to launch Flameshot with a custom keyboard shortcut since `/Applications/flameshot.app/Contents/MacOS/flameshot gui` doesn't do anything.

**Comment by mmahmoudian** [comment]
@erickhavel I think the issue you have is not related to this issue. I suggest opening a new issue and provide detailed information.

**Comment by MatanRubin** [comment]
Same for me, running `/Applications/flameshot.app/Contents/MacOS/flameshot gui` (or any other subcommand) does nothing on macOS.
