### ISSUE TITLE
flameshot v0.8.5+git10.376a6f2 does not have a taskbar icon

### ISSUE THREAD

**Issue by tawmoto** [flameshot-org/flameshot#1293]
I installed it via snap and when i run it, it does not have an icon in the taskbar.

I am running Xubuntu 18.04.

![image](https://user-images.githubusercontent.com/35702340/107380771-d7cd7f00-6af6-11eb-9f51-5025b4cbbd78.png)

thanks

**Comment by corndog2000** [comment]
This might be similar to #1280 .

**Comment by borgmanJeremy** [comment]
It works fine for me in a clean Xubuntu 18.04 VM. 
![image](https://user-images.githubusercontent.com/46930769/108089003-bad90480-703e-11eb-8555-3fa6f6fa0019.png)

Have you made any gnome extension tweaks?

**Comment by mmahmoudian** [comment]
@borgmanJeremy it has happened to me on KDE (I never use Gnome). I don't remember which installation method I used. I will try to find which one it was.

**Comment by borgmanJeremy** [comment]
Weird, I mostly use KDE as well and haven't had the issue.

**Comment by borgmanJeremy** [comment]
@tawmoto Is the issue still there for you on the 0.9 release? Are you sure in the settings you have not disabled to tray icon? Config file can be found at ~/.config/flameshot/flameshot.ini

**Comment by tawmoto** [comment]
> @tawmoto Is the issue still there for you on the 0.9 release? Are you sure in the settings you have not disabled to tray icon? Config file can be found at ~/.config/flameshot/flameshot.ini

Sorry I dropped flameshot in favour of gnome default screenshot app, it's simpler and just works. I tried 2 times to use flameshot, one last year and now and I got problems in the first minute. I am sure that it's a great app but I don't have the patience to investigate it further.
Thanks for your help.
