### ISSUE TITLE
Being able to change text size (and possibly colour) in annotations

### ISSUE THREAD

**Issue by SonephetR2** [flameshot-org/flameshot#1294]
Awesome application :) Today, I ran into an issue regarding font size in annotations however. It currently cannot seemingly be changed in the GUI or config and in my case text size is really quite small for some reason (see attached).

Adding an option to the config interface, or even better when actually using flameshot gui (more case-by-case), would make Flameshot even more powerful.

![Screenshot 210209-181303](https://user-images.githubusercontent.com/47414122/107401260-f9ccfe80-6b02-11eb-9e47-947083902d0b.png)

**Comment by borgmanJeremy** [comment]
If you hit spacebar it will open a side menu that allows you to adjust the font.

**Comment by SonephetR2** [comment]
Oh, my bad!! Thanks a lot! I should've RTFM instead of relying on external write-ups.

**Comment by borgmanJeremy** [comment]
No problem :)
