### ISSUE TITLE
Regression: Rectangle tool now makes an ellipse if started from bottom-right, non-rectangular shapes from bottom-left and top-right, and rectangle only from top-left

### ISSUE THREAD

**Issue by AlexFolland** [flameshot-org/flameshot#1295]
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.2

This is `flameshot-git` from the AUR, and I have this git information copied from RabbitVCS log in my pamac build cache:

Revision: f24bae0
Author: Boyuan Yang
Date: 2021-02-08 10:34:26
CMakeLists.txt: Add option to use external spdlog library (#1290)

**Describe the bug**

The rectangle tool now makes an ellipse if started from the bottom-right, a non-rectangular shape if started from the bottom-left or top-right, and only makes a rectangle shape if started from the top-left.  Here's a demonstration, with rectangles started from the 4 possible corners:

![image](https://user-images.githubusercontent.com/601517/107450521-46f8a280-6afa-11eb-94ba-c9941c245bd8.png)

**To Reproduce**

1. Start a screenshot with Flameshot.
2. Select the rectangle tool.
3. Create 4 rectangles: one from each possible starting corner.

**Expected behavior**

The rectangle tool is expected to always make a rectangle, regardless of the starting corner.

**System Information**

Manjaro XFCE Nibia 20.2.1

**Comment by borgmanJeremy** [comment]
This bug was introduced in the PR with this commit: b1edf99be113523466da0edc5aba8187c1c230e2

seems like the rounded corner feature is not working as intended.
