### ISSUE TITLE
Make it possible to always save to disk

### ISSUE THREAD

**Issue by roelvanduijnhoven** [flameshot-org/flameshot#1297]
My usual flow when using this awesome tool involves copying a screenshot to the clipboard, and directly pasting it somewhere else. However now I have been doing that for a while, I notice that I miss those screenshots that I made a lot! Previously I would have them in a folder on my machine, but now the pictures folder remains empty!

My suggestion: add a command line option go `gui` that will always save the image to a folder, when you _use_ it in some way. I.e.: when you press ENTER and copy to the clipboard, we also save to disk.

Proposal for interface:

```
flameshot gui -p ~/Pictures --always-save-to-disk
```

Would this be something that would be merged, if I create a PR for this?

**Comment by corndog2000** [comment]
@roelvanduijnhoven Have you tried the GUI setting "Save image after copy"?

**Comment by roelvanduijnhoven** [comment]
@corndog2000 Sorry! I did not realize I was not on the latest version. But Ubuntu 20.04 run 0.6.x. Now build from source, and .. this is exactly what I want :D :partying_face: .

Thanks a bunch, and sorry, I was unaware that I was not running latest and greatest.
