### ISSUE TITLE
Apple Silicon M1 support

### ISSUE THREAD

**Issue by merrcury** [flameshot-org/flameshot#1302]
When can we expect native support of flameshot for Apple Silicon Processors?

**Comment by borgmanJeremy** [comment]
When someone donates one 😝 In all seriousness when someone with an M1 wants to do the code contribution and testing is when support will be added. 


I also  don't know the state of Qt on M1s

**Comment by ZetaoYang** [comment]
https://bugreports.qt.io/browse/QTBUG-85279

**Comment by merrcury** [comment]
> Qt 6.2 will support Apple Silicon (arm64). https://bugreports.qt.io/browse/QTBUG-85279

That's sweet.

**Comment by sam0delkin** [comment]
for those who concern, i was able to compile flameshot for M1. Looks like brew is already have an ARM formula for qt@5: https://formulae.brew.sh/formula/qt@5 so, i just used the script from README.md:
```
brew install qt5
brew install cmake
mkdir build
cd build
cmake ../
make
```

note, that i was need to use `CMAKE_PREFIX_PATH` to set a correct path to qt5 that was installed by homebrew

**Comment by petrukngantuk** [comment]
how can I help to make this  released to the release page ?

**Comment by borgmanJeremy** [comment]
You will need to update the CI scripts

**Comment by mmahmoudian** [comment]
@petrukngantuk we use Github Actions to build the Flameshot for different platforms. You can find all our scripts here:

https://github.com/flameshot-org/flameshot/.github/workflows

**Comment by petrukngantuk** [comment]
well after some digging, the issue was the github actions workflows still not support macos arm64 arch,
I can help with building it using self hosted runner, but it's quite tricky and not long term solution, wdyt ?

**Comment by ZetaoYang** [comment]
> 
> 
> well after some digging, the issue was the github actions workflows still not support macos arm64 arch,
> I can help with building it using self hosted runner, but it's quite tricky and not long term solution, wdyt ?

Is it possible to cross-compile on Intel-based Macs (x86_64)?

**Comment by borgmanJeremy** [comment]
I think maybe we could move the Mac build to TravisCI if it's still free for FOSS

**Comment by ZetaoYang** [comment]
About Qt official release,
[Qt 5.15.4](https://wiki.qt.io/Qt_5.15_Release#Qt_5.15_LTS_Commercial_Releases) support MacOS Big Sur ARM64, but you must have a commercial license. 

[The article](https://www.qt.io/blog/qt-on-apple-silicon) mentions "Some patches already went into Qt 5, so Qt 5.15.4 and above should build and run by passing -device-option QMAKE_APPLE_DEVICE_ARCHS=arm64 to configure. Note that this configuration is not tested in CI, and is hence unsupported at this point."

The community version will not support MacOS ARM64 and Windows ARM64 until Qt6.2.  https://wiki.qt.io/New_Features_in_Qt_6.2

Most CI platforms currently do not have a MacOS ARM64 environment. Therefore, there are only two ways left:
1. use QEMU to emulate MacOS ARM64, this approach is difficult as far as QEMU is concerned. Although some people have successfully tried it out, it is still very complicated. see https://blogs.blackberry.com/en/2021/05/strong-arming-with-macos-adventures-in-cross-platform-emulation and https://github.com/cylance/macos-arm64-emulation
2. cross-compile, which should be feasible. Using [osxcross](https://github.com/tpoechtrager/osxcross) should work, successful case https://github.com/bitcoin/bitcoin/issues/20371#issuecomment-871090816. But of course you need to cross-compile the source code of Qt 5.15.2(need spply some patches, Available at https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt@5.rb). 

Plus,
The native compiled ARM64 version can be found here. 
>brew install qt@5
>brew install cmake
>mkdir build
>cd build
>cmake ../
>make

There is also a [macdeployqt-universal](https://github.com/crystalidea/macdeployqt-universal) tool that can be used.

**Comment by ZetaoYang** [comment]
@mmahmoudian @borgmanJeremy Qt 6.2 LTS released. https://www.qt.io/blog/qt-6.2-lts-released 
it's mentioned at Qt blog,
> Qt 6.2 fully supports macOS on Apple Silicon. Qt now makes it easy to create universal binaries and to develop for macOS on both Intel and Apple Silicon. Of course, that version is also fully tested in our CI system. It has always been possible to run Qt applications on Apple silicon via the Rosetta layer, but Qt 6.2 now provides full support to run natively on the Apple silicon.

**Comment by petrukngantuk** [comment]
Any plan to upgrade to Qt 6.2 shortly?

**Comment by borgmanJeremy** [comment]
It's not in our plan for the upcoming release. Perhaps the release after that?

**Comment by borgmanJeremy** [comment]
I ended up getting an M1 air and the lastest master branch is working perfectly on it, it did not require an upgrade to qt6.2. The only thing to figure out is if we need to update the CI.

**Comment by asyba** [comment]
> I ended up getting an M1 air and the lastest master branch is working perfectly on it, it did not require an upgrade to qt6.2. The only thing to figure out is if we need to update the CI.

strange for me, when i opened the app is not doing anything, no errors and not opening.

**Comment by borgmanJeremy** [comment]
Did you try compiling from source?

**Comment by asyba** [comment]
> Did you try compiling from source?

no, just with the dmg file from this github repo https://github.com/flameshot-org/flameshot/releases

**Comment by borgmanJeremy** [comment]
Okay that goes back to needing to update the CI so it builds a package for aarch64 in addition to x86. I think if you build from source it will work.

**Comment by kholisrag** [comment]
I tried many approach to do cross-compile in qt5,
but no luck for success, always got a problem when it linking the binary, maybe lack of knowledge from myself how to properly crosscompile qt5

you can check it out [here](https://github.com/kholisrag/flameshot/actions/workflows/MacOS-pack.yml)

**Comment by borgmanJeremy** [comment]
Maybe this helps? https://github.com/crystalidea/macdeployqt-universal

**Comment by kholisrag** [comment]
> Maybe this helps? https://github.com/crystalidea/macdeployqt-universal
> 
> Edit: Why do you uninstall qt@5 with brew before building? I think the problem is cmake is looking there for the qt tools used in generating the MOC files.

will try to look at that universal macdeployqt
I just realized that there is hardcoded `brew --prefix` in the ~2/3 place in cmakelist.txt, and its make custom qt5 installation directory path not working as expected and will try to depend my understanding about cmake first

**Comment by borgmanJeremy** [comment]
Since flameshot is working perfectly fine on Rosetta I am going to close this.

**Comment by realityworks** [comment]
@borgmanJeremy why are you closing this when Apple Silicon M1 support is still not native to bitcoin core... :/

**Comment by borgmanJeremy** [comment]
Because I don't intend to work on this. It is running fine on Rosetta.

If someone else can figure out how to build a universal image in our CI I'll happily merge that, but don't have time to work this when their is no real value.

**Comment by sybercorp** [comment]
> Because I don't intend to work on this. It is running fine on Rosetta.
> 
> If someone else can figure out how to build a universal image in our CI I'll happily merge that, but don't have time to work this when their is no real value.

Functioning in Rosetta is one thing, but by not running natively it causes additional power draw from the system, especially when the helper is running in the background constantly.  So, the "real value" is having the system perform better and not draining the battery as fast.  For heavy users, that drain may be more of an issue than it is for the occasional/casual user.

**Comment by mmahmoudian** [comment]
> especially when the helper is running in the background constantly

You can invoke Flameshot in a one-off mode (explained in the release notes of v11.0.0) which will remove the background process as soon as Flameshot is closed.

Regarding the M1, it would be nice if some of you can work on it and add M1 support to this Free and Libre OpenSource Software. Any form of contribution is most welcome 🤗

**Comment by rylincoln** [comment]
Although _nice_ to have - in my experience running flameshot under rosetta works flawlessly and does not noticeably impact energy consumption on an M1 device. (chrome however does a lot ... 😄  )
![image](https://user-images.githubusercontent.com/741887/159943335-2bd77ab1-d377-4cd1-a72c-d07e462f4f0c.png)

**Comment by muthusk** [comment]
Looks like recently [Public Beta of M1 Mac runners for Github actions](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/.) were made available.   Would this help in getting flameshot for Mac M1s natively without having to use rosetta? @borgmanJeremy

**Comment by msavdert** [comment]
that would be great

+1
