### ISSUE TITLE
Best Screenshot Tool Award

### ISSUE THREAD

**Issue by eknowlton** [flameshot-org/flameshot#1303]
Saw you on Hacker News.

Replaced all my screenshot tools with Flameshot. Amazing work. 
Wish I could show my appreciation with money.

**Comment by borgmanJeremy** [comment]
Thanks! Just found the thread on hacker news. We are planning on another release this weekend that actually addresses many of the questions in the thread.

**Comment by ZetaoYang** [comment]
Here's the hn news link https://news.ycombinator.com/item?id=26113753
