### ISSUE TITLE
Feature request 2of2: take snapshot /then/ open the edit toolbar + and include a filename textbox

### ISSUE THREAD

**Issue by canDry** [flameshot-org/flameshot#1305]
Quite often I'm doing a screenshot of something dynamic on the screen (a changing compile screen) and need the shot to happen quickly.  
  
Could there be an option to take the snapshot /then/ present the image taken with the editing toolbar to allow annotations?  
  
Also, to reduce steps to save the file, add a filename textbox on the edit toolbar.  By changing the field (filename) and pressing <ENTER> it will then save the image.  
  
Cheers!

**Comment by mmahmoudian** [comment]
I don't understand this part of your feature request:

> Could there be an option to take the snapshot /then/ present the image taken with the editing toolbar to allow annotations?

Would you please elaborate more. Even adding gifs, hand drawing, video, etc. Can sometimes help to convey the message.

**Comment by mmahmoudian** [comment]
Considering that we haven't heard back from you for 3 months, I'm closing this issue, but before that I want to provide a solution:

It seems you can do `flameshot full -p ~/myStuff/captures` (bind it to a keyboard shortcut) to take quick screenshot and save it to your disk. You can then open the image in any image viewer (e.g `sxiv` or `feh`) in fullscreen mode and use `flameshot gui` to take a screenshot from that image with the annotations you need.
