### ISSUE TITLE
Instructions for adding KDE shortcuts don't work

### ISSUE THREAD

**Issue by dandv** [flameshot-org/flameshot#1306]
**Flameshot version**
0.6.0+git20191002-2(Debian)

**Describe the bug**
I've followed [the instructions to import the shortcuts file for KDE Plasma](https://github.com/flameshot-org/flameshot/blob/master/README.md#on-kde-plasma-desktop), but none of the shortcuts work (<kbd>Print</kbd>, <kbd>Ctrl+Print</kbd>).

![image](https://user-images.githubusercontent.com/33569/107845825-9ea93f00-6d82-11eb-870f-2a344deae2fb.png)

![image](https://user-images.githubusercontent.com/33569/107845834-af59b500-6d82-11eb-84ee-e3dcb7517505.png)

Other custom shortcuts do work in KDE (e.g. I have Ctrl+Alt+P to launch Pinta).

**System Information**
Kubuntu 20.4, Plasma 5.18.5.

**Comment by borgmanJeremy** [comment]
Can you please test using a newer version of flameshot? We are no longer supporting 0.6. In fact 0.9 is going to be released shortly.

**Comment by ZurMaD** [comment]
![image](https://user-images.githubusercontent.com/28235457/107857596-2fbcfc00-6dfd-11eb-8e9b-879a7fbe24be.png)

**Comment by dandv** [comment]
> Can you please test using a newer version of flameshot? We are no longer supporting 0.6.

Sorry, 0.6 is the one in the Ubuntu repos.

0.8 works as it should!
