### ISSUE TITLE
flameshot crashes wayland on fedora

### ISSUE THREAD

**Issue by zany130** [flameshot-org/flameshot#1314]
**Flameshot version**

0.8.5-1.fc33

**Describe the bug**
flame shot crashes Wayland on fedora and requires a reboot to get back on desktop.

**To Reproduce**

launch flame shot launcher in wayland
**Expected behavior**

flame shot launcher opens and lets me take a screenshot
**System Information**
 Fedora 33 Gnome.
https://linux-hardware.org/?probe=28fab5c03d

**Comment by borgmanJeremy** [comment]
We have a version coming out in the next day or so that will significantly improve wayland performance. You can build it from the master branch or a wait a few days for the 0.9 release.

**Comment by zany130** [comment]
still crashes on latest master

**Comment by borgmanJeremy** [comment]
Hrmmm. I frequently test on Fedora33 and do not have this issue. Could you help provide more details on how it crashes or the steps to take to make it crash?

Have you done any strange customization?

**Comment by zany130** [comment]
I just installed and ran ```flameshot launcher ``` in the terminal and the whole wayland server crashes I get a black screenj and then I am thrown into the login screen. where trying to login throws me back into the login after a black the link above shows the specs of my system and some logs. which basicly show all hell broke lose when I ran that command and wayland and a bunch of other apps just core-dumped

**Comment by zany130** [comment]
[flameshot-crash.log](https://github.com/flameshot-org/flameshot/files/5978638/flameshot-crash.log)

**Comment by borgmanJeremy** [comment]
Can you list your gnome extensions so I can test against the same ones? In a fully up to date Fedora33 VM I an unable to replicate it. I tested with both 1 and 2 virtual displays.

**Comment by zany130** [comment]
yes it was actually due to a gnome extension in fact it was the blur shell extension. it was not only crashing flame shot but any other screenshot tool I just uninstalled it as I don't really use it but I plan to send a bug report anyway

**Comment by borgmanJeremy** [comment]
Awesome thanks for reporting back!
