### ISSUE TITLE
Are PNG images under data/img/material/{black,white}/ dir useless?

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1316]
It seems that there are both the SVG version and the PNG version of icons under `data/img/meterial/{black,white}/` directories. However, it seems that the buildsystem (CMake) is only using the svg icons. Does that indicate that the PNG icons are redundant and should be deleted?

**Comment by borgmanJeremy** [comment]
They might be unused. It's unclear to me what they were ever for. Have you tried removing them and seeing if there is a difference?

**Comment by hosiet** [comment]
Looks like those PNG files are indeed not needed and removing them triggers no difference. Please consider removing them in the next release.

**Comment by hosiet** [comment]
Hmmm maybe we can just finish it within v0.9.0 release cycle? Saying "next release" I was actually referring v0.9.0. This is a very trivial task and there's no reason for pontponing.

**Comment by borgmanJeremy** [comment]
Sure, can you submit a PR? I'm pretty busy with other flameshot tasks in my limited free time.
