### ISSUE TITLE
Window CI fails with Releace Candidate Tag

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1319]
@ZetaoYang Is there a good way to modify the workflow file or cmake file so when I create a release candidate tag the pipeline does not fail?

The issue is CMake only uses Major/ Minor/Patch versions like 0.9.0. When I create a release candidate I use a tag with RC in it like 0.9.0.rc1. This causes the .exe and .zip files to not match what the CI is looking for.

**Comment by ZetaoYang** [comment]
My solution was to rename the win packages according to the git tag version information.
