### ISSUE TITLE
Cursor disappears *sometimes* while using flameshot gui

### ISSUE THREAD

**Issue by j0lol** [flameshot-org/flameshot#1320]
**Flameshot version**

0.8.3-2
**Describe the bug**

Sometimes when using `flameshot gui` my cursor will disappear and will make the screenshot tool practically unusable. Seemingly random chance of happening while screenshotting. Can show for a small amount of time and disappear. Seems to happen repeatedly once it starts happening. Restarting flameshot does not seem to help.
**To Reproduce**

Call `flameshot gui`
**Expected behavior**

Cursor should show with + icon.
**System Information**

OS: Pop!_OS 20.10 x86_64 
Kernel: 5.8.17 
DE: GNOME 3.38.2 
WM: Mutter 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce GTX 770 + NVIDIA GeForce GTX 1060 6GB
Memory: 16022MiB 
Resolution: 1920x1080 + 1920x1080

**Comment by borgmanJeremy** [comment]
By "cursor", do you mean the crosshair target used to select a region?

**Comment by j0lol** [comment]
yes the + shaped target for drawing a region to screenshot

**Comment by j0lol** [comment]
update: this seems to happen to me consistently, it works the first time i start it but never after
i think this could be an issue with gnome? i dont have the same problem on a diff system with Plasma DE installed

**Comment by borgmanJeremy** [comment]
Ive spent some time testing this in a pop 20.10 VM and I cannot replicate it.

**Comment by j0lol** [comment]
weird, i guess ill close it then? maybe my systems just broken in some way

**Comment by borgmanJeremy** [comment]
If you can figure out the trigger for the behavior be sure to let us know. and we can dig into it.

**Comment by twinpigs** [comment]
In Fedora 34 with GNOME 40 cursor is invisible permanently.

**Comment by vishnudevk** [comment]
Fedora 34 with GNOME 40 cursor is invisible permanently.

vishnudev@fedora  Wayland

OS: Fedora 34 (Workstation Edition) x86_64 
Host: MacBookPro8,2 1.0 
Kernel: 5.12.8-300.fc34.x86_64 
Uptime: 1 hour 
Shell: bash 5.1.0 
Resolution: 1920x1080 
DE: GNOME 40.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-2675QM (8) @ 3.100GHz 
GPU: Intel 2nd Generation Core Processor F 
GPU: AMD ATI Radeon HD 6630M/6650M/6750M/7 
Memory: 5280MiB / 15914MiB

**Comment by mmahmoudian** [comment]
@vishnudevk @twinpigs considering that this is Wayland-specific and even Gnome wayland, I suggest opening a new issue.

**Comment by twinpigs** [comment]
Done https://github.com/flameshot-org/flameshot/issues/1659

**Comment by luixal** [comment]
As I've posted in #1659 I think is **not** a wayland-specific issue. I'm having the same problem on X11 too using gnome 41.

**Comment by azzamsa** [comment]
I still got the issue in my system.

![image](https://user-images.githubusercontent.com/17734314/175476429-30ea0945-a38d-46fe-b808-2484087ed3b4.png)

```
OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-15-amd64
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Memory: 12162644 kB
Emacs version: GNU Emacs 29.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2022-01-06
```

```
~ 
❯ flameshot --version
Flameshot v12.0.0 ()
Compiled with Qt 5.15.2
```

Any solution for this?

**Comment by Dzordzu** [comment]
In my case it was the wrong xcursors theme. Fixed by `swaymsg seat seat0 xcursor_theme Adwaita`
