### ISSUE TITLE
ENABLE_OPENSSL flag detection should be more fine-grained

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1321]
When building the 0.9.0 rc1 source code on Linux platform, I noticed that there is a warning saying that "OpenSSL is required to upload screenshots". This does not seem to make sense since not enabling the flag does not affect image uploading in imgur.

I am wondering if this flag is only meaningful on Microsoft Windows platform. If so, the check should only appear when Windows environment is detected.

**Comment by borgmanJeremy** [comment]
I agree this could use some cleanup. However SSL is required to link against on linux. My guess is this is handled by QT Networking on Linux? I need to do more research.

You can see that libssl is loaded on linux even when the CMAKE flag is disabled. 

```
$ ldd src/flameshot | grep ssl
libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f4abff33000)
```

@thepurple I believe you added this code. Any preference on how we address this?

**Comment by hosiet** [comment]
This is indeed handled by system Qt. Most Qt in Linux distributions enabled openssl. If they did not enable it, we cannot control it either.

**Comment by borgmanJeremy** [comment]
Sounds good, I agree with your proposal to move the check to windows only unless @thepurple  has a different suggestion.
