### ISSUE TITLE
Flameshot is always activated on one screen when 2 screens are aligned in parallel

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1322]
**Flameshot version**
v0.9.0rc1

**Describe the bug**
When starting flameshot v0.9.0 to capture screen on a dual-monitor environment, only one of the screens is darkened (in my case the left monitor `#2` ), no matter where my mouse cursor is.

Detailed monitor alignment:

![图片](https://user-images.githubusercontent.com/8443926/107891592-ae916200-6eed-11eb-827f-32b20de003be.png)

This bug did not appear on v0.8.5. I consider it a regression.

**To Reproduce**
* Set up a dual-monitor environment side by side
* Install flameshot v0.9.0rc1
* Run /usr/bin/flameshot
* Open flameshot launcher and drag it into the certain screen where screenshot is needed
* Click the screenshot button inside the launcher

**Expected behavior**
All the screens should be covered in dark by flameshot and the screenshot should be able to be taken from both screens. (v0.8.5 behavior)

**System Information**
Debian Sid/Unstable
Flameshot v0.9.0-rc1
GNOME 3.38 + Xorg (NOT wayland)

**Comment by borgmanJeremy** [comment]
@hosiet I agree, thanks for reporting this. After bisecting the source this was added in: 77c509e7989b924d31d54e78c6f8e7a7e68968b9

If we cant fix it I can just rollback this patch.

**Comment by borgmanJeremy** [comment]
@jfly can you investigate if this is fixable or if we need to roll the change back?

**Comment by jfly** [comment]
Oh darn, I don't have a clue how to go about fixing this. We should probably roll back, and can investigate a fix without this broken for people?

**Comment by borgmanJeremy** [comment]
@jfly Sure I can roll it back before the release next weekend so we don't have to rush to fix it.

**Comment by AtjonTV** [comment]
I can confirm the same issue on rc1 build on Gentoo Linux ;D

**Comment by AlexFolland** [comment]
I am seeing this with `flameshot-git` from the AUR on Manjaro XFCE.

**Comment by UltraBlackLinux** [comment]
I'm facing the same issue on wayland again: ![2022-02-12_11-16](https://user-images.githubusercontent.com/62404294/153707222-51ef27c6-1e5e-4c1b-9d9f-717a3077bc14.png)
I captured this on my right screen, but it captured my left screen with a tiny part of my right screen
