### ISSUE TITLE
Undo doesn't work for 

### ISSUE THREAD

**Issue by Eldrior** [flameshot-org/flameshot#1334]
Flameshot version 0.9.0 Compiled with Qt 5.15.2
MacOS 10.15.7

If I use the selection or rectangle tool and use the undo function, both are not undone but stay completely or in parts on the screen. If I copy the screenshot to my clipboard the lines are visible as well. 
I can only recreate that with the lowest "Active thickness". 

![Bildschirmfoto 2021-02-16 um 20 02 54](https://user-images.githubusercontent.com/7557576/108109355-07016480-7092-11eb-9662-129086860c3d.png)

**Comment by borgmanJeremy** [comment]
Confirmed on linux too. Only with thinnest setting.

**Comment by borgmanJeremy** [comment]
Issue was added with rounded rectangles in b1edf
