### ISSUE TITLE
Overview Shortcuts does not work properly

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1339]
**Flameshot version**
Git version, commit 67952f06abb7261b5862428f2b1ee76fd7b008af 

**Describe the bug**
In the Settings -> Shortcuts are always the default values shown when you open it and not the correct shortcuts.

**To Reproduce**
Go to Settings -> Shortcuts, change there e.g. the shortcut for Pen. Default is the key "P". Change the shortcut to e.g. "CTRL+ALT+P", close the dialog, go back to the settings and instead of "CTRL+ALT+P" it says "P" again, but internally Flameshot works with "CTRL+ALT+P".

**System Information**
Arch Linux, Xfce

**Comment by thepurple** [comment]
I can reproduce it too, will fix it.

**Comment by thepurple** [comment]
fixed: https://github.com/flameshot-org/flameshot/pull/1340

**Comment by kpcee** [comment]
Just tested it and it works, great! 
Found another bug though. Go to reset in the settings and close the dialog. Then go back to Settings → Shortcuts, then all shortcuts are gone! Tested with version commit 3649379a00735ce4e02096f984cec215340e8e4c.

**Comment by thepurple** [comment]
@kpcee 
If you'll restart Flameshot all default hotkeys will be back, but anyway, it's a bug, you're right.
That's another issue, please create it.

**Comment by kpcee** [comment]
Hmm, I guess I didn't test carefully enough but in the current version it is no longer possible to reset the shortcuts to default. Now the user-defined shortcuts are always preserved. 
Git commit 16fd3b2915829ccb550a023d7b829b7a46beebde.

**Comment by thepurple** [comment]
@kpcee 
Yes, you're right.
In general there should be another key on the related tab, it looks like feature request, not a bug.
I hadn't enough time to implement it, you can create a feature request for this feature.
Currently you can reset shortcuts by removing section "[Shortcuts]" in the **flameshot.ini** file and restart **Flameshot**. Usually it is located at **${HOME}/.config/flameshot/flameshot.ini**.

**Comment by kpcee** [comment]
If it's a feature and not a bug, then it's okay. ;)
