### ISSUE TITLE
AppImage fails to execute

### ISSUE THREAD

**Issue by MichaelTunnell** [flameshot-org/flameshot#134]
I really like the idea of this tool and I like the AppImage usage but when I tested the AppImage here are the errors I received on Ubuntu 16.04 (KDE Neon technically).

`QXcbConnection: XCB error: 9 (BadDrawable), sequence: 277, resource id: 92274694, major code: 55 (CreateGC), minor code: 0`

`QXcbConnection: XCB error: 9 (BadDrawable), sequence: 278, resource id: 92274694, major code: 130 (Unknown), minor code: 3`

**Comment by ZetaoYang** [comment]
@MichaelTunnell This looks like a known Qt bug: https://bugreports.qt.io/browse/QTBUG-31389 - should be fixed in Qt 5.5.0.
Currently appimage is compiled using Qt 5.3.2.

**Comment by luzpaz** [comment]
Has the Appimage Qt version been updated ?

**Comment by ZetaoYang** [comment]
AppImage building has been trasfered to https://github.com/flameshotapp/packages.
Qt version was upgrade to 5.6.1, built on Ubuntu 16.04
