### ISSUE TITLE
Reset settings removes all shortcuts

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1347]
Git version (commit 3649379a00735ce4e02096f984cec215340e8e4c)
Go to reset in the settings and close the dialog. Then go back to Settings → Shortcuts, then all shortcuts are gone!

Arch Linux, Xfce

**Comment by borgmanJeremy** [comment]
Confirmed this is still present after the large namecheap merge. Thanks for reporting.

**Comment by thepurple** [comment]
I've fixed it, will send a PR soon

**Comment by borgmanJeremy** [comment]
Oh ok great! thanks for letting me know I just started looking into it.

**Comment by thepurple** [comment]
PR: https://github.com/flameshot-org/flameshot/pull/1352
