### ISSUE TITLE
Changing the Save Path does not work

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1348]
Git version (commit 3649379a00735ce4e02096f984cec215340e8e4c )
If you try to change the Save Path in the settings, you can select it in a file dialog, but it is not applied. It remains with the default value `/home/$USER/Pictures`

Arch Linux, Xfce

**Comment by thepurple** [comment]
This one is fixed in the big PR https://github.com/flameshot-org/flameshot/pull/1338

File: src/config/geneneralconf.cpp → src/config/generalconf.cpp 
Line 423
chooseFolder(path);	->    path = chooseFolder(path);

**Comment by thepurple** [comment]
@kpcee if you have a free time please test PR https://github.com/flameshot-org/flameshot/pull/1338
It has a lot of small fixes like this and some new features. I hope it will be merged into the master soon.

**Comment by kpcee** [comment]
I compiled the branch origin/nc_0_8_5_10 and the bug is fixed, however many other things were changed. Whole 38 commits which were not taken over yet, so I'd better wait until that happens, so that bugs that have already been fixed are not posted here unnecessarily.

**Comment by borgmanJeremy** [comment]
Merged #1338
