### ISSUE TITLE
Disabling Autostart not possible after resetting settings

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1351]
Autostart is generally enabled, but disabling it can cause problems if you reset the settings.

To follow up:
* Autostart is enabled
* Click on reset settings
* Deactivate Autostart, now click on another checkbox, Autostart activates itself again, repeat this ... Autostart cannot be deactivated and the file "Flameshot.desktop" is not deleted either. 
* To disable Autostart you have to click Autostart 3 times until the checkbox behaves normally again. 

Compiled Git version with latest changes (commit 66c9f67626b7d339894ca7cea91806178d84ed91) 
Arch Linux

**Comment by borgmanJeremy** [comment]
Thanks for reporting this I can confirm it.

I love when you test flameshot, you find great bugs :)

**Comment by kpcee** [comment]
Wow thanks :)
