### ISSUE TITLE
The frequency in which the configuration file is saved

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1359]
This is not a real bug and maybe too insignificant to address the problem. Flameshot uses QSettings directly for saving its variables, which means that changes are saved immediately to disk at smallest changes. A click with the left mouse button on the tray icon causes e.g. the configuration file to be saved at least 2x, a click on a checkbox also causes a save, moving the Opacity slider can cause dozens of saves, the same is true when editing a screenshot. Changing the thickness with the mouse wheel triggers a save every time the value changes, with every step, just like all other changes made there and saved in QSettings. 

Since the configuration file is smaller than 1000 bytes, it is not noticeable and probably not really significant, but I wanted to mention it anyway.

**Comment by thepurple** [comment]
It's really insignificant, just a few settings are updating during the normal work of Flameshot, I would say that it's just "drawColor". And even that value is not updated too often in real cases. All other settings are updated very rarely. 
Reading is not a problem at all, it is cached on different levels quite well.

**Comment by borgmanJeremy** [comment]
Yeah i agree that its pretty insignificant given all the other overhead of the system.

**Comment by kpcee** [comment]
I don't know if the problem has gotten worse but as it is now, it's really not good. Even if it is only a 1000 bytes file. But as soon as you open the settings dialog the configuration file "flameshot.ini" is saved several times per second, even if you change absolutely nothing in the settings!

https://user-images.githubusercontent.com/39984895/109301097-b6c79680-7837-11eb-8870-01531d5ba7c4.mp4

**Comment by borgmanJeremy** [comment]
I haven't been able to replicate this. I set up a watch with inotify:  inotifywait -mr --timefmt '%H:%M' --format '%T %w %e %f' flameshot

Was this on your XFCE arch box? I tried on KDE arch, but I can repeat the testing in a VM. 

![inotify](https://user-images.githubusercontent.com/46930769/109684467-e7644480-7b45-11eb-9ff9-7d6a03feb064.gif)

**Comment by borgmanJeremy** [comment]
@kpcee Can you post your flameshot.ini file? maybe it is specific to your config file.

**Comment by kpcee** [comment]
I downloaded the current git version and can't reproduce the bug here, but if you go back to commit 5705e45e32387b3c57514d8150b0a22888d53ddf and test it, Flameshot goes crazy as soon as you enable the autostart option, which is enabled by default. The bug has, where it looks like, already been fixed in the meantime.
