### ISSUE TITLE
Wrong Flameshot Version in the Repo&flatpak

### ISSUE THREAD

**Issue by MrNilDev** [flameshot-org/flameshot#1368]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
```
➜ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2
--------------------------------------
➜ sudo dnf info flameshot   
Last metadata expiration check: 0:27:34 ago on Sat 20 Feb 2021 04:54:49 PM +0330.
Installed Packages
Name         : flameshot
Version      : 0.8.5
Release      : 1.fc33
Architecture : x86_64
Size         : 1.2 M
Source       : flameshot-0.8.5-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Powerful and simple to use screenshot software
URL          : https://github.com/lupoDharkael/flameshot
License      : GPLv3+ and ASL 2.0 and GPLv2 and LGPLv3 and Free Art
Description  : Powerful and simple to use screenshot software with built-in
             : editor with advanced features.
```
**System Information**
I am running Fedora 33, and i3.

**Comment by borgmanJeremy** [comment]
On rc1 or rc2?

**Comment by MrNilDev** [comment]
what is even rc

**Comment by borgmanJeremy** [comment]
Version 0.9.0 is still in beta so we have been releasing it as release candidates (RC).

What methods did you use to install flameshot?

**Comment by MrNilDev** [comment]
`sudo dnf install flameshot` that's all

**Comment by borgmanJeremy** [comment]
Hrmmm seems like fedora packaged our beta release which I would not have wanted.

Who is listed as the package maintainer?

**Comment by MrNilDev** [comment]
1. How can I check that?
2. there is an interesting thing to know
```
➜ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2
--------------------------------------
➜ sudo dnf info flameshot   
[sudo] password for pouridev: 
Last metadata expiration check: 0:27:34 ago on Sat 20 Feb 2021 04:54:49 PM +0330.
Installed Packages
Name         : flameshot
Version      : 0.8.5
Release      : 1.fc33
Architecture : x86_64
Size         : 1.2 M
Source       : flameshot-0.8.5-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Powerful and simple to use screenshot software
URL          : https://github.com/lupoDharkael/flameshot
License      : GPLv3+ and ASL 2.0 and GPLv2 and LGPLv3 and Free Art
Description  : Powerful and simple to use screenshot software with built-in
             : editor with advanced features.
```

**Comment by MrNilDev** [comment]
Still the same result installing with flatpak

**Comment by MrNilDev** [comment]
Ok , now it works but i'm still on this version 
```
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**Comment by T3rminat0r** [comment]
> ➜ sudo dnf info flameshot   
> Last metadata expiration check: 0:27:34 ago on Sat 20 Feb 2021 04:54:49 PM +0330.
> Installed Packages
> Name         : flameshot
> Version      : 0.8.5
> Release      : 1.fc33
> Architecture : x86_64
> Size         : 1.2 M
> Source       : flameshot-0.8.5-1.fc33.src.rpm
> Repository   : @System
> From repo    : updates
> Summary      : Powerful and simple to use screenshot software
> URL          : https://github.com/lupoDharkael/flameshot

Well, @borgmanJeremy , I guess that might answer who the maintainer listed is? @lupoDharkael ? :)

**Comment by mmahmoudian** [comment]
@borgmanJeremy does this answer your question m:

https://src.fedoraproject.org/rpms/flameshot

I'm not very familiar with fedora as I haven't used the distro for over 10 years. If this is not what you were after, I can invest some time and contact them via IRC.

**Comment by MrNilDev** [comment]
On the arch repositories it's fine, works as expected. Good job new version .9.0

**Comment by mmahmoudian** [comment]
I just checked the Fedora repo and it seems that they are gradually transitioning to v0.9.0 . @MrNilDev Would you please check if the issue has been fixed?

**Comment by jn64** [comment]
`flameshot-0.8.5-1.fc33` was built on 2020-10-15 and could not have contained 0.9.0. Must be user error.

Anyway Fedora packages have been updated to 0.9.0 so it doesn't matter any more.

Package build history https://koji.fedoraproject.org/koji/packageinfo?packageID=26139

**Comment by mmahmoudian** [comment]
@jn64 thanks for the update. I’ll close this issue then.
