### ISSUE TITLE
Localisation is partial/inconsistent (on windows, at least)

### ISSUE THREAD

**Issue by T3rminat0r** [flameshot-org/flameshot#1370]
**Flameshot version**
0.9rc2 win64 msi

**Describe the bug**

The Translation of menus to the system locale is partial/inconsistent: (green = german, red = english, system locale being german)
![image](https://user-images.githubusercontent.com/9053174/108597617-3f52bc80-738a-11eb-82f6-df7060408122.png)
![image](https://user-images.githubusercontent.com/9053174/108597860-72e21680-738b-11eb-98b0-b10100911bd3.png)

**To Reproduce**
Start flameshot on a (windows?) system with a non-english locale

**Expected behavior**
Consistent translation into system locale (and **ideally**, a setting to get a non-systemlocale translation activated, without changing system locale (i.e. settings drop down with selectable locales to pick from, including english. (could potentially even ask this in the installer))

**System Information**
Windows 10 2004, german locale

P.S: if pointed in the right direction, I might be able to help with some German translations :)

**Comment by borgmanJeremy** [comment]
Here are the directions for correcting translations: https://github.com/flameshot-org/translation-instruction

I would really appreciate if you could fix the translation within 1 week, then it will make it into the 0.9 release :)

Thanks!

**Comment by borgmanJeremy** [comment]
BTW the issue happens because when we add a new feature, we don't have a team of translators on "standby" all the translations are a community effort.

**Comment by T3rminat0r** [comment]
See PR #1375
