### ISSUE TITLE
Wrong color shown on color-wheel during a screencapture

### ISSUE THREAD

**Issue by T3rminat0r** [flameshot-org/flameshot#1371]
**Flameshot version**
0.9rc2 (win64, msi)

**Describe the bug**
When capturing (on windows?), and changing the color of the marking tool via rightclick, the highlight of the "current color" always shows the color that was active when starting the current capture, not actually the currently selected color. (it only gets updated after the current/before the next screen capture)
![image](https://user-images.githubusercontent.com/9053174/108598176-66aa8900-738c-11eb-8a32-c4ed3bc2962c.png)
(talking about the lightgreen ring on "green", in this screenshot, it doesn't move to red, if I select red, until I start a new screenshot, after selecting red...)

**To Reproduce**
1. Start a capture
2. change the drawing color via right click to red.
3. right click again, to check which color is selected (and note the green ring is still on green, not red)

**Expected behavior**
The color wheel on right click should always hightlight the currently active color, so the user sees which color the next drawn object will have.
(i.e. in Step 3, the wheel should look like this:  ![image](https://user-images.githubusercontent.com/9053174/108598273-f8b29180-738c-11eb-94bc-c69641e209aa.png) )

**System Information**
Windows 10, 2004, (German locale)

**Comment by T3rminat0r** [comment]
Hmm, did this get lost? or is it known, already?

**Comment by mmahmoudian** [comment]
I can confirm that the issue (ring stock around the initial color) happens on Linux on version 0.9.0 installed through AUR `flameshot-git` .

As one can see, in the first round (drawing rectangles), the ring is around yellow despite of the color change, and in second round (arrows) it is stuck around the blue:

![Peek 2021-03-03 18-35](https://user-images.githubusercontent.com/390889/109839237-993b6800-7c4f-11eb-943a-c734294b6ef6.gif)
