### ISSUE TITLE
0.9.0.rc2 regression on Windows + 2 screen + mixed DPI

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1373]
**Flameshot version**
0.9.0.rc2

**Describe the bug**
I believe the 0.9.0.rc2 release or some earlier changes introduced a regression to the fix of #986 (PR: #1126). Looking at 0.9.0.rc2 tag, the related codeblock is like this:

https://github.com/flameshot-org/flameshot/blob/96cfd440470c5d609dbf22129572f1f184fbb14f/src/widgets/capture/capturewidget.cpp#L109-L122

However according to the PR #1126 , the fix should have been committed before in https://github.com/flameshot-org/flameshot/commit/a0156be7b6e5f032ff2f8ed6671c00b29ab2ae37 .

Running `git blame`, it seems that the regression was introduced in https://github.com/flameshot-org/flameshot/commit/dc7f62ab8d92508971b356b01054d998a0c3b030#diff-2be90f26b81be6188da6c119a948d793df60dcb9c8e0e3118aec2cb8aa0085d3R116 . Since this commit claims to be **fixing an issue on macOS** but the change was made in the **Windows-only code block**, the regression surely was introduced by accident.

**To Reproduce**
Follow the same procedure in #986 .

**Expected behavior**
See #986 .

**System Information**
See #986 .

**Comment by thepurple** [comment]
Sorry for inconvenience, most probably it was me.
I had a big and hard work on merging two quite different code bases (hadn't sync for a long time) with nearly 60-70 commits with MacOS improvements and some other fixes.
Can you please send this fix again, or I'll take a look at it a bit later and fix it.

**Comment by borgmanJeremy** [comment]
@hosiet This was fixed in 12e3c9eb

Can you give the latest master a build?

**Comment by hosiet** [comment]
It seems that the latest build is working. Thanks!

**Comment by borgmanJeremy** [comment]
Awesome thanks for reporting it.
