### ISSUE TITLE
flameshot gui should start flameshot if necessary

### ISSUE THREAD

**Issue by btdmaster** [flameshot-org/flameshot#1376]
This may technically be a duplicate of #90, but I think this specific issue is still not fixed. Currently, in i3, it is necessary to either run with dbus-launch or run the flameshot daemon manually before flameshot gui. The former seems excessive and the latter is, at best, a hack. Could this specific feature be reconsidered?

**Comment by borgmanJeremy** [comment]
Flameshot GUI will start flameshot as long as dbus is working right?

**Comment by btdmaster** [comment]
As long as i3 is launched with dbus-launch, yes. That seems to work fine on my system, though I have heard various reports of other things breaking or performance crawling to a halt.

**Comment by btdmaster** [comment]
One thing I recently noticed -- all the other commands seem to suffer from the same bug. Though I think flameshot gui is the most important one to fix.

**Comment by borgmanJeremy** [comment]
This is not a bug fyi this is a feature request. It's working as intended. I'd be okay merging in something to allow this to be called without dbus as long as it's not a massive refactor.

**Comment by btdmaster** [comment]
Found the actual issue; when trimming my `.xinitrc`, I removed all the scripts under `/etc/X11/xinit/xinitrc.d/`. I added this back as a fix:
`. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh`
Closing.
