### ISSUE TITLE
Autostart in Windows 10 does not work

### ISSUE THREAD

**Issue by update-freak** [flameshot-org/flameshot#1379]
**Flameshot version**
0.9.0 RC2 Beta Release

**Describe the bug**
The program does not start automatically when Windows 10 is started

**To Reproduce**
Start Windows 10

**Expected behavior**
The program starts automatically when Windows 10 is started (if the corresponding setting is activated)

**System Information**
Windows 10 20H2

**Comment by borgmanJeremy** [comment]
Is this an regression in 0.9 or did 0.8.4 behave the same ?

**Comment by hosiet** [comment]
I took a try and autostart is working on both v0.8.4 and v0.9.0rc2 (Windows 10 20H2).

**Comment by update-freak** [comment]
ok, then it is a wrong configuration in Windows?
Before the Windows app "Cut out and sketch" was installed.

**Comment by pegasusearl** [comment]
I just freshly installed flameshot in Windows 10. Same problem, flameshot does not run on start even if "Launch at startup" is enabled.
```
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10
```

**Comment by plolrt** [comment]
Same problem here, even if I enabled "Launch at startup".

```
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19042
windows: 10
```
