### ISSUE TITLE
dual-monitors, can capture only left half of main monitor

### ISSUE THREAD

**Issue by Qbsoon** [flameshot-org/flameshot#1389]
**Flameshot version**
0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
I have two monitors, set like this:
<img width="248" alt="2021-02-24_10-29" src="https://user-images.githubusercontent.com/29931713/108979738-3e23d700-768b-11eb-9c6e-23a3ac053aac.png">
When I use fullscreen option of screenshot, it screenshots both screens, but if I use the 2nd option, that where I can select area for screenshot, I cannot select anything from my main monitor, I can select only area from second monitor, but second monitor somehow shows on it's right side, left half of my first monitor, and on it's left side, black screen. So I can capture only black screen or something from left half of my main monitor.

**To Reproduce**
Set monitors like I showed on the image, use screenshot option, where you choose the area for the screenshot. (it started to happen after I set monitors like this, when they were set side-by-side, everything worked good)

**Expected behavior**
It should let me choose any portion of main and second screen.

**System Information**
Windows 10 Pro 2004
Build: 19041.804
Windows Feature Experince Pack 120.2212.551.0
Graphics: Palit GeForce GTX 1070 8GB JetStream
Processor: AMD FX-8350
Resolution: Monitor supports 1920x1080, but I have it renderd in 3840x2160 (nvidia DSR functions)

**Comment by mmahmoudian** [comment]
I believe it is related to #1386.

**Comment by Qbsoon** [comment]
> 
> 
> I believe it is related to #1386.

Oh, yes it seems so, I checked that issue, but when I saw that it has problem with language, i exit it and created new issue, didn't read the whole thread of that issue.

**Comment by mmahmoudian** [comment]
@Qbsoon no worries, if @ZetaoYang also believes that these two issues are because of the same internal behaviour, you can later copy parts of this issue and comment it under #1386 as supporting evidence and close this one.

**Comment by ZetaoYang** [comment]
> I believe it is related to #1386.
> 
> @ZetaoYang what do you think?

Yes
