### ISSUE TITLE
MacOS 11.2.1 bug. Windows disappear when taking screenshot

### ISSUE THREAD

**Issue by benjymouse** [flameshot-org/flameshot#1393]
**Flameshot version**
v0.9.0

**Describe the bug**

When I attempt to take screenshots using Mac OS, the active windows all slide away to the left and all I can screenshot is the wallpaper.

![image](https://user-images.githubusercontent.com/78871760/109087461-84a12200-76db-11eb-9dc9-8a4149133420.png)

**To Reproduce**
Click on Flameshot icon
Select Take Screenshot
[screen slides away at this point]

**Expected behavior**
Work as awesomely as it did in the Ubuntu.

**System Information**
Mac OS 11.2.1 Big Sur

**Comment by thepurple** [comment]
You didn't give permissions to the Flameshot for Screen Recording.

* On your Mac, choose Apple menu  > System Preferences, click Security & Privacy, then click Privacy.
* Select Screen Recording.
* Select the checkbox next to an app to allow it to record your screen.

Details: https://support.apple.com/guide/mac-help/control-access-to-screen-recording-on-mac-mchld6aa7d23/mac

**Comment by benjymouse** [comment]
Thanks @thepurple. I tried that but unfortunately it is disabled. :(  

<img width="589" alt="Screen Shot 2021-02-25 at 6 51 28 AM" src="https://user-images.githubusercontent.com/78871760/109149935-33724c00-7736-11eb-9d83-dd3b2a413f37.png">

**Comment by thepurple** [comment]
Click on **Click the lock to make changes** (at bottom left) and set checkbox for the Flameshot **Checked**.

**Comment by benjymouse** [comment]
that was it! You're awesome, thanks for your help @thepurple 

FYI I'm a long term Linux user, reluctantly switching to MacOS. I can't live without Flameshot. Keep up the great work.
