### ISSUE TITLE
Flameshot freezes one minute before let me copy/save images

### ISSUE THREAD

**Issue by krpovmu** [flameshot-org/flameshot#1394]
Hi,
I'm facing a problem with my flameshot installation, the program starts well but when I try to take a screenshot it freeze for 1 minute before let me copy the image same happens when I try to save an image either.
It happens when you click on tray icon appears screen selection you make your selection and edit without problems, but when you try save or copy you click on anyone and flameshot freezes.

Flameshot v0.8.5
Compiled with Qt 5.15.1

System:
  Host: shuma Kernel: 5.9.16-1-MANJARO x86_64 bits: 64 
  Desktop: KDE Plasma 5.20.5 Distro: Manjaro Linux 
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.10 driver: loaded: intel 
  unloaded: modesetting resolution: 1: 1920x1200~60Hz 2: 1600x900~60Hz 
  OpenGL: renderer: Mesa DRI Intel Iris Graphics 5100 (HSW GT3) 
  v: 4.5 Mesa 20.3.4 

Linux shuma 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux

Thanks

**Comment by borgmanJeremy** [comment]
Do you have a notification manager working?

**Comment by krpovmu** [comment]
@borgmanJeremy yes you right sorry for silly question, that was the problem, right now is working really fine

**Comment by mmahmoudian** [comment]
@krpovmu do you use a window manager? I thought you are using KDE, and KDE is shipped with a notification manager

**Comment by krpovmu** [comment]
@mmahmoudian Yes you right but some day I've disabled it because I had a lot of notifications and I needed to concentrate but I forgot enabled it again, Thanks
