### ISSUE TITLE
Windows capture bugs out with dual stacked monitors

### ISSUE THREAD

**Issue by 33Fraise33** [flameshot-org/flameshot#1397]
**Flameshot version**

Flameshot 0.9.0 RC2 Windows 64 MSI

**Describe the bug**

When trying to capture a screenshot on windows my images move to the right so not everything is visible anymore. This only happens when my dual monitors are stacked in windows, with 1 screen or when they are next to each other instead of above each other everything works as expected. 

**To Reproduce**

install 0.9.0RC2 and try to capture a something on a dual monitor setup (both screens above each other)
Result: (captured with windows screen capture tool)
![Screenshot (2)](https://user-images.githubusercontent.com/6802744/109208270-6524fa80-77aa-11eb-8fb0-cc43a39eb523.png)

**Expected behavior**

Everything stays in place and allows me to take a pic. 

**System Information**

Windows 10

**Comment by mmahmoudian** [comment]
I guess your monitors are not from the same size and resolution or they are not perfectly stacked and aligned.

Please also post your monitor alignment and resolutions.

**Comment by 33Fraise33** [comment]
Looks very similar to that issue. My resolution is :
3440x1440p100
1920x1080p60

Profile looks like this: 
![image](https://user-images.githubusercontent.com/6802744/109216957-7a535680-77b5-11eb-8bc9-f3100fc9ad2e.png)

**Comment by mmahmoudian** [comment]
I know that devs are working on it. Would you please close this issue and post the screenshot you posted as supporting material to the #1386.

**Comment by 33Fraise33** [comment]
Done thanks!
