### ISSUE TITLE
Issues with Save as

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1399]
If Flameshot is set to ask for save location and name each time, the following minor bugs exist:
* It cannot be saved as BMP, after selecting BMP it is saved as PNG. (By the way, instead of BMP I would offer the modern WebP as an option, it is afaik the most modern format what Qt currently supports out of the box).

* Cancel save as dialog: Flamesot shows the desktop notification that the file is saved.

* Cancel save as dialog: Flameshot will change the save path in the preferences to ".png".

Latest Git (commit 5705e45e32387b3c57514d8150b0a22888d53ddf )
Arch Linux, Xfce

**Comment by MrNilDev** [comment]
Try giving us some more information or we can not help you with that 
**Flameshot version**
**To Reproduce**
**Expected behavior**
and please keep them separately.

**Comment by kpcee** [comment]
I have written which version I use, even the commit was given. It's all about the save as dialog when it's enabled and is it really necessary to write an "Expected behavior" when it's logical what is meant or what is going wrong?
  
If saving as BMP is not possible, even though there is the option, the "Expected behavior" should be that Flameshot saves as BMP. Likewise, there should be no desktop notification that saving was done when you cancel the save operation, and also the save path in the settings should not be changed to ".png" when you cancel the save operation.

**Comment by hosiet** [comment]
I can confirm that:

* Saving as BMP file is working well on Microsoft Windows (with v0.9.0 release).
* Saving as BMP file is indeed not working on Linux platform **if the user does not explicitly provide the .bmp suffix in the filename**:

1.  If the user choose bmp in the saving dialog and use `my_filename` as file name, the saved file would be of PNG format.
2. If the user choose bmp in the saveing dialog and use `my_filename.bmp` as file name, the saved file would be of BMP format.


This is considered a bug.

**Comment by TomaszPluta** [comment]
Would it be ok to if after choosing a bmp in file save dialog ".bmp" sufix will be added automatically?

**Comment by mmahmoudian** [comment]
@TomaszPluta are you planning to make a PR? If so, it would be nice to have the feature also configurable (auto-extension can be enabled/disabled in config)

**Comment by TomaszPluta** [comment]
I have tested this issue, and I can confirm it is easy to reproduce. Fixing in that way shouldn't take a lot of time, so I could try.
Provide it as config option is good idea and only one thing need clarification - such option should be default enabled or disabled?

**Comment by mmahmoudian** [comment]
I love it when people ask the right question at the right time 👍🏼🤘🏼

In my opinion, it should be enabled by default, as I doubt if anyone even in Linux world is excluding extensions from image files. Plus as far as I know, many tools like ImageMagic, Gimp, and Incscape does such automation filetype detection based on the provided filename.

So my suggestion is:
1. Enable it by default 
2. In the pull request's comment clarify that it is on by default just to help the person who is going to merge it to re-think this before merging.

**Comment by kpcee** [comment]
GIMP does an excellent job here, an additional option in the settings unnecessary. Simply offer the option in the Save As dialog

* By file extension
* PNG
* JPG
* BMP
* (WebP which can later be replaced by JPEG XL or AVIF, depending on what can be officially established as JPEG successor and what is supported by Qt)

The file extension is given by default (maybe save what was used last) and then save in that format. If the suffix and the selection contradict, Gimp will ask what you want to do. So everything is packed into one dialog and also easy to understand.

**Comment by TomaszPluta** [comment]
OK, I have working draft, but one question appears:
What to do in case when  user choose "By file extension" option and dont give any extension? For me no extension should be give. Possibly i could name a fileter "By file extension (default *.png)" and add *.png as so far.

Second case - for me it much simpler to just save file  in chosen format and add extension after closing a window, in a way that user doesn't see added extension when he not add any. Do you concern it as desired to add in GUI, "in real-time" the suffix to entered name? I don't know i made myself clear enough.

**Comment by kpcee** [comment]
Hi TomaszPluta,

I just looked this up in GIMP and if no file extension specified a dialog opens and says to specify a valid extension. This is not so easy to do with Qt as the Save As dialog closes automatically when the user click on Save and stays open in GIMP when the message comes up.

I would suggest to handle this as simple as possible, no complicated things that are changed in real time. ;)  I would therefore generally specify a name in the Save As dialog without file extension, that is easier to implement in any case. The suggestion "By file extension (default *.png)" is great. If the user does not specify an extension or an invalid one, the file would simply be saved as PNG and ".png" is appended to the name.

* If a graphic format would be selected, the file name is completely ignored and the extension of the selected graphic format would be appended to the entered file name and will be saved  in this format.
* If the filename is empty, the saving process would be aborted.
* If the file exists, it would be best to ask whether it should be overwritten, if not call the Save As dialog again.
* I would only save the selected file extension entry in the Save As dialog and restore this setting the next time.

**Comment by TomaszPluta** [comment]
Please review above PR. I tested it many times on Ubuntu, so i think it works as expected, but feel free to test this branch.
The implementation behaves as before in "Win" and "Mac" environments ("#ifdef used in code returns "old" untouched function). Solution is based on some discussion found in internet (it is know issue in QT), so code may look a little bit complicated, but i don't see a simpler way. If you have an idea to simplify a code - please add remars in review.
