### ISSUE TITLE
Add flameshot to scoop package manager

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#1404]
It would be awesome to add Flameshot to scoop.

I've made a request to the scoop-extras bucket, https://github.com/lukesampson/scoop-extras/issues/5631.

**Comment by ZetaoYang** [comment]
Examples: https://github.com/lukesampson/scoop-extras/tree/master/bucket

**Comment by ZetaoYang** [comment]
Examples: https://github.com/lukesampson/scoop-extras/tree/master/bucket

**Comment by 42wim** [comment]
Is it possible to also add a sha256sum for `flameshot_portable-0.9.0-win64.zip` on the releases?

**Comment by ZetaoYang** [comment]
Now flameshot is available in scoop extra bucket, https://github.com/lukesampson/scoop-extras/blob/master/bucket/flameshot.json

**Comment by ZetaoYang** [comment]
> 
> 
> Is it possible to also add a sha256sum for `flameshot_portable-0.9.0-win64.zip` on the releases?
> (and every future release ;-)

@borgmanJeremy
