### ISSUE TITLE
Various bugs in v0.9.0 signed .msi installer

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#1406]
* No flameshot icon in the installer.
* `LICENSE` not provided in the installer. The default "cpack" license placeholder is shown instead.
* Flameshot cannot be found in the Start Menu.
* Manually starting `flameshot.exe` indicates that all Qt-related dll libraries are missing. The program will then crash.
* Software is installed under `C:\Program Files\flameshot 0.9.0\` instead of `C:\Program Files\Flameshot\`.

**Comment by ZetaoYang** [comment]
signed .msi installer and .zip from appveyor CI.

**Comment by borgmanJeremy** [comment]
Sorry I think I know the issue. I didn't find this during my testing because I had previously added qt to the system path. I need to tweak the sign path manifest.

**Comment by borgmanJeremy** [comment]
@ZetaoYang  Can you help me understand how the qt dll's are packaged in the github workflow? I looked through the windows yaml file but I dont understand why the qt dll's are successfully packed on github but not appveyor.

**Comment by ZetaoYang** [comment]
> @ZetaoYang Can you help me understand how the qt dll's are packaged in the github workflow? I looked through the windows yaml file but I dont understand why the qt dll's are successfully packed on github but not appveyor.

In github actions, we use `windeployqt.exe` to find qt dlls, but this is using the `QTDIR` environment variable  `QTDIR: ${{ github.workspace }}\build\Qt\${{ matrix.qt_ver }}\${{ matrix.config.qt_arch_install }}\`. 

![image](https://user-images.githubusercontent.com/10769951/109439743-93d0f880-7a6a-11eb-9102-5405d1d6508c.png)
![image](https://user-images.githubusercontent.com/10769951/109439677-553b3e00-7a6a-11eb-9e80-bfbb412d0ebc.png)

And OpenSSL dlls,
![image](https://user-images.githubusercontent.com/10769951/109439705-684e0e00-7a6a-11eb-9e38-ebcac1fd87e7.png)

However, in appveyor it is `Qt5_INSTALL_DIR` `Qt5_INSTALL_DIR: 'C:\Qt\5.15.2\msvc2019_64'`.
![image](https://user-images.githubusercontent.com/10769951/109439642-2ae98080-7a6a-11eb-99c7-ff7c7d9e16f3.png)

**Comment by borgmanJeremy** [comment]
@hosiet I just uploaded a new binary that looked good to me. Please give it a try and report back if you find further issues.

**Comment by hosiet** [comment]
I think the newly-uploaded msi installer solved all previous issues. Thanks!
