### ISSUE TITLE
Sliding effect when copy/close/etc capture on MacOS BigSur

### ISSUE THREAD

**Issue by danielleontiev** [flameshot-org/flameshot#1410]
**Flameshot version**

0.9.0

**Describe the bug**

1) When screenshot is created, closing the window, copy to clipboard, etc, causes windows to slide, because screenshot is opened in new fullscreen window 
https://imgur.com/a/b1pDDPl
2) Similar effect appears when creating screenshot of some active window but at the beggining of the capture

**To Reproduce**

Take screenshot, select any region, click "copy to clipboard"

**Expected behavior**

Sliding effect should not appear

**System Information**

MacOS BigSur

**Comment by CySpiegel** [comment]
This also happens on Catalina

**Comment by borgmanJeremy** [comment]
I have no idea how we could solve this. I think the operating system is adding the animation

**Comment by yzq-del** [comment]
I meet same problem. ask for help
