### ISSUE TITLE
"copy selection to clipboard" is not working

### ISSUE THREAD

**Issue by bhzhu203** [flameshot-org/flameshot#1413]
**Flameshot version**
❯ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.11.1

**Describe the bug**
After screenshoting , click the copy button , but clipboard is  empty

[message.txt](https://github.com/flameshot-org/flameshot/files/6067333/message.txt)

**To Reproduce**
First click flameshot icon on the tray  , then click the copy button

**Expected behavior**
copying selection to clipboard successfully

**System Information**
linux  LFS

**Comment by borgmanJeremy** [comment]
Linux LFS = Linux from scratch? If so you might want to find a linux distro that is similar to what you set up and see what packages are different.

**Comment by bhzhu203** [comment]
> Linux LFS = Linux from scratch? If so you might want to find a linux distro that is similar to what you set up and see what packages are different.

Compiled in Ubuntu 20.04.2 is working normal. Finally I use root(or other user) privileged  user to run flameshot, it is working ! Solved.

Could I know where (what directory) dose flameshot to write the tmp file for the clipboard ? In the same System (my Linux from scratch system ), the Screencloud is working normally for the clipboard ,but the  flameshot is not working. Thanks

**Comment by bhzhu203** [comment]
I  reproduce the  the issue in the configuration when I select the "Use JPG format for clipboard(PNG default)".

It looks like web based Dingtalk does not support "jpg format for clipboard" ,.But libreoffice supports both jpg and PNG in clipboard

![2021-03-03_19-32](https://user-images.githubusercontent.com/3523160/109800846-add02e00-7c58-11eb-9010-9b8b11afabe8.png)

You can close this issue . Thanks

**Comment by mmahmoudian** [comment]
I'm not sure how the part that Dingtalk does not accept JPG is affecting what is in your clipboard. Regardless, as per your suggestion in your last comment, I'm going to close this issue. Feel free to re-open it if needed.
