### ISSUE TITLE
v0.9.0 Windows CLI Parsing still not working since introduction of Boost Program Options

### ISSUE THREAD

**Issue by Michael-Gibbons** [flameshot-org/flameshot#1417]
**Flameshot version**
0.9.0

**Describe the bug**

According to #988  and #945 Boost Program Options was added for cross platform CLI parsing. However, it does not seem to be working as of v0.9.0

![image](https://user-images.githubusercontent.com/13829417/109769313-431ae600-7bb7-11eb-9581-6a45253245f0.png)

**To Reproduce**

Try to pass in cli information to flameshot.exe in the installation directory.

**Expected behavior**

cli parsing

**System Information**

Windows 10.0.19401 Build 19401

**Comment by hosiet** [comment]
Boost Program Options was still not added for cross platform CLI parsing as of v0.9.0. Flameshot is using neither libboost nor cxxopts as of v0.9.0. We need to solve #945 first.

**Comment by borgmanJeremy** [comment]
Yeah I am going to close this since its not implemented yet. We can track progress on #945
