### ISSUE TITLE
Shared Library Preloading

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#1419]
When I open flameshot for the first time and then take a screenshot (OS: Windows 20H2), those tool buttons below the flameshot screenshot area are very laggy and slow, I hope someone can implement shared library preloading to make the first screenshot process a bit smoother.

**Comment by borgmanJeremy** [comment]
Is shared library preloading something that is supposed to happen at the application level? Or should it be handled by the OS. I have not looked into this before.

**Comment by ZetaoYang** [comment]
Improve the response speed of capturing by automatically reloading dlls periodically.
