### ISSUE TITLE
No hotkeys work for upload to imgur

### ISSUE THREAD

**Issue by FunWithUrban** [flameshot-org/flameshot#1425]
**Flameshot version**
v0.9.0

**System Information**
Kubuntu 20.10

**Describe the bug**
No matter what I set the hotkey to for "upload to imgur" nothing happens. The few others that I have tried work perfectly but even if I change the "upload to imgur" hotkey to something that works elsewhere it still doesnt seem to do anything.

**Comment by mmahmoudian** [comment]
I confirm this bug

**Comment by borgmanJeremy** [comment]
Found the issue, will be merged soon.
