### ISSUE TITLE
Hitting enter doesn't take screenshot

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [flameshot-org/flameshot#1429]
**Flameshot version**

**Describe the bug**
I used to be able to run `flameshot gui` select the area I want to take a screenshot of and hit enter which would take the screenshot and copy it to the clipboard. But this no longer happens I have to manually click the copy button.

**To Reproduce**
Happened after doing an update on Arch

**Expected behavior**
Take the screenshot and copy it to the clipboard.

**System Information**
Arch Linux
i3 wm

**Comment by mmahmoudian** [comment]
Because enter (a.k.a "Return") key is not mapped to copy to clipboard. To copy to clipboard you should press <kbd>Ctrl</kbd>+<kbd>c</kbd> to copy to clipboard.

**Comment by nerdthatnoonelikes** [comment]
Thank you. Ctrl+C works.

**Comment by FichteFoll** [comment]
The help text that shows during a capture that tells to hit "Enter" to capture the selection should probably be updated to reflect the configured shortcuts. This also confused me for a while, especially since "Return" used to work before.

**Comment by FichteFoll** [comment]
Related 1416
