### ISSUE TITLE
Pressing escape in the save dialog leads to unwanted behavior (Windows)

### ISSUE THREAD

**Issue by zzynx** [flameshot-org/flameshot#1433]
**Flameshot version**
FlameShot v0.9.0
Compiled with Qt 5.15.2
(Remark: it would be handy to let me copy/paste the above info from the About window)

**Describe the bug**
When in the Save dialog (on Windows) I press esc or click the Cancel button, 
1/ the screenshot is nevertheless saved (with the name .png!)
2/ it is NOT saved in the directory I configured
3/ the directory to save screenshots in I configured is no more used

**To Reproduce**
0/ Make sure you have configured a specific location to save the screenshots in
1/ I press PrintScreen to activate FlameShot
2/ I drag a rectangle to indicate the screen area I want to screenshot
3/ I press Ctrl+S to save the screenshot
4/ A Save popup dialog opens
5/ I press Esc (or left-click on the window's Cancel button)
6/ I get a FlameShot notification that my screenshot has been saved as .png (unwanted)
7/ I find a .png file in the same directory as flameshot.exe (unwanted)
8/ When I repeat the steps 1 to 3, the save popup dialog opens with Windows default 'Pictures' directory and I have to configure my screenshot location again. (certainly unwanted)

**Expected behavior**
When I press escape or click the Cancel button in the Save dialog I don't want the screenshot to be saved at all.

**System Information**
I'm running the portable version on Windows 10

**Comment by zzynx** [comment]
Label "Unconfirmed Bug".
Does that mean you can't reproduce it?

**Comment by mmahmoudian** [comment]
I just checked it on Manjaro KDE and I could reproduce it. The file is saved as `~/.png` (in my home folder without name and just extension) and not even in pictures folder!


-------
@zzynx that tag means that no one else has reported that bug and we haven't reproduced it ourselves (either because we couldn't or because we didn't find time to). Sometimes we might also forget and a reminder like what you did can help us remember. I'm sorry for delay in reproducing it.

**Comment by hadis-git** [comment]
This issue has been fixed [here](https://github.com/flameshot-org/flameshot/commit/dc1c53f1c337e46d3c19a38cadc2ba22561b6eaf#diff-434ccdd93a0ac05f95ab5160d25267e0c2a394a2b32cd8e07a2326b174052fcaR171) if I am not mistaken and should be closed.

When you press escape in the file chooser you get a popup saying "Saving canceled".

**Comment by mmahmoudian** [comment]
@hw-lunemann Sorry, this issue was buried under many others. Thank you for your comment and pointing to the correct code. It is indeed fixed, and I also tried it again and confirmed it.
