### ISSUE TITLE
Icon on tray

### ISSUE THREAD

**Issue by wsalmeida** [flameshot-org/flameshot#1435]
am using the flameshot version 0.9.0 in debian with xfce and I notice strange behavior in the icons of it changes as it is clicked I believe this is a bug
![2021-03-07_16-14](https://user-images.githubusercontent.com/38542279/110251952-dbbbb800-7f61-11eb-9b32-b6324f2d0b84.png)
![2021-03-07_16-26](https://user-images.githubusercontent.com/38542279/110251953-dd857b80-7f61-11eb-8061-350ee35aaddd.png)

https://user-images.githubusercontent.com/38542279/110251954-e0806c00-7f61-11eb-817d-0740d552eb38.mp4

**Comment by ZetaoYang** [comment]
Same with https://github.com/flameshot-org/flameshot/issues/1378

**Comment by borgmanJeremy** [comment]
Closed as duplicate.
