### ISSUE TITLE
Can't work at bigsur

### ISSUE THREAD

**Issue by SLin0218** [flameshot-org/flameshot#1437]
**version**
I downloaded from `https://github.com/flameshot-org/flameshot/releases/download/v0.9.0/flameshot.dmg` 
 but  `/Applications/flameshot.app/Contents/Info.list` show version 0.8.5
 
**Describe the bug**
Process exists after opening, There is no icon in the menu bar.
```
 ps -ef | grep flameshot
  501  2236     1   0  9:18下午 ??         0:03.92 /Applications/flameshot.app/Contents/MacOS/flameshot
```

I get the source code and compile it is the same problem.

**To Reproduce**

**Expected behavior**

**System Information**
`macOS 11.2.2 20D80 x86_64`

**Comment by SLin0218** [comment]
@Itai-Nelken How to find the program log file

**Comment by borgmanJeremy** [comment]
I believe this is working now, I do half my testing on a mac
