### ISSUE TITLE
Flameshot doesn't unfreeze screen after copying to clipboard

### ISSUE THREAD

**Issue by harshhhdev** [flameshot-org/flameshot#1442]
**Flameshot version**
v0.9.0

**Describe the bug**
When I take a screenshot and hit copy to clipboard (saving it to my directory works fine) my entire laptop freezes  

**To Reproduce**

execute `flameshot gui`

take a screenshot

hit the copy to clipboard button.

**Expected behaviour**

Unfreeze the screen and return to normal speed with the screenshot copied to clipboard.

**System Information**

EndeavourOS 2021.02.03 

i3 Window Manager

**Comment by borgmanJeremy** [comment]
Please make sure you have a notification manager like dunst installed.

**Comment by harshhhdev** [comment]
> Please make sure you have a notification manager like dunst installed.

Yep. I've installed Dunst.

**Comment by harshhhdev** [comment]
Also, as a quick update, @borgmanJeremy . The screen goes back to normal after a while, but it still freezes after I click copy to clipboard.

**Comment by borgmanJeremy** [comment]
Are you starting i3 with dbus? https://wiki.archlinux.org/index.php/Flameshot

**Comment by harshhhdev** [comment]
> Are you starting i3 with dbus? https://wiki.archlinux.org/index.php/Flameshot

@borgmanJeremy yep. Also, I feel I should mention this issue just recently popped up a few hours ago after I installed Plasma.

**Comment by mmahmoudian** [comment]
@harshhhdev I don't think it can have anything to do with `sddm` although tbh I haven't tried any other DM since 2019. The issue might stem from not having a "compatible" clipboard manager. For example try installing `xsel` or `xclip` (I have both installed on Manjaro)

**Comment by harshhhdev** [comment]
I'm using xsel as of now. xclip doesn't seem to fix it :thinking: I'll try to uninstall KDE and see if that fixes it.

**Comment by Chaeold** [comment]
try this
https://github.com/flameshot-org/flameshot/issues/1179#issuecomment-795475067

**Comment by harshhhdev** [comment]
Hey, I've switched my operating system to pure Arch Linux from EndevourOS, and I no longer have thsi issue.

**Comment by borgmanJeremy** [comment]
Ok thanks for reporting back.
