### ISSUE TITLE
add Linux arm builds (32bit and 64bit)

### ISSUE THREAD

**Issue by Itai-Nelken** [flameshot-org/flameshot#1444]
I use Flameshot a lot on my Raspberry Pi and because the version of flameshot available from the APT repositories is pretty old and missing some features that I use I compile it from source. but I change OS's a lot and compiling Flameshot from source each time isn't ideal.

can you add Linux ARM builds to the next releases please?

Thanks a lot!

**Comment by borgmanJeremy** [comment]
Someone just needs to update the github CI and be available to test the ARM builds.

**Comment by Itai-Nelken** [comment]
I can test them, but I don't know how to update the github CI.

**Comment by Itai-Nelken** [comment]
thats ok with me. though could you do flatpak instead?

**Comment by borgmanJeremy** [comment]
I'm going to start with snap since they supposedly make it very easy to release on arm.

**Comment by Itai-Nelken** [comment]
> I'm going to start with snap since they supposedly make it very easy to release on arm.

ok, thanks a lot anyway!

**Comment by ZetaoYang** [comment]
> Someone just needs to update the [github CI](https://github.com/flameshot-org/flameshot/blob/2ad8dda66a5880c0ea4ef0faf41a7c1135c42e02/.github/workflows/Linux-pack.yml) and be available to test the ARM builds.

https://github.com/ZetaoYang/flameshot/actions/runs/644710652

![image](https://user-images.githubusercontent.com/10769951/110890387-e9d75300-832a-11eb-97ca-555088718ef4.png)

**Comment by ZetaoYang** [comment]
@Itai-Nelken https://github.com/flameshot-org/flameshot/pull/1460
You can download the ARM version of the deb from our CI daily build now.

https://github.com/flameshot-org/flameshot/pull/1460/checks?check_run_id=2102541059

![image](https://user-images.githubusercontent.com/10769951/111033672-55b1dc80-844d-11eb-8086-94a7a92ce083.png)
Or
![image](https://user-images.githubusercontent.com/10769951/111033746-c2c57200-844d-11eb-8b26-6483cb19f0a0.png)

**Comment by Itai-Nelken** [comment]
@ZetaoYang the armhf one works, but is it normal for the tray icon to be a 'i' (information)?
I don't have a arm64 OS currently flashed, I will flash one to a sd card later this week and test the arm64 deb.

**Comment by mmahmoudian** [comment]
@Itai-Nelken I think the "i" icon is related to #1378

**Comment by Itai-Nelken** [comment]
@mmahmoudian I'm pretty sure its the same issue as well after reading it, maybe if I set flameshot to autostart on login and reboot it will fix the problem?

**Comment by mmahmoudian** [comment]
I think the fix is  on the horizon based on [Jeremy's comment](https://github.com/flameshot-org/flameshot/issues/1378#issuecomment-793925558)

**Comment by Itai-Nelken** [comment]
>Does the "i" goes away after some time?

@mmahmoudian no, flameshot is already running for 1 hour and the 'i' is still there.

**Comment by borgmanJeremy** [comment]
It's a known bug. It's not flameshot issue but I'm going to just remove the info icon. Taking a break for a few days but I'm targeting a patch release next weekend that includes this fix.

**Comment by Itai-Nelken** [comment]
> It's a known bug. It's not flameshot issue but I'm going to just remove the info icon. Taking a break for a few days but I'm targeting a patch release next weekend that includes this fix.

thanks a lot!
