### ISSUE TITLE
Imgur upload does not work

### ISSUE THREAD

**Issue by All3xJ** [flameshot-org/flameshot#1448]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
link of a video showing the bug: https://streamable.com/qezyuu

**System Information**
Manjaro
KDE 5.21.2
Xorg

**Comment by borgmanJeremy** [comment]
Thanks, this is fixed on master with #1423 

I'll do a patch release this weekend.
