### ISSUE TITLE
MacOS install help and auto startup

### ISSUE THREAD

**Issue by CySpiegel** [flameshot-org/flameshot#1457]
After building from source and doing the sudo make install on macOS, how do I get this program to run at startup? It doesn't add the flameshot command to zsh so im not sure how to use it.
BTW is there a discord community for this project? I would like a place to ask questions like this because GitHub is not really the place for that lol.

**Comment by mmahmoudian** [comment]
My OSX knowledge might be a bit rusty, but in general to have a command to your shell (e.g zsh) you should put the binary in your path. You can see your paths by `echo $PATH` (note that they are separated by `:`. You can either create a symlink to flameshot binary in one of those folder listed (check out `man ln`) or add the folder that contains Flameshot to your path (`export PATH="path/to/your/folder:$PATH"`)

For startup, you should check the OSX settings (just search for "startup" in the settings window) and add Flameshot.

As for community forum, we have a Slack:

Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg

**Comment by CySpiegel** [comment]
i got everything working

**Comment by borgmanJeremy** [comment]
Great. Is there anything missing in our documentation to make it easier to set up for other Mac users? If so please submit a Pr or let us know.
