### ISSUE TITLE
missing option to not make desktop icon

### ISSUE THREAD

**Issue by qbarron73** [flameshot-org/flameshot#1461]
**Flameshot version**

0.9.0 on windows

**Describe the bug**

installer has no opption to not make a desktop icon. easy to delete but should be able to skip during install

**To Reproduce**

install flameshot 0.9 on windows and see desktop icon

**Expected behavior**

option to create the icon or not during install

**System Information**

windows 10

**Comment by Ring-A-Bell** [comment]
Is this a beginner-friendly issue? If yes, I would love to try this, just need some direction. I'm running Win10.

**Comment by mmahmoudian** [comment]
@Ring-A-Bell 
I think this issue has nothing to do with Flameshot, but related to the GitHub Actions that created the `.msi`. It should be a good issue to play with as you just need to check that one single GitHub Action:

https://github.com/flameshot-org/flameshot/blob/master/.github/workflows/Windows-pack.yml

Perhaps @ZetaoYang can give you some guidance if you got stuck.

**Comment by Ring-A-Bell** [comment]
I couldn't find anything in the above link that indicated a problem to me. After a lot of research, I still have no clue.
https://github.com/flameshot-org/flameshot/blob/220bf0a6ec2638842866c4a1c63f7703b2e5e297/.github/workflows/Windows-pack.yml#L150
https://github.com/flameshot-org/flameshot/blob/7c3c075a56cc2597af562ba8ce7b7430c501d337/CMakeLists.txt#L132

**Comment by borgmanJeremy** [comment]
I looked into this a bit and it is not trivial. There is not easy way in CPack to do this: https://cmake.org/cmake/help/latest/cpack_gen/wix.html#cpack_gen:CPack%20WIX%20Generator

I believe one would need to create a custom WiX wxs file. It seems like a bunch of work for a small pay off.
