### ISSUE TITLE
Create upload service API

### ISSUE THREAD

**Issue by skorokithakis** [flameshot-org/flameshot#1463]
I would like to write an upload plugin for [IMGZ](https://imgz.org/). Since all these services are basically the same, I would appreciate a simple API, where I would basically:

* Define the name of the service, an executable to run, and a templated command line.
* The executable would exit 0 on success and print the image's URL on STDOUT, or 1 on failure and print an error message on STDERR.
* Flameshot would show/copy/whatever the URL on success and show the error on error.

The command line I would specify would look something like this:

```
imgz --title=Screenshot-{title}-{date} {filename}
```

and Flameshot would interpolate the title, date and filename into the cli.

That way, adding uploading services would be trivial.

**Comment by borgmanJeremy** [comment]
We are planning to create an HTTP API similar to ShareX. See #955 for details.
