### ISSUE TITLE
Using "-p ~" gives "Invalid path, it must be a real path in the system"

### ISSUE THREAD

**Issue by mariusa** [flameshot-org/flameshot#1465]
**Flameshot version**

0.8.5

**Describe the bug**

I've set a keyboard shortcut for `flameshot gui -p ~`

**To Reproduce**

1. set a keyboard shortcut for `flameshot gui -p ~` (as mentioned in docs https://flameshot.org/command-line-options/ )
2. press shortcut
3. flameshot says "Invalid path, it must be a real path in the system"

If changing ~ to `/home/user`, it works.

**Expected behavior**

Have flameshot start and save to /home/user

**System Information**

Fedora 34 beta, gnome 4, bash

**Comment by mmahmoudian** [comment]
I cannot reproduce that in either bash or zsh. In either case pressing save button or <kbd>Ctrl</kbd>+<kbd>s</kbd> saves it to the given path.

**Comment by mariusa** [comment]
Doesn't help, it says again 'invalid path'.

Note, this is set as a keyboard shortcut in Gnome > Keyboard.
`~` works fine if launched from terminal.

**Comment by mmahmoudian** [comment]
Right, I didn't tried with Gnome. This means that gnome most probably wraps the command. I assume using `$HOME` doesn't help the situation either. I kinda agree with @borgmanJeremy in the PR that adding shell expansion to Flameshot is not good as shell expansion should happen at shell. Flameshot should respect whatever the input is.

@mariusa what do you think?

**Comment by mariusa** [comment]
>  I kinda agree with @borgmanJeremy in the PR that adding shell expansion to Flameshot is not good as shell expansion should happen at shell.

That makes sense. Gnome should handle the `~`. Thanks for looking into this!

**Comment by mmahmoudian** [comment]
@mariusa thank you for helping us improving Flameshot. Keep your ideas and bug reports coming 👍🏼
