### ISSUE TITLE
Remove Pixelate due to Security Concerns

### ISSUE THREAD

**Issue by W4RH4WK** [flameshot-org/flameshot#1466]
I haven't used this software, but from the gif in the README there seems to be a _pixelate_ feature, intended to blank out text.

I suggest removing this feature as it's unclear how secure this method actually is.

Reference: https://www.researchgate.net/publication/305423573_On_the_Ineffectiveness_of_Mosaicing_and_Blurring_as_Tools_for_Document_Redaction

**Comment by borgmanJeremy** [comment]
The pixel size is configurable through the thickness setting. For more privacy you can increase the pixel size. The feature will not be removed.
