### ISSUE TITLE
Issue with toolbar on Windows with multiple monitors

### ISSUE THREAD

**Issue by kura** [flameshot-org/flameshot#1467]
**Flameshot version**
0.9.0 from GitHub releases - https://github.com/flameshot-org/flameshot/releases/tag/v0.9.0

**Describe the bug**

I have 2 x 1440p monitors (both are also 144HZ if that makes any difference) set up horizontally. Monitor 1 is on the left, 2 is on the right.

If I take a screenshot and do a selection on monitor 1 (left) the toolbar correctly arranges itself around the selection.
![20210313_231206](https://user-images.githubusercontent.com/109507/111052384-323d6080-8452-11eb-8852-636268970251.jpg)

If I move the selection to monitor 2 (right) the toolbar moves location to the top left corner of monitor 1 (left) and some of the icons disappear.
This is also the case if when I take a screenshot I only highlight an area on monitor 2, so it's not just an issue with just moving the selection it happens no matter what.
![20210313_231153](https://user-images.githubusercontent.com/109507/111052387-36697e00-8452-11eb-8ffa-0a1f0ad4104c.jpg)

**To Reproduce**
Have Windows 10, multiple monitors and take a screenshot.

**Expected behavior**
The toolbar should be attached to the selection.

**System Information**
Windows 10, 19042.867, 20H2

**Comment by kura** [comment]
![2021-03-13_23-20-17](https://user-images.githubusercontent.com/109507/111052447-c0b1e200-8452-11eb-9786-ebf6e809b15b.png)

Display arrangement.

**Comment by mmahmoudian** [comment]
Is it duplicate of #1434?

**Comment by kura** [comment]
You are right, it is.
