### ISSUE TITLE
flameshot gui --raw doesn't make selection on enter

### ISSUE THREAD

**Issue by kaihendry** [flameshot-org/flameshot#1468]
<img src=https://s.natalian.org/2021-03-14/1615688639_1920x1080.png>

**Flameshot version**
0.8.5 and 0.9

**Describe the bug**
When making a selection and then hitting Enter key, nothing happens

**To Reproduce**
`flameshot gui --raw > /tmp/wth`

**Expected behavior**
Selection copied to clipboard

**System Information**
Archlinux

**Comment by mmahmoudian** [comment]
Can you post your Flameshot config file here.

**Comment by kaihendry** [comment]
https://s.natalian.org/2021-03-14/flameshot.ini is my config, cheers!

**Comment by ronneycz** [comment]
> ![](https://camo.githubusercontent.com/b234583d4fffc84293cc049b9c2640bd9e253cb6aee829abe31638ddb6d06aed/68747470733a2f2f732e6e6174616c69616e2e6f72672f323032312d30332d31342f313631353638383633395f3139323078313038302e706e67)
> 
> **Flameshot version**
> 0.8.5 and 0.9
> 
> **Describe the bug**
> When making a selection and then hitting Enter key, nothing happens
> 
> **To Reproduce**
> `flameshot gui --raw > /tmp/wth`
> 
> **Expected behavior**
> Selection copied to clipboard
> 
> **System Information**
> Archlinux

Same issue here on both flameshot from repos and flameshot-git from AUR.

**Comment by borgmanJeremy** [comment]
Yes right now the best way to resolve this is to map "Copy" to "Enter"

**Comment by mmahmoudian** [comment]
@ronneycz Sorry for my late reply, but if you check your `flameshot.ini` you will see what function is mapped to Enter:
```sh
echo "$(curl -fsSL https://s.natalian.org/2021-03-14/flameshot.ini)" | grep -i --color -P "(copy)|(Return)"
```
> ```
> TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
> TYPE_COPY=Ctrl+C
> TYPE_IMAGEUPLOADER=Return
> ```

As Jeremy correctly pointed out, the easy solution is to remap the `Return` key to the function you want. For example:

```sh
echo "$(curl -fsSL https://s.natalian.org/2021-03-14/flameshot.ini)" \
    | sed 's/Return//' \
    | sed 's/Ctrl+C/Return/'
```
<details>
  <summary>Click to expand</summary>
<p>

> ```
> [General]
> disabledTrayIcon=false
> drawColor=#ff0017
> drawThickness=0
> savePath=/tmp
> savePathFixed=false
> showStartupLaunchMessage=true
> 
> [Shortcuts]
> TYPE_ARROW=A
> TYPE_CIRCLE=C
> TYPE_CIRCLECOUNT=
> TYPE_COMMIT_CURRENT_TOOL=Ctrl+
> TYPE_COPY=Return
> TYPE_DRAWER=D
> TYPE_EXIT=Ctrl+Q
> TYPE_IMAGEUPLOADER=
> TYPE_MARKER=M
> TYPE_MOVESELECTION=Ctrl+M
> TYPE_MOVE_DOWN=Down
> TYPE_MOVE_LEFT=Left
> TYPE_MOVE_RIGHT=Right
> TYPE_MOVE_UP=Up
> TYPE_OPEN_APP=Ctrl+O
> TYPE_PENCIL=P
> TYPE_PIN=
> TYPE_PIXELATE=B
> TYPE_RECTANGLE=R
> TYPE_REDO=Ctrl+Shift+Z
> TYPE_RESIZE_DOWN=Shift+Down
> TYPE_RESIZE_LEFT=Shift+Left
> TYPE_RESIZE_RIGHT=Shift+Right
> TYPE_RESIZE_UP=Shift+Up
> TYPE_SAVE=Ctrl+S
> TYPE_SELECTION=S
> TYPE_SELECTIONINDICATOR=
> TYPE_SELECT_ALL=Ctrl+A
> TYPE_TEXT=T
> TYPE_TOGGLE_PANEL=Space
> TYPE_UNDO=Ctrl+Z
> ```

</p>
</details>

**Comment by kaihendry** [comment]
Updating my `.config/flameshot/flameshot.ini` shortcut to `TYPE_COPY=Return` makes it work like before... which begs the question.

How did it work before?! :exploding_head:

**Comment by deliciouslytyped** [comment]
I have the same problem - Ctrl-C for saving when `-r` is passed feels awkward.
I don't like the solution of mapping Enter to the action but it's a workaround in the meantime.

The downside of this solution is that it clobbers the clipboard. I don't want flameshot to do anything, other than output the image data on stdout. I'd like to have Enter for "continuing", with saving to a file if -p is passed, and output on stdout if -r is passed.

**Comment by kaihendry** [comment]
Tbh this "downside" is my favorite feature of flameshot. That it records to file and clipboard at the same time. It's such a pain on the MacOS's native screenshot tool to keep track where I'm exporting to.

**Comment by deliciouslytyped** [comment]
Could be solved with a flag.
I really just want the image on stdout.
https://github.com/flameshot-org/flameshot/issues/1480 is related.

**Comment by mmahmoudian** [comment]
@kaihendry
> How did it work before?! 🤯

This is my understanding of the situation:
one of the contributors made a mistake and changed the default shortcut key while implementing the custom shortcuts.

-------

@deliciouslytyped I take the discussion under the issue you opened.

**Comment by kaihendry** [comment]
https://s.natalian.org/2021-07-22/flameshot.ini

This issue has come up for me **again** on 0.10.0-1.
