### ISSUE TITLE
Homebrew Cask?

### ISSUE THREAD

**Issue by karlhorky** [flameshot-org/flameshot#1475]
Hi there, thanks for your effort on Flameshot - looks really amazing!!

**Is your feature request related to a problem?**

Installation on macOS currently requires downloading a DMG or [manually building the project](https://github.com/flameshot-org/flameshot/issues/586#issuecomment-720612189).

To make this process easier for users, would the maintainers be open to adding a Homebrew Cask? This would enable users to install via `brew install --cask flameshot`.

A guide to adding a new cask can be found here: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by borgmanJeremy** [comment]
You actually do not need to build from source, the .dmg file is on our release page. 

That said adding to homebrew is a good idea.

**Comment by karlhorky** [comment]
> You actually do not need to build from source, the .dmg file is on our release page.

Ah sorry, I was looking for something like this, but somehow this detail eluded me! I've added it to the description above.

**Comment by lfalcao** [comment]
@karlhorky here https://github.com/Homebrew/homebrew-cask/pull/101084

**Comment by karlhorky** [comment]
Thanks, subscribed to that PR!

**Comment by karlhorky** [comment]
@lfalcao Oh no, it was closed :( I guess they need also a "zap stanza" as well over there

https://github.com/Homebrew/homebrew-cask/pull/101084#issuecomment-823801315

**Comment by karlhorky** [comment]
There was also another PR from @cometeme, but it was closed because @lfalcao had Homebrew/homebrew-cask#101084 open at that time 😫 :

https://github.com/Homebrew/homebrew-cask/pull/101280

**Comment by cometeme** [comment]
I opened a new PR: Homebrew/homebrew-cask#104415

**Comment by borgmanJeremy** [comment]
Thanks! looks like this is merged I was able to install flameshot via homebrew this morning.

**Comment by nippyin** [comment]
I was able to install flameshot via brew install --cask flameshot however unable to run this application on BigSur. I see process is running though but nothing shows up when I run application.

**Comment by mmahmoudian** [comment]
@nippyin have you tried `flameshot gui` in terminal while the background process is running?

**Comment by nippyin** [comment]
Terminal does not recognise flameshot. Even after putting the /application/flameshot.app in environment variable.

Also tried to build manually and same result.

Is it possible to check if this works in Mac?

-S

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
