### ISSUE TITLE
Update checker is not disabled even though it's option is unchecked

### ISSUE THREAD

**Issue by staticssleever668** [flameshot-org/flameshot#1477]
**Flameshot version**
0.9.0

**Describe the bug**
Update checker is not being disabled even with the "Automatic check for updates" option toggled off.
How did I knew this? Well, on every start-up Flameshot tries to resolve "api.github.com", which wasn't the case before the latest (0.9.0) update, where the update checker was added. I get this information from OpenSnitch application-level firewall.

**To Reproduce**
Install Flameshot, go to the options and uncheck the "Automatic check for updates" option. Restart the application.  See the "api.github.com" trying to be resolved.

**Expected behavior**
Flameshot should not try to open any internet connections without a reason.

**System Information**
Arch Linux
Package: flameshot 0.9.0-1

**Comment by borgmanJeremy** [comment]
Can you check that #1478 solves your issue? I'll merge it before our patch release this weekend if you can confirm it.

**Comment by staticssleever668** [comment]
It seems like it doesn't: I still get the connection notification.

**Comment by borgmanJeremy** [comment]
Hmmm ok . I'll debug in more depth with wireshark.

**Comment by staticssleever668** [comment]
I debugged it myself a bit, and I can tell that the function where you added the check is never invoked (at least in the while when I was debugging), instead `Controller::getLatestAvailableVersion()` is called from the initializer of `Controller` class on the line 109

**Comment by borgmanJeremy** [comment]
Okay thanks for helping debug it. I moved the check. It appears to be working locally but I actually can't use wireshark to debug it, I've got encrypted DNS enabled to my pihole. I didn't want to spend a bunch of time messing with my firewall logs, so if you can validate the fix I would appreciate it.

It appears the original code simply disabled the graphical menu when the option was disabled. However I agree it makes sense to disable the ping to the github api.

**Comment by staticssleever668** [comment]
I just checked it and it now works as expected. Thanks!

**Comment by mmahmoudian** [comment]
@staticssleever668 
Shall we consider this closed then?

**Comment by borgmanJeremy** [comment]
Thanks for reporting back! I'll close this and it will be in the patch release this weekend.
