### ISSUE TITLE
Run without background process when -r or -p is passed (also allows not using dbus)

### ISSUE THREAD

**Issue by deliciouslytyped** [flameshot-org/flameshot#1480]
Flameshot currently requires starting a separate background process, with the rationale that this is required to handle the clipboard.
Currently flameshot is the only screenshot application that I was able to find, that works on gnome3 with wayland. `gnome-screenshot` doesn't do what I want, so I **need** to use flameshot.

I want to output a screenshot on stdout, and this is possible with the -r option, however, needing to run a background process for `flameshot gui` to work, is awkward.

`flameshot gui` starting a proper flameshot process, taking a screenshot, and then returning the output, is the desired behaviour.
Having this all done in one process context would also allow flameshot to work properly without dbus.

My current solution is this awkward mess:
```
set +m; mkfifo wat; { ( flameshot & flame_pid="$!" ; cat wat; kill -9 "$flame_pid" ) & sleep 5 } 2>/dev/null; flameshot gui -r | display `#do stuff here`; echo > wat; rm wat; set -m;
```
which could be reduced to:
```
flameshot gui -r | display `#do stuff here`
```

https://github.com/flameshot-org/flameshot/issues/1468#issuecomment-799966502 is related to making this process less awkward as well.

**Comment by deliciouslytyped** [comment]
Here is a oneliner for OCR-ing screenshots: 
```
nix-shell -p flameshot tesseract imagemagick --run "set +m; mkfifo wat; { ( flameshot 2>/dev/null & flame_pid="$!" ; cat wat; kill -9 "$flame_pid" ) & sleep 5; } 2>/dev/null; flameshot gui -r | convert -resize 400% /dev/stdin /dev/stdout | tesseract stdin stdout 2>/dev/null; echo > wat; rm wat; set -m;"
```

**Comment by mmahmoudian** [comment]
@deliciouslytyped I don't this this dbus is going away anytime soon, but your "feature request" imho has nothing to do with the dbus but rather having an override on saving to the file when `-r` is specified.

Perhaps the more complete solution is that Flameshot respects all flags (`-c`, `-r`, and `-p`) if the user has specifically specified them.

**Comment by deliciouslytyped** [comment]
The dbus stuff was a side-issue.
The key thing is to not need to start a background process.
Using `-r` and `-p` are just the general contexts where this makes sense.
You can keep the dbus stuff even if you aren't running a separate background process, it just isn't _needed_ anymore in that specific case, because the output target is not the X11 clipboard.

**Comment by mmahmoudian** [comment]
@borgmanJeremy @ZetaoYang @Martin-Eckleben @lupoDharkael 
What do you think?

I personally think that there is no necessity for Flameshot to do one single action and it can send the output in different routes sequentially (e.g `flameshot screen -r -c -p img.png`).

Regarding the dbus, I don't have proper understanding on what are the use cases of it, so the only comment I can give is that it make sense to not have the dbus whenuser has specifically asked for `-p` and `-r` iff its only purpose of dbus is to handle the clipboard.

**Comment by migzamudior3** [comment]
La verdad es la primera vez que analizo esto y pues se me terminó el
tiempo, pero me esforzare por mejorar mi lógica mental y comprender mejor
el ingles ya que sólo se poquito y esta activad apenas hace una hora y
media supe que existia. Gracias:)

**Comment by ZetaoYang** [comment]
> @borgmanJeremy @ZetaoYang @Martin-Eckleben @lupoDharkael
> What do you think?
> 
> I personally think that:
> 
> 1. there is no necessity for Flameshot to do one single action and it can send the output in different routes sequentially (e.g `flameshot screen -r -c -p img.png`).
> 2. Regarding the dbus, I don't have proper understanding on what are the use cases of it, so the only comment I can give is that it make sense to not have the dbus whenuser has specifically asked for `-p` and `-r` iff its only purpose of dbus is to handle the clipboard.

@deliciouslytyped 

The following should work.
```
flameshot full -r | display `#do stuff here` 
``` 
or
 ```
flameshot screen -n 1 -r | display `#do stuff here` 
````
or
Via `flameshot gui`
![image](https://user-images.githubusercontent.com/10769951/111283451-1d431600-867a-11eb-8531-0884db787dbf.png)

![image](https://user-images.githubusercontent.com/10769951/111283504-2b913200-867a-11eb-9ee0-7a8117a16f4d.png)

**Comment by mmahmoudian** [comment]
@ZetaoYang

This works (raw to stdout and copied to clipboard):

```sh
flameshot screen -n 2 -r -c | display
```

This does not work:

```sh
flameshot screen -n 2 -r -c -p ~/test.png | display
```
does not save the screenshot to `\\test.ong`, does not copy to clipboard and also produces:

> display: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.

**Comment by deliciouslytyped** [comment]
@mmahmoudian @ZetaoYang: None of these work without the background flameshot process running. Please check that you don't have any flameshot processes running in the background when you test these, or you can probaby kill it with `echo Killed: $(kill -9 $(pgrep -f '/flameshot$'))`.

**Comment by mmahmoudian** [comment]
@deliciouslytyped 
> None of these work without the background flameshot process running. Please check that you don't have any flameshot processes running in the background when you test these

I changes the background of my monitors to be different make it easier to see what is screenshot and what is not. I'm recording from my 3rd monitor (with Manjaro background) and I took screenshot from my 2nd monitor (with dark patterned background).

![Peek 2021-03-17 11-16](https://user-images.githubusercontent.com/390889/111443642-40210900-8712-11eb-8f0e-c209c85be139.gif)

**Comment by deliciouslytyped** [comment]
Hm. Ok, I'm not sure what's going on.

**Comment by l29ah** [comment]
Do i get it right that i need to explicitly `killall flameshot`after every time i run flameshot to avoid the process running in the background indefinitely and eating my battery while listening to my key presses?

**Comment by mmahmoudian** [comment]
@l29ah You got the comcept awfully wrong. Flameshot does not listen to your keys. To put it in simple terms, Flameshot has 2 parts:
1. The main process which listens to `org.flameshot.Flameshot` dbus. your system already has tons of dbus which you can list using `qdbus` command. To count the number of dbus running on your computer you can do `qdbus | wc -l` (I have 131 on my computer).
2. the flameshot command (e.g `flameshot gui`) which sends the command to the main process and asks it to do a specific thing (in case of my example, the `gui` command).

Flameshot main process does NOT listen to your  key presses. 

What @deliciouslytyped is asking is actually to kill Flameshot's main process to probably save some memory. On my computer it uses 147KB of memory. So imho no one should be worried about saving that much memory:

![image](https://user-images.githubusercontent.com/390889/116373790-5a243000-a816-11eb-8907-7601d9ea1d2b.png)




For more information about dbus read the following:
- https://unix.stackexchange.com/questions/46301/a-list-of-available-d-bus-services
- https://en.wikipedia.org/wiki/D-Bus
- https://wiki.archlinux.org/index.php/D-Bus

**Comment by l29ah** [comment]
> Flameshot does not listen to your keys.

`strace` says it does, as it wakes up and syscalls every time i hit a key in my X session.

> your system already has tons of dbus

```
‰ qdbus | wc -l
qdbus: could not find a Qt installation of ''
0
```

> The numfmt command is number formatter and it converts the numbers in column 4 and 5 from Bytes to Kilobyte or Megabyte to make it more human readable.

No, your script (or in fact your interpretation of its output) is incorrect, and in your example it consumes 145MB of RAM (and being 0.4% of your 32GB installed), as ps outputs sizes in kilobytes.

**Comment by mmahmoudian** [comment]
@l29ah you are right about the `ps`. For other who are on the same wrong wagon as I was, I just checked the documentation again and:
![image](https://user-images.githubusercontent.com/390889/116411139-180ee480-a83e-11eb-9238-0ffae1010bc6.png)

Regarding the `qdbus`, i think you need to have qt-dev installed. but according to a post I found on [How to identify what processes are consuming dbus sockets](https://access.redhat.com/solutions/438023) the following should work to some extent:
```sh
sudo lsof -u dbus | grep -i socket | wc -l
```

About the listening to keystokes, perhaps @borgmanJeremy or @thepurple  can provide better answer.
