### ISSUE TITLE
Map more than one keystroke for each function

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1481]
It would be nice to be able to map more than one keystroke for each function. E.g Return and Ctrl+c both does copying to clipboard.

(This was a by-product of #1443 and originally proposed by @mkbaranovskyi )

**Comment by veracioux** [comment]
@mmahmoudian Is this now unnecessary as of the new "Accept capture" mechanism?

**Comment by mmahmoudian** [comment]
Tbh I don't remember my reasoning behind it. I think we can consider it closed👍🏼
