### ISSUE TITLE
Can not set "Enter" as shortcut

### ISSUE THREAD

**Issue by Porrumentzio** [flameshot-org/flameshot#1483]
**Flameshot version**
0.9.0

**Describe the bug**
I'm not able to set Enter key as shortcut for "copy to clipboard".

**To Reproduce**
Flameshot Settings > Shortcuts > Copy selection to clipboard
There, click to set shortcut and press Enter key, without result

**Expected behavior**
I expected to be able to set Enter, specially when on the previous version that key was used for that action. Related to #1429

**System Information**
Manjaro 20.2.1, MATE 1.24.1

**Comment by borgmanJeremy** [comment]
This is fixed on the main branch, will be release in 0.9.1
