### ISSUE TITLE
[Feature Request] Multiple Capture areas/Combine multiple captures

### ISSUE THREAD

**Issue by JonathanWolfe** [flameshot-org/flameshot#1489]
My main use case for tools like this is to capture a before and after shot. Sometimes it's decently easy to line up the options next to each other for a group photo, but other times I'm required to take a shot, copy to clipboard, paste to Paint or something, and then repeat for the second shot.

On Windows this isn't too terrible of a work around, as Paint.exe is universal and always works the same, but on Mac there is no default image editing software installed and lots of the replacements are more cumbersome that really needed. (I don't use Linux, but I'd wager it's closer to Mac usage than windows).

I'd like to be able to do a capture, and then click a button to do another capture, which would be placed directly below the first one in the annotations/edit window. I'm perfectly okay with a stipulation being that the capture size remains the same dimensions to make canvas resizing simple, but it does have to allow the second capture area to be relocatable.

**Comment by ZetaoYang** [comment]
@JonathanWolfe @mmahmoudian 
This can be easily achieved by using the pin tool several times. Though the current pin tool is very rudimentary.
![image](https://user-images.githubusercontent.com/10769951/111558008-d57ed480-87c8-11eb-81f2-2f815097ed3d.png)

**Comment by JonathanWolfe** [comment]
@ZetaoYang This does work! Thanks!
