### ISSUE TITLE
Add possibility to increment manually the « Auto incrementing counter bubble »...

### ISSUE THREAD

**Issue by Creteil** [flameshot-org/flameshot#1492]
Hi,

When creating tutorials, it is current to use many screenshot to illustrate the subject, and numbering them by steps.

Here is one as example : « [Tutoriel Remplacement potentiomètre volet de climatisation...](url) »

Actually, using the « Auto incrementing counter bubble », it is impossible to start at a manually chose number when using it.

Why not assigning the « CTRL + Scroll wheel » to set the starting number of the bubble ?

**Comment by mmahmoudian** [comment]
I think your idea is a variation (i.e special case) of #1214. If you do agree, please close this issue and comment on the other issue and support the suggestion. If you don't think these are the same, please explain in why you thing this feature request is different.

**Comment by Creteil** [comment]
You can close this ticket, i am gonna comment on the other side...
