### ISSUE TITLE
Color pick from background

### ISSUE THREAD

**Issue by Pixel48** [flameshot-org/flameshot#1495]
## Simple but useful functionality  
When holding right-click color can be picked from color samples by only hovering on them, so left-click outside color sample circle (when holding right-click) could pick clicked pixel's color as drawing color

**Comment by borgmanJeremy** [comment]
I don't 100% follow this request. @mmahmoudian can this be closed in favor of the color picker rework?

**Comment by mmahmoudian** [comment]
@borgmanJeremy yes I believe this is fulfilled by the color grabbing feature we just added.
