### ISSUE TITLE
Q : how to set text font size

### ISSUE THREAD

**Issue by htso** [flameshot-org/flameshot#1500]
Q : Is there a way to change text font size ? Right now, regardless of size of pic, the font is very tiny.

**Comment by htso** [comment]
Just found the answer from another post. 

After adding the text field, use the mouse wheel, roll up --> bigger font.

**Comment by mmahmoudian** [comment]
@htso Alternatively. for every tool you have selected, you can change the settings in the Tool Settings sidepanel. Just press space or click on the Tool Settings


![image](https://user-images.githubusercontent.com/390889/111970116-9e2f6100-8b03-11eb-8969-3378041d5b31.png)
