### ISSUE TITLE
Flameshot fails to upload screenshot to Imgur - The Loading window freezes and then close

### ISSUE THREAD

**Issue by Cloufish** [flameshot-org/flameshot#1501]
**Flameshot version**

Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
When I select the area to screenshot, and press 'Upload to Imgur', the new window (loading) appear - which is okay, but after two seconds it hangs, then closes without new window of imgur overview appearing

![image](https://user-images.githubusercontent.com/32965886/111962012-112fdc00-8af2-11eb-88ec-a108a8ce556f.png)

Then this loading window disappears, and I get the notification "URL copied to clipboard" (Which it didn't)

**To Reproduce**
1. Open ```flameshot gui```
2. Select area to screenshot
3. Press "Upload to Imgur" button
4. See that new loading window hangs/freezes and no upload is made

**Expected behavior**

The Loading window shouldn't have freeze, and after it completes there should appear new window that  gives the option to copy URL of the Imgur

**System Information**
```$ uname -r```
```5.11.7-arch1-1```

**Comment by mmahmoudian** [comment]
If I don't make mistake, it has uploaded, but the app does not recover after uploading. Would you please try again and then check the "Latest uploads" section:
![image](https://user-images.githubusercontent.com/390889/111968822-3fb5b300-8b02-11eb-901c-0540c036f672.png)

**Comment by Cloufish** [comment]
Oh god, you're a genius mmahmoudian. Yes, it appears on the Latest Uploads. Thank you very much!
