### ISSUE TITLE
flameshot starts but doesn't take screenshot

### ISSUE THREAD

**Issue by HazemElmahy** [flameshot-org/flameshot#1502]
**Flameshot version**
flameshot-0.6.0-3.fc30.x86_64 

**Describe the bug**
Flameshot starts normally tray icon appears I can navigate to configuration and information but nothing happens when I click take screenshot

or execute ```flameshot gui``` in terminal 

It worked fine yesterday the one thing that I changed I had a problem with the gtk file chooser 
I changed the /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml 
and compiled schemas ```glib-compile-schemas .```
I don't know if this is related but that's the one thing I changed in the system

**To Reproduce**

**Expected behavior**
start take screenshot window selection

**System Information**
Fedora 30
i3wm

**Comment by mmahmoudian** [comment]
@HazemElmahy Your flameshot version is very old. We cannot investigate older versions. Please upgrade to the latest version. The latest version is 0.9.0 (soon we will release 0.9.1) and it is available as `.rpm` file to install manually. Alternatively you can download it via Flatpak, AppImage or Snap. Please let us know and re-open this issue if after using the latest version, you still have the same problem with Flameshot.
