### ISSUE TITLE
Tools not shown around screen shot location

### ISSUE THREAD

**Issue by jonashilmersson** [flameshot-org/flameshot#1504]
**Flameshot version**
0.9.0

**Describe the bug**
When I try to copy a part of the screen to the right of the middle of the screen, the tool icons are shown up in the top left corner instead of the location to copy. See screen shot of my external screen below.

**To Reproduce**
Take a screen shot on either the laptop screen, or on the external screen somewhere in the middle or a little bit to the right.

**Expected behavior**
The tool icons should be located around the screen shot location.

**System Information**
Windows 10 20H2 19042.867
3840x2160 external screen connected to a Thinkpad laptop with 1920x1080 screen. 
![image](https://user-images.githubusercontent.com/846721/112046043-d2c70b00-8b4b-11eb-9251-debc9eb2d4b3.png)

**Comment by mmahmoudian** [comment]
Isn't this duplicate of #1440?

**Comment by jonashilmersson** [comment]
Closed as this is a duplicate of #1440.
