### ISSUE TITLE
Image seems corrupted when copying to clipboard

### ISSUE THREAD

**Issue by Mindslave** [flameshot-org/flameshot#1505]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1
(Installed with dnf)

**Describe the bug**
1. I tried to make a screenshot (using the area selection) and copied it to my clipboard, Flameshot reports that the image has been copied to the clipboard.
2. I tried to copy the image into obsidian.md, nothing happens.
3. I tried to copy the image into libreoffice writer, nothing happens. 
4. I tried to copy the image into Telegram, it works, but the image seems...wrong? corrupted? I don't know the correct description, see the attached image:
![photo_2021-03-23_09-32-04](https://user-images.githubusercontent.com/38843153/112074918-b7dfaf80-8bba-11eb-8619-1b2ecd93b5ae.jpg)

It was a screenshot of a simple google search, since that's really not obvious anymore...
5. If I save the image instead, everything works as expected.

This is also not a one-time thing, it happens everytime I try to copy a screenshot to my clipboard.

**Expected behavior**
I would expect the image to get copied to my clipboard as is.

**System Information**
Fedora 33
Gnome Version: 3.38.4
Windowing System: Wayland

To take screenshots I bound the command `/usr/bin/flameshot gui` to a shortcut.

**Comment by Mindslave** [comment]
Sure
```
[General]
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
savePath=/home/marius/Pictures
```
I did not modify this file at all after the installation tho.

**Comment by borgmanJeremy** [comment]
Ahh sorry I just saw you are on 0.8.5, We improved the wayland support in 0.9.0. Could you please try with that version? I specifically made changes to improve the clipboard on Gnome Wayland.

**Comment by Mindslave** [comment]
Indeed I updated to 

```
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

And now everything works as expected! 
Thanks! Working with the default screenshot utility that comes with fedora I really realized how awesome flameshot is, missed it so much!

**Comment by mmahmoudian** [comment]
@Mindslave shall we close this issue?

**Comment by Mindslave** [comment]
Yes, this can be closed, thanks again!
