### ISSUE TITLE
Activate rectangle selection without clicking tray icon

### ISSUE THREAD

**Issue by conformist-mw** [flameshot-org/flameshot#1507]
Now I have to click on the tray icon to activate the selection. I would like to be able to activate this mode with hotkeys, and for that it should be possible to run `flameshot` from cli with arguments.

Thanks.

**Comment by mmahmoudian** [comment]
In is already implemented.

Try `flameshot --help` to see all the arguments. For ehat you are after, `flameshot gui` is the command.

**Comment by conformist-mw** [comment]
Thanks! I saw this option, but I thought it was the GUI option (show the main window), and I was looking for something like `run`.

**Comment by mmahmoudian** [comment]
The naming might not be optimal. We are working on improving our documentation and help. Please feel free to propose alternative sentences for the help manual and documentation.
