### ISSUE TITLE
Feature Proposal: FlameShot as presentation tool

### ISSUE THREAD

**Issue by zell-mbc** [flameshot-org/flameshot#1508]
I often find myself in the situation that I am running a presentation from my PC and I want to highlight certain aspects of the screen. Enter FlameShot, quick hit on print, "A" for an arrow, draw an arrow, talk, esc and onwards.
This works great already, however there is one piece I either haven't figured out, or is not there, which visually breaks this otherwise seamless workflow.

I seem to only get the tools (arrow, rectangle, etc.) when I start Flameshot with rectangular region selection, which means the screen is dimmed out first and I need to manually size the rectangle to fit my whole screen. And that's where things sometimes go off track, I may get the selection wrong, start all over,  etc, just a second, but I noticed that this de-focuses from the presentation and I end up explaining what I am trying to do instead of staying on my actual topic.

If there was a way to start with full screen selection (similar to "flameshot screen") **and** show the tools, FlameShot would not only be the best screenshotter on the planet but also the best presentation companion out there :-)

And to close things off, if my drawings are meaningful enough to send it to the attendees afterwards I'd hit ctrl-s, otherwise ESC, and onwards. This is really really cool! And would be even better with the full screen rectangle + tools feature :-)

**Comment by mmahmoudian** [comment]
I myself use Flameshot in the same way as it is super convenient to annotate the screen while presentation, but I think removing the dimmed area would cause confusion for users.
How about Ctrl+a to select all visible screen of the monitor that mouse is in it? This was the same shortcut can be used for those who want to take screenshot from their whole monitor except the application bar or something similar (basically Ctrl+a and then just dragging the handle for the side they want to shrink).

**Comment by zell-mbc** [comment]
I didn't know about Ctrl-a, that's a perfect solution! Print + Ctrl-a and I am in business, love it!
Thanks for helping me out with this one and another big thank you for building Flameshot.

**Comment by mmahmoudian** [comment]
@zell-mbc happy to know it was resolved and on behalf of the main devs of this project, I'm glad to hear that you have found Flameshot useful.
