### ISSUE TITLE
wont start - linux mint 20.1

### ISSUE THREAD

**Issue by thracyturnix** [flameshot-org/flameshot#1510]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

System:
  Host: xx Kernel: 5.4.0-70-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.2.6 

**Describe the bug**
Wont start. 
x@x:~$ flameshot
qt5ct: using qt5ct plugin
qt5ct: custom style sheet is disabled

**To Reproduce**
Use shortcut or from cli

**Expected behavior**
start and icon on taskbar

**System Information**
above

**Comment by mmahmoudian** [comment]
We do not support very old versions of Flameshot. The current version is 0.9.0 .

But regarding your issue, try `flameshot gui` in terminal
