### ISSUE TITLE
Allow to move the pinned image outside the screen partially

### ISSUE THREAD

**Issue by yusanshi** [flameshot-org/flameshot#1511]
I often pin a screenshot for later reference. Sometimes the screenshot area is too large and it is occupying most of my display. I want to move it outside the screen partially but once the image border hits the screen border I cannot move it anymore.

So I hope the pinned image can be moved outside the screen partially just like a regular program does. 

Example: file explorer program

![image](https://user-images.githubusercontent.com/36265606/112600952-c9d88100-8e4c-11eb-84e9-7c7dd4c0c225.png)

<br><br>

## Current
![image](https://user-images.githubusercontent.com/36265606/112600452-30a96a80-8e4c-11eb-8c9d-f64a85bb6539.png)

## Ideal (example with Snipaste on Windows)
![image](https://user-images.githubusercontent.com/36265606/112599683-39e60780-8e4b-11eb-9fab-1d3377c5dbc1.png)

<br><br>
**My environment**

System: Ubuntu 20.04
Display server: X11
Display manager: gdm3

**Comment by mmahmoudian** [comment]
isn't this duplicate of #984 ?

**Comment by yusanshi** [comment]
Yes it’s a duplicate of #984 (I have searched but did not find that :)

Thanks and I’ll close this issue.
