### ISSUE TITLE
The tray icon is not showing

### ISSUE THREAD

**Issue by thalesruan** [flameshot-org/flameshot#1514]
**Flameshot version** 
0.9.0 - Flatpak

**Describe the bug**
When the application is open, the icon don't appear in the tray. There's just an unclickable blank space

**Expected behavior**
When i open the application, its icon will be shown in the system tray, and when i click on it, i be abble to select an area and take the screenshot of that.

**System Information**
Actually using Arch + Gnome 40, but the problem has been observed since Arch + Gnome 3.38

**Comment by azisnaufal** [comment]
Maybe you need to install KStatusNotifierItem gnome extension. I installed it and the flameshot icon is working well.
![gambar](https://user-images.githubusercontent.com/2264036/112743466-c6b2d180-8fc1-11eb-9525-3b668beab6ed.png)

**Comment by mmahmoudian** [comment]
@thalesruan would you please provide a screenshot of the icon.

Also you can run Flameshot that you have installed from Flatpak with the following command and assign a keyboard shortcut to it:
```sh
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=flameshot org.flameshot.Flameshot gui
```

Alternatively you can use [peek](https://github.com/phw/peek) to record a gif and post it here

**Comment by kpcee** [comment]
Gnome dropped the support for tray icons years ago. Most likely the used Gnome extension is faulty, I would try another one or a proper desktop environment that supports tray icons natively.

**Comment by thalesruan** [comment]
> Maybe you need to install KStatusNotifierItem gnome extension. I installed it and the flameshot icon is working well.
> ![gambar](https://user-images.githubusercontent.com/2264036/112743466-c6b2d180-8fc1-11eb-9525-3b668beab6ed.png)
> 
> Edit: Tested on Fedora 34 beta gnome 40 wayland with font dpi scaling at 1.25. Flameshot is installed via dnf.

I use this extension already :D

**Comment by thalesruan** [comment]
> @thalesruan would you please provide a screenshot of the icon.
> 
> Also you can run Flameshot that you have installed from Flatpak with the following command and assign a keyboard shortcut to it:
> 
> ```shell
> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=flameshot org.flameshot.Flameshot gui
> ```
> 
> Alternatively you can use [peek](https://github.com/phw/peek) to record a gif and post it here

The icon just don't appear in the tray. And Peek don't record the tray area

**Comment by skewty** [comment]
I also had this issue with Fedora 33 (kStatusNotifierItem gnome extension installed).  I need to kill the process and restart it or the icon does not appear in tray.

This is likely a race condition (which extension is started first).  Is there some way to query for support and sleep for up to 3 seconds (in small sleep increments) to give other extensions time to start eventually giving up and continuing?

**Comment by borgmanJeremy** [comment]
Im not really interested in hacking around gnome issues like this. I would like it to be fixed upstream (where the problem is).

**Comment by skewty** [comment]
How is a 3rd party extension a gnome issue?  If flameshot's workflow depends on a 3rd party extension to work on the most popular GUI platform in the linux space then I believe it is worth trying to fix.  But that is just my opinion.

**Comment by skewty** [comment]
The tray as used by flameshot was deprecated years ago by gnome.  If flameshot requires it, it will have to play nice with [the other extension](https://extensions.gnome.org/extension/615/appindicator-support/) that provides this feature back into gnome.  

Probably a simple sleep for a second before loading on gnome-shell would suffice.

**Comment by kpcee** [comment]
As borgmanJeremy already said it is an upstream problem. Gnome has officially stopped supporting trayicons, if it doesn't work properly with third party extensions it is either a bug from
 * Gnome because they don't support it anymore and willfully ignore the System Tray Specifications from freedesktop.org
 * the extension because it does not work properly
 * or a problem on Qt side because they don't support the gimmick from Gnome
 
Adding any workarounds for Gnome would only cause new problems, moreover the behavior may change at any time and a going workaround may suddenly stop working. Also it is not trivial to read out the used desktop environment, it is error prone especially when people use several in parallel. Flameshot uses the QSystemTrayIcon class to display the tray icon and this is provided by Qt, upstream.

**Comment by rsaleri** [comment]
Pop!_OS 20.04 LTS 
GNOME 3.36.8

Looks like the icon is not found, but its space is there and working:
![image](https://user-images.githubusercontent.com/33120404/113974344-0a1d0380-983e-11eb-8a95-828467428fbd.png)

When first loading after boot the blue question mark icon appears, like a placeholder waiting to be replaced by the actual icon, then it simply disappear.

Also, despite aving checked the "Launch at startup" flag, it doesn't launch at startup. It never did.

**Comment by mmahmoudian** [comment]
@rsaleri i bet the icon is there, but the color of the icon matches the color of your bar. Somehow it has not detected to use the dark theme icon. Can you try changing the bar color and see if my hypothesis stands?

**Comment by alefvanoon** [comment]
https://i.imgur.com/XPptWlF.png

**Comment by rsaleri** [comment]
> @rsaleri i bet the icon is there, but the color of the icon matches the color of your bar. Somehow it has not detected to use the dark theme icon. Can you try changing the bar color and see if my hypothesis stands?

Oh, yeah, you're right:
![image](https://user-images.githubusercontent.com/33120404/114148505-21312380-991a-11eb-8db9-1bb6c16f72f0.png)

**Comment by mmahmoudian** [comment]
@rsaleri how did you install Flameshot? I think it is good to have that on the record as well.

**Comment by rsaleri** [comment]
@mmahmoudian flatpack via Pop!_Shop

On a side note, it maybe didn't catch the "dark theme" because i set the "light" one in settings:
![image](https://user-images.githubusercontent.com/33120404/114161429-55abdc00-9928-11eb-9b26-30ce6c18c2d4.png)

**Comment by ShurikuS57** [comment]
- Linux Mint 20 Cinnamon
- Flameshot v0.9.0
![screen1](https://user-images.githubusercontent.com/1519692/114261810-65d5c100-99e5-11eb-87c6-fb654aadcac7.gif)

**Comment by cocoonkid** [comment]
I have a issue with the icon in arch xfce.

it just shows as a lightbulb (and syncthing does too).

I remember with my last install it worked without issues.

Any ideas ion how to fix ?

![image](https://user-images.githubusercontent.com/43231640/114405499-09220400-9ba7-11eb-84f2-2fb1ffd1de19.png)

This might be totally unrelated to flameshot itself yes .

**Comment by mmahmoudian** [comment]
@cocoonkid Flameshot uses notification icon (lightbulb) initially when it runs, and then it will change to the flameshot icon, but perhaps on Xfce it cannot switch icon. If I remember correctly though, @borgmanJeremy is planning to remove the lightbulb thingy in the next release.

**Comment by borgmanJeremy** [comment]
Yes the lightbulb will be removed in the next point release

**Comment by cocoonkid** [comment]
@mmahmoudian  Thank you. I am still wondering why it does not change to the native flameshot icon.
I am sure in my preceding arch xfce installation it worked. Will report back when I find what is different now.

**Comment by herrenP** [comment]
> I have a issue with the icon in arch xfce.
> 
> it just shows as a lightbulb (and syncthing does too).
> 
> I remember with my last install it worked without issues.
> 
> Any ideas ion how to fix ?
> 
> ![image](https://user-images.githubusercontent.com/43231640/114405499-09220400-9ba7-11eb-84f2-2fb1ffd1de19.png)
> 
> This might be totally unrelated to flameshot itself yes.
> 
> other apps icons work without problems.

Not sure if you still have this issue but if you install flameshot-git from the AUR then the tray icon works as expected. I had this issue too when using flameshot from community.
