### ISSUE TITLE
[Feature request] Hotkey for each tool: Alt+1, Alt+2, ...

### ISSUE THREAD

**Issue by gmolledaj** [flameshot-org/flameshot#1516]
Atribuu rapidan klavon al ĉiu ilo, Alt + 1 desegnaĵo, Alt + 2 linio, Alt + 3 sago, ... Kaj du klavoj, +/- por ŝanĝi la grandecon de la ilo.
Assign a hotkey to each tool, Alt + 1 drawing, Alt + 2 line, Alt + 3 arrow, ... And two keys, +/- to change the size of the tool.
Asignar una tecla rápida a cada herramienta, Alt+1 dibujo, Alt+2 línea, Alt+3 flecha, ...  Y dos teclas, +/- para cambiar el tamaño de la herramienta.

**Comment by borgmanJeremy** [comment]
This is already supported in the 0.9 release
