### ISSUE TITLE
cannot work, 

### ISSUE THREAD

**Issue by coolksj** [flameshot-org/flameshot#1518]
**Flameshot version**
0.90 x64

**Describe the bug**

Stop on the screenshot, can't pop up the sidebar, can't realize any function, can't continue operation

**To Reproduce**

**Expected behavior**

**System Information**

windows 10 , 20H2

**Comment by mmahmoudian** [comment]
I would appreciate it if you can add some more details. Your description is very general and vague (sounds like a complaint rather than a bug report). I suggest adding some more text and clarify what has happened and how to reproduce the bug and if you can provide some picture (e.g take a photo with your phone from your monitor or use some other screenshot tool).

**Comment by leoneivaw** [comment]
It happens to me. "flameshot gui" freezes the entire system for 10 or 20 seconds. 
The screenshot tool opens but gets inoperant.
Cant hide or minimize flameshot. Have to wait.
It was working on Kubuntu but after installing KDE Neon it doesnt work as spected.
Installing with "sudo apt get" from the repository works pretty well, but is an very old version of flameshot.

I tried snap and flathub. 
(One doesn't even open) -- (Other freezes)

Thanks
Operating System: KDE neon 5.21
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-71-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by mmahmoudian** [comment]
@leoneivaw let me guess, the one from flathub didn't open? As explained on [the website](https://flameshot.org/getting-started/), to open the Flatpak one you should use:

```
flatpak run org.flameshot.flameshot
```

For the freezing, can you confirm that notification works on your system? (you can use `notify-send "aa"` to test)

**Comment by leoneivaw** [comment]
No, 

I am trying here and i figured out I can't open snap using the default installation shortcut. But i can open from command line with sudo: sudo /snap/bin/flameshot

Flatpak - I can open using default shortcut installation or "flatpak run org.flameshot.flameshot". And now i figured out it only freezes when i copy (Ctrl+c or using copy button). I can save, draw or close. 

i hadn't notify-send installed. But after its installation nothing changed.

Thanks again

**Comment by mmahmoudian** [comment]
@borgmanJeremy this issue very much feels like to be related to #1442, especially considering the https://github.com/flameshot-org/flameshot/issues/1442#issuecomment-795644158

There both happened in KDE and both experienced freezing after copying.

**Comment by mmahmoudian** [comment]
@leoneivaw can you try this:

1. In the flameshot config file add: `showDesktopNotification=false`
2. Run flameshot and hit the copy button

**Comment by leoneivaw** [comment]
Sorry. doesn't work.
I have to wait 20 seconds after copying to unfreeze.

**Comment by mmahmoudian** [comment]
@leoneivaw I was helping [someone with some what similar issue](https://github.com/flameshot-org/flameshot/issues/1619) yesterday and I think your issue might be related. Your KDE compositor settings might also be heavier that what your computer can handle (I have the same issue on a laptop). It might be a good idea to check if the freezing issue is resolved by turning off the compositor in KDE.

**Comment by mmahmoudian** [comment]
I'm closing this as it has been stale for over 4 months and it is about an old version. Please consider opening a new issue of you face any problems with the newest version of Flameshot.
