### ISSUE TITLE
Do not copy screenshot path to clipboard

### ISSUE THREAD

**Issue by sws33** [flameshot-org/flameshot#1519]
**Flameshot version**
0.9.0

**Describe the bug**
Do not copy screenshot path to clipboard

**To Reproduce**
1. Select area
2. Press Ctrl-S to save file
3. Check clipboard - nothing

**Expected behavior**
3. Must be a path to saved screenshot file

**System Information**
Debian Buster 64 bit. 
Flameshot is compiled from source

**Comment by mmahmoudian** [comment]
@sws33 can you confirm that in your `.config/flameshot/flameshot.ini` the `copyPathAfterSave` is set to `true`

**Comment by mmahmoudian** [comment]
I confirm that the bug exists in 0.9.0 on AUR version as well.

My `flameshot.ini`
<details>
<p>
[General]
closeAfterScreenshot=false
contrastOpacity=188
copyPathAfterSave=true
disabledTrayIcon=false
drawColor=#00ff00
drawThickness=0
saveAfterCopy=false
saveAfterCopyPath=/home/mehrad/Pictures/Screenshots
savePath=/home/mehrad/Pictures
savePathFixed=false
showDesktopNotification=true
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#fa8c00
</p>
</details>

**Comment by borgmanJeremy** [comment]
@mmahmoudian I can confirm the issue. Something in the notification stack is freezing. Im digging into it.

**Comment by borgmanJeremy** [comment]
Check out the build from #1526 This was in fact that same problem that I don't totally understand. If a clipboard action happens shortly before the dbus call, dbus freezees and time outs. 

If this fixes it for you (works for me) I'll merge it in.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I tried with AppImage with the following sha256sum:
<details>
530123114df329b22e776396cf4693d120f5d50e3efe9f86ca7b94e7d4197aa9
</details>

It works perfect 👍🏼  . The lag and freezing is gone and the path is correctly copied in clipboard.

System info:

<details>
<pre><code>
System:
Host: Chrstphr Kernel: 5.11.6-1-MANJARO x86_64 bits: 64
Desktop: KDE Plasma 5.21.3 Distro: Manjaro Linux
Graphics:
Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
driver: i915 v: kernel
Device-2: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 460.56
Device-3: Sunplus Innovation HD 720P webcam type: USB
driver: snd-usb-audio,uvcvideo
Display: x11 server: X.Org 1.20.10 driver: loaded: modesetting,nvidia
unloaded: nouveau resolution: 1: 1080x1920~60Hz 2: 1080x1920~60Hz
3: 1920x1080~60Hz
OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 460.56
</code></pre>
</details>
