### ISSUE TITLE
Click window to fill selection.

### ISSUE THREAD

**Issue by carnager** [flameshot-org/flameshot#152]
Sometimes one wants to capture a specific window. It would be useful if Flameshot allowed to single click a window which results in an automatic selection. Maybe even add a right click option which selects the whole screen.

**Comment by lupoDharkael** [comment]
This feature will be available probably for the next version. When I have more time to work on adding big features I will work on a computer vision based approach for this.

**Comment by morfikov** [comment]
That's really nice idea to have such option. :)

**Comment by tobias-haenel** [comment]
If the selection would be performed before creating the actual screenshot (like in maim - https://github.com/naelstrof/maim), obtaining the desired window geometry should be easy. At least it would be easier and more reliable then a computer vision approach.

**Comment by AlexWayfer** [comment]
Duplicate of #5.

**Comment by borgmanJeremy** [comment]
Closing as duplicate of #5. We will get this discussed after the 0.8 release.
