### ISSUE TITLE
point where a line / arrow / rectangle starts 

### ISSUE THREAD

**Issue by jmramires** [flameshot-org/flameshot#1520]
When starting a line / arrow / rectangle starts the starting point is not where mouse pointer is, how can I modify this behavior? (If I'm drawing the firs line on the screen, the start point is the bottom right corner)

**Comment by mmahmoudian** [comment]
It should start drawing from where your mouse is. If it is not, it means it is a bug. Therefore please provide your full system information including:
- Flameshot version and how you have installed it from
- operating system and its version
- if you are a Linux user, please checkout this page: https://flameshot.org/issue-reporting/

**Comment by jmramires** [comment]
The "strange" thing it worked before as expected, and at some moment the behavior changed. This is the info from my system: 

root:~# flameshot --version 
Flameshot v0.6.0
Compiled with Qt 5.11.1

root:~# inxi --width 80 --system --graphics
bash: inxi: command not found...

root:~# loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11

root:~# xrandr --listactivemonitors
Monitors: 1
 0: +*eDP-1 1920/309x1080/173+0+0  eDP-1
 
 
root:~# update-pciids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  267k  100  267k    0     0  30398      0  0:00:09  0:00:09 --:--:-- 26799
Done.

root:~# lspci | grep -i 'vga\|3d\|2d'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)

root:~# lshw -class display
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:133 memory:eb000000-ebffffff memory:a0000000-afffffff ioport:e000(size=64) memory:c0000-dffff
       
root:~# uname -a
Linux li-e71697cc-30dc-11b2-a85c-cfbd5a390c8a.ibm.com 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Wed Dec 16 03:30:52 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
First thing first, your Flameshot version is very old. The newest version is 0.9.0 and many things has been improved and fixed. Please try that and see if it still has the issue.

**Comment by jmramires** [comment]
oh ok , thanks I need to check how to install the newest version as this machine has some restrictions, I'll give feedback later

**Comment by mmahmoudian** [comment]
That is easy, try the AppImage. It doesn't need installation. Follow instructions here regarding AppImage:

https://flameshot.org/getting-started/

**Comment by jmramires** [comment]
Great , the Appimage worked and now I have the version 0.9.0 and worked as expected , thanks

**Comment by mmahmoudian** [comment]
I'm glad that it worked 👍🏼
Shall we close this issue?

**Comment by jmramires** [comment]
Yes the issue can be closed, thanks for your help!
