### ISSUE TITLE
No Text tool

### ISSUE THREAD

**Issue by andim27** [flameshot-org/flameshot#1525]
**Flameshot version**

Flameshot 0.5.1-1(debian)
There is not Text(T) button(tool)
**System Information**
 Linux Mint 19.1

**Comment by borgmanJeremy** [comment]
Please retest on the latest release (At this time it is 0.9.0) You can install via snap, flatpak, appimage, source, or .deb.

**Comment by borgmanJeremy** [comment]
How did you originally install it?

**Comment by andim27** [comment]
apt install ...

**Comment by borgmanJeremy** [comment]
Remove it through apt. Then reinstall with snap, flat pan, app image etc

**Comment by hosiet** [comment]
You have another choice of upgrading to a newer release of Linux Mint. Mint 19.1 is based on Ubuntu 18.04 and features software dated back in 2018. Upgrading to a newer Linux Mint release (e.g., 20.1) will bring the system to be based on Ubuntu 20.04, which is still not ideal but at least much more recent.
