### ISSUE TITLE
«Undo» action hotkey is not working

### ISSUE THREAD

**Issue by ExposedCat** [flameshot-org/flameshot#1528]
**Flameshot version**
flameshot/unstable,now 0.9.0+ds1-1

**Describe the bug**
Ctrl+Z does nothing instead of undoing the last action

**To Reproduce**
Take screenshot, draw arrow and press Ctrl+Z

**Expected behavior**
Arrow removed

**System Information**
OS: Debian SID
DE: GNOME 3.38

**Comment by mmahmoudian** [comment]
Can you post here the content of the Flameshot config file (`~/.config/flameshot/flameshot.ini`)

**Comment by thepurple** [comment]
One more point to check is layout. There is a known issue with hotkeys in non-latin layouts.
It wasn't fixed if I'm not mistaken.

**Comment by ExposedCat** [comment]
@mmahmoudian 
![image](https://user-images.githubusercontent.com/44642024/113296757-8c6b6c00-9302-11eb-8a07-40cc4063d4c8.png)
Whole config: https://paste.debian.net/1191979/
I tried to use it with RU and EN layouts. Before update i was able to use both, now neither RU nor EN is not working.

**Comment by ExposedCat** [comment]
Ahahaha, it works on any layout after i added `TYPE_UNDO=Ctrl+Z`. Maybe update removes this line.

**Comment by mmahmoudian** [comment]
@ExposedCat super interesting, you don't have the undo in GUI config and not in the config file! I wonder if it is caused by manual manipulation of the config file (accidentally removing that line) or some bug.

I suggest you uninstall Flameshot, remove config file, and install it back again (in case you want your configs, backup the file and later diff it with the new config file)

**Comment by ExposedCat** [comment]
@mmahmoudian i did not do any modifications myself. Only `apt install flameshot` to update it

**Comment by mmahmoudian** [comment]
Installing Debian (stable) has took over an hour on VM that I'm giving up reproducing it. Sorry.

**Comment by mmahmoudian** [comment]
I finally managed to installed Debian Gnome. considering that the Debian does not have v0.9.0 in official repo, I compiled the latest version here and yet couldn't reproduce this issue.

![image](https://user-images.githubusercontent.com/390889/115959309-4b870180-a514-11eb-9cfd-0b7cbdf6e5b6.png)

**Comment by ExposedCat** [comment]
@mmahmoudian idk what it was :)
