### ISSUE TITLE
Add send e-mail button

### ISSUE THREAD

**Issue by jose1711** [flameshot-org/flameshot#1534]
A feature I am using a lot on Windows with Snipping Tool is "Send Snip" which basically stages an e-mail with the current screenshot as an attachment and a pre-filled subject (`Sent from Snipping Tool`). If I were to replace Snipping Tool with flameshot completely I would need to use clipboard and it would require more clicking and typing.

Therefore I'd welcome if similar feature makes its way to flameshot.

**Comment by borgmanJeremy** [comment]
You are on windows?

If so this is actually a duplicate of #1309 

Once that is fixed it lets you open the image directly in the email client after taking the screenshot.

**Comment by jose1711** [comment]
Yes, sometimes I am working with Windows. Closing as duplicate.
