### ISSUE TITLE
Doesn't capture screenshot with Right Mouse Button menu open

### ISSUE THREAD

**Issue by k-slava** [flameshot-org/flameshot#1536]
**Flameshot version**
V.0.9.0

**Describe the bug**
It is imposible to take screenshot if menu from Right Mouse Button open.

**To Reproduce**
1. Setup taking screenshot with Flameshot on PrtSc button.
2. Press Right Mouse Button somewhere where it leads to contects menu. For example, press on desktop.
3. Now press PrtSc button - nothing happend.

**Expected behavior**
Step 3: Now press PrtSc button - the screenshot has taken.

**System Information**
Linux Mint 20.1 Cinnamon 4.8.6

**Comment by borgmanJeremy** [comment]
Unfortunately this is not something we can fix, as it is handled by the desktop environment. IE its not passing on the printscreen hotkey when the menu is open. The best work around is to use the "launcher" to set a few second delay, and then open the menu you want to screenshot.

**Comment by k-slava** [comment]
> The best work around is to use the "launcher" to set a few second delay, and then open the menu you want to screenshot.

Could you please help me with settings? I am with Linux for the second week.
I understand that I need to create a "launcher" with delay command, put it into menu and assign the shortcut on it. But could you help me with command?

**Comment by borgmanJeremy** [comment]
Sure, if you right click the icon in the systray you should see a menu come up, on that menu there is a button that says "open launcher". That gives you an option to set a delay. Let me know if that doesnt work.

**Comment by k-slava** [comment]
> I understand that I need to create a "launcher" with delay command, put it into menu and assign the shortcut on it.

I see. I understood it wrongly. You can open "launcher" by RMC on the flameshot. It is simple. Thanks!

**Comment by k-slava** [comment]
> right click the icon in the systray

Yep, found it too. Thank you, it works!
