### ISSUE TITLE
Mac OSX Dual external monitors: when trying to take screenshot flameshot only shows empty desktop for selection

### ISSUE THREAD

**Issue by AlexYoOS** [flameshot-org/flameshot#1537]
**Flameshot version**

flameshot.dmg - Mac OS distro

**Describe the bug**

When trying to take a screenshot, all opened applications go away and only the blank desktop is visible for selection:
<img width="2560" alt="Screenshot 2021-04-06 at 22 50 01" src="https://user-images.githubusercontent.com/46506824/113776925-bc63a680-972a-11eb-9353-8ab032c6d019.png">

My background is black, which is why it is all black, if I change the background colour, it will be that colour.

I have also tried to use flame shot on in-built MacBook display, but its the same, even without the monitors

**To Reproduce**

1. Open flameshot on Mac OS BigSur
2. Try taking a screenshot with flameshot
3. 
**Expected behavior**

I expected to be allowed to select and area of the active monitor and its opened windows and applications.

**System Information**

MacOS BigSur

**Comment by borgmanJeremy** [comment]
Did you give flameshot security permissions to record your desktop?

**Comment by AlexYoOS** [comment]
Of course, it was not given permission, not its working fine, thank you Jeremy!

**Comment by AlexYoOS** [comment]
Of course, it was not given permission before, now it is working fine, thank you Jeremy!
