### ISSUE TITLE
Error on uploading to Imgur «Error transfering - server replied: nginx»

### ISSUE THREAD

**Issue by adem4ik** [flameshot-org/flameshot#1542]
**Flameshot version**
v0.9.0

**Describe the bug**
Error on uploading to Imgur. It doesn't happen everytime. Only for 1-2 hours everyday. Last time it was 2020.04.08 11:17 UTC
![image](https://user-images.githubusercontent.com/4707112/114018096-ee395200-987d-11eb-828f-fa1785e21f6b.png)

**To Reproduce**
- make a screenshot
- upload to imgur

**Expected behavior**
screenshot is uploaded to Imgur sucessfully

**System Information**
Windows 10 x64

**Comment by abskill** [comment]
Some times I have the same problem

**Comment by borgmanJeremy** [comment]
@mmahmoudian Do you have the ability to check if we are hitting the Imgur daily API limit?

**Comment by borgmanJeremy** [comment]
After discussion with @mmahmoudian our best guess is we are hitting the hourly imgur limit. In the next release we will allow uses to use thier own imgur API key.

**Comment by theTestingApproach** [comment]
Hello,

Having the same issue.Any solutions pls.
thanks

**Comment by mmahmoudian** [comment]
@theTestingApproach The solution is to wait for the next version of Flameshot in which you can use your own imgur API key.

**Comment by nurgasemetey** [comment]
> Hello,
> 
> Having the same issue.Any solutions pls.
> thanks

Copy selection, go to imgur and paste. It will automatically create image.

**Comment by nurgasemetey** [comment]
> Hello,
> 
> Having the same issue.Any solutions pls.
> thanks

Copy selection, go to imgur and paste. It will automatically create image

**Comment by online** [comment]
@nurgasemetey Unfortunately, I can’t copy the link in Linux Mint :(

**Comment by mmahmoudian** [comment]
@online I think what @nurgasemetey meant was that copy the image, open browser, got to imgur, click on the + green button from top of the page and paste the screenshot you copied.

**Comment by changchichung** [comment]
can we can use own  own imgur API key now ?
I just clone from github and compile flameshot 
now my flameshot is version V11.0.0 (aa6b5ea)
but I can not find any option in settings to config my own imgur API key ???
