### ISSUE TITLE
Screenshot menu with dual screen

### ISSUE THREAD

**Issue by Mibou** [flameshot-org/flameshot#1545]
**Flameshot version**
v0.9.0

**Describe the bug**

In dual screen mode, the menu is moved to first screen

**To Reproduce**

Plug a second screen and take a screenshot on second screen

**Expected behavior**

The menu should appear around the screenshot zone as usual :

![image](https://user-images.githubusercontent.com/1668996/114038049-d2d04600-9881-11eb-92e0-8b3789a4acc0.png)

But appears on first screen upper left corner.

![image](https://user-images.githubusercontent.com/1668996/114038063-d5cb3680-9881-11eb-8965-136ffef7bdd3.png)

**System Information**

Windows 10

**Comment by mmahmoudian** [comment]
Duplicate of #1440
