### ISSUE TITLE
有考虑增加录屏（gif或者mp4)，OCR识别 功能么？

### ISSUE THREAD

**Issue by aoeiuv-liu** [flameshot-org/flameshot#1546]
**Is your feature request related to a problem?**

**Comment by mmahmoudian** [comment]
Translation:
> Have you considered adding screen recording (gif or mp4) and OCR recognition functions?

**Comment by mmahmoudian** [comment]
Flameshot is an screenshot tool. For gif and mp4 I can suggest you to use [peek](https://github.com/phw/peek).
As for OCR, it has been discussed and implemented. I'll find the link and update this sentence.
