### ISSUE TITLE
Even smaller thickness and ghosting after undo

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1547]
**Flameshot version**
Flameshot 0.9.0 (instaleed via Manjaro official repository)

**Describe the bug**
when the minimum thickness is defined as zero, while drawing the line we still can go below that by scrolling while the left-click is pressed and we are drawing the line. 
This also causes some ghosting of the line when the undo is pressed.
This only happens when <kbd>Ctrl</kbd> is pressed while drawing the line and only when drawing horizontal or vertical lines. When drawing diagonal lines while pressing <kbd>Ctrl</kbd>, the ghosting does not happen but still we can go to smaller thickness.

![Peek 2021-04-09 13-15](https://user-images.githubusercontent.com/390889/114166263-2dc37500-9936-11eb-949a-e49fe5ee6c1e.gif)

**To Reproduce**
1. Flameshot 0.9.0
2. `flameshot gui`
3. before anything, just scroll down to make sure the thickness is set to zero (check from the top-left indicator circle)
4. select the line tool
5. hold down <kbd>Ctrl</kbd> and draw horizontal or vertical line
6. press undo

**Expected behavior**
1. cannot go below the zero theickness
2. ghosting doesn't happen

**System Information**
> ```
> System:
>   Host: precisiontower Kernel: 5.9.16-1-MANJARO x86_64 bits: 64
>   Desktop: KDE Plasma 5.21.3 Distro: Manjaro Linux
> Graphics:
>   Device-1: Intel driver: i915 v: kernel
>   Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
>   Display: x11 server: X.Org 1.20.10 driver: loaded: amdgpu,ati,intel
>   unloaded: modesetting resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
>   OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.39.0
>   5.9.16-1-MANJARO LLVM 11.1.0)
>   v: 4.6 Mesa 20.3.4
> ```

**Comment by thepurple** [comment]
Check it on the latest master branch, please. Undo/redo stack is completely new now.

**Comment by mmahmoudian** [comment]
I confirm that a clean build from master (commit `55e61b8`) works just fine :+1: . I also realized that the thickness does not go below 1 (previously it used to go to 0) which I think was your workaround (haven't checked the code yet).
