### ISSUE TITLE
[Question] How do I use keybinds?

### ISSUE THREAD

**Issue by Dragonizedpizza** [flameshot-org/flameshot#1550]
I want flameshot to take a screenshot and copy it to my clipboard when I use `alt` + `shift` + `s` together. How do I do that?
Sort of like how Ubuntu's default screenshot tool works.
![image](https://user-images.githubusercontent.com/70718540/114342741-a86dd980-9b5c-11eb-9dd0-c02f3cc6d5f2.png)

Along with that, how do I upload the image to my own custom server?

**Comment by Dragonizedpizza** [comment]
I also want flameshot to take a screenshot and send it to my upload server when I use `alt` + `shift` + `w` together. How do I do that?

**Comment by mmahmoudian** [comment]
Perhaps it is better to mention what operating system you are using.

Assuming that you are on Linux, bind a keybinding to `flameshot gui -c` to copy to clipboard. Alternatively, if you don't mind using keyboard shortcuts in Flameshot, you can also use <kbd>Ctrl</kbd>+<kbd>c</kbd> to copy the selection to clipboard, <kbd>Ctrl</kbd>+<kbd>s</kbd> to save to disk and so on and so forth. You can change the keyboard shortcuts of Flameshot from the configurations (right click on the tray icon)

As for uploading to imgur, I don't think there is a command line flag, but you can create a keyboard shortcut to upload to imgur while you are in `flameshot gui` (in the mode that you can select the region of your screen).

**Comment by Dragonizedpizza** [comment]
I am using Ubuntu.

Also, I do not want to upload to imgur, I want to upload to my own server, via a script someone made.

![image](https://user-images.githubusercontent.com/70718540/114366061-5daf8a00-9b7b-11eb-9d36-1aeca2347d4e.png)

**Comment by Dragonizedpizza** [comment]
I'm not really sure where to put that script though

**Comment by mmahmoudian** [comment]
@Dragonizedpizza The scrip is a bash script. Save it in a file somewhere on your system (for example `~/my_scripts/my_flameshot_uploader.sh`), the add the following line to the beginning of that file:
```
#!/usr/bin/env bash
```

Then create a keyboard shortcut to run your script via `bash ~/my_scripts/my_flameshot_uploader.sh`. The script automatically opens Flameshot for you and then upload it.
Remember to add your password to that script.

**Comment by Dragonizedpizza** [comment]
yep, thanks!
