### ISSUE TITLE
Unable to take screenshot after switching from gnome3 to i3-gaps

### ISSUE THREAD

**Issue by tcdude** [flameshot-org/flameshot#1555]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
The tray icon loads up and is responsive. I can also configure flameshot just fine, the only thing that doesn't work is running `flameshot gui` doesn't mask the screen and it doesn't let me select an area on the screen.

When I run `flameshot` in a terminal to get it's output, these messages appear upon launch:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
```
and this is the output I get as soon as I try to capture a screenshot both when using the `flameshot gui` command or using the tray icon:
```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

PS *I made sure that i3 is being launched with dbus-launch as described in the FAQ*

**To Reproduce**

Unfortunately I can't make out the problem why this isn't working. On the exact same setup, just with gnome3 it worked perfectly fine. The only difference is that I switched from gnome to i3-gaps. I'm happy to provide further information if instructed what sort of information could be helpful.

**Expected behavior**
The usual behavior of flameshot, let me select an area, decorate it and copy to clipboard or save it.

**System Information**

Manjaro (kept up to date) running i3-gaps using GDM
`Linux tcdev 5.11.10-1-MANJARO #1 SMP PREEMPT Thu Mar 25 17:14:55 UTC 2021 x86_64 GNU/Linux`

**Comment by tcdude** [comment]
Is there maybe a way to start flameshot to output more verbose information?
When I start it, I get the tray icon and if I then try to use the launcher I can grab and save a screenshot of the entire screen. The only thing that doesn't work and silently fails is to grab a rectangular region.

**Comment by mmahmoudian** [comment]
Just to confirm my understanding of your steps:
1. you open a terminal and run `flameshot` and you get the tray icon
2. you open a new terminal and run `flameshot gui` 

If the above is not correct, please try it and then let me know what messages do you get in each of those terminals.

**Comment by tcdude** [comment]
Yes, this is correct. And the messages are listed in the first post of this issue. To be clear, any call to `flameshot gui` does not result in any output whatsoever in it's own terminal, it simply instantly exits. Only the `flameshot` command is giving me output, which is what I listed in the first post of this issue, split up in what is being output right at launch of it and the second part appears when I try to grab a screenshot using `flameshot gui`.

**Comment by tcdude** [comment]
I just figured it out myself. I had a multi monitor configuration from my previous setup before I switched to i3 and my now single monitor had still an offset, which apparently tripped flameshot up. Resetting the position to 0x0 did the trick.

Sorry for the waste of your time!

**Comment by mmahmoudian** [comment]
@tcdude it is not waste of time, it is education for us(at least for me) and also for other people who have the same issue and will find this issue in future. Thanks for reporting back. I would be thankful if you can elaborate more on how you setup your monitor offset in i3 (presumably in arandr?)

**Comment by tcdude** [comment]
@mmahmoudian sure, happy to elaborate further:

I use xrandr and I had a straggling xorg config file (seemingly something related to Manjaro/mhwd) that still had a line in it to activate the configuration I had before I removed 3 of my 4 displays.

The file in question can be found at `/etc/X11/xorg.conf.d/90-mhwd.conf` and did override my `xorg.conf` that is located one folder up (i.e. `/etc/X11/xorg.conf`). The remaining monitor wasn't set at position 0x0, which was the reason that threw flameshot off from what I could make out. The configuration thus also wasn't specific to i3 but rather a X11 specific setting, combined with the binary blob driver from nvidia under Manjaro, which is installed using the `mhwd` tool, found in every Manjaro distribution.

**Comment by borgmanJeremy** [comment]
Since you are on Manjaro install flameshot-git from the aur. We fixed the issue but have not issued a new release with the fix.

**Comment by johnjacobkenny** [comment]
Great, thanks!
