### ISSUE TITLE
Crosshair disappears and is not visible

### ISSUE THREAD

**Issue by munkiwarra** [flameshot-org/flameshot#1557]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
Crosshair not visible.
The Crosshair to select the area of the screen disappears after a millisecond. The colors on right-click and icons around the area as well as "Tool Settings" text are visible.
I recently switched back to gdm, after screenlock issues with lightdm, so this might be related, but appart from flameshot I have no problems with icons or cursors.

**To Reproduce**
I do not know how to reproduce this bug

**Expected behavior**
flameshots crosshair is visible for selection on screen.

**System Information**
Manjaro Linux
GNOME 40
X11

**Comment by mmahmoudian** [comment]
Can you record your screen (for example using [peek](https://github.com/phw/peek)). I'm not sure if I understood what you mean.

**Comment by munkiwarra** [comment]
![flameshot](https://user-images.githubusercontent.com/35305597/114616614-5daca880-9ca7-11eb-8804-731e01512a53.gif)

Weirdly enough I did not see the cursor (crosshair, grab, pointer) when I recorded the screen, but on the gif they are visible.
I tried to reproduce again, but everytime I start peek the crosshair is now visible again.

Well, at least now I know how to bring them back whenever they disappear.
I'll be back if this comes back again permanently.

Thank you for your unintentional tip ^^

**Comment by mmahmoudian** [comment]
😂😅 glad that I could be helpful

But we have had people reporting some visual things that they didn't manage to reproduce when recording the screen. I don't really know what the issue can be.

Please reopen this when ever you got more info on how to reproduce it or even if it got hidden permanently or ...
