### ISSUE TITLE
Can't start flameshot.

### ISSUE THREAD

**Issue by Nemirtingas** [flameshot-org/flameshot#1558]
Hi, I'm on a Ubuntu 18.04.5 LTS with gnome3 and I can't start flameshot. I installed it with the command: 
`snap install flameshot` and it installed the version: `flameshot v0.9.0.rc2+git33.856e08a`.

When trying to launch it with my user, it got this error: 
```
flameshot 
cannot create user data directory: /home/username/snap/flameshot/77: Permission denied
```

The folder tree/rights are like this:
```
drwxr-xr-x 3 username activedirectoryusers 4096 avril 14 07:27 snap
drwxr-xr-x 4 username activedirectoryusers 4096 avril 14 07:28 snap/flameshot
lrwxrwxrwx 1 username activedirectoryusers 2 avril 14 07:27 snap/flameshot/current -> 77
drwxr-xr-x 2 username activedirectoryusers 4096 avril 14 07:28 snap/flameshot/77
drwxr-xr-x 2 username activedirectoryusers 4096 avril 14 07:27 snap/flameshot/common
```

For now, I use flameshot 0.5.1 installed with `apt`, it works fine.

Any idea ?

**Comment by mmahmoudian** [comment]
Might be relat6ed to #1144.

**Comment by lflucasferreira** [comment]
Same here.
