### ISSUE TITLE
Clipboard save from CLI in a GUI mode

### ISSUE THREAD

**Issue by kaldown** [flameshot-org/flameshot#1559]
I want to have the same `--clipboard` feature when making rectangle selection (`flameshot gui`) and not click on an "copy" incon every time.

**Comment by mmahmoudian** [comment]
It is already implemented. Use `Flameshot gui -c`.

**Comment by kaldown** [comment]
No, it's not
```
➜  ~ flameshot gui -c
the option 'c' is not a valid option for the argument 'gui'. See flameshot --help.
➜  ~ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2
➜  ~
```

**Comment by mmahmoudian** [comment]
I have to check it out as as far as I remember it should work, but for now you can use <kbd>Ctrl</kbd>+<kbd>c</kbd>.

**Comment by mmahmoudian** [comment]
I just checked, you are right, the `-c` is not implemented for the `flameshot gui` at least according to the `flameshot gui --help`

**Comment by Anu-bhav** [comment]
Hi, I was searching for this exact issue else i would have posted it myself.

@mmahmoudian hello, is this feature going to be in the next release?

**Comment by mmahmoudian** [comment]
@Anu-bhav I'm not sure, but considering that it is still easily doable with existing flags and shell, I suggest you try that for the time being:
```sh
flameshot gui -r | xclip -select clip
```

(I'm typing this one the phone and might have a typo in the xclip argument. Check if with `man xclip`)

**Comment by kaldown** [comment]
> @Anu-bhav I'm not sure, but considering that it is still easily doable with existing flags and shell, I suggest you try that for the time being:
> 
> ```shell
> flameshot gui -r | xclip -select clip
> ```
> 
> (I'm typing this one the phone and might have a typo in the xclip argument. Check it with `man xclip`)

it won't work as well as `-c` or clicking `copy` icon.
I.e. it won't persist in a buffer for pasting in other GUI.
Using i3wm (for instance)

**Comment by kaldown** [comment]
https://github.com/chhajedji/scripts/blob/master/screenshot.sh#L31

that could be solution.
Still would be quite nice to have that option by default without moving too much of an ad-hoc solutions.

**Comment by mmahmoudian** [comment]
I wrote my previous comment on my phone and I couldn't test it on the spot. The idea was just to point you at the right direction (`man xclip`).

So as the @kaldown pointed out, the command should look like:
```sh
flameshot gui -r | xclip -in -selection clipboard -target image/png
```

**Comment by mmahmoudian** [comment]
Perhaps when #1531 is addressed, the experience of `-r` would be improved and will be less confusing.

**Comment by Anu-bhav** [comment]
Hello, @mmahmoudian @kaldown 👋

Actually I wanted flameshot to act like window's snipping tool. For example when I select an area, upon mouse click release, it will be automatically placed in my clipboard. I've even mapped `flameshot gui` to `win+shift+s`

I've tried `flameshot gui -r | xclip -in -selection clipboard -target image/png` and it's not working like snipping tool.

Then I realised that flameshot is used for quick editing on the selected area itself, hence it does not disappear immediately.  However I'll be using this feature in certain use cases so i've mapped `flameshot gui` to `win+shift+a`.

And for the snipping tool behaviour, I'm using `xfce4-screenshooter`. 
I've mapped `xfce4-screenshooter --window --clipboard` to `win+shift+s` .

This works well for my use case.
However if in future, flameshot gets the clipboard function, i'll replace `xfce4-screenshooter`.

**Comment by kaldown** [comment]
Same thing here.
Thats why adding `Return` was crucial for me.
Since it's natural to select and instantly hit Enter.

Also want `scroot` like functionality to just save/copy selected area without questioning.

**Comment by mmahmoudian** [comment]
@Anu-bhav do you know that you can run `flameshot gui`, then select the area you want and then hit <kbd>Ctrl</kbd>+<kbd>c</kbd> to copy to clipboard?

**Comment by Anu-bhav** [comment]
@kaldown @mmahmoudian yes I used to do it like that, but I was not satisfied as I usually take multiple screenshots at once. Each time I have to hit `ctrl c`, sometimes I just wanted to select an area and it copied automatically. @kaldown I don't even like to hit `enter`, I just want to select and upon release, it copies it to my clipboard.

Actually I use `copyq` so I can copy a bunch of things at once(text, screenshots) and I just paste them in the order I want when doing a report same as in windows. I've also mapped `copyq toggle` to `win+v`.

For now, i'm satisfied doing it like this. It is same as in windows and I'm used to using it like this. If i need to modify the screenshot, I just use `win shift a` as it is mapped to `flameshot gui`.

**Comment by Anu-bhav** [comment]
@kaldown however flameshot is faster, I find that `xfce4-screenshooter` is a bit slower to launch when I trigger the bind.

**Comment by mmahmoudian** [comment]
@Anu-bhav Then I think you will be satisfied by #1576 in combined with this (#1559)

**Comment by Anu-bhav** [comment]
@mmahmoudian YESSSS, if we can have some arguments like --clipboard as in #1576 combined with an argument that does not require any additional keypress, it will be perfect for me. 

![image](https://user-images.githubusercontent.com/41940586/115879132-5f6e2d00-a45a-11eb-9233-0bcb8f9e24f0.png)
for this screenshot, I'm using xfce-screenshooter as I do not need to modify it. It is mapped to `win shift s`

![image](https://user-images.githubusercontent.com/41940586/115879339-980e0680-a45a-11eb-903c-38ae40d3812d.png)
and this one is using flameshot as I added the box and it is mapped to `win shift a` and after modifying it, I just use `ctrl c` to copy it.

![image](https://user-images.githubusercontent.com/41940586/115879627-ef13db80-a45a-11eb-933b-56696650aa0a.png)
This is the clipboard I was talking about, copyq.

**Comment by fsevenm** [comment]
My workaround, 

![image](https://user-images.githubusercontent.com/29963765/129828586-dc8bd073-295c-4f9b-aad6-d5609ea6669a.png)

Set `Enter` as a shortcut for copy to clipboard instead of `Ctrl` + `C`.

![image](https://user-images.githubusercontent.com/29963765/129828867-20308fd4-6b09-4ef6-9e22-d0c01f2925c8.png)

Call `flameshot gui`, hit `Enter`, and there you go.

**Comment by veracioux** [comment]
Can this be closed now?
