### ISSUE TITLE
Consider adding support for XDG Portal screenshot API

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#156]
Making screenshot under Wayland is known messy. We know that flameshot has provided desktop-specific experimental support for Wayland + GNOME and Wayland + KDE. However, there is indeed an effort in providing a desktop-agnostic method of taking screenshot under Wayland (of course, via D-Bus).

There will be a [org.freedesktop.portal.Screenshot](https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.portal.Screenshot.xml) interface available if the user installs package `xdg-desktop-portal` on system. At least [GIMP has added support for it](https://www.phoronix.com/scan.php?page=news_item&px=GIMP-FreeDesktop-Screenshot-API). It would be another highlighted feature if flameshot is to support it as well.

**Comment by borgmanJeremy** [comment]
The issues with xdg-desktop-portal is it gives the user an additional prompt. If the DE supports an API that avoids this addition prompt I would like to use that instead. 

We just merged the xdg-desktop-portal version for sway only since it did not have a DE specific version.
