### ISSUE TITLE
Flameshot from Flatpak doesn't work on wayland

### ISSUE THREAD

**Issue by g7fernandes** [flameshot-org/flameshot#1560]
**Flameshot version**
0.9

**Describe the bug**
If you install flameshot from the flatpak package (currently on commit 148feac) and try to use on wayland (`flatpak run org.flameshot.Flameshot gui`), the GUI fails to start with  and a popup with  *Unable to capture screen*  pops up. 

**To Reproduce**
Install the flatpak package
```
flatpak install flathub org.flameshot.Flameshot
```
Login on a Wayland session. Any of these commands will fail to start the GUI:
```
flatpak run org.flameshot.Flameshot gui
QT_QPA_PLATFORM=xcb flatpak run org.flameshot.Flameshot gui
QT_QPA_PLATFORM=wayland-egl flatpak run org.flameshot.Flameshot gui
```

**System Information**

OS: openSUSE Tumbleweed 
Kernel: 5.11.12-1-default
DE: GNOME 40.0 
WM: Mutter

Note: Also doesn't work on Gnome 3.38. 

By downloading with zypper from OpenSUSE repos, it works.

**Comment by asamofal** [comment]
I guess I have the same problem here... 

```
$ flatpak run org.flameshot.Flameshot
Qt: Session management error: None of the authentication protocols specified are supported
```

Ubuntu 21.04
GNOME Shell 3.38.4
Flatpak 1.10.2
Linux kernel 5.11.0-16-generic
Wayland 3.38.4

**Comment by oshanz** [comment]
I'm also using the opensuse tumbleweed. DE is KDE plasma 5.22. installed the flamshot using zypper and the version is 0.9
app is working fine when login in using x11 but not through the wayland session.

**Comment by borgmanJeremy** [comment]
Since that change is now merged I will close this.
