### ISSUE TITLE
Incomplete Menu

### ISSUE THREAD

**Issue by Dragonizedpizza** [flameshot-org/flameshot#1562]
When I click on the flameshot screenshot in the system tray, I get only these 2 options, while I remember some time ago that flameshot had an entire menu which take screenshot and such.

OS: ZorinOS (essentially Ubuntu 18.04)
![image](https://user-images.githubusercontent.com/70718540/115104964-624db700-9f5c-11eb-8279-576f0b233993.png)

**Comment by Dragonizedpizza** [comment]
Installed via aptitude, `sudo apt install flameshot`

**Comment by ZetaoYang** [comment]
> 
> 
> Installed via aptitude, `sudo apt install flameshot`

Try the latest flameshot from github release, please.

**Comment by mmahmoudian** [comment]
@Dragonizedpizza let us know if it works. If it doesn't, please provide your system information as was instructed in the bug report template.

**Comment by Dragonizedpizza** [comment]
yea, nevermind. looks like the version on aptitude is just old.

**Comment by mmahmoudian** [comment]
@Dragonizedpizza shall we close this issue?

**Comment by Dragonizedpizza** [comment]
Yeah, thanks for the help. 
Also, you should update the version on apt.

**Comment by mmahmoudian** [comment]
The versions on Linux distributions are not managed by us. They are managed by those distros. You should ask them or:
1. Update your Ubuntu to the latest (but in a year it will fall behind again and you ahould update the Ubuntu again)
2. Move to a rolling release distro (e.g Manjaro, Arch, Solus, OpenSUSE Tumbleweed) as they tend to update packages more frequently
3. Use one of the things we manage:
    - Snap (`snap install flameshot`)
    - Flatpak (`flatpak install flathub flameshot`)
    - AppImage

For all the above, checkout:

https://flameshot.org/getting-started/

**Comment by s-ayush2903** [comment]
Hi @mmahmoudian can you please add reference to trailing comment of yours(https://github.com/flameshot-org/flameshot/issues/1562#issuecomment-821798313) and directly downloading the latest package(from [releases](https://github.com/flameshot-org/flameshot/releases/) section of the repository) for ubuntu distros somewhere in readme(maybe appending it inside braces of the `ubuntu 18.04+` bullet?(kinda [permalink](https://github.com/flameshot-org/flameshot#packages-from-repository))). 
It'll make things easier for other people :)

**Comment by mmahmoudian** [comment]
@s-ayush2903 how about this: https://github.com/flameshot-org/flameshot-org.github.io/pull/23

**Comment by s-ayush2903** [comment]
Yes that is totally exhaustive regarding this `incomplete menu` issue, even better. But what I intended to convey was:
> The versions on Linux distributions are not managed by us. They are managed by those distros' maintainers.

I didn't know this(and you can ignore all text ahead, if this info is very common). And being unaware of this fact, I used `apt` for installing flameshot(yesterday, on Ubuntu 18.04) and got an older version of it, then before filing an issue here, I searched this in existing issues and landed here :P

And btw, in the PR you linked, in the final rendered version of troubleshooting.md(to be precise, [here](https://github.com/mmahmoudian/flameshot-org.github.io/blob/master/docs/guide/troubleshooting.md#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection)), the images you linked, ain't being rendered as expected(you can ignore, If you were aware of this and planned to fix it in some upcoming commit)

**Comment by mmahmoudian** [comment]
@s-ayush2903 please check again the same pull request, I added some more text in the linux installation page.

**Comment by s-ayush2903** [comment]
Thanks a lot! It clarifies everything.
