### ISSUE TITLE
I can't take a screenshot after switching from Manjaro with X11 to Arch with Wayland

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1564]
**Flameshot version**
0.9.0

**Describe the bug**
I just can't take a screenshot,if I press the shortcut or click on the flameshot icon,then nothing happens.

**To Reproduce**
Try to make a screenshot

**Expected behavior**
That it works

**System Information**
Arch Kde Wayland

**Comment by borgmanJeremy** [comment]
Check out #1380 and #1330 

I have not tested it yet, but others say it works. We need to fix the appimage build and then I can merge it to main. If you are able to test the PR build that would be helpful.

I am going to close this issue since it is documented elsewhere.
