### ISSUE TITLE
Cannot run flameshot

### ISSUE THREAD

**Issue by Mango0x45** [flameshot-org/flameshot#1567]
**Flameshot version**
```
[thomas@mango-os build $] flameshot -v
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**Describe the bug**
I am unable to run flameshot. I have tried downloading it from the AUR and building from source. When running `flameshot gui` or `flameshot launcher` etc. the program just doesn't launch. When running `flameshot` I get this output:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
```

**To Reproduce**
Install flameshot and try to run it from the terminal.

**Expected behavior**
I want flameshot to launch so I can take a screenshot.

**System Information**
Arch Linux
Kernel 5.11.15-arch1-2

**Comment by mmahmoudian** [comment]
What is your Desktop Environment or your Window Manager?
Additionally, please make sure that you have a notification daemon (e.g `dunst`) and `dbus` installed.
You can confirm if your notification daemon works via `notify-send "test"` and seeing the notification popping up.

**Comment by lucasgcb** [comment]
On Ubuntu 20.04.2, installed it through Snap today and it simply hands when running `flameshot` or abruptly closes with `flameshot gui`.

`notify-send "test"` works and flameshot doesn't call it.

**Comment by mmahmoudian** [comment]
@lucasgcb I think your issue might be different from @Mango0x45, but please provide us the messages you get in terminal when you run `flameshot`

**Comment by lucasgcb** [comment]
> @lucasgcb I think your issue might be different from @Mango0x45, but please provide us the messages you get in terminal when you run `flameshot`

Hi, thanks for the reply. I restarted my computer to try this out and it works now. :+1:

**Comment by Mango0x45** [comment]
> What is your Desktop Environment or your Window Manager?
> Additionally, please make sure that you have a notification daemon (e.g `dunst`) and `dbus` installed.
> You can confirm if your notification daemon works via `notify-send "test"` and seeing the notification popping up.

I have both `dunst` and `dbus` installed and running. My window manager is DWM.

**Comment by SCOTT0852** [comment]
I'm having the same issue, my notification thing is tiramisu. I'm using i3-gaps on Arch.
Here's what the various flameshot commands give as output:
![image](https://user-images.githubusercontent.com/33875157/115493154-0ca53300-a218-11eb-9cbb-8575df10327d.png)
For what it's worth I don't seem to be getting any notifications from polynotifications (which is basically a tiramisu frontend for polybar), but running "killall tiramisu" and then starting tiramisu in a terminal shows that it does receive the notification from "notify-send "test"".

**Comment by mmahmoudian** [comment]
@Mango0x45 since DWM by default doesn't have systray and as mentioned in the FAQ [Flameshot needs systray](https://flameshot.org/faq/#flameshot-doesnt-start-no-tray-icon) can you confirm that you have a writing systray (what I used to use with my DWM was [stalonetray](https://wiki.archlinux.org/index.php/Stalonetray))


@SCOTT0852 when you run `flameshot`, do you see the icon in your polybar tray area?

**Comment by SCOTT0852** [comment]
> @SCOTT0852 when you run `flameshot`, do you see the icon in your polybar tray area?

As far as I'm aware Polybar isn't actually a systray, just a status bar (I was unaware Flameshot required one). Replacing it with the original i3bar makes flameshot work perfectly, although it's certainly uglier.

**Comment by mmahmoudian** [comment]
@SCOTT0852 I'm not a polybar user and I have no experience with it, but this is what I found by Googling:

in the [bar-settings](https://github.com/polybar/polybar/wiki/Configuration#bar-settings) in the polybar wiki:
>```ini
> ; Position of the system tray window
> ; If empty or undefined, tray support will be disabled
> ; NOTE: A center aligned tray will cover center aligned modules
> ;
> ; Available positions:
> ;   left
> ;   center
> ;   right
> ;   none
> tray-position =
> 
> ; If true, the bar will not shift its
> ; contents when the tray changes
> tray-detached = false
> 
> ; Tray icon max size
> tray-maxsize = 16
> 
> ; DEPRECATED! Since 3.3.0 the tray always uses pseudo-transparency
> ; Enable pseudo transparency
> ; Will automatically be enabled if a fully transparent
> ; background color is defined using `tray-background`
> tray-transparent = false
> 
> ; Background color for the tray container 
> ; ARGB color (e.g. #f00, #ff992a, #ddff1023)
> ; By default the tray container will use the bar
> ; background color.
> tray-background = ${root.background}
> 
> ; Tray offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
> tray-offset-x = 0
> tray-offset-y = 0
> 
> ; Pad the sides of each tray icon
> tray-padding = 0
> 
> ; Scale factor for tray clients
> tray-scale = 1.0
>```

**Comment by Mango0x45** [comment]
@mmahmoudian I have installed `stalonetray`, and even with it running I am getting the same errors and results.

**Comment by mmahmoudian** [comment]
@Mango0x45 and you don't see Flameshot tray icon?

**Comment by Mango0x45** [comment]
I think I solved the issue. No systray is actually required, I just didn't realize that you need to have `flameshot` runnning in the background. Putting `flameshot &` in my `.xinitrc` fixed everything.

**Comment by mmahmoudian** [comment]
@Mango0x45 based on your [original post](https://github.com/flameshot-org/flameshot/issues/1567), I thought you have already done that and that's how you have quoted the output of `flameshot`.

Regardless, I'm glad that it got solved 👍🏼
