### ISSUE TITLE
GUI Cursor does not work correctly or has weird behavior on non-wayland apps on wayland

### ISSUE THREAD

**Issue by uncomfyhalomacro** [flameshot-org/flameshot#1570]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
`flameshot full` works but `flameshot gui`'s cursor does not work on non-wayland apps. The footage below shows what happens when `flameshot gui`'s cursor is hovered over a non-wayland app such as discord-canary (electron app but not yet built for wayland, it runs though) and brave browser (same result). If a flameshot's window is within the area of the non-wayland apps, it will cause a weird behavior. Weird behaviors include gui cursor not working correctly (e.g. cannot select and drag to resize window), or if a gui window button is inside the non-wayland app, you cannot click it. I observed this behavior by chance when trying to test flameshot on my new rice while my discord app is open in maximized window. I ran flameshot gui and I notice I cannot click anywhere except my waybar. Firefox Fedora Edition works however since it is built for wayland.
Here is a screenrecording:

https://user-images.githubusercontent.com/66054069/115548054-9832c880-a2d9-11eb-8a13-6727e08d52fd.mp4

**Expected behavior**
It should work even with non-Wayland apps that can run on wayland.

**System Information**
Arch Linux

**Desktop Environment**
Sway - sway version 1.6

**Comment by mmahmoudian** [comment]
Interesting! Also what I observed in your video is that the mouse pointer create s ghost when the mouse pointer is hovering on Discord (the first rectangle you draw on the right side of Discord)!

**Comment by nullobsi** [comment]
hi,

have you tried adding the following to your sway config?
`for_window [app_id="flameshot"] fullscreen enable global`
it appears that flameshot is not taking up the entire screen (the top bar does not go gray). in addition, please ensure flameshot is running under wayland, and not an X11 window. if it's running under X, my guess is Sway is getting a bit confused on where to direct the input. if it is running under wayland, it would have to be a Sway issue.

**Comment by mmahmoudian** [comment]
@nullobsi Do you have some "good things to consider" for Wayland users? I'm adding content to flameshot.org and I was thinking about adding a Wayland section, but I've not used Wayland yet. PR to the [website repo](https://github.com/flameshot-org/flameshot-org.github.io) would be superb, but if you don't feel like it, you can leave them as an issue and I will copy-paste them to the markdown files.

**Comment by nullobsi** [comment]
@mmahmoudian I added a markdown file to the docs folder here, but now that you say there is a website repo I will open a PR there later

**Comment by ReneganRonin** [comment]
@nullobsi thanks!! I know it is late to notify you but I followed your suggestion and added XDG_CURRENT_DESKTOP as sway and it currently works. Should this be added in the documentation? I dont see it in the README as well.

**Comment by mmahmoudian** [comment]
@ReneganRonin seems @nullobsi didn't find time to create the PR and I'm not a Wayland user yet. If you want, as you have done it already on your computer, write what you have done in a section to the website repo or the main repo.

**Comment by nullobsi** [comment]
there is more info about how to get the desktop portal working on the GitHub wiki for xdg-desktop-portal-wlr, which can be a good reference along with any flameshot specifics :)

**Comment by sandmuel** [comment]
> @nullobsi thanks!! I know it is late to notify you but I followed your suggestion and added XDG_CURRENT_DESKTOP as sway and it currently works. Should this be added in the documentation? I dont see it in the README as well.

I actually get a similar issue, but this doesn't seem to fix it... am I supposed to to put this in .bashrc or some other place?

**Comment by uncomfyhalomacro** [comment]
Closing. I already have updated the Wiki for this iirc.
