### ISSUE TITLE
Can't take a screenshot of windows that aren't flameshot's own (MacOS)

### ISSUE THREAD

**Issue by gur111** [flameshot-org/flameshot#1571]
**Flameshot version**
v0.9.0

**Describe the bug**
This is what actually there:
![image](https://user-images.githubusercontent.com/7829415/115603133-742ab380-a2e8-11eb-9052-d7b65a882da2.png)

This is what Flameshot captures:
![image](https://user-images.githubusercontent.com/7829415/115603051-5cebc600-a2e8-11eb-859f-9dcb7b00c2f2.png)

**To Reproduce**
Take a screenshot of some other windows (any window except Flameshot's own).

**Expected behavior**
You should see that window in the screenshot

**System Information**
MacOS 11.3 Beta

**Comment by borgmanJeremy** [comment]
Did you read through the FAQ to make sure your permissions are correct

**Comment by gur111** [comment]
I thought I did but seems that I missed the screen recording. I've only added accessibility.
Sorry 🤦

**Comment by borgmanJeremy** [comment]
No problem, glad that worked !
