### ISSUE TITLE
Wayland annoing that someting saved in /tmp

### ISSUE THREAD

**Issue by zorn-v** [flameshot-org/flameshot#1572]
In KDE plasma all works fine now in wayland. But if I decide to take screenshot appears that terrible annoying unnecessary ones "OH WOW WE SAVED SOME JPG TO /tmp". Is it should be disabled by user if he need it ?

**Comment by zorn-v** [comment]
![изображение](https://user-images.githubusercontent.com/12619075/115629044-ef21b780-a344-11eb-9b08-edd33de79ec2.png)

**Comment by zorn-v** [comment]
Some times I do many screenshots, and I do not want that half of screen will filled with unrelated information.

**Comment by mmahmoudian** [comment]
So, to sum up your unclear 3-comment issue, you are requesting a feature that user can suppress notifications. Right?

**Comment by zorn-v** [comment]
Yep )
Sorry for unclear

**Comment by mmahmoudian** [comment]
According to the main dev this has been already implemented. Try what explained here:

https://github.com/flameshot-org/flameshot/issues/1179#issuecomment-795475067

If it worked, please close this issue. If it didn't work, post here.

**Comment by zorn-v** [comment]
1. dunst package is not installed
2. `showDesktopNotification=false` is not present

If I run just `flameshot` in console and then take a screenshot (via menu or hotkey) notification does not appear (and no "bimp" sound).
But if I run `flameshot gui` (or press global hotkey without flameshot loaded), notifications with sound start appears.

PS. This only happen in wayland session but not in X11

**Comment by zorn-v** [comment]
Sorry, prev described behavior was in X11. In wayland, notification with sound appears in any case

**Comment by zorn-v** [comment]
KDE by the way

**Comment by nullobsi** [comment]
this notification is not from flameshot, it is from KDE notifying you that an application has taken a screenshot. i have not used KDE in a while but there may be an option to disable it.
