### ISSUE TITLE
Cannot save Screenshots

### ISSUE THREAD

**Issue by betuxy** [flameshot-org/flameshot#1581]
First of all, great tool!
However when I want to save a screenshot I get the following error:
Permissions shouldn't be a problem, as it is started as my user right? I couldn't find a corresponding ticket for my problem.

![image](https://user-images.githubusercontent.com/72452886/115973968-aa666e00-a548-11eb-8f99-3651da881bcd.png)

$ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2

OS: Void Linux x86_64
DE: Plasma 5.21.4

**Comment by Goblin80** [comment]
Maybe there is some permission issue with the "Pictures" directory.

Can you try changing the save directory?

![d48cbc82-3f61-44a2-a35f-17dc59f06477](https://user-images.githubusercontent.com/1815268/115993965-5fdf0300-a5d5-11eb-9a82-3ad7f83e530f.png)

**Comment by betuxy** [comment]
Hey, yes sorry I forgot to mention, i tried that already. However it had no effect. 
However when i close the related processes and start it in a shell, as long as the session is open it works. 
The processowner is me either way

**Comment by betuxy** [comment]
I fiddled around a bit and it works now, the only thing i did was adding the path to flameshot in the .config/autostart/flameshot which should make a difference as usr/bin is in PATH anyway right? However now it works, even after logout/reboot.

**Comment by mmahmoudian** [comment]
Glad you found the solution and thanks for sharing it.
