### ISSUE TITLE
Chinese IME(Sogou) doesn't work, ie. I can not input any Chinese characters. Is fcitx supported by flameshot?

### ISSUE THREAD

**Issue by Likenttt** [flameshot-org/flameshot#1585]
**Flameshot version**
v0.9.0

**Describe the bug**
I can not switch to Chinese IME mode. The input typed on the screen is always ASCII characters.
![Demo](https://user-images.githubusercontent.com/26034018/116194999-2d174500-a764-11eb-8bff-0cd4342eacc1.png)

**To Reproduce**
Install Chinese IME and take a screenshot
**Expected behavior**
Chinese input supported.

**System Information**
5.10.30-1-MANJARO

**Comment by mmahmoudian** [comment]
@ZetaoYang @hosiet would it be easy for you to test this?

**Comment by ZetaoYang** [comment]
@Likenttt  
1. Can you try the AppImage from https://github.com/flameshot-org/flameshot/releases/download/v0.9.0/Flameshot-0.9.0.x86_64.AppImage ? If you tried, please tell us the result.
In our CI system, we have put fcitx4 IM Module in Appimage.

![](https://user-images.githubusercontent.com/10769951/116577779-5fcb6400-a943-11eb-86ee-18f06d43af94.png)
2. Have you installed Qt5 IM Module for Fcitx, legacy is https://github.com/fcitx/fcitx-qt5 for fcitx4, new is https://github.com/fcitx/fcitx5  for fcitx5.

**Comment by Likenttt** [comment]
Hi,  @ZetaoYang @mmahmoudian Thanks for your attention. I find it is not a problem related to flameshot. I tried `fcitx-diagnose`, the command shows the issue is caused by my system locale.  `sudo locale-gen "zh-CN.UTF-8"` and restart can fix it.
