### ISSUE TITLE
How to upload images to our own imgur account?

### ISSUE THREAD

**Issue by laranz** [flameshot-org/flameshot#159]
Is this possible? or imgur API doesn't allow that?

Thanks for the screen-shot tool, it is just awesome! I used Monosnap from my mac but I couldn't find anything similar to that for my Ubuntu, and at last I found Flameshot :+1:

**Comment by lupoDharkael** [comment]
Still not implement but it's in the roadmap.

**Comment by laranz** [comment]
Awesome, will looking forward to it. :+1:

**Comment by urbels** [comment]
+1

**Comment by shahmoeen** [comment]
Thank you so much for such a great tool, I really like it and use it almost every day on Ubuntu. 
I just want to add +1 for this feature, it will help a lot. 
Just sent a tiny little amount in your paypal for your great work. thank you again!

**Comment by wdesign22** [comment]
We still need it! :)

**Comment by KOT040188** [comment]
I'm waiting!

**Comment by lamth99** [comment]
I am still waiting

**Comment by rajeshisnepali** [comment]
I'm waiting.

**Comment by dgw** [comment]
Instead of writing passive-aggressive comments, y'all should submit patches.

**Comment by KOT040188** [comment]
I would have provided patches if I knew what it was. I'm not a programmer.

**Comment by dgw** [comment]
I'm just pointing out that comments about "waiting" for a new feature are not helpful, and might even discourage project developers if they feel too much pressure. Better to thumb-up the original post and forego the comment. (It also avoids sending emails to everyone who watches the repo.)

**Comment by borgmanJeremy** [comment]
Please track this RFC for future discussion on this topic: https://github.com/flameshot-org/flameshot/pull/955

**Comment by borgmanJeremy** [comment]
We just merged a patch that allows users to use thier own API key.

**Comment by rajeshisnepali** [comment]
How can I find uploaded images in my imgur account?

**Comment by mmahmoudian** [comment]
@rajeshisnepali 
> How can I find uploaded images in my imgur account?

At the moment uploads are done via tokens which means they are anonymous and not under your accounts. This is also briefly explained here: 

- https://github.com/flameshot-org/flameshot/issues/2740#issuecomment-1171500805
