### ISSUE TITLE
Shared Memory Lock failed

### ISSUE THREAD

**Issue by AtjonTV** [flameshot-org/flameshot#1590]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**

```
$ flameshot 
SingleApplication: Unable to create block.
SingleApplication:  8 "QSharedMemoryPrivate::initKey: unable to set key on lock"
```

I wish I could provide a LLDB backtrace, but its empty.

**To Reproduce**
I dont have exact steps but compiling from source with both GCC and Clang result in the error above.

No other Qt Application is failing with similar error messages.

**Expected behavior**
Flameshot should start and be running in the background

**System Information**
Operating System: ATVG Linux 2021.1
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.10.32-ATVG
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × Intel® Core™ i9-9880H CPU @ 2.30GHz
Memory: 31.0 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2080/PCIe/SSE2
(Gentoo Base 2.7 with Profile 17.1 OpenRC)

**Comment by borgmanJeremy** [comment]
Is this on ARM hardware?

https://github.com/itay-grudev/SingleApplication/issues/58

**Comment by AtjonTV** [comment]
No, this is on Intel Core i9.

(I also updated the system information section to include processor, memory and graphics chip)

**Comment by borgmanJeremy** [comment]
Where can I find info on ATVG Linux? Having trouble finding it.

Ultimately this is an issue with QTSingleApplication but I'd like to get more info before I bug them.

**Comment by AtjonTV** [comment]
ATVG Linux is a custom system that is not publicly accessible .. but its basically just Gentoo Linux with stable versions of both Qt 5.15 and KDE 5.21.

**Comment by borgmanJeremy** [comment]
Hmmm. Perhaps build the examples from this: https://github.com/itay-grudev/SingleApplication with debug symbols and see if you find anything? I know we have other gentoo users so I am suspecting an issue with the kernel flags supplied to your kernel.

**Comment by AtjonTV** [comment]
Hmm, yea .. it is failing too ..

I am wondering what kernel flags would do that .. I am using a custom kernel that came from Arch Linux and was reduced to what hardware I am using .. the only changes made to the flags are what ever the upstream kernel changes. (changes from upstream kernel.org are applied to the custom config before build)

**Comment by AtjonTV** [comment]
If I where to know what flags are at fault, I could rebuild my kernel and give a response later today or tomorrow ..

**Comment by borgmanJeremy** [comment]
Yeah if you figure it out let me know I would be very interested.

Is there anything related to security or hardening? That is what I first suspect since it is related to QShared memory. 

Another option is to edit QSingleApplication to print out the return code error: https://doc.qt.io/qt-5/qsharedmemory.html#SharedMemoryError-enum

That might help narrow in on the issue.

**Comment by AtjonTV** [comment]
So, I am now back on Kernel 5.10.30 and its working again .. I am currently rebuilding kernel 5.10.32 with a more generic configuration to find out if this is a kernel bug or a configuration bug.

**Comment by AtjonTV** [comment]
Ok, I can confirm now that this is a kernel configuration issue.

It seems that for some reason the following configs where missing:

```
CONFIG_SYSVIPC=y
CONFIG_SYSVIPC_SYSCTL=y
CONFIG_SYSVIPC_COMPAT=y
```

And thus shared memory for non-root wasnt working .. even Steam didnt want to start.

As this is, clearly, a Kernel bug and not a Flameshot bug, I am going to close this issue now.
