### ISSUE TITLE
Chocolatey Package?

### ISSUE THREAD

**Issue by karlhorky** [flameshot-org/flameshot#1591]
**Is your feature request related to a problem?**

Currently there are easy commands in the readme to copy/paste to the terminal and install Flameshot on Linux and macOS.

It would be nice if there would be an option to be able to install Flameshot on Windows via the command line with [Chocolatey](https://chocolatey.org/)

Similarly to what @cometeme and @lfalcao did for macOS in https://github.com/flameshot-org/flameshot/issues/1475, maybe it would be possible to [submit Flameshot to Chocolatey as a package](https://docs.chocolatey.org/en-us/create/create-packages) and then documented in the readme?

**Comment by borgmanJeremy** [comment]
@ZetaoYang  has already put it into scoop. Will that work for you? Also feel free to package it in chocolatey in addition to scoop if you want.

**Comment by karlhorky** [comment]
> @ZetaoYang has already put it into scoop

Ah interesting, not as familiar with Scoop - can these packages be consumed by Chocolatey as well?

I guess the installation instructions for Scoop could be added to the readme too - what's the command?

**Comment by karlhorky** [comment]
Ah, seems like [it's also available via `winget`](https://github.com/flameshot-org/flameshot/issues/1225#issuecomment-776058321) - that could also be added to the readme...

**Comment by karlhorky** [comment]
Ok, I've submitted a request for a Chocolatey package over here: https://github.com/chocolatey-community/chocolatey-package-requests/issues/973

**Comment by ZetaoYang** [comment]
> 
> 
> > @ZetaoYang has already put it into scoop
> 
> Ah interesting, not as familiar with Scoop - can these packages be consumed by Chocolatey as well? Would be nice to get a solution for Chocolatey users - last I looked, it's the more common package manager.
> 
> I guess the installation instructions for Scoop could be added to the readme too - what's the command?

https://github.com/lukesampson/scoop-extras/blob/master/bucket/flameshot.json

enable scoop extras bucket `scoop bucket add extras`, then `scoop update`, finally `scoop install flameshot`.
![图片](https://user-images.githubusercontent.com/10769951/116420273-6b018f80-a870-11eb-9151-824d92ca8960.png)

**Comment by borgmanJeremy** [comment]
Addedin readme
