### ISSUE TITLE
Document Windows Installation Instructions in Readme

### ISSUE THREAD

**Issue by karlhorky** [flameshot-org/flameshot#1592]
**Is your feature request related to a problem?**

Currently there are easy commands in the readme to copy/paste to the terminal and install Flameshot on Linux and macOS.

It would be nice if there would be an option to be able to install Flameshot on Windows via the command line.

@ZetaoYang already submitted Flameshot to [`scoop`](https://github.com/flameshot-org/flameshot/issues/1225#issuecomment-774662015) and [`winget`](https://github.com/flameshot-org/flameshot/issues/1225#issuecomment-776058321) (already accepted), and I've submitted it to [Chocolatey](https://github.com/flameshot-org/flameshot/issues/1591#issuecomment-828458299)

**Comment by borgmanJeremy** [comment]
Feel free to submit a PR with the updates the README. Im sure a maintainer will do it if you don't want to, but we welcome community contributions.

**Comment by mmahmoudian** [comment]
Interesting that this came up today. Last night I started adding these into the flameshot.org . I will also add Chocolatey to the mix.

**Comment by karlhorky** [comment]
@mmahmoudian thanks! Please note that Chocolatey has not yet responded to my package request here: https://github.com/chocolatey-community/chocolatey-package-requests/issues/973

**Comment by mmahmoudian** [comment]
Thanks, I checked it and figured out it is not there yet. I will add it when it was accessible via choco command. 👍🏼

**Comment by mmahmoudian** [comment]
On it's way to the website: https://github.com/flameshot-org/flameshot-org.github.io/pull/22
