### ISSUE TITLE
Disable a shortcut keyboard should appear directly

### ISSUE THREAD

**Issue by gakramx** [flameshot-org/flameshot#1596]
**Flameshot version**
 Flameshot v0.9.0
Compiled with Qt 5.15.2

**System Information**
```
Operating System: Arch Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.10.32-1-lts
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-5300U CPU @ 2.30GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500
```

**Describe the bug**
The Flameshot must empty the key column after disabling the Keyboard shortcut "after pressing backspace" from GUI  
To appear that the key is empty, you must restart GUI. 

**To Reproduce**
1.  Right-click on tray icon
2.  Click on "configuration"
3.  Go to "shortcuts" tab
4.  Click on an item and press "Backspace" 
 
 
**Expected behavior** 
The key should appear that it is empty without the need to restart GUI .

**Comment by mmahmoudian** [comment]
Since you are on Arch, can you try the AUR `flameshot-git`? That will compile and install the head of master of this repo which is version 0.10.0 . Can you confirm that you still have this issue even in that version?
