### ISSUE TITLE
stuck completelly

### ISSUE THREAD

**Issue by kaldown** [flameshot-org/flameshot#1597]
I was trying to create a gui screenshot.
Suddenly it stopped working.
Sill can move frames and highlight a text, but.
`CTRL+S` or `Return` or `ESC` doesn't work.

Bad thing is - wont be able to call for a console to kill the service, so I've been forced to open another terminal `ALT+CTRL+F2`.

I don't even know how to reproduce that, since after `killall flameshot` it works correctly.
Nether the less, really frightening bug.

**Comment by mmahmoudian** [comment]
Even when the keyboard shortcuts stop working, you can always close with pressing the (X):
![image](https://user-images.githubusercontent.com/390889/116569346-faab4a80-a911-11eb-886c-ffe5416e0cbb.png)


But back to your issue, if an application takes control while `flameshot gui` is active (for example pressing F12 in KDE to spawn Yakauke), all of your keyboard shortcuts would not go to Flameshot and instead they go to the other application.

**Comment by kaldown** [comment]
> Even when the keyboard shortcuts stop working, you can always close with pressing the (X):
> ![image](https://user-images.githubusercontent.com/390889/116569346-faab4a80-a911-11eb-886c-ffe5416e0cbb.png)
> 
> But back to your issue, if an application takes control while `flameshot gui` is active (for example pressing F12 in KDE to spawn Yakauke), all of your keyboard shortcuts would not go to Flameshot and instead they go to the other application. This behavior is not a bug, it is what your window manager does.
> 
> As a side not, please ALWAYS provide system info when you are reporting a potential bug.


The thing is, i disabled almost every default ;)
I'm not using any keyboard capturer.
Pure `i3wm` with the minimal gui whatsoever.

**Comment by mmahmoudian** [comment]
How about if you accidentally press <kbd>Super</kbd>+<kbd>2</kbd> when you are on the first workspace? can you reproduce that?

**Comment by kaldown** [comment]
> How about if you accidentally press Super+2 when you are on the first workspace? can you reproduce that?

that's exactly it!

`super+2` is my "code" workplace!

**Comment by mmahmoudian** [comment]
But <kbd>Super</kbd>+<kbd>2</kbd> is not a default shortcut key in Flameshot. As far as I can remember, none of the default shortcuts uses <kbd>Super</kbd> key.

I hypothesized that while you are on workplace 1 and taking the screenshot, by accidentally pressing <kbd>Super</kbd>+<kbd>2</kbd> you are telling i3 to take you to workspace 2 and that's where Flameshot is loosing the focus and does not receive the keybord input. There is nothing you can do in Flameshot, but perhaps you can change your i3 config to prevent workspace change when `flameshot gui` is running.

**Comment by kaldown** [comment]
> But Super+2 is not a default shortcut key in Flameshot. As far as I can remember, none of the default shortcuts uses Super key.
> 
> I hypothesized that while you are on workplace 1 and taking the screenshot, by accidentally pressing Super+2 you are telling i3 to take you to workspace 2 and that's where Flameshot is loosing the focus and does not receive the keybord input. There is nothing you can do in Flameshot, but perhaps you can change your i3 config to prevent workspace change when `flameshot gui` is running.

But that wasn't an accidental click, so changing binds wouldn't solve the problem.
While `flameshot` is in "awaiting" mode, I instantly switched back to the other workspace to see necessary staf, then back again to save a proper screenshot.

I think that would be solved with https://github.com/flameshot-org/flameshot/issues/1576 since I don't need `flameshot` to wait anyway.

Thank you.
