### ISSUE TITLE
Error trying to save as .png

### ISSUE THREAD

**Issue by positiveworld9** [flameshot-org/flameshot#1607]
**Flameshot version**
0.9.0

**Describe the bug**
Whenever I try to take a screenshot the window "Error trying to save as .png" appears.
Screenshot attached.

Other 2 programs (Gnome screenshot and shutter) had no problem. Shutter was uninstalled when I installed flameshot.

![2021-05-04T18:32:14 95](https://user-images.githubusercontent.com/83659303/117035224-ba323f00-ad0c-11eb-85ab-944044f8cd17.png)

**To Reproduce**
Install flameshot from the Software app then attempt to take a screenshot using the program.
![2021-05-04T19:52:13 92](https://user-images.githubusercontent.com/83659303/117040237-5a3e9700-ad12-11eb-877f-8283cf2ba50a.png)
Gnome screenshot was already installed, but I don't think it's related.

**Expected behavior**
The error should not appear.

**System Information**
Xubuntu 18.04.5 (I don't know why uname -a shows 18.04.1)
Linux PC 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I use X11 (not wayland), on a laptop (single monitor).

If I try to get the info requested at
https://flameshot.org/issue-reporting/
I get:
` inxi --width 80 --system --graphics
/usr/bin/inxi: illegal option -- -
Error 7: One of the options you entered in your script parameters: --width
is not supported.The option may require extra arguments to work.
`
However my version of inxi seems to work with short codes, like inxi -G, which gives:
`Graphics:  Card: Advanced Micro Devices [AMD/ATI] RC410M [Mobility Radeon Xpress 200M]
           Display Server: x11 (X.Org 1.20.8 ) drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1280x800@59.91hz
           OpenGL: renderer: ATI RC410 version: 2.1 Mesa 20.0.8
`

For the rest of the system info, if it is needed I can add it.
However it looks like a file processing error, not a graphic error, so all details about graphics seem useless.

**Comment by borgmanJeremy** [comment]
Was it installed from the .deb or flatpak or snap?

**Comment by positiveworld9** [comment]
As far as I see it is a snap package.
![2021-05-04T19:52:13 92](https://user-images.githubusercontent.com/83659303/117040237-5a3e9700-ad12-11eb-877f-8283cf2ba50a.png)

**Comment by borgmanJeremy** [comment]
Could be related to #2047

**Comment by positiveworld9** [comment]
> @positiveworld9 do you still have the same issue with Flameshot version 0.10.1?

Yes, sorry for the late response.

**Comment by positiveworld9** [comment]
> Could be related to #2047

What is the "namebox"? On Xfce/ flameshot snap, Configuration, (tab) General, the Save Path is not editable at all, and empty.

**Comment by borgmanJeremy** [comment]
It's fixed on the master branch.

**Comment by borgmanJeremy** [comment]
Since this is fixed now I am going to close.
