### ISSUE TITLE
implement milisecond (nanosecond) filename support

### ISSUE THREAD

**Issue by positiveworld9** [flameshot-org/flameshot#1609]
For the filename editor tab present in Configuration, if I type in the Edit field
`%Y-%m-%dT%H:%M:%S.%2N`
the **%2N** is not giving an actual value as it should, that is "returns the current time with nanoseconds rounded to the first 2 digits", see [this answer](https://stackoverflow.com/a/18704121) - I must mention Gnome screenshot gives the actual result.

This feature is extremely needed if fast consecutive uses (without GUI) fall in the same second, that would erase the first and only keep the second screenshot.

Edit: some programs might attend a number to filename, but for example gnome screenshot just keeps the most recent; or maybe it's a desktop environment/file manager issue.

**Comment by borgmanJeremy** [comment]
Actually it would not delete the first image, if the names are the same it will append _1, _2, _3, etc

**Comment by borgmanJeremy** [comment]
Also the formatting string is not dictated by the echo command, it follows the strftime function in c++. Furthermore it restricts the set of format specifiers to the specifiers allowed by the MSVC compiler which is a subset of the specifiers support by GCC and CLANG.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-160

**Comment by borgmanJeremy** [comment]
Closing this since we already support adding a _n to avoid duplicate names and strftime does not support miliseconds.
