### ISSUE TITLE
4k capture area issue

### ISSUE THREAD

**Issue by MustaphaAlioglou** [flameshot-org/flameshot#1610]
**Describe the bug**
after i run  the command  the screen flickers  and it doesnt stop until i press the escape button from the keyboard. after that it will not flicker again but you wont be able to screenshot the whole 4k monitor. it looks like the capture area is under the main window of the application but its not big enough. the window should open in the screen that the mouse is in.
*open the image to see the bug. you cant see it in the preview*
![Screenshot from 2021-05-05 16-42-27](https://user-images.githubusercontent.com/26637959/117150800-27071100-adc1-11eb-88be-29d4a165226d.png)
![Screenshot from 2021-05-05 16-42-48](https://user-images.githubusercontent.com/26637959/117150813-2a020180-adc1-11eb-83c7-13d1e06995ff.png)

**To Reproduce**

you need one 1080 monitor for the main screen, a 4k secondary and popos 20.04 lts.
type flameshot gui from the terminal or from a shortcut

**System Information**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

LOGO=distributor-logo-pop-os

**Comment by thepurple** [comment]
In general it's not about 4k, it's because of different resolution of displays. The same issue will be on FullHD and HD.

**Comment by MustaphaAlioglou** [comment]
the problem its not the bottom part. the problem is it cant strech to fully to the right

**Comment by MustaphaAlioglou** [comment]
this is the maximum width i can get

**Comment by ryolambert** [comment]
Having the exact same issue here with the same os and a portrait 1080p / landscape 4k display setup... The only way I can get flameshot to work without blacking out is to make sure that HiDPI Daemon is off. Which causes the skewed screenshot area to only fit the screen boundaries to the lowest res display across both monitors...

**Comment by alexamy** [comment]
Have the same problem with 2160p + 1080p display setup.

**Comment by rashaunny** [comment]
Same issue with 2560x1600 using NVidea Nuveau drivers, Ubuntu 20.04

**Comment by thepurple** [comment]
As for me, the only way to fix it is to disable (add option to disable/enable) multi-display mode for capture and make as on MacOS, capture active display only. Otherwise buttons may disappear in invisible area on a smaller screen if capture area will cover two displays.

**Comment by thepurple** [comment]
I thought about how we can handle this for a while.
The only way I can see is to add the ability to capture the current screen only like in MacOS.

In the current "capture all screens" mode, we can do one of the following:
- incorrect placement of buttons on the big screen (current behavior)
- some buttons may be off-screen on the small display

**Comment by pavangayakwad** [comment]
Does not work well with pop_os.
1) Does not cover full 4K area, you can see in my screenshot below

![image](https://user-images.githubusercontent.com/1834890/141650954-0f52039a-2963-401c-8d0d-34f74319db26.png)

2) It flickers continuously when another monitor is connected. 

This is a crashing defect, I really wonder how come it is not prioritized and fixed till date.

**Comment by leiless** [comment]
Met the same issue:
Screen resolution: 3840 x 2160
Screen scale: 175%
OS: Ubuntu 20.04 LTS x86_64
GPU: Intel
DE: GNOME + X11 windowing system

**Comment by klausbadelt** [comment]
Not a 2 screens issue - I have the with single 4k screen, 125% fractional scaling. https://github.com/flameshot-org/flameshot/issues/1610#issuecomment-968093149 describes my issue precisely.
