### ISSUE TITLE
Screen goes black and start blinking when using monitor scaling

### ISSUE THREAD

**Issue by IgorMunizS** [flameshot-org/flameshot#1611]
This bug happens when I'm using monitor scaling on Ubuntu 20.04. I have a 2.5k monitor and I prefer to use a 125% scaling for work. If I turn off scaling or set it to 100%, flameshot works fine.

Flameshot version
(0.6.0+git20191001-2)

Describe the bug
When using monitor scaling on Ubuntu 20.04 I can't use flameshot to take a screenshot. When I try to do that, the monitor lose his signal and the screen goes black. It happens to all monitors. The screen starts to blinking like it's in a loop losing and getting a connection (similar to a cable issue). If not using scaling, flameshot works well.

To Reproduce
Set monitor scaling for something above 100% (Ubuntu - Settings-Monitors) and try to take a screenshot using flameshot.

Expected behavior
Monitor should work normally and we should be able to take a screen shot.

**Comment by mmahmoudian** [comment]
I thought it is either duplicate or heavily related to #564

@IgorMunizS you Flameshot version is very old. Please update to the new version. In case Ubuntu official repo has that old version, you can install it via Snap or Flatpak or use AppImage (check https://flameshot.org for instructions if you don't know what these are)

**Comment by mmahmoudian** [comment]
@borgmanJeremy  sold this be closed?

**Comment by IgorMunizS** [comment]
@mmahmoudian you are right. I had an old version but after update it to Flameshot v0.9.0
Compiled with Qt 5.12.3 via Snap, I'm still getting the same behavior.

**Comment by IgorMunizS** [comment]
I'm closing this issue since it's related to #564
