### ISSUE TITLE
Buttons not showing up

### ISSUE THREAD

**Issue by iamludal** [flameshot-org/flameshot#1614]
**Flameshot version**
`v0.9.0`

**Describe the bug**
When capturing the screen, editing buttons are not showed.

![bug](https://user-images.githubusercontent.com/44783088/117467185-bfcd9600-af53-11eb-8e98-7e34087fdc9c.gif)

**To Reproduce**
I guess it has something related with multiple monitors. On my 2n monitor, everything works fine. But whenever I move the selection rectangle on my first screen, the buttons either disappear or show up at a random location (on either of the two monitors).

**Expected behavior**
The buttons should show up normally.

**System Information**
Windows 10

**Comment by iamludal** [comment]
It does work with your latest build, though I can't import my settings file. 🤔

**Comment by mmahmoudian** [comment]
@borgmanJeremy @iamludal shall we consider this as closed?

**Comment by iamludal** [comment]
Yes, you can, since it will be available in future versions. Thank you. 🥳
