### ISSUE TITLE
[Question] Build/package system.

### ISSUE THREAD

**Issue by angelskieglazki** [flameshot-org/flameshot#1617]
@borgmanJeremy
Hello Jeremy.

I have a small question. I am doing the program, something like reference board for 2D / 3D artists.

I took the build system of flameshot program as a basis (I copied almost everything except the deployment section in the appveyor.yml. I have not made the signpath signature yet.).

I have one problem, the portable archive has all the dll-libraries but no executable file. The MSI installer also installs everything except the executable file. Perhaps you came across this when you did the build-system and you can tell me where I went wrong.

Here is my repository: https://github.com/try-hard-factory/familiar   ci-build branch.

regards, max

**Comment by borgmanJeremy** [comment]
I'm going to close the issue here but I'm happy to help via email borgman_jeremy@pm.me. If you build it locally does the .exe exist? (it doesn't build for me on linux currently).

Again please reply via email so we don't bother all the other flameshot devs with this.

**Comment by angelskieglazki** [comment]
I wrote. Thank you
