### ISSUE TITLE
ubuntn 18.04 configuration not effect 配置不起作用

### ISSUE THREAD

**Issue by i-wanglei** [flameshot-org/flameshot#1621]
System: Ubuntu 18.04 for Linux
Phenomenon: Check the box to start automatically，restart configuration , configuration restore（勾选开机自动启动，重新打开配置，配置依旧没被勾选）

**Comment by mmahmoudian** [comment]
Translation from Chinese:

> Check the auto start after boot, reopen the configuration, the configuration is still unchecked

**Comment by mmahmoudian** [comment]
@i-wanglei 
Please provide:
- Flameshot version
- how have you installed Flameshot
- your Desktop Environment or Window Manager (run `inxi --system --graphics` and post the results here)

**Comment by i-wanglei** [comment]
Hello, thank you for your answer!
The install way(for linux): sudo apt install flameshot
flameshot version :0.5.1
![image](https://user-images.githubusercontent.com/73985820/118346329-362e5180-b56d-11eb-909d-83dd99b5f454.png)
I have a solution that adds software directly to the linux boot boot task,but I don't want to do that. I want to solve it through software configuration.

**Comment by mmahmoudian** [comment]
Your Flameshot version is very very old. Please try installing the new version (0.9.0).

About loading Flameshot at startup, it should be done via Gnome and not Flameshot.

```sh
sudo apt-get install gnome-tweak-tool
```
