### ISSUE TITLE
Configurable upload site

### ISSUE THREAD

**Issue by Arsimael** [flameshot-org/flameshot#1623]
Hi,

I use flameshot nearly on a daily basis and it's one of the most helpful tools I use at the moment.
However there is one major feature I badly miss: 
Changing the upload website. 

imgur is a nice to use site, but it's a pain in the butt to remove an once uploaded file. 

If it is possible, can this be changed to allow different websites? I use cheverento, a self hosting image platform (https://github.com/Chevereto/Chevereto-Free) which allows me to host images under my control and not giving them into the hands of a profit-driven company. 

Thank you for your hard work on this tool, and if I can give you a coffee somehow, let me know.

A.I.

**Comment by Officialstrike** [comment]
Aren't they working on this per #955? The current plan is to support the ShareX plugin format.

**Comment by borgmanJeremy** [comment]
Yeah thanks for linking to the duplicate. That's still the plan just been very busy lately.
