### ISSUE TITLE
Configurable background dimming

### ISSUE THREAD

**Issue by Pheggas** [flameshot-org/flameshot#1624]
Let's explain this on example. Well, on windows, when you want to screenshot something with Flameshot, you press Printscreen and select the area. But most of the time, i'm working on dark areas and everything has in dark mode. For example i'm using Dark Reader for every site. Now, when i want to screenshot something, i can only hardly see where it is and what i want to screenshot (especially on sunny days). I looked for this option in config file but without luck. Can you please add customizable dim level of that screenshot background so i can easier see where on screen is thing that i want to screenshot?

**Comment by Pheggas** [comment]
Found it in Tray icon -> Configure.

Closing...

**Comment by arsenerei** [comment]
For posterity:

Interface > Opacity of area outside selection

<img width="1911" height="1069" alt="Image" src="https://github.com/user-attachments/assets/568b9cc1-d236-4412-86fc-4d4a004a90b5" />
