### ISSUE TITLE
[Windows] Bug with two monitors

### ISSUE THREAD

**Issue by dankmolot** [flameshot-org/flameshot#1625]
**Flameshot version**
v0.9.0 (installed from release, .msi installation)

**Describe the bug**
When you select an area for a screenshot on the right screen, the buttons (draw, blur, etc.) are on the left screen, and not around the area

When selecting an area on the left screen
![image](https://user-images.githubusercontent.com/44505837/118354941-2a935880-b576-11eb-8901-14558f451949.png)

When selecting an area on the right screen
![image](https://user-images.githubusercontent.com/44505837/118354949-37b04780-b576-11eb-8d66-9c932b00494d.png)

**To Reproduce**
1. Two monitors, one on the right, one on the left
![image](https://user-images.githubusercontent.com/44505837/118354849-bbb5ff80-b575-11eb-8668-17593f8318ea.png)
2. Open flameshot
3. Select area on the monitor to the right

**Expected behavior**
The buttons will be on the left screen, and not around the area

**System Information**
Windows 20H2

**Comment by borgmanJeremy** [comment]
This is fixed on the main branch. Will be in a release soon.
