### ISSUE TITLE
Export to img uri:Base64

### ISSUE THREAD

**Issue by fabiovila** [flameshot-org/flameshot#1626]
Your software is great for annotations. Could you add export to <img URI:base64>? 
This would be very useful for adding images taken from screenshots to webpages and editors like CKEditor.

**Comment by borgmanJeremy** [comment]
This is supported on our Linux version with the "open in" feature.

**Comment by fabiovila** [comment]
If someone has the same need this script convert image to Base64 and copy to clipboard. Use the "open in" feature to call this script.

```
#!/usr/bin/env python

import base64
import sys
import os.path
import pyperclip

if __name__ == '__main__':
	if len(sys.argv) > 1:
		ext = os.path.splitext(sys.argv[1])[1]
		with open(sys.argv[1], "rb") as img_file:
			b64_string = base64.b64encode(img_file.read())	
		output = '<img src="data:image/'+ext.lower()+';base64,'+ b64_string.decode() + '"/>'
		pyperclip.copy(output)
```
