### ISSUE TITLE
Can't open web browser to delete imgur screenshot

### ISSUE THREAD

**Issue by Tchekda** [flameshot-org/flameshot#1628]
**Flameshot version**
```
Flameshot v0.6.0
Compiled with Qt 5.14.2
```

**Describe the bug**
When trying to delete picture from imgur, I get the following error message : 
```
Unable to open the URL.
```
And I found this message in the system's journal
```
org.dharkael.Flameshot[6657]: Unable to detect a web browser to launch [MY_URL]
```

But every other applications are successfully opening Firefox as my default browser

**To Reproduce**

1. Take a screenshot with the gui
2. Upload it to imgur
3. Try to delete it

**Expected behavior**
Open firefox with the page to delete the screenshot

**System Information**
```
- system: `"x86_64-linux"`
- host os: `Linux 5.11.16, NixOS, 20.09.4025.dc326c78a93 (Nightingale)`
```
Firefox : 85.0b6 (64-bit) Developer Edition

**Comment by borgmanJeremy** [comment]
Version 0.6 is no longer supported. Could you please try using our latest 0.9.0 release?

**Comment by Tchekda** [comment]
> Version 0.6 is no longer supported. Could you please try using our latest 0.9.0 release?

0.6 is the latest version available in the stable channels of NixOS. 

I've just installed 0.9 but now there is another problem. Once I click on `Upload to imgur`, it closes the window and copies the URL in the clipboard. How am I supposed to delete the screenshot now ? 

Thank you for your quick answer

**Comment by mmahmoudian** [comment]
Right-click on the tray icons, the click on "Latest Uploads" and from there you can delete them.

**Comment by Tchekda** [comment]
> Right-click on the tray icons, the click on "Latest Uploads" and from there you can delete them.

Hi, I'm using i3 without tray icons, how can I access it without the tray icon ?

Because I tried the launcher command of the command line tool, but didn't find it...

**Comment by mmahmoudian** [comment]
@Tchekda I think without systray you are out of luck. Flameshot has been primarily designed as a GUI tool with high dependency on systray. 

I'm sure if you are persistent enough, you can find where the ID for the uploaded images are in your disk and from the code and Imgur API you can get to know how to create a correct query to delete what you want. From top of my head, I don't have a ready solution other than installing polybar, use they tray icon and then remove polybar.

**Comment by Tchekda** [comment]
@mmahmoudian thank you for your idea. 
I just added flameshot to my existing polybar and finally got the tray menu.

But still the same error when I try to delete the file : `Unable to detect a web browser to launch 'https://imgur.com/delete/slWNwpuu8hF0zCe'`

**Comment by mmahmoudian** [comment]
Well, the error is very clear: you don't have a default web browser set. You can copy the URL into your browser manually, or set default web browser.

**Comment by Tchekda** [comment]
> Well, the error is very clear: you don't have a default web browser set. You can copy the URL into your browser manually, or set default web browser.

@mmahmoudian my default browser is set because every other application is working well with Firefox. 
Including my Terminal, Discord, Evince, and other application that opens links... 

Where do you want me to check what is configured by flameshot ?

**Comment by mmahmoudian** [comment]
Try to see if running this in terminal opens your default web browser:

```sh
xdg-open "http://example.com"
```

If it doesn't do what is explained in these two links:
1. https://adamsimpson.net/writing/setting-a-default-browser-in-i3
2. https://www.rockyourcode.com/change-the-default-browser-in-i3-manjaro-linux/

**Comment by Tchekda** [comment]
> Try to see if running this in terminal opens your default web browser:
> 
> ```shell
> xdg-open "http://example.com"
> ```
> 
> If it doesn't do what is explained in these two links:
> 
>     1. https://adamsimpson.net/writing/setting-a-default-browser-in-i3
> 
>     2. https://www.rockyourcode.com/change-the-default-browser-in-i3-manjaro-linux/

worked without a problem. This is how every other application opens its links. 

Is flameshot using the PATH variable to open firefox ?

**Comment by mmahmoudian** [comment]
> Is flameshot using the PATH variable to open firefox ?

@borgmanJeremy this is out of my knowledge base. Would you please answer this.

**Comment by borgmanJeremy** [comment]
Under the hood we are using this:

https://doc.qt.io/qt-5/qdesktopservices.html#openUrl

I am not entirely certain how Qt determines which browser to use. However it's not directly set in flameshot.
