### ISSUE TITLE
I want to be able to easily save the flameshot I just created as a .png file even if I have already pressed the enter key.

### ISSUE THREAD

**Issue by Raytle** [flameshot-org/flameshot#1633]
**Is your feature request related to a problem?**

Yes.

First and foremost, Flameshot is great. Thanks for creating it and for continuing to develop it.

Second, sometimes I make a mistake. Sometimes when I'm done flameshotting I inadvertently press `Enter` instead of `ctrl + s`. In those cases I am unable to easily save the flameshot I just created as a .png file. Sure, I can paste the flameshot into a document and then use Flameshot to copy the flameshot I just pasted, but that's a little cumbersome.

Therefore, I'd like like something that functions similar to `ctrl + z` (undo). Here is one way I have imagined doing that...

When  a user saves a flameshot to his clipboard, Flameshot would save that flameshot  to, for example, `~/.config/Dharkael/most_recent_flameshot`. Furthermore, a  message would appear saying, "Your flameshot was just copied to your clipboard. Would you like to save your flameshot as a .png file?" As long as users could A) press the `esc` to cancel that message and B) choose not to see that message by changing a Flameshot preference, I think it might be a good way to implement the feature without requiring you write too much.

Sure, you could even change `~/.config/Dharkael/most_recent_flameshot` to `~/.config/Dharkael/most_recent_flameshotS` (that's flameshotS plural), save  the last X flameshots which the user had copied to the clipboard and, as I suppose you have surmised, and add an option to allow users to view the last X flameshots. Personally, I doubt I would use that feature very often but, I figured I would mention it in passing.

In case you have not gleaned the fundamental point I am making, here it is: Flameshot has a philosophical problem. It violates the "undo-ability-ness" (the ability to press undo) which is part of what makes using modern computers delightful. Yet here's the really nice thing: it would be remarkably easy to fix this philosophical problem because, well,  Linux, Microsoft Windows, and macOS all have "undo-ability" built into them.

**Comment by borgmanJeremy** [comment]
The latest versions of Flameshot have an option to always save the image after copy:

![image](https://user-images.githubusercontent.com/46930769/118861261-ebc90f80-b8a1-11eb-8c1e-bedb780055d3.png)

**Comment by Raytle** [comment]
Thanks for letting me know. I appreciate that. I will check it out.

`Save image after copy` **for the previous X flameshots** would allow users to save, for example, their last 5 or 10 or even 100 flameshots. It's not a feature I would probably use much, but I presume it would be trivial for you to add and, well, I imagine some users would like that feature.

Generally, I try to avoid the dreadful disease of [scope creep](https://en.wikipedia.org/wiki/Scope_creep) (feature creep). I know it tends to be endless. But I tend to look for ways to add features that are trivial for developers to add yet might be useful to some users. Fundamentally, this is essentially increasing undo-ability-ness from "undo once" (which is one way to understand "Save image after copy" to **undo 5 times** or **undo 10 times** or **undo 100 times**.

Frankly, most developers tend to write software that "scratches their own itch" (which does something that they want) and then only later—once a litany of complaints begin pouring down on them like a monsoon—realize that other people want other features. I'm not a big believer in agile development. Sure, it is appropriate for some projects. But I think it's usually better to design the house first, and then build it instead of building the house first and then constantly trying to retrofit it.

Flameshot has some other glaring philosophical problems which I suppose you might realize. If you want me to "re-architect" your delightful little open source project please let me know. Although, I find Flameshot very useful—to me, at least—it's fundamentally flawed presumably because it was never really designed to become as popular and full-featured as it has become.

I've found most FOSS developers don't want to hear my opinions about "their baby." That's fine. See, I don't want to unnecessarily raise your hackles (upset you) unless you actually want to redesign Flameshot. And no. That's not scope creep. That's a redesign. They are inherently different concepts.

**Comment by Raytle** [comment]
> The latest versions of Flameshot have an option to always save the image after copy:

I just checked. The most recent version of Flameshot for Ubuntu seems to be...

Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

I presume that's not the version of Flameshot you were referring to. Right?

**Comment by borgmanJeremy** [comment]
Correct, the latest release is 0.9 and 0.10 will be released in the next couple of weeks. You can download the .deb from the release page or install via snap, flatpak, appimage.

**Comment by Raytle** [comment]
Thank you! I now have...

Flameshot v0.9.0
Compiled with Qt 5.11.3

The auto incrementing bubbles are clever! I will probably use them.

I know developers usually dislike writing documentation. Therefore, I thought I would give you a hand. Under... https://github.com/flameshot-org/flameshot#installation why not include something like this...

***********************
***********************
Updating package managers is a hassle. Therefore, well, I don't update them often. As a result they tend to contain outdated releases of Flameshot. In just a few minutes, you can install the latest stable release of Flameshot without too much hassle. Really. It's pretty easy. Try following these steps...

1. https://github.com/flameshot-org/flameshot/releases
2. Then download a file.
3. For example, let's say you were to download a file named.... `flameshot-0.9.0-1.debian-10.amd64.deb`.
4. Let's imagine you had downloaded `flameshot-0.9.0-1.debian-10.amd64.deb` to the following location on your computer: `/home/YOUR_NAME/downloads/`. In other words, imagine `/home/YOUR_NAME/downloads/` contained `flameshot-0.9.0-1.debian-10.amd64.deb`.
5. Then open a terminal.  (Normally `ctrl+alt+u` on "buntus", such as Ubuntu, Lubuntu, and Xbuntu, will open a terminal).
6. Pro tip: to paste into your terminal try "right clicking" on the terminal window with your mouse. Want a terminal that allows you to easily paste with `ctrl+v`? Try [kitty](https://github.com/kovidgoyal/kitty).
7. Enter the following into your terminal... `sudo dpkg -i /home/YOUR_NAME/downloads/flameshot-0.9.0-1.debian-10.amd64.deb`. Of course, replace `/home/YOUR_NAME/downloads/flameshot-0.9.0-1.debian-10.amd64.deb` with the actual path to the file you downloaded.
***********************
***********************

Previously I used `apt install flameshot` to install Flameshot. Until about 20 minutes ago I had the following version installed on my machine...

Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

Of course that's a very old version of Flameshot. It's not  0.9. It's not even  0.8 or  0.7. Rather it is  0.6.

**Comment by Raytle** [comment]
> This isn't really accurate, it's the distro's responsibility to update their packages each release. 

I'm sorry. I had not intended to denigrate you. Thanks for disabusing me of that misconception.


> Regardless we can put something similar in the documents.

In my mind a fun heading would be something like...

#### Do you want it fresh and hot... instead of cold and stale?

or

#### Here's how to get the good stuff

I presume that many users don't want to bother upgrading. Therefore, why not use "Fear of missing out" (FOMO) to persuade them to upgrade?
