### ISSUE TITLE
This is a typo (a mistake). It should be "much" not "mush".

### ISSUE THREAD

**Issue by Raytle** [flameshot-org/flameshot#1634]
This is a typo (a mistake). It should be[ "much" not "mush"](https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop)...

![Screenshot at 11-52 on Wednesday 19 May 2021](https://user-images.githubusercontent.com/81956552/118868232-cf74a500-b898-11eb-8c08-742a8831ec74.png)

**Comment by borgmanJeremy** [comment]
Can u fix via a PR?

**Comment by Raytle** [comment]
![Screenshot at 06-53 on Thursday 20 May 2021](https://user-images.githubusercontent.com/81956552/118990964-2ed5c200-b938-11eb-9d8f-72fa0fb95c3f.png)

I don't know what a PR is.

Maybe you misunderstood me.

The typo I referred to is located on https://github.com/flameshot-org.

**Comment by borgmanJeremy** [comment]
Okay, I fixed it. thanks
