### ISSUE TITLE
Add support for IMGBB

### ISSUE THREAD

**Issue by iMonZ** [flameshot-org/flameshot#1639]
Add support for the IMGBB.com hoster

**Comment by mmahmoudian** [comment]
It is related to #955

**Comment by borgmanJeremy** [comment]
You can track the progress here: https://doc.qt.io/qt-5.12/qtwidgets-touch-pinchzoom-example.html

**Comment by mmahmoudian** [comment]
@borgmanJeremy I believe it is related to #1929 as the imgbb.com is image sharing service.

@iMonZ would you please mention it in the #1929
