### ISSUE TITLE
MacOS cannot be opened

### ISSUE THREAD

**Issue by kaihendry** [flameshot-org/flameshot#1641]
**Describe the bug**
Cannot run it on MacOS Big Sur

**To Reproduce**
1. ` brew install --cask flameshot`

<img src="https://s.natalian.org/2021-05-22/flameshot.png">

**System Information**
<img src="https://s.natalian.org/2021-05-22/big-sur.png">

**Comment by MatheusR42** [comment]
Same problem here

**Comment by borgmanJeremy** [comment]
Yes this is not a problem with flameshot directly. The only way to remove this is to have apple digitally sign the application which costs us a yearly fee.

**Comment by ErickMwazonga** [comment]
Is there a solution to this problem?

**Comment by mmahmoudian** [comment]
@ErickMwazonga read the following:
- https://github.com/flameshot-org/flameshot/issues/1641#issuecomment-847894888
- #3049
- #2721

**Comment by jbothma** [comment]
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

> To override your security settings and open the app anyway, follow these steps:
>
> In the Finder  on your Mac, locate the app you want to open.
>
> Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.
> 
> Control-click the app icon, then choose Open from the shortcut menu.
> 
> Click Open.
>
> The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.

**Comment by iddqdiddqd** [comment]
Troubleshooting documentation has been filled out with the solution to this issue in https://github.com/flameshot-org/flameshot-org.github.io/pull/151
