### ISSUE TITLE
Edit created text annotations 

### ISSUE THREAD

**Issue by JaredStemper** [flameshot-org/flameshot#1644]
When typing out a quick annotation to add, I frequently might make a small typo, want to change the font style, or placement of the text. 

When viewing the "Tool Settings"/options I can see the previously created text annotations, but when selecting them (example text below) I'm not able to make any further changes.

![image](https://user-images.githubusercontent.com/31346981/119740262-9b2d5580-be51-11eb-8c13-386157b108ac.png)

I would love to see this feature built in! Regardless, this is a fantastic project and my go-to screenshot program!

**Comment by borgmanJeremy** [comment]
This is actually possible if you build from source or if you are on Arch you can install from flameshot-git. 

We have a release in the pipeline to officially release this feature but I've been really busy and haven't found the time to do the release.

**Comment by mmahmoudian** [comment]
As @borgmanJeremy mentioned, a feature has been implemented by @thepurple to modify annotations (moving, resizing, etc.). It will almost certainly be in the latest release (v0.10.0). In addition to the ways mentioned by @borgmanJeremy you can try it out through AppImage which has been [built automatically](https://github.com/flameshot-org/flameshot/runs/2633446461?check_suite_focus=true):
https://we.tl/t-Y8TEpb1bIY

**Comment by JaredStemper** [comment]
Thanks you two! I'm on v0.9.0 and hadn't realized that it was already included.

As a note, the WeTransfer link you sent was expired, but I'll go ahead and build from source like @borgmanJeremy suggested. 

Thanks again for all the hard work! It's greatly appreciated.

**Comment by mmahmoudian** [comment]
If you are on Arch-based distro, you can install from AUR (`yay -S flameshot-git`). But if you are not, you can easily compile it yourself as you mentioned. If you faced any issue, also check:

https://flameshot.org/guide/installation/compilation/
