### ISSUE TITLE
Flameshot 0.9.0 segfaults on startup, but latest git does not.  Is a new release viable?

### ISSUE THREAD

**Issue by AlexFolland** [flameshot-org/flameshot#1646]
**Flameshot version**
0.9.0 and latest git

**Describe the bug**
When running flameshot 0.9.0 on my machine, the only output I see is "Segmentation fault (core dumped)" now.  This was not the case until recently (some time this week; not sure exactly when), with the same flameshot version.  I installed `flameshot-git` from the AUR to check if that works, and it does not have the same problem.

**To Reproduce**
Install flameshot 0.9.0 and run it.  Maybe the latest nvidia driver or Linux 5.12, or something else that my system happens to have, is necessary to reproduce.  I'm not sure.

**Expected behavior**
Crashes are never expected.

**System Information**
- I'm running Manjaro 21.0.5 with the latest Nvidia driver available and Linux 5.12.
- Flameshot 0.9.0 was installed from the official Manjaro community repository.
  - I would ask Manjaro maintainers for a new update to the latest flameshot release, but 0.9.0 is the latest flameshot release.

**Additional commentary**
Maybe this could be solved by making a new flameshot release.  The latest git version seems great to me.  What do you think?

Thanks for all your hard work on flameshot.  It's awesome software.

**Comment by mmahmoudian** [comment]
If you install from AUR `flameshot-git`, which is maintained by me and @borgmanJeremy, you will get the latest changes in master branch and you are better to consider it as "nightly build" or "beta". At the moment of writing this comment, we are planning to release v0.10.0 soon and the one you get from AUR has therefore the version 0.10.0.

Now, back to your issue, I suspect that your issue can even be resolved in v0.9.0 simply by compiling it yourself. You can check the instructions here:
https://flameshot.org/guide/installation/compilation/

**Comment by felipejoribeiro** [comment]
Same issue here. After compiling the aur version (flameshot-git), everything is fine as well.

**Comment by borgmanJeremy** [comment]
0.10 was just released
