### ISSUE TITLE
Screenshot GUI never opens despite program seeming to run

### ISSUE THREAD

**Issue by papuSpartan** [flameshot-org/flameshot#1647]
**Flameshot version:** 5.15.2

**Describe the bug**
Flameshot starts and the system tray icon can be seen. However, the gui never actually appears and it is not possible to take a screenshot.

**To Reproduce**
run application normally

**Expected behavior**
screenshot gui opening

**System Information**
Arch 5.12.6-zen1-1-zen
WM: bspwm
Compositor: picom

**Console Output**
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

**Comment by mmahmoudian** [comment]
I wonder how did you even manage to get that old version of Flameshot from Arch repos. Please consider updating to the latest version (v0.9.0).

I close this issue for now. Feel free to reopen it if you had the same issue with the latest version.

**Comment by papuSpartan** [comment]
> I wonder how did you even manage to get that old version of Flameshot from Arch repos. Please consider updating to the latest version (v0.9.0).
> 
> I close this issue for now. Feel free to reopen it if you had the same issue with the latest version.

Still having the same issue with the v0.10.0 with similar output:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

**Comment by mmahmoudian** [comment]
@papuSpartan please make sure you have notification manager installed and the daemon is running. you can test that using the following command:

```sh
notify-send "some text here"
```

**Comment by papuSpartan** [comment]
@mmahmoudian notify-send does indeed work and I have installed notification daemon and set it to run on d-bus signals.

**Comment by papuSpartan** [comment]
@mmahmoudian it was through the AUR package `flameshot-git`

**Comment by mmahmoudian** [comment]
@papuSpartan I in general don't like mysterious solutions, but if it is solved already, let's close this issue and reopen it if it reappears.
