### ISSUE TITLE
[Request] add support for JPEG XL or a more compressed lossless format 

### ISSUE THREAD

**Issue by Darkcast** [flameshot-org/flameshot#1651]

**Comment by mmahmoudian** [comment]
I believe either duplicate of, or highly related to #1640

**Comment by mmahmoudian** [comment]
@Darkcast Flameshot now support saving is many more formats. Does this satisfy your feature-request?

![image](https://user-images.githubusercontent.com/390889/132332406-b7da7ad2-2254-4365-b9ba-b6c11049bfb6.png)

**Comment by borgmanJeremy** [comment]
We now support those new formats so I will close this.

**Comment by Killercat103** [comment]
> @Darkcast Flameshot now support saving is many more formats (thanks to #1680). Does this satisfy your feature-request?
> 
> ![image](https://user-images.githubusercontent.com/390889/132332406-b7da7ad2-2254-4365-b9ba-b6c11049bfb6.png)

I so not see how those formats satisfy the request for JPEG XL (*.jxl)? I would also like to see this support for this image format integrated into Flameshot. (Theres a library called libjxl for this btw)

**Comment by mmahmoudian** [comment]
@Killercat103 I think installing `libjxl` should do the trick. More info: https://github.com/libjxl/libjxl

**Comment by Killercat103** [comment]
Oh thank you for the info. I managed to get it working on Windows and will try to make it work on Gentoo Linux as well as I noticed Hyprland support has been merged 🙂

**Comment by novomesk** [comment]
On Gentoo:

`USE="avif jpegxl" emerge -1 kde-frameworks/kimageformats`

**Comment by jvschiavo** [comment]
Sorry, but I don't get it. How do we save in JPEG XL *lossless*?

Can we even change the quality parameters of JPEG XL (or other formats beyond jpeg)?

**Comment by jvschiavo** [comment]
> Sorry, but I don't get it. How do we save in JPEG XL _lossless_?
> 
> Can we even change the quality parameters of JPEG XL (or other formats beyond jpeg)?

For my second question, I think I got my answer on #506.

For my first question, I'm still not sure if it's possible (but I guess it's not).
