### ISSUE TITLE
Has flameshot gui deprecated ability to save to clipboard by pressing enter?

### ISSUE THREAD

**Issue by thepenguinthatwants** [flameshot-org/flameshot#1652]
Hi,
I've being using flameshot by taking screenshot and then saving to keyboard by pressing enter.
This feature seems to have being taken off.

It has being replaced by ctrl-c and I've tried to bind it to enter again but it doesnt seem to allow. Is there a reason for this?

**Comment by mmahmoudian** [comment]
@thepenguinthatwants No, I think from version 0.8.5 we introduced customizable shortcut keys and to comply with most other softwares we changed the default to <kbd>Ctrl</kbd>+<kbd>c</kbd>. You can customize the actions to your preference from GUI (the image below) or modifying the config file and set `TYPE_COPY=Return`



![image](https://user-images.githubusercontent.com/390889/120345873-8d6d4980-c303-11eb-96fd-bb57665aa06b.png)
![image](https://user-images.githubusercontent.com/390889/120346121-bee61500-c303-11eb-9f1d-1d54f255a8cb.png)

**Comment by mmahmoudian** [comment]
I just realized you mentioned that you cannot change the shortcut. Please try the methods above and let me know how it goes.

**Comment by thepenguinthatwants** [comment]
Writing to the flameshot.ini file did the trick. Thanks!!

**Comment by ElijahLynn** [comment]
Crosslinking my related issue: https://github.com/flameshot-org/flameshot/issues/1671
