### ISSUE TITLE
Get screen from different user using root

### ISSUE THREAD

**Issue by CrazySky2121** [flameshot-org/flameshot#1653]
Hello! It would be great to be able get screens from different user using root in Wayland.

For example:

```
flameshot full -p /root -u <user>
```

or

```
export <something>
```

```
flameshot full -p /root
```

Is there no such possibility at the moment?

**Comment by mmahmoudian** [comment]
Can you elaborate on the use case? I can't imagine how such feature can be useful and be used for good.

**Comment by borgmanJeremy** [comment]
I dont think we can support this due to the way we grab the screens.
