### ISSUE TITLE
capture rectangle area bug in arch linux flameshot-git repo.

### ISSUE THREAD

**Issue by zw963** [flameshot-org/flameshot#1654]
**Flameshot version**
Name            : flameshot-git
Version         : r1354.8f6b6b08-1

 ╰─ $ flameshot --version
Flameshot v0.10.0
Compiled with Qt 5.15.2

It is a new version which introduce the new feature in #782 

**Describe the bug**

This bug was never happen on older flameshot version, it only happen frequently after i update to use new version.

When i start to add a screenshot with `flameshot gui ` command, i create a rectangle selection with mouse, after done,
then use `Ctrl+C` to copy rectangle area to system clipboard.

The current issue is, it copy the entire desktop into clipboard frequently when i `Ctrl+C`, this case never happen when use
arch linux old `flameshot` package (not flameshot-git)

I hard to reproduce, but, that happen frequently. maybe because i press `Ctrl+C` twice?  i have no idea.

**Expected behavior**
always capture the rectangle area as old version does.

**System Information**
arch linux.

**my config**

```
[General]
contrastOpacity=188
disabledTrayIcon=false
drawColor=#ff0000
drawFontSize=37
drawThickness=4
savePath=.png
savePathFixed=false
showStartupLaunchMessage=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

thank you.

**Comment by mmahmoudian** [comment]
I cannot reproduce this on Manjaro and Flameshot v0.10.0 even after pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> twice.

**Comment by zw963** [comment]
okay,  i will switch back again to test it.

flameshot-git-r1369.6a54285f-1

**Comment by mmahmoudian** [comment]
@zw963 Thank you. It would be great if we can have a deterministic way to reproduce it, because it makes it easier to fix the bug.

**Comment by zw963** [comment]
In fact, i don't know why, when i switch to use `flameshot-git r1372.91919387-1` in arch, i start to copy both my two desktop (i use a external monitor) instead of only selected region when i pressing `Ctrl+C` occasionally.

But, i can confirm this never happen on current released version.

**Comment by mmahmoudian** [comment]
Please reopen this issue if you happen to experience the same bug

**Comment by zw963** [comment]
@mmahmoudian , Hi, i can't reopen this issue, but i can reproduce it now, though, that is maybe not flameshot issue, it caused by i change my touchpad to enable `tap-and-drag-lock` settings.

### following is reproduce

1. run `flameshot gui`
2. draw a rectangle use my touchpad. i my finger not left touchpad and click again, current rectangle will keep pressed (if use mouse, it same as left button keep pressed)
3. Press `Ctrl+C` hot key, try copy rectangle area into clipboard, but, it capture full desktop to clipboard.


### What i expected:

If i draw a rectangle, but never released, i expect `Ctrl+C` no operation instead of copy full desktop.

Thank you.

**Comment by mmahmoudian** [comment]
@zw963 the way Flameshot works is that when you open `flameshot gui` (before selecting the capture area), it assumes tgat you want all of the screen. To test this you can do:
1. `flameshot gui` (don't even touch your mouse
2. press <kbd>Ctrl</kbd>+<kbd>c</kbd>
3. Check the file. It should be a fullscreen screenshot.

This is intended behaviour and is not a bug.

Thank you for clarification and all the information. I'm glad that you found the issue. Please feel free to open bug reports if you faced any bug.

**Comment by zw963** [comment]
> * `flameshot gui` (don't even touch your mouse
> 
> * press Ctrl+c

Yes, i know this is expected behavior, but, if it is possible when user start to create a rectangle region use mouse, but before release this mouse, to create the region,  we can disable this default behavior temporarily?

Thank you.

**Comment by mmahmoudian** [comment]
> when user start to create a rectangle region use mouse, but before release this mouse, to create the region, we can disable this default behavior temporarily?

That makes sense. Would you please create a feature request suggesting this?
