### ISSUE TITLE
Ability to quicksave

### ISSUE THREAD

**Issue by flriancu** [flameshot-org/flameshot#1655]
Hi, this feature request is inspired from a similar feature in Lightshot.

When using a key combination (for example in the case of Lightshot it would be Shift + Print Screen), the current full screens would be immediately saved to disk.

* In the above case, a single image with the concatenation of all displays would be saved, though maybe with Flameshot the user could choose between a single combined image, or one image for every display.

This is useful in cases where one needs to make several screenshots in quick succession, on short notice (e.g. when watching a live stream, a movie etc.).

In the case of Flameshot, a potential issue may be when the user did not check "Use fixed path for screenshots". This could potentially be solved for example by having a separate fixed path for quicksaves, or have the app always use a fixed path, or only having it work when the user has chosen to use a fixed path etc. (I'm honestly not sure about the proper approach).

Looking forward to feedback.

**Comment by mmahmoudian** [comment]
You can use command line and bind the shift+printscreen to `flameshot full -p "/path/to/folder/$(date +%s.%N).png"`
The `date +%s.%N` guarantees in nanoseconds that you will not overwrite the previous screenshot unless you take two screenshots in the same exact nanosecond!

Does this solves your issue?

**Comment by flriancu** [comment]
I'm using the app on Windows, where the command-line options (e.g. `full`, `config`) don't seem to generate any output (it's entirely possible I'm missing something).

The `Shift+Print Screen` combination was only an example w.r.t Lightshot - maybe `Ctrl+Print Screen` would be more appropriate, given that `Shift+Print Screen` is already used for screenshot history, and it doesn't seem to be editable.

**Comment by mmahmoudian** [comment]
Yes, Windows in general is not designed to be user-friendly and customisable. Perhaps there is a software to let users modify the shortcuts.

Regarding the command prompt, perhaps you can try it in powershell. But note that the command I gave above is GNU specific and will not work in Windows.

Perhaps @ZetaoYang knows better how to get this working in Windows.

**Comment by flriancu** [comment]
A bit off-topic, but looking at the existing issues, I found this comment on #1579. It says that command-line options are disabled on Windows, though I can't seem to find any reason as to why, or any way to enable them.

**Comment by borgmanJeremy** [comment]
The reason they are not currently enabled is they are just a wrapper to dbus calls which does not exist on windows. We need to reimplement the cli system to use a different IPC system or avoid IPC all together.

**Comment by borgmanJeremy** [comment]
Closing since this will be solved when CLI is added to windows and this is tracked via #1579
