### ISSUE TITLE
Rectangle marker

### ISSUE THREAD

**Issue by gabriele-v** [flameshot-org/flameshot#1657]
Hello, I'm not sure if I was not able to find it or it's not there.

Is it possible to have a marker but with rectangle selection?
How can I highlight for example all the rectangle on the right?
![image](https://user-images.githubusercontent.com/7106290/120970430-b78f9300-c76b-11eb-8dfe-08828875c273.png)

**Comment by mmahmoudian** [comment]
For regional selection, it it common to draw a rectangle around the area of interest, So I believe this is not implemented, but it just occurred to me that by changing the color of the rectangle tool and make it transparent, one can achieve what you are looking for.

**Comment by gabriele-v** [comment]
Yes, my example was not the real scenario, consider for example a text where you need to select two rows or something like that where a line could be too close or confusing.

Could be related to this? https://github.com/flameshot-org/flameshot/issues/249

**Comment by mmahmoudian** [comment]
Yes,  I have totally forgotten we have already that feature request ( #249).
Basically, as I showed, the bits and pieces are there, one should just implement a way to adjust that in GUI.

Shall we close this favor of #249?

**Comment by gabriele-v** [comment]
Yes, just continue there
