### ISSUE TITLE
on Big Sur, using the hardcoded key causes screens to scroll away

### ISSUE THREAD

**Issue by mcampbell** [flameshot-org/flameshot#1658]
**Flameshot version**
0.9.0

**Describe the bug**
After upgrading to big sur, when I hit ctrl-shift-alt-4, both of my 2 external monitor "screens" scroll to the left, or disappear, leaving me nothing to actually capture.

I should note I am running in "clamshell" mode; laptop screen is off, 1 screen is driven through USB-C -> DVI, the other is USB-C -> hub/converter -> VGA.

This same setup worked fine in Catalina; the change was my upgrade to Big Sur.

**To Reproduce**
Ctrl-shift-alt-4

**Expected behavior**
For Flameshot to not "scroll away" the screens under the cursor.

**System Information**
MacOS Big Sur V11.4 (20F71)

Movie of behavior attached.

https://user-images.githubusercontent.com/692557/121031475-5e7a2c00-c778-11eb-8962-bad61fad7d61.mp4

**Comment by MarcelBochtler** [comment]
I do have the same issue on Big Sur.
Additionally I get the screen recording permission popup every time, even if I granted the permission already.

![Screenshot 2021-06-07 at 22 23 37](https://user-images.githubusercontent.com/4022103/121083105-4db0d100-c7df-11eb-8c78-f9be14e96336.png)

**Comment by borgmanJeremy** [comment]
Unfortunately I don't have a machine running bigsur. We will need community help digging into this.

**Comment by mcampbell** [comment]
@MarcelBochtler GOOD CATCH!  I didn't even think to check that since I was not getting the popup, but this led me to a workaround.  I tried removing, and giving back, flameshot the permission and this did not work.  What DID work was to completely remove flameshot from the list, quit flameshot, restart flameshot, let the dialog pop up, then giving it permissions.

https://i.imgur.com/RbsAzd6.png  (<-- uploaded with flameshot!)

**Comment by mcampbell** [comment]
@borgmanJeremy Not sure if we can close this, but it seems (at least for me), completely removing flameshot from the permissions list; like removing the app altogether, not just turning it "off"; and then re-adding it when flameshot requests permissions seemed to work.

**Comment by MarcelBochtler** [comment]
Thanks for the hint.
Removing and readding flameshot in the permissions works, while reinstalling flameshot somehow doesn't.

**Comment by nowell-morris** [comment]
Yeah, it is not that the screens scroll to the side, it's just that the "screen recording" permissions are not being honored if you upgrade to Big Sur.  The movement of the screens is Mac's way of showing that it will allow flameshot only permissions to see its icon in the status bar.  
mcampbell's solution worked!
