### ISSUE TITLE
Flameshot refuses to work without dbus

### ISSUE THREAD

**Issue by l29ah** [flameshot-org/flameshot#1663]
When it fails to read `/etc/machine-id` or launch `dbus-launch` (due to security policies, for instance), `flameshot gui` hangs silently and indefinitely, even though it doesn't need to speak with any other dbus applications to do its job.

**Comment by l29ah** [comment]
Apparently, DBusUtils::checkDBusConnection's check fails, as QDBusConnection thinks it's connected for some strange reason.

**Comment by l29ah** [comment]
Looking at the code, it seems like flameshot speaks to itself via dbus.

**Comment by mmahmoudian** [comment]
Yes, `flameshot gui` (or any other sub command for that matter other than `help` I assume) is basically sending a command to Flameshot process through dbus. Therefore Flameshot should not work then dbus is not there.

Shall we consider this as a feature request to "throw some proper error if dbus cannot be found"?
