### ISSUE TITLE
How to build flameshot with cmake on win10?

### ISSUE THREAD

**Issue by Fifate** [flameshot-org/flameshot#1664]
when I build with cmake on win10, I got some problem.

First, I cmake it but got this:
```
$cmake -G "MinGW MakeFiles" ..
CMake Error at src/CMakeLists.txt:319 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to  command.
```
So I open the src/CMakeLists.txt:319，which like tihs:
![image](https://user-images.githubusercontent.com/65692635/121759334-c99c7780-cb57-11eb-8daa-f1ef51e7043f.png)

Because I didn't use openssl, so I put "src/CMakeLists.txt:319" after `if`.
Then I cmake it again, and this time it just tell me 2 waring:
```CMake Warning at cmake/Cache.cmake:28 (message):
  ccache is enabled but was not found.  Not using it
```
```
CMake Warning at src/CMakeLists.txt:204 (message):
  OpenSSL is required to upload screenshots
```
Finally I make it but errors occurred.
```[  1%] Automatic MOC for target SingleApplication

make[2]: *** [external\singleapplication\CMakeFiles\SingleApplication_autogen.dir\build.make:70: external/singleapplication/CMakeFiles/SingleApplication_autogen] Error 1
make[1]: *** [CMakeFiles\Makefile2:301: external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/all] Error 2
make: *** [Makefile:155: all] Error 2
```
Is this the reason of  the 2 warnings or others？
My system enviroment is set as below:
$QTDIR = G:\program\qt\install\5.12.9\mingw73_64
$MinGW = F:\program\mingw\mingw64
$Path = %QTDIR%\bin; %MinGW%\bin;

How can I solve the errors and build flameshot on win10?

**Comment by jialeens** [comment]
You can change this 319 line `$ENV{OPENSSL_ROOT_DIR}` to `"$ENV{OPENSSL_ROOT_DIR}"`，like this
``` 
STRING(REGEX REPLACE "\\\\" "/" OPENSSL_ROOT_DIR $ENV{OPENSSL_ROOT_DIR} )
```
to
```
 STRING(REGEX REPLACE "\\\\" "/" OPENSSL_ROOT_DIR "$ENV{OPENSSL_ROOT_DIR}" )
```
