### ISSUE TITLE
On MacOS the icon in the top bar stretches with multiple displays

### ISSUE THREAD

**Issue by danielgroen** [flameshot-org/flameshot#1665]
This issue occurs when i have 2 displays which have different resolutions.
The icon stretches dependant on which screen i am focussed.

So if i am focussed with my mouse at screen 1, the icon in screen 2 looks like this:
![afbeelding](https://user-images.githubusercontent.com/6578052/121853351-1d8e9400-ccf1-11eb-8868-642de26a5579.png)

I'm running on `Big Sur`

**Comment by thepurple** [comment]
This is an issue in the Qt 5.x library, unfortunately it cannot be fixed at this time. 
Hopefully, when we have time to migrate to Qt 6, the problem will go away.

**Comment by borgmanJeremy** [comment]
Closing since it's an upstream issue we cannot fix.
