### ISSUE TITLE
The error sound plays when I try to take a screenshot

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1666]
**Flameshot version**

Latest git version.
**Describe the bug**

When I try to make a screenshot,then I get the error sound,but everything works.
**To Reproduce**

press your shortcut to take a screenshot.
**Expected behavior**

That I don't get an error sound
**System Information**

Arch

**Comment by mmahmoudian** [comment]
I very much doubt that this is Flameshot issue as it is triggered by your OS and window manager. There is only one scenario that this might happen as far as I can think of, which is you are always killing Flameshot process and every time you want to make the screenshot, you are running the Flameshot again which pushes one notification. Perhaps @borgmanJeremy can weigh in and give us his thoughts on this.

Apart from what I mentioned above, I would be thankful if you **completely** provide all the requested information in the bug report. Some of the things you have failed to mentioned:
- Flameshot version and the way you have installed it (I know you have compiled it yourself, but not everyone reads every single issue and remembers who have done what)
- Your DE/WM

**Comment by Toadfield** [comment]
I use kde and latest git flameshot from aur.

**Comment by mmahmoudian** [comment]
And I assume you are [still on Wayland](https://github.com/flameshot-org/flameshot/issues/1380#issuecomment-859194058). Can you also confirm that?

Also the latest git as you know is prune to change very frequently. At the moment I'm working on a way to create more accurate versioning system for users how use AUR.

**Comment by Toadfield** [comment]
Yes I am still on wayland.
I use flameshot version r1354.8f6b6b08-1.

**Comment by borgmanJeremy** [comment]
I tested this on v0.10.0 and don;t seem to hear the error sound.

I do hear the notification sound. This is because by default KDE Notification service plays a sound, this can be disabled if you want.
