### ISSUE TITLE
Sub commands not opening

### ISSUE THREAD

**Issue by Davincible** [flameshot-org/flameshot#1670]
This is another one of those issues with subcommands not opening. I use Manjaro, and used to use KDE, there it worked perfectly, now I switched to i3, and flameshot isn't working. I am launching via dbus. The only way to get it to work is to enable systemtray in polybar, and then launch & click the icon. But the sub commands don't work, so I can't bind shortcuts. Don't get any errors from the commands.

Using `Flameshot v0.9.0 Compiled with Qt 5.15.2`, kernel 5.12, i3-gaps, launched with `dbus-launch`

**Comment by mmahmoudian** [comment]
Flameshot depends on two things that tiling WM users usually overlook:
1. systray
2. notification daemon

Would you please follow these steps and report back:
1. you have the systray enabled
2. your notification is working (`notify-send "test text"`)
3. when seeing the Flameshot icon in systray, run `flameshot gui` in a terminal

**Comment by Davincible** [comment]
Ahhh I think the notification daemon is the issue, I'm trying to set up dunst but that's also giving issues.

I do have systray enabled in polybar, and clicking the systray icon does work. Running flameshot first and then flameshot gui also does nothing.

**Comment by mmahmoudian** [comment]
In future versions we **might** move away from having notification and systray as hard dependencies, but considering the amount of refactoring it needs, most probably it will not happen in close future. But stay tuned 🙂
