### ISSUE TITLE
New version (10) is auto-uploading to imgur: how to turn off?

### ISSUE THREAD

**Issue by ElijahLynn** [flameshot-org/flameshot#1671]
**Flameshot version**
❯ flameshot --version
Flameshot v0.10.0
Compiled with Qt 5.15.2

**Describe the bug**

I just updated to latest Flameshot and now all my screenshots upon pressing `<enter>` are being uploaded to Imgur and not copied to clipboard like previous behavior. 

How can I make this stop? I don't see an option in config/settings for this:
![image](https://user-images.githubusercontent.com/1504756/122471876-a9fcb900-cf74-11eb-9d6c-80ab6af8d11c.png)

**System Information**
Arch Linux

**Comment by mmahmoudian** [comment]
I assume the missing word in you text is "Enter". If I correctly guessed the missing word, then please go to the next tab on the right in your settings and configure the <kbd>Return</kbd> (a.k.a Enter) to what ever action you want, **and also close this issue**.

If I guessed the word wrong, please let us know in the comment the complete sentence so that we can investigate.

**Comment by ElijahLynn** [comment]
Thank you, yes, the markdown stripped out `<enter>` as it thought it was HTML I guess. I made it a code block now. 

Your suggestion worked, I deleted that new default shortcut mapping and assigned it back to copy to clipboard. 

Lastly, this is a pretty rough security issue. I just uploaded a bunch of personal finance information to Imgur and have no way to delete it. I don't think it was wise to default `<enter>` to uploading to Imgur and is likely going to result in uploading a ton of sensitive information to Imgur without peoples consent. Uploading to Imgur should have been/and still still should be an opt-in setting because of this.

**Comment by mmahmoudian** [comment]
You can, just right click on the tray icon, go to the screenshot history and delete them

**Comment by ElijahLynn** [comment]
> You can, just right click on the tray icon, go to the screenshot history and delete them

Nice, that worked!!! Phew!

**Comment by ElijahLynn** [comment]
> Also for future reference `<kbd>Enter</kbd>` will translate to Enter

Today I learned, thanks!

**Comment by mmahmoudian** [comment]
You can always reach us in Matrix or Slack if it is such emergency.

https://matrix.to/#/#Flameshot:feneas.org

https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg
