### ISSUE TITLE
Unable to capture screen started using first launch of `flameshot gui` command on Sway

### ISSUE THREAD

**Issue by ritikrajdev** [flameshot-org/flameshot#1673]
**Flameshot version**
v0.10.0
r1355.35a6d430-1

**Describe the bug**
on starting flameshot with `flameshot` command it works normally as it should do, but when used `flameshot gui` (Flameshot shouldn't be running already), it doesn't work and says unable to capture the screen + there's no icon of flameshot in the system tray.

Here's the preview of the issue mentioned (tested on my Arch Linux - 5.12.11-zen1-1-zen, Sway).

https://user-images.githubusercontent.com/56875929/122627800-8d28c880-d0cf-11eb-8aa3-33867da6e96d.mp4

**To Reproduce**
1. Use sway, waybar(to check system tray icon not showing)
2. export QT_QPA_PLATFORM=wayland
3. now just start flameshot using just `flameshot` command
4. try to capture screenshot using `flameshot gui`, it'll work now !
5. end the process after checking that it works (ctrl + C)
6. `pkill flameshot` just for surety that no instance of flameshot is running
7. now start flameshot with `flameshot gui` command and try to capture screenshot.

**Expected behavior**
I Expected to work it on starting even with flameshot gui + it doesn't look good having no icon in system tray of waybar when started with `flameshot` command only.

**System Information**
Arch Linux - 5.12.11-zen1-1-zen, Sway

**Comment by mmahmoudian** [comment]
I realized that the icon shows properly when you run `flameshot gui` but you see no icon when you run `flameshot`.

What happens when you do another `flameshot gui` for the second time without killing the first one?

**Comment by ritikrajdev** [comment]
> I realized that the icon shows properly when you run `flameshot gui` but you see no icon when you run `flameshot`.
> 
> What happens when you do another `flameshot gui` for the second time without killing the first one?
> 
> 

When i do `flameshot gui` for second time it takes screenshot only if the process was initiated using `flameshot` command.

The icon above remains unaffected in each case, means no icon if started using `flameshot`, flameshot icon if started using `flameshot gui`.

**Comment by mmahmoudian** [comment]
What I meant was to do something like this:
```sh
pkill flameshot; sleep 1s; flameshot gui; sleep 3s; flameshot gui
```

**Comment by ritikrajdev** [comment]
> What I meant was to do something like this:
> 
> ```shell
> pkill flameshot; sleep 1s; flameshot gui; sleep 3s; flameshot gui
> ```

sorry for late reply was just checking the thing again
As expected, it sent the notification stating **Unable to capture screen** two times.

**Comment by ReneganRonin** [comment]
idk if this is relevant but when this happens, I usually just compile flameshot from source with qt-wayland-devel and weirdly enough that fixes it.

**Comment by mmahmoudian** [comment]
@ReneganRonin I don't see such package in the Arch repositorIes or AUR. What is your OS and what is your qt-wayland version?

**Comment by ReneganRonin** [comment]
@mmahmoudian it is actually the qt5-wayland-devel package from Void Linux (which I am currently using).

**Comment by ReneganRonin** [comment]
@ritikrajdev btw, try adding `XDG_CURRENT_DESKTOP=sway` when starting flameshot. I also do that when I am on river, otherwise it will not start correctly.

**Comment by ritikrajdev** [comment]
> @ritikrajdev btw, try adding `XDG_CURRENT_DESKTOP=sway` when starting flameshot. I also do that when I am on river by tricking flameshot that it is on sway, otherwise it will not start correctly. Also refer https://github.com/flameshot-org/flameshot/issues/1570

I do that on tty before launching sway.
Hence `XDG_CURRENT_DESKTOP=sway` is already set universally in sway.

**Comment by ritikrajdev** [comment]
I found a thing that may help in resolving i think,

it's not only happening on one single command `flameshot gui`
instead it is happening for each of the command `flameshot screen -c`, `flameshot full -c`. (-c is just for copying to clipboard)
if all these commands are run when there's a running instance of firefox using `flameshot` command only then they all work, but when flameshot is started using those commands instead, then it shows unable to capture screen.

as per my thinking, process of initialisation of flameshot daemon is different in all those sub commands as compared to the main flameshot command.

**Comment by veracioux** [comment]
Please check if the newest master (233c765b1fa82a2bfd92cfd7bfbb324464165efb) helps with this issue. You can compile it or download from [here](https://flameshot.org/docs/installation/development-build).
