### ISSUE TITLE
Capture screen also when right click menu in view, or panel drop downs in view (gnome)

### ISSUE THREAD

**Issue by spxak1** [flameshot-org/flameshot#1675]
**Is your feature request related to a problem?**

Gnome 3.38 on Pop 20.10.

I have flameshot on ```ctrl+shift+F``` and it works fine, however, if I have a drop down from the top panel (openweather extension, or the notifications/calendar, or the main drop down -wifi/eth/power), flameshot will not open.

I need to run ```flameshot launcher``` set the delay to a few seconds, click to open the drop down (or right click on desktop to make the context menu appear) for it to be captured.

It would be great if ```flameshot gui``` could be invoked (as it happens with my shortcut``` also when these items are open.

Example: https://i.imgur.com/XQYtmIN.png 
I had to do a time delayed capture for this.

Thank you for this amazing tool. Very much appreciated.

**Comment by mmahmoudian** [comment]
This has already been implemented. The following is an example from [our webpage](https://flameshot.org/advanced/command-line-options/):

open GUI with a delay of 2 seconds:

```sh
flameshot gui -d 2000
```
