### ISSUE TITLE
I want to be able to easily change, for example, the line thickness *after* I have drawn a line.

### ISSUE THREAD

**Issue by Raytle** [flameshot-org/flameshot#1676]
Oftentimes **after** I have drawn, for example, a line I want to change that line's thickness. Of course to do this I choose undo, change the line thickness, and then redraw the line. I would prefer to be able to change the line thickness **after** I have drawn a line.

Yes, I realize the distinction between raster ("paint programs") and vector ("draw programs"). Yes, I realize that Flameshot seems to be a raster program.

By the way, I've been playing around with using Google Draw to edit my screenshots. Please see, [Playing around with Google Drawing for editing screenshots](https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/edit?usp=sharing). After using Google Draw to edit one of my screenshots I can then open Flameshot, select the part of the Google Draw document I want to upload to Imgur, and upload it to Imgur.

**Comment by mmahmoudian** [comment]
Install the latest version, draw the line. Then change click on the line button to deselect it, then just click on the line. This way you can move around the line and change all the properties incline the thickness. Also in close future we are releasing a feature to be able to save the screenshot as SVG so that users can use Inkscape or any other vector graphics tool to edit their annotations.

Try what I explained above and let me know how it works for you (I will keep this issue open).

**Comment by Raytle** [comment]
> Install the latest version

In my terminal, I entered`flameshot -v` I hade...
Flameshot v0.9.0
Compiled with Qt 5.12.8

Therefore I went to https://github.com/flameshot-org/flameshot/releases and downloaded `flameshot-0.9.0-1.ubuntu-20.04.amd64.deb`.

Then, in a terminal, I ran...

`sudo dpkg -i flameshot-0.9.0-1.ubuntu-20.04.amd64.deb`

It was installed successfully.



> draw the line. 

I did.


> Then change click on the line button to deselect it,

Did you mean, "Then click on the line button to deselect it." In other words, is the, word **change** in "Then change click..." extraneous?


> then just click on the line. 

I did.


> This way you can move around the line and change all the properties incline the thickness. 

You probably meant **including** not **incline**. Right?

I was unable to. In other words, that did not work for me.

Perhaps you might create a 10 to 20 second screencast for me. I use [OBS studio](https://obsproject.com/) to create screencasts.  Of course many other screencasting applications exist. Screencasts up to 60 seconds can be uploaded to Imgur. See... [How to Upload Video (to Imgur)](https://help.imgur.com/hc/en-us/articles/360003632072-How-to-Upload-Video)


> Also in close future 

In English the word **close** is normally used for physical proximity; whereas the word **near** is used for temporal proximity and physical proximity. Don't ask me why. English has many nonsensical rules. When I used to teach conversational English I simply told my students something like, "English has many nonsensical rules. I think many of these are foolish. However, if you want to communicate properly in  English you need to learn many nonsensical rules."


> we are releasing a feature to be able to save the screenshot as SVG so that users can use Inkscape or any other vector graphics tool to edit their annotations.

Good!

Have you considered allowing users to easily copy their screenshot to a particular Google Drawing URL? For example, the URL for the document which I created named, [Playing around with Google Drawing for editing screenshots](https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/) is, https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/.

In case you are confused please see, https://i.imgur.com/7KHm5ke.png

I suppose my workflow would normally be either of the two following scenarios:

### Scenario 1 (for screenshots I only annotate briefly)
1. Take a screenshot with Flameshot.
1. Briefly annotate it.
1. Upload it to Imgur.com

or

### Scenario 2 (for screenshots I only annotate in significant detail)
1. Take a screenshot with Flameshot.
1. Click on a tool button that does yet not currently exist in Flameshot—but I am imagining you might add to Flameshot—that would copy the screenshot I had just taken and then open that screenshot in the Google Drawing whose URL I would have entered into my Flameshot preferences such as, https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/
1. Significantly annotate my screenshot in detail in my Google Drawing.
2. Take a screenshot with Flameshot of my Google Drawing.
1. Upload it to Imgur.com

Why would I want to use an **existing** Google Drawing document? Why wouldn't I want open a new Google Drawing document? Because I would have some of my own "tools" already open in my Google Drawing. Furthermore, Google Drawings automatically saves revisions which means if I were to inadvertently replace a version of Google Drawings with a new information, I would be able to easily retrieve my previous drawing. For more information please see, [Use revision history in Google Files](https://gsuitetips.com/tips/docs/use-revision-history-in-google-files/).


> Try what I explained above and let me know how it works for you (I will keep this issue open).

As I indicated above, I tried yet I failed.

**Comment by mmahmoudian** [comment]
@Raytle Thanks for comprehensive explanation and also the quick English lesson. I typed those when I just woke up and most of typos were caused by typing on my phone less than a minute after I've woke up. But as you have guessed it, English is not my mother tongue.

I quickly recorded a Gif using Peek and ScreenKey to demo what I meant:
![Peek 2021-06-21 17-16](https://user-images.githubusercontent.com/390889/122777560-d128f280-d2b4-11eb-8a1c-7187c119725d.gif)

**Comment by Raytle** [comment]
> Thanks for comprehensive explanation and also the quick English lesson. 

Sure.


> I typed those when I just woke up and most of typos were caused by typing on my phone less than a minute after I've woke up. But as you have guessed it, English is not my mother tongue but I'm hoping I'm not that bad in it either sweat_smile.

No problem. 


> I quickly recorded a Gif using Peek and ScreenKey to demo what I meant:
Peek 2021-06-21 17-16

Thanks for creating the screencast for me. It's excellent. I suggest you put it on the Flameshot homepage under a category named, "**Coming Soon!**" with the following verbiage, "The following feature is currently available in `flameshot-0.10.0.rc1`. It's so hot; it's cool!"

> Regarding your remark about non-existing tool, yes we don't [yet] support uploading to any other services, but reading your scenarios make me wonder why don't you use the "copy to clipboard" tool (or simply press Crrl+c) to copy the screenshot with all the annotations and then paste it into your preferred editor application

I suppose that I might end up using, for example, [maim](https://github.com/naelstrof/maim) to send a screenshot to an existing Google Drawing document of mine. Frankly, I suppose I might abandon Flameshot altogether. See, I found Flameshot a couple of years ago. I like it. But I wearied of being unable to edit screenshots like I can in a diagramming application such as Google Drawings.

**Comment by Raytle** [comment]
I installed [maim](https://github.com/naelstrof/maim). It was a delightfully quick and easy process. Then, after viewing...

1. [maim copy screenshot clipbboard and save to specified location?](https://www.reddit.com/r/linuxquestions/comments/cbiu3t/maim_copy_screenshot_clipbboard_and_save_to/) and,
2. [Read a URL from a file and open it in a Firefox tab](https://askubuntu.com/a/865575)

I cobbled (kludged) together the following Bash script which, frankly, I don't fully understand. But it more or less does what I want, which is...

1. It allows me to drag on my screen to select a portion of my screen—which is almost always what I want to be able to do—as opposed to, for example, taking a screenshot of my entire screen or of an entire window.
2. It then copies that selection to my clipboard, and 
3. saves that selection to my local drive.
4. Finally it opens an existing Google Drawing of mine.

```
#!/bin/sh

maim -s /home/pictures/screenshot.png ; cat /home/pictures/screenshot.png | xclip -selection clipboard -t image/png
echo "https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/edit" > foo && google-chrome-stable -new-tab
```
I bound it to a key combination using [Shortcut Keys](https://manual.lubuntu.me/stable/3/3.2/3.2.14/shortcut_keys.html). The script above ends up putting a tiny file named `foo` in my home directory which contains https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwl2HJ23bnuyGSuwNojgUkxyF4froM/edit. I don't want that `foo` file in my home directory—although it is tiny, less than 1k, it is clutter—but I'm not sure how to get rid of it. I tried removing `foo` from the Bash script above but each time I removed it,  the subsequent time I ran the Bash script, it worked improperly (at least from my vantage point).

I'm neither an engineer nor do I aspire to become an engineer. I try to learn as little as possible about computers. When I learn stuff I need type notes in what has become a shockingly copious number of Google Docs I have hyperlinked together to create my own little knowledge base. Then I try to quickly forget as much as possible of the new "computer stuff" I just learned because it leaves me feeling ice cold and is—at least in my opinion—a waste of time for me to bother trying to remember. Yeah. Sure. I can and do perform some elementary "computer stuff" such as cobbling together Bash and Python scripts, but I detest doing it. I'd rather watch grass grow or paint dry than do "computer stuff".

**Comment by mmahmoudian** [comment]
I'm glad you found a solution, but:

1. What you did with maim could have easily be done with Flameshot without the mess of writing into file and cat and xclip and etc. Simply do `flameshot gui -c` and it will copy the selected area.

2. This google draw thing you are insisting on is very much off-topic to this issue. The issue is about changing the thickness after drawing (which in the demo I showed it is both possible and available if you get the v0.10.0)

3. This repo is dedicated to Flameshot and although many softwares out there can do many great things, we prefer to keep the focus of this Gituhub project on Flameshot (for obvious reasons)

4. Flameshot like many many tools out there are designed to address specific needs. Many features will never be implemented and many will stay in the backlog simply because the devs of this project are doing this for free (zero fee, zero ads, zero telemetry).

5. There is a project I put together to help some users to get what they need:

https://codeberg.org/mehrad/dmenu_shot

You can modify the code and make your life easier instead of jumping through multiple hoops fir a simple copy action 👍🏼

-------

considering my second point, I will now close this issue.

**Comment by Raytle** [comment]
Thanks for taking the time to send that message to me along with those links. I appreciate that.

**Comment by Guitarheroua** [comment]
> [@Raytle](https://github.com/Raytle) Thanks for comprehensive explanation and also the quick English lesson. I typed those when I just woke up and most of typos were caused by typing on my phone less than a minute after I've woke up. But as you have guessed it, English is not my mother tongue but I'm hoping I'm not that bad in it either 😅.
> 
> I quickly recorded a Gif using Peek and ScreenKey to demo what I meant: [ ](https://user-images.githubusercontent.com/390889/122777560-d128f280-d2b4-11eb-8a1c-7187c119725d.gif) ![Peek 2021-06-21 17-16](https://user-images.githubusercontent.com/390889/122777560-d128f280-d2b4-11eb-8a1c-7187c119725d.gif) [ ](https://user-images.githubusercontent.com/390889/122777560-d128f280-d2b4-11eb-8a1c-7187c119725d.gif)
> 
> Regarding your remark about non-existing tool, yes we don't [yet] support uploading to any other services, but reading your scenarios make me wonder why don't you use the "copy to clipboard" tool (or simply press Crrl+c) to copy the screenshot with all the annotations and then paste it into your preferred editor application.

Is there a way to resize drawn elements, such as arrows or rectangles? Currently, it seems possible to edit only their position, thickness, and color.

**Comment by Raytle** [comment]
That's what I wanted to do! Yes! Thank you very much for the helpful explanation. I appreciate.

By the way, at this point I don't remember why I used maim instead of Flameshot.

Hopefully peace will come soon to Ukraine. War is hell.
