### ISSUE TITLE
Flameshot chooses different windows on every printscreen

### ISSUE THREAD

**Issue by leynebe** [flameshot-org/flameshot#1677]
I run Arch Linux, X11, gdm display manager, kde plasma desktop environment.

I know this probably has nothing to do with flameshot but more my setup. I used to use flameshot on X11 and Gnome DE and that worked well. I switched to KDE (on a new laptop) and every time I press the prntscrn button it uses a different application to freeze flameshot on. It's also to be noted that every application isn't in the state anymore that I see frozen. If it chooses firefox for example, it will display tabs on firefox which I closed some time ago. It seems like it's a cached version of the application? I have no idea :)

I tried the installation file first https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde, then bound `/usr/bin/flameshot gui` to printscrn button but got the same results.

I don't really expect a solution but more of a guide on where to start searching if anyone knows.

Anyway, I love flameshot and it would be a shame if I had to go back to Gnome because of it, and I would because flameshot is amazing! 

Thanks!

Ben

**Comment by leynebe** [comment]
I found out it happens on the default KDE screenshotting tool as well so I'll search further in the arch or kde forums!

**Comment by leynebe** [comment]
This will probably fix my issue: https://bbs.archlinux.org/viewtopic.php?id=263247

**Comment by mmahmoudian** [comment]
@leynebe I appreciate your investigation. This is an issue a friend of mine had some weeks ago when he fresh installed Manjaro on an Ideapad. I saw a video recording of it and it was so bizarre. Would you please confirm if the removal of `xf86-video-intel` and rebooting solved your issue?

**Comment by leynebe** [comment]
Unfortunately I wasn't able to log in after removing the package so I reinstalled it and then logged back in. I may try again later.

I did notice however after logging in that it seemingly becomes worse the longer your session is.
I was trying it out right after logging in and got either a "KDE loading" screen or my actual screen when I pressed the button (50-50 split). 
When I use it and copy the image with ctrl+c (complete a flameshot gui run) the last frame of that flameshot run gets added as a new freeze frame when I try printscrning again. 
Not sure if I explained that well but the behavior is indeed very weird.

I would provide screenshots but yeah... that's the whole problem.

Thanks for picking this up even though!

**Comment by leynebe** [comment]
I reopened it since you show interest, but feel free to close since I don't think this is really flameshot's fault (?)

**Comment by leynebe** [comment]
The arch wiki also has a couple of things to say about the package, I hesitated first on using it but installed it anyway, but may indeed come back on the decision if it solves the issue and I can log in to my DE again.

https://wiki.archlinux.org/title/Intel_graphics#Installation

**Comment by leynebe** [comment]
I found out I had an X11 config `/etc/X11/xorg.conf.d/20-intel-graphics.conf` for the `xf86-video-intel` package. 
I had that config to reduce screen flickering but later fixed that with a kernel parameter. (https://wiki.archlinux.org/title/Intel_graphics#Screen_flickering)

Anyway, I removed the config and package, rebooted, was able to log in again and flameshot works correctly now!

**Comment by mmahmoudian** [comment]
@leynebe thanks for investigating this. I had no easy way to reproduce it. I will try to see if your approach also helps my friend's situation (he is not a linux user and is very hard to investigate this remotely on his laptop)👍🏼
