### ISSUE TITLE
Cannot Upload Screenshot to Imgur 

### ISSUE THREAD

**Issue by wrac4242** [flameshot-org/flameshot#1679]
**Flameshot version**

v0.9.0

**Describe the bug**

Attempting to upload a screenshot causes the `uploading to imgur` popup to appear, there it lasts for a long time, then comes up with a `Server Reply: Gateway error`
![image](https://user-images.githubusercontent.com/42539664/123090531-29303800-d420-11eb-9c33-3b84061d0fb4.png)

**To Reproduce**

Take a screenshot, attempt to upload it to Imgur 

**Expected behavior**

A successful upload to Imgur 

**System Information**

Fedora 33, GNOME 3.38.4

**Comment by mmahmoudian** [comment]
@wrac4242 Please check if you still have the problem. If so, please provide the output of the following two commands:

```sh
nslookup api.imgur.com
ping -c 10 api.imgur.com
```

**Comment by wrac4242** [comment]
@mmahmoudian 
```
[wrac@wracfedora ~]$ nslookup api.imgur.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
api.imgur.com	canonical name = ipv4.imgur.map.fastly.net.
Name:	ipv4.imgur.map.fastly.net
Address: 151.101.16.193

[wrac@wracfedora ~]$ ping -c 10 api.imgur.com
PING ipv4.imgur.map.fastly.net (151.101.16.193) 56(84) bytes of data.
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=1 ttl=57 time=15.9 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=2 ttl=57 time=11.1 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=3 ttl=57 time=14.5 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=4 ttl=57 time=11.3 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=5 ttl=57 time=8.43 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=6 ttl=57 time=9.20 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=7 ttl=57 time=11.2 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=8 ttl=57 time=10.1 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=9 ttl=57 time=13.4 ms
64 bytes from 151.101.16.193 (151.101.16.193): icmp_seq=10 ttl=57 time=14.3 ms

--- ipv4.imgur.map.fastly.net ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9011ms
rtt min/avg/max/mdev = 8.433/11.945/15.886/2.349 ms```

**Comment by wrac4242** [comment]
plus manual uploads are successful, [see here](https://imgur.com/a/gmjLOKX)

**Comment by mmahmoudian** [comment]
I doubt this is distro-specific issue, so I haven't tested it in a fedora VM and have only tested it on my Manjaro and couldn't reproduce it. Are you using some sort of proxy or VPN or even a browser extension that redirects your traffic?

**Comment by wrac4242** [comment]
nope, none of those

**Comment by wrac4242** [comment]
i could try building from source and seeing if its related to my system or the build

**Comment by wrac4242** [comment]
same error there

**Comment by mmahmoudian** [comment]
@wrac4242 The gateway error indicates some network issue rather than the build issue.

For now I just mark this as "unconfirmed bug" as I couldn't confirm it. Let's see what other devs and users can do about this.

**Comment by wrac4242** [comment]
The issue seems to have resolved itself now, thanks anyway

**Comment by mmahmoudian** [comment]
@wrac4242 I'm glad that is is now resolved. Flameshot at the moment uses our own Imgur account and API token which considering the large usebase we have, the quote can easily get maxed out. There are plans to let users use their own API key:
- https://github.com/flameshot-org/flameshot/issues/1542#issuecomment-815903534
- https://github.com/flameshot-org/flameshot/pull/955/

When that is fully implemented, such incidents will happen less often as I expect some hardcore Imgur users setup their own API key and that will reduce the load on our quota.
