### ISSUE TITLE
[Request (two part, but related)] Allow saving to predefined path without prompt upon hotkey press (ex. ctrl+s), as well as allowing the save action to call a user-defined script, passing the image location/name as argument.

### ISSUE THREAD

**Issue by MostHated** [flameshot-org/flameshot#1681]
**Is your feature request related to a problem?**
Yes, it is.

Hey there, 
    My main goal was to have more advanced Imgur support (upload directly to account as hidden), but when I think about it, it would probably end up being more useful to more people, in more ways, to have a user-defined field for a script that gets called when a screenshot is saved with ctrl + s and passes in the path and filename of the image as an argument to the script. This way people can implement any sort of post-operation with the new image using the tooling of their choice. This would require much less upfront investment, and minimal ongoing maintenance compared to keeping up with a third-party API.

Thanks,
-MH

**Comment by mmahmoudian** [comment]
I wonder why not using `flameshot gui -r > output.png` in a script in the first place?

**Comment by MostHated** [comment]
Oh, it looks like that would work out just fine. I didn't realize that hitting enter as opposed to ctrl+s when doing > filename.png would drop it right to disk like that. That should be perfect. Thanks!

**Comment by MostHated** [comment]
I had a quick question, or possibly could use a recommendation. I finally got around to making my script and it is working well minus one thing, even if I cancel by pressing esc when taking a screenshot, a file gets created due to sending flameshots output to > image.png. Here was what I had currently:

```sh
function main() {
    # -- Use flameshot to take the image ----
    img_file="$(date +"${FILE_NAME_FORMAT}")"
    img_path="${FILE_DIR}/${img_file}"
    flameshot gui -r >${img_path}
    if [ -f $img_path ]; then
        echo $(${IMGURSCRNSHT} -l true ${img_path}) &!
    fi
}
```

Unfortunately, even if a screenshot doesn't get taken, the output file is still created, so checking if the file exists before attempting to send it to imgur-screenshot for upload doesn't work, it just attempts to upload a bad file.

Is there any other recommended mechanism in which would help ensure that an image exists/is output from flameshot before putting something on disk, or can/does flameshot return a path to the newly created image if it is created, otherwise if canceled, don't return anything? If nothing jumps to mind, I will just try and come up with a way to determine if the item on disk is in fact a real image, otherwise delete it before it gets to the 'if' statement.

Thanks,
-MH

**Comment by mmahmoudian** [comment]
@MostHated Sorry for the late reply. This thread got lost among others.

Unfortunately `flameshot gui -r` does return the "screenshot aborted"  when pressing Esc in standard output. Because of this, there is always something written in the stdout and will be written in the file. To differentiate this file from a read image, you can simply count the number of lines in that output file using `wc -l`. So change your code to:

```sh
function main() {
    # -- Use flameshot to take the image ----
    img_file="$(date +"${FILE_NAME_FORMAT}")"
    img_path="${FILE_DIR}/${img_file}"
    flameshot gui -r >${img_path}
    if [ "$(cat "${img_path}" | wc -l)" -gt "1" ]; then          # <--- I changed this line
        echo $(${IMGURSCRNSHT} -l true ${img_path}) &!
    fi
}
```

**Comment by MostHated** [comment]
No worries, I had edited my post with a solution I came up with soon after I had made it that may not have shown up.

I had also since posted it here, in case anyone else is looking to do the same.
https://gist.github.com/instance-id/4cc914663d642b853318f581d85b37aa
