### ISSUE TITLE
Getting "Unable to Capture Screen" - Version '0.9.0'

### ISSUE THREAD

**Issue by benwinding** [flameshot-org/flameshot#1683]
Can't capture screen using flameshot anymore...

**Flameshot version**
Installed from Snap package
```
flameshot v0.9.0.rc2+git33.856e08a from Jeremy Borgman (borgman-jeremy) installed
```
**Describe the bug**
After running `flameshot` command in terminal, I get this output:
```
[error] cannot open locale definition file `en': No such file or directory
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Qt: Session management error: Could not open network socket
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=1000 pid=14014 comm=\"/snap/flameshot/77/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1124 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=1000 pid=14014 comm=\"/snap/flameshot/77/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1124 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
```
I click `Take screenshot` in gui options, then I get this message `Unable to Capture Screen`:
![Screenshot from 2021-06-27 19-28-37](https://user-images.githubusercontent.com/11782590/123540395-e81c8880-d77d-11eb-93dc-669d414b9868.png)

**To Reproduce**
Install snap package and run `flameshot` command in terminal

**Expected behavior**
Should work

**System Information**
- Intel® Core™ i7-2760QM CPU @ 2.40GHz × 8 
- Ubuntu 21.04
- 64-bit
- Gnome 3.38.5
- Wayland

**Comment by mmahmoudian** [comment]
It seems you have at least two problems, one of which I can probably help with. Please run the command `locale` and post here the output.

For instance, mine looks like:

> ```
> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=en_US.UTF-8
> LC_TIME=en_US.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=en_US.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=en_US.UTF-8
> LC_NAME=en_US.UTF-8
> LC_ADDRESS=en_US.UTF-8
> LC_TELEPHONE=en_US.UTF-8
> LC_MEASUREMENT=en_US.UTF-8
> LC_IDENTIFICATION=en_US.UTF-8
> LC_ALL=
> ```

**Comment by benwinding** [comment]
Thanks @mmahmoudian,

Here's the output for that command: 

```
in /home/ben/ 
› locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```

**Comment by NicolasGoeddel** [comment]
I've got the same issue here on a freshly installed Ubuntu 21.04. But the locales are okay.

**Comment by mmahmoudian** [comment]
@benwinding Would you please check if the newly released version V0.10.0 works?

**Comment by p-himik** [comment]
FWIW, v0.10.0 snap works for me while still producing a very similar log:
```
$ flameshot
Qt: Session management error: Could not open network socket
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.167\" (uid=1000 pid=96995 comm=\"/snap/flameshot/131/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1135 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.167\" (uid=1000 pid=96995 comm=\"/snap/flameshot/131/usr/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1135 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```
Everything below `"Object path cannot be empty"` seems to have appeared because I tried capturing - and it worked just fine.

**Comment by mmahmoudian** [comment]
@benwinding Would you please try it with the newest Snap version v0.10.1

**Comment by alculete** [comment]
@mmahmoudian  I can't take screenshots also, even on this new version, tried edge channel with no success either

**Comment by mmahmoudian** [comment]
@alculete are you also on Ubuntu 21.04? What is your DE?

**Comment by alculete** [comment]
yes I'm on ubuntu 
OS: Ubuntu 21.04 x86_64 
DE: GNOME 3.38.4

**Comment by alculete** [comment]
I'm able to to capture now...

**Comment by mmahmoudian** [comment]
@alculete do you know what has changed since then that you got it working?

**Comment by alculete** [comment]
I'm not sure, thee only core snap that updated on my system as snapd

**Comment by mmahmoudian** [comment]
@benwinding do you still have this issue with v0.10.1?

**Comment by benwinding** [comment]
@mmahmoudian
I'm just using `0.9.0` on mac at the moment, no issues, no need to upgrade
![image](https://user-images.githubusercontent.com/11782590/132266047-b06efe75-f5e5-476d-8db9-6a00067552bc.png)

**Comment by mmahmoudian** [comment]
@benwinding of course one perk of updating is to get the new features and bug fixes.😉

Anyways, should we close this issue then?
