### ISSUE TITLE
Does not work in crontab under Wayland

### ISSUE THREAD

**Issue by Microtribute** [flameshot-org/flameshot#1685]
**Flameshot version**
0.9.0

**Describe the bug**
`flameshot` did not work in crontab under Wayland. Wanted to use `flameshot` to take the screenshot periodically.

**To Reproduce**
Just add the following line under `crontab -e`:
```sh
* * * * *        flameshot full -p [Your Folder Path]
```

**Expected behavior**
Shoot the screen every minute.

**System Information**
Ubuntu 21.04 GNOME on Wayland

**Comment by borgmanJeremy** [comment]
Is the flameshot daemon running in the background before the cron job starts?
