### ISSUE TITLE
needs a better icon

### ISSUE THREAD

**Issue by gek169** [flameshot-org/flameshot#1686]
it's called flameshot. The icon looks like feathers. What is this, Apache? What is this minimalist garbage?

get some 🔥FIRE🔥  in there. Make it look like the inner circles of hell! When people see flameshot in the menu, there should be a fireball next to it. It can even have the minimalism too

but it definitely shouldn't be the stupid feathers you have now:
![image](https://user-images.githubusercontent.com/6974902/123575224-4a39b580-d79f-11eb-8454-6f050c3b36e1.png)

**Comment by Raytle** [comment]
Why not keep the icon and change the name of the application to "feathershot"? I'm being facetious of course. I agree with you: the logo is so inappropriate that it strikes me as being bizarre. For an average illustrator flame is very easy to draw. When people see the flameshot icon they should instantly recognize the flame in the icon.

**Comment by gek169** [comment]
what idiot thought feathers should be the icon for a program with "flame" in the name?

if it's supposed to be like a phoenix, they should look like phoenix feathers! Not like a peacock

**Comment by borgmanJeremy** [comment]
Keep it civil. If you have alternative icon ideas feel free to post them but please don't refer to the artists as stupid or degrade their work, they put in more effort than you have.

You can also locally change your icon pack .

**Comment by gek169** [comment]
![image](https://user-images.githubusercontent.com/6974902/123891654-3d47ce00-d927-11eb-9541-13b32af29007.png)

I dunno, I think this post took more effort to type than that "art" took to make

Took a lot more thought certainly
