### ISSUE TITLE
FR - add short-cut key to open in most recently used app (without asking which app)

### ISSUE THREAD

**Issue by jedd** [flameshot-org/flameshot#1687]
**Is your feature request related to a problem?**

No

Description:

The Ctrl-O option to open the current screen capture in an app is convenient when processing small numbers of screen captures, but is time-consuming when repeatedly having to identify the preferred app on every iteration.   Especially frustrating as my WM (KDE/Plasma) does not seem to remember the window sizing for the app selection widget, and I have about 15 apps that *can* open a png.

Modifying Ctrl-O would break current user workflow, and adding a configuration item to set the default preferred app is probably overkill.

Request:

Instead I ask for a new option - I suggest Ctrl+Shift+O - that will immediately open the current capture in another instance / window of the app I last used via Ctrl-O.

**Comment by mmahmoudian** [comment]
I don't think the information on "last used app" gets transferred to Flameshot. Therefore, I think the better approach would be to add an option so that user can define the default editor/application.

Apart from this feature request, you can of course always use the following and assign it to a keyboard shortcut:

```sh
flameshot gui --raw > /tmp/tmp_screenshot.png ; gimp /tmp/tmp_screenshot.png &
```

**Comment by jedd** [comment]
Hi -  yeah, I'd assumed that because flameshot is always running (on KDE/Debian at least) that it had some local state to store that in, and this would be simpler than a configuration item -- though a configurable option would be better / more intuitive, so that sounds more appealing.

Thanks also for the shortcut - I'll play around with that.  My use case earlier today was an edge case for me.  I wanted to take a screen shot, and then proceed with a change, while referring to that screenshot after the (live) screen content itself had changed.   
I then wanted to discard the cap a minute or so later, without having to save to disk.  KDE Spectacle, and even Microsoft Snipit, lend themselves to this, though they only have one instance running, and I really wanted multiple concurrent captures on-screen.  I was churning through this process a few dozen times, so it was a bit cumbersome.   I'll wrap some timestamps into that shortcut and see how I go.

**Comment by mmahmoudian** [comment]
You can use `flameshot gui -p` to define a different path to store screenshots. It will handle timestamp itself. You can then load everything to something like gimp when you are done with taking the screenshots.
