### ISSUE TITLE
flameshot gui -r works properly when I use my mouse to copy but not when I use the shortcut key I assigned to copy in flameshot

### ISSUE THREAD

**Issue by Raytle** [flameshot-org/flameshot#1688]
The Bash script at the bottom of this issue works properly when I use the mouse to click on the flameshot button labeled, "Copy the selection into the clipboard". However, when I press the shortcut key I have assigned to "Copy the selection into the clipboard" the Bash script at the bottom of this issue **fails** to work properly.

By "works properly" I mean in the first case (when I use my mouse), after I choose a region on my  screen with flameshot then my Google Drawing (indicated below) comes to the foreground and the screenshot I just took with flameshot is pasted into my Google Drawing; whereas, in the second case my Google Drawing (indicated below) **neither** comes to the foreground nor is  the screenshot I just took with flameshot pasted into my Google Drawing.

```
    #!/bin/sh

    # Pastes a screenshot and into an existing Google Drawing

    google-chrome-stable -new-window https://docs.google.com/drawings/d/1g3JREjF6LK4KNjwsq2HJ23bnuyGSuwNojgUkxyF4froM/edit 
    sleep 0.5 

    xdotool key alt+Tab 
    sleep 5.0

    flameshot gui -r >screenshot_that_my_script_creates.png && xdotool key alt+Tab && sleep 4.0 && xdotool key ctrl+v
```

**Comment by mmahmoudian** [comment]
What does this command outputs:

```sh
ls -al screenshot_that_my_script_creates.png
```

**Comment by Raytle** [comment]
That command outputs:

`~$ ls -al screenshot_that_my_script_creates.png
-rw-rw-r-- 1 y y 129403 Jun 29 04:03 screenshot_that_my_script_creates.png`

**Comment by mmahmoudian** [comment]
Then it clearly shows the issue is not related to the Flameshot, as Flameshot correctly took the screenshot in raw format and the bash successfully wrote it to a file.

On why your script terminates before finishing what is is supposed to do, you can debug it but putting a command as checkpoint:

```bash
# set the path to different files
THE_FILE="path/to/the/file.png"
THE_LOG="path/to/the/log/file.txt"

# delete previous captures if exist
rm -f "${THE_FILE}"

# run Flameshot
flameshot gui -r > "${THE_FILE}"

# [checkpoint] did Flameshot work?
if [ -f "${THE_FILE}" ]; then
    # append to log file
    echo "Flameshot worked" >> "${THE_LOG}"
else
    # append to log file
    echo "Flameshot didn't work" >> "${THE_LOG}"
fi￼
```

You can create a checkpoint for each step and see what fails.



P.s: using `&&` has it's place (in one-liner if conditions and in chains of commands that should get executed iff (if and only if) the previous command has ran successfully. I advise you not to use `&&` in any of you bash scripts and instead check the file existence with an `if` condition.

**Comment by Raytle** [comment]
Thanks for your advice about using an `if` condition instead of `&&`. Also thanks for sending me the debugger. I tested out the debugger but I don't want to discuss my results debugging results that at the moment. 

Instead I am confused.

> Then it clearly shows the issue is not related to the Flameshot, as Flameshot correctly took the screenshot in raw format and the bash successfully wrote it to a file.

Then why does my script work properly when I use the mouse to click on the flameshot button labeled, "Copy the selection into the clipboard"?

**Comment by mmahmoudian** [comment]
It depends on many factors, one scenario I can think of is that you are running your script manually and then using Ctrl+c to copy, and Ctrl+c in general terminates bash scripts and because you have used `&&` nothing will be executed.

You can be helped only when you can figure out which command in your shell script was the last working one. Without that info, it is like looking for a wooden needle in haystack in absolute darkness (wooden to eliminate using magnets or burning the whole haystack and sieving through the ashes)

**Comment by Raytle** [comment]
> It depends on many factors, one scenario I can think of is that you are running your script manually and then using Ctrl+c to copy, and Ctrl+c in general terminates bash scripts and because you have used && nothing will be executed.

Thanks! That essentially solved my problem.

My shortcut key I had been pressing to copy was "c" (not Ctrl+c).  I changed the shortcut key to Alt+Shift+m because I assumed it probably wasn't used by most bash scripts to do anything. Now my script works properly for me when I use my keyboard to copy just like it had been working properly when I used my mouse to copy.

> You can be helped only when you can figure out which command in your shell script was the last working one. Without that info, it is like looking for a wooden needle in haystack in absolute darkness (wooden to eliminate using magnets or burning the whole haystack and sieving through the ashes)

**In this case**, that whole line of reasoning was obviously false. That's why I was unwilling to engage you in a discussion about much of what you had messaged me.

Metaphorically, I prefer to shave with [Occam's razor](https://en.wikipedia.org/wiki/Occam's_razor). See, my script—as bad as it is (I know very little about shell scripting which I barely ever use)—was working properly when I clicked with my mouse therefore obviously the script was not defective. Obviously pressing the shortcut key was "doing something extra."

"When you are a hammer every problem looks like a nail." This problem wasn't a nail but you tried to solve it with a hammer. More to the point, I have wasted much of my time following bad advice proffered to me by well-intentioned engineers who have gleefully trotted out a strawman—as you have done—instead of applying simple logic to solving a problem. Put simply: most engineers I have worked with predictably jettison the scientific method in favor of illogical emotional arguments. It used to shock me that "men of science" would easily abandon the scientific method. But, well, in my experience, that's what ends up happening... almost invariably.

I'm not an engineer. I do not aspire to become an engineer. But I try to solve engineering problems using the scientific method: despite my emotions. I'll be blunt: in my experience engineers who allow their emotions to cloud their judgement typically "paint themselves into a corner" by making remarkably illogical assertions.

Nonetheless, I really do appreciate your help. Thank you for helping me solve my problem!

**Comment by mmahmoudian** [comment]
@Raytle I cannot talk about others, but just put things in the correct perspective about me:

- BSc Microbiologist
- MSc Bioinformatics
- PhD Bioinformatics (still on going)

Therefore by education I'm more of a biologist, and I learnt to code out of hobby and later necessity.


Glad your issue got resolved.

**Comment by Raytle** [comment]
Thanks for letting me know. I appreciate that.
