### ISSUE TITLE
Option to change color for marking tools.

### ISSUE THREAD

**Issue by gauraputu** [flameshot-org/flameshot#1690]
**Is your feature request related to a problem?**

I need to mark my screenshot, so I can tell which part of my screenshot people need to focus on. the problem is I need to mark a lot of different parts that are close to one another because the marking tools only use red color it quickly becomes a mess. instead of making it clear, the screenshot is now confusing. An options to change marking color would be helpful.

**Comment by mmahmoudian** [comment]
There are two things you can do. When a tool is selected (e.g arrow):

1. Right click to open the color wheel with some preset colors
2. Press space to open the sidebar and the color-picker to make the color you want with more details


I assume the point above will address your question, and therefore, I'll close this issue. Feel free to open it if it didn't fully addressed your question.

**Comment by johnjacobkenny** [comment]
I am on windows and I am trying to use the sidebar to change the color. The color wheel works and I am able to select different colors. The list of undo steps also works.

The dropper though is behaving randomly and not at all picking colors from the screen. When I do something on the sidebar, it seems to alternate between white and black or something random. When I do something on the main screen, it uses the current tool as normal.

Am I missing something?
