### ISSUE TITLE
suggestion: recommend "KStatusNotifierItem/AppIndicator Support" extension for Gnome 40

### ISSUE THREAD

**Issue by seekr** [flameshot-org/flameshot#1692]
The documentation recommends https://github.com/Ubuntu/gnome-shell-extension-appindicator on Gnome but I found that the extension is not available for Gnome 40 (and it seems deprecated now). 

I tried the built-in extension (I'm on Fedora 34) called "KStatusNotifierItem/AppIndicator Support" and it works for flameshot.

**Comment by borgmanJeremy** [comment]
Thanks for letting me know... feel free to submit a pull request to fix the docs

**Comment by borgmanJeremy** [comment]
How does #1717  look?
