### ISSUE TITLE
please add resizing option on painting option of screenshot

### ISSUE THREAD

**Issue by habibulislam6862** [flameshot-org/flameshot#1693]
I can't resize the border of the shape, can't resize the text size, or painting brash size. Please add this feature.

**Comment by mmahmoudian** [comment]
There are three ways that you can change the size/thickness in Flameshot. First select a tool and then:
1. Mouse scroll (scroll up even while annotating to change the size/thickness)
2. Press <kbd>spacebar</kbd> and from the sidebar change the size
3. In version 0.10.0 you can add two button to your tools from configurations to increase and decrease size/thickness. If you have version 0.10.0, right-click on the tray icon of Flameshot, click on configurations and scroll to bottom and put checkmarks beside the <kbd>+</kbd> and <kbd>-</kbd>
