### ISSUE TITLE
Getting rid of the dependency to systray

### ISSUE THREAD

**Issue by cooperbang** [flameshot-org/flameshot#1696]
With newer Gnome versions flameshot can only be used through CLI and keyboard because Gnome doesn´t support systray by default.

Flameshot should be able to run with current Gnome versions without installing additional extensions.

At least (as a simple workaround) flameshot should start visually when clicking the launcher icon (like entering `flameshot gui` in a terminal) instead of doing nothing caused by missing systray. 

Please look here:
https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines

> **Primary windows**
Every application should always have a primary window and this window should always be raised when the application is launched. This is important, as it ensures consistent and predictable behavior. The GNOME Human Interface Guidelines provide more information on this.

**Comment by mmahmoudian** [comment]
> At least (as a simple workaround) flameshot should start visually when clicking the launcher icon (like entering flameshot gui in a terminal) instead of doing nothing caused by missing systray.

Actually I think it does. If you click on Flameshot from Gnome Launcher and then in terminal try `pgrep -i flameshot` you will most likely see that the Flameshot is running there.

Although I marked this issue as "Enhancement" and I agree with the removal of systray dependency, I highly doubt we ever follow the GNOME Human Interface Guidelines as it really doesn't make sense to raise a window as it will just clutter user's view and hurt their experience. So I can suggest you to try the following a get a super quick and one-time fix:

1. open the file `org.flameshot.Flameshot.desktop` on my computer it is stored in `/usr/share/applications/org.flameshot.Flameshot.desktop`
2. Go to the line that contains `Exec=/usr/bin/flameshot`
3. change it to `Exec=/usr/bin/flameshot gui -d 200`

This basically tells your computer to by default load Flameshot with the `gui` flag and with 200 millisecond delay (some grace time for the launcher to get closed).

The following one-liner does what I explained automatically:
```sh
sed -i 's#Exec=/usr/bin/flameshot#Exec=/usr/bin/flameshot gui -d 200#' "/usr/share/applications/org.flameshot.Flameshot.desktop"
```

**Comment by cooperbang** [comment]
Thanks for your info concerning the .deskop file. This really works as a workaround.

Nevertheless I think flameshot should raise a window when starting and then should automatically hide when taking a screenshot.

**Comment by kpcee** [comment]
> Nevertheless I think flameshot should raise a window when starting and then should automatically hide when taking a screenshot.

Such a behavior would certainly disturb or annoy many users who do not use Gnome. Gnome is broken by design and violates the freedesktop.org specifications. If you want this kind of behavior, you should specifically use programs written for Gnome.

**Comment by cooperbang** [comment]
https://blogs.gnome.org/tbernard/2021/06/11/community-power-1/
https://blogs.gnome.org/tbernard/2021/06/15/community-power-2/
https://blogs.gnome.org/tbernard/2021/06/23/community-power-3/
https://blogs.gnome.org/tbernard/2021/07/13/community-power-4/

`The “traditional desktop” is dead, and it’s not coming back. Instead of trying to bring back old concepts like menu bars or status icons, invent something better from first principles.`

**Comment by mmahmoudian** [comment]
@cooperbang Thanks for the links, and I understand your frustration, but Gnome to my understanding is the only outlier in this matter and of course I didn't expect them to bash their move on their own website (clearly they are bias 😉)
Even MacOS and Windows have systray. All major companies (e.g Google, Dropbox, Cisco, Amazon) also use systray for their software. So clearly Gnome, as they have typically done in the past 10 years, simply made a big miscalculation. I myself was a big fan of Gnome2 but anything after that was imho utter disaster.

Regardless, we in Flameshot are trying to get rid of this systray dependency to also satisfy those Gnome purists who don't want to install the Gnome plugin. 🤗
