### ISSUE TITLE
[Suggestion] Add Unix Timestamp Filename

### ISSUE THREAD

**Issue by s0h3ck** [flameshot-org/flameshot#1699]
There should be a mechanism to allow the user to configure the filename through the command line interface.

For now, the quick solution is to add the Unix timestamp in the filename pattern, but in the future, I think a more handy functionality is to be able to customize it via the command.

Here is an example that is possible with the main utility:

maim --select -u > /tmp/$(date +%s).png

Here is what I would like to see with the flameshot utility:

flameshot gui -p /tmp/$(date +%s).png

This is only an example. :)

**Comment by mmahmoudian** [comment]
Try this:

```sh
flameshot gui -r > /tmp/$(date +%s).png
```

Does this satisfy your needs?

**Comment by s0h3ck** [comment]
Three issues with the option (-r):

(1) The buffer in the terminal is corrupted. I know because the cursor changes. If I refresh the system, it goes back to normal. That seems to be a bug.

(2) The (-r) will corrupts flameshot meaning that I will not be able to execute `flameshot gui -r [...]` anymore and somehow a reboot is required. I can kill flameshot, but when I try to run `flameshot gui -r `again, it starts a stalled process. 

(3) The command will creates the Unix timestamp as you suggested, but there will be a duplicated file with the filename matching the filename pattern in the flameshot configuration. In other words, you get one file with Unix timestamp and another file with whatever filename pattern you specified.

If I am very unlucky, I get one Unix timestamp saved in the /tmp folder.

**Comment by mmahmoudian** [comment]
The points 1 & 2 are definitely not reproducible on my systems with Flameshot versions 0.9.0 and 0.10.0, as I am heavily using `-r` in this dmenu:

https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md

**Comment by mmahmoudian** [comment]
Ok, to me it is clear that this issue should be closed as the requested feature is already implemented. If `-r` has some issues for you, please open a bug report. Thanks.
