### ISSUE TITLE
[Bug] Issues with flameshot gui -r

### ISSUE THREAD

**Issue by s0h3ck** [flameshot-org/flameshot#1701]
Based on the discussion [1699](https://github.com/flameshot-org/flameshot/issues/1699), three issues were identified:

Issue (1) - Coredump if flameshot is not running in the background.

Video: [Issue_01.mp4](https://drive.google.com/file/d/1_TeMToeLBcHjs5AFSpvXYwZrhZGtHBJb/view?usp=sharing)

Issue (2) - The `flameshot gui -r > /tmp/test.png` will create the test.png, but there will be a duplicated file with the filename matching the filename pattern in the flameshot configuration. In other words, you get one file with test.png and another file with whatever filename pattern you specified.

Video: [Issue_02.mp4](https://drive.google.com/file/d/1_ZuGPwXAg6IpMic3esIvI0JgzYXp6CC_/view?usp=sharing)

Issue (3) - The cursor in the terminal is acting like it has been "corrupted". It takes 6 seconds to come back in the video, but sometimes a refresh screen is required.

Video: [Issue_03.mp4](https://drive.google.com/file/d/1apLwixiWcPdcc8EoZ1ctJjmuKT7IFhB-/view?usp=sharing)

**Comment by mmahmoudian** [comment]
@s0h3ck Few issues here:

1. The mp4 videos needs permission. Please consider uploading them to Github: https://github.blog/2021-05-13-video-uploads-available-github/
2. one of the reasons I asked for filing a bug report is to get your system information (OS, flameshot version, window-manager, shell you use, ...). These are essential as I cannot reproduce any of your 3 reported issues on Manjaro KDE and Flameshot version >0.9.0)
3. what keys do you press or which buttons you press while `flameshot gui -r > ...` is running to trigger the screenshot? There is already a feature request (#1531) to remove the confusion, but until that is implemented, we should still ask that from user as there are so many ways to do this:
    - press <kbd>Ctrl</kbd>+<kbd>s</kbd> or click on save button
    - press <kbd>Ctrl</kbd>+<kbd>c</kbd> or click on copy

My guess is that if you trigger the screenshot with copy, your 2nd issue should not happen. Please report back as per my understanding as long as the `-r` is used, all other functionalities (i.e copy, save, upload) should be disabled.

**Comment by s0h3ck** [comment]
**Update issue 1**

System: Arch Linux
Version: 5.12.15-arch1-1
Flameshot: flameshot 0.9.0-1
Window Manager: i3
Terminal: urxvt

Core dump: [core_dump.txt](https://github.com/flameshot-org/flameshot/files/6808805/core_dump.txt)

https://user-images.githubusercontent.com/7539558/125451449-6318b5c0-d235-43fd-bf02-73dc809cd5cf.mp4

**Comment by s0h3ck** [comment]
**Update issue 2**

See information above. If you need more information, let me know.

https://user-images.githubusercontent.com/7539558/125452078-ed9557d2-db0a-487d-abdc-902dd57fb162.mp4

**Comment by s0h3ck** [comment]
**Update issue 3**

I pressed Ctrl+s or click on save button.

https://user-images.githubusercontent.com/7539558/125454527-83ddd382-9461-4a86-8028-d2c6ed97c8e4.mp4

**Comment by mmahmoudian** [comment]
> Update issue 1

To me it seems that you don't have the Flameshot process running in the background. try running `flameshot` in one terminal and then the `flameshot gui -r > /tmp/test.png`
There are also some logs in your journal about a QT issue. If the suggestion above does not help, then perhaps @borgmanJeremy can assist you further considering the following:
![image](https://user-images.githubusercontent.com/390889/125627233-17f2202e-d4f3-4b88-a757-a08c17132279.png)

**Comment by mmahmoudian** [comment]
> Update issue 2

You are right. This is a confusion that my proposal in #1531 is trying to resolve. I myself am struggling with this in daily basis, but because I use <kbd>Ctrl</kbd>+<kbd>c</kbd> to finalize the capture action, I don't get affected by tons of extra files on my system. I undersnad your concern about over-writing your clipboard, but I'm afraid until #1531 is addressed, there is no easy way to avoid this other than using a clipboard manager (e.g [CopyQ](https://hluk.github.io/CopyQ/))

**Comment by mmahmoudian** [comment]
> **Update issue 3**

if by "corrupt" you mean "hollow", then I believe this is related to #784 as your terminal does not understand that it is back in focus. The surprising part is that according to the window decoration (border color, heading) the i3 knows that the terminal is in focus but it takes few seconds for urxvt to figure that out. Would it be possible for you to test it with another terminal application (e.g [Alacritty](https://github.com/alacritty/alacritty), [Kitty](https://sw.kovidgoyal.net/kitty/))

P.s: it has been [pointed out before that urxvt focus and tmux are not playing well together](https://bbs.archlinux.org/viewtopic.php?pid=1444863#p1444863). I also realized that you are using some sort of terminal multiplexer:
![image](https://user-images.githubusercontent.com/390889/125630854-034e8777-0b68-413a-903b-02ba25274bde.png)
Turn that off and see if you still can reproduce this hollow cursor effect.

**Comment by s0h3ck** [comment]
> [Update issue 1] To me it seems that you don't have the Flameshot process running in the background. 

That is correct. A bit later in one of the video, I illustrated that when you have the flameshot service in the background it works. 

Would it be possible to run `flameshot gui -r > /tmp/$(date +s).png` only when needed? 

Maybe something like that:

`( flameshot & ) && ( sleep 0.1s && flameshot gui -r > /tmp/$(date +%s).png) && (killall flameshot)`

> [Update issue 2]

It sounds like we would have to wait for the #1531 changes. 

Would it be easy to reuse the behavior of ctrl+c, remove the clipboard part and shift those changes on `-r` option?

> [Update issue 3]

Yes, I tested in Alacritty, same "hollow" acting.

> I also realized that you are using some sort of terminal multiplexer:

Hahaha. Nothing fancy there. It can be activated or disabled by using the tabbed option in the urxvt configuration file. Here is an example: `URxvt.perl-ext-common:      default,matcher,tabbed`.

**Comment by mmahmoudian** [comment]
> > [Update issue 2]
It sounds like we would have to wait for the #1531 changes.
> 
> Would it be easy to reuse the behavior of ctrl+c, remove the clipboard part and shift those changes on `-r` option?

I agree. If I was confident enough with my C++ skills I would have implemented the #1531 and create PR. I'm sure it will be implemented at some point.

> > [Update issue 3]
> Yes, I tested in Alacritty, same "hollow" acting.

Interesting! This has never happened to me when using Alacritty in DWM, AwesomeWM, or KDE.

**Comment by borgmanJeremy** [comment]
Is this okay to close? seems like the core issue was the flameshot daemon was not running?

**Comment by mmahmoudian** [comment]
@borgmanJeremy i believe this can be closed, but I personally think #1531 should be prioritised as it brings some logical bugs and confusion with the current state.
