### ISSUE TITLE
Glitched GUI?

### ISSUE THREAD

**Issue by SpeedyCraftah** [flameshot-org/flameshot#1702]
I'm not using a template since this is more of a question than a formal bug report since it seems the issue appears to happen on my side.

After updating my OS, the screenshot and configuration GUIs of Flameshot have been glitched. I'm not sure if this is a problem with how the OS renders the QT windows but after trying some things including changing themes, I'm stumped.

![image](https://user-images.githubusercontent.com/45142584/125523243-b8234e8f-4a02-4503-a9ad-f9ebb0ccf87b.png)
![image](https://user-images.githubusercontent.com/45142584/125523421-abbcf310-ace9-40e0-8cef-03b3cd52ad21.png)

**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
After an OS update, the graphical displays seem to be distorted and out of place.

**To Reproduce**
I'm not sure it just suddenly happened after an OS update.

**Expected behavior**
The display should render correctly.

**System Information**
Manjaro Gnome 40.2.0, X11

**Comment by borgmanJeremy** [comment]
This is for sure a bug, I have no idea whats causing it...if you post the other info in the template we might be able to help.

**Comment by SpeedyCraftah** [comment]
> This is for sure a bug, I have no idea whats causing it...if you post the other info in the template we might be able to help.

I have updated my issue.

**Comment by SpeedyCraftah** [comment]
Turns out I had multiple DE's messing up my Qt design haha (not laughing since it took long enough to figure out).
