### ISSUE TITLE
Section titled "Examples of using Flameshot with other applications"

### ISSUE THREAD

**Issue by Raytle** [flameshot-org/flameshot#1703]
Have the project maintainers considered adding a section entitled which might be named, "Examples of using Flameshot with other applications"? I imagine this section might include sections such as, but not limited to, the following...

1. How to automatically scale an image.
2. How to automatically attach an image to a Thunderbird email.
3. How to automatically upload an image to Nextcloud.
4. And so on.

Regardless of whether these features are within the scope of Flameshot, they are almost certainly within the scope of Flameshot's **documentation**. Why? Because many users of Flameshot certainly do things with Flameshot images after they use Flameshot. Of course adding "Examples of using Flameshot with other applications" to the Flameshot documentation would not require the Flameshot devs to add any new features to Flameshot.

In addition, instead of merely making off the cuff assertions such as...

> I believe this can be very very easily done by using `convert` command from ImageMagic. Basically piping `flameshot gui -r` into `convert`.

"Examples of using Flameshot with other applications" would actually explain, step-by-step, how to actually use  Flameshot with other applications.

Asserting, "Oh, yeah. I think you can do X with Y", is easy. The internet is full of this sort of information.  It's not necessarily useless information. It can actually be helpful. But it's usually much more valuable to end users to see  step-by-step instructions explaining how to actually implement a solution.

**Comment by mmahmoudian** [comment]
**Regarding your 1st point:**

> How to automatically scale an image.

As [I suggested in your previous feature request](https://github.com/flameshot-org/flameshot/issues/1700#issuecomment-879711798), scaling is very easy using ImageMagic and it is not that complicated task to make tutorial for. For people who don't want to be bothered with the command line and yet want these functionalities, I have put together a project named [dmenu_shot](https://codeberg.org/mehrad/dmenu_shot) to help users with use-cases slightly out of the scope of Flameshot. I even quickly [added the scale functionality](https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md) to it (asks what scale percentage or dimension you want).

<img src="https://codeberg.org/mehrad/dmenu_shot/raw/branch/main/assets/scaled.jpg" width="250" height="250">

-------

**Regarding your 2nd point:**

> How to automatically attach an image to a Thunderbird email.

That is something that you should search. I personally don't even thing this is a useful thing when we can easily have the screenshot get copied to the clipboard and then user can simply paste it in the email.

-------

**Regarding your 3rd point:**

> How to automatically upload an image to Nextcloud.

There is already a RFC in place to let users have plugins for uploading to their preferred platform/software/website/cloud: #955

-------

**Regarding your documentation point:**

The beauty of OpenSource software is that users can also contribute to the project. Our website is also fully opensource and any contribution is more than welcome. If you are willing to contribute you can:
1. Prepare your account's SSH key ([Github instructions](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh))
    1.1. Go to https://github.com/settings/keys
    1.2. Check if you have a SSH key ([Github instructions](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/checking-for-existing-ssh-keys)) if you don't have one, generate one ([Github instructions](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent))
    1.3. Add your SSH public key to your Github account ([Github instructions](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account))
2. Create a copy of the repository for yourself so you can change it
    2.1. Navigate to https://github.com/flameshot-org/flameshot-org.github.io
    2.2. From the top right corner click on "Fork" button. This will create a copy in your own Github account
    2.3. Clone the repo on your computer `git clone git@github.com:Raytle/flameshot-org.github.io.git`
3. Change/improve the documentation
4. Create pull request
    4.1. Add the changes to git `git add .`
    4.2. Commit everything to git `git commit -m "SOME DESCRIPTIVE MESSAGE HERE"`
    4.3. Push the changes to your Github account `git push` (you will be asked for your SSH key password)
    4.4. Go to https://github.com/Raytle/flameshot-org.github.io/pulls
    4.5. Click on the green "New pull request" button on the right side of the page
    4.6. Fill the necessary information and submit the form

**Comment by Raytle** [comment]
> **Regarding your 1st point:**
> 
> > How to automatically scale an image.
> 
> As [I suggested in your previous feature request](https://github.com/flameshot-org/flameshot/issues/1700#issuecomment-879711798), scaling is very easy using ImageMagic and it is not that complicated task to make tutorial for. For people who don't want to be bothered with the command line and yet want these functionalities, I have put together a project named [dmenu_shot](https://codeberg.org/mehrad/dmenu_shot) to help users with use-cases slightly out of the scope of Flameshot. I even quickly [added the scale functionality](https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md) to it (asks what scale percentage or dimension you want).
> 
> <img alt="" width="250" height="250" src="https://camo.githubusercontent.com/e44b792869d2225c53a17ee90fa8678a60b0444278638f1e49152c0c936c09f2/68747470733a2f2f636f6465626572672e6f72672f6d65687261642f646d656e755f73686f742f7261772f6272616e63682f6d61696e2f6173736574732f7363616c65642e6a7067">

Thanks. You showed me that before. I suppose some tech guys would probably appreciate this feature but I doubt many non-tech people will use it.

I just created a Python script so that typing:

-  `...7` will trigger `flameshot gui -r | convert png:- -resize 70% png:my_file.png`
-  `...6` will trigger `flameshot gui -r | convert png:- -resize 60% png:my_file.png`
-  `...5` will trigger `flameshot gui -r | convert png:- -resize 50% png:my_file.png`

I suppose many non-tech people would use that.


> **Regarding your 2nd point:**
> 
> > How to automatically attach an image to a Thunderbird email.
> 
> That is something that you should search. I personally don't even thing this is a useful thing when we can easily have the screenshot get copied to the clipboard and then user can simply paste it in the email.

I see.


> **Regarding your 3rd point:**
> 
> > How to automatically upload an image to Nextcloud.
> 
> There is already a RFC in place to let users have plugins for uploading to their preferred platform/software/website/cloud: #955

Thanks for letting me know. I appreciate that. I see that it was opened about ten months ago (Sep 21, 2020).

**Comment by mmahmoudian** [comment]
> I suppose some tech guys would probably appreciate this feature but I doubt many non-tech people will use it.

The whole interface is graphical and user does not need to run or even have python:
1. in the first menu you choose your main function
![image](https://user-images.githubusercontent.com/390889/125618100-77e3105d-a1b1-48d7-8aee-d2ba341e00ea.png)

2. If user selects "Scaled" they will be asked to input the percentage:
![2021-07-14_14-58](https://user-images.githubusercontent.com/390889/125618306-ff35abf1-6bad-47f1-9cad-2ef2b0c8c651.png)


Don't judge a book by its cover ;)

**Comment by Raytle** [comment]
I predict that unless it is well-integrated into Flameshot at least 99.99% of Flameshot users will never use your side project. On the other hand, if Flameshot had a button labeled, for example, "Resize your screenshot" which opened up your side project, then I predict a significant number of Flameshot users would use it.

You seem to be myopically focused on technology yet ignoring marketing. Technology matters. Sure it does. But marketing matters too... if you actually want large numbers of people to use your side project. If your side project is merely for you and a few of your friends, then—of course—marketing would be essentially irrelevant.

It is well-known that many brilliant scientists throughout history have lived in poverty. For example, a great yet impoverished inventor who creates a great invention needs to figure out some way to earn money from his invention otherwise he will tend to remain a great yet impoverished inventor. Sure. I know. Flameshot is FOSS (free and open source) project. But because you focus too much on building stuff you enjoy building but not enough time on building stuff which people (such as customers and/or clients) are actually willing to pay for I think you will never earn as much money and you probably should. 

Put another way, unless a scientist successfully serves commerce (that is, unless scientist creates a good and/or a service which is sold profitably and in sufficient volume), then scientists will normally primarily earn money from their vocation because a wealthy patron or institution pays them a salary, which, of course, is very often a low salary.

**Comment by mmahmoudian** [comment]
I'll be glad to discuss this further over on some other platform as it is getting slightly off-topic ([Slack](https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg), [Martix](https://matrix.to/#/!AYbNXDGTDwApLwzkNg:feneas.org?via=feneas.org), [XMPP](xmpp:mehrad@snopyta.org) ).

But as a brief clarification, the side project is not supposed to take off and be super-widely adopted. it is something I started to encompass some of the slightly off-topic feature requests so that the main devs of Flameshot stop worrying about those feature and users also feel that their needs are somehow addressed. I myself use the Trim and Remove White frequently and the rest very rarely.

P.s: I highly appreciate the lengthy comments and I read them fully even if I don't reply.

**Comment by Raytle** [comment]
> I'll be glad to discuss this further over on some other platform as it is getting slightly off-topic ([Slack](https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg), [Martix](https://matrix.to/#/!AYbNXDGTDwApLwzkNg:feneas.org?via=feneas.org), XMPP ).

I would prefer to communicate via email. On 21 June 2021 I sent an email to two of your email addresses: one ends **.ai**, the other ends **.me**. I have not received a reply from either account.

I hate Slack. I have never heard of Matrix. I didn't realize XMPP was still widely used. I haven't heard anyone mention XMPP in a couple of decades. XMPP reminds me of instant messaging (ICQ, AIM, etc). I hate instant messaging.


> But as a brief clarification, the side project is not supposed to take off and be super-widely adopted.

As it stands now, I imagine that it will likely be very, very narrowly adopted... by perhaps one hundred people or fewer.


> it is something I started to encompass some of the slightly off-topic feature requests so that the main devs of Flameshot stop worrying about those feature and users also feel that their needs are somehow addressed. 

This is some truly bizarre reasoning. Users wanted some features in an application that is extremely popular and has a reasonably nice user interface so instead of putting those features in the application, I built an obscure application with an ugly user interface so that hardly anyone will use it. Do you grasp how inane that is?


> I myself use the Trim and Remove White frequently and the rest very rarely.

I see.


> P.s: I highly appreciate the lengthy comments and I read them fully even if I don't reply.

My pleasure. I appreciate your comments too... although I find some of them bewildering. "Don't add Trim, Remove White, or Scale to Flameshot because, um, well, errr... because, because, because, ummm, wellll, errrr...  users might use those features!!!" Ah. Yes. Right. I see. Up is down; down is up; water is dry; 2+2=5. Sure. Yes. Of course.

**Comment by mmahmoudian** [comment]
@Raytle 
> On 21 June 2021 I sent an email to two of your email addresses: one ends .ai, the other ends .me. I have not received a reply from either account.

Yes, I vividly remember those emails. One of them was caught by spam filter and the other one, considering its content, I have deleted it. Suffice to say I'm not a fan of targeted marketing.

> Users wanted some features in an application that is extremely popular and has a reasonably nice user interface so instead of putting those features in the application, I built an obscure application with an ugly user interface so that hardly anyone will use it. Do you grasp how inane that is?

I suppose I do. Flameshot was initially created and for a long time maintained by @lupoDharkael because he wanted to learn C++ and created a nice tool and published it in public domain. Later in August 2020 some talented developers who had some will and slightly more free time compared to @lupoDharkael got the maintainer and main dev role and worked on improving the software. None of us are getting paid even a single cent from this project, and we cover all the costs from our own pockets. We don't [yet] accept any form of financial donation but we do encourage our users to contribute to the project (either the code or graphical design, or documentation) as this will benefit everyone. Now, if any of our users think the UI/UX is not up to the standard or can be improved, they can easily make their voice heard and can easily contribute. I myself don't code in C++ and all I do for this particular project is as follows:
- triage of issues (feature requests & bug reports) and PRs
- help users find solution to their problems (even if it is not directly related to Flameshot)
- documentation
- maintaining the website
- maintaining social platforms (Slack, Matrix)

All these mean that you can potentially help this project in your free time if you also believe in importance of this software. Otherwise, we will soon

**Comment by Raytle** [comment]
I appreciate your lengthy explanation. I really do. Nonetheless, we are "talking past one another." Specifically, you have utterly ignored some my questions. The word in English, which is not your mother tongue, to describe that one who does that is **ignorant.** Therefore, in this thread you have behaved in an ignorant manner. Yeah. "Ignorant" is an ugly word to describe despicable behavior.

But hey. This is a hobby for you. Therefore, you are free to act like an ignorant "open-source oligarch." You guys are all cut from the same cloth; you are frustrated nerds who crave power.

**Comment by borgmanJeremy** [comment]
Wow that type of behavior is not tolerated here. Locking this and if you continue acting rude you will be banned.
