### ISSUE TITLE
Allow to disable update checker for the packaged builds

### ISSUE THREAD

**Issue by xvitaly** [flameshot-org/flameshot#1706]
**Is your feature request related to a problem?**

Please allow to disable update checker for the packaged builds with a special compile-time flag. Eg. `-DDISABLE_UPDATE_CHECKER:BOOL=ON`.

**Comment by borgmanJeremy** [comment]
I want to keep it as a run time option so users can check if the version their distribution provides is out of date.

**Comment by xvitaly** [comment]
> I want to keep it as a run time option so users can check if the version their distribution provides is out of date.

This is not a good idea. All distributions follows their own Updates guidelines. They will patch and drop this code.

**Comment by xvitaly** [comment]
@borgmanJeremy Btw, [this code](https://github.com/flameshot-org/flameshot/blob/55e61b874320c864c3abbd47c61d33babfc5fe3d/src/core/controller.cpp#L176-L193) should be replaced by build-in Qt [QVersionNumber](https://doc.qt.io/qt-5/qversionnumber.html).

```c++
QVersionNumber foo =  QVersionNumber::fromString("1.0.0.1");
QVersionNumber bar =  QVersionNumber::fromString("1.0.1.0");

if (foo > bar) { ... }
```

**Comment by borgmanJeremy** [comment]
They are welcome to patch it out if they feel that strongly about it. A majority of issues opened here are from users running old versions and I want to empower 
my users to see if they have an outdated version.

**Comment by borgmanJeremy** [comment]
> @borgmanJeremy Btw, [this code](https://github.com/flameshot-org/flameshot/blob/55e61b874320c864c3abbd47c61d33babfc5fe3d/src/core/controller.cpp#L176-L193) should be replaced by build-in Qt [QVersionNumber](https://doc.qt.io/qt-5/qversionnumber.html).
> 
> 
> 
> ```c++
> 
> QVersionNumber foo =  QVersionNumber::fromString("1.0.0.1");
> 
> QVersionNumber bar =  QVersionNumber::fromString("1.0.1.0");
> 
> 
> 
> if (foo > bar) { ... }
> 
> ```

Ok thanks I'll dig into that.

**Comment by xvitaly** [comment]
> A majority of issues opened here are from users running old versions and I want to empower

I understand your pain, but you cannot change distributions guidelines. Debian/Ubuntu for example cannot perform major updates on stable releases.

**Comment by borgmanJeremy** [comment]
Yeah I know debian can't release the new version, but the update notification will prompt the users to manually download the new version outside the package manager.

They can do so via our .deb file, appimage, flatpak, or snap.

**Comment by mmahmoudian** [comment]
I think it is a good idea to:
1. Add what OP suggested, despite my massive dislike of how non-rolling release distros work.
2. Add an option in the config (GUI and of course the .ini) for the user to opt-out

There are tons of concerns about leaking IP when softwares are checking for updates esp. with [legit] the ever growing dislike of BigTech (e.g Microsoft). I don't want us to become something like bpytop or Audacity.

In my book, a screenshot software should not need to access internet until and unless the user specially ask for it (i.e click on Upload button or Check Updates button)

**Comment by borgmanJeremy** [comment]
Ok if the consensus is it should be a build flag I'll support that in the v11 release.

**Comment by xvitaly** [comment]
> Ok thanks I'll dig into that.

Sent a PR #1776 with fix.

**Comment by Alaskra** [comment]
> I think it is a good idea to:
> 
>     1. Add what OP suggested, despite my massive dislike of how non-rolling release distros work.
> 
>     2. Add an option in the config (GUI and of course the .ini) for the user to opt-out
> 
> 
> There are tons of concerns about leaking IP when softwares are checking for updates esp. with [legit] the ever growing dislike of BigTech (e.g Microsoft). I don't want us to become something like bpytop or Audacity.
> 
> In my book, a screenshot software should not need to access internet until and unless the user specially ask for it (i.e click on Upload button or Check Updates button)

I agree. The update notification in software is annoying to me. There are some software I don't use very often so update is waste of time.

I would like that there is an option to disable update in config panel so user can set it manually. And the build flag `-DDISABLE_UPDATE_CHECKER:BOOL=ON` can set it as default. Can it assigned to me?

**Comment by borgmanJeremy** [comment]
No, the default should be enabled and users can disabled if desired. Distro maintainers can adjust accordingly.

**Comment by Alaskra** [comment]
> the default should be enabled and users can disabled if desired. Distro maintainers can adjust accordingly.

That's what I mean.
