### ISSUE TITLE
Modern, Single-page Landing Page for Flameshot

### ISSUE THREAD

**Issue by Correct-Syntax** [flameshot-org/flameshot#1710]
Hi, I'd like to help out with Flameshot.

I was wondering if you all would accept a modern landing page design and (possibly) also the completed html page for Flameshot if I did it. This page would link to the manual/docs which are currently at https://flameshot.org/ and give end-users a bit of information on the features Flameshot provides, as well as provide download links so that they don't need to sort through Github releases.

The mockup image below shows the initial style that I am (currently) thinking (please note: **this mockup is definitely *not* completed in any way...**), but I wanted to get some feedback and see if you all wanted a landing page in the first place before I continued much further.

**Please note that the image in the second section would be the GIF currently on the readme**

![HD Copy 3@2x](https://user-images.githubusercontent.com/60711001/125848652-6a81bea8-eb38-429e-9ec9-b09e932aebd6.png)

**Comment by borgmanJeremy** [comment]
This looks great to me and I'd love to hear what @mmahmoudian has to say.

Would this still be a static site so non web devs can update it?

**Comment by Correct-Syntax** [comment]
> This looks great to me and I'd love to hear what @mmahmoudian has to say.

Thanks.

> Would this still be a static site so non web devs can update it?

Yes, I was thinking just a static html page since it's just 1 page.

**Comment by mmahmoudian** [comment]
@Correct-Syntax Thanks for the suggestion and the time you have already put into it. I agree with @borgmanJeremy, it indeed is great and I love the style and the color palette (kinda extrapolating in my mind a bit based on the mockup 😅). I think we can definitely use a modern lightweight landing page to add to our current static website.

I would like to also tag few more to also know their input: @ZetaoYang, @hosiet, @lupoDharkael, @Martin-Eckleben, @pavel-the-best, @lebaux (I'm sure I have missed many, but I only remembered these usernames from top of my head)

The only issue I can think of is the integration with the current MkDocs static website. I myself am more experienced with Zola and a bit Hugo and I would say the MkDocs is pretty much enough for our use-case, and it would be great if we can figure out a way to set custom landing page.

**Comment by Correct-Syntax** [comment]
> The only issue I can think of is the integration with the current MkDocs static website.

That was my main concern as well. I don't think we need a fancy static site generator like hugo, etc though.

An idea would be to:

1. use github pages (like you currently do) to host the html landing page 
2. transfer the current documentation to sphinx (it is also markdown-based so it would be very little change to the docs themselves). 
3. You could then place the sphinx generated html files in the same place as the landing page to host them from Github pages there (or host the docs at https://readthedocs.org/ for free). 

Of course, that might not be the best option, but I suggest it because I am more-so familiar with sphinx and I think it could definitely work. I hadn't even heard of MkDocs until recently.

**Comment by mmahmoudian** [comment]
Tbh I'm personally not a big fan of sphinx, nothing against it, just that it looks like Google Blogger or Yahoo Geocities when they initially rolled out 😅.

I think if we can manage to retrofit the landing page to the existing MkDocs system we have, it would be a great win-win situation as the Github actions and SEO and everything is already working (perfectly computer-readable) and with the new landing page we improve the aesthetics for human eyes.

I'm sure there must be a way. 10 seconds Googling resulted in:

https://stackoverflow.com/questions/63438788/how-to-add-a-landing-page-to-a-mkdocs-doc-site-using-mkdocs-material

**Comment by Correct-Syntax** [comment]
> Tbh I'm personally not a big fan of sphinx, nothing against it, just that it looks like Google Blogger or Yahoo Geocities when they initially rolled out

I would agree with that -about some themes. But, for instance https://docs.wagtail.io/en/stable/ is sphinx. (BTW, this isn't to convince you to use it, just to show that it isn't sphinx's fault that some docs look ancient and terrible.) 😅 

> I think if we can manage to retrofit the landing page to the existing MkDocs system we have, it would be a great win-win situation

I agree. Let's aim for that, if possible. 😄

**Comment by ZetaoYang** [comment]
@Correct-Syntax  Your mockup is great, just a few opinions,
1. the "Download" button, after the user clicks on it, which interface does it redirect to and what does it show? Or does it redirect directly to the GitHub Release Page?
2. above the "Docs" I suggest changing to "Guide". The Guide above should be user level docs.

> You could then place the sphinx generated html files in the same place as the landing page to host them (I think) from Github pages there (or host the docs at https://readthedocs.org/ for free).

Also, I think host the development docs at https://readthedocs.org is good.

**Comment by Correct-Syntax** [comment]
Alright, here's my latest progress...and I have a few questions for you all (below the image):
![HD Copy 3@2x](https://user-images.githubusercontent.com/60711001/125880585-81486915-4aa8-43e8-b0db-686765207a35.png)

**Questions:**

1. I am not sure what exactly to write for each point in the Features section, so I have placeholder text there right now. Could someone advise as what to write for the text? I am still a noob at using Flameshot so I am probably not the best person to be writing about it. 😄 
2. I've been following the features listed in the current documentation at https://flameshot.org/#features. However, I left out DBus interface because it seems that doesn't really interest the end user. Being a developer, I can understand why DBus interface is a good thing, but should that be listed as a feature for the end-user to see?
3. For the downloads section (currently WIP in the image above) I was thinking about using tabs for different OS' (e.g: Linux, Windows, MacOs, etc) and inside each tab individual download buttons for different package variations (e.g: flameshot-0.9.0-1.ubuntu-18.04.amd64.deb, flameshot-0.9.0-1.ubuntu-20.04.amd64.deb). I am wondering if this is a good idea to arrange them this way or if someone had a better idea I didn't think of yet.

> the "Download" button, after the user clicks on it, which interface does it redirect to and what does it show? Or does it redirect directly to the GitHub Release Page?

My current thought is that all the links and the main cta "Download button", except for the "Docs"/"Guide" link would just be links that would scroll to the relevant section on the landing page (e.g: Download would just scroll to the Download Flameshot section). 

> above the "Docs" I suggest changing to "Guide". The Guide above should be user level docs.

That's a good suggestion. Probably easier for people to understand than "Docs". 👍

**Comment by Correct-Syntax** [comment]
Near-completed design mockup below. If anyone has suggestions please let me know, otherwise I'll start implementing the static html page based on the mockup.
![HD Copy 3](https://user-images.githubusercontent.com/60711001/126260884-3717d43c-4c10-4adc-ab20-421c8f89049f.png)

cc @mmahmoudian

**Comment by ZetaoYang** [comment]
@Correct-Syntax Why 64 bit only for Windows? There're some ARM Windows devices can run 32bit app, so this's very helpful for them.

**Comment by Correct-Syntax** [comment]
> Why 64 bit only for Windows? There're some ARM Windows devices can run 32bit app, so this's very helpful for them.

Okay, thank you for your feedback @ZetaoYang. I thought Flameshot only provided 64-bit packages since the portable zip shows 64-bit and the installer is 64-bit. Are there also 32-bit packages provided as well?

Though, either way this doesn't affect the design and that text can easily be changed later if needed.

**Comment by mmahmoudian** [comment]
@Correct-Syntax This looks great. Thanks for all the efforts so far! I have few suggestions:

1. There are plans to add other services to upload to, therefore, it would be nice to say "Direct upload to:" and then list Imgur and leave some room for other platforms when added.
2. Would be nice to mention that it is OpenSource and licensed under GPLv3, perhaps by adding their logo:
    - https://en.wikipedia.org/wiki/GNU_General_Public_License
    - https://en.wikipedia.org/wiki/Open_Source_Initiative

**Comment by borgmanJeremy** [comment]
We only provide signed images for x64 on windows. This is a somewhat manual process and I don't want to take the extra time to sign the x32 images.

**Comment by Correct-Syntax** [comment]
Thank you, @mmahmoudian  and @borgmanJeremy for the feedback.

> We only provide signed images for x64 on windows

Just to clarify, does that mean that we provide binaries for 32-bit or not?

> There are plans to add other services to upload to, therefore, it would be nice to say "Direct upload to:" and then list Imgur and leave some room for other platforms when added.

Okay, I will keep that in mind.

> Would be nice to mention that it is OpenSource and licensed under GPLv3, perhaps by adding their logo somewhere in the header: 

Alright, are you referring to the "copyleft" logo or the GPL logo specifically?

**Comment by mmahmoudian** [comment]
> Alright, are you referring to the "copyleft" logo or the GPL logo specifically?

Well, landing pages usually act as a marketing business card as well, but people usually don't pay attention to detailed text, but they usually go through the icons and pictures. The green OpenSource logo is different from the black and white copyleft

![opensource logo](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Open_Source_Initiative_keyhole.svg/240px-Open_Source_Initiative_keyhole.svg.png)

![copyleft logo](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Copyleft.svg/240px-Copyleft.svg.png)

I'm definitely not a designer and I'm definitely not skilled enough for this, but I was thinking if it is possible to include the OpenSource green logo and GPL3 red logo somewhere in the top area of the website (of course in small size not to disturb your beautiful design).

**Comment by Correct-Syntax** [comment]
Ok, I think it's much more clear that Flameshot is open-source now. I also fixed the text to leave it open for more upload platforms.

![HD Copy 3](https://user-images.githubusercontent.com/60711001/126572476-af847474-4f0b-46d2-bf99-f0d7ccbccd2d.png)

**Comment by mmahmoudian** [comment]
@Correct-Syntax it is beautifully done. Having good taste and understanding of color palettes do matter in software design🍻

Btw, I just realized that you didn't put your [nick]name as the designer at the bottom of the page. Considering that it will become one commit in the website's GitHub repo, please take the credit for the awesome contribution of yours.

**Comment by Correct-Syntax** [comment]
> it is beautifully done

HalleluYah and thank you. 😄 

> I just realized that you didn't put your [nick]name as the designer at the bottom of the page. Considering that it will become one commit in the website's GitHub repo, please take the credit for the awesome contribution of yours.

Okay, I will do that with my name and a link to my Github profile, if that is okay with you.

Also, when I implement the html page, what is the best way to commit it? I have forked the Flameshot website repository, but maybe you can give me guidance on where the page needs to be there. I am guessing the root directory.

**Comment by mmahmoudian** [comment]
> when I implement the html page, what is the best way to commit it? I have forked the Flameshot website repository, but maybe you can give me guidance on where the page needs to be there.

To be honest with you, I haven't done this with mkdocs, so I have to do some tests to figure it out, of course by using a temporary html page. I'll work on it on weekend👍🏼

This might take multiple try-and-error to get it working. So I would like to suggest taking the short talks and chats to Flameshot's Slack ([by using this link](Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg)). Alternatively you can find my My Matrix and XMPP accounts on:
mehrad.gitlab.io

**Comment by Correct-Syntax** [comment]
@mmahmoudian I created a DM via element.

**Comment by borgmanJeremy** [comment]
Is this effort still underway?

**Comment by Correct-Syntax** [comment]
@borgmanJeremy yes, it is. We have just been chatting via Element and haven't updated the current progress here. 😄 

We ended up deciding to try using Zola static site generator. 
The latest news is that after some trial and error, the landing page is now working. My forked repository: https://github.com/Correct-Syntax/flameshot-org.github.io and the deployment: https://correct-syntax.github.io/flameshot-org.github We have yet to get the docs part working though.

**Comment by mmahmoudian** [comment]
@borgmanJeremy yes, the issue is that neither me nor @Correct-Syntax manages to integrate this to the current mkdocs. So we decided to try to bring up the website using Zola. @Correct-Syntax started a repo with that and so far it looks great:

https://github.com/Correct-Syntax/flameshot-org.github.io

We should just work on it and add the md files to the new system and get it to work
