### ISSUE TITLE
New release for Windows

### ISSUE THREAD

**Issue by Keller18306** [flameshot-org/flameshot#1715]
Where i can download new verison for windows?
![image](https://user-images.githubusercontent.com/23178771/126202255-887a0fce-51f6-40f1-97a9-aed50c4e6237.png)

**Comment by borgmanJeremy** [comment]
I think I mentioned in the release notes but I'm having issues getting into the code signing service. Once I resolve that I will upload it.

**Comment by Keller18306** [comment]
And I read it. Closed.
![image](https://user-images.githubusercontent.com/23178771/126202429-7bec5dac-0d2c-46da-9410-6a531b5e2d11.png)
