### ISSUE TITLE
0.10.0 Update notice still shown in 0.10.0

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [flameshot-org/flameshot#1718]
**Flameshot version**
0.10.0

**Describe the bug**
After updating to 0.10.0, the update notice message still shown when using flameshot.

**To Reproduce**
Just use flameshot 0.10.0 normally

**Expected behavior**
Message would not be shown after updating to 0.10.0

**System Information**
Arch Linux, flameshot package version 0.10.0-1

**Comment by borgmanJeremy** [comment]
I cannot replicate this in Arch

**Comment by mmahmoudian** [comment]
I cannot reproduce this on Manjaro either

**Comment by chuahou** [comment]
I cannot replicate this on 0.10.0 on NixOS. I was, however, able to replicate it with the following steps:

1. Run flameshot 0.9.0, causing the daemon to start running.
2. Update to flameshot 0.10.0.
3. Run flameshot 0.10.0 with the flameshot 0.9.0 daemon still running. The update notice is still shown.

Given @JohnTheCoolingFan's phrasing of "After updating to 0.10.0", I suspect this might be similar to what originally happened.

**Comment by mmahmoudian** [comment]
@JohnTheCoolingFan I believe @chuahou has a valid point. You might have upgraded Flameshot to v0.10.0 but forgot about the running 0.9.0 process. To test this, kill all instances of Flameshot by `pkill Flameshot` and then run `flameshot` again.

**Comment by JohnTheCoolingFan** [comment]
@mmahmoudian Yes, that's probably what happened. I didn't restart flameshot or reboot my pc inbetween updating and submitting this issue. After many reboots, I noticed that the message is not shown anymore.
