### ISSUE TITLE
Flathub v0.10.0 not available

### ISSUE THREAD

**Issue by ryannathans** [flameshot-org/flameshot#1719]
I see the snap is available and binaries are out but there's no flatpak for v0.10.0, the latest still shows v0.9.0.

https://flathub.org/apps/details/org.flameshot.Flameshot
![image](https://user-images.githubusercontent.com/1307375/126258985-351988fd-0063-4ad4-9cd5-b75c61ac86f6.png)

Had a quick search but didn't see any info about why a flatpak release might be delayed

**Comment by borgmanJeremy** [comment]
The work was in progress. It's a lot more work than one might think to support all these different package formats :) 

Its now updated.
