### ISSUE TITLE
Windows build for v0.10 missing

### ISSUE THREAD

**Issue by gs-rickchristy** [flameshot-org/flameshot#1720]
Simple as the topic says: Windows build for v0.10 is missing.

Thank you I love this program!

**Comment by gaduaxe** [comment]
I'm too, waiting for Windows's version

**Comment by franciscohanna92** [comment]
Can't wait to have those new features on Windows!

**Comment by borgmanJeremy** [comment]
As mentioned in the release notes the work is in progress. I had some issues with my code signing account but its being resolved.

**Comment by borgmanJeremy** [comment]
Added a signed windows version to the 0.10.1 release (fixed some issues with the 0.10 release).
