### ISSUE TITLE
Save screenshot file name broken

### ISSUE THREAD

**Issue by kophjager007** [flameshot-org/flameshot#1722]
**Flameshot version**

Flameshot 0.10.0.rc1-1 (flameshot-0.10.0.rc1-1.ubuntu-20.04.amd64.deb)

**Describe the bug**

When saving a screenshot with `.`'s in the file name, such as naming a screenshot after an IP address (eg `12.13.14.15-p80-vuln.png`), the screenshot will be saved as `12.png`. Everything after the first `.` in the file name will be dropped. Additionally, Flameshot will not prompt for overwrite in this condition.

**To Reproduce**

Attempt to save a screenshot with `.`'s in it, such as `12.34.56.78.png` and the results will be `12.png`.

**Expected behavior**

As in prior versions, the screenshot should be saved with the intended name. For example, `12.34.56.78.png`.

**System Information**

Ubuntu 20.04LTS Gnome 3.36.7

**Comment by unashamedgeek** [comment]
I'm seeing the same behavior.

**Comment by mmahmoudian** [comment]
I could reproduce this on Manjaro KDE + Flameshot v0.10.0. everything between the first `.` and the extension will be wiped out.

**Comment by borgmanJeremy** [comment]
We changed the file parsing to allow more extensions and we likely introduced the defect at that time.
