### ISSUE TITLE
Broken AppImage Build

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#1723]
AppImage fails to build in the pipeline: 

https://github.com/flameshot-org/flameshot/runs/3098284247?check_suite_focus=true

@ZetaoYang Any ideas? Not sure why its looking for android libraries.

**Comment by ZetaoYang** [comment]
> AppImage fails to build in the pipeline:
> 
> https://github.com/flameshot-org/flameshot/runs/3098284247?check_suite_focus=true
> 
> @ZetaoYang Any ideas? Not sure why its looking for android libraries.

It is probably due to the libxcb of the android emulator in the ubuntu 20.04 environment of github actions. Changing to build in a docker container solves the problem.

**Comment by mmahmoudian** [comment]
@ZetaoYang Just as an idea: Ubuntu is getting bloated day by day and they are adding more and more stuff to the mix, should we migrate all Actions to Alpine or something similar?

**Comment by ZetaoYang** [comment]
> Alpine

Alpine using musl instead of glib

**Comment by borgmanJeremy** [comment]
And it's not an Ubuntu problem really. The issue is we use the image made by GitHub which adds many things that are not installed by default.
