### ISSUE TITLE
UI problem: Save Path is very squashed (on two different Linux PCs)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [flameshot-org/flameshot#1726]
**Flameshot version**
0.9.0
Compiled with QT 5.11.3

**Describe the bug**

On one of my computers [EDIT: a **ThinkPad X230**, resolution 1366x768, with no Hi-DPI scaling], I see this:

![image](https://user-images.githubusercontent.com/47056543/126389126-5be790df-317d-441b-b73a-a1ec7c0ec34a.png)

On another of my computers [EDIT: a **ThinkPad X1CG6**, resolution 2560x1440 , with 2x Hi-DPI scaling for GTK and with `QT_AUTO_SCREEN_SCALE_FACTOR=1`], I see this:

![image](https://user-images.githubusercontent.com/47056543/126401242-cc2d96c4-1264-4340-b4bc-c6bec2d9b333.png)

**To Reproduce**
Open the relevant configuration pane.

**Expected behavior**
Obviously, the 'Save Path' part of the configuration file should be readable.

**System Information**
Both computers are ThinkPads running Linux Mint Cinnamon on a 5.8 kernel. EDIT: for further information, please see above.

**Comment by borgmanJeremy** [comment]
Can you post your resolution? I'll fire up a mint VM, guessing it's cinnamon related.

**Comment by borgmanJeremy** [comment]
Btw which thinkpads? I have a x230 I could test on

**Comment by LinuxOnTheDesktop** [comment]
Thank you.

I have updated my first post with the necessary information.

**Comment by mmahmoudian** [comment]
@borgmanJeremy the squashed effect looks a lot like the #1697, hence they might be related or get solved together.

**Comment by borgmanJeremy** [comment]
Yup, I  can confirm this issue on setups with small vertical resolutions. The solution will be to embed all the settings in a vertical scroll bar. 

I never noticed it on my x230 because it runs i3 which maximizes the vertical space enough. I replicated it in a VM and by installing plasma on my x230.

**Comment by HarisGusic** [comment]
I submitted a [pull request](https://github.com/flameshot-org/flameshot/pull/1782) that is supposed to fix the issue. See my [comment](https://github.com/flameshot-org/flameshot/issues/1697#issuecomment-888755915) in #1697.

**Comment by HarisGusic** [comment]
@borgmanJeremy  I think this issue can be closed as well.
