### ISSUE TITLE
Add a copy button to the About window

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1732]
I suggest adding a button in the bottom of the About window to copy the version info into the clipboard. This can assist users to easily copy the information for bug reports.

![image](https://user-images.githubusercontent.com/390889/126475081-cc7a91e1-408f-4154-ad6f-efdb30f583c6.png)

**Comment by borgmanJeremy** [comment]
Check out #1756

**Comment by borgmanJeremy** [comment]
Im going to close this since the first version is merged in. If you have more suggestions for metrics to collect let me know and I'll add it.
