### ISSUE TITLE
Fullscreen screeshots upload automatically to imgur

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1733]
When I take a full screen screenshot, the file is automatically uploaded to imgur.

Ideally this would open on screen with the flameshot toolbar to add annotation, but not sure if thats possible.
Or if not possible, an option to choose to save automatically to imgur or locally.

**Comment by borgmanJeremy** [comment]
This happened when we introduced hotkeys. Essentially our default key bindings put upload on the "Enter" key. If you open the config tool and change the hot keys that should fix it.

**Comment by erlisdhima** [comment]
I changed the shortcut to `shift+return`, but now when I press enter nothing happens.
It seems like it was designed to upload full screen images directly to imgur instead of locally.

![image](https://user-images.githubusercontent.com/7734108/126487099-cfb9702f-f6ab-4d2c-b31f-92f19ec4565f.png)

**Comment by Scramblejams** [comment]
Can you imagine the reaction when someone hits enter and discovers their screenshot, which they'd intended to keep private, has been uploaded for the world to see?

Recommend changing the default.

**Comment by borgmanJeremy** [comment]
Yeah I agree we should change it

**Comment by borgmanJeremy** [comment]
Ok this is fixed via #1747 

I will be releasing a hot fix (10.1) to fix a segfault and include this in the release.
