### ISSUE TITLE
Regression: flameshot gui --raw doesn't make selection on enter

### ISSUE THREAD

**Issue by kaihendry** [flameshot-org/flameshot#1739]
https://github.com/flameshot-org/flameshot/issues/1468#issuecomment-884712757

TYPE_COPY=Return doesn't work?

Downgrading on Archlinux doesn't appear to work either. Perhaps it's some QT change?

**Comment by mmahmoudian** [comment]
I assume you were intending to create a bug report? If so, please provide the details asked in the bug report template.

I believe you are using v0.10.0-1 (presumably from AUR), and your Flameshot config file can be found in [a link you posted](https://s.natalian.org/2021-07-22/flameshot.ini) which I copied here:


<details>
<summary>Your <code>flameshot.ini</code> content</summary>

```ini
[General]
disabledTrayIcon=false
drawColor=#ff0017
drawThickness=1
ignoreUpdateToVersion=0.10.0
savePath=/tmp
savePathFixed=false
showStartupLaunchMessage=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Return
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

</details>

-------

Apart from this, I would like to also point out that there is a Feature Request (#1531) to limit the actions in `--raw` mode (basically removing copy, save, upload, pin, ... as they don't make sense in this mode and just adds to users' confusion)

**Comment by mmahmoudian** [comment]
Also after looking your config file, it seems you have the following conflict:

![image](https://user-images.githubusercontent.com/390889/126614175-49eb3fd4-7295-4aa0-b928-87dc4ee68164.png)

**Comment by kaihendry** [comment]
Thank you, removing the uploaded line fixed my issue!!

**Comment by R8s6** [comment]
This happened again in version v12.1.0 (on Archlinux).

First i ran:
`$ flameshot gui --raw`

after selection, i hit `enter`, and it appeared to have done nothing (the capture tool didn't quit, and nothing appeared to be copied).

My goal is to feed the screenshot to `tesseract` for text recognition, and the commands i tried to use was:
`flameshot gui --raw | tesseract stdin stdout | xclip -in -selection clipboard`

Because of this, the pipe couldn't move to the 2nd part. 

Here's in the `flameshot.ini`:

```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x11\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\f)
checkForUpdates=false
contrastOpacity=191
contrastUiColor=#ee8b10
copyAndCloseAfterUpload=true
disabledTrayIcon=false
drawColor=#0000ff
drawThickness=2
savePath=/home/abc
savePathFixed=false
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#000000
uploadClientSecret=xyz
uploadWithoutConfirmation=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Return
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

Thanks!
