### ISSUE TITLE
Unable to remove an image off of imgur (no deleteHash) and upload does not show up on "Latest Uploads"

### ISSUE THREAD

**Issue by JKleinne** [flameshot-org/flameshot#1752]
**Flameshot version**
0.10.0-1

**Describe the bug**
This is an extension of https://github.com/flameshot-org/flameshot/issues/1751. An unwanted upload of a screenshot to imgur cannot be deleted since it does not show up on _Latest Uploads_ and the `deleteHash` cannot be retrieved.

**To Reproduce**
1. 
![2021-07-24_11-57](https://user-images.githubusercontent.com/17832326/126874790-01529d99-c19b-4034-be40-e1ad7cbafc8e.png)

2. "Select an area with the mouse [...] Press Enter to capture screen". Pressing _Enter_ uploads the screenshot without confirmation from the user, but the resulting upload does not show up on the _Latest Uploads_ section

**Expected behavior**
The resulting upload should show up in the _Latest Uploads_ section and the `deleteHash` should be made visible

**System Information**
OS: Manjaro 21.1.0 Pahvo
Kernel: x86_64 Linux 5.13.4-1
_Installed via Manjaro community repository (pacman/pamac)_

**Comment by borgmanJeremy** [comment]
hmmm, can you post your config file? I am on arch and unable to reproduce this issue.

**Comment by JKleinne** [comment]
Just tried it again, and it still uploads without showing up on _Latest Uploads_ :/
![2021-07-24_14-21](https://user-images.githubusercontent.com/17832326/126877844-6a54ba33-c4d2-41d9-87e9-af9c8efb7759.png)

**flameshot.conf**
```
[General]
contrastOpacity=188
disabledTrayIcon=false
drawColor=#0000ff
drawThickness=1
savePath=/home/jkleinne/Downloads
savePathFixed=false
setSaveAsFileExtension=
showStartupLaunchMessage=true
startupLaunch=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Comment by borgmanJeremy** [comment]
Are you on KDE? I'll test in a Manjaro VM

**Comment by JKleinne** [comment]
Yes on KDE
```
DE: KDE 5.84.0 / Plasma 5.22.3
WM: KWin
```

**Comment by JKleinne** [comment]
Hopefully this helps, pressing "Enter" when clicking on the flameshot icon uploads it into imgur, but _Latest Uploads_ remain empty so there is no way to delete it off of imgur with the `deleteHash`.

https://user-images.githubusercontent.com/17832326/126878918-01a827ce-aa76-4c21-b027-5489c279459a.mp4

**Comment by borgmanJeremy** [comment]
Thanks this is really helpful, I 
misunderstood the issue and now I see the concern!

**Comment by JKleinne** [comment]
Glad I could help!

**Comment by borgmanJeremy** [comment]
As a quick fix I will remove hotkeys for uploads. See #1753 

I am doing a hotfix release this weekend anyway and really dont want to put a user in a bad spot with sensitive data.
