### ISSUE TITLE
Flameshot wont Open across 2 monitors (Wayland Kde)

### ISSUE THREAD

**Issue by davigamer987** [flameshot-org/flameshot#1755]
**Flameshot version**

0.10.0 
**Describe the bug**

Gui only opens on only secondary monitor
**To Reproduce**

Use Garuda Linux on Wayland, Run flameshot 
**Expected behavior**

Gui spans across the 2 monitors
**System Information**

Garuda Linux Dragonized Kde (Gaming Edition) On wayland

**Comment by graves501** [comment]
@davigamer987 Please provide the log output as well by running `flameshot` in a terminal.

**Comment by davigamer987** [comment]
K i have some updates: I unistalled flameshot from the community repo and i installed flameshot-git additionally i also moved My menu to my primary screen which made flameshot open in the primary monitor, It still Wont span across the 2 monitors tho

**Comment by davigamer987** [comment]
Output from running Flameshot in a terminal
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject*
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active

**Comment by davigamer987** [comment]
https://github.com/flameshot-org/flameshot/issues/668 Im Having This Exact Issue

**Comment by davigamer987** [comment]
I Also Found That It Duplicates the image on my main screen to my 2nd screen on the screenshot, Very weird

**Comment by lucasjome** [comment]
Exact same issue here.
KDE wayland on arch.

**Comment by Elufimov** [comment]
Same issue kubuntu 21.04 kde 5.22

**Comment by mmahmoudian** [comment]
@Elufimov @lucasjome Would you please confirm your Flameshot version

**Comment by Elufimov** [comment]
```
$ flameshot -v 
Flameshot v0.8.5-4(Debian)
Compiled with Qt 5.15.2

```

**Comment by mmahmoudian** [comment]
@Elufimov We have done many changes and optimizations since that version. Would it be possible for you to use [Snap](https://flameshot.org/guide/installation/installation-linux/#snap), [Flatpak](https://flameshot.org/guide/installation/installation-linux/#flatpak), [AppImage](https://flameshot.org/guide/installation/installation-linux/#appimage) or even use [the .deb](https://github.com/flameshot-org/flameshot/releases) file for your specific Ubuntu version?

**Comment by Elufimov** [comment]
@mmahmoudian latest version has the same behavior.
```
$ flameshot -v
Flameshot v0.10.1
Compiled with Qt 5.12.8
```

**Comment by davigamer987** [comment]
When i used env QT_QPA_PLATFORM=xcb /usr/bin/flameshot It worked for the first time, but then after i closed flameshot and opened it again the screenshot gui wont show at all

**Comment by davigamer987** [comment]
I can get the gui to open again if i don't use any flags (Still only opens in one monitor)

**Comment by davigamer987** [comment]
I got it working again with env QT_QPA_PLATFORM=xcb /usr/bin/flameshot If i put that in the .desktop file it wont work tho, for some reason only works when i use the terminal

**Comment by homemmakako** [comment]
Also having the same problem: Flameshot works but only opens the GUI on one monitor. (In my case, only the secondary monitor)

<details>
  <summary><b>System and Version Info</b></summary>

>**Wayland**: 1.19.0-1
**Wayland Protocols**: 1.21-1
**OS**: Manjaro (KDE)
**Kernel**: Linux 5.13.8-1
**Flameshot**: 0.10.1 (Compiled with Qt 5.15.2)

  
</details>
<details>
  <summary><b>Logs</b></summary>

```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```
  
</details>

**Comment by imran-iq** [comment]
QT_QPA_PLATFORM=xcb /usr/bin/flameshot**QT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshot**QT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshotQT_QPA_PLATFORM=xcb /usr/bin/flameshot

**Comment by juusujanar** [comment]
> > When i used env QT_QPA_PLATFORM=xcb /usr/bin/flameshot It worked for the first time, but then after i closed flameshot and opened it again the screenshot gui wont show at all
> 
> With `QT_QPA_PLATFORM=xcb /usr/bin/flameshot` from terminal it will launch across all monitors fine, but shortcuts (e.g. ctrl+s, esc) don't work to exit the gui. System hangs happen on issuing any flameshot command.

Can confirm the shortcuts do not work. Did not have any system hangs though.

Fedora 35 with KDE on Wayland, Flameshot v0.10.1 (compiled with Qt 5.15.2) from official Fedora repository. Using a desktop computer with two screens attached at all times.
