### ISSUE TITLE
A few suggestions about the current 0.10.1 release

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#1757]
**Is your feature request related to a problem?**
![image](https://user-images.githubusercontent.com/10769951/126922562-120e52df-1d53-4ce5-a2eb-7652c5585191.png)

1. Windows .msi release misses sha256sum
2. Suggested renaming `flameshot-0.10.1-win64.zip.sha256` to `flameshot-0.10.1-win64.zip.sha256sum`

**Comment by borgmanJeremy** [comment]
Thanks, I made the suggested changed.

**Comment by ZetaoYang** [comment]
> Thanks, I made the suggested changed.

![](https://user-images.githubusercontent.com/10769951/127003081-85a0b782-c2ac-4085-bcb7-de8bc27ae848.png)

**Comment by borgmanJeremy** [comment]
Wow, this is a bug with github. It keeps re-adding that suffix if I edit through the browser. 

I deleted and re-added it and now it looks correct.
