### ISSUE TITLE
'Undo limit' isn't translated

### ISSUE THREAD

**Issue by adem4ik** [flameshot-org/flameshot#1761]
**Flameshot version**
v0.10.1

**Describe the bug**
'Undo limit' isn't translated, and it is not available for translation in Weblate

**To Reproduce**
Swicth to Russian, Open Options/ General tab

**Expected behavior**
'Undo limit' is avalable for translatation in Weblate project at least

**System Information**
Windows 10 x64
![2021-07-26_15-32](https://user-images.githubusercontent.com/4707112/126982169-1745afc9-60c9-4d66-9dc8-32cfa4259db0.png)

**Comment by mmahmoudian** [comment]
It seems everything in Russian is translated:

https://hosted.weblate.org/projects/flameshot/flameshot/ru/

Perhaps this part is not transferred to our glossary on weblet

**Comment by borgmanJeremy** [comment]
The weblate project was locked due to merge conflicts but it is fixed now.

**Comment by adem4ik** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/4707112/127503277-eb5beb16-6789-4a02-93cb-699df5674cb8.png)
