### ISSUE TITLE
Flameshot closes suddenly :(

### ISSUE THREAD

**Issue by Dansito** [flameshot-org/flameshot#1764]
**Flameshot version**

flameshot 0.10.0-1

**Describe the bug**

When opening flameshot gui it closes suddenly, a temporary solution is to delete config and all files, but when restarting the pc the same thing happens again ... the version in archlinux says to be the last one, but I still get the notification to update, which is weird ... I suppose it will be time to wait a few days, but a shame I love it and I use flameshot daily, I hope you can help me or let me know when it is solved, thank you. 

**To Reproduce**

**Expected behavior**

**System Information**

Endeavouros(Arch) 
Kernel : 5.13.5

**Comment by mmahmoudian** [comment]
you stated that it closes "suddenly", but does it close immediately when you open it or it will stay open and after some time it closes?

Regarding the update, we rolled out a hot fix (v0.10.1) which if you on Arch-based distro you can easily get via the `flameshot-git` AUR (maintained by maintainers of this Github repo)

**Comment by borgmanJeremy** [comment]
This is fixed by 10.1
