### ISSUE TITLE
flameshot path hard coded in .desktop file

### ISSUE THREAD

**Issue by c0dev0id** [flameshot-org/flameshot#1766]
Hello,

The change in https://github.com/flameshot-org/flameshot/commit/57dac0d73de3b3de7838a639467a4fe3bbdfe087 breaks the desktop file on some systems/distributions that install flameshot to a custom location like `/usr/local`. Packagers can fix this, but it would be nice if upstream could honor `PREFIX` here and install it with the correct path.

**System Information**
OpenBSD-current

**Comment by borgmanJeremy** [comment]
This format was required to fix kde wayland. I don't think we can package it in a way to satisfy all systems.

**Comment by hosiet** [comment]
The problem may still be solvable even if we have to use absolute path (which is the reason behind 57dac0d73de3b3de7838a639467a4fe3bbdfe087 ). Maybe simply create a `org.flameshot.Flameshot.desktop.in` template and use CMake to fill in the file with `PREFIX` environment variable. I believe CMake `configure_file()` is meant for that. Also it is much more elegant than manual `sed`.

**Comment by c0dev0id** [comment]
Maybe `/usr/bin/env flameshot` would work? This would be portable.

**Comment by hosiet** [comment]
I doubt "/use/bin/env flameshot" would work. That means that "/usr/bin/env" will be granted  screenshot privilege, not "/usr/bin/flameshot".

**Comment by xvitaly** [comment]
> Maybe simply create a org.flameshot.Flameshot.desktop.in template and use CMake to fill in the file with PREFIX environment variable.

`CMAKE_INSTALL_FULL_BINDIR` already includes prefix. Sent PR #1775 with fix.

**Comment by xvitaly** [comment]
GNU/Linux maintainers can forward `-DUSE_LAUNCHER_ABSOLUTE_PATH:BOOL=OFF` to avoid hard-coding of absolute paths.
