### ISSUE TITLE
Enter uploads screenshot to imgurl by default without asking for confirmation

### ISSUE THREAD

**Issue by cabo40** [flameshot-org/flameshot#1768]
**Flameshot version**
0.10.0 (-)

**Describe the bug**
Enter key uploads screenshot to imgurl by default without asking for confirmation.

**To Reproduce**
Press enter after taking a screenshot

**Expected behavior**
A less intrusive default (since sensitive data can be accidentally uploaded) or a confirmation pop up.

**System Information**
Archlinux

**Comment by noobishply** [comment]
Can confirm this happens to me too. Pressing enter when clicking the flameshot icon in the system tray automatically uploads the whole screen to imgur

**Comment by mmahmoudian** [comment]
2 days ago we released a new version (v0.10.1). Please consider upgrading to that version. Also, you can always change the shortcut key to something else! Right click on the tray icon > configuration > shortcuts

**Comment by cabo40** [comment]
Ah, thank you very much! And thanks for this great project.
