### ISSUE TITLE
0.10.x crashes related to QNetworkReply

### ISSUE THREAD

**Issue by xvitaly** [flameshot-org/flameshot#1770]
**Flameshot version**
0.10.0

**Describe the bug**
Crash on start.

Full backtrace: [backtrace.txt](https://github.com/flameshot-org/flameshot/files/6884193/backtrace.txt)
Fedora downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1986186
Fedora ABRT crash analyzer issue: https://retrace.fedoraproject.org/faf/reports/210921/

**To Reproduce**
```
$ flameshot gui
```

**Expected behavior**
It should not crash.

**System Information**
Fedora 34 Workstation

**Comment by richardtatum** [comment]
I am having the same issue on Arch, 5.13-5. `flameshot gui` crashes as soon as it opens.

Quick gif:
![out](https://user-images.githubusercontent.com/46816684/127134347-f36703fd-3dbe-462b-bf8a-467afe45034a.gif)

**Comment by mmahmoudian** [comment]
This is fixed in v0.10.1 which was released 2 days ago. Please update and see if the issue persists.

I close this issue as I'm pretty sure this issue is the one that we fixed in that hot fix update, but please re-open this issue if you faced the same problem in v0.10.1.

**Comment by richardtatum** [comment]
@mmahmoudian this issue persists in 10.0-1, as that is the version I am using.

Please let me know how best to provide any logs you require.

**Comment by richardtatum** [comment]
Apologies @mmahmoudian, whilst pacman reports that flameshot 0.10.0-1 is installed, `flameshot --version` returns just `v0.10.0`, this likely means the AUR was incorrectly updated.
