### ISSUE TITLE
The "screenshot aborted" should go to stderr

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1771]
While answering to #1681 I realized that `flameshot gui -r > file.png` would always create the file even if the screenshot is aborted (e.g by pressing <kbd>Esc</kbd>). This is because the error "screenshot aborted" is always written to stdout instead of stderr (although the exit code 1 is produced afterwards). I propose writing the errors to stderr.

**Comment by veracioux** [comment]
I agree. I also propose that all the subcommands (gui, screen, etc.) return a non-zero exit code if the daemon is not running. This would be more in line with the Linux philosophy IMO. This is easy to implement and I really need it for some of my scripts to work :)

**Comment by hosiet** [comment]
I disagree with blindly returning non-zero exit code if the daemon is not running.

* If the daemon was not running and subcommands successfully activates flameshot daemon via [D-Bus Activation](https://specifications.freedesktop.org/desktop-entry-spec/1.1/ar01s07.html), the subcommand should return zero. This is exactly why we install `/usr/share/dbus-1/interfaces/org.flameshot.Flameshot.xml` and `/usr/share/dbus-1/services/org.flameshot.Flameshot.service` on Linux system.
* If the daemon was not running and subcommands fail to activate flameshot daemon via D-Bus Activation (e.g., the user is using WM and did not start user D-Bus session), the subcommand should return non-zero.

**Comment by mmahmoudian** [comment]
I agree with @hosiet on both points. Flameshot is a tool that many non-tech-savvy users use it on daily basis and certain things should be handled if possible by the software instead of throwing error without trying. Although I can see that an extra flag can potentially be added to the CLI so that it Flameshot does not even try to load the dbus and throws non-zero exit if daemon wasn't running.

**Comment by veracioux** [comment]
I didn't realize that the daemon is automatically started if it wasn't already running. This doesn't happen on my Arch Linux machine running i3wm. I will investigate this and open an issue if the problem is not on my end. Anyway, I think it is proper to amend my initial statement: the non-zero exit code should be returned if the D-Bus `QDBusConnection::call` method returns a reply of type `QDBusMessage::ErrorMessage`.

For example here:
https://github.com/flameshot-org/flameshot/blob/b2ecb70e386c51315d25fd1ab5b45a7bfc9e04a9/src/main.cpp#L288

I am sorry about the confusion.

**Comment by mmahmoudian** [comment]
On Manjaro (KDE Plasma, AwesomeWM, and dwm) the `flameshot gui` starts the daemon if it is not already started.

Regarding the condition you mentioned, I'm not going to express my opinion as I'm not a C++ developer. Others including @borgmanJeremy and @hosiet are the people who know best. But thank you for the efforts (issues, PR, etc.) you have put into Flameshot these past days 👍🏼

**Comment by veracioux** [comment]
In that case, I could implement the changes if they get approved.

@mmahmoudian You're welcome. Flameshot is a great piece of software which I use a lot. And this is a great learning experience.
