### ISSUE TITLE
could not get the flameshot icon and window after install 0.10.1 version on ubuntu18.04

### ISSUE THREAD

**Issue by FrancisGeek88** [flameshot-org/flameshot#1772]
**Flameshot version**
flameshot-0.10.1-1.ubuntu-18.04.amd64.deb

**Describe the bug**
I install it with following: 
$ sudo dpkg -i flameshot-0.10.1-1.ubuntu-18.04.amd64.deb

$ flameshot --version
Flameshot v0.10.1
Compiled with Qt 5.9.5

**To Reproduce**
$ flameshot
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
Failed to get information about the latest version.  "Error transferring https://api.github.com/repos/flameshot-org/flameshot/releases/latest - server replied: rate limit exceeded"
Failed to get information about the latest version.  "Error transferring https://api.github.com/repos/flameshot-org/flameshot/releases/latest - server replied: rate limit exceeded"

**Expected behavior**
start up normally.

**System Information**
Ubuntu 18.04.5 LTS

**Comment by mmahmoudian** [comment]
Could not reproduce on a clean-install fully updated Ubuntu 18.04

![image](https://user-images.githubusercontent.com/390889/127164118-6057a657-3306-4c7b-b396-a903186b66bf.png)

**Comment by mmahmoudian** [comment]
@FrancisGeek88 please provide all the information asked in the bug report template. We need to know for example:

- what is your DE (Gnome, KDE)
- What is your WM (i3, psbwm, dmw)
- if you are on Wayland or Xorg

I suggest this approach:

```sh
apt install inxi
inxi -G -S
```

**Comment by FrancisGeek88** [comment]
$ inxi -G -S
System:    Host: work Kernel: 4.15.0-151-generic x86_64 bits: 64
           Desktop: Gnome 3.28.4 Distro: Ubuntu 18.04.5 LTS
Graphics:  Card: NVIDIA GP107GL [Quadro P620]
           Display Server: x11 (X.Org 1.19.6 )
           drivers: fbdev,nouveau (unloaded: modesetting,vesa)
           Resolution: 1920x1080@77.00hz
           OpenGL: renderer: llvmpipe (LLVM 10.0.0, 256 bits)
           version: 3.3 Mesa 20.0.8

**Comment by FrancisGeek88** [comment]
$ inxi -G -S
System:    Host: work Kernel: 4.15.0-151-generic x86_64 bits: 64
           Desktop: Gnome 3.28.4 Distro: Ubuntu 18.04.5 LTS
Graphics:  Card: NVIDIA GP107GL [Quadro P620]
           Display Server: x11 (X.Org 1.19.6 )
           drivers: fbdev,nouveau (unloaded: modesetting,vesa)
           Resolution: 1920x1080@77.00hz
           OpenGL: renderer: llvmpipe (LLVM 10.0.0, 256 bits)
           version: 3.3 Mesa 20.0.8

**Comment by mmahmoudian** [comment]
@FrancisGeek88 what happens when in the config file (`~/.config/flameshot/flameshot.ini`) you set the update checking to `checkForUpdates=false`?

**Comment by FrancisGeek88** [comment]
$ cat ~/.config/flameshot/flameshot.ini 
[General]
disabledTrayIcon=false
showStartupLaunchMessage=true
checkForUpdates=false

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
lsx@work ~ $ ps -e | grep flameshot
lsx@work ~ $ flameshot
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed

**Comment by mmahmoudian** [comment]
And now do you get the tray icon and does Flameshot works normally?

P.s: I modified your last post to make it more readable (just added some Markdown styling)

**Comment by FrancisGeek88** [comment]
> And now do you get the tray icon and does Flameshot works normally?
> 
> P.s: I modified your last post to make it more readable (just added some Markdown styling)

no, flameshot did not come out, only this output:

> $ flameshot
> QSettings::value: Empty key passed
> QSettings::value: Empty key passed
> QSettings::setValue: Empty key passed
> QSettings::value: Empty key passed
> QSettings::setValue: Empty key passed

**Comment by FrancisGeek88** [comment]
![Selection_006](https://user-images.githubusercontent.com/53205476/127327787-4d5eb47b-a0b3-4ef5-9a21-e4663731cf0f.jpg)
I screenshot this pic, a flameshot process running but no icon come out.

**Comment by mmahmoudian** [comment]
This is correct. Now you should tell flameshot what to do. in your lower terminal you can run:

- `flameshot gui` to manually select the area you want to take screenshot from
- `flameshot screen` to capture the screen
- `flameshot full` to capture all monitors
- `flameshot config` to open flameshot config

probably because you are using Gnome, you don't have systray. You have to install a gnome extension (https://extensions.gnome.org/extension/1503/tray-icons/) as explained [here](https://flameshot.org/guide/troubleshooting/#in-gnome-the-flameshot-icon-does-not-appear-in-the-tray).

**Comment by FrancisGeek88** [comment]
> This is correct. Now you should tell flameshot what to do. in your lower terminal you can run:
> 
> * `flameshot gui` to manually select the area you want to take screenshot from
> * `flameshot screen` to capture the screen
> * `flameshot full` to capture all monitors
> * `flameshot config` to open flameshot config
> 
> probably because you are using Gnome, you don't have systray. You have to install a gnome extension (https://extensions.gnome.org/extension/1503/tray-icons/) as explained [here](https://flameshot.org/guide/troubleshooting/#in-gnome-the-flameshot-icon-does-not-appear-in-the-tray).

thanks so much, i can use flameshot fluently now. Thanks!!!
