### ISSUE TITLE
How do I set the same shortcut for multiple actions?

### ISSUE THREAD

**Issue by matthpmore** [flameshot-org/flameshot#1789]
Hello. I wanted to both save and copy to clipboard when taking a screenshot with gui, so I tried setting these actions to Return but it doesn't work. What am I supposed to do exactly? Many issues point to editing the configuration.ini file, but they never say what I have to do.

**Comment by borgmanJeremy** [comment]
You can only map one action per hotkey.

However if what you want to do is save AND copy the image, you can set this in the configuration menu

Config > General > Save Image after Copy

**Comment by matthpmore** [comment]
Oh, I see. Thanks for your help
