### ISSUE TITLE
MSVC and GCC incompatibility that causes bugs on Windows

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1794]
There are multiple instances in the code where `#if not defined(Q_OS_MACOS)` is used. This works well in GCC, but in MSVC behaves unexpectedly. What happens is that the code inside this directive gets ignored when compiled with MSVC.

Here's the reason:

Because `not` in this case gets interpreted as a preprocessor constant, and it is undefined, this is equivalent to just `#if defined(Q_OS_MACOS)`. Please see [Microsoft docs](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp?view=msvc-160#remarks) to understand why.

This only happens on Windows, because a) it uses the MSVC compiler, b) it is not a Mac. At least I think so, but I'm not very familiar with MacOS so someone should check.

A simple search will indicate the places in the code where this is used. And it will immediately be clear to you which bug this causes: a missing 'Open with App' button in gui mode on windows. Also someone should check if the button is missing on MacOS.

**Comment by HarisGusic** [comment]
Another bug this same problem caused: #1543
