### ISSUE TITLE
Drawings glitch on undo

### ISSUE THREAD

**Issue by selfdocumentingcode** [flameshot-org/flameshot#1804]
**Flameshot version**
Flameshot 0.8.5-4(Debian)

**Describe the bug**
After I draw a shape and I use the undo command (or use the history panel), the shape doesn't disappear and mixes with the background image.

**To Reproduce**
Select a capture area, draw a rectangle, undo. 

**Expected behavior**
The drawn rectangle should disappear when using the undo command. 

**System Information**
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-25-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 15,1 GiB of RAM
Graphics Processor: AMD RENOIR

**Demo**

https://streamable.com/0ksqvy

![2021-08-06_01-20](https://user-images.githubusercontent.com/8089471/128433555-21e9aa0f-9c39-40a3-b832-c8dfeb85da78.png)

**Comment by borgmanJeremy** [comment]
Please test against our latest version (0.10.1) I think we resolved this.

**Comment by selfdocumentingcode** [comment]
Oh, I didn't realize I wasn't running the latest version. 
I just installed it through apt-get. Where do I get the latest one from?

**Comment by borgmanJeremy** [comment]
Since Debian is a static distribution it does not really provide up to date software.

You can download the .deb from our release page, or use snap or flatpak. Personally I recommend the .deb as the universal packages seem to generate more bug reports.

**Comment by borgmanJeremy** [comment]
Oh sorry I saw you are on kubuntu 21.04 ... strange that they are using an outdated version.

**Comment by selfdocumentingcode** [comment]
I tried to install the .deb package, but it said that "It couldn't satisfy dependencies".
I installed the snap version (with --dangerous) and can confirm that it works as expected now (on v0.10.1).
Thank you!

**Comment by borgmanJeremy** [comment]
Ok great, since you are on Ubuntu you can just snap install from the snap store and always have the latest version.
