### ISSUE TITLE
Windows hidden when attempting to take screenshot on OSX Catalina

### ISSUE THREAD

**Issue by iforwms** [flameshot-org/flameshot#1805]
**Flameshot version**
0.10.1

**Describe the bug**
When selecting "Take Screenshot" from the toolbar menu or via a shortcut the modal overlay is displayed but all windows are hidden and only the desktop background image is shown.

**To Reproduce**
Select "Take Screenshot" from the toolbar menu or via a shortcut.

**Expected behavior**
View currently open windows.

**System Information**
macOS Catalina 10.15.7

**Comment by borgmanJeremy** [comment]
Make sure you gave flameshot screen recording permissions. If it worked on an older version and broke after upgrading, you likely need to remove and re add the permission.

**Comment by iforwms** [comment]
Thanks a lot, yes revoking and re-adding the screen recording permission worked a charm!
