### ISSUE TITLE
Circle counter is not available in Linux

### ISSUE THREAD

**Issue by MohamadKh75** [flameshot-org/flameshot#1807]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Describe the bug**

I can't find the circle counter in Linux version!
![image](https://user-images.githubusercontent.com/25561893/128601402-c5693131-2157-4212-af10-4974c982c0f9.png)

I also checked the config and there is no option for that
![image](https://user-images.githubusercontent.com/25561893/128601455-3f4ffc70-71fa-4353-a3a0-8161d4b27628.png)

**To Reproduce**
Simply use `flameshot gui` and you can't find that!

**Expected behavior**
To have it!

**System Information**

```bash
System:
  Host: ZenBook Kernel: 5.4.0-80-generic x86_64 bits: 64
  Desktop: KDE Plasma 5.18.5 Distro: Ubuntu 20.04.2 LTS (Focal Fossa)
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX150] driver: nvidia v: 460.91.03
  Display: x11 server: X.Org 1.20.11 driver: modesetting,nvidia
  unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz
  OpenGL: renderer: GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 460.91.03
```

**Comment by borgmanJeremy** [comment]
You are on a very outdated version. Please download the latest version from our release page.

**Comment by MohamadKh75** [comment]
I used `apt install flameshot` and I didn't notice the "they could be old warning" 😁 
Thanks!

**Comment by borgmanJeremy** [comment]
No problem , let us know if you need anything else 😁
