### ISSUE TITLE
Feature: Color grabber preview

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1808]
There are many times when I want to grab a color from the screen and the region with the color is quite small (e.g. a color from text). I would like to implement a small widget that shows a zoomed-in region around the color grabber when the mouse is being held down. So everything about the color grabber would work the same except for when the mouse is held down.

Maybe it would be good to add a timer that waits a certain time after pressing the mouse before the widget appears.

**Comment by mmahmoudian** [comment]
I agree, half a second should be roughly a good delay. Would be also nice to see the hexadecimal number of the selected color in the sidebar under the color wheel.

**Comment by mmahmoudian** [comment]
Alternatively it can be activated by scrolling while holding down the mouse, but that makes it hard for laptop users, so I would go with your approach

**Comment by keslerm** [comment]
Random but I was just wondering if flameshot did this today

**Comment by veracioux** [comment]
@keslerm I did start working on it a while back, but I ran into some issues, so I postponed it a bit. I'll continue work on it soon. Nice to see interest in the feature :)

**Comment by veracioux** [comment]
Implemented the preview widget with a 0.5 second timer.
Still have to implement the hex code preview that @mmahmoudian suggested.

**The feature in action:**

https://user-images.githubusercontent.com/29044423/132095615-f654a217-b16c-40e9-a99b-8e2c1a547ba6.mp4

**Testing:**
- test all the scenarios you can think of
- I would appreciate it if someone could test it on MacOS
- also test with multiple monitors if you can (haven't done this myself yet)

**Comment by veracioux** [comment]
Question: Should the overlay message be displayed regardless of `showStartupLaunchMessage`? My opinion is that we should display it regardless.

Because a user can use flameshot for a long time before ever having to use the color grabber (me). By that time they could be annoyed by the startup help message and disable it, but they would have no way to find out all the features that the color grabber supports. The message disappears on mouse enter anyway, and I think that's enough.

**Comment by borgmanJeremy** [comment]
Yes I agree it should always be shown.

**Comment by mmahmoudian** [comment]
I also believe that it should be displayed regardless. I myself was the first user who didn't read the message in the overlay and as the result missed w beautiful and useful functionality with the spacebar.
