### ISSUE TITLE
Filename pattern is cut off if it includes periods

### ISSUE THREAD

**Issue by axelson** [flameshot-org/flameshot#1809]
**Flameshot version**
v0.10.1

**Describe the bug**
Cannot create a filename with multiple periods (dots). I'm trying this pattern `Screenshot %Y-%m-%d %I.%M.%S` (to match what I have on my mac via Dropbox). The preview looks great: `Screenshot 2021-08-07 11.42.44`. However, when I save the screenshot it is saved as `Screenshot 2021-08-07 11.png`. This then causes any other screenshots made in the same hour to be overwritten.

**To Reproduce**

1. Set the Filename pattern to `Screenshot %Y-%m-%d %I.%M.%S`
2. Take a screenshot
3. Filename instead matches `Screenshot %Y-%m-%d %I`

**Expected behavior**
Instead in step 3 I expect the filename to match the given pattern (with minutes and seconds included)

**System Information**
Arch Linux

**Comment by borgmanJeremy** [comment]
This is fixed on master branch with #1733

**Comment by axelson** [comment]
Ah, thanks! Didn't see that because it didn't mention 'period' or 'dot'.
