### ISSUE TITLE
Save Screenshot With Multiple Periods in Filename

### ISSUE THREAD

**Issue by scottzach1** [flameshot-org/flameshot#1810]
**Flameshot version**

Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**

When the user is presented with the save file dialogue, they are also asked to provide a filename. When the user attempts to save to a filename that contains multiple `.`'s, the contents in between the first and last `.` are chomped.

> _Apologies if this was referenced within one of the other saving issues, when searching through before I couldn't find any that exactly matched this description._

Take, for example, the following filenames:

```
screenshot3.ignore.png     -- saves to --> screenshot3.png
screenshot3.ignore.old.png -- saves to --> screenshot3.png
```

**To Reproduce**

1. Launch the screenshot GUI dialogue
2. Save to file `screenshot3.ignore.png`
3. Observe the file `screenshot3.png` was saved.

**Expected behaviour**

The tool should preserve any text **leading up** to the final file extension.

**System Information**

Distro: Arch Linux
Kernel: 5.13.8-arch1-1

**Comment by borgmanJeremy** [comment]
See #1809
