### ISSUE TITLE
Options to capture a single window's area

### ISSUE THREAD

**Issue by OctarineSourcerer** [flameshot-org/flameshot#1816]
It'd be super lovely if there was a way to automatically select the area of the current window - just as there's `flameshot screen` and `flameshot full`, it could be useful to have a `flameshot window` that automatically screenshots the window that's currently focused. 

An alternative or addition to this could be to allow a click to automatically select the area of the window the mouse is over in `manual` mode; `maim` currently does this. `maim -s` instructs it to select an area, but it automatically highlights around the window the mouse hovers, and if you click, it captures the area of that window.

I really like the look of this project by the way!

**Comment by mmahmoudian** [comment]
Isn't this a duplicate of #334 and also partly duplicate of #5 ?

**Comment by OctarineSourcerer** [comment]
> Isn't this a duplicate of #334 and also partly duplicate of #5 ?
> 
> As a side-note, if I have understood your point correctly `flameshot gui` can solve part of your feature request.

You're correct about the issues, my bad! I'll close this one. `flameshot gui` can, yes, though it's very useful to be able to select a window without manually making sure you've got the border selected right

**Comment by mmahmoudian** [comment]
I think you might find this interesting:
https://github.com/flameshot-org/flameshot/issues/1814#issuecomment-895660648

We should definitely push this forward, but I don't think we merge this in the next version or two as we have already a backlog of features and bugs to fix. In case you can  or know someone who can do the final touches on this opencv branch, it might even get to the next release.

**Comment by mmahmoudian** [comment]
> it's very useful to be able to select a window without manually making sure you've got the border selected right

I myself use Flameshot for some presentations and I need to have the cropping happens precise and fast (#1490), so I ended up putting together a dmenu script which I have showcased what it can do:
https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md

perhaps this can also help you for the time being until we implement this in Flameshot.
