### ISSUE TITLE
IRC or some other form of chat

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1818]
Recently I have been engaged in a few lengthy discussions and I have the feeling that it would be more efficient if we used some form of chat for some on-the-fly discussions and debugging. Also, sometimes I have a small question and don't know where to ask it. Opening an issue seems like a waste.

I suggest that we register an IRC channel. I have a hunch that a lot of the developers are familiar with that form of communication. Registering a channel on [Libera.Chat](https://libera.chat/chanreg#on-topic-projects) should not be too difficult.

What are your thoughts?

**Comment by borgmanJeremy** [comment]
Right now we have a slack workspace . If we want to move away from slack I would prefer matrix.

**Comment by veracioux** [comment]
@borgmanJeremy Sorry, I somehow missed that there is a slack workspace. Looking at [RFC.md](https://github.com/flameshot-org/flameshot/blob/2f087980729231b9d3c3d866e6b4a1cba1ec1f2f/docs/RFC.md), it seems that the URL doesn't work. Could you post a valid URL?

I would personally prefer IRC to slack, and matrix has a way to [bridge](https://matrix.org/bridges/#slack) them together.

**Comment by borgmanJeremy** [comment]
Yeah I actually bridge to slack through my matrix home server.

Here is the link: https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg

**Comment by mmahmoudian** [comment]
I have also made a Matrix channel for Flameshot:

https://matrix.to/#/#Flameshot:feneas.org
