### ISSUE TITLE
Error when starting from cli (flatpak)

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1820]
When starting flameshot (flatpak version) from cli, I get this error:
```
Gtk-Message: 12:20:38.483: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:20:38.484: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
```

This could also be related to another issue I'm having when switching to different screens. 
Flameshot works fine when I have my laptop connected to an external screen. Once I disconnect to that screen and try to take a screenshot, it messes up my laptop screen resolution (everything is zoomed in).
But when I try to open it after a couple of tries, resolution does not change, but flameshot is only highlighting part of the screen.

When I try to open it from cli `flatpak run org.flameshot.Flameshot` , only those errors are thrown and nothing happens.

**Comment by mmahmoudian** [comment]
Basically when you run Flameshot without arguments, all you are doing is running the daemon. You should then try to run Flameshot with `gui` argument from another terminal

**Comment by erlisdhima** [comment]
Hi @mmahmoudian , yes, providing the argument `gui` worked fine. Thanks!   
Is it possible to show the help info by default, instead of throwing those errors?

For the resolution, I was able to get a screenshot using the default ubuntu screenshot tool.

![image](https://user-images.githubusercontent.com/7734108/129333726-dde550a5-20ce-46de-82ef-a5512e77fb02.png)

See the flameshot area is not full screen. I'm able to select only in that area. This happens when switching between an external monitor to the laptop monitor (disconnecting the external monitor and using the laptop monitor only).

**Comment by mmahmoudian** [comment]
@erlisdhima running `flameshot` only starts the daemon, in other words it starts a service and if you have tray area it shows the icon there (stupidly enough gnome has removed the tray bar but there is an [easy solution on our website](https://flameshot.org/guide/troubleshooting/#linux)) users should run the Flameshot in the background first (for example via `flameshot &` or using the startup or the app launcher), and then trigger `flameshot gui` or `flameshot screen` or `flameshot full` via keyboard shortcuts like printscreen button on keyboard or left clicking on the tray icon.

That said, to dig out why you are facing the issue of not getting fullscreen screenshot, please provide us the output of the following command in addition to the position of your screens relative to each other (from settings of your ubuntu)

```sh
inxi -s -g
```

**Comment by erlisdhima** [comment]
Both screens have a 1920x1080 resolution. I usually disable the laptop screen and use external screen only when connecting to the external screen.
The issue happens when disconnecting from the external screen. 
When trying to take a screenshot using shortcuts, Flameshot zooms in the entire screen, and keep "refreshing" the screen, and it ends up in high CPU usage. Until I cancel, kill the running flameshot process, and open it again, and I get the result in the screenshot above.

If you're asking for the graphics details, please see below based on what you requested above.
```
$ inxi -s -G
Graphics:  Device-1: NVIDIA GP107GLM [Quadro P2000 Mobile] driver: nvidia v: 470.57.02 
           Display: x11 server: X.Org 1.20.11 driver: nvidia resolution: 1920x1080~60Hz 
           OpenGL: renderer: Quadro P2000/PCIe/SSE2 v: 4.6.0 NVIDIA 470.57.02 
Sensors:   System Temperatures: cpu: 50.0 C mobo: 47.0 C gpu: nvidia temp: 48 C 
           Fan Speeds (RPM): cpu: 0 
```

**Comment by borgmanJeremy** [comment]
Im closing this since the flatpak seems to be working and we have refactored the code to the point that some of these comments are not true any more (ie daemon not required).
