### ISSUE TITLE
Rotate screenshot before saving

### ISSUE THREAD

**Issue by anishmittal2020** [flameshot-org/flameshot#1821]
Would be useful if its possible to rotate the rectangular selection box, by **arbitrary angle**, before saving the screenshot?

**Comment by mmahmoudian** [comment]
To my understanding it is a very niche use case and slightly out of the scope of a screenshot tool as usually everything is aligned on a screen. That said, I can see that it can be a module, sort of like when one click on the handles on an object in Inkscape or LibreOffice. So I mark this as enhancement and let the community show their support 👍🏼

**Comment by borgmanJeremy** [comment]
I agree with @mmahmoudian  that this is out of scope for flameshot.
