### ISSUE TITLE
"Open the Capture" Feature Doesn't List All Programs

### ISSUE THREAD

**Issue by rm-greenzie** [flameshot-org/flameshot#1822]
**Flameshot version**
Flameshot v0.10.1
Compiled with Qt 5.9.5

**Environment**
Ubuntu 18.04

**Describe the bug**
Not all of my programs show up when I try to choose a program to edit the capture. The program in question was install via snap. 

**To Reproduce**
- Install Inkscape via snap.
- Use flameshot to take a screenshot.
- Try to open the capture with inkscape

**Expected behavior**
That it would list all of my programs or at least give me the option of manually typing in the command

**Comment by R3FR4G** [comment]
Same here, i'm trying to use Pinta to open the capture but it is not in the list and it doesn't seem like you can manually specify a command.
In my case, i built Pinta from source

**Comment by mmahmoudian** [comment]
@R3FR4G Considering that Pinta is available everywhere (snap, flatpak, AUR, official repos, ...), I wonder how have you installed Pinta, and also what OS you are using.

**Comment by R3FR4G** [comment]
I used the instructions in Pintas README file (running autogen.sh, make, make install) and I'm on Mint 20.2 Cinnamon.
The versions distributed on flatpak and snap doesn't seem to be the latest ones and as the original message says, it would most likely be better for Flameshot to either list all applications or let you type the command to be executed

**Comment by mmahmoudian** [comment]
@R3FR4G do you have .desktop file for pinta then?

**Comment by R3FR4G** [comment]
Oh that's what it's looking for, i created one and now it works, thanks!

**Comment by mmahmoudian** [comment]
@rm-greenzie would you please also confirm this? Basically is there any app that has a `.desktop` file but does not show in the listed apps? These files should be at `/usr/share/applications/` or at `~/. local/share/applications/`.

**Comment by rm-greenzie** [comment]
So inkscape I found a few .desktop files for inkscape
```
/snap/inkscape/9090/meta/gui/inkscape.desktop
/snap/inkscape/9090/share/applications/org.inkscape.Inkscape.desktop
/var/lib/snapd/desktop/applications/inkscape_inkscape.desktop
```
but added them to `~/.local/share/applications/` only had partial success. The Good: inkscape did show up as an application to choose on the menu. The Bad: clicking on it didn't actually open inkscape.

Not sure if this is a one-off issue with the inkscape .desktop file or not. I can open .png files with inkscape normally

**Comment by mmahmoudian** [comment]
@rm-greenzie i think the .desktop files you found are not formatted correctly. Would you please put here the content of the one that you copied in `~/.local/share/applications/`

**Comment by borgmanJeremy** [comment]
Is it okay to close this? Flameshot is just looking for .desktop files to find external programs.

**Comment by mmahmoudian** [comment]
@borgmanJeremy considering that we have got some open issues with mime types, I wonder if this is related to that or not. I'm going to assign this to myself and if it opened in my Inkscape we can the conclude that the issue lies somewhere in the .desktop file

**Comment by mmahmoudian** [comment]
For those who are reading this thread to find a solution, I should point out that applications like `sxiv` and `feh` have `NoDisplay=true` in their .desktop file which prohibit them from showing up in applications listing including the list of applications in KDE plasma and also in Flameshot. Simply deleting that line would make them appear in the list.

**Comment by mmahmoudian** [comment]
I believe this can be closed. the MIME issues can be addressed through their issue pages
