### ISSUE TITLE
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. 

### ISSUE THREAD

**Issue by rjousse18** [flameshot-org/flameshot#1826]
0.10.1

When I launch flameshot I have this error : 
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.

**Expected behavior**

**System Information**
Zorin 0S 16 Beta (Ubuntu 20.04)

**Comment by borgmanJeremy** [comment]
My guess is this is an issue with the Zorin WM setting the wrong QT variables.
