### ISSUE TITLE
Option to remember last region

### ISSUE THREAD

**Issue by matheusfillipe** [flameshot-org/flameshot#1827]
Flameshot could optionally remember the last region/rectangle that was used. It could be an option with the `flameshot gui` command.

**Comment by mmahmoudian** [comment]
@matheusfillipe  Isn't this exact duplicate of #1509?

**Comment by matheusfillipe** [comment]
Yes it is. Sorry for duplicating!

**Comment by mmahmoudian** [comment]
@matheusfillipe no worries, keep sending your nice ideas 👍🏼
