### ISSUE TITLE
Ubuntu 21.04 deb package building from source fail with error...

### ISSUE THREAD

**Issue by Creteil** [flameshot-org/flameshot#1828]
**Flameshot version**
latest commit 0.10.1-25-g39afd66

**Describe the bug**
Trying to build using the « packaging/debian » from repository fail.

**To Reproduce**
```
git clone https://github.com/flameshot-org/flameshot.git
cd flameshot
ln -sf packaging/debian .
DEBEMAIL="PUT Yourmailhere <someone.at.somewhere@on.the.net>" dch -b -v $(git --git-dir .git --work-tree . describe --always --tags | cut -c2-) "Update to latest GIT Version..." && sed -i '$!N; /^\(.*\)\n\1$/!P; D' debian/changelog ; head -10 debian/changelog
dpkg-checkbuilddeps && dpkg-buildpackage -rfakeroot
```

**Expected behavior**
debian package created.

**System Information**
Ubuntu 21.04 hirsute

Building package process fail with error :

[100%] Built target flameshot
make[2] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
/usr/bin/cmake -E cmake_progress_start /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/CMakeFiles 0
make[1] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 fakeroot debian/rules binary
dh binary 
   dh_testroot
   dh_prep
   dh_auto_install
	cd obj-x86_64-linux-gnu && make -j8 install DESTDIR=/home/bigbob/tmp/Building/flameshot/flameshot/debian/flameshot AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true"
make[1] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
/usr/bin/cmake -S/home/bigbob/tmp/Building/flameshot/flameshot -B/home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/CMakeFiles /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[2] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make  -f external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build.make external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/depend
make  -f external/spdlog/CMakeFiles/spdlog.dir/build.make external/spdlog/CMakeFiles/spdlog.dir/depend
make[3] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
cd /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/bigbob/tmp/Building/flameshot/flameshot /home/bigbob/tmp/Building/flameshot/flameshot/external/singleapplication /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/singleapplication /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/DependInfo.cmake --color=
make[3] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
cd /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/bigbob/tmp/Building/flameshot/flameshot /home/bigbob/tmp/Building/flameshot/flameshot/external/spdlog /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/spdlog /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/spdlog/CMakeFiles/spdlog.dir/DependInfo.cmake --color=
make[3] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make  -f external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build.make external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build
Consolidate compiler generated dependencies of target spdlog
make[3] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
[  1%] Automatic MOC for target SingleApplication
cd /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/singleapplication && /usr/bin/cmake -E cmake_autogen /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu/external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/AutogenInfo.json None
**make[3]: *** [external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build.make:74 : external/singleapplication/CMakeFiles/SingleApplication_autogen] Erreur 255
make[3] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make[2]: *** [CMakeFiles/Makefile2:305 : external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/all] Erreur 2
make[2]: *** Attente des tâches non terminées....
make[3] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make  -f external/spdlog/CMakeFiles/spdlog.dir/build.make external/spdlog/CMakeFiles/spdlog.dir/build
make[3] : on entre dans le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make[3]: rien à faire pour « external/spdlog/CMakeFiles/spdlog.dir/build ».
make[3] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
[  7%] Built target spdlog
make[2] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
make[1]: *** [Makefile:159 : all] Erreur 2
make[1] : on quitte le répertoire « /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu »
dh_auto_install: error: cd obj-x86_64-linux-gnu && make -j8 install DESTDIR=/home/bigbob/tmp/Building/flameshot/flameshot/debian/flameshot AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:19 : binary] Erreur 2
dpkg-buildpackage: erreur: fakeroot debian/rules binary subprocess returned exit status 2**

**Comment by ZetaoYang** [comment]
The bold part of the error message is translated into English,
**make[3]: *** [external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build.make:74 : external/singleapplication/CMakeFiles/SingleApplication_autogen] Error 255
make[3]: we leave the directory " /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu "
make[2]: *** [CMakeFiles/Makefile2:305 : external/singleapplication/CMakeFiles/SingleApplication_autogen.dir/all] Error 2
make[2]: *** Waiting for unfinished tasks....
make[3]: Exit the directory "/home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu
make -f external/spdlog/CMakeFiles/spdlog.dir/build.make external/spdlog/CMakeFiles/spdlog.dir/build
make[3]: we enter the directory "/home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu
make[3]: nothing to do for "external/spdlog/CMakeFiles/spdlog.dir/build".
make[3]: we leave the directory "/home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu".
[ 7%] Built target spdlog
make[2]: leave the directory " /home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu "
make[1]: *** [Makefile:159 : all] Error 2
make[1]: leave the directory "/home/bigbob/tmp/Building/flameshot/flameshot/obj-x86_64-linux-gnu
dh_auto_install: error: cd obj-x86_64-linux-gnu && make -j8 install DESTDIR=/home/bigbob/tmp/Building/flameshot/flameshot/debian/flameshot AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:19 : binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2**

**Comment by ZetaoYang** [comment]
I tried to build flameshot on https://labs.play-with-docker.com docker environment Ubuntu 21.04, here is my steps,
1. login play-with-docker via ssh, ssh -i C:/Users/your user name/.ssh/play_with_docker_rsa ip172-18-0-35-c4g66pnnjsv000ehlmo0@direct.labs.play-with-docker.com
2. `docker pull packpack/packpack:ubuntu-hirsute`
3. `docker run --name build -it packpack/packpack:ubuntu-hirsute`
3. install dev dependencies via `apt install qttools5-dev-tools libqt5svg5-dev qttools5-dev`
4. git clone https://github.com/flameshot-org/flameshot.git
cd flameshot
ln -sf packaging/debian .
5. dpkg-checkbuilddeps && dpkg-buildpackage -b

**NOTE.**  `packpack/packpack:ubuntu-hirsute` is the root user by default, so you don't need _fakeroot_.

@Creteil So it's not flameshot's problem, it's your own problem. 
@mmahmoudian 
I suggest turning on the github discussions feature and moving this issue there.

**Comment by Creteil** [comment]
OK, fixed it with :

```
sudo apt purge fakeroot-ng
sudo apt install fakeroot
```

Then building process end without error :

```
dpkg-deb: building package 'flameshot' in '../flameshot_0.10.1-25-g39afd66_amd64.deb'.
dpkg-deb: building package 'flameshot-dbgsym' in 'debian/.debhelper/scratch-space/build-flameshot/flameshot-dbgsym_0.10.1-25-g39afd66_amd64.deb'.
	Renaming flameshot-dbgsym_0.10.1-25-g39afd66_amd64.deb to flameshot-dbgsym_0.10.1-25-g39afd66_amd64.ddeb
 dpkg-genbuildinfo
 dpkg-genchanges  >../flameshot_0.10.1-25-g39afd66_amd64.changes
dpkg-genchanges: info: inclusion du code source original dans l'envoi (« upload »)
 dpkg-source --after-build .
dpkg-buildpackage: info: envoi complet ; paquet Debian natif (inclusion du code source complet)
dpkg-buildpackage: avertissement: construction non-publiée (UNRELEASED) non signée ; veuillez utiliser --force-sign pour passer outre
bigbob@bigbob-UX331UN:~/tmp/Building/flameshot/flameshot$
```

Hope it help...
