### ISSUE TITLE
Strange controls behavior with multiple monitors on Windows 10

### ISSUE THREAD

**Issue by zdmitchell** [flameshot-org/flameshot#1830]
**Flameshot version**

0.9.0 installed using scoop

**Describe the bug**

These are my displays:
![image](https://user-images.githubusercontent.com/51836911/130290244-49a6845d-5bfb-4f06-ad1a-40b65a3ff43f.png)
The right display is my main display.

<details>
<summary>When capturing an image on the left display, everything works great.</summary>

![screenshot1](https://user-images.githubusercontent.com/51836911/130291470-beb97602-cd91-44ed-bd6e-bdcc12d88354.jpg)
</details>

<details>
<summary>However, when capturing an image on the right display (my main display) the controls bundle into the top left of the left display.</summary>

![screenshot2](https://user-images.githubusercontent.com/51836911/130291505-cab0ef47-a9f5-402a-bb72-2138206b513b.jpg)
</details>

**Expected behavior**
The controls should bundle around the screenshot in both cases.

**System Information**

Windows 10 10.0.19043 Build 19043

**Comment by borgmanJeremy** [comment]
This is fixed in the latest version. The scoop package is out of date but we don't directly maintain that.

**Comment by ZetaoYang** [comment]
> This is fixed in the latest version. The scoop package is out of date but we don't directly maintain that.

Update https://github.com/lukesampson/scoop-extras/pull/6669

**Comment by mmahmoudian** [comment]
@zdmitchell shall we close this issue?

**Comment by zdmitchell** [comment]
Yes. Thanks for the help everyone!

**Comment by ZetaoYang** [comment]
0.10.1 is available, https://github.com/lukesampson/scoop-extras/blob/master/bucket/flameshot.json
