### ISSUE TITLE
`flameshot gui` always save in the clipboard

### ISSUE THREAD

**Issue by mhalano** [flameshot-org/flameshot#1833]
**Flameshot version**
v0.10.1

**Describe the bug**

I try to capture a selection of the screen and save to a file, but it always went to the clipboard. I'm using the command `flameshot gui --path /tmp`. Since I'm using --path the screenshot should be saved there. II use other commands like `flameshot screen --path /tmp` and works fine.

**To Reproduce**

1. Execute `flameshot gui --path /tmp`
2. It will be showed a notification saying the capture was saved in clipboard

**Expected behavior**

The capture should be saved inside the directory, in this case /tmp

**System Information**

Ubuntu 21.04 using the Snap

**Comment by mmahmoudian** [comment]
@veracioux considering that you recently worked on adding `--clipboard` to `flameshot gui`, you might have a fresh memory of the codebase and if this issue is related or not.

**Comment by veracioux** [comment]
I could not reproduce the issue on ubuntu 20.04 (snap, v0.10.1).
And I do not see which part of the code could cause the issue.
@mhalano Could we see your flameshot configuration?

**Comment by mhalano** [comment]
@veracioux I was doing more tests today and found Snap isn't very functional, at least for me, so I got the Deb package from Debian (it has the latest version) and installed on Ubuntu 21.04. I think I misunderstood how to use the tool: After I execute `flameshot gui --path /tmp`, I can select part of the screen, but I couldn't save when pressing Enter (that was said in pop-up, to press Enter to capture), so I have to click in the diskette icon, and it saves a new capture in the indicated place.
Because of that, I will open up a new bug, so we can check the behavior of enter key to save the selection of screen.

**Comment by mhalano** [comment]
I opened this bug which, I think, is the correct one #1835
