### ISSUE TITLE
Deleting the config file leaves me with no keyboard shortcuts

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1842]
If I delete the config file, I am left with no keyboard shortcuts. This means that new users will have to manually add the shortcuts. I think I remember that a previous version of flameshot would fall back to default shortcuts in that case. Was that feature removed intentionally or is it a bug? It is also possible that I have introduced the bug while working on some bug fixes :)

I would like to implement the following behavior:
- If you delete the config file, the default shortcuts will be active
- Only shortcuts that the user changes (or disables) will be written to the config file

As a side note: Why is image upload excluded from the default shortcuts [here](https://github.com/flameshot-org/flameshot/blob/41ca51bc1028dd475b1bcc8954f44fda46168305/src/utils/configshortcuts.cpp#L15-L19)?

**Comment by borgmanJeremy** [comment]
Yes it used to come up with default. I would bisect the code to see where it was introduced.

We disabled image upload hotkeys until we add a confirmation dialog to uploads. We had too many instances of users accidentally uploading data.

**Comment by veracioux** [comment]
I started bisecting the code from v0.10.1 where the feature worked. But it didn't work as well as I would like it to. If I deleted the file while the daemon was running, the default shortcuts would not work. So I implemented the fix myself, using the opportunity to refactor a little.
