### ISSUE TITLE
Add shortcuts in the tooltip

### ISSUE THREAD

**Issue by majkinetor** [flameshot-org/flameshot#1854]
It would be great to show current shortcuts in the tooltip

For example, instead

- Set arrow as a paint tool

use

- Set arrow as a paint tool (A)

**Comment by veracioux** [comment]
@majkinetor Already implemented in [this commit](https://github.com/flameshot-org/flameshot/commit/2f087980729231b9d3c3d866e6b4a1cba1ec1f2f) :)

**Comment by majkinetor** [comment]
Ah nice, looked for issues and not MRs. Thanks.
