### ISSUE TITLE
Only quarter of screen viewable for snapshot

### ISSUE THREAD

**Issue by n4562** [flameshot-org/flameshot#186]
Hello,

Really impressed by flameshot; I've been testing such tools for a while but never found the perfect one.
I do have an issue; I am on KDE / OpenSuse Leap 42.3. On a Dell laptop (xrandr of eDP-1 connected 3840x2160+0+0). Compiled from source using Qt 5.6.0 and gcc 4.9.4.
When trying the snapshot (e.g. PrtScr) only the top left quarter of my screen is "shown"; the other 3 quarters can be selected but are just blank.
Some trials:
* If the selection overlaps both the "blank" and "viewable" area, selection gets cropped to only the "viewable" area 
* If the selection only overlaps the "blank" area, saved snapshot is the full "viewable" area
* if the selection only overlaps the "viewable" area, saved snapshot is the correct one.

Any ideas?

Cheers,

**Comment by lupoDharkael** [comment]
What's your desktop environment?

**Comment by n4562** [comment]
$plasmashell --version
plasmashell 5.8.7

$kf5-config --version
Qt: 5.6.2
KDE Frameworks: 5.32.0
kf5-config: 1.0
