### ISSUE TITLE
[Question] How to create a keybind for Windows?

### ISSUE THREAD

**Issue by Dragonizedpizza** [flameshot-org/flameshot#1861]
There's no option to create a keybind on windows, is there any way I can do so?

**Comment by mmahmoudian** [comment]
@Dragonizedpizza Flameshot by default uses <kbd>PrintScreen</kbd> on Windows. Is that what you wabt to change?

**Comment by Dragonizedpizza** [comment]
Yes

**Comment by Dragonizedpizza** [comment]
To alt shift s
