### ISSUE TITLE
flameshot does not work correctly with 3 displays with 4k

### ISSUE THREAD

**Issue by dennisTGC** [flameshot-org/flameshot#1863]
Hi, 

I'm a big fan of the tool but it looks like it has some problems with 3 screens if they are on 4k each. Flameshot only targets the half of the side screens and the full main screen. 

I'm working on a Dell precision 3420 workstation with Ubuntu 20.04.1 with KDE.

**Comment by borgmanJeremy** [comment]
Are you using fractional scaling?

**Comment by dennisTGC** [comment]
yes I did, I turned it off and flameshot worked as expected, it took all 3 screens. Seems an error with fractional scaling indeed (https://github.com/flameshot-org/flameshot/issues/1296), thanks borgman!

you can close this issue as an duplicate
