### ISSUE TITLE
Screenshoting not working on kernel 5.14 Ubuntu 21.04

### ISSUE THREAD

**Issue by stepanselyuk** [flameshot-org/flameshot#1865]
**Flameshot version**
```
$ snap install flameshot --edge
flameshot (edge) v0.10.1+git38.ec70df1 from Jeremy Borgman (borgman-jeremy) installed
```

**Describe the bug**
When I click "Take screenshot" nothing happening. Tried to install with --classic mode, nothing changed.

**To Reproduce**
Install on Ubuntu 21.04 with kernel 5.14

**Expected behavior**
Should work.

**System Information**
Ubuntu 21.04 with kernel 5.14
```
$ uname -a
Linux stepan-xps 5.14.0-051400-generic #202108292331 SMP Sun Aug 29 23:33:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
```

**Comment by mmahmoudian** [comment]
I'm not sure what you mean by Take Screenshot but I guess it is from the launcher.

Does the normal gui way work? For example left-click on the tray icon.

**Comment by stepanselyuk** [comment]
@mmahmoudian yes, the normal GUI is working fine. When I click on the left button on the icon in tray, it shows the menu, and then I click on "Take screenshot" and nothing happens. Same as I click on "Open launcher", the launcher window opens, but it's not doing a screenshot then (after click on the button).

**Comment by mmahmoudian** [comment]
I cannot reproduce this on AUR install Flameshot v0.10.1 (ec70df10).

@stepanselyuk what is your Window Manager and your Display Manager?

**Comment by stepanselyuk** [comment]
@mmahmoudian 
```
$ wmctrl -m
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF

$ printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: ubuntu:GNOME
Session: ubuntu
```

**Comment by mmahmoudian** [comment]
@stepanselyuk sorry, I'm not familiar with this output. Does it means that you are on Xorg?

**Comment by stepanselyuk** [comment]
I have a default Ubuntu 21.04 installation :-)

**Comment by mmahmoudian** [comment]
I actually don't know what Ubuntu uses in their 21.04. Would you please give me the output of the following command:

```sh
loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
```

Or check this page:

https://flameshot.org/guide/issue-reporting/

**Comment by stepanselyuk** [comment]
@mmahmoudian 
```
$ loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
wayland
```

**Comment by felipe3dfx** [comment]
@mmahmoudian 

Same error but is installed with apt

`$ loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value`
`x11`

**Comment by borgmanJeremy** [comment]
The latest snap released yesterday solves this problem.
