### ISSUE TITLE
Change text font

### ISSUE THREAD

**Issue by soichih** [flameshot-org/flameshot#1866]
It looks like flameshot is defaulting to use a fixed-width font for the text tool.

Is there a way to change it to Sans-Serif font?

**Comment by borgmanJeremy** [comment]
yes, if you hit spacebar to open the sidebar you can change the font.

**Comment by soichih** [comment]
Ah! I did know you can do that!

However, the sidebar seems to be truncated?

![2021-09-03_15-13](https://user-images.githubusercontent.com/923896/132055499-5929a0ef-8c44-4137-b78d-08876d039899.png)

Is there a way to *save* the current font selection / size so I don't have to keep resetting them?

**Comment by mmahmoudian** [comment]
@soichih add this to your config with whatever font you want:

```
fontFamily=Noto Mono
```

About the truncation, as far as I can remember, there was a bug and it was solved some versions ago. Which version are you using?

**Comment by Kin-Zhang** [comment]
> @soichih add this to your config with whatever font you want:
> 
> ```
> fontFamily=Noto Mono
> ```
> 
> About the truncation, as far as I can remember, there was a bug and it was solved some versions ago. Which version are you using?

But it seems didn't work on Window in the lastest release version 10.1
![image](https://user-images.githubusercontent.com/35365764/140002526-8c9072b8-ce5d-430b-94c2-2f263794c29f.png)
I import this conf, the path of picture saved is changed but the font didn't change

**Comment by mmahmoudian** [comment]
@Kin-Zhang how have you installed Flameshot? What is the exact version of your Flameshot (right click on the tray icon > About > copy)?

**Comment by Kin-Zhang** [comment]
> @Kin-Zhang how have you installed Flameshot? What is the exact version of your Flameshot (right click on the tray icon > About > copy)?
Sorry for the late reply, thank you for asking.
I download the version of Flameshot-0.10.1-win64.msi from: https://github.com/flameshot-org/flameshot/releases
Version is 0.10.1

**Comment by mmahmoudian** [comment]
I don't have a Windows machine to test this. @borgmanJeremy If I recall correctly you have a Windows VM. If you still have it, can you test this
