### ISSUE TITLE
Screenshot gets copied multiple time into the clipboard

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1867]
When hitting <kbd>Ctrl + C</kbd>, the image is copied several times into the clipboard.
This happens only when using the shortcut. It doesn't happen when you click the copy icon from the flameshot gui.

Also, when using the shortcut to copy the screenshot, it will keep that screenshot into the clipboard and will not copy new screenshots. Basically it will be locked into the initial screenshot you took. You can get out of this state if you use the copy icon, or if you copy some text and take another screenshot.

I'm using the latest version of the flatpak version (v0.10.1). I'm on Ubuntu 20.04.3 LTS

**Comment by mmahmoudian** [comment]
I assume you have a software like CopyQ installed from which you realized it will copy to clipboard multiple times, right?

**Comment by erlisdhima** [comment]
Hi @mmahmoudian , sorry for the delay!

Yes, thats correct. I'm using something similar called GPaste.
 
The problem happens only with flameshot. It does not copy the clipboard multiple times when copying some text for example.

But it may as well be an issue with that, because when I was monitoring the CPU usage, it seems GPaste is using it the most.
This didn't happen with CopyQ. I guess its time to switch. :) 

Thanks for your time and suggestion!
