### ISSUE TITLE
[Feature Request] Auto-Incrementing Numbered Bullets

### ISSUE THREAD

**Issue by H8to** [flameshot-org/flameshot#187]
Hey there,
great tool!

I miss a tool for auto-incrementing number bullets. This would allow easy highlighting of screenshot details from e.g. a documentation text.

![](https://1.bp.blogspot.com/-UsgGUyDWUPE/WT90tEL5aXI/AAAAAAAAPQs/YU5vpZ2qArcDDR_a2zHueGBfwluzeOYewCLcB/s1600/2017_GreenShotCounters.png)

Is this a feature you may consider to implement?

**Comment by ZetaoYang** [comment]
@H

**Comment by ZetaoYang** [comment]
@H8to I like this idea.

**Comment by Rmano** [comment]
@xstable the first one (writing text) has been already added. It's not movable (once written, I mean) but it works quite ok.

**Comment by DavidPerezIngeniero** [comment]
I don't know how to write text.  I've tested with version 0.6.0

**Comment by Rmano** [comment]
1. call `flameshot config`, enable the text tool: 
![image](https://user-images.githubusercontent.com/6414907/45031741-ff7bab80-b04f-11e8-8ecf-057b8c6173ce.png)

2. Use the text tool; mouse wheel to select size, right click for color. 

![screenshot from 2018-09-04 14-41-56](https://user-images.githubusercontent.com/6414907/45031982-c55ed980-b050-11e8-8cdd-3fb29c1ce242.png)

**Comment by DavidPerezIngeniero** [comment]
Thanks!

**Comment by DavidPerezIngeniero** [comment]
Version 0.6.0 doesn't have it yet.

**Comment by Rmano** [comment]
Have you stopped the old flameshot after installing the new one? 
```killall flamsehot```
...and then restart it. Flameshot keeps running in background...

**Comment by DavidPerezIngeniero** [comment]
That's it! 
Here is the solution:
```
pkill flameshot
flameshot&
flameshot config
```

**Comment by wokezombie** [comment]
> That's it!
> Here is the solution:
> 
> ```
> pkill flameshot
> flameshot&
> flameshot config
> ```

Thank you so much for this! I've been looking for something like greenshot on windows, for linux, just discovered flameshot, and couldn't figure out the text feature! Then couldn't figure out how to enable it, thanks a lot, this helped me!!  Now onto exploring this repo to see if there's a way to adjust the font! :)

**Comment by lupoDharkael** [comment]
I've started working on this feature.

**Comment by whnr** [comment]
> I've started working on this feature.

Love it! This has been one of the most useful features when explaining multiple things in a single shot

**Comment by sparcbr** [comment]
> I've started working on this feature.
@lupoDharkael Hey, have you made any progress? I could help.

**Comment by Frankstar** [comment]
Any Update on this?
its the only thing i miss from Windows / Greenshot

**Comment by mattiz** [comment]
This is the only feature I've been missing on Flameshot. It's a really good alternative for Shutter!

**Comment by sebastienPoussard** [comment]
I concur, auto increment bullet is a great feature I miss on Flameshot

**Comment by xstable** [comment]
I'm not sure if this Project is still alive. A pitty, that since a long time there is no progress on it.
Would be great if the maintainer would add some developers (someone who still send pull-requests) to the project.
I still use flameshot and like it, but I've also started to test & use  `[ksnip](https://github.com/ksnip/ksnip)` as alternate Snapshot-Tool.

I would prefer to use flameshot, but if this project isn't under maintenance anymore, I think ksnip will overtake flameshot soon.

**Comment by borgmanJeremy** [comment]
Check out #769 and provide feedback. I added this feature to my local fork a while back.

**Comment by xstable** [comment]
Can you send an PR to this repo. I would love to see it in the main release

**Comment by borgmanJeremy** [comment]
Yeah there is a PR #770 .

You can just clone the repo and build in qt creator.

**Comment by borgmanJeremy** [comment]
Merged into master and will be in next release.
