### ISSUE TITLE
Assigning a key for "Take Screenshot"?

### ISSUE THREAD

**Issue by kangaroo72** [flameshot-org/flameshot#1871]
Hi team,

maybe I did not see it, but isn't it possible, to add a key (like print screen) to the "Take Screenshot"-Function?

Thank you,

-Tom-

**Comment by mmahmoudian** [comment]
@kangaroo72 I guess you missed [this part of the documentation](https://github.com/flameshot-org/flameshot/#global)
On Windows it automatically maps to the PrintScreen key. On Linux you have to configure it.

If you have any issues with mapping it in linux, just post here your operating system and your Desktop Environment and I'll help you.

**Comment by kangaroo72** [comment]
Thanks so much for your help...
I'm on Ubuntu Budgie 21.04 (Gnome)
I tried that, but after pressing "Print" Key, it's just making a full screen screenshot...

**Comment by mmahmoudian** [comment]
So you did all the following:

![image](https://user-images.githubusercontent.com/390889/132352417-887b12a5-ea56-460a-a1c7-e0d9eba7061a.png)


and then when you pressed the PrintScreen key, did you see the following message?

![image](https://user-images.githubusercontent.com/390889/132352824-bef9dd98-82c7-4149-89fe-ef6f8b7844bf.png)

**Comment by kangaroo72** [comment]
Yes, I did that...
![image](https://user-images.githubusercontent.com/6906390/132355845-04c611e1-a14a-470b-a3ea-c3ef8cb7a871.png)
But no effect.
When pressing the key, the screen just flashes, and a full screenshot is saved by Ubuntu.

**Comment by kangaroo72** [comment]
Wait ... now it works - let me do a reboot...

**Comment by kangaroo72** [comment]
Yeaaaah - it's reboot-resistant - thanks a lot!!!

**Comment by mmahmoudian** [comment]
a typical "turning it off an on again" situation 😉 

https://www.youtube.com/watch?v=nn2FB1P_Mn8

**Comment by mmahmoudian** [comment]
@kangaroo72  Shall we close this issue then?

**Comment by kangaroo72** [comment]
For that case, yes. I'm still working on a autostart-feature.
I have to start FS, once, if the machine has rebootet...
The Option is activated for autostart.

**Comment by mmahmoudian** [comment]
![image](https://user-images.githubusercontent.com/390889/132357178-3e725dae-be48-4684-85e5-b07cad563b4b.png)

**Comment by kangaroo72** [comment]
Now print screen doesn't work anymore :-(

**Comment by kangaroo72** [comment]
Is the snappy version maybe a problem?

**Comment by kangaroo72** [comment]
This happens, while pressing print screen...
https://cloud.escher.cc/s/F2bEi3LCFa3KeWX

**Comment by borgmanJeremy** [comment]
It might be an issue with the snap, unfortunately that package seems buggier than the .deb release. It requires a total rebase and when I last checked the newer KDE base was not ready .

**Comment by kangaroo72** [comment]
I will replace it with *.deb

thx
