### ISSUE TITLE
Flameshot can't reopen after quit application on Mac

### ISSUE THREAD

**Issue by rahmadsandy** [flameshot-org/flameshot#1872]
Flameshot cant reopen after quit application on Mac, when i tried to running from terminal `/Applications/flameshot.app/Contents/MacOS/.flameshot`

``` bash
SingleApplication: Unable to create block.
SingleApplication:  7 "QSharedMemory::create: out of resources"
````

Mac OS version: Big Sur 11.3.2 Apple M1

**Comment by mmahmoudian** [comment]
@rahmadsandy Please specify your Flameshot version (possibly through `--version` argument via terminal)

**Comment by rahmadsandy** [comment]
hello @mmahmoudian noting verbose result through terminal
![image](https://user-images.githubusercontent.com/57087446/132453669-960dcfe7-4d28-45d9-9579-f0ab7969f1c1.png)

but in GUI version
![image](https://user-images.githubusercontent.com/57087446/132453715-3cc7c61d-465e-4829-a194-47573185f3a8.png)

**Comment by mmahmoudian** [comment]
@rahmadsandy would you press give me the output of this command:

```sh
ls -al /Applications/flameshot.app/Contents/MacOS/
```

**Comment by rahmadsandy** [comment]
here @mmahmoudian 
![image](https://user-images.githubusercontent.com/57087446/132477431-647c5ac0-a011-4615-af57-3a2fe2680fb1.png)

i installed flameshot troughs homebrew

**Comment by mmahmoudian** [comment]
in that case you had an extra `.` in the command you ran:

```sh

/Applications/flameshot.app/Contents/MacOS/.flameshot
#                                          ^
#------------------------------------------'
```

I don't have Mac, but I suggest following either of these instructions:
- https://support.apple.com/guide/terminal/execute-commands-and-run-tools-apdb66b5242-0d18-49fc-9c47-a2498b7c91d5/mac
    - ```sh
      open -a flameshot.app
      ```
- https://smallbusiness.chron.com/execute-file-macbook-terminal-49381.html
    - ```sh
      cd /Applications/flameshot.app/Contents/MacOS/
      ./flameshot
      ```

**Comment by rahmadsandy** [comment]
its same error result with issue description above
![image](https://user-images.githubusercontent.com/57087446/132479637-53ea9ad5-7ef1-4c70-b60f-25d28e16112b.png)

**Comment by veracioux** [comment]
Perhaps the newest master (233c765b1fa82a2bfd92cfd7bfbb324464165efb) indirectly solves (or at least mends) this issue, as it invalidates the need for a daemon to run constantly. You can compile it or download from [here](https://flameshot.org/docs/installation/development-build).
