### ISSUE TITLE
Use Mozilla JPEG Encoder (MozJPEG) for JPEGs

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1873]
I have heard many good things about [MozJPEG](https://github.com/mozilla/mozjpeg) and I wonder if it is feasible and practical to it (potentially optionally using a checkmark in the config) for the JPEGs.

**Comment by hosiet** [comment]
I don't see much benefits of introducing yet another dependency solely for jpeg handling:

* Flameshot uses PNG by default, and only part of the users explicitly choose jpeg.
* Mozjpeg is not in the official repo any of the major Linux distributions (deb, fedora, Arch). Using it complicates building process for packagers as well as buildsystem for flameshot.
* Mozjpeg, as a drop-in replacement of libjpeg-turbo, provides the same API/ABI as existing libraries. This means that using mozjpeg will have almost no change to user experience, and all existing bugs about jpeg remain the same.

The sole improvement brought by mozjpeg could be higher visual quality / small file size as claimed by mozjpeg project. However, users could just switch back to PNG if they need those improvement.

**Comment by mmahmoudian** [comment]
@hosiet well put. I have no strong feelings about this and I've never used it myself either. Since their repo is well maintained I thought it might be a good choice. I should have checked the repos though before making the suggestion. 😅

Anyways, perfect logic and explanation 👍🏼
