### ISSUE TITLE
Feature: Change tool size by entering number

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1877]
Here's a state diagram, assuming for convenience that the size indicator has a timeout of 1 sec:
- You press the size increase/decrease button.
- The size indicator shows up in the top left corner
- While the size indicator is active, you press numbers on your keyboard:
  - You press `1` => the size changes to 1 (size indicator's timeout is prolonged by 1 sec)
  - Then you press `2` => the size changes to 12 (timeout prolonged again)

To elaborate further: each time you enter a number, the size indicator's life should be prolonged. So if the default timeout is 1 sec, after pressing a number the timer should be reset so that the indicator remains displayed 1 sec after pressing the number.

In addition to this, maybe it would be good to enable changing the tool size by entering a number even when the size indicator is not active, but only if there are no keyboard shortcuts that are composed of single numbers. After pressing the first number, the size indicator should appear and everything should proceed as in the state diagram from that point onwards.

**Comment by mmahmoudian** [comment]
This is very useful esp. when I want all my arrows to be 4 but all the rectangles to be 2. At the moment I should scroll every time. and try to get it right.

The only thing I'm not very fund of is the 1sec delay. imo it is too long of waiting.

**Comment by veracioux** [comment]
@mmahmoudian It was just for illustration purposes. I was just too lazy to check what delay is currently implemented :)

**Comment by borgmanJeremy** [comment]
Yeah this seems like a great idea.

**Comment by veracioux** [comment]
Done. I also reduced the notifier box timeout from 1200 to 600 milliseconds. And greatly improved the performance of the thickness update.
