### ISSUE TITLE
The "copy to clipboard" button keeps the margin of the selected annotation

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1879]
**Flameshot version**
Flameshot v0.10.1 (ec70df10)
Compiled with Qt 5.15.2

**Describe the bug**
The copy function does not deselect the selected item and then copy and the dotted line would remain the screenshot. This behavior is also present in the `--raw` but does **not** happen with save.

Also interestingly enough, the <kbd>Ctrl</kbd>+<kbd>c</kbd> doers not even save the screenshot but Flameshot still gets closed!!

![image](https://user-images.githubusercontent.com/390889/132851302-6c2b27b7-87db-41cf-93ba-94b69302dd04.png)

**To Reproduce**
1. `flameshot gui`
2. Select an area
3. draw an arrow
4. select the arrow (and for example scroll to increase the size)
5. press the copy button.

**Expected behavior**
The selection dotted line should not get copied to the clipboard

**System Information**
> ```
> System:
>   Host: precisiontower Kernel: 5.10.60-1-MANJARO x86_64 bits: 64
>   Desktop: KDE Plasma 5.22.5 Distro: Manjaro Linux
> Graphics:
>   Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
>   Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
>   Display: x11 server: X.Org 1.20.13 driver: loaded: amdgpu,ati,modesetting
>   resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
>   OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.40.0
>   5.10.60-1-MANJARO LLVM 12.0.1)
>   v: 4.6 Mesa 21.2.1
> ```

**Comment by thepurple** [comment]
I can reproduce it too, will try to find some time to fix it.

**Comment by thepurple** [comment]
@mmahmoudian please this fix: https://github.com/flameshot-org/flameshot/pull/1881
