### ISSUE TITLE
A new window is opened when taking screenshot

### ISSUE THREAD

**Issue by mohad12211** [flameshot-org/flameshot#1886]
Taking a screenshot will open a new window instead of showing an overlay.
Flameshot v0.10.1 (d8d428f)

https://streamable.com/hkovpn

latest commit Flameshot v0.10.1 (c3dd1ce5):

https://streamable.com/o4a3os

compiling with d8d428f will result in the expected behavior, with c3dd1ce5 it will open a new window. I took a quick look at the last 4 commits and I still don't understand why this happens. I'm using the aur package `flameshot-git` and this is the PKGBUILD:
![image](https://user-images.githubusercontent.com/51754973/132985132-6fa9dcce-6a4b-4684-867f-bd0dcf9e2383.png)
I think the `FLAMESHOT_DEBUG_CAPTURE` is off by default and it's not enabled, so this is not debug configuration right?
I believe it only happens with window managers. not sure tho.

System information:-
using archlinux.
no desktop environment. dwm as a window manager.

**Comment by mmahmoudian** [comment]
I cannot reproduce [that effect](https://streamable.com/o4a3os) you showed, but I faced another issue!! when the `flameshot gui` starts, my whole monitor shifts down  and the above half of the screen will be filled with a black color:


https://user-images.githubusercontent.com/390889/132987022-4c7251bc-6ada-4aee-8ad9-39abcfff7064.mp4

My monitor setup in case it is relevant:
![image](https://user-images.githubusercontent.com/390889/132987088-f82a0cfc-d2ad-4227-ba92-17a4540b11b4.png)

**Comment by veracioux** [comment]
#1888 should fix both your issues.

**Comment by mohad12211** [comment]
after some investigations I knew it was a problem in the WM hints and I was wondering why it wasn't applied. your PR fixed it.
