### ISSUE TITLE
Flameshot screenshots entire screen if ctrl+C is hit while using the snipping tool (flameshot gui)

### ISSUE THREAD

**Issue by ManInTheSuit** [flameshot-org/flameshot#1893]
**Flameshot version**
v0.10.1

**Describe the bug**
Flameshot screenshots entire screen if ctrl+C is hit while using the snipping tool (flameshot gui) - what I mean is **while dragging the selection over the screen**, not just "being in flameshot gui".

**To Reproduce**
Start flameshot gui, and when dragging the screenshotting rectangle, press ctrl+C to copy before finishing and voila. 

**Expected behavior**
Nothing or copy the area marked up until that point to clipboard. 

**System Information**
Newest Solus 

***Why is this even reported as a bug?***
Even though it's not a "big" bug, it has caused me to inadvertently copy paste my entire screen to forums/discord instead of the part that I want, causing me to accidentally reveal more information than I wanted to. My fault for not double checking, but I didn't expect it.

**Comment by veracioux** [comment]
#1894 should fix the issue. Please confirm.
