### ISSUE TITLE
Add more colors

### ISSUE THREAD

**Issue by MohamadKh75** [flameshot-org/flameshot#1895]
**Is your feature request related to a problem?**
No

**Description**
Let's have more colors on the wheel! like white, black, or even some RGB or HEX color input!

**Comment by mmahmoudian** [comment]
@MohamadKh75 there is already a button in the color picker that opens the sidebar for you to access the color wheel. Alternatively you can click the "Tool Settings" button or <kbd>Space bar</kbd> to open the sidebar.

![image](https://user-images.githubusercontent.com/390889/133247061-c7ee4e87-588e-4546-b2fa-099ba1117874.png)

**Comment by mmahmoudian** [comment]
Should we close this issue?

**Comment by MohamadKh75** [comment]
Oops! I didn't know that option would do that!
Thanks 😁
