### ISSUE TITLE
Intercept active window

### ISSUE THREAD

**Issue by yinxiulong** [flameshot-org/flameshot#1902]
How to intercept the active window? Instead of choosing your own area！

**Comment by mmahmoudian** [comment]
I assume by "intercept" you mean take a screenshot from. When you run the command `flameshot gui` you will have the option to select the region (of course you can use <kbd>Ctrl</kbd>+ <kbd>a</kbd> to select all of the active monitor), if you want to capture one monitor you can use `flameshot screen` and if you want to capture everything in all monitors you can use `flameshot full`.

**Comment by yinxiulong** [comment]
I just want to select a window, not the whole screen.

**Comment by borgmanJeremy** [comment]
duplicate of #334
