### ISSUE TITLE
Show selection window's position coordinates in addition to its size

### ISSUE THREAD

**Issue by eugenesvk** [flameshot-org/flameshot#1903]
Currently flameshow only shows the size/dimensions of the selection rectangle.
It'd be nice if it would also show the coordinates, e.g. top-left corner of the selection window is at `X,Y`, might be a bubble located at the top-left corner screen
This helps with repeated screenshots, e.g. if you've missed a few pixels in your original selection, you can remember the position of the previous selection and move your new selection to the exact same spot

**Comment by borgmanJeremy** [comment]
This should be added via comments on #2766

**Comment by mmahmoudian** [comment]
I think this is fully implemented in #2766 . I am closing this issue. If you think there is still something missing, please consider re-opening and commenting.
