### ISSUE TITLE
Improvement - Bold Text

### ISSUE THREAD

**Issue by BiLachner** [flameshot-org/flameshot#1912]
To make text and even the numbers in circles better visible, the possibilty to have "bold" text would be nice. Of cause, I can make the text bigger, but sometimes I want smaler and thicker text.

**Comment by mmahmoudian** [comment]
When taking a screenshot, press <kbd>Space bar</kbd> to open the side panel, then select the text tool and start typing. you will see that Italic and Bold are implemented already:
![image](https://user-images.githubusercontent.com/390889/133986514-849a55f6-c889-4f1a-a543-733082a53095.png)

For the "autoincrementing counter bubble", the font size is not adjustable and I personally don't think it is necessary. How strongly do you feel that the numbers should be bolded?

**Comment by BiLachner** [comment]
Okay ... I'm using OpenSuse-Linux ... may be an other version!?
Looks good!

Thanks!

**Comment by mmahmoudian** [comment]
@BiLachner what is your OpenSUSE version? Some of them have pretty old versions. The latest flameshot release is v0.10.1 

![image](https://user-images.githubusercontent.com/390889/134050070-3e969265-0c6f-41e1-839b-c83b7d7c1d12.jpeg)

If your distro does not provide the latest version, you can always use other ways to have the latest Flameshot version on your computer. Just checkout this think:

https://flameshot.org/guide/installation/installation-linux/
