### ISSUE TITLE
There is a delay of about 4 seconds when I try to start screenshot

### ISSUE THREAD

**Issue by syvshc** [flameshot-org/flameshot#1916]
Here is my system info
![image](https://user-images.githubusercontent.com/38098591/134199969-674568d2-97e6-44fb-b4c6-74beeb2fa456.png)

Here is my Flameshot's version, I have to say: this problem appeared at v0.10.1, v0.10.0 and the git version on [AUR](https://aur.archlinux.org/packages/flameshot-git/)

![image](https://user-images.githubusercontent.com/38098591/134270747-b3c26a28-a64c-49c0-a424-276e6385930b.png)

And here is a gif when I try to start it, the delay also exists when I choose a line or pen or something else:
![Peek 2021-09-21 23-28](https://user-images.githubusercontent.com/38098591/134200729-7dfbc056-2c7a-4b82-9185-99b115b157b1.gif)

when I use terminal, the problem still exists

![Peek 2021-09-21 23-42](https://user-images.githubusercontent.com/38098591/134208602-5678c48c-75f3-4efd-88cc-ec1a02a28562.gif)

I remember when I install it the first time on this system, it didn't have this delay. I've tried re-install flameshot but it didn't work, so could anyone tell me  how can remove the delay?

I have tested by re-install flameshot, I found that it starts suddenly when I click the icon or `flameshot gui` in terminal ONLY FOR SEVERAL TIMES SCREENSHOTS AFTER INSTALL. And then the delay began longer and longer, until reach the longest, 4 seconds perhaps. I really confused about this problem.

P.S. English is not my native language, but Chinese is. If there is something I didn't explain well, please ask me straight.

**Comment by syvshc** [comment]
I solve the problem, but I still don't know why. I'll put the procedure below:

1. I first noticed that the shortcut of `Sepctacle` didn't work, see this [link](https://forum.kde.org/viewtopic.php?f=17&t=166079) 
2. I solved `Sepctacle`'s problem by deleting `~/.config/kglobalshortcutsrc` and re-logging in KDE to rebuild this file
3. I found the problem this issue mentioned has been solved together.

**Comment by mmahmoudian** [comment]
@syvshc I don't understand how that cause such issue. Please re-open this issue if the problem occurs again.

**Comment by syvshc** [comment]
OK, the problem occurs again after I reboot my computer... I wounder what caused this problem too. Maybe it is a problem of KDE but not flameshot? I have no idea.

**Comment by mmahmoudian** [comment]
what happens if you delete that file again and reboot?

**Comment by syvshc** [comment]
> what happens if you delete that file again and reboot?

nothing happened, after a little bit long time of starting up the system ( I guess it was generating the `kglobalshortcutsrc` file ) and the delay of flameshot still exists

**Comment by mmahmoudian** [comment]
Thanks for testing. I can't think of any reason from the top of my head that this is happening. Let's see if other devs have any ideas.

**Comment by syvshc** [comment]
> Thanks for testing. I can't think of any reason from the top of my head that this is happening. Let's see if other devs have any ideas.

And thanks for your reply too, I'll see if others have some ideas.:)

**Comment by borgmanJeremy** [comment]
My guess is this is a KDE issue since its related to deleting that file.

**Comment by syvshc** [comment]
> My guess is this is a KDE issue since its related to deleting that file.

I guess so, and I guess the problem may not related with that file straight. Maybe the deletion of the first time changed something by accident.

**Comment by syvshc** [comment]
The problem was gone after this morning's system boot...I guess it may be caused by lots of system cache? I still have no ideas

**Comment by mmahmoudian** [comment]
@syvshc considering that we have not raised any new versions and none of the merged Pull Requests to my understanding has anything to do with this, it might be safe to conclude that this was not Flameshot's bug.

Let's close this and reppen it if needed.

**Comment by syvshc** [comment]
I think I solved the problem! I found that `ballo_file_extractor` takes huge of CPU on my computer. It makes Load Average more than 5, at this time all actions on my computer become slow and have delay. I disabled baloo, and everything becomes fine. :)
