### ISSUE TITLE
Add Drop-Shadows

### ISSUE THREAD

**Issue by claytron5000** [flameshot-org/flameshot#1919]
One problem I have with Flameshot annotations is that they don't always stand out from the background. One solution to this would be to add drop-shadows, or the option to add drop-shadows to annotations.

Simple drop-shadows may be enough, or one could look to Skitch for inspiration and add white outlines + drop-shadows (at least on text).

**Comment by mmahmoudian** [comment]
@claytron5000 isn't this duplicate of #313?

**Comment by claytron5000** [comment]
Yes, it is!
