### ISSUE TITLE
Error Building MacOS BigSur

### ISSUE THREAD

**Issue by claytron5000** [flameshot-org/flameshot#1921]
**Flameshot version**
git commit `7199fd392cdb276f2d4d60bf8717aeb5e2687e67`

**Describe the bug**
When building from source on MacOS BigSur, I encounter the following error:

```
no member named 'MacOSBigSur' in 'QOperatingSystemVersion'
```

**To Reproduce**
Follow the steps in install dependencies:
```
brew install qt5
brew install cmake
```
The build:
```
mkdir build
cd build
cmake ../ -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
make
```

**Expected behavior**
Application builds without error.

**System Information**
MacOS BigSur 11.4
M1 silicon
```
brew list --versions qt@5
qt@5 5.15.2
```

It seems obvious this is a Qt issue, but I'm not sure how to investigate why Qt is missing `MacOSBigSur`

**Comment by claytron5000** [comment]
Just to sanity check I pulled down qtbase, and in `v5.15.2` it is defined 
```
const QOperatingSystemVersion QOperatingSystemVersion::MacOSBigSur = [] {
```

**Comment by borgmanJeremy** [comment]
Okay I actually picked up an M1 Air and its running BigSur. I was able to compile and run flameshot. Perhaps Qt fixed a bug that was preventing this working?

There are still some bugs, but it built properly

**Comment by claytron5000** [comment]
Thanks @borgmanJeremy. Installing `cmake` gave me a point version bump, so maybe that fixed the issue. Either way, closed!
