### ISSUE TITLE
Using shift instead of ctrl to create perfect shapes

### ISSUE THREAD

**Issue by Neykuratick** [flameshot-org/flameshot#1922]
Is there a way to rebind ctrl over to shift for making perfect shapes (e.g circle or square instead of ellipse and rectangle respectively)?

**Comment by mmahmoudian** [comment]
@Neykuratick No those are hardcoded. Of course you can download the source code, modify that bit of the code and compile it yourself.

**Comment by Neykuratick** [comment]
Pretty much yes. Thank you!
