### ISSUE TITLE
“flameshot” app cannot be opened on MacOS

### ISSUE THREAD

**Issue by hui-zheng** [flameshot-org/flameshot#1925]
**Flameshot version**
```
❯ brew info flameshot
flameshot: 0.10.1
https://flameshot.org/
/opt/homebrew/Caskroom/flameshot/0.10.1 (123B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/flameshot.rb
==> Name
Flameshot
==> Description
Screenshot software
==> Artifacts
flameshot.app (App)
```

**Describe the bug**

After a successful installation of flameshot on MacOS using brew, the app can not be opened. it says
```
“flameshot” cannot be opened because the developer cannot be verified.
```
![image](https://user-images.githubusercontent.com/2249215/134819519-7fe229b7-edf3-4d29-beb3-e80ecffc1721.png)

**To Reproduce**

**Expected behavior**
install flameshot 
``` 
brew install --cask flameshot
```

**System Information**
```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

**Comment by borgmanJeremy** [comment]
https://flameshot.org/guide/troubleshooting/#macos

**Comment by mmahmoudian** [comment]
@hui-zheng This is not a Flameshot bug and it is user's responsibility to white-list softwares from MacOS settings. Please follow the link  @borgmanJeremy kindly provided.

I'll close this issue, but if you followed the instructions and still has issues, please reopen this thread.

**Comment by hui-zheng** [comment]
Hi @mmahmoudian , @borgmanJeremy 
I looked at the link provided, which is about to give Flameshot security permissions to "record" your desktop which is for a different issue.

my issue is that the app could not be verified by MacOS to be authentic.

**Comment by hui-zheng** [comment]
I think here is more info about this. https://support.apple.com/en-ca/guide/mac-help/mh40616/mac

**Comment by borgmanJeremy** [comment]
Oh sorry, I should probably add an FAQ for this issue also.

The only way to "solve" this is to pay Apple money for a developer account so I can sign the binary, I don't want to pay Apple :) SignPath donates a certificate so we can sign Windows binaries, but there is no such arrangement with Apple. 

The documentation you linked to should help manually add a security exception.

**Comment by hui-zheng** [comment]
I see. no problem. I understood. 
didn't know that Apple charges you just so that they could verify your signature. 
ok, I will add a security exception.

If you don't mind, may I know how I could verify that the app that I downloaded via `brew install` is indeed the one that you build with code only on this git repo?
I think I am a bit more cautious when it comes to an app like "flameshot" because it could essential "view" and access my whole desktop screen. I just want to take my precaution to make sure I do not download a hacked version

**Comment by borgmanJeremy** [comment]
Thats a really good question. We do not directly maintain the cask that brew installs, but we do post the Mac release and its SHA256 here: https://github.com/flameshot-org/flameshot/releases

The brew script is located here: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/flameshot.rb 

You can see the SHA256 referenced in the brew script matches the SHA256 that we post. To be extra sure you could calculate the SHA256 of the .dmg file that is installed by brew.

**Comment by mmahmoudian** [comment]
@hui-zheng it might surprise you, but a software does not need to have a graphical user interface to record your screen 😉 for example the famous [ffmpeg can easily do that](https://stackoverflow.com/questions/39733635/how-to-capture-a-timed-screen-recording-on-a-mac-with-ffmpeg) which means potentially any software that can open a shell session or even any single bash file can start recording your screen. 

When you use Homebrew in MacOS or AUR in Arch Linux or scoop in Windows, they check the checksum (sha1 or sha256 or etc.) when they download a file but even then you are prune to two possible security issues:
1. Man in the middle attack (either spoofing the recipe or spoofing the checksum)
2. Hash collision 

What I'm trying to say is that security is relative, not absolute. 

Now, if you want to be relatively safe and paranoid as I am for many software, you can create a small bash/zsh file to either download the .dmg and checksum from our GitHub and install that if the checksum matched, or clone the repo and compile it on your computer. Of course the former is much easier than the latter as you don't have to deal with dependencies during the compile time, but the former is slightly more secure as for any attack they should change the git history on the fly.

**Comment by dandv** [comment]
> The only way to "solve" this is to pay Apple money for a developer account so I can sign the binary, I don't want to pay Apple :)

Is that $99?

Would you accept donations?

**Comment by mmahmoudian** [comment]
@dandv 

> Would you accept donations?

No. This is explained here: https://flameshot.org/donate/

> Also, the troubleshooting link is broken.

Please try this: https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by dandv** [comment]
> @dandv
> 
> > Would you accept donations?
> 
> No. This is explained here: https://flameshot.org/donate/

Would a Developer account qualify as an indirect donation?

> > Also, the troubleshooting link is broken.
> 
> Please try this: https://flameshot.org/docs/guide/troubleshooting/#macos

Thank you. I can't find an answer among those 3 that talks about the inability to install on MacOS. Either way, can you please update the link at https://github.com/flameshot-org/flameshot/issues/1925#issuecomment-927372837 for others who arrive at this issue?

**Comment by mmahmoudian** [comment]
> Would a Developer account qualify as an indirect donation?

Can you elaborate more? Perhaps this can be discussed in a dedicated Github discussion or on the dev room on our Matrix space (both will be publicly accessible)

**Comment by iddqdiddqd** [comment]
Troubleshooting documentation has been filled out with the solution to this issue in https://github.com/flameshot-org/flameshot-org.github.io/pull/151
