### ISSUE TITLE
change flameshot notification

### ISSUE THREAD

**Issue by wael444** [flameshot-org/flameshot#1927]
a very aesthetically insignificant 'enhancement' to be able to change the flameshot notification message
>**Flameshot info**
>Capture saved to clipboard. Capture saved as <directory, image>

to something like using %F as file, etc

**Comment by wael444** [comment]
> a very **aesthetically insignificant** 'enhancement'

what i mean is instead of showing 
![image](https://user-images.githubusercontent.com/47404953/135097504-3457be26-5f33-4b6a-8ffa-258e5ce4eb5f.png)
you could be able to change the norification to something similar to
![image](https://user-images.githubusercontent.com/47404953/135097812-1aa27af6-6db2-42c5-9b02-6353ff86dbd1.png)
or to generally be able to customize it from `flameshot config` 

note: this is PURELY for aesthetic reasons.

**Comment by mmahmoudian** [comment]
@wael444 ok, thanks for the elaboration. I marked it as visual enhancement. Let's see how much traction and response it will get from the community.

**Comment by wael444** [comment]
I'll change the code myself to make it display what I want since this a one man issue, sorry for wasting your time.

**Comment by mmahmoudian** [comment]
@wael444 any suggestion is always welcome.
