### ISSUE TITLE
Take screenshot of other screen not working

### ISSUE THREAD

**Issue by dannykorpan** [flameshot-org/flameshot#1932]
Flameshot version
Flameshot v0.10.1 (4e406ec)
Compiled with Qt 5.15.2
OS macOS 11.6 (arm64)
System: Kernel: Darwin 20.6.0 arm64 bits: 64 compiler: clang v: 13.0.0 Console: tty s000 OS: Darwin 20.6.0 

Describe the bug
When trying to take a screenshot of a second or third screen using flameshot, only the primary screen is selected and flameshot active.

To reproduce
- connect a second screen
- start flameshot from macOS menubar from the second screen

Expected behavior
Flameshot starts on the second screen and you can normally take a screenshot.

**Comment by mmahmoudian** [comment]
Have you tried to see if after connecting the second monitor, closing Flameshot completely (right-click on the tray icon and clicking on Quit) and then starting Flameshot would solve the problem or not?

**Comment by dannykorpan** [comment]
With a completely restart of Flameshot after connecting the second monitor, it's working. But I have always restart Flameshot after connecting a second monitor.

**Comment by mmahmoudian** [comment]
@dannykorpan so my guess was correct that the state of your monitors are not updated for Flameshot when a new monitor is attached. How do you connect the monitor? Through Thunderbolt or USB-C?

**Comment by truefan4ever** [comment]
The same issue

**Comment by dannykorpan** [comment]
For me it's now working with the latest beta of V11. Anybody can confirm this?

**Comment by borgmanJeremy** [comment]
@dannykorpan even if you attach the second monitor after starting flameshot?

**Comment by dannykorpan** [comment]
> @dannykorpan even if you attach the second monitor after starting flameshot?

Yes

**Comment by Marcosaurios** [comment]
I'm experiencing the same issue here. Also when I'm in the second screen and I want to take a screenshot, Flameshot creates a new empty Virtual Desktop window, not letting me to capture what I wanted.

**Comment by mmahmoudian** [comment]
@Marcosaurios Have you given Flameshot proper permissions? https://flameshot.org/docs/guide/troubleshooting/#macos It is a known issue with macOS that the permissions does not get transferred to the new version of the same software, therefore you have remove the permission, then give the permission again and restart you macOS (I don't know why restart is needed, but everyone have reported that without restart the permission is not applied)

**Comment by Marcosaurios** [comment]
> @Marcosaurios ... remove the permission, then give the permission again and restart you macOS ...

That made the trick and allowed me to use Flameshot on both screens successfully. Thank you so much :)
