### ISSUE TITLE
Suggestion: Add a --wait flag to flameshot gui

### ISSUE THREAD

**Issue by dorian-marchal** [flameshot-org/flameshot#1935]
**Is your feature request related to a problem?**

Yes, after taking a screenshot, I would like to open my file manager to the screenshot location.

**Suggestion:**

Add a `--wait ` flag to `flameshot gui` to make the command return only when the screenshot has been saved (or the capture canceled).

This way, I could do this:

```
flameshot gui --wait && xdg-open ~/Pictures
```

It would be extra nice if `flameshot gui --wait` would only return 0 when a screenshot has been saved (and not dismissed).

Also, thanks for this tool, it is great and the UX is top notch. :+1:
I'd \*love\* a user friendly tool like that for screencasts. :)

**Comment by mmahmoudian** [comment]
@dorian-marchal thanks for the feature request, but I'm struggling to understand this: waiting for what? Clearly you don't mean something equivalent to `sleep`, but I'm puzzled about what Flameshot should wait for.

**Comment by dorian-marchal** [comment]
It should wait for either:
- the screenshot being saved (in this case the command status code would be 0)
- the UI being closed (escape or cross button), in this case the status code would be != 0)

Basically, I would like `flameshot gui --wait` to return once its GUI has been closed but not before.

**Comment by mmahmoudian** [comment]
After reading your [comment in the other issue](https://github.com/flameshot-org/flameshot/issues/1072#issuecomment-932828530) I think I now understand what you mean. All `flameshot gui` does is to trigger a DBus call to the main Flameshot process that is running in the background, therefore in your case the `flameshot gui` successfully did the job of creating the DBus call and your shell jumped to the next part after `&&`. I don't know even if such thing that you suggested is possible because of what `flameshot gui` do. I can see how this is inconvenient for scripting, I just don't know what the best solution can be.

**Comment by mmahmoudian** [comment]
@borgmanJeremy @veracioux I wonder if `flameshot gui` can wait for a response from the main process. I mean if Flameshot daemon can send back the status (success, fail) to DBus and the `flameshot gui` reads it?

**Comment by dorian-marchal** [comment]
OK, I understand. For my specific use case, a single "open screenshot folder after save" in the settings would do the job, though.

**Comment by veracioux** [comment]
@dorian-marchal As a temporary workaround, you could use `flameshot gui -r >/dev/null`. Note that this does not return the correct exit code in all cases.

@mmahmoudian
> @borgmanJeremy @veracioux I wonder if `flameshot gui` can wait for a response from the main process. I mean if Flameshot daemon can send back the status (success, fail) to DBus and the `flameshot gui` reads it?

Yes it can. After all, that's what `flameshot gui -r` does. But personally, I would be a bigger fan of taking the screenshot without using DBus at all.

@borgmanJeremy For some time I have been thinking about a non-dbus interface for flameshot. The only reasons for DBus I can think of are for flameshot to react to hotkeys and to keep widgets open after the capture gui closes. Other than that, it just complicates things.

**Comment by dorian-marchal** [comment]
> @dorian-marchal As a temporary workaround, you could use flameshot gui -r >/dev/null. Note that this does not return the correct exit code in all cases.

Thanks @veracioux , that's close to what I would expect from a `--wait` flag, indeed :+1:
This seems to work just fine:

```shell
#!/usr/bin/env bash

screenshot_directory="/home/dorian/Pictures/"

flameshot gui --path "$screenshot_directory" -r > /dev/null

screenshot_path=$(find "$screenshot_directory" -type f -newermt `date --date='1 second ago' +%Y-%m-%dT%H:%M:%S` | head -n 1)

if [ -n "$screenshot_path" ]; then
    nautilus "$screenshot_path"
fi

```

Out of curiosity, when does the exit code is not correct?

**Comment by veracioux** [comment]
@dorian-marchal For example if you press the save button and then exit the save dialog, it will return 0. This might be a bug actually.

**Comment by borgmanJeremy** [comment]
@veracioux DBUS is more of an implementation detail than a hard requirement. I already want to restructure the CLI parsing away from DBUS so it works on mac and windows.

If we can remove DBUS and meet the requirements we have today I see no issues. Somethings listed below need to be reimplemented. 

1. Have a global hotkey
2. Parse CLI arguments
3. Prevent duplicate instances of flameshot (suppose this is a nice to have)

**Comment by borgmanJeremy** [comment]
I believe this is all working properly now in version 11.
