### ISSUE TITLE
Selection would shift when changing color with right mouse button

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#194]
![peek 2018-04-20 23-13](https://user-images.githubusercontent.com/8443926/39059265-990c7e9e-44f0-11e8-8a67-e38450d6fde0.gif)

Please see the screencast above; I think it should be a bug.

**Comment by ZetaoYang** [comment]
@hosiet Yes, I found this bug too. When the selection window is moved to the upper left or lower left corner of the screen, the mouse becomes a hand shape, but the mouse shape is still in the hand when moving to other positions.

**Comment by lupoDharkael** [comment]
@hosiet please, explain the process to reproduce, I can't with the actual master branch.

@ZetaoYang does it happen in master?

**Comment by hosiet** [comment]
1. Trigger flameshot
2. Make a selection
3. Press right mouse button and hold it; the palette will pop out around the cursor
4. Move the mouse onto any color circle
5. Release the right mouse button

Now, the selection will shift and this shift is the bug.

* * *

But wow, I tested with git HEAD and the problem seems disappeared. @ZetaoYang can you confirm with this?

**Comment by lupoDharkael** [comment]
After looking at your video I see the size of the buttons is quite large. I resize the buttons at runtime based on the font metrics, a button like the Size Indicator needs to have enough space to show the text with the size. For some reason it gets large with your font.
Please @hosiet, open an issue so we can track this problem.
