### ISSUE TITLE
Add black and white as default-color

### ISSUE THREAD

**Issue by xstable** [flameshot-org/flameshot#1942]
Would be great if black and white would be always there for the default-colors... without the need to add them to the ini-file.

**Comment by xstable** [comment]
If that customized colors stays there, and didn't need to be re-choosed any time, it would be the perfect solution.

**Comment by tecosaur** [comment]
> Would it be enough if the color-wheel (right-click color menu) could be also customized visually in the configuration window?

This is quite funny, I was about to make an issue about customising the colours available, and I see this. Just to add my 2c, I'd absolutely love to be able to (persistently) set the colours. If it's not too difficult, I think it would also be good to make the number of colours customisable.

**Comment by borgmanJeremy** [comment]
I like your idea with the wheel! lets settle on that for the requirements.

**Comment by mmahmoudian** [comment]
@xstable In my sketch, the + button was meant to add a new circle into the mix:

![image](https://user-images.githubusercontent.com/390889/136354087-1278658b-e21c-4690-a35b-eac76ce3569c.png)

**Comment by veracioux** [comment]
@mmahmoudian Then we can put this widget under the "Color-wheel" tab.

**Comment by borgmanJeremy** [comment]
> How about this? A bit more work to implement, but it looks better. ![sketch](https://user-images.githubusercontent.com/29044423/136611557-0d281233-02eb-4a9c-823a-5b5e568db9e8.png)
> 
> Ignore the design of the "+" button. Expanding on @xstable's suggestion, a spin box can also be added so you can pick a preset. Inside the spin box, a "+ new preset" should also be added to create a new preset. And a "remove" button right beside the spin box to remove a preset.

FYI I started implementing it this way and it was kinda a pain, so I went back to a simple table for now. If we ant to move it to a circle later all the "plumbing" will be there.

To do it the right way I wanted to refactor the colorpicker and colorwheel classes to make them a bit more generic.

**Comment by deo002** [comment]
I would like to tackle this issue.
