### ISSUE TITLE
Leading `#` turnes to `%23` in config file

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1943]
**Flameshot version**
Flameshot v0.10.1 (aca0db96)
Compiled with Qt 5.15.2
linux: 5.10.68-1-MANJARO

**Describe the bug**

When commenting a line in the config file and after running `flameshot gui` once, the config file will be automatically sorted and (this is expected as we discussed before) and the `#` would turn into it's hex code (`%23`). I believe it is confusing for the user and also this will break syntax highlighting of any texteditor.

**To Reproduce**
1. `flameshot`
2. Add a `#` to the begining of a line in the config file
3. `flameshot gui`
4. get out of Flamehsot (cancel or capture)
5. check the config file again

**Expected behavior**

I expect the `#` to stay as the same character.

**System Information**

> ```
> System:
>   Host: precisiontower Kernel: 5.10.68-1-MANJARO x86_64 bits: 64 
>   Desktop: KDE Plasma 5.22.5 Distro: Manjaro Linux 
> Graphics:
>   Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel 
>   Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel 
>   Display: x11 server: X.Org 1.20.13 driver: loaded: amdgpu,ati,modesetting 
>   resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz 
>   OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.40.0 
>   5.10.68-1-MANJARO LLVM 12.0.1) 
>   v: 4.6 Mesa 21.2.2 
> ```

**Comment by veracioux** [comment]
This is unfortunately the behavior of QSettings. But I have an idea on how to make this work so I'll look into it and let you know.

**Comment by mmahmoudian** [comment]
@veracioux Should I mark this as "bug" or "enhancement"?

**Comment by veracioux** [comment]
@mmahmoudian Definitely "enhancement" since INI files use `;` for comments by default.

**Comment by veracioux** [comment]
@borgmanJeremy I'm working on custom read and write functions for QSettings which should solve this issue.

I don't think we should switch to TOML. TOML is very similar to INI and flameshot's config is not very complex, so I don't see any advantage. And I hate to involve 3rd party libraries unless necessary.

**Comment by mmahmoudian** [comment]
@kpcee the original post stemmed from a mistake of mine that I thought in INI files lines leading with # are comments.

-------

@veracioux & @borgmanJeremy 
Personally I believe comments and order of lines are important and if QSettings cannot properly handle it, regardless or being used by the whole world or a single  application, it has pitfall.

All that said, regardless of what I believe to be "correct", I acknowledge that I'm not C++ savvy enough to know what are the implications of manual mending this bad behaviour, so I'll be fine with any solution that works and is easy to implement for you devs. Therefore, I'm fine with what you all are fine with 👍🏼
