### ISSUE TITLE
Flameshot does not properly handle QT_SCALE_FACTOR

### ISSUE THREAD

**Issue by CocaineJohnsson** [flameshot-org/flameshot#1947]
**Flameshot version**
$ flameshot --version
Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**

An picture says a thousand words

EDIT: Offset not preserved in final screenshot, had to replace with photos of screen(s)

![20211007_102718](https://user-images.githubusercontent.com/53689060/136348213-6930370b-0fe2-4869-97b2-9f4a80d699ad.jpg)
![20211007_102711](https://user-images.githubusercontent.com/53689060/136348234-7dedf310-9cc0-4ab3-8242-6c3313752b21.jpg)

Additionally while investigating I found a rendering bug with the blur tool (and probably others) where if you blur over the offset it'll just stretch whatever you were blurring into it, this is demonstrated in a photo

With a QT_SCALE_FACTOR greater than 1.0 (*required* as an environment variable because QT doesn't handle 4K and various applications have UI breakage when it's not set -- it's also useful to control ui element size even for applications that handle it correctly) the entire screen shifts left by a scale factor dependent amount of pixels (in % above 1.0, a factor of 2.0 would shift by a full screen), this makes it impossible to screenshot anything near the edge of the screen.

**To Reproduce**
4K may be necessary.
multi-monitor may be necessary.

export QT_SCALE_FACTOR, and start flameshot 

use flameshot gui, observe the offset.

higher values produce a more dramatic result (each number past 1.0 seems to correlate to a full screens worth, which makes intuitive sense, 1.9 is 90% of a screen width offset)

**Expected behavior**
The screen should not offset since this makes it hard to screenshot things and cuts off windows

**System Information**
Arch Linux 5.14.9-arch2-1 
Nvidia proprietary 470.74
Bspwm 0.9.10

**Comment by CocaineJohnsson** [comment]
The obvious workaround is just to start flameshot as such:

QT_SCALE_FACTOR=1.0 flameshot 2>&1 </dev/null &


But that doesn't fix the issue, that just bypasses it temporarily.

**Comment by borgmanJeremy** [comment]
Not that I've discovered. You can read in detail here where I first started posting details: https://github.com/flameshot-org/flameshot/issues/564#issuecomment-727297870
