### ISSUE TITLE
Support for export actions from CLI

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1956]
I would like to complement the existing CLI options `-p, -c, -r, -g` to `flameshot gui/screen/full` with the following options:

- `--pin`, ~`-P`~; When the screenshot is accepted, pin screenshot. [#1834](#1834)
- `--upload`, `-u`; When accepted, upload to imgur
- `--accept-on-select` ~`--done-on-select`~, `-s`; Accept the capture as soon as a selection is made (on mouse release). [#642](#642)

To understand what I mean by **accept**, please look at #1955.

Note: Maybe the pin option should not be available in `flameshot full`. It could have weird behavior. Thoughts?

Please let me know what you think about these options. Do you have additional suggestions?

Another thought I'd like to drop here:
We could merge `--path` and `--raw` into a single `--output/-o` option. When used as `--output -` or `-o -` it should behave exactly as `--raw`. Otherwise it should behave the same as `--path`. This is more in line with the usual behavior of CLI programs. And it would allow `--pin` to be shortened to `-p`.

**Comment by mmahmoudian** [comment]
@veracioux I think there are two issues with the pin:
1. We use `-p` for path and now using `-P` would be very confusing. (Perhaps `-i`?)
2. The pin only make sense for `flameshot gui` and not the `flameshot screen` or `flameshot full`

Also, imho the capture on mouse release would only make sense for `flameshot gui` too.

About the `--output -`, I wonder if at the moment one can chain `--raw --path` and get the screenshot saved and sent to stdout simultaneously. If it is possible, I think the `--output` would break an existing "feature".

**Comment by veracioux** [comment]
@mmahmoudian 
> 1. We use `-p` for path and now using `-P` would be very confusing. (Perhaps `-i`?)

I'd prefer to reserve `-i` for specifying an input image if we decide to implement that feature in the future (there have been some issues discussing this). I'd like to leave out a short option for `--pin` for the time being.

> 2. The pin only make sense for `flameshot gui` and not the `flameshot screen` or `flameshot full`

I think `flameshot screen --pin` could be useful. For example, you can take a screenshot of one screen and put it on another screen. Maybe you want to compare something or just fool someone about the contents of your other screen.

> Also, imho the capture on mouse release would only make sense for `flameshot gui` too.

Of course, silly me :)

> About the `--output -`, I wonder if at the moment one can chain `--raw --path` and get the screenshot saved and sent to stdout simultaneously. If it is possible, I think the `--output` would break an existing "feature".

Yeah, you can use both `--raw` and `--path` at the same time. You have changed my mind about this.

I will change `--done-on-select` to `--accept-on-select` to prevent confusion.

**Comment by veracioux** [comment]
> Can't it be done by piping the raw into feh or sxiv?

Of course it can. But it is not always positioned exactly where the screen is, unlike the `--pin` option.
