### ISSUE TITLE
Windows 11: "Print Screen"-button do not work...

### ISSUE THREAD

**Issue by mkikets99** [flameshot-org/flameshot#1961]
**Flameshot version**
v0.10.1 (4e406ec)

**Describe the bug**
Pressing "Prt Sc" on Windows 11 calls windows standard printscreen saving function.
(Right click on "Create screenshot" in context menu does work as expected)

**To Reproduce**
Install windows 11, install Flameshot from github and test "Prt Sc"

**Expected behavior**
Flameshot called to take screenshot

**System Information**
Windows 11 (22000.194)

**Comment by borgmanJeremy** [comment]
Can this be closed since a MS update solved the problem? 

Unfortunately I can't test this either. I haven't been able to get Windows 11 working in a VM yet.

**Comment by andyfore** [comment]
Has someone verified that a Windows Update fixed it?  My comment was indicating that it didn't start until after those two updates were applied.  There have been no more updates issued for Windows 11 since those two that I am aware of for the GA release.

**Comment by mkikets99** [comment]
Yup... seems like 22000.256 is working normal again

**Comment by andyfore** [comment]
> @mkikets99 I am running 22000.258 and it is not normal.

Actually, what I mean by not normal is "inconsistent" behavior.  Sometimes the flameshot app comes up with the Printscreen key and sometimes I get the standard windows behavior.

**Comment by mkikets99** [comment]
> @mkikets99 I am running 22000.258 and it is not normal.

Did you checked all updates in `Windows Update Center`?

Cause i update all packages on windows 11 and even checked for possible updates on `flameshot`... And with 22000.258 it's working smoothly...

I will check if something from cumulative updates something break...

**Comment by ampcpmgp** [comment]
I'm having this problem too.

**Comment by mmahmoudian** [comment]
@andyfore & @ampcpmgp we released a new stable version less than 12 hours ago (v11.0) please try that as it has undergone massive code refactoring and comes with tons of bug fixes and packed with tons of new features.

Please open a new issue if the problem still exists with this new version and please also mention this issue in the description as well. Thanks.

**Comment by CrypticVader** [comment]
> Still getting very inconsistent behavior with this. Sometimes when I reboot it works, sometimes the Printscreen button activates the default Windows behavior.

Same, here it works at times, Win 11 22000.466
Flameshot v11.0.0 (ad1bf28)

**Comment by borgmanJeremy** [comment]
I don't think any of our devs have a windows 11 pc or VM due to the TPM requirement.

We likely need help from the community to fix this.

**Comment by mkikets99** [comment]
> I don't think any of our devs have a windows 11 pc or VM due to the TPM requirement.
> 
> We likely need help from the community to fix this.

Hmm... you might just need to somehow get a ISO for VM with Win11 on Win10 installation....
You need help with that? Because i already installed win 11 on 2 laptops without TPM Requirements...

**Comment by borgmanJeremy** [comment]
I'm mostly waiting for it to work out of the box with quick emu. Last I tried it didn't work and there are many other flameshot bugs I can easily triage 😁

**Comment by borgmanJeremy** [comment]
I upgraded to windows 11 and flameshot is working fine for me. (needed to enable TPM in my BIOS)

**Comment by mmahmoudian** [comment]
@omaru-ok have you read #1861?

**Comment by omaru-ok** [comment]
yep  i do 
 buts its not usefull u  need another app to change hot-key is not good :(

**Comment by mmahmoudian** [comment]
@omaru-ok No, you don't need another software. It is done with Windows. This is a screenshot from [the link I shared there](https://www.popsci.com/story/diy/custom-keyboard-shortcuts-windows/) :

![image](https://user-images.githubusercontent.com/390889/185633377-eabbcffd-e1cf-4908-96d5-cf0a72ecfe0d.png)

**Comment by omaru-ok** [comment]
omg that is good 


:O

**Comment by sainitush** [comment]
I am having the same issue with the latest version, Flameshot v12.1.0 in windows 10. When I press printscreen button, my windows snipping tool opens up. I tried to disabling it and then when I press the prtscreen button it says that I have disabled the software bla bla. So basically my prntscreen button is not assigned to flameshot. I am also not even to assign printscreen from properties to flameshot as it opens up the dialog box that has the message that i have disabled the snipping tool.

**Comment by an1msh** [comment]
I uninstalled the snipping tool from the "Installed Apps" in Windows 11. I followed it up by disabling the "Use The Print Screen key to open Snipping Tool". Now the print screen opens up Flameshot! I had also done the "DisableSnippingTool" in [regedit](https://www.youtube.com/watch?v=1mXsfgqmG3I). Not sure exactly what made it work, but its working now.

**Comment by dev-vitor-gabriel** [comment]
> Desinstalei a ferramenta de recorte dos "Aplicativos instalados" no Windows 11. Em seguida, desabilitei a opção "Usar a tecla Print Screen para abrir a Ferramenta de recorte". Agora a tela de impressão abre o Flameshot! Eu também fiz o "DisableSnippingTool" no [regedit](https://www.youtube.com/watch?v=1mXsfgqmG3I) . Não sei exatamente o que fez funcionar, mas está funcionando agora.

Resolveu meus problemas, depois de remover o app de captura e desmarcar a opção de captura de tela, apenas precisei reiniciar o flameshot

**Comment by Nergy101** [comment]
Thanks @an1msh !

Following that YT tutorial for the regedit, uninstalling Snipping Tool and disabling that "Print Screen key"-setting, did the job for me.

**Comment by jinmiaoluo** [comment]
‌‌If you are using the latest Windows 11 operating system, you can disable the PrtSc binding in settings.
![image](https://github.com/flameshot-org/flameshot/assets/39730824/a334dc29-e580-49c7-be0a-a30a2fb3c1f7)

**Comment by yjerez** [comment]
This works for me.

**Comment by JoaquinSM13** [comment]
What happens if i dont want to uninstall Snipping Tool cause its helps with screen recording now? Is there a way to modify the button in flameshot configuration?
