### ISSUE TITLE
macOS app has outdated version information.

### ISSUE THREAD

**Issue by vitorgalvao** [flameshot-org/flameshot#1973]
**Flameshot version**
[0.10.1](https://github.com/flameshot-org/flameshot/releases/tag/v0.10.1)

**Describe the bug**
To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

In flameshot, [the former is fixed at `0.8.5`](https://github.com/flameshot-org/flameshot/blob/dabc596566c60378f313d26f2fe143d2a37ede5b/cmake/modules/MacOSXBundleInfo.plist.in#L25L26) and [the latter is empty](https://github.com/flameshot-org/flameshot/blob/dabc596566c60378f313d26f2fe143d2a37ede5b/cmake/modules/MacOSXBundleInfo.plist.in#L21L22).

If they’re not set during the build process, they can be changed after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. Technically they should be different, but that’s a secondary concern. An accurate version number is important for macOS to know which app to open in ambiguous situations; for users who expect the information available via the Finder; and for interoperability with other apps.

**To Reproduce**
Select the app in the Finder and do <kbd>⌘</kbd><kbd>I</kbd> (Get Info). Note the version field is `--`.

Alternatively, verify the contents of `Info.plist` as indicated above.

**Expected behavior**
Version should be in line with release.

**System Information**
macOS (any version)

**Comment by borgmanJeremy** [comment]
I fixed this in #1987 . Does that look okay to you?

I also updated the releasing documentation so I remember to do it each release.
