### ISSUE TITLE
Autostart doesn't work on NixOS

### ISSUE THREAD

**Issue by yizhepku** [flameshot-org/flameshot#1975]
**Flameshot version**
Tested on both master and v0.11.1

**Describe the bug**

Autostart doesn't work.

On NixOS, if the directory `~/.config/autostart` doesn't exist, Flameshot will try to write the desktop file to somewhere in `/nix/store`. However, `/nix/store` is read-only, so that fails.

**To Reproduce**

Install Flameshot on NixOS. Launch it with `strace flameshot 2>&1 | grep open` so that we can observe where it tries to write files. When flipping `Launch at startup` in configuations, strace will print some like this:

```
openat(AT_FDCWD, "/nix/store/nkgiwqxc5i6fhkzm4lj8p11gjpclm5cj-plasma-workspace-5.21.5/etc/xdg/autostart/Flameshot.desktop", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 EROFS (Read-only file system)
```

**Expected behavior**

The desktop file should be written to `~/.config/autostart`, creating the directory if necessary.

**System Information**

NixOS 21.05

**Comment by YizhePKU** [comment]
The buggy code is in `src/utils/confighandler.cpp`, function `ConfigHandler::setStartupLaunch`.

```
    QString path = QStandardPaths::locate(QStandardPaths::GenericConfigLocation,
                                          "autostart/",
                                          QStandardPaths::LocateDirectory);
    QDir autostartDir(path);
    if (!autostartDir.exists()) {
        autostartDir.mkpath(".");
    }

    QFile file(path + "Flameshot.desktop");
```

I think `QStandardPaths::locate` prefers existent path to writable path. My suggested fix is:

```
    QString path = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    QDir autostartDir(path);
    if (!autostartDir.exists()) {
        autostartDir.mkpath(".");
    }

    QFile file(path + "/autostart/Flameshot.desktop");
```

**Comment by YizhePKU** [comment]
I tested my solution locally and it works nicely. Didn't run the test suite though, this should be fine?
