### ISSUE TITLE
Flameshot daemon creates `~/.config/flameshot/flameshot.conf`

### ISSUE THREAD

**Issue by veracioux** [flameshot-org/flameshot#1980]
**Flameshot version**
Flameshot v0.10.1 (dabc5965)
Compiled with Qt 5.15.2

**Describe the bug**
Flameshot uses `~/.config/flameshot/flameshot.ini` for storing the configuration. When the daemon launches, it creates a `~/.config/flameshot/flameshot.conf`. This file is always empty and is unused by flameshot.

**To Reproduce**
Launch the daemon by just running `flameshot`. Look inside `~/.config/flameshot/`.

**Expected behavior**
Do not create this file.

I suspect the issue is caused by `QSettings` being used somewhere before the config format is set. The format is initialized as `INI` in this line of code:
https://github.com/flameshot-org/flameshot/blob/dabc596566c60378f313d26f2fe143d2a37ede5b/src/utils/confighandler.cpp#L167

**System Information**
Arch Linux
WM: i3wm, X11
kernel: 5.13.13-arch1-1

**Comment by mmahmoudian** [comment]
I was actually wondering if some of my wrapper scripts are creating it.

**Comment by veracioux** [comment]
@AdavisSnakes You are right. I just tested it on Windows 10, no conf file is created.

**Comment by veracioux** [comment]
@borgmanJeremy Thanks, I think I managed to fix it. Will push soon.

**Comment by veracioux** [comment]
@borgmanJeremy @mmahmoudian Please see if #1972 fixes it.
