### ISSUE TITLE
Zoom and/or Resize

### ISSUE THREAD

**Issue by ambuddy** [flameshot-org/flameshot#1994]
Please make feature to Zoom In like Magnifying Glass or make additional tool in Editing mode to resize screenshot. Almost that I looking for is Pinning screenshot to Desktop what can be zoomed in, but I need to view particular pixels of screenshot and not blured zoomed image.

OS: Ubuntu 20.04

**Comment by ambuddy** [comment]
Hi, @veracioux. Sorry for bothering you, but can you explain how to get this feature in Flameshot? Can I download a build or so for my Ubuntu 20.04 from somewhere?

**Comment by veracioux** [comment]
@ambuddy No bother at all. You can download the latest development packages from [here](https://flameshot.org/nightly).
