### ISSUE TITLE
Feature request: Show selection size when resizing

### ISSUE THREAD

**Issue by ElEd0** [flameshot-org/flameshot#2006]
Hi, really like the tool, but something I miss is the ability to see the exact size of the screenshot when resizing the selection, like lightshot does. Right now you can see the selection size in one of the bubbles, which is great, but these bubbles hide when you are resizing the image, which makes it a bit annoying when you want to pinpoint a screenshot of an exact size, say 512x512 for example (I do this quite often). Maybe you could add an option to keep this bubble while resizing or something like that.

**Comment by mmahmoudian** [comment]
@ElEd0 Shall we close this then in favor of #1903 or there are more to be added?

**Comment by ElEd0** [comment]
> @ElEd0 Shall we close this then in favor of #1903 or there are more to be added?

Closed it myself ;)
