### ISSUE TITLE
Semantic error in 'setSaveAsFileExtension'. Expected: supported image extension

### ISSUE THREAD

**Issue by teaper** [flameshot-org/flameshot#2009]
OS：Arch Linux
Desktop：gnome
Flameshot version：Flameshot v0.10.1 (067f4a19)
Compiled with Qt 5.15.2

![2021-10-27_01-17.png](http://tva1.sinaimg.cn/large/006kWbIoly1gvt7yssxyxj30hh08bt9v.jpg)

**Comment by borgmanJeremy** [comment]
Did this resolve the issue?

**Comment by McStecca** [comment]
It worked for me

**Comment by PrakashLakhara** [comment]
Copy on the clipboard is not working after commenting the line @veracioux

**Comment by veracioux** [comment]
@PrakashLakhara Can you post the contents of `~/.config/flameshot/flameshot.ini.bak` here?

**Comment by PrakashLakhara** [comment]
> @PrakashLakhara Can you post the contents of `~/.config/flameshot/flameshot.ini.bak` here?

Yes, but the full commented line I removed from that before some days. Pasting below: Strange thing is the new config file was empty after reinstallation yet flameshot is working.
```
[General]
contrastOpacity=188
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=1
ignoreUpdateToVersion=0.10.0
savePath=/home/prakash/Pictures
savePathFixed=false
showStartupLaunchMessage=true
startupLaunch=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Comment by mmahmoudian** [comment]
@PrakashLakhara 

> Strange thing is the new config file was empty after reinstallation yet flameshot is working.

If I understand you correctly, you are wondering why Flameshot works properly even when there is no config file or when the config file is empty. The reason is that Flameshot has a default config which will be overwritten by the items user's config file.
