### ISSUE TITLE
Eraser + (ctrl+A) + ability to change default tool after this app appears

### ISSUE THREAD

**Issue by 174n** [flameshot-org/flameshot#202]
It would be great to have an eraser like in lightshot so I can erase things if I made a typo or something.
Also the ability to write straight after you click the print screen button and make fullscreen screenshot after CTRL+A would not hurt

**Comment by Maralai** [comment]
It would be nice if the app could recognize a stylus eraser button press with any erase feature.

**Comment by tsids** [comment]
Hi, when will the eraser feature be added? It's been 5 years...
@borgmanJeremy or any other developer

**Comment by mmahmoudian** [comment]
@tsids 

> Hi, when will the eraser feature be added? It's been 5 years...

This is already in a way implemented. You can de-select the active tool, then click on the object you want to delete, and press delete button on your keyboard. By selecting the object you can also move, change size, and change color.

-------

I'm going to close this issue for three reasons:
1. For making a typo, it is possible to double-click and edit the text
2. For other mistakes, the object can be modified and also deleted and created again
3. The "like in lightshot" is vague and I personally don't know what type of eraser the OP intended
