### ISSUE TITLE
weird zoom behaviour if a pinned image

### ISSUE THREAD

**Issue by RusackN1** [flameshot-org/flameshot#2021]
**Flameshot version**
v0.10.1 (4e406ec)

**Describe the bug**
After pinning the image, everything is fine, it's movable and stays on top. But as soon as I try to zoom it, it acts weirdly (random + or -, pinch doesn't work, only 2-finger scroll)

**To Reproduce**
pin a screenshot and try to zoom it on M1 Macbook pro 13, 16gb, 512

**Expected behavior**
Pinch-to-zoom or scroll up/down should make the pinned image bigger or smaller

**System Information**
macOS 12.0.1

**Comment by mmahmoudian** [comment]
I think Pinch-to-zoom is something that should be implemented and QT does not translate the gesture to scroll.

@RusackN1 Would it be possible to record a short video from your screen to show this behavior. You can use Quicktime that is shipped with your MacOS: 
https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac

**Comment by borgmanJeremy** [comment]
I've replicated this. Pinch does nothing and scrolling only makes it smaller.

**Comment by borgmanJeremy** [comment]
https://doc.qt.io/qt-5.12/qtwidgets-touch-pinchzoom-example.html

**Comment by borgmanJeremy** [comment]
@AndreaMarangoni okay cool. I was looking into this a bit last week and I think the best way to fix it is to implement the zoom gesture event: https://doc.qt.io/qt-5/qtwidgets-gestures-imagegestures-example.html

**Comment by AndreaMarangoni** [comment]
> @AndreaMarangoni okay cool. I was looking into this a bit last week and I think the best way to fix it is to implement the zoom gesture event: https://doc.qt.io/qt-5/qtwidgets-gestures-imagegestures-example.html

Sounds good!

**Comment by AndreaMarangoni** [comment]
@borgmanJeremy I was wondering: do we want to leave the current behaviour for mac platform (so scrolling and pinching will zoom the pinned image)? or do we want to use scroll for non-mac platforms, and pinch for mac platform  (effectively replacing the scroll with pinching for mac platform) ? 🤔

**Comment by mmahmoudian** [comment]
I suggest we keep pinching as an alternative way to change the size of a pinned image and even not make it mac-specific, as some Linux DEs/WMs are moving towards supporting touch gestures and it would be good that we also adopt this early-on.

**Comment by RusackN1** [comment]
a lot of mac users are still using a mouse, so they typically scroll and not pinch

**Comment by AndreaMarangoni** [comment]
PR #2447
