### ISSUE TITLE
Add upload/copy on mouse release

### ISSUE THREAD

**Issue by WideTracked** [flameshot-org/flameshot#2025]
I'm using Flameshot on Linux.

I'm transitioning from Windows to Linux and one (admittedly small) thing that I miss from all the screenshot software I've tried is the ability to quickly select a region, let go of the mouse and have the program copy the image to clipboard and upload. I know you can press Enter to confirm the screenshot but that is an extra step. This way saves some hassle especially when capturing a large amount of images. ShareX allows the user to switch between having to press Enter or not by enabling multi-region mode. It would be nice if this feature was added to Flameshot.

**Comment by veracioux** [comment]
This has been added in the newest development versions. You can download it from [here](https://flameshot.org/nightly).

Launch flameshot like `flameshot gui --clipboard --upload --accept-on-select`. This should accomplish what you are asking for. You can also pass a `--help` option to see other useful options.

Remember to kill and then relaunch the flameshot daemon by running `pkill flameshot; flameshot` beforehand.

**Comment by WideTracked** [comment]
> This has been added in the newest development versions. You can download it from [here](https://flameshot.org/nightly).
> 
> Launch flameshot like `flameshot gui --clipboard --upload --accept-on-select`. This should accomplish what you are asking for. You can also pass a `--help` option to see other useful options.
> 
> Remember to kill and then relaunch the flameshot daemon by running `pkill flameshot; flameshot` beforehand.

Just tried it and it works wonderfully. Thanks so much for your help and for your contribution to this amazing piece of software!

**Comment by veracioux** [comment]
@WideTracked My pleasure :D

**Comment by ElijahLynn** [comment]
Yes, wonderful feature, thank you!
