### ISSUE TITLE
bugged CTRL+Z in windows 10

### ISSUE THREAD

**Issue by axiss-code** [flameshot-org/flameshot#2030]
**Flameshot version**
0.10.1 (latest)

**Describe the bug**
CTRL+Z is not working the time of taking the screenshot. Only when undo function is asociated to "CTRL+Z". 

**To Reproduce**
Undo is not functioning at the time of taking the screenshot, when asociated to "CTRL+Z". (Arrows_Buttons UNDO and REDO are ok, so the function is perfect. It's the shortcut which is not working.
Tried with Z only and is ok (without CTRL), but with CTRL doesnt do anything.
I noticed that " ´ ", is recognized as " Z " when trying to associate it as a new shortcut. (Spanish keyboard layout)
Resume:
" Z " = " ´ " // it works properly when pressing Z at the moment of the screenshot
"CTRL+Z" = "CTRL+Z"  // recognized as CTRL+Z in shortcuts options, but ignored at screenshot usage

**Expected behavior**
Z being properly recognized in shortcuts. Not as " ´ ".

**System Information**
Windows 10_x64_21H1 - Spanish keyboard layout

**Comment by veracioux** [comment]
Very interesting. Does this happen consistently, i.e. every time you press `Z` in flameshot it is recognized as `´`? Does the same happen when you insert text using the text tool?

Does `Ctrl+Z` always work in programs other than flameshot (if you have programs installed that you know are written in Qt, these are the best to try with)?

**Comment by veracioux** [comment]
Also, can you post your config, once with undo bound to `Z` and another time with undo bound to `Ctrl+Z`? On Windows, the config is most likely in `%appdata%/flameshot/flameshot.ini`.
