### ISSUE TITLE
Upload to Imgur hotkey design decision

### ISSUE THREAD

**Issue by FunWithUrban** [flameshot-org/flameshot#2034]
Do you plan on keeping #1753 permanent or is it just temporary until a better solution is implemented? 

My suggestion would be to keep the hotkey empty until a user sets it himself. That way new users aren't uploading anything by mistake and by setting the hotkey themselves they know not to activate it unless they want to.

For me the draw of Flameshot was being able to activate it with a hotkey, quickly select what I want, then upload the image with the URL automatically copied to my clipboard. The current change slows down my workflow to fix a (warranted) problem that can be solved another way.

Flameshot version
v0.10.1
System Information
Arch

**Comment by veracioux** [comment]
@FunWithUrban In a recent commit, I made the change you are asking for. You can download the latest development version either from the AUR (package `flameshot-git`) or from [here](https://flameshot.org/nightly).

@borgmanJeremy I wasn't aware of #1753. Do I have to revert my change?

**Comment by borgmanJeremy** [comment]
@veracioux we need to make sure we add in a confirmation box before uploading. Since that confirmation box was not present and we had multiple users that accidentally uploaded data I removed the upload hotkey for a quick fix.

**Comment by deo002** [comment]
> @veracioux we need to make sure we add in a confirmation box before uploading. Since that confirmation box was not present and we had multiple users that accidentally uploaded data I removed the upload hotkey for a quick fix.

I am working on the confirmation box issue.

**Comment by FunWithUrban** [comment]
Awesome, Ill switch to the development version once the changes are implemented. Thank you to everyone working on this!

**Comment by veracioux** [comment]
@deo002 Thanks. Please take into account #1751 also.

**Comment by deo002** [comment]
@veracioux Yes, thanks!

**Comment by mmahmoudian** [comment]
@FunWithUrban & @borgmanJeremy & @veracioux shall we close this one?
