### ISSUE TITLE
KDE/Wayland: Can't take a screenshot 

### ISSUE THREAD

**Issue by haizaar** [flameshot-org/flameshot#2036]
**Flameshot version**

0.10.1

**Describe the bug**

I'm running flameshot on KDE 5.23.1 and attempting to take the screenshot does nothing but dropping the following error line:
```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
P.S. Upon startup the following is printed as well:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
```
**To Reproduce**

Install NixOS unstable with plasma5 and flameshot. Run flameshot in terminal. Attempt to take snapshot by operating the tray applet or by running `flameshot gui` in another terminal.

**Expected behavior**

Screenshot UI to kick in.

**System Information**

NixOS unstable. KDE 5.23.1. Flameshot 0.10.1

**Comment by borgmanJeremy** [comment]
This PR fixes it for me on Arch: https://github.com/flameshot-org/flameshot/pull/2045

Do you have an easy way to test that on Nix? Or should I merge it and you can test once merged? It's important that when you test it the new .desktop file is properly registered.

**Comment by haizaar** [comment]
Thanks @borgmanJeremy. I tried testing 0.10.1 with your patch applied and now it spits
```
kf.windowsystem: Could not find any platform plugin
```
upon attempt to take a screenshot. Any ideas?

**Comment by haizaar** [comment]
Not sure why this was marked as closed. Flameshot still doesn't work for me for KDE + Wayland

**Comment by borgmanJeremy** [comment]
Have you tried on the master branch or flameshot-git from AUR?

**Comment by haizaar** [comment]
I'm on NixOs, no Arch :)
There is a PR pending for flameshot on NixOS: https://github.com/NixOS/nixpkgs/pull/145777
