### ISSUE TITLE
MacOs how get fullbuild?

### ISSUE THREAD

**Issue by cryerenable** [flameshot-org/flameshot#2040]
How i can build Flameshot to dmg container?
i have flameshot.app with size 2.5mb, but it not working on another macOs device.

**Comment by borgmanJeremy** [comment]
If you just want the build on MacOs you can install with brew. 

If you actually want to build the .dmg i recommend you use this as a reference: https://github.com/flameshot-org/flameshot/blob/master/.github/workflows/MacOS-pack.yml

**Comment by mmahmoudian** [comment]
@cryerenable I believe the information Jeremy provided answered the question. Is there any additional information you would need or shall we consider this issue as closed?

**Comment by cryerenable** [comment]
Hello again.
Why **my build** doesn't have someone dirs as in **Original release build**?
How fix it?
<img width="667" alt="scr" src="https://user-images.githubusercontent.com/15123106/140276898-53404ab6-b64b-4e1f-8068-4ccca09337ef.png">

**Comment by borgmanJeremy** [comment]
Did you follow all of the steps outlined in the github workflow?

**Comment by cryerenable** [comment]
> Did you follow all of the steps outlined in the github workflow?

Oh, sorry, I'm a donkey.
This solved my problem.
`“$(brew --prefix qt5)/bin/macdeployqt” flameshot.app -dmg`
borgmanJeremy thank you mentor
