### ISSUE TITLE
How can I delete file uploaded to imgur?

### ISSUE THREAD

**Issue by byteshiva** [flameshot-org/flameshot#2046]
How can I delete the file uploaded to imgur? Is there any time or auto-expire set on the file uploaded to Imgur? 

**Flameshot version**

``Flameshot v0.10.1 Compiled with Qt 5.15.3``

**Describe the bug**

`How can I delete files uploaded to imgur?`

**To Reproduce**

**Expected behavior**

**System Information**

**Comment by borgmanJeremy** [comment]
If you look in the upload history you can find the image and delete from there.

**Comment by byteshiva** [comment]
> If you look in the upload history you can find the image and delete it from there.

Thanks  :+1:

**Comment by byteshiva** [comment]
I've deleted the file from upload history, but still, the file has not been deleted from the Imgur server,
Is it a soft delete or hard delete?

**Comment by borgmanJeremy** [comment]
If you deleted it from the history rather than using the history to delete it from Imgur I think it's on Imgur forever unless they can delete it for you.

**Comment by byteshiva** [comment]
> If you deleted it from the history rather than using the history to delete it from Imgur I think it's on Imgur forever unless they can delete it for you.

Does `flameshot` create a unique user id or session id or just guest id for uploaded files on Imgur? I see it not deleted,

I have used the delete option available in upload history to delete the file, Still, I can see the file available in Imgur!
Are there any logs where I can see the deleted history of flameshot!

**Comment by byteshiva** [comment]
I've raised a request on Imgur to delete the file, It's been deleted now. 

But It would be good to see the `delete URL` or the `deletehash`, Just in case of any failure or errors happening during the deletion process.

**Comment by byteshiva** [comment]
My mistake,

I see now, after clicking delete on flames shot it had opened the `delete url` in a browser, it was on my other dual monitor.

I used it to delete the file. 

Thanks
