### ISSUE TITLE
Program and DE Hanging when uploading image

### ISSUE THREAD

**Issue by coolyc3** [flameshot-org/flameshot#2051]
**Flameshot version**
445a4c68

**Describe the bug**
When uploading to Imgur, the program hangs for about 20 seconds and hangs the DE as well.

**To Reproduce**

Take a screenshot and upload, The program and the DE hang for about 20 seconds.

**Expected behavior**

Take a screenshot and upload, The program uploads quickly and does not interfere with the DE.

**System Information**

Manjaro 21.1.6 KDE

**Comment by FunWithUrban** [comment]
Can confirm this is happening to me as well after updating switching to the git version. I'm using the current AUR package flameshot-git r1354.8f6b6b08-1 which Flameshot tells me is version 445a4c68.

**System Information**
Arch
KDE Plasma

**Comment by borgmanJeremy** [comment]
Thanks, after bisecting the commit log it looks like 988dcab is the offending commit. 

I'm guessing this is a race condition with the notification manager.

**Comment by borgmanJeremy** [comment]
#2053 should resolve the issue once merged.
