### ISSUE TITLE
When Flameshot is opened from GUI, screen sometimes shrinks.

### ISSUE THREAD

**Issue by mi1ez** [flameshot-org/flameshot#2054]
**Flameshot version**
0.10.1 (4e406ec)

**Describe the bug**
When taking a screenshot using the GUI, the visible screen will sometimes shrink to less than a quarter of the monitor size and be cropped. This seems to happen most frequently after the machine has been put into a sleep state, but not every time. I'm also not sure if having a second monitor connected is an agravating factor.

Before opening Flameshot:
![flameshot-not-open](https://user-images.githubusercontent.com/19889543/140832332-137f31ea-c978-4f5f-b0a8-f44e97f68da9.jpg)

Once Flameshot is opened:
![flameshot-open](https://user-images.githubusercontent.com/19889543/140832378-c5906139-c3bf-4196-afc1-16b57d6c8b24.jpg)

Closing and reopening Flameshot returns it to expected behaviour.

Not sure if this is the "fractional scaling" issue mentioned in the FAQs as the description isn't very clear. Either way, I have no scaling set, and this is affecting applications that aren't fullscreen as the FAQs imply.

**To Reproduce**
Unable to reproduce consistently.

**Expected behavior**
Screen visible area to remain the same whilst taking screenshot.

**System Information**
MacOS 11.6

**Comment by borgmanJeremy** [comment]
On macOS there is an issue where if your screen config changes after starting flameshot, you must restart Flameshot.

I should probably add this to the FAQ as it's a pretty common complaint.

**Comment by veracioux** [comment]
@borgmanJeremy I'm assuming this won't be as much of a problem after the DBus PR?

**Comment by borgmanJeremy** [comment]
I don't see why the dbus stuff would fix it, but maybe I'm missing something.

I haven't tried to troubleshoot this one yet.

**Comment by veracioux** [comment]
@borgmanJeremy The way I understand it: Currently there is a time interval between launching the daemon and launching the GUI capture. In that time interval, the screen config can change. If `flameshot gui` is self-contained (as it will be after #2003), then the screen config will be synced at each run of that subcommand.

**Comment by borgmanJeremy** [comment]
Is that PR in a place where I could test it on a Mac?

**Comment by mi1ez** [comment]
> On macOS there is an issue where if your screen config changes after starting flameshot, you must restart Flameshot.
> 
> I should probably add this to the FAQ as it's a pretty common complaint.

Nothing about the way MacOS deals with a second monitor surprises me any more. All round terrible experience.

Every time my Macbook goes to sleep or turns the screen off it seems to forget the second monitor exists, so that would line up with what you're saying, although it doesn't seem to happen every time.

**Comment by mmahmoudian** [comment]
Isn't it weird that the message and the sidebar button are neither vertically nor horizontally aligned to the monitor or the scaled picture, but the shade has filled the monitor fully.
Feels like there are three different dimensions in play:
1. The actual monitor size (shade respects it properly)
2. The smallest one which the screenshot is shrunk to
3. The one in between where the message and the sidebar button are using to align themselves

**Comment by thapaliya19** [comment]
I encountered a similar bug in my Archlinux installation with kernel version 6.9.1-arch1-2. My current flameshot version is v12.1.0. Are there any solutions to this issue?

**Comment by hiddengerbil** [comment]
I have the same issue. I'm on Arch Linux, KDE, running Weyland. I have Flameshot to run in my system tray at login. I click on the icon to start the app, and the screen shrinks to the top left corner. I have to then select the region I want to capture on the shrunken desktop.

Quitting and restarting the app doesn't fix the behaviour (as someone mentioned above).

I'm on AMD CPU & GPU. My screen is 5120 x 1440 (Samsung curved screen)

I have another machine with a 1920 x 1080 screen and the same thing happens on that one.

**Comment by Dasonic** [comment]
Same issue, when scaling is set to 125% then this bug happens. Setting scaling to 100% fixes it, but this is far too tiny.

**Comment by AJR07** [comment]
Same issue here, linux 6.12.8.arch1-1, when scaling set to more than 100%.

**Comment by gurubyte** [comment]
Same issue here on Fedora 41 KDE Plasma

**Comment by codeshaunted** [comment]
Same issue here on Arch + KDE Plasma

**Comment by mariusse** [comment]
Same on Linux Mint, Cinnamon with 200% scaling, X11, Nvidia.
13.1.0 - weirdly shrinks desktop
12.1.0-2buil2 - works fine

**Comment by Kirstukas** [comment]
This happens on arch with `Xft.dpi: 192` set in _.Xresources_. I found a dirty fix by setting `QT_SCREEN_SCALE_FACTORS=1.00001`.
