### ISSUE TITLE
Minimum size for Thickness Slider

### ISSUE THREAD

**Issue by claytron5000** [flameshot-org/flameshot#2066]
**Is your feature request related to a problem?**

Currently, the Active Thickness slider is much too small, so it's hard to finely adjust the width/font size of an element.
![image](https://user-images.githubusercontent.com/5767672/141653254-7ef6e2ce-69b2-458b-a8e8-864119cd5d85.png)
Propose to set a minimum width to the slider, and allow form elements to wrap.
![image](https://user-images.githubusercontent.com/5767672/141653285-a4b817a3-17e8-45c3-9864-254c1c771d36.png)

**Comment by mmahmoudian** [comment]
This is how I see it now and it kinda feels out of place. it is not filling the whole row and there is empty space between the "Active tool size" and "Active color". 

![image](https://user-images.githubusercontent.com/390889/142213307-c9f16de9-81ee-405f-b59c-f339d9b18030.png)

I'm using the following:

Flameshot v0.10.1 (f25d58b6)
Compiled with Qt 5.15.2
linux: 5.10.70-1-MANJARO
manjaro: unknown

**Comment by borgmanJeremy** [comment]
@mmahmoudian Can you open a separate issue for centering it? I should be able to do that but I don't want to forget.

**Comment by mmahmoudian** [comment]
@borgmanJeremy Done #2092
