### ISSUE TITLE
Flameshot don't open or don't capture Gnome 41 - Fedora 35

### ISSUE THREAD

**Issue by lcquerido** [flameshot-org/flameshot#2069]
[

**Flameshot version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**System Information**
](https://bin.snopyta.org/?19d9190677f0a46a#JE5wCPJissPFJboBwzDriDYJRiCWHq12ZQ14L3P2kyA5)

**Comment by borgmanJeremy** [comment]
Duplicate of 1910
