### ISSUE TITLE
Set default save path

### ISSUE THREAD

**Issue by jankatins** [flameshot-org/flameshot#207]
I initially configured my screenshots to just `flameshot full` but apparently that doesn't work: it needs a `-p <path>` to work.

It would be nice if I could specify a default save path (`~/Pictures/Screenshots`) in the config and could then run `flameshot full` without specifying a path.

**Comment by sixpointzero** [comment]
Apparently, there's a config file at ``~/.config/Dharkael/flameshot.ini`` (I'm not sure why it isn't ``~/.config/flameshot/flameshot.ini`` or simply ``~/.config/flameshot.ini`` ... it would've been better don't you think?) in which a ``savePath`` variable exists, I still need to mention the path when I try to take a fullscreen shot.

Please consider fixing this issue. It also would be better if there was an option to specify the default save directory in the GUI config window opened using ``flameshot config``.

Thanks for making an awesome tool.

**Comment by Neules** [comment]
It's not saving anywhere, not even on default "`Pictures/Screenshots`" folder :(

I'm using Manjaro KDE Plasma.

I've tried just clicking from the system try icon, by using the custom hotkey file and pressing `prt scr`, or `ctrl prt scr` or whatever. 

I haven't had `Pictures/Screenshots` initially because of location, but even creating it didn't do the trick. Nor changing `.config/Dharkael/flameshot.ini`'s `savePath`, nothing. Flameshot doesnt save anywhere. Tried by console to get any debug, with no luck...

Application just shows and works as expected but saving. 

Maybe it's a permission's issue?

**Comment by daviddoji** [comment]
Same here!
Works fine but I can´t save the screenshot!

**Comment by traversng** [comment]
FWIW, on Ubuntu, its saving just fine, only problem is its not going to `~/Pictures/Screenshots` as expected when following the tutorial on the site [here](https://github.com/lupoDharkael/flameshot#on-kde-plasma-desktop)

![image](https://user-images.githubusercontent.com/8641085/60831527-63df2e00-a17f-11e9-8e6f-f15ab7472582.png)

Instead it saves to `~/Pictures` as a sibling to the `~/Pictures/Screenshots` directory

![image](https://user-images.githubusercontent.com/8641085/60831619-9557f980-a17f-11e9-99c5-9329b27527a7.png)

**Comment by cbagpipe** [comment]
I'm using Kubuntu with non-English locale and Flameshot rewrites savePath on startup with:
`savePath=/home/username/\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f`
So I haven't Pictures folder, and so I can't save any shot. Please fix it asap.

**Comment by whiteShtef** [comment]
Still not fixed, bump

**Comment by joeySeal** [comment]
Any updates here? If I change the save path in `.config/Dharkael/flameshot.ini` it gets changed back to `Pictures/Screenshots` I have also tried exporting the config, editing the path and than importing to no avail.

**Comment by michaelignacio** [comment]
Glad to know I'm not alone in this, I'm using Kubuntu 18.04 and all other features work fine except for saving a screenshot to a file. This is the message that I get:

`Error trying to save as Pictures/Screenshots/screenshot.png`

Even when I have the `savePath` set to something else, the same error still occurs.

**Comment by jctratt** [comment]
On KDE neon User Edition 5.18 having same problem. Changed the `.config/Dharkael/flameshot.ini` without success.
FIXED:
System Settings -> Shortcuts -> Custom Shortcuts -> Flameshot -> Take screenshot -> Action (tab)
in Arguments: change `'Pictures/Screenshots' 0 0`
to `'/home/username/Pictures/Screenshots' 0 0` Replace _username_ with your username.
Repeat for other shortcuts:

- Take screenshot with delay
- Take full-screen screenshot and save

Now it's working.

Note to developer: This worked correctly when I installed, then started saving to ~/Pictures/ but then stopped working. In-between ~/Pictures and not working, I did reinstall KDE neon with same /home/user but completely wiped /.
First iso: neon-user-20200220-1117.iso
This iso: neon-user-20200312-1118.iso
Hope that helps.

**Comment by SecretAgentAgentX** [comment]
I'm on Garuda which isn't all that much different than Manjaro and when I do a full screen capture Flameshot saves to the clipboard. Problem is trying to copy the screens to any folder either doesn't work or I end up with unusable files. Really need Flameshot to have a proper option for saving the capture rather it's the entire screen or part of the screen to a location of the users choice.

**Comment by borgmanJeremy** [comment]
Confirmed on main branch. This would be nice to get into 0.8, ill see if we can get to it in time.

**Comment by borgmanJeremy** [comment]
@SecretAgentAgentX does garuda let you pull from aur? If so could you please test with flameshot-git? I am actually not able to replicate this now.

**Comment by Moini** [comment]
Mmmh. I can set it now, but it's ignored :-/ (0.8.0 AppImage)

**Comment by Mobuos** [comment]
> On KDE neon User Edition 5.18 having same problem. Changed the `.config/Dharkael/flameshot.ini` without success.
> FIXED:
> System Settings -> Shortcuts -> Custom Shortcuts -> Flameshot -> Take screenshot -> Action (tab)
> in Arguments: change `'Pictures/Screenshots' 0 0`
> to `'/home/username/Pictures/Screenshots' 0 0` Replace _username_ with your username.
> Repeat for other shortcuts:
> 
>     * Take screenshot with delay
> 
>     * Take full-screen screenshot and save
> 
> 
> Now it's working.
> 
> Note to developer: This worked correctly when I installed, then started saving to ~/Pictures/ but then stopped working. In-between ~/Pictures and not working, I did reinstall KDE neon with same /home/user but completely wiped /.
> First iso: neon-user-20200220-1117.iso
> This iso: neon-user-20200312-1118.iso
> Hope that helps.

Seems then that the culprit at least in my case was the [custom shortcuts for kde](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde) that I imported into kde, which passes `'Pictures/Screenshots' 0 0` to flameshot, overwriting user configs?
