### ISSUE TITLE
Flameshot does not work with MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by Raj-Joshi-dev** [flameshot-org/flameshot#2070]
**Flameshot version**
v0.10.

**Describe the bug**
Installed via homebrew using `brew install --cask flameshot`

![Flameshot](https://user-images.githubusercontent.com/52413491/141691104-de49731d-a8cf-43fa-b373-e5cf735ca4b9.png)

**To Reproduce**
1. Launch flameshot.
2. Pop up appears that you cannot run the program.

**System Information**
macOS Monterey 12.0.1

**Comment by borgmanJeremy** [comment]
This is because we do not pay apple to sign the binary. You need to go into the security settings and allow the app to run.

**Comment by Raj-Joshi-dev** [comment]
Thanks a lot! It worked.
