### ISSUE TITLE
[Arch] Flameshot takes screenshots in the past

### ISSUE THREAD

**Issue by ExperiBass** [flameshot-org/flameshot#2075]
**Flameshot version**

**Describe the bug**

Flameshot takes screenshots in the past. When opening the gui, it displays the desktop as of around 5 minutes ago.

**To Reproduce**

- Open the GUI or take a screenshot.
- notice how the image doesn't match what is currently on the screen.

**Expected behavior**

Flameshot will screenshot whats on the screen as of now.

**System Information**

endeavourOS (rolling), Kernel 5.14.13-1mbp-16.1-linux-wifi
DE: Cinnamon 5.0.7
WM: Mutter (Muffin)
Flameshot v0.10.1 (AUR)
Compiled with Qt 5.15.2

**Comment by borgmanJeremy** [comment]
What method did you use to install Flameshot?

**Comment by ExperiBass** [comment]
i used the AUR.

**Comment by borgmanJeremy** [comment]
did you install "flameshot" or "flameshot-git", if flameshot-git, can you please post the SHA? You can find it in the about menu of flameshot.

**Comment by ExperiBass** [comment]
plain `flameshot`

**Comment by borgmanJeremy** [comment]
I did a fresh install and it seems to be working properly. Not sure what the difference would be.

![image](https://user-images.githubusercontent.com/46930769/141859344-5cd0326a-1d1d-44b5-ab91-96bef6e244f5.png)

**Comment by ExperiBass** [comment]
interesting...

for me it happens nearly every time i open it, i have to open, then close, then open for it to update

**Comment by borgmanJeremy** [comment]
That's so strange, I cant even think how that possibly is happening.

Is it possible its not returning from 5-7 minutes ago, but rather returning a previous image you captured?

**Comment by ExperiBass** [comment]
thats what i thought too, but it would display apps like VScode that i had closed ages ago and hadnt ever taken a screenshot of

**Comment by sigaloid** [comment]
Does it return the screenshot from 5 minutes ago, or does it lag for 5 minutes then appear somehow (maybe delayed, maybe triggered by another screenshot)?

**Comment by mmahmoudian** [comment]
@borgmanJeremy this was also reported to me by a friend of mine around 5 months ago on Manjaro. We did some tests and couldn't even figure out how to reproduce it. At the time I had the same exact Manjaro and Flameshot versions on 3 different computers and yet no joy in reproducing it!

@ExperiBass you forgot to provide the Flameshot version. Please specify exactly what version of Flameshot you have.

**Comment by ExperiBass** [comment]
Both the about menu and the cli --version don't give me the git build. Is there something I'm missing?

**Comment by mmahmoudian** [comment]
@ExperiBass how have you installed Flameshot? If you are still using the AUR version as [you said before](https://github.com/flameshot-org/flameshot/issues/2075#issuecomment-969348453), then it means that it is not updated, try installing it again. For example using paru:

```sh
paru flameshot-git
```

**Comment by ExperiBass** [comment]
I ran `yay -S flameshot`, do you want me to switch to flameshot-git?

**Comment by mmahmoudian** [comment]
There is no AUR with the name `flameshot`:

https://aur.archlinux.org/packages/?O=0&SeB=nd&K=Flameshot+&outdated=&SB=n&SO=a&PP=50&do_Search=Go

The only packages in Arch that we support are `flameshot-git` AUR and the `flameshot` from community repo:

https://archlinux.org/packages/?sort=&q=Flameshot+&maintainer=&flagged=

**Comment by ExperiBass** [comment]
Ahhh ok, I got the community version then. I'll try the git when I get home if that's what you need?

**Comment by mmahmoudian** [comment]
Considering that this is a rare issue, would be nice to know what version you have (which now we know because you have installed the community version), and if the newest AUR still has this issue.

**Comment by ExperiBass** [comment]
alright, im back home

installed Flameshot v0.10.1 (53cc11ac), we'll see how it goes

**Comment by maxgqc** [comment]
I have the same issue
I installed with yay -S flameshot
Tried flameshot-git but I can't get it to work. flameshot gui doesnt do anything, also system shortcut doesn't work with flameshot-git while flameshot does screenshot in the past. It even bring back windows that were closed 2 minutes before

**Comment by ExperiBass** [comment]
So far I haven't encountered it, not like I can test further cause for some reason cinnamon has decided to crash on startup

**Comment by mmahmoudian** [comment]
@maxgqc try the following for `flameshot-git`:
1. Install it again. I use `paru` and I don't know if `yay` updates properly when there is a new git commit merged into master.
2. Open a new terminal and run

```sh
pkill flameshot
sleep 2s
Flameshot
```

3. Tell us what version you have installed: right click on the try icon > About > copy

4. I assume you are KDE and your shortcuts are probably for the old version. Try importing [this file](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde.khotkeys) into your keyboard shortcut settings. We have explained it [here](https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop)

5. Open a new terminal and try:

```sh
flameshot gui
```

6. If the Flameshot didn't start, copy the output of both terminals and paste them here

7. Give us a full system info:

```sh
inxi --graphics --system
```

**Comment by mmahmoudian** [comment]
@borgmanJeremy @veracioux based on [the link](https://www.reddit.com/r/kde/comments/p9ojj2/screenshot_tools_taking_screenshots_fromthe_past/) @maxgqc shared, the issue of that redditor was resolved by removing the intel graphics driver:

> EDIT: Thanks to throwaway6560192 for the solution. The issues were resolved after removing the xf86-video-intel package.

I also remember that my friend was also using Manjaro KDE on his laptop with Intel GPU, and perhaps the same `xf86-video-intel` driver.

I wonder if there is an easy way to simulate this on a VM and reproduce it.


-------
@ExperiBass and @maxgqc can you also confirm that if you are using integrated Intel GPU or not?

**Comment by ExperiBass** [comment]
Yes, I'm using Intel Iris Plus.

**Comment by mmahmoudian** [comment]
@ExperiBass please keep using Flameshot you installed from AUR and see if the issue rises again, and please keep us posted. This is a very rare issue and perhaps needs a very specific set of hardware and software to happen, and for that reason it would be good to know what are the conditions and what is the main issue.

**Comment by borgmanJeremy** [comment]
Based on that info I found this arch wiki page too: https://bbs.archlinux.org/viewtopic.php?id=263247 I think we should close this and you should file an upstream bug. This is so far down the technology stack that we wont really be able to fix it or effectively troubleshoot. Flameshot uses the qt screenshot utility, which somehow ties into X11, and that ties into the driver. Once we get past Qt, we really aren't going to be much help. 

I did dig into the Qt source code but nothing caught my eye or sparked a thought for what to try next.

**Comment by ExperiBass** [comment]
Just my luck, I stumble across a deep issue lol

I'll look into filing a upstream report, thanks for the help!

**Comment by mmahmoudian** [comment]
@ExperiBass please also post the link of the issue you open in upstream here so that we can also have it on the records and follow.

**Comment by npit** [comment]
Just mentioning that I the same weird issue with flameshot 12.1.0, but only on a lenovo laptop (desktops and other laptops work fine).

**Comment by joelchrono12** [comment]
I've had the same issue, this time on void linux, v 12.1.0

Opening and closing multiple times kinda fixes it, but its still annoying

**Comment by mmahmoudian** [comment]
@joelchrono12 as [mentioned before](https://github.com/flameshot-org/flameshot/issues/2075#issuecomment-974893135) this is an upstream issue. We have to wait until they fix it 🤷‍♂️

**Comment by h1ac** [comment]
Same here!!
