### ISSUE TITLE
Save screenshot file name broken

### ISSUE THREAD

**Issue by kophjager007** [flameshot-org/flameshot#2080]
**Previous Issue** 
The previous closed issue #1722 is still present in the latest stable release.  

**Flameshot version**

Flameshot 0.10.2-1 ( flameshot-0.10.2-1.ubuntu-20.04.amd64.deb )
* previously installed version was 0.9.0.

**Describe the bug**

When saving a screenshot with `.`'s in the file name, such as naming a screenshot after an IP address (eg `12.13.14.15-p80-vuln.png`), the screenshot will be saved as `12.png`. Everything after the first `.` in the file name will be dropped. Additionally, Flameshot will not prompt for overwrite in this condition.

**To Reproduce**

Attempt to save a screenshot with `.`'s in it, such as `12.34.56.78.png` and the results will be `12.png`.

**Expected behavior**

As in prior versions, the screenshot should be saved with the intended name. For example, `12.34.56.78.png`.

**System Information**

Ubuntu 20.04LTS Gnome 3.36.7

**Comment by borgmanJeremy** [comment]
0.10.2 was only intended to fix a critical issue on gnome. We did not merge other fixes.

**Comment by mmahmoudian** [comment]
@kophjager007 this is resolved by #1773. You should wait for version 0.11.0
