### ISSUE TITLE
App doesn't open in Fedora 35 with Gnome and X11.

### ISSUE THREAD

**Issue by jeffclay** [flameshot-org/flameshot#2082]
**Flameshot version**
flameshot-0.10.1-1.fc35.x86_64

**Describe the bug**
Opening the program doesn't appear to do anything. I see it running under my user when I run 'ps aux | grep flameshot'. I have attempted killing the process and restarting it to no effect.

**To Reproduce**
Install flameshot via 'dnf install flameshot'
Open Flameshot

**Expected behavior**
I expect to see a gui of some sort for taking and managing the screenshot.

**System Information**
Fedora 35
Gnome
X11 (not wayland)
Thinkpad T14(AMD) Gen 1.

**Comment by borgmanJeremy** [comment]
Do you have a system tray working: https://github.com/flameshot-org/flameshot#considerations

**Comment by jeffclay** [comment]
Thanks, that did the trick.
I had only read the requirements at https://flameshot.org/#considerations and not the git readme.

**Comment by borgmanJeremy** [comment]
Glad that fixed it for you! If you end up using wayland we just put out a release to fix an issue with gnome41 and wayland. It should hit the fedora repo's soon.
