### ISSUE TITLE
Black tray icon in Linux XFCE even Qt and GTK icon theme is light

### ISSUE THREAD

**Issue by makeworld-the-better-one** [flameshot-org/flameshot#2083]
**Flameshot version**
v0.10.1

**Describe the bug**

![](https://user-images.githubusercontent.com/25111343/142090265-07695075-6627-438f-a875-3e149ab51bdc.png)

The tray icon is black in Linux XFCE. I am using the Breeze Dark theme for icons, meaning the icons should be white. I have set this theme for both GTK and Qt applications, and I have observed them obeying it, Flameshot seems to be the odd one out.

**To Reproduce**

Have Flameshot installed, and Breeze Dark set as your style and icon theme for GTK. Set Breeze Dark as your style and icon theme for Qt, following [these instructions](https://wiki.archlinux.org/title/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma). I used the `qt5ct-kde` package over the default `qt5ct` one.

**Expected behavior**

A white icon appears.

**System Information**

Arch Linux, XFCE 4.16

**Comment by borgmanJeremy** [comment]
So right now for linux we only distribute the color icon. Most Linux DE's follow the freedesktop spec for icons. Therefore when you install an icon pack, that icon pack needs to properly provide the app icon. I suspect the breeze dark icon set doesnt properly package a white flameshot icon. 

I use the papirus icon set on KDE and it provides its own flameshot SVG's.

**Comment by mmahmoudian** [comment]
@makeworld-the-better-one I think this is the place you should visit:

https://github.com/KDE/breeze-icons

Note that they have mentioned

> To report a bug or request new icons, use the [KDE Bugtracker](https://bugs.kde.org/enter_bug.cgi?product=Breeze&component=Icons)

**Comment by makeworld-the-better-one** [comment]
Updated my packages and this is now fixed.
