### ISSUE TITLE
macOS app showing update available, when update is only for Linux

### ISSUE THREAD

**Issue by dunhao** [flameshot-org/flameshot#2087]
**Flameshot version**
0.10.1 macOS

**Describe the bug**
On 0.10.1 macOS version.
There was new update available in Github, but it is only for Linux and no download option available for macOS users.
But when I try to take new screenshots, it always shows there is new update available popup.

**To Reproduce**
On macOS, (Whatever, I used Monterey)
Install 0.10.1 version.
Try to take new screenshot.
It shows the notification.

**Expected behavior**
It should not show update available notification if macOS or any specific platform update is not available.

**System Information**
macOS Monterey 12.0.1

**Comment by borgmanJeremy** [comment]
I added macos to the release. In the future ill post binaries for all platforms even if its just a hotfix for a specific OS.
