### ISSUE TITLE
Active thickness slider fill the width of the sidebar

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2092]
### Feature Description

I propose that the slider fills the whole width of the sidebar (of course with some padding). At the moment it looks like:

![image](https://user-images.githubusercontent.com/390889/142213307-c9f16de9-81ee-405f-b59c-f339d9b18030.png)

which is not filling the whole row and there is empty space between the "Active tool size" and "Active color".

**Comment by borgmanJeremy** [comment]
#2093 should fix this
