### ISSUE TITLE
Unable capture on Ubuntu 22.04 (Jammy Jellyfish)

### ISSUE THREAD

**Issue by qwert-f** [flameshot-org/flameshot#2100]
### Flameshot Version

Flameshot v0.10.1
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04 (Jammy Jellyfish)

### Description

I use the flameshot gui command start the software but notification show "Unable to capture screen". While I use flameshot command  the terminal show me "Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway."

### Steps to reproduce

run flameshot gui 
use tray menu "Take screenshot" to capture
see notification

run flameshot
waiting for response

### System Information

System:
  Host: qwert Kernel: 5.13.0-21-generic x86_64 bits: 64 Desktop: GNOME 40.5
  Distro: Ubuntu 22.04 (Jammy Jellyfish)
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nouveau v: kernel
  Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision HD
  Integrated Webcam
  type: USB driver: uvcvideo
  Display: wayland server: X.Org 1.21.1.2 driver: loaded: fbdev
  unloaded: modesetting,vesa resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 21.2.2

**Comment by borgmanJeremy** [comment]
Update to 0.10.2... see the pinned issue for details
