### ISSUE TITLE
In V0.10.2 version at Macbook, the workspace switched

### ISSUE THREAD

**Issue by hasancse91** [flameshot-org/flameshot#2102]
### Flameshot Version

v0.10.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS, 12.0.1

### Description

When launch the flameshot, the current workspace is switched. So that I cannot take screenshot of my desired screen. I have added screen recording with voice. Please have a look.

### Steps to reproduce

1. Install 0.10.2 version on mac
2. run the flameshot by shortcut key or from system tray
3. You'll find, the workspace is switched every time

See the recordings and listen the audio.

### Screenshots or screen recordings

https://user-images.githubusercontent.com/3769029/142969589-3c954c6e-9b88-4f2a-aa6a-ce000b861889.mp4

### System Information

1. macOS Monterey, 12.0.1
2.
<img width="619" alt="Screenshot 2021-11-23 at 9 54 32 AM" src="https://user-images.githubusercontent.com/3769029/142969134-c1b8079e-28e7-47d9-92b7-ed67c3509993.png">
3.
<img width="616" alt="Screenshot 2021-11-23 at 9 55 30 AM" src="https://user-images.githubusercontent.com/3769029/142969206-2d6d988b-7f13-488f-ba7a-698a0f5fe321.png">

**Comment by mmahmoudian** [comment]
@hasancse91 out of curiosity, what is that icon on the top right corner of the screen when you start Flameshot?

**Comment by hasancse91** [comment]
hey! I've just check and found it is working fine!
Maybe the issue was for granting the permission for new update of the app from Mac security settings.
I think you can close the issue.
Thanks for your nice project.

**Comment by hasancse91** [comment]
> @hasancse91 out of curiosity, what is that icon on the top right corner of the screen when you start Flameshot?

![image](https://user-images.githubusercontent.com/3769029/142984574-2694872e-50b1-411a-a88e-7d00f642d107.png)
This one? It is Siri.

**Comment by mmahmoudian** [comment]
I'm glad it got resolved. I haven't used mac for quite a few years now, so I had no idea new versions of the same sugar need new permission. Mac works in mysterious ways I suppose 😅

Thank you for the nice and comprehensive bug reporting.

**Comment by mmahmoudian** [comment]
> This one? It is Siri.

No when Flameshot gui window is open, I see a pink icon on the top right corner

**Comment by hasancse91** [comment]
> > This one? It is Siri.
> 
> No when Flameshot gui window is open, I see a pink icon on the top right corner

![image](https://user-images.githubusercontent.com/3769029/142985108-aeda29cc-9334-49cf-a56a-ab08b59adf84.png)
This one? It's the indication of using microphone. When I use microphone for any audio/video call or event screen recording, this indication get visible automatically.

**Comment by borgmanJeremy** [comment]
BTW this might be caused by adding and removing monitors. Restarting flameshot generally solves it.
