### ISSUE TITLE
Last update broke Flameshot in macOS 12 (Monterey)

### ISSUE THREAD

**Issue by JohnAntoineG710** [flameshot-org/flameshot#2104]
### Flameshot Version

Flameshot v0.10.2 (bde36fb)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS 12 (Monterey) - Homebrew

### Description

when invoked, Flameshot switches to a completely empty virtual desktop, similar to fullscreen apps. I think macOS is treating it as a full-screen application and moving it. This way, you can't take screenshots at all. 

### Steps to reproduce

1- Invoke the Flameshot shortcut
2- A completely empty desktop appears with Flameshot UI superimposed on it

Please review the attached GIF in the next section

### Screenshots or screen recordings

https://john-antoine.codes/tmp/flameshot.gif

### System Information

OS: macOS 12.0.1 - Monterey
Monitor: Macbook Air 2020 (M1) built-in monitor - single display

**Comment by borgmanJeremy** [comment]
Every time you update flameshot you need to remove and re allow screen sharing.

**Comment by JohnAntoineG710** [comment]
> Every time you update flameshot you need to remove and re allow screen sharing.

Are you taking about the accessibility rights? More info would be appreciated

**Comment by JohnAntoineG710** [comment]
Nevermind, It's the screenshot privileges, just revoke flameshot then add it again, for anyone having the same issue
@borgmanJeremy Thank you, Appreciate your work.
