### ISSUE TITLE
Big box around the captured image when using i3

### ISSUE THREAD

**Issue by c02y** [flameshot-org/flameshot#2105]
### Flameshot Version

Tried versions:
0.10.1-1 installed from ArchLinux repo
or 
downloaded 0.10.2 appimage

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), AppImage

### Operating System type and version

ArchLinux 5.15.4-zen1-1-zen

### Description

When I try to take a screenshot, and pin it in the desktop, there is big box around the captured image, check the gif in attachment for demo

The box is only gone when I zoom in/out using mouse, moving/resizing window doesn't make the box go away.

### Steps to reproduce

1. run "flameshot gui"
2. capture an area
3. pin it
4. there is a box around the image

### Screenshots or screen recordings

![Peek 2021-11-24 04-46](https://user-images.githubusercontent.com/2135996/143117463-e47a3ec1-64f1-4762-a10f-bf4ec353a9dc.gif)

### System Information

1. ArchLinux 5.15.4-zen1-1-zen
```
>> flameshot --version
Flameshot v0.10.1
Compiled with Qt 5.15.2
>> /tmp/Flameshot-0.10.2.x86_64.AppImage --version
Flameshot v0.10.2
Compiled with Qt 5.12.8
```
2. Not sure if the following info is what you want:
```
>> xrandr
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
```
3. DE: none, WM: i3, 
 compositor: picom, when disabled, black box,  when enabled, transparent box
 using Xorg

Other info:

```
>> inxi --width 80 --system --graphics
System:
  Host: chz Kernel: 5.15.4-zen1-1-zen x86_64 bits: 64 Desktop: i3 4.20.1
  Distro: Arch Linux
Graphics:
  Device-1: NVIDIA TU106M [GeForce RTX 2060 Max-Q] driver: nvidia v: 495.44
  Device-2: Syntek Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.org 1.21.1.1 driver: loaded: nvidia
  resolution: <missing: xdpyinfo>
  OpenGL: renderer: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2
  v: 4.6.0 NVIDIA 495.44
```

```
>> loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11
```

```
>> xrandr --listactivemonitors
Monitors: 1
 0: +*DP-0 2560/597x1440/336+0+0  DP-0
```

```
>> xrandr | grep -v " disconnected "
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   2048x1080     60.00    24.00
   1920x1080     60.00    59.94    50.00
   1600x1200     60.00
   1280x1024     75.02    60.02
   1280x720      60.00    59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DP-2 connected (normal left inverted right x axis y axis)
   1920x1080    144.00 +
   640x480       59.94
```

```
>> sudo update-pciids && lspci | grep -i 'vga\|3d\|2d'
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Max-Q] (rev a1)
```

```
>> lshw -class display
WARNING: you should run this program as super-user.
  *-display
       description: VGA compatible controller
       product: TU106M [GeForce RTX 2060 Max-Q]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:205 memory:a2000000-a2ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:3000(size=128) memory:a3080000-a30fffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

```
>> uname -a
Linux chz 5.15.4-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 21 Nov 2021 21:34:35 +0000 x86_64 GNU/Linux
```

**Comment by mmahmoudian** [comment]
I hypothesise that your tiling window manager is forcing new windows to be centered with some gap from the margins, but because the area you selected is small, the picture is left-middle aligned. This can be checked with a much smaller selection and see if it behaves as I explained

**Comment by c02y** [comment]
@mmahmoudian Yes, thanks, in my i3 config, 
1. I set all flameshot windows as floating windows
2. all floating windows are centered automatically.
3. All this kind of floating windows has a default window size, which is the size of the big box
4. When I capture a bigger area (bigger than the default size for floating window), the box is gone.

I remembered that when I was using Manjaro there is no such box, after I converted my Manjaro to Arch( literally convert, not reinstall ArchLinux), I notice this box. (i3 config is the same)

 Is there anything I can do to disable the box?

**Comment by mmahmoudian** [comment]
I think the class and tag of the window is unique and you can add a line in your config to not force dimension to the pin window. I'm typing this on my phone as I'm AFK, so I cannot test this.

**Comment by c02y** [comment]
The class of it is `flameshot`, I don't know what its tag is, is it from `xprop`?


`to not force dimension to the pin window`, sorry, I don't think I get it.
You can tell me more about if you can test it, thanks.

**Comment by borgmanJeremy** [comment]
Sorry but I dont think this is a flameshot bug. This seems to be from the underlying window manager.

**Comment by mmahmoudian** [comment]
@c02y sorry I'm again on my phone without access to a computer. I believe there is a difference between the pinned window of Flameshot and the config and launcher (if not I think it should be a good idea to add it for facilitate window rules in difficulty WMs).
