### ISSUE TITLE
Moving layers

### ISSUE THREAD

**Issue by affirVega** [flameshot-org/flameshot#2106]
### Feature Description

When I was editing a picture, I needed to change layer of one element from the list, but found nothing about how to do so.
I was unable to find such feature request, but I might have missed it.
Problem example: I first created text, then I thought it would be nice to create a rectangle behind the text, but now I have remove text, create rectangle and then create text again.
I have implemented basic movement of layers and wanted to create pull-request, but I'm afraid that might be RFC.
Should I follow RFC procedure or just create pull request?

![image](https://user-images.githubusercontent.com/60240851/143130870-d03fea4a-06d1-4d73-80ee-af58c324724d.png)

I clicked on red rectangle, clicked "Down" and this is how it looks now:
![image](https://user-images.githubusercontent.com/60240851/143131000-4b07dd58-28f1-4338-b715-6963231e4e73.png)

**Comment by borgmanJeremy** [comment]
No need to open an RFC . We can discuss here or on a PR. Generally I really like the feature! Might want to use arrows instead of text . I'll test it more once I build from the PR.

**Comment by affirVega** [comment]
That's very relieving :D
Using arrows instead of text would be great!
I'll open PR, I think it's better to discuss there.

**Comment by affirVega** [comment]
Resolved with pr #2108
