### ISSUE TITLE
Flameshot doesn't work with sway

### ISSUE THREAD

**Issue by Benibla124** [flameshot-org/flameshot#2109]
### Flameshot Version

Flameshot v 0.10.1

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux Rolling (Kernel 5.15.4)

### Description

Flameshot starts, it does show the tray icon. Clicking it does nothing, the screenshot tool won't open.

### Steps to reproduce

- Use sway
- Run Flameshot
- It won't work

### Screenshots or screen recordings

Here's the log:
https://bin.snopyta.org/?4cf0e34e4783de3f#HzdpEfg4EoEwDPLVvMzqETpPszKQKhwCxGQMGRrfaPVM

### System Information

OS: Arch Linux x86_64
Host: Predator PH317-52 V1.26
Kernel: 5.15.4-arch1-1
Resolution: 1920x1080
WM: sway
CPU: Intel i7-8750H (12) @ 2.200GHz
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
Memory: 2039MiB / 15842MiB

Using Wayland with sway.

**Comment by mmahmoudian** [comment]
Have you already followed this:

https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by Benibla124** [comment]
I didn't, but after doing all of the above mentioned steps it's still the same behaviour.

**Comment by RiedleroD** [comment]
works for me
I'm using current master and sway 1.6.1, no special workarounds.

**Comment by mmahmoudian** [comment]
@Benibla124 i just realized you have not provided the full version info (or your Flameshot version is some months old) try force installing the AUR (e.g `paru flameshot-git`) and then give us the full version info which should contain the git commit hash as well.

**Comment by Benibla124** [comment]
I tried with flameshot-git, still didn't change anything.

**Comment by RiedleroD** [comment]
Works for me with stable (0.10.2-1) as well - @Benibla124 are you sure you've got the dependencies installed? They're `grim xdg-desktop-portal xdg-desktop-portal-wlr`.

**Comment by Benibla124** [comment]
@RiedleroD Yeah, got them installed.

**Comment by mmahmoudian** [comment]
@Benibla124 do you have notification manager?

**Comment by RiedleroD** [comment]
Just freshly installed sway on my new laptop; can now reproduce. I'll send an update once I figure out which dependency I need to install.

**Comment by RiedleroD** [comment]
I GOT IT
IT DEPENDS ON GRIM WHAT THE FUCK

someone explain this to me.

**Comment by borgmanJeremy** [comment]
https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by RiedleroD** [comment]
wtf, didn't read that because that info is supposed to be in the package manager :/

**Comment by borgmanJeremy** [comment]
Sorry we don't control the packaging for upstream.

**Comment by RiedleroD** [comment]
ik, I'm sending the guy that packaged flameshot a mail rn

**Comment by borgmanJeremy** [comment]
I'm not sure how they would package it so grim is only requires on sway.

**Comment by RiedleroD** [comment]
as I said, optional dependencies. They can even add an explanation for each optdep. (and that's one reason why I think arch is better than debian ;P)

**Comment by mmahmoudian** [comment]
In the AUR I have added GRIM ages ago as optional dependency (check line 103):

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flameshot-git

**Comment by hosiet** [comment]
Adding optional depends similar to Arch is also always possible on debian via Recommends or Suggests fields since the very beginning. The only part missing is the conditional-depends feature, which I think won't be available in near future.

If package grim is useful to Sway users, we can update dependency fields in deb packages. The only question is that whether we should use the Recommends field or Suggests field:

* Depends: echo to users during installation, installed by default; will not fail if not exist
* Recommends: echo to users during installation, installed by default; will not fail if user opt not to install
* Suggests: echo to users during installation, not installed by default; will not fail if user opt not to install

I think using Suggests or Recommends may all be reasonable.

**Comment by mmahmoudian** [comment]
@hosiet I would go with "Recommends" as it is not a massive library.

**Comment by hosiet** [comment]
Thanks, I have implemented it in Debian's flameshot (version 11.0~rc1+ds1-2). Please also see the Pull Request at #2212 .
