### ISSUE TITLE
Screenshot while selecting object saves image with selection border around object

### ISSUE THREAD

**Issue by affirVega** [flameshot-org/flameshot#2110]
### Flameshot Version

Flameshot [b8c0b74](https://github.com/flameshot-org/flameshot/commit/b8c0b74ea22b14c97a9f25c4e34d1b6d640ebaac)

### Installation Type

Compiled from source

### Operating System type and version

Linux

### Description

Small bug.
When selecting an object in the side panel, object gets dotted border. If you click "copy" while selecting an object, it will copy a screenshot with that border. I think this is a bug.

### Steps to reproduce

1. Run flameshot gui
2. Select some area
3. Create an object inside that area
4. Open sidebar
5. Select this object inside sidebar
6. Click "Copy" button or Ctrl-C

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/60240851/143282983-8258a6d1-7b64-4b4b-979a-d74bf14f81c3.png)

### System Information

1. Arch Linux
2. 1366x768 laptop screen
3. XFCE, Xorg

**Comment by mmahmoudian** [comment]
I have experienced this before while testing a PR made by @thepurple some months back, but as far as I recall it was fixed. I haven't tested it yet though.

**Comment by mmahmoudian** [comment]
I just tested it. You don't actually need to even open the sidebar, selecting the object normally would also have the same effect:

![2021-12-08_12-14](https://user-images.githubusercontent.com/390889/145191278-47eba0ac-30c1-4410-a552-3384603aa06c.png)

Flameshot v0.10.1 (203b5baa)
Compiled with Qt 5.15.2
linux: 5.14.18-1-MANJARO

**Comment by thepurple** [comment]
I'll take a look on it this week. Probably it was broken somehow again. I've found a few new issues after recent code refactoring.

**Comment by borgmanJeremy** [comment]
Merged in version 11
