### ISSUE TITLE
Unable to install flameshot nightly builds

### ISSUE THREAD

**Issue by ajunior7** [flameshot-org/flameshot#2114]
Currently on a fresh install of Fedora 35.

Upon downloading the development packages from the website and installing the fc35 rpm package locally, I am met with a dependency needing libqtcolorwidgets.so.2()(64bit)
![image](https://user-images.githubusercontent.com/40948231/143376666-e4e4dad9-1f80-4e7e-baa3-55b8c3ddc735.png)

I don't know where to proceed from here. I am adamant on using the nightly build, because I have a shortcut that uses --accept-on-release which isnt on the main release branch, only on the nightly builds. It reminds me of how shareX does its screenshots.

Any advice?

**Comment by mmahmoudian** [comment]
We are working on migrating to Qt6 and I think this is the reason you are getting this issue. Easy quick fix for you can be to install Flameshot from an older commit. For example: f675123e0ac91777a2d61eac7d535ec725927a94

**Comment by ajunior7** [comment]
Built from the commit, thank you so much!

**Comment by borgmanJeremy** [comment]
Thanks for reporting this. I'm going to reopen t is so I don't forget to resolve the issue before release.
