### ISSUE TITLE
windows dual monitor issue

### ISSUE THREAD

**Issue by alainbelez** [flameshot-org/flameshot#2120]
### Flameshot Version

windows version: 0.10.2 (f81a971)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

windows

### Description

i'm using a portable monitor which is below my primary monitor and for some reason that monitor is not being detected when doing a screenshot, monitors on the side works though.

### Steps to reproduce

1. stack monitor top and bottom
2. drag to create a screenshot (this will stop at the boundaries of top monitor) cannot even take a screenshot on the lower monitor

### System Information

1. windows
2. 
![image](https://user-images.githubusercontent.com/6648110/143525509-e545a909-cb04-42ef-bb86-83ea2101f4e4.png)

**Comment by GabrielVander** [comment]
I'm facing the same issue. It only takes screenshots on the primary monitor. Other tools, like Lightshot, support multiple monitors. Running Windows 11 here.

**Comment by mmahmoudian** [comment]
@alainbelez and @GabrielVander can it be related to #2128?

What happens when you close Flameshot from the tray icon, connect your secondary monitor and then start Flameshot?

**Comment by alainbelez** [comment]
> @alainbelez and @GabrielVander can it be related to #2128?
> 
> What happens when you close Flameshot from the tray icon, connect your secondary monitor and then start Flameshot?

ohh. just tried it now, and it looks like the same issue as the one you linked

**Comment by GabrielVander** [comment]
> @alainbelez and @GabrielVander can it be related to #2128?
> 
> What happens when you close Flameshot from the tray icon, connect your secondary monitor and then start Flameshot?

Yup, that's exactly it. After restarting Flameshot it works fine. Thanks!

**Comment by mmahmoudian** [comment]
@alainbelez and @GabrielVander thank you both. So now you have a solid work around to bypass the issue for the time being. I'll more close this issue in favour of #2128 as it has more clear explanation for the dev team.
