### ISSUE TITLE
Flameshot won't load itself automatically in awesomeWM

### ISSUE THREAD

**Issue by lygamac** [flameshot-org/flameshot#2123]
### Flameshot Version

flameshot 0.10.2-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux (Kernel Linux 5.10.81-1-lts)

### Description

When I was using i3wm, flameshot will automatically load itself for any given command if it's not running, which is the expected behavior as described [here](https://github.com/flameshot-org/flameshot/issues/1701#issuecomment-881203739).

But in the case of awesomeWM, it can only be done by the old way, running `flameshot &` and then `flameshot gui`, `flameshot screen -p ~/`, etc.

### Steps to reproduce

In a terminal window, what works:
```
flameshot &
flameshot gui
```
what won't work (exits immediately without errors):
```
pkill flameshot
flameshot gui
```

### System Information

Arch Linux (Kernel Linux 5.10.81-1-lts)

Flameshot v0.10.2
Compiled with Qt 5.15.2

AwesomeWM in Xorg

**Comment by veracioux** [comment]
@lygamac It seems to be a fairly common issue for people using window managers (I have this same issue in i3wm, maybe I forgot to change some config option). But it should be fixed in the newest development version of flameshot (and in the v11 release which is coming soon). You can test it out by installing `flameshot-git` from the AUR.

**Comment by mmahmoudian** [comment]
@lygamac would you please test the `flameshot-git` AUR (or build from source) and let us know if the issue is resolved?

**Comment by lygamac** [comment]
@mmahmoudian the git version seems to work fine. Thanks
