### ISSUE TITLE
User workflow opaque in v0.10.2

### ISSUE THREAD

**Issue by ghbrown** [flameshot-org/flameshot#2132]
### Flameshot Version

Flameshot v0.10.2 (c4081c65)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Manjaro Linux

### Description

First, I've been using Flameshot for quite a while and have really been enjoying it (so thanks!). However, I'm not as satisfied with the latest update.

Previously, Flameshot's tray/top bar icon immediately allowed you to select a region which popped up the nice purple box and all of the options. Now it seems that clicking the icon takes a whole screen capture, and all of the cropping and editing functionality is hidden behind the Share button/option.
Not only is this less convenient, but it's much less clear for users, in my opinion. Previously, clicking the icon immediately got you the description box that directed users to select a region, after which the intuitive icons would appear. Even as somebody who used Flameshot for quite a while, this new update appeared to remove almost all the functionality (when in reality it was hidden behind Share). As an example of how unclear things are, my first instinct was to search in Options (where crop would usually be in other programs, for example) to no avail, and only clicked on Share out of desperation.

Perhaps my use case is odd, or perhaps I'm missing how the new user workflow is better or more intuitive. In either case, please let me know what I've missed.

I see in #2095 that  v0.10.2 is a quick fix, but I'm hoping all these reversions are either somehow my fault, or are very temporary.

Also, the new system notifications don't appear to be as well integrated, but that's a minor gripe I can live with.

### Steps to reproduce

1. get Flameshot via pacman `$ sudo pacman -S flameshot`
2. compare workflow, functionality, and aesthetic of installed version to those advertised on website (v 0.10.0)

### System Information

1.
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```
2.
```
Orientation: Landscape
Resolution: 1920 x 1080 (16:9)
Refresh Rate: 60.03 Hz
Scale: 100%
```
3. Desktop Environment / Window Manager: GNOME with Pop Shell Tiling; Wayland

**Comment by borgmanJeremy** [comment]
Please see the pinned issue. This is caused by gnome not us.

**Comment by borgmanJeremy** [comment]
Thanks for the feedback, if I have time ill try to summarize it more concisely and pin that.
