### ISSUE TITLE
"Save image after copy" ignores the --path launch flag.

### ISSUE THREAD

**Issue by Rakqoi** [flameshot-org/flameshot#2133]
### Flameshot Version

Flameshot v0.10.2 (cda5a0f1)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Garuda Linux

### Description

I have configured a global shortcut to create a new directory named after the current month, and then use the directory as the path for launching Flameshot, [as described in this issue.](https://github.com/flameshot-org/flameshot/issues/510#issuecomment-860043364)

I have noticed, however, doing this only updates the configured save path when I save the image with Ctrl+S, and it uses the previously set directory when copying the image to the clipboard using Ctrl+C, with the option "Save image after copy" enabled.

Saving an image (Ctrl+S) *does* update the path, and copying an image (Ctrl+C) afterwards uses the new, updated path.

In my use case, I always copy the captured images to my clipboard and I never save them without copying. This becomes an issue when a new month begins, and Flameshot will continue to save screenshots to the previous month's folder, until I remember to "save" an image to update the path, or just manually change the save path.

Expected behavior:
Saving a screenshot through the "Save image after copy" setting should use the path provided by `flameshot gui -p <path>`.

### Steps to reproduce

1. Create a new directory somewhere.
2. Configure Flameshot to "Save image after copy".
3. Launch Flameshot through the command `flameshot gui -p <path to directory created in step 1>` and select a region.
4. Use Ctrl+C to copy the image to the clipboard.
5. Screenshot will save to whatever directory was previously configured, ignoring the argument provided in the launch command.

### System Information

```
System:
Kernel: 5.15.5-zen1-1-zen x86_64 bits: 64
Desktop: KDE Plasma 5.23.3 Distro: Garuda Linux
Graphics:
Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 495.44
Display: x11 server: X.Org 1.21.1.1 driver: loaded: nvidia resolution:
1: 1920x1080~60Hz 2: 2560x1440~144Hz
OpenGL: renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 495.44
```

**Comment by veracioux** [comment]
Your proposal can't really be applied to the newest development version of flameshot (which will be released in v11 soon). Right now when you call `flameshot gui` with one of the `--path`, `--clipboard`, etc options, the only thing you get is an accept button and corresponding shortcut (save, copy, upload etc don't even show up in the gui).

One thing you could do is use `flameshot gui -p <path> -c` and then click the accept button (or shortcut, which is Enter by default, unless your config has it already bound to something). The downside to this is that if you decide that you want to upload or pin the screenshot instead, you must relaunch `flameshot gui` without arguments, or by passing `--upload` or `--pin` respectively. Maybe there is a nice way to resolve this, but can't think of one right now.

You can test this out by installing the [development version](https://flameshot.org/docs/installation/development-build/), or waiting for the v11 release.
