### ISSUE TITLE
Enable lzo compression for Snap package

### ISSUE THREAD

**Issue by the-spyke** [flameshot-org/flameshot#2136]
### Feature Description

Current Snap package uses default `xz` compression which leads to very slow cold start times. Snap provides much better option:

```yaml
compression: lzo
```

1. https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm
2. https://snapcraft.io/blog/why-lzo-was-chosen-as-the-new-compression-method
3. https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714

**Comment by borgmanJeremy** [comment]
Sure I have no problem with this change. However, our snap is currently failing to publish because we are using an "experimental" framework. I moved to this newer version of KDE framework to fix a few bugs. All in all snap packaging has been harder than I expected :(

**Comment by borgmanJeremy** [comment]
Fixed in #2250. Will make it to the stable channel tonight or tomorrow.
