### ISSUE TITLE
"flameshot gui" runs GNOME screenshot tool 

### ISSUE THREAD

**Issue by wait-what** [flameshot-org/flameshot#2143]
### Flameshot Version

Flameshot v0.10.1 (f5bbf73c)
Compiled with Qt 5.15.2
https://aur.archlinux.org/packages/flameshot-git/

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux x86_64 / 5.15.5-zen1-1-zen

### Description

Running `flameshot gui` starts `gnome-screenshot` instead of the Flameshot GUI

### Steps to reproduce

1. Start GNOME 41.1 on Wayland
2. Start the `flameshot` daemon and keep it running
3. Run `flameshot gui`

Expected:
Flameshot GUI opens and you can take your screenshot

Result:
1. Screens blink white (gnome screenshot behaviour)
2. Gnome screenshot tool previews the taken screenshot of all displays
3. Flameshot never did anything

### Screenshots or screen recordings

![Screenshot from 2021-12-03 16-32-23](https://user-images.githubusercontent.com/25844213/144619829-9271aa8f-8679-423c-b8cd-49b4d4a748b9.png)

### System Information

Operating system and version
Up to date Arch Linux x86_64

Monitor configuration
Two monitors side-by-side

DE
GNOME 41.1 on Wayland

**Comment by wait-what** [comment]
Would you mind to elaborate?

**Comment by borgmanJeremy** [comment]
This issue is pinned to the top of the issues and gets submitted as a duplicate like twice a day.

It's also NOT flameshots fault so it's driving me crazy.

**Comment by wait-what** [comment]
It doesn't mention anything about gnome-screenshot starting, but rather nothing happening at all.

I guess it's related then.

**Comment by mmahmoudian** [comment]
@wait-what in short, Gnome decided to treat their own applications as privileged and special and started limiting other applications. In the pinned post you can find a link yo their gitlab and the discussion under in which they say why they are doing this. In that thread you will read that they have made a private (read privileged) API for their own applications and are forcing all other softwares to use a "public API" which means every other application will suffer.

If you have any complaints, I strongly suggest you as a Gnome user to take it to the gnome devs and make your voice heard. We and no one else outside of Gnome can affect or alter the situation.

Situation in one sentence: Our hands are tied by Gnome people.
