### ISSUE TITLE
Flameshot Snap

### ISSUE THREAD

**Issue by CWM030** [flameshot-org/flameshot#2147]
### Flameshot Version

0.10.1

### Installation Type

Snap from Snapcraft

### Operating System type and version

Debian 11 Cinnamon DE

### Description

Cannot select folder of choice

### Steps to reproduce

When changing the location to save screenshots 
it just keeps asking you to pick a folder over and over again

For instance I want to use:
~/home/chris/Flameshot Screenshots
or
~/home/chris/desktop

but while in the file chooser I click /home
and then the Flameshot folder
but then the select button greys out.

As in it wants you to pick yet another directory?

No matter how many directories you make or how deep they are, its still asking for another folder.

Same thing happens with selecting desktop

I don't understand why I can't select the folder of my choice?
Even selecting to use a fixed location, the same thing I said above happens. 

### System Information

Debian 11 

1920 x 1080
60 Hz

Cinnamon Desktop

Muffin Window Manager

xorg

**Comment by borgmanJeremy** [comment]
This is a bug in the version of Qt/GTK that is used in our base snap image. 

I have already migrated the snap to a new base, but its still "experimental" so I can't actually release it on snapcraft. I'm honestly considering dropping snap as a supported package because it takes disproportional amount of maintenance compared to flatpak.

**Comment by CWM030** [comment]
Does the flatpak have the same issue as the snap?

Thanks, 
Chris

⁣Get BlueMail for Android ​

**Comment by borgmanJeremy** [comment]
I don't think so, but I dont run the flatpak daily

**Comment by mmahmoudian** [comment]
@CWM030 I don't have Flameshot installed via either Snap or Flatpak, but one thing is certain, we never got any of such issues reported by Flatpak users.

**Comment by borgmanJeremy** [comment]
I checked again today and we still cant release the fix. The core20 kde-neon extension is still experimental, and I cannot enable this in their CI: 

https://forum.snapcraft.io/t/this-extension-may-be-enabled-with-the-enable-experimental-extensions-parameter/27603/3

**Comment by CWM030** [comment]
On Mon, 27 Dec 2021 06:38:15 -0800
borgmanJeremy ***@***.***> wrote:

> I checked again today and we still cant release the fix. The core20
> kde-neon extension is still experimental, and I cannot enable this in
> their CI: 
> 
> https://forum.snapcraft.io/t/this-extension-may-be-enabled-with-the-enable-experimental-extensions-parameter/27603/3
> 
> 

I see... Thanks for the follow up

Please keep me informed

Chris

**Comment by borgmanJeremy** [comment]
Good news. I learned now to manually upload a snap built with the proper extensions. There is a partial working version on the edge channel but version 11 will make it to stable tonight or tomorrow.
