### ISSUE TITLE
apt install flameshot installs v. 10.1 and not 10.2

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#2148]
### Feature Description

I try to install v. 10.2 with apt install flameshot, but it installs 10.1, why is that?

Then I downloaded 10.2 AppImage to ~/Applications/Flameshot
I get this error:
```
Failed to get information about the latest version.  "Host api.github.com not found"

```

Plus, I'm not able to configure system custom shortcut for screenshoting via flameshot.

![image](https://user-images.githubusercontent.com/1093841/145274837-800521a1-66b5-437a-ab9e-159d04dc918d.png)

**Comment by borgmanJeremy** [comment]
Version 11 will be in beta testing by the weekend. Please see the pinned issue for the discussion, but I am not planning to fix the versioning issue on 10.2
