### ISSUE TITLE
Can't start flameshot

### ISSUE THREAD

**Issue by VG08** [flameshot-org/flameshot#2154]
### Flameshot Version

v0.10.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

arch linux

### Description

the problem I am having is that when i run `flameshot gui` it does nothing and exits instantly and when I do `flameshot` it gives me this error 
`QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
`

### Steps to reproduce

I don't remember doing anything special because of this is happening but it is giving me what I told above.

### Screenshots or screen recordings

![maim-region-20211210-084328](https://user-images.githubusercontent.com/71305756/145511198-25e403d8-8927-419b-8d95-6465095f5e31.png)

### System Information

I am using arch linux. dwm with xorg

**Comment by mmahmoudian** [comment]
@VG08 dwm does not ship with two important things: notification manager and systray. There is a patch for systray and for notification you can install something like dunst.

But if you really don't want to have these on your system, you can turn off the systray and notifications options in the Flameshot config before launching flameshot.

If you have sort them out (either by installing or disabling) and you still have issues, please try the following and give us the output:

1. Open two terminals
2. In the first one run
```sh
pkill flameshot
flameshot
```
3. In the second terminal run
```sh
flameshot gui
```

**Comment by VG08** [comment]
@mmahmoudian so I have notifs through Dunst and no systray srtip

**Comment by VG08** [comment]
@mmahmoudian I have dunst for for notifs no systray tho, I did what you said and flameshot gui opens up flameshot, I actually thought that `flameshot gui` runs without flameshot running in bg, also I used trayer to check for systray and flameshot shows up there, also sorry for late reply.

**Comment by mmahmoudian** [comment]
@VG08 in newer version the idea is to reduce dependency to dbus and therefore much much less need for background process.

**Comment by VG08** [comment]
oh ok thanks, imma put ```flameshot``` into my startup
