### ISSUE TITLE
Flameshot icon is visible in tray area but when I click on it nothing happens

### ISSUE THREAD

**Issue by kubaorlen** [flameshot-org/flameshot#2155]
### Flameshot Version

Flameshot 0.10.2-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux, Kernel Version: 5.15.5-arch1-1 (64-bit)

### Description

I followed the instructions from official site.

Link: [https://bin.snopyta.org/?7888e03143504f37#DMBtqbWjWzqnydMqk8MvToGxaWAwNMbnyCbScZ9DxvfQ](url)

### Steps to reproduce

When I click on icon in system tray nothing happens, also there is no output during starting `flameshot gui` in terminal.

### System Information

Operating System: `Arch Linux`
KDE Plasma Version: `5.23.4`
KDE Frameworks Version: `5.88.0`
Qt Version: `5.15.2`
Kernel Version: `5.15.5-arch1-1 (64-bit)`
Graphics Platform: `Wayland`
Processors: `8 × AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx`
Graphics Processor: `AMD Radeon Vega 10 Graphics`

**Comment by mmahmoudian** [comment]
I can't think of a reason why this is happening. What I can suggest is that you can try to install using AUR ([flameshot-git](https://aur.archlinux.org/packages/flameshot-git/)) as it builds from master branch of this git repo and you almost get what will be soon released in v0.11.0 (we are releasing it this weekend)

**Comment by kubaorlen** [comment]
I installed` flameshot-git` from AUR. After running command `flameshot gui` I get this output `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

**Comment by etircopyh** [comment]
> `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

This doesn't have anything to do with your problem. It's just something Qt Wayland platform warns you about when you use wayland.

**Comment by kubaorlen** [comment]
Idk, no idea why program is not working.

**Comment by mmahmoudian** [comment]
@kubaorlen why did you close the issue? Is it resolved?
