### ISSUE TITLE
`--version` out of sync against release tag

### ISSUE THREAD

**Issue by johnrichardrinehart** [flameshot-org/flameshot#2159]
### Flameshot Version

v0.10.2

### Installation Type

Compiled from source

### Operating System type and version

linux-x86_64

### Description

https://github.com/flameshot-org/flameshot/blob/8ab1ac0eaad8fa958d9d342fed9988e502013dc0/CMakeLists.txt#L4

### Steps to reproduce

1. `flameshot --version`
2. Should be `v0.10.2`, but is `v0.10.1`

### System Information

NixOS in a VirtualBox VM :(

**Comment by borgmanJeremy** [comment]
That version is released on a maintenance branch only. The main branch includes the same fix

**Comment by johnrichardrinehart** [comment]
I'm sorry. I don't understand. `2bf8a92e700781a36d2cd85d3c34dc275edf28a6` has `v0.10.1` in `CMakeLists.txt` but is `git tag`ged as `v0.10.2`. This is expected?
