### ISSUE TITLE
Gyazo upload support

### ISSUE THREAD

**Issue by ash-f** [flameshot-org/flameshot#2164]
### Feature Description

Would be nice if you could support Gyazo which allows unlimited upload on the free plan.
https://gyazo.com/

API
https://gyazo.com/api/docs

**Comment by mmahmoudian** [comment]
@ash-f isn't this a duplicate of #2149?

**Comment by ash-f** [comment]
Yes.

**Comment by mmahmoudian** [comment]
@ash-f thanks. Please always search in the issues to see if anyone else has suggested the feature or the bug you are reporting.
