### ISSUE TITLE
"Return" keybind to upload to Imgur does not work 

### ISSUE THREAD

**Issue by isak102** [flameshot-org/flameshot#2166]
### Flameshot Version

flameshot 0.10.2-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

5.15.7-arch1-1

### Description

As stated in the documentation you should be able to hit Return to upload the screenshot directly to Imgur, but this doesn't work for me. I can't see any entry to change the keybind in the `flameshot config` interface either.

![15-12-2021_19-20](https://user-images.githubusercontent.com/90389894/146243687-f6e8aba7-56a2-4f0e-bfba-93920b28f04c.png)

This is my configuration file:
```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x11\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\xe\0\0\0\x11)
contrastOpacity=191
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=10
filenamePattern=%d-%m-%Y_%H-%M
ignoreUpdateToVersion=0.10.2
savePath=/home/isak102/screenshots
savePathFixed=true
setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
showDesktopNotification=true
showHelp=false
showSidePanelButton=false
showStartupLaunchMessage=false
startupLaunch=false
uiColor=#078a00

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

### Steps to reproduce

1. run `flameshot gui`
2. select area
3. press Enter

### System Information

1. Arch Linux `5.15.7-arch1-1`
2. 
![image](https://user-images.githubusercontent.com/90389894/146244325-17d6efa2-8c00-4789-82d6-02b7a45353b4.png)
3. i3-gaps, Xorg

**Comment by veracioux** [comment]
@isak102 Should be fixed in the newest master commit. You can download the newest build from [here](https://flameshot.org/docs/installation/development-build/).
