### ISSUE TITLE
unable to provide the output file name using the --path option

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#217]
**Describe the bug**
flameshot only accepts path names ending in directory names and not file names in the ``-p`` option.

**To Reproduce**
```
$ flameshot full -p /home/user/screen.png -d 100
Invalid path, it must be a real path in the system. See 'flameshot --help'.
```

**Expected behavior**
flameshot should figure out whether argument given to ``-p`` ends in a directory or a file name and act accordingly. It should also overwrite files if the given file name is the same as the file already present in that directory

**Desktop (please complete the following information):**
 - Arch Linux Linux 4.14.40 x86_64
 - 0.5.1

**Comment by JohnTheDaniel** [comment]
Any news on this issue?

**Comment by beanaroo** [comment]
This would be very useful for using flameshot programmatically.
In my case, I have a simple screen locking script that takes a screenshot of the desktop before processing it further (blur and/or pixelize) and using it as the lock screen.

**Comment by ANGkeith** [comment]
Hello,  heres a quick workaround using redirections:
`flameshot gui -p /tmp -r > /home/user/screen.png`

**Comment by ChTBoner** [comment]
Here's what I do:
`flameshot full -r > ${HOME}/screen.png`

But yeah, flameshot man page and error message are not really helpful here.

**Comment by kevr** [comment]
Are you folks accepting PRs for this issue? I'd love to use `flameshot`, but this is just.. too much. Might as well use `scrot`.

**Comment by veracioux** [comment]
#1784 would address this issue. It is still awaiting discussion.
