### ISSUE TITLE
cannot grab color on linux

### ISSUE THREAD

**Issue by godalming123** [flameshot-org/flameshot#2172]
### Feature Description

It appears that flameshot has a color grabber but as far as I can see there's no way to see the hex code of the color which is all I want to know. I open the tool by running ```flameshot gui``` then open the tool settings panel on the left and click grab color I click on the on screen color, see my color appear perfectly as the active color but with no obvious way to copy it. And if flameshot is copying it to my clipboard (which it is'nt I've checked my clipboard) it should send a notification about it.

**Comment by veracioux** [comment]
@godalming123 The newest development version of flameshot (which will soon be released as v11) includes the hex code which you can edit or copy to clipboard, and the color grab mechanism is also improved. You can download a build from [here](https://flameshot.org/docs/installation/development-build/).

**Comment by godalming123** [comment]
have a great experience with flameshot 11 keep up the good work!
