### ISSUE TITLE
Closing pinned image closes the daemon

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#2181]
### Flameshot Version

Built from latest master: 960710

### Installation Type

Compiled from source

### Operating System type and version

M1 Air Monterey

### Description

When I pin an image and close the pin, the daemon stops. 

### Steps to reproduce

Run flameshot from CLI. 
Pin an image
Double click to close pin

### System Information

Flameshot v0.10.1 (96071020)
Compiled with Qt 5.15.2
darwin: 21.2.0
osx: 12.1

**Comment by borgmanJeremy** [comment]
@veracioux  I bisected the code and this was introduced in #2003 (203b5ba)

Any ideas what could be causing this? Copy and Upload do not cause the daemon to close, just closing the final pinned image.

**Comment by veracioux** [comment]
If you have `autoCloseIdleDaemon=true` in your config, then this is expected behavior.

**Comment by borgmanJeremy** [comment]
Shouldn't the same behavior apply to upload?

**Comment by veracioux** [comment]
@borgmanJeremy No. Upload is handled by the active gui instance, not through the daemon.

**Comment by borgmanJeremy** [comment]
Actually the bug is present irrespective of the setting. It is also reproducible on linux.
![Peek 2021-12-23 10-25](https://user-images.githubusercontent.com/46930769/147267468-0caa4e7e-161c-4373-a535-bab2afdd91f0.gif)

**Comment by veracioux** [comment]
Will take a look then.

**Comment by borgmanJeremy** [comment]
I think the bug is here. My sense is that the bug is related to the !instance() function, however, I need to step away for a few hours. I can come back to it later if you haven't already solved it.  I would expect the first if to be taken because m_persist is true, but need more time to figure out the intention of the instance() function. 

```
void FlameshotDaemon::quitIfIdle()
{
    if (m_persist && !instance()) {
        return;
    }
    if (!m_hostingClipboard && m_widgets.isEmpty()) {
        qApp->exit(0);
    }
}
```

**Comment by veracioux** [comment]
@borgmanJeremy I'll take a stab at it.

**Comment by veracioux** [comment]
The `instance` method is now documented.
