### ISSUE TITLE
Using gnome with HDMI Screen & Wayland with increased 150% scaled can capture only top-left 1/3rd of screen

### ISSUE THREAD

**Issue by theitguynumber1** [flameshot-org/flameshot#2193]
I installed fameshot on a PC with no display but connected to HDMI. 
Increased display scare to 150%. Taking screenshot is only possible for the 1/9th (1/3rd from top and 1/3rd from left) of the screen. 

Screenshot (taking with printscreen rather) of the normal screen: 

![Screenshot from 2021-12-27 10-43-23](https://user-images.githubusercontent.com/33011744/147422628-0c8b05e3-7fcc-40a8-8b5d-1e37b47952f8.png)

Screenshot when flameshot is activated to take snap (see how it is increased in size and not possible to go beyond down or right): 

![Screenshot from 2021-12-27 10-43-07](https://user-images.githubusercontent.com/33011744/147422631-0bd9dbe1-a68b-4666-bd08-c8cf6113e06a.png)

**Comment by theitguynumber1** [comment]
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish


$ uname -a
Linux TV-Desktop 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ grep -i wayland /etc/gdm3/custom.conf 
#WaylandEnable=false

**Comment by borgmanJeremy** [comment]
I'm on mobile so I dont have the issue number handy, but if you search "fractional scaling" in our issues you will find a detailed description of this issue and where we are at.

**Comment by theitguynumber1** [comment]
Yes - thanks. 

https://github.com/flameshot-org/flameshot/issues/564

[https://github.com/flameshot-org/flameshot/issues/564](url)
