### ISSUE TITLE
Flameshot stucks in i3

### ISSUE THREAD

**Issue by ethan-rod6** [flameshot-org/flameshot#2194]
### Flameshot Version

v.0.10.2

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux 2021

### Description

I have installed flameshot in Arch linux and it worked perfectly. But when I switched to i3 window manager I can't use clipboard feature. However I can use the other features. When I clicked on clipboard option my pc stucks. Any idea on this?

### System Information

Linux 5.15.11-zen1-1-zen GNU/Linux

**Comment by borgmanJeremy** [comment]
Try using the version 11 beta we just released. This sounds like you are missing a notification manager. We made this more optional in version 11.

Alternatively disable notifications in flameshot or install something like dunst.

**Comment by ethan-rod6** [comment]
I installed the version 11 now and still it's same. But I'm getting this error now.
`flameshot: error: The configuration contains an error. Falling back to default.`

**Comment by borgmanJeremy** [comment]
Open the config menu and it will tell you which line has the error

**Comment by ethan-rod6** [comment]
I'm sorry. I dont know how to open it

**Comment by borgmanJeremy** [comment]
Right click the tray icon and hit config or from the cli type 

flameshot config

**Comment by ethan-rod6** [comment]
But it doesn't have any logs. I mean errors.

**Comment by borgmanJeremy** [comment]
![image](https://user-images.githubusercontent.com/46930769/147616010-f8963ba6-847a-4ad0-aa12-43c6555af18b.png)

**Comment by ethan-rod6** [comment]
I don't have that option

**Comment by borgmanJeremy** [comment]
Hmmm you are sure it's version 21?

**Comment by ethan-rod6** [comment]
yeah I installed it now, with yay

**Comment by borgmanJeremy** [comment]
ok weird, you can post your config and I'll look at it to see why that dialog is not appearing.

**Comment by ethan-rod6** [comment]
This is my `flameshot.ini`, I guess this is what you want
```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x13\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\xe\0\0\0\x11)
contrastOpacity=188
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=3
savePath=/home/dead/Pictures
savePathFixed=false
setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
showStartupLaunchMessage=true
startupLaunch=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Comment by borgmanJeremy** [comment]
The offending line is setSaveASFileExtension

Not sure why you are not seeing that dialog box, I tested on the same commit as you and I see it.

**Comment by ethan-rod6** [comment]
Urghhhhhhhhhhh. These days are bad for me. First this and now my wm isn't working properly

**Comment by borgmanJeremy** [comment]
Sorry to hear that. Join the dark side on kde plasma 😁

**Comment by mmahmoudian** [comment]
For those who have the same issue and didn't understand what to do, change this line:

```ini
setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
```

To:

```ini
setSaveAsFileExtension=png
```

-------

@borgmanJeremy do you want to keep this open?

**Comment by borgmanJeremy** [comment]
I think it can be closed
