### ISSUE TITLE
Update release versions for Ubuntu 18 and 20.

### ISSUE THREAD

**Issue by omkarnathsingh** [flameshot-org/flameshot#2195]
### Flameshot Version

v 0.6.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20

### Description

We have still v0.6.0 available from apt package manager for Ubuntu 20.04. Please update it to have latest stable versions.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/12734027/147478587-1eeaa980-c6fa-4a9a-812e-64f9a2c4571c.png)

_No response_

### System Information

Ubuntu 20.04.

**Comment by borgmanJeremy** [comment]
You need to file this with Ubuntu, we do not control what they ship. I recommend installing our flatpak.

**Comment by omkarnathsingh** [comment]
Even flameshot versions are not updated. Is there no control from dev side?

**Comment by borgmanJeremy** [comment]
No it's up to your software distributor (that's actually why it's called a distro, it's thier job to package and distribute the software).

Again you can install from flathub which I do keep up to date.

**Comment by hosiet** [comment]
I shall let you know that actually *no one* is controlling flameshot package in Ubuntu. I can partially influence the future Ubuntu versions by packaging in Debian side, but flameshot in published Ubuntu is not taken care of by anyone; we need a interested Ubuntu Developer to take care of them, which does not exist yet.
