### ISSUE TITLE
Black and white colors in the color picker

### ISSUE THREAD

**Issue by plastboks** [flameshot-org/flameshot#22]
Hey, great app!

Would you consider adding _white_ and _black_ colors to the color-picker-wheel-thingy?

Sometimes I want to remove text or graphics from my screenshots, and the available colors make this a bit awkward.

**Comment by lupoDharkael** [comment]
I plan to add a menu in the configuration window where you can edit the colors of that widget.

**Comment by lupoDharkael** [comment]
Yes, it will be implemented soon™, I'm just kinda busy with life stuff and working on other projects.

**Comment by wjtk4444** [comment]
Still WIP? Can't find it anywhere in options.

**Comment by hosiet** [comment]
@wjtk4444 Currently you may use the color picker in the sidebar to choose white and black.

**Comment by wjtk4444** [comment]
@hosiet I had no idea flameshot had sidebar. Great, thanks.

**Comment by VasoVV** [comment]
Still no success (
```
 flameshot -v
Flameshot 0.6.0+git20190714-1(Debian)
Compiled with Qt 5.12.4
```

**Comment by LoLei** [comment]
> @wjtk4444 Currently you may use the color picker in the sidebar to choose white and black.

Press `space` to open the sidebar in case you were confused like me.

**Comment by ninovanhooff** [comment]
Can the sidebar store presets? It seems to indicate so since it shows a list with the entry <empty>

**Comment by MarcoIeni** [comment]
You can customize colors in your ini file. For example, add the following line:
```
userColors=#800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, #ffffff, #000000
```

Anyway I agree that black and white should be there by default.

**Comment by Malorn44** [comment]
adding the above to my ini file breaks flameshot

**Comment by borgmanJeremy** [comment]
Since the color picker is now added through the spacebar I think that is a good balance of simplicity in the color wheel, and customizability in the color picker.

**Comment by xstable** [comment]
@borgmanJeremy It's nice that there is a color-picker, but it solve not this request. 
Black and white are used so often, that it should be available by right-click.
The need to open color-chooser and choose black or white is time-consuming ... even if you very often need this general color.

**Comment by mmahmoudian** [comment]
@xstable It has been already discussed and you could have land on the correct thread by searching through issues. For example in #720 it has been mentioned that you can add any color you want to the color wheel by adding a line to your config file. For example in your case add the following line under the `[General]` section of `.config/flameshot/flameshot.ini` to literally add the white and black:

```ini
userColors=#800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, white, black
```
