### ISSUE TITLE
Flameshot Ubuntu screen zoom 1.25%

### ISSUE THREAD

**Issue by bksubhuti** [flameshot-org/flameshot#2203]
### Flameshot Version

0.9+ds1-2 debian
QT 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

gnome ubuntu 21.10

### Description

display size 100% works fine
display size 125% flashes black screen on and off.

### Steps to reproduce

set display size 125%
run flameshot

### Screenshots or screen recordings

none

### System Information

ubuntu gnome 21.10
xorg

**Comment by mmahmoudian** [comment]
Isn't this duplicate of #564?

**Comment by bksubhuti** [comment]
yup
