### ISSUE TITLE
Copy to clipboard button or Ctrl+C 

### ISSUE THREAD

**Issue by JackieMium** [flameshot-org/flameshot#2210]
### Flameshot Version

`flameshot-11.0.rc1-1.debian-11.amd64.deb`

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Debian sid with Xfce4 as DE

### Description

After upgrade from `flameshot-0.10.2-1.debian-10.amd64.deb` to `flameshot-11.0.rc1-1.debian-11.amd64.deb`, launching regional screenshot in terminal with `flameshot gui -r` or any other `flameshot gui ` command with an arguement/arguements such as `-p /path/to/file` will randomly make the copy screenshot to clipboard button disappear and Ctrl-C stops working (about 50-50 chance it will/won't work). But this doesn't seem to happen by clicking the tray icon. I tried the package from Debian repository and GitHub deb packages. But after downgrade from 11.0-rc1 to 0.10.2 the issue goes away. 

### Steps to reproduce

1. Run `flameshot gui -r` in terminal;
2. Clink `Copy` button or press Crl+C;

### System Information

System: Debian sid with Xfce4 as DE, Xorg backend.

**Comment by borgmanJeremy** [comment]
When you say randomly, do you mean:

1.) It seems random which arguments cause copy to disappear?
2.) The same set of arguments will on occasion make the copy button to disappear?

**Comment by JackieMium** [comment]
@borgmanJeremy 2). Same sets of arguements sometimes lead to the issue and sometimes not.

**Comment by borgmanJeremy** [comment]
Okay, I'll get a debian unstable VM set up.

**Comment by borgmanJeremy** [comment]
Can you please also upload your config file at /home/<user>/.config/flameshot/flameshot.ini

**Comment by JackieMium** [comment]
@borgmanJeremy will do that tomorrow when I am with my computer.

**Comment by JackieMium** [comment]
> Can you please also upload your config file at `/home/<user>/.config/flameshot/flameshot.ini`

I installed `flameshot-0.10.2-1.debian-10.amd64.deb` this morning and confirmed the issue doesn't exist, Then quit flameshot, delete `~/.config/flameshot/flameshot.ini` and upgraded to `flameshot-11.0.rc1-1.debian-11.amd64.deb` again, the issue appeared. This is `~/.config/flameshot/flameshot.ini` (should be default configs):

```
[General]
disabledTrayIcon=false
drawColor=#ff0000
showStartupLaunchMessage=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Comment by veracioux** [comment]
@JackieMium When using flameshot 11.0, and calling it as `flameshot gui -r` and with the other offending arguments (`-p`, `-c`, etc), does an *Accept* button appear? It looks like this:

![image](https://user-images.githubusercontent.com/29044423/147850477-7168d751-81bb-44a8-a3db-9d6d37d47803.png)

**Comment by JackieMium** [comment]
@veracioux  Yes, the *Accept* button does apear and seems to work (clicking it does copy screenshot to clipborad with `-c`, and save to file with `-p`). But both `-c` and `-p` arhuement result in garbage output in terminal like this:

![image](https://user-images.githubusercontent.com/12944832/147851752-5fb7951c-4b90-416b-b226-65c078b5a50d.png)

Looks like raw binary data or metadata to me.

**Comment by veracioux** [comment]
@JackieMium But the exact purpose of the `-r` option is to print the image to stdout, which is a binary datatype. So there is no problem there.

Also, in your comment you say the binary output appears when you use `-c -p`, but in the screenshot you use `-r -c`. Is that a typo?

**Comment by JackieMium** [comment]
@veracioux hah sorry, I misunderstood the meaning of `-c` before, it's working if I don't add a `-r` arguement now. So now the problem becomes: I have a keyboard shortcut calling `flameshot gui -p /path/to/screenshots` and I could still copy without saving a file in the past, but now version `11-rc` doesn't support that as the *Copy* button disappears with `-p`, and with `-c -p` there is only *Accept* but no *Copy* either but clinking *Accept* saves and copy. Is this an expected behavior change?

**Comment by veracioux** [comment]
@JackieMium This is intended behavior. When you specify an action using the CLI options, you don't get to choose additional actions, only to accept the screenshot with the actions from the CLI. This behavior is due to some limitations in how flameshot works currently. I have been toying with some ideas to work around this, and I will propose to include them in the next release (v12).

**Comment by JackieMium** [comment]
@veracioux OK, got it. Thanks for your classification.

**Comment by mmahmoudian** [comment]
@veracioux @JackieMium should we consider this issue closed?

**Comment by JackieMium** [comment]
@mmahmoudian Yes, please do that.
