### ISSUE TITLE
Please allow saving as PDF

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#2215]
### Discussed in https://github.com/flameshot-org/flameshot/discussions/2205

<div type='discussions-op-text'>

<sup>Originally posted by **elad2109** December 30, 2021</sup>
Often time I have to save as a PDF.</div>

**Comment by veracioux** [comment]
I'm not against adding this as an option, if the implementation is not too difficult (right now I don't have a sense if it is or isn't). If you know C++ and Qt, you are welcome to contribute. @mmahmoudian @borgmanJeremy What do you think?

**Comment by mmahmoudian** [comment]
I personally think we severely lacking vector graphics output (SVG, PDF, ...). This has been discussed before and NC was also in favour of it. I just don't know how much extra work it needs to have both SVG and PDF.

**Comment by borgmanJeremy** [comment]
SVG is a good idea since it would be a good format to resume editing. Pdf is a bit annoying because it's a hack onto the way we populate other file's.

It would be better to add printing and let the system handle print to pdf so we do t need to start talking about page size, rotation, scaling, etc

**Comment by mmahmoudian** [comment]
I guess when we have the svg, turning that into pdf would be straightforward either by us, through printing, or by a plugin.

**Comment by borgmanJeremy** [comment]
Based on this discussion I think we should close this as there is already an issue for adding a printer. The more I think about PDF the less I want to add it because of the number of other features that need to go along with it.

**Comment by mmahmoudian** [comment]
@borgmanJeremy how about SVG? Adding layered SVG support would partially solve #2055 and #1515

**Comment by elad2109** [comment]
> 



> I guess when we have the svg, turning that into pdf would be straightforward either by us, through printing, or by a plugin.

Jודא

**Comment by elad2109** [comment]
> <img alt="@elad2109" width="20" height="20" src="https://avatars.githubusercontent.com/u/1093841?s=60&amp;v=4">

BTW SVG sounds a game changer. But how can it help the PDF printing? It sounds parallel to me. No?

**Comment by borgmanJeremy** [comment]
SVG I want to think about carefully as an save/resume format


Pdf will not be added natively due to the complexities I outlined above.
