### ISSUE TITLE
flameshot doesn't exit after uploading image

### ISSUE THREAD

**Issue by mohad12211** [flameshot-org/flameshot#2221]
### Flameshot Version

Flameshot v11.0.0 (9a5af9f1) (tested both on latest commit and flameshot-11.0.rc1) 
Compiled with Qt 5.15.2
linux: 5.15.12-arch1-1

### Installation Type

User repository (AUR), Using the ready-made package from Github Releases

### Operating System type and version

test on my archlinux (dwm) and linux mint 

### Description

if I run `flameshot gui` and select upload image, flameshot gui will not exist, which prevents me from running it again.

### Steps to reproduce

1. run `flameshot gui`
2. select upload image
3. flameshot doesn't exit and I can't run `flameshot gui` after that

### Screenshots or screen recordings

https://user-images.githubusercontent.com/51754973/147859834-c6b4b9fe-93a4-4126-b795-4520a9cbca9a.mp4

### System Information

tested on linux mint and archlinux, Xorg.
Archlinux using dwm as windows manger and no desktop environemnt.
linux mint cinnamon latest version

**Comment by veracioux** [comment]
@mohad12211 I'm on it!

**Comment by borgmanJeremy** [comment]
@veracioux can this be closed now?

**Comment by mohad12211** [comment]
I tried to reproduce the bug after the latest commit and it was solved, we can close this, Thank you

**Comment by mohad12211** [comment]
this commit [883e55c](https://github.com/flameshot-org/flameshot/commit/883e55c52db375a77b1343311f0f39a6a78cc600) introduced a new bug, the url is not copied correctly to the clipboard

**Comment by veracioux** [comment]
@mohad12211 Does #2246 fix it for you?

**Comment by mohad12211** [comment]
@veracioux yes it fixes it.

**Comment by SiddharthGuptaPyDev** [comment]
The issue still exists for me, how do I fix it. It takes around 10-15 second to print the 'save' message while the image gets saved way before. It takes the time for no reason
