### ISSUE TITLE
Could NOT find Qt6Designer (missing: Qt6Designer_DIR)

### ISSUE THREAD

**Issue by hexh250786313** [flameshot-org/flameshot#2224]
### Flameshot Version

try to run `yay -S flameshot-git`, then it logs `Could NOT find Qt6Designer (missing: Qt6Designer_DIR)` and build failed.

### Installation Type

User repository (AUR)

### Operating System type and version

5.10.89-1-MANJARO

### Description

try to run `yay -S flameshot-git`, then it logs `Could NOT find Qt6Designer (missing: Qt6Designer_DIR)` and build failed.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/26080416/148007370-81d327eb-966d-4d86-a273-1b74e74f548c.png)

### System Information

![image](https://user-images.githubusercontent.com/26080416/148007463-fb14e6c0-3490-4b75-8a4e-6a2fe0731a6e.png)

**Comment by hexh250786313** [comment]
It seems to be resolved after I ran `yay -S qt6-tools`. But I got a new error:

![image](https://user-images.githubusercontent.com/26080416/148009750-18b759d1-3c9d-4773-8ad6-73221c1a064d.png)

**Comment by mmahmoudian** [comment]
I can confirm this on one of my Manjaro machines.

**Comment by borgmanJeremy** [comment]
This is a weird issue where our embedded dependency defaults to Qt6, but flameshot defaults to Qt5 for now. The correct fix is to finish porting flameshot to Qt6. 

This will not be done for version 11, so I will "hack" the embedded dependency to use Qt5 until we finish the migration.

**Comment by borgmanJeremy** [comment]
Can you try building from this PR #2230 ? I can't replicate the problem on my Arch box so Im not sure that this fixed it.

**Comment by mmahmoudian** [comment]
@borgmanJeremy yeap it seems it works on my machine

**Comment by hexh250786313** [comment]
@borgmanJeremy It works for me

**Comment by borgmanJeremy** [comment]
Thanks for confirming! merged.
