### ISSUE TITLE
v11.0.rc1 has the wrong version number in source

### ISSUE THREAD

**Issue by johnrichardrinehart** [flameshot-org/flameshot#2225]
### Flameshot Version

v11.0.rc1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

NixOS

### Description

https://github.com/flameshot-org/flameshot/blob/v11.0.rc1/CMakeLists.txt#L4 has the wrong version tag.

### Steps to reproduce

1. Build flameshot from source having had checked out `v11.0.rc1`.
1. ```
    $ flameshot --version  
    Flameshot v0.10.1
    Compiled with Qt 5.15.3
```

### Screenshots or screen recordings

_No response_

### System Information

N/A

**Comment by borgmanJeremy** [comment]
Thanks, this is caused by how I generated the beta. I will update our releasing documentation to make it more fool proof.

**Comment by johnrichardrinehart** [comment]
@borgmanJeremy No worries!
