### ISSUE TITLE
V11.0 beta, Copy to clipboard / save shortcut doesn't work with flameshot gui --path

### ISSUE THREAD

**Issue by Racle** [flameshot-org/flameshot#2227]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

pop_os 21.10

### Description

Copying to clipboard (`ctrl+c`) doesn't work when using `flameshot gui --path ~/Pictures/`. It works as expected if used without `--path`.
Also saving (`ctrl+s`) doesn't work. You have to use `accept` button.
And there is no button to copy to clipboard.

This has been working with earlier versions which I have used.

### Steps to reproduce

1. Run  `flameshot gui --path ~/Pictures/`
2. Press `ctrl+c` and nothing happens

### System Information

pop_os 21.10, x11

**Comment by borgmanJeremy** [comment]
That is intended behavior with the new version. Before it was nebulous which tasks worked when called from the CLI. If you want to copy to clipboard AND save to a path, call it with both arguments from the CLI

```
flameshot gui --path <path> -c
```
Also FYI if you want it copied to your clipboard make sure the daemon is running in the background.

**Comment by Racle** [comment]
> if you want to copy to clipboard AND save to a path, call it with both arguments from the CLI

That's the thing, I want to choose, I don't need both 99.99% of the time. Old behavior worked just fine, new way feels much more like downgrade. And it's slower to press button than press shortcut key.

I have `prnt scrn` mapped to `flameshot gui --path ~/my_folder`. And I'm used to press `ctrl+c` when copying, `ctrl+s` when I want to save to disk. Most of the time I just want it copy to clipboard, but now and then I need that as file.

I personally have few shortcuts which I just apply to other machines via dconf load. And got few usernames so I cannot put fixed path to `flameshot.ini`. (this situation doesn't probably apply for lot of people.).

To fix this issue, I need to edit flameshot.ini for every machine and just use `flameshot gui`, which is extra work when old version just worked.

**Comment by borgmanJeremy** [comment]
You could instead select this option to get what you want I think:
![image](https://user-images.githubusercontent.com/46930769/148234401-697b899a-1d07-4fd9-851f-047bd7ca3b15.png)

 And then change your script to use -c instead.

**Comment by mmahmoudian** [comment]
@borgmanJeremy to my understanding @Racle wants to do either copy or save at every given screenshot, and the only reason they set the `-p` is because their username on different machines are different. I think one way to handle this is to use an environmental variable, assuming that one ca use such variable inside the `flameshot.ini` for the `savePath`. I cactually don't know if it is already supported.

**Comment by Racle** [comment]
@mmahmoudian is correct, I want to either save to custom path or copy to clipboard. I don't want images to waste my space when I do not need those. But I have situations where I cannot just paste image and need file.

> environmental variable, assuming that one ca use such variable inside the flameshot.ini 

That doesn't work. I tried to use `~/my_folder` and `$HOME/my_folder` earlier today.
If that gets supported, I could change my shortcut to be just `flameshot gui` and use `~` or `$HOME` in `flameshot.ini`

**Comment by borgmanJeremy** [comment]
I don't think we will be rolling the behavior back to the old way. I am really happy with the consistency this new design gives up. 

We have also discussed a couple times about path expansion and decided that should be handled by the shell and not flameshot, so I don't think we will do environmental substitution.

**Comment by Racle** [comment]
@borgmanJeremy 
> I don't think we will be rolling the behavior back to the old way. I am really happy with the consistency this new design gives up.

Are you saying you will remove the working behavior also from `flameshot gui` (which still has working shortcut keys)?

**Comment by mmahmoudian** [comment]
@Racle I agree with @borgmanJeremy that the new/current behavior is much more consistent and way less confusing. Also he is absolutely correct that path expansion would be a security issue as it has been discussed numerous times.

How about having a small `sed` command in your dotfiles to replace the `savePath=${HOME}/Pictures` to the expanded version in each of your systems upon boot?

**Comment by borgmanJeremy** [comment]
> Are you saying you will remove the working behavior also from flameshot gui (which still has working shortcut keys)?

No, its just when you call flameshot with a "terminal action" like copy to clipboard, save, pin, or upload. 

When you use the CLI, you can list multiple of these. The old method was a tossup for what worked and what did not.

**Comment by Racle** [comment]
> that the new/current behavior is much more consistent and way less confusing

@mmahmoudian I'm just confused, keeping the shortcut keys in `flameshot gui` but not in `flameshot gui --path` is much more consistent and way less confusing?

I personally feel that might confuse other people, as you have keys in configuration file but those doesn't work every time.

**Comment by mmahmoudian** [comment]
> Are you saying you will remove the working behavior also from flameshot gui (which still has working shortcut keys)?

No the `flameshot gui` works normally. The logic is when you define `--path`, ´--clipboard´, `--raw`, or `--upload`, you are selecting a final action. For that reason the faith of your screenshot is already decided and therefore there is only one "Accept" button.

**Comment by mmahmoudian** [comment]
@Racle 
> I personally feel that might confuse other people, as you have keys in configuration file but those doesn't work every time.

You are the second person since we have pre-released the version 11 that has brought this up and in the previous case the user had a setup in which he could easily adopt the change (didn't have path expansion complication). But I agree that there will be some initial confusion, but perhaps that can be upfront explained to the user.

Also as @borgmanJeremy mentioned, you can use any combination of "final action" when using the CLI. I myself have bound <kbd>prntscrn</kbd> to `flameshot gui` and I use the CLI flag when I need them specifically. In your case though, I see what the problem is and I believe the fastest and easiest way would be to use `sed` and rewrite the full path to the config file of each machine. This way you can get the functionality you want without being bothered to change the path every time manually. I can assist you to write the `sed` command.

**Comment by borgmanJeremy** [comment]
I will also update the release notes to make this more clear

**Comment by Racle** [comment]
@mmahmoudian That still does make it feel like downgrade rather than upgrade. Probably good thing that there isn't a ton of people who use it like I do, so that change doesn't affect so many people.

Changing config per machine is doable for me, I just need use `sed` on my initial installation script, so it shouldn't be too much trouble (first I need flameshot to generate config (ex. start daemon manually and wait 1s) and run `sed` after that)

And if there is other users who has this same issue, they probably find this thread and don't see this as bug as I did, but as on new intended behavior.

**Comment by veracioux** [comment]
@Racle What do you think about #2231?

**Comment by Racle** [comment]
So instead of running action immediately, you could toggle on/off your actions?

Good addition, personally I'll probably just change path with `sed` and run only `flameshot gui` as it's faster to press shortcut and finalize the action immediately that way (I rarely/ever need image to both disk and clipboard and I would be doing `ctrl+s` + `ctrl+c` a lot if they were toggle options with `-p`). 

But that should keep the shortcuts usable, which is little more consistent than without. And I would personally keep shortcuts on by default, but that just my personal preference. I like to use keyboard more than mouse for that kind of stuff, as I find it faster.

**Comment by mmahmoudian** [comment]
@Racle voinko lopetta tämä issue?

**Comment by Cretezy** [comment]
I'm using the following flameshot version (from AUR, flameshot-gui):

```
Flameshot v11.0.0 (42917930)
Compiled with Qt 5.15.2
```

When doing `flameshot gui`, selecting something, and hitting `Ctrl+C`, the image is no longer copied. I'm not using `--path` or `-c`.

**Comment by mmahmoudian** [comment]
@Cretezy this is intentional, please read the release notes of v11 or https://github.com/flameshot-org/flameshot/issues/2275#issuecomment-1015073816

**Comment by alkaris2** [comment]
I have to agree with @Racle this really feels like a huge downgrade and inconvenience to not have the buttons in the GUI to either just save or to just copy to clipboard. And it's for that reason I refuse to upgrade flameshot if this is the way you're going to force it in the most ass backwards way possible. What you could of done instead was include one other extra button to Save + Copy to Clipboard, not completely remove the Save Only and Copy to Clipboard Only options from the GUI.

**Comment by borgmanJeremy** [comment]
Please keep your comments civil

**Comment by mmahmoudian** [comment]
@alkaris2 perhaps you can benefit by reading this very short piece: 

https://flameshot.org/docs/advanced/commandline-options/#final-actions

You ***can*** do save **and** copy to clipboard at the same time! You can even do more than 2 actions, let's even add pin and upload to the mix:

```sh
flameshot gui --path ~/Pictures --clipboard --pin --upload
```

Now, if you still want to hang on to an older version, you neither need to have excuse nor have to explain yourself to anyone 😊 but have in mind that we only support our latest version. 😉
