### ISSUE TITLE
Set an Image Editor as Default Application in App Launcher

### ISSUE THREAD

**Issue by ilovefreesw** [flameshot-org/flameshot#2233]
### Feature Description

Right now, we have to select an app explicitly after opening a screenshot in an editor program, for example Kolourpaint. I always use this, so it would be nice/faster to open the current screenshot in Kolourpant in 1 click, means I only have to set it once, so the intermediate dialog window(to choose an application) won't appear.

![image](https://user-images.githubusercontent.com/77317006/148386990-70727ac7-8dce-4237-b9d9-a0dc67186737.png)

A checkbox can be added like shown above. And in case someone wants to assign some different program, then they can reset the app launcher settings. For that, a button can be added to the General tab in the Flameshot settings.

**Comment by mmahmoudian** [comment]
Isn't this duplicate of #2091?

**Comment by ilovefreesw** [comment]
Oh yeah... funny I did search for it and it didn't show up. Sorry...will close this.

**Comment by steinm** [comment]
On my system (Linux with xfce) the option "Set as default" doesn't show up. So, it might still be helpful to have an extra button for your personal upload tool.

**Comment by mmahmoudian** [comment]
@steinm this issue is closed because it was a duplicate, as I mentioned before. If you want to add to the discussion, you should post in an open issue.

As for your custom upload issue, please read:

https://github.com/flameshot-org/flameshot/issues/1734#issuecomment-884798959
