### ISSUE TITLE
Error starting application

### ISSUE THREAD

**Issue by wsalmeida** [flameshot-org/flameshot#2234]
### Flameshot Version

11.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Debian

### Description

When trying to launch an application through its graphical interface, application not executed generating an error message

### Steps to reproduce

run flameshot launcher

### Screenshots or screen recordings

![Captura de tela_2022-01-06_12-03-48](https://user-images.githubusercontent.com/38542279/148403450-0a92ca81-db8c-4718-9bd0-ac22877dc95b.png)
![Captura de tela_2022-01-06_12-05-18](https://user-images.githubusercontent.com/38542279/148403656-4a1a9cc8-c0ce-438b-b006-4bef447dd37c.png)

### System Information

Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	        testing
Codename:	bookworm

graphic interface: xfce
Graphic: Xorg

**Comment by borgmanJeremy** [comment]
Click the show errors button at the top. The config file specification changed for this version.

**Comment by wsalmeida** [comment]
The issue was resolved after I removed the configuration file there was some configuration conflict before the application was updated to a new version.

**Comment by mmahmoudian** [comment]
@wsalmeida you can always use `flameshot config --check` to see what has caused the error.

**Comment by wsalmeida** [comment]
yes close the problem this is not a bug but a configuration error thanks
for your attention.

Em sex., 7 de jan. de 2022 04:45, Mehrad Mahmoudian <
***@***.***> escreveu:
