### ISSUE TITLE
Flatpak requires KDE?

### ISSUE THREAD

**Issue by igorsantos07** [flameshot-org/flameshot#2235]
### Flameshot Version

most recent?

### Installation Type

Flatpak from Flathub

### Operating System type and version

Linux Mint 20.2.0, Mate version

### Description

Flatpak command requests installation of KDE runtime

### Screenshots or screen recordings

```
$ flatpak install flathub org.flameshot.Flameshot
Looking for matches…
Required runtime for org.flameshot.Flameshot/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15) found in remote flathub
Do you want to install it? [Y/n]: n
error: The application org.flameshot.Flameshot/x86_64/stable requires the runtime org.kde.Platform/x86_64/5.15 which is not installed
```

### System Information

- Linux Mint 20.2.0
- Mate version

**Comment by borgmanJeremy** [comment]
Yes we use the kde runtime

**Comment by igorsantos07** [comment]
And that's a requirement for the flatpak? I installed it from the Ubuntu repos apparently without any KDE suggestions... But I do see it depends on Qt stuff. I guess on Ubuntu it installs just the required pieces, while with Flatpak it seems to require more stuff?

Bottom-line: it might be useful to have some disclaimer explaining this "KDE runtime" requirement, which could confuse non-KDE users (like me).

**Comment by borgmanJeremy** [comment]
This is just how flatpak works. It's not related to flameshot particularly. I'm on mobile so sorry for the brief reply.

**Comment by igorsantos07** [comment]
Got it. I'm not sure if I'm just new to Flatpak stuff, but if my suggestion
doesn't make sense, I guess you can close the issue :)
Otherwise, a note on KDE requirements being just the Qt stuff could be
helpful on the install guides where Flatpak is mentioned. Not sure how to
better phrase it within the docs, so I won't open a PR.
