### ISSUE TITLE
App switches to empty Spaces desktop before activating in MacOSX 11.6

### ISSUE THREAD

**Issue by goodwid** [flameshot-org/flameshot#2239]
### Flameshot Version

Flameshot v11.0.0 (4680dcd)
Compiled with Qt 5.15.2

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

darwin: 20.6.0 osx: 11.6

### Description

I have two external monitors connected, plus the main screen active on my MacBook Pro.  Also, I use additional Spaces desktops extensively.

In addition to the below steps, I have also disconnected external monitors, removed all apps from full-screen extra desktops, and still am able to reproduce this.

## Action
1. click 'Take Screenshot' from the app

## Expected result
1. the screen dims and allows me to drag to position the capture space on the existing desktop

## Actual result
1. A new empty desktop is created
2. the new empty desktop is selected on the monitor from which the app is clicked
2. The screen dims and I am able to select a screenshot of the empty desktop
3. I select a space and select 'copy' 
4. I get a screenshot of the background image

I added the last few steps to confirm that I was not just seeing an overlay that was covering existing window data, and that the screenshot would actually be just the background.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/5066042/149009824-31f3d492-2143-41c3-a795-c8a0a34080d9.png)

https://user-images.githubusercontent.com/5066042/149010673-9fed277e-e844-4829-b4ed-c18587140778.mp4

### System Information

AMD Radeon Pro 5500M:

  Chipset Model:	AMD Radeon Pro 5500M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x7340
  Revision ID:	0x0040
  ROM Revision:	113-D3220E-190
  VBIOS Version:	113-D32206U1-020
  Option ROM Version:	113-D32206U1-020
  EFI Driver Version:	01.A1.190
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Family:	Supported, Metal GPUFamily macOS 2
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	3072 x 1920 Retina
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
PLL2410W:
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080 @ 60.00Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	Yes
  Connection Type:	DVI or HDMI
  Adapter Firmware Version:	7.55
PLL2410W:
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080 @ 60.00Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	Yes
  Connection Type:	Thunderbolt/DisplayPort

**Comment by mmahmoudian** [comment]
Have you checked if you issue is mot similar to #1805 and #1658 ?

**Comment by goodwid** [comment]
I followed those steps and was unable to restore the functionality, however this morning my machine had rebooted after a crash, and when flameshot started it asked for permissions again, and now all is well.  Thanks!

**Comment by mmahmoudian** [comment]
@goodwid I'm glad that it got resolved, and thanks for reporting it. This way other users would know that restarting their MacOS might help resolving permission issues. :+1:

**Comment by beauso** [comment]
FWIW I had to allow `skhd` screen recording permission as I had the hotkey to launch `flameshot gui` in my `~/.skhdrc`, in case anyone has the same issue.
