### ISSUE TITLE
Ability to hide GUI for live annotations

### ISSUE THREAD

**Issue by velocity-ed** [flameshot-org/flameshot#2240]
### Feature Description

I think it would be great if we could hide the GUI to allow live screen annotations.
It would be useful during screen recording and screen casting, as the GUI always hides some part of the screen.
The ability to select text and drawing tools while the GUI is hidden is essential.

**Comment by mmahmoudian** [comment]
Isn't this a duplicate of #273?

**Comment by velocity-ed** [comment]
> Isn't this a duplicate of #273?

Yes, I'm sorry I must have searched for the wrong terms. 
I'll close this and my vode to the original issue.

Thanks
