### ISSUE TITLE
snap stored at snapcraft.io is out of date

### ISSUE THREAD

**Issue by Semnodime** [flameshot-org/flameshot#2241]
### Flameshot Version

none

### Installation Type

Snap from Snapcraft

### Operating System type and version

none

### Description

snap stored at snapcraft.io is out of date

### Steps to reproduce

1. snap install flameshot --edge

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/19511852/149196545-620f3643-94f0-41d0-8c55-13b9020b1e8b.png)

### System Information

none

**Comment by Semnodime** [comment]
![image](https://user-images.githubusercontent.com/19511852/149197099-a5be755f-fecc-475f-a7dc-f9f100103192.png)

**Comment by borgmanJeremy** [comment]
Yeah the build is broken until they enable the new kde framework on core20 or allow custom flags during build

**Comment by Semnodime** [comment]
Maybe then omit the 'Update available' note or make it say 'Update available (no snap support yet).

**Comment by borgmanJeremy** [comment]
Well there is an update it's just not available via snap. When we do the version 11 release I plan to upload the .snap to the store which should also mitigate the notification.

**Comment by borgmanJeremy** [comment]
Fixed yesterday
