### ISSUE TITLE
Flameshot shortcuts not working when pop-shell tiling mode is active

### ISSUE THREAD

**Issue by ad-on-is** [flameshot-org/flameshot#2242]
Flameshot usually closes when a selection is copied to the clipboard CTRL-C or when the ESC-key is hit. This however does not work, when pop-shell tiling mode is active.

## Steps to reproduce
- Enable tiling mode in pop-shell
- Open flameshot to take a screenshot
- Press ESC to exit flameshot (does not work)
- Select an area and press CTRL-C to copy the selection to clipboard (does not work)

When I disable tiling-mode in pop-shell, everything works as expected.

## System 
- EndeavourOS - 5.15.13-arch1-1
- GNOME 41.3

```
flameshot -v 
Flameshot v0.10.2
Compiled with Qt 5.15.2
```

**Comment by RafaelMoreira1180778** [comment]
This behavior started to appear to me as well since this morning, not sure what has changed tho.
Came here to open an issue but I am glad that someone else has this problem as well.

**Comment by ad-on-is** [comment]
@RafaelMoreira1180778 I also reported the issue to pop-shell. 
https://github.com/pop-os/shell/issues/1315

TBH, I used pop-shell on and off, but don't know whether it used to work or not.

**Comment by RafaelMoreira1180778** [comment]
@borgmanJeremy yes, it stopped working for no apparent reason. Maybe it's due to POP-Shell updating or something because I can see they release [an update](https://github.com/pop-os/shell/releases/tag/1.2.0) yesteday and I keep my OS updated on a daily basis so I must have that update.

@ad-on-is thank you for that, I went ahead and reacted to it, let's see if they can fix it, it's a bummer because I always use window tilling because of my ultrawide monitor I have at work and CTRL-C for screenshots not working anymore presents some productivity troubles.

**Comment by mmahmoudian** [comment]
@RafaelMoreira1180778 as a side note, I just realized that you are using an ancient version of Flameshot. You might want to consider updating to the latest version.

**Comment by ad-on-is** [comment]
I just updated to the newest version of pop-shell which was released yesterday, and it solved the issue for me.

**Comment by RafaelMoreira1180778** [comment]
@mmahmoudian Just tried to install flameshot using `apt` and got the elder version again:

```
❯ sudo apt remove --purge flameshot -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  flameshot*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1220 kB disk space will be freed.
(Reading database ... 224009 files and directories currently installed.)
Removing flameshot (0.6.0+git20191001-2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...

❯ sudo apt install flameshot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  flameshot
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 288 kB of archives.
After this operation, 1220 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 flameshot amd64 0.6.0+git20191001-2 [288 kB]
Fetched 288 kB in 1s (404 kB/s)  
Selecting previously unselected package flameshot.
(Reading database ... 223977 files and directories currently installed.)
Preparing to unpack .../flameshot_0.6.0+git20191001-2_amd64.deb ...
Unpacking flameshot (0.6.0+git20191001-2) ...
Setting up flameshot (0.6.0+git20191001-2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...

❯ flameshot -v
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5
```

Not sure why this is happening, snapcraft.io version is also elderly and Flatkpak version is 0.10.1 and not 0.10.2.

@ad-on-is how may I check my pop-shell version and possibly update it? Also can you share what Flameshot installation you currently have?

**Comment by ad-on-is** [comment]
> @mmahmoudian Just tried to install flameshot using `apt` and got the elder version again:
> 
> ```
> ❯ sudo apt remove --purge flameshot -y
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages will be REMOVED:
>   flameshot*
> 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
> After this operation, 1220 kB disk space will be freed.
> (Reading database ... 224009 files and directories currently installed.)
> Removing flameshot (0.6.0+git20191001-2) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for man-db (2.9.1-1) ...
> Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
> 
> ❯ sudo apt install flameshot
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   flameshot
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 288 kB of archives.
> After this operation, 1220 kB of additional disk space will be used.
> Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 flameshot amd64 0.6.0+git20191001-2 [288 kB]
> Fetched 288 kB in 1s (404 kB/s)  
> Selecting previously unselected package flameshot.
> (Reading database ... 223977 files and directories currently installed.)
> Preparing to unpack .../flameshot_0.6.0+git20191001-2_amd64.deb ...
> Unpacking flameshot (0.6.0+git20191001-2) ...
> Setting up flameshot (0.6.0+git20191001-2) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for man-db (2.9.1-1) ...
> Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
> 
> ❯ flameshot -v
> Flameshot 0.6.0+git20191001-2(Debian)
> Compiled with Qt 5.12.5
> ```
> 
> Not sure why this is happening, snapcraft.io version is also elderly and Flatkpak version is 0.10.1 and not 0.10.2.
> 
> EDIT: downloaded the v11 beta and managed to install it using the `.deb` file.
> 
> @ad-on-is how may I check my pop-shell version and possibly update it? Also can you share what Flameshot installation you currently have?

I'm on Arch Linux (EndeavourOS), and installed both, flameshot and pop-shell, from the Arch/AUR repo.
