### ISSUE TITLE
More functionalities for pinned items (edit, change opacity)

### ISSUE THREAD

**Issue by eazyAlf** [flameshot-org/flameshot#2251]
### Feature Description

Hi there,

I think it'd be very useful to be able to work reopen pinned items and edit them.
Currently it's really easy to accidentally close them and then they're gone.

Also to be able to lower the opacity of them so you can see through pinned items (to compare things visually or if you dont have space to let a screenshot float around)

**Comment by mmahmoudian** [comment]
The pinned images are not saved anywhere. So if they are closed, they are gone for good. There is already a feature request for opening the files in Flameshot (#1100). Perhaps you can follow this part there.

About the opacity you can either continue here or discuss it in #954

**Comment by mmahmoudian** [comment]
There has been some development. I don't remember when we added this feature, but now you can right-click on a pinned image and copy it to clipboard or save to a file. This will not cause the pinned image to be closed:

![image](https://user-images.githubusercontent.com/390889/195023150-866b8a2d-a3be-40f4-93f6-f7cda9492993.png)

About the opacity, although you suggested it almost 10 months ago, let's follow that in #2943
