### ISSUE TITLE
https://github.com/hluk/CopyQ/issues/1878

### ISSUE THREAD

**Issue by zw963** [flameshot-org/flameshot#2258]
### Flameshot Version

Flameshot v0.10.2
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch linux

### Description

Please check following issue, i describe detailed there, thank you.

https://github.com/hluk/CopyQ/issues/1878

### Steps to reproduce

https://github.com/hluk/CopyQ/issues/1878

### Screenshots or screen recordings

https://github.com/hluk/CopyQ/issues/1878

### System Information

https://github.com/hluk/CopyQ/issues/1878

**Comment by borgmanJeremy** [comment]
This does not seem at all like a Flameshot bug if you can see the image in the copyQ clipboard.

**Comment by zw963** [comment]
> 

All right, thank you!
