### ISSUE TITLE
The Persian translation is not in the final Flameshot package

### ISSUE THREAD

**Issue by eshagh79** [flameshot-org/flameshot#2259]
### Flameshot Version

Flameshot V11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

ubuntu 21.10

### Description

Hello
Persian language has been completed on weblate for more than five months, but is not yet in the flameshot package.
I think this is because the Persian translation has not been added to the "flameshot / src / CMakeLists.txt" file.
If so please add it.
Thank you for your good program

### System Information

.

**Comment by mmahmoudian** [comment]
Thanks for reporting this. It seems you are right.

ممنون بابت کمک در ترجمه 👍🏼

**Comment by borgmanJeremy** [comment]
Weblate should have all the strings later today, i merged the changes but there is usually some delay to propagate.
