### ISSUE TITLE
Windows 11: "Print Screen"-button do not work!

### ISSUE THREAD

**Issue by ampcpmgp** [flameshot-org/flameshot#2261]
### Flameshot Version

Frameshot v11.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11 Home & 21H2 & 22000.434

### Description

Pressing "Prt Sc" on Windows 11 calls windows standard printscreen saving function.
(Right click on "Create screenshot" in context menu does work as expected)

Same https://github.com/flameshot-org/flameshot/issues/1961

### System Information

Windows 11 Home & 21H2 & 22000.434

Three display
![image](https://user-images.githubusercontent.com/13173632/149623998-09581152-6d93-4161-aa86-aad1612ac873.png)

**Comment by krokofant** [comment]
Works for me on Windows 11 Enterprise / 21H2 / 22000.376 with Flameshot v11.0.0

**Comment by CrypticVader** [comment]
Pressing PrtScr simply copies a snapshot of the entire screen for me, same OS build.
I did like a shortcut to quickly launch Flameshot instead of just the tray icon.

**Comment by ampcpmgp** [comment]
I didn't do anything, but it's fixed.

**Comment by krokofant** [comment]
@ampcpmgp Then you could close this issue to help the devs. 😄

**Comment by Shrugsy** [comment]
This started occurring to me seemingly out of nowhere, possibly after a windows update at some stage.

In windows settings, under `Accessibility > Keyboard`, I found that the following setting was enabled: `Use the Print screen key to open Snipping Tool`. After disabling that setting and restarting windows, the print screen key once again would trigger Flameshot's print screen functionality 👍

**Comment by mmahmoudian** [comment]
Perhaps looking our documentation can help our Windows users to save some time :D

https://flameshot.org/docs/guide/windows-help/

**Comment by IOGGOI** [comment]
Follow these steps and it will likely work, even after the KB5025310 update, that prevents from other screen-capture tools use the Print key:

1. If you have it installed, uninstall Flameshot.
2. Open Registry as administrator and double click on the **PrintScreenKeyForSnippingEnabled** key (right click > modify).
Path: Computer\HKEY_CURRENT_USER\Control Panel\Keyboard
4. Set the value to 0 > OK
5. Close Registry.
6. Install Flameshot.

![SnippingTool_Nightmare](https://github.com/flameshot-org/flameshot/assets/131985965/af31ed03-923b-4957-b3fe-46851367d084)

Flameshot should be now open when pressing the Print key.

Works for Windows 10, 11, regardless the build.

**Comment by mifeputri-34** [comment]
> This started occurring to me on windows 11 seemingly out of nowhere, possibly after a windows update at some stage.
> 
> In windows settings, under `Accessibility > Keyboard`, I found that the following setting was enabled: `Use the Print screen key to open Snipping Tool`. After disabling that setting and restarting windows, the print screen key once again would trigger Flameshot's print screen functionality 👍

this should be added to readme

**Comment by dbruehlmeier** [comment]
All of the sudden, my ``PrtSc`` button did not trigger Flameshot anymore. Tried all of the approaches above, none of them worked.

Turns out, it was due to an automatic update of Logi Options+ (I'm using a MX KEYS from Logitec).

The update changed the assignment of the ``PrtSc`` button to the Windows built-in method.

After changing it to ``ASSIGNMENT_NAME_PRINT_SCREEN`` (sic!), it worked again...

![Image](https://github.com/user-attachments/assets/eebee651-943e-4417-8ca7-cf3df0961edd)

**Comment by auphucdup** [comment]
> All of the sudden, my `PrtSc` button did not trigger Flameshot anymore. Tried all of the approaches above, none of them worked.
> 
> Turns out, it was due to an automatic update of Logi Options+ (I'm using a MX KEYS from Logitec).
> 
> The update changed the assignment of the `PrtSc` button to the Windows built-in method.
> 
> After changing it to `ASSIGNMENT_NAME_PRINT_SCREEN` (sic!), it worked again...
> 
> ![Image](https://github.com/user-attachments/assets/eebee651-943e-4417-8ca7-cf3df0961edd)

This fixed my issue and I wouldn't have made the connection for a while - thank you!

**Comment by flipbit03** [comment]
Abbykito's [reply](https://github.com/flameshot-org/flameshot/issues/2261#issuecomment-2613992793) worked for me, the moment you disable the screenshot in windows Accessibility menu, the key is freed for flameshot to pick up
