### ISSUE TITLE
Typing numeric size issues

### ISSUE THREAD

**Issue by Idomo** [flameshot-org/flameshot#2265]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

macOS 12.1

### Description

First of all, thanks for this great upgrade!
I've noticed 2 issues with the new feature `Thickness of tools can now be set with the keyboard. Simply type a numerical value like "15" and you will see the indicator in the upper left.`:
1) It doesn't recognizing when pressing numbers on the numpad on the right side of the keyboard.
2) When you're focusing on some text layer and typing a number that is smaller than the current size of the text, the old sized text stay on the screen (see screenshot).

### Steps to reproduce

1. Start the GUI
2. Select area
3. Type text
4. Focus on the text
5. Type size (e.g. 50)
6. Type smaller size (e.g. 20)

### Screenshots or screen recordings

![image](https://i.imgur.com/T7csDgZ.gif)

### System Information

I'm using an external monitor.

**Comment by borgmanJeremy** [comment]
Thanks! I replicated this on linux too so its not platform specific. We often have a point release to fix minor issues after a major release and this can get resolved there most likely.

**Comment by borgmanJeremy** [comment]
If possible can you test #2386 ?

**Comment by Idomo** [comment]
@borgmanJeremy I'm not sure how to download it, may you attach a dmg?

**Comment by mmahmoudian** [comment]
@Idomo 

![image](https://user-images.githubusercontent.com/390889/152790325-db05a65e-a5fb-485a-8527-7e9efb6023ef.png)

![image](https://user-images.githubusercontent.com/390889/152790437-19d44929-f2f9-49f7-92a2-21813d1f48a1.png)

![image](https://user-images.githubusercontent.com/390889/152790606-ae40dc73-e634-4a5b-9820-7aa42660c17a.png)

![image](https://user-images.githubusercontent.com/390889/152790110-ac85e7b4-5f7e-4161-90bb-75ec1557438d.png)

**Comment by Idomo** [comment]
Thanks @mmahmoudian, it seems to be fixed with this commit.
I have another question that I'm not sure if thats a bug or not; Does double click on the selected area should automatically upload to imgur and copy the link?
