### ISSUE TITLE
Flameshot v11.0.0 is marked as rc for linux

### ISSUE THREAD

**Issue by ricardoseriani** [flameshot-org/flameshot#2267]
The current release of flameshot is marked as RC for linux, but not for windows.

Is the release for linux really RC, or this is a bug in the release filename ?

**Comment by borgmanJeremy** [comment]
Which package is marked rc? It should not be

**Comment by veracioux** [comment]
@borgmanJeremy All the linux assets on the github release page contain rc1 in their name.

**Comment by borgmanJeremy** [comment]
Ok I'll rename them later today. I fixed it for the snap I uploaded.

If you look in the snapcraft file you can see the hack I did there. The current CI sorts the tags and puts the rc ahead of the non rc.

I think if you run flameshot --version it should be right

**Comment by borgmanJeremy** [comment]
Thanks I fixed it.
