### ISSUE TITLE
v11 breaks screen capture shortcut

### ISSUE THREAD

**Issue by matteo-bloomandwild** [flameshot-org/flameshot#2274]
### Flameshot Version

v11

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

MacOS Monterey 12.1

### Description

Since I upgraded to v11, my pre-existing shortcut (cmd + opt + shift + 4) stopped working.
Trying to re-set it in the configuration, represents it with `$` instead of `4` (as shown in the picture), and does not work.
![image](https://user-images.githubusercontent.com/93405661/149791549-15a3c388-2d43-4878-8156-f2afb1debf47.png)

Setting any other shortcut also does not work.

### Steps to reproduce

1. Upgrade flameshot from a previous version to v11
2. Observe the previously configured shortcut not working anymore
3. Attempt to set it again, observe wrong text displayed in configuration, also that the shortcut does not work
4. Attempt to set any other shortcut, and observe it not working.

### Screenshots or screen recordings

Existing shortcut (or set again) shown as:
![image](https://user-images.githubusercontent.com/93405661/149791887-0861c137-cc9b-4c22-af76-a9ea6a5a7ef7.png)

Same but with `1`:
![image](https://user-images.githubusercontent.com/93405661/149791965-56820c91-0eb0-4dbe-b563-1226a8dcbc6f.png)

Without the shift button (displayed correctly, but not working):
![image](https://user-images.githubusercontent.com/93405661/149792071-3b1a87f9-ece7-41fa-8580-4d1a3851b44a.png)

### System Information

![image](https://user-images.githubusercontent.com/93405661/149792158-419e820e-3544-445e-9a71-92eee91e2af9.png)

**Comment by borgmanJeremy** [comment]
Thanks for reporting. I can duplicate the problem However if you use a combo that does not involve the numbers / symbols you can work around it for now. For example command+shift+p

**Comment by matteo-bloomandwild** [comment]
Hi, thanks for your reply!
I tried your suggested keybinding
![image](https://user-images.githubusercontent.com/93405661/149923163-acf1dd08-514b-4f05-a783-ae05fd310126.png)
Which displays as expected, but for some reason pressing it does not trigger a screen capture anyway for me. Could I be forgetting something in my OS configuration that is preventing it to work, or do you think this is part of the bug I'm reporting?

**Comment by MathiasVandePol** [comment]
I am experiencing the same as @matteo-bloomandwild . Tried setting it to any other key combination but didnt work.

**Comment by borgmanJeremy** [comment]
@MathiasVandePol Thanks for that hint. It looks like a full reboot is not required but restarting flameshot is. There is still a defect related to the symbols / numbers we will resolve.

**Comment by matteo-bloomandwild** [comment]
@borgmanJeremy thanks, good shot! I confirm restarting flameshot makes the shortcut work again

**Comment by Kin-Zhang** [comment]
I met the same problem after uploading, but with restart and reboot, my shortcut still not working.
----
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 20.6.0
osx: 11.6
----

**Comment by borgmanJeremy** [comment]
After some research I don't think there is a clear way to resolve this. Here is a good explanation of the problem: https://forum.qt.io/topic/25902/how-to-get-shift-1-string-sequence-from-shift-qkeyevent/7

I don't think this will impact users too much since they can set plenty of other hotkeys, and if someone REALLY wants this particular hotkey it can still be manually defined in the config file.

**Comment by matteo-bloomandwild** [comment]
That topic looks quite old and the keybindings with the shift button were working before the update?

**Comment by borgmanJeremy** [comment]
It was working before because it was hard coded. That's the same reason it will work if you manually define it in the config.

I played around for quite some time and am pretty sure there is no easy fix. There will always be an edge case due to keyboard layout and localization differences.

**Comment by matteo-bloomandwild** [comment]
Ahh yes I forgot it was hardcoded before. Nvm then I agree it's not something important, thanks for the replies!
