### ISSUE TITLE
Clipboard and Save to File buttons no longer appearing

### ISSUE THREAD

**Issue by socketbox** [flameshot-org/flameshot#2275]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.9.5
linux: 5.4.0-70-generic
linuxmint: 19.3

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Linux Mint 19.3 (based on Ubuntu 18.04)

### Description

In Flameshot 10, there were two buttons available to me that are not appearing in this most recent version of Flameshot. The save-to-file button (which looked like a floppy disk icon) and a copy-to-clipboard button (which looked like two offset sheets of paper). Neither of these buttons appear for me after upgrading to v11.

What have I done to resolve the issue?
1. Moved my old `.ini` file out of the way
2. Open up Flameshot configuration, ensuring that the checkboxes for these buttons were, in fact, checked and then exported the configuration.
3. Configuration file is pretty sparse, showing only 
```
[General]
contrastOpacity=188
saveAsFileExtension=png
savePath=/home/chb/Desktop/Screenshots
showStartupLaunchMessage=false
```
4. Restarted Flameshot.

No luck. Next attempt:

All of the above, except that before step 4, restarting, I edited the `.ini` file to include the `buttons` line from the sample `.ini` from the repo. So it looks like this:
```
[General]
contrastOpacity=188
saveAsFileExtension=png
savePath=/home/chb/Desktop/Screenshots
showStartupLaunchMessage=false
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x14\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe\0\0\0\x11)
```
But again, neither of the two buttons is present.

### Steps to reproduce

1. Run flameshot from the Mint start menu. This results in a process that has `flameshot` as its command.
2. Hit PrintScreen (bound to `flameshot gui -p /home/username/Desktop/Screenshots`)
3. See that there are some missing buttons.

### Screenshots or screen recordings

![FF87FFD4-E994-4B26-82F4-ABF75A214D95](https://user-images.githubusercontent.com/1593835/149822831-cf829bb7-8e5a-4d69-9e9a-91ea7a46afe9.jpg)
 

### System Information

```
System: 
    Kernel: 5.4.0-70-generic x86_64 bits: 64 
    Desktop: Cinnamon 4.4.8 
    Distro: Linux Mint 19.3 Tricia

Graphics:  
    Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] driver: amdgpu 
    Display: x11 server: X.Org 1.19.6 driver: amdgpu resolution: 2560x1440~60Hz, 2560x1440~60Hz 
    OpenGL: renderer: AMD Radeon RX 480 Graphics (POLARIS10 DRM 3.35.0 5.4.0-70-generic LLVM 10.0.0) v: 4.6 Mesa 20.0.8
```

**Comment by borgmanJeremy** [comment]
This is an intentional change. See this thread for details

https://github.com/flameshot-org/flameshot/issues/2227

**Comment by mmahmoudian** [comment]
@socketbox 

The logic is when you define `--path`, `--clipboard`, `--raw`, or `--upload`, you are defining the final action. For that reason the faith of your screenshot is already decided and therefore there is only one "Accept" button. This brings the possibility of defining multiple final actions at once. For instance you can do

```sh
flameshot gui --clipboard --upload --path ~/Pictures/
```

To save the screenshot, upload it to imgur, and copy it to clipboard at the same time.

If you are using `--path` because you have keybinding for taking screenshot to a static path, you are better to save that in your configurations.

**Comment by socketbox** [comment]
@borgmanJeremy 
@mmahmoudian 

Thanks for the assistance and apologies for not reading the Release Notes.

I removed the path argument from the key binding and selected the checkbox that keeps the application from prompting for a path. ![image](https://user-images.githubusercontent.com/1593835/149946999-029e60a2-ac64-4772-b751-5a95fe6cbfa2.png)

Now, behavior is much as it was for me in v10. 

Thank you, again.

**Comment by ElijahLynn** [comment]
Thanks, I was having this issue too and was confused by this. This issue makes it clearer what is happening now. 

However, when I launch with keyboard shortcut with `flameshot gui --path /home/elijah/Pictures/ --clipboard` now, I can't press enter after I select the area. I can only click on the "Accept the capture" button for it to work. I am not using Wayland, fwiw, still on X.

**Comment by ElijahLynn** [comment]
I just worked around my issue though by using `--accept-on-select` which "should" work most of the time, but not for when I want to be able to annotate too. So I still need to figure this out for those 10% of use cases for me.

**Comment by ElijahLynn** [comment]
K, I got the <Return> key working but don't understand why. 

I changed:

`TYPE_COPY=Return`

to:

`TYPE_COPY=Ctrl+C`

And now <return> works, not Ctrl+C though, which is the opposite of what I was expecting. I'll open a new issue I suppose.

**Comment by alkaris2** [comment]
This is a stupid downgrade decision for flameshot.

**Comment by mmahmoudian** [comment]
@alkaris2 mind your language and keep the conversation polite.

Flameshot is a free and Libre OpenSource software, all the discussions and decisions were public and you had every opportunity to express your opinion and participate in the discussions during the development.

If you don't like the change, feel free to use another tool, but never ever complain about changes when you couldn't even be bothered to contribute.
