### ISSUE TITLE
Flameshot doesn't run by D-Bus call

### ISSUE THREAD

**Issue by wolandtel** [flameshot-org/flameshot#2277]
### Flameshot Version

Flameshot v0.10.1 (11.0~rc1+ds1-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian GNU/Linux bookworm/sid

### Description

After the last update hotkey configured in KDE for flameshot stopped working.
Configuration is shown on the screenshot. It hasn't been changed for years.
I've found a tip to use org.dharkael.Flameshot instead of org.flameshot.Flameshot, but such interface doesn't exists in my D-Bus session.

### Steps to reproduce

1. Configure the hotkey in the KDE configuration manager as shown on the screenshot.
2. Press the configured key combination.
3. Expected: flameshot starting the screenshot capture process.
4. Actual: nothing happens.

### Screenshots or screen recordings

Configuration:
![Flameshot_2022-01-18_134430](https://user-images.githubusercontent.com/1917417/149902304-7c7c2b90-1a2d-4984-be9a-e15cc5d07d49.png)

Interface doesn't have method 'graphicCapture' anymore:
![Flameshot_2022-01-18_134516](https://user-images.githubusercontent.com/1917417/149902390-a2d2024c-c647-47c0-83a3-5e1661e2e307.png)

### System Information

KDE, KWin.
Xorg.

**Comment by mmahmoudian** [comment]
> I've found a tip to use org.dharkael.Flameshot instead of org.flameshot.Flameshot, but such interface doesn't exists in my D-Bus session.

No, that is depricated. In version 10 we were still using `org.flameshot.Flameshot` but in version 11.0 we have tried to move away from DBus. You can find the working set of commands for hotkeys here:
https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde.khotkeys

**Comment by wolandtel** [comment]
Thanks a lot.
