### ISSUE TITLE
Installing from snap doesn't provide the same options if installing from Ubuntu store

### ISSUE THREAD

**Issue by Gil80** [flameshot-org/flameshot#2278]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
linux: 5.13.0-25-generic
ubuntu-core: 20

### Installation Type

Snap from

### Operating System type and version

Ubuntu VERSION_ID="21.10"

### Description

Expected behaviour: to work like flameshot that was installed from ubuntu store.
Examples: prtsc keyboard shortcut used to work. Taking region screenshot provides options to save or upload.

These are missing or not working with the flameshot version installed from snap store.
The keyboard shortcut doesn't work.
I don't see any options to upload the screenshot after I take a screenshot

### Steps to reproduce

1. install using snap install flameshot
2. remove old installation
3. start using flameshot

### System Information

PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

**Comment by mmahmoudian** [comment]
@Gil80 how are you running Flameshot? I have a feeling that you are running Flameshot with the `-p` argument and your issue is the same as  #2275.

**Comment by Gil80** [comment]
@mmahmoudian I just launch the app from the GUI of Ubuntu.

**Comment by mmahmoudian** [comment]
Would you please record a video of your screen and show this bug? If you don't have a tool to record a video, I suggest [peek](https://github.com/phw/peek)

**Comment by Gil80** [comment]
I tried using peek but the GIFs it generates are all black screen and it only shows the mouse cursor.

**Comment by borgmanJeremy** [comment]
I just tested in a clean VM and its working fine.

**Comment by mmahmoudian** [comment]
@Gil80 

> The keyboard shortcut doesn't work.

I believe by shortcut you mean the shortcut that triggers Flameshot to open so that you can take a screenshot. Right? if so, you should configure that in your computer. You can follow this instructions (I assumed you are using Gnome):

https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en#custom

Just remember to use the `flameshot gui` command.

> I don't see any options to upload the screenshot after I take a screenshot

This is perhaps you are using the wrong command. it is easy to try:

1. open a new terminal
2. type this command: `flameshot gui`
3. now you should see the Save and Upload buttons (in my computer I have disabled the upload button)
    - ![image](https://user-images.githubusercontent.com/390889/150657706-290117d5-2464-4c2f-998d-fc588c9a78ca.png)
4. now close flameshot
5. close that terminal
6. open a new terminal
7. type this command: `flameshot gui --path ~/Pictures`
8. now since you have already defined a final action (`--path`), you should only see an accept button
    - ![image](https://user-images.githubusercontent.com/390889/150657746-6ee62f50-b728-46cd-8318-a8ce01737b9d.png)

Does this answer your issue?

**Comment by Gil80** [comment]
hi @mmahmoudian  and thank you for your detailed response. 
I've followed your steps and they are exactly as I've done previously.
The keyboard shortcut (prnt scr) is defined as `flameshot gui`

Steps I'm taking:
1. booting the PC. Flameshot is not running on startup and it is not running in the system trey.
2. When I press that button, the entire screen is SHARE, CANCEL or OPTIONS
3. If I choose SHARE, then I'm presented with the ability to take regional screenshot.
4. I select to save the image, but it is not saved.

Repeat the above, only this time have Flameshot running in the system trey.
Step 4 will now work and the image will be saved.

Desired behavior as per the older Flameshot installation I had:
1. Regardless if Flameshot is running in the system trey, pressing the shortcut button will always trigger regional screenshot and then provide me with the options to Save, upload, copy to clipboard, etc.
2. Screenshots are saved locally even if Flameshot wasn't running in the system trey.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I have reproduced this on a [Rigolith](https://regolith-linux.org) (Ubuntu 21.04 i3 gaps) clean install VM. the `.qcow2` file is 28GB I can share it if you have Qemu to run the VM.

**Comment by borgmanJeremy** [comment]
Can you please review this gif and see if I am missing anything? I used gnome since thats what the original bug report was for. I'll try again with i3 but I actually tested i3 this morning. https://imgur.com/a/89ws61p

**Comment by mmahmoudian** [comment]
This is interesting. on a clean install Pop!_os 21.10 which is practically gnome and it worked

![image](https://user-images.githubusercontent.com/390889/153041022-328b32a3-d7d7-4722-9476-7ba76cc690e0.png)

I wonder how can i track down the issue as I have two separate VMs based on the same Ubuntu version using the same software suite (gnome stack) just with different window manages, in one of which I can reproduce the issue and on the other I cannot.

**Comment by mmahmoudian** [comment]
@Gil80 I came back to this issue to see what I can do, and unfortunately I have deleted the Regolith VM I had, so I installed Ubuntu 21.10 in a VM, updated it (`sudo apt update && sudo apt upgrade`) and then `snap install flameshot` and then `flameshot gui` and could not reproduce this issue. Would you please try and see if you still can reproduce the issue?


https://user-images.githubusercontent.com/390889/177793235-88252a71-e905-421c-bcf9-9f38fa9ce5f9.mp4

**Comment by mmahmoudian** [comment]
I'm gonna close this because:
1. I cannot reproduce this anymore
2. Ubuntu 21.10 is EOL already (source: https://endoflife.software/operating-systems/linux/ubuntu)
3. stale issue
