### ISSUE TITLE
Flameshot seems to not working on Gnome 41.3

### ISSUE THREAD

**Issue by h0nus** [flameshot-org/flameshot#2279]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora Linux 35

### Description

If I start it from terminal by typing: `flameshot`, no output is gave.
with `flameshot gui` the GUI starts but it won't save the screenshot to clipboard
same goes with `flameshot screen -c` and `flameshot full -c`

I tried with builtin screenshot tool from Fedora Gnome 41.3 and works.

### Steps to reproduce

1) run any `flameshot gui`
2) take the snip
3) save to clipboard
4) try to paste it in some chats (eg. Telegram Desktop)
5) doesn't work (same goes with `screen -c` and `full -c`

### Screenshots or screen recordings

I have no errors , so i don't know how to help.

### System Information

- Gnome 41.3 on Xorg
- Fedora 35
- CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz
- GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate
- Kernel: 5.15.14-200.fc35.x86_64

**Comment by borgmanJeremy** [comment]
Do you have the daemon running in the background?

**Comment by leoluk** [comment]
Same with i3 on Xorg - I can take a snapshot but it's not actually copied to the clipboard.

**Comment by h0nus** [comment]
Yes I have it:

```
ivan       46766  0.0  0.0      0     0 ?        Z    Jan18   0:00 [flameshot] <defunct>
ivan       80902  2.0  0.1 999868 58804 ?        Sl   12:28   0:00 flameshot
ivan       81048  0.0  0.0 221792  2336 pts/0    S+   12:28   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i flameshot
```

Strangely, after some time without using PC, i've just tried to `killall flameshot` then tried with my custom keyboard shortcut that invokes `flameshot gui` and seems working again.
I wonder why

**Comment by borgmanJeremy** [comment]
okay if its working now I will close the issue.

**Comment by xvitaly** [comment]
[Backported](https://src.fedoraproject.org/rpms/flameshot/c/226b41efa77e74907f3a2c58f2f9a2e8b04794f2?branch=rawhide) upstream fix Fedora.

@h0nus Can you try [this build](https://bodhi.fedoraproject.org/updates/FEDORA-2022-c2a1f83868)?
