### ISSUE TITLE
How to use the pin tools?

### ISSUE THREAD

**Issue by SYSU-Jmiao** [flameshot-org/flameshot#228]
**Is your feature request related to a problem? Please describe.**
Please, a single feature per issue.

**Comment by Rmano** [comment]
I use it to composite different snapshot of different places/status of an app. Do a screenshot, pin it, move it, do another one, etc...

![image](https://user-images.githubusercontent.com/6414907/40253196-2e8408da-5adf-11e8-865e-e574d277f34d.png)

**Comment by Rmano** [comment]
Ah! I did not know the resize thing! Nice :-)

**Comment by et2010** [comment]
There is no pin-tool button here. I'm using the git version under Mint 18.3 (ubuntu 16.04) and compile flameshot from master branch.

**Comment by Rmano** [comment]
It's not enabled by default, have you enabled it in the settings dialogs?

**Comment by et2010** [comment]
Ah, I feel really stupid. Thanks for the hint!

**Comment by ZetaoYang** [comment]
There is an initial( imperfect) official document https://flameshot.js.org .

**Comment by cmpute** [comment]
This tool is quite useful! I guess it could be enabled by default?
