### ISSUE TITLE
Request: Invert the color of the "Leave the capture screen" button

### ISSUE THREAD

**Issue by 0lhi** [flameshot-org/flameshot#2282]
### Feature Description

Sometimes Fireshot is pressed on accident, and finding the close button can take a bit. Having it distinguished from the others would save some time.

**Comment by borgmanJeremy** [comment]
You can hit the esc key instead

**Comment by borgmanJeremy** [comment]
@mmahmoudian @veracioux I am not really in favor of this but I want your thoughts before we make a final decision.

**Comment by veracioux** [comment]
> I also believe this is unnecessary as
> 
> * I don't see this as a problem (this is the first complaint we have got)
> 
>  * probably too much effort for too little gain (as there should be a config option to toggle this)

I agree with this.
