### ISSUE TITLE
My filename-pattern (monthly sub-folder) broke with v11

### ISSUE THREAD

**Issue by GitLinko** [flameshot-org/flameshot#2289]
So I had my Flameshot set up to automatically save to a location like: 
`E:\Screenshots`

And then used the following filename-pattern:
`%Y-%m\%F_%H-%M`

Which resulted in my file being saved to "E:\Screenshots\2022-01\filename.jpg" for example.
This worked well for me thus far (at the start of every month I had to create the new folder myself, cause Flameshot couldn't, but that wasn't to much of a bother)

But after I updated to v11 this behaviour broke.
When I configure it like above it works for exactly one screenshot. After I take one screenshot the configured path is automically set to:
`E:\Screenshots\2022-01\`

And when I try to take another screenshot it's now trying to save the file at (which doesn't work because the folder doesn't exist):
`E:\Screenshots\2022-01\2022-01\filename.jpg`

**Comment by mmahmoudian** [comment]
Would have been nice if you were using the template we provided for bug report.

Regarding your issue, please provide the following information:

- How have you installed Flameshot
- your Flameshot config file (just the top section would be enough

**Comment by GitLinko** [comment]
```
[General]
disabledTrayIcon=false
drawColor=#ff00ff
savePath=E:/Screenshots
savePathFixed=true
showStartupLaunchMessage=true
contrastOpacity=188
filenamePattern=%Y-%m\\%F_%H-%M
startupLaunch=true
drawFontSize=8
drawThickness=3
uploadWithoutConfirmation=true
```

I've installed it through winget on Windows 11.

**Comment by hosiet** [comment]
Having slash or backslash in filename template is almost certainly fragile and platform-specific (Windows `\` vs. linux&mac `/`) since they are not allowed to be used as part of filename. I understand the idea of putting files under subfolders, but such feature should not be supported from the very beginning.

**Comment by mmahmoudian** [comment]
@GitLinko 

I don't have a Windows machine to test this on, but try:
1. Close Flameshot (right click on the tray icon and quit the application)
2. change the `%Y-%m\\%F_%H-%M` to `%Y-%m/%F_%H-%M` in the config file manually
3. Start Flameshot again and see if it has helped

**Comment by GitLinko** [comment]
No that doesn't work. The forward slash gets turned into '?'. And then it can't save the file either.

**Comment by borgmanJeremy** [comment]
I agree with @hosiet . I agree this is a change in behavior but its not a bug. If you want to set the path you should use "save path" under general settings.
