### ISSUE TITLE
v11 not able to take screenshot on MacOS

### ISSUE THREAD

**Issue by xakraz** [flameshot-org/flameshot#2290]
### Flameshot Version

```
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 20.6.0
osx: 11.6
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS BigSur 11.6.2

### Description

I have upgraded to Flameshot v11 yesterday.

Since then, the app keeps asking for permissions to capture the screen, which it already has.

<img width="672" alt="Screenshot 2022-01-20 at 12 40 30" src="https://user-images.githubusercontent.com/1590399/150332550-7559de83-ccce-44a7-91e3-d2f2f9c68722.png">

<img width="673" alt="Screenshot 2022-01-20 at 12 41 25" src="https://user-images.githubusercontent.com/1590399/150332557-fe7ebb14-f0d8-4f62-86d0-d3d7b85a6e5d.png">

What I have done:
- [x] Tick / unTick the check box + Restart
- [x] Remove / Re-add the app completely from the system preferences panel + Restart

None of these actions work and I am not able to save screenshots  anymore ...

### Steps to reproduce

1. Install Flamshot v11 via Homebrew on macOS BigSur 11.6.2
2. Launch the daemon
  + you will get the prompt
3. Try to take a screenshot

### Screenshots or screen recordings

<details>
<summary>Details</summary>

</details>

### System Information

1. macOS 11.6.2

<img width="673" alt="Screenshot 2022-01-20 at 12 52 35" src="https://user-images.githubusercontent.com/1590399/150333816-d562bfa4-405c-4a96-9bbb-2adb944808f4.png">

**Comment by borgmanJeremy** [comment]
Have you also tried rebooting? Mac is really weird with its permissions. I develop about 50% of the time on mac and cannot replicate this.

**Comment by I4son** [comment]
Hi, had the same issue earlier. Reboot the machine post installation does the trick. 👍🏻

**Comment by xakraz** [comment]
Indeed, I have rebooted and it worked 😅 

It remembers me Windows time ...
