### ISSUE TITLE
Adding more settings to the configuration GUI

### ISSUE THREAD

**Issue by mimecry** [flameshot-org/flameshot#23]
Hi lupo! May I suggest adding a few more simple options to the GUI, such as specifying a delay (yes I know you can do this through terminal), or having an option to map different functions to hotkeys. Even better if you can somehow make it behave like ShareX where you can specify a workflow and map it to a hotkey.

Thanks very much for this wonderful and creative piece of software

**Comment by lupoDharkael** [comment]
That's a good suggestion.
It would be interesting if we could assign the functionality of the buttons the shortcuts of our election.

**Comment by thiemo-taken** [comment]
+1 delay on gui (I need to do it with spectale now)

**Comment by borgmanJeremy** [comment]
Okay I believe all these issues are resolve don master.

* Delay was added in 0.8.x with the launcher.
* Hotkey support was added by namecheap and merged to master (unstable)
