### ISSUE TITLE
Unable to create screenshot

### ISSUE THREAD

**Issue by dshleg** [flameshot-org/flameshot#2316]
### Flameshot Version

11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

MacOS Catalina

### Description

dmg downloaded from github

### Steps to reproduce

click "Take ScreenShot"

### System Information

Macbook with M1 CPU , MacOS Catalina

**Comment by borgmanJeremy** [comment]
See this thread: https://github.com/flameshot-org/flameshot/issues/2290

Almost certainly a permissions issue.
