### ISSUE TITLE
It would be better if it had this function

### ISSUE THREAD

**Issue by YQisme** [flameshot-org/flameshot#2317]
### Feature Description

Directly using the keyboad shortcuts to take a screenshot instead of clicking twice.

**Comment by borgmanJeremy** [comment]
You can already do this. But it is operating system specific. What os are you on? If Linux, which desktop environments

**Comment by YQisme** [comment]
My os is win10,how can i do it?

**Comment by borgmanJeremy** [comment]
On windows 10 you should just be able to hit the print screen key on your keyboard. If this is always bound to something like greenshot it won't work.

There is an existing issue open to let users configure the hotkey like we do on MACOS

**Comment by YQisme** [comment]
OK.Thank you.
