### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mablae** [flameshot-org/flameshot#232]
**Describe the bug**
Dunno... It just crashed hard? 

**To Reproduce**
Kill via sigterm, since it didn't appear in the gnome toolbar after autostart. 

**Expected behavior**
Should not segfault!

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 Gnome

![grafik](https://user-images.githubusercontent.com/389360/40714021-bef21b34-6401-11e8-9734-774479de3207.png)

**Comment by luzpaz** [comment]
@mablae can you recreate with v0.6 ?

**Comment by mablae** [comment]
I will check it and report back, Sir. 

Thanks for the pointer I totally missed the 0.6 release it seems

**Comment by vcidst** [comment]
I'm on Ubuntu 18.04 and still facing the same issue (also referred in #680),

![image](https://user-images.githubusercontent.com/683016/80054283-6d822880-853c-11ea-8bc2-eb5b5e279462.png)

I installed flameshot with `apt` and noticed I wasn't running 0.6 so I ran `apt update` and `apt upgrade`. The version of flameshot is still the same. Is there any other way to update it to v0.6?

**Comment by borgmanJeremy** [comment]
Can you please test if this is still an issue on 0.8.1?

**Comment by vcidst** [comment]
@borgmanJeremy I've upgraded to Ubuntu 20.20 and haven't had this issue in last two months. I'm using the version `0.6.0+git20191001-2` as it is current stable version coming from default sourcelists
