### ISSUE TITLE
Settings are inaccessible if tray icon is disabled

### ISSUE THREAD

**Issue by bellerofonte** [flameshot-org/flameshot#2334]
### Flameshot Version

v11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS Monterey 12.2

### Description

There is no way to open Flameshot settings again after disabling tray icon on macOS. 

Possible solution - add button 'Flameshot settings' near 'Toolbox settings' at the capture screen.

### Steps to reproduce

1. install and run Flameshot app
2. Open settings
3. Show tray icon -> checked
4. Confirm
5. Oops

### System Information

macOS Monterey 12.2
Macbook Pro 16 M1 Max
Flameshot v11.0.0
default monitor configuration

**Comment by borgmanJeremy** [comment]
Run "flameshot config " from the command line and you can change it back.

**Comment by bellerofonte** [comment]
Yep, works.
But in my case `/Applications/flameshot.app/Contents/MacOS/flameshot config`
Will I receive `new version available` notification while tray icon is hidden?

**Comment by borgmanJeremy** [comment]
I don't think so

**Comment by edwardstorks** [comment]
I have done everything possibly. I acidentally unchecked the Tray Icon in the Configuration. Now I can't get it back. The app is running, and I am able to take a screenshot. But I can't find this `/Applications/flameshot.app/Contents/MacOS/flameshot config` file.

How to enable the Tray Icon back again?
![image](https://github.com/flameshot-org/flameshot/assets/115942881/6a436111-0f4c-4533-a09f-da9260018611)
![image](https://github.com/flameshot-org/flameshot/assets/115942881/ad5face9-7dee-49c5-a585-34a8dc167b51)
