### ISSUE TITLE
11.0.0 not working in macOS Big Sur (11.6.2)

### ISSUE THREAD

**Issue by joeygibson** [flameshot-org/flameshot#2339]
### Flameshot Version

11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

macOS Big Sur 11.6.2

### Description

I had been using a 10.x version installed via Homebrew. I upgraded to 11.0, and after that every time I launch Flameshot, it pops up the "flameshot would like to record this computer's screen", with links to go to system preferences, or "deny". I've gone into system preferences several times, and enabled it; each following time, it's _still_ enabled, but flameshot can't capture the screen. I've also tried unchecking, restarting flameshot, re-checking, restarting flameshot, but it still doesn't work.

I uninstalled the version from brew, and downloaded the `.dmg` from Github, but I'm getting the exact same results. 

### Steps to reproduce

1. On macOS 11.6.2, launch flameshot
2. Go to System Preference and allow it to record the screen
3. Let flameshot restart

### System Information

macOS Big Sur (11.6.2)
Late 2013 Macbook Pro 15" using the laptop screen

**Comment by borgmanJeremy** [comment]
The process shown here has worked for everyone #2331
