### ISSUE TITLE
Feature Request: Make text in the «About» window copy-paste-able 

### ISSUE THREAD

**Issue by Semnodime** [flameshot-org/flameshot#2340]
### Feature Description

Make text in the About window copy-paste-able to ease submitting bug reports.
![image](https://user-images.githubusercontent.com/19511852/151679805-84876da2-e385-4b7a-8a16-7918e1894ebf.png)

**Comment by borgmanJeremy** [comment]
It should be in version 11.

**Comment by mmahmoudian** [comment]
Duplicate of #1732

It is already implemented in the latest version of Flameshot
