### ISSUE TITLE
Change the preset color

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2347]
### Feature Description

At the moment the hexadecimal number of the colors cannot be modified and instead the user have to add a new color and delete the one they don't like. It would be nice to be able to modify them on the spot.

Also would be nice to be able to re-arrange the colors in GUI

![image](https://user-images.githubusercontent.com/390889/151717981-df4d3f72-b54e-48b3-8a0a-10325ccd9d84.png)

**Comment by deo002** [comment]
@mmahmoudian How about removing the spinbox altogether? Users can select a preset by clicking it. In the spinbox's place, we can add 2 arrow buttons for reordering.

**Comment by mmahmoudian** [comment]
I don't know which one of the two circles are you referring to as "spinbox", but I assume it is the lower one. For the sake of this comment and until you correct me I'm going to call the top one "colorwheel" and the lower one "spinbox".

I believe the most intuitive UI would be that the spinbox goes in the center of the colorwheel and spinbox is only shown when one of the circles in the colorwheel is selected. And for reordering, I think dragging the circles in the preset colors is the intuitive way.

All these said, I don't know how easy or hard it is to implement these, plus this is just my personal opinion and other should also express their opinions.

**Comment by deo002** [comment]
> I don't know which one of the two circles are you referring to as "spinbox"

![](https://i.imgur.com/AdfuZ4L.png)
The widget used for selecting presets.

**Comment by deo002** [comment]
> And for reordering, I think dragging the circles in the preset colors is the intuitive way.

I like this idea though. Better than the 2 arrow one.

**Comment by mmahmoudian** [comment]
> The widget used for selecting colors.

Imho this is very unintuitive. As a user I expected to be able to edit the text of that box you showed to change the hex of the selected color. I think the circles should be clickable and selectable (instead of selecting through the box you showed) and then instead of this box there should be a an input field to modify the hex of the selected circle.

**Comment by deo002** [comment]
> I think the circles should be clickable and selectable (instead of selecting through the box you showed) and then instead of this box there should be a an input field to modify the hex of the selected circle.

Sounds good! I would like to work on it.

**Comment by mmahmoudian** [comment]
@deo002 let's first hear the opinion of other devs before diving into the code.

@borgmanJeremy @veracioux what do you think? Any feedbacks on the thread above?

**Comment by borgmanJeremy** [comment]
I think what was discussed here sounds good to me. Dragging the circles seems like it might be complicated but it seems like the most intuitive way to do it.
