### ISSUE TITLE
Flameshot doesn't work under Fedora Linux 35 (KDE)

### ISSUE THREAD

**Issue by gvsafronov** [flameshot-org/flameshot#2352]
### Flameshot Version

Flameshot version: v11.0.0

### Installation Type

Linux Package manager dnf

### Operating System type and version

Linux Fedora 35

### Description

Hello!
Flameshot gui doesn't launch flameshot on Linux Fedora 35. 
Also Flameshot  doesn't work if I click on icon in tray when flameshot is running.
Flameshot version: 11.00
In logs and in terminal-I dodn't see any error's
I use Waylang

### Steps to reproduce

I launch graphic's tray icon

### System Information

Linux Fedora 35
Enviroment: KDE Plasma 5.23.4
Kernel: 5.16.18.200

**Comment by zhullyb** [comment]
Same problem here.

**Comment by gvsafronov** [comment]
> Same problem here.

I',m sorry but you forgett to attach the link.

**Comment by borgmanJeremy** [comment]
Frankly our KDE Wayland experience is not great right now. We probably need someone from the community to commit to working on Wayland KDE.

**Comment by mmahmoudian** [comment]
@gvsafronov we have had somewhat similar issue with Fedora 35 and Pop!_os but other DE. Would you please try the AppImage and let us know if it works for you?

**Comment by kuba-orlik** [comment]
I'm experiencing the same issue on Gnome 41.4 on Wayland. Both regular binary and AppImage have this problem on my setup

**Comment by stribny** [comment]
I installed through https://flathub.org/apps/details/org.flameshot.Flameshot and I also cannot properly launch Flameshot. The process is visible in the system monitor, but no GUI is shown whatsoever.

**Comment by mmahmoudian** [comment]
@stribny how are you running Flameshot?

**Comment by stribny** [comment]
Actually, I just realized I commented under the bug report for KDE. In my case, I am using Fedora with Gnome. After installation, I tried starting Flameshot with standard Gnome launcher, and I also tried `flameshot gui` to run it from the command line.

**Comment by mmahmoudian** [comment]
Try `flatpak run org.flameshot.Flameshot gui` as explained [here](https://flameshot.org/docs/installation/installation-linux/). Flatpak does not put the binary in the PATH. You can create a symlink and put it in your PATH though.

**Comment by stribny** [comment]
Thanks! I tried it this way and I am able to start it. At first, Gnome screenshot will take a screenshot and ask whether the screenshot should be shared with Flameshot. After clicking on "Share", Flameshot app opens.

I don't want to hijack this thread anymore, so thank you for your help!

**Comment by borgmanJeremy** [comment]
This should be resolved with our recent merge to have KDE Wayland use the XDG portal
