### ISSUE TITLE
Screenshot aborts when changing from text to anything else using `flameshot gui`

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2353]
### Flameshot Version

Flameshot v11.0.0 (42917930)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

linux: 5.10.93-1-MANJARO

### Description

When Flameshot is invoked by `flameshot gui`, switching from text tool to anything else would abort the screenshot. this glitch does not happen when flameshot is triggered using clicking on tray icon or when the text tool is first de-selected and then some other tool is selected.

### Steps to reproduce

1. run `flameshot gui`
2. select an area
3. select the test tool and type something
4. click on something else (e.g arrow tool)

### Screenshots or screen recordings

In this video I first invoke flameshot by clicking on the tray icon and show that everything works normal, then I press printscreen button to invoke `flameshot gui` and show that it breaks after attempting to change the tool.

https://user-images.githubusercontent.com/390889/152166216-8d2d68e4-890b-4aa2-a2da-2e82c04a419c.mp4

### System Information

>```
> System:
>   Host: precisiontower Kernel: 5.10.93-1-MANJARO x86_64 bits: 64
>     Desktop: KDE Plasma 5.23.5 Distro: Manjaro Linux
> Graphics:
>   Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
>   Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
>   Display: x11 server: X.Org 1.21.1.3 driver: loaded: amdgpu,ati,modesetting
>     resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz 3: 1080x1920~60Hz
>   OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.40.0
>     5.10.93-1-MANJARO LLVM 13.0.0)
>     v: 4.6 Mesa 21.3.4
>```

**Comment by yutv** [comment]
I have the same issue.

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
linux: 5.11.0-46-generic
ubuntu: 20.04

**Steps to reproduce:**
1. Take Screenshot
2. Select area
3. Choose "Text", enter some text
4. Click to "Arrow"

As result flameshot user interface disappears.
The following lines apper in the `journalctl -f`
```
Feb 04 20:04:47 ubuntu systemd[2839]: Started Application launched by gsd-media-keys.
Feb 04 20:04:47 ubuntu gnome-shell[3128]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x220000a specified for 0x2200008.
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::begin: Paint device returned engine == 0, type: 2
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::setRenderHint: Painter must be active to set rendering hints
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::setCompositionMode: Painter not active
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::translate: Painter not active
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::setPen: Painter not active
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::setBrush: Painter not active
Feb 04 20:04:47 ubuntu gsd-media-keys[108047]: QPainter::setBrush: Painter not active
Feb 04 20:04:53 ubuntu gnome-shell[3128]: Window manager warning: WM_TRANSIENT_FOR window 0x2200008 for override-redirect window 0x2200024 is an override-redirect window and this is not correct according to the standard, so we'll fallback to the root window.
Feb 04 20:04:54 ubuntu gnome-shell[3128]: Window manager warning: WM_TRANSIENT_FOR window 0x2200008 for override-redirect window 0x220002f is an override-redirect window and this is not correct according to the standard, so we'll fallback to the root window.
Feb 04 20:05:01 ubuntu systemd[2839]: gnome-launched-flameshot-108047.scope: Succeeded.
```

**Comment by mmahmoudian** [comment]
@yutv thanks for pointing out that this issue is almost identical to #2283. As the matter of fact I think it is the same issue although I faced it on Xorg!

**Comment by borgmanJeremy** [comment]
@mmahmoudian  can we close this as a duplicate? 

I originally said I could not replicate it, but on a hunch I tried it by using "flameshot gui" instead of the system tray. I CAN reproducte it now with "flameshot gui"
