### ISSUE TITLE
Keyboard shortcut has changed for mac to ⌘ + shift + X , please reflect it in Documentation

### ISSUE THREAD

**Issue by hossein-bakhtiari-revolut** [flameshot-org/flameshot#2354]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 20.6.0
osx: 11.6

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macos

### Description

It was previously the default mac ⌘ + shift +  option + 4 ---> now it's changed to shorter on ⌘ + shift + X,
Please reflect this in README.md

### System Information

MacOS bigsur

**Comment by borgmanJeremy** [comment]
Thanks, i fixed it in the readme.
