### ISSUE TITLE
Feature: Show current tool size and gain option to change via text-entry

### ISSUE THREAD

**Issue by jose1711** [flameshot-org/flameshot#2356]
### Feature Description

It is possible to change current tool size by typing a number. But IMHO:
 - this feature is not immediately visible
 - it would be nice to see the current value
The idea is something like this:

![obrázok](https://user-images.githubusercontent.com/1406222/152287586-13826044-c58a-4b08-91d5-862c98972416.png)
with text item being clickable and editable (and obviously mapped to scrollbar)

**Comment by borgmanJeremy** [comment]
@mmahmoudian @veracioux I'm fine with this proposal. Any objections?

**Comment by mmahmoudian** [comment]
I believe it is a good addition. It would make the UI more intuitive, although I personally would keep the current behaviour as well

**Comment by jose1711** [comment]
> I personally would keep the current behaviour as well

me too, I have nothing against the current behaviour

**Comment by veracioux** [comment]
I concur.
