### ISSUE TITLE
File extensions list selection misaligned

### ISSUE THREAD

**Issue by sybercorp** [flameshot-org/flameshot#2361]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 21.3.0
osx: 12.2

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

macOS 12.2 (21D49)

### Description

The drop-down list for saving a screenshot is off with the exception of the first 2 entries (BMP and HEIC).  Anything after those first 2 options is off by 1, so if you select PNG it will actually be JPG, if you select the first JPEG option it's actually HEIC, etc.  The extension for the very last item in the list is unusable because of this (because it selects the extension listed above it).

### Steps to reproduce

1. Open flameshot
2. Take a screenshot
3. Save the screenshot
4. Attempt to change the file extension/format via the drop-down menu in the save diaglog

### System Information

1. OS: macOS 12.2 (21D49)
2. Model: MacBook Pro (14-inch, 2021)
3. CPU: Apple M1 Pro

**Comment by borgmanJeremy** [comment]
There is a duplicate issue with this and it's under investigation. On mobile so I do t have the link handy. It's actually a bug in qt.

**Comment by sybercorp** [comment]
> There is a duplicate issue with this and it's under investigation. On mobile so I do t have the link handy. It's actually a bug in qt. 

Good to know. I tried searching for existing bugs before I posted it but must not have used the right wording.   So, if it's a Qt bug, is it resolved in the current releases of Qt already if you upgraded your code to that?

**Comment by borgmanJeremy** [comment]
No unfortunately it's present even in qt 6.2.2.

We have a workaround that will go in the next release.
