### ISSUE TITLE
[Bug] flameshot 11.0.0-1 does not show the save icon

### ISSUE THREAD

**Issue by s0h3ck** [flameshot-org/flameshot#2362]
### Flameshot Version

Flameshot 11.0.0-1 

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux

### Description

Issue: ArchLinux package version flameshot 11.0.0-1 does not show the save icon when using the command line shortcut.
Shortcut: ```( flameshot & ) && ( sleep 0.1s && flameshot gui -r | tee /tmp/$_time.png | xclip -selection clipboard -t image/png -i) && (killall flameshot); sleep 10; ```

Package version is Flameshot 11.0.0-1
Distribution: Arch Linux
Location: https://archlinux.org/packages/community/x86_64/flameshot/

Previously working in Flameshot version 0.10.2-2. 

### Steps to reproduce

1. pacman -S flameshot
2. Run the shortcut defined in the description.

### System Information

NA

**Comment by mmahmoudian** [comment]
In the release notes we have explained this, but for a lengthier read checkout https://github.com/flameshot-org/flameshot/issues/2275#issuecomment-1015073816

Also you don't need to do that weird shortcut anymore, as explained in the release notes, we now have a one-off mode which means you don't need to keep the Flameshot in the tray area and in background. Just run `flameshot gui` (with any arguments you want) and it will get closed as soon as you are done with taking the screenshot. The only exceptions are if you pun something or copy something which Flameshot will stay in the background until the pin is closed or the clipboard is changed.

**Comment by s0h3ck** [comment]
Yes sir! According to the release notes it said : "Note that in case one of these options (or --path, --raw also) is used, an Accept button is shown and the Save, Copy, Upload, Pin, Open With buttons are hidden."

I do not have an Accept button nor do I have a Save or Copy or Upload or Pin. So, what is the magic sequence?

If I understand the new language, the command will be as follow : ```flameshot gui --path /tmp/ --clipboard```.

Thanks!

**Comment by mmahmoudian** [comment]
@s0h3ck 
Interesting. If you don't have the accept button, then this is a bug and we should re-open this issue. The accept button looks like this 👇🏼  You might have made it hidden by accident (by default it is marked to be shown)

![image](https://user-images.githubusercontent.com/390889/152543164-703d1b87-1e3c-4601-b65a-0be6261cb31f.png)
![image](https://user-images.githubusercontent.com/390889/152543347-6e43a596-f536-42b8-b578-6c4b90021e3d.png)

**Comment by mmahmoudian** [comment]
I forgot to mention that the "final actions" are `--path <path>`, `--clipboard`, `--raw`, `--upload`, `--pin`, `--print-geometry`. Of course in case you provide `--accept-on-select` you will not see any buttons as Flameshot will close immediately after the mouse release.

**Comment by s0h3ck** [comment]
Yes! I edited the message yesterday. This issue can be closed. Thank you @mmahmoudian! :)
