### ISSUE TITLE
Flameshot GUI on MacOS

### ISSUE THREAD

**Issue by jamalbernhard** [flameshot-org/flameshot#2366]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Monterey 12.1

### Description

Maybe I'm missing something obvious, but after installing using `brew install --cask flameshot`, when I launch`/Applications/flameshot.app` it just runs flameshot in the background with no GUI. So, I created a script containing:
```
#!/bin/bash
/Applications/flameshot.app/Contents/MacOS/flameshot gui
```
Executing this script works, EXCEPT it launches the terminal application to run which then sits on top of whatever I was trying to screenshot in the first place, making it unusable.

Is there a canonical way to get the flameshot GUI working properly in MacOS? Thanks.

### System Information

MacOS Monterey 12.1
MacBook Pro (intel)

**Comment by mmahmoudian** [comment]
I believe in macOS the keyboard shortcut is cmd+shift+x

Give it a try and let me know if it solves your issue. You can find the shortcuts by right clicking on the tray icon, then select Configurations, then go to shortcuts tab and scroll to to bottom.

**Comment by jamalbernhard** [comment]
The shortcut works! Sorry for the noise.

**Comment by mmahmoudian** [comment]
Questions, comments, bug reports and feature requests are always welcome 🤗
