### ISSUE TITLE
I run flameshot gui in terminal and nothing hapens

### ISSUE THREAD

**Issue by dogunbound** [flameshot-org/flameshot#2367]
### Flameshot Version

[dogunbound@dogunbound-systemproductname ~]$ flameshot --version
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavorOS (Gnome edition)

### Description

`[dogunbound@dogunbound-systemproductname ~]$ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[dogunbound@dogunbound-systemproductname ~]$ 
`

I run the command `flameshot gui` in the terminal and it gives me a warning and immediately shuts down. Seems like this maybe a wayland support on gnome problem.

### Steps to reproduce

1. run `flameshot gui` on endeavorOS gnome edition with wayland enabled

### System Information

EndeavorOS gnome edition
wayland

**Comment by borgmanJeremy** [comment]
I cannot replicate this on endeavor OS +  wayland + gnome. This means there is some system difference between your machine and the machines we test on. 

The best way you can help us is to try to replicate this on a clean VM or clean install. Then we can compare what differences might exist.

**Comment by dogunbound** [comment]
Huh, it magically started working today. Maybe a reboot + an update in the past 2 days fixed it. Thanks!
