### ISSUE TITLE
Copying, Uploading not working 

### ISSUE THREAD

**Issue by TheBlapse** [flameshot-org/flameshot#2370]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.2
linux: 5.16.5-arch1-1
arch: unknown

### Installation Type

User repository (AUR)

### Operating System type and version

linux: 5.16.5-arch1-1

### Description

After updating to version 11 I am not able copy or upload the screenshot even after enabling those options from configurations.
![image](https://user-images.githubusercontent.com/76247922/152640900-fe3d4675-f432-48ab-9a8f-893dcd461e1f.png)

### Screenshots or screen recordings
![Peek 2022-02-05 17-23](https://user-images.githubusercontent.com/76247922/152641023-4be21b24-a23d-422a-a025-952302d2f50c.gif)

### System Information

linux: 5.16.5-arch1-1 
i3 window manager
X session

**Comment by mmahmoudian** [comment]
@TheBlapse I wonder why did you close this issue. Did you manage to find the solution?

**Comment by TheBlapse** [comment]
Yes @mmahmoudian it was some issue my window manager's configuration, it worked fine when I started from CLI.

**Comment by mmahmoudian** [comment]
I can't see how some i3 config can cause this behaviour.

If you still have this issue, would you please paste here your config file (`~/.config/flameshot/flameshot.ini`)

**Comment by TheBlapse** [comment]
> I can't see how some i3 config can cause this behaviour.

I had something like this in my config
```
bindsym $mod+Shift+S exec flameshot gui  -p /home/user/Pictures/screenshots/
```
that's why it was not working, after removing `-p /home/user/Pictures/screenshots/`, it started working.

**Comment by mmahmoudian** [comment]
It seems to me that you have also (perhaps by accident) unchecked the Accept button. I was looking for that to see if you have defined any of the [final actions](https://flameshot.org/docs/advanced/commandline-options/#final-actions) but I didn't see it in the screen-recording you provided.

![image](https://user-images.githubusercontent.com/390889/152687070-798fffe5-bea3-4484-8be0-338e55deeda3.png)

Anyways, I'm glad that it is resolved and thank you for being responsive 👍🏼

**Comment by TheBlapse** [comment]
oh yes its actually unchecked!
