### ISSUE TITLE
Text annotation tool doesn't show up on Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by ijash** [flameshot-org/flameshot#2375]
### Flameshot Version

Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint 19.3 Cinnamon. based on ubuntu 18.04

### Description

**Text annotation** doesn't show up.
In the screenshot, text option doesn't show up too..

_and pin icon doesn't show up too, but that doesn't matter for the moment._
### Steps to reproduce

1. run flameshot gui
2. capture area
3. check text annotation

### Screenshots or screen recordings

**Text annotation** doesn't show up.:
![e9397885-7c67-4f89-af40-f7029f00c719](https://user-images.githubusercontent.com/30673286/152682122-1fe606b5-f515-416b-bd56-e68f87e68b43.jpeg)

but in homepage seems had the icon:
![image](https://user-images.githubusercontent.com/30673286/152682687-e2f28dcb-2864-4a12-9a17-7fdc7a95325a.png)

### System Information

_https://flameshot.org/guide/issue-reporting/ <<< url in the template not working_

```
Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4
```
https://termbin.com/ungl
```

System:
  Host: LM-PC Kernel: 5.4.0-97-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8 
  Distro: Linux Mint 19.3 Tricia 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 390.144 
  Display: x11 server: X.Org 1.20.8 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa 
  resolution: 1920x1080~60Hz, 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 390.144 
```

**Comment by borgmanJeremy** [comment]
That version is ancient and no longer supported. Please download the latest version from snap, flatpak, or our release page.
