### ISSUE TITLE
Input Text after couter bubble display error.

### ISSUE THREAD

**Issue by zw963** [flameshot-org/flameshot#2388]
### Flameshot Version

 ╰─ $ flameshot --version
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch linux

### Description

It more easy to describe use screen.

### Steps to reproduce

1. run flameshot
2.  click couter bubble to create a bubble
![image](https://user-images.githubusercontent.com/549126/152795315-a460d75a-32b1-4474-a47a-a9416a0cff36.png)
3. pressing `t` hotkey in the keyboard try to add text in current place
4.  It add a red circle under the point unexpectly.

### Screenshots or screen recordings

No

### System Information

GNOME + Wayland on arch linux.

**Comment by borgmanJeremy** [comment]
This should be fixed by #2386
