### ISSUE TITLE
Fixed position of round buttons in interface

### ISSUE THREAD

**Issue by MurzNN** [flameshot-org/flameshot#239]
At now round buttons in interface wraps selected rectangle, and if size is small - can be placed in left-right-top side of area. 

This looks cool, but too bad for usability - often used buttons every time located in random place, so I need to look closely for search them.

Will be good to see all buttons in fixed order and place, eg in one line at bottom side of selected area, even if the selected area is very small.

**Comment by lupoDharkael** [comment]
The order of the buttons is always the same, they are given a position counter-clockwise starting from the bottom.

**Comment by MurzNN** [comment]
Order is same, but position of last buttons is random :(

**Comment by MurzNN** [comment]
My suggestion is to draw all buttons in one horisontal line at bottom side of rectangle, centered by middle of rectangle. If rectangle is near the side of screen - stick outside button to this side of screen.

**Comment by borgmanJeremy** [comment]
Not intending to change this behavior at this time.
