### ISSUE TITLE
After the latest update, all my Flameshot keyboard shortcuts stopped working.

### ISSUE THREAD

**Issue by zell-mbc** [flameshot-org/flameshot#2391]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.5-arch1-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux: 5.16.5-arch1-1

### Description

After the latest update, all my Flameshot keyboard shortcuts stopped working.
Journalctl shows the following error when pressing any one of my shortcuts:

`Feb 07 16:37:12 hermes kded5[53716]: Cannot find '.graphicCapture' in object / at org.flameshot.Flameshot`

The "." before "graphicCapture" is a little strange, it's not present in my settings screen.
Starting flameshot via the taskbar icon or from the cli works fine.

### Steps to reproduce

1. Start journalctl -f in a terminal
2. Press any of the keyboard shortcuts defined before the upgrade
2. Observer the error

### Screenshots or screen recordings

Here's one of the settings, no "." before graphicCapture

![image](https://user-images.githubusercontent.com/29018767/152821710-da426a28-2541-409b-8b46-de5c34985fd3.png)

### System Information

Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.5-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6920HQ CPU @ 2.90GHz
Memory: 31,1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530

**Comment by tobil4sk** [comment]
I'm also having this issue where my shortcuts do not work, however, I don't get the "Cannot find '.graphicCapture'" error and it doesn't seem to add a dot in front of graphicCapture. I am on the same version of Flameshot, and on Manjaro.

This is my journal output:
```
Feb 07 20:37:42 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "fullScreen" : ("", "true", "0", "0")
Feb 07 20:37:48 manjaro systemsettings5[13344]: 
Feb 07 20:37:48 manjaro systemsettings5[13344]: 1
Feb 07 20:37:50 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "fullScreen" : ("", "true", "0", "0")
Feb 07 20:37:54 manjaro systemsettings5[13344]: 
Feb 07 20:37:54 manjaro systemsettings5[13344]: 1
Feb 07 20:37:55 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "fullScreen" : ("", "true", "0", "0")
Feb 07 20:37:58 manjaro systemsettings5[13344]: 
Feb 07 20:37:58 manjaro systemsettings5[13344]: 1
Feb 07 20:38:00 manjaro systemsettings5[13344]: 
Feb 07 20:38:00 manjaro systemsettings5[13344]: 1
Feb 07 20:38:01 manjaro systemsettings5[13344]: 
Feb 07 20:38:01 manjaro systemsettings5[13344]: 1
Feb 07 20:38:05 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "fullScreen" : ("Pictures/Screenshots", "false", "0", "0")
Feb 07 20:38:06 manjaro systemsettings5[13344]: 
Feb 07 20:38:06 manjaro systemsettings5[13344]: 1
Feb 07 20:38:09 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "graphicCapture" : ("Pictures/Screenshots", "0", "0")
Feb 07 20:38:10 manjaro systemsettings5[13344]: 
Feb 07 20:38:10 manjaro systemsettings5[13344]: 1
Feb 07 20:38:12 manjaro kded5[1110]: D-Bus call: "org.flameshot.Flameshot" : "/" : "graphicCapture" : ("Pictures/Screenshots", "3000", "0")
Feb 07 20:38:13 manjaro systemsettings5[13344]: 
Feb 07 20:38:13 manjaro systemsettings5[13344]: 1
```

I can still open it using `flameshot gui` or manually clicking the tray icon.

**Comment by mmahmoudian** [comment]
@zell-mbc & @tobil4sk 
Well, in the release note of v11.0.0 we have explained that we no longer depend of DBus calls. the updated config file for KDE can be found [here](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde.khotkeys). Basically you should convert all thos DBus calls to commands (e.g `flameshot gui`, `flameshot gui --clipboard`). Also please make sure to read the very short documentation on [final actions](https://flameshot.org/docs/advanced/commandline-options/#final-actions) as you perhaps have also missed that too from the release notes.

**Comment by tobil4sk** [comment]
I did some digging and I managed to fix this issue for myself. It seems to be related to: #2277

To fix it I removed the old kde shortcuts, restarted my system, and then redid the steps listed here:
https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop

**Comment by zell-mbc** [comment]
I did indeed miss the release notes. But with your help above I got things converted asap and am back in business again :-)
Thanks for your help and even more so for the best screen shot tool out there, no doubt!
I use it constantly…

**Comment by mmahmoudian** [comment]
@zell-mbc I'm glad you find it useful 😃 I know that our documentation is not the best out there, but we are constantly working on the code and documentation, so if you think there are ways to improve our documentation or the software, please let us know (or even better, create a Pull Request). Any contribution by any means can help us progress and make Flameshot better.

**Comment by dausruddin** [comment]
I am on Arch KDE and steps above didn't work. Here what I did to fix it.

1. Remove flameshot (`pacman -Rns flameshot`) and the shortcuts.
2. Reboot
3. Install flameshot
4. Import shortcut.

Seems that reinstalling flameshot was necessary for me. . Hope it helps someone.
