### ISSUE TITLE
Unrecognized settings `setSaveAsFileExtension`, `saveAfterCopyPath`

### ISSUE THREAD

**Issue by mcp292** [flameshot-org/flameshot#2393]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

I get an error when trying to issue `flameshot gui` from a keybinding. I see no documentation listed in the README about an update breaking this.

### Steps to reproduce

```sh
$ flameshot config --check
flameshot: error: Unrecognized setting: 'setSaveAsFileExtension'

flameshot: error: Unrecognized setting: 'saveAfterCopyPath'
```

### System Information

Arch Linux
dwm

**Comment by borgmanJeremy** [comment]
The sematics for some of the config options changed in version 11. But it should allow you to autoresolve them. It will blow away those options and you can reconfigure them in the gui.

**Comment by mcp292** [comment]
It sounds like you're describing "resolve" as just deleting those lines. I want those lines for reference so I can update the syntax. I'd rather know the syntax and have access to updated documentation than have to config through the gui. Is this possible?

**Comment by borgmanJeremy** [comment]
@mmahmoudian do we have an update annotated config file? I tend to just edit with the GUI to figure out the variable name.

**Comment by mmahmoudian** [comment]
@borgmanJeremy  because the ini format does not support comment lines, I have already gave up on the idea of having a well-annotated config sample.

@mcp292 the `setSaveAsFileExtension` should be a string of lowercase letters (e.g `png`), I guess you have the messed up config which was introduced by a bug in v0.10.x. As for `saveAfterCopyPath` though, I don't think it is a valid config argument. We have `savePath` (which accepts a path) and `saveAfterCopy` (which is boolean), but we don't have their mix!

**Comment by mcp292** [comment]
> @mcp292 the setSaveAsFileExtension should be a string of lowercase letters of the extension (e.g png), I guess you have the messed up config which was introduced by a bug in v0.10.x. 
Will check it out and report back.

> As for saveAfterCopyPath though, I don't think it is a valid config argument. We have savePath (which accepts a path) and saveAfterCopy (which is boolean), but we don't have their mix!
Very odd, I definitely found that in the documentation somewhere and have been using it for years. Might of been in `flameshot config --help`.

**Comment by mcp292** [comment]
@mcp292 the setSaveAsFileExtension should be a string of lowercase letters of the extension (e.g png), I guess you have the messed up config which was introduced by a bug in v0.10.x.

Yes this is what is there:
```
setSaveAsFileExtension=By extension [default: *.png] (*.png)
```

I am changing it to:
 ```
setSaveAsFileExtension=png
``` 

despite the `*.png` hint, yes?

**Comment by mcp292** [comment]
Where are the config file variables documented? I would like to know what `savePathFixed` does for example.

**Comment by borgmanJeremy** [comment]
You would need to reference the source code. It's possible to modify the file by hand but isn't really intended.

**Comment by mcp292** [comment]
Okay thank you for clarifying, so my takeaway is for this project only config with the gui.

**Comment by mcp292** [comment]
Okay thank you very much for the info!

For anyone following this thread the supported solution is to hit `Resolve All` which will remove those options, then issue `flameshot config` to re-set them through the GUI.

In my case `saveAfterCopyPath` has been removed and `setSaveAsFileExtension` was renamed to `saveAsFileExtension`. The proper syntax is:
```
saveAsFileExtension=png
```

**Comment by mmahmoudian** [comment]
There is still something you can do. You can use `flameshot config --check` to get some information on what is wrong and what is expected

**Comment by mcp292** [comment]
Thanks for the tip!
