### ISSUE TITLE
Flameshot v11.0 locks up KDE when saving screenshot

### ISSUE THREAD

**Issue by YMan84** [flameshot-org/flameshot#2398]
### Flameshot Version

Flameshot 11.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

I have flameshot installed natively through pacman from the "community/flameshot" repo. 

When running ```time flameshot gui```, the gui starts up instantly, and I can take a screenshot, but after I click the save button it locks up the entire KDE desktop for about 5-10 seconds (I cannot select anything from the taskbar or within Dolphin) until I assume it saves the screenshot, then KDE becomes responsive again. I'm having this issue on both my laptop and on my desktop, which are both running the same OS and Kernel. Laptop is using Intel HD graphics, and Desktop has an NVIDIA graphics card. 

result of:
```time flameshot gui```
flameshot: info: Capture saved as /home/yuriy/Syncthing/Screenshots/20220208_232023.png
real    0m28.897s
user    0m0.810s
sys     0m0.205s

### Steps to reproduce

1. run ```flameshot gui```
2. select region and click the save button
3. KDE desktop and KDE applications hang for a couple of seconds while the screenshot presumably gets saved. 

### System Information

OS: EndeavourOS [x86_64] (Arch Linux Based)
Kernel: 5.16.5-arch1-1
DE: KDE Plasma 5.23.5
WM: KWin (X11)

**Comment by senses3** [comment]
Same thing happening for me on 5.15.19-1-MANJARO with flameshot v11.

**Comment by mmahmoudian** [comment]
I cannot reproduce this on using Flameshot  v11.0.0 (bcb4041e)

My system info:
> Operating System: Manjaro Linux
> KDE Plasma Version: 5.23.5
> KDE Frameworks Version: 5.90.0
> Qt Version: 5.15.2
> Kernel Version: 5.10.96-1-MANJARO (64-bit)
> Graphics Platform: X11
> Processors: 20 × Intel® Core™ i9-10900K CPU @ 3.70GHz
> Memory: 31.1 GiB of RAM
> Graphics Processor: AMD Radeon Pro WX 3200 Series

```console
❯  time flameshot gui
kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file:///home/mehrad/Pictures/.directory")
Qt: Session management error: networkIdsList argument is NULL
flameshot: info: Capture saved as /home/mehrad/Pictures/2022-02-10_13-21.png
flameshot gui  0.98s user 0.21s system 11% cpu 10.261 total
```

**Comment by xRasea** [comment]
same issue here
copy pasting my clipboard during this timeframe in discord results in discord temporarily going OOM and restarting, if that says anything.

result of `time flameshot gui`

```
real	0m27,375s
user	0m0,171s
sys	0m0,055s
```

Operating System: Arch Linux x86_64
Qt Version: 5.15.3
Kernel Version: 5.16.13-lqx2-4-lqx 
Window Manager: i3
Graphics Platform: X11
CPU: AMD Ryzen 5 1600 @ 3.4GHz
Graphics Processor: AMD ATI Radeon RX 580

**Comment by awerlang** [comment]
The setting that triggers the partial lock up is "Copy file path after save"

It's definitely related to https://github.com/flameshot-org/flameshot/pull/2053 and https://github.com/flameshot-org/flameshot/blob/v11.0.0/src/utils/screenshotsaver.cpp#L51 IOW a race condition, as the workarounds seem to indicate.

**Comment by embeddedt** [comment]
I'm also encountering this issue when using the upload to Imgur option.

Flameshot Version: 11.0.0-4 (from `pacman`)
Operating System: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.12-arch1-1 (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE2

**Comment by borgmanJeremy** [comment]
@YMan84 do you have multiple 4k monitors? Do you have notifications working on KDE?

**Comment by YMan84** [comment]
> 

I have just have one 1440p monitor,
And yes, notifications are enabled in KDE

**Comment by hissssst** [comment]
I am experiencing the same issue __every time__ flameshot's saving window appears.
It's sway on nixos with 1080p display.
This is unrelated to the save to clipboard option

**Comment by mmahmoudian** [comment]
I **cannot** reproduce this. I am on Manjaro KDE (fresh install) and Flameshot v11.0.0 (0870eca8)

**Comment by embeddedt** [comment]
@mmahmoudian Here are the steps that can always reproduce this on an Arch installation updated to latest packages yesterday:

1. Run `flameshot gui` in the Terminal.
2. Select an area.
3. Click the "upload to Imgur" button.
4. The spinner will begin spinning and then freeze. The entire KDE user interface (e.g. the start menu) will remain unresponsive during this time, but you will be able to interact with other programs.
5. After about 10-15 seconds, the upload will finish and the system will resume functioning as normal.

**Comment by mmahmoudian** [comment]
@embeddedt this thread is not about uploading, it is about saving to file.

**Comment by embeddedt** [comment]
@mmahmoudian If I enable "Copy file path after save" in the options as described [above](https://github.com/flameshot-org/flameshot/issues/2398#issuecomment-1075825146), I get the same behavior when saving to a file. So it's probably related to whatever logic interacts with the clipboard.

**Comment by xRasea** [comment]
This behaviour has been consistent on my machine. Across multiple desktop environments, configurations, kernels, settings changed (save file after copy, copy path after saving etc). I can currently get one screenshot per 30ish seconds which isn't quite perfect.

Not necessarily locking up the system, but flameshot being unusable for 25~30 seconds.

If I hit "save", flameshot is unusable for 30 (25~30) seconds then usable again but I can work with the screenshot at least as it gets saved properly. 
If I "copy", flameshot is unusable for 30 seconds, and trying to use whatever is stored on my clipboard will cause arbitrary behaviour, mostly causing programs to go OOM (chromium, electron, firefox) Save after copy doesn't change anything. 
If I hit "Upload", it lets me use the window to properly copy url path or save image after the 30 seconds have passed. Behaviour isn't affected by any setting.

Changed clipboard managers, no thing good came out of it but rather the possibility that I now have a broken clipboard manager due to changing what worked to try finding a fix.

**Comment by borgmanJeremy** [comment]
The issue is most likely a notification manager configuration on your desktop since it cannot be reproduced in a clean VM. You can also post your config file and I can test with that specific config file.

**Comment by embeddedt** [comment]
It is necessary to enable either the "copy file path after save" or "copy URL to clipboard" options to reproduce the issue, depending on which of the actions you are performing.

**Comment by borgmanJeremy** [comment]
This is stale since no one can replicate it. I am going to close it for now and if there is ever new info we can reopen it.
