### ISSUE TITLE
Auto copy url to clipboard after upload to Imgur

### ISSUE THREAD

**Issue by MurzNN** [flameshot-org/flameshot#241]
Will be good to have an option for auto copy url to clipboard after successful upload to Imgur, with only popup notify and auto-close upload window.

**Comment by WEBBRACE** [comment]
Такая возможность должна была быть изначально, сделайте, очень жду!

**Comment by c1tru55** [comment]
:+1: must have option, I'm pretty sure that 90% of time this awesome app is used to select area on the screen, add some arrows/text, upload somewhere and automatically get URL copied in clipboard. less actions you need to do in the workflow - is **better**. this modal window after upload is just unnecessary.

**Comment by gburgwardt** [comment]
Bumping this because I couldn't find a way to implement it. What would need to be done?

**Comment by thepurple** [comment]
I guess we should make it configurable and add hotkeys for different features. Different people wants different default behavior.

**Comment by rfaile313** [comment]
Just noting here that this already seems to be the case. Demonstration:

![ezgif-7-f0e33de986bf](https://user-images.githubusercontent.com/13829168/133598347-5f3d9d48-95c2-4138-9fe0-482155729d43.gif)

Can probably close this issue?

**Comment by thepurple** [comment]
It was implemented a long time ago.
It should be closed.
