### ISSUE TITLE
Unrecognized option `setSaveAsFileExtension`

### ISSUE THREAD

**Issue by RayZ0rr** [flameshot-org/flameshot#2413]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.15.21-1-lts

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

Getting error on opening flameshot because of `setSaveAsFileExtension` is being reported as unknown option. Saw this related issue https://github.com/flameshot-org/flameshot/issues/2393 with the fix. However, in the [example file](https://github.com/flameshot-org/flameshot/blob/master/flameshot.example.ini), the option is still provided.

### System Information

Arch Linux
i3-gaps

**Comment by veracioux** [comment]
Thanks!
