### ISSUE TITLE
Help tooltip not displaying properly

### ISSUE THREAD

**Issue by Xenorio** [flameshot-org/flameshot#2416]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora Linux 35

### Description

The help tooltip in the middle of the GUI is not being displayed properly

### Steps to reproduce

1. run ``flameshot gui``
2. look at your screen

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/39472201/153616285-0ebc4988-1a3b-4722-aec1-7ab9e2e681c1.png)

### System Information

![image](https://user-images.githubusercontent.com/39472201/153616081-7b39ce67-14b0-43ee-a66d-e95eb2c78738.png)
![image](https://user-images.githubusercontent.com/39472201/153616198-ccbc2ace-f6e5-4646-bcfb-6abe3191ae0f.png)
![image](https://user-images.githubusercontent.com/39472201/153616235-4eacc54f-e170-41b7-be96-7dbd0d74cde3.png)

**Comment by skipperTux** [comment]
I can confirm this bug on Fedora 35 (Gnome), [Nvidia driver](https://negativo17.org/nvidia-driver/), X11 and Flameshot installed from Fedora repository (RPM), Flameshot v11.0.0 (-) compiled with Qt 5.15.2.
However the [Flatpak version](https://flathub.org/apps/details/org.flameshot.Flameshot) does not have this issue.

**Comment by borgmanJeremy** [comment]
Per #2539 this is an upstream bug that we are not planning to work around in flameshot since it is solved in newer versions of Fedora.
