### ISSUE TITLE
Copy shortcut on mac in Russian layout selects the circle instead of copying

### ISSUE THREAD

**Issue by RusackN1** [flameshot-org/flameshot#2417]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 21.3.0
osx: 12.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS 12.2

### Description

So, when the layout is in English, no problems. cmd+C works perfectly fine.
Whenever the layout is in Russian, cmd+C selects the circle-drawing feature instead of copying the screenshot. 

### Steps to reproduce

1. select area for a screenshot
2. change keyboard layout to Russian
3. click command+c

### System Information

MacBook Pro M1 (macOS Monterey 12.2)

**Comment by mmahmoudian** [comment]
Isn't this the duplicate of #2406?

**Comment by RusackN1** [comment]
oops, sorry, it is :)
