### ISSUE TITLE
Unable to capture screen on ubuntu 21

### ISSUE THREAD

**Issue by luisbattle** [flameshot-org/flameshot#2418]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
linux: 5.13.0-28-generic
ubuntu: 21.10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

PRETTY_NAME="Ubuntu 21.10" NAME="Ubuntu" VERSION_ID="21.10" VERSION="21.10 (Impish Indri)" VERSION_CODENAME=impish ID=ubuntu ID_LIKE=debian HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" UBUNTU_CODENAME=impish

### Description

When I try to take screenshot flameshot return unable to capture screen

### Steps to reproduce

Execute the following command:
flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.

### Screenshots or screen recordings

When I try to get a screenshot of Ubuntu is opened(not flameshot), then I press Cancel and receive the error "Unable to capture"
![image](https://user-images.githubusercontent.com/22923322/153721123-ead9dbfb-06dc-43c2-a7ef-3f118d5d31c5.png)

### System Information

![image](https://user-images.githubusercontent.com/22923322/153721243-cc0c9ada-6015-40c7-9ee3-e39165579314.png)

**Comment by loxK** [comment]
Using Wayland ? I have the same behavior on Wayland sessions. Try this command in the terminal, and report back with the resulting output:

```bash
echo $XDG_SESSION_TYPE
```

**Comment by luisbattle** [comment]
@loxK thanks for your response!
This is the output:
luisbattle@luis-ProBook-440:~$ echo $XDG_SESSION_TYPE
wayland
luisbattle@luis-ProBook-440:~$
 
Do you know how to resolve it?

**Comment by loxK** [comment]
I've had the same experience trying the Wayland session. So I went back to X11 for now on. To do it, click your username on the login screen, then click the cog icon that appears bottom right of the screen. Choose "Ubuntu on xorg", or "Ubuntu" if you have an "Ubuntu on wayland" option.

**Comment by luisbattle** [comment]
@loxK thanks! The workaround its worked! 
another question , when I press print screen doesn't open flameshot... only take the screen with another application.
Do I need to configure something else ?
Thanks for all

**Comment by loxK** [comment]
@luisbattle you need to configure custom shortcuts. Got to settings > keyboard and customize shortcuts. I removed the default shortcuts for 
- `Print Screen`
- `Shift` + `Ctrl` + `Print screen`
- `Shift` + `Print screen`

I then created new one like so:
- `Print screen`, with command: `/snap/bin/flameshot full -p ~/Images/Screenshots`
- `Shift` + `Ctrl`+ `Print screen`, with command: `/snap/bin/flameshot gui -c`
- `Shift` + `Print screen`, with command: `/snap/bin/flameshot gui -p ~/Images/Screenshots`

**Comment by luisbattle** [comment]
@loxK It's worked! you are the best!

**Comment by jerry1970** [comment]
When I do `loginctl` to get the session and then `loginctl show-session <SESSION> -t Type`, I get `Type=X11`. So no Wayland but still no clipboard using Flameshot v11. I reverted back to the repo version:
```
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5
```

**Comment by loxK** [comment]
@jerry1970 wrong thread, it is not about clipboard issues. Search other issues.
