### ISSUE TITLE
Auditory Confirmation

### ISSUE THREAD

**Issue by Beinsezii** [flameshot-org/flameshot#242]
I propose the option of a simple auditory confirmation of sorts to make sure that the screenshot was captured, such as a quick beep or click. This'll make it clear if the screenshot captured successfully.

Low priority. Unlike with Windows, I've yet to have anything steal access from my global commands, so the screenshots always capture. Still mildly paranoid though.

As an aside, this program 100% needs some way to set the color more precisely (#RRGGBB or something) via the config file or UI, as not knowing your exact color is kinda annoying when you're trying to synchronize themes between all your graphical apps. Not going to make a ticket for this as it already has a few dedicated tickets.

**Comment by lupoDharkael** [comment]
Please, open individual issues for every different suggestion. It is easier to track that way just reading the tittle.
