### ISSUE TITLE
Save location is being reset to /run/user/1000/doc/by-app/snap.flameshot 

### ISSUE THREAD

**Issue by amitguptagwl** [flameshot-org/flameshot#2421]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
linux: 5.8.0-36-generic
ubuntu-core: 20

### Installation Type

Snap from

### Operating System type and version

Ubuntu 20.10

### Description

Save location is being reset to "/run/user/1000/doc/by-app/snap.flameshot" every time I start my computer. I've changed the configuration and set default location to Downloads. But it sets to Pictures folder. That also will work. But when I restart my computer this again sets to above mentioned path. There I need to find the screenshot in randomly generate folders.

### Steps to reproduce

1. run flameshot
2. take screenshot
3. save on desire location
4. You'll not find it. 
5. Check the system notifications to check the actual location (/run/user/1000/doc/by-app/snap.flameshot/<random folder name>)
6. Change flameshot configuration to change the default save location
7. Restart computer
8. Check flameshot configuration. You'll find that the location is reset again.

### System Information

Ubuntu 20.10

**Comment by mmahmoudian** [comment]
@borgmanJeremy can this be related to #2147 and #1144?

**Comment by borgmanJeremy** [comment]
@mmahmoudian It sounds similar. 20.10 is deprecated though and it works on 21.10.

It also seems broken on 20.04 which is still under maintenance. However on 20.04 if you manually add the file suffix it works.

**Comment by borgmanJeremy** [comment]
Also the flatpak works fine on 20.04. 

To be completely honest since the snap is fixed on newer versions of ubuntu, and the flatpak works fine on old versions I am not going to spend time on this one.

**Comment by mmahmoudian** [comment]
@amitguptagwl thanks for reporting this bug. Considering the valid points of @borgmanJeremy (20.10 is not supported by Ubuntu, Flatpak works fine, ...) I've close this issue. I suggest using the Flatpak or trying .deb file from our release page.

As a general friendly suggestion, I strongly suggest you to upgrade your Ubuntu to a more recent version so that you get security updates from Ubuntu.
