### ISSUE TITLE
Double click closes flameshot (successfully)

### ISSUE THREAD

**Issue by Aster89** [flameshot-org/flameshot#2427]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.5-arch1-1
arch: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Archlinux (updated at least daily)

### Description

Right click results in flameshot closing (without a confirmation dialog, if closing on double click is intended behavior)

### Steps to reproduce

1. run `flameshot gui && echo oooops`
2. select any rectangular area
3. double click in it

You'll see flameshot closing abruptly, and the terminal printing `oooops` indeed, meaning flameshot terminated successfully.

### System Information

1. Archlinux updated frequently and regularly
2. no special configuration, plus Arandr UI doesn't really show any interesting info; but if you really need some info, tel me and I'll provide it
3. I use `i3` with Xorg

**Comment by mmahmoudian** [comment]
I'm confused, double-click or right click?
![image](https://user-images.githubusercontent.com/390889/154103941-07df72a0-0f65-47df-868f-04d0eaea0156.png)

**Comment by mmahmoudian** [comment]
![image](https://user-images.githubusercontent.com/390889/154104559-9ff050ad-1935-40ac-898b-21e206c4bd1c.png)

**Comment by mmahmoudian** [comment]
Shall we close this issue?

**Comment by borgmanJeremy** [comment]
Yes but as we discussed on another issue I think we need a way to disable this.

**Comment by mmahmoudian** [comment]
@borgmanJeremy while i was trying to investigate this issue I realized double right-click also copies which it should not since we explicitly have stated that the "Left Double-click" should copy.

**Comment by Aster89** [comment]
@borgmanJeremy , can you link the other issue?

In my opinion the left double-click should have no functionality at all, because it breaks some workflows. For instance, it happens to be triggered everytime I click somewhere to finish a text insertion and click again to begin a new one.

**Comment by mmahmoudian** [comment]
@Aster89 it is #2374

**Comment by borgmanJeremy** [comment]
#2432 will resolve this

**Comment by borgmanJeremy** [comment]
Merged
