### ISSUE TITLE
FLAMESHOT DOES NOT START IN GNOME 41 WAYLAND

### ISSUE THREAD

**Issue by bambinounos** [flameshot-org/flameshot#2430]
### Flameshot Version

Version I am using flameshot-11.0.0-1.ubuntu-20.04.amd64
After upgrading gnome 3.36 to 41, Flameshot does not work.
When I use flameshot gui, it takes a capture successful

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

UBUNTU 20.04.03

### Description

The icon is not showed in the notification bar and when I click the app it does not start.

### System Information

I am using wayland, and the main information is here.
Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
System:
  Host: berenisse-V14 Kernel: 5.13.0-28-generic x86_64 bits: 64 
  Desktop: Gnome 41.1 Distro: Ubuntu 20.04.3 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel driver: i915 v: kernel 
  Display: wayland server: X.Org 1.21.1.3 driver: i915 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics (JSL) v: 4.6 Mesa 21.2.6 

0: +*XWAYLAND0 1920/310x1080/170+0+0  XWAYLAND0

Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
00:02.0 VGA compatible controller: Intel Corporation JasperLake [UHD Graphics] (rev 01)
AVISO: debería ejecutar este programa como superusuario.
  *-display                 
       descripción: VGA compatible controller
       producto: JasperLake [UHD Graphics]
       fabricante: Intel Corporation
       id físico: 2
       información del bus: pci@0000:00:02.0
       versión: 01
       anchura: 64 bits
       reloj: 33MHz
       capacidades: vga_controller bus_master cap_list
       configuración: driver=i915 latency=0
       recursos: iomemory:600-5ff iomemory:400-3ff irq:127 memoria:6000000000-6000ffffff memoria:4000000000-400fffffff ioport:4000(size=64) memoria:c0000-dffff
AVISO: la salida puede ser incompleta o imprecisa, debería ejecutar este programa como superusuario.

Linux berenisse-V14 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
I would be thankful if you only put the appropriate information in the requested fields and to NOT use ALL CAPS. Thank you.

Apart from these, please answer these questions:

Q1: Do you see the icon in the tray area when you run `flameshot` in your terminal?
Q2: Did I understand correctly that you can successfully capture a screenshot and save it when you run `flameshot gui` in terminal?
Q3: What do you mean by "when I click the app it does not start"? Do you mean that when you open your application list and you click on the Flameshot icon, it does not open Flameshot in the tray area?

**Comment by bambinounos** [comment]
So sorry about that.
Q1: Do you see the icon in the tray area when you run flameshot in your terminal?
NO
PLEASE CHECK THE CAPTURE
![Captura de pantalla de 2022-02-15 11-40-26](https://user-images.githubusercontent.com/65610134/154107815-e526b99c-dd53-4132-84d5-e73f74c4464b.png)


Q2: Did I understand correctly that you can successfully capture a screenshot and save it when you run flameshot gui in terminal?
YES
Q3: What do you mean by "when I click the app it does not start"? Do you mean that when you open your application list and you click on the Flameshot icon, it does not open Flameshot in the tray area?
When you click here
![Captura de pantalla de 2022-02-15 11-43-10](https://user-images.githubusercontent.com/65610134/154108103-94f882ce-77f5-465a-afa9-973cccad30ba.png)

**Comment by mmahmoudian** [comment]
To me it seems you don't have systray. It was removed from Gnome and you should install it manually in Gnome these days:
https://ep.gnt.md/index.php/how-to-install-and-enable-gnome-system-tray-icons-in-debian-10/

**Comment by bambinounos** [comment]
Thans for your help.
You are right and it was solved
if some have the same problem it needs to do.
I think it is the easiest way.
Download the extension manager.
https://github.com/mjakeman/extension-manager
Install it
run it and search
![imagen](https://user-images.githubusercontent.com/65610134/154143273-37df7a1b-6b2a-4958-89c4-3cdb16231e18.png)
When it is installed
add the application flameshot to the tray
![imagen](https://user-images.githubusercontent.com/65610134/154143592-44503a94-a9da-476a-ab51-6b07c801e43f.png)
Thanks
