### ISSUE TITLE
no working keyboard shortcuts if launching gui with -r and -p parameters

### ISSUE THREAD

**Issue by Giraffaman** [flameshot-org/flameshot#2431]
### Flameshot Version

v11.0.0 (-)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Manjaro 21.2.3 (xfce4)

### Description

Hi,

Just updated and got the prompt described in #2393, chose "resolve all", ran "flameshot config" to make sure the save path is still set. Also ran 'flameshot config --check' which reported no errors.

Now I can run "flameshot gui" in the terminal and copying/saving screenshots using ctrl+c/s works fine. However, when I use my keyboard shortcuts configured through xfce4's application shortcuts, flameshot gui opens, but ctrl+c/s does nothing. I see no errors in journalctrl.
My application shortcut is bound to ctrl+shift+print and runs 'flameshot gui -r -p /home/user/Pictures/Screenshots'. Using these parameters in the terminal also launches the gui without working shortcuts.

Is there anything else I can check or are keyboard shortcuts broken right now?

### System Information

Manjaro 21.2.3
Xfce4 (xorg)

**Comment by borgmanJeremy** [comment]
See the pinned issue #2365

**Comment by Giraffaman** [comment]
@borgmanJeremy ah sorry, somehow managed to miss that pinned issue. The only thing to note is that, when launching with -p, pressing enter to save the selected screenshot does not seem to work as implied in the linked issue. I have to explicitly click the accept button. Doesn't really matter to me as I'll just start flameshot gui and use ctrl+c/s - just thought I'd mention it.

Thank you!
