### ISSUE TITLE
flameshot gui not working as expected

### ISSUE THREAD

**Issue by JasmineCA** [flameshot-org/flameshot#2433]
### Flameshot Version

```
Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
linux: 5.13.0-28-generic
org.kde.Platform: 5.15
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

KDE Neon 5.24 

### Description

Since the last update I am unable to launch the screenshot tool from command line or from a shortcut with "flameshot gui" defined as the command triggered. 

I've tried to reset my shortcuts following this issue [2391](https://github.com/flameshot-org/flameshot/issues/2391) but I didn't work.

I don't know where logs could be written for this kind of issue.  

`journalctl -f` when I'm using my shortcut for "flameshot gui"
```
févr. 16 19:11:40 jas-aspirex3990 systemd[1245]: Started flameshot.
févr. 16 19:11:40 jas-aspirex3990 systemd[1245]: app-flameshot-e347bbd7bc4e4456835089473f21f160.scope: Succeeded.
```

### Steps to reproduce

1. Run `flameshot gui` from terminal or from shortcut
2. Waiting for the tool to show up
3. Nothing is displayed

### Screenshots or screen recordings

No screen 

### System Information

OS: KDE Neon 5.24 (based on (K)Ubuntu) 
Monitor: 1920x1080
Desktop Environment: KDE Plasma with Xorg

**Comment by mmahmoudian** [comment]
@JasmineCA what happens when you run `flameshot` in terminal? Also what happens when you run `flameshot config`?

**Comment by JasmineCA** [comment]
Sorry for the delay. If I run either `flameshot` or `flameshot config` nothing appears on the screen. `flameshot` opens a new instance, that's the expected behaviour I think.

More info: I configured flameshot to open at startup. So when I run `flameshot` from the terminal, I have two icons on my system tray. If I close all the instances of flameshot, then run `flameshot` and `flameshot gui`, I can take a screen. But still not working with the shortcut. Of course I can still take a screenshot when I click the icon on my system tray

**Comment by JasmineCA** [comment]
While looking around, it turns out that I had the flatpak version and the apt version at the same time. Both starting at login, but only the flatpak one was showing up. I don't know how this mess happened. I've deleted the flatpak version, rebooted and now everything works as expected. 

Sorry for that, your app is amazing!
