### ISSUE TITLE
Pixelation as blur can be reversed, time to use another blur / redaction algorithm?

### ISSUE THREAD

**Issue by R8s6** [flameshot-org/flameshot#2439]
### Feature Description

I came across [a blog](https://bishopfox.com/blog/unredacter-tool-never-pixelation) claiming pixelation can now be "hacked" or reversed to reveal the original english text and numbers.

![](https://github.com/BishopFox/unredacter/raw/main/img/wow_such_secrets.gif)

The code is available on github too:
https://github.com/bishopfox/unredacter

Nothing too urgent, but perhaps the current blur algorithms can be changed to something else?

**Comment by borgmanJeremy** [comment]
I saw that too. You can simply draw a black box if you need more security. You can also increase the kernel size in flameshot to make more letters to into a single block.

**Comment by R8s6** [comment]
black blocks will do, thanks!

**Comment by mmahmoudian** [comment]
@R8s6 if you read their explanation you'll get to know that they are very much relying on the information they get from adjacent pixels' contrast and formation. Therefore one easy way is ro increase the pixel size of the pixelisation tool (scroll) to have the pixels larger than your line height. Also this way when you use normal fonts, one pixel will cover more than one character and therefore much harder, if not impossible, to guess the text.

@borgmanJeremy there is an algorithmically easy fix, although I don't know how the pixelation is implemented. If the pixels are shuffled around randomly, then this can make the guessing also very hard as massive noise is induced
