### ISSUE TITLE
Feature: Mosaic

### ISSUE THREAD

**Issue by gdude2002** [flameshot-org/flameshot#244]
Flameshot's Blur isn't very good, as pointed out in #201 and #121.

![image](https://user-images.githubusercontent.com/204153/40972644-47bb9358-68b9-11e8-9927-711d254199d1.png)

As an alternative, I would suggest a mosaic option instead.

![image](https://user-images.githubusercontent.com/204153/40972801-d0e3125a-68b9-11e8-91b5-da9529e070ea.png)

Even a pixel size of 4 is enough!

**Comment by wirew0rm** [comment]
While it is not easily human readable, I'm not convinced it's impossible to recover the original text, especially if you can make some assumption about the text and font and know the algorithm (see [1]).
In the example, even with the bare eye it is possible to make out word boundaries and character heights, which might be enough to guess the content.
The required pixel size is also obviously depending on the font size, so it would have to be configurable or auto detected.

I think the blur tool should display a warning against using it on sensitive information and to use the box tool instead.

A better implementation with pixelation/mosaic or a combination of them would be nice nevertheless.
Maybe there even is a way to make a secure blurring algorithm. Something like detecting text and replacing it with bogus text before blurring. That's the way I would do it manually if I wanted to be secure and maintain the overall looks.

[1] https://dheera.net/projects/blur

**Comment by gdude2002** [comment]
You make a very interesting point. I looked over that link and I do agree with you - a good solution to the problem of anonymizing an image is therefore to warn about using blur/mosaic and recommend box instead.

I do still think that mosaic is a nice option to have, though.

**Comment by spirituallyinsane** [comment]
Mosaic is nice for maintaining context and anonymizing without obliterating the fact that there *was* information there before.  Pixelation and blurring can already be undone to some extent by AI methods, so you're also right that a box is the only true redaction.  Perhaps a random or "pseudotext" mosaic that just samples the colors in the space would do the job.

**Comment by borgmanJeremy** [comment]
This is merged to master as the new blur tool.
