### ISSUE TITLE
bug/question: fedora, gnome, wayland: screenshot is not shared with the requesting application

### ISSUE THREAD

**Issue by AdamJel** [flameshot-org/flameshot#2441]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.9-200.fc35.x86_64
fedora: 35

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux: 5.16.9-200.fc35.x86_64 fedora: 35

### Description

Hello, I setup the custom keyboard shortcut "printscreen" key => "flameshot gui" command. It successfully triggers the flameshot, but the screenshot is at first taken by the native screenshot application and then it prompts the user - me, if "Share the screenshot with the requesting application?" If I click "Share", then the flameshot takes over and starts taking the screenshot.

Is there a way to turn off this share-check and start flameshot right away?

### Steps to reproduce

1. run `flameshot gui`

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/33990009/154670087-ea220fb8-a8af-4151-bee6-802225788cfd.png)

### System Information

gnome: 41.3
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.9-200.fc35.x86_64
fedora: 35
windowing system: Wayland

**Comment by jrs-a** [comment]
I had this issue yesterday. Today I changed my nvidia graphics driver from open-source to proprietary then restarted, and then its gone.

**Comment by mmahmoudian** [comment]
@jrs-a it has nothing to do with Nvidia, itis Gnome. Read #2186 and https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
