### ISSUE TITLE
Consider migrating to another project platform

### ISSUE THREAD

**Issue by elypter** [flameshot-org/flameshot#245]
If you haven't heard already Microsoft has bought Github yesterday. This feels very much like a tactical aquisition to combat free software. They are also known to let projects they bought from competitors rot or to actively make them bad. If you want to migrate to gitlab then it is quite easy. https://www.youtube.com/watch?v=VYOXuOg9tQI however i would not trust Microsoft to keep the required API accessible forever if they see users migrating.

**Comment by julian-alarcon** [comment]
Added some useful links:
http://www.itprotoday.com/open-source/why-open-source-software-moving-gitlab-after-microsoft-github-deal
https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/
https://dev.to/maxart2501/what-i-think-is-bad-about-microsoft-acquiring-github-gme
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/
https://blog.github.com/2018-06-04-github-microsoft/

**Comment by borgmanJeremy** [comment]
We will be staying on github at this time.
