### ISSUE TITLE
Blank desktop bug when using CLI on OSX Catalina

### ISSUE THREAD

**Issue by iforwms** [flameshot-org/flameshot#2451]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

OSX Catalina 10.15.7 (19H1615)

### Description

Opening flameshot via a shortcut works correctly, but when I try and use `flameshot gui` I get the blank desktop issue.

### Steps to reproduce

1. Symlink flameshot bin `sudo ln -s /Applications/flameshot.app/Contents/MacOS/flameshot /usr/local/bin/flameshot`
2. Run `flameshot gui` (flameshot is already running with a tray icon)
3. Flameshot opens but only with a blank desktop (running `flameshot screen` generates a screenshot of an empty desktop)

### System Information

MacBook Pro 13", no external monitors.

**Comment by mmahmoudian** [comment]
I have a hunch that you have two Flameshots on your computer, one has proper permissions and you open it with keyboard shortcut, and one which doesn't have the permissions and you run it with CLI. Try checking the versions.

Another thing to try is to see if the issue happens when you click on the tray icon.

**Comment by iforwms** [comment]
I can't seem to find a duplicate version. 

I can confirm that using the shortcut key as well as pressing "Take Screenshot" from the tray icon results in successful screen capture, it's only when I call the flameshot executable from the command line that I get the blank desktop issue. Whether I call it directly from inside the `flameshot.app` MacOS direcory or using the symlink.

![image](https://user-images.githubusercontent.com/10304616/155275243-80085d6e-fe8a-4c22-9542-c358e54ab69d.png)

![image](https://user-images.githubusercontent.com/10304616/155275272-c6086bc9-123b-45fa-acc4-cd332d535b18.png)

![image](https://user-images.githubusercontent.com/10304616/155275467-ee8926de-24d3-4e61-bb71-d0b04f53afcc.png)

![image](https://user-images.githubusercontent.com/10304616/155275524-25cc8091-2e4d-42d4-96df-b65f22984850.png)

![image](https://user-images.githubusercontent.com/10304616/155276513-d753e4b0-27e6-4a54-8897-2b79f7120cac.png)

![image](https://user-images.githubusercontent.com/10304616/155276623-227ab7e8-f2e3-42bd-8a13-0318a31d93cc.png)

![image](https://user-images.githubusercontent.com/10304616/155276766-bf10573e-286b-49b7-8ded-a7e80f5e0ddf.png)

**Comment by mmahmoudian** [comment]
I'm not 100% sure about this, but as I don't have access to macOS at the moment to test this, but according to [this SO answer](https://stackoverflow.com/a/1308947/1613005) you should be able to do the following in macOS:

```sh
open ./AppName.app --args -AppCommandLineArg
```

[Another answer](https://stackoverflow.com/a/39541927/1613005) have said that the `-a` argument to `open` will tell it to look into the `/Applications/`, so you don't need to include the `.app` in the name and you can use:

```sh
open -a APP_NAME --args ARGS
```

which means for Flameshot you should be able to use

```sh
open -a flameshot --args gui
```

Give this a try and let me know if it works. I have a hypothesis that Apple's permission system has the `/Applications/flameshot.app/` on the record but ignores subfolders.

**Comment by iforwms** [comment]
Perhaps this could be added to the FAQ somewhere, in case someone else runs into the same issue.

**Comment by mmahmoudian** [comment]
@iforwms Thanks for the update and providing the final solution. I wonder if you would need the `-n` in `open` if you do `pkill flameshot` before running the `open`.

@borgmanJeremy This is bizarre and it might be an issue with Apple's permission system, but I wonder what do you think about this?

**Comment by iforwms** [comment]
If flameshot is already running in the tray, then `pkill flameshot && open -a flameshot --args gui` seems to work. But re-running the same command doesn't seem to do anything, the terminal loses focus and that's it, tried with `screen` as well and no screenshot was saved. 

Re-opening flameshot so it's running in the tray you can once again run the `pkill...` command. 

Adding the `-n` option has worked every time.

**Comment by mmahmoudian** [comment]
> If flameshot is already running in the tray, then `pkill flameshot && open -a flameshot --args gui` seems to work. But re-running the same command doesn't seem to do anything

That is because you are using `&&` which will only run the right side if the left side is successful and when you don't have any Flameshot process, the pkill will of course fail and the right side will not run. You can replace the `&&` with `;` to get it working regardless of if pkill fails or not :) But this is a different story. I believe based on our discussion that macOS gives permission to `/Applications/flameshot.app` and not `/Applications/flameshot.app/*`. Of course one alternative would be that you also manually give permission to `Applications/flameshot.app/Contents/MacOS/flameshot`. This way your issue should be in theory resolved even without the `open`.

**Comment by iforwms** [comment]
Of course! Too late in the day here, brain not working properly!
