### ISSUE TITLE
Multiply copies of image in the clipboard if clipboard is not empty

### ISSUE THREAD

**Issue by TuserYT** [flameshot-org/flameshot#2453]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
linux: 5.13.0-30-generic
ubuntu: 20.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 20.04.3 LTS

### Description

When the clipboard is not empty and then the selected image copying in the clipboard using the Copy selection to clipboard button then many copies of this image are replaced previously in the clipboard. That is, the same image is constantly pasted to the clipboard instead of only one image being pasted.
this can be seen if using any clipboard manager. For example, GPaste.
Please see attached files.

If the clipboard is empty then all is working ok.

### Steps to reproduce

1. Run flameshot gui
2. Copy anything into the clipboard
2. Select a region on the monitor
3. Open any clipboard manager(for example, GPaste)
4. Click the Copy selection to clipboard button
5. Pay attention to the clipboard manager

Actual result: more than one copy of image is pasted in the clipboard

### Screenshots or screen recordings

![Flameshot-clipboard-issue](https://user-images.githubusercontent.com/24720092/155334703-0cbf6a01-4118-4ae5-b2bd-3e05df06d012.gif)

### System Information

```
e.gabets@CMDB-81141:~$ flameshot --version
Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
e.gabets@CMDB-81141:~$ inxi --width 80 --system --graphics
System:
  Host: CMDB-81141 Kernel: 5.13.0-30-generic x86_64 bits: 64 
  Desktop: Gnome 3.36.9 Distro: Ubuntu 20.04.4 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: i915 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 21.2.6 
e.gabets@CMDB-81141:~$ xrandr --listactivemonitors
Monitors: 2
 0: +*HDMI-3 1920/521x1080/293+0+0  HDMI-3
 1: +DP-2 1920/521x1080/293+1920+0  DP-2
e.gabets@CMDB-81141:~$ lshw -class display
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: UHD Graphics 630 (Desktop)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:136 memory:a0000000-a0ffffff memory:90000000-9fffffff ioport:3000(size=64) memory:c0000-dffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
e.gabets@CMDB-81141:~$ uname -a
Linux CMDB-81141 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
e.gabets@CMDB-81141:~$ 
```

![image](https://user-images.githubusercontent.com/24720092/155335673-7999d6cd-f4c8-4158-be21-da7041053042.png)

**Comment by mmahmoudian** [comment]
In a clean VM I could not replicate this issue. Perhaps it is something wrong with your system.

![image](https://user-images.githubusercontent.com/390889/155722654-633f9bd5-cb86-433a-a49b-d9b2fc806194.png)

**Disclaimer: ** You didn't mention how you have installed Flameshot, so I downloaded the .deb file, installed it with `dpkg -i` and ran it.

**Comment by mmahmoudian** [comment]
@TuserYT Would you please try to replicate this in a clean VM and report back the results?
