### ISSUE TITLE
Screenshot aborted when changing tool from Text

### ISSUE THREAD

**Issue by danodan** [flameshot-org/flameshot#2454]
### Flameshot Version

Flameshot v11.0.0 on Manjaro KDE 5.15.19

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro KDE 5.15.19 KDE Plasma

### Description

You have drawn an arrow on your screen, you chose the text tool and write some text, you switch back on the arrow tool..bam screenshot aborted

This is happening when you have the tool settings panel hidden
If you press the text tool button before switching back to another tool (arrow or rectangle) this will not happen

### Steps to reproduce

1 drag the mouse to select an area of the screen
2 make sure the panel settings is hidden
3 draw an arrow
4 select the text tool and put some text
5 switch back to the arrow tool or a rectangle
6 screenshot aborted

### System Information

Linux Manjaro KDE Plasma 5.15.19

**Comment by borgmanJeremy** [comment]
It's also been fixed on the main branch.

**Comment by dandv** [comment]
I still see this bug when clicking the rectangle tool - Flameshot aborts and it loses all my work :-/

At least make it confirm, if the user spent more than a minute editing the screenshot.

![Flameshot screenshot aborted when clicking the rectangle tool](https://user-images.githubusercontent.com/33569/222433718-d7f7aca4-a164-4213-bc27-4cc78c13dfcb.gif)

**Comment by dandv** [comment]
Same bug when clicking the :blue_square: tool

**Comment by mmahmoudian** [comment]
@dandv I cannot reproduce this. Please provide your setup information (i.e flameshot version, how you have installed it, OS, window manager/DE, display server, ...)
