### ISSUE TITLE
[Mac - M1 Pro] Flameshot 11 will open in a new fullscreen desktop

### ISSUE THREAD

**Issue by hb0nes** [flameshot-org/flameshot#2456]
### Flameshot Version

11

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Monterey 

### Description

When I take a screenshot, the desktop will switch to an empty one and there won't be anything to screenshot.
Flameshot 10 does not have this behaviour, so I switched back to 10.

### Steps to reproduce

Right click tray icon
Take screenshot

### System Information

-

**Comment by mmahmoudian** [comment]
Have you read and followed instructions in these places:
- https://flameshot.org/docs/installation/installation-osx/
- https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by mmahmoudian** [comment]
Have you read and followed instructions in these places:
- https://flameshot.org/docs/installation/installation-osx/
- https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by mmahmoudian** [comment]
Have you read and followed instructions in these places:
- https://flameshot.org/docs/installation/installation-osx/
- https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by hb0nes** [comment]
I guess in my case, Flameshot 11 didn't show up and I would have to add it manually. I will try this later, but I believe I can close this issue.

Thank you.
