### ISSUE TITLE
Falling to compile from source on Windows 10

### ISSUE THREAD

**Issue by Walleton2** [flameshot-org/flameshot#2457]
Hi, Sorry I am new to the c++, qt, and cmake stuff etc.

I'm trying to compile flameshot from source on W10. However it errored out while nearly the end of building phase.

```
[ 97%] Building CXX object src/CMakeFiles/flameshot.dir/tools/toolfactory.cpp.obj
[ 97%] Building RC object src/CMakeFiles/flameshot.dir/__/data/flameshot.rc.obj
D:\qt\Tools\mingw730_64\bin\windres.exe: C:\\Users\\wific\\Videos\\flameshot\\data\\flameshot.rc:34: syntax error
mingw32-make.exe[2]: *** [src\CMakeFiles\flameshot.dir\build.make:1916: src/CMakeFiles/flameshot.dir/__/data/flameshot.rc.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:658: src/CMakeFiles/flameshot.dir/all] Error 2
mingw32-make.exe: *** [Makefile:155: all] Error 2
03:20:00: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project flameshot (kit: Desktop Qt 5.12.12 MinGW 64-bit)
When executing step "Build"
```
I'm not sure what I'm doing wrong here. This is what I have installed.

- Qt 5.12.12 ( installed from `qt-opensource-windows-x86-5.12.12.exe` )
- MSVC 2017 64-bit ( installed from `qt-opensource-windows-x86-5.12.12.exe` )
- MinGW 7.3.0 64-bit w/ toolchain ( installed from `qt-opensource-windows-x86-5.12.12.exe` )
- Cmake version on 3.23.0-rc2

Any help would be very much appreciated, I've been trying to compile it for hours already.

**Comment by borgmanJeremy** [comment]
You need to use MSVC compiler, not MinGW
