### ISSUE TITLE
Let's save to clipboard and disk ss on pin

### ISSUE THREAD

**Issue by Shirobachi** [flameshot-org/flameshot#2467]
### Feature Description

I think that would be great to make possible (optional) following behavior, if you "pin" ss then automatic save it in clipboard or/and disk drive. Like it's with saving in clipboard, you can config it to save in disk when saving in clipboard:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/16509749/156431956-5bcabb56-6e81-4485-a135-ebff022aedfa.png">

In my case it's often that I pin something, and later I make a select screenshot of the pin to share it on the web :D  

BTW. I love flameshot, it's amazing <3 Thanks for this software

**Comment by mmahmoudian** [comment]
This is already possible. You should just start Flameshot with this command and then press Enter or click on the checkmark when you selected the area:

```sh
flameshot gui --clipboard --pin --path ~/Pictures/
```

Here I assumed you are Linux user. If you are Windows user just change the `~/Pictures/` to something Windows understands.

To find out more, read this:

https://flameshot.org/docs/advanced/commandline-options/

**Comment by Shirobachi** [comment]
Not exactly what I wanted, I mean if it's not possible it can work for me. But I am normally use shortcut to run `flameshot gui` then if I click
- **enter**, it will save ss in clipboard and in ~/downloads
- **`** , it will pin ss (I would like to save it also in ~/Downloads

Let me know what do you think

**Comment by mmahmoudian** [comment]
I think this is a niche use case and this can be easily handled by binding different keyboard shortcuts to different Flameshot commands. For instance you can have <kbd>Printscreen</kbd> for `flameshot gui` and  <kbd><kbd>Shift</kbd><kbd>Printscreen</kbd></kbd> for `flameshot gui --pin --path ~/Downloads`. I myself am using [a dmenu wrapper](https://codeberg.org/mehrad/dmenu_shot) which contains all my custom-made Flameshot  functions and it is bound to a keyboard shortcut.

But perhaps it is a good idea to hear other dev's opinion: @borgmanJeremy @veracioux @ZetaoYang @hosiet

**Comment by Shirobachi** [comment]
Fully understand if it's niche use case, I just thought it may be useful. Thanks for sharing suggestion of key binding, I'll use them <3
