### ISSUE TITLE
Flameshot taking screenshots don’t work - arch linux

### ISSUE THREAD

**Issue by antonhtmnn** [flameshot-org/flameshot#2470]
### Flameshot Version

Flameshot v11.0.0 (a6144df3)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

OS: Arch Linux x86_64

### Description

If I type "_flameshot_" into the terminal I get the following warning:
"_Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway._"
and the tray icon shows up in my top panel. I can open the configuration by typing "_flameshot config_" into the terminal or by right klick on the tray icon > "configuration".
But typing "_flameshot gui_" or by right klick on the tray icon > "take screenshot" function does not work for me (nothing happens except the same warning).
Thank's for the help! :D

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/77544336/156852096-edad950f-ba8d-4310-baa6-329a24cee3be.png)

### System Information

OS: Arch Linux x86_64
Kernel: 5.16.12-arch1-1
DE: GNOME 41.4
Wayland

**Comment by antonhtmnn** [comment]
Flameshot only works for me without problems when choosing "GNOME on Xorg" at startup.

**Comment by se7en-x230** [comment]
Arch dwm 
since today I can't start flameshot anymore

Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)

**Comment by borgmanJeremy** [comment]
Make sure you install: 
xdg-desktop-portal
xdg-desktop-portal-gnome
