### ISSUE TITLE
Scale problem on 4k Wayland 

### ISSUE THREAD

**Issue by Corvology** [flameshot-org/flameshot#2471]
I was using flameshot on X protocol on 4k display when it was clear and fix.
But now I changed to wayland and when I try to take screenshot it just auto-zoom top-left corner of my display on 1280x720 scale.

**Comment by mmahmoudian** [comment]
Please fill a proper bug report and provide all requested information:

https://github.com/flameshot-org/flameshot/issues/new?template=bug-report.yaml
