### ISSUE TITLE
Unable to capture area with flameshot gui shortcut

### ISSUE THREAD

**Issue by fulljackz** [flameshot-org/flameshot#2474]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04

### Description

Hi folks, since my upgrade from Ubuntu 21.10 to Ubuntu 22.04 I can't capture areas anymore with flameshot.

I have a shortcut with Ctrl+Alt+S -> `flameshot gui`. 
When pushing theses keys, it makes a a screenshot of my full dual screen, then open a window with a Cancel, Option and Share buttons.

- If I click Cancel, the window closes and flameshot prompt Flameshot Error, Screenshot aborted.
- If I click Options, it opens a window for choosing "grabe the whole screen, current window etc"
- I I click Share, it opens a window with the drag option for selecting area.

### Steps to reproduce

Don't really known, upgrade from 21.10 to 22.04, using wayland.

### System Information

1 - Ubuntu 22.04
2 - 
![image](https://user-images.githubusercontent.com/12140932/157210084-046ef997-22f7-4655-ab37-37cf8de6dfd9.png)
3 - Gnome 42 beta, Wayland

**Comment by mmahmoudian** [comment]
The window with the share button is Gnome 41 and they started doing this since Gnome 41 Wayland.

This us well explained here:

https://github.com/flameshot-org/flameshot/issues/1910#issuecomment-1023925922

If you are after fixing the issue, my personal suggestion is moving away from Gnome
