### ISSUE TITLE
flameshot gui doesn's start 

### ISSUE THREAD

**Issue by tassosblackg** [flameshot-org/flameshot#2478]
### Flameshot Version
`flameshot --version`

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Official Repository (community) (Manjaro Add software) 

### Operating System type and version

Manjaro Linux (Arch)
Release:	21.2.4
Codename:	Qonos

### Description

Every time I try to start the flameshot app, it doesn't open. The only way to use flameshot is to hit `flameshot gui` through terminal.

### Steps to reproduce

Click on flameshot  icon, the app doesn't respond.

### System Information

1. Manjaro Linux 21.2.4 Qonos
2. Dual monitor setup
3. GNOME 41.4

**Comment by mmahmoudian** [comment]
What do you mean that "it doesn't open"? Doesn't clicking on the tray icon work?

Additionally you either are reporting the version wrong or the installation method wrong. Please correct that.

**Comment by tassosblackg** [comment]
I mean when I try to open the app it doesn't show any window (GUI) as before. In order to select window, frame etc.

**Comment by mmahmoudian** [comment]
> ## Steps to reproduce
> Click on flameshot icon, the app doesn't respond.

Do you mean that you click on the tray icon and nothing happens or you click on the icon in the application menu and nothing happens?

-------

As a side note, you forgot to correct the information you provided. Either you reported the wrong version or you reported the wrong installation method. If you install from AUR you should get something like (notice the extra text at the end of the version):

```console
❯  flameshot --version
Flameshot v11.0.0 (a6144df3)
Compiled with Qt 5.15.2
```

Considering your edit to the original post, I assume you have selected the wrong installation method.

**Comment by tassosblackg** [comment]
Yes you're right it's the Official Repositories(community) from Add Software using Manjaro.

**Comment by mmahmoudian** [comment]
> ## Steps to reproduce
> Click on flameshot icon, the app doesn't respond.

Do you mean that you click on the tray icon and nothing happens or you click on the icon in the application menu and nothing happens?

**Comment by sergiuprt** [comment]
Hey guys. I have the same problem, but it seems that's because the app installed as a flatpack, even though I've installed it via the Pop_Shop and I've chosen deb.
So, how do I add the command to run it? I'm searching the web but no answers so far.

**Comment by mmahmoudian** [comment]
@sergiuprt I believe your issue is unrelated, so I'll hide it and also hide my response (this comment).

For information on how to use flatpak, read https://flameshot.org/docs/installation/installation-linux/#flatpak
