### ISSUE TITLE
Shortcut to take a screenshot does not work in visual studio code

### ISSUE THREAD

**Issue by dbonattoj** [flameshot-org/flameshot#2482]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

Flameshot is running and works perfectly when I click on the "Print screen" key on the keyboard.

The only place where it does not work is when I’m writing code in Visual Studio Code. The software does not start.

If I click on the windows icons bar while the Visual Studio Code window is still there, I can again use the "Print screen" key and everything works.

I suspect Visual Studio Code capture the "Print Screen" key and does not forward it to flameshot, but I find this suspicious.

### Steps to reproduce

1. Run flameshot
2. Open Visual Studio Code
3. Try to take a screenshot with the "Print Screen" key
4. Note that it does not work
5. Open an issue

6. Click on the windows menu bar
7. Try to take a screenshot with the "Print Screen" key
8. Note that it works

### Screenshots or screen recordings

https://user-images.githubusercontent.com/28501597/157780444-3c3afac6-8ea3-47ee-91ed-9bf0a85a7dc9.mp4

### System Information

Windows 10

**Comment by mmahmoudian** [comment]
I don't have Windows and cannot attempt to reproduce this, but for the sake of reproducibility, please edit your post and add complete version of your Windows and VSCode.

**Comment by veracioux** [comment]
@dbonattoj This is clearly caused by what @borgmanJeremy said. It can't be solved on flameshot's side unfortunately.

**Comment by Ihor-Bilyk** [comment]
For anyone who struggles with this, take a look at this StackOverflow post, this helped me
https://stackoverflow.com/questions/35210599/greenshot-does-not-work-in-visual-studio

**Comment by MarcoGrillo-dev** [comment]
> For anyone who struggles with this, take a look at this StackOverflow post, this helped me https://stackoverflow.com/questions/35210599/greenshot-does-not-work-in-visual-studio

For me this is the solution :)
