### ISSUE TITLE
Pin image causes high cpu

### ISSUE THREAD

**Issue by mohad12211** [flameshot-org/flameshot#2485]
### Flameshot Version

Flameshot v11.0.0 (a6144df3)

### Installation Type

User repository (AUR)

### Operating System type and version

Archlinux

### Description

Pinning an image causes relatively high cpu, I don't think this is normal. cpu drops after closing the pinned image.
on left is `qps` total cpu percentage, and right is `htop`'s readings. 

### Steps to reproduce

1. run `flameshot gui`
2. take screenshot
3. pin it

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/51754973/158059293-44f40601-1779-46c9-bdcb-b229ccbd3003.png)

### System Information

Archlinux
1 monitor 1080p
dwm window manager, no desktop environment
Xorg

**Comment by borgmanJeremy** [comment]
Wow thanks for reporting this.

**Comment by mmahmoudian** [comment]
yeap, I can reproduce this on Manjaro too.

**Comment by borgmanJeremy** [comment]
I bisected the code base and it was introduced with the gesture support at 412a3f

**Comment by borgmanJeremy** [comment]
fixed by #2502

**Comment by mohad12211** [comment]
can confirm that #2502 fixes the issue.
