### ISSUE TITLE
Desktop partially freezes when saving screenshot to file system

### ISSUE THREAD

**Issue by awerlang** [flameshot-org/flameshot#2491]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.10-1-default
opensuse-tumbleweed: 20220223

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

openSUSE Tumbleweed

### Description

Saving a screenshot to file system results in a freeze of a few seconds (~30s).

This doesn't happen when (any of them):

- ~Setting "Show desktop notifications" to off~ (this setting is indifferent)
- Setting "Copy file path after save" to off
- Copying screenshot to clipboard

### Steps to reproduce

1. Have flameshot as a tray icon
2. Activate flameshot with global shortcut
3. Make a selection
4. Hit tool "Save screenshot to a file"

Observed behavior:

- Desktop freezes
- After a couple seconds an outline of a notification is shown 
- Some windows won't update (i.e. videos)
- Taskbar unresponsive
- Laucher unresponsive
- Some windows still handle input events
- After ~30s two notifications are shown: path copied to clipboard, image saved
- Desktop unfreezes

### System Information

KDE Plasma on Xorg

**Comment by mmahmoudian** [comment]
Might be connected or even duplicate of #2446

**Comment by awerlang** [comment]
> Might be connected or even duplicate of #2446

Hi! Thanks for taking a look! I don't think it's related to that issue, since I can't reproduce that in my regular environment.

It's definitely related to https://github.com/flameshot-org/flameshot/pull/2053 and https://github.com/flameshot-org/flameshot/blob/v11.0.0/src/utils/screenshotsaver.cpp#L51 IOW a race condition, as the workarounds seem to indicate.

**Comment by xRasea** [comment]
#2398 this seems to be the same issue.

**Comment by awerlang** [comment]
Closing this issue in favor of #2398
