### ISSUE TITLE
Copy screenshot to clipboard failed unless an instance already running at background

### ISSUE THREAD

**Issue by qvoid** [flameshot-org/flameshot#2496]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3

### Installation Type

Snap from Snapcraft

### Operating System type and version

Ubuntu 20.04.4 LTS

### Description

If there is no Flameshot already running, calling flameshot by command `flameshot gui` won't save screenshot to clipboard.
So I add Flameshot to start-up, and always keep flameshot minimized at top bar tray icon area.
Configuration is kept as default : 
![image](https://user-images.githubusercontent.com/9588447/159230103-b0c78dbb-c3d0-412a-ab42-8acdb663faa7.png)
![image](https://user-images.githubusercontent.com/9588447/159230214-0c4c54cd-0d50-4c68-86bd-3390d8f24d71.png)

### Steps to reproduce

1. make no Flameshot already running
2. run `flameshot gui`
3. capture any area
4. "Copy selection to clipboard"
5. Open libreoffce or other software, press `Ctrl + V` to do paste
6. No screenshot is pasted

### System Information

```
➜  ~ loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11
➜  ~ xrandr --listactivemonitors
Monitors: 1
 0: +*DP-1 2560/553x1440/311+0+0  DP-1
➜  ~ inxi --width 80 --system --graphics
System:
  Host: johnson-HP-ProDesk-480-G7-PCI-Microtower-PC 
  Kernel: 5.13.0-35-generic x86_64 bits: 64 Desktop: Gnome 3.36.9 
  Distro: Ubuntu 20.04.4 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: i915 resolution: 2560x1440~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CML GT2) v: 4.6 Mesa 21.2.6 
➜  ~ flameshot --version
Flameshot v11.0.0 ()
Compiled with Qt 5.15.3

```

**Comment by hitchhooker** [comment]
struggling with same issue,  flameshot gui command stop working for copying pictures and URL if uploaded to imgur. 
flameshot works fine tho but requires more manual stuff

changing tool size to make arrows and else is also broken and wont change to other sizes

**Comment by Tcll** [comment]
I would like to re-assert my request that was rudely downplayed in this issue:
https://github.com/flameshot-org/flameshot/issues/635
(I would link/quote directly but I have to enable malware on here for menus to work)

> could you make it possible to specify an option that keeps flameshot running after calling `flameshot gui`

this is not already possible as you have to manually run `flameshot` at startup
`flameshot gui` **DOES NOT** have a configurable checkbox option to enable or disable auto-starting a flameshot daemon as requested.

again, the **workaround** is manually configuring `flameshot` at startup
there is **NO** option to configure an auto-start process when `flameshot gui` is run

this was preventing images from being copied to the clipboard as the previous issue was about.
(or rather images were deleted on copy)

**Comment by borgmanJeremy** [comment]
Yes currently the fix is to start the daemon with a "flameshot" invocation. Or set it to automatically start on login.

**Comment by luikluikluik** [comment]
same with me :(

**Comment by Globabee** [comment]
i have same problem

**Comment by PetrusZ** [comment]
I think I have same issue, when I take a screenshot  by `flameshot gui`, it can copy to clipboard, but when I use `flameshot gui -p ~/Screenshot`, the copy to clipboard function failed to work.

**Comment by mmahmoudian** [comment]
@PetrusZ that is intended behavior. Please read the following link as you have clearly missed the release notes for v11.0.0:


https://flameshot.org/docs/advanced/commandline-options/#final-actions


I'm going to hide your post as it is off-topic.

**Comment by borgmanJeremy** [comment]
@mmahmoudian What are your thoughts here? We specifically changed the internals so d-bus is not required and you can run the CLI in a fully standalone mode. However, clipboard does not work without the daemon running. This is inherent to linux, there is nothing we can do about that. 

We get yelled at for starting a daemon in the background and simultaneously expected to always have the clipboard work.

My suggestion is to leave the behavior as is and maybe try to explain this more in the docs? If a user wants to use the clipboard and no daemon they can always do something like: 

```
flameshot gui --raw | xclip -sel clip -t image/png
```

**Comment by mmahmoudian** [comment]
@borgmanJeremy I also believe that the curdent behavior is what it should be and should not be changed. People yell because they don't think about the implications of their request and the implementation challenges and the limitations it can bring.

That said, as far as I understand, the reported problem in this issue is that the daemon is not getting launched automatically for the one-off usage, which as far as I can remember from our discussions before, that is the expected behavior. The daemon should keep running as long as the clipboard is kept or as long as a pinned window exists.

**Comment by borgmanJeremy** [comment]
@mmahmoudian I understand how we can keep the daemon running for a pinned image, but not sure how we could do that for the clipboard?

**Comment by mmahmoudian** [comment]
> @mmahmoudian I understand how we can keep the daemon running for a pinned image, but not sure how we could do that for the clipboard?

At least for Flameshot v11.0.0 (1b97fb51) when running `pkill flameshot && sleep 1s && flameshot gui --clipboard` it correctly opens the daemon, and keeps it running, but it will not close the daemon when the clipboard is changed/emptied. Is this understanding correct? If so, as you said, the only way forward is documentation. I myself am also puzzled why the daemon needs to be running to keep the screenshot in the clipboard. Why can't we pass the screenshot to system clipboard so that there is no need for FLameshot daemon to be running?

**Comment by demonlibra** [comment]
Have the same problem.
Checked flameshot 12.0 and 12.1
OS LinuxMint 20.3

Resolved by creating bash script and run it by hotkeys

cd <path_to_flameshot>
./flameshot &
./flameshot gui

**Comment by Ariandr** [comment]
Hi @borgmanJeremy 
I don't think this issue needs to be closed. Behavior is inconsistent and it's definitely a bug.

I have this issue too, I'm on 12.1.0 and MacOS 12.4.

I just launch the screenshot capture with the hotkey combination.
When I'm done and want to copy to the clipboard, `CMD+C` sometimes works, sometimes doesn't.

But when I click 'Copy selection to clipboard' button, it always works.

**Comment by mmahmoudian** [comment]
@Ariandr please only post the same issue once. Few seconds ago you posted the same exact text in another thread. Thank you.
