### ISSUE TITLE
Feature request - allow reordering of buttons

### ISSUE THREAD

**Issue by nneul** [flameshot-org/flameshot#2497]
### Feature Description

It would be nice to be able to change the order of the toolbar buttons - to be able to put the most commonly used to the left/start so that they are more "fixed" in position. Right now, the one I'll use the most is copy to clipboard - and it's position is variable depending on size of the selection if the selection isn't wide enough for the button to fit on the bottom.

If you're making the position/order adjustable - you might consider allowing full configurability of placement of each button as well:

i.e. both order and orientation such as "Bottom, Left-to-Right", "Bottom, Center", "Right, Top-to-Bottom" -- or even just "Left, Bottom, Right, Top" as choices - to always have the buttons in particular places instead of moving around -- that might also be sufficient for my use case - I could choose to always put the copy buttons on Left, editing on bottom, save/upload/etc. on right for example.

**Comment by mmahmoudian** [comment]
This is almost duplicate of #2245 especially the second part

**Comment by nneul** [comment]
I agree, in interests of simplicity, I'll close this one and comment about reordering on the other.
