### ISSUE TITLE
Upload to imgur stopped working

### ISSUE THREAD

**Issue by Alt37** [flameshot-org/flameshot#2500]
### Flameshot Version

Flatmeshot V11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Kubuntu 20.04

### Description

Uploading to imgur fails with error
> Error transferring https://api.imgur.com/3/image?title=&description=2022-03-24_12-00 - server replied: nginx 

Yesterday (2022-03-23) my co-worker noticed it, then problem went away. Today it returned.
I also tried Spectacle (v19.12.3 which comes with a distro) and upload works there.

### Steps to reproduce

1) Take a screenshot
2) Click "upload" button
3) Confirm upload

### System Information

OS: Kubuntu 20.04
DE: KDE Plasma
Session: Xorg

**Comment by kamilszewczyk** [comment]
Same for me and I'm having same issues with imgur on other tools. Looks like imgur is over capacity - but for me it's happening for a few days now

**Comment by borgmanJeremy** [comment]
Flameshot shares 1 API key across all installs. This means we often hit the daily upload limit #188

In an ideal world this is fixed by the upload plugin system, but that is a long way off. I'm starting to think we should allow for users to override the default API key before we finish plugins.

**Comment by webmaster85** [comment]
Same for me, happening for a few days, no VPN in use:
![image](https://user-images.githubusercontent.com/29068748/160807611-1a6671c0-c3d5-4ccf-b6ea-79f43e54b0b7.png)

**Comment by borgmanJeremy** [comment]
This will be solved with #2503 It will continue to happen randomly until that is merged.

**Comment by raniesantos** [comment]
what version will #2503 be included in?

**Comment by borgmanJeremy** [comment]
The next one

**Comment by raniesantos** [comment]
@borgmanJeremy 12? 11.0.1? 11.1.0?

**Comment by mmahmoudian** [comment]
@raniesantos  it is a [Schrödinger's cat situation](https://www.youtube.com/watch?v=UjaAxUO6-Uw): you'll never know unless and until you see it yourself. Until then it is all those states at the same time. But most probably 12.0.0

**Comment by mmahmoudian** [comment]
@Cloud-Mak I don't think it is an issue of AppImage vs. deb, but rather the luck. If you are using the default config, you are using our imgur key, meaning that you and everyone else who are using that key are sharing the same quota. in version 12 we have now the possibility to use your own key:

![image](https://user-images.githubusercontent.com/390889/178990045-39c14926-0a55-4462-97eb-5ba18110c5a7.png)

Btw, please consider updating your Flameshot for the latest version to get new features and bug fixes.
