### ISSUE TITLE
Error: Unrecognized setting: 'saveAfterCopyPath'

### ISSUE THREAD

**Issue by zacharytyhacz** [flameshot-org/flameshot#2501]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux: 5.16.13-arch1-1

### Description

I updated flameshot, and now running any flameshot command fails with this error.

### Steps to reproduce

1. run any flameshot command ( `gui`, `screen`, `full`, `launcher, and `config )
2. Error appears in a popup:

flameshot: error: Unrecognized setting: 'saveAfterCopyPath'

### Screenshots or screen recordings

Just an error pop up saying:

```
You must resolve all errors before continuing:

saveAfterCopyPath                   [Remove]

------------------------------------------------------------
[Resolve all] [Cancel] [Details]
```

'Resolve all' does not do anything and details shows the error:

flameshot: error: Unrecognized setting: 'saveAfterCopyPath'

#### Kernel: 5.16.13-arch1-1

<br><br>

This is my `~/.config/flameshot/flameshot.ini`
```ini
[General]
contrastOpacity=188
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=6
savePath=/home/zac/Screenshots
savePathFixed=true
showStartupLaunchMessage=true
startupLaunch=false

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

I cloned the repo and did a search for this term `saveAfterCopyPath` and nothing comes up.

Therefore, I am assuming it could be clipboard related ( maybe `flameshot` needs a variable of which clipboard binary to use? ) 

```sh
local/xclip 0.13-3
    Command line interface to the X11 clipboard
local/xorg-xclipboard 1.1.3-3
    X clipboard manager
```

**Comment by zacharytyhacz** [comment]
I may be wrong, but I think this _could_ be related to #2481

**Comment by borgmanJeremy** [comment]
This is very confusing since you don't have that in your config file. I assume you have tried closing and re-opening flameshot after hitting resolve?

What that error means is it sees a key in the config file literally named "saveAfterCopyPath" which is obviously not there.

**Comment by mmahmoudian** [comment]
@zacharytyhacz 
> I may be wrong, but I think this could be related to #2481

I don't think they are related. What @borgmanJeremy mentioned is interesting indeed. Did you press the Resolve All button before fetching the content of your config?

**Comment by zacharytyhacz** [comment]
Hey guys. apologies for late reply.

@mmahmoudian 
The 'Resolve All' button does not do anything when I click it.

@borgmanJeremy 
Yes, I have tried killing flameshot and then restarting again - still same error.

I even have tried fully uninstalling flameshot through pacman and reinstalling again - still same error.

**Comment by mmahmoudian** [comment]
@zacharytyhacz please try to kill Flameshot, and then rename the Flameshot config folder, and run Flameshot again. (e.g `mv ~/.config/flameshot ~/.config/flameshot.old`)

**Comment by mmahmoudian** [comment]
@zacharytyhacz any updates?

**Comment by mmahmoudian** [comment]
> Is there any other place where flameshot could have a config?

No, that's the only config we have

> Could it be my clipboard program? xclip ?

No. I myself am actually using xclip and don't have this issue.

Please try installing via AUR. It is maintained by us andit should give you the compiled version based of HEAD of this repo.
