### ISSUE TITLE
flameshot fails to start

### ISSUE THREAD

**Issue by mioxyz** [flameshot-org/flameshot#2506]
### Flameshot Version

flameshot-11.0.0-4
latest commit

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), User repository (AUR)

### Operating System type and version

Manjaro Linux x86_64, Kernel Version: 5.13.13-1-MANJARO

### Description

When installed via pacman, flameshot fails to start with the error message:
```
flameshot: symbol lookup error: /usr/lib/libQt5WaylandClient.so.5: undefined symbol: wl_proxy_marshal_flags
```

Installing flameshot from source via the flameshot-git community AUR-package results in a similar error during linking with ld:
```
...
[ 95%] Building CXX object src/CMakeFiles/flameshot.dir/tools/abstractactiontool.cpp.o
[ 96%] Building CXX object src/CMakeFiles/flameshot.dir/tools/abstractpathtool.cpp.o
[ 96%] Building CXX object src/CMakeFiles/flameshot.dir/tools/abstracttwopointtool.cpp.o
[ 97%] Building CXX object src/CMakeFiles/flameshot.dir/tools/capturecontext.cpp.o
[ 97%] Building CXX object src/CMakeFiles/flameshot.dir/tools/toolfactory.cpp.o
[ 98%] Building CXX object src/CMakeFiles/flameshot.dir/main.cpp.o
[ 98%] Building CXX object src/CMakeFiles/flameshot.dir/flameshot_autogen/IJ3KGTTQ5V/qrc_graphics.cpp.o
[100%] Linking CXX executable flameshot
/usr/bin/ld: /usr/lib/libKF5GuiAddons.so.5.91.0: undefined reference to `wl_proxy_marshal_flags'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/flameshot.dir/build.make:2078: src/flameshot] Error 1
make[1]: *** [CMakeFiles/Makefile2:686: src/CMakeFiles/flameshot.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: flameshot-git
```

### Steps to reproduce

For installing flameshot package, run on a fresh manjaro install:
```
pacman -Sy
pacman -Rs manjaro-settings-manager-notifier manjaro-settings-manager
pacman -S cmake base-devel git qt5-base qt5-tools;
pacman -S qt5-svg;
pacman -S flameshot;
flameshot
```
note: I remove `manjaro-settings-manager-notifier` and `manjaro-settings-manager` because they conflict with `qt5-base`

For building from source I used yay:
```
yay flameshot-git
```

### System Information

running X11
OS: Manjaro Linux x86_64
Host: 24413TG ThinkPad W530
Kernel: 5.13.13-1-MANJARO
Uptime: 5 hours, 36 mins
Packages: 1096 (pacman)
Shell: bash 5.1.12
Resolution: 1920x1080, 1920x1080
WM: i3
Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3]
Terminal: alacritty
CPU: Intel i7-3720QM (8) @ 3.600GHz
GPU: NVIDIA Quadro K1000M
GPU: Intel 3rd Gen Core processor Graphics Controller
Memory: 3533MiB / 7772MiB

**Comment by borgmanJeremy** [comment]
This needs to be fixed in arch not flameshot. They likely need to rebuild kf5 against qt
