### ISSUE TITLE
Unable to capture screen on xwayland

### ISSUE THREAD

**Issue by marekvospel** [flameshot-org/flameshot#2507]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

Arch linux 5.16.16-arch1-1

### Description

Recently I have switched from x11 to xwayland. With this transition, flameshot stopped working. (flameshot can't take screenshot, `flameshot config` does open the config ui)
Output of `flameshot gui`
```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
```

I'm using pipewire, and all other screen capturing apps are working (I've installed `xdg-portal-wlr`, and the screen chooser doesn't open)

### Screenshots or screen recordings

https://imgur.com/a/c6lRchS

### System Information

System:
  Host: MarekPC2 Kernel: 5.16.16-arch1-1 arch: x86_64 bits: 64 Desktop: sway
    v: 1.7 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.0
    compositor: sway v: 1.7 driver: X: loaded: amdgpu,modesetting gpu: amdgpu
    resolution: 1: 2560x1440~170Hz 2: 2560x1440~170Hz 3: 1920x1080~144Hz
  OpenGL:
    renderer: AMD DIMGREY_CAVEFISH (DRM 3.44.0 5.16.16-arch1-1 LLVM 13.0.1)
    v: 4.6 Mesa 21.3.7

**Comment by mb720** [comment]
I get the same results when running flameshot on Arch Linux, installed it from community repository. Package name and version are: `flameshot-11.0.0-4-x86_64`

    flameshot: error: Unable to capture screen
    flameshot: error: Unable to capture screen
    qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**Comment by channelbeta** [comment]
Hello all. I remember having a similar problem, and it was solved by installing the package `qt5-wayland`:

```shell
$ pacman -Qs qt5-wayland
local/qt5-wayland 5.15.3+kde+r40-1 (qt qt5)
    Provides APIs for Wayland
```

If you're using flameshot from the community repo, it should have been installed automatically, because flameshot depends on kguiaddons which depends on qt5-wayland:

```shell
$ pacman -Qi kguiaddons
Name            : kguiaddons
Version         : 5.92.0-1
Description     : Addons to QtGui
Architecture    : x86_64
URL             : https://community.kde.org/Frameworks
Licenses        : LGPL
Groups          : kf5
Provides        : None
Depends On      : qt5-x11extras  qt5-wayland <--- here
```

It is worth checking if you have it, anyways. It is working fine for me on Gnome Wayland:

![flameshot_gnome_wayland](https://user-images.githubusercontent.com/88544994/162750615-0c584d9a-1d96-4d68-a66c-62a7416b1c71.png)

Note that the `XDG_SESSION_TYPE=wayland` warning can be ignored, the application worked fine on both tries, and the screenshot above was captured by flameshot.

**Comment by marekvospel** [comment]
I have had both qt5-wayland and qt6-wayland installed. The gui does open, only taking a screenshot seems to be a problem
```
qt5-wayland 5.15.3+kde+r41-1
qt6-wayland 6.2.4-1
```

**Comment by marekvospel** [comment]
Going trough the AUR comments I have found the solution. On wlroots based compositors `grim` is required to capture a screenshot.
https://aur.archlinux.org/packages/flameshot-git#comment-813310

I haven't noticed this in docs.
https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by gutopardini** [comment]
If you're still using GNOME + Wayland and struggling with Flameshot/XWayland issues, take a look at my project:

https://github.com/gutopardini/wayshot

WayShot uses the native GNOME screenshot tool under Wayland and automatically opens a modern annotation editor afterwards (arrows, text, blur, shapes, etc).

The goal is to provide a more native and reliable screenshot workflow for GNOME Wayland users.
