### ISSUE TITLE
No copy to clipboard / crash between 2 screenshots

### ISSUE THREAD

**Issue by AlexanderStavrop** [flameshot-org/flameshot#2508]
### Flameshot Version
![image](https://user-images.githubusercontent.com/56675566/160306029-0a86c8a2-b1fc-46c7-b17f-c4584d1d3d19.png)
default configuration

### Installation Type
Linux, MacOS, or Windows Package manager (paru)

### Operating System type and version
Arch Linux

### Description

Since last week i have been having the following issue.
When i take a screenshot, i try to copy it and the result is the screenshot not beeing copied and the program to freeze. After some time it unfreezes and i can take a new screenshot and when i copy the second one, the first appears on my clipboard manager.
ClipboardManager : Copy copyq 6.1.0-1

### Steps to reproduce
- I press the print-screen button on my laptop and  select the area 
- Press ctrl +C or double click (doesn't matter)
- Check if the screenshot is copied.
- Try to take another screenshot.
- When you are able to, take a new one and copy ti
- Check if the new screenshot is copied, or the old one ?!

### System Information

![image](https://user-images.githubusercontent.com/56675566/160306197-b1b2d4ee-879d-4234-8f11-d44ff6a584df.png)

**Comment by borgmanJeremy** [comment]
Please post your config file

**Comment by AlexanderStavrop** [comment]
I have been using the default config since the problem occured, but it didn't solve anything

**Comment by AlexanderStavrop** [comment]
> Please post your config file


I have been using the default config since the problem occured, but it didn't solve anything

**Comment by mmahmoudian** [comment]
what is your clipboard manager? Also please give provide the output of:

```sh
pacman --query | grep -i -e "copy" -e "clip"
```

**Comment by AlexanderStavrop** [comment]
> what is your clipboard manager? Also please give provide the output of:
> 
> ```shell
> pacman --query | grep -i -e "copy" -e "clip"
> ```
Clipboard manager is CopyQ
> ```shell
> copyq 6.1.0-1
> ```

**Comment by borgmanJeremy** [comment]
Wow that's weird. We have no electron dependencies.

**Comment by AlexanderStavrop** [comment]
> Wow that's weird. We have no electron dependencies.

I really dont know, i ve been crash problems with discrod and signal (those programs use electron). All three of the problems have been solved since the reinstall.

Don't know. Don't care.

**Comment by Atreyagaurav** [comment]
I have the same issue, my clipboard manager is xclip. I can't copy the image to clipboard, it simply has no effect no output on the terminal, no notifications. I also don't have any config as I only installed it few minutes ago.

```
Arch Linux (kernel: 5.17.2-arch3-1 )
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```
