### ISSUE TITLE
pinning and copying stopped working for one-off mode `flameshot gui`

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2509]
### Flameshot Version

Flameshot v11.0.0 (54690d5b)
Compiled with Qt 5.15.3

### Installation Type

User repository (AUR)

### Operating System type and version

5.10.105-1-MANJARO x86_64 GNU/Linux

### Description

When `flameshot gui` is ran on one-off mode (i.e no background daemon), the pinning does not work, instead the tray icon goes invisible although it retains the space in the tray icon. The same thing happens with `flameshot gui --pin`.

The copying is affected, but the tray icon follow the same behavior as the pinning.

Note that if I run the daemon first and then run the `flameshot gui`, both pinning and copying work.

### Steps to reproduce

1. `pkill flameshot`
2. `flameshot gui`
3. select a region
4. pin it
5. observe that nothing is pinned
6. observe the tray area

### Screenshots or screen recordings

https://user-images.githubusercontent.com/390889/160420256-ae92867a-2979-48e6-a737-102bf6fc5027.mp4

https://user-images.githubusercontent.com/390889/160421455-d594fa75-ef66-4f09-abb2-24099db055d2.mp4

### System Information

System:
  Host: precisiontower Kernel: 5.10.105-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.3 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: amdgpu,modesetting gpu: amdgpu resolution: 1: 1920x1080~60Hz
    2: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon Pro WX 3200 Series (POLARIS12 DRM 3.40.0
    5.10.105-1-MANJARO LLVM 13.0.1)
    v: 4.6 Mesa 21.3.7

**Comment by Infinidoge** [comment]
Can reproduce
Flameshot:
```
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3
```

System:
```
System:
  Host: Infini-DESKTOP Kernel: 5.17.0 x86_64 bits: 64 Desktop: N/A (Window Manager: Qtile 0.21.0)
  Distro: NixOS 22.05 (Quokka) 
Graphics:
  Message: No device data found. 
  Display: x11 server: X.Org 1.20.13 driver: loaded: N/A resolution: 
  1: 2560x1080~60Hz 2: 1920x1080~60Hz 3: 1920x1080~60Hz 
  OpenGL: renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 
  v: 4.6.0 NVIDIA 510.60.02
  ```

**Comment by Infinidoge** [comment]
Nevermind, I retract the above, unsure if anything that particularly affects flameshot has changed.

**Comment by mmahmoudian** [comment]
This is a general case of #2496

**Comment by Alaskra** [comment]
I can't reproduce, although I have almost the same environment with you.

```
> inxi --system --graphics --width=80
System:
  Host: alaskra-redmibook14 Kernel: 5.4.188-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.4 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nvidia v: 510.60.02
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.3.8

> ./src/flameshot --version
Flameshot v11.0.0 (0e2f37f)
Compiled with Qt 5.15.3

```

**Comment by borgmanJeremy** [comment]
@mmahmoudian I believe this is resolved now. Can you confirm?
