### ISSUE TITLE
Option to configure default behavior when hitting ctrl+c/enter

### ISSUE THREAD

**Issue by GriffinCodes** [flameshot-org/flameshot#251]
Hello there, I am a previous user of Screencloud and I'm just getting started with Flameshot. So far, I'm finding it's extremely well made, and has lots of awesome features that I will be using a _lot_. 

One of my favorite features of Screencloud was the ability to configure the default behavior when you're ready to save the screenshot. I always had it set to upload to imgur, then immediately copy the URL to my clipboard. I would greatly appreciate it if something like this could be added to this project as well.

Thanks!

**Comment by dskuratovich** [comment]
I also affiliate with this idea; so it'd be perfect if there's such ability!

**Comment by GriffinCodes** [comment]
This was added a while ago

**Comment by mmahmoudian** [comment]
@GriffinCodes thanks for as spotting this. There are so many backlogs that we sometimes forget to close all related issues.
