### ISSUE TITLE
Blur everything without the selected area

### ISSUE THREAD

**Issue by ProdigyMaster** [flameshot-org/flameshot#2510]
### Feature Description

Blur everything without the selected area. I would like to select an area on the screenshot, and everything outside this area should be blurred to focus attention only on the not blurred things. 

Use case: 
- Show single email without showing all inbox

Thank you :)

**Comment by Alaskra** [comment]
This is repeat with https://github.com/flameshot-org/flameshot/issues/165 and maybe I can help improve it.

**Comment by mmahmoudian** [comment]
This can either be implemented by a toggle button in settings of the blur tool in the sidebar or via a plugin. I suggest the former
