### ISSUE TITLE
Flameshot save slow after changing size with keyboard

### ISSUE THREAD

**Issue by vegantom** [flameshot-org/flameshot#2512]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)
pacman install from community repo (not the aur)

### Operating System type and version

Arch Linux

### Description

When saving some images the save GUI lags severely. If I just take a quick snap it's okay, but if I manually change the width and height of the image and blur it and change the position on the screen, when I go to save the image it's incredibly laggy.

### Steps to reproduce

Open flameshot, adjust the pixel size of the image (using my keyboard) and use the blur feature, after around 2 minutes when I'm happy with the changes to the image I save it, and the save GUI is very buggy. Screenshot attached is of the screen I am talking about.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/17987290/160641562-c7c5be46-c538-4629-80df-fd7b976348bf.png)

### System Information

System:
  Host: Arch-Tom Kernel: 5.16.16-arch1-1 arch: x86_64 bits: 64 Desktop: GNOME
    v: 41.5 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 510.54
  Display: x11 server: X.org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1440
  OpenGL: renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 510.54

**Comment by mmahmoudian** [comment]
I can confirm too using Flameshot v11.0.0 (0c9a58fa)

**Comment by veracioux** [comment]
#2545 should fix it.
