### ISSUE TITLE
flameshot doesn't take a screenshot

### ISSUE THREAD

**Issue by leonardon397** [flameshot-org/flameshot#2513]
## My flameshot version is:

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.16-200.fc35.x86_64
fedora: 35

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 35 (KDE Plasma), with kernel 5.16.16-200.fc35.x86_64

### Description

When I click in the flameshot's icon in tray, it's not happens. When I click with right button, opens a context menu and I click in "Tirar Captura de Tela" (My OS is in PT-BR, that it's like to "Take Screenshot"), but, it doesn't work. When I click with right button and "Abrir Launcher" (I think in English version is "Open Launcher"), opens a dialog, however, when I click in "Tirar uma nova captura de tela" (In English version, I think it means "Take a new screenshot"), nothing happens, giving the impression that button is just a useless ornament.

Please, help-me!

I followed all steps discribed in <https://flameshot.org/docs/guide/troubleshooting/>, and I got the link <https://bin.snopyta.org/?75e7d15480ce5aa4#8j3Phr1qvhw5o5i2rwWzbd4bqDaNfRbNerfQ9JwGhioQ>.

### System Information

OS: Fedora Linux 35 (KDE Plasma) x86_64
Kernel: 5.16.16-200.fc35.x86_64
Window Manager: Wayland
Qt: Version 5.15.2 (compiled with 5.15.2)
KDE Frameworks Version 5.91.0

**Comment by pposiew** [comment]
I have the same problem on Fedora 35.
On X11, when flameshot is not run, I can take screenshot from command line (eg. flameshot screen). When it was run and is in tray,  it's not happens. 
On Wayland, when I take a screenshot, from command line it is open format “Save screenshot”, when I click “Save”, it calls “Error trying to save” and file has 0B.
When I call “flameshot gui”  from command line, it hangs up and write message "qt.qpa.wayland: Wayland does not support QWindow::requestActivate()"
When it runs in tray, iit behaves like X11.

**Comment by pposiew** [comment]
Yes, it works fine now. 
Thanks.

**Comment by borgmanJeremy** [comment]
Thanks for reporting back. I think we are at a critical mass of bug fixes so we should have a release soonish
