### ISSUE TITLE
Crash on choosing other tools after making text element

### ISSUE THREAD

**Issue by ahangarha** [flameshot-org/flameshot#2514]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Kubuntu 20.04

### Description

After making text element, if I choose any other tool, the app crashes.

### Steps to reproduce

1. Make a text element
2. Click somewhere else
3. Choose another tool (line, move,...)
4. Crash

### Screenshots or screen recordings

https://user-images.githubusercontent.com/11241315/161009820-2976d5d7-cda2-4eee-94f0-fcbd3b402a21.mp4

### System Information

Kubuntu 20.04

![image](https://user-images.githubusercontent.com/11241315/161009975-095b3746-ebba-49ea-be1a-68c95411fe54.png)

Xorg

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8

System:
  Host: luvuntu Kernel: 5.4.0-105-generic x86_64 bits: 64 
  Desktop: KDE Plasma 5.18.8 Distro: Ubuntu 20.04.4 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel 
  Device-2: AMD Sun PRO [Radeon HD 8570A/8570M] driver: radeon v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: modesetting,radeon FAILED: ati 
  unloaded: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) 
  v: 4.2 Mesa 21.2.6

**Comment by mmahmoudian** [comment]
Thank you for filing a bug report. Unfortunately it is duplicate of all the following:

- #2283
- #2353
- #2402
- #2407
- #2429
- #2434
- #2454
- #2458
- #2489


Additionally, it has been already been fixed in the main branch and you can download the latest builds from this link:

https://flameshot.org/docs/installation/development-build/

**Comment by sahilrajput03** [comment]
I felt happy that a lot of other people faced this same issue a lot.. ! :)

**Comment by sahilrajput03** [comment]
Thanks @mmahmoudian  for fixing the issue...

**Comment by mmahmoudian** [comment]
@sahilrajput03 I didn't do much. All the credit should go to @AndreaMarangoni for creating #2369 PR
