### ISSUE TITLE
Clipboard copy keyboard shortcut is not working

### ISSUE THREAD

**Issue by hihabib** [flameshot-org/flameshot#2521]
This option is not working. I am using ZorinOS Pro (ubuntu 20 based)

![image](https://user-images.githubusercontent.com/63936164/161374981-c1c72018-6b25-40fd-96e4-6bd7b62fba9a.png)

**Comment by mmahmoudian** [comment]
Please consider filing a proper and complete bug report. This bug report lacks many details that are vital to follow up the case.

**Comment by habibulislam6862** [comment]
> Please consider filing a proper and complete bug report. This bug report lacks many details that are vital to follow up the case.

sorry for this lack. I am not familiar with those formalities. Could you please tell me or give me a link of article so that I can know how to submit a bug report properly?

**Comment by mmahmoudian** [comment]
This is where the bugs should be reported:

https://github.com/flameshot-org/flameshot/issues/new?assignees=&labels=Unconfirmed+Bug&template=bug-report.yaml

**Comment by borgmanJeremy** [comment]
Any update on the details needed? If not I will close this.

**Comment by habibulislam6862** [comment]
> 
https://github.com/flameshot-org/flameshot/issues/2526
yeah bug report done.

**Comment by pigsbeforeswine** [comment]
FWIW, I was able to resolve this by setting Flameshot to start automatically on startup. From my observations, just binding it to the print screen key will otherwise work and you can still save screenshots, but Flameshot has to be specifically started as any other app before it starts storing into the clipboard.
