### ISSUE TITLE
Problem with compiling Flameshot 11.0.0

### ISSUE THREAD

**Issue by Bars7878** [flameshot-org/flameshot#2524]
### Flameshot Version

Flameshot 11.0.0 
Qt 15.5.0
MinGW 8.1.0

### Installation Type

Compiled from source

### Operating System type and version

Windows 10

### Description

Hi! Please, help with compiling Flameshot project from sources. I receive error at the end of compiling process:
[100%] Linking CXX executable flameshot.exe
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0xa5): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x188): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x333): undefined reference to `_imp___ZN13color_widgets10ColorWheelC1EP7QWidget'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x33e): undefined reference to `_imp___ZN13color_widgets10ColorWheel13colorSelectedE6QColor'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x38a): undefined reference to `_imp___ZN13color_widgets10ColorWheel16staticMetaObjectE'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x3e1): undefined reference to `_imp___ZN13color_widgets10ColorWheel12colorChangedE6QColor'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x423): undefined reference to `_imp___ZN13color_widgets10ColorWheel16staticMetaObjectE'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0xfc4): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(uicoloreditor.cpp.obj):uicoloreditor.cpp:(.text+0x112f): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(colorpickereditor.cpp.obj):colorpickereditor.cpp:(.text+0x26c7): undefined reference to `_imp___ZN13color_widgets10ColorWheelC1EP7QWidget'
CMakeFiles\flameshot.dir/objects.a(colorpickereditor.cpp.obj):colorpickereditor.cpp:(.text+0x26f8): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(colorpickereditor.cpp.obj):colorpickereditor.cpp:(.text+0x2ffe): undefined reference to `_imp___ZN13color_widgets10ColorWheel13colorSelectedE6QColor'
CMakeFiles\flameshot.dir/objects.a(colorpickereditor.cpp.obj):colorpickereditor.cpp:(.text+0x300f): undefined reference to `_imp___ZN13color_widgets10ColorWheel16staticMetaObjectE'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0x7b6): undefined reference to `_imp___ZN13color_widgets10ColorWheelC1EP7QWidget'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0x7e1): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0xc3f): undefined reference to `_imp___ZN13color_widgets10ColorWheel13colorSelectedE6QColor'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0xc8a): undefined reference to `_imp___ZN13color_widgets10ColorWheel16staticMetaObjectE'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0x1090): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
CMakeFiles\flameshot.dir/objects.a(sidepanelwidget.cpp.obj):sidepanelwidget.cpp:(.text+0x1105): undefined reference to `_imp___ZN13color_widgets10ColorWheel8setColorE6QColor'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [src\CMakeFiles\flameshot.dir\build.make:2214: src/flameshot.exe] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:658: src/CMakeFiles/flameshot.dir/all] Error 2
mingw32-make.exe: *** [Makefile:155: all] Error 2
16:18:35: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project flameshot (kit: Desktop Qt 5.15.0 MinGW 32-bit)
When executing step "Build"
16:18:35: Elapsed time: 04:16.

Please, help how its error can be resolved?

### Steps to reproduce

.

### System Information

Windows

**Comment by borgmanJeremy** [comment]
Can you describe how you are building this? For example, are you opening this in QtCreator? How are you installing Qt? It appears you are not linking to the embeded color_widget dependency.

**Comment by Bars7878** [comment]
Yes, Qt Creator 7.0.0 installed, QT 5.15.0 with MinGW 8.1.0 x32/x64. I open CMakeLists.txt in QT Creator and try Build. Seems all dependencies is installed and i really dont understand how resolve this.

**Comment by Bars7878** [comment]
Problem with m_colorWheel class. But all needed dependcies seems installed. Which parameters need check for color_widget dependency ?

**Comment by borgmanJeremy** [comment]
I booted into my Windows drive and I think the main difference is I have QtCreator set to compile with MSVC. MinGW should generally work though, we build against it in our CI. 

Your error is specifically a linker error so you will need to dig in to see why your linker is not finding the symbols:
- Maybe find the verbose log and see if an include path is missing
- Check the actual object files to see if the symbols are there

As I said, it works on my PC, and our CI builds against MSVC and MinGW so it's an issue local to your setup.

**Comment by Bars7878** [comment]
@borgmanJeremy  i am dont use QT and compiling solutions in my work. I just need compiling Flameshot without upload images to imgur and update functions for Windows. This is one-time task. Please, can you help me?

**Comment by borgmanJeremy** [comment]
This appears to be an issue with gnu windows compiler: https://stackoverflow.com/questions/19486070/resource-rc-windres-syntax-error-mingw

Try building with MSVC compiler on windows instead.

**Comment by mmahmoudian** [comment]
Although ideologically I prefer Gnu stuff to Microsoft😅, in this particular case based on some of the forums I read it seems MSVC does a better job, plus it "provides some additional VS tools such as MFC, ATL, DirectX and GDI+" (although as far as I understand, I don't think we would need them).

**Comment by veracioux** [comment]
@borgmanJeremy I don't have much of an opinion on this, so I agree with whatever you think is best.

**Comment by borgmanJeremy** [comment]
Okay officially requiring MSVC.

**Comment by zzu-andrew** [comment]
因为使用Mingw进行编译时，rc文件和msvc的不太一样，这里最为暴力的修改方式就是直接将 
![image](https://github.com/flameshot-org/flameshot/assets/22228543/1afbded7-c803-4545-9951-27a156883099)
随便修改一个字符串，然后再将代码中关于MSVC的export去掉就可以了
![image](https://github.com/flameshot-org/flameshot/assets/22228543/13fa9161-6ea6-4bcc-a41e-9881acf0ea29)
![image](https://github.com/flameshot-org/flameshot/assets/22228543/b894011c-4224-48a0-b2aa-e225143e1687)
