### ISSUE TITLE
A new version of xdg-portal has been released, and it's now possibile to "remember the choice" instead of clicking "Share" at every screenshot. 

### ISSUE THREAD

**Issue by All3xJ** [flameshot-org/flameshot#2536]
### Feature Description

https://github.com/flatpak/xdg-desktop-portal/pull/638#issuecomment-1092863714
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/NEWS

As you can see, it has been released the new version of portal. Now it's possible to set "remember the choice" instead of manually clicking on "Share" at EVERY screenshot via Flameshot.

Can you implement it in Flameshot, this would finally make Flameshot experience under Wayland USABLE AGAIN!

**Comment by borgmanJeremy** [comment]
This seems to only be for the "screen-cast" portal which is used for video and audio. We use the "screenshot" portal.

**Comment by mmahmoudian** [comment]
I believe this can be closed now. Please feel free to reopen it in case there is more to this. I might have missed something.

**Comment by All3xJ** [comment]
If you want that this is supported, please go here and support this: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/27
