### ISSUE TITLE
src/utils/confighandler.cpp:517: possible use of wrong operator ?

### ISSUE THREAD

**Issue by dcb314** [flameshot-org/flameshot#2537]
### Flameshot Version

11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

fedora linux

### Description

New C compiler clang-14 says:

src/utils/confighandler.cpp:517:12: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]

Source code is

    return checkUnrecognizedSettings(log) & checkShortcutConflicts(log) &
           checkSemantics(log);

Maybe better code:

    return checkUnrecognizedSettings(log) && checkShortcutConflicts(log) &&
           checkSemantics(log);

### System Information

fedora 36 beta

**Comment by borgmanJeremy** [comment]
Yes, clang is correct. Feel free to submit a PR.
