### ISSUE TITLE
Print Screen doesn't show up flameshot interface in Ubuntu 21.04

### ISSUE THREAD

**Issue by konstantin83** [flameshot-org/flameshot#2542]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 21.04

### Description

Installed the Flameshot from Github download link. It starts and runs perfectly. But I cant' figure out the main shortcut to start making screenshots without clicking on tray icon.
Obviously it must be print-screen button. But it's not reacting.
How can I bind it?

### System Information

Ubuntu 21.04
Flameshot v11.0.0

**Comment by mmahmoudian** [comment]
I assume you are relatively new to Linux. The keyboard shortcuts to run applications are managed by the Window Manager part of your Desktop Environment. I assume your Desktop Environment is Gnome. You can follow the instructions in the following link to setup a keyboard shortcut:

https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en

Make sure to set the shortcut to run the following command:

```sh
flameshot gui
```

**Comment by konstantin83** [comment]
@mmahmoudian you are right. It's my 5-th day of Linux-only usage. 

Thank you very much for your help. But it seems to me that this advise MUST be included in Installation guide.

**Comment by borgmanJeremy** [comment]
The problem with including it in the installation guide is it varies across all the different desktop environments. One of the downsides is the same as its upside, customizability. This means it makes it really hard for us to write a universal guide.

**Comment by mmahmoudian** [comment]
@konstantin83 welcome to Linux community. This GitHub repo is for Flameshot, but if you have some Linux questions, you can ask them on [matrix](https://matrix.to/#/@mehrad:kde.org).

I would also surest you to watch some YouTube videos to get more familiar with some concepts in Linux. My suggestion is to start from here:

https://youtube.com/playlist?list=PL5--8gKSku14YHwPizdlWW5tWLIi9opy8
