### ISSUE TITLE
Copy selection to clickboard frequently does not work in Linux mint 19.3

### ISSUE THREAD

**Issue by richfuns** [flameshot-org/flameshot#2543]
### Flameshot Version

Flameshot v11.0.0 

### Installation Type

Snap from Snapcraft

### Operating System type and version

 Linux Mint 19.3

### Description

Copy selection to clickboard frequently does not work in Linux mint 19.3

thanks for you work. 

### System Information

 Operating System: Linux Mint 19.3
  Kernel: Linux 4.15.0-175-generic
   Architecture: x86-64

**Comment by mmahmoudian** [comment]
What is your Desktop Environment? Cinnamon, Mate, ot Xfce?

**Comment by richfuns** [comment]
> What is your Desktop Environment? Cinnamon, Mate, ot Xfce?

Cinnamon

**Comment by mmahmoudian** [comment]
I cannot reproduce this in a clean VM.

![image](https://user-images.githubusercontent.com/390889/163213294-21cbc5ac-7b35-48e9-b255-d6f18652dc75.png)

Unless you can narrow down in which conditions it does not copy, we cannot take any actions for this issue as have no way to reproduce this.

To clarify, these are what I have done:
1. install Linux mint 19.3 Cinnamon (in virt-manager)
2. `sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y`
3. `systemctl reboot`
4. `sudo apt install snapd`
5. `snap install flameshot` (v11.0.0)
6. `flameshot` (Cinnamon application menu did not detect the installed snap)

@richfuns After installing Linuxmint I realized the preferred containerized-applications installation method in Linuxmint is Flatpak. You can give that a try.

**Comment by richfuns** [comment]
@mmahmoudian 

Thank you so much for you hard trying. 

Lastly, I tried to download flameshot through PackageManager of Linux MInt and that version is noted Flatpak, version number is 11.0.0 stable, and it works well eventually. 

But` flameshot gui` command cannot be used again, would you please let me know why? 

Thanks again.

**Comment by mmahmoudian** [comment]
Read this:
https://flameshot.org/docs/installation/installation-linux/#flatpak

You can create an alias though:

```sh
alias flameshot="flatpak run org.flameshot.Flameshot"
```
