### ISSUE TITLE
Window Rectangle Recognition

### ISSUE THREAD

**Issue by XMuli** [flameshot-org/flameshot#2548]
### Feature Description

Can I add smart window rectangle position recognition (only windows) to it? If approved, I will do the work later to add this feature and submit a PR

**Comment by mmahmoudian** [comment]
This feature has been requested many times:

- #5
- #334
- #1814
- #1816

and the plan has been to use opencv for this.

As far as I can recall, @borgmanJeremy [correctly imho] is against having a feature that is platform-specific. ([example](https://github.com/flameshot-org/flameshot/issues/1814#issuecomment-1011462752))

So, do you think you can make it cross-platform?

**Comment by XMuli** [comment]
@mmahmoudian Thanks for your reply!

Previously, I was thinking of wrapping the APIs for Linux, Windows, and MacOS in turn, and then wrapping a separate abstraction layer to achieve a cross-platform approach.

> and the plan has been to use opencv for this.

Wouldn't it be a bit unwieldy to add opencv as a library? (just the senses above).

But I will study how to use opencv to accomplish this function (this may take a long time, because I am not very familiar with this library),, I am also interested in this way of implementation, if I have free time later

**Comment by borgmanJeremy** [comment]
Opencv was just an idea on how to do it but it had some serious limitations.

You may be understanding the effort on doing this manually especially on Linux platforms as there will be a different method for every DE*2 (for wayland and xorg) . There also is no stability on the Linux side so this might be a high maintenance burden.

**Comment by borgmanJeremy** [comment]
I'm going to close this in favor of #5
