### ISSUE TITLE
Command line options don't work on windows

### ISSUE THREAD

**Issue by jrozner** [flameshot-org/flameshot#2554]
### Flameshot Version

11.0.0 and master

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Application starts and exits with no error message and doesn't take a screenshot.

### Steps to reproduce

1. run `flameshot gui`

### System Information

windows 11
2 displays

**Comment by veracioux** [comment]
This is a duplicate of #2118.
