### ISSUE TITLE
Fixed location save for QUICK save (Ctrl + C)

### ISSUE THREAD

**Issue by nn653** [flameshot-org/flameshot#2557]
### Feature Description

Hello, I really like your project, but there are some inconveniences when saving screenshots using the "**Ctrl + C**" key combination.

When you take a screenshot using this key combination, the original image is saved at the path specified in the application configuration. But there are times when you need to specifically specify the save path for the image, with a specific name (in another folder), but when you try to do this, it also changes the save path for the following screenshots. It would be nice to make a separate property that points to the path to save screenshots using the **Ctrl + C** key combination. 

![123](https://user-images.githubusercontent.com/41921371/164775852-1408ddc6-74d5-4778-9b69-2d935bb47978.png)

Thanks!

**Comment by mmahmoudian** [comment]
I strongly disagree. This would bloat the settings without adding much. Instead the command line should be used to satisfy these type of needs. I can see that you are a windows user and I have no understanding on how to customize keyboard shortcuts, but ideally (similar to linux) you should be able to define a shortcut that you call using a keyboard shortcut (e.g <kbd>Ctrl</kbd>+<kbd>PrintScreen</kbd>}. I suggest the following command for you:

```sh
flameshot gui --clipboard --path /alternative/path/that/you/like/
```

**Comment by borgmanJeremy** [comment]
I agree with @mmahmoudian. This will be better on windows when someone adds CLI ability to windows.

**Comment by kkard2** [comment]
> I strongly disagree. This would bloat the settings without adding much. Instead the command line should be used to satisfy these type of needs. I can see that you are a windows user and I have no understanding on how to customize keyboard shortcuts, but ideally (similar to linux) you should be able to define a shortcut that you call using a keyboard shortcut (e.g Ctrl+PrintScreen}. I suggest the following command for you:
> 
> ```shell
> flameshot gui --clipboard --path /alternative/path/that/you/like/
> ```
> 
> I don't close this before hearing other dev's opinions.

what if someone doesn't want a separate shortcut for clipboard? i like my current workflow of first selecting a region, making changes, and then deciding between ctrl+c/ctrl+s. i also like having all screenshots saved to files in one location, so i was really surprised when flameshot started putting my ctrl+c images in the new path.

(also, is it even possible to accept a capture with keyboard in the `--clipboard` mode? i don't want to search for a gui button)
