### ISSUE TITLE
Screenshot goes through "Portal" and not directly to Flameshot GUI

### ISSUE THREAD

**Issue by Yair-Ziv** [flameshot-org/flameshot#2560]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Snap from

### Operating System type and version

Ubuntu 21.10 x86_64

### Description

I was using the apt version of Flameshot until I've noticed it's an old version and I can't seem to download a more recent version via apt, so I uninstalled the apt Flameshot and downloaded via Snap (snap install flameshot). 

The installation went fine, using flameshot -v echos the correct version but when taking a screenshot it goes through a "Portal" application that asks me "Share this screenshot with the requesting application?". After pressing Share it will lead me to the Flameshot app but I don't feel like that's the intended behavior.

Another problem I've been having is that flameshot echos the following line: Qt: Session management error: Could not open network socket. I don't know if that's related or not.

### Steps to reproduce

1. run flameshot gui.
2. take a screenshot.

### Screenshots or screen recordings

![cropped](https://user-images.githubusercontent.com/94287812/164968154-725c8ea2-a933-4527-8434-aac79669bed9.png)

### System Information

OS: Ubuntu 21.10 x86_64
Monitor Configuration: 
Monitors: 3
 0: +*XWAYLAND2 2560/600x1440/340+1920+0  XWAYLAND2
 1: +XWAYLAND0 2560/600x1440/340+4480+0  XWAYLAND0
 2: +XWAYLAND1 1920/310x1080/170+0+141  XWAYLAND1

Desktop Environment: Gnome, Wayland

**Comment by mmahmoudian** [comment]
Read this and take your complaints to Gnome:
https://flameshot.org/docs/guide/wayland-help/#gnome

**Comment by moshfiqrony** [comment]
[This solved my issue](https://askubuntu.com/a/1356534/1291208)

**Comment by victorabarros** [comment]
Ty @moshfiqrony .
I just upgrade my ubuntu from 19 to 22.
Big mistake. thefuck, openvpn, flameshot, zoom... All of them were affected.

**Comment by mmahmoudian** [comment]
@victorabarros this is not a Linux support forum, but I can suggest you to switch to KDE Wayland for a more smooth experience. Although for the time being Wayland in general is not as smooth as X11, but it is gradually getting there. Install KDE or Gnome X11 on the side and switch to those if your workflow has badly affected by Wayland issues. Follow this:
https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop

In my personal opinion using latest Ubuntu and switch to X11 (Xorg) is less of a security risk than to go back to older Ubuntu.

**Comment by tirzasrwn** [comment]
Thanks @moshfiqrony
This is really big mistake as @victorabarros said. My ms-teams cannot share screen too.

**Comment by deividrp** [comment]
> The option by default turned on is Wayland. But we need to disable it. And it is already in the config file but commented out. So it's also safe to use.
> 
> What you need to do is. At first check is Wayland activated or deactivated in your system.
> 
> ```
> echo $XDG_SESSION_TYPE
> ```
> 
> If the above command outputs, wayland, your system is using wayland. Then We have to disable wayland and enable xorg (x11). To do this,
> 
> Please go to this file
> 
> ```
> sudo nano /etc/gdm3/custom.conf
> ```
> 
> Uncomment this line.
> 
> ```
> WaylandEnable=false
> ```
> 
> Reboot your system.
> 
> [Reference and full solve here](https://askubuntu.com/a/1407496/1291208)

This solution works fine, but if you are looking for a way to stay with Wayland enable instead X11, try this way:
 
`/bin/sh -c "flameshot gui" > /dev/null &`

![flameshot](https://github.com/user-attachments/assets/6f7c77e0-140c-4931-8c22-4f1c7f480df7)

**Comment by funfely** [comment]
great !!! tank you so much for the solution, the error dont appear again.
https://github.com/flameshot-org/flameshot/issues/2560#issuecomment-1223943716
