### ISSUE TITLE
An additional window appeared in Ubuntu 22

### ISSUE THREAD

**Issue by proger-su** [flameshot-org/flameshot#2563]
### Flameshot Version

Flameshot v11.0.0 ()

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04 LTS

### Description

In Ubuntu 22.04
After clicking "Take Screenshot" an additional window is appeared where I must click "Share" and after that flameshot tools opens.

### Steps to reproduce

1. run flameshot
2. click "Take Screenshot" in tray icon

### Screenshots or screen recordings

[https://i.imgur.com/XxPbcYv.png](https://i.imgur.com/XxPbcYv.png)

### System Information

[https://i.imgur.com/4RmCrW4.png](https://i.imgur.com/4RmCrW4.png)

**Comment by borgmanJeremy** [comment]
Duplicate issue. It's an upstream gnome choice.

**Comment by mmahmoudian** [comment]
@proger-su this is because of Gnome. Please take your complaints to them. More info here:
https://flameshot.org/docs/guide/wayland-help/#gnome

**Comment by proger-su** [comment]
@mmahmoudian 
Thanks a lot.

But I cannot understand, will it be fixed soon? Or will it be better to downgrade to Ubuntu 20.04?

Because other apps I use have a problem with screenshots too, and I think for the same reason.

**Comment by mmahmoudian** [comment]
@proger-su

> will it be fixed soon?

this is something you should ask from Gnome devs.

> will it be better to downgrade to Ubuntu 20.04?

If you are looking for a permanent solution, switch from Gnome to something else like [KDE](https://itsfoss.com/install-kde-on-ubuntu/) or [Xfce](https://bytexd.com/how-to-install-xfce-desktop-or-xubuntu-in-ubuntu/)

**Comment by adamwojt** [comment]
Would be nice to have workaround for this. Perhaps we could have it open just for visibility ? I love flameshot but unfortunately I am forced to use Ubuntu in my workplace.

**Comment by mmahmoudian** [comment]
@adamwojt you might be forced to use Ubuntu, but you are not forced to use Gnome. This is not an issue with Ubuntu, but it is an issue with Gnome.

-------

I personally suggest you to consider switching to a more sensible Desktop Environment. You can read about some of them in [this article](https://tecadmin.net/best-linux-desktop-environments/)

**Comment by proger-su** [comment]
I have downgraded to Ubuntu 20 for a time being...

I really like Ubuntu for its simplicity. I'm a freelancer and I need to work and not fiddle with settings.

In Ubuntu 22, not only the flameshot was broken. All applications that take screenshots stopped working correctly (for example, Upwork time tracker)

And with such antics, Ubuntu is increasingly pushing me to switch to a Mac 😁

**Comment by proger-su** [comment]
I have not heard about the ElementryOS before. Thanks for the tip, worth a try.
