### ISSUE TITLE
Blinking screen during area selection on Ubuntu 22.04 when custom scale is set

### ISSUE THREAD

**Issue by barisoztop** [flameshot-org/flameshot#2564]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3

### Installation Type

Snap from Snapcraft

### Operating System type and version

Ubuntu 22.04 (5.14.21-051421-generic)

### Description

Whenever I activate flameshot to take screenshot via area selection, there is some problem with resolution and it goes to cycle of a blank screen and a bit screen content. This repeats until I exit from flameshot with ESC or completing taking a screenshot. I was thinking it is because of ubuntu upgrade, but I realized that I scaled up the content from 100% to 125% under settings > displays. So this works fine when it is 100%. I cannot tell if it was working on this bigger scale with older Ubuntu.

### Steps to reproduce

scaled up the content from 100% to 125% under settings > displays
run flaneshot to take a screenshot on the command line via `/snap/bin/flameshot gui`

### System Information

Ubuntu 22.04 (5.14.21-051421-generic)
Resolution: 3840x2160 or 1920x1080

**Comment by barisoztop** [comment]
I had a chance to try this with another monitor. Same issue there. Also keep in mind that if you try to reproduce this on a environment with multiple monitors, all monitors have to be rescaled to 125%

**Comment by borgmanJeremy** [comment]
@sahilvirk  please don't hijack this thread. Open a new issue with your details or join our matrix server.

**Comment by borgmanJeremy** [comment]
Im going to close this as a dup of the other fractional scaling issues.
