### ISSUE TITLE
qt.qpa.fonts: Populating font family aliases took 258 ms

### ISSUE THREAD

**Issue by dzg** [flameshot-org/flameshot#2565]
Running `flameshot gui` on Mac showed:
`qt.qpa.fonts: Populating font family aliases took 258 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost.
flameshot: info: Screenshot aborted.`

Seems like a Qt issue. Where exactly do I configure font family?

**Comment by borgmanJeremy** [comment]
Does that warning actually cause you an issue? I also get that warning on my Mac.
