### ISSUE TITLE
Flameshot "hangs" whenever used

### ISSUE THREAD

**Issue by levalithan** [flameshot-org/flameshot#2571]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

User repository (AUR), Flatpak from Flathub

### Operating System type and version

Manjaro 21.2.6

### Description

I'm trying to run flameshot gui through a bash script that i've bound to a super+enter bind, though you can still recreate this issue in the terminal

Whenever I enter flameshot gui in the terminal, i'm prompted to take a screenshot which mostly works fine, but after hitting escape or saving the screenshot the program doesn't end, so I have to stop it manually in the terminal by hitting ctrl+c

Same goes for using the bind, after taking one screenshot i have to kill the program before i'm able to take another.

### Steps to reproduce

1. run "flameshot gui" in the terminal
2. exit out of the gui (either by hitting escape or by saving / copying the image)

### System Information

Manjaro 21.2.6
spectrwm
Xorg

Main DELL monitor on the right, XP Pen 13.3 pro on the left

**Comment by borgmanJeremy** [comment]
Do you have a notification manager?

**Comment by levalithan** [comment]
i didn't, but i installed dunst and it works great now, thanks for the help
