### ISSUE TITLE
Set image size manually?

### ISSUE THREAD

**Issue by OnkelTem** [flameshot-org/flameshot#2573]
### Feature Description

Sometimes I need to make screenshots of a specific size. For example Twitter pics should be of `504px` width for the feeds and  of `600px` width for tweet pages  precisely to prevent scaling. However, while I can see the current size, I cannot enter it.

I'd propose to add a popup form with two fields `width` and `height` when clicking on the (currently inactive) size-control.

But ideally there should also be a `ratio` control, for we could select `1:1`, `4:3`, `16:9` etc.

**Comment by mmahmoudian** [comment]
This is something that should be done through a plugin system which we are planning at the moment, but for the time being you can either script it yourself or use wrappers. For instance I made this tool to handle some of the things I needed:

https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md

**Comment by borgmanJeremy** [comment]
@mmahmoudian actually I think this will be added with the addition of the origin + size to the launcher. I was rushing to get it in v11 and need to go back and clean it up.

**Comment by OnkelTem** [comment]
@mmahmoudian Yeah, plugins would be awesome!

@borgmanJeremy 🙏 😊

**Comment by mmahmoudian** [comment]
Sorry, I've misunderstood the feature request, I thought @OnkelTem wants to resize/shrink the taken screenshot to a specific size. @borgmanJeremy thanks for correcting me 👍🏼

**Comment by borgmanJeremy** [comment]
okay I merged the ability to enter the region in the launcher.

**Comment by 2-fly-4-ai** [comment]
Add A button to lock the aspect ratio. Everyone needs it. Can't even see the x/y things while dragging. Not stoked.

**Comment by mmahmoudian** [comment]
@2-fly-4-ai 

> Add A button to lock the aspect ratio. Everyone needs it. Can't even see the x/y thing while dragging. Not stoked.

This issue is not regarding what you described, although it is in the same ballpark. For your case, you can already do it by holding down the <kbd>Ctrl</kbd> while dragging the handles on the region. In Flameshot we _usually_ follow the way Inkscape does things.

**Comment by 2-fly-4-ai** [comment]
What you are describing is manually resizing the box to an exact size and then locking the aspect by dragging it. You should be able to select a basic aspect ratio before and just snap that section. Imagine I want a 1:1 image or a 3:2 image. What is the proposed way of achieving this with the application?

**Comment by mmahmoudian** [comment]
>  Imagine I want a 1:1 image or a 3:2 image. What is the proposed way of achieving this with the application?

There are multiple ways to pre-select your region. Perhaps the easiest way is by using the launcher:
1. right click on the tray icon and click on Open Launcher
    ![image](https://github.com/flameshot-org/flameshot/assets/390889/cbf19f42-277b-4d83-8840-60db713b287b)

3. then type the size you want e.g 100x100 which is 1:1
    ![image](https://github.com/flameshot-org/flameshot/assets/390889/004e78e6-edbd-4c98-8c24-2d8f7ede0fab)



Another way is to use the commandline:

```sh
flameshot gui --region 100x100+123+456
```

which will select a 100 by 100 pixel region at x = 123 and y = 456

**Comment by mmahmoudian** [comment]
> Is there a way to resize it now and maintain that aspect ratio.

As I said, you can maintain aspect ratio with holding <kbd>Ctrl</kbd> while resizing the region. It is very simple, easy, and convenient.

> That is the basic functionality that everyone is looking for.

Actually, statistically, speaking you are in a very tiny minority. Simply take a look at issues and see how much attention users have given to such feature.

> Just add a button shortcut. Add the 4 main aspect ratios. Allow people to select which one. ,

it is not that simple as:
1. we should figure out a good way to implement it from UI/UX perspective
2. we have already got lots of complaints that the UI is too crowded and busy

At some point this can become possible using the plugin system, but for now there is no such thing.

But if you are a Linux user, you can create a simple keyboard shortcut that calls `flameshot gui --region 100x100+123+456` with different aspect ratios. If you don't know how, I can assist you in getting it working.

> Make it possible to resize the shape by scrolling and just dragging onto the spot.

That is a completely different paradigm of UX and I'm pretty confident no one would change the current design and usage of scroll to resizing the region.

**Comment by 2-fly-4-ai** [comment]
Okay well, that would make sense as to the missing functionality.

Pressing Ctrl+ resize does nothing. If it worked that would be pretty convenient.

**Comment by mmahmoudian** [comment]
@2-fly-4-ai 

> Pressing Ctrl+ resize does nothing. If it worked that would be pretty convenient.

Considering that <kbd>Ctrl</kbd><kbd>+</kbd> / <kbd>Ctrl</kbd><kbd>+</kbd> increases/decreases font size or enlarge/zoom out in most software that I Know of, I think it fits the bill. Pressing this shortcut triggers increasing/decreasing the region maintaining the aspect ratio.

But:
1. Should it work when tools are selected/active?
2. How large of a step it should take

**Comment by 2-fly-4-ai** [comment]
All I am personally after is a program that can take a screenshot of a certain aspect ratio. I would need to be able to specify the region. Snap a screen, slap some arrows on there, and save it. 

Just imagine I am someone who writes blogs. I need to be able to snapshot images of certain dimensions. Recommended dimensions for a blog image is 3:2. Instagram is 1:1. Features image is 2:1 etc. Just some simple aspect ratios you could choose from. Lock the ratio, drag, and "zoom" or make the shape bigger and smaller somehow(not really zoom but the ability to change sizes but maintain aspect). Then SNAP!

I just downloaded the top 5 screenshot programs and not a single one has this basic functionality. I imagine it's not a super rare use case either since there must be a lot of people snapshotting for blogs or social media. 

Right now this process involves a bunch of unnecessary steps and the built-in tools for Windows to handle this are pitiful.

Will do.

**Comment by mahmoud-rashwan** [comment]
I have the same issue as well in **windows 11 using build 13.1.0** , When I take a screenshot the screen is resized automatically and not taking the full screenshot

<img width="1280" height="538" alt="Image" src="https://github.com/user-attachments/assets/905fe1f7-b739-4ed5-bd01-a2ae85f8e5c5" />

**Comment by mmahmoudian** [comment]
@mahmoud-rashwan your issue is not relevant to this thread, but perhaps it is more in-line with #4172

**Comment by o0omega** [comment]
> All I am personally after is a program that can take a screenshot of a certain aspect ratio. I would need to be able to specify the region. Snap a screen, slap some arrows on there, and save it.
> 
> Just imagine I am someone who writes blogs. I need to be able to snapshot images of certain dimensions. Recommended dimensions for a blog image is 3:2. Instagram is 1:1. Features image is 2:1 etc. Just some simple aspect ratios you could choose from. Lock the ratio, drag, and "zoom" or make the shape bigger and smaller somehow(not really zoom but the ability to change sizes but maintain aspect). Then SNAP!
> 
> I just downloaded the top 5 screenshot programs and not a single one has this basic functionality. I imagine it's not a super rare use case either since there must be a lot of people snapshotting for blogs or social media.
> 
> Right now this process involves a bunch of unnecessary steps and the built-in tools for Windows to handle this are pitiful.
> 
> Will do.

SAME! I am so desperate that this basic function isn't present literally anywhere!
I also can't stand the fact that you can't even keep the dimensions label stationary, when you are resizing the screenshot capture, it just keeps jumping and you are wasting so much time to control it to precise number, what is that UX design???

**Comment by mmahmoudian** [comment]
@o0omega 

> when you are resizing the screenshot capture, it just keeps jumping

It seems you are using an old version of Flameshot. This was solved years ago and the dimension box stays where you configure it. Please consider updating to the latest version.

Also, if you want a specific dimension, you can either use Launcher (right-click on the tray icon) or use command line:

```sh
flameshot gui --region <WxH+X+Y>
```
