### ISSUE TITLE
flameshot crashed when run `flameshot gui --region 100x100+100+100`

### ISSUE THREAD

**Issue by Alaskra** [flameshot-org/flameshot#2575]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.4.188-1-MANJARO
manjaro: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

manjaro

### Description

flameshot crashed when run `flameshot gui --region 100x100+100+100`

### Steps to reproduce

1. run `flameshot gui --region 100x100+100+100`
2. flameshot crashed

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/49367127/166200454-c6e84d86-8079-4f79-a66d-7d15155d6bee.png)

### System Information

linux manjaro x11

**Comment by Alaskra** [comment]
![image](https://user-images.githubusercontent.com/49367127/166200785-1431327d-e4cc-49d1-a6b0-f140652fa828.png)
I think it's caused by this line. I don't know what it does, but delete it can fix the problem.

**Comment by borgmanJeremy** [comment]
Can you post your monitor / resolution configuration? On MacOs currently and can't replicate but I can try on Linux later.

@veracioux are we at a point that the FIXME can be resolved after your refactoring?

**Comment by Alaskra** [comment]
![image](https://user-images.githubusercontent.com/49367127/166395745-5015a0a3-388d-439e-8cfc-3735d4cf39b2.png)

**Comment by borgmanJeremy** [comment]
I cannot replicate this on Arch +  KDE X11 + same resolution as you

**Comment by Alaskra** [comment]
@mmahmoudian my environment is the same as you, but it will crash every time when run the command.

**Comment by mmahmoudian** [comment]
@Alaskra would you please try installing the via AUR and see if the issue persists

**Comment by Alaskra** [comment]
yes, issue persists.

**Comment by borgmanJeremy** [comment]
Since no one can replicate this I am going to close the issue unless fresh information can be posted.
