### ISSUE TITLE
flameshot not working immediately again

### ISSUE THREAD

**Issue by c-oss** [flameshot-org/flameshot#2577]
### Flameshot Version

community/flameshot 11.0.0-5
archlinuxcn/flameshot-git r1703.4aebf2b5-1
aur/flameshot-git r1629.0fe55916-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch linux 5.17.5-arch1-1

### Description

Flameshot doesn't work when I take another screenshot immediately after saving or copying to clipboard, only after killing flameshot can I take another screenshot

### System Information

Arch linux 5.17.5-arch1-1
DWM

**Comment by mmahmoudian** [comment]
Do you have notification manager installed and patched your DWM for systray?

**Comment by c-oss** [comment]
I just installed a new system and haven't used systray yet.
and
CPU: i9-10900K, Motherboard: MSI Z590i unify

**Comment by c-oss** [comment]
> Have you installed notification manager and patched your DWM for systray?

I just installed a new system and haven't used systray yet.
And
CPU: i9-10900K, Motherboard: MSI Z590i unify

**Comment by mmahmoudian** [comment]
@c-oss any updates?
