### ISSUE TITLE
Cinnamon desktop not supported by Flameshot flatpak

### ISSUE THREAD

**Issue by aplatypus** [flameshot-org/flameshot#2580]
### Flameshot Version

**flameshot**

```
$ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**cinnamon**
````
 $ cinnamon --version
Cinnamon 4.8.6
````

**flatpak**

```
$ flatpak list | grep  flameshot
Flameshot	org.flameshot.Flameshot	11.0.0	stable	system
```

### Installation Type

Flatpak from Flathub

### Operating System type and version

Description:	Ubuntu 21.10

### Description

* Moved here from: https://github.com/flathub/org.flameshot.Flameshot/issues/13

**Problem**

* I have been using Flamshot for many years on Cinnamon installed on Ubuntu (not using Mint)
* When I decided to move apps to use flatpak Flamshot fails to start:
```
 $ flatpak run org.flameshot.Flameshot
QIBusPlatformInputContext: invalid portal bus.
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"

(flameshot:2): GLib-GIO-ERROR **: 12:40:46.126: Settings schema 'org.cinnamon.desktop.interface' is not installed
```
* Flamshot installed from `apt` works fine under Cinnamon.

**System info**
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

 $ cinnamon --version
Cinnamon 4.8.6

$ flatpak list | grep  flameshot
Flameshot	org.flameshot.Flameshot	11.0.0	stable	system

The missing component does not see to be available:

```
$ flatpak search org.cinnamon.desktop.interface
No matches found
```

### Steps to reproduce

1 flatpak install flathub flameshot
2 I decided to move apps to use flatpak Flamshot fails to start:
```
 $ flatpak run org.flameshot.Flameshot
QIBusPlatformInputContext: invalid portal bus.
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"

(flameshot:2): GLib-GIO-ERROR **: 12:40:46.126: Settings schema 'org.cinnamon.desktop.interface' is not installed
```
  * Flamshot installed from `apt` works fine under Cinnamon.

### System Information

**System info**
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

**Comment by mmahmoudian** [comment]
Based on the error you got at the last line, it seems to be an issue on your end. Read this thread for symptoms and the solution:
https://github.com/linuxmint/cinnamon/issues/8239

**Comment by aplatypus** [comment]
* I followed gthe advice to reinstall flatpak and all the apps
* No change at all.
* The error reported sounds like flatpak needs a cinnamon runtime
  * `org.cinnamon.desktop.interface`, or
*  Access to the missing elements
    * 'QIBusPlatformInputContext: invalid portal bus.`
    * `Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"`
    * `Settings schema 'org.cinnamon.desktop.interface'`
    
* I have not found any documentation or references to a: `'org.cinnamon.desktop.interface'`.  
* The runtimes that installed with flatpak or the apps I've loaded are:

```
 $ flatpak list --runtime 
Filezilla translations	org.filezillaproject.Filezilla.Locale		stable	system
Freedesktop Platform	org.freedesktop.Platform	20.08.19	20.08	system
Freedesktop Platform	org.freedesktop.Platform	21.08.13	21.08	system
Mesa	org.freedesktop.Platform.GL.default	21.1.8	20.08	system
Mesa	org.freedesktop.Platform.GL.default	21.3.8	21.08	system
nvidia-510-60-02	org.freedesktop.Platform.GL.nvidia-510-60-02		1.4	system
nvidia-510-73-05	org.freedesktop.Platform.GL.nvidia-510-73-05		1.4	system
Intel	org.freedesktop.Platform.VAAPI.Intel		20.08	system
Intel	org.freedesktop.Platform.VAAPI.Intel		21.08	system
openh264	org.freedesktop.Platform.openh264	2.1.0	2.0	system
Freedesktop SDK	org.freedesktop.Sdk	21.08.13	21.08	system
GNOME Application Platform version 41	org.gnome.Platform		41	system
meld translations	org.gnome.meld.Locale		stable	system
Adwaita theme	org.kde.KStyle.Adwaita		5.15-21.08	system
KDE Application Platform	org.kde.Platform		5.15-21.08	system
okular translations	org.kde.okular.Locale		stable	system
LibreOffice translations	org.libreoffice.LibreOffice.Locale		stable	system
```

**Comment by mmahmoudian** [comment]
Perhaps this sold be discussed in Cinnamon forums. Please tag us there or leave the link to the thread here so that we can participate in the discussion if needed and help to resolve it

**Comment by hsandt** [comment]
Same on Ubuntu 22.04, Unity desktop.

> $ flatpak run org.flameshot.Flameshot 
Gtk-Message: 20:15:03.529: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:15:03.564: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:15:03.564: Failed to load module "canberra-gtk-module"
