### ISSUE TITLE
remember last region

### ISSUE THREAD

**Issue by sl5net** [flameshot-org/flameshot#2584]
### Feature Description

1.  start flameshot
2. draw region 
3. save
4. close flameshot
5. start flameshot (last region is already there)
6. save (with last region)

or maybe add cli:
`--region last`

**Comment by mmahmoudian** [comment]
Note that you can already do this using an environmental variable:

```sh
export FLAMESHOT_LAST_REGION=$(flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
```

it basically reads the last region from the variable, let you create the screenshot, get the new region (if you have changed it) and save it again on the same variable. It will select the region `100x100+100+100` if the `FLAMESHOT_LAST_REGION` variable is not defined. So I suggest to export the environmental variable to your environment when you boot your computer with whatever value you would like.

Alternatively you can modify the code to write into (and read from) a file for example in `~/.config/flameshot/last_region`.

**Comment by sl5net** [comment]
good i don't get a error using this:
```sh
> bash
$ export FLAMESHOT_LAST_REGION=$(flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
```

and how i could start it?

i tried 
```sh
flameshot gui --path /home/seeh/Pictures/captures/
```
but was region was not preselected. how could i start it correct then?

**Comment by mmahmoudian** [comment]
Use the updated version of Flameshot and just run what I suggested, you'll be fine.

Reading this would help you a lot of headaches:
https://flameshot.org/docs/installation/installation-linux/

**Comment by sl5net** [comment]
i mixed
```sh
flatpak run org.flameshot.Flameshot
```
+
```sh
 export FLAMESHOT_LAST_REGION=$(flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
 ```
=
```sh
export FLAMESHOT_LAST_REGION=$(flatpak run org.flameshot.Flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
```
it work one time.

now i get error if i use it again message:
```sh
export FLAMESHOT_LAST_REGION=$(flatpak run org.flameshot.Flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
QSettings::value: Empty key passed
QSettings::value: Empty key passed
flameshot: error: Invalid region, use 'WxH+X+Y' or 'all' or 'screen0/screen1/...'.
See flameshot --help.
```

**Comment by mmahmoudian** [comment]
I don't understand what has went wrong, perhaps you can check the value of the `FLAMESHOT_LAST_REGION` variable using `echo ${FLAMESHOT_LAST_REGION}` and see what has went wrong.

Just to make your life easier (instead of mixing the two commands), as explained [on our website](https://flameshot.org/docs/installation/installation-linux/#flatpak), you can create a symlink to the flatpak binary:

```sh
ln -s /var/lib/flatpak/exports/bin/org.flameshot.Flameshot ~/.local/bin/flameshot
```
