### ISSUE TITLE
--saveKey=enter

### ISSUE THREAD

**Issue by sl5net** [flameshot-org/flameshot#2585]
### Feature Description

a save key already works. its **Ctrl+C**

please add a posibility for config this hotkey or add a parameter when using CLI-mode:
`flameshot gui --path ~/Pictures/ --saveKey=enter`

**Comment by mmahmoudian** [comment]
Before everything, save key is **NOT** set to <kbd>Ctrl</kbd><kbd>c</kbd> by default, that is for **copy to clipboard**:

![image](https://user-images.githubusercontent.com/390889/166684012-82ce1d7f-61ae-4c20-aaef-d479ba1abb14.png)

Now, back to your issue. If I have understood your feature request correctly:

It seems you have not read about the [Final Actions](https://flameshot.org/docs/advanced/commandline-options/#final-actions). Please read that, but the gist of it is that when you are defining a final action through the CLI, e.g. `--path`, you cannot do anything other than "Accept" which is triggered by <kbd>Enter</kbd> by default, but you can customize that to your liking:

![image](https://user-images.githubusercontent.com/390889/166684762-22f709e9-94b4-4c63-b83a-9abcc45a5fba.png)


If the above does not address your concern, please elaborate more (much more) to help us understand what you are exactly after. Thank you.

**Comment by sl5net** [comment]
my configuration looks different:
![Screenshot_20220505_191645](https://user-images.githubusercontent.com/5634759/166977457-1c603997-7f84-4342-a02d-7e58b9614da6.png)
i found this configuration by doing this:
```sh
$ flameshot -h
Usage: flameshot [flameshot-options] [arguments]

Options:
  -h, --help     Displays this help
  -v, --version  Displays version information

Arguments:
  gui            Start a manual capture in GUI mode.
  screen         Capture a single screen.
  full           Capture the entire desktop.
  launcher       Open the capture launcher.
  config         Configure flameshot.
$ flameshot config
```
my Version (installed yesterday as ubuntu recomandet):
```sh
flameshot -v
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5
```

**Comment by mmahmoudian** [comment]
@sl5net you can see from your Flameshot version that it is released back in October 2019. We are now at version 11.0.0 and soon 12.0.0

And if I may suggest, use Flatpak as the snap might have some issues

**Comment by sl5net** [comment]
workaround for this old version:
```python
# Title: flameshot
# Class: flameshot.flameshot 
# Works for me if i use
# - Window Filter with Class-Name
# - Hotkey: <enter>
keyboard.send_keys("<ctrl>+s") 
```
