### ISSUE TITLE
dislocation when use two different resolving power screen

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [flameshot-org/flameshot#2586]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

 Manjaro Linux x86_64/5.17.1-3-MANJARO/Plasma 5.24.4

### Description

I have two screen(left 2560x1600 16x10 and right 1920x1080 16x9)
when excute flameshot, the screen will dislocation.(like the screencut below)
And even after I set two screen with  the same configuration(1920x1080 16x9)，there is still the same situation.

By the way，the default software SpacTecle work fine.

### Screenshots or screen recordings
full screen cut of left screen
![full screen cut of left screen](https://user-images.githubusercontent.com/59465493/166648368-4e2aa0a5-753d-40a5-9874-97c5b613d624.png)

### System Information
display configuration
![image](https://user-images.githubusercontent.com/59465493/166649396-0f078027-1f7a-4d08-b466-6bf7f1fa7bab.png)

**Comment by mmahmoudian** [comment]
Are you on Wayland or X11?

```sh
inxi --system --graphics --width=80
```

**Comment by mmahmoudian** [comment]
Also try the solutions provided here:

https://github.com/flameshot-org/flameshot/issues/1386#issuecomment-1088680394

**Comment by Hou-Xiaoxuan** [comment]
> 

Thanks, it solve my problem.
Use command `QT_SCREEN_SCALE_FACTORS="" flameshot gui` works for me.
