### ISSUE TITLE
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome in Ubuntu 22.04

### ISSUE THREAD

**Issue by JunPham** [flameshot-org/flameshot#2587]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04

### Description

Full error: 
   Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
   flameshot: error: Unable to capture screen
   flameshot: error: Unable to capture screen
My Ubuntu:
   Distributor ID:	Ubuntu
   Description:	Ubuntu 22.04 LTS
   Release:	22.04
   Codename:	jammy
Flameshot version:
   Flameshot v11.0.0 (11.0.0-2 Debian)
   Compiled with Qt 5.15.2

I can't turn on flameshot's gui. Although I can do it when I press Share, it's quite inconvenient

### Screenshots or screen recordings

![flameshot](https://user-images.githubusercontent.com/42670522/166709553-e655e730-5fac-4a1c-884f-6a1243c9fb5c.png)

### System Information

Gnome
![de](https://user-images.githubusercontent.com/42670522/166710707-8af5219e-69d6-4a62-892c-81fcc1e1f315.png)

**Comment by borgmanJeremy** [comment]
Is this isssue just stating you must hit share?

If so please search our issues, this has been report at least 50 times and it is 100% a gnome change and nothing to do with Flameshot.
