### ISSUE TITLE
Shortcut's could not set to Enter and removed shortcut Enter could not set back to default

### ISSUE THREAD

**Issue by sl5net** [flameshot-org/flameshot#2588]
### Flameshot Version

```
flatpak run org.flameshot.Flameshot -v
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.3
```

### Installation Type

Flatpak from Github

### Operating System type and version

kUbuntu Flameshot v11.0.0 (ad1bf28) Compiled with Qt 5.15.3 

### Description

i tried replace a shortcuts to **Enter** (**that not works**)
And i tried to set back **Accept the capture** to **Enter** (**that not works**)

And i tried to do this config in a config file 
and read https://flameshot.org/docs/advanced/configuration/
my ` ~/.config/flameshot/flameshot.ini.` is empty
( i don't know how to do by using this ini file. )

### Steps to reproduce
open config menu tab shortcuts and change
**Accept the capture** to **Ctrl+Enter** (that works)
**Save Screenshot to File** to **Enter** (**that not works**)
then i tried to set back
**Accept the capture** to **Enter** (**that not works**)

### System Information

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.13.0-40-generic
OS Type: 64-bit

**Comment by borgmanJeremy** [comment]
I cannot replicate this
