### ISSUE TITLE
Copy selected area to separate window for semi-persistent screenshots

### ISSUE THREAD

**Issue by ludberg** [flameshot-org/flameshot#2589]
### Feature Description

Please consider adding an option to move selected area to separate and movable window.

I often need to screenshot part of my work and then place it next to my work so I can continue working and compare my work against the previous screenshot. 

Today I either have to save the screenshot, find it on my computer, open it in my photo app to be able to place it next to my work, or I have to upload it to imgur from Flameshot so that I get the screenshot in a new window I can move around. 

I suggest adding an option to Flameshot to directly pop out the selected area to a new movable window. 

Example of an area poped out to a separate window (after using upload to imgur feature): https://i.imgur.com/77lzubL.png

**Comment by mmahmoudian** [comment]
Have you tried pinning the screenshot? This is exactly what you are asking for.

Start taking a screenshot, instead of uploading or saving, click on the pin 📌 icon

**Comment by ludberg** [comment]
This is to a large extent the feature I'm asking for... my bad

It would be great if
* the pinned window didn't always stayed on top of everything
* it was possible to resize the window/screenshot
* it was possible to save the screenshot

**Comment by mmahmoudian** [comment]
> it was possible to resize the window/screenshot

Changing the size of everything in Flameshot is bound to mouse scroll.

> it was possible to save the screenshot

If you want to save and the pin at the same time, use the `--pin` and `--path /the/file/you/want.png` at the same time in the command line 

> the pinned window didn't always stayed on top of everything

I don't think this would change. If you want it to act like a normal window, it is better to use some sort of image viewer like `pqiv`, `feh`, or `imv`

- https://archlinux.org/packages/community/x86_64/pqiv/
- https://archlinux.org/packages/community/x86_64/pqiv/
- https://archlinux.org/packages/community/x86_64/imv/

But just we can also ask the opinion of other devs about this ( @borgmanJeremy @veracioux )

**Comment by ludberg** [comment]
Zoom worked fined. That I didn't know. Thanks

I'm not using the command line but the 📌 icon to screenshot a selected area. After I've done that, can the screenshot be saved from the command line?

Normal window: 
That's the thing, I don't want to first save the screenshot and then open it in another app to have it next to my other work. It's not a convenient workflow. 

My suggestion is that the screenshot is, after pinned, be placed in a similar window like the one we get after using "Upload to imgur". That window is possible to resize and place behind other windows.

**Comment by mmahmoudian** [comment]
I suggest closing this issue as what you are asking for is easily achievable as I explained.
