### ISSUE TITLE
The text is cropped

### ISSUE THREAD

**Issue by Marusyk** [flameshot-org/flameshot#2591]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

Can't see my text "This is my text that will be cropped"

### Steps to reproduce

1. take a screen
2. add a text
3. type a few words
4. save 

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/9221694/167157383-8d119de2-cb54-46fb-b754-5e0f9ca9fa35.png)
![image](https://user-images.githubusercontent.com/9221694/167157842-98a8c418-91e8-455f-b846-94436a7dfd3d.png)

### System Information

1. Windows 10
2. Display
![image](https://user-images.githubusercontent.com/9221694/167349329-87127541-59d6-4d4b-a759-add6379fce63.png)
![image](https://user-images.githubusercontent.com/9221694/167349396-82206957-2b1b-4687-960a-f63ed14d66b8.png)

**Comment by Marusyk** [comment]
ping

**Comment by mmahmoudian** [comment]
@Marusyk  This is most probably the issue with fractional scaling (125%). No improvements have been made since your initial post. You don't need to bump the issue as it is already in the list. When we can check the reproducibility of this issue, we'll mark it as [![label: bug][~bug]](https://github.com/flameshot-org/flameshot/labels/Bug).

I'm going to hide your comment and this comment as neither of them add anything to this discussion.

[~bug]: https://img.shields.io/badge/-bug-f00.svg

**Comment by mmahmoudian** [comment]
@Marusyk why did you close this? Did gough managed to solve the issue?

**Comment by EmanuelAlexandru** [comment]
I'm having the same problem on windows 11. I just tried copping the text shown above and it gets cropped. I tried restarting my laptop without any luck. 4k60 with 2x scaling.
![2024-06-19_22-10](https://github.com/flameshot-org/flameshot/assets/22559586/c7dd914d-5e4e-42d0-94df-dbf4557e5133)

**Comment by mmahmoudian** [comment]
@EmanuelAlexandru what is your Flameshot version?

**Comment by EmanuelAlexandru** [comment]
> @EmanuelAlexandru what is your Flameshot version?

too late, I uninstalled it and immediately installed the latest version v12.1.0. The problem is fixed so far.

**Comment by mmahmoudian** [comment]
@EmanuelAlexandru Exactly my thought. You most probably had the older version. I'm glad it is working now. Enjoy
