### ISSUE TITLE
Flameshot only allows full screen shots and uploads instead of saving with ubuntu: 22.04

### ISSUE THREAD

**Issue by vogella** [flameshot-org/flameshot#2593]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ubuntu: 22.04

### Description

In older versions of Ubuntu and Flameshot I could make a screenshot, edit it and save it.

If I now make a screenshot it makes a screenshot of all my screens and allow me to share it.

![image](https://user-images.githubusercontent.com/139910/167370832-3081a011-6b95-4868-bf31-32aeff1b69b2.png)

Even if I select the option to select the screen area I do not have the option anymore to edit and save the file

![image](https://user-images.githubusercontent.com/139910/167371000-627977a6-4057-403a-8a55-a30c1ce274d0.png)

How can I configure the new version of flameshot to have again the option to save and edit the screenshot? Not that the above screenshots were not done with Flameshot, as I did not manage to use it.

### Steps to reproduce

Trying to use Flameshot like in older releases.

### System Information

ubuntu: 22.04 with default settings.

**Comment by vogella** [comment]
Ah, looks like the screen I see it a temp area for the screenshot. Afterwards I can use the regular tools to select and save. Can this in-between screen be skipped by configuration?

**Comment by vogella** [comment]
I'm getting used to this new workflow. Closing the issue, sorry for the noise

**Comment by mmahmoudian** [comment]
@vogella 
This is a Gnome issue, please read this to save your time:

https://flameshot.org/docs/guide/wayland-help/#gnome

If you are annoyed of this behavior of Gnome, I suggest using a better Desktop Environment (e.g KDE, Xfce, LXQt)
