### ISSUE TITLE
Flameshot just takes screenshot with no opportunity to select area or annotate in 22.04 ubuntu

### ISSUE THREAD

**Issue by geoffreymbrown** [flameshot-org/flameshot#2594]
### Flameshot Version

snappy edition

### Installation Type

Snap from Snapcraft

### Operating System type and version

Ubuntu 22.04

### Description

I've used flameshot alot with Ubuntu 20.04.  In that case, opening flameshot gives the opportunity to select a region and, after selecting, add graphic annotations.   In 22.04 the snap edition (and the current version with apt install) bypasses all that and just takes a full screenshot.  Once that happens, there's an opportunity to take a screenshot of a selected region but in neither case is there an opportunity to annotate the screen shot.

### Steps to reproduce

run flameshot gui

### System Information

Linux 22.04

**Comment by geoffreymbrown** [comment]
Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-27-generic
ubuntu: 22.04

**Comment by mmahmoudian** [comment]
when it "just takes screenshot with no opportunity to select area or annotate", does it show a window with a "Share" button on the top right corner? is it similar to this:

https://imgur.com/XxPbcYv

**Comment by geoffreymbrown** [comment]
Yes, it shows a window with a "Share" button.

**Comment by mmahmoudian** [comment]
@sahir-taib If this pop-up is the reason you have been writing in this thread, you have been wasting your time! That popup is Gnome's thing, it has nothing to do with Flameshot.

I have explained it many times in many different issues including but not limited to:

- #2563 
- #2560 
- https://github.com/flameshot-org/flameshot/issues/2296#issuecomment-1018261655
- #2186
- #2143

And if you want to read some the Gnome people's response on our repo:

- https://github.com/flameshot-org/flameshot/issues/2186#issuecomment-1001232452

⚠️  We have also explained it with all the details you might need on our website:

https://flameshot.org/docs/guide/wayland-help/#gnome

If you are annoyed, use a better Desktop Environment (e.g KDE, Xfce, LXQt)

**Comment by mmahmoudian** [comment]
@geoffreymbrown It might help you have a better experience in Gnome: Click the Share button so that Gnome let Flameshot have access to the screenshot, so that you can annotate and etc.

**Comment by geoffreymbrown** [comment]
Thanks for your help.  Yes, clicking the Share button gives me what I want.

**Comment by ruslanzelinskyy** [comment]
Solution I'm using (disable wayland and use xorg instead):

`sudo nano /etc/gdm3/custom.conf`
uncomment `WaylandEnable=false`
`sudo systemctl restart gdm3`

**Comment by jonathantito** [comment]
> Ubuntu 22.04 Solution I'm using (disable wayland and use xorg instead):
> 
> `sudo nano /etc/gdm3/custom.conf` uncomment `WaylandEnable=false` `sudo systemctl restart gdm3`
> 
> Also if logged in from rdp it works perfectly on guest os (Remmina)

It worked for me :) Thank you so much :)

**Comment by changuelsami** [comment]
@ruslanzelinskyy it worked but "Copy selection in clipboard" don't work any more :(

**Comment by mmahmoudian** [comment]
@changuelsami remember, this share button is Gnome thing and has nothing to do with Flameshot. The clipboard is a different issue that have been already reported.

**Comment by mrmohitrathod** [comment]
> Ubuntu 22.04 Solution I'm using (disable wayland and use xorg instead):
> 
> `sudo nano /etc/gdm3/custom.conf` uncomment `WaylandEnable=false` `sudo systemctl restart gdm3`
> 
> Also if logged in from rdp it works perfectly on guest os (Remmina)

It worked for me, Thanks 
you have relived a lot of stress :D
