### ISSUE TITLE
Fix Flameshot application window title

### ISSUE THREAD

**Issue by nathaneltitane** [flameshot-org/flameshot#2599]
### Flameshot Version

![2022-05-11_11-36](https://user-images.githubusercontent.com/5674757/167890192-43cd5a81-f01b-4cc6-8cd7-51b818958ece.png)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Kubuntu 22.10

### Description

Small little typo? should be Flameshot rather than flameshot on window title

![2022-05-11_11-35](https://user-images.githubusercontent.com/5674757/167890361-2c7181ce-39d8-41a6-8ba9-2d7b59272a78.png)

### Steps to reproduce

1 - right click on taskbar icon
2 - open launcher

### System Information

System:
  Host: Hades Kernel: 5.13.0-40-generic x86_64 bits: 64 
  Desktop: KDE Plasma 5.22.5 Distro: Ubuntu 21.10 (Impish Indri) 
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
  Device-2: AMD Polaris 22 XT [Radeon RX Vega M GH] driver: amdgpu v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: loaded: amdgpu,ati,modesetting 
  unloaded: fbdev,vesa resolution: 3840x2160~60Hz 
  OpenGL: renderer: AMD VEGAM (DRM 3.41.0 5.13.0-40-generic LLVM 12.0.1) 
  v: 4.6 Mesa 21.2.6

**Comment by borgmanJeremy** [comment]
This is fixed on the master branch  from the port to QtDesigner. 
![image](https://user-images.githubusercontent.com/46930769/171523307-bc761bb6-ae4d-4d7b-9f0d-43f7d98a3e0f.png)
