### ISSUE TITLE
I cancle screenshot but style svae whole screen screenshot to my ~/Pictures

### ISSUE THREAD

**Issue by qwert-f** [flameshot-org/flameshot#2600]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

fedora36

### Description

I run flameshot gui, but after that I don`t screenshot, I click cancle by mistake.after that I find a whole screen screenshot in my ~/Pictures dir. I also can`t open flameshot by click the desktop shotcut on my desktop.

### Steps to reproduce

run flameshot gui
click cancle

### Screenshots or screen recordings

https://user-images.githubusercontent.com/50124761/168026517-8504c5eb-0324-4ab3-8967-6f956ccd454f.mp4

### System Information

Linux fedora 5.17.6-300.fc36.x86_64 #1 SMP PREEMPT Mon May 9 15:47:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
The video you upload doesn't work, and you didn't provide the information about your system completely. What window manager and what display server are you using?

**Comment by qwert-f** [comment]
> The video you upload doesn't work, and you didn't provide the information about your system completely. What window manager and what display server are you using?

System:
  Host: fedora Kernel: 5.17.6-300.fc36.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 42.0 Distro: Fedora release 36 (Thirty Six)
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nouveau v: kernel
  Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision HD
    Integrated Webcam
    type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 22.0.3

upload this video because issues template have this item, so just ignore it

**Comment by qwert-f** [comment]
> The video you upload doesn't work, and you didn't provide the information about your system completely. What window manager and what display server are you using?

System:
  Host: fedora Kernel: 5.17.6-300.fc36.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 42.0 Distro: Fedora release 36 (Thirty Six)
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nouveau v: kernel
  Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision HD
    Integrated Webcam
    type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 22.0.3

upload this video because issues template have this item, so just ignore it

**Comment by vanheck** [comment]
Hi, thats no problem with Flameshot, but bug/feature of `xdg-desktop-portal-gnome` component. I've suggest the change https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/10
