### ISSUE TITLE
Gnome 42 + Wayland 

### ISSUE THREAD

**Issue by RandomnessRobin** [flameshot-org/flameshot#2601]
I'm not able to take a screenshot with flameshot on Wayland in Gnome 42. This happens on any distro I've tried that uses Wayland. 
## **This is what I get when I try to use flameshot**

![image](https://user-images.githubusercontent.com/35129955/168187467-57e2c55b-255b-42df-8c5d-db9487b4ea99.png)

### **Note:**
 When I click on **Share**, it then allows me to use flameshot. The keyboard shortcuts like **Ctrl** + **S** or **Ctrl** + **C** do not work. 

Not sure if it did already get mentioned. Hope this helps with that case if it did.

### **Distro:** 
Fedora 36

**Comment by borgmanJeremy** [comment]
Duplicate issue. On mobile so don't have the link handy
