### ISSUE TITLE
Can't screen anything on Wayland KDE

### ISSUE THREAD

**Issue by JasmineCA** [flameshot-org/flameshot#2604]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
linux: 5.13.0-40-generic
org.kde.Platform: 5.15-21.08

### Installation Type

Flatpak from Flathub

### Operating System type and version

KDE Neon based on Ubuntu 20.04

### Description

On Wayland, when I select "Open the launcher", I have nothing in the screen preview. If I try to take a screenshot, nothing happens. The window closes. I attached a screen of the said window (sorry it's in French)
![image](https://user-images.githubusercontent.com/44299370/168323908-c3197402-553d-4d08-93ee-c541f6b19e02.png)
In X11 everything works as expected. The screen preview shows my screen and when I click the button to capture my screen, I have the flameshot gui opens. 

### Steps to reproduce

1. Opens flameshot to have it in the system tray (if it's not already started)
2. Right click on the flameshot icon
3. Click "Open the Launcher"
4. See nothing in the screen preview.
5. Click on the capture button and watch the window closes itself

### System Information

OS: KDE Neon 5.24 (based on (K)Ubuntu)
Monitor: 1920x1080
Desktop Environment: KDE Plasma with Wayland

**Comment by borgmanJeremy** [comment]
Have you install xdg-desktop-portal-kde and xdg-desktop-portal?

**Comment by JasmineCA** [comment]
xdg-desktop-portal and xdg-desktop-portal-kde were already installed automatically

**Comment by yswtrue** [comment]
Same problem here

**Comment by JasmineCA** [comment]
Yes that's normal, by the time the bug has been resolved, probably by a package update related to Wayland

**Comment by mmahmoudian** [comment]
> Yes that's normal, by the time the bug has been resolved, probably by a package update related to Wayland

Ok thanks, I will close this issue then
