### ISSUE TITLE
"Launch at startup" / Autostart doesn't work on Windows

### ISSUE THREAD

**Issue by krokofant** [flameshot-org/flameshot#2605]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.22000
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Setting the application to autostart doesn't work. This has been reported by two other people on an old closed issue https://github.com/flameshot-org/flameshot/issues/1379 for version 11.

Workaround:
Paste a flameshot shortcut into the folder `shell:startup`

### Steps to reproduce

1. Install flameshot
2. Restart machine
3. Flameshot is not started

### System Information

Windows 11
Version 21H2, Build 22000.613

**Comment by csijake** [comment]
Duplicate of #2422?

**Comment by mmahmoudian** [comment]
@csijake Thanks for tagging the correct issue. Much appreciated.
