### ISSUE TITLE
Save to specific file

### ISSUE THREAD

**Issue by nkh** [flameshot-org/flameshot#2607]
### Feature Description

tested the "-p path" option and FS saves "screenshotxxxxxx" in the path as expected

FS -p path/file.png doesn't work, this forces one to jump through loops to rename screenshotxxxxx to file.png

Could the -p option also take a filename?

**Comment by mmahmoudian** [comment]
This should work by default:

![image](https://user-images.githubusercontent.com/390889/168584734-35957d83-7d77-403c-a330-effd358916d7.png)

If you have the latest version, and still it does not work, please file [a bug report](https://github.com/flameshot-org/flameshot/issues/new?assignees=&labels=Unconfirmed+Bug&template=bug-report.yaml).

**Comment by nkh** [comment]
flameshot gui -p /tmp/a.png
Invalid path, it must be a real path in the system. See 'flameshot --help'.

**Comment by nkh** [comment]
there is definitely a /tmp directory, there's even a lot of other files in it.

~/a.png does't work either and gives the same error message

**Comment by mmahmoudian** [comment]
What shell are you using (e.g bash, zsh, ksh, csh, fish, nu)?

What error do you get when running this command: `echo "aaa" > /tmp/a.txt`

**Comment by nkh** [comment]
I'm using Bash 5.0.17, and flameshot 0.6.0 compiled with QT 5.12.5

I develop on my machine every day, no other application has complained about paths (including mine).

let me know if you want me to run something a bit more complicated, other versions of FS, or if there's some debug flag and logs you want to get.

Cheers, Nadim.

**Comment by mmahmoudian** [comment]
Seems you are using a Flameshot version that is around 4 years old. We are at version 11.0.0 now. Please consider upgrading.
