### ISSUE TITLE
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' flameshot: error: Unable to connect via DBus

### ISSUE THREAD

**Issue by Imbored2457** [flameshot-org/flameshot#2608]
Hello,
i am getting this error when trying to copy my screenshot.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' flameshot: error: Unable to connect via DBus
I am running this on a linux system
Pop_OS!

**Comment by mmahmoudian** [comment]
I marked this two days ago to get back to this with a fresh and calm mind, but again to the save vibe after reading it again. I will close this as you did not provide enough information:
- Operating system version
- Flameshot version
- how have you installed Flameshot
- how you are running Flameshot that you are getting this error

**Comment by mlwdofc** [comment]
I get the same error, although Flameshot runs successfully.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
flameshot: error: Unable to connect via DBus

OS:  Linux Mint 21 (vanessa)
Flameshot Version:  12.1.0
Install Method:  compiled from source (followed https://github.com/flameshot-org/flameshot#installation)
Run Method:  ./flameshot

**Comment by emoxam** [comment]
any news ?

**Comment by emoxam** [comment]
@mmahmoudian I did. Is it ok ?
https://github.com/flameshot-org/flameshot/issues/3544

**Comment by mmahmoudian** [comment]
> I did. Is it ok ?
> https://github.com/flameshot-org/flameshot/issues/3544

Thanks. I modified your post to have better markdown formatting. Thanks for providing all info.

**Comment by poochat** [comment]
Solutions and operating procedures：https://blog.csdn.net/weixin_41194129/article/details/120399123
