### ISSUE TITLE
Autosave using folders in the filename

### ISSUE THREAD

**Issue by saulob** [flameshot-org/flameshot#2613]
### Feature Description

I would like to be able to create folders on autosave, using the filename variables

Something like this: a folder with a year and month

![image](https://user-images.githubusercontent.com/3660977/169438193-e9533e53-882c-49d6-8c4c-b12c15fe50bc.png)

**Comment by borgmanJeremy** [comment]
In my opinion folder creation should be delegated to the shell not flameshot. But I'd like to hear from @mmahmoudian too.

**Comment by mmahmoudian** [comment]
@borgmanJeremy the reason I didn't respond to this yesterday was that I felt the same as you, but I can also see some merit in this feature as well. So having mixed feelings here 😅

I think @hosiet and @veracioux would also think the same way as this is something that should be handled elsewhere.

**Comment by saulob** [comment]
I got used to this functionality in Greenshot, I miss it :(

**Comment by saulob** [comment]
> In my opinion folder creation should be delegated to the shell not flameshot. But I'd like to hear from @mmahmoudian too.

How can I do that in Windows? My shell... It would be easier if the program did that

**Comment by veracioux** [comment]
I agree that folder creation should be handled explicitly (by the user) instead of implicitly (by flameshot) in general. But I think the benefit from being able to specify a directory tree dynamically (e.g. `%Y/%m/...`) outweighs the downside which is kinda philosophical anyway.

**Comment by saulob** [comment]
Yeah, think about doing that manually in Windows. Every month, creating a new numeric folder (06, 07, 08...), then going into Flameshot and choosing the new patch

**Comment by mmahmoudian** [comment]
@saulob you don't need to do that manually. Even on Windows you can use command line to create folders automatically. The only difference is that I don't know how you should run your command periodically

**Comment by saulob** [comment]
> @saulob you don't need to do that manually. Even on Windows you can use command line to create folders automatically. The only difference is that I don't know how you should run your command periodically

If the option existed in flameshot I wouldn't need to do anything in windows and I wouldn't even need to know shell commands for it...

See how simple it is in Greenshot, you don't have to do anything else, just use \ and that's it, see the "help screen" of it

![image](https://user-images.githubusercontent.com/3660977/169668876-88094089-8d65-430e-9809-1213f7c15bd0.png)

**Comment by mmahmoudian** [comment]
@saulob 
This is getting slightly off-topic, but this is the classic apples and oranges comparison ([U+1F34E](https://emojipedia.org/emoji/%F0%9F%8D%8E/) `!=` [U+1F34A](https://emojipedia.org/emoji/%F0%9F%8D%8A/)). You are comparing a windows-only FOSS tool with a cross-platform FOSS tool that was primarily designed for Linux. Flamehot is not a clone of Greenshot, and Greenshot is not a clone of Flameshot.  The core idea of Flameshot is not to provide file management tools, but rather a convenient way to screenshot and annotate them.

All these said, as I mentioned before, **I do see some merit into this feature request** as it is relatively common that people organize their screenshots in folders and the date information is something that we already are getting from the system. What I suggested to you about scripting is that you can have that feature almost immediately compared to waiting for the faith of this feature request is decided and this feature is implemented. I tried to be helpful towards solving your problem for the moment.

Considering that this comment of mine (at least in my mind) is off topic, I'm going to hide it to keep this thread clean. I'll do the same to yours too as it does not add extra information or perspective to this feature request as you practically just stated the obvious 😉

**Comment by xstable** [comment]
I think it should be handled by flameshot. 
The reason is written in this issue #2674 and in short words... it simplify a lot if you work with "auto erased directories at reboot"

**Comment by mmahmoudian** [comment]
@xstable 
> The reason is written in this issue https://github.com/flameshot-org/flameshot/issues/2674 and in short words... it simplify a lot if you work with "auto erased directories at reboot"
> To archive this currently, I need to use an own script, which does this (like described in the above issue).
And that makes the save to file of flameshot totally useless to me.


one should never store anything permanently in `/tmp/`. That's the design of Linux folder structure. You should move your screenshot folder to something like `~/tmp/` if you want to keep them

**Comment by bgoewert** [comment]
It would be helpful for newbies like me to have this feature. But at the same time it forces you to learn. By taking ~30 mins to dig around, I found the `inotifywait` utility could watch the screenshots folder and help in creating date organized sub-folders.

For any other newbies looking for the same thing, this may help get you started:
https://gist.github.com/bgoewert/6d49acec4d14085e995d96fee74b7dd1
