### ISSUE TITLE
Counting functionality

### ISSUE THREAD

**Issue by jdm-arc-99** [flameshot-org/flameshot#2620]
### Feature Description

Hello everyone,
Have yet to find this functionality. 

When using the number feature how do you delete the previous when trying to count up? 
Like starting from 3 or 4
Being able to edit 
![image](https://user-images.githubusercontent.com/87446164/169705086-50c98f66-65d4-442f-b837-540a49045670.png)

Please point me in the correct direction. 
If I want to start from 2 then how do I get rid of 1

Thanks,
Jonathan

**Comment by borgmanJeremy** [comment]
This is not currently possible. Someone tried to add this feature a while back and it broke the undo/redo and the layer reordering.  Open to a PR that adds this, but it needs to be carefully discussed how to implement it without breaking other features.

**Comment by mmahmoudian** [comment]
> how do you delete the previous 

you can de-select the active tool, and then select the one you want to delete. But this would reset the counting. Basically you can think of it as layers and when you delete a layer, the second one become the first. You can press <kbd>Space</kbd> to open the side bar and see the layers.

> Like starting from 3 or 4

This is not possible in the way you are thinking, but very easily achievable: 
![image](https://user-images.githubusercontent.com/390889/169707239-ea378ec0-16d8-4b30-8f62-f745a422baf8.png)

**Comment by mmahmoudian** [comment]
@borgmanJeremy As far as I remember, @thepurple was conceptually against the idea. I don't have a strong opinion on this, but considering that with the current implementation it is very easy to achieve this effect, I don't think changing it would bring so much on the table. Kinda reminds me of the famous phrase "if it works don't touch it".

**Comment by thepurple** [comment]
@mmahmoudian thanks for mentioning me in your message. Unfortunately I don't have enough time and energy to follow what is new here. 
I was against it, because usually it is used like numbering the steps or something like that. 
I'm not against some new options, but by default feature should work as before. Most of the users like new features and hate when the default behavior changes.
As for me, I like you proposition with some numbers outside of the screenshot are. I don't think that this feature is really important for the everyday use.

**Comment by LevitatingBusinessMan** [comment]
For me the numbers button is completely missing?

I am on `0.6.0+git20191001-2`

**Comment by mmahmoudian** [comment]
@LevitatingBusinessMan Flameshot latest version is 12.1.0 and as you can imagine, your Flameshot version is from 2018. Please consider updating to latest version:
https://github.com/flameshot-org/flameshot/releases/latest

**Comment by LevitatingBusinessMan** [comment]
@mmahmoudian Thanks, I realized just after I made my comment. I had upgraded my version of flameshot, but I am using a Bedrock Linux system and it was still using the version installed by a different distribution.
