### ISSUE TITLE
Consider adding number bubble pointers

### ISSUE THREAD

**Issue by dsirov** [flameshot-org/flameshot#2623]
### Feature Description

I think it could be great if, in addition to regular number bubbles, we could have pointing number bubbles.
Example:
![image](https://user-images.githubusercontent.com/25965216/170062920-f0f804b4-0cf2-438c-9ab5-6346ee5ec859.png)
![image](https://user-images.githubusercontent.com/25965216/170063022-03a5519c-33cb-46a4-ab34-62a87f5feef3.png)

I should be made possible to modify the pointing arrow:
![image](https://user-images.githubusercontent.com/25965216/170062701-8aa8be04-56ec-4943-861e-685ea0967a4c.png)

Keep doing great job!

[Idea taken from [ksnip](https://github.com/ksnip/ksnip)]

**Comment by mmahmoudian** [comment]
Considering this can be easily achieved with the combination of bobbles and arrows, I don't really see the point:

![image](https://user-images.githubusercontent.com/390889/170261745-ac367f92-54ee-4101-a378-ca6689b201c1.png)

Let's see what other devs think about this.

**Comment by borgmanJeremy** [comment]
@mmahmoudian I do the same thing as you with the arrows.

However, for silly technical reasons the number tool inherits from the "AbstractTwoPointTool". This is the same parent class that draws lines and rectangles. We just ignore the mouse release on the number tool.

Therefore it would be pretty straightforward to implement this feature by using the ignored second click to draw the triangle. Also if a user does not not want the new behavior they can just click once with no drag.

**Comment by mmahmoudian** [comment]
@borgmanJeremy is it feasible to have a prototype to test it? I'm not opposing this behavior you mentioned, but I wonder how annoying it will be if the person click duration is a bit longer. I just don't want to break a currently working tool.

**Comment by vozdeckyl** [comment]
Hi @mmahmoudian @borgmanJeremy,
Can I can try to implement this, so we can see how annoying it is?

**Comment by mmahmoudian** [comment]
@vozdeckyl 
Considering [the comment Jeremy wrote in the thread](https://github.com/flameshot-org/flameshot/issues/2511#issuecomment-1138953339), I'll assigned this to you

**Comment by borgmanJeremy** [comment]
Yes please. Thanks for the help

**Comment by vozdeckyl** [comment]
Hi @mmahmoudian, @borgmanJeremy,
I've got this implemented in my [dev branch](https://github.com/flameshot-org/flameshot/compare/master...vozdeckyl:dev-bubble-pointers). You can have a look and test it out. Let me know what you think. Also, should I create a pull request? Thanks.

**Comment by mmahmoudian** [comment]
@vozdeckyl
Great work, thanks! It didn't compile on my computer though. I created a PR to that branch of your fork (https://github.com/vozdeckyl/flameshot/pull/1)

Also, is it possible to have the tip a bit narrower? This imo is not "pointy" enough 😅 

![image](https://user-images.githubusercontent.com/390889/171352579-338d720e-31a4-440b-ae60-a53a47831a70.png)

**Comment by borgmanJeremy** [comment]
@vozdeckyl also feel free to submit a PR here to run it against our CI.

**Comment by vozdeckyl** [comment]
Hi @mmahmoudian,
well-spotted. Obviouly this was not my intention and it is easily fixed by setting the size of the pen to 0.
![pointers](https://user-images.githubusercontent.com/55758629/171482416-3a38c110-f9c4-4f47-87c6-839aa0150c09.png)
Is this pointy enough for you? :)

**Comment by borgmanJeremy** [comment]
Added by @vozdeckyl  in #2638
