### ISSUE TITLE
Add and option to run flameshot with delay

### ISSUE THREAD

**Issue by sirio81** [flameshot-org/flameshot#2625]
### Feature Description

Hi, some time I have to take a snapshot of a menu.
When clicking "prt scr" flameshot does take a snapshot but just before it the focus on the menu get lost, so the menu is not visible in the screen shot.
I have then to open the luncher, set a delay and repeat the screenshot.
I'd like to have a shortcut to run flameshot with a default delay.
Honestly I don't know exactly hot to achieve that.
On kde I can creare a shortcut that run flameshot but I can't edit the command e.g. "flameshot --delay 4".
Any idea?

**Comment by mmahmoudian** [comment]
This is very much possible already. You can use `flameshot gui --delay 2000` to delay 2000 milliseconds. Alternatively you can use the `sleep` command on Linux: `sleep 2s && flameshot gui`
