### ISSUE TITLE
Use xdg-desktop-portal-gtk provided file-chooser dialog

### ISSUE THREAD

**Issue by hissssst** [flameshot-org/flameshot#2628]
### Feature Description

subj

**Comment by hissssst** [comment]
Sure, right now flameshot uses custom filechooser dialog. However, flameshot also uses xdg-desktop-portal protocol to make screenshots (to copy the screen to be more precise). It would make sense to use a file-chooser provided with this protocol, to be more consistent with the enviroment

**Comment by hissssst** [comment]
Yeah, sometimes you need to write code to get things working. If you want, I can create a PR and maintain it for a while

**Comment by hissssst** [comment]
The xdg one is integrated into deskop, has bookmarks, recent files and stuff. The QT one has almost no features and differs in keybindings (for example, I can't hit Return to save a file).

Qt one works, but it is not the best user experience there. And since portal is used, it'd be nice to have at least an option like `file-picker = auto|xdg|qt`

![scrot_220527001700](https://user-images.githubusercontent.com/37012324/170572871-4c95ba4a-c6a3-49a9-91b2-2391dd443271.png)

**Comment by borgmanJeremy** [comment]
This is only because you are using sway. We use the native file dialog box. If you use gnome you get the GTK dialog box, if you use Qt, you get a Qt dialog box.

**Comment by amitnovick** [comment]
This issue still exists and impacts me on my LM 21 XFCE.

The following images is the one used by Flameshot which I installed through APT as per the installation instructions for Ubuntu-based systems.

![flameshot-screenshot-file-browser](https://github.com/flameshot-org/flameshot/assets/43674238/8556384d-5991-4c79-8320-ce151653be95)

My system's native file browser is Thunar, and all of my favorite folders on the filesystem are available to me on all programs that call for it (through xdg), however none of them are available through this custom file dialog.

Please support the native file browser to make this program more usable for Linux users. The non-native file browse dialog is the biggest reason I stopped using Flameshot, even though it has some better functionalities than other tools. This is a big one for me.

You don't owe me anything and I still benefited from using it for a while, so thanks for your work in any case! :)

**Comment by edu-flores** [comment]
> ![flameshot-screenshot-file-browser](https://private-user-images.githubusercontent.com/43674238/251855455-8556384d-5991-4c79-8320-ce151653be95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODk3NzAsIm5iZiI6MTcyODE4OTQ3MCwicGF0aCI6Ii80MzY3NDIzOC8yNTE4NTU0NTUtODU1NjM4NGQtNTk5MS00Yzc5LTgzMjAtY2UxNTE2NTNiZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA0Mzc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTQ3MjM1OWRlMzEyZWJhOTgzYjFiYWQ1MzhiYzY4NmI4ZGZkMDcxNGQ3NTE5MDQwMWEwMmQzN2M4OTA1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3rQ08PacdvTkDSSr4LiOiv39f0_eDZAGczSoMWglW2E)

Mine also looks like this instead of opening the gtk dialog, and my mimeapps.list is in order :disappointed:
