### ISSUE TITLE
flameshot uses 100% cpu whilst repeating keys is enabled

### ISSUE THREAD

**Issue by Foriki** [flameshot-org/flameshot#2632]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

User repository (AUR)

### Operating System type and version

linux-arch

### Description

if you have repeating keys enabled and you hold down the flameshot button it spikes the cpu power

### Steps to reproduce

1. enable repeating keys
2. take a screenshot
3. hold down the screenshot key
4. discard the screenshot
5. check the cpu usage right after the screenshot

### System Information

X11

 0: +*HDMI-0 1920/477x1080/268+1920+0  HDMI-0
 1: +DVI-I-1 1920/477x1080/268+0+0  DVI-I-1

Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 16384 x 16384
DVI-I-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94  
HDMI-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  59.94  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x480       59.94    59.94  
   640x480       75.00    72.81    59.94  

00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)

Linux allah 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux

**Comment by borgmanJeremy** [comment]
I'm not seeing why this is an issue? You are essentially calling into flameshot as fast as your keyboard is sending the signal. This could be calling out to us hundreds of times a second.

**Comment by Foriki** [comment]
what how is it not? it should only open 1 instance of its self it shouldn't keep calling itself, I think there should be a check to see if its already opened or not, and if it already has one then mb prob some sort of kde configuring issue

**Comment by borgmanJeremy** [comment]
**It does** [check if there is an instance already running](https://github.com/flameshot-org/flameshot/blob/1b97fb51e4c44f6cb90dde6eda4cdc0527795daf/src/main.cpp#L341). 

However you PC still has to do work to get to that check (ie do all the setup code). That setup code takes time / CPU. Just don't hold the key down.
