### ISSUE TITLE
Active Tool Size slider not working

### ISSUE THREAD

**Issue by rexelbartolome** [flameshot-org/flameshot#2643]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

Manually moving the slider in the Active Tool Size doesn't work. Though it works if you use the scroll wheel.

### Steps to reproduce

1. run flameshot by clicking the tray
2. select a region
3. select any tool
4. change the size of the selected tool by manually dragging the Active Tool Size slider
5. change in size doesn't work

### Screenshots or screen recordings

https://user-images.githubusercontent.com/88552647/171752725-178464d3-9541-4c7c-aaac-ae4c0d96941d.mp4

### System Information

![image](https://user-images.githubusercontent.com/88552647/171753038-3ca2c7e0-a18c-4ec4-8b9d-43eb281a316d.png)

Not sure I understand the monitor configuration but this is what I understood
![image](https://user-images.githubusercontent.com/88552647/171753105-be8da005-e10f-4111-8136-27b50c1c4c26.png)

**Comment by borgmanJeremy** [comment]
Thanks for reporting. This has already been fixed on the main branch #2530 and will be in the next release (date unknown).
