### ISSUE TITLE
Share this screenshot with the requesting application?

### ISSUE THREAD

**Issue by Zetvue** [flameshot-org/flameshot#2646]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.17.11-300.fc36.x86_64
fedora: 36

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 36, Wayland on GNOME

### Description

GNOME keeps asking if I should share the SS with Flameshot

### Steps to reproduce

1. run `flameshot gui`

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/87939327/172032594-fc11796f-8fd9-4bb5-a9a2-e0c12a40f2e5.png)

https://user-images.githubusercontent.com/87939327/172032734-57461567-ca2f-4ef7-9302-c8c3e02097d1.mp4

### System Information

Fedora 36
GNOME Shell
Wayland

**Comment by Zetvue** [comment]
Whoops! Searched on issues, this is a GNOME thing. Sorry!

**Comment by mmahmoudian** [comment]
@Zetvue Thanks for closing this. You have been the **only one** so far since the release of Gnome41 that has searched and closed their duplicated issue regardingthis gnome behavior. Thank you.
