### ISSUE TITLE
Copy to clipboard doesn't work in 11.0.0 version on Windows

### ISSUE THREAD

**Issue by DDamianoff** [flameshot-org/flameshot#2650]
### Flameshot Version

11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

WIndows 10 Pro 64bit  Build 19044.1706

### Description

As the title says, just doesn't copy the image to the clipboard.
I tried reinstalling the app and same thing.

I just downgraded to the version `0.10.2-win64` and now works fine.

### Steps to reproduce

1. start the app.
2. Select an area.
3. Press Ctrl+C.
4. Try to paste it in somewhere (nothing happens).

### System Information

Device name	JW2
Processor	AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G    3.30 GHz
Installed RAM	8,00 GB (6,96 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	21H2
Installed on	‎5/‎5/‎2022
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Edit:** Corrected "previous version" number.

**Comment by borgmanJeremy** [comment]
Can you post your config file and clarify if you installed with the .msi or are running the portable vesion?

It works on my test windows 11 box.

**Comment by DDamianoff** [comment]
> Can you clarify if you installed with the .msi or are running the portable vesion?
msi version.

> Can you post your config file?
Sure! Where can I find it?

**Comment by borgmanJeremy** [comment]
Sure: 
```
C:\Users\Jeremy\AppData\Roaming\flameshot\flameshot.ini
```

**Comment by Alaskra** [comment]
> Same bug here... [flameshot.zip](https://github.com/flameshot-org/flameshot/files/8878057/flameshot.zip)

the content of the file `flameshot.ini`:

> [Shortcuts]
> TYPE_PENCIL=P
> TYPE_DRAWER=D
> TYPE_ARROW=A
> TYPE_SELECTION=S
> TYPE_RECTANGLE=R
> TYPE_CIRCLE=C
> TYPE_MARKER=M
> TYPE_TEXT=T
> TYPE_PIXELATE=B
> TYPE_CIRCLECOUNT=
> TYPE_SELECTIONINDICATOR=
> TYPE_MOVESELECTION=Ctrl+M
> TYPE_UNDO=Ctrl+Z
> TYPE_REDO=Ctrl+Shift+Z
> TYPE_COPY=Ctrl+C
> TYPE_SAVE=Ctrl+S
> TYPE_EXIT=Ctrl+Q
> TYPE_PIN=
> TYPE_TOGGLE_PANEL=Space
> TYPE_RESIZE_LEFT=Shift+Left
> TYPE_RESIZE_RIGHT=Shift+Right
> TYPE_RESIZE_UP=Shift+Up
> TYPE_RESIZE_DOWN=Shift+Down
> TYPE_SELECT_ALL=Ctrl+A
> TYPE_MOVE_LEFT=Left
> TYPE_MOVE_RIGHT=Right
> TYPE_MOVE_UP=Up
> TYPE_MOVE_DOWN=Down
> TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
> TYPE_DELETE_CURRENT_TOOL=Del
> 
> [General]
> copyPathAfterSave=false
> showStartupLaunchMessage=false
> uploadWithoutConfirmation=true
> useJpgForClipboard=true

**Comment by Alaskra** [comment]
The problem is cause by this line:
> useJpgForClipboard=true
If delete it, copy to clipboard can work.

**Comment by demonlibra** [comment]
Have the same problem if run flameshot by command _./flameshot gui_
If run by _./flameshot_ and click to flameshot icon in systray, copy to clipboard working fine.

Checked with flameshot 12.0 and 12.1
OS: LiniuxMint 20.3
