### ISSUE TITLE
Update the clipboard automatically on change (without Ctrl+C)

### ISSUE THREAD

**Issue by ding-dang-do** [flameshot-org/flameshot#2652]
### Feature Description

The old Microsoft snippet tool has one feature, that I really miss in flameshot. You don't need to use _Copy+C_ to copy a picture into your clipboard, because every change you do, updates the clipboard automatically.

Please add an option to enable this in flameshot.

Greets ddd 8)

**Comment by mmahmoudian** [comment]
This option is there if you are on Linux. You can use `flameshot gui --clipboard` to automatically send the screenshot to clipboard. You can also add more Final Actions to the mix. You can read more about them in the following link:

https://flameshot.org/docs/advanced/commandline-options/

If you are on Windows, the CommandLine support is not implemented yet for Windows, you can follow the discussion and progress in #2118

If these were not addressing your feature request, feel free to re-open this thread and add more description to clarify what you are after. Thanks.
