### ISSUE TITLE
Free-hand draw with the Marker tool

### ISSUE THREAD

**Issue by ding-dang-do** [flameshot-org/flameshot#2653]
### Feature Description

In flameshot you can mark something only in a straight line. Please add the possibility to mark arbitrary, like the pencil does, but with transparency.
~~Btw. It would be nice, when the level of transparency would be adjustable. The workaround to mark something a few times is not optimal.~~

Arbitrary marks in Windows snippet tool:
![textmarker_snippet_tool](https://user-images.githubusercontent.com/33965659/172808074-3fe51235-c722-49a6-985d-03243959ced9.png)

**Comment by mmahmoudian** [comment]
Duplicate #249.

**Comment by mmahmoudian** [comment]
So shall we close this issue?
