### ISSUE TITLE
flameshot full -c : gets stuck

### ISSUE THREAD

**Issue by Creator54** [flameshot-org/flameshot#2654]
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Compiled from source

### Operating System type and version

NixOS 21.05

### Description

[
![2022-06-10_16-00](https://user-images.githubusercontent.com/34543609/173050893-83d00245-8abd-48e3-bd75-c04aad84d5b4.png)
](url)

### Steps to reproduce

flameshot full -c

### System Information

 - wm: `dwm`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.13-xanmod1-cacule, NixOS, 21.05.3208.8dd8bd8be74 (Okapi), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-22.05.615.11e805f9935"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mmahmoudian** [comment]
Have you read this?

https://flameshot.org/docs/guide/troubleshooting/

**Comment by Creator54** [comment]
> Have you read this?
> 
> https://flameshot.org/docs/guide/troubleshooting/

thanks, i still can't get it working !
does it has to do something with my notification manager as it does seem to have some issues but notifications still work.

![2022-06-12_02-01_2](https://user-images.githubusercontent.com/34543609/173203945-8c047cf5-0891-4b31-93e2-1321338aadcc.png)

**Comment by Creator54** [comment]
> > does it has to do something with my notification manager as it does seem to have some issues but notifications still work.
> 
> I don't know. This is weird that dunst failed to load but you still have some notification! Can it be that you have other notification manager installed? kill all process of dunst and try `notify-send` again to check this.
> 
> But now I have one more question: WHY do you get list of files every time you run Flameshot any commands?!
> 
> ![image](https://user-images.githubusercontent.com/390889/173555423-03bb3fc8-0ed4-4484-a15b-178f9654af5f.png)

if i disable dunst then, i don't have notifications/notify-send(installed via libnotify pkg) doesn't work
[https://sharedby.creator54.me/files/2022-06-14_16-05.png](url) (adding screenshot to github was giving errors )

about the list of files getting printed , it is due to a shell theme i made for personal use has few features , doing ls -la on each repaint if the if it has space [https://github.com/Creator54/mzish](url)

**Comment by borgmanJeremy** [comment]
I suspect this has something to do with your setup. It seems like a majority of the issue are reported by users using a minimal window manager or custom setup. 

If you are at all a c++ dev I recommend compiling from source and attaching a debugger to see where the program is stuck.

**Comment by Creator54** [comment]
> I suspect this has something to do with your setup. It seems like a majority of the issue are reported by users using a minimal window manager or custom setup.
> 
> If you are at all a c++ dev I recommend compiling from source and attaching a debugger to see where the program is stuck.

So i did compile from source with all dependencies that i thought were needed/faced errors about (https://github.com/Creator54/flameshot/commit/f050918ab3803ba18623bdc90d881b5ef495bc66) .
After compiling I don't see it stuck  but it does'nt seem to copy to clipboard.
> for people unfamiliar with:
shell.nix: lets user create virtual env. for any project
direnv/.envrc : here loads the deps. defined via shell.nix on cd'ing into project.

![test](https://user-images.githubusercontent.com/34543609/176995249-9576860f-4fa7-4ce5-961c-17bd97ff0a29.gif)

**Comment by Creator54** [comment]
nvm got it working now. though I don't get what was the issue earlier 😅.
