### ISSUE TITLE
Allow opt-out for double left click as a shortcut

### ISSUE THREAD

**Issue by ding-dang-do** [flameshot-org/flameshot#2655]
### Feature Description

I would like to take up @[elad2109](https://github.com/elad2109)'s idea #2558 and create the corresponding feature request. Below I have just copied his suggestion. I absolutely agree with his idea.

![](https://user-images.githubusercontent.com/1093841/164948698-2ef77f8b-d72e-4ac5-9b14-23d755859660.png)
Often times my non-sensitive mouse makes an unplanned left double click which exits from the edit screenshot window.
Please allow to disable this shortcut.

**Comment by borgmanJeremy** [comment]
Yes please do!. I plan to get a beta out this weekend but I can wait a few days if you think it will be done soon. Hit me up here or on the [matrix channel](https://matrix.to/#/!AYbNXDGTDwApLwzkNg:feneas.org?via=kde.org&via=matrix.org) if you have questions or want help implementing it.

**Comment by mmahmoudian** [comment]
This is implemented (screenshot below). Shall we close this?

![image](https://user-images.githubusercontent.com/390889/185634973-424016a9-c9d4-4f19-9eea-7686b1237f5e.png)

**Comment by JeanBaptistePelliccia** [comment]
Hello,

I would also like to disable it but it seems that in the general settings the option "Copy on double click" is no longer present for me..

I am on Xfce and I use the following version of flameshote:
Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

Help me please.

**Comment by JeanBaptistePelliccia** [comment]
Yes it worked, thanks !
