### ISSUE TITLE
flameshot with path option not able to copy to clipboard

### ISSUE THREAD

**Issue by Heusini** [flameshot-org/flameshot#2665]
### Flameshot Version

**Versions tested:**
Compiled from source:
Flameshot v12.0.0 (6f6a8dde)
Compiled with Qt 5.15.4

Arch pacman install:
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3

### Installation Type

Compiled from source

### Operating System type and version

Arch

### Description

**Problem:**
Cannot copy to clipboard if the 'path' option for flameshot gui is used. Like so:
``flameshot gui -p PATH``

**Expected Behaviour:**
if I use `flameshot gui -p PATH` I still want to be able to copy the image to the clipboard. 

This was possible at some point.
If I do `flameshot gui` it is possible for me to copy to the clipboard

### Steps to reproduce

1. run `flameshot gui -p PATH`
2. select region
3. cannot copy to clipboard

### System Information

System:
  Host: archsh Kernel: 5.18.2-arch1-1 arch: x86_64 bits: 64 Desktop: dwm
    v: 6.2 Distro: Arch Linux
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel
  Device-2: Chicony HD Webcam type: USB driver: uvcvideo
  Display: x11 server: X.org v: 1.21.1.3 driver: X: loaded: amdgpu
    unloaded: modesetting gpu: amdgpu resolution: 1920x1080~60Hz
  Message: Unable to show GL data. Required tool glxinfo missing.

**Comment by borgmanJeremy** [comment]
This is intended behavior because you specified a "final action". You can find more info on the documentation of our website.

**Comment by mmahmoudian** [comment]
@Heusini please read the Final Actions in the link below:

https://flameshot.org/docs/advanced/commandline-options/
