### ISSUE TITLE
Translation strings on weblate.org are not updated

### ISSUE THREAD

**Issue by adem4ik** [flameshot-org/flameshot#2671]
### Flameshot Version

Flameshot v12.0.0 (55ba195f)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10 x64 

### Description

Version 12.0.rc1 has new strings, but they are not presented on Weblate. i.e. `Copy on double click` or `Imgur API key`. Also the whole tray RMC menu isn't not translated, but the strings are translated on Weblate.

### Steps to reproduce

1. Run Flameshot 12.0.rc1 on any system with non-English localization

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/4707112/173976056-f76a952f-ec3b-492a-8b62-29546f09da8a.png)
![image](https://user-images.githubusercontent.com/4707112/173975981-91a96f19-7d0f-48ac-9e80-3b6e3c3b15f9.png)
![image](https://user-images.githubusercontent.com/4707112/173976001-b266045e-9100-416d-aa75-2fb79eed7568.png)
![image](https://user-images.githubusercontent.com/4707112/173976138-6cea7b39-f53c-4d59-ba0d-0085cc7f83a0.png)

### System Information

N/A

**Comment by borgmanJeremy** [comment]
Can you check again? I just refreshed the translation files

**Comment by adem4ik** [comment]
I've translated everything on crowdin, downloaded .ts file, then released it to .qm with Qt Linguist and replaced Internationalization_ru.qm in \Flameshot\bin\translations path. In the result Settings, tray RMC menu got translations, but there are still some untranslated strings:

Hotkeys
![image](https://user-images.githubusercontent.com/4707112/174425596-ad4787de-11ce-4c6a-b40a-94f38d5b148d.png)

Tool settings > Color picker > Color picker popup
![image](https://user-images.githubusercontent.com/4707112/174426019-ecabfd6e-3e99-4028-a6d6-b45bf5bd5814.png)

Tool settings > RMC on color field
![image](https://user-images.githubusercontent.com/4707112/174425988-272d9a1b-10d9-428a-adca-7cf9bacb23aa.png)

**Comment by borgmanJeremy** [comment]
I can't do anything about the RMC menu as that is not created by Flameshot.

The other missing strings should be fixed now. They were missing a tr() around them. I checked some of the .ts files and they are now present.

**Comment by adem4ik** [comment]
@borgmanJeremy 
> The other missing strings should be fixed now.

Thank you, i'll check it later this night.

> I can't do anything about the RMC menu as that is not created by Flameshot.

It is translated in the base Qt translations. Afaik they are installed on most Linux distributions, or at least they are being installed automatically after installing Qt-based apps. But that's not the case for Windows, so the base translations should be shipped with official binares by the devs.

Here is trick that works for me:
- got qtbase_ru.ts from https://github.com/qt/qttranslations/tree/dev/translations
- released it to .qm with Qt Linguist and renamed to qt_ru.qm
- dropped it to the same folder as other translations

![image](https://user-images.githubusercontent.com/4707112/174442876-41f08232-e129-40c8-8747-8fdc0d35dfea.png)
![image](https://user-images.githubusercontent.com/4707112/174442857-975dee87-9a92-41e9-a7fe-4bbb9c24d125.png)

If they are any other standard forms apart from Tool settings RMC will be translated too.

**Comment by adem4ik** [comment]
I've checked with the latest windows artifacts and manual qm release from crowdin. Seems fine:
![image](https://user-images.githubusercontent.com/4707112/174453187-1f0e19b6-d978-4346-a338-933d75e8eb4a.png)
![image](https://user-images.githubusercontent.com/4707112/174453233-db95b244-134b-4614-867f-84a4dedc3834.png)

**Comment by mmahmoudian** [comment]
@adem4ik so shall we close this issue or there is something left to be addressed?

**Comment by adem4ik** [comment]
Apart from Tool settings RMC menu, it is fine. Feel free to close the issue.
