### ISSUE TITLE
Uploaded image does not populate the Latest Uploads list

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2672]
### Flameshot Version

Flameshot v12.0.0 (55ba195f)
Compiled with Qt 5.15.4

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro KDE (Kernel: 5.15.46-1-MANJARO x86_64)

### Description

Regardless of whether the daemon is running or in one-off mode, every time an image is uploaded to imgur, the Latest Uploads window remains empty.

### Steps to reproduce

1. `flamesho gui`
2. select a region
3. click on upload
4. wait for the upload to be complete and the upload window is closed
5. confirm that the URL of the uploaded image is stored in clipboard
6. check the Latest Uploads window

### Screenshots or screen recordings

https://user-images.githubusercontent.com/390889/174030618-b60e6d31-a57c-47d4-a689-45123e78265c.mp4

### System Information

```console
❯  inxi --system --graphics --width=80
System:
  Host: precisiontower Kernel: 5.15.46-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.3 driver: X: loaded: amdgpu,modesetting
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
    3: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon Pro WX 3200 Series (polaris12 LLVM 13.0.1 DRM
    3.42 5.15.46-1-MANJARO)
    v: 4.6 Mesa 22.1.1
```

**Comment by borgmanJeremy** [comment]
Hmmm, I cant reproduce this. Are you using a custom imgur key? Can you post your config?

**Comment by mmahmoudian** [comment]
Sure:

<details>
<summary>My Flameshot config</summary>

```ini
[General]
allowMultipleGuiInstances=true
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x16\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\
0\x16\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\x17\0\0\0\xe\0\0\0\f\0\0\0\x11)
contrastOpacity=135
copyPathAfterSave=true
disabledTrayIcon=false
drawColor=#fa0164
drawFontSize=14
drawThickness=1
ignoreUpdateToVersion=0.10.2
predefinedColorPaletteLarge=false
savePath=/home/mehrad/Pictures
savePathFixed=false
showMagnifier=false
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#ff7300
undoLimit=100
uploadHistoryMax=0
useJpgForClipboard=false
userColors=picker, #800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, #fa0164

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=
TYPE_PIN='
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_SIZEDECREASE=-
TYPE_SIZEINCREASE=+
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

</details>

For what It's worth, this does not happen on my other Manjaro KDE x11 desktop computer with Flameshot v11.0.0 (0870eca8) nor with 55ba195f. I should later see if I can reproduce this in a VM

**Comment by borgmanJeremy** [comment]
@mmahmoudian Your maximum upload history is set to 0 :)

**Comment by mmahmoudian** [comment]
Interesting! I of course haven't intentionally changed that, perhaps it was a mistake. How about showing an appropriate text in the upload history window? Something like "Max history is set to zero and this list will not get populated"
