### ISSUE TITLE
Pinned Image can't be closed anymore

### ISSUE THREAD

**Issue by xstable** [flameshot-org/flameshot#2673]
### Flameshot Version

Flameshot v12.0.0 (b036e531)
Compiled with Qt 5.15.4
linux: 5.15.46-1-MANJARO

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux: 5.15.46-1-MANJARO

### Description

Since my switch to the `git`-Version of flameshot (means since the last update of flameshot from my perspective of view), it's not possible anymore to remove an "pinned image" from the desktop.

Before it was easily possible if I click with the mouse on the image, and press ESC, but this don't work anymore.

### Steps to reproduce

1. run flameshot
2. make a screenshot
3. pin it to desktop
4. make another screenshot
5. take it to clipboard (CRTL+C)
6. Try to close the pinned image (you only archive this by killing flameshot)

### Screenshots or screen recordings

Nothing to show

### System Information

Linux (see above) 
KDE / Xorg
Monitors: 2
 0: +*VGA1 1920/530x1080/300+0+0  VGA1
 1: +LVDS1 1920/380x1080/210+1920+0  LVDS1

**Comment by mmahmoudian** [comment]
@xstable 
I don't remember when the <kbd>Esc</kbd> was removed, but double-click for closing was always an option ([case and point](https://github.com/flameshot-org/flameshot/issues/954#issue-705983940))

@borgmanJeremy do you recall when the <kbd>Esc</kbd> was removed?

**Comment by xstable** [comment]
Ok, thanks. Never know, that double-click exist for that :) 

BTW: Then there is an inconsistency, because if you Pin an Image to the desctop, and don't do another flameshot-screenshot afterwards, ESC still works to close the pinned image. 

The `new behavior` only happend if you pin an image to desktop, create a new screenshot which include this pinned image, and try to remove the pinned image afterwards.

**Comment by borgmanJeremy** [comment]
I've always used double click and not esc to close. Since I never tracked closing with esc as a feature I'm not sure when the behavior changed.

**Comment by mmahmoudian** [comment]
> BTW: Then there is an inconsistency, because if you only Pin an Image to the desktop, and don't do another flameshot-screenshot afterwards, ESC still works to close the pinned image.

At least on my setup that is not the case. Esc does not work at all under any circumstances using Flameshot v12.0.0 (55ba195f)

**Comment by xstable** [comment]
![flameshot issue_Peek 2022-06-16 14-41](https://user-images.githubusercontent.com/1778068/174072334-6b9d41f6-fa3b-4e63-9740-d9f8c8ed6c99.gif)

**Comment by mmahmoudian** [comment]
> Do you also use Linux & KDE?

Yes, Manjaro KDE X11

> Sorry for the flickering of the record. Don't know what that strange issue with the recorder is

use [peek](https://github.com/phw/peek). The end of the video is not comprehensible. I don't understand what you are trying to achieve.

Regarding the config window screenshot you sent with blue arrows, yes, the Esc is set to cancel taking a screenshot, not to close the pinned image.

**Comment by borgmanJeremy** [comment]
After more consideration I dont think this is a bug. It can be double clicked to close and there is another issue opened to add close to the menu.
