### ISSUE TITLE
'It would be very helpful if you posted on the discussion linked to this release': please give that link somewhere easy to find

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [flameshot-org/flameshot#2678]
[This page](https://github.com/flameshot-org/flameshot/releases/tag/v12.0.rc1) contains the text above. I think that at one point I found the 'discussion linked to this release' but now I cannot find it. For future release announcements, please consider giving the link immediately after - or within - the text that mentions the discussion. Thank you.

**Comment by borgmanJeremy** [comment]
Great suggestion. I modified the release notes accordingly.
