### ISSUE TITLE
Regression: broken flameshot icon in about window ( caused by #2318 )

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#2684]
### Flameshot Version

12.0-rc1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian Sid / Unstable

### Description

The flameshot icon in about window is broken. Meanwhile, stderr has multiple output of "`qt.svg: Invalid path data; path truncated.`".

I believe current SVG icon has some incompatibilities with Qt5's SVG library. We all know that in #2318 the SVG icon was manually "optimized". When reverting the icon to un-optimized version (`flameshot.svg` and `org.flameshot.Flameshot.svg` from https://github.com/flameshot-org/flameshot/tree/9752b975c132056cb0fb5add4d28bf5c60ef6d84/data/img/app ), everything works well again. I am using the most up-to-date Qt5 LTS version (5.15.4) so I believe we should make things compatible with this Qt version.

Ping original author @RiedleroD so that you may look further into it.

### Steps to reproduce

1. Run `/usr/bin/flameshot`.
2. Open "About" dialog from tray icon.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/8443926/174442745-dc65074a-6b7b-4a2c-ba35-8535c1d85064.png)

### System Information

* Debian Sid/Unstable
* Qt 5.15.4
* Desktop environment: (reproducible on all major Desktop Environments, including MATE and KDE Plasma)
* X11 environment

**Comment by mmahmoudian** [comment]
This is similar to #2667 but of course not duplicate.

**Comment by borgmanJeremy** [comment]
I'll revert the SVG.

**Comment by RiedleroD** [comment]
oh, this was actually my fault (for not fully correcting for known bugs in QtSVG)

I'll open a PR with the paths fixed & you'll see if that fixes is, ok?
