### ISSUE TITLE
Printsc functionality.

### ISSUE THREAD

**Issue by Drogobo** [flameshot-org/flameshot#2686]
### Feature Description

I want an option to take a screenshot when I press Print Screen. This is a good feature. I have seen it in lightshot. This app is good, but it is missing this feature to me.

**Comment by mmahmoudian** [comment]
This is something that your window manager should handle. On Windows this worksout of the box, on Mac there is no <kbd>prnt scr</kbd>, and on Linux and BSD it is something you should configure through your window manager.
