### ISSUE TITLE
Fail to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by TANSixu** [flameshot-org/flameshot#2692]
### Flameshot Version

Flameshot v11.0.0(latest)

### Installation Type

Compiled from source

### Operating System type and version

Ubuntu 18.04

### Description

I followed the compilation steps in the instruction with Cmake 3.22.5, however the make procedure failed with the following error information:

[  1%] Automatic MOC for target SingleApplication
[  1%] Built target SingleApplication_autogen
[  2%] Building CXX object external/singleapplication/CMakeFiles/SingleApplication.dir/SingleApplication_autogen/mocs_compilation.cpp.o
[  2%] Building CXX object external/singleapplication/CMakeFiles/SingleApplication.dir/singleapplication.cpp.o
[  3%] Building CXX object external/singleapplication/CMakeFiles/SingleApplication.dir/singleapplication_p.cpp.o
[  3%] Linking CXX static library libSingleApplication.a
[  3%] Built target SingleApplication
[  3%] Automatic MOC and UIC for target QtColorWidgets
[  3%] Built target QtColorWidgets_autogen
[  3%] Automatic RCC for resources/QtColorWidgets/color_widgets.qrc
[  4%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/QtColorWidgets_autogen/mocs_compilation.cpp.o
[  4%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/abstract_widget_list.cpp.o
[  5%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/bound_color_selector.cpp.o
[  5%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_2d_slider.cpp.o
[  6%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_delegate.cpp.o
[  6%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_dialog.cpp.o
[  7%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_line_edit.cpp.o
[  7%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_list_widget.cpp.o
[  8%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_names.cpp.o
[  8%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_palette.cpp.o
[ 10%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_palette_model.cpp.o
[ 10%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_palette_widget.cpp.o
[ 11%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_preview.cpp.o
[ 11%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_selector.cpp.o
[ 12%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_utils.cpp.o
[ 12%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/color_wheel.cpp.o
[ 13%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/gradient_slider.cpp.o
[ 13%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/hue_slider.cpp.o
[ 14%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/swatch.cpp.o
[ 14%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/gradient_editor.cpp.o
[ 15%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/harmony_color_wheel.cpp.o
[ 15%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/src/QtColorWidgets/gradient_list_model.cpp.o
[ 16%] Building CXX object external/Qt-Color-Widgets/CMakeFiles/QtColorWidgets.dir/QtColorWidgets_autogen/CRZPDLJRNK/qrc_color_widgets.cpp.o
[ 16%] Linking CXX static library libQtColorWidgets.a
[ 16%] Built target QtColorWidgets
[ 16%] Automatic MOC and UIC for target flameshot
[ 16%] Built target flameshot_autogen
[ 17%] Automatic RCC for ../data/graphics.qrc
[ 17%] Generating Internationalization_bg.qm
Updating '/opt/flameshot/build/src/Internationalization_bg.qm'...
    Generated 416 translation(s) (400 finished and 16 unfinished)
[ 19%] Generating Internationalization_ca.qm
Updating '/opt/flameshot/build/src/Internationalization_ca.qm'...
    Generated 412 translation(s) (353 finished and 59 unfinished)
    Ignored 4 untranslated source text(s)
[ 19%] Generating Internationalization_cs.qm
Updating '/opt/flameshot/build/src/Internationalization_cs.qm'...
    Generated 412 translation(s) (381 finished and 31 unfinished)
    Ignored 4 untranslated source text(s)
[ 20%] Generating Internationalization_de_DE.qm
Updating '/opt/flameshot/build/src/Internationalization_de_DE.qm'...
    Generated 412 translation(s) (382 finished and 30 unfinished)
    Ignored 4 untranslated source text(s)
[ 20%] Generating Internationalization_el.qm
Updating '/opt/flameshot/build/src/Internationalization_el.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 21%] Generating Internationalization_es.qm
Updating '/opt/flameshot/build/src/Internationalization_es.qm'...
    Generated 412 translation(s) (381 finished and 31 unfinished)
    Ignored 4 untranslated source text(s)
[ 21%] Generating Internationalization_eu.qm
Updating '/opt/flameshot/build/src/Internationalization_eu.qm'...
    Generated 412 translation(s) (361 finished and 51 unfinished)
    Ignored 4 untranslated source text(s)
[ 22%] Generating Internationalization_fa.qm
Updating '/opt/flameshot/build/src/Internationalization_fa.qm'...
    Generated 412 translation(s) (383 finished and 29 unfinished)
    Ignored 4 untranslated source text(s)
[ 22%] Generating Internationalization_fi.qm
Updating '/opt/flameshot/build/src/Internationalization_fi.qm'...
    Generated 412 translation(s) (383 finished and 29 unfinished)
    Ignored 4 untranslated source text(s)
[ 23%] Generating Internationalization_fr.qm
Updating '/opt/flameshot/build/src/Internationalization_fr.qm'...
    Generated 411 translation(s) (381 finished and 30 unfinished)
    Ignored 5 untranslated source text(s)
[ 23%] Generating Internationalization_gl.qm
Updating '/opt/flameshot/build/src/Internationalization_gl.qm'...
    Generated 411 translation(s) (376 finished and 35 unfinished)
    Ignored 5 untranslated source text(s)
[ 24%] Generating Internationalization_grc.qm
Updating '/opt/flameshot/build/src/Internationalization_grc.qm'...
    Generated 264 translation(s) (264 finished and 0 unfinished)
[ 24%] Generating Internationalization_he.qm
Updating '/opt/flameshot/build/src/Internationalization_he.qm'...
    Generated 412 translation(s) (383 finished and 29 unfinished)
    Ignored 4 untranslated source text(s)
[ 25%] Generating Internationalization_hu.qm
Updating '/opt/flameshot/build/src/Internationalization_hu.qm'...
    Generated 412 translation(s) (362 finished and 50 unfinished)
    Ignored 4 untranslated source text(s)
[ 25%] Generating Internationalization_id.qm
Updating '/opt/flameshot/build/src/Internationalization_id.qm'...
    Generated 412 translation(s) (383 finished and 29 unfinished)
    Ignored 4 untranslated source text(s)
[ 26%] Generating Internationalization_it_IT.qm
Updating '/opt/flameshot/build/src/Internationalization_it_IT.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 26%] Generating Internationalization_ja.qm
Updating '/opt/flameshot/build/src/Internationalization_ja.qm'...
    Generated 412 translation(s) (358 finished and 54 unfinished)
    Ignored 4 untranslated source text(s)
[ 28%] Generating Internationalization_ka.qm
Updating '/opt/flameshot/build/src/Internationalization_ka.qm'...
    Generated 412 translation(s) (338 finished and 74 unfinished)
    Ignored 4 untranslated source text(s)
[ 28%] Generating Internationalization_ko.qm
Updating '/opt/flameshot/build/src/Internationalization_ko.qm'...
    Generated 412 translation(s) (340 finished and 72 unfinished)
    Ignored 4 untranslated source text(s)
[ 29%] Generating Internationalization_nb_NO.qm
Updating '/opt/flameshot/build/src/Internationalization_nb_NO.qm'...
    Generated 412 translation(s) (337 finished and 75 unfinished)
    Ignored 4 untranslated source text(s)
[ 29%] Generating Internationalization_nl.qm
Updating '/opt/flameshot/build/src/Internationalization_nl.qm'...
    Generated 235 translation(s) (187 finished and 48 unfinished)
    Ignored 181 untranslated source text(s)
[ 30%] Generating Internationalization_nl_NL.qm
Updating '/opt/flameshot/build/src/Internationalization_nl_NL.qm'...
    Generated 412 translation(s) (382 finished and 30 unfinished)
    Ignored 4 untranslated source text(s)
[ 31%] Generating Internationalization_pl.qm
Updating '/opt/flameshot/build/src/Internationalization_pl.qm'...
    Generated 412 translation(s) (375 finished and 37 unfinished)
    Ignored 4 untranslated source text(s)
[ 31%] Generating Internationalization_pt_BR.qm
Updating '/opt/flameshot/build/src/Internationalization_pt_BR.qm'...
    Generated 412 translation(s) (379 finished and 33 unfinished)
    Ignored 4 untranslated source text(s)
[ 32%] Generating Internationalization_ru.qm
Updating '/opt/flameshot/build/src/Internationalization_ru.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 32%] Generating Internationalization_sk.qm
Updating '/opt/flameshot/build/src/Internationalization_sk.qm'...
    Generated 412 translation(s) (381 finished and 31 unfinished)
    Ignored 4 untranslated source text(s)
[ 33%] Generating Internationalization_sr_SP.qm
Updating '/opt/flameshot/build/src/Internationalization_sr_SP.qm'...
    Generated 412 translation(s) (343 finished and 69 unfinished)
    Ignored 4 untranslated source text(s)
[ 33%] Generating Internationalization_sv_SE.qm
Updating '/opt/flameshot/build/src/Internationalization_sv_SE.qm'...
    Generated 412 translation(s) (363 finished and 49 unfinished)
    Ignored 4 untranslated source text(s)
[ 34%] Generating Internationalization_tr.qm
Updating '/opt/flameshot/build/src/Internationalization_tr.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 34%] Generating Internationalization_uk.qm
Updating '/opt/flameshot/build/src/Internationalization_uk.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 35%] Generating Internationalization_vi.qm
Updating '/opt/flameshot/build/src/Internationalization_vi.qm'...
    Generated 411 translation(s) (372 finished and 39 unfinished)
    Ignored 5 untranslated source text(s)
[ 35%] Generating Internationalization_zh_CN.qm
Updating '/opt/flameshot/build/src/Internationalization_zh_CN.qm'...
    Generated 416 translation(s) (416 finished and 0 unfinished)
[ 37%] Generating Internationalization_zh_HK.qm
Updating '/opt/flameshot/build/src/Internationalization_zh_HK.qm'...
    Generated 412 translation(s) (337 finished and 75 unfinished)
    Ignored 4 untranslated source text(s)
[ 37%] Generating Internationalization_zh_TW.qm
Updating '/opt/flameshot/build/src/Internationalization_zh_TW.qm'...
    Generated 412 translation(s) (365 finished and 47 unfinished)
    Ignored 4 untranslated source text(s)
[ 37%] Building CXX object src/CMakeFiles/flameshot.dir/flameshot_autogen/mocs_compilation.cpp.o
[ 38%] Building CXX object src/CMakeFiles/flameshot.dir/cli/commandlineparser.cpp.o
[ 38%] Building CXX object src/CMakeFiles/flameshot.dir/cli/commandoption.cpp.o
[ 39%] Building CXX object src/CMakeFiles/flameshot.dir/cli/commandargument.cpp.o
[ 39%] Building CXX object src/CMakeFiles/flameshot.dir/config/buttonlistview.cpp.o
[ 40%] Building CXX object src/CMakeFiles/flameshot.dir/config/cacheutils.cpp.o
[ 40%] Building CXX object src/CMakeFiles/flameshot.dir/config/clickablelabel.cpp.o
[ 41%] Building CXX object src/CMakeFiles/flameshot.dir/config/colorpickereditmode.cpp.o
[ 41%] Building CXX object src/CMakeFiles/flameshot.dir/config/colorpickereditor.cpp.o
[ 42%] Building CXX object src/CMakeFiles/flameshot.dir/config/configerrordetails.cpp.o
[ 42%] Building CXX object src/CMakeFiles/flameshot.dir/config/configresolver.cpp.o
[ 43%] Building CXX object src/CMakeFiles/flameshot.dir/config/configwindow.cpp.o
[ 43%] Building CXX object src/CMakeFiles/flameshot.dir/config/extendedslider.cpp.o
[ 44%] Building CXX object src/CMakeFiles/flameshot.dir/config/filenameeditor.cpp.o
[ 44%] Building CXX object src/CMakeFiles/flameshot.dir/config/generalconf.cpp.o
[ 46%] Building CXX object src/CMakeFiles/flameshot.dir/config/setshortcutwidget.cpp.o
[ 46%] Building CXX object src/CMakeFiles/flameshot.dir/config/shortcutswidget.cpp.o
[ 47%] Building CXX object src/CMakeFiles/flameshot.dir/config/strftimechooserwidget.cpp.o
[ 47%] Building CXX object src/CMakeFiles/flameshot.dir/config/styleoverride.cpp.o
[ 48%] Building CXX object src/CMakeFiles/flameshot.dir/config/uicoloreditor.cpp.o
[ 48%] Building CXX object src/CMakeFiles/flameshot.dir/config/visualseditor.cpp.o
[ 49%] Building CXX object src/CMakeFiles/flameshot.dir/core/capturerequest.cpp.o
[ 49%] Building CXX object src/CMakeFiles/flameshot.dir/core/flameshot.cpp.o
/opt/flameshot/src/core/flameshot.cpp: In member function ‘void Flameshot::screen(CaptureRequest, int)’:
/opt/flameshot/src/core/flameshot.cpp:146:24: error: ‘class QApplication’ has no member named ‘screenAt’; did you mean ‘screens’?
         screen = qApp->screenAt(globalCursorPos);
                        ^~~~~~~~
                        screens
src/CMakeFiles/flameshot.dir/build.make:620: recipe for target 'src/CMakeFiles/flameshot.dir/core/flameshot.cpp.o' failed
make[2]: *** [src/CMakeFiles/flameshot.dir/core/flameshot.cpp.o] Error 1
CMakeFiles/Makefile2:658: recipe for target 'src/CMakeFiles/flameshot.dir/all' failed
make[1]: *** [src/CMakeFiles/flameshot.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to reproduce

1. git clone https://github.com/flameshot-org/flameshot.git
2. apt install g++ cmake build-essential qtbase5-dev qttools5-dev-tools libqt5svg5-dev qttools5-dev
3. apt install libqt5dbus5 libqt5network5 libqt5core5a libqt5widgets5 libqt5gui5 libqt5svg5
4. apt install git openssl ca-certificates
5. cd flameshot
6. mkdir build
7. cd build
8. cmake ../
9. make

### System Information

4.15.0-184-generic #194-Ubuntu SMP Thu Jun 2 18:54:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by borgmanJeremy** [comment]
Ubuntu 18.04 is no longer supported by us. We support the latest two LTS's from Ubuntu so current 22.04 and 20.04

**Comment by TANSixu** [comment]
> Ubuntu 18.04 is no longer supported by us. We support the latest two LTS's from Ubuntu so current 22.04 and 20.04

Ah I see. I have checked out earlier version and it works. Thanks!
