### ISSUE TITLE
Add menu action 'Close' to pinned screnshot

### ISSUE THREAD

**Issue by adem4ik** [flameshot-org/flameshot#2699]
### Feature Description

It would be really useful if pinned screenshot menu had 'Close' item. Sometimes I have to compare a few similar screenshots, and it takes some time to find a right one on Windows task bar in order to close it.
![image](https://user-images.githubusercontent.com/4707112/175012966-05e06dc2-a43f-408b-a0da-75add546f241.png)

So it looks more usable to had such option inside RMC menu.
![image](https://user-images.githubusercontent.com/4707112/175013180-76ec4f1b-8455-4b0d-892e-42e3e4b66e40.png)

**Comment by borgmanJeremy** [comment]
If you double click the pinned image it will close.

Since we have a pin menu I am not opposed to adding a close button though.

**Comment by mmahmoudian** [comment]
> Since we have a pin menu I am not opposed to adding a close button though.

Me too. It perhaps should just be at the bottom of the list with a separator line (to increase the distance)
