### ISSUE TITLE
Launch shortcut

### ISSUE THREAD

**Issue by HarryHq** [flameshot-org/flameshot#270]
When I want to intercept the screen on the status bar, the screen on the status bar disappears if I want to start from the startup icon. If there is a launch shorcut, it will fix it very well.

**Comment by javierin** [comment]
I have configured my PrScr key in the keyboard to just launch /usr/bin/flameshot gui -p /home/user/PictureFolder and it works just fine

**Comment by borgmanJeremy** [comment]
The newer 0.8.x releases have a launcher. Thanks!
