### ISSUE TITLE
Magnifier Off Screen When Using Multiple Monitors

### ISSUE THREAD

**Issue by Nyhtfury** [flameshot-org/flameshot#2700]
### Flameshot Version

v12.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10 10.0.19044 Build 19044

### Description

Magnifier was added in v12.0.0 per #2219 which was released a few hours ago. I'm really excited for this because this is probably the capability I miss most in Flameshot since moving away from Greenshot since Greenshot is Windows only and I use Linux systems frequently.

In this specific instance, I am using Windows with 3 screens that are aligned horizontally, and it causes the magnifier preview to appear on a separate screen (exactly one screen to the 'left'). Here's a picture of just two of my screens:

![image](https://user-images.githubusercontent.com/24866162/175097354-574c9c64-10b4-443b-bd11-dfe62fe58b33.png)

Either a configuration could be added to set a distance offset (meh), or it could be more like Greenshot and only appear when I'm grabbing one of the nodes of the selection area when enabled in the configuration (preferred). I'm sure there would be some users that would want a key toggle when dragging nodes of the selection area, but I don't have a strong opinion about that (and that might just be a separate request entirely).

### Steps to reproduce

Prerequisite: need multiple monitors. 

1. Run flameshot gui
2. Right click on tray icon
3. Select Configuration 
![image](https://user-images.githubusercontent.com/24866162/175097978-5e809ef6-081a-4b14-a079-bc5e5907fc42.png)
4. Select the General Tab
5. Scroll to the bottom of the checkbox settings
6. Enable `Show Magnifier` if not already enabled
![image](https://user-images.githubusercontent.com/24866162/175098737-08578853-466d-4e9c-a761-029b87b556c3.png)
7. Close the configuration window
8. Attempt to take a screenshot

### System Information

Windows 10 10.0.19044 Build 19044
![image](https://user-images.githubusercontent.com/24866162/175098294-2fb90a28-c215-47ce-a14e-cb7fd21cbfc1.png)
All screens are 1920x1080 resolution in landscape orientation.

**Comment by borgmanJeremy** [comment]
My only windows test setup is Windows 11 with 2x Monitors. I cannot replicate this issue using that setup.

Did you modify your screen configuration AFTER starting flameshot? If so, try restarting flameshot.

**Comment by MajZoa** [comment]
I'm having the same issue. (I use 2 monitors)

**Comment by mmahmoudian** [comment]
@Nyhtfury Thanks for comprehensive and detailed explanations and investigation.

> Very strange behavior: I get it to work with 1 monitor if the displays are in ascending order, left to right.
> But if I change the order of the displays...
> Then I get the magnifier on the wrong screen (exactly one screen to the left).

I think this is what causes the issue. Would it be easy for you to test and see in your work environment (the one with 3 monitors in descending order from left to right) to change the order to ascending and see if the issue is gone?

**Comment by Nyhtfury** [comment]
@mmahmoudian there was one permutation I missed (since 3 pick 3 where order matters is 6):
![image](https://user-images.githubusercontent.com/24866162/175290963-80f2032f-b55b-4d74-86d7-0088a31723c1.png)

And that worked too.

I ran through the test cases again:
1-2-3 - magnifier 1 screen to the right
1-3-2 - magnifier 1 screen to the right
2-1-3 - works
2-3-1 - works
3-2-1 - magnifier 1 screen to the left
3-1-2 - magnifier 1 screen to the left

I will test in my Pop!_OS environment (Debian) in a bit.

**Comment by Nyhtfury** [comment]
I just confirmed a new hypothesis: 
The magnifier works when your 'main' display is left most. 2 is my main display which is why those two permutations worked. If I change 3 to be my main display then 3-2-1 works (which is the permutation I care about).

**Comment by Nyhtfury** [comment]
This does not appear to be an issue on my Pop!_OS (debian) system. It is using 2-3-1 where 3 is the primary display.

**Comment by mmahmoudian** [comment]
And on Manjaro with 3 monitors with 2-1-3 configuration when 1 is the primary, I don't have any issue. This indicates that the issue is specific to Windows

**Comment by jasonycw** [comment]
Not sure if this is related, but on MacOS, the magnifier also behave weirdly with multiple monitors

https://user-images.githubusercontent.com/4518597/175845147-e415cdb8-56ca-4524-99d3-b04cc3a7bf1d.mov

https://user-images.githubusercontent.com/4518597/175845485-cabd0928-9d3b-41b5-853c-32819d7caf4f.mov

This happen on the top left display only

![image](https://user-images.githubusercontent.com/4518597/175845267-136f35ec-4d31-4dbf-b600-b9866f7415c3.png)

On the bottom display, the magnifier is off pixel by around the amount of the notch status bar

https://user-images.githubusercontent.com/4518597/175845709-2b9c7b9c-cf42-4cd4-800a-752921e3ddda.mov

And magnifier does not appear at all on the top right display

Maybe related to https://github.com/flameshot-org/flameshot/issues/2710 and https://github.com/flameshot-org/flameshot/issues/2612

**Comment by jasonycw** [comment]
Not sure if this is related, but on MacOS, the magnifier also behave weirdly with multiple monitors

https://user-images.githubusercontent.com/4518597/175846884-85bb9a70-3a3e-4844-9079-c3c46964bcb7.mov

This happen on the top left display only

![image](https://user-images.githubusercontent.com/4518597/175845267-136f35ec-4d31-4dbf-b600-b9866f7415c3.png)

On the bottom display, the magnifier is off pixel by around the amount of the notch status bar

https://user-images.githubusercontent.com/4518597/175846952-965891fa-c66a-44c0-b778-337d47841d03.mov

And magnifier does not appear at all on the top right display

Maybe related to https://github.com/flameshot-org/flameshot/issues/2710 and https://github.com/flameshot-org/flameshot/issues/2612

**Comment by jasonycw** [comment]
Not sure if this is related, but on MacOS, the magnifier also behave weirdly with multiple monitors

https://user-images.githubusercontent.com/4518597/175846884-85bb9a70-3a3e-4844-9079-c3c46964bcb7.mov

This happen on the top left display only

![image](https://user-images.githubusercontent.com/4518597/175845267-136f35ec-4d31-4dbf-b600-b9866f7415c3.png)

On the bottom display, the magnifier is off pixel by around the amount of the notch status bar

https://user-images.githubusercontent.com/4518597/175846952-965891fa-c66a-44c0-b778-337d47841d03.mov

And magnifier does not appear at all on the top right display

Maybe related to https://github.com/flameshot-org/flameshot/issues/2710 and https://github.com/flameshot-org/flameshot/issues/2612

**Comment by borgmanJeremy** [comment]
#2746 fixes this for me with two monitors

**Comment by Nyhtfury** [comment]
Resolved in [v12.1.0](https://github.com/flameshot-org/flameshot/releases/tag/v12.1.0) per #2746
