### ISSUE TITLE
Enter to Accept Capture

### ISSUE THREAD

**Issue by andymuk** [flameshot-org/flameshot#2701]
For the longest time I've been using this default key shortcut for doing print screens.

Recently installing the latest version on a few PCs has resulted in this key now no longer working.

This has been apparent for the last few versions I have installed using the MSI installer on Windows.

Windows 11 Pro is the OS.

**Comment by mmahmoudian** [comment]
Three or four versions ago we introduced a new concept called Final Actions. Read more about it here:

https://flameshot.org/docs/advanced/commandline-options/#final-actions

You can still bind Enter to a specific action, but if you use any commandline argument that is a final action, your enter key will only work to Accept the execution.

If you want to know and change the key bindings, right-click on the tray icon and go to Configurations
