### ISSUE TITLE
Unable to resize pinned screenshots

### ISSUE THREAD

**Issue by hf02** [flameshot-org/flameshot#2702]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.22000
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11 Home 21H2

### Description

After updating to 12.0.0, I'm unable to resize a pinned screenshot by scrolling.

### Steps to reproduce

1. Take screenshot
2. Pin screenshot
3. Scroll on pinned screenshot, and nothing happens

### System Information

Windows 11 Home 21H2

Two 1920x1080 monitors side-by-side

**Comment by keesse** [comment]
Same here on Ubuntu 22.04

Flameshot v12.0.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-39-generic
ubuntu: 22.04

**Comment by mmahmoudian** [comment]
@keesse whatisyour DE? Are you on Gnome or Wayland?

Please read the following page to know what information we need and how to obtain them from your computer:

https://flameshot.org/docs/guide/issue-reporting/

**Comment by keesinqdo** [comment]
@mmahmoudian , I've looked it up in /etc/gdm3/custom.conf:
#WaylandEnable=false
So I am running Wayland

**Comment by attendeany** [comment]
Same problem

Version:
Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

Installation:
From releases page
[flameshot-12.0.0-win64.zip](https://github.com/flameshot-org/flameshot/releases/download/v12.0.0/flameshot-12.0.0-win64.zip)

**Comment by Pixel48** [comment]
Same here 

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10 home x64

installed from [Flameshot-12.0.0-win64.msi](https://github.com/flameshot-org/flameshot/releases/download/v12.0.0/Flameshot-12.0.0-win64.msi)

**Comment by borgmanJeremy** [comment]
Okay I've confirmed this on Windows and will investigate.

**Comment by borgmanJeremy** [comment]
As expected the offending commit is: 413a3f93729abd354d8722d02cd5abb875c9449b

**Comment by borgmanJeremy** [comment]
Welp, I pushed the fix directly to master on accident.....Please test it out but it worked locally 1f3ca56b977832cbf403a336c51d56a3da55cd8c. 

On another note I need to setup branch protection, somehow it was disabled.

**Comment by hf02** [comment]
Running [the artifact from here](https://github.com/flameshot-org/flameshot/actions/runs/2580069387), it seems to be working. Thanks.

**Comment by keesse** [comment]
@borgmanJeremy I can't find a new build, is there one (ubutu/linux) that I can download to test?
BTW I found out there also is a MacOS version, I installed it and that works fine!

**Comment by keesse** [comment]
@borgmanJeremy thank you for your reply, I'll have to be more patient then.
At least I now know where to find the builds.
