### ISSUE TITLE
Human issue - you guys must coordinate an agreement about API use on Gnome 41/42 DE

### ISSUE THREAD

**Issue by alansenairj** [flameshot-org/flameshot#2704]
### Feature Description

The bug is a human guided. 

Flameshot uses an private API. Gnome guys talks about public API. 

You guys must have an agreement about that!!! 

![image](https://user-images.githubusercontent.com/20565821/175163495-14030142-4e99-4e64-850a-f5983398d920.png)

![image](https://user-images.githubusercontent.com/20565821/175163454-921bbbe9-1970-427a-ab9f-9f89a6567f55.png)

![image](https://user-images.githubusercontent.com/20565821/175163574-9569b339-4729-49a6-b5d0-8ef4524436fa.png)

**Comment by mmahmoudian** [comment]
I'm sick of this! Our source code is opensource, and nothing to hide on our end. Study it carefully and decide yourself who is is using what and which human is to be faulty!
