### ISSUE TITLE
flameshot launcher have some problems

### ISSUE THREAD

**Issue by Alaskra** [flameshot-org/flameshot#2706]
### Flameshot Version

Flameshot v12.0.0 (10a8c318)
Compiled with Qt 5.15.4

### Installation Type

Compiled from source

### Operating System type and version

5.4.197-1-MANJARO

### Description

when use `flameshot launcher` to take screenshot, two problems occur:
1. the help message doesn't disappear, until start another selection
2. the content of the button that show X or Y demensions of the selection disappear 

### Steps to reproduce

1. run `flameshot launcher`
2. press `Take new screenshot` button
3. then the problem happen as above shows

ps: if run falmeshot as daemon and right click tray icon to open launcher, the problem also happen.

### Screenshots or screen recordings

![2022-06-23_08-51](https://user-images.githubusercontent.com/49367127/175184727-6c5f7c9c-4f98-4387-9cf5-4f8dc4fc8cd1.png)

### System Information

\> inxi --width 80 --system --graphics
System:
  Host: alaskra-redmibook14 Kernel: 5.4.197-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nvidia v: 515.48.07
  Display: x11 server: X.Org v: 21.1.3 driver: X: loaded: modesetting,nvidia
    gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 22.1.1

**Comment by Alaskra** [comment]
I think the help message should hide after initial selection but it hide after select region manually.

https://user-images.githubusercontent.com/49367127/176226259-4127aac7-41a4-4f50-ac35-daeebe0f76ed.mp4

**Comment by borgmanJeremy** [comment]
#2734 fixes the size indicator.

**Comment by borgmanJeremy** [comment]
In my opinion the help message is not a bug but I would also like @mmahmoudian  to weigh in. The reason I think it is not a bug:

- There is an option to disable it, if the user has it enabled, then we should display the help message
- Even though the help message occludes the image, it does not get saved or copied with the final image so it does not affect the result
- The help message dissapears if the widget is resized. **Maybe we could also hide it if a tool is clicked**
