### ISSUE TITLE
Incorrect Release v12.0.0 binaries

### ISSUE THREAD

**Issue by theofficialgman** [flameshot-org/flameshot#2707]
### Flameshot Version

https://github.com/flameshot-org/flameshot/releases/tag/v12.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

NA

### Description

the files are labeled as rc1. this breaks updating through methods I use (as well as some of your own links in the release) and does not reflect that this is an official release and not rc1 (that version was different). 

### System Information

NA

**Comment by mmahmoudian** [comment]
Thanks for reporting this. I'll tag @borgmanJeremy

**Comment by TheReptile** [comment]
I only checked the Ubuntu deb file, the version string of the executable seems to be right, but other metadata in the deb file still shows the rc1 references.

**Comment by theofficialgman** [comment]
closed with 12.1.0
