### ISSUE TITLE
Magnifier not showing up on external monitor on Macbook

### ISSUE THREAD

**Issue by jasonycw** [flameshot-org/flameshot#2710]
### Flameshot Version

12.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS 12.2.1

### Description

Magnifier is not showing on external monitors for macbook

### Steps to reproduce

1. Connect external monitor
2. Turn on magnifier
3. Use Flameshot to screenshot something on external monitor

### System Information

macOS 12.2.1

<img width="780" alt="image" src="https://user-images.githubusercontent.com/4518597/175259843-f24843bc-3852-4b2c-a8c0-8011e316914e.png">

**Comment by pr0PM** [comment]
For my macbook 12.4 it's unable to take a screenshot of anything other than the desktop screen

**Comment by jasonycw** [comment]
> For my macbook 12.4 it's unable to take a screenshot of anything other than the desktop screen

Need to go to System Preference > Security & Privacy > Screen Recording and then disable and reenable flameshot

**Comment by Nyhtfury** [comment]
Probably related: #2700

**Comment by borgmanJeremy** [comment]
Can you retry on 12.1?

**Comment by jasonycw** [comment]
Seems to be working on 12.1
