### ISSUE TITLE
[Mac] Screenshot dont show anything since the 12.0.0

### ISSUE THREAD

**Issue by MilkyTommy** [flameshot-org/flameshot#2712]
### Flameshot Version

Flameshot 12.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Montery 12.4 (21F79)

### Description

When i try to take a screenshot of whatever the app (full screen or not) won't show anything except the blank desktop (without my drive or the dock).

I tried so far :

1. Screenshot via the shortcut  (shift +command + x)
2. Screenshot via the the app on the taskbar via "Take Screenshot"
3. Take a screenshot of a full screen app
4. Take a screenshot of a non full screen app
5. Close and reopen the app 
6. Accept the new " "Flameshot.app" would like to record this computer's screen" popup 
7. Reboot my mac
8. Install the version 12 beta
9. Install via Brew install flameshot
10. Install via the .dmg

 but nothing work except to go back to the version 11.0.0

All seem working, but i can't take a screenshot of anything except my default wallpaper.

### Steps to reproduce

Shift + command + x

### Screenshots or screen recordings

version 11.0.0:
![image](https://user-images.githubusercontent.com/5721250/175323883-c865a379-0215-48f7-b45b-4b2e956e0bf5.png)

Version 12.0.0:
![image](https://user-images.githubusercontent.com/5721250/175324149-3f80dcc5-d09a-41e0-99f4-a231e276817c.png)

the screenshots are take from the same desktop with the same app open, 2 min. appart from each other

### System Information

![image](https://user-images.githubusercontent.com/5721250/175326174-4101d59c-d689-4b56-bd5a-4ecee07bad08.png)

**Comment by mubbashir** [comment]
I can also confirm for 12.0.0,
It looks like it moves to empty desktop before taking the screenshoot, hence it's always just the empty desktop.
 Downgraded to 11

**Comment by MilkyTommy** [comment]
> I can also confirm for 12.0.0, It looks like it moves to empty desktop before taking the screenshoot, hence it's always just the empty desktop. Downgraded to 11

It's more than that, if you look my screenshot, flameshot seem don't have access to all components (like it only show flameshot in my taskbar, not even the time)

But I tried to check/unchecked and multi reboot the mac but it's seem a access problem.

**Comment by mmahmoudian** [comment]
Please read:
 https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

This is an issue with Mac that it needs the new permission for every new version

**Comment by mmahmoudian** [comment]
Let me know if this solves your problem

**Comment by Euzebius** [comment]
> Please read: https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection
> 
> This is an issue with Mac that it needs the new permission for every new version

This solved the issue on my side indeed!
One need to remove flameshot permission and then add it again and after that everything works back.
Thanks for the link ;)

**Comment by Prakash-Reddy-Potlapadu** [comment]
@Euzebius, thanks a lot, that worked
