### ISSUE TITLE
Flameshot opens in the wrong window

### ISSUE THREAD

**Issue by ElieLeHackeur** [flameshot-org/flameshot#2717]
### Flameshot Version

Flameshot v12.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS Monterey V12.4

### Description

When I press the hotkey to take a screenshot with flameshot, instead of taking the screenshot on whatever I want, flameshot creates a new screen with just my wallpaper.

### Steps to reproduce

1. press shift + command + x
2. flameshot opens a new screen instead of taking a capture of my screen

### Screenshots or screen recordings

link of my recording : https://wormhole.app/az473#VstJ1RUKfFzYreYe1jAD6A

### System Information

macOS Monterey V12.4
Monitor configuration : https://wormhole.app/oYDkQ#_m3oNiLt0X5uI0wyBo4t2g

**Comment by aneneve-corra** [comment]
> > Same issue in my MacOs 12.4 with Flameshot 12.0.0, downgrade to Flameshot 11 for now.
> 
> How did you downgrade ? I can't figure how to do it with homebrew.

Hmm, I didn't install using Homebrew, maybe you could remove using homebrew, then download the .dmg file, it's easier to install.
https://github.com/flameshot-org/flameshot/releases/download/v11.0.0/flameshot.dmg

P.S. On first launch hold "CONTROL" button to bypass Developer warning.

**Comment by ElieLeHackeur** [comment]
> 



> > > Same issue in my MacOs 12.4 with Flameshot 12.0.0, downgrade to Flameshot 11 for now.
> > 
> > 
> > How did you downgrade ? I can't figure how to do it with homebrew.
> 
> Hmm, I didn't install using Homebrew, maybe you could remove using homebrew, then download the .dmg file, it's easier to install. https://github.com/flameshot-org/flameshot/releases/download/v11.0.0/flameshot.dmg
> 
> P.S. On first launch hold "CONTROL" button to bypass Developer warning.

thx ❤️

**Comment by mmahmoudian** [comment]
it is not an issue of flameshot. You should grant flameshot permission for every new version. Read more here:

https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

**Comment by danielleontiev** [comment]
It looks like flameshot issue for me: after installing 12.0.0 and running it flameshot asks to open system preferences and grant the permissions for screen recording - if you open privacy settings you could see that permission for flameshot is already granted (all in all, i've tryied to unselect it and select again). They after computer restart first thing that you get after starting flameshot is permission request - again, while it's granted. Then you reboot -> get request again -> reboot -> etc... While taking screen never works during all steps. Rolling back to 11.0.0 works just fine

**Comment by aneneve-corra** [comment]
For me it worked with 12.0.0, but was necessary to remove from Privacy Settings, then search for apps and add again.
In other words, just unchecking and checking again doesn't work.
@danielleontiev

**Comment by danielleontiev** [comment]
By bad - thank you @aneneve-corra, now works just fine

**Comment by mmahmoudian** [comment]
Thank you @aneneve-corra for extended explanation. Yes, this is a macos bug that doesn't recognize the updated versions as the same software.

**Comment by jagibson** [comment]
Just confirming @aneneve-corra 's answer worked for me.  Security & Privacy > Privacy tab -> Screen Recording.  I removed flameshot.app and re-added it, then restarted flameshot.  Works!  Thanks!
