### ISSUE TITLE
Confusing setting name for custom Imgur key

### ISSUE THREAD

**Issue by thehunmonkgroup** [flameshot-org/flameshot#2718]
### Flameshot Version

Flameshot v12.0.0 ()
Compiled with Qt 5.12.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop!_OS 20.04 LTS

### Description

https://github.com/flameshot-org/flameshot/pull/2503 added the ability to configure a custom Imgur key.

However, I got pretty tripped up about *what* to put in there. The Imgur documentation talks about needing to use an access token to make write requests to an account, so I spent quite a bit of time generating Oauth access tokens and putting them in the `Imgur API Key` field, which of course kept failing with permission denied errors.

It was only after I looked at the actual code in https://github.com/flameshot-org/flameshot/pull/2503 that I realized it was the `Client ID` from the created Imgur app that was supposed to go in that setting.

Given the crazy amount of complexity in the Oauth sequence, and the number of different ID/secrets/tokens generated (Client ID, Client secret, Access token, Refresh token), I think a more precise label for that setting would be in order, perhaps `Imgur Application Client ID` ?

### Steps to reproduce

N/A

### Screenshots or screen recordings

N/A

### System Information

N/A

**Comment by borgmanJeremy** [comment]
Great suggestion!
