### ISSUE TITLE
Flameshot not working on MacOS after latest update

### ISSUE THREAD

**Issue by NP2215** [flameshot-org/flameshot#2721]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Monterey 12.4

### Description

After upgrading to the latest version (v12.0.0), flameshot completely stops working on MacOS. The app requests for permission to `screen record`, but even after it is given the permission the app is unable to detect the presence of the permission and keeps returning the error in loop.

### Steps to reproduce

1. Run `flameshot.gui`
2. Try to take a screenshot either by hitting `Take Screenshot` or by using your usual keybinding.
3. App asks for permission to screen record, grant it. 
4. Quit and reopen the app
5. The app asks for permission again (and process loops)

### Screenshots or screen recordings

https://user-images.githubusercontent.com/76003870/175774933-0bc51d3e-d159-4497-b2eb-61326fa32406.mp4

### System Information

Operating system - MacOS
Version - MacOS Monterey 12.4 
![image](https://user-images.githubusercontent.com/76003870/175774830-61964e37-bb57-4fd5-a631-0d676d1cb885.png)

**Comment by mmahmoudian** [comment]
Close flameshot, remove permission,add the permission again and then run Flameshot. You should not have the process running while changing the permissions. It will not get applied

**Comment by NP2215** [comment]
Does not work even then.

https://user-images.githubusercontent.com/76003870/175778460-3850affc-647c-41fe-a86c-e2ec21edf7f6.mov

**Comment by borgmanJeremy** [comment]
Try rebooting. macOS is weird with these permissions.

**Comment by NP2215** [comment]
Done that thrice now, no luck with that either.

**Comment by borgmanJeremy** [comment]
Unfortunately we can't fix this. It works fine for me

**Comment by NP2215** [comment]
I tried downgrading to v11.0.0 and it works just fine with all the permissions. It seems more of a v12.0.0 problem than an overall system problem.

**Comment by salmanfarisvp** [comment]
@NP2215 I had the same issue. To solve, What I did is!

1. Quit the flame shot application 
2. Remove Screen recording permission
3. Open flame shot 
4. Asking permission -> Open system 'security and privacy
5. Give permission 
6. Relaunch the application automatically 
7. Issue solved.  

Please check.

**Comment by borgmanJeremy** [comment]
I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.

**Comment by ozgurg** [comment]
> I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.

Try removing the permission by clicking the minus icon and reopen Flameshot. Flameshot permission should appear again. Then give the permission. This worked for me.

**Comment by ivanseibel** [comment]
I've tried all suggestions and it still doesn't work. Every time I restart the app it asks for permission, even though the consent has been already given.

**Comment by ivanseibel** [comment]
> I've tried all suggestions and it still doesn't work. Every time I restart the app it asks for permission, even though the consent has been already given.
> 
> macOS Monterrey 12.4.

Actually, @ozgurg solution worked for me.

**Comment by thrasher456** [comment]
I was facing this same issue and @ozgurg solution worked for me too. That "minus" sign is important. not just unticking permission.

**Comment by borgmanJeremy** [comment]
I researched this quite a bit and it seems I can fix it by enrolling in the apple developer program and code signing it.

I'm still on the fence about this cuz it feels dirty to pay the apple tax.

**Comment by NP2215** [comment]
> > I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.
> 
> Try removing the permission by clicking the minus icon and reopen Flameshot. Flameshot permission should appear again. Then give the permission. This worked for me.

This indeed worked for me too. Thanks!

**Comment by ook** [comment]
This issue should be referenced in a troubleshooting section of the readme: since closed, you can't see it if you don't search it…

**Comment by patschwork** [comment]
It also worked for me with the "-" in the permission window. After restarting and giving permission again, flameshot works again

**Comment by mmahmoudian** [comment]
@NP2215 Please make sure to remove it (not just toggling the checkbox, but remove it completely), then add the permission again. This is an issue with macOS that does not refresh permissions when only the checkbox is toggled. When you remove it completely and add it again, macOS then understands the change.

**Comment by garthhumphreys** [comment]
> > I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.
> 
> Try removing the permission by clicking the minus icon and reopen Flameshot. Flameshot permission should appear again. Then give the permission. This worked for me.

This worked for me too, thanks! @ozgurg

**Comment by giri-sh-irke** [comment]
> It also worked for me with the "-" in the permission window. After restarting and giving permission again, flameshot works again

This works if the initial solution dint work.

**Comment by tarcisiomiranda** [comment]
Stable version for Mac M1 OSX Ventura
- Bug: when I request a print, the objects leave the screen
https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0

**Comment by mmahmoudian** [comment]
@tarcisiomiranda make sure you have read everything here:
https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by lawson-ng** [comment]
> > I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.
> 
> Try removing the permission by clicking the minus icon and reopen Flameshot. Flameshot permission should appear again. Then give the permission. This worked for me.

This worked for me. Thanks @ozgurg 🎉

**Comment by FamousNoBody** [comment]
> @NP2215 I had the same issue. To solve, What I did is!
> 
> 1. Quit the flame shot application
> 2. Remove Screen recording permission
> 3. Open flame shot
> 4. Asking permission -> Open system 'security and privacy
> 5. Give permission
> 6. Relaunch the application automatically
> 7. Issue solved.
> 
> Please check.

Thanks, bro. It works for me.

**Comment by pwhite1989** [comment]
> @NP2215 I had the same issue. To solve, What I did is!
> 
>     1. Quit the flame shot application
> 
>     2. Remove Screen recording permission
> 
>     3. Open flame shot
> 
>     4. Asking permission -> Open system 'security and privacy
> 
>     5. Give permission
> 
>     6. Relaunch the application automatically
> 
>     7. Issue solved.
> 
> 
> Please check.

Its 2025 and after updating to 13.1, this guide works for me as well - thanks! Don't forget to click the minus to completely remove the permission before setting it up again.

**Comment by shiyishiaa** [comment]
> > I promise you it's not. Mac is just remembering the permissions from the last time you had v11 installed.
> 
> Try removing the permission by clicking the minus icon and reopen Flameshot. Flameshot permission should appear again. Then give the permission. This worked for me.

This problem happened to me today, and this solution saved my life!
