### ISSUE TITLE
Update qt from 5.15.2 to ···

### ISSUE THREAD

**Issue by tasty0tomato** [flameshot-org/flameshot#2727]
### Feature Description

Since qt release 5.15.3, 5.15.4, 5.15.5 under open source license, if it is possible to build flameshot using a newer version of qt since newer qt may be less buggy?
Just a small advice and I am not very famaliar with qt.

**Comment by borgmanJeremy** [comment]
Yea you can build flameshot against any version of qt5 as long as it meets our minimum version documented on the readme.
