### ISSUE TITLE
Blank Flameshot window appears after screenshot save to file

### ISSUE THREAD

**Issue by robmaurizio** [flameshot-org/flameshot#2728]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.22621
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11 Pro, Version 22H2

### Description

A blank flameshot window appears after saving a screenshot out to a png image file

### Steps to reproduce

1. Invoke flameshot using the keyboard shortcut
2. Select area of screen to capture
3. Click save button to save the capture
4. name the file
5. Click save

A blank window appears for each screenshot saved. Blank windows will stack if multiple shots are taken.
![2022-06-27_11-38](https://user-images.githubusercontent.com/45679381/175992319-9df670a9-f5e4-4691-88df-5802e679f753.png)

### Screenshots or screen recordings

![2022-06-27_11-38](https://user-images.githubusercontent.com/45679381/175991587-befcb051-6d22-4f64-bb4e-b5cf4d652f49.png)

### System Information

Edition: Windows 11 Pro
Version: 22H2
Installed on: 5/‎11/‎2022
OS build: 22621.160
Experience: Windows Feature Experience Pack 1000.22632.1000.0

Monitor setup attached
![monitor 1](https://user-images.githubusercontent.com/45679381/175992026-7114fd44-20b4-426c-b155-8174de2169a4.png)
![monitor 2](https://user-images.githubusercontent.com/45679381/175992036-f2fe20dc-fecd-4b51-8f5e-9f2081de49c5.png)

**Comment by mmahmoudian** [comment]
I think this #2698 has addressed this. If you want to test it, you can download our nightly build from the link below, otherwise we should wait and see what other devs think about this

https://flameshot.org/docs/installation/development-build/

**Comment by AmandaBSobrinho** [comment]
Can confirm that this is happening with Linux as well.

Flameshot v12.0.0 ()
Compiled with Qt 5.15.2
linux: 5.16.0-kali7-amd64
kali: 2022.2

**Comment by mmahmoudian** [comment]
@AmandaBSobrinho what is your DE?

**Comment by mmahmoudian** [comment]
> @mmahmoudian sorry, what do you mean by DE?

Desktop Environment (e.g Gnome, KDE, Xfce, LXQt)

**Comment by thiagosanches** [comment]
That is happening on XFCE as well, after copying a screenshot to the clipboard.
![image](https://user-images.githubusercontent.com/5191469/176428105-9418f457-34dc-4c92-89bc-171550384434.png)
