### ISSUE TITLE
v12.0.0 screenshots only empty desktop (not the opened window) on macOS Monterey

### ISSUE THREAD

**Issue by mathiajusth** [flameshot-org/flameshot#2732]
### Flameshot Version

Flameshot v12.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS Monterey version 12.4 (21F79)

### Description

When activating "Take Screenshot" all apps seem to be minimized hence only the empty desktop can be screenshoted.

Works correctly with the previous version - flameshot v11.0.0. In the meantime it would be really nice if you could add the Homebrew Cask for the v11 (only v12 is available now) so it is possible to install it via brew.

### Steps to reproduce

1. run "Take Screenshot"
2. you see only empty desktop

### System Information

macOS Monterey version 12.4 (21F79)

**Comment by borgmanJeremy** [comment]
see: https://github.com/flameshot-org/flameshot/issues/2721
