### ISSUE TITLE
Can't zoom pinned images

### ISSUE THREAD

**Issue by jonasmuller98** [flameshot-org/flameshot#2733]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.19043
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10 Pro 21H1 Compiled 19043.1110, Windows Feature Experience Pack 120.2212.3530.0

### Description

After pinning an image, can't zoom in and out using mouse scroll the pinned image. 
On the previous release was working fine.
I'm using two monitors, don't know if this can't make a difference.
Zoom in/out seems to be working fine while using the "Change tool size behaviour", before pinning image.

### Steps to reproduce

1. Run flameshot
2. Press print screen on any monitor
3. Pin the print
4. Try to zoom pinned image

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/40892141/176514570-b2e57376-5aa2-481b-8225-3e667144efeb.png)

### System Information

1. Windows 10 Pro 21H1 Compiled 19043.1110, Windows Feature Experience Pack 120.2212.3530.0
2. Two monitors, 100% scale, both 1920x1080, Landscape, Extend these displays,

**Comment by borgmanJeremy** [comment]
We just fixed this on the master branch.

**Comment by mmahmoudian** [comment]
For the record, fixed with 1f3ca56b977832cbf403a336c51d56a3da55cd8c
