### ISSUE TITLE
Pinned images don't zoom anymore

### ISSUE THREAD

**Issue by Aevrin** [flameshot-org/flameshot#2738]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.22000
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Edition	Windows 11 Education Version	21H2 OS build	22000.778 Experience	Windows Feature Experience Pack 1000.22000.778.0

### Description

Previously when pinning an image you could zoom in and out with simply the scrollwheel.  Now the image doesn't zoom in or out anymore regardless of scrolling, scrolling with shift, ctrl, or using the +/- keys.

### Steps to reproduce

Run flameshot.  Screen capture, drag the selection, hit the pin tool.  Attempt to scroll.  Watch as it no longer zooms.

### System Information

Edition	Windows 11 Education Version
21H2 OS build	22000.778 Experience
Windows Feature Experience Pack 1000.22000.778.0

2 Monitors, Primary 2560x1080, Secondary 1920x1080

**Comment by borgmanJeremy** [comment]
Duplicate

**Comment by mmahmoudian** [comment]
Duplicate of #2733
