### ISSUE TITLE
Screen goes blank while taking screen shot for 2560x1600 display with 150% scale.

### ISSUE THREAD

**Issue by LilMonk** [flameshot-org/flameshot#2748]
### Flameshot Version

Flameshot v12.0.0 (latest)

### Installation Type

AppImage, Using the ready-made package from Github Releases

### Operating System type and version

Pop OS 22.04

### Description

The screen goes blank while taking a screen shot and remains blank until escape key is pressed. The screen is 2560x1600 display with 150% scale. The laptop I'm using is Lenovo Legion 5 pro AMD version.

### System Information

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

KERNEL=5.17.15-76051715-generic

**Comment by borgmanJeremy** [comment]
Does this happen if you change to 100% scaling?

**Comment by LilMonk** [comment]
Nope. For 100% scaling, it works fine.

**Comment by borgmanJeremy** [comment]
!fractionalscaling

**Comment by borgmanJeremy** [comment]
Okay I'll close this as a duplicate then.
