### ISSUE TITLE
New installation, there's no way to use the select area + editing tools

### ISSUE THREAD

**Issue by javibg6** [flameshot-org/flameshot#2751]
### Flameshot Version

 v12.0.0

### Installation Type

Flatpak from Flathub

### Operating System type and version

Fedora 36, Gnome 42.2

### Description

I recently installed fedora, coming from other distros (recently Arch) and having used flameshot for quite some time. I installed flameshot, and i can't manage to take a simple screenshot just selecting an area, so that i can edit it and copy to clipboard. All i can access always is the Take screenshot tool, which makes a full screenshot. There, i can use the options button and click select area to grab, but even doing so, i don't get the tools i used to get in Arch.

I have tried with using the command flameshot gui, and it does the same. Also now, when i hit the tray icon, it always launches the menu, in my previous installation, when i use the left click, the pointer directly converts to the select area tool, while now, both right and left click show the menu. 

### System Information

Fedora 36, Gnome 42.2, Wayland

**Comment by mmahmoudian** [comment]
I'm guessing on Arch you were not using Gnome Waylanad and now you are, and you see a "share" button on the top right corner of that fullscreen screenshot. Is that right?

**Comment by javibg6** [comment]
> > All i can access always is the Take screenshot tool, which makes a full screenshot. There, i can use the options button and click select area to grab, but even doing so, i don't get the tools i used to get in Arch.
> 
> I'm guessing on Arch you were not using Gnome Waylanad and now you are, and you see a "share" button on the top right corner of that fullscreen screenshot. Is that right?
> 
Hi mmahmoudian. That's right, i was using cinnamon. That's the screen i get everytime, the one with the options and share buttons on the top right corner.

> > while now, both right and left click show the menu.
> 
> This is something that I should try to see if is reproducible in a clean VM

**Comment by borgmanJeremy** [comment]
!gnome41

**Comment by mmahmoudian** [comment]
@javibg6 and also read this:
https://flameshot.org/docs/guide/wayland-help/#gnome-wayland
