### ISSUE TITLE
Open images with Flameshot

### ISSUE THREAD

**Issue by OnkelTem** [flameshot-org/flameshot#2767]
### Feature Description

I've just got an idea, immediately went to try it, but... nah, it doesn't seem to work. So I thinks it's a good candidate for a nice feature. Besides, it doesn't look difficult to implement.

Imagine you **already have** a screenshot and you just need to annotate it using the brilliant Flameshot UI. But you cannot open your image with Flameshot directly now, instead - you open it with a viewer of your preference and THEN run Flameshot over it. But FS doesn't know anything about the boundaries of the image and it's almost impossible to adjust the bounding box *precisely* along the dimentions of the image :-/

It would be great to have Flameshot to open images itself, automatically setting boundaries along the image's dimentions. 

I feel like I'm gonna win an award on the yearly contest of witty feature requests. Do you have one? ;-)

**Comment by borgmanJeremy** [comment]
The award should go to #1100 which is the original request for this feature 

Since this is a duplicate I am going to close this, but I've had some new thoughts on how to do this.

**Comment by OnkelTem** [comment]
Haha, cool! Then I can't wait to see it implemented. Sure, you can say: PRs are welcome. And I'll have nothing to object to. Yeah, generating ideas is not a real work. We're just idling lazy buns :)
