### ISSUE TITLE
`flameshot full` not capturing all screens on Mac

### ISSUE THREAD

**Issue by jasonycw** [flameshot-org/flameshot#2771]
When running the following command on MacOS

```sh
flameshot full
```

Only the screen with the terminal was captured, not all screens. 

According to https://flameshot.org/docs/advanced/commandline-options/

it's supposed to do fullscreen capture (no select capture area), but on MacOS, this command not actually doing fullscreen capture, only single screen with the terminal windows.

-----------------

About:
Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 21.3.0
osx: 12.2

_Originally posted by @jasonycw in https://github.com/flameshot-org/flameshot/issues/2328#issuecomment-1178614334_

**Comment by mmahmoudian** [comment]
I marked all your comments and my replies in the #2328 as off-topic, I then edited your post above and brought one of your sentences and the screenshot to here. For the sake of completeness, please add your flameshot version to your post above and the ultimate installation method you went for (you mentioned in [your other post](https://github.com/flameshot-org/flameshot/issues/2328#issuecomment-1178540807) that you have used the DMG file and then [in another post](https://github.com/flameshot-org/flameshot/issues/2328#issuecomment-1178614334) you mentioned that you also tried homebrew)

**Comment by jasonycw** [comment]
@mmahmoudian because I tried both install methods.

Before version 12, I was using homebrew to install
```
brew install --cask flameshot
```

When version 12 launched, flameshot on homebrew was not verified and I accidentally deleted it when launching the app(the mac os security pop up have a button to move application to bin), so I used the DMG file to install version 12

Then when version 12.1 launched, I want to try the [updated magnifier](https://github.com/flameshot-org/flameshot/issues/2710#issuecomment-1178467678), since homebrew's version was not updated yet, I install 12.1 through DMG again

I have tried `brew reinstall --cask flameshot` today as well
![image](https://user-images.githubusercontent.com/4518597/177953741-d0880f9d-ada5-4baa-a757-3133c17f31cb.png)


After all these, I am not quite sure whether the flameshot.app in Application is the one from DMG or homebrew now

**Comment by mmahmoudian** [comment]
> After all these, I am not quite sure whether the flameshot.app in Application is the one from DMG or homebrew now

Well, this is easy, just remove flameshot with `brew`, then check if it is also gone from `Applications/` (if not remove it as well), then install with for example DMG

**Comment by jasonycw** [comment]
> > After all these, I am not quite sure whether the flameshot.app in Application is the one from DMG or homebrew now
> 
> Well, this is easy, just remove flameshot with `brew`, then check if it is also gone from `Applications/` (if not remove it as well), then install with for example DMG

OK, I reinstalled 12.1 through homebrew
![image](https://user-images.githubusercontent.com/4518597/177957317-03ddf346-0977-496a-9bbc-171e9e368673.png)
I also made sure flameshot is removed after uninstall

 `flameshot` command is still not found even with homebrew install
![image](https://user-images.githubusercontent.com/4518597/177957786-23359324-198a-48d1-9b92-971e63d4e0a2.png)

I still need to use the full path
![image](https://user-images.githubusercontent.com/4518597/177957717-5e90f0c7-1864-41d0-a3e1-411bff6ca184.png)

**Comment by mmahmoudian** [comment]
> I still need to use the full path

This is because you don't have it in your `PATH` variable. you should create a symlink:

```sh
sudo ln -s /Applications/flameshot.app/Contents/MacOS/flameshot /usr/local/bin/flameshot
```

Alternatively, you can add an alias to your shell (I personally don't like this approach as it will cause issues when you creat other aliases for flameshot). In your `~/.zshrc` file add this:

```sh
alias flameshot="/Applications/flameshot.app/Contents/MacOS/flameshot"
```

**Comment by borgmanJeremy** [comment]
On MacOs we can only display fullscreen across a single monitor so we unfortunately cannot fix this.
