### ISSUE TITLE
Flameshot keyboard shortcuts not working after update

### ISSUE THREAD

**Issue by mohammedbehjoo** [flameshot-org/flameshot#2781]
### Flameshot Version

Flameshot v 0.6.0 + git 20191001-2(Debian)
Complied with QT 5.12.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20.04.4 LTS

### Description

I have recently removed and installed Flameshot to update it thoroughly. But this procedure, the keyboard shortcuts are not working when editing and doodling on the taken screenshot. For example, I want a rectangle on some part of the image( SC ), but when I press the "R" button on my keyboard, it won't select the rectangle tool like it always did. Now I have to move my mouse to select the rectangle tool. One of the most significant advantages of Flameshot was these shortcuts. It made us more productive and quicker. But now, they simply don't work.

### Steps to reproduce

1. run "flameshot gui"
2. select a region to take an SC
3. press the "R" button for the rectangle tool.
It won't work, as I mentioned in the description box.

### System Information

I'm using Gnome Xorg

**Comment by mmahmoudian** [comment]
ورژن 6 مال ۲۰۱۸ بود. الان ورژن 12.1.0 هستیم

لطفا از snap یا flatpak نصب کن

**Comment by mohammedbehjoo** [comment]
ممنون از لطفتون
