### ISSUE TITLE
Error transferring https://api.imgur.com/3/image?title=&description=2022-07-12_12-26 - server replied: nginx

### ISSUE THREAD

**Issue by webmaster85** [flameshot-org/flameshot#2784]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Flatpak from Github

### Operating System type and version

Windows 10 Pro

### Description

Getting this daily when trying to upload images:

`Error transferring https://api.imgur.com/3/image?title=&description=2022-07-12_12-26 - server replied: nginx`

![image](https://user-images.githubusercontent.com/29068748/178458414-4e6fd188-e566-4e77-b7de-10f16d76cc19.png)

### Steps to reproduce

1. Make a printscreen.
2. Try using the _**Upload the selection**_ button.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/29068748/178458648-1f9b4141-e73e-4fba-9058-b73c1d8e4b51.png)

### System Information

Windows 10 Pro

**Comment by mmahmoudian** [comment]
Perhaps our quota is full, therefore it is not a bug. Try using your own Imgur token.

As a side note, we are now at version 12.1.0, please consider updating

**Comment by webmaster85** [comment]
@mmahmoudian I still get this even today: 
![image](https://user-images.githubusercontent.com/29068748/181213607-bb3751cc-2f52-4827-a3ad-00c25bdb35bc.png)

Not sure what you mean by the token, can you share documentation where I can see how that should be done? Also, the update process doesn't seem to be automatic, rather re-downloading the file from GitHub and reinstalling it. I've done it anyway but it's the same, each day around this time when I am working (customer support) I get that error and cannot upload an image.

Any help would be appreciated. TIA!

**Comment by mmahmoudian** [comment]
> Also, the update process doesn't seem to be automatic

It was never supposed to be automatic. You either use a package manager that automates it for you (like choco or winget on Windows), or you have to download it manually.

> can you share documentation where I can see how that should be done

I will update this shortly

**Comment by mmahmoudian** [comment]
For users that land on this thread i future, you can find updated instructions on the following page:

https://flameshot.org/docs/guide/imgur-help/

**Comment by webmaster85** [comment]
@mmahmoudian That's awesome, thanks! 😄
