### ISSUE TITLE
MacOS: `CMD+C` shortcut works inconsistently, while `Copy selection to clipboard` button always works

### ISSUE THREAD

**Issue by Ariandr** [flameshot-org/flameshot#2786]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 21.5.0
osx: 12.4

(But it happened on v11.0.0 and v12.0.0 too)

### Installation Type
.dmg file in release assets

### Operating System type and version

MacOS 12.4

### Description

I launch the screenshot capture with the hotkey combination.

When I'm done and want to copy to the clipboard, `CMD+C` sometimes works, sometimes doesn't.

But when I click `Copy selection to clipboard` button, it always works.

Moreover, I didn't find a pattern why `CMD+C` is not working consistently. It can suddenly stop working even though it worked 3 minutes before. And then in 5 minutes start working again.

### Steps to reproduce

1. Launch Flameshot from Applications
2. Run hotkey combination to Take screenshot
3. Select needed area
4. Press `CMD+C` to copy to the clipboard

Actual result:
- Sometimes nothing happens, window is not closed, screenshot is not copied to the clipboard.

Expected result:
- Same behavior as when you click `Copy selection to clipboard` button, because it works consistently. Always copies the screenshot and closes the window.

### System Information

MacOS 12.4, Macbook Pro M1 Pro 16"

**Comment by Ariandr** [comment]
My configuration:

```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x14\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x16\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\x17\0\0\0\x11)
contrastOpacity=127
contrastUiColor=#ffffff
drawColor=#ff0000
drawFontSize=19
drawThickness=4
saveAsFileExtension=jpeg
savePath=/Users/aleks/Desktop
showDesktopNotification=false
startupLaunch=true
uiColor=#3d82ff
uploadWithoutConfirmation=true

[Shortcuts]
TAKE_SCREENSHOT=Ctrl+Shift+9
TYPE_CIRCLE=\x421
TYPE_COPY=Ctrl+C
```

**Comment by Ariandr** [comment]
@mmahmoudian 
I also noticed, that the problem might be not just with `CMD+C`. `CMD-Z` and other editing shortcuts don't work, when `CMD+C` doesn't work. So it might be the problem of shortcuts recognition during capture and editing.

**Comment by Ariandr** [comment]
It's not actual for me anymore. Happened while I was on another keyboard language, so my bad😅

**Comment by mmahmoudian** [comment]
No worries. We have gad this issue before and so far we don't have a final decision on how to approach this.

@borgmanJeremy do you think we can add an indicator somewhere on the screen to indicate that the keyboard is in another [non-Latin alphabet] language? Something like when capslock is on and SDDM kinda tell the user about it
