### ISSUE TITLE
My adjustable color palette

### ISSUE THREAD

**Issue by sebastian-65** [flameshot-org/flameshot#2787]
### Feature Description

I mostly need same set of colors which would be super handy to configure as a palette. So you can easily pickup from colors you really do use.

**Comment by borgmanJeremy** [comment]
Can you explain this a bit more? The palette is fully customizable in version 12

**Comment by sebastian-65** [comment]
Oh! I still had the version 11, and after upgrade I see you have done exactly what I asked for! :+1:  Well done, and thank you so much! :1st_place_medal:
