### ISSUE TITLE
Add toggleable visual to confirm screenshot capture with -c and -s flags

### ISSUE THREAD

**Issue by cyrus01337** [flameshot-org/flameshot#2789]
### Feature Description

Thanks to the incredible API that the application uses, I'm able to create commands that allow me to capture specific regions and instantly have them copied to the clipboard. The only problem that I have is being able to discern when the application has actually copied in cases where Flameshot may not be running on my system, or when using the clipboard `-c`, accept on select `-s` and `--region` flags simultaneously.

Another possible alternative would be to create a flash similar to how Gnome desktop's screenshot at the selected region (or in the case where a screen is provided, the entire screen's dimensions).

An external workaround (for those wanting this if it ends up being difficult to implement/not implemented at all) is to use audio as a cue instead and play sounds conditionally via logic gates, i.e. when using PulseAudio's `paplay` that ships with Ubuntu (my OS):
```sh
flameshot gui && paplay success.wav || paplay fail.wav
```

**Comment by mmahmoudian** [comment]
Thank you for the feature request

> where Flameshot may not be running on my system

The `flameshot gui` can be run in one-off mode, meaning that you don't need to have the daemon running if you only want to capture a quick screenshot. Therefore if Flameshot is installed and nothing crashes, and you don't cancel the screenshot, the "failed" part of your code will never run.

> The only problem that I have is being able to discern when the application has actually copied

> An external workaround ... is to use audio as a cue instead

You can use `notifysend "screenshot was copied"`. This is a better solution as in mpst sane DEs you can suppress notifications by activating a Do Not Disturb mode.

> Another possible alternative would be to create a flash similar to how Gnome desktop's screenshot at the selected region

I know that macOS does this too, but I don't think it worth the trouble. Such feature means that we should then support all implementations of wayland and all tiling window managers in future, which might make the gain to cost ratio tilt towards unfeasible.

I'll leave this open for other devs to comment.

**Comment by cyrus01337** [comment]
I was not originally aware of `notifysend`, thank you kindly for the recommendation! :)
