### ISSUE TITLE
Please add a way to configure Flameshot to emulate the useful notification behavior of the screenshot tool in GNOME 42 (if it doesn't already exist)

### ISSUE THREAD

**Issue by venteto** [flameshot-org/flameshot#2791]
### Feature Description

I still use the GNOME screenshot tool when I don't need to annotate anything. One of the reasons is because when it creates a notification bubble that a new screenshot has been saved to my drive, all I have to do to open the saved image is click the notification bubble.

Flameshot also creates a notification bubble, but clicking it does not do anything. I still have to open my file manager, navigate to the folder where Flameshot saves images, and open the the image in gThumb manually.

I discovered the Ctrl + O shortcut to choose a program to open the capture with, but A) I can't seem to find a way to use that after saving the image explicitly (i.e., somewhere other than /tmp, and with a filename of my choosing), and B) I seem to have to invoke the keyboard shortcut every time (I was hoping it would self a configuration setting instead).

There may already be a way that I am unaware of to do what I want, so I'm trying to determine that first, before I have to turn around and convert this discussion topic into a separate enhancement request issue.

Thank you.

(I tried but was not able to post this in Discussions, the submit button would not work.)

**Comment by demonlibra** [comment]
You can add hotkeys to run flameshot and filemanager
`flameshot gui; nautilus`

**Comment by mmahmoudian** [comment]
@demonlibra Thank you for providing useful comment and practical example. I think it can be even improved by `--path` and then even opening the nautilus and select the file:

```sh
tmp_path="${HOME}/Pictures/$(date -u +"%Y-%m-%dT%H.%M.%SZ").png" ; flameshot gui --path "${tmp_path}" ; nautilus --select "${tmp_path}"
```

@venteto I don't use Gnome and at the moment I cannot test it on Gnome to see how it behaves, but it works perfectly fine on KDE. Not only the notification shows the path to the file, but it shows a preview of the image, clicking it would open the image, and using the hamburger menu on its right would let me open containing folder and etc.:

![2022-07-13_22-40](https://user-images.githubusercontent.com/390889/178828054-1942206f-0f00-4e07-a8f8-1330baa3e4ef.png)

I leave this open until I can see how Gnome would react, but in Linux world it is super easy to pull off these types of tasks as @demonlibra kindly mentioned.

> (I tried but was not able to post this in Discussions, the submit button would not work.)

perhaps you forgot to fill the title textbox

**Comment by venteto** [comment]
Ok, I will install a dropdown terminal and use a workaround in lieu of a feature, thanks.

@mmahmoudian Nah, I didn't forget to fill in the title textbox

**Comment by mmahmoudian** [comment]
@venteto 

> Ok, I will install a dropdown terminal and use a workaround in lieu of a feature, thanks.

Sarcasm can just take you so far! Instead let's learn a little bit for a change:
you can set that command as a keyboard shortcut in your gnome. If you don't know how:

https://www.cyberciti.biz/faq/howto-create-keyboard-shortcuts-in-gnome/
