### ISSUE TITLE
Bug Report Template Misspelled Word

### ISSUE THREAD

**Issue by Zer0F8th** [flameshot-org/flameshot#2795]
# Misspelled word in bug-report.yaml

Inside bug-report.yaml the word `recordig` is misspelled

```yaml
If you think it would be beneficial for us to understand the issue, please provide a screenshots or screen recordig. For screen recording you can use Peek
```

Sorry I know this is minor, but I thought I would bring it to flamshot's attention! :smile:

**Comment by borgmanJeremy** [comment]
If you would like to fix it before us you can submit a PR. The file is here:

https://github.com/flameshot-org/flameshot/blob/d4b39c2aaa66237630541d9a403e2e402c83e7cc/.github/ISSUE_TEMPLATE/bug-report.yaml

**Comment by Zer0F8th** [comment]
Great thanks! I submitted a PR (https://github.com/flameshot-org/flameshot/pull/2796).
