### ISSUE TITLE
Tool Settings window doesn't adjust to screen size (Windows 11)

### ISSUE THREAD

**Issue by manolol1** [flameshot-org/flameshot#2799]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11 Pro 21H2

### Description

When clicking the purple "Tool Settings" button (when screenshot mode is open), the tool settings window is cut off, because it's too high. (like on the image below

![image](https://user-images.githubusercontent.com/70203223/179360630-b30c9ccb-e1a8-4fb5-ac29-50cb45533dff.png)

(I only see that button on the secondary screen)

### Steps to reproduce

1. Start the screenshot mode
2. click the purple "Tool Settings" button on the left side of the screen

### Screenshots or screen recordings

_Already included in the description._

### System Information

OS: Windows 11 Pro Windows 11 Pro 21H2

Main Display: 
![image](https://user-images.githubusercontent.com/70203223/179360882-5ebcc0d8-d0ec-4250-9c71-b9883e2dda8a.png)

Secondary Display (the one, where the cut-off window is shown):
![image](https://user-images.githubusercontent.com/70203223/179360902-9a01dec9-3702-48af-920d-9c7384895e31.png)

_This is the first time, I started an issue on Github, so please inform me, if I did something wrong :)_

**Comment by manolol1** [comment]
I've now tried it on my Linux Mint (20.3 Cinnamon) Laptop, too, and it works perfectly fine here.
Seems like a Windows-Only problem.

**Comment by cuongzinza** [comment]
I got the same problem on Windows 11 with 2 monitors.
Why is this issued closed without discussion?

**Comment by mmahmoudian** [comment]
@cuongzinza which flameshot version are you using?
