### ISSUE TITLE
How to verify checksum on Windows

### ISSUE THREAD

**Issue by ScalableCodex** [flameshot-org/flameshot#2800]
So I'm fairly new to this, but I downloaded the .msi and the SHA256 for the .msi as well. But when I compare them, they're always different. Am I missing something? Doesn't seem very straightforward, and I've tried looking online for help.

**Comment by borgmanJeremy** [comment]
How are you comparing them?

**Comment by ScalableCodex** [comment]
> How are you comparing them?

Just using CMD. Cert Util -hashfile. It works fine for everything else I've done.

**Comment by mmahmoudian** [comment]
They are definitely a match:
![image](https://user-images.githubusercontent.com/390889/179525339-8a51b391-e652-4eba-abf5-6a41b8c87f0c.png)

I'm not a Windows user, so I have no idea how to do this, but Googling landed me on this page which seems to be relatively recent and have clear instructions:

https://www.shellhacks.com/windows-md5-sha256-checksum-built-in-utility/

> Cert Util -hashfile. It works fine for everything else I've done.

What is the exact command you are using? to me it seems you have forgot to specify which algorithm you want to use (note the last argument):

```powershell
certUtil -hashfile Flameshot-12.1.0-win64.msi SHA256
```

**Comment by ScalableCodex** [comment]
> They are definitely a match:
> 
> ![image](https://user-images.githubusercontent.com/390889/179525339-8a51b391-e652-4eba-abf5-6a41b8c87f0c.png)
> 
> 
> 
> I'm not a Windows user, so I have no idea how to do this, but Googling landed me on this page which seems to be relatively recent and have clear instructions:
> 
> 
> 
> https://www.shellhacks.com/windows-md5-sha256-checksum-built-in-utility/
> 
> 
> 
> > Cert Util -hashfile. It works fine for everything else I've done.
> 
> 
> 
> What is the exact command you are using? to me it seems you have forgot to specify which algorithm you want to use (note the last argument):
> 
> 
> 
> ```powershell
> 
> certUtil -hashfile Flameshot-12.1.0-win64.msi SHA256
> 
> ```

Yeah I use the entire command. Works for everything else like Pop_OS ISO, but not when comparing the two files for flame shot. I'll try again tomorrow.

**Comment by mmahmoudian** [comment]
> but not when comparing the two files for flame shot.

This command is not for comparing two files. You should calculated the checksum of the `.msi` file and compare the out put hash with the content of the `.msi.sha256sum`

**Comment by ScalableCodex** [comment]
> > but not when comparing the two files for flame shot.
> 
> This command is not for comparing two files. You should calculated the checksum of the `.msi` file and compare the out put hash with the content of the `.msi.sha256sum`

That's what I was trying to ask. I don't understand how this works. So I open up the hash file? How do I do that? I don't have any apps that can. 

So I just open it up, and THEN compare that number?

**Comment by mmahmoudian** [comment]
Ok, now I understood your question :) alright, this is very easy, but let me first go through one basic concept:

The SHA256 is one of the many algorithms we have to create a hash from data. Perhaps you have heard of MD5 and SHA1 before. These algorithms would get a series of 0s and 1s as input and generate a number as an output in form of a hash.

To check the integrity of a file using the checksum, you should:
1. download/obtain the target file
2. obtain the hash by the file provider (can be displayed on their website or in our case inside a text file)
3. calculate the checksum of the target file
4. compare the two numbers (which in our case is 68 character long)

Now, back to your question on how to open the file: it is a text file, so open it with any text editor you want. For example Notepad. If Windows is stupid and doesn't let you to open it in Notepad, then rename the file and add `.txt` at the end of the file and then open it with Notepad

**Comment by ScalableCodex** [comment]
> Ok, now I understood your question :) alright, this is very easy, but let me first go through one basic concept:
> 
> 
> 
> The SHA256 is one of the many algorithms we have to create a hash from data. Perhaps you have heard of MD5 and SHA1 before. These algorithms would get a series of 0s and 1s as input and generate a number as an output in form of a hash.
> 
> 
> 
> To check the integrity of a file using the checksum, you should:
> 
> 1. download/obtain the target file
> 
> 2. obtain the hash by the file provider (can be displayed on their website or in our case inside a text file)
> 
> 3. calculate the checksum of the target file
> 
> 4. compare the two numbers (which in our case is 68 character long)
> 
> 
> 
> Now, back to your question on how to open the file: it is a text file, so open it with any text editor you want. For example Notepad. If Windows is stupid and doesn't let you to open it in Notepad, then rename the file and add `.txt` at the end of the file and then open it with Notepad
> 
> 
> 
> Does this answer your question?

Omg wow yes. Thank you!! I can't believe it's that easy...I legit actually feel so stupid. I'm insanely thankful people like you exist. Got my hashes to match up!

Thanks again!

**Comment by mmahmoudian** [comment]
@ScalableCodex shall we close this issue?

**Comment by ScalableCodex** [comment]
> @ScalableCodex shall we close this issue?

Yup!
