### ISSUE TITLE
"Copy selection to clipboard" button description does not check for "Copy on double click" selection from config -> General

### ISSUE THREAD

**Issue by dsticks** [flameshot-org/flameshot#2807]
### Flameshot Version

v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

"Copy selection to clipboard" button description does not check for "Copy on double click" selection from config -> General, so the text for the pop-up button description always adds "or Left Double-Click" whether that option is checked or not in config -> General

### Steps to reproduce

run Flameshot gui
select an area
hover over "copy selection to clipboard" button
description will display "<shortcut> or Left Double-Click" whether the double click config option is checked or not.

### System Information

Confirmed using Windows 10 and Ubuntu 22.04
64 bit (both OSes)

**Comment by se7en-x230** [comment]
flameshot 12.1.0-1 on arch same problem.
Neither double click nor icon adds the image to the clipboard.

**Comment by mmahmoudian** [comment]
This issue is resolved via #2806

@se7en-x230 your issue is completely different. Please create a new issue
