### ISSUE TITLE
subcommand launcher should not remember the last 'WxH+x+y'

### ISSUE THREAD

**Issue by JohanChane** [flameshot-org/flameshot#2811]
### Feature Description

Because sometime need to delay to take a screenshot, i set a shortcut using 'flameshot launcher'.  Now I have to adjust the region instead of  just drawing a region.

**Comment by mmahmoudian** [comment]
1. You can always draw a new region. Just start selecting a region outside of the current region
2. You can start Flameshot with delay without opening the launcher. For example the following starts it after 2 seconds:
```sh
flameshot gui --delay 2000
```
For more information about commandline arguments visit our website:
https://flameshot.org/docs/advanced/commandline-options/

**Comment by JohanChane** [comment]
How about adding a "reset" button or 'flameshot launcher --reset'.

**Comment by JohanChane** [comment]
Click the outside of the selected region. And I can reselect the region.

**Comment by mmahmoudian** [comment]
> Click the outside of the selected region. And I can reselect the region.

That's literally the first thing I suggested. I'm glad you have found it sufficient and satisfactory
