### ISSUE TITLE
flameshot screen -c bug on dual monitor (X11)

### ISSUE THREAD

**Issue by porudev** [flameshot-org/flameshot#2815]
### Flameshot Version

latest

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux

### Description

when i use flameshot screen -c one of my monitor return a black stuttering image

### Steps to reproduce

run flameshot screen -c
both via command or bindsym of i3

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/81072838/180373375-9671d502-fbff-4e85-b912-40647a88e88c.png)
![image](https://user-images.githubusercontent.com/81072838/180373400-7f796077-d718-4ab1-9343-807ff60bf0c1.png)

First and second monitor screenshot result

### System Information

- Version:
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

- System:
  Host: poru-pc Kernel: 5.18.12-arch1-1 arch: x86_64 bits: 64 Desktop: i3
    v: 4.20.1 Distro: Arch Linux
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 515.57
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: intel,nvidia unloaded: modesetting,vesa
    gpu: i915,nvidia,nvidia-nvswitch resolution: 1: 1920x1080
    2: 1920x1080~144Hz
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 22.1.3
  
- DSP: X11
  
- Monitors: 2
 0: +*eDP1 1920/340x1080/190+1920+0  eDP1
 1: +HDMI-1-0 1920/521x1080/293+0+0  HDMI-1-0

**Comment by porudev** [comment]
> 

Sorry my bad for quoting it wrong, i've tried switch to the flameshot-git version from aur and the problem still persist

may i ask how to identify which monitor is intel or nvidia, thank you!

**Comment by mmahmoudian** [comment]
>  i've tried switch to the flameshot-git version from aur and the problem still persist

Thanks for trying it out and reporting it

> how to identify which monitor is intel or nvidia

My guess is that you are on a laptop with dual GPU and based on the information you provided I can tell that you have connected the external monitor using HDMI, your monitors have the same resolution, are arranged horizontally, and the external monitor is located on the left side of your laptop monitor. If my understanding is correct, of your setup, the external monitor is on the Nvidia and your laptop display is on Intel.

**Comment by porudev** [comment]
> 

welp you quote that totally correct, do you need more information

**Comment by mmahmoudian** [comment]
> do you need more information?

Yes, you still haven't mention which monitor is affected and which monitor works. Is it the laptop monitor?

**Comment by porudev** [comment]
> > do you need more information?
> 
> Yes, you still haven't mention which monitor is affected and which monitor works. Is it the laptop monitor?

the laptop monitor didn't work, the HDMI however work perfectly!
