### ISSUE TITLE
Can not disable whole area automatic screenshot when making screenshot from icon tray 

### ISSUE THREAD

**Issue by coolspawn** [flameshot-org/flameshot#2816]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-41-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux: 5.15.0-41-generic ubuntu: 22.04

### Description

When clicking Take Screenshot menu from tray, got preview window with already made screenshot without any ability to chose area.

### Steps to reproduce

Start Flame Shot
Open menu in the tray
Chose Take Screenshot

### Screenshots or screen recordings

[Screencast from 22.07.2022 08:17:37.webm](https://user-images.githubusercontent.com/49014515/180375749-821d7f9b-fe3f-4fbd-98b9-c5e7001300ce.webm)

### System Information

![image](https://user-images.githubusercontent.com/49014515/180375881-4a663f02-5480-4f95-839c-1330864f2685.png)

**Comment by mmahmoudian** [comment]
@coolspawn please always search in all issues (not just the open ones).
