### ISSUE TITLE
Screenshot Save Path Option not Available

### ISSUE THREAD

**Issue by g-h-97** [flameshot-org/flameshot#2827]
### Flameshot Version

```console
~ $ flameshot -v
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.4
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Voidlinux

### Description

Based on issue number #2818. Here is my config file bellow:

```ini
[General]
disabledTrayIcon=false
drawColor=#008bff
drawThickness=3
savePath=/home/user/Pictures/
showStartupLaunchMessage=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

### System Information

Voidlinux
Linux pc 5.18.11_1
DWM
Xorg

**Comment by mmahmoudian** [comment]
Interesting! Does it start working if you add `filenamePattern=%F_%H-%M` to the `[General]` section of your config file?

**Comment by g-h-97** [comment]
Sorry for my late response !

What I meant is that, I would like to be able to choose a file name even if the `-p` path option is set. Since in this case it automatically uses the `filenamePattern` format.

**Comment by mmahmoudian** [comment]
> I would like to be able to choose a file name even if the `-p` path option is set.

The `--path` is a [Final Action](https://flameshot.org/docs/advanced/commandline-options/#final-actions) and when it is set in the CLI, the file will be saved without question. You have few options if you want to be asked about the file name:
1. you can set `savePathFixed=false` to make flameshot ask you for file name and suggest a filename with the pattern you suggested with `filenamePattern=%F_%H-%M` inside the folder you have defined by `savePath=/home/mehrad/Pictures`. This way you can use `flameshot gui` and it works as you have asked.
2. if you want to use an alternative path for some reason and do not want to change your `savePath` settings, you have to get it and parse it yourself in bash/zsh (you can even [use yad](https://sanana.kiev.ua/index.php/yad)).

The Final actions are meant for when you know what you want to do with your screenshot. There is no need to pass any of the Final Action arguments when you don't know the final faith of your screenshot.

Does these answer your question?

**Comment by g-h-97** [comment]
Yeah, since there is no way to do it using Flameshot CLI a did what you just suggested. I used a bash script and dmenu to do it.

@mmahmoudian , Thank you very much for the details, I truly appreciate you time.

**Comment by mmahmoudian** [comment]
I myself have a project named [dmenu_flameshot](https://codeberg.org/mehrad/dmenu_shot) which does things that is either out of the scope of Flameshot or things that are not yet implemented and I needed them. PRs are also welcome on that repo if you think you have an elegant way to do it that can help others ;)
