### ISSUE TITLE
Appending text to the name of the file,  while screeshooting

### ISSUE THREAD

**Issue by hubyhuby** [flameshot-org/flameshot#2847]
### Feature Description

USE CASE
I am using a lot flameshot, especially the "floppy icone" to save to file with a schem like this
ScrShot-%d-%b
Also I  end up with **thousands of files**, ordered by date.
**I have no keywords to find what a picture is related to.**

PROPOSED SOLUTION

1) a text field - next to the floppy icone - while snapshooting .
2) This text field  would be appended to the file name after pushing save
3) Optional : when screenshooting a 2nd time the text field wouldn NOT be reseted. At least in my use case, I often do series of snapshots, for example "work for company 1", "photos for the blog", "design sprint cocacola"...
4) Optional : beeing able to define a folder schem. Like %TextFfolder : would save in the entered SUB folder (without reseting the text aswell)
(alternate solution : the current 'T' text icone to write on the picture could be appended to the name of the file)

Example :
Proposed patern : ScrShot-%d-%b-%text  => ScrShot-02-août_2-MyOwnTypedText.png
OLD patern : ScrShot-%d-%b  => ScrShot-02-août_2.png

![image](https://user-images.githubusercontent.com/26340942/181685064-53e8d527-b19d-42ba-a6b4-413546ec0523.png)
Instead of lists of unknown files, like this one, I could search by name the screen shots : 
![image](https://user-images.githubusercontent.com/26340942/181685770-6a29dffe-9691-44c9-a283-a0520fe98fe9.png)

PS: I have checked in "enhancements" and didn t find this request
Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
Thanks for this super software !

**Comment by mmahmoudian** [comment]
I'm against this suggestion. With the current implementation the user have the chance to choose the file name (after clicking on the save button, a window opens and asks for the name). If you don't see that window, then it means you have checked this box (the checkbox should not be marked if you want to modify the file name or path):

![image](https://user-images.githubusercontent.com/390889/181724713-22a281a8-5ea0-440b-9519-7d4b2079cd41.png)

**Comment by hubyhuby** [comment]
Ha interesting, I didn t understand this option (I understood path as folder). Just tried it.
Only when saving with this option, you don t have the "ScrShot-%d-%b-%text " you have defined.
This would be perfect if the defined schem name of the file would be proposed. For now it is empty. 
![image](https://user-images.githubusercontent.com/26340942/181810779-d2092b26-567c-4abf-a609-b175779f49fe.png)

**Comment by mmahmoudian** [comment]
The name should be there based on the pattern you define. If it is not there, it is a bug and should be reported.
