### ISSUE TITLE
Does not work in crontab

### ISSUE THREAD

**Issue by aivchen** [flameshot-org/flameshot#2851]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Manjaro Linux

### Description

flameshot is working from console but not from cron

### Steps to reproduce

crontab:
```* * * * * flameshot full -p ~/Screenshots/```

The error:

```
systemctl status cronie

авг 01 12:14:01 manjaro CROND[85927]: (andrew) CMD (flameshot full -p ~/Screenshots/)
авг 01 12:14:01 manjaro flameshot[85927]: qt.qpa.xcb: could not connect to display
авг 01 12:14:01 manjaro flameshot[85927]: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
авг 01 12:14:01 manjaro flameshot[85927]: This application failed to start because no Qt platform plugin could be initialized. Reinstallin>
                                             
                                             Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland->
авг 01 12:14:01 manjaro CROND[85926]: (andrew) CMDEND (flameshot full -p ~/Screenshots/)
авг 01 12:14:01 manjaro CROND[85926]: pam_unix(crond:session): session closed for user andrew
```

### System Information

- i3wm
- Xorg
- Manjaro Linux 21.3.6

**Comment by nullobsi** [comment]
The QT error says
> could not connect to display

This isn't a flameshot bug but a natural issue with the way cron jobs work :)

Cronie runs as a systemd service and so does not run under the same environment that all your GUI runs as. There are a few different things you can try, but they seem like hacky workarounds. Some ideas I have:
- when your x11 session runs, under .xinitrc or in a startup application store the DISPLAY, XAUTHORITY and other related x11 variables to a file you can load from a script in cronie
- just try DISPLAY=:0?
- start flameshot in the GUI as a tray icon so it communicates over DBus

not sure if any of these will work, but good luck getting it working

**Comment by veracioux** [comment]
@nullobsi On my machine (Arch Linux, i3wm, X11) setting `DISPLAY=:0` works.
Also note that since flameshot version 11 the daemon does not need to be running for the other commands to work (`flameshot gui`, `flameshot full` etc), unless the screenshot is being saved to the clipboard or pinned, in which case the daemon should be launched automatically.
