### ISSUE TITLE
FS not working in Fedora 36 Gnome 

### ISSUE THREAD

**Issue by thorrrr** [flameshot-org/flameshot#2855]
### Flameshot Version

Mine does not have an about

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 36 Gnome 

### Description

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                1/1 
  Installing       : kf5-filesystem-5.96.0-1.fc36.x86_64                                                                                            1/5 
  Installing       : kf5-kguiaddons-5.96.0-3.fc36.x86_64                                                                                            2/5 
  Installing       : qtlockedfile-qt5-2.4-36.20150629git5a07df5.fc36.x86_64                                                                         3/5 
  Installing       : qtsingleapplication-qt5-2.6.1-43.fc36.x86_64                                                                                   4/5 
  Installing       : flameshot-12.1.0-1.fc36.x86_64                                                                                                 5/5 
  Running scriptlet: flameshot-12.1.0-1.fc36.x86_64                                                                                                 5/5 
  Verifying        : qtlockedfile-qt5-2.4-36.20150629git5a07df5.fc36.x86_64                                                                         1/5 
  Verifying        : qtsingleapplication-qt5-2.6.1-43.fc36.x86_64                                                                                   2/5 
  Verifying        : flameshot-12.1.0-1.fc36.x86_64                                                                                                 3/5 
  Verifying        : kf5-filesystem-5.96.0-1.fc36.x86_64                                                                                            4/5 
  Verifying        : kf5-kguiaddons-5.96.0-3.fc36.x86_64                                                                                            5/5 

Installed:
  flameshot-12.1.0-1.fc36.x86_64                              kf5-filesystem-5.96.0-1.fc36.x86_64               kf5-kguiaddons-5.96.0-3.fc36.x86_64     
  qtlockedfile-qt5-2.4-36.20150629git5a07df5.fc36.x86_64      qtsingleapplication-qt5-2.6.1-43.fc36.x86_64     

### Steps to reproduce

I have just moved over from Zorin and used FS daily no issues. BUt now in Fedora 36 installed from terminal and it will not work.
It grabs image but no edit options popup is makes a sound it has captured but error pops  up unable to save.
Just cannot get anything in it to work 

### System Information

![image](https://user-images.githubusercontent.com/8170673/182567975-19715429-68c4-40cd-826b-b0277b9ad070.png)

**Comment by mmahmoudian** [comment]
Please always use a title that explains the issue. "not working" is not informative.

> ## Flameshot Version
> 
> Mine does not have an about

This is not possible. Plus you can run `flameshot --version` in your terminal. Based on the rest of your post I'd say it is `flameshot-12.1.0`

> I have just moved over from Zorin

And you were not using Gnome Wayland before

> It grabs image but no edit options popup is makes a sound it has captured but error pops up unable to save.

And you have a "Share" button on the top-right corner of that window. If my assumption is correct, then read the following:
- https://flameshot.org/docs/guide/wayland-help/#gnome-wayland
- https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+is%3Aclosed+label%3ADuplicate+label%3A%22Won%27t+Fix%22+gnome

and if the issue is resolved, please close this issue, otherwise explain exactly what happens and what is wrong. You can record a short video to show us what the issue is.

**Comment by thorrrr** [comment]
Hi
Sorry I had not seen this when searching, this is very reminiscent od what Windows or IOS do
There app is very poor lacks major functionality and badly designed.
Looks like back to wine and fastone capture. I feel for you guys doing all this hardwork i hope it gets resolved

**Comment by thorrrr** [comment]
Cheers for the help

**Comment by mmahmoudian** [comment]
@thorrrr of course you can get rid of Gnome and use KDE (what I use), Xfce, LXQt, or any other alternative.

**Comment by thorrrr** [comment]
I know but i do not want to do a full reinstall again. I know you can convert but been told by several it can corrupt files and directories

**Comment by mmahmoudian** [comment]
Actually you don't need to reinstall or convert, just install KDE or whatever alongside of Gnome and use that. Also, nothing gets corrupted, if you purge Gnome meta package, you might have to install some of them back as dependencies of some of your installed software. But installing alongside gives you the freedom to choose. Freedom is what Linux and FOSS ls all about, something that is jot fully comprehended by certain devs I guess.

**Comment by thorrrr** [comment]
you mean like a dual boot to copies of Fedora Gnome  KDE?

**Comment by mmahmoudian** [comment]
No, it is not dual boot. It is the same OS, just a different software as window manager. One example instruction:

https://www.linuxcapable.com/how-to-install-kde-plasma-desktop-on-fedora-36-linux/
