### ISSUE TITLE
in Tooltips and config, upper/lower case of the keybindings are not respected

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2856]
### Flameshot Version

Flameshot v12.1.0 (001726a5)

### Installation Type

User repository (AUR)

### Operating System type and version

5.15.57-2-MANJARO

### Description

At the moment the in the tooltips and config window, all keybindings are shown as upper-case letters where as they only work when the key is pressed without holding the <kbd>Shift</kbd>. A little more investigation also shows that the config file also contains upper-case letters. This means that although Flameshot is capable of recognizing upper and lower-case letters (e.g `T` doesn't work but `t` does), the user does not have the option to use upper case for one keybinding and lower-case for another.

I suggest:
1. display the correct form of the keybinding          **<- the bug**
2. letting user to also utilize upper-case bindings   **<- the feature request**

### Screenshots or screen recordings

Showcasing tooltip:

![image](https://user-images.githubusercontent.com/390889/182840652-227aef85-37f3-47d5-81bd-0fabacee971d.png)

Showcasing config window:
![image](https://user-images.githubusercontent.com/390889/182841046-d25564ed-f96c-426a-9be8-e0208761d482.png)

Showcasing the message box:
![image](https://user-images.githubusercontent.com/390889/182842068-310df2e6-d0fb-4421-8de8-2d2ab4907903.png)

### System Information

```console
❯  inxi --system --graphics --width=80
System:
  Host: aaa Kernel: 5.15.57-2-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.6 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CometLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Lexa XT [Radeon PRO WX 3200] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.4 driver: X: loaded: amdgpu,modesetting
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1080x1920~60Hz
    3: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon Pro WX 3200 Series (polaris12 LLVM 14.0.6 DRM
    3.42 5.15.57-2-MANJARO) v: 4.6 Mesa 22.1.4
```

**Comment by mmahmoudian** [comment]
@Tomasito665 Thanks for your comment, but I disagree. This would make the non-tech savvy users confused. Take a look at any software out there, the key combination is presented as lower case.

**Comment by Tomasito665** [comment]
@mmahmoudian I agree that `T` could suggest a `Shift + T` key combination. However, representing a `Shift + T` combination simply with an upper-case T is ambiguous in some cases. Take the Greek keyboard layout, for example, which yields an upper-case sigma for both keys W and S. Given a shortcut represented with `Σ`, you would have no way to tell whether the shortcut is `Shift + W` or `Shift + S`. 

What do you think of Google's approach to Chrome's keyboard shortcut descriptions? It defines all shortcut descriptions with lower-case letters and prepends shift-modified ones with `Shift +`. This takes away the confusion you describe and is not ambiguous.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/12563382/193536570-db0c9054-01c7-48d2-98a0-d00eed1570ea.png">

https://support.google.com/chrome/answer/157179

**Comment by borgmanJeremy** [comment]
I think @Tomasito665 latest proposal is the way to go.

**Comment by mmahmoudian** [comment]
> However, representing a Shift + T combination simply with an upper-case T is ambiguous in some cases. 

This is exactly my point number 1. We should show the lower case, and show the modifier keys if they are used. I'm not suggesting to use `T` but rather show `Shift+t`.

**Comment by borgmanJeremy** [comment]
Ohhhh ok I misunderstood

**Comment by Tomasito665** [comment]
> > However, representing a Shift + T combination simply with an upper-case T is ambiguous in some cases.
> 
> This is exactly my point number 1. We should show the lower case, and show the modifier keys if they are used. I'm not suggesting to use `T` but rather show `Shift+t`.

We are on the same page, then :-)

**Comment by Tomasito665** [comment]
I went ahead and gave it my best shot. _Humongous_ pull request:
https://github.com/flameshot-org/flameshot/pull/2934

**Comment by mmahmoudian** [comment]
@Tomasito665 yeap, it took me thousands of milliseconds to read the changes 😅 thanks for the PR. Simple and efficient as far as I can tell. 👍

**Comment by Tomasito665** [comment]
Are there any pending tasks for this issue? If not, let's close it! :-)

**Comment by mmahmoudian** [comment]
Thanks again for the PR. I'm closing this now.
