### ISSUE TITLE
Tray icon disappeared from menu bar

### ISSUE THREAD

**Issue by Tizian512K** [flameshot-org/flameshot#2858]
### Flameshot Version

Because of the missing tray icon I couldn't find the version

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Montery 12.4

### Description

The tray icon in the menu bar of macOS disappeared and there is no possibility to bring it back. I've tried to delete and reinstall flameshot but it still saves his settings without the icon

### Steps to reproduce

1. install flameshot on Mac
2. remove the icon from the menu bar
3. try to bring it back

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/88047865/183069085-d3c2ff33-6d21-4ba3-9c30-01f530c64d16.png)

### System Information

MacOS Montery 12.4

**Comment by borgmanJeremy** [comment]
You can run flameshot config to bring up the config menu and re-enable the icon

**Comment by mmahmoudian** [comment]
> Because of the missing tray icon I couldn't find the version

`flameshot --version`

> I've tried to delete and reinstall flameshot but it still saves his settings without the icon

Have you tried the following?
1. checking if you have `disabledTrayIcon=true` in your config file (`~/.config/flameshot/flameshot.ini`) and setting it to `false`?
2. restarting your computer

**Comment by Tizian512K** [comment]
Thank you for your tips. In the terminal it doesn't find flameshot commands 
![image](https://user-images.githubusercontent.com/88047865/183087213-0401e1e9-ddcb-4b1a-a9b1-2b43ef5f5b42.png)

**Comment by Tizian512K** [comment]
Turns out flameshot was present only at `/Applications/flameshot.app/Contents/MacOS/flameshot` which was not included in my `$PATH`.
I've now symlinked it to `/usr/local/bin/flameshot` with the help of a friend.
After then following your steps the tray icon is visible again.

**Comment by cchaglund** [comment]
How to symlink:

`ln -s /Applications/flameshot.app/Contents/MacOS/flameshot /usr/local/bin/flameshot`
