### ISSUE TITLE
Flameshot does not work on Ubuntu 22.04 with Wayland XDG Session

### ISSUE THREAD

**Issue by metaer** [flameshot-org/flameshot#2859]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-43-generic
ubuntu: 22.04

### Installation Type

Using the ready-made package from Github Releases
Snap installation behaves the same way

### Operating System type and version

Ubuntu 22.04.1 linux kernel: 5.15.0-43-generic

### Description

When I click Take screenshot from the menu of tray icon, nothing happens

### Steps to reproduce

Click tray icon, than click Take screenshot

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/6103208/183108378-798f75a4-80ef-46b3-b420-66fc48ea92d6.png)

### System Information

inxi --width 80 --system --graphics
System:
  Host: pavel-XPS-15-7590 Kernel: 5.15.0-43-generic x86_64 bits: 64
    Desktop: GNOME 42.2 Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: N/A
  Device-3: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 resolution: 3840x2160~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 22.0.5

**Comment by mmahmoudian** [comment]
Would you please record a video to show what happens

**Comment by metaer** [comment]
[Screencast from 05.08.2022 23:36:08.webm](https://user-images.githubusercontent.com/6103208/183159036-991d5bd8-04be-4924-bcc0-b3326e99798f.webm)

**Comment by metaer** [comment]
Nothing happens after clicking Take Screenshot

**Comment by metaer** [comment]
It worked well on Ubuntu 21.10. After upgrade to 22.04 it did not work. I uninstalled completely flameshot and after that tried to install via apt-get and via snap and via deb-package from github. And any of these ways does not work.

**Comment by metaer** [comment]
Does flameshot write any error logs, which I could attach?

**Comment by metaer** [comment]
I've tried to run command `flameshot gui` via terminal also.
Here is output:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

**Comment by metaer** [comment]
Switching xdg session type from Wayland to x11 helped.

**Comment by metaer** [comment]
I want to donate crypto for flamehot development. Can I do that? I need this software so much.

**Comment by metaer** [comment]
> Switching xdg session type from Wayland to x11 helped

But "copy to clipboard" feature does not work with x11

**Comment by metaer** [comment]
Running `flameshot` command via terminal (with x11) produces these errors:

> Qt: Session management error: Could not open network socket
> propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.306\" (uid=1000 pid=7976 comm=\"/snap/flameshot/183/usr/local/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=855 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
> nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.306\" (uid=1000 pid=7976 comm=\"/snap/flameshot/183/usr/local/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=855 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
> "Object path cannot be empty"

**Comment by metaer** [comment]
> But "copy to clipboard" feature does not work with x11

It works if I run "flameshot" command first and then run "flameshot gui" in new terminal tab, not cancelling flameshot command in the first terminal tab.

Why I use terminal command? Because it is very convenient to have custom shortcut in OS, which runs `flameshot gui`

**Comment by metaer** [comment]
> But "copy to clipboard" feature does not work with x11

Problem has gone after setting checkbox "Launch at startup" on in Configurration window and switching on flameshot in Startup Application Preferences.

**Comment by mmahmoudian** [comment]
For wayland please make sure you have installed xdg-desktop-portal-gnome:

sudo apt install xdg-desktop-portal-gnome
It can be a duplicate of #2199

For donation, read these:

- https://github.com/flameshot-org/flameshot/issues/1235

- https://flameshot.org/donate/

**Comment by metaer** [comment]
> For wayland please make sure you have installed xdg-desktop-portal-gnome

Thank you, I'll try it later

**Comment by mmahmoudian** [comment]
@metaer please let us know if the issue was resolved with installing xdg-portal

**Comment by metaer** [comment]
Ok

**Comment by metaer** [comment]
`sudo apt install xdg-desktop-portal-gnome`
It does not help when using wayland session

**Comment by xit4r** [comment]
> @metaer please let us know if the issue was resolved with installing xdg-portal

this doesn't work for me, on clicking take a screenshot or running `flameshot gui` command, a full-screen screenshot is taken, and when I click on the share button, then a proper flameshot gui appears but a full-screen screenshot being saved in the system and clicking on the share button is overhead.
I have:
Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
and `xdg-desktop-portal-gnome` is installed

**Comment by mmahmoudian** [comment]
@xit4r I have answered this more than 150 times so if you don't mind I will not waste my time on Gnome nonsense. Read this:
https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
