### ISSUE TITLE
Keyboard Shortcut wont Work (Xfce,Xubuntu 20.04.4)

### ISSUE THREAD

**Issue by CapeCrusader321** [flameshot-org/flameshot#2864]
### Flameshot Version

Flameshot info- Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 5.15.0-43-generic
org.kde.Platform: 5.15-21.08

Software- Xubuntu 20.04.4

### Installation Type

Flatpak from Flathub

### Operating System type and version

Xubuntu 20.04.4 (Xfce 4.14)

### Description

Issue- Keyboard Shortcut key wont work as expected.I replaced the xfce settings and configured it as given in Flameshot github page, but it wont work, some pics for better understanding;

![Bugs3](https://user-images.githubusercontent.com/100503303/183570757-0583cc29-ed1e-4711-8b10-4ae1e99ac111.png)
![Bugs2](https://user-images.githubusercontent.com/100503303/183570764-1c8a5638-15e4-4f3f-bb80-67c232464526.png)
![Bugsx](https://user-images.githubusercontent.com/100503303/183571400-f808d1e3-e3f0-4fa0-a5fe-af231123f264.png)

### Screenshots or screen recordings

![Bugs3](https://user-images.githubusercontent.com/100503303/183570420-f38209aa-99b2-4fa4-b623-9a366c18ac7c.png)
![Bugs2](https://user-images.githubusercontent.com/100503303/183570424-6dc54cf5-2afb-4b66-bbf7-efddd49d12a4.png)
![Bugsx](https://user-images.githubusercontent.com/100503303/183571400-f808d1e3-e3f0-4fa0-a5fe-af231123f264.png)

### System Information

Xubuntu 20.04.4
Xfce ver.- 4.14
Display resolution -1366*768, 60.3 Hz
Xorg

**Comment by mmahmoudian** [comment]
This is because flatpaks don't put the binary in the path. This is explained on our website with two ways to solve it:
https://flameshot.org/docs/installation/installation-linux/#flatpak

**Comment by Anuranj-Krishnan** [comment]
Or you can use the command of flameshot app from menu by adding it to the panel as app launcher. Then go to properties of that app from panel, there you'll find command. Just copy that command, paste it in keyboard shortcut of "Print". Add " gui" at the end of the command.
