### ISSUE TITLE
flameshot tray icon turned dark and is basically invisible now

### ISSUE THREAD

**Issue by Ryder17z** [flameshot-org/flameshot#2867]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
linux: 5.15.59-1-MANJARO
manjaro: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Manjaro 21.2.6

### Description

I can not find an option to revert to the white systray icon.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/2000703/183976333-19f38f21-1b7e-4bb7-a554-5882821c53cf.png)

### System Information

xfce

**Comment by singhayushh** [comment]
this is most likely a bug from the distribution's side instead of flameshot. The icon theme you're using is probably the one to blame.

**Comment by Ryder17z** [comment]
I don't know. changing that doesn't help the issue.

**Comment by mmahmoudian** [comment]
The tray icon is based the icon pack which is typically chosen by your computer based on having a light or dark theme. I don't think we can do anything about it. There was a discussion in the past to make the tray icon customizable, but it is not planned yet as far as I can remember.

**Comment by Ryder17z** [comment]
the issue reverted itself
