### ISSUE TITLE
Impossible to have the screenshot launcher

### ISSUE THREAD

**Issue by sebastienserre** [flameshot-org/flameshot#2869]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-46-generic
ubuntu-core: 20

### Installation Type

Snap from Snapcraft

### Operating System type and version

Ubuntu 22.04

### Description

When I want to create a snapshot by launching the launcher to select the area and maybe use the tool to create arrows r something, Ubuntu is taking the screenshot directly...

### Screenshots or screen recordings

https://user-images.githubusercontent.com/3902621/184294765-ea4d7f10-225c-4e22-8a66-a3c57e6deaf9.mp4

### System Information

Default Ubuntu 22.04 with Gnome default

**Comment by omersi** [comment]
same here.

**Comment by sebastienserre** [comment]
I've restarted many times and still have this issue....

**Comment by borgmanJeremy** [comment]
!gnome41

**Comment by sebastienserre** [comment]
This is not the purpose of my issue. The screenshot is made (without my permission) directly without the Flameshot launcher.

**Comment by borgmanJeremy** [comment]
It’s the same root cause

**Comment by borgmanJeremy** [comment]
Hit share and the launcher will ipen

**Comment by mmahmoudian** [comment]
@sebastienserre  this has been explained here:
https://flameshot.org/docs/guide/wayland-help/#gnome-wayland

**Comment by sebastienserre** [comment]
In my case, Ubuntu doesn't ask me to share the screen. It take a screenshot directly with the Gnome default app and then ask to share it by e-mail or other ways.
But OK, this won't be fixed.

**Comment by mmahmoudian** [comment]
@sebastienserre 
> In my case, Ubuntu doesn't ask me to share the screen. It take a screenshot directly with the Gnome default app and then ask to share it by e-mail or other ways.

Would you please record your screen to demo what is happening. What you are explaining is not consistent with the video you shared initially (the arrow is added by me to point to the "Share" button):

![image](https://user-images.githubusercontent.com/390889/185392715-1a8bd156-c915-4f22-b37a-22d3d8e7db5a.png)

**Comment by mozesj** [comment]
Thank you @mmahmoudian this has been my case since upgrade from Ubuntu 20.04 to 22.04.

**Comment by mmahmoudian** [comment]
> Thank you @mmahmoudian this has been my case since upgrade from Ubuntu 20.04 to 22.04.

For the millionth time: This is because Ubuntu switched to Gnome Wayland and that is the problem with Gnome Wayland that you get this. If you are unhappy, change to Kubuntu or something else and stop using Gnome. Or go and complain to Gnome. All info are available on our website:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time


You yourself chose to use Gnome, you are now suffering from their design. We in Flameshot **cannot do anything about this**. We do not develop Gnome. We are **not** responsible for mistakes and bad designs of other software. Please try to understand this.

**Comment by sebastienserre** [comment]
Wow what a violent message !
Try to understand we have a problem with Flameshot, so we report to Flameshot.

For others, in the Ubuntu Start session, you can select to use "Ubuntu on Xorg" https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop

**Comment by mmahmoudian** [comment]
@mozesj Thanks to constructive criticism of @sebastienserre I modified my last comment to make it sound ultra accurate and subsequently less "harsh"
