### ISSUE TITLE
[Question] How to update Flameshot to the latest version without reinstalling it ?

### ISSUE THREAD

**Issue by kevinadhiguna** [flameshot-org/flameshot#2876]
### Flameshot Version

*Flameshot version* (copied directly from Flameshot) :

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-46-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04.1

### Description

I installed Flameshot via a package manager (apt). However, I want to update it to the latest version (my current version is v11.0.0 but the latest version now is v12.1.0).

This is what dropdown of Flameshot shows : 

![flameshot-update](https://user-images.githubusercontent.com/43397636/185500247-83a2fd5c-ffb6-4727-800f-cd3708bfff7d.png)

---

I tried to update it : 
```
$ sudo apt install flameshot
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
flameshot is already the newest version (11.0.0-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

It said it already has the newest version installed (v11.0.0-2) which should not be true. Is it possible to update Flameshot via a package manager (apt) without reinstalling it ?

### Steps to reproduce

1. Install Flameshot via apt : `sudo apt install flameshot`
2. See there is an update saying v12.1.0 in Flameshot, after launching it
3. Try to update it (without reinstalling it) : `sudo apt install flameshot`
4. See the logs saying : `flameshot is already the newest version (11.0.0-2).` (failed to update via apt)

### System Information

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-46-generic
ubuntu: 22.04

**Comment by mmahmoudian** [comment]
Your question is not specific to Flameshot.

#### Some general info that you don't know

In Linux world we have roughly two types of distros: point-release (e.g debian, Ubuntu), and we have rolling-release distros (e.g Arch, Solus). The rolling release distros are constantly getting software updates, but although rarely, also have the risk of things not working properly (e.g Nvidia driver gets updates and your computer does not boot into a graphical environment). On the other hand, a point-release distro brings more "stability", but:
1. The softwares do not get frequent updates
2. There are version numbers (e.g Ubuntu 20.04) that user have to upgrade the whole system when a new system update comes (e.g Ubuntu 22.04).

Alternatively, there are some point-release distros with a fast cycles that are getting releases much quicker (e.g Fedora), but they are point release nonetheless. Some distros have one point-release and one rolling-release type (e.g Opensuse Leap and Opensuse Tumbleweed)

In the following link you can see which distros has what version of Flameshot (green is latest, and red is already old version):

https://repology.org/project/flameshot/versions

#### How to solve your problem

You can either (**from least to most convenient**):

- switch to a rolling release (I suggest you to stick to Ubuntu or Fedora until you learn Linux a bit more)

- download the .deb file from our Github release page and install that using `dbkg -i XXXX.deb` where the `XXXX.deb` is the .deb file

- install it via a distro-agnostic method: Flatpak, Snap, or AppImage. For instructions read:
 https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

**Comment by Dh42** [comment]
If you are going to be snarky at someone at least provide a working command.  `dbkg -i XXXX.deb` whats dbkg?
