### ISSUE TITLE
Double click to save the image to the save path or copy it to the clipboard

### ISSUE THREAD

**Issue by zkyf** [flameshot-org/flameshot#2877]
### Feature Description

This tool is the best one I've seen on ubuntu. It would be great if this tool allows the user to save the image to the save path, or copy to the clip board by double clicking the screen. The behavior of double click can be configured in the config GUI. Such interaction is more efficient for users like me who need to take a lot of screenshots while writing reports.

**Comment by mmahmoudian** [comment]
> It would be great if this tool allows the user to save the image to the save path

It does. you can either configure it from the Configurations window, or you can use the CLI. Read more about the CLI here:
https://flameshot.org/docs/advanced/commandline-options

> copy to the clip board by double clicking the screen

![image](https://user-images.githubusercontent.com/390889/185634973-424016a9-c9d4-4f19-9eea-7686b1237f5e.png)

Does these answer your question?

**Comment by zkyf** [comment]
Thanks! I missed that

**Comment by mmahmoudian** [comment]
No worries, we are thinking about restructuring the whole configuration window layout to make it easier to find stuff. Do let us know if you have any other ideas or question. We'll be happy to help.

**Comment by zkyf** [comment]
It would be better to group the setting options into several smaller tabs like:
* **User Interface**: whether to show some panels/buttons, launch at startup etc
* **Screenshot Interaction**: use last region, double click to copy, save image after copy, undo limit etc
* **Image Setting**: save path, file format, whether to use JPG for clipboard etc
* **Upload**: imgur client id, copy url after upload etc.
