### ISSUE TITLE
MacOS Monterey 12.5.1 & Flameshot v12.1.0 opens on a new MacOS screen

### ISSUE THREAD

**Issue by victortrac** [flameshot-org/flameshot#2881]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Monterey 12.5.1

### Description

Flameshot used to work great, but now it just opens a new MacOS Screen (like a full-screen app in MacOS), so any screenshots I highlight are just my desktop.  This happens every time since something on my system updated a couple of months ago.  

### Steps to reproduce

1. Click on "flameshot" icon and select "Take screenshot"
2. The flameshot mouse selector opens on an new, empty MacOS screen.  Swiping back to the screen that I want to take the screenshot from makes the flameshot selector go away.

### System Information

1. MacOS Monterey 12.5.1
2. M1 Macbook Pro 14"

**Comment by mmahmoudian** [comment]
Please read https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

You need to to delete the permission and set it again
