### ISSUE TITLE
 Moving the drawn

### ISSUE THREAD

**Issue by LeraTroy** [flameshot-org/flameshot#2882]
### Feature Description

Greetings. I represent a group of CG artists. We really enjoyed your Flameshot app. But we are missing one feature. Please add the ability to move what is already drawn over the selected area. Thanks

**Comment by borgmanJeremy** [comment]
This is possible in the latest version

**Comment by LeraTroy** [comment]
Tell me please how can i do this? I could not find the movement of drawn objects in the application

**Comment by LeraTroy** [comment]
I have v12.1.0

**Comment by borgmanJeremy** [comment]
You just click the object and can move it with the mouse

**Comment by LeraTroy** [comment]
Hmmmm, i see that i can move the whole screenshot area, nore the drawings. Maybe i've select any tool?

**Comment by LeraTroy** [comment]
after clicking the right mouse button on the drawn object, a new object is drawn. the old one doesn't move

**Comment by LeraTroy** [comment]
![image](https://user-images.githubusercontent.com/111787311/185994994-801cb3d2-caf3-4819-9674-9055f24cb413.png)

**Comment by borgmanJeremy** [comment]
Can you de select the active tool? I can post a gif when I’m at my pc next. Or there is an example in the gif of our main GitHub page

**Comment by LeraTroy** [comment]
Thanks to your last comment, I figured out how to move the drawing. I didn't really turn off the active tool. Thanks a lot!

**Comment by LeraTroy** [comment]
Thanks to your last comment, I figured out how to move the drawing. I didn't really turn off the active tool. Thanks a lot!

**Comment by mmahmoudian** [comment]
@LeraTroy It seems I'm late to the party, but there is also one other way to select objects: sidebar

Press SpaceBar on your keyboard and the sidebar will open. In that you can change the order of layers and also select all the items you have drawn even if they are hidden under other objects.


Shall we consider this issue closed?

**Comment by LeraTroy** [comment]
Thank you very much for the answer. yes, the  issue closed
