### ISSUE TITLE
Allow save to a layer preserving format

### ISSUE THREAD

**Issue by fzzylogic** [flameshot-org/flameshot#2883]
### Feature Description

First up, Flameshot is really great, thank you!

Feature requests are a dime a dozen, but here's one for what it's worth: Allow save to a format that preserves layers could be very useful. If used in documentation for example, one could adjust layers after the fact without having to retake screenshots.

Greenshot has .greenshot, F@stCapture has .FSC and GIMP has .XFC, but discourages using it as an interchange format. One possibility could be OpenRaster (.ORA) another could be .SVG. For example, one could use a data URI to embed the main screenshot, and use opinionated defaults, such as that the default view were constrained to the user selection.

Using a standard layer supporting format as a save target wouldn't require that Flameshot be able to open the file, as it could be opened in another editor if needed.

Easier said than done, but putting it here for what it's worth. Thanks again for a very cool app!

**Comment by mmahmoudian** [comment]
> Allow save to a format that preserves layers could be very useful.

It has been discussed to have a feature to save as SVG. (https://github.com/flameshot-org/flameshot/issues/2055#issuecomment-964172769). Also partially related to #1515


>Greenshot has .greenshot, F@stCapture has .FSC and GIMP has .XFC, but discourages using it as an interchange format

I personally am against inventing the wheel from scratch. If we output as SVG, it can be opened with Inkscape or any other tool to swap the layers and done post-screenshot modifications

> Using a standard layer supporting format as a save target wouldn't require that Flameshot be able to open the file, as it could be opened in another editor if needed.

:+1:

> Thanks again for a very cool app!

Thank you for using the software, and thank you for suggesting improvements

**Comment by mmahmoudian** [comment]
I'll close this in favor of #2055. Please put a comment here if I have missed anything and wrongfully closed it.
