### ISSUE TITLE
MacOS 12 screen capture security setting not functioning properly

### ISSUE THREAD

**Issue by bunk3m** [flameshot-org/flameshot#2884]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 21.6.0
osx: 12.5.1

### Installation Type

AppImage

### Operating System type and version

MacOS 12.5.1

### Description

Each time Flameshot.app starts (it is one of my start-up items), I get the message that Flameshot wishes to capture the screen and give it permission.  [First screenshot] This was done the first time I started.
<img width="468" alt="Screen Shot 2022-08-24 at 09 05 24" src="https://user-images.githubusercontent.com/3494567/186427208-25f6b100-b85d-4950-9b08-fbac525ce695.png">
As you can see, the permission has been granted but it happens at each start.  See permission screenshot
<img width="665" alt="Screen Shot 2022-08-24 at 09 06 07" src="https://user-images.githubusercontent.com/3494567/186427243-6c05f599-a247-4063-ab3e-bdffd20907f7.png">
.

### System Information

MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by mmahmoudian** [comment]
Please remove the permission and add it again. if didn't work, reboot your computer. It has briefly explained here:
https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by mmahmoudian** [comment]
please reopen this issue if the none of the above worked

**Comment by bunk3m** [comment]
Been there done that.  As @mmahmoudian said it doesn't help.

**Comment by mmahmoudian** [comment]
Ok, then let's get the information correct and complete:
1. AppImage is for Linux. Please state the correct installation menthod
2. Please record a short video to demo the issue. The devil is in details and you might have missed mentioning something in the explanation. A video can sometimes help

**Comment by bunk3m** [comment]
Hello @mmahmoudian . Thanks for your help.

1) Download the Flameshot dmg & sha256 files from Github [flameshot.dmg]
2) Check sha256
3) Open flameshot.dmg
4) Drag Flameshot to /Applications
5) Ctrl + Click to open
6) Accept to start
7) Change Security Options when added -> add Flameshot to Screen Recording
8) In System Preference add Flameshot to start-up items

**Comment by jankatins** [comment]
Can also confirm: restarted mac and/or flameshot and re-added the setting multiple times, still seeing this after every restart. I installed from brew (last updated yesterday)

**Comment by Melkitavu** [comment]
> Restarted mac and/or flameshot and re-added the setting (select/deselect) multiple times, still saw this after every restart. what worked was removing the whole entry and restarting flameshot and then selecting it.

Same thing for me,

Flameshot v12.1.0
Compiled with Qt 5.15.5
darwin: 21.6.0
osx: 12.5.1

**Comment by bunk3m** [comment]
> Restarted mac and/or flameshot and re-added the setting (select/deselect) multiple times, still saw this after every restart. what worked was removing the whole entry and restarting flameshot and then selecting it.

This appears to have worked.  But I'm not sure if that is really what worked since I've restarted, reinstalled, deleted preference files etc. etc. many times over the past couple of days.

I will try now with a new MBP.  Maybe I can recreate.

**Comment by borgmanJeremy** [comment]
Hey all,

I'm sorry you guys are having this issue, but unfortunately this is not really a Flameshot bug. what @jankatins pointed out is what works most reliably. Completely remove the entry and re add it.

The reason this problem occurs on each upgrade is we do not pay the Apple Tax to code sign our binaries. They also do not have any programs for FOSS programs to sign software for free the same way some Microsoft signing services do (Thanks to CodeSign for sponsoring our Windows builds). 

The fact that you have to remove the program and re-add it a bunch of times should be filed as a bug with Apple not Flameshot.

**Comment by bunk3m** [comment]
@borgmanJeremy while I feel your pain, I can't see how this is a code signing issue.  Flameshot does start OK.  It's behaviour changed on the Monterey OS.

I can also confirm that @jankatins solution works for a new install.
1) install Flameshot on Monterey by dropping the app into the Applications folder
2) Right click to start.
3) If you see the message about allowing Flameshot to take screen captures (or not) go to the System Preferences:Privacy & Security
4) In the Privacy tab, scroll down the right side until you reach "Screen Recording"
5) Remove Flameshot from the list using the "-" button.
6) Shutdown
7) Start computer
8) Go back to System Preferences:Privacy & Security and manually add Flameshot to the "Screen Capture".
9) Double-click or right-click on Flameshot to start.
10) Accept the notification preference.

**Comment by borgmanJeremy** [comment]
When you upgrade flameshot MacOs does not realize it is the "same application" without code signing. But there is a bug in their permissions GUI that does not list both the old and new versions of flameshot causing the bug.

This bug only occurs after upgrading the OS or flameshot. Never on first installation of the application.
