### ISSUE TITLE
Flameshot creating new desktop and so can't capture anything (Macos Monterey)

### ISSUE THREAD

**Issue by bunk3m** [flameshot-org/flameshot#2885]
I just upgraded to Monterey over the weekend.  Prior to the upgrade, I ran Flameshot via Macports and it worked great.  With the upgrade, I started using the app downloaded here.  Unfortunately with the app version I am getting exactly what @mikiTesf  is seeing.  When I use the quick command shift+command+x to capture a screenshot, Flameshot ends up switching to another desktop which has only the background.  I'm not sure if there are any specific settings I need to change as everything is default.  Attached screenshot shows what I get now.

Any suggestion for whichever settings I need to change are appreciated.  I suspect this is a setting issue but as @mikiTesf said, might be a bug due to Monterey.
<img width="1440" alt="Screen Shot 2022-08-24 at 08 56 52" src="https://user-images.githubusercontent.com/3494567/186425293-e34c8abe-23fb-418b-8284-eba41b1be901.png">

_Originally posted by @bunk3m in https://github.com/flameshot-org/flameshot/discussions/2874#discussioncomment-3465576_

This was copied over from a discussion where there are many additional screenshots.

**Comment by mmahmoudian** [comment]
Please read https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by mikiTesf** [comment]
> Please read https://flameshot.org/docs/guide/troubleshooting/#macos

That doesn't solve the problem @mmahmoudian. I have that permission set on my machine and still see the behaviour.

**Comment by mmahmoudian** [comment]
these are things that other macOS users have told us that works:
- Remove the permission and add them again
- Reboot

They never told us the order, so they might have done it the following way (I don't use macOS, so I cannot check the validity):
1. remove the permission
2. reboot
3. add the permission
4. reboot
5. check if it works now

In my head, depending on what has caused this bug, one of the reboots can flush the cache and let the new permission get set correctly

**Comment by mikiTesf** [comment]
BTW, I'm just realising that we are discussing about a different issue and not [this](https://github.com/flameshot-org/flameshot/discussions/2874) 😄. This closed issue can be solved by following the instructions to which you commented a link earlier.
