### ISSUE TITLE
Accessibility: Check if a keyboard is present

### ISSUE THREAD

**Issue by Pobega** [flameshot-org/flameshot#2888]
### Flameshot Version

12.1.0

### Installation Type

Flatpak from Flathub

### Operating System type and version

SteamOS

### Description

I was looking for a screenshot tool on my Steam Deck and Flameshot came up pretty early in the Flathub results. I tried it out but it resulted in me having to force reboot my Deck since it locks you into a menu that seems to require a physical keyboard to escape.

Now that the Deck is a thing it's possible we'll be seeing more and more keyboard-less devices using packages from Flathub, it might be worth checking that a keyboard is present or something similar before locking the user into a keyboard driven menu.

### Steps to reproduce

1. run flameshot
2. click flameshot in system tray
3. get stuck with no keyboard

### System Information

Steam Deck on KDE Plasma

**Comment by borgmanJeremy** [comment]
Where did it lock you? I used it on my deck with no problem.

**Comment by Pobega** [comment]
Maybe I just misunderstood how it works due to not using it on my desktop previous, but my experience was that I clicked it in the system tray and the window overlayed over my desktop. I was stuck in some sort of color picker at that point.

Likely PEBKAC though if you've tested on the Deck, so I can close this :')

**Comment by borgmanJeremy** [comment]
Yeah it should fully support the touch screen and gestures.

**Comment by mmahmoudian** [comment]
@Pobega 
This seems like a good opportunity to also promote our Mastodon account by referencing the exhibit A 😅

https://fosstodon.org/@flameshot/108447399833869841
