### ISSUE TITLE
MacOS - taking screenshot hides all windows

### ISSUE THREAD

**Issue by EmilianNowak** [flameshot-org/flameshot#2894]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 21.6.0
osx: 12.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS 12.5.1

### Description

When I try to take a screenshot all windows disappear, so I can only take a screenshot from wallpaper.
It was working for months but suddenly stopped working after some upgrade (unfortunatly I don't remember which version)

### Steps to reproduce

1. From flameshot tray-icon select screenshot 
2. All windows disappear
(same baheaviour when invoked by keyboard shortcut)

### System Information

1. MacOs 12.5.1 (intel)
doesn't matter If I have one or two monitors connected.

**Comment by borgmanJeremy** [comment]
!macpermission
