### ISSUE TITLE
support Windows system?

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#29]
I change some code and use Mingw32 to build on windows10, It runs well, but there are still some problems, such as color widgets. I upload the compiled application [here](https://drop.me/Bxp9jb).

![flameshot](https://user-images.githubusercontent.com/10769951/33894206-5a4bc1b4-df98-11e7-8aac-cf141acc9463.png)

**Comment by lupoDharkael** [comment]
Flameshot uses functionality specific of Unix-like systems (like DBus). I tried to design it in a way to make it _not very hard_ to port to other systems. I'd like to support more systems as it would help to expand the usage of the program. I have a lot of content to implement from my TODO list and porting requires some time (I'm having exams soon).
I'll keep this open as a reminder.

**Comment by lupoDharkael** [comment]
As a side note. If you share a binary of a modified version for Windows, please, provide the source code with the modifications as Flameshot is GPL. You may not have bad intentions but that binary could contain anything.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/fc9c576c1f58792bb9efa580940c51f9b776b5a7 should have fixed the errors of the compilation. I think I'll start adapting Flameshot for Windows sooner than I expected.

**Comment by ZetaoYang** [comment]
Sounds great.
Have you solved dbus on Windows system? Maybe, for adapting to different platform features, conditional compilation can use.

**Comment by lupoDharkael** [comment]
I'm disabling dbus related code for Windows just to make it work. I'll investigate alternatives for IPC and it will have an alternative implementation in the future.

I have to implement support for global key press detection, a shortcut management menu, an autostart in boot option and other stuff too.

**Comment by ZetaoYang** [comment]
@lupoDharkael  Hi, I tell you a good news. There is an open sourced library [QHotKey](https://github.com/Skycoder42/QHotkey) for global shortcuts/hotkeys, which can be used directly in projects. It works on Windows, Mac and X11, currently does not support Wayland. Check the details [here](https://github.com/Skycoder42/QHotkey/issues/14). I hope this will be helpful to you.

**Comment by lupoDharkael** [comment]
thanks! It is useful

**Comment by b4ssrp** [comment]
### _May be offtop_
_There is @Greenshot for windows and it has builtin image editor, but it may be slow._

**Comment by smaragdus** [comment]
@lupoDharkael 
Any approximate deadline for the Windows version?

**Comment by davtur19** [comment]
Some news?
I'd like to be able to use it on Windows as well, as it's the best tool for screenshots I've ever used

**Comment by ZetaoYang** [comment]
@davtur19 At present, you can use CI daily build version. https://ci.appveyor.com/project/lupoDharkael/flameshot
![image](https://user-images.githubusercontent.com/10769951/38479106-af848a9a-3bef-11e8-8f02-df4d2b8c1b1e.png)

**Comment by lupoDharkael** [comment]
#188 should be fixed before the release fro Windows as that release could increase a lot the usage of the program.

**Comment by smaragdus** [comment]
I would not call **Flameshot** version **0.5.1-37-g205cd7c** portable since it saves the configuration file (**flameshot.ini**) not in program folder but in AppData:

`C:\Users\UserName\AppData\Roaming\Dharkael\flameshot.ini`

I would appreciate a command-line parameter which forces **Flameshot** to save **flameshot.ini** in program folder, for example:

`flameshot.exe -portable`

Time (%H:%M:%S) and Time (%H:%M) are not valid for Windows.

**Comment by lupoDharkael** [comment]
Flameshot isn't portable, nor ready for a windows release, it still requires some work.

**Comment by smaragdus** [comment]
@lupoDharkael 
It seems I was mislead by the name of the archive (flameshot_win_x86_portable_0.5.0.zip).
Anyway, please consider a command-line argument which will make Flameshot portable on Windows-
 (configuration file saved in program folder.
Take your time, I am patient, many Linux programs took years to be ported to Windows.

**Comment by AssAsIN10556** [comment]
I downloaded the zip file and tried to run it, but all i got was an error saying "The code execution cannot proceed because Qt5DBusd.dll was not found. Reinstalling the program may fix this problem."
Thing is, it's right there in the folder.

**Comment by SirTell** [comment]
I have also problem. If I start the C:\flameshot/flameshot.exe
It says can't find Qt5Cored.dll, psl try to reinstall the software.

I hope you can fix this I love this app in Linux.

**Comment by balthild** [comment]
Is it able to compile/run on macOS now?

**Comment by ZetaoYang** [comment]
@balthild Not yet. However, we are working in process.

**Comment by limonte** [comment]
You can get the links to test the application from [AppVeyor builds](https://ci.appveyor.com/project/lupoDharkael/flameshot):

- https://transfer.sh/gBN86/flameshot_0.6.0_win_x86.zip (32 bits)
- https://transfer.sh/PJ4w6/flameshot_0.6.0_win_X64.zip (64 bits)

**Comment by fmaiabatista** [comment]
I'm somewhat newbie on building Linux applications and I'd like to try Flameshot on Windows.

Could you guys provide a dummy-proof step-by-step guide to do it?

I just loved the app and now I'm willing to ditch my current Windows screenshot app for Flameshot!

**Comment by ipenev92** [comment]
> You can get the links to test the application from [AppVeyor builds](https://ci.appveyor.com/project/lupoDharkael/flameshot):
> 
> * https://transfer.sh/gBN86/flameshot_0.6.0_win_x86.zip (32 bits)
> * https://transfer.sh/PJ4w6/flameshot_0.6.0_win_X64.zip (64 bits)

Just me, or neither of the links work?

**Comment by Lenart12** [comment]
They are not working for me either

**Comment by Julien-Peeters** [comment]
Using those links gave me a version that works! that's great to be honest. (AssAsIN10556 here, got new account)

**Comment by xcme** [comment]
Do I understand correctly these windbows builds are unofficial? I download and started 0.6.0 and it works. I really need this tools under windows because it's best tool I seen. :)

**Comment by Julien-Peeters** [comment]
Today i noticed a bug where i'm only able to take a screenshot on my main screen. My laptop screen is not affected by flameshot anyomore and clicking in that screen exits Flameshot. I have no clue how this happened since i haven't changed any settings since i installed it.

**Comment by ZetaoYang** [comment]
@xcme Currently, these windows building are official, but it still has some unkown bugs, it's unstable.

**Comment by Metadorius** [comment]
AppVeyor builds give 404. :\

**Comment by TuxGamer** [comment]
@Metadorius Go to https://ci.appveyor.com/project/lupoDharkael/flameshot , select your platform (32 or 64 bit) and search for "curl --upload-file". It prints the download link slightly below that.

As of today, the links are:
- https://transfer.sh/sKEDg/flameshot_0.6.0_win_X64.zip (64 bit)
- https://transfer.sh/5c4aE/flameshot_0.6.0_win_x86.zip (32 bit)

**Comment by Julien-Peeters** [comment]
> 
> 
> @Metadorius Go to https://ci.appveyor.com/project/lupoDharkael/flameshot , select your platform (32 or 64 bit) and search for "curl --upload-file". It prints the download link slightly below that.
> 
> As of today, the links are:
> 
>     * https://transfer.sh/sKEDg/flameshot_0.6.0_win_X64.zip (64 bit)
> 
>     * https://transfer.sh/5c4aE/flameshot_0.6.0_win_x86.zip (32 bit)

Hey, uh
None of these links work anymore, the only text that appears in the webpage is "Not found"...

**Comment by Julien-Peeters** [comment]
> 
> 
> @Metadorius Go to https://ci.appveyor.com/project/lupoDharkael/flameshot , select your platform (32 or 64 bit) and search for "curl --upload-file". It prints the download link slightly below that.
> 
> As of today, the links are:
> 
>     * https://transfer.sh/sKEDg/flameshot_0.6.0_win_X64.zip (64 bit)
> 
>     * https://transfer.sh/5c4aE/flameshot_0.6.0_win_x86.zip (32 bit)

Hey, uh
None of these links work anymore, the only text that appears in the webpage is "Not found"...

**Comment by Mackzwellz** [comment]
For those who still don't get it (as I did at first), here's a few screenshots that explain how to get the link for the latest build:
https://imgur.com/a/90DK6yU

**Comment by 4sStylZ** [comment]
Thank you for the imgur gruide.

The build seem's broken…

```
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
Command exited with code 2
```

**Comment by Mackzwellz** [comment]
You can try to find the most recent successful build on History tab.
For now it's this one: https://ci.appveyor.com/project/lupoDharkael/flameshot/builds/29235281

**Comment by 4sStylZ** [comment]
Thank you.

**Comment by DrunkenPoney** [comment]
Steps to download the latest windows version of Flameshot:

1. Go to the [Flameshot's build history page in AppVeyor](https://ci.appveyor.com/project/lupoDharkael/flameshot/history)
2. Select the latest successful build
	![Build history](https://i.imgur.com/mXBTulw.png)
3. Select the job corresponding to your platform
	![Jobs](https://i.imgur.com/OTK1nw0.png)
4. Scroll down to the end of the logs and find the link to the zip archive
	![Logs](https://i.imgur.com/rMr66pL.png)

**Comment by Lysak** [comment]
> Steps to download the latest windows version of Flameshot:
> 
> 1. Go to the [Flameshot's build history page in AppVeyor](https://ci.appveyor.com/project/lupoDharkael/flameshot/history)
> 2. Select the latest successful build
>    ![Build history](https://camo.githubusercontent.com/863220338236817fc95aa8ce87c77a74c0c2e54f/68747470733a2f2f692e696d6775722e636f6d2f6d584254756c772e706e67)
> 3. Select the job corresponding to your platform
>    ![Jobs](https://camo.githubusercontent.com/3db77bdbbeb83389b4a6670b9eafd68ea92ebf49/68747470733a2f2f692e696d6775722e636f6d2f4f544b316e77302e706e67)
> 4. Scroll down to the end of the logs and find the link to the zip archive
>    ![Logs](https://camo.githubusercontent.com/475bb93f8bf262c6d901a669a0f8a9caa75b46dc/68747470733a2f2f692e696d6775722e636f6d2f724d723636704c2e706e67)

when open link -- Not Found

**Comment by DrunkenPoney** [comment]
@Lysak [transfer.sh](https://transfer.sh/#features) only keeps files for 14 days, so if the build is older than 14 days, you won't be able to download it.

**Comment by ZetaoYang** [comment]
@Lysak You can download Windows binary from the latest pull request.
![image](https://user-images.githubusercontent.com/10769951/72362584-602ff380-372e-11ea-9020-8f304442090a.png)

**Comment by djalmajr** [comment]
Same with me... This build has only 11 hours, but I get "Not Found" yet. Am I missing something?

![image](https://user-images.githubusercontent.com/1858147/73191100-b9702d80-4105-11ea-90fe-9be88e693c98.png)

![image](https://user-images.githubusercontent.com/1858147/73191391-2a174a00-4106-11ea-9546-b4b0bb4cc9bd.png)

https://transfer.sh/2Yn8e/flameshot_0.6.0_win_X64.zip

**Comment by xcme** [comment]
It seems there is no more updates for last 1,5 years. Should we forget about stable official release for Windows?

**Comment by InventM4n** [comment]
I can download it just now, yesterday I couldn't

I let you a mirror here http://www.mediafire.com/file/37ea95nff127297/flameshot_0.6.0_win_X64.zip/file

**Comment by djalmajr** [comment]
Thanks a lot!

**Comment by djalmajr** [comment]
This app is awesome! Thanks...

Just one more question: there is a way to add arguments to flameshot run a screen capture on Windows? 😁 I have tried tu run `flameshot.exe gui` but doesn't work... `flameshot.exe` works though and the app shows in the tray system.

**Comment by oyhel** [comment]
Did you ever find a way to call `flameshot.exe gui` from Windows 10? This tool is very useful, but having to click the button in the tray makes it a bit of a hassle to use.

**Comment by DniweTamp** [comment]
latest release uses printscreen button to open the gui

**Comment by borgmanJeremy** [comment]
I opened #861 so that we will officially host the binaries on github after the next release. If there are still specific bugs after the next release lets file new reports.

**Comment by lucidBrot** [comment]
> latest release uses printscreen button to open the gui  
> - @DniweTamp 

Is there a way do specify the shortcut (on Windows)? I'd like to use <kbd>Win</kbd><kbd>PrntScrn</kbd> because <kbd>PrntScrn</kbd> is already mapped for a different program.

**Comment by shiftgeist** [comment]
@lucidBrot You can use [AutoHotkey](https://www.autohotkey.com/). To my knowledge there is no option to change the shortcut in flameshot, is there?
