### ISSUE TITLE
Select active window?

### ISSUE THREAD

**Issue by soviet-man** [flameshot-org/flameshot#2901]
How to make a shot of active window only? Most of times I want to share the view of window of specific app, not full desktop.

`scrot` has corresponding flag and it's a usefull feature.

**Comment by mmahmoudian** [comment]
Duplicate of #334

If you are on Xorg you can easily script it yourself. For example I have made a dmenu script to do many things including this one:

https://codeberg.org/mehrad/dmenu_shot
