### ISSUE TITLE
Multiple monitors on MacOS

### ISSUE THREAD

**Issue by mtodor0va** [flameshot-org/flameshot#2902]
I'm currently using the latest version of Flameshot on a MacBook.

When I have a second monitor connected via a hub with a HDMI cable, I'm unable to take screenshots on that monitor.
I'd have to pull whatever I'm trying to screenshot down to my main display.

So far, I've only been able to encounter this on Mac, as otherwise, Flameshot works fine with my dual monitor setup on Windows.

Is this a known bug, perhaps, or something that I've missed in the configuration?

Let me know if additional details are needed here.

**Comment by borgmanJeremy** [comment]
Restart flameshot after connecting the second monitor and let us know if you still have the issue.

**Comment by aquinzi** [comment]
Had the same issue and restarting flameshot allows me now to take screenshots in the second monitor. I think is only needed when you restart the computer; afterwards seems to work fine

**Comment by mtodor0va** [comment]
> Restart flameshot after connecting the second monitor and let us know if you still have the issue.

This seems to have solved it, thanks!

**Comment by silashansen** [comment]
> > Restart flameshot after connecting the second monitor and let us know if you still have the issue.
> 
> This seems to have solved it, thanks!

Restarting absolutely solves it, but since I switching my monitor setup multiple times per day between work, laptop-only and home, I have to restart flameshot multiple times per day, so while it solves the problem, it's not a great experience.

I really appreciate your hard work, so this is only chiming in with extra information in case it makes sense.

**Comment by tvt173** [comment]
note also that your mouse has to be above the screen you want to screenshot. it will not allow you to screenshot from either screen. only the one currently in focus (as per mouse location at time of screenshot)
