### ISSUE TITLE
Command "flameshot gui" doesn't work without message

### ISSUE THREAD

**Issue by FireSK7** [flameshot-org/flameshot#2903]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

### Installation Type

User repository (AUR)

### Operating System type and version

linux: 5.15.65-1-lts arch: unknown

### Description

  Command "flameshot gui" doesn't work without any error  message. I want to bind the command "flameshot gui" with a i3 shortcut , and it just doesn't work . Then I try to run "flameshot gui" on the terminal , it doesn't work either. The only way that I can take a screenshot is click on the icon on the bottom right corner, which is not that convinient. 

  And there is some message is like 

```QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
flameshot: error: Unable to connect via DBus
Failed to get information about the latest version.  "Error transferring https://api.github.com/repos/flameshot-org/flameshot/releases/latest - server replied: rate limit exceeded"
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
```

### Steps to reproduce

1. run ”flameshot gui”

### Screenshots or screen recordings

1. run ”flameshot gui”

### System Information

linux: 5.15.65-1-lts arch: unknown
1080p screen
in i3wm 
using xorg

**Comment by FireSK7** [comment]
When I roll back to version 0.10.1 ,every thing works fine beside the pin function.

**Comment by FireSK7** [comment]
Still not working.

**Comment by mmahmoudian** [comment]
Have you already followed instructions here:

https://flameshot.org/docs/guide/troubleshooting/#linux
