### ISSUE TITLE
Ability to repeat the last screenshot taken

### ISSUE THREAD

**Issue by hailwood** [flameshot-org/flameshot#2904]
### Feature Description

For comparison screenshots it would be super useful to be able to run `flameshot gui --repeat` or similar that would open up with screen capture gui with the exact same dimensions and position as the last capture.

**Comment by mmahmoudian** [comment]
I love more CLI options, and I can see that this would make scripting easier as the user does not need to define environmental variable or file to store the last coords, but I considering that it is still possible in a one-liner, I'm not sure if it is a good enough addition:

```sh
export FLAMESHOT_LAST_REGION=$(flameshot gui --print-geometry --region "$([[ -v FLAMESHOT_LAST_REGION ]] && echo ${FLAMESHOT_LAST_REGION} || echo '100x100+100+100')")
```

More explanation here: https://github.com/flameshot-org/flameshot/issues/2584#issuecomment-1117328120

I'm not 100% sold on the idea. Of course I'm just a cog in a whole gearbox, and my opinion is not reflect the whole team. So let's see what others think. 

-------

On a side note, are you aware of this option in the Configurations

![image](https://user-images.githubusercontent.com/390889/189107562-8b6eae8d-1424-4827-ae96-531b7592ffef.png)

and this in the Launcher:

![image](https://user-images.githubusercontent.com/390889/189108472-7ef2c00b-cfa3-4a3d-ade9-1377b11f4f13.png)

**Comment by hailwood** [comment]
@mmahmoudian 
I wasn't aware of the option - turns out I was still on V11 :)
Updated and it's exactly what I need - and looking we have `flameshot gui --last-region` for the cli in V12.

I'm going to close this issue now as I believe it's all covered :+1: 
Thanks!

**Comment by mmahmoudian** [comment]
Woops, I also forgot about that flag 😅 Thanks for reminding me
