### ISSUE TITLE
Windows quick access integration

### ISSUE THREAD

**Issue by funnym0nk3y** [flameshot-org/flameshot#2907]
### Feature Description

On windows there is a quick access bar in the lower right corner with a quick access button. See picture below. This comes in very handy if the notebook is in tablet mode. It would be nice if flameshot could hook into that and instead of using the standard snipping tool flameshot could be used. 

![grafik](https://user-images.githubusercontent.com/41870754/189765065-d97c48f4-810d-490f-a422-ba8952f83bda.png)

**Comment by borgmanJeremy** [comment]
Do you know if 3rd party apps are allowed to integrate there?

**Comment by markhc** [comment]
On Windows 11 the Notification Center changed drastically. Now it no longer offers that shortcut, and I can't see a way to add it.

![image](https://user-images.githubusercontent.com/11592227/193476963-4954d2bb-2adf-4c41-aedc-567e16fdfda2.png)

**Comment by borgmanJeremy** [comment]
Okay I’m going to close this because I do t think it’s possible.
