### ISSUE TITLE
Keybinding not working - Pop OS

### ISSUE THREAD

**Issue by gracadedues** [flameshot-org/flameshot#2908]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 5.19.0-76051900-generic
org.kde.Platform: 5.15-21.08

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop!_OS 22.04 LTS GNOME 42.4 Windowing X11

### Description

Installed flameshot through the Popshop. This is a brand new desktop with latest Pop OS. I followed the instructions here: https://flameshot.org/docs/guide/key-bindings/ for Ubuntu/Gnome but nothing happens when I press the Print Screen button or any other key combination I set.

In terminal after running 'pkill flameshot' when I run either 'flameshot' or 'flameshot gui' I get the following message:
Command 'flameshot' not found, but can be installed with:
sudo apt install flameshot

Thanks, appreciate any help with this.

### System Information

![image](https://user-images.githubusercontent.com/29995192/189868131-9a1b67d5-0f3e-478b-a9cc-d6fd4c2af757.png)

![image](https://user-images.githubusercontent.com/29995192/189867996-f216a4b3-4162-4ec8-b2b5-5ad3cc1ff8a5.png)

**Comment by borgmanJeremy** [comment]
It looks like the popshop installed the flatpak version so you can start it with
```
flatpak run org.flameshot.Flameshot gui
```

**Comment by gracadedues** [comment]
@borgmanJeremy thanks so much! this worked perfectly!!
