### ISSUE TITLE
Display Selection Size

### ISSUE THREAD

**Issue by Novack** [flameshot-org/flameshot#2919]
### Feature Description

Lightshot has a size indicator for the rectangle selection, that is quite useful. In Flameshot the size indicator dissapears while the selection is being resized, which deminishes the feature full potential.

![image](https://user-images.githubusercontent.com/1981463/192283664-14047aef-6eca-4d97-99b2-7e64e24ed7d2.png)

**Comment by mmahmoudian** [comment]
This is implemented already in #2766. Please update to the latest version.

**Comment by Novack** [comment]
Oh that is wonderful news, thank you @mmahmoudian.

I have the latest release (v12.1.0 [Latest](https://github.com/flameshot-org/flameshot/releases/latest) but this is not there. Makes sense however, given that the latest release is from july 3, before than even the PR. But I will wait for the next release, knowing is already on th pipeline. Thank you!

**Comment by mmahmoudian** [comment]
@Novack you are right, I didn't check the release date and commit. This will be in the next release. Arch Linux users can already use it by installing the AUR, and others can use it by manually installing it from our nightly builds:

https://flameshot.org/docs/installation/development-build/
