### ISSUE TITLE
Flameshot in Jamf

### ISSUE THREAD

**Issue by eranszp** [flameshot-org/flameshot#2923]
### Flameshot Version

--

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macos

### Description

Hello
i am trying to deploy Flameshot from Jamf, but i cant create a configuration profile in order to allow the screen recording due to the "application is not signed"
is someone else manage to solve it and manage somehow to create a configuration profile for it?
thanks in advance

### System Information

macos monterey 12.6

**Comment by borgmanJeremy** [comment]
I think the only way to solve this would be for us to sign the application. We do not currently have plans to do this due to the $100 annual fee.
