### ISSUE TITLE
Screenshot prompt is something that looks like GNOME instead of the usual Flameshot GUI tool with a rectangular selector and all the tools

### ISSUE THREAD

**Issue by mattwelke** [flameshot-org/flameshot#2926]
### Flameshot Version

```
flameshot --version
Flameshot v12.1.0 ()
Compiled with Qt 5.11.3
```

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 22.04.01 LTS

### Description

I'm trying to set up Flameshot on a fresh Ubuntu install the way I usually do. I follow instructions for unmapping the PRINT button (print screen) with whatever it was mapped to by default and mapping it instead to `flameshot gui` (using the absolute path to the binary on my system).

I usually use [this askubuntu.com question](https://askubuntu.com/questions/1036473/how-to-change-screenshot-application-to-flameshot-on-ubuntu-18-04) which has the most detailed answer out there, and I just do what I need to do to account for the fact that the answer is based on an older version of Ubuntu.

So in my case, it means I open Settings > Keyboard, go to "Keyboard Shortcuts", click "View and Customize Shortcuts", click "Screenshots", click "Take a screenshot interactively", then hit Backspace to disable it.

Then, I go to Settings > Keyboard, click 'View and Customize Shortcuts", scroll down, click "Custom Shortcuts", and make a new shortcut. I name it something I like, then use `/usr/bin/flameshot gui` for the Command, and use `Print` for the Shortcut.

When I hit `Print` on my keyboard, I get what looks like a GNOME window. I'd normally include a screenshot right here on GitHub to help explain what I'm seeing, but because of the issue I'm experiencing, I'm unable to always produce screenshots.

It has the title "Screenshot", and three buttons - "Cancel", "Options...", and "Share". It displays a message "Share this screenshot with the requesting application?". If I click Share, I get the purple Flameshot GUI tool that allows me to perform a rectangular area screenshot. Everything at this point works like I expected it to based on my experience setting up Flameshot before on Ubuntu. I can adjust the size of the selection, copy the selection to my clipboard, save a file of the selection, etc.

However, I don't like having to perform the redundant intermediate step where I have to click "Share" from that new window that appears for me, which results in me finally getting to the point where I can take my screenshot. It's also a bit slow. 1 second or so, compared to Flameshot how I remember it, which was basically instant.

### Steps to reproduce

1. Be running Ubuntu 22.04.1.
2. Install Flameshot via the `.deb` file in GitHub releases. Latest version as of Sept 27th 2022.
3. Remove the default `Print` keyboard shortcut.
4. Add a new custom keyboard shortcut for `Print` with the command `/usr/bin/flameshot gui`.
5. Hit `Print` on your keyboard. Observe the window that appears with a full screenshot.
6. Click "Share" in the new window. Observe normal Flameshot behavior.

### System Information

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by mattwelke** [comment]
Noticed that if I do everything from the terminal, by running `flameshot gui`, I get the same thing happening, but I see warnings in the logs:

```
flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
```

If I run it with that env var set, I get the same behavior. It seems like the env var has no effect on Flameshot.

```
QT_QPA_PLATFORM=wayland flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
```

**Comment by borgmanJeremy** [comment]
!gnome41

**Comment by mattwelke** [comment]
@borgmanJeremy Actually, I have a second computer that was setup earlier with Ubuntu 22.04.1 and it works fine. When I hit `Print` I get the Flameshot GUI immedaitely. No intermediate GNOME "share" dialog.

Here are my details for the system I'm checking this on right now, where it *does* work:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

```
flameshot --version
Flameshot v11.0.0 ()
Compiled with Qt 5.11.3
```

![image](https://user-images.githubusercontent.com/7719209/192924072-0337fbd0-e555-4582-a47e-ca669ae7b7be.png)

**Comment by mattwelke** [comment]
Read into those linked issues. I understand now that this is caused by a combination of things - Using GNOME 41+ *and* using Wayland. So I just need to ensure I'm using X11 instead of Wayland and my issue should go away. I'll have to figure out why my newer computer has decided to use Wayland. Seems like there's nothing left to do here. ty

**Comment by Pheggas** [comment]
Any workaround on this?

**Comment by mmahmoudian** [comment]
@Pheggas Well, you are asking a Gnome question from Flameshot devs. That said, It seems there has been some improvement on xdg_desktop_portal in which they have "fixed" this. More detailed info can be found in #2868
