### ISSUE TITLE
Error transferring to Imgur

### ISSUE THREAD

**Issue by vladrozdo** [flameshot-org/flameshot#2933]
### Flameshot Version

Flameshot v12.1.0 (96c2c82)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS Monterey 12.6, Windows 10 Pro 21H1

### Description

When uploading a screenshot to imgur gives an error -  "Error transferring https://api.imgur.com/3/image?title=&description=2022-10-04_13-18 - server replied: "

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/114992890/193795857-3281eb5d-04f8-42be-a6f6-78fa54d4c303.png)

### System Information

MacOS Monterey 12.6, Windows 10 Pro 21H1

**Comment by vladrozdo** [comment]
Get this error in browser - {"data":{"error":"Authentication required","request":"\/3\/image","method":"GET"},"success":false,"status":401}

**Comment by OnkelTem** [comment]
@vladrozdo In which version it's fixed? 
I'm still getting it on `12.1.0`

**Comment by mmahmoudian** [comment]
@OnkelTem what @vladrozdo is saying is that the error has nothing to do with Flameshot, it is a connection issue between your computer and imgur.

**Comment by vladrozdo** [comment]
> 

Hi, I changed default API-key (Client ID) to my own, that I created in my Imgur-account.
