### ISSUE TITLE
Where is the menu when taking a screenshot?

### ISSUE THREAD

**Issue by Rufus13apostol** [flameshot-org/flameshot#2939]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ubuntu 22

### Description

Where is the menu bar when taking a screenshot? I've touched every option in config, but I get only this when launching flameshot:

### Steps to reproduce

1. install flameshot trough the software center
2. run flameshot trought terminal: flameshot gui
3. try to take a screenshot
4. menu does not appear.

### Screenshots or screen recordings

![Captura desde 2022-10-06 10-37-23](https://user-images.githubusercontent.com/10268282/194264784-79a49a5c-e588-45c8-b6d3-74942eaebcb3.png)

### System Information

ubuntu 22
Xorg

System:
  Host: localhost Kernel: 5.15.0-48-generic x86_64 bits: 64 Desktop: GNOME 42.4
    Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: Realtek USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.0.5

**Comment by borgmanJeremy** [comment]
!gnome41
