### ISSUE TITLE
Docs: Inside the README.md file `on ubuntu` not working

### ISSUE THREAD

**Issue by muditchoudhary** [flameshot-org/flameshot#2946]
Inside the README.md file `on ubuntu` link does not link to its corresponding section.

![Peek 2022-10-14 19-36](https://user-images.githubusercontent.com/74391865/195867862-bb3e9269-ed17-49dc-bbb0-5a6a439e78ba.gif)

**Comment by muditchoudhary** [comment]
Would like to fix this.

**Comment by borgmanJeremy** [comment]
Please go ahead and fix it in a PR. happy to help if you have a question.
