### ISSUE TITLE
Annotation Text is Cut Off

### ISSUE THREAD

**Issue by worace** [flameshot-org/flameshot#2947]
### Flameshot Version

```
$ flameshot --version
Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04

### Description

I recently upgraded to ubuntu 22.04 and installed the latest flameshot from Apt repository.

I have noticed that when adding text annotations, they are often cut off (usually on the left side, it seems). Lines or other annotations (arrows, etc) seem to be working OK.

Here is an example where I typed `pizzapizzapizza` twice, but what actually shows is like `zzapizzapizza`

![image](https://user-images.githubusercontent.com/1227440/195877582-c618e77f-f44f-4568-90b2-3b3e4cebc344.png)

### Steps to reproduce

1. Take a screenshot -- seems to not matter what. I only have 1 monitor
2. Annotate text on that image
3. See the text get cut off

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/1227440/195877764-6d32f7e2-5f28-4781-8791-86ef0233f9d0.png)

### System Information

- ubuntu 22.04

```
$ echo $XDG_SESSION_TYPE
x11
```

**Comment by borgmanJeremy** [comment]
Can you please test on 12.1? we only support the latest version.

**Comment by mmahmoudian** [comment]
@worace you can install the latest version from Flatpak, Snap, AppImage, or install from the .deb file of the latest release.

**Comment by worace** [comment]
Ah wow, 12.1 looking good so far. Sorry for the false alarm!
 
![image](https://user-images.githubusercontent.com/1227440/196202836-a70b7ae3-d094-4a5d-8878-8e859463e6fc.png)
