### ISSUE TITLE
Flameshot does not start in Ubuntu

### ISSUE THREAD

**Issue by pesekviktor** [flameshot-org/flameshot#2951]
### Flameshot Version

Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20.04.5 LTS

### Description

When I start flameshot from the terminal I get
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "domain.replaceAll is not a function")

Running flameshot-gui works.

I am on Ubuntu 20.04.5 LTS.

Would anyone know how to fix it?

### Steps to reproduce

run `flameshot`

### System Information

System:
  Kernel: 5.4.0-128-generic x86_64 bits: 64 
  Desktop: Gnome 3.36.9 Distro: Ubuntu 20.04.5 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
  Device-2: NVIDIA GP108M [GeForce MX150] driver: nvidia v: 470.141.03 
  Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 3000x2000~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.2.6

**Comment by borgmanJeremy** [comment]
Please test using our latest version 12.1

**Comment by pesekviktor** [comment]
Hi @mmahmoudian, I used the snap version to install the latest, but the issue prevails unfortunately. Calling flameshot from terminal gives
`
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.145\" (uid=1000 pid=9318 comm=\"/snap/flameshot/183/usr/local/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1244 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.145\" (uid=1000 pid=9318 comm=\"/snap/flameshot/183/usr/local/bin/flameshot \" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1244 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "domain.replaceAll is not a function")
`

A notification appears with the message Hello there..., but I can't find the icon anywhere. I can though "Take screenshot" or "Open launcher correctly".

Btw: the Readme suggest to use package manager, maybe it could be updated :)
![image](https://user-images.githubusercontent.com/33232478/196240967-76489e78-a54d-4e68-b881-9d1891b7082a.png)

**Comment by mmahmoudian** [comment]
Can it be a duplicate of #2300? If it is, then based on that thread to me it seems that Ubuntu 22.04 has fixed the issue with AppArmour. But lets see if @borgmanJeremy has a different diagnosis as he knows more than me.

About installing from `apt`, the best install method is of course always your Linux distro's package repo, but unfortunately Ubuntu and Debian are not rolling release distros by nature and therefore users will not get the latest version of software. This is one of the reasons that we are also providing Snap, Flatpak and AppImage. In other words, your distro of choice is the limiting factor for you in this situation.

**Comment by pesekviktor** [comment]
https://github.com/flameshot-org/flameshot/issues/2300 looks very much the same. Thanks for the installation explanation.
