### ISSUE TITLE
`grabWindow()` does not work in MacOS 12.6.

### ISSUE THREAD

**Issue by XMuli** [flameshot-org/flameshot#2957]
### Flameshot Version

flameshot: ff7028d8ab45f293e1529777a81cb80653c33014   2022.10.16 GMT+8 20:50:44

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Flatpak from Github, Compiled from source

### Operating System type and version

v12.0.0 (or more big)

### Description

`grabWindow()` is disabled in MacOS 12.6.
The expectation is to capture the entire desktop (including windows, displayed on top of the desktop wallpaper); however, only the desktop (and no other windows) is actually captured.

### Steps to reproduce

1. clone the source code, then run it with qt5.15.2 + Mac12.6 to reproduce
2. ![截屏2022-10-21 14 13 17](https://user-images.githubusercontent.com/33887845/197131510-43899776-f68e-4fb8-99ee-5f775226b620.png)
![截屏2022-10-21 14 14 05](https://user-images.githubusercontent.com/33887845/197130239-571bcfb9-e528-4bc4-b359-f4d496dbe612.png)

<br>
3. or run [v12.0.0 flameshot.dmg](https://github.com/flameshot-org/flameshot/releases/download/v12.0.0/flameshot.dmg) directly to reproduce

**Not the realistic expected screen desktop (open windows are not shown in the screenshot)**
![截屏2022-10-21 14 25 59](https://user-images.githubusercontent.com/33887845/197130730-5fbf6c5b-4379-4709-b019-38e86077c03c.png)

### Screenshots or screen recordings

See above

### System Information

MacOS：12.6   MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) ，Intel
Qt：5.15.2

**Comment by mmahmoudian** [comment]
Please:
1. search in the existing open and closed issues on github before creating a new issue
2. give proper permissions to Flameshot. read here: https://flameshot.org/docs/guide/troubleshooting/#macos

**Comment by XMuli** [comment]
thanks.

1. I searched for issuse and found nothing similar
2. I have set " record" on, but still

I made sure that the previous two still didn't work, so I brought up a new one.

But by deleting and re-adding the permissions, it worked fine (I feel like macos is really a pitfall at this point); thanks for your reply!

<img src="https://user-images.githubusercontent.com/33887845/197151901-46140682-0ef9-403c-b13a-00b1e6fb3d20.png" width="70%"/>

**Comment by mmahmoudian** [comment]
> 1. I searched for issuse and found nothing similar

Usually people forget to switch to "Closed" issues and they only search in the "Open" issues. But you can checkout all different varients of the same question here:
https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+label%3AMacOS+is%3Aclosed+permission

-------

> 2. I have set " record" on, but still

This is a known issue in MacOS that the permissions are bound to the binary and not the software, so if you update the software, you have to re-apply the permissions. In [the link I provided earlier](https://flameshot.org/docs/guide/troubleshooting/#macos) we have the following sentence to indicate to users what to do:
>> If you were still getting the following message when restarting Flameshot, try removing (using the "-" button) and then adding Flameshot to the list above.

-------

> I feel like macos is really a pitfall at this point

Yes, it is definitely an issue on MacOS side, but I'm sure Apple can turn this bug into a feature with a simple marketing pitch 😉 

-------

> thanks for your reply!

My pleasure.

**Comment by XMuli** [comment]
> Yes, it is definitely an issue on MacOS side, but I'm sure Apple can turn this bug into a feature with a simple marketing pitch 😉

hhhhhhhhhhhhhhhh,  Thank you for your patience and guidance, and it is bound to the binary (another new knowledge learned)
