### ISSUE TITLE
Use flameshot as an image editor (without capturing screenshot)

### ISSUE THREAD

**Issue by KSXGitHub** [flameshot-org/flameshot#2958]
### Feature Description

Flameshot already has to ability to edit screenshot right after it was captured, but this feature cannot be used to edit images that already exist. I think it would be really helpful if user can type `flameshot edit ~/Pictures/my-picture.png` to open a simple image editor.

**Comment by mmahmoudian** [comment]
Duplicate of:
- #2005
- #1427
- #240
- #83
