### ISSUE TITLE
Ubuntu 22.10 can only work at one display

### ISSUE THREAD

**Issue by kmephistoh** [flameshot-org/flameshot#2962]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4
linux: 5.19.0-23-generic
ubuntu: 22.10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.10

### Description

![image](https://user-images.githubusercontent.com/2638142/197926622-9dcd5841-cf8b-4b17-8948-bcd8db0fca2e.png)

I have two displays, settting as above. 
when run 'flameshot gui', it can only capture the number 1 display (Built-in display), when you try to select an area on dispaly 2, the window's content became the same as display 1,  even can't select anything.  I don't konw why

➜  ~ /usr/bin/gnome-shell --version
GNOME Shell 43.0
➜  ~ echo $XDG_SESSION_TYPE
wayland
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
➜  ~ /usr/bin/flameshot -v
Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

### Steps to reproduce

1. run 'flameshot gui'
2. try to capture display 2 content
3. you will find can't select any area of display 2

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/2638142/197928259-a9174558-7498-41ba-aabb-a7d5349fb1e0.png)

### System Information

➜  ~ /usr/bin/gnome-shell --version
GNOME Shell 43.0
➜  ~ echo $XDG_SESSION_TYPE
wayland
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
➜  ~ /usr/bin/flameshot -v
Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

**Comment by devbranch-vadym** [comment]
Seeing the exact same issue on Ubuntu 22.10.
The screenshot UI displays contents of the first screen at second and third monitors. Also the UI itself seems to be duplicated across all monitors as well.

**Comment by artur-kabirov** [comment]
Same issue on Ubuntu 22.10

Terminal:
```
~ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by devbranch-vadym** [comment]
Just checked it,
```
QT_QPA_PLATFORM=wayland flameshot gui
``` 
ends up with same results.

**Comment by vlakam** [comment]
Experiencing the same issue on X11 KDE 
Flameshot v12.1.0 (edd228b9)
Compiled with Qt 5.15.6

**Comment by mmahmoudian** [comment]
@artur-kabirov if that is the case, doesn't it mean that there is a driver (and its libraries) issue rather than dependency?

**Comment by artur-kabirov** [comment]
@mmahmoudian may be you are right

**Comment by mkhrystunov** [comment]
> Just installed displaylink driver for ubuntu (needed for another purposes) from https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu, and issue with "flameshot working only in one display resolved. Maybe some addition dependencies installed did solve my problem

Didn't help me :/

**Comment by SunicYosen** [comment]
> Just installed displaylink driver for ubuntu (needed for another purposes) from https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu, and issue with "flameshot working only in one display resolved. Maybe some addition dependencies installed did solve my problem

Great but not perfect! It works for me sometimes but within a short time. Thanks a lot!

**Comment by joaociocca** [comment]
I'm seeing something that sounds similar, and could have the same root: on windows, if I attach a new display extending my desktop and try to take a screenshot, flameshot will limit the area to the size of the desktop before the new display was attached, anchoring on top-left.
So the "capturable area" of flameshot won't resize to grab the whole desktop.

**Comment by kmephistoh** [comment]
```
gnome-shell-common/kinetic-updates,kinetic-updates 43.1-0ubuntu1 all [upgradable from: 43.0-1ubuntu2]
gnome-shell-extension-prefs/kinetic-updates 43.1-0ubuntu1 amd64 [upgradable from: 43.0-1ubuntu2]
gnome-shell/kinetic-updates 43.1-0ubuntu1 amd64 [upgradable from: 43.0-1ubuntu2]
```

**Comment by kmephistoh** [comment]
upgrade to Ubuntu 23.04, Flameshot works well.
