### ISSUE TITLE
The region capture feature did not work in the Ubuntu22.04 wayland environment

### ISSUE THREAD

**Issue by WX-Yang** [flameshot-org/flameshot#2967]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-52-generic
ubuntu: 22.04

### Installation Type

Flatpak from Github

### Operating System type and version

ubuntu: 22.04

### Description

The region capture feature did not work in the Ubuntu22.04 wayland environment

### System Information

ubuntu: 22.04

**Comment by cnmicha** [comment]
I cannot reproduce this issue under Wayland with Ubuntu 22.10, installed from Ubuntu's repositories using apt-get:
```
Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4
linux: 5.19.0-23-generic
ubuntu: 22.10
```

**Comment by mmahmoudian** [comment]
@WX-Yang please fill all the requested information in the bug report. The current state of bug report lacks so much info that it is invalid. Please explain what you exactly mean by "did not work". Fill the Steps to Reproduce section.

**Comment by WX-Yang** [comment]
> 

I found this problem on my company computer, and I reinstalled Ubuntu2204 through the virtual machine when I got home. The phenomenon is consistent. I don't think this problem is a random one.

**Comment by mmahmoudian** [comment]
I created a clean VM, installed exactly as you wrote and ... It works just fine:

[Peek 2022-11-02 17-14.webm](https://user-images.githubusercontent.com/390889/199527876-5d610ff1-54a0-4d28-9c94-cb5ed736e5a0.webm)

**Comment by WX-Yang** [comment]
> I created a clean VM, installed exactly as you wrote and ... It works just fine:
> Peek.2022-11-02.17-14.webm

I'm so sorry. It's my fault. I don't share after I click the "Take Screenshot" button, which is different from xrog.
Thank you for your reply and sorry for wasting your time.
