### ISSUE TITLE
flameshot lost focus when select area closed to the top of the dock in ubuntu 

### ISSUE THREAD

**Issue by changchichung** [flameshot-org/flameshot#2968]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

linux: 5.15.0-47-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ubuntu 22.04

### Description

call flameshot by custom hotkey ( ctrl +1 ) , then I want to use some tools in flameshot , but I can not select any tool by click icons ( flameshot hotkey still works)  , this happened when the select area closed to the dock in the bottom of the screen

### Steps to reproduce

1. call flameshot ( flameshot gui )
2. select capture area
3. flameshot lost focus

### Screenshots or screen recordings

https://youtu.be/xsrGKHnpahI
about 0:54 , you can see when the select area closed to the top of the dock in the bottom of screen , flameshot will lost focus.

### System Information

1. Operating system and version: ubuntu 22.04 
2. ![](https://i.imgur.com/N466wiQ.png)
3. X11
```
chchang@dc034:~/git$ echo $XDG_SESSION_TYPE
x11
chchang@dc034:~/git$
```

**Comment by mmahmoudian** [comment]
Would you please update to the latest version (at the moment it is 12.1.0) and see if you are still having this issue?

**Comment by changchichung** [comment]
> Would you please update to the latest version (at the moment it is 12.1.0) and see if you are still having this issue?

after updating to 12.1.0, the issue still exists

**Comment by mmahmoudian** [comment]
Thanks for testing. How have you installed the 12.1.0? I installed it via Flatpak on a clean VM and I cannot reproduce the issue:

[Peek 2022-11-04 17-01.webm](https://user-images.githubusercontent.com/390889/200007477-a2ea5228-f86f-4d2d-b98b-8bba4015c4db.webm)

I also tested it on the same VM on Wayland and still couldn't reproduce this.

**Comment by changchichung** [comment]
>> How have you installed the 12.1.0?

```
sudo apt remove apt --purge -y
wget https://github.com/flameshot-org/flameshot/releases/download/v12.1.0/flameshot-12.1.0-1.debian-10.amd64.deb
sudo dpkg -i flameshot-12.1.0-1.debian-10.amd64.deb
```

**Comment by mmahmoudian** [comment]
Sorry, I cannot reproduce that either. Are you able to reproduce that in a VM yourself?:

[Peek 2022-11-07 10-54.webm](https://user-images.githubusercontent.com/390889/200268094-ef4408bf-677a-4425-a120-d5f00cb91191.webm)

**Comment by changchichung** [comment]
I do not have the same issue in a new VM . I will reinstall the system and try again some other day , thanks !
