### ISSUE TITLE
Can I add the function of automatically adding borders after screenshots?

### ISSUE THREAD

**Issue by HeliusHao** [flameshot-org/flameshot#2985]
### Feature Description

Can I add the function of automatically adding borders after screenshots? thinak

**Comment by qoreQyaS** [comment]
do you ask if you may add the functionality of automatically adding a border to a screenshot and want that merged into flameshot or if you are asking if someone could do that for you or if its already possible?

your label hints to the former case, my crystal ball to the latter.

i would do this with imagemagick

see https://imagemagick.org/script/command-line-options.php#border for an explanation of the options

```flameshot gui --raw | convert -bordercolor white -border 20 - output.jpg```
this adds a 20px white border to the screenshots and saves it as output.jpg in the wd

**Comment by mmahmoudian** [comment]
There is already a peripheral dmenu script that does what you are asking and more:

https://codeberg.org/mehrad/dmenu_shot

You can see what it does here:

https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md
