### ISSUE TITLE
feature regressions upgrading to v.11

### ISSUE THREAD

**Issue by michield** [flameshot-org/flameshot#2990]
### Feature Description

I just upgraded my Ubuntu from 20.04 to 22.04 and of course immediately made sure to have my **favourite screenshot tool Flameshot** upgraded and installed as well.

Only to find, the functionality and usability has **dramatically regressed** to the level that it's has become **unusable**.

**Before**, I would pick Flameshot from my system bar, choose the area to screenshot, draw on it to outline the issue involved, click copy and paste it in my issue tracker.

**Now**, I pick Flameshot from my system bar and it simply automatically makes a screenshot of my entire screen and saves it in my Pictures folder. I have various screens. Never in my life would I want a screenshot of all of it. That would require opening the image, editing it, and saving it and all that kind of nonsense. Flameshot was my favourite, because none of that was needed. Now it is. That is a **massive regression in functionality** 

I have searched everywhere in the settings to go back to the old ways, but I can't find any option to tick the box "be a sensible and useful screenshot tool".

No doubt, the developers have decided on this for some reasons known to them, hopefully backed by usability research or something of the kind, and I'm totally different from everyone else who uses Flameshot, but I just want to contribute my use-case and hope some people may agree. 

In the meantime, I'm looking for another tool, because Flameshot has unfortunately become a time-waster.

**Comment by mmahmoudian** [comment]
First and foremost, calm down, breath, and let's investigate this together 🤗. Nothing has changed in that regards.

Is it possible for you to record  your screen and show us what the problem is? From your description I didn't quite understand what you mean.

**Comment by michield** [comment]
Yes, fair enough, maybe that was expressed slightly too over the top as an issue. I can't really give you a screencast, without effectively revealing my entire screen(s), so let me explain what happens.

1. I have flameshot in my system bar as a small icon
2. I select it, and choose "Take screenshot"
3. it takes immediately takes a screenshot of my entire, two, screens.
4. I then get a dialog which has "Options" where I can choose "Select area to grab"
5. I have to take another screenshot
6. Now I have a screenshot of an area of my screen.
7. I can't draw on it, copy it in my clipboard or anything else useful (like I used to be able to)
8. there's some option to "Share with flameshot", but when I do that, nothing happens apart from some weird greyed out dialog in the top left of my left screen.

Instead, before I would use flameshot like this:

1. I have flameshot in my system bar as a small icon
2. I select it, and choose "Take screenshot"
3. It asks me the area to screenshot
4. I draw a rectangle and it takes the screenshot
5. it comes up with the screenshot with tools around it, which allow me to draw on the area I just screenshotted (circles, rectangles, arrows, lines etc) and then I click "Copy" to copy it to my clipboard.
6. Then I go to my issue tracker, eg this one, and paste the image I just copied

I just upgraded to v12, using snap, and it's still the same.

I guess you're trying to create some "service" by having an upload function, but I'm afraid that's not going to work. I'm not going to publish my stuff in places I don't control.

**Comment by michield** [comment]
Ok, looking further into it, I think it may be an Ubuntu issue and not flameshot. When taking the screenshot, I need to share it back with Flameshot to get to the editing part of it. Ubuntu has made this totally unusable. 

I will investigate further and will re-open if it's still an issue.

**Comment by mmahmoudian** [comment]
> looking further into it, I think it may be an Ubuntu issue and not flameshot. 

You may want to read this:
https://flameshot.org/docs/guide/wayland-help/#gnome-wayland

> I guess you're trying to create some "service" by having an upload function, but I'm afraid that's not going to work. I'm not going to publish my stuff in places I don't control.

Again, I think the tone is inappropriate. Few extra points:
1. Flameshot is free (as in "free beer" and as "freedom") software. All the source code is publicly available, so you can read the code and make sure nothing nasty is being done.
2. We are not even accepting donation (for reasons that [is stated on our website](https://flameshot.org/donate/). So I can't see how we are giving any "service"!!
3. This is a classic PEBCAK. You might want to read the documentation and troubleshootings that we have put countless hours into helping users.
4. You **chose** to use Gnome, and you are getting the bad experience they created. One solution: Switch to something else (e.g KDE Plasma).
5. I'll be happy to guide you further (hopefully no further base-less accusations and pointing fingers in return)

**Comment by michield** [comment]
>     1. Flameshot is free (as in "free beer" and as "freedom") software. All the source code is publicly available, so you can read the code and make sure nothing nasty is being done.

Yes, I know. I've done that for 25 years.
> 
>     2. We are not even accepting donation (for reasons that [is stated on our website](https://flameshot.org/donate/)). So I can't see how we are giving any "service"!! We are volunteers who are creating software out of passion.

Admirable. As I stated from the start, it's one of my favourite tools and I recommend it all the time.
> 
>     3. This is a classic PEBCAK. You might want to read the documentation and troubleshootings that we have put countless hours into helping users.

Who's accusing whom of inappropriate tone? It is definitely a problem, and not imagination. I was wrong, and corrected myself, in pointing at flameshot. My sincere apologies for jumping to the wrong conclusion too soon. The issue is still there, regardless of documentation. It's just that it is caused by a different project.

> 
>     4. You **chose** to use Gnome, and you are getting the bad experience they created. One solution: Switch to something else (e.g KDE Plasma). As a side note, in the next gnome this wonky behavior is fixed!

No, I don't choose Gnome. I choose Ubuntu, as it's the distro that has given me stability for years. I used to compile my own kernels, I don't do that any longer either. I used to switch KDE and Gnome and found myself caught up in some project feud, I don't care about that any longer either. My focus is on a working platform, not knowing the details of each application.

> 
>     5. I'll be happy to guide you further (hopefully no further base-less accusations and pointing fingers in return)

Thanks, you've been very helpful and patient. If your first reply had been "yes, that's a known issue, with a link" we would both have wasted a little less time. I'm sorry about my tone, that was incorrect, but I was just upset that my favourite tool seemed to have gone rogue. I'm pleased to find out I was wrong.

**Comment by mmahmoudian** [comment]
Thank you for your reply. I disagree with your Gnome statement, but that is off-topic. Regardless, I hope you enjoy using Flameshot and also if possible consider contributing back. Wish you a nice and productive week ahead :+1:
