### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Aspartaco** [flameshot-org/flameshot#2991]
### Feature Description

Where is the download? It's not in the website and I can't find it here.

**Comment by mmahmoudian** [comment]
It is there:
https://flameshot.org/

If you cannot find it, please comment.

**Comment by Aspartaco** [comment]
> It is there: https://flameshot.org/
> 
> If you cannot find it, please comment.

I can't find it there. All it has is a link to this github.

To be specific, I'm looking for the portable Windows version, but I can't find the installer either.

**Comment by mmahmoudian** [comment]
![image](https://user-images.githubusercontent.com/390889/203075840-6d7b3a35-ae0c-46ba-9c84-91137210da35.png)

![image](https://user-images.githubusercontent.com/390889/203075945-fcc59997-cf21-408e-9966-2134f6d4f3fe.png)

![image](https://user-images.githubusercontent.com/390889/203076018-f043beb1-9129-45a4-8cbd-b3f0d5759d30.png)

![image](https://user-images.githubusercontent.com/390889/203076105-0d8c42a3-7915-458c-9a5c-10e01b38701d.png)

![image](https://user-images.githubusercontent.com/390889/203076194-b589fd7b-1d88-409f-9484-7dcb11da3338.png)

![image](https://user-images.githubusercontent.com/390889/203076524-03d6fa34-c6c5-4fd8-8784-02be0ec082ec.png)

**Comment by Aspartaco** [comment]
Ok thanks. I had a look there and thought the whole list was source files, since most of the extensions are unknown to me.

**Comment by mmahmoudian** [comment]
No worries. I'm glad I was useful and you got what you were looking for.

Just in case it help you later, the `.msi` stands for "Microsoft Installer", `.exe` is "executable" which you will find inside that `.zip` file
