### ISSUE TITLE
Windows 11 - no side panel

### ISSUE THREAD

**Issue by Lungshot** [flameshot-org/flameshot#3002]
The hotkey assigned does not open the side panel at any point for me. 
I tried changing the hotkey to different things.
Dual monitors - one running 2560x1080 and another 1920x1080. 
-----DISABLING MY 1920X1080 MONITOR FIXED THE ISSUE BUT IT RETURNS WHEN IT IS ENABLED AGAIN------
Would love to be able to run both with flamshot.
Latest version of everything - drivers etc. Nvidia GTX graphics card.

Package was installed with chocolatey, but I uninstalled and tried the development MSI installer x64 and the normal release installer.

Config export:
[General]
savePath=C:/Users/USERNAME/Desktop
contrastOpacity=232
drawColor=#00ff00
drawFontSize=3
startupLaunch=true
userColors=picker, #800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080, #ffffff, #000000
drawThickness=12
showMagnifier=true

[Shortcuts]
TYPE_TOGGLE_PANEL=Ctrl+Space

**Comment by mmahmoudian** [comment]
Please fill a complete bug report. This is not valid as it lacks all the necessary information, and it has a structure very different from what we are asking.

Thanks.
