### ISSUE TITLE
Can't capture a popup window of a FireFox add-on

### ISSUE THREAD

**Issue by ilyaigpetrov** [flameshot-org/flameshot#3005]
### Feature Description

1) I click some extension icon in FireFox -- popup window opens.
2) I press "PrtSc" (print screen) on the keyboard.$ apt version firefox
107.0.1+linuxmint1+vanessa
3) Popup closes, FlameShot shows it's dialogue.

Expected: popup window doesn't close, FlameShot shows its capture dialogue.

There is no such problem with Chrome.

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-56-generic
linuxmint: 21

```sh-session
$ apt show firefox
Package: firefox
Version: 107.0.1+linuxmint1+vanessa
Priority: optional
Section: web
Maintainer: Clement Lefebvre <root@linuxmint.com>
Installed-Size: 242 MB
Provides: gnome-www-browser, www-browser
Pre-Depends: ubuntu-system-adjustments (>= 2021.12.16)
Breaks: firefox-dbg (<< 95.0.1+linuxmint1+una), firefox-dev (<< 95.0.1+linuxmint1+una), firefox-geckodriver (<< 95.0.1+linuxmint1+una), firefox-mozsymbols (<< 95.0.1+linuxmint1+una)
Replaces: firefox-dbg (<< 95.0.1+linuxmint1+una), firefox-dev (<< 95.0.1+linuxmint1+una), firefox-geckodriver (<< 95.0.1+linuxmint1+una), firefox-mozsymbols (<< 95.0.1+linuxmint1+una)
Download-Size: 68,8 MB
APT-Manual-Installed: yes
APT-Sources: http://packages.linuxmint.com vanessa/upstream amd64 Packages
Description: The Firefox web browser
 The Mozilla Firefox Web Browser.

$ apt version firefox
107.0.1+linuxmint1+vanessa

$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
Codename:       vanessa

$ uname -a
Linux netbook 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

![ffx-about-mint](https://user-images.githubusercontent.com/1090811/206040809-8bcb8f68-7b55-48bb-8aa0-fdf26af9aa5c.png)

With Chrome popup doesn't close:
![chrome-popup-shown](https://user-images.githubusercontent.com/1090811/206041878-f806330d-c364-4d59-af03-216ef8da7614.png)

**Comment by mmahmoudian** [comment]
Use delay timer using the Flameshot Launcher. What you are explaining is how window managers and Firefox behave.
