### ISSUE TITLE
Remove strange black and white border around counter numbers

### ISSUE THREAD

**Issue by fabiochelly** [flameshot-org/flameshot#3008]
### Feature Description

When I insert counter numbers, there is strange triple border (white/black/white) around the circle. Is there a way 
![sandwich](https://user-images.githubusercontent.com/4060753/206737596-019b5e78-0a4b-41c5-8825-507c761a5afe.png)
to remove it?

**Comment by mmahmoudian** [comment]
No, that is our design. Perhaps it can be set to be customizable at some point if you create a well-formatted feature request. The current format is not suitable to be considered as a feature request.
