### ISSUE TITLE
New shortcuts to capture screen and last tool

### ISSUE THREAD

**Issue by fabiochelly** [flameshot-org/flameshot#3009]
### Feature Description

Is there a way to use another shortcut to capture screen than the "Print Screen" button? On my laptop, that key is not easy to use and I would prefer to use Ctrl+Shift+S for instance that we can find on other apps.

And can Flameshot remember the last tool we used ? (I always use the ellipse tool and I have to select it at every screenshot)

**Comment by mmahmoudian** [comment]
> Is there a way to use another shortcut to capture screen than the "Print Screen" button?

Yes. It is something that your window manager should do. If you are using Microsoft Windows you have few options one of which is explained on our website:

https://flameshot.org/docs/guide/windows-help/

The other way is https://www.autohotkey.com/

If you are on Linux or BSD, follow instructions of your window manager.

> And can Flameshot remember the last tool we used ?

No. But you can use keyboard shortcut to select tools
