### ISSUE TITLE
Flameshot not pasting into discord.

### ISSUE THREAD

**Issue by interstate420productions** [flameshot-org/flameshot#3021]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 6.0.6-76060006-generic
pop: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop OS:  22.04

### Description

Suddenly from one day to the next  My beloved Flameshot quit pasting into Discord

### Steps to reproduce

Take a screenshot
Open Discord.
Try to paste.

### System Information

Dell G15 Alienware
Pop OS 22.04

**Comment by ardishco-the-great** [comment]
try the web version of discord to see if it's actually pastable or something else like obsidian, discord sometimes just doesn't let you paste big images...

**Comment by mmahmoudian** [comment]
@interstate420productions as you know we have not released an update for few months now. Perhaps either the issue stems from what @ardishco-the-great kindly suggested, or from discord update.

Please do this test and let us know the results:
1. Use flameshot and copy the screenshot
2. Open LibreOffice or Inkscape or Gimp (which ever you have) and paste the image
3. Also, paste a screenshot in your browser (e.g in the comment section of this thread)

Let us know which one worked and which one didn't

**Comment by ManuSecsearch** [comment]
In my case i was unable to copy / paste into obsidian and the issue was coming from the fact that the general/settings 
*Use JPG format for clipboard (PNG default)* was checked. Don't know if this help

**Comment by ardishco-the-great** [comment]
@mmahmoudian Discord has seen 3 major updates ever since this post was made and the probem is still there but It's been fixed somewhat, I'm pretty sure the method that flameshot uses to copy it the clipboard is kinda flawed in this way because with some apps it works but with some not so much

**Comment by v1sages** [comment]
"Use jpg format for clipboard option" unchecked does NOT fix this issue on my system. 
When I run flameshot via terminal and take a screenshot, then copy to clipboard using `ctrl + c`, I can see that flameshot copied the image to the clipboard. However, I am still unable to paste in any other application, including Signal-desktop and Discord. 
I am using i3wm and dunst for notifications. Please advise. I'd really like for Flameshot to work this way again on my system.
