### ISSUE TITLE
Doesn't work main feature - screenshot - Flameshot v12.1.0 MacOS 13.0.1

### ISSUE THREAD

**Issue by averholantsev** [flameshot-org/flameshot#3028]
### Flameshot Version

Flameshot v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS 13.0.1 (Macbook Pro 2019 Intel)

### Description

Then I tried to take a screenshot by hotkeys or right click by icon in upper Dock menu I have a bug... Take a look👇
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44668485/208291343-19fbf848-f5e5-453a-bb5b-f129431ee017.gif)

In previous version 11.X.X all works fine.

### Steps to reproduce

0. install by brew install flameshot
1. run flameshot
2. right click on flameshot icon in dock
3. click on Take Screenshot
4. Take a area
5. Have an empty screen without content, just background image

### System Information

MacOS 13.0.1 (Macbook Pro 2019 Intel)
Flameshot v12.1.0 (previous v11.X.X)

**Comment by mmahmoudian** [comment]
Please delete the permission and give it again. This is a know macOS issue and you should do this for every new version of Flameshot (or any other software). We can bypass this by paying money to Apple, but we don't want to pay Apple tax.

Read more here:

https://flameshot.org/docs/guide/troubleshooting/#macos

Also it would be a good idea to check our documentation first. It would save you lots of time.
