### ISSUE TITLE
Flameshot GUI won't open

### ISSUE THREAD

**Issue by jamiehewitt15** [flameshot-org/flameshot#3030]
### Flameshot Version

Currently using Flameshot v12.1.0
But also had the same issue with Flameshot v11 (I tried updating to see if that would solve the issue)

### Installation Type

Snap from

### Operating System type and version

Ubuntu 22.04.1 LTS

### Description

If I type the command `flameshot gui` it will just immediately take a screenshot, it doesn't open the GUI. 

Also, when I click "Open Launcher" Flameshot just takes a screenshot, it won't open the GUI.

### Steps to reproduce

1. `flameshot gui`
2. For me this fails to open the gui, it just takes a screenshot of my entire screen. 
3. Getting the following error in the terminal: 

```
~$ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Qt: Session management error: Could not open network socket
```

### System Information

1. Ubuntu 22.04.1 LTS
2. Have tried both with my external monitor and without. 
3. Flameshot v12.1.0 ()
Compiled with Qt 5.15.3

$ echo $XDG_SESSION_TYPE
wayland
$ /usr/bin/gnome-shell --version
GNOME Shell 42.5

**Comment by Oneloutre** [comment]
I think Wayland is known to be troubleful, when you see how much issues related to wayland there is...

**Comment by mmahmoudian** [comment]
@jamiehewitt15 please check documentation before opening an issue:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

**Comment by jamiehewitt15** [comment]
> Also it have been asked more than 70 times already. So searching among open and closed issue would save everyone's time

Thanks for pointing me in the right direction. Before opening it, I had a look in the open issues and FAQ and didn't see anything related. Given that this has been raised so many times (70+) it would be great to add it to the FAQ, that should help prevent further duplicate issues raised here.

**Comment by Infinixius** [comment]
It's pretty hard to miss, but I agree it should be added to the FAQ.

![image](https://user-images.githubusercontent.com/68125679/209836890-8ee14ff9-263f-4ea8-8704-4cea86a43fc2.png)

**Comment by mmahmoudian** [comment]
It literally is the first pinned issue. Also this is Wayland ans Gnome specific. But ok, I'm open to add yet another thing since you two and @brlin-tw in the following issues raised it:

https://github.com/flameshot-org/flameshot-org.github.io/issues/108

Please tell me your opinion what is the best way to convey this message. Let's discuss it in the thread above, and have a solid solution once and for all. I'm sorry that I have such vibe, but it is out of frustration. Thank you all for helping us figuring this out.
