### ISSUE TITLE
option to disable upload

### ISSUE THREAD

**Issue by AlBundy33** [flameshot-org/flameshot#3042]
### Feature Description

I think disabling the upload function could be necessary in enterprise environments.

**Comment by mmahmoudian** [comment]
Duplicate. Please search before posting

**Comment by AlBundy33** [comment]
I thought I did it but i think that I've only checked the settings.

In #1529 is explained how to disable the upload
https://github.com/flameshot-org/flameshot/issues/1529#issuecomment-812110134
