### ISSUE TITLE
select window for screenshot

### ISSUE THREAD

**Issue by AlBundy33** [flameshot-org/flameshot#3043]
### Feature Description

It would be nice if I could select a complete window for a screenshot.
-> without manually selecting the region of course

**Comment by mmahmoudian** [comment]
Duplicate. Please consider searching in open **and** closed issues before posting new ideas. It would save you some time and you'll get to answer much faster.

On x11 there is a solution, on Waland, mac, windows nothing

**Comment by AlBundy33** [comment]
#334
