### ISSUE TITLE
Flameshot v12.1.0 not working on Ubuntu 22.10 (ker 5.19.0-28): Showing Unable to capture screen

### ISSUE THREAD

**Issue by Akshaychdev** [flameshot-org/flameshot#3047]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux-Ubuntu 22.10 (kernel-5.19.0-28)

### Description

Flameshot fails to start or capture screen on Ubuntu 22.10 - with windowing system Wayland

### Command line output

```bash
> flameshot gui

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.
```

run `QT_QPA_PLATFORM=wayland flameshot` with same result
 
### Already Tried

- Installed `xdg-desktop-portal-gnome`, `xdg-desktop-portal`
- Installed `xapp` to remove this warning
   ```bash
   Gtk-Message: 12:13:21.471: Failed to load module "xapp-gtk3-module"
   ```

### Steps to reproduce

1. Run `flameshot gui` on the terminal

### Screenshots or screen recordings

Error Notification on panel
![image](https://user-images.githubusercontent.com/63786863/211135458-6bd5dd4a-6eab-48d9-baec-08e447b6a16d.png)

### System Information

1. Linux-Ubuntu 22.10 (kernel-5.19.0-28)
2. Monitor Setup
![image](https://user-images.githubusercontent.com/63786863/211136481-48f7c833-6454-40c7-a047-dbb6e8137aa4.png)
3. Using Wayland on Ubuntu 22.10

**Comment by mmahmoudian** [comment]
Cannot be reproduced!


[Peek 2023-01-25 16-28.webm](https://user-images.githubusercontent.com/390889/214589631-52e46b72-4ec1-4a50-8c2b-182511605d69.webm)

**Comment by Akshaychdev** [comment]
It was issue with 'wayland' enabled, also facing the same with wayland on Ubuntu 24.04

Only option worked for me was to install it using flatpak

```bash
sudo apt install flatpak

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.flameshot.Flameshot
flatpak permission-set screenshot screenshot org.flameshot.Flameshot yes

# Check working
flatpak run --command=flameshot org.flameshot.Flameshot gui

# Verify
flatpak list
```

After that I can use it, also able to add Keyboard shortcut to
`Ctrl + Print` -> `flatpak run --command=flameshot org.flameshot.Flameshot gui`
