### ISSUE TITLE
mac install issues

### ISSUE THREAD

**Issue by miarosemathews** [flameshot-org/flameshot#3049]
### Flameshot Version

Hi, when i try and install my mac says it cannot install because apple cannot verify this software is free from malware.

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

mac os 12.6.1

### Description

When downloading from https://github.com/flameshot-org/flameshot/releases/tag/v12.1.0

### System Information

Mac os 12.6.1

**Comment by mmahmoudian** [comment]
Sorry, but this is a bug. This is the way apple forces developers to pay Apple a lot of money for getting some useless certificate. 

If you want to check for malware, you can send any of our files from [our release page](https://github.com/flameshot-org/flameshot/releases) to the following link:

https://www.virustotal.com/gui/home/upload

Flameshot is an opensource software and it is free (as in freedom and free of charge), we don't have any source of income to have funding for such nonsenses that companies try to pull off (basically it is a bribe).

Anyways, like any software use it at your own risk, but if you cannot trust us (which you ideally should not) you can either read the source code to make sure nothing nasty is going on, or as I mentioned, you can some tools to scan the files.

Also make sure to always download the .dmg from our release page or use HomeBrew that is using out Github repo to compile or our release .dmg . Any other sources are not at all under our supervision and control.

**Comment by miarosemathews** [comment]
I verified it myself m. How much is the certification cost through apple?

**Comment by mmahmoudian** [comment]
> How much is the certification cost through apple?

I don't know. It feels like an extortion, so the collective agreement have been to not getting it. Plus it might come with some terms of use that can be potentially against the freedom of the project.

From where I stand, Flameshot is Free and Libre OpenSource Software with reproducible builds, and a normal user can verify everything. So it is relatively easy to prove that our software does not have malware, but no user can be 100% confident that Apple stuff is malware-free. No thirdparty can audit their code. And yet they have the audacity to put such message (yes I know it is a general message and not only for flameshot, but my point it the same warning should be applied for all non-opensource apple software).

Anyways, the bottom-line is that we (developers of Flameshot) are already paying too much off our own pocket and our own personal time, that we don't want to pay some ransom money just to bypass a useless warning message.

If you are thinking about donating the certificate, I encourage you to read our donation page:

https://flameshot.org/donate/

**Comment by iddqdiddqd** [comment]
Troubleshooting documentation has been filled out with the solution to this issue in https://github.com/flameshot-org/flameshot-org.github.io/pull/151

**Comment by NatHrab** [comment]
it still won*t work

**Comment by antoncyrol** [comment]
You can open Flameshot as follows (worked for me):
https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html

**Comment by NatHrab** [comment]
> You can open Flameshot as follows (worked for me): https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html

Thank you. It helped
