### ISSUE TITLE
Fedora 37 xfce4 custom .desktop files, not expanding Desktop Entry field codes (%f, %F, etc) ?

### ISSUE THREAD

**Issue by oveee92** [flameshot-org/flameshot#3050]
I have a newly installed (and updated) Fedora 37 with xfce4, and have installed flameshot using the package manager. 
I've created a custom `zbarimg-flameshot.desktop` file that should launch zbarimg to read QR codes, using a simple script:

```ini
[Desktop Entry]
Version=1.0
Name=QRread
GenericName=QR_code_reader
Comment=Application to read a QR code
Exec=/usr/local/bin/zbarimg-flameshot %F
Terminal=true
Type=Application
Categories=Graphics
```

The script being launched is not really important for this Issue as it never gets this far in the execution, but for completeness' sake:

```bash
#!/bin/bash
zbarimg --display $1
echo "Press Enter to close!"
read
```

This works on my Rocky 8 xfce desktop, with Flameshot v0.6.0.

I'm trying to make it work on Fedora 37 with Flameshot v12.1.0 (-)

## Expected and actual behaviour

It should immediately open a new terminal, like so:

![image](https://user-images.githubusercontent.com/49921317/211194690-adf60c8b-8b1d-4903-b0f7-c9f886850989.png)

Instead, I get this:

![image](https://user-images.githubusercontent.com/49921317/211194732-a0e94a63-c40d-4f79-b846-0c2ffe9e7a13.png)

For some reason it just doesn't expand the %F field code when it comes from flameshot.

## What I've tried:

- Removing the `%F` field code
  Now the application won't show up in the "Open With" dialogue of Flameshot, so I won't get any further
- Using `%f` or `%U` instead
  Same issue as before
- Tried adding double qoutes around the entire command, and around just the field code
  Same issue as before
- Removing the absolute path, and letting it fall back to the $PATH variable
  Same issue as before, and this was not neccesary on my Rocky 8.
- Open the capture with Ristretto Image Viewer, which uses `%U`
  Works fine, the picture is opened in the image viewer
- Run the command `gtk-open zbarimg-flameshot /tmp/2023-01-08_12-23.png` to simulate executing the .desktop file
  Works fine, the new terminal opens as expected

I've also rebooted, verified that mode, ownership and selinux contexts are the same as the others, and that the script is executable.

Not sure what Flameshot does internally to use the desktop entries, but I don't quite know what could be wrong here; the flameshot launcher seems to work since I can open other applications, the .desktop entries seem to work since I can use gtk-open successfully, and the configuration as a whole should work since it works on my Rocky 8 install, which is pretty similar.

Does anyone have an idea what the problem might be, or how I can continue troubleshooting?

**Comment by mmahmoudian** [comment]
I'm sorry, but which part of this are you using Flameshot?

**Comment by oveee92** [comment]
I'm using the "open with application" button after taking a capture with the gui (cannot remember the exact name of the button, I'm currently on mobile) to open my custom .desktop file. 

After clicking the icon for my custom desktop entry, it fails as shown in the screenshot in the original post. 

Sorry if that wasn't clear!

**Comment by oveee92** [comment]
Still not sure why it isn't working, as it is working fine with the exact same config using Rocky 8 w/XFCE; Most likely due to changes in XFCE4 though, not Flameshot :)

Bottom line is, it looks like the .desktop file cannot execute bash scripts directly in Fedora 37. This might become relevant to others who want to execute custom scripts, so here's what worked for me:

Remove `Terminal=true` from the .desktop file, and then set `Exec=exo-open --launch TerminalEmulator flameshot_qr %F`

**Comment by mmahmoudian** [comment]
Thanks for the detailed comments.
