### ISSUE TITLE
Open preconfigured Saved Folder from Tray Icon

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#3055]
### Discussed in https://github.com/flameshot-org/flameshot/discussions/3053

<div type='discussions-op-text'>

<sup>Originally posted by **npatel007** January 10, 2023</sup>
It will be lot more convenient to add Open saved screen capture folder by clicking on tray icon (right click) </div>

**Comment by kurayami07734** [comment]
Please assign me to this issue

**Comment by kurayami07734** [comment]
Is there discord channel for flameshot?
I want to ask a few things

**Comment by mmahmoudian** [comment]
No, Discord is against the FLOSS philosophy of this project. We have a Matrix Space which contains multiple channels. You can join via the following URL:
https://matrix.to/#/#flameshot-org:matrix.org

There are Help, Announcement, and [Developers](https://matrix.to/#/!AYbNXDGTDwApLwzkNg:feneas.org?via=kde.org&via=matrix.org&via=ryan77627.xyz) Channels. I believe the latter is what you are looking for.

**Comment by espdev** [comment]
Hello,

This is a useful feature!

It would also be nice to be able to open a pre-configured saved folder after saving a screenshot with the screenshot selection (enabled/disabled by an option in the settings).

This is a fairly common use case where I need to access a file immediately after saving a screenshot.
