### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by karlhorky** [flameshot-org/flameshot#3057]
### Feature Description

Hi Flameshot maintainers! 👋 Thanks for your continuing work here, really great tool.

Since AVIF is now supported in [79% of browsers](https://caniuse.com/avif) (with [Safari in macOS Ventura and iOS 16 supporting it](https://www.coywolf.news/webdev/safari-supports-avif-in-macos-ventura-and-ios-16/)), would you consider adding this as an output format for screenshots? This would allow for smaller images.

**Comment by mmahmoudian** [comment]
Thank you for making a feature request. I suggest you to [search for things](https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+AVIF) before making a new feature request as it saves your time. 😉 

As of #1680 (2021-07-31) we allow saving in any supported format. In the screenshot below:
1. This is where you can find it (if you have the updated version of Flameshot)
2. Github itself does not support this format

![image](https://user-images.githubusercontent.com/390889/212862912-4c889592-30c3-479d-915d-9eed6d2a02f2.png)

**Comment by karlhorky** [comment]
> I suggest you to [search for things](https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+AVIF+sort%3Aupdated-desc) before making a new feature request as it saves your time

I did search with multiple search terms. That search link you provided does not return the issue #1680, nor is AVIF mentioned on that page.

Also, it's unclear what a "supported format" means:

1. Supported by which software?
2. Once we know what the software is that should support the file format, where exactly can a user find the supported list of file formats for this software? If this is dependent on the OS, where can users find support lists for older versions of the OS?

Eg. I tried the latest released version ([`v12.1.0`](https://github.com/flameshot-org/flameshot/releases/tag/v12.1.0), released 3 July 2022), and there is no option to save AVIF files on macOS (see version details below):

```
Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5

darwin: 22.2.0
osx: 13.1
```

I checked for updates, but Flameshot reports that there are no new updates available.

**Comment by karlhorky** [comment]
Ok, understood. Looks like [v11.0 Beta](https://github.com/flameshot-org/flameshot/releases/tag/v11.0.rc1) was the release with the change:

> - Every file format supported by your underlying system is now an option for file format when saving.

In my opinion, as a software package, it is the responsibility of Flameshot to its users to document these things, eg:

- Changelogs detailing which version on which OSes supports a feature - this seems to be partially there, but I would expect that some file formats would be mentioned in the release notes for v11.0 Beta
- The Flameshot docs should mention this feature, including details about installation and correct usage of additional packages, if necessary

But I understand it's a community-run project and sometimes things are not completely documented.

However, that's also another good reason to open the issue - there were no other details specifically about AVIF in other issues or documentation, and now this issue serves as at least a rudimentary level of documentation for other users.

**Comment by karlhorky** [comment]
> I am not a macOS user, but perhaps you can try installing appropriate libs (e.g [libavif](https://formulae.brew.sh/formula/libavif)). On Arch Linux `sudo pacman -S libavif` should do the trick I guess.

The reason for these instructions above is still unclear to me. I don't understand what Flameshot is doing to check for "support" for a given file format on an operating system.

Given my experience with software packages which have dependencies on other software packages, usually the dependent package knows what other software packages it requires and has dependencies on. Therefore I was expecting my question of "Supported by which software?" to have a clear answer, something like:

- for AVIF, Flameshot will look for the `x` binary, install it like this...
- for WebP, Flameshot will lookk for `y`, install it like this...
- etc

But apparently it can support any binary that it finds? How would Flameshot know that I have some random AVIF encoding library installed on my OS?

**Comment by novomesk** [comment]
Flameshot is Qt application and image formats are supported via plug-ins.

On Linux systems where the AVIF plugin is installed, Flameshot can save AVIF images. When the plug-in is not present, Flameshot cannot save AVIF images.

Installing libavif is not enough. My qt-avif-image-plugin uses libavif and libaom. I am able to build it on Linux and Windows. Unfortunately I cannot tell you how to built it on macOS, but I know that author of qView image viewer was able to do it.

**Comment by karlhorky** [comment]
@novomesk Thanks for the additional details!

@mmahmoudian since there are additional details about other packages here which are relevant, maybe this could indeed be fully documented by Flameshot. Would you be ok with reopening this issue? If not, I can create another issue for adding documentation on how to enable support for file formats on all OSes.

**Comment by karlhorky** [comment]
@mmahmoudian Thanks for reopening! I've also updated the title and description of the issue.

**Comment by bugb** [comment]
@mmahmoudian thank you so much for making the awesome software.
Currently I am using Arch with the latest Flameshot version. I cannot find the format `webp` when saving

![image](https://github.com/flameshot-org/flameshot/assets/9280412/5939db61-42f0-4d9c-9572-eee01c795b1d)

I have installed the package `libwebp` btw.

Do you have any ideas?

**Comment by onkoe** [comment]
@bugb i don't use Arch, but on Fedora, it requires `qt5-imageformats`.

if you can find a similar package on your distribution, it should work out the same! 

![image](https://github.com/flameshot-org/flameshot/assets/66580279/cf55f1dc-594c-45da-8e99-ac7f8279d610)

**Comment by edmundlaugasson** [comment]
`qt5-imageformats` package is also on Arch Linux available and solves the issue - then also other file formats are available. Although there is also `qt6-imageformats` available. This is question, when Flameshot is planning to use Qt6...
Although have `libavif`, `libheif` installed, still no avif format in list of supported image file formats. It might be, that since Flameshot was last updated on 2022, then newer components might not comply with older Flameshot ones.
![Image](https://github.com/user-attachments/assets/13c37a36-c5f1-4927-9f77-ace889b42e02)

Such additional dependencies, e.g. about image file formats would be appreciated if these could be described also in guidance https://flameshot.org/docs/installation/installation-linux/ - in the end of that document there even are _runtime dependencies_ but would propose to add additional chapter _file format dependencies_ where could be described, which additional packages in case of which image file format should be installed.

We can consider also [other alternatives](https://alternativeto.net/software/flameshot/?feature=screenshot-capture&license=opensource&platform=linux) if Flameshot remains not updated. E.g. [Shutter](https://shutter-project.org/) is a bit newer ([2024 currently last update](https://github.com/shutter-project/shutter/releases)).

**Comment by mmahmoudian** [comment]
@edmundlaugasson 
> This is question, when Flameshot is planning to use Qt6...

That is a big porting step, and considering that Flameshot is completely volunteer-based software, we need a developer with enough free time and knowledge of Qt6 to port the code to Qt6. 

> Seems like kind of pull request about supporting additional image file formats is waiting since September 14, 2023 - #3334

Yes, you can of course test that PR (at your own risk) and tell us how it goes and if it breaks something. We need rigorous checking of every PR to make sure:
1. The PR works as intended
2. It doesn't break other features
3. It doesn't contain malicious code

So any help from the community is highly appreciated

> It might be, that since Flameshot was last updated on 2022, ... We can consider also other alternatives if Flameshot remains not updated.

Of course you are free to choose the software that you want to run on your computer as a fundamental rule of the Free Software. That said, I should emphasis that Flameshot **have been updated** , but we have not released a stable release. It is funny how people don't see the commit history and just rely on release dates as how active a project is! If you want to download the latest bleeding edge version, they are available here:

https://flameshot.org/docs/installation/development-build/

> would propose to add additional chapter file format dependencies where could be described, which additional packages in case of which image file format should be installed.

Great. Our website is also OpenSource and we welcome PRs for improvement. Would you care to create a PR?

https://github.com/flameshot-org/flameshot-org.github.io

**Comment by Wylbur** [comment]
For anyone landing here that is looking for file format support on Linux, please note.  I installed the latest Linux download https://github.com/flameshot-org/flameshot/releases/download/v13.3.0/flameshot-13.3.0-1.ubuntu-24.04.amd64.deb.  This version does NOT support many file formats that are available with the same version of the flatpak version!  There are 26 formats available via the flatpak version and less than a dozen with the .deb version.  

For me it was specifically missing the .webp extension.  

Not sure why the versions are so far apart!  Hope this helps someone else looking for options!

**Comment by ElTh0r0** [comment]
@Wylbur do you have **qt6-image-formats-plugins** installed on your system? It is marked as [suggested](https://github.com/flameshot-org/flameshot/blob/51a55180fbed01ea08b3697278e3380083b036af/packaging/debian/control#L43) in the deb package, so it must be explicit selected for installation.  This should add webp.
