### ISSUE TITLE
Clipboard works sometimes

### ISSUE THREAD

**Issue by Carlos12001** [flameshot-org/flameshot#3058]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Windows Package manager (winget.)

### Operating System type and version

Windows 10

### Description

When I try to take a screenshot sometimes work, but in the most of time doesn't work. I installed Flameshot with winget. I don't know if that would affect.

### Steps to reproduce

1. run `Capture screen`
2. select a region on the primary monitor
3. Copy the selection to clipboard
4. I verify with Windows Clipboard History
5. **The image isn't there.**

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/62664256/212385674-79bb7dd1-c604-444a-8605-3b56017c2ec0.png)
![image](https://user-images.githubusercontent.com/62664256/212385843-a75d9e27-d721-4ba0-8161-6244ce54268f.png)

### System Information

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎30/‎2022
OS build	19045.2486
Serial number	009329593357
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by phante** [comment]
I have the same issue

**Flameshot Version**

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

**Installation Type**

Windows Package manager, scoop

**Operating System type and version**

Windows 10

**Description**

Take a screenshot, save it to clipboard using Ctrl+C or the interface buttom, the clipboard remains empty.

**System Information**

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎31/‎05/‎2021
OS Build	19044.2364
Experience Windows Feature Experience Pack 120.2212.4190.0

**Comment by minitolgy** [comment]
Do you have enabled jpg format? At least in my case it worked again after disabling it.

**Comment by Carlos12001** [comment]
> Do you have enabled jpg format? At least in my case it worked again after disabling it.

Yes it was that. I turned off the jpg option and it worked again. Thank you.
