### ISSUE TITLE
Selection/Annotation Tools not available

### ISSUE THREAD

**Issue by realAnish9** [flameshot-org/flameshot#3063]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04

### Description

Flameshot does not show rectangle selection area and tools, Just takes screenshot as shown below
![ezgif com-gif-maker](https://user-images.githubusercontent.com/23690070/213565237-a3de6c5d-4b8a-4b01-99bf-ccf349e00482.gif)

### System Information

Monitors: 3
 0: +*XWAYLAND0 1920/310x1080/170+0+0  XWAYLAND0
 1: +XWAYLAND1 1920/510x1080/290+3840+0  XWAYLAND1
 2: +XWAYLAND2 1920/510x1080/290+1920+0  XWAYLAND2

**Comment by artptr** [comment]
I got the same issue after upgrading from Ubuntu 20.04 to 22.04.

**Comment by mmahmoudian** [comment]
@realAnish9 @artptr please read this:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
