### ISSUE TITLE
Window focus losts after flameshot exit

### ISSUE THREAD

**Issue by backdround** [flameshot-org/flameshot#3065]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Archlinux

### Description

Window doesn't get focus back after flameshot exit.

### Steps to reproduce

1. Run any window to get focus
2. Run `flameshot gui`
3. Exit from flameshot (Esc)
5. Get notification
6. Inspect no focus on the window

### System Information

- Archlinux
- i3-wm (4.22-3)
- no picom is running (#1694)

**Comment by backdround** [comment]
The modified workaround from #784 works fine for me:
```bash
set -euo pipefail
FOCUSED_WINDOW=$(xdotool getwindowfocus)

flameshot gui || true

test "$FOCUSED_WINDOW" = "$(xdotool getwindowfocus)" || {
	xdotool windowfocus $FOCUSED_WINDOW
}
```

**Comment by mmahmoudian** [comment]
I don't think this is something that we can control. Your window manager is responsible for assigning focus to different windows.

Your best chance is to discuss this with the i3 community and see how it can be addressed (most probably a small line in your i3 config).
