### ISSUE TITLE
MacOS: Active tool size is not saved

### ISSUE THREAD

**Issue by Dr4hcir** [flameshot-org/flameshot#3070]
Set tool size large, so that a drawing of a rectangle is very thick
make a screenshot
Now, make a second screenshot
Select rectangle tool (s)
hit 'space' to check settings

Expected: Active tool size is saved. It's still thick, so I expect my rectangle to be thick also

Result: Very narrow drawing. I have to actively move the 'Active tool size' every time I make a screenshot. As you see here the setting is thick, but the actual drawing is thin.
![image](https://user-images.githubusercontent.com/26461357/214795416-2c5783a7-059e-409d-b37d-a741aa1f94ad.png)

**Comment by mmahmoudian** [comment]
This is an invalid bug report. It does not have the information we need and is not in the uniform format we want. Please use our bug report form:

https://github.com/flameshot-org/flameshot/issues/new?assignees=&labels=Unconfirmed+Bug&template=bug-report.yaml

Thank you

**Comment by Dr4hcir** [comment]
Thanks for the tip. I've added #3079 3079
