### ISSUE TITLE
Cursor is too small

### ISSUE THREAD

**Issue by Fractal-Tess** [flameshot-org/flameshot#3075]
Hey there,

First of all, thank you guys for bringing and developing this amazing software. I've used a couple of other SS utilities but nothing comes close to flameshot. 

There is however 1 minor issue that I'm having pain with and sometimes it's incredibly annoying.
The cursor when in screen-shooting mode is incredibly small, and sometimes when there isn't enough contrast between the background and the cursor, I tend to lose it entirely.

Here is an example:
![image](https://user-images.githubusercontent.com/75957529/215241108-946e058c-f3a2-44d4-8d96-6e985110e2c5.png)

Can you see the cursor here? You might be able to, but at first glance, it is incredibly hard for me to see its position - look bottom right.

Anyhow, is there any way I can remedy this issue? Perhaps use a different cursor that has a white body, or increase the size of the cursor?

```
❯ uname -a
Linux VD 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux
❯ leftwm --version
leftwm 0.4.1
❯ flameshot --version  // Installed via paru
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

Thank you for your time!
Cheers

**Comment by mmahmoudian** [comment]
Thanks for the issue but:
1. Please use our bug report forms. It helps us collect the info we need and in a uniform format
2. This looks like a duplicate of #2004. What do you think?
3. Paru is pacman wrapper and AUR helper. So it does not tell if you have installed it from Arch repo (`paru flameshot`) or AUR (`paru flameshot-git`).  But based on your version I can say that you are using the Arch repo binary.

Also, considering that you are using leftwm, what mouse pointer package are you using?

**Comment by Fractal-Tess** [comment]
> Thanks for the issue but:
> 
>     1. Please use our bug report forms. It helps us collect the info we need and in a uniform format
> 
>     2. This looks like a duplicate of [Flameshot cursor is not visible when taking screenshots #2004](https://github.com/flameshot-org/flameshot/issues/2004). What do you think?
> 
>     3. Paru is pacman wrapper and AUR helper. So it does not tell if you have installed it from Arch repo (`paru flameshot`) or AUR (`paru flameshot-git`).  But based on your version I can say that you are using the Arch repo binary.
> 
> 
> Also, considering that you are using leftwm, what mouse pointer package are you using?

1: Sorry for this, but the template forms were explicitly meant for bugs, and I believe this is not a bug and more of a question that aims for me to get more insight into how and why this is happening. I'm sorry for not posting this into discussions - I should've done that instead.
2: Nope - the cursor is perfectly visible at all times, it's just that it is extremely hard to make it out since it has almost no contrast to be background (being small, thin and nearly the same colour when flameshot tones down the background)
3: I'm sorry for the confusion and this is entirely my fault as I did not specify if I had installed the bin version or the git one. I can confirm that I have opted for the bin.

4:  Wait... there is no 4th. 
But in all seriousness, you were correct to point me to the cursor pack. The one I was using `Breeze Obsidian` seems to be the culprit in my case. Switching to a different cursor pack solves my issue entirely.

Anyway, thanks a lot <3.

Cheers!

**Comment by mmahmoudian** [comment]
@Fractal-Tess Sorry, I use my free time for this project, and usually the free time is when I'm not behind a computer. So I answer those that I can with my phone. And typing on the phone is not as smooth and easy and that's why I use lists and bullet points.

I'm glad that the issue was resolved. Happy screenshotting.
