### ISSUE TITLE
Show X and Y dimension of the selection not working

### ISSUE THREAD

**Issue by Xandorion** [flameshot-org/flameshot#3077]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10

### Description

If you use the function to measure the pixels (I hope this is what it is meant for), nothing happens when it is activated, or you don't see a dimension or x/y coordinate anywhere. Idk what i am doing false. Or is there any other option i should do first? Or ist it a problem with the screen resolution? 

### Steps to reproduce

1. start flameshot
2. select a region
3. try to use the x/y measurement button

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/96028955/215538546-9d4c4554-f6b6-45be-b849-bbe4e231d3aa.png)

### System Information

Windows 10  (21H2)

1. Monitor 125% Scaling
Resolution 2560 x 1440

2. Monitor 100% Scaling
Resolution 1920 x 1080

**Comment by jonasstein** [comment]
@Xandorion I think this is a misunderstanding of the functionality. I expected also some kind of reaction after clicking on the button. Now I think this is not a button, but an indicator and it shows you the dimension of the current snapshot. You will capture `x=672` and `y=379` pixels in your example. I suggest to rephrase the tool tip and drop the leading 'Show' in the English version and 'anzeigen' in German.

**Comment by Xandorion** [comment]
Ohh, now i understand, sorry i didn't saw that.

Thanks, then it works as expected. And thanks for the explanation.

**Comment by jonasstein** [comment]
I see the file https://github.com/flameshot-org/flameshot/blob/70be63d478a271da549597d69bd4868607c0a395/src/tools/sizeindicator/sizeindicatortool.cpp was removed. So there is nothing left to do here

**Comment by Xandorion** [comment]
What do u mean with "removed" the function is still there, or what do u mean?

**Comment by jonasstein** [comment]
@Xandorion I think it is not. Please paste the link to the source here, if you think it is still there in the latest code.

**Comment by Xandorion** [comment]
Sorry, I have no idea about programming. I'm using the latest version of Flameshot and it seems to be included. At least I still see this "button" when I take a screenshot.

**Comment by mmahmoudian** [comment]
@Xandorion we perhaps have to remove it in the next version to avoid confusion. We now have better ways to show the selected regions dimension. Thanks for your input

**Comment by thinrope** [comment]
@mmahmoudian What are those better ways? And since what version was that changed?

I just installed 12.1.0/Gentoo and I thought something was not working as well, since the "button" was not doing anything :-) Now I know it is actually showing the size.
