### ISSUE TITLE
Can't upload screenshot to imgur

### ISSUE THREAD

**Issue by lestrangeqq** [flameshot-org/flameshot#3080]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20.04

### Description

When I try to upload image I got this error:

`Error transferring https://api.imgur.com/3/image?title=&description=2023-02-03_11-29 - server replied: Unknown Error`

Noticed today.

### Steps to reproduce

1. start flameshot
2. hit the button to make screenshot
3. click to upload screenshot (icon with cloud image)

### Screenshots or screen recordings

![Screenshot from 2023-02-03 11-34-18](https://user-images.githubusercontent.com/25365923/216565011-7262d68d-adb0-48d1-a65c-9ddfd366509d.png)

### System Information

`Linux lestra-sys 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mmahmoudian** [comment]
I don't think this is a bug. Try using you own imgur token. Our quota might have been full. Try the instructions in the following page:

https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

**Comment by lestrangeqq** [comment]
Oh, i didn't know it. Thank you!

**Comment by mmahmoudian** [comment]
@lestrangeqq Please let us know if following the instructions above have solved the issue or not. Thanks.

**Comment by OnkelTem** [comment]
I ran into the same issue, configuring my own token now.
But look, quite a quota it is, if we're  hitting the limit only now!
This also means that more and more people use this beautiful program.
And that's great!

**Comment by xahon** [comment]
I've changed default imgur token and it works but no window pop up after upload and there's no new image on my account. In recent uploads window I can see uploaded images and can delete them

**Comment by mmahmoudian** [comment]
@xahon 
> no new image on my account.

yes, that is how imgur works. You can find some detailed explanation here:

https://github.com/flameshot-org/flameshot/issues/3127#issuecomment-1480690759
