### ISSUE TITLE
Pin as a Layer with transparency to help people retro engineer design

### ISSUE THREAD

**Issue by 4sStylZ** [flameshot-org/flameshot#3081]
### Feature Description

Hello there, 

I 3d model parts based on real logo or make .svg with a hand-drawing. To do it, I often use flameshot to screenshot something and pin it to my screen, but I can only « replicate » curve and not use the flameshot pinned screenshot as a layer because there is no transparency on it.

To really facilitate my work. I would love to be able to pin screenshot, with a transparecy setting, and also a way to not clic on the image but rather on the app below it. 

What do you think ?

Thank's.

**Comment by mmahmoudian** [comment]
Already implemented:

![image](https://user-images.githubusercontent.com/390889/216651916-0a105e13-6510-41de-a91b-b9ef1ada5576.png)

**Comment by 4sStylZ** [comment]
Thank you, 

I can't find the option in the last release unfortunately. Is it unreleased for now ?

**Comment by mmahmoudian** [comment]
Yes it is not in the v12.1.0 release and will be in the next release. You can have it either by AUR if you are on Arch-based linux distro, or build from head, or you can download our development builds (a.k.a nightly builds):

https://flameshot.org/docs/installation/development-build/
