### ISSUE TITLE
flameshot full captures only part of the screen

### ISSUE THREAD

**Issue by in-in** [flameshot-org/flameshot#3086]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Linux Mint 21.1 Cinnamon

### Description

For example, this is a screenshot of the whole screen
![23037103208](https://user-images.githubusercontent.com/8797432/217002204-a3787ca9-7a54-4ff4-b82f-82b0866807a0.png)

And this is a screenshot after running `flameshot full`
![23037103305](https://user-images.githubusercontent.com/8797432/217003225-49e1b8b2-11f5-4b00-afef-12fb9e60f276.png)

I use the "Use last region" option, but I don't think it should work for `flameshot full`
![23037093147](https://user-images.githubusercontent.com/8797432/217003653-d8794177-5c72-4dda-8fb0-73a0c0183358.png)

I don't use fractional scaling or Wayland and have only one display.

### Steps to reproduce

1. check "Use last region" in flameshot configuraton
2. run `flameshot gui`
3. select a region on the primary monitor
4. save to file
5. run `flameshot full`
6. you should get the same screenshot as in the previous step

### System Information

1. Linux Mint 21.1 Cinnamon

2. ![23037155648](https://user-images.githubusercontent.com/8797432/217005791-a4ea850d-45a4-40f6-9d23-fbe80d79dcfa.png)

3.
System:
  Host: mercury Kernel: 5.15.0-58-generic x86_64 bits: 64
    Desktop: Cinnamon 5.6.7 Distro: Linux Mint 21.1 Vera
Graphics:
  Device-1: NVIDIA GK104 [GeForce GTX 760] driver: nvidia v: 470.161.03
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 760/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.161.03

**Comment by mmahmoudian** [comment]
I can confirm that the issue is there, and `flameshot full` uses the `use last region` to capture, which it should not.

**Comment by bgoewert** [comment]
Ran into this today. I agree `flameshot full` should not be using  `use last region`. I like being able to use the last region for area screenshots. But also need a "fullscreen" screenshot occasionally. Right now I am simply selecting the entire screen so I can keep `use last region` enabled.

```text
Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
```

**Comment by HubKing** [comment]
I am using Gnome Wayland fractional scaling. Flameshot was installed from the extra repo. Version 12.1.0. Dual monitors 100%, 150%. When taking a screenshot, the screen gets zoomed in, so I can only capture left-top area.

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
linux: 6.6.4-arch1-1
endeavouros: unknown
```

**Comment by Abdull** [comment]
> I am using Gnome Wayland fractional scaling. Flameshot was installed from the extra repo. Version 12.1.0. Dual monitors 100%, 150%. When taking a screenshot, the screen gets zoomed in, so I can only capture left-top area.
> 
> ```
> Flameshot v12.1.0 (-)
> Compiled with Qt 5.15.10
> linux: 6.6.4-arch1-1
> endeavouros: unknown
> ```

@HubKing, because you mention fractional scaling, your issue sounds like #748.
