### ISSUE TITLE
How to revoke the take screenshot permission on Wayland?

### ISSUE THREAD

**Issue by Wxrlds** [flameshot-org/flameshot#3092]
### Summary
Title pretty much says it all.
How do I revoke the take screenshot permission on Wayland Linux?
I'm more or less experiencing the opposite of this issue here https://github.com/flameshot-org/flameshot/issues/2868#issuecomment-1212429625.

### What happened
To test out the program before installing it on my Windows machine, I installed it on my Fedora machine.
I took a screenshot using the tray icon, I was asked if I want to allow flameshot to take a screenshot, did allow it to and now I do not need flameshot installed anymore but cannot figure out how to revoke the take screenshot permission.
I was only asked once this entire time and all subsequent screenshots worked flawlessly without the permission request but now I want to revoke the permission (IMO the less programs are allowed to do stuff the less could happen, even if uninstalled)
I did uninstall flameshot but when I reinstall it, I don't even get asked if I want to allow flameshot to take a screenshot, it just does it.
The above link to the issue links to a comment that shows the take screenshot permission in the settings but for me it only shows the notification permission.
Already restarted, checked that there is no flameshot.desktop file, searched through dconf-editor for flameshot and did not find anything.

### Flameshot version:
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
linux: 6.1.9-200.fc37.x86_64
fedora: 37

### Installation Type
Linux (sudo dnf install flameshot)

### Operating system
OS: Fedora Linux 37 (Workstation Edition)
Kernel: 6.1.9-200.fc37.x86_64 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: GNOME 43.2 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD FX-6300 (6) @ 3.500GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 4045MiB / 15896MiB
![image](https://user-images.githubusercontent.com/42120270/217342411-50a174ec-fd5c-4b66-8960-ee73834cac38.png)

**Comment by mmahmoudian** [comment]
Sorry, this is gnome issue, not a Flameshot issue. You will have a better luck asking the gnome devs.

**Comment by warmbroke** [comment]
Use `flatpak permission-remove screenshot screenshot`

**Comment by mmahmoudian** [comment]
@warmbroke The question is not about Flatpak, but it is about Gnome permission when they have used Fedora repositories to install Flameshot

**Comment by PolyMeilex** [comment]
> > @warmbroke The question is not about Flatpak, but it is about Gnome permission when they have used Fedora repositories to install Flameshot
> 
> Nope, this is a xdg-desktop-portal permission. And xdg-desktop-portal is a flatpak component.

I don't think this is xdg permission, I believe it's Gnome specific one, but either way just take away the permission in Gnome settings app (Settings -> Apps -> Flameshot -> Screenshot toggle).
![image](https://github.com/flameshot-org/flameshot/assets/20758186/70458baf-bd6c-45cd-b415-dffeba608af1)
