### ISSUE TITLE
Error transferring https://api.imgur.com/3/image?title=&description=2023-02-08_12-55 - server replied: Unknown Error

### ISSUE THREAD

**Issue by canahmetmaple** [flameshot-org/flameshot#3094]
### Flameshot Version

Flameshot v12.1.0

### Installation Type

Snap from Snapcraft, Snap from

### Operating System type and version

ubuntu 20.04 LTS

### Description

I can upload screenshots to imgur

### System Information

Ubuntu 20.04 Lts

**Comment by mmahmoudian** [comment]
Please search before posting new issues.
