### ISSUE TITLE
Add a live size indicator to the capture bounding box 

### ISSUE THREAD

**Issue by claytron5000** [flameshot-org/flameshot#3099]
### Feature Description

I think it would be great if we could add a live label to the capture bounding box as you shrink and grow it. This would display the pixel width and height of the bounding box as you change the size. This would make it easy for a user to create screen-shots of the same size repeatedly. It would also allow the user to see the screenshot size before releasing the mouse button.

**Comment by mmahmoudian** [comment]
Already implemented in #2766.
