### ISSUE TITLE
Doesn't copy to clipboard consistently

### ISSUE THREAD

**Issue by RandomLegend** [flameshot-org/flameshot#3107]
### Flameshot Version

Flameshot v12.1.0 (3ededae5)
Compiled with Qt 5.15.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), User repository (AUR)

### Operating System type and version

Arch Linux / 6.1.12-zen1-1zen

### Description

Same issue as #635 

Sadly the recommendation didn't help me; I already configured it to use JPG for Clipboard. I have KDE 5.27 and since that i cannot consistently copy into clipboard.

Sometimes it works, but most of the time it doesn't.

### System Information

KDE Plasma 5.27.1
KWIN / PICOM
X11

**Comment by dw-dengwei** [comment]
same issue

**Comment by RandomLegend** [comment]
Tried all the different ways of installation now and built from source. Still not possible to copy into clipboard anymore
