### ISSUE TITLE
How to set colors

### ISSUE THREAD

**Issue by sebastienserre** [flameshot-org/flameshot#3109]
### Flameshot Version

V12.1.0

### Installation Type

Snap from Snapcraft

### Operating System type and version

LInux Mint 21

### Description

Hello,

How to change the element color like the arrow on the image below ?
![2023-02-24_15-31](https://user-images.githubusercontent.com/3902621/221204323-014e6a10-dfa2-4b58-8814-42cbd5f39c81.jpg)

Thank you

### System Information

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
Linux Desktop 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
Righclick will open the color wheel. Also pressing <kbd>Space</kbd> will open the sidebar from which you can select a color, grab a color from the picture, change size , font, and even order layers.
