### ISSUE TITLE
Flameshot gui not working and heavy delay on selection box

### ISSUE THREAD

**Issue by FelixJochems** [flameshot-org/flameshot#3111]
### Flameshot Version

Flameshot v12.1.0 (3ededae5)
Compiled with Qt 5.15.8
linux: 6.1.12-arch1-1
arch: unknown

### Installation Type

User repository (AUR)

### Operating System type and version

Arch - 6.1 Kernel

### Description

With the latest addition of the GRIM-based adapter the command ```flameshot gui``` no longer works and there's a heavy delay in drawing the box when making a screenshot.

I previously used it with the command ```env XDG_CURRENT_DESKTOP=sway flameshot gui``` as a hacky workaround but it worked flawlessly.

This is the standard output while using flameshot and taking a screenshot:

```
flameshot: warning: grim's screenshot component is implemented based on wlroots, it may not be used in GNOME or similar desktop environments
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Capture saved as /home/felix/Pictures/Screenshots/2023-02-27_05-28.png
```

Interestingly when trying to take a 2nd screenshot when it will also give some errors about QPainter. The following is a log where I try to take 2 screenshots after each other:
```
flameshot: warning: grim's screenshot component is implemented based on wlroots, it may not be used in GNOME or similar desktop environments
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: warning: grim's screenshot component is implemented based on wlroots, it may not be used in GNOME or similar desktop environments
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
 ```

### Steps to reproduce

git clone https://aur.archlinux.org/flameshot-git.git
edit the PKGBUILD to include ```-DUSE_WAYLAND_GRIM=true```
build and install the package.
Running flameshot gui, running ```echo $?``` will show that it exited with status 1
Running flameshot and then making a screen via the tray icon will show the heavy delay
Taking a 2nd screenshot will show the 2nd log provided in the description

### Screenshots or screen recordings

https://user-images.githubusercontent.com/123550588/221476451-9e517eb7-f0f1-4c1e-8db5-9853268f9eeb.mp4

### System Information

Arch - Kernel 6.1
2 monitor setup
Hyprland (Wayland)

**Comment by FelixJochems** [comment]
Misclicked but wanted to add that: ```grim -g "$(slurp)"``` does work without a delay

**Comment by FelixJochems** [comment]
After some more and profiling I found out that the issue was caused by continuously repainting the little size indicator in the bottom right. Since #2766 added this feature. There is currently an PR #3059 that fixes this issue and I can confirm that this completely solved my issues. Leaving the issue open because the PR isn't merged yet and for visibility if other people have the same problem.

**Comment by mmahmoudian** [comment]
@veracioux This has been reported elsewhere as well ([example](https://github.com/flameshot-org/flameshot/issues/2978#issuecomment-1441026552)).

**Comment by FelixJochems** [comment]
Closed since PR has been merged.
