### ISSUE TITLE
Flameshot can't copy/paste when Parsec running

### ISSUE THREAD

**Issue by asarubbi** [flameshot-org/flameshot#3113]
Flameshot works perfectly fine, except when running Parsec (https://parsec.app/), it can't just copy paste to anything. I get presented the region selector and get the system message saying that screenshot has been copied to clipboard, but clipboard wouldn't contain the image. Saving the image works just fine. 

Tested in: Debian, Ubuntu (all variants except Unity and KDE), Mint, PopOS (all latest versions available)

Tested both repo versions (latest and 2 previous) and flatpak versions to no avail. 

Tweaking configurations in Flameshot wouldn't do anything. 
Notifications test works just fine. 

Wayland vs X11 won't do the trick (tried both)

Tested other screenshot capture software:
- the ones that comes with the OS work just fine (lame extra tools tho, hence the use of Flameshot)
- ksnip: same behavior: it works, unless Parsec is running
- shutter: same behavior: it works, unless Parsec is running

After my testing, I'm almost 100% convinced this is not a Flameshot issue per-se, but just wanted to check if you have seen something similar or have more hints as to how to debug this.

**Comment by terrehbyte** [comment]
Parsec released an update on Feb 28, 2023, addressing issues with copy and paste operations while the client was open:

> [Ubuntu] Fixed the issue where the Parsec client on Ubuntu prevents non-text clipboard use for other applications.

Any idea if that potentially solved your issue? I ran into the same issue on an Arch-based system but haven't used Parsec on it since, so I'm not sure on my end.

**Comment by asarubbi** [comment]
Thank you for your reply. Alas, tried today again and apparently is not fixed yet. At least for PopOS (will try with Ubuntu just in case). Closing this thread and moving out of Flameshot for good :(  (too bad. I really liked it while it lasted)

Out of curiosity, which tool did you fallback to? Most stock apps currently are lame in terms of features. I mean, screenshots only in 2023? no annotations?  Nope.
