### ISSUE TITLE
flameshot text and shapes cannot be selected to move or re-edit.

### ISSUE THREAD

**Issue by lykiao** [flameshot-org/flameshot#3116]
### Feature Description

like this：
![无标题](https://user-images.githubusercontent.com/54703532/222882368-7fdaea30-77d9-4324-815c-6bd0a9003e96.png)
![无标题2](https://user-images.githubusercontent.com/54703532/222882373-ed810499-48c5-4586-b4f0-93b6166e9251.png)
![无标题3](https://user-images.githubusercontent.com/54703532/222882375-e77a6416-1de6-4049-8c94-d4d88d1374ee.png)

**Comment by mmahmoudian** [comment]
Already possible:

[Peek 2023-10-02 18-21.webm](https://github.com/flameshot-org/flameshot/assets/390889/2a862259-1e52-4b15-8eec-1fdfc2fa028a)
