### ISSUE TITLE
Antergos(Arch Linux) + KDE

### ISSUE THREAD

**Issue by DanitiKain** [flameshot-org/flameshot#312]
**Describe the bug**
using flameshot full -c -p /dir is very slow if I remove the -c it works just fine.

**To Reproduce**
Install KDE and Antergos.  I think this is a KDE issue as I have cinnamon installed on on another machine using Antergos and have no issues.

**Expected behavior**
Capture full screen and copy to clipboard quickly.

**Desktop (please complete the following information):**
 Linux 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux

Antergos 18.9

**Comment by farseerfc** [comment]
Do you mean `flameshot full -c -p /dir` is slow ? I am asking because `flameshot -c -p /dir` will output an error saying: 
```
the option 'c' is not a valid option for the argument 'flameshot'. See 'flameshot --help'.
```

**Comment by DanitiKain** [comment]
Yes with the full option I missed it when I had typed it instead of copying and pasting.

**Comment by DanitiKain** [comment]
Take a look at ksnip he had to make this work for kde and wayland support. It seems to be working perfect for me.

**Comment by lupoDharkael** [comment]
what version of Flameshot are you using?

**Comment by DanitiKain** [comment]
Flameshot v0.5.1 Complied with QT 5.11.1

**Comment by lupoDharkael** [comment]
Today I've released Flameshot v0.6. That problem should be fixed in the last version. The new version should come soon to Arch.

**Comment by farseerfc** [comment]
Version v0.6.0-1 has been released on Arch Linux https://www.archlinux.org/packages/community/x86_64/flameshot/

**Comment by DanitiKain** [comment]
Ok thanks for the update.
