### ISSUE TITLE
Add copyAfterSave configuration option

### ISSUE THREAD

**Issue by mcp292** [flameshot-org/flameshot#3124]
### Feature Description

We have `saveAfterCopy`, but I would like to use `copyAfterSave` instead. It's more reliable to hit save after a screenshot: Mentally you know you won't lose it, conveniently it was also copied to clipboard.

**Comment by mmahmoudian** [comment]
> It's more reliable to hit save after a screenshot

Can you elaborate on this:

**Comment by mcp292** [comment]
Sure! In normal operation, when you copy something it could be accidentally overwritten. So saving that thing first is your safest bet and a best practice.

With that logic, your habit should be to hit save, and then as a convenience it is automatically copied to your clipboard.

**Comment by mmahmoudian** [comment]
> Maybe you would feel more comfortable adding a single button and commandline option for saving and copying at once.

That is exactly why I ask. The CLI already easily do that:

https://flameshot.org/docs/advanced/commandline-options/

So you can change the default behavior of your keybinding. 
Would this already address your issue?

Also, saving to file is practically always slower than copying to clipboard. Also one can have a clipboard manager like copyQ.

**Comment by mcp292** [comment]
These are all great points. I had overlooked the commandline options for this. Honestly, your probing revealed what I actually wanted: both to occur always.

Clipboard manager is a very good idea as well.
