### ISSUE TITLE
Taking a screenshot ends up with getting black screen

### ISSUE THREAD

**Issue by AyushSehrawat** [flameshot-org/flameshot#3125]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.19.0-35-generic
ubuntu: 22.04

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 22.04

### Description

Hi! I recently ( yesterday) switched from dual boot of windows and linux ( Ubuntu 22.10 ) to pure Ubuntu 22.04.

Installed Flameshot from deb package and setup a shortcut to trigger it from keyboard shortcuts and also enable it on startup by making a startup application with command `flameshot`.

Now i set the keyboard shortcut to `Ctrl + Q`  first, and then `Print`.

It was working perfectly fine yesterday but today when i press my key combination and then ctrl c to copy to clipboard, i often end up getting a black screen.
Once it even automatically shutdown too..
2nd time and onwards the black screen was there for long and it wasn't shutdown so i ended up doing force shutdown.

This is happening very often. I love Flameshot and use it on daily basis. Please look into. 

### Steps to reproduce

1.) set Flameshot as startup application by setting command as `flameshot`

2.) set Flameshot keyboard shortcut to Print

3.) use Print to take screenshot of a area and press ctrl c to copy it to the clipboard

### System Information

$ inxi --width 80 --system --graphics
System:
  Host: mini Kernel: 5.19.0-35-generic x86_64 bits: 64 Desktop: GNOME 42.5
    Distro: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Graphics:
  Device-1: NVIDIA GP107M [GeForce GTX 1050 3 GB Max-Q] driver: nvidia
    v: 525.85.05
  Device-2: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Quanta HP TrueVision HD Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: amdgpu,ati,nvidia unloaded: fbdev,modesetting,nouveau,radeon,vesa
    gpu: amdgpu resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon Vega 8 Graphics (raven LLVM 15.0.6 DRM 3.47
  5.19.0-35-generic)
    v: 4.6 Mesa 22.2.5

$ loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11

$ xrandr --listactivemonitors
Monitors: 1
 0: +*eDP 1920/344x1080/194+0+0  eDP

mini@mini:~$ xrandr | grep -v " disconnected "
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     59.98*+  39.98  
   1680x1050     59.98  
   1280x1024     59.98  
   1440x900      59.98  
   1280x800      59.98  
   1280x720      59.98  
   1024x768      59.98  
   800x600       59.98  
   640x480       59.98 

$ lspci | grep -i 'vga\|3d\|2d'
01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 3 GB Max-Q] (rev a1)
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c2)

$ lshw -class display
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: GP107M [GeForce GTX 1050 3 GB Max-Q]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:61 memory:f6000000-f6ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:f000(size=128) memory:f7000000-f707ffff
  *-display
       description: VGA compatible controller
       product: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:04:00.0
       logical name: /dev/fb0
       version: c2
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 resolution=1920,1080
       resources: irq:24 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:c000(size=256) memory:f7500000-f757ffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

$ uname -a
Linux mini 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
Try `flameshot gui` and see if this keeps happening. You do not necessarily need to have Flameshot running at startup, but it helps to start Flameshot faster.

As a side note you can read about some commandline arguments here:

https://flameshot.org/docs/advanced/commandline-options/

**Comment by mmahmoudian** [comment]
Did you try with the command I mentioned in the comment above?

**Comment by AyushSehrawat** [comment]
my shortcut key calls `flameshot gui` , it sometimes work fine but sometimes it's crashing

**Comment by mmahmoudian** [comment]
The shutdown is peculiar! It really might be an issue with your graphics drivers rather than Flameshot. At best Flameshot process itself should crash or segfaults, but it should not affect the operating system at all. 

Can you try using our AppImage or Flatpak instead and see if the issue persists?

**Comment by AyushSehrawat** [comment]
@mmahmoudian This is again occurring on PopOS.

Do you have any idea of Nvidia driver version it's fine with?

I have a custom keyboard shortcut of prt sc which on pressing runs `flameshot gui`, as soon as i click the ss and press ctrl c to copy to clipboard, the laptop shows black screen. Then i close the lid, reopen, relogij, works for like 1-5s and then again black screen.

I end up doing shutdown only.

Please look into it. It happened with me on multiple distros. It worked fine on ZornOS but issues on Ubuntu and PopOS

**Comment by Cwpute** [comment]
Hi, did your issue resolve itself again @AyushSehrawat  ?
May i ask you what was the culprit driver, how you fixed it if you did fix it ?

**Comment by AyushSehrawat** [comment]
> Hi, did your issue resolve itself again [@AyushSehrawat](https://github.com/AyushSehrawat) ? May i ask you what was the culprit driver, how you fixed it if you did fix it ?

Switched to other os and it fixed itself. Was never able to identify the problem :/
