### ISSUE TITLE
Confusion about custom Imgur Client ID

### ISSUE THREAD

**Issue by Hutch79** [flameshot-org/flameshot#3127]
### Flameshot Version

![image](https://user-images.githubusercontent.com/42042811/224548760-8c2b649a-86d3-4470-a436-59ac7098266b.png)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11

### Description

It's not really an issue, just a confusion/question on my site.

I set up Flameshot with the custom Imgur Client ID, and it works just fine. But I'm confused why I don't see the uploaded Screenshots on my profile.

Now I'm wondering if this is intended or an error in my configuration or what ever.

I would love to see a history on Imgur of the stuff I've uploaded, but if it's not implemented/possible, it's fine as well.

### System Information

![image](https://user-images.githubusercontent.com/42042811/224548940-4e80edfc-9484-4ef4-ae3f-b7551284ff7f.png)

**Comment by picli3** [comment]
I have the same confusion, I would like to have all my screenshots in one place in case I want to download them one day.

**Comment by mmahmoudian** [comment]
> I set up Flameshot with the custom Imgur Client ID, and it works just fine. But I'm confused why I don't see the uploaded Screenshots on my profile.
> 
> Now I'm wondering if this is intended or an error in my configuration or what ever.

Please read the documentation of imgur carefully. The token you are getting if just for uploading to imgur. It does not attach it to your profile. Basically all it is, is to give you an independent upload quota.

This is also the reason that we at Flameshot do not see and control the screenshots our users upload to imgur. 

We have wrote a quick help on our website:

https://flameshot.org/docs/guide/imgur-help/

Which contains a link to imgur documentation:

https://api.imgur.com/

Which has clearly stated:

> For public read-only and anonymous resources, such as getting image info, looking up user comments, etc. all you need to do is send an authorization header with your client_id in your requests. This also works if you'd like to upload images anonymously (without the image being tied to an account), or if you'd like to create an anonymous album. This lets us know which application is accessing the API.

**Comment by Hutch79** [comment]
Oh, thanks for clarification @mmahmoudian 
So basically the Token is a key to anonymously upload stuff.

Would it be possible for you guy's (if you see it as necessary enough) to add an option to upload it to the corresponding profile?
The Screenshots (in my opinion) should still be private, so only accessible via the URL, but the user could access easily all uploaded Screenshots he ever created.

**Comment by mmahmoudian** [comment]
> Would it be possible for you guy's (if you see it as necessary enough) to add an option to upload it to the corresponding profile?

It has been discussed, and we have got to the conclusion to [provide plugin system for Flameshot](https://github.com/flameshot-org/flameshot/discussions/2529) so that community can manage and maintain plugins for various tasks including uploading to custom platforms.

> The Screenshots (in my opinion) should still be private, so only accessible via the URL, but the user could access easily all uploaded Screenshots he ever created.

that is the limitation of a free Imgur free account and free non-commercial API. We at Flameshot do not decide on that. The public imgur is implemented in Flameshot to assist user to quickly share screenshots to others. I suggest you find the correct thread and help and contribute in having a mature idea for the upload plugin. You can find all the plugin-related topics here:

https://github.com/flameshot-org/flameshot/issues?q=is%3Aopen+is%3Aissue+label%3APlugin

**Comment by picli3** [comment]
What greenShot does seems good to me, having a local history of the captures I have made.

![image](https://user-images.githubusercontent.com/11140497/227647352-da90d622-f53a-4159-892f-02e5cb37c845.png)

**Comment by mmahmoudian** [comment]
> having a local history of the captures I have made.

We have had that for years. Right-click on Flameshot's tray icon and find it from there

**Comment by picli3** [comment]
this is clear for me,  thank and sorry!!

**Comment by jesuslalvaro** [comment]
Please allow much more than 50 items in history of imgur uploads (> 500)
thanks

**Comment by mmahmoudian** [comment]
> Please allow much more than 50 items in history of imgur uploads (> 500)
> thanks

Please open a feature request
