### ISSUE TITLE
Which is portable file for windows?

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#3128]
### Feature Description

`Download Portable` button on flameshot.org redirects here. I'm not a developer, I don't know which setup file to choose. Could you show me which is the portable file?

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/224860090-818eeb86-efbd-46b2-a8e6-c34876aa901b.png)

![resim](https://user-images.githubusercontent.com/110184059/224858927-ef683228-0ed4-4e1b-8724-4d7ec953d82f.png)

</details>

**Comment by mmahmoudian** [comment]
For Windows, the `.exe` files are executable, and `.msi` stands for Microsoft Installer. Therefore if you want the portable, you should not got with `.msi` and should use `.exe`. There if a chance that Github has truncated the list. If this happens, at the bottom of the list there is a "Show all 36 assests" that you should click on to see the full list.
