### ISSUE TITLE
Brush size resets to the max size when changing tool

### ISSUE THREAD

**Issue by juh9870** [flameshot-org/flameshot#3129]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10

### Description

Every time Flameshot starts up, or when I change a tool, brush size resets to maximum.

### Steps to reproduce

1. Select a region
2. Switch tool

It started happening ~2 weeks ago, and worked fine before that

### System Information

- **Edition:** Windows 10 Enterprise
- **Version:** 22H2
- **Installed on:** ‎26.‎12.‎2022
- **OS build:** 19045.2604
- **Experience:** Windows Feature Experience Pack 120.2212.4190.0

![image](https://user-images.githubusercontent.com/15922601/225386227-e0291177-49bc-4b0c-b254-618145499b7f.png)

**Comment by mmahmoudian** [comment]
> but I didn't see this config in GUI configuration tab

if you mean in the configuration window (i.e `flameshot config`),  then yes, it is not listed there, but you can see the active tool size in the sidebar:

![image](https://user-images.githubusercontent.com/390889/227890290-a3567dcb-86f9-4cb2-8cd7-a8a522a22fbd.png)

I remember some discussion about having tool-specific sizes. I know that at the moment font size and thickness are two different values.

I close this issue as it was resolved though.

**Comment by mmahmoudian** [comment]
Two points worth mentioning:

1. Please comment/reopen this if the issue reappears
2. For the sake of usability, you can change the tool size by scrolling or typing the number relatively fast and the tool size would change
