### ISSUE TITLE
Some suggsetions for upload screenshot

### ISSUE THREAD

**Issue by qwert-f** [flameshot-org/flameshot#3130]
Now, we can upload to Imgur,  but for some coutries Imgur cann't be using. This lead to uplad just a void button not an useful module

**Comment by mmahmoudian** [comment]
Thanks for the suggestion, but please search among open **and closed** issues before opening a new one. This way you get to the answer much faster.

Duplicate of many, including:
- #1623
- #1463
-#1190
-#750
-#608
-#178
-#45
-#27

The bottom line is that we have concluded that this should be done via a plugin, and therefore you have to wait until we implement the plugin system.
