### ISSUE TITLE
Text Outline

### ISSUE THREAD

**Issue by JosukeHigashkata** [flameshot-org/flameshot#3150]
### Feature Description

I think it would be great if it has adding outline(stroke) for texts

**Comment by mmahmoudian** [comment]
Isn't this duplicate of #1249  and to some extent #313 ?

**Comment by JosukeHigashkata** [comment]
YES but with adjustable border strength and custamizable colors

**Comment by mmahmoudian** [comment]
I suggest you mention your suggestions on those threads because when a developer starts implementing, they will not sieve through all the issues in the repo. It is good to have everything in one place.

I will close this issue.
