### ISSUE TITLE
Typo in dimensions "WxH+X+Y"

### ISSUE THREAD

**Issue by jonasstein** [flameshot-org/flameshot#3152]
https://github.com/flameshot-org/flameshot/blob/3ededae5745761d23907d65bbaebb283f6f8e3f2/data/translations/Internationalization_de_DE.ts#L1918

```
        <source>Print geometry of the selection in the format WxH+X+Y. Does nothing if raw is specified</source>
        <translation>Geometrie der Auswahl im Format B H X Y ausgeben. Ignoriert, falls raw ausgewählt ist</translation>
```
I guess it should be

```
        <source>Print geometry of the selection in the format WxH, XxY. Does nothing if raw is specified</source>
        <translation>Geometrie der Auswahl im Format BxH, XxY ausgeben. Ohne Funktion, falls raw ausgewählt ist</translation>
```

**Comment by mmahmoudian** [comment]
Thanks for the report, but:
1. Please try to use the templates we have specified for bug reporting when possible
2. the `WxH+X+Y` is correct. You can see that info also by `flameshot gui --help`
