### ISSUE TITLE
How to set key bind for flameshot macOS

### ISSUE THREAD

**Issue by Dragonizedpizza** [flameshot-org/flameshot#3154]
How do I set a key bind to take a screenshot via flameshot on macOS? I tried the following:
![image](https://user-images.githubusercontent.com/70718540/230722575-caf06875-de94-4d53-924e-b7bbe4ae1143.png)
But it didn't work.

I'm on macOS Ventura 13.3.1 and installed macOS via the dmg file in releases.

**Comment by mmahmoudian** [comment]
I don't know how macOS works these days, but try to bind a keybinding with `flameshot gui` command. You can find more info about the command line interface here:

https://flameshot.org/docs/advanced/commandline-options/
