### ISSUE TITLE
[MACOS] Not capturing the screen

### ISSUE THREAD

**Issue by Mittelblut9** [flameshot-org/flameshot#3162]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 22.5.0
osx: 13.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOS

### Description

When I use my shortcut to take a screenshot, the screen goes black and only a small part of the screen is visible.

### Steps to reproduce

1. run flameshot on macOS Ventura 13.4
2. (change the screenshot shortcut to (Option+Shift+S))
3. Take a screenshot

### Screenshots or screen recordings

![Screenshot 2023-04-12 at 19 14 56](https://user-images.githubusercontent.com/67608550/231533253-b199488a-08ac-437a-9752-d43ec6333893.png)

### System Information

OS: Apple M1 - macOS Ventura 14.4

Your monitor configuration: I don't know what that means

**Comment by mmahmoudian** [comment]
Do you have fractional scaling? Meaning do you have something other than 100% zoom level?

**Comment by Mittelblut9** [comment]
> Do you have fractional scaling? Meaning do you have something other than 100% zoom level?

No. But i have restarted the macbook. And now everything works again as it should. Hmm

**Comment by mmahmoudian** [comment]
The good old "turning it off and on again"🤓.

I will close this issue, but please reopen it if it happened again. Thanks
