### ISSUE TITLE
Another version of docment without systemd with support in sway.

### ISSUE THREAD

**Issue by shengliawa** [flameshot-org/flameshot#3167]
### Feature Description

[Sway and wlroots support](https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md)
It seems to be use systemd to control the environment variables.
How can it work without systemd?

**Comment by mmahmoudian** [comment]
This depends on your setup and possibly your init system. I personally am a systemd user and not that much experienced with alternatives, but of course without knowing what is your setup, it is impossible to help.

**Comment by shengliawa** [comment]
> This depends on your setup and possibly your init system. I personally am a systemd user and not that much experienced with alternatives, but of course without knowing what is your setup, it is impossible to help.

It seems this question is die.So using systemd base system.
