### ISSUE TITLE
Screenshot shortcuts

### ISSUE THREAD

**Issue by Fling7521** [flameshot-org/flameshot#3169]
### Feature Description

When I use the screenshot shortcut print screen, the system will call onedrive first, when I try to change the screenshot shortcut, I find that I can't change it, I hope to change the default shortcut for screenshot, or make it user-definable.

**Comment by mmahmoudian** [comment]
I'm going to close this because it is duplicate of many others. Considering that you have not mention your operating system, I think it is safe to assume you are a Windows user, therefore please read the info and help we have provided:

https://flameshot.org/docs/guide/windows-help/
