### ISSUE TITLE
Command to take a screen onshot on windows?

### ISSUE THREAD

**Issue by reDpz** [flameshot-org/flameshot#3170]
I know that on linux you can just type something along the lines of `flameshot gui` to take a screen but how do you do the same thing on windows? I have an autohotkey script to handle most of my shortcuts and I want to add it there so I can just run flameshot via pressing win shift s instead of having to look at the system tray and right clicking then taking screenshot.

**Comment by mmahmoudian** [comment]
Please search before creating a new issue. Thanks.

Duplicate of #2118
