### ISSUE TITLE
Screenshot misplace when use multi screen

### ISSUE THREAD

**Issue by Albelt** [flameshot-org/flameshot#3180]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

### Installation Type

User repository (AUR)

### Operating System type and version

Kubuntu 22.10

### Description

I have 2 screen, one is my laptop's builtin screen, another is a 24 inch monitor connected by HDMI

> ![image](https://user-images.githubusercontent.com/35684393/234454397-1369a133-9dc4-4fef-9df3-36ce6f1e2bab.png)

When I use flameshot to take a screenshot on this mode, I got the screen shift left like this
> ![image](https://user-images.githubusercontent.com/35684393/234455028-f237157b-8a30-4f73-8964-9a2f4f8b274e.png)

It's quite strange because when I use only one screen, it works perfect.

### Screenshots or screen recordings

![Peek 2023-04-26 11-11](https://user-images.githubusercontent.com/35684393/234460152-fb2c308a-fa2d-4186-8348-356c81c53625.gif)

### System Information

OS: Kubuntu 22.10
kernel: linux5.19-41-generic(64bit)   
Desktop: KDE Plasma 5.25.5
Window Manager: kwin 5.25.5
Screen：
```
Monitors: 2
0: +*HDMI-1 1920/527x1080/296+0+0  HDMI-1
1: +eDP-1 1920/344x1200/215+1920+0  eDP-1
Scaling: 125%
```
CPU：intel i5-13500H
GPU: intel iris Graphics
OpenGL(EGL) version: 1.5
OpenGL(GLX) version: 1.4
Vulkan Instance Version: 1.3.224
X Server Version: 1.21.1.4
GPU Driver Info: 
```
00:02.0 VGA compatible controller: Intel Corporation Device a7a0 (rev 04) (prog-if 00 [VGA controller])
Subsystem: Lenovo Device 3c48
Flags: bus master, fast devsel, latency 0, IRQ 164
Memory at 6000000000 (64-bit, non-prefetchable) [size=16M]
Memory at 4000000000 (64-bit, prefetchable) [size=256M]
I/O ports at 3000 [size=64]
Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
Capabilities: <access denied>
Kernel driver in use: i915
Kernel modules: i915
```

**Comment by mmahmoudian** [comment]
You didn't properly provided the information we asked. For instance you didn't give us your exact monitor configuration. Do you have fractional scaling on any of your monitors?

**Comment by Albelt** [comment]
> You didn't properly provided the information we asked. For instance you didn't give us your exact monitor configuration. Do you have fractional scaling on any of your monitors?

I have added some infomation abort my screens and drivers, is there any other details needed?

**Comment by Albelt** [comment]
Ok, it might be the problem of scaling 🤣 ，when I changed scaling to 100%, it just works fine
