### ISSUE TITLE
flameshot is particularly slow

### ISSUE THREAD

**Issue by jack9603301** [flameshot-org/flameshot#3187]
### Flameshot Version

master #3018 

### Installation Type

Compiled from source

### Operating System type and version

gentoo

### Description

I found a strange problem where the flameshot gui would always get quite slow, I used gdb to troubleshoot and found that it seemed to be stuck in the log output of my grim adapter! What are people's thoughts on this? I'm testing the effect of adding -DCMAKE_BUILD_TYPE=Release

see #3018

### Steps to reproduce

run

### System Information

gentoo

**Comment by jack9603301** [comment]
note> And in most cases, flameshot will terminate execution with an exception

**Comment by jack9603301** [comment]
Well, it seems to be my fault when I recompile the kernel to turn off apparmor afterwards. It works fine

**Comment by mmahmoudian** [comment]
Thanks for reporting back
