### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [flameshot-org/flameshot#3188]
Hi!
I am the Developer Evangelist of SignPath.

Could you change the notice about us from

    Free code signing provided by [SignPath.io](https://signpath.io/), certificate by [SignPath Foundation](https://signpath.org/).

to

    This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=flameshot), and a certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=flameshot)

I am happy to submit a PR for it.
Thanks!

**Comment by mmahmoudian** [comment]
This is practically hiding some tracking code behind the URL. How about being completely transparent about it?

**Comment by SabotageAndi** [comment]
Thanks for putting us on your website!

> So your campaign link seems a bit invalid as people will not come from Github

Nope, we get a lot of traffic from GitHub. That is why we want to add UTM parameters (https://en.wikipedia.org/wiki/UTM_parameters) to the links to see in detail from which projects the people come.
We don't get more information than that from UTM parameters. 

So not really much tracking going on here.

**Comment by mmahmoudian** [comment]
> Nope, we get a lot of traffic from GitHub.

What I meant was that people can land on your website from our website too (which is not github), therefore, `utm_campaign=flameshot` would still be valid, but the `utm_medium=github` would not be valid anymore.

> So not really much tracking going on here.

Fair point. I will add it. 

I just noticed that the wording has changed:
```
code signing provided by SignPath.io, certificate by SignPath Foundation
                                     '-----------'
                                           ^
                                           |
                                           v
                                     ,-----------------,
code signing provided by SignPath.io, and a certificate by the SignPath Foundation
```

The new sentence indicates that Flameshot is getting two things from SignPath. but as far as I can understand the dynamics, we get a certificate which is already signed by SignPath. Would it be ok if I update the links to the existing sentence?

**Comment by SabotageAndi** [comment]
If you want to be 100% accurate, you get two things. It is the free code signing certificate from the SignPath Foundation and a free subscription to SignPath.io.

For the website, please use the `utm_medium=website`
