### ISSUE TITLE
Screenshot has different color

### ISSUE THREAD

**Issue by memjr** [flameshot-org/flameshot#3196]
The image in the screen shot have different colors than the original.  The link shows a png I took with screen shot and pasted into GIMP, then exported in the highest possible quality.  The car in the top is the original pic.  The car in the bottom is a screen shot of the car on top.  The final PNG you see is then top: screenshot of original and bottom screenshot  of a screenshot.  The second link is a screen shot of this same screen shot (saved and exported the same way in GIMP). In that one, you can see the color changes even more. 
 Both of those cars in the PNG have a different color than the one you'd see by looking at the original on the screen.

https://photos.app.goo.gl/sfvsJhFq64YECCJ58
https://photos.app.goo.gl/MRjkRbAQvJd4PvH3A

Let me know what kind of info you need form my system, if any, that may help with this.

**Comment by mmahmoudian** [comment]
Please fill a bug report and provide all the information in that form. Also please upload the images directly to github. For security reason we do not open third-party links. Thanks.
