### ISSUE TITLE
Image to text conversion using tesseract 

### ISSUE THREAD

**Issue by kk-rishang** [flameshot-org/flameshot#3202]
### Feature Description

Many time we share screenshots regards some technical issue, while many times try to copy error messages, for screenshot it gets a little hard as we need to read and write manually, we can use tools like https://github.com/tesseract-ocr/tesseract to extract text information from the image, making work easy in some situations. 

somewhat like what google lens offers in androids.

**Comment by mmahmoudian** [comment]
Duplicates of many. Just search OCR and see.
