### ISSUE TITLE
THANK YOU!!

### ISSUE THREAD

**Issue by hyperfocus1337** [flameshot-org/flameshot#321]
THIS SOFTWARE IS GREAT!!

**Comment by SuperNami** [comment]
This solves a big paint point for me, how can I donate?

**Comment by simonbcn** [comment]
Really it's a great program. :+1:

**Comment by AlfredoRamos** [comment]
> how can I donate?

At the bottom of the [README](https://github.com/lupoDharkael/flameshot/blob/master/README.md) there's a PayPal link where you can donate to the author.

**Comment by kramer65** [comment]
I was back on version 0.5.1 which was ok-ish. It worked, but I mainly missed adding text. I just downloaded version 0.6.0 though, and that is simply awesome! After enabling the text-thing (why is that not enabled by default) I can finally use it like I want to. I'll probably be using this on a semi-daily basis, so a huge thanks to you!

**Comment by lupoDharkael** [comment]
I'm not really intro crypto, do you know services that allow paying using the creditcard without a login?If you have a preference I could look into it.

**Comment by kramer65** [comment]
@lupoDharkael - I did a 5 minute search but I can't really find anything. Setting up crypto accounts online is really easy. Takes you about 5 minutes, so that should be easy.

I'd be happy to hear it if you have an alternative donation button!

**Comment by RichNahra** [comment]
This is great software.  Thank you very much

**Comment by mimecry** [comment]
still room for new features, but fair to say that this is now the best screenshotting software on Linux, just as it was destined to become. phenomenal effort, and a huge thanks to @lupoDharkael and everyone else involved

**Comment by fmaiabatista** [comment]
This software is really great. Since I couldn't find a channel to send new features suggestions, I'd like to launch the idea here: 

Feature: to have an option to remember last selection's size and position. 

Use case: for people that need to take screenshots in sequence and need the window position to remain the same. 

Benchmark: the Lightshot utility for Windows has this option, which I find myself using every so often.

By the way, it's my main printscreen utility when I'm on Windows and I'm looking forward to FS being ported/emulated there so I can ditch it in favor of this. ;)

Congrats, I might be donating very soon!

**Comment by SuperNami** [comment]
For some reason the paypal donate doesn't work for me, check screenshots:

After selecting an amount and clicking next it shows my account has 0 balance
https://i.imgur.com/Gtqv2ih.png

Account does have balance but it just doesn't display at donate, same account is logged in
https://i.imgur.com/QjqKZ0n.png

Plz add crypto donate options. (btw I like the fact that I'm using your software to help me with showing you this)

**Comment by lupoDharkael** [comment]
Now Bitcoin is an alternative donation option:
https://github.com/lupoDharkael/flameshot/commit/234a51baeab00d4c434af07f7a5a438b1d087871

**Comment by SuperNami** [comment]
The BTC transaction fees are actually pretty ridiculous for small donations, I would rather donate you more instead, can you add bitcoin cash address as well? Much lower fees: https://bitinfocharts.com/comparison/transactionfees-btc-bch.html

**Comment by azzamsa** [comment]
Really great software, cut down my time to add those line and text in GIMP.

Before: maim -> GIMP -> share
Now: (if need to add line) flameshot -> share

Thanks a lot!

**Comment by soundsbeard** [comment]
incredibly great tool, thank you, developers!
