### ISSUE TITLE
Screenshot hotkey not working anymore after new Windows Update

### ISSUE THREAD

**Issue by uilton-oliveira** [flameshot-org/flameshot#3214]
### Flameshot Version

v12.1.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11 - Moment 3

### Description

Microsoft recently replaced the Screenshot hotkey with the Snipping Tool, since that, when i press the Print Screen, it no longer opens Flameshot, but do open the Snipping Tool instead.

### Steps to reproduce

Press the Print Screen button with the newest windows 11 update.

### System Information

Windows 11 - M3

**Comment by uilton-oliveira** [comment]
PS: If you disable it on settings, the flameshot start working again..
https://www.makeuseof.com/print-screen-opens-snipping-tool-windows-11/

**Comment by octocatsup** [comment]
> Thanks, but we already had those instructions on our website:
> 
> https://flameshot.org/docs/guide/windows-help/#how-to-disable-windows-snipping-tool-when-i-press-printscreen
> 
> I'm going to close this issue as it is bad behavior of Windows rather than a Flameshot bug (a good OS would not screw up a user's custom settings without proper heads-up)

Hi, the provided instructions on your website are no longer valid because Microsoft. The new location of the Print Screen key toggle in the Windows settings is: 

**Windows Settings > Accessibility > On-screen keyboard, access keys, and Print screen**

![image](https://github.com/flameshot-org/flameshot/assets/75054337/e6d2f135-5ee1-4763-86b6-ad1dcc04c566)

**Comment by vzakharov-rxnt** [comment]
Flameshot needs to be reinstalled if windows setting was changed after it was installed. This sounds like a bug to me.
I confirmed via close/reopen and also system restart. Print screen key did not start working until I reinstalled Flameshot.
