### ISSUE TITLE
When you add text to capture and change your keyboard layout at the same time, the focus is lost

### ISSUE THREAD

**Issue by w3lifer** [flameshot-org/flameshot#3221]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-73-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04.2 LTS

### Description

When you add text to capture and change your keyboard layout at the same time, the focus is lost.

### Steps to reproduce

1. Make capture.
2. Start adding text to the capture and change the keyboard layout at the same time — the focus is lost.

### Screenshots or screen recordings

https://github.com/flameshot-org/flameshot/assets/14075412/837cb7ce-5d94-4311-be5d-27241de8533b

### System Information

- Ubuntu 22.04.2 LTS
- Monitor:

```
  *-display                 
       description: VGA compatible controller
       product: WhiskeyLake-U GT2 [UHD Graphics 620]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:145 memory:c0000000-c0ffffff memory:b0000000-bfffffff ioport:4000(size=64) memory:c0000-dffff
```
- Desktop Environment: ubuntu:GNOME; Window Manager: ubuntu-xorg.

**Comment by mmahmoudian** [comment]
@w3lifer Any particular reason you have closed this issue? Did it get resolved?

**Comment by justislav** [comment]
this helped me

https://askubuntu.com/questions/1410895/switching-keyboard-layout-intercepts-window-focus-collapses-fullscreen-windows

I just have istalled https://github.com/ankostis/gnome-shell-quick-lang-switch#install
and got no more focus lose in flameshot add text tool

**Comment by w3lifer** [comment]
@mmahmoudian, as @justislav mentioned, when switching the keyboard layout, the focus switched to the layout switching widget:

https://github.com/flameshot-org/flameshot/assets/14075412/72602446-e1d4-4f8d-906f-8412cbcb10ff

So I don't think it's a Flameshot problem.

I somehow changed the keyboard shortcut for switching the layout to `Alt`+`Left Shift` and now it works without calling this widget. And the old one (`Super`+`Space`) calls (in the video above).

If my memory is not mistaken, then I did it like this: https://askubuntu.com/a/1430496/455004.
