### ISSUE TITLE
If you press the Arrow while entering text, Flameshot exits edit mode without saving

### ISSUE THREAD

**Issue by w3lifer** [flameshot-org/flameshot#3222]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-73-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04.2 LTS

### Description

If you press the Arrow while entering text, Flameshot exits edit mode without saving.

### Steps to reproduce

1. Make capture.
2. Start adding text to the capture and press Arrow buttont — Flameshot exits edit mode without saving.

### Screenshots or screen recordings

https://github.com/flameshot-org/flameshot/assets/14075412/98b5f9ca-96e3-4404-a0c3-e6327a4c4668

### System Information

- Ubuntu 22.04.2 LTS
- Monitor:

```
  *-display                 
       description: VGA compatible controller
       product: WhiskeyLake-U GT2 [UHD Graphics 620]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:145 memory:c0000000-c0ffffff memory:b0000000-bfffffff ioport:4000(size=64) memory:c0000-dffff
```
- Desktop Environment: ubuntu:GNOME; Window Manager: ubuntu-xorg.

**Comment by mmahmoudian** [comment]
Thanks for taking the time to report but:
- Your flameshot is very old
- this bug is already reported and fixed.

Please always make sure to check among open and closed issues.

**Comment by w3lifer** [comment]
@mmahmoudian, how can I install the latest version of the app on Ubuntu 22.04?

**Comment by mmahmoudian** [comment]
You can all the info about that here:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic
