### ISSUE TITLE
Copied to clipboard screenshot could not be pasted into browswer when `Use JPG format for clipboard` is used.

### ISSUE THREAD

**Issue by KES777** [flameshot-org/flameshot#3225]
### Flameshot Version

$ flameshot --version
Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint v21.1 Cinnamon

### Description

When this option is enabled, I can not paste copied to clipboard image into FF. (see below)
![image](https://github.com/flameshot-org/flameshot/assets/799021/747dea94-d0c3-4e66-9b41-1854d7df2f01)

Probably this is the issue of FF and Chrome, that they do not understand JPG format. Telegram messenger, for example, works fin and understand copied JPG into clipboard.

As different resolution I suppose to make this hint more descriptive:
![image](https://github.com/flameshot-org/flameshot/assets/799021/b981b342-c19f-481d-8d53-de4eb4a7dbcb)

eg. `... Also please notice that some applications like FF/Chrome could not understand JPG formats`

### Steps to reproduce

1. Enable `Use JPG format for clipboard`
2. Do screenshot
3. Try to <kbd>CTRL+V</kbd> into firefox on imgur.com

### System Information

Linux Mint v21.1 Cinnamon 

***why I need to input operating system twice? )

**Comment by mmahmoudian** [comment]
Please search other open and closed issues **before** creating a new one. Also please test the latest version as many bugs have been fixed since old version.

**Comment by KES777** [comment]
@mmahmoudian Sorry. I was sure that I used the last version:
![image](https://github.com/flameshot-org/flameshot/assets/799021/ca64fc76-6e70-4bba-af11-9677426cc337)

Tried to add PPA, but `Flameshot`s PPA does not support `jammy` yet:

![image](https://github.com/flameshot-org/flameshot/assets/799021/aa5b000c-8330-43e4-ae29-deb9364a26c6)

**Comment by KES777** [comment]
Thank you for the interesting link to the `repology`.

>you will not get the latest versions
I know that. But if I want the latest release for a given application, I can add only its `PPA` directly. So I will be able to get the latest version. By in my case of distro, I can not do that, because `flameshot`s PPA was not updated to support `jammy`.
