### ISSUE TITLE
Improve help message

### ISSUE THREAD

**Issue by KES777** [flameshot-org/flameshot#3226]
### Feature Description

![image](https://github.com/flameshot-org/flameshot/assets/799021/5b43141f-cd02-45fa-8603-7f7c6dfa247d)

From here I can not find list of options for `gui` command, eg. `flameshot gui --help`

It would be better to name flameshot `arguments` as `commands`. 

Proposition: show help like `flameshot [flameshot-options] [command] [command-options] [command-arguments]

Also many programs starts to support `help` command, eg. `flameshot help gui`

Thank you.

**Comment by mmahmoudian** [comment]
Yes, I believe we should use the terminology that is used in the manpage (i.e `man flameshot`):

![image](https://github.com/flameshot-org/flameshot/assets/390889/4fe272eb-77f2-411b-bdb0-d4b2f06f36f3)

**Comment by KES777** [comment]
@mmahmoudian `subcommand` is Ok

**Comment by toadkarter** [comment]
I can have a look at this one if this hasn't already been completed? I presume that the ultimate goal here is to ensure that "help" is more or less consistent with the "man" page?

**Comment by mmahmoudian** [comment]
@toadkarter yes, it is as simple as you explained. Just "arguments" -> "subcommands". If you also see any discrepancies, feel free to fix those too. Take manpage as the reference.

**Comment by toadkarter** [comment]
Great, thanks! I'll open a PR once I've had a go at it
