### ISSUE TITLE
Deletaion for active tool does not work

### ISSUE THREAD

**Issue by KES777** [flameshot-org/flameshot#3228]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint v21.1 Cinnamon

### Description

I tried to 

![image](https://github.com/flameshot-org/flameshot/assets/799021/54cef321-ebfa-48f5-a756-96742448de9a)

### Steps to reproduce

1. run `flameshot gui`
2. Select tool `c`
3. Try to delete current tool `Del`

If you press `Esc` it deselects current tool though.

### Screenshots or screen recordings

dd

### System Information

Linux Mint v21.1 Cinnamon

System:
  Host: kes-X406UA Kernel: 5.15.0-73-generic x86_64 bits: 64
    Desktop: Cinnamon 5.6.8 Distro: Linux Mint 21.1 Vera
Graphics:
  Device-1: Intel HD Graphics 620 driver: i915 v: kernel
  Device-2: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.2.5

**Comment by mmahmoudian** [comment]
I think we have used a bad word here. By "delete current tool" what we mean is "delete the selected object". This is used in the following scenario:
1. open `flameshot gui`
2. select a tool (e.g arrow by pressing <kbd>a</kbd>)
3. draw something
4. deselect the tool (e.g by clicking on the tool again, or pressing <kbd>Esc</kbd> or pressing <kbd>a</kbd>)
5. select what you have draw (a dotted rectangle appears around the object)
6. press <kbd>Del</kbd>

**Comment by KES777** [comment]
@mmahmoudian *oh... I used Flameshot couple of years, but never know that I can delete what I draw not by <kbd>CTRL+z</kbd>  undo it! Why help message was not displayed for tools too??*

Ok. Thank you for this tip! It seems would be useful to have "hand" tool. So people could see it and understand that it is possible to select something when none other tools were selected. eg. when deselecting current tool - activate "hand" tool by default. 

1. Implement "hand" tool

2. For backward compatibility "Show 'hand' tool" option could be implemented (enabled by default). So old users could disable it.

3. My proposition for name is: `Delete selected drawn object`

**Comment by KES777** [comment]
4. Probably here should be implemented also `Unselect current active tool` hotkey option.

**Comment by mmahmoudian** [comment]
> 4. Probably here should be implemented also `Unselect current active tool` hotkey option.

As I mentioned in my 4th point, <kbd>Esc</kbd> deselect the active tool.

**Comment by KES777** [comment]
Yes, and for this action there is not `shortcut`.
![image](https://github.com/flameshot-org/flameshot/assets/799021/57450de4-178c-482c-91ad-59152ea93135)

Which I propose to implement.

**Comment by mmahmoudian** [comment]
> Yes, and for this action there is not shortcut.

The Esc is the shortcut, but it is not customizable, and that is by design. The only key that we reserved our rights to keep it as is and do not allow user to change it. This is because users do all sorts of weird things with their config, and we need to have a universal and uniform way to instruct them to cancel things without asking them their config.

**Comment by mmahmoudian** [comment]
Shall we close this issue? For hand tool please open a feature request and copy paste your comment about it. (And modify it if you want).

**Comment by mmahmoudian** [comment]
I just realized the name change should be done before closing the issue. I checked and it can be straightfoward thing but the translations would make it complicated for me to change. I would rather wait for other devs to do it or suggest the best way so I can do it myself.

**Comment by Amangupta0000** [comment]
https://github.com/flameshot-org/flameshot/pull/3348#issue-1909996144

**Comment by Amangupta0000** [comment]
https://github.com/flameshot-org/flameshot/pull/3348#issue-1909996144 
Changed the name.

**Comment by serebryakov02** [comment]
Hi, it looks like this issue may already be resolved.

From the discussion, the remaining action item was to rename `Delete current tool` to `Delete selected drawn object`, and that change appears to have been merged in #3348. I also see the updated text in the current codebase.

Should this issue be closed now, or is there still another part of the original request that needs work?
