### ISSUE TITLE
Can't launch Flameshot after updating Windows 11

### ISSUE THREAD

**Issue by gabrieldantasv** [flameshot-org/flameshot#3234]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.22621

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11

### Description

22H2

### Steps to reproduce

The print screen feature on windows if launching after pressing the print screen button.
Just opening flameshot manually I can run the flameshot.

### System Information

22H2 Windows 11 Version

**Comment by LoboMetalurgico** [comment]
Same with me!

Windows 11 Home
Version: 22H2
Compilation: 22621.1900

**Comment by LoboMetalurgico** [comment]
Workaround: You can disable the default windows snipping tool, just go to `Settings > Accessibility > Keyboard` and disable `Use printscreen button to open snipping tool`, restart flameshot and voila, flameshot is back in the game !

**Comment by mmahmoudian** [comment]
Please read documents *and* search among open and closed issued *before* creating a new issue.

You can find the solution here:
https://flameshot.org/docs/guide/windows-help/

**Comment by FrancysSousa2020** [comment]
Olá pessoal. Resumindo

**Comment by pedroaugustorgg** [comment]
> Olá pessoal. Resumindo, não tem como então usar a teclar print para o Flameshot né? Abraço

~É possível sim, assim como já comentaram anteriormente, basta você desabilitar essa opção em "Configurações > Acessibilidade" e depois fechar o flameshot. Quando abrir novamente, a tecla de PrintScreen irá abrir o flameshot ao invés do app padrão do windows.

![Image](https://github.com/user-attachments/assets/ac1d41f4-59b9-44d5-aab7-7a836db8e89d)
