### ISSUE TITLE
[Bug]The bottom area of the screenshot is black when there are more than one window in screenshot zoom

### ISSUE THREAD

**Issue by DreamMaoMao** [flameshot-org/flameshot#3237]
### Flameshot Version

Flameshot v12.1.0 (3ededae5)
Compiled with Qt 5.15.8
linux: 6.2.0-20-generic
ubuntu: 23.04

### Installation Type

Compiled from source

### Operating System type and version

ubuntu23.04 with hyprland

### Description

The bottom area of the screenshot is black  when there are more than one window in shot zoom

1.screenshot one window
![image](https://github.com/flameshot-org/flameshot/assets/30348075/46f27053-c4ef-4001-ab24-f13bd2e7fd89)

2.screenshot more than one window
![image](https://github.com/flameshot-org/flameshot/assets/30348075/8274f531-7011-474b-835b-9f74af33ad0e)

3. use another screenshot tool:
![image](https://github.com/flameshot-org/flameshot/assets/30348075/d7f49fbc-a271-4d44-b84b-9f0cd4697603)

### Steps to reproduce

1.run `flameshot` in terminal 
2.mouse to right click the flameshot icon and select start screeshot
3.seletct a zoom 
4.click copy button
5.paste the picture 

### System Information

Operating system and version:
ubuntu 23.04

Desktop Environment and your Window Manager:
hyprland

Xorg or Wayland:
wayland with support xwayland

**Comment by DreamMaoMao** [comment]
After pasting, you can only see the top half of the screenshot

**Comment by ardishco-the-great** [comment]
@mmahmoudian this not exclusive to Wayland, this is a chromium/electron problem as I've observed. When pasting into discord (which uses chromium 89 by default, I think) this is observed. However the same is not present on Firefox or discord-screenaudio (which is basically a wrapper that uses qt5-webengine for discord)

I have had this issue on KDE Plasma (Xorg). BSPWM, Sway and Hyprland (basically every desktop I have ever used, basically)

Checking the copied image, It's properly rendered. This has been an issue for the longest time and should be fixable given that a grim/slurp does not reproduce the same issue

**Comment by mmahmoudian** [comment]
@ardishco-the-great which OS are you using?

**Comment by ardishco-the-great** [comment]
I thought I replied to this yesterday. Huh, guess I didn't.

Anyway, I am on Arch Linux, latest Zen Kernel (though the same results are observable on any other kernel I have tried.)

**Comment by bachhh** [comment]
Just want to say I'm encountering the same issue, pasting into Slack/Discord/Chromium browsers. Glad it's not a Wayland thing.

**Comment by DreamMaoMao** [comment]
cmake -DUSE_WAYLAND_GRIM=true

use grim can fix this problem
