### ISSUE TITLE
Windows - rectangular region selection only available on main screen (multi-monitor setup) when connecting to docking station

### ISSUE THREAD

**Issue by mRniiat** [flameshot-org/flameshot#3238]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

### Installation Type

Compiled from source

### Operating System type and version

Windows 10 Pro 22H2 (OS Build 19045.3086)

### Description

Sorry if this was reported already, I tried my best to search first. 

When booting my laptop and connecting do a USB-C docking station with additional monitors afterwards, the running Flameshot process only captures the main screen for rectangular selection depending on what monitor (internal or external, both work) is set as main monitor. All other monitors stay the way they are (no Flameshot overlay).
After completely quitting and restarting Flameshot, all monitors are available for rectangular selection again. 

### Steps to reproduce

1. start laptop / computer
2. start Flameshot (if not in autostart)
3. connect additional monitor
4. click tray icon or press PrintScrn 

### System Information

Windows 10 Pro 22H2 (OS Build 19045.3086)

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

Number of **n** monitors set to expand

**Comment by mmahmoudian** [comment]
Yes, it is duplicate. This is known issue and we cannot do much about it at this point. What you can do it to kill flameshot (close from tray area) and start it again.

It will be addressed at some point.
