### ISSUE TITLE
Add option to save and temporarily hide a pinned screenshot

### ISSUE THREAD

**Issue by JackieMium** [flameshot-org/flameshot#325]
The latest pin function is realy useful, especially when I am reading a long paper and want to check the figures andd table along with text which are usually not on the same page. But it occured to be that the pin function does not allow me to save the pinned screenshot if I later find it important and want a local copy of it. I have to drop the pinned screenshot and take another one. And sometimes a pinned screenshot is right above something and I want to temporarily hide it so I can see the text below, this is also impossible and I have to drop it an later take another again.

So I think adding a save and hide option to pinned screenshot will be helpful, and make flameshot even more powerful. May add them to a pop out menu when  right click on a pinned screenshot is the thing to do.

**Comment by ZetaoYang** [comment]
@JackieMium More features/functions about 'Pin tool' need global hot key support. If flameshot achieved that, more user action/option will be added into flameshot.

**Comment by JackieMium** [comment]
@ZetaoYang Having keyboard shortcuts is surely great. But it is also acceptable to take steps in doing this. For example, first we add right click menu options for saving and hiding, then we consider the hot key issue.

_Sent from my ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by borgmanJeremy** [comment]
Let's continue discussions related to pin tool on #954
