### ISSUE TITLE
Hotkeys dont work

### ISSUE THREAD

**Issue by back-lacking** [flameshot-org/flameshot#3252]
### Flameshot Version

Flameshot v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 38

### Description

I am currently running Fedora 38 with GNOME 44.2 and Wayland. I am unable to use hotkeys for Flameshot. I set a 2 custom shortcuts for flameshot. I set `flameshot gui -c -s -p ~/Pictures/Screenshots` to PrtSc and `flameshot screen -c -p  $HOME/Pictures/Screenshots` to Ctrl+PrtSc. Pressing the keys dont bring up flameshot. running the commands in the terminal does work. Ive checked the issues and found issue #1577 but it is for arch. Ive checked the troubleshooting and wayland help articles on the documentation but they dont seem to have an section for keybinds not working. 

### Steps to reproduce

1. Set a custom flameshot shortcut using the prtsc key in gnome settings in Keyboard > View and Customize shortcuts > custom shortcuts. 
2. press the keybind for the flameshot shortcut. 
3. see whether or not it works. 

### System Information

Fedora 38
Single 1920x1080 60hz monitor
![image](https://github.com/flameshot-org/flameshot/assets/86173810/c49fc0bd-de78-4426-a93a-bbb3a31503f1)
Gnome 44.2, Wayland

**Comment by back-lacking** [comment]
screenshots were taken using gnomes own screenshot tools

**Comment by back-lacking** [comment]
also checked faq.

**Comment by mmahmoudian** [comment]
> screenshots were taken using gnomes own screenshot tools

Do you mean you see this window:

![](https://flameshot.org/media/content/docs/guide/wayland-help/2022-08-04_11-39_gnome_share_permission_indow.png)

If so, this is how Gnome works and it has been explained here:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

If not, please clarify what you mean by "gnomes own screenshot tools".

> running the commands in the terminal does work.

This shows that the issue is not with Flameshot but rather your Gnome keybinding configuration. Can you send a screenshot from the part that you have defined these keybindings. For obvious reasons I do not use Gnome, but perhaps I can help you figuring out the issue.

**Comment by back-lacking** [comment]
> > screenshots were taken using gnomes own screenshot tools
> 
> Do you mean you see this window:
> 
> ![](https://camo.githubusercontent.com/b3949b04a0abc205ddfff63d5bfa327fd5dae5069e97d01f4887ed5272632a09/68747470733a2f2f666c616d6573686f742e6f72672f6d656469612f636f6e74656e742f646f63732f67756964652f7761796c616e642d68656c702f323032322d30382d30345f31312d33395f676e6f6d655f73686172655f7065726d697373696f6e5f696e646f772e706e67)
> 
> If so, this is how Gnome works and it has been explained here:
> 
> https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
> 
> If not, please clarify what you mean by "gnomes own screenshot tools".
> 
> > running the commands in the terminal does work.
> 
> This shows that the issue is not with Flameshot but rather your Gnome keybinding configuration. Can you send a screenshot from the part that you have defined these keybindings. For obvious reasons I do not use Gnome, but perhaps I can help you figuring out the issue.

i was meant to send in a screenshot of my gnome shortcuts, mb. also i do not see the share screen prompt. i did get a prompt similar asking the one shown when i first ran flameshot and allowed the permission for flameshot. 
here are my gnome shortcuts. 
![image](https://github.com/flameshot-org/flameshot/assets/86173810/7f885504-2577-459f-b324-9daaa75786bc)
![image](https://github.com/flameshot-org/flameshot/assets/86173810/8bc9a7b4-f46f-454b-b109-b43fa1812e26)

**Comment by mmahmoudian** [comment]
Thanks for the response. I cannot see any issue with the commands, so it must be something about how Gnome executes the commands. Please replace one of those commands with the following and see if pressing the shortcut gives you a notification:

```sh
notify-send -t 10000 "Our keyboard event" "This was successfully triggered"
```

**Comment by back-lacking** [comment]
> Thanks for the response. I cannot see any issue with the commands, so it must be something about how Gnome executes the commands. Please replace one of those commands with the following and see if pressing the shortcut gives you a notification:
> 
> ```shell
> notify-send -t 10000 "Our keyboard event" "This was successfully triggered"
> ```
sorry for a bit of a late response. 
here is a video showing that the custom notification shortcut does work.

https://github.com/flameshot-org/flameshot/assets/86173810/4c53d84b-942e-4825-8fad-dd9c0f466700

**Comment by mmahmoudian** [comment]
ok, then it means that either the Flameshot is not in your PATH variable or somehow it faces some error. My next test will be to use absolute path instead of `~` or `$HOME` and see if that time it works. Basically the variable expansion is the duty of your shell, and therefore it is probable that when Gnome is running a command, it is not able to expand the variables. A way to test the variable expansion of course is to use the same `notify-send` and instead of a static text ask it to print your variable:

```sh
notify-send -t 10000 "Our keyboard event" "$HOME"
```

**Comment by back-lacking** [comment]
> ok, then it means that either the Flameshot is not in your PATH variable or somehow it faces some error. My next test will be to use absolute path instead of `~` or `$HOME` and see if that time it works. Basically the variable expansion is the duty of your shell, and therefore it is probable that when Gnome is running a command, it is not able to expand the variables. A way to test the variable expansion of course is to use the same `notify-send` and instead of a static text ask it to print your variable:
> 
> ```shell
> notify-send -t 10000 "Our keyboard event" "$HOME"
> ```

just replaced the ~ in my path of my flameshot command with the `/home/timmy` and it now it works 
also tried the command you sent, it only shows "$HOME" instead of my home path in the notif.

**Comment by mmahmoudian** [comment]
Thanks for reporting back.

> tried the command you sent, it only shows "$HOME" instead of my home path in the notif.

Then this shows that the Gnome does not allow expansion of environmental shell variables inside the keybinding.

> just replaced the ~ in my path of my flameshot command with the /home/timmy and it now it works

I'm glad that the issue was resolved.

**Comment by mmahmoudian** [comment]
@back-lacking 
Btw, one question, why are you even setting the path like that? if you always want to save your screenshots there, why not setting it properly in the config file and just call `flameshot gui` from your Gnome keybinding?

![image](https://github.com/flameshot-org/flameshot/assets/390889/031a99ed-a664-4c38-aed3-086ea9d73c9c)

**Comment by back-lacking** [comment]
@mmahmoudian the reason i wanted to set the path that way was so that i could use the keybind on other linux installs with gnome. Also, if i understand correctly, can i just omit the -path part of the command? Ive already set the path the screenshots go to in the config. I just thought that i would have to specify the path when manually running the command and carried that logic over to the gnome hotkey.

**Comment by mmahmoudian** [comment]
> can i just omit the -path part of the command?

Yes, that was what I was trying to convey. Flameshot uses the config if no CLI arguments are provided. The CLI has priority

**Comment by mmahmoudian** [comment]
> can i use variables like $HOME in the config

It has been long debated to allow variable expansion in Flameshot, but we ultimately decided that this is the duty that should be carried out by the shell not by a screenshot tool. Therefore you cannot use any of your environmental variables in the config file, but this does not mean that you have to manually type them. For example, if you want to have a portable config, you can have a very small script to use `sed -i` to change the config file in place and inject the expanded form of the environmental variable you want.

**Comment by deividrp** [comment]
Try this command:

`/bin/sh -c "flameshot gui" > /dev/null &`

![Uploading flameshot.png…]()

**Comment by NoobGajen** [comment]
> Try this command:
> 
> `/bin/sh -c "flameshot gui" > /dev/null &`
> 
> ![flameshot](https://private-user-images.githubusercontent.com/5632495/360701153-3d5b2da9-7d5f-41d2-9751-3132660af130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMjkyODQsIm5iZiI6MTcyNzEyODk4NCwicGF0aCI6Ii81NjMyNDk1LzM2MDcwMTE1My0zZDViMmRhOS03ZDVmLTQxZDItOTc1MS0zMTMyNjYwYWYxMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMjIwMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzMDg1YmQ0NDIyNDhkZTU3MWEyYjM2YjBmYjJiYjZkYzRiYzAwZGQ0MDQwNzNkYjVjN2ZlNmM3MzUzMTNlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zZes62WA_QDDGZixov43MhDX7VFiFq80qTcxeBAT1Js)

Still the issue is same when I try to take screenshot from gnome keybindings
![image](https://github.com/user-attachments/assets/732221a7-3175-4190-aa65-7cc5fd83bc5b)

**Comment by natema** [comment]
I have the same issue on Fedora 41, Gnome 47.1. The shortcut `flameshot gui` errors, while `gnome-terminal -- flameshot gui` works but opens a terminal.

**Comment by natema** [comment]
I made some progress [in this gist discussion](https://gist.github.com/linuxkathirvel/5e8bb416f487b4b47a97daa42288502f?permalink_comment_id=5295761#gistcomment-5295761) on the issue. Now the shortcut works but the flameshot editor crops the screen.

**Comment by jarulsamy** [comment]
@natema thanks for the tips, I ended up getting this to work decently by using Kitty and instruct it to start as minimized:
```
kitty --start-as=minimized -- flameshot gui -s -c
```
It feels a little kludgy but ends up working quite well.

**Comment by Joaojgnogueira** [comment]
<details>
<summary>The dbus-monitor content</summary>


![Image](https://github.com/user-attachments/assets/d6bedc29-8fa4-40ee-9ca7-f1579c162ea8)

</details>

**Comment by gutopardini** [comment]
If you're still using GNOME + Wayland and struggling with Flameshot/XWayland issues, take a look at my project:

https://github.com/gutopardini/wayshot

WayShot uses the native GNOME screenshot tool under Wayland and automatically opens a modern annotation editor afterwards (arrows, text, blur, shapes, etc).

The goal is to provide a more native and reliable screenshot workflow for GNOME Wayland users.

**Comment by mmahmoudian** [comment]
@gutopardini I noticed that you copy-pasted the same advert on multiple threads. I hid them all with "off-topic". Consider this as the first strike. Spamming is not tolerated even if it is about a FLOSS, let alone for a software with non-free license! Suggesting some tool is one thing, advertising it under multiple threads is another.
