### ISSUE TITLE
Hotkeys dont work - Windows 11

### ISSUE THREAD

**Issue by LorhanSohaky** [flameshot-org/flameshot#3259]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.22621
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11 Pro (22621.1928)

### Description

I have already disabled the Windows Snipping tool, but even so when I press PrintScreen, Flameshot is not executed and neither is the Windows Snipping tool.

Note: if I manually open the launcher, the screenshot works, only because of a shortcut that does not open

### Steps to reproduce

1. flameshot autostart
2. [Disable Windows Snipping tool as shown on the website](https://flameshot.org/docs/guide/windows-help/#how-to-disable-windows-snipping-tool-when-i-press-printscreen)
3. Press PrintScreen

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/16273730/50a3091f-d992-4900-a343-14ff2112027c)

### System Information

Edição	Windows 11 Pro (22621.1928)
Versão	22H2
Instalado em	‎15/‎11/‎2022
Compilação do SO	
Experiência	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by iresten** [comment]
I experienced the same thing on logon today with same windows version and same Flameshot version. 
But i got i to work again by the following:
1. Activate "Use the PrntScn" button to open screen snipping.
a)The prntscrn button now open windows snipping and not Flameshot.
2. Inctivate "Use the PrntScn" button.
3. Reboot windows.

After this with autostart on flameshoot my prntscrn button on both computer and external keyboard opens flameshot snipping as per usual.

**Comment by pavlidisnick** [comment]
> I experienced the same thing on logon today with same windows version and same Flameshot version. But i got i to work again by the following:
> 
> 1. Activate "Use the PrntScn" button to open screen snipping.
>    a)The prntscrn button now open windows snipping and not Flameshot.
> 2. Inctivate "Use the PrntScn" button.
> 3. Reboot windows.
> 
> After this with autostart on flameshoot my prntscrn button on both computer and external keyboard opens flameshot snipping as per usual.

This workaround works. Good job! 🚀

**Comment by LorhanSohaky** [comment]
> I experienced the same thing on logon today with same windows version and same Flameshot version. But i got i to work again by the following:
> 
>     1. Activate "Use the PrntScn" button to open screen snipping.
>        a)The prntscrn button now open windows snipping and not Flameshot.
> 
>     2. Inctivate "Use the PrntScn" button.
> 
>     3. Reboot windows.
> 
> 
> After this with autostart on flameshoot my prntscrn button on both computer and external keyboard opens flameshot snipping as per usual.

This works for me, thanks!
