### ISSUE TITLE
Print screen button no longer opens flameshot in windows version 10.0.22621 Build 22621

### ISSUE THREAD

**Issue by agustaf9** [flameshot-org/flameshot#3270]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2

winnt: 10.0.22621
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11 10.0.22621 Build 22621

### Description

The print screen button takes me to the windows print screen interface

### Steps to reproduce

1. Open flameshot
2. Push `Print Screen` key on keyboard

### System Information

See above

**Comment by mmahmoudian** [comment]
Please read documentations and search among open and closed issues before creating a new one. This would save you a lot of time.

https://flameshot.org/docs/guide/windows-help/
