### ISSUE TITLE
Zoom on cursor

### ISSUE THREAD

**Issue by jeancastel** [flameshot-org/flameshot#328]
Hi,
It'll be a good feature to implement a zoom box around the cursor during screen selection.
This feature will permit to take precises screenshots.

Thank you !

**Comment by kyrios123** [comment]
I agree, this is really something I miss to easily select the windows border (especially when being on a host taking a screenshot of a window running in a virtual guest machine).
Something similar to the [magnifying glass of greenshot](http://www.cid-auditeur.com/images/bt_portfolio/87/original/36896cbbee8440076c0735ae21d22bea.png) for example would be awesome!

**Comment by anmsh** [comment]
+1  I love this on greenshot and would love to see on flameshot now. Another vote for this.

**Comment by mmahmoudian** [comment]
@veracioux considering that you have implemented the zoom thing for the color selection, and considering the suggestion of @borgmanJeremy to have a key pressed for loading the zoomed part, can we use these elements to implement this?

I'm bot saying that this feature request should be done, I'm just saying that I think the elements are there and can potentially be combined.

**Comment by veracioux** [comment]
@mmahmoudian Sure, I can try to extend the feature some time. But I am really busy lately so I'll have to put it on hold or someone else can try to adapt my code from the color grabber.
