### ISSUE TITLE
Can't upload images to Imgur (Read description before closing please) !!!!

### ISSUE THREAD

**Issue by cdkw2** [flameshot-org/flameshot#3288]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3
linux: 6.1.21-v8+
debian: 11

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

OS: Debian GNU/Linux 11 (bullseye) OS architecture: 64-bit Last updated Pi-Apps on: 08/02/2023 Latest Pi-Apps version: 08/02/2023 Kernel: aarch64 6.1.21-v8+ Device model: Raspberry Pi 4 Model B Rev 1.2  Cpu name: Cortex-A72 Ram size: 3.79 GB Raspberry Pi OS image version: 2023-05-03 Language: en_US.UTF-8

### Description

![image](https://github.com/flameshot-org/flameshot/assets/67598073/6a920577-d318-4436-b0e8-3be6a1e704be)

Can not upload images to Imgur. I know that a duplicate of this issue exists but it has no clear answer and it is of windows 11 and I am using a raspberry pi so it is not of any help. Kindly tell me how can I resolve this because I use flameshot a lot in my daily life.

### Steps to reproduce

1. Run flameshot
2. Take a screenshot
3. try to upload
4. Get error

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/67598073/620558b1-c49e-4574-be07-32e1cffe7944)

![image](https://github.com/flameshot-org/flameshot/assets/67598073/29045c99-cce8-4306-8ada-f842cf1b0c24)

## System:
  Host: raspberrypi Kernel: 6.1.21-v8+ aarch64 bits: 64 Desktop: LXDE 0.10.1 
  Distro: Debian GNU/Linux 11 (bullseye) 
## Graphics:
  Device-1: bcm2711-vc5 driver: vc4_drm v: N/A 
  Device-2: bcm2711-hdmi0 driver: N/A 
  Device-3: bcm2711-hdmi1 driver: N/A 
  Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting 
  unloaded: fbdev resolution: 1680x1050~60Hz 
  OpenGL: renderer: V3D 4.2 v: 2.1 Mesa 20.3.5

**Comment by cdkw2** [comment]
Fixed on my own LOL.

**Comment by theofficialgman** [comment]
@cdkw2 re-open as you are running the latest release. Let upstream close it once they make a new release.

**Comment by cdkw2** [comment]
@theofficialgman  Sure thing !

**Comment by mmahmoudian** [comment]
@theofficialgman @cdkw2 thanks for the efforts, posts and comments on both repos.

I checked all merges PRs just to be sure about this statement: we have not changed anything regarding Imgur since 12.1.0, therefore, whatever the issue is, it is between the machine (Rpi) and the imgur server. I agree that in Flameshot we do not have good handling procedures for imgur errors and some messages from imgur is not fully returned to user. That is something that we should work on, but this reported issue is not anything we can handle in Flameshot.

Also just as a side note, one of the typical issues is that in default Flameshot we use our own API token by default, but it has a quota and in some times of day when many users upload with our token, we run out of quota and this is among those errors that we are not reporting it to user properly. The solution is to create your own Imgur token as it is explained in our documentation:

https://flameshot.org/docs/guide/imgur-help/

**Comment by cdkw2** [comment]
> @theofficialgman @cdkw2 thanks for the efforts, posts and comments on both repos.
> 
> I checked all merges PRs just to be sure about this statement: we have not changed anything regarding Imgur since 12.1.0, therefore, whatever the issue is, it is between the machine (Rpi) and the imgur server. I agree that in Flameshot we do not have good handling procedures for imgur errors and some messages from imgur is not fully returned to user. That is something that we should work on, but this reported issue is not anything we can handle in Flameshot.
> 
> Also just as a side note, one of the typical issues is that in default Flameshot we use our own API token by default, but it has a quota and in some times of day when many users upload with our token, we run out of quota and this is among those errors that we are not reporting it to user properly. The solution is to create your own Imgur token as it is explained in our documentation:
> 
> https://flameshot.org/docs/guide/imgur-help/

Well I have solved the issue none the least. All I had to do was reinstall the whole software, still don't know why it was fixed but it was fixed. Thank you for answering.

**Comment by mmahmoudian** [comment]
@theofficialgman Thanks for the comment.

> have you thought about including a high number of api tokens (lets say 10) in flameshot

Well, we don't need to do that. Users who want reliability and stability can create a token using their own accounts and insert the token in Flameshot settings. The fact is that the utter correct approach would be not to provide any token for the users and force them to create an account (then they will be fully accountable for everything they upload and they will be in control). For now, and to provide ease of use for users who occasionally upload something, our token can be used. When other integration gets added (Good Drive, Pixelfed, OneDrive, ...) to Flameshot, there will not be a default set token and users have to use their own tokens and credentials from the get-go.

I would always argue that in Flameshot our duty is to provide a easy-to-use and stable software which allow the user to easily customize and fit it into their workflow. This is the main reason we are [discussing a plugin system](https://github.com/flameshot-org/flameshot/discussions/2529). This way users can use the plugin to really integrate this screenshot tool to their workflow.

Thanks again for the comment, but I felt like explaining in a little bit more details to explain the current stands of the dev team. Of course these stands can change during time 😉 , plus feedbacks and/or contributions from the community is always very warmly welcome
