### ISSUE TITLE
I can't take screenshots via Prt Sc on Windows 10

### ISSUE THREAD

**Issue by kanishknishar** [flameshot-org/flameshot#3292]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10 22H2 19045.3271

### Description

I tried taking a screenshot by pressing Prt Sc but that did not work. There is one other thread I found which said that possibly some other software was using the same shortcut so I stopped all software except sabnzbd, Windows Defender and Flameshot. I still couldn't take screenshots. 
 
Is there a way to change the shortcut to open Flameshot?

### Steps to reproduce

1. Opened Flameshot.exe
2. Stopped all other background apps 
3. Pressed Prt Sc
4. Nothing happened

### System Information

Device name	Lance
Processor	AMD Ryzen 5 5500U with Radeon Graphics            2.10 GHz
Installed RAM	16.0 GB (15.3 GB usable)
Device ID	D8F9FB30-ADAF-4031-8BF5-F24F5EDA9B79
Product ID	00356-02656-70053-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Home
Version	22H2
Installed on	‎23-‎07-‎2023
OS build	19045.3271
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by mmahmoudian** [comment]
It is not about killing processes , it is about changing your window settings. It is explained in pur documentation:

https://flameshot.org/docs/guide/windows-help/

I'm going to close this as this seems to be keybinding issue. Please reopen and add more details of this didn't solve the issue
