### ISSUE TITLE
Open with... is empty

### ISSUE THREAD

**Issue by jano2358** [flameshot-org/flameshot#3298]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

The dialog 'Open with' after capturing something appears empty, I cannot select an app to open the picture. If I paste the path for an app it will do nothing with it.

### Steps to reproduce

1. run flameshot
2. select something to capture
3. hit ctrl-o or hit the icon open with
4. the dialog appears empty

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/11798801/4e8691d4-325c-4db9-bcf1-ee41785a7617)

### System Information

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

**Comment by klamar** [comment]
I have the same problem.

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

**Comment by Nightblade** [comment]
Dupe of #1309?

**Comment by jano2358** [comment]
yup, I'm closing this one

**Comment by EraNetGit** [comment]
> yup, I'm closing this one

Why was this ticket closed, has this been fixed?
It still doesn't work on Windows 10.

Thanks.

**Comment by Nightblade** [comment]
@EraNetGit  Because #1309 already covers this bug.

**Comment by untamed1** [comment]
Just curious why not use the selected Preferred save file extension as the default and/or all of the feasible image formats associated open with said list associated to the current users file extensions under App > Default apps > Choose defaults by file type.
REG Key: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\{.ext}\OpenWithList
