### ISSUE TITLE
'Take Screenshot' moves the screen away

### ISSUE THREAD

**Issue by manbeing** [flameshot-org/flameshot#3299]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 22.5.0
osx: 13.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macos: 13.4 

### Description

I used  brew to install flameshot.
After I clicked 'Take Screenshot', the screen just moved away, please refer to the screenshot, so nothing can be caught. 
![image](https://github.com/flameshot-org/flameshot/assets/39745132/5161bcad-2232-4518-b80b-caecd5b6f27d)

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/39745132/d2f1644c-bd3f-41aa-8dd2-f291b11be162)

### System Information

macos: 13.4

**Comment by manbeing** [comment]
not a defect

**Comment by Glyphack** [comment]
Hi @manbeing I have the same issue, how did you resolve this?

**Comment by mmahmoudian** [comment]
@Glyphack Perhaps you can find your answer in our documentation:
https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

**Comment by Glyphack** [comment]
My bad thanks for the link.
