### ISSUE TITLE
Anything non-screenshot, gui-related, won't open

### ISSUE THREAD

**Issue by JonasVerhofste** [flameshot-org/flameshot#330]
**Flameshot version**
Latest commit: [1d7186a2f08284e8182ee14d54f5803cb6aa0ca8](https://github.com/lupoDharkael/flameshot/commit/1d7186a2f08284e8182ee14d54f5803cb6aa0ca8)

**Describe the bug**
I can't get any of the gui-functions to open, except for the screenshot-function itself. Making screenshots (with `flameshot gui`) and the like is no problem, but from the moment I want to save it to a file, it just seems to exit (while I remember there should be a "save as"-dialog or something). Copying to clipboard works fine tho.

Also can't open the configuration-gui (configuring through cli is not a problem), not with the command `flameshot config` or through the taskbar icon (which is visible, but disappears the moment I click "Configuration")

Is there a package I'm missing (except for the ones mentioned in the readme)?

**To Reproduce**
Clean Install of [flameshot-git-package](https://aur.archlinux.org/packages/flameshot-git) in AUR-repository. (Although I remember also having the problem with the stable one)

**Expected behavior**
Showing a dialog or configuration menu.

**System Information**
Arch Linux 4.18.5-arch1-1-ARCH
Shell: bash 4.4.23
DE: KDE (X11)
WM: Kwin
WM Theme: breeze

**Comment by JonasVerhofste** [comment]
Just noticed something: when I start flameshot from a console (i.e. `$ flameshot`), the pop-up's do work. When I, for example, open the config-window, I get the following notices in my console:

`Icon theme "gnome" not found.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active`

To clarify, this is the kind of window I'm talking about:
![screenshot-24-09-18--11-03](https://user-images.githubusercontent.com/25819942/45944268-0c4d4880-bfd9-11e8-94a0-0ca006d03fb2.png)

**Comment by lupoDharkael** [comment]
I find the description rather confusing, could you record a video showing what happens when you try to open the configuration and the other problems?
> but from the moment I want to save it to a file, it just seems to exit 
if you define a path in the command it should save the screenshot there without asking for a path (flameshot gui -p /my/path)

**Comment by JonasVerhofste** [comment]
As requested:
![flameshot-problem](https://user-images.githubusercontent.com/25819942/46909996-caeeef80-cf2b-11e8-99b3-c1e1f466ae20.gif)
No other instance of flameshot was running while this video was taken. The first command, `flameshot gui` was the 'first' time flameshot was run.
Note how the "save" and "config" gui's don't open (flameshot crashes), but after starting it without options, it works fine. Setting "Launch on startup" doesn't solve the problem either.

**Comment by JonasVerhofste** [comment]
@lupoDharkael

**Comment by Fr3llD** [comment]
I have the same problem, the terminal gives me:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

Also, running "flameshot gui" or "flameshot config" does nothing

**Comment by markovic-nikola** [comment]
> I have the same problem, the terminal gives me:
> 
> ```
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  locale::facet::_S_create_c_locale name not valid
> ```
> Also, running "flameshot gui" or "flameshot config" does nothing.
> 
> I'm running ubuntu 18.04 with KDE on a XPS13-9350

I'm having the same issue, using Manjaro 18.0.4 with KDE

**Comment by zell-mbc** [comment]
Same error message here: "flameshot gui" works but "flameshot config" does nothing other than producing the c_locale error in journalctl. I saw some notes that one needs to check locale settings which I did, but I don't know what to set to make flameshot work again.
I am running Manjaro KDE.
