### ISSUE TITLE
Option to disable Left-Double-click from copy-selection-to-clipboard and exiting the current flameshot edit

### ISSUE THREAD

**Issue by SamDevelopsCode** [flameshot-org/flameshot#3304]
### Feature Description

I want to have more control of when the current flameshot edit exits. As of now the copy-selection-to-clipboard has 2 keybinds but the double-click on the left mouse button cannot be disabled from what I have tried.

Its pretty easy to accidentally double click and lose the entire edit. It would be nice to be able to have a checkbox toggle to turn this feature off or have full control of the [copy selection to clipboard] keybind so I can remove the Left Double-click.

![image](https://github.com/flameshot-org/flameshot/assets/122749374/65e496b9-bbd8-42d9-a195-eeeecd5f1155)

**Comment by SamDevelopsCode** [comment]
Duplicate issue. My mistake.

**Comment by snakeru** [comment]
Where is the link to duplicate?
