### ISSUE TITLE
MediaManager like Shutter

### ISSUE THREAD

**Issue by xstable** [flameshot-org/flameshot#331]
It would be a great feature to have some kind of media manager where you have an overview of all your taken screenshot.
Because sometimes it becomes handy to see older screenshots, edit them, or send them again (to other recipients).
For sure, you also can handle it via Filemanager... but it would be more compfortable to be able to to all this stuff in flameshot themself.

BTW, thank you for this great Application.

**Comment by mmahmoudian** [comment]
@xstable Although this issue was posted first, but considering the discussion in #2011 I suggest we close this issue in favor of the other one and keep track of this feature request there.
