### ISSUE TITLE
Blur is not sufficient

### ISSUE THREAD

**Issue by madduck** [flameshot-org/flameshot#3323]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian unstable

### Description

When using the blur tool to hide e.g. email addresses or other sensitive information, one has to drag across the area twice, or else the original information is not sufficiently obscured.

Case in point, below is a screenshot of the version info above, where I tried to hide the Debian version in use (just for demonstration).

Please increase the blur amount.

### Steps to reproduce

1. Run GUI
2. Select portion of screen
3. Use blur tool to obscure some text
4. Observe that the text can still be discerned.

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/195073/55730006-a422-4335-be56-8f8a7af2332e)

### System Information

Not that I think this is relevant, but:
Debian unstable, Xorg, dual-monitor using XRandR, AwesomeWM

**Comment by mmahmoudian** [comment]
This is duplicate of multiple other issues. Usually searching among open and closed issues can save your time. 😊


Like any other tool in Flameshot you can"increase the tool size" by scrolling or kust simply typing the number you want. Regarding bluring security issues and how to mitigate it, I have answered this is great details here:

https://github.com/flameshot-org/flameshot/issues/3242#issuecomment-1609122285
