### ISSUE TITLE
randomly cause linux mint to enter black screen

### ISSUE THREAD

**Issue by GopherJ** [flameshot-org/flameshot#3330]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint 21.1

### Description

No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21.1
Release:        21.1
Codename:       vera

### Steps to reproduce

1. run upgrade
2. click flameshot

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/33961674/ecc5bb9f-eac3-4300-b8de-b7c0a3c60c3a)
it also influenced some icons

### System Information

1. Linux Mint 21.1
2. N/A
3. Alacritty as terminal, normal linux mint window manager

**Comment by mmahmoudian** [comment]
The version 11.0.0 id very old. We cannot track bugs for version that old. Please try to use our latest version. If your distro does not provide the latest version of Flameshot, try installing via Flatpak. More information in the following links:

https://flameshot.org/docs/installation/installation-linux/#flatpak

https://flathub.org/apps/org.flameshot.Flameshot
