### ISSUE TITLE
Imgur Client ID Field / Input  is Missing.

### ISSUE THREAD

**Issue by interstate420productions** [flameshot-org/flameshot#3341]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

OS: Linux Mint 21.2 x86_64

### Description

Imgur Client ID Field / Input  is Missing.
![2023-09-19_14-02](https://github.com/flameshot-org/flameshot/assets/24223200/29fa4422-1e40-4be0-b3e3-5c73a32c582f)

### Steps to reproduce

After Registering for a Client ID  and attempting to add client ID only to discover field is missing.

### Screenshots or screen recordings

![Peek 2023-09-19 14-12](https://github.com/flameshot-org/flameshot/assets/24223200/fb3368f9-6a28-4a4a-83cc-29ffa4c52668)

### System Information

alastor@alastor-Dell-G15-5511:~$ inxi --width 80 --system --graphics
System:
  Host: alastor-Dell-G15-5511 Kernel: 5.15.0-84-generic x86_64 bits: 64
    Desktop: Cinnamon 5.8.4 Distro: Linux Mint 21.2 Victoria
Graphics:
  Device-1: Intel TigerLake-H GT1 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 535.86.05
  Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~360Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
    v: 4.6.0 NVIDIA 535.86.05
alastor@alastor-Dell-G15-5511:~$ 
==========
X11
==========
Monitors: 1
 0: +*eDP-1-1 1920/344x1080/193+0+0  eDP-1-1
=========
alastor@alastor-Dell-G15-5511:~$ xrandr | grep -v " disconnected "
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080    360.04*+  60.05 +  60.05  
   1680x1050     60.05  
   1400x1050     60.05  
   1600x900      60.05  
   1280x1024     60.05  
   1400x900      60.05  
   1280x960      60.05  
   1440x810      60.05  
   1368x768      60.05  
   1280x800      60.05  
   1152x864      60.05  
   1280x720      60.05  
   1024x768      60.05  
   1024x768i     60.05  
   960x720       60.05  
   928x696       60.05  
   896x672       60.05  
   1024x576      60.05  
   960x600       60.05  
   832x624       60.05  
   960x540       60.05  
   800x600       60.05  
   840x525       60.05  
   864x486       60.05  
   700x525       60.05  
   800x450       60.05  
   640x512       60.05  
   700x450       60.05  
   640x480       60.05  
   720x405       60.05  
   720x400       60.05  
   684x384       60.05  
   640x400       60.05  
   576x432       60.05  
   640x360       60.05  
   640x350       60.05  
   512x384       60.05  
   512x384i      60.05  
   512x288       60.05  
   416x312       60.05  
   480x270       60.05  
   400x300       60.05  
   432x243       60.05  
   320x240       60.05  
   360x202       60.05  
   360x200       60.05  
   320x200       60.05  
   320x180       60.05  
   320x175       60.05  
=================
00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
00:17.0 SATA controller: Intel Corporation Device 43d3 (rev 11)
01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
2d:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. Device 2600 (rev 21)
===============
alastor@alastor-Dell-G15-5511:~$ sudo lshw -class display
Identified face as alastor
  *-display                 
       description: VGA compatible controller
       product: GA106M [GeForce RTX 3060 Mobile / Max-Q]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=nvidia latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:620-61f irq:165 memory:83000000-83ffffff memory:6000000000-61ffffffff memory:6200000000-6201ffffff ioport:4000(size=128) memory:84080000-840fffff
  *-display
       description: VGA compatible controller
       product: TigerLake-H GT1 [UHD Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: iomemory:620-61f iomemory:400-3ff irq:164 memory:622c000000-622cffffff memory:4000000000-400fffffff ioport:5000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
======================
alastor@alastor-Dell-G15-5511:~$ uname -a
Linux alastor-Dell-G15-5511 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
========================
<details>
<summary>The dbus-monitor content</summary>

```

alastor@alastor-Dell-G15-5511:~$ pkill flameshot
alastor@alastor-Dell-G15-5511:~$ dbus-monitor --session sender=org.flameshot.Flameshot
signal time=1695158484.037973 sender=org.freedesktop.DBus -> destination=:1.189 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.189"
signal time=1695158484.038012 sender=org.freedesktop.DBus -> destination=:1.189 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.189"
method call time=1695158495.314091 sender=:1.190 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1695158495.314121 sender=:1.190 -> destination=org.freedesktop.DBus serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method call time=1695158495.314184 sender=:1.190 -> destination=org.freedesktop.DBus serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1695158495.314218 sender=:1.190 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1695158495.314537 sender=:1.190 -> destination=org.a11y.Bus serial=16 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method call time=1695158495.314975 sender=:1.190 -> destination=org.a11y.Bus serial=17 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "IsEnabled"
method call time=1695158561.678677 sender=:1.190 -> destination=org.freedesktop.Notifications serial=18 path=/org/freedesktop/Notifications; interface=org.freedesktop.DBus.Introspectable; member=Introspect
method call time=1695158561.679658 sender=:1.190 -> destination=org.freedesktop.DBus serial=19 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1695158561.679667 sender=:1.190 -> destination=org.freedesktop.DBus serial=20 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
method call time=1695158561.679898 sender=:1.190 -> destination=org.freedesktop.Notifications serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "flameshot"
   uint32 0
   string "flameshot"
   string "Flameshot Info"
   string "Capture saved to clipboard. Capture saved as /home/alastor/Pictures/2023-09-19_14-22.png"
   array [
   ]
   array [
      dict entry(
         string "x-kde-urls"
         variant             array [
               string "file:///home/alastor/Pictures/2023-09-19_14-22.png"
            ]
      )
   ]
   int32 5000
method call time=1695158561.690118 sender=:1.190 -> destination=org.freedesktop.DBus serial=22 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method return time=1695158561.690760 sender=:1.190 -> destination=:1.193 serial=23 reply_serial=8
^C
alastor@alastor-Dell-G15-5511:~$ 

```

</details>

**Comment by interstate420productions** [comment]
Bump

**Comment by mmahmoudian** [comment]
You are using version v11.0.0 and that feature was not implemented back then. We are on version v12.1.0 . Please consider updating to the latest version. If your Linux distro does not have the latest version in their repository, try installing via Flatpak, Snap, or get AppImage:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

**Comment by interstate420productions** [comment]
Thank you for your Input :)  Much Love.
