### ISSUE TITLE
Please fix f*c**ng hidpi scale on wlroots

### ISSUE THREAD

**Issue by Kamillaova** [flameshot-org/flameshot#3342]
### Flameshot Version

9557cd68ae0cd113b2e617a6f5e1af7288aeec05 with 3165, 3166 pr patches, USE_WAYLAND_GRIM=ON

### Installation Type

Compiled from source

### Operating System type and version

ArchLinux with Nix

### Description

Flameshot crops screenshot from top to 2x (scale is 2x..?) when using HiDPI scale

### Steps to reproduce

run `flameshot gui` with sway scale to 2x

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/54859825/f920ab98-fb4b-4972-8621-6e730e8b4c1e)

### System Information

```hcl
output eDP-1 {
  modeline 500.84  2880 2888 2920 2960  1800 1808 1816 1880 +hsync -vsync
  render_bit_depth 10
  scale 2
  max_render_time 10
  subpixel none
}

for_window [app_id="flameshot"] border pixel 0, floating enable, fullscreen disable, move absolute position 0 0
```

sway stable, wlroots stable (with xwayland hidpi patches)

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let 
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        packages = rec {          
          flameshot = pkgs.flameshot.overrideAttrs (prev: rec {
            version = "9557cd68ae0cd113b2e617a6f5e1af7288aeec05";

            src = pkgs.fetchFromGitHub {
              owner = "flameshot-org";
              repo = "flameshot";
              rev = version;
              sha256 = "sha256-cgpCprl1eichm4Y8jEgMaKbd3cnsk2I57hDyl1mARfI=";
            };

            patches = [ ./3165.patch ./3166.patch ];

            buildInputs = prev.buildInputs ++ (with pkgs; [ grim libsForQt5.kguiaddons ]);

            cmakeFlags = [
              "-DUSE_WAYLAND_GRIM=ON"
              "-DUSE_WAYLAND_CLIPBOARD=ON"
              "-DDISABLE_UPDATE_CHECKER=ON"
            ];
          });

          default = flameshot;
        };
      }
    );
}
```

**Comment by mmahmoudian** [comment]
[RTFM](https://en.m.wikipedia.org/wiki/RTFM) and mind you language next time.

https://flameshot.org/docs/guide/wayland-help/#4k-displayed-and-fractional-scaling

Also we are volunteers here, if it hurt you that much, learn to contribute [with code](https://flameshot.org/#contribute) or [with money and making a code bounty](https://flameshot.org/donate/)
