### ISSUE TITLE
[Debian testing crashed] exec 'flameshot gui' in debian testing distro, crashed by Segmentation Fault

### ISSUE THREAD

**Issue by kean0048** [flameshot-org/flameshot#3367]
### Flameshot Version

Flameshot 12.1.0 and master branch

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian testing

### Description

Installed the Flameshot 12.1.0 in testing version, when I exec 'flameshot gui', output:
**_QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault_**

then I pull the master branch and compile in locally and meet the same issues.
_m75t@debian:~/Downloads$ flameshot gui
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault
m75t@debian:~/Downloads$_

### Steps to reproduce

1. install or compile from source code, v12.1.0 and master branch
2. run 'flameshot gui'
3. crashed -> QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Segmentation fault

### Screenshots or screen recordings

![flameshot-gui](https://github.com/flameshot-org/flameshot/assets/20370671/741f8349-d889-4c3a-9987-66c1c891588b)

### System Information

m75t@debian:~/Downloads$ uname -a
Linux debian 6.4.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) x86_64 GNU/Linux

Monitor:

![monitor](https://github.com/flameshot-org/flameshot/assets/20370671/62bbf752-457b-40ed-a1af-00ea8f1e6fa5)

**Comment by marceldev89** [comment]
I'm seeing the same issue on arch using flameshot-git so I guess it's confirmed now :)

**Comment by marceldev89** [comment]
Figured out while testing different commits that https://github.com/flameshot-org/flameshot/pull/3313 is the issue and they're already aware of it, apparently. 😛

**Comment by kean0048** [comment]
@marceldev89,

Thanks for your update.
It works on my platform, that's fine.
Kean.
