### ISSUE TITLE
Failed to register AppImage in system via libappimage

### ISSUE THREAD

**Issue by alexandrul** [flameshot-org/flameshot#3382]
### Flameshot Version

Flameshot 12.1.0 (10ab227368a704f2d66cded7a7aa8248)

### Installation Type

AppImage

### Operating System type and version

Linux Mint 21.2 Victoria

### Description

Using AppImageLauncher:
- 12.1.0 throws the `Failed to register AppImage in system via libappimage` error when choosing "Integrate and run"
- 11.0.0 works as expected

### Steps to reproduce

1. Double click on `Flameshot-12.1.0.x86_64.AppImage`
2. Choose "Integrate and run" from the AppImageLauncher dialog

### System Information

1. Linux Mint 21.2 x86_64 (Victoria)
2. Dual monitor: left landscape (1920x1080), right portrait (1080x1920)
3. Desktop Environment: Cinnamon 5.8.4, Window Manager: Mutter (Muffin), Xorg

**Comment by alexandrul** [comment]
```
❯ ./appimagetool-x86_64.AppImage --list Flameshot-12.1.0.x86_64.AppImage                               
appimagetool, continuous build (commit 5735cc5), build <local dev build> built on 2023-03-08 22:52:04 UTC
Squashfs image uses (null) compression, this version supports only xz, zlib.
sqfs_open_image error
```

**Comment by alexandrul** [comment]
After deleting the `.AppImage` extension the app can be started and it works as expected.

```
Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.12.8
linux: 6.2.0-34-generic
linuxmint: 21.2
```

**Comment by mmahmoudian** [comment]
Aaah, classic AppImageLauncher.

Please report this to maintainers of AppImageLauncher as this is clearly their issue.

You don't need such a software to manage your AppImages. The AppImage format is fully self contained. Just run the app (e.g double click, from terminal, ...) . If you need a .desktop file, copy it from another software and edit the file to run your AppImages.
