### ISSUE TITLE
Flameshot not working properly in GNOME 45

### ISSUE THREAD

**Issue by archthegreat** [flameshot-org/flameshot#3403]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8
linux: 6.5.0-10-generic
ubuntu: 23.10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 23.10 

### Description

After updating Ubuntu 23.04 to 23.10 which ships with GNOME 45, Flameshot has started behaving erratically. I've got `Super` + `F` as the shortcut for `flameshot gui`, but when I press the keys, Flameshot sends a notification telling that it's unable to capture the screen. When I click on the 'Take Screenshot' option in the drop-down menu of the tray icon, the same thing happens.
 
However, if I open a Terminal window and type `flameshot gui` the screenshot is taken. I don't quite understand why it's happening, but I'm pretty sure it's started happening since I updated to Ubuntu 23.10.

### Steps to reproduce

**Ensure you're on GNOME 45, preferably on Ubuntu 23.10**
(1) Click on the `Super` key
(2) Type 'Flameshot'
(3) Select the Flameshot app
(Wait for the tray icon to appear)
(4) Click on the tray icon
(A drop-down menu appears)
(5) Click on the 'Take Screenshot' option
(Wait for a couple of seconds)
You'll see a notification from Flameshot titled 'Unable to capture screen'

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/113207560/d437d459-635a-4670-9032-cc28f5604f28)

### System Information

(1) Ubuntu 23.10
(2) 
![image](https://github.com/flameshot-org/flameshot/assets/113207560/898dce9f-6647-4da4-8bc2-4575f535f8f7)
(3) - GNOME 45
     - Wayland

**Comment by maptile** [comment]
I have exactly the same problem.

OS: Ubuntu 23.10
Desktop: Gnome 45 Wayland
Flameshot version: v12.1.0

Additional details:
On Ubuntu 23.04, which used Wayland and an unspecified version of GNOME, Flameshot failed to operate properly when installed via the apt command. Interestingly, the AppImage version of Flameshot did function correctly, despite being the same version as the apt install.

Following an upgrade to Ubuntu 23.10, featuring Wayland and GNOME 45, both installation methods ceased to work.

Currently, a temporary solution is to launch Flameshot directly from the terminal, which remains effective.

**Comment by Trogie** [comment]
Same problem after upgrading Ubuntu Desktop from 23.04 to 23.10: no more working flameshot anymore.

**Comment by marcosjoao37** [comment]
Same problem for me after upgrading from Fedora 38 to Fedora 39, which uses Gnome 45.

**Comment by mmahmoudian** [comment]
This seems to be duplicate of #3383 and the solution to this round of Gnome's behavior is here:

https://github.com/flameshot-org/flameshot/issues/3383#issuecomment-1789630803

**Comment by theuargb** [comment]
@mmahmoudian  I`m still getting the same error on the latest Fedora 39 Gnome 45 Wayland. Either shortcut is set to run `flameshot gui` or `/bin/sh -c '/usr/bin/flameshot gui'`

**Comment by gutopardini** [comment]
If you're still using GNOME + Wayland and struggling with Flameshot/XWayland issues, take a look at my project:

https://github.com/gutopardini/wayshot

WayShot uses the native GNOME screenshot tool under Wayland and automatically opens a modern annotation editor afterwards (arrows, text, blur, shapes, etc).

The goal is to provide a more native and reliable screenshot workflow for GNOME Wayland users.
