### ISSUE TITLE
Latest macOS build is not being signed

### ISSUE THREAD

**Issue by Andreybest** [flameshot-org/flameshot#3404]
### Flameshot Version

Flameshot v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS 14.1

### Description

After installation macOS does not allow to open neither brew cask nor app from dmg.
Getting: "Cannot Be Opened Because the Developer Cannot be Verified". And I guess this build shows that it is still persists: https://github.com/flameshot-org/flameshot/actions/runs/6683449351/job/18159677958#step:7:19

### Steps to reproduce

Download flameshot via brew or dmg

### System Information

macOS 14.1

**Comment by mmahmoudian** [comment]
It was never signed. Signing means we have to pay some good chunk of money to Apple and Microsoft. Flameshot is free, plus we don't accept donations, and all the work is volunteer work. Already some costs are on own pockets (e.g domain), and paying more, especially to a mega corp just for signing package is not justifiable.
