### ISSUE TITLE
Flameshot froze after copying(CTRL+C & copy button) screenshot

### ISSUE THREAD

**Issue by Dellrall** [flameshot-org/flameshot#3409]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 6.5.9-1-default
org.kde.Platform: 5.15-21.08
Compiled with Qt version: 5.15.5

### Installation Type

Flatpak from Flathub

### Operating System type and version

openSUSE Tumbleweed 20231108

### Description

Copying screenshot would froze up the application upto a few seconds and then works again but didnt even copying to the clipboard. 

I have tried different troubleshooting step(from site guide & clean install), including having using .AppImage.

Issue is similar to #3300 #3107, but in this scenario the prompt for successful copy to clipboard isnt showing at all.

### Steps to reproduce

1. run 'flameshot gui' or click on flameshot tray icon
2. click and drag screenshot area
3. Ctrl+C or click copy button.
4. Observe issue(clicking the tray icon or launching the configuration tool)

### Screenshots or screen recordings

A recording of issue reproduce:
I press ctrl+C, and I didnt perform anything afterward.
https://github.com/flameshot-org/flameshot/assets/74344714/50148217-106d-4898-a76a-23a30b9821a1

### System Information

Desktop environment: KDE Plasma Version: 5.27.9
Display server: Xorg

**Comment by mmahmoudian** [comment]
Can you try running the Damon first (e.g by opening if from Plasma menu, or buy running `flameshot` in terminal), and then vlick on the tray icon and see if the copy works this time

**Comment by Dellrall** [comment]
Nvm I found the trigger for this problem, I disabled the notification on my system tray which caused this problem.

Once I enabled it, it works again, thanks for the reminder tho, and also for the development of this amazing application

**Comment by mmahmoudian** [comment]
@Dellrall this is interesting, because this issue was supposed to be fixed already (I don't remember in which commit it was fix though, might have been after the release of 12.1.0).

It have been some years since I last used OpenSuse, but in case you feel comfortable with compiling, I suggest to you to use the latest commit and build Flameshot (would take about 20 seconds using 16 CPU cores).
