### ISSUE TITLE
Flameshot doesn't work on Waland: Sway Hyprland River

### ISSUE THREAD

**Issue by TAforever** [flameshot-org/flameshot#3413]
### Flameshot Version

12.1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

archlinux

### Description

I was away for a month and when I updated the system flameshot stopped working. Previously it worked great on both river and hyprland with xdg-desktop portal xdg-desktop-portal-gtk xdg-desktop-portal-wlr installed and the environment variable XDG_CURRENT_DESKTOP=sway set.

### System Information

archlinux

**Comment by TAforever** [comment]
I found that the reason is the xdg-desktop-portal update

**Comment by TAforever** [comment]
Just in case, I’ll open an issue again because I don’t know who should do the work, you or xdg-desktop-portal

**Comment by TAforever** [comment]
I just installed flameshot-git and everything works. Thank you for such a good program!

**Comment by cvoges12** [comment]
#3674 Might be related.
