### ISSUE TITLE
Is there a keyboard shortcut for pinning images to the desktop?"

### ISSUE THREAD

**Issue by hedachun321** [flameshot-org/flameshot#3435]
### Feature Description

I know there is a shortcut for taking screenshots, but I haven't found a shortcut for pinning them to the desktop. If there is one, could you please let me know? If not, I would really look forward to this feature, as I find it very convenient.As shown in the picture, the feature located at the mouse cursor.
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg  MsgID=5947505255171111211 skey=@crypt_1323e01c_6bed8e3fb48e398e0ef7312280d4806c mmweb_appid=wx_webfilehelper](https://github.com/flameshot-org/flameshot/assets/62691883/a5d7566e-2331-4404-b656-b182dc98c00a)

**Comment by mmahmoudian** [comment]
It has. Right click on the tray icon, from the menu select Configurations, and there you can find all shortcuts and even modify them.

**Comment by mmahmoudian** [comment]
Well, your version is about 6 years old I guess. The latest version is 12.1.0
If your Ubuntu is that old, I suggest you to install Flameshot via one of the distro agnostic method such as Flatpak. More information here:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

**Comment by hedachun321** [comment]
> 嗯，我猜你的版本已经有 6 年了。最新版本是 12.1.0 如果您的 Ubuntu 太旧，我建议您通过一种与发行版无关的方法（例如 Flatpak）安装 Flameshot。更多信息请点击这里：
> 
> https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

Thank you for your response. I understand now.
