### ISSUE TITLE
 Software update issues 

### ISSUE THREAD

**Issue by SA-GIMA** [flameshot-org/flameshot#3481]
### Feature Description

 My current computer system is Ubuntu 18.04 and the installed version is v11.0.0. I have seen updated software, but I am not sure if my system supports installing v12.0.0 or higher

**Comment by mmahmoudian** [comment]
We do not manage Flameshot on Ubuntu. You have few options:
1. Migrate to a newer Ubuntu (in fee months we will have 24.4 out)
2. Use Flatpak or AppImage. Instructions can be found in: https://flameshot.org/docs/installation/installation-linux/#distro-agnostic  this would take you about 2 minutes.
