### ISSUE TITLE
Upload screenshot stop works

### ISSUE THREAD

**Issue by Slach** [flameshot-org/flameshot#3484]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19042
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

windows 10

### Description

Looks like API imgur broken or reject our application id?
Upload screenshot now return 
```
Error transferring https://api.imgur.com/3/image?title=&description=2024-01-31_18-18 - server replied: Unknown Error
```

### Steps to reproduce

run flameshot.exe
press print screen
press "upload screenshot"

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/105560/2983b21e-fa39-41f7-92a4-54cd19b87902)

### System Information

Windows 10 22H2

**Comment by mmahmoudian** [comment]
Thanks for reporting, but that is unlikely to be the cause. Please have a look at out our documentation:

https://flameshot.org/docs/guide/imgur-help/

If the issue was resolved by following the documentation, please close this issue. Thank you.

**Comment by Slach** [comment]
Issue resolved itself, looks like it was API error on IMGUR side
