### ISSUE TITLE
Can't capture screen under Wayland on KDE Plasma 6 RC 2

### ISSUE THREAD

**Issue by Troplo** [flameshot-org/flameshot#3489]
### Flameshot Version

Flameshot v12.1.0 (b61b0472)

### Installation Type

Compiled from source

### Operating System type and version

Arch Linux, Linux 6.7.4, Wayland, KDE Plasma 5.93.0, AMDgpu

### Description

On KDE Plasma 6, the following gets output when running `flameshot gui`
```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
```

Downgrading to KDE Plasma 5 resolves the problem. I have xdg-desktop-portal and xdg-desktop-portal-kde and OBS, Spectacle work just fine, it's just Flameshot which doesn't work.

### Steps to reproduce

1. run `flameshot gui` under KDE Plasma 6 RC 2.
2. see error

### System Information

Arch Linux, Linux 6.7.4, Wayland, KDE Plasma 5.93.0, AMDgpu

**Comment by ranjithsiji** [comment]
I got the same bug on Fedora 39, KDE Plasma 6 RC 2. 

` alpha39@fedora$ flameshot gui                                          
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
`

**Comment by poltpolt** [comment]
I have the same on Plasma 6 final release, Opensuse Tumbleweed

**Comment by YukiAlmasy** [comment]
I am having a similar issues on KDE Neon 6.0 user edition in OBS

**Comment by AlekEagle** [comment]
I only get the single line:
```sh
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
before locking up. I can kill the process with CTRL+C, but no screenshot.

A temporary workaround for flameshot at least is to make it believe it is running under sway with `XDG_CURRENT_DESKTOP=sway flameshot gui`. The GUI will be displayed and it appears to function properly.

**Comment by Troplo** [comment]
Strangely, after upgrading on Arch from Plasma 6 RC 2 to the final 6.0.0 release in `extra-testing` / `kde-unstable`, it just works for me on both of my computers.

**Comment by AlekEagle** [comment]
i updated my flameshot and it worked

**Comment by Lampe2020** [comment]
> Strangely, after upgrading on Arch from Plasma 6 RC 2 to the final 6.0.0 release in `extra-testing` / `kde-unstable`, it just works for me on both of my computers.

I'm on Neon 6.1 and I cannot screencapture in any application. Discord, Vesktop, WebCord, Firefox, OBS, all don't get any screen input. But a red dot appears in the system tray, which doesn't disappear when I exit the application from which I requested .
