### ISSUE TITLE
2 errors when running flameshot gui and flameshot screen

### ISSUE THREAD

**Issue by ukcai696969** [flameshot-org/flameshot#3499]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Flameshot v12.1.0 (Debian 12.1.0-2) Compiled with Qt 5.15.8

### Description

when running both flameshot gui and flameshot gui this error happens:

```console
ukcai6969@penguin:~$ flameshot screen
flameshot: error: Unable to detect desktop environment (GNOME? KDE? Sway? ...)
flameshot: error: Hint: try setting the XDG_CURRENT_DESKTOP environment variable.
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.
```

```console
ukcai6969@penguin:~$ flameshot gui
flameshot: error: Unable to detect desktop environment (GNOME? KDE? Sway? ...)
flameshot: error: Hint: try setting the XDG_CURRENT_DESKTOP environment variable.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.
```

### Steps to reproduce

1.run flameshot gui or flameshot screen

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/111254389/2e49fae1-d46d-4b14-b1b8-d90f8a85a7e7)

### System Information

debian

**Comment by ukcai696969** [comment]
flameshot config loads then config menu

**Comment by mmahmoudian** [comment]
As you can see, it is failing to detect your Desktop Environment. Also, in the bug report form we explicitly asked you to provide your Desktop Environment and your Display server protocol.

Please provide these information. This vug report in this current state is invalid as it lacks essential information. Thank you.

P.s: I also edited your post as you forgot to add markdown code fences around the output.

**Comment by ukcai696969** [comment]
the command: xrandr --listactivemonitors
![image](https://github.com/flameshot-org/flameshot/assets/111254389/b49c7bba-2d07-443e-8ead-f8c9f6d82144)

**Comment by ukcai696969** [comment]
@mmahmoudian

**Comment by mmahmoudian** [comment]
@ukcai696969 This is weird. Why your monitor says xwayland? Why that weird resolution? Are you using VNC or some other remote desktop?

Also, you still didn't provide your Desktop Environment.

If you really don't know how, just install `inxi` (probably something like `apt install inxi`) and then run:

```sh
inxi --system --graphics --width 80
```

and copy-paste the output here.

This will collect your "system" and "graphics" information that we need.

**Comment by mmahmoudian** [comment]
I'm sorry to bring it up to you, but you are not using Linux. You are using ChromeOS with a virtual Linux. This means practically you are not using GNU/Linux as your main OS:

https://support.google.com/chromebook/answer/9145439?hl=en

As far as I understand, you cannot use Flameshot or any other screenshot tools from a virtualized guest OS to access the host display.

I close this issue as it cannot and will not be "fixed".

**Comment by ukcai696969** [comment]
okay thanks

**Comment by mmahmoudian** [comment]
Just to clarify more, you have ChromeOS and inside that you have virtualized a Debian. But that Debian doesn't have it's own monitor or display, and even it is not showing anything (because you are not running a graphical software in it). Your Flameshot is sitting inside this virtual environment. Then you have your browser or Discord in your ChromeOS.

So Flameshot that is inside that machine has no way to escape the virtualized environment and take a photo of the software that is on your ChromeOS. So unless ChromeOS provides your monitor output to the virtual environment).

If you want to use Flameshot, you should have Linux, MacOS, Windows, or BSD installed on your machine. But I don't know if ChromeBook allows you to change the Operating System ti something else.

Perhaps you should ask in ChromeBook forums and see what others have done.

Good luck

**Comment by ukcai696969** [comment]
@mmahmoudian thanks, i can install .deb files i know that probs isn’t helpful but is there a way to install flameshot by a .deb?

**Comment by mmahmoudian** [comment]
You can download the deb file from this link

https://github.com/flameshot-org/flameshot/releases

But remember that tour issue is that **you are not running Debian** natively. You are virtualizing Debian on ChromeOS which does not have access to your ChromeOS monitor.

**Comment by kaushiksahu18** [comment]
## having same issue in hyprland
```bash
$ export XDG_CURRENT_DESKTOP=Hyprland
$ flameshot gui
flameshot: error: Unable to detect desktop environment (GNOME? KDE? Sway? ...)
flameshot: error: Hint: try setting the XDG_CURRENT_DESKTOP environment variable.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
```

**Comment by jalovisko** [comment]
> ## having same issue in hyprland
> 
> $ export XDG_CURRENT_DESKTOP=Hyprland
> $ flameshot gui
> flameshot: error: Unable to detect desktop environment (GNOME? KDE? Sway? ...)
> flameshot: error: Hint: try setting the XDG_CURRENT_DESKTOP environment variable.
> flameshot: error: Unable to capture screen
> flameshot: error: Unable to capture screen
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> flameshot: info: Screenshot aborted.

`Hyprland` is not a valid option, you can try `Sway`, should work on Hyprland too.
