### ISSUE TITLE
Flameshot not taking screenshot on active display

### ISSUE THREAD

**Issue by penalvch** [flameshot-org/flameshot#3511]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 23.3.0
osx: 14.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS Sonoma 14.3.1 M1

### Description

What is expected to happen with Flameshot, is when one has external displays via DisplayLink software enabled device (e.g. KVM, Port Replicator, etc.) when an external display has the mouse cursor and window active, when one initiates screenshot via:
1. Keyboard shortcut Shift+Command+X
2. Mouse clicks Flameshot tray icon in the active display > Take Screenshot

Flameshot GUI shows up indicating a screenshot is being taken on the active display.

What happens instead is that it is taking a screenshot of only the built-in display.

This has been reproducible with multiple:
1. versions of DisplayLink software (1.9, 1.10),
2. external DisplayLink based devices (Anker 563, VisionTek VT4950),
3. external monitor MFGs,
4. versions of macOS (13.5 through 14.3.1),
5. Mac devices (MBA M1, MBP M2)

TEMPORARY WORKAROUND: Exit Flameshot. Relaunch the application and then immediately attempt to take a screenshot with the external display active and mouse cursor. However, this inevitably returns to prior noted behavior.

### Steps to reproduce

Above

### System Information

1. Above
2. 
![image](https://github.com/flameshot-org/flameshot/assets/115644052/db3fd651-91b1-47cc-93ad-c8f91f38cf36)
![image](https://github.com/flameshot-org/flameshot/assets/115644052/a912a5d5-bdb3-4262-96b9-b03c370e6320)
3. N/A

**Comment by tpcgold** [comment]
Seems to be the same issue:
https://github.com/flameshot-org/flameshot/issues/3505

**Comment by penalvch** [comment]
@tpcgold thanks for taking a look! Appears to be same as #3505. If this can be marked a duplicate of, I'm ok with it.

**Comment by penalvch** [comment]
@mmahmoudian no updates have been made to Flameshot, this is actively reproducible, but this was closed. What fix precisely was released in scope of this?

**Comment by mmahmoudian** [comment]
@penalvch it was marked as duplicate and then it was closed.

As kindly and correctly mentioned by @tpcgold , this issue is duplicate of #3505.
