### ISSUE TITLE
Flameshot aborts on "rectangle -> text -> rectangle"

### ISSUE THREAD

**Issue by PatrickRoesler** [flameshot-org/flameshot#3515]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint 21 Cinnamon

### Description

Flameshot aborts when clicking on rectangle after drawing rectangle and text.

### Steps to reproduce

1. run 'flameshot gui'
2. Select some screen selection (it does not mind if small area, big area or full screen)
3. Select rectangle tool
4. Draw a rectangle
5. Select text tool
6. Click somewhere in the selected area
7. Hit some keys to write anything
8. Click somewhere in the selected area to leave text input field
9. Try to select rectangle tool <- this fails. Notification says "Flameshot Info - Screenshot aborted"

### Screenshots or screen recordings

![peekFlameshot](https://github.com/flameshot-org/flameshot/assets/61048262/dcbb1a06-e7cc-4f52-b13a-f2aee05340ab)

### System Information

![grafik](https://github.com/flameshot-org/flameshot/assets/61048262/4bec5eee-4bc5-4a01-8eef-119f670fa32f)

---

inxi --width 80 --system --graphics
System:
  Host: ... Kernel: 5.15.0-91-generic x86_64 bits: 64
    Desktop: Cinnamon 5.4.12 Distro: Linux Mint 21 Vanessa
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera (1280x720@30) type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon Vega 10 Graphics (raven LLVM 15.0.7 DRM 3.42
  5.15.0-91-generic)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1

**Comment by israelyago** [comment]
Can confirm the bug occurs.

Note however, that the bug seems to happen every time you "Select the text tool" -> "Other tool", with some exceptions like the save button

**Comment by PatrickRoesler** [comment]
> ...with some exceptions like the save button

That's right.

Rectangle -> Text -> Save Button

This combination works for me, too.

**Comment by mmahmoudian** [comment]
This have been fix about a year back. Please update to the latest version. If your distro does not have the latest version, try installing via Flatpak or use AppImage:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic



or download deb file from our nightly builds:

https://flameshot.org/docs/installation/development-build/
