### ISSUE TITLE
Allow windows version to change the screenshot hotkey

### ISSUE THREAD

**Issue by LuigiBrito** [flameshot-org/flameshot#3536]
### Feature Description

The 'Capture Screen` hotkey right now is greyed out to PrntScrn button in the Windows version. This conflicts with the native solution and one or the other activates making it inconsistent. 

Allow users to change this hotkey to something else like Ctrl+Shift+S

**Comment by mmahmoudian** [comment]
Thanks for filing this feature request, but there is already an open issue for this. Please consider searching in open and closed issues before creating a new one. This would first and foremost save your own time. Thanks.
