### ISSUE TITLE
Undo/Redo does not work on a scaled screen

### ISSUE THREAD

**Issue by mrousavy** [flameshot-org/flameshot#355]
**Flameshot version**
`0.6.0-2(Debian)`

**Describe the bug**
When using a custom scaling factor in KDE display settings, the undo and redo actions do not work because they replace the modified area with a screen capture of the pixel value, not including the scaling factor.

**To Reproduce**
1. Enable scaling in KDE display settings
2. Do anything in a captured area
3. Press undo/redo

**Expected behavior**
Flameshot should correctly undo/redo the action, replacing with a screengrab of what was under the modified area before.

**System Information**
```
       _,met$$$$$gg.          mrousavy@xps-15 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux unstable (sid) x86_64 
 ,$$P'              `$$$.     Model: XPS 15 9560 
',$$P       ,ggs.     `$$b:   Kernel: 4.9.0-4-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 40 minutes 
 $$P      d$'     ,    $$P    Packages: 3099 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.6.2 
 $$;      Y$b._   _,d$P'      Resolution: 3840x2160 
 Y$$.    `.`"Y$$$$P"'         DE: KDE 
 `$$b      "-.__              WM: KWin 
  `Y$$                        WM Theme: Arc 
   `Y$$.                      Theme: Arc Dark [KDE], Arc [GTK2/3] 
     `$$b.                    Icons: Papirus-Light [KDE], Papirus [GTK2/3] 
       `Y$$b.                 Terminal: konsole 
          `"Y$b._             Terminal Font: Hack 11 
              `"""            CPU: Intel i7-7700HQ (8) @ 3.800GHz 
                              GPU: Intel Device 591b 
                              Memory: 2666MiB / 32029MiB
```
> System Settings > Display and Monitor > Displays > Scale Display > Scaling set to `1.5`

**Comment by hexchain** [comment]
I have this problem too, on the current master 94daa4f, Arch Linux.

Plasma scaling sets `QT_AUTO_SCREEN_SCALE_FACTOR` to 0 and `QT_SCREEN_SCALE_FACTORS` to the scale factor set by user:

```
~ $ echo $QT_AUTO_SCREEN_SCALE_FACTOR 
0
~ $ echo $QT_SCREEN_SCALE_FACTORS 
eDP-1=2;DP-1=2;DP-2=2;
```

Also the icons look pixelated when running with these two variables:
![image](https://user-images.githubusercontent.com/529520/48980476-c8a2b800-f0c9-11e8-9328-8f12007cbe37.png)

To compare, here is a screenshot when running without the two variables:
![image](https://user-images.githubusercontent.com/529520/48980481-de17e200-f0c9-11e8-969a-50ab24ff91c6.png)

**Comment by RigoLigoRLC** [comment]
Same here, confirmed on Manjaro KDE 18.1.5, with 120% scaling factor. I hope it will be fixed soon cuz it's already been more than a year and this annoying issue still persists.

**Comment by matheusfillipe** [comment]
Confirmed on Arch Linux x86_64 KDE 5.20.2. I have a lot of scaling so I didn't even understand this was the issue at first. 
![image](https://user-images.githubusercontent.com/24435787/99162011-16f65a80-26d7-11eb-91ba-373ca79a1c21.png) 

![image](https://user-images.githubusercontent.com/24435787/99162009-1362d380-26d7-11eb-9088-1055cba62d7f.png)

**Comment by All3xJ** [comment]
still an issue. very bad bug :( basically undo/redo ruins the screenshot and you have to take the screenshot again.
Manjaro KDE 5.21.2 with 125% scaling factor.
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Comment by borgmanJeremy** [comment]
I think this is resolved now if someone is willing to test (build from master branch).

**Comment by matheusfillipe** [comment]
@borgmanJeremy  Working for me!!! Really great job!  Thanks.
 
![Peek 2021-05-14 15-43](https://user-images.githubusercontent.com/24435787/118314999-4d1c6780-b4cb-11eb-9ba2-863e1ad72899.gif)

**Comment by borgmanJeremy** [comment]
Awesome thanks for reporting back. We will put out a beta release this weekend and an official release next week.
