### ISSUE TITLE
Copy to clipboard not working on Wayland

### ISSUE THREAD

**Issue by GARN3K** [flameshot-org/flameshot#3556]
### Flameshot Version

Flameshot v12.1.0 
Compiled with Qt 5.15.10
### Installation Type

Archlinux offical package
### Operating System type and version

Archlinux, Kernel: 6.8.1-arch1-1 
### Description

After taking the screenshot both:
* 'ctrl + c' 
* 'Copy selection to clipboard' 

Do not work. I receive a notification 'Capture saved to clipboard' but it doesn't get saved. **Saving to a file works fine**.

After starting flameshot from terminal with 'flameshot gui' after clicking copy to clipboard nothing happens, but when saving to a file we get 'flameshot: info: Capture saved as /home/garn3k/Pictures/2024-04-03_11-27_1.png'. 

Tried the AUR package 'flameshot-git' but it didn't solve the problem. Using *'flameshot gui --raw|wl-copy'* works but doesn't provide the whole feature set. 

Issue previously mentioned in [2848](https://github.com/flameshot-org/flameshot/issues/2848). [3501](https://github.com/flameshot-org/flameshot/issues/3501), [3551](https://github.com/flameshot-org/flameshot/issues/3551), and in Wiki issue [144](https://github.com/flameshot-org/flameshot-org.github.io/issues/144)
### Steps to reproduce

As in description.
### System Information

Operating System: Archlinux 6.8.1
Sway version: 1.9
Wl-clipboard version: 1:2.2.1-1
xdg-desktop-portal version: 1.18.2-1
Kernel Version: 6.8.1-arch1-1

**Comment by shinysquirrel04** [comment]
duplicate of what can you tell us?
