### ISSUE TITLE
Imgur upload and Settings Configuration

### ISSUE THREAD

**Issue by seal308** [flameshot-org/flameshot#3558]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.5.0-26-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Lubuntu 22.04.4 LTS x86_64 

### Description

I get this error: Error transferring https://api.imgur.com/3/image?title=&description=2024-04-06_09-02 - server replied: Too Many Requests

In FAQ for imgur it mentions to add your own imgur client ID to the flameshot settings.
In the FAQ it shows this:

![client faq](https://flameshot.org/media/content/docs/guide/imgur_help/2022-07-27_20-37_create_client_id_03.png)

But on my flameshot version I only see a config file option:

![configfile](https://github.com/flameshot-org/flameshot/assets/6391773/16bb084e-43b0-4e89-b8b0-18c35833c094)

### Steps to reproduce

1. run flameshot
2. select upload button

### System Information

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
x11
Monitors: 1
 0: +*eDP-1 1440/286x900/179+0+0  eDP-1
Screen 0: minimum 320 x 200, current 1440 x 900, maximum 8192 x 8192
eDP-1 connected primary 1440x900+0+0 (normal left inverted right x axis y axis) 286mm x 179mm
   1440x900      59.84*+
   1400x900      59.84  
   1440x810      59.84  
   1368x768      59.84  
   1280x800      59.84  
   1280x720      59.84  
   1024x768      59.84  
   960x720       59.84  
   928x696       59.84  
   896x672       59.84  
   1024x576      59.84  
   960x600       59.84  
   960x540       59.84  
   800x600       59.84  
   840x525       59.84  
   864x486       59.84  
   700x525       59.84  
   800x450       59.84  
   640x512       59.84  
   700x450       59.84  
   640x480       59.84  
   720x405       59.84  
   684x384       59.84  
   640x360       59.84  
   512x384       59.84  
   512x288       59.84  
   480x270       59.84  
   400x300       59.84  
   432x243       59.84  
   320x240       59.84  
   360x202       59.84  
   320x180       59.84  
/usr/share/misc/pci.ids is read-only, exiting.
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

**Comment by impressivewebs** [comment]
I think you need to download the latest version. I just upgraded from version 9 to version 12.1.0 of Flameshot, and it shows the field for the Application Client ID for Imgur.

**Comment by seal308** [comment]
Thanks that worked!

**Comment by impressivewebs** [comment]
No problem. You should probably close this thread so they don't think it's an actual bug.
