### ISSUE TITLE
[Feature Request] Run script on save

### ISSUE THREAD

**Issue by ronjouch** [flameshot-org/flameshot#357]
I like to pass my screenshots through [pngquant](https://pngquant.org/), for excellent lossy-but-I-don't-care-for-screenshots compression.

I do this manually each time, but it would be great if Flameshot had a `Run script on save` option.

- It would require configuration of a path to a script/binary.
- After screenshot save, if configured and if the path provided exists and is executable, the script/binary would be called with the full path passed as argument.

**Comment by lupoDharkael** [comment]
why don't you configure an alias or shortcut to do that?

**Comment by ronjouch** [comment]
@lupoDharkael thanks for the fast feedback 🙂.

I wanted to like `flameshot gui -r`, but it's annoying: it will result in *two* pngs being written 😕.

**Comment by lupoDharkael** [comment]
You are right, I guess it would be a good idea to have optional scripts called after the capture is done (and passing the path of the image to the script as an argument)

**Comment by drm86** [comment]
This could be a nice feature, for now I have to use a crappy shell script to do things like upload the result screenshot to other service different than imgur (like ptpb.pw). This is what I'm using now and this script is binded to Print Screen key:
```bash
#!/bin/bash

PATH_IMG=/tmp/$RANDOM$RANDOM$RANDOM

mkdir $PATH_IMG &&

RESULT_CAP=$(flameshot gui -p $PATH_IMG -r > $PATH_IMG/img.png && head -n 1 $PATH_IMG/img.png)

if [[ $RESULT_CAP != "screenshot aborted" ]] ; then
    
    RESULT_CURL=$(curl -F c=@$PATH_IMG/img.png https://ptpb.pw/?u=1)
    echo $RESULT_CURL | xclip -i -rmlastnl -selection clipboard
    notify-send "Captura subida a: "$RESULT_CURL "El enlace copiado en el portapapeles" -u normal -t 7500 -i clipboard
fi

rm -rf $PATH_IMG;
```
Other problem with scripting is there's no Exit Codes present in this application, so the only way I can manage is reading the first line of the raw output file.

Thanks.

**Comment by chelobaka** [comment]
I'm looking for a program to replace outdated and broken Shutter, and Flameshot could be my choice if it could pass a screenshot to a custom script. (I need to upload images over WebDAV and copy URLs to clipboard.)

UI part of this feature could be done like this:
1. In the settings user adds a script, gives it a name. Several scripts can be added.
2. In screenshot window for each user script extra button is created with script name shown, when cursor is over the button.

**Comment by ronjouch** [comment]
I gave up on Flameshot and other do-it-all screenshot tools. No harsh feelings on Flameshot at all, at the end of the day I think it's just too much to ask to a single free app. I prefer to delegate [screenshot, edition, automation] to dedicated tools, tied together by a customizable script. Here's my current script that:

1. Makes a screenshot, using the minimal `gnome-screenshot` (but replace with whatever you like).
2. Optionally passes it to Inkscape.
3. Runs pngquant on it.
4. Saves for archival in a dedicated folder.

```sh
#!/usr/bin/env sh

date=$(date +%Y-%m-%d-%H:%M:%S)
filename="screenshot_$date.png"
file_orig="/tmp/${filename}"

gnome-screenshot --area --include-pointer --file="$file_orig"
if [ ! -f "$file_orig" ]; then exit 1; fi

title="$(zenity --entry --title='Screenshot' --text='Optionally name the screenshot (start with "i " to edit in Inkscape):' --ok-label='Save screenshot')"
if [ $? -ne 0 ]; then exit 1; fi

if [ "${title#i }" != "${title}" ]; then
  inkscape "$file_orig"
  title="${title#i }"
fi

folder="$(xdg-user-dir 'PICTURES')/Screenshots"
if [ ! -d "folder" ]; then
  mkdir -p "$folder"
fi

if command -v pngquant > /dev/null; then
  if [ -n "$title" ]; then
    middle="_${title}_"
  else
    middle="_"
  fi

  file="${folder}/screenshot${middle}${date}.png"
  pngquant --strip --force --output "$file" "$file_orig"
  # zopfli too slow, disabled but enable it if you want to shave even more bits from your PNGs
  # if command -v zopflipng > /dev/null; then zopflipng -y "$file" "$file"; fi
else
  zenity --warning --text='Please install pngquant'
fi
rm "$file_orig"

nautilus "$folder"
```

I bind this to <kbd>PrtScr</kbd> using GNOME Shell's native keybinding mechanism. ❤ ensues. Improvements welcome!

**Comment by vyachkonovalov** [comment]
@drm86
> ```shell
> PATH_IMG=/tmp/$RANDOM$RANDOM$RANDOM
> ```

can be replaced with  

```shell
PATH_IMG=`mktemp -dqp /tmp flameshot-XXXXXX`
```

**Comment by kaihendry** [comment]
Here is how I script flameshot:

* https://github.com/kaihendry/dotfiles/blob/master/bin/fscreenshot with [dmenu](https://tools.suckless.org/dmenu/)
* https://github.com/kaihendry/dotfiles/blob/master/bin/upload does the pngquant stuff

**Comment by borgmanJeremy** [comment]
Also flameshot supports outputing the raw image with the '-r' flag. This allows for easy scripting.

**Comment by gunqqer** [comment]
Why what this issue closed?
If I could have this (or some way of scripting with flameshot) that would make my life easier. Also, while the raw output may be userful, with how aborting works (writing the errors to the .png) using raw output is incredibly unreliable without writing a fair bit of script to check the picture.

**Comment by borgmanJeremy** [comment]
I closed it because I don't plan to add or merge this feature. While it is cumbersome it can be achieved with either the raw option, or dbus calls to save the image.

We also have the open in external app option so you could hook a script into that.
