### ISSUE TITLE
Magnifier is useless on OSX

### ISSUE THREAD

**Issue by Rigido71** [flameshot-org/flameshot#3599]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 23.5.0
osx: 14.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS Sonoma Versione Beta di 14.5 (23F5074a)

### Description

Using FS GUI, when you try to take a screenshot what's shown on magnifier is far far away from the cursor.

### System Information

Using macOS Sonoma Versione Beta di 14.5 (23F5074a) on Mac Mini M1 with just one monitor (LG 4K HDR), Flameshot installed with brew.

╰─ system_profiler SPDisplaysDataType                                                                                          ─╯
Graphics/Displays:

    Apple M1:

      Chipset Model: Apple M1
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 8
      Vendor: Apple (0x106b)
      Metal Support: Metal 3
      Displays:
        LG HDR 4K:
          Resolution: 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)
          UI Looks like: 2560 x 1440 @ 60.00Hz
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported

**Comment by mmahmoudian** [comment]
Do you have any scaling on for that monitor?

**Comment by Rigido71** [comment]
Yes, as you can read monitor is 4K but desktop is set to 2560x1440.

**Comment by Rigido71** [comment]
Probably something changed from Beta to Official as now the whole screen is zoomed and magnifier works fine.
