### ISSUE TITLE
Save history of screenshots taken

### ISSUE THREAD

**Issue by ricardo-properati** [flameshot-org/flameshot#360]
Adds capability to flameshot hold history of screenshots taken is awesome to retrieve old screenshots. Another software that do that with a good UX is the [Budgie Screenshot Widget](https://github.com/cybre/budgie-screenshot-applet) as you can see below:

![image](https://user-images.githubusercontent.com/43390015/46359086-d5151200-c63e-11e8-9bdd-cd7667f33b05.png)

**Comment by LonFas** [comment]
Yep, i want this feature too, with function of delete images. Sometimes it's very necessary

**Comment by arnestig** [comment]
I created a pullrequest for an implementation of screenshot history: https://github.com/lupoDharkael/flameshot/pull/715

Screenshots taken are saved in the history and can be run through flameshot again if you want to modify it in some way.


![image](https://user-images.githubusercontent.com/9248196/78791734-8c1ae800-79b0-11ea-8a97-b31064377947.png)
