### ISSUE TITLE
Flameshot aborts after entering text

### ISSUE THREAD

**Issue by oherikee** [flameshot-org/flameshot#3615]
#### Flameshot version:
Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.5.0-35-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04.4 LTS

### About the problem
Whenever I add text to the screenshot, then try to add any other object (square, arrows, etc.) the flameshot aborts. Demonstrative video below:

https://github.com/flameshot-org/flameshot/assets/140446973/5416090a-ef4a-4cdf-84f0-55f1a2e7f376

### Steps to reproduce

1. Run "flameshot gui";
2. Insert a text;
3. Try to insert another object;

### Screenshots or screen recordings

https://github.com/flameshot-org/flameshot/assets/140446973/5416090a-ef4a-4cdf-84f0-55f1a2e7f376

### System Information

1. Ubuntu 22.04.4 LTS;
2. Monitor config:
![image](https://github.com/flameshot-org/flameshot/assets/140446973/af030046-106e-436a-8ade-b61b9ee654d2)
3. Gnome

**Comment by derlui** [comment]
Same Issue on Linux Mint 21.3, but only after a number of screenshots have been taken and edited successfully.

**Comment by Camusensei** [comment]
Same issue when switching back from wayland to Xorg

**Comment by mmahmoudian** [comment]
This is already fixed. Please consider using the updated version of Flameshot. Version 11.0.0 is very old. You can use Flatpak or AppImage if your distro does not ship the latest version.
