### ISSUE TITLE
Flameshot appears in new desktop workspace in Mac

### ISSUE THREAD

**Issue by mcnaveen** [flameshot-org/flameshot#3620]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

darwin: 23.4.0 osx: 14.4

### Description

I'm facing a weird issue with Flameshot on Mac. Whenever I try to open flameshot to take a screenshot, it opens up a new desktop workspace window. Please watch the below video recording to understand what I mean.

I'm connected to an external display right now, but this is the same case with MacBook display as well.

### Screenshots or screen recordings

1. Run Flameshot
2. Try taking a screenshot

https://github.com/flameshot-org/flameshot/assets/8493007/b30ad3de-76cb-42f2-a8d9-89d78d3a2e9a

### System Information

![image](https://github.com/flameshot-org/flameshot/assets/8493007/b18d92e2-2004-49e6-9200-e1b0df384c57)

**Comment by Rigido71** [comment]
I think it is working as designed, it is the most annoying thing of FS....well, consider it is useless on my configuration as FS gets "confused" by desktop scaling.

**Comment by mcnaveen** [comment]
What do you mean by "Working as designed" it's not even letting me take a screenshot of any application? It opens as a separate Window and shows me only wallpaper.

**Comment by aibncox** [comment]
I have the same problem on Sonoma 14.4.1 with M1 Pro... I use Flameshot on for all my screeenshotting on Linux and was excited to try it on macOS but it doesn't take a screenshot of the current screen when it does that. I'm a bit okay with the new desktop workspace, I just need the screenshot to be of the workspace that I'm working from originally.

**Comment by aibncox** [comment]
Okay, I just realized that Flameshot only exhibits this behaviour when I start it from iTerm2. If I open the app directly from Spotlight for instance the problem doesn't occur. I think it's because the permissions for screencapture are applied broadly and iTerm2 for instance doesn't have permission to capture my screen which causes Flameshot to behave this way.

**Comment by mcnaveen** [comment]
Ah, this is really strange. I don't face any issues if I open it from the Application folder. Happens only when I launch from Raycast.
