### ISSUE TITLE
can't install using pacman or yay - 404

### ISSUE THREAD

**Issue by rikkarth** [flameshot-org/flameshot#3622]
### Flameshot Version

latest

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), User repository (AUR)

### Operating System type and version

6.9.2-arch1-1

### Description

Error Dump

I tried with both pacman and yay

```
:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 qt5-translations-5.15.13-1-any is up to date
 Total ( 1/10)           2.3 MiB  10.9 MiB/s 00:00 100%
error: failed retrieving file 'qt5-translations-5.15.13-1-any.pkg.tar.zst.sig' from mirror.osbeck.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
error installing repo packages
```

### Steps to reproduce

```
pacman -S flameshot
```

or 

```
yay -S flameshot
```

or 

```
yay -S flameshot-git
```

### System Information

distro-version: 6.9.2-arch1-1
window-manager: i3wm

**Comment by Acpear** [comment]
Hi, have you updated the package database in time? According to the archlinux.org package [search](https://archlinux.org/packages/?q=qt5-translations), the maintainer updated version [5.15.14](https://gitlab.archlinux.org/archlinux/packaging/packages/qt5-translations/-/commits/main) on May 28th, and the download operation you performed three days ago (June 2nd) is still downloading version 5.15.13, which may lead to a file not found issue.

```sh
pacman -Syu  # use this to update your package database
```

The [link](https://bbs.archlinux.org/viewtopic.php?id=137528) that may be relevant.

**Comment by rikkarth** [comment]
Thank you for your reply @Acpear 

You are right. I didn't notice the version update which would consequently cause the file not found error.

After updating the package database it works.
