### ISSUE TITLE
Support ALT+PRINT SCREEN to only capture the active window and open Flameshot GUI

### ISSUE THREAD

**Issue by Hassias** [flameshot-org/flameshot#3636]
### Feature Description

Other screenshot tools, and even the build-in support in windows support pressing ALT+PRINT SCREEN. In Flameshot, the GUI does not open when using this combination, only the image is copied to the clipboard.

**Comment by Korb** [comment]
@Hassias, apparently, in any case, we will have to wait for the implementation of #334.

**Comment by cspaniard** [comment]
Being able to capture and annotate the active window would be of great help.

**Comment by mmahmoudian** [comment]
Thanks for the feature request, but this is duplicate of https://github.com/flameshot-org/flameshot/issues/1341 . Please consider searching among open and closed issues before creating a new one. Thanks.
