### ISSUE TITLE
Screenshots don't appear in "screenshot history" when copying the screenshot to the clipboard (not sure if this is intended)

### ISSUE THREAD

**Issue by oMqngo** [flameshot-org/flameshot#3643]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19045
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

Whenever taking a screenshot, it appears in the windows clipboard but doesn't in Flameshot's screenshot history.

Im not sure if this is intended behavior, if it is sorry for the false report!

### System Information

Windows 10 22H2

**Comment by mmahmoudian** [comment]
History is only meant to keep record of uploads so that users can delete them if they need to. If you would like to keep track of your clipboard, you have to install a clipboard manager like CopyQ.

**Comment by oMqngo** [comment]
ah i see, thank you for the response!
