### ISSUE TITLE
Change Panel Icon [Question]

### ISSUE THREAD

**Issue by bicodegas** [flameshot-org/flameshot#366]
Is it possible to change the panel icon? Papirus Icon Theme has a mono icon for flameshot but it seems there's no easy way to change it.

Thanks for this app,
Cheers

**Comment by AlfredoRamos** [comment]
Which panel? Do you mean the system tray icon? Is so, it must be named `flameshot-tray` and it will fallback to a PNG image it none of the installed themes have that file or symlink. See:

https://github.com/lupoDharkael/flameshot/blob/6c49a227c403bc7f33deee5d4ad65bb6f30782d6/src/core/controller.cpp#L194

**Comment by bicodegas** [comment]
Thanks for your reply,
Yes, sorry, it's the system tray icon. The icon theme has a flameshot-tray but is an SVG file. 
I tried making a symlink, editing the SVG to PNG but the system tray keeps using the normal colored icon.

**Comment by AlfredoRamos** [comment]
Did you clear/refresh the theme cache?

When I proposed to change the UI icons to SVG, I also tried to use the SVG image for the tray icon but I couldn't get it to work, I'm not sure if that is also related with this issue. I'll try to look into it.

**Comment by bicodegas** [comment]
Yes, I refreshed the theme cache. I'm going to try my "workaround" again, if anything changes I'll report it.

Thank you.

**Comment by AlfredoRamos** [comment]
I can't reproduce using the latest release of that theme.
![20181008_104417](https://user-images.githubusercontent.com/4165935/46619269-52310300-cae7-11e8-9b6b-5176762b314e.png)
Are you sure you are using the latest release (>= 20181007) or an updated snapshot?

I don't think this is a problem with this application.

**Comment by hosiet** [comment]
@bicodegas The software version in released Ubuntu (e.g., 18.04) will almost never gets updated from distribution side since it is considered "stable,". The only exception would be if some severe security bugs were discovered in flameshot. Anyway no Ubuntu Developer is maintaining flameshot in Ubuntu so at least we need a Ubuntu developer before doing anything.

**Comment by bicodegas** [comment]
Thank you.
I think Ubuntu 18.10 already has an upgraded version, flameshot (0.6.0-5). I tried to install it but got dependency issues. Oh well, this is a thing I can live with.

Thank you both for your time.
Cheers.

**Comment by ZetaoYang** [comment]
I think flameshot can achieve a setting config to switch icon theme.

**Comment by s3r6** [comment]
Please add monochrome white icons to fit dark themes. Also bright icon is nice but looks like an active notification and distracts to check if there are any.

**Comment by borgmanJeremy** [comment]
I don't think any further action is required on this since #445 and #452
