### ISSUE TITLE
Feature Request: Screen record with sound (wayland)

### ISSUE THREAD

**Issue by mercifulboss** [flameshot-org/flameshot#3688]
### Feature Description

Hello,

Thank you for your amazing app. Auto uploading to imgur from my desktop is really convenient and saves ALOT of time. However, one feature I feel is sorely missing is screen recording WITH sound. Spectacle kind of has screen recording but it cannot record sound due to limitations of kpipewire.

It would be really nice if one could use flameshot as both a universal screenshot app and a screen recorder using pipewire and xdg-desktop-portal on KDE/GNOME as it would make it more of a universal app for any DE

**Comment by mmahmoudian** [comment]
Thanks for taking the time to write this feature request. Unfortunately this is a duplicate issue. Others have suggested it before, and it have been discussed. The ultimate decision was that Flameshot is a screenshot and annotation tool, and having screen recording is out of the scope of this program.

But as a fellow Linux user and KDE fan, I can suggest using OBS:

https://obsproject.com/
