### ISSUE TITLE
Wrong version installation

### ISSUE THREAD

**Issue by serafm** [flameshot-org/flameshot#3708]
Hey,

I tried to install the new version of flameshot **v12.1.0** by running the command on Ubuntu 22.04:

`sudo apt install flameshot` 

but it installs the **v.11.0.0** version instead.

Any insights about this and how to install the latest version?

**Comment by serafm** [comment]
Thanks for the update!

**Comment by mmahmoudian** [comment]
I hope the info above have cleared the situation and give you how to proceed, but if you had any issues, we will gladly assist you.
