### ISSUE TITLE
Imgur Upload Failed "server replied: Too Many Requests"

### ISSUE THREAD

**Issue by jbagwell27** [flameshot-org/flameshot#3709]
### Flameshot Version

Flameshot v12.1.0 (-)  
Compiled with Qt 5.15.12  
linux: 6.10.6-200.fc40.x86_64  
fedora: 40

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 40

### Description

Trying to upload to imgur, I receive the following error  
`Error transferring https://api.imgur.com/3/image?title=&description=2024-08-30_11-29 - server replied: Too Many Requests`

### Steps to reproduce

1. Run `flameshot gui`  
2. select a region on primary monitor  
3. click the upload button (cloud with arrow icon)
4. error message appears

### Screenshots or screen recordings

![Peek 2024-08-30 11-36](https://github.com/user-attachments/assets/a9d42691-3ba9-46d6-b611-9ae6114575ed)

### System Information

# System Details Report
---

## Report details
- **Date generated:**                              2024-08-30 11:37:50

## Hardware Information:
- **Hardware Model:**                              Gigabyte Technology Co., Ltd. Z390 I AORUS PRO WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   Intel® Core™ i9-9900K × 16
- **Graphics:**                                    NVIDIA GeForce GTX 1080
- **Disk Capacity:**                               600.1 GB

## Software Information:
- **Firmware Version:**                            F6
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.10.6-200.fc40.x86_64

## Display Information
-**Number of Monitors** 2
-**Display Resolution** 1920x1080
-**Refresh Rate** 165Hz, 144Hz

**Comment by mmahmoudian** [comment]
The error is pretty self-explanatory. You are using our account to upload (along with thousands of other users) and running out of quota. We have explained the solution in our documentation:

https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

**Comment by meandrii** [comment]
> The error is pretty self-explanatory. You are using our account to upload (along with thousands of other users) and running out of quota. We have explained the solution in our documentation:
> 
> https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

It doesn't work anymore, if you navigate to page to create APP it redirects you to main page

**Comment by AnJellyCue** [comment]
> It doesn't work anymore, if you navigate to page to create APP it redirects you to main page

True,  doesn't work

**Comment by mmahmoudian** [comment]
@meandrii @AnJellyCue 
We at Flameshot are not responsible for imgur. Please contact their support if you need assistance for their platform.
