### ISSUE TITLE
Smart Window Edge Detection

### ISSUE THREAD

**Issue by Renari** [flameshot-org/flameshot#3723]
### Feature Description

I'm trying to switch over to flameshot from ShareX (due to ShareX being Windows exclusive and I'm planning to switch over to a Linux machine soon), and one of the features I miss the most is simply being able to click a window to take a screenshot of that window.

e.g.
![image](https://github.com/user-attachments/assets/0cbcf0c6-8781-481f-af5f-27c13b39485f)

Notice how hovering my mouse over that window highlights it as the screenshot area.

I believe this feature is a significant ask however since unlike ShareX which only supports Windows flameshot supports MacOS, Windows as well as Wayland and X11. Maybe it would make more sense to split this request up into an implementation for each windowing system.

**Comment by mmahmoudian** [comment]
First and foremost, welcome to the great world of Linux.

This issue have been suggested and discussed before, for example in #2948. There is also a new addition to Wayland protocol for selecting a window without doing any edge detection, although that is jot implemented in most of the compositors.

Regardless, thanks for suggesting this, but since it is a duplicate, I'm going to close it in favor of the other one.

**Comment by Renari** [comment]
> First and foremost, welcome to the great world of Linux.
> 
> This issue have been suggested and discussed before, for example in #2948. There is also a new addition to Wayland protocol for selecting a window without doing any edge detection, although that is jot implemented in most of the compositors.
> 
> Regardless, thanks for suggesting this, but since it is a duplicate, I'm going to close it in favor of the other one.

I read the other issue and didn't think it was the same since it talked about adding a ruler and using opencv for edge detection, the Microsoft tool it links to simple measures distances of elements on a window. I wasn't looking to measure anything rather just automatically select the area of a window via clicking it for a screenshot, which those dimensions should be able to be pulled from the window manager.

**Comment by Renari** [comment]
@mmahmoudian I do think there has been a mistake, I read through the entire other thread on the issue you linked and it is not the same. Please let me know if you need clarification on my original post.
