### ISSUE TITLE
Error transferring https://api.imgur.com/3/image?title=&description=2024-09-18_06-22 - server replied: client read error

### ISSUE THREAD

**Issue by thracyturnix** [flameshot-org/flameshot#3728]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian 12

### Description

try to upload to imgur. Get error

Error transferring https://api.imgur.com/3/image?title=&description=2024-09-18_06-22 - server replied: client read error

### Steps to reproduce

1. take screenshot
2. try to upload to imgur

### Screenshots or screen recordings

![flameshot](https://github.com/user-attachments/assets/f3a0dc7b-8fc4-426b-9844-a5e690604ab1)

### System Information

System:
  Host: xps179700 Kernel: 6.1.0-18-amd64 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.5 Distro: Debian GNU/Linux 12 (bookworm)
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.9 with: Xwayland v: 22.1.9
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: iris gpu: i915 resolution: 1920x1200~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel UHD Graphics (CML GT2)

**Comment by AnimalRescuer** [comment]
Same problem on Win 11.
Client read error AND Too many requests.

**Comment by thracyturnix** [comment]
The solution is here https://flameshot.org/docs/guide/imgur-help/

For reasons known only to themselves, the Dev has not bothered to change the error message to something meaningful despite the fact this is a known issue with the app and the imgur API (The API being the cause). One would think it s simple matter to link to the URL instead of providing a nonsensical error. It would definitely save them a shit ton of issues being raised here. 

They also havent bothered to state this in the docs on the main page. Anyway you can fix it easily by just adding your own API thingo.

**Comment by AnimalRescuer** [comment]
Imgur really should go back to just being Reddit's filing cabinet.
