### ISSUE TITLE
Flameshot not working on macos

### ISSUE THREAD

**Issue by caem1420** [flameshot-org/flameshot#3738]
### Flameshot Version

v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Macos 15.0

### Description

When using the option "Take screenshot" the screen moves to the desktop, and its not possible to take the shot of the window that is present at the moment, just shows the desktop wallpaper

### Steps to reproduce

1. Click flameshot icon on the top bar
2. Click take screenshot

### Screenshots or screen recordings

https://github.com/user-attachments/assets/bfea8c4a-39bd-46a8-9957-77d3983fc023

### System Information

Macbook air m1 - Macos 15.0

**Comment by thomasphansen** [comment]
No problems on MacOS 14.7 - probably something introduced in Sequoia?

**Comment by thomasphansen** [comment]
Maybe you need to review the screen sharing permissions for flameshot? I know Sequoia added more restrictions on it (for example, Microsoft Teams now needs to ask for screen sharing permissions every month...

**Comment by caem1420** [comment]
The solution of the problem, was simply restart the computer, after that everything normal.
