### ISSUE TITLE
Can't upload image to Imgur

### ISSUE THREAD

**Issue by bee1yash** [flameshot-org/flameshot#3744]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows

### Description

Can't upload image to imgur, changing many times API, create new account but still getting error
Error transferring https://api.imgur.com/3/image?title=&description=2024-10-01_09-44 - server replied: Too Many Requests

### Steps to reproduce

1. make a screenshot
2. press Ctrl + D

### System Information

Windows 11
1920x1080

**Comment by mmahmoudian** [comment]
Thanks for taking time to report a potential bug, but please search among open and closed issues before creating a new one. It would first and foremost save your own time.

https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+%22Too+Many+Requests%22+

The solution is also explained in our documentation:

https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

**Comment by bee1yash** [comment]
your solution didn't help me, as I said before, I tried to create a new applications many times..

**Comment by mmahmoudian** [comment]
But that is the error you are getting. Are you sure you are going through all the steps that we have documented here:

https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

**Comment by bee1yash** [comment]
Now, I made step-by-step but still error
Error transferring https://api.imgur.com/3/image?title=&description=2024-10-07_09-19 - server replied: Too Many Requests
