### ISSUE TITLE
Black line on top of screenshot when pasting in HTML with Firefox

### ISSUE THREAD

**Issue by SemaphoreOxalis** [flameshot-org/flameshot#3776]
### Flameshot Version

Flameshot 12.1.0
Firefox 132

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11H2

### Description

Hi,
As mention by multiple ppl in the #2459 in some condition Flameshot "add" some very annoying black line on border.
In my case I have confirmed 100% of the time of the issue with Windows 10 and 11, Firefox and html app like webmail, online writer UI like MD files, Onlyoffice, Github etc

### Steps to reproduce

1. Take a screenshot from a windows10 or 11 computer
2. Open Firefox and a webamil or this same Github here
3. Paste the image like this 
![image](https://github.com/user-attachments/assets/104b2ae3-2d46-4a6d-9997-e7067760c627)
4. Confirm there is a black line on top of the image

### System Information

Windows 10 or 11 anyversion
Any monitor settings
Any firefox HTML app

**Comment by mmahmoudian** [comment]
@SemaphoreOxalis Thank you for opening a bug report. This issue you are facing is very different from what was mentioned in the #3566. This is the difference:

![image](https://github.com/user-attachments/assets/c1ca4e14-4d2a-443b-843b-b8a0f131d275)

The issue in #3566 is Wayland-specific in Linux machines and has nothing to do with macOS or Windows.

**Comment by SemaphoreOxalis** [comment]
Indeed, I make a mistake, it was the #2459 .

**Comment by SemaphoreOxalis** [comment]
Okay, I don't get the "QT" comment at this time, now you say it : I understand flameshot use QT and the issue must be related to the QT framework. I think I can confirm this : I just test Ksnip, another screentool based on QT : Same issue
I'm so sad as a user daily user... Hoping this could be fix one day.
