### ISSUE TITLE
Handle XDG_CURRENT_DESKTOP correctly

### ISSUE THREAD

**Issue by gen2brain** [flameshot-org/flameshot#3780]
### Flameshot Version

Flameshot v12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Gentoo Base System release 2.17

### Description

`XDG_CURRENT_DESKTOP` has always been a colon-separated list of strings, although that list may have a single string. Mine is `LXQt:labwc:wlroots`, but Flameshot warns with `Unable to detect desktop environment (GNOME? KDE? Sway?`. Surely one of these is supported, I just glanced over the code but it looks like you handle it like it is just a plain string.

### System Information

I am using the LXQt/labwc combo.

**Comment by gen2brain** [comment]
Just to note, I can take a screenshot when I set `XDG_CURRENT_DESKTOP=sway`, but the colon issue remains. This should be an easy fix, and while at it, please add more compositors to the list.

**Comment by FelixJochems** [comment]
It's not really a case of reading an environment variable and acting upon it. 
It's that almost all of those are Wayland compositors, which we don't have full support for yet.

**Comment by gen2brain** [comment]
It works for me though, I can take a screenshot, not sure about the missing features. However, I should not export env var to `sway` that I have no relations whatsoever to work. And like it is now, you surely cannot `LXQt:labwc:wlroots` to `sway` or `wlroots.

**Comment by FelixJochems** [comment]
You're not missing out on anything, whenever `XDG_SESSION_TYPE` is set to `wayland` it will search the `XDG_CURRENT_DESKTOP` for applicable string(s). But there is no real improvement to any wayland WM at the moment.

That error is already fixed in the git version by defaulting to the `OTHER` type but that code is not in the latest released version.
