### ISSUE TITLE
Create Text overlay feature

### ISSUE THREAD

**Issue by peteichuk** [flameshot-org/flameshot#379]
Create Text overlay feature.

**Comment by hosiet** [comment]
@peteichuk If it is a feature request, could you elaborate further on what is text overlay? I'm not sure what text overlay is and the detailed effect is not clear. It would be even better if you could provide images or screenshots to demonstrate that feature.

**Comment by AlfredoRamos** [comment]
If you mean to add text to an screenshot, there's already a tool for that since version [0.6.0](https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0), if you already have that version make sure you have it enabled.

**Comment by febcrash** [comment]
It should be better like Shutter Editor

**Comment by riscie** [comment]
@AlfredoRamos I am on v0.6.0 and can not find the text-overlay tool. I had a look at the config too. Do you know where one can enable it?

**Comment by mcampbell** [comment]
> If you mean to add text to an screenshot, there's already a tool for that since version 0.6.0, if you already have that version make sure you have it enabled.

Can you point out where this enabling configuration is?  I was unable to find it; it doesn't show as a tool to enable when I run `flameshot config`?

I have:
```
% flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.9.5
```

**Comment by mcampbell** [comment]
Thanks @riscie, this did fix it.  `pkill flameshot`, then re-run it, and `flameshot config` shows the text tool.

**Comment by QuAzI** [comment]
Today om Kubuntu 18.04 with last updates was installed. And by default "Text" feature hidden from tools. Please made id available by default
```
$ flameshot --version
Flameshot v0.6.0-23-g35459e1
Compiled with Qt 5.9.5
```
