### ISSUE TITLE
Filename possibilities - Window/Tab Name?

### ISSUE THREAD

**Issue by codesterribly** [flameshot-org/flameshot#383]
Would be nice to add to the list of filename stubs that are possible in the configuration dialog.
Greenshot tends to take the name of the Window or Tab that is open, and use that as part of the filename. Works fairly well.

If no one else takes this up, I will attempt to figure out how to add the option.

**Comment by AlexP11223** [comment]
Yeah, would be cool.

Might encounter some DE-specific issues on Linux though.

**Comment by borgmanJeremy** [comment]
This is not really possible due to complexities in abstracting the underlying OS and DE.
