### ISSUE TITLE
Openbox freezes when copying to clipboard

### ISSUE THREAD

**Issue by GasparVardanyan** [flameshot-org/flameshot#389]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.11.1

**System Information**
OS: Arch Linux
Kernel: x86_64 Linux 4.18.16-arch1-1-ARCH
WM: OpenBox

**Comment by AlfredoRamos** [comment]
Might be related to #353

**Comment by almostscheidplatz** [comment]
I see the same freezing behavior (for ~40s) when copying to clipboard. Even with deactivated flameshot desktop notifications. So I guess it is not directly connected to #353

**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.10.1

**System Information**
OS: Void Linux
Kernel: 4.18.10_1
WM: cwm

**Comment by almostscheidplatz** [comment]
Is your dbus configured correctly? I could resolve my problems by making sure dbus is running properly. Not working dbus was a problem even with deactivated flameshot desktop notifications!

**Comment by j0n4t** [comment]
> #353 didn't helped.

For me using arch, .xinitrc and openbox worked, just needed to install and start dunst.

**Comment by GasparVardanyan** [comment]
... I already don't use flameshot ))

**Comment by borgmanJeremy** [comment]
Flameshot currently required dbus and a notification service. We are looking at refactoring this, and this is captured in another issue so I will close this.
