### ISSUE TITLE
[Feature request] Auto-save option/mode

### ISSUE THREAD

**Issue by misejoh** [flameshot-org/flameshot#394]
Awesome app, but I'd like to suggest some enhancements.

- An auto-save option, (e.g. on the name pattern) to save them instead-of/in-addition to copy to clipboard.
- Some sort of "retake same area" option in the context menu (right click).

That would be awesome.
Thanks for developing this app.
Regards.

**Comment by Alexxz** [comment]
Additional idea: add an action to open the directory with auto-saved images. I'm migrating to flameshot from shutter and missing some nice and cool features

**Comment by magicvince** [comment]
Auto-save could be a nice option for multi shot

**Comment by ElijahLynn** [comment]
Cross linking similar issues:
* https://github.com/lupoDharkael/flameshot/issues/546
* https://github.com/lupoDharkael/flameshot/issues/394
* https://github.com/lupoDharkael/flameshot/issues/73
* https://github.com/lupoDharkael/flameshot/issues/734

**Comment by borgmanJeremy** [comment]
#516 is now merged for the 0.8 release.
