### ISSUE TITLE
FYI: incorrect labeling in Ubuntu Software

### ISSUE THREAD

**Issue by peterhebert** [flameshot-org/flameshot#398]
This is more informational than an issue per se - looking at Flameshot in the Ubuntu Software store, it incorrectly identifies the license as 'proprietary', when it says here it's GPL 3.0. Also found in Universe repository, might want to contact Ubuntu to correct this.

Ubuntu 18.04

![flameshot-ubuntu-software](https://user-images.githubusercontent.com/3053120/48233860-c9b6b400-e36b-11e8-885a-0ed197206519.png)

**Comment by hosiet** [comment]
The information source should be clarified -- I guess it came from AppStream metadata, which is provided by the software **itself**. It has nothing to do with Ubuntu.

Well, currently the metadata provided by flameshot is actually broken. See https://appstream.debian.org/sid/main/issues/flameshot.html for diagnostic info.

**Comment by lupoDharkael** [comment]
@hosiet should flameshot.appdata.xml be modified?

**Comment by borgmanJeremy** [comment]
@hosiet is this corrected after the recent changes?

**Comment by hosiet** [comment]
I believe this is fixed by 961ce5f732505436c6691a842708b7a83c712584 but I am not sure when it will be reflected in gnome-software (or AppStream). Maybe we can keep it open and wait till after 0.8.0 release and see if there are any improvement.

**Comment by hosiet** [comment]
This should have been fixed at least in 0.8.5:

![图片](https://user-images.githubusercontent.com/8443926/108613081-7d68d400-73bc-11eb-8fb8-5bbd6bdf1f96.png)

@borgmanJeremy I believe we should close this issue now.
