### ISSUE TITLE
Cannot run flameshot with any arguments

### ISSUE THREAD

**Issue by MiguelBarq** [flameshot-org/flameshot#403]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.11.1

**Describe the bug**
Running flameshot with any of the arguments listed by `flameshot -h` results in an immediate exit with no messages and nothing being run. I also had the copy-hang issue listed in #353 , fixed in the same way.

I saw this same issue in #123 but I don't see a resolution there.

**To Reproduce**
Run any of the following:
`flameshot gui`
`flameshot screen [flag]`
`flameshot full [flag]`
`flameshot config`

**Expected behavior**
Program to launch and run.

**System Information**
OS - Arch 4.18.16
DE - xfce4
WM - xfwm4

**Comment by christianmtr** [comment]
I had a similar problem, in my case I seted up flameshot to run with the system, It was working fine but two weeks ago (I don't remember if it was updated) it don't launching at system's startup. From that I only can run it with `flameshot gui` or `flameshot config` and it keeps in the panel icon and works fine (I disabled "Launch at startup" too). I just tryed to setted up "Launch at start up" again and it seems like the problem was solved.

**Comment by Fr3llD** [comment]
#330

**Comment by Migillope** [comment]
I'm not sure how our issues are related. You can only run it from `flameshot gui` or `flameshot config` and I can run it from neither of those. It should also be noted that running anything other than `flameshot` does not give me a panel icon, either.

Running flameshot alone then clicking the icon allows the program to run. Selecting the "copy" option causes the entire DE to hang for a solid 15 seconds or so. Selecting the "save" option causes just the program itself to hang for the same amount of time. This is all with desktop notifications turned off. Here is what the program output to the console after hanging (notably, it does actually _work_):

`QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
`

**Comment by dlangerenken** [comment]
I'm seeing similar issues as @Migillope - `flameshot gui` or `flameshot config` is not doing anything. No log, no tray icon, nothing. However, selecting copy will not cause my DE to hang - it works fine. Everything works fine when started with `flameshot`. Unfortunately I really like to use `gui` since I set my hotkeys to it ;).

OS: Ubuntu 18.10

**Comment by Migillope** [comment]
@dlangerenken Out of curiosity, what is your DE? GNOME, I assume?

**Comment by Fr3llD** [comment]
gui or config do nothing with me:

OS: Ubuntu 18.04.1 LTS x86_64 
Host: XPS 13 9350 
Kernel: 4.15.0-36-generic 
Uptime: 10 days, 23 hours, 34 mins 
Packages: 2821 
Shell: bash 4.4.19 
Resolution: 2880x1620 
DE: KDE 
WM: KWin 
Theme: Breeze [KDE], Breeze [GTK3] 
Icons: Breeze [KDE], Breeze [GTK3] 
CPU: Intel i7-6500U (4) @ 3.100GHz 
GPU: Intel HD Graphics 520 
Memory: 7613MiB / 15906MiB

**Comment by Migillope** [comment]
Oddly, it works for me on i3 arch 4.20, but not for my friend with the same kernel and WM.

**Comment by Lisible** [comment]
I'm having the same issue with an almost fresh arch/i3 install

OS: Arch Linux x86_64 
Host: GT60 2PC REV:0.C 
Kernel: 5.1.15-arch1-1-ARCH 
Uptime: 1 hour, 22 mins 
Packages: 482 (pacman) 
Shell: bash 5.0.7 
Resolution: 1920x1080 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: urxvt 
Terminal Font: Source Code Pro 
CPU: Intel i7-4800MQ (8) @ 3.700GHz 
GPU: Intel 4th Gen Core Processor 
GPU: NVIDIA GeForce GTX 870M 
Memory: 2004MiB / 7895MiB

**Comment by mmahmoudian** [comment]
@MiguelBarq Sorry for asking you this after such long time, but would you please check if this issue is fixed with version 0.9.0?

**Comment by mmahmoudian** [comment]
I'm closing this as it has been stale for over a month and it is about an old version. Please consider opening a new issue of you face any problems with the newest version of Flameshot.
