### ISSUE TITLE
Windows - invalid date formats cause the software to crash

### ISSUE THREAD

**Issue by TuxGamer** [flameshot-org/flameshot#410]
**Flameshot version**
v0.6.0-26-g94daa4f with Qt 5.9.7
Downloaded from here: https://transfer.sh/Y81UM/flameshot_0.6.0_win_X64.zip

**Describe the bug**
Flameshot crashes ("has stopped working") when entering an invalid date format, such as a percent sign without a date specifier after it. Entering other strings like "Screenshot_" beforehand is fine.

See this gif: https://i.imgur.com/T6a3HHm.gifv

**To Reproduce**
Open up the configuration window and select the Filename Editor tab. Paste the following text in the text box at the bottom: "Screenshot_%"

**Expected behavior**
The application does not crash and silently ignores the error. Ideally, it performs a validation when clicking the Save button at the bottom and opens up an alert window, if the format is invalid.

**System Information**
Windows 10 Enterprise, Version 1709, build 16299.785,
Windows 8.1 Pro, Build 9600,
Windows Server 2016 Standard Edition, Version 1607, Build 14393.2125

**Comment by thepurple** [comment]
Is fixed in our fork, will be merged a bit later.

**Comment by borgmanJeremy** [comment]
This is fixed on the master branch.
