### ISSUE TITLE
Feature: Progress bar embedded in to animated gif

### ISSUE THREAD

**Issue by luzpaz** [flameshot-org/flameshot#415]
Some people find long (more than 10 sec) animated gifs disorienting. They don't know where it starts or finishes. Other screencapture software out there (ScreenToGif) has solved this by adding a progress bar. 

Example: 
![body01](https://user-images.githubusercontent.com/4140247/49585397-3f427f80-f92c-11e8-8fe8-aef45a4425a7.gif)

Can something like this be added to flameshot ?

**Comment by AlfredoRamos** [comment]
Flameshot doesn't even support GIF animations, so I think this would take time.

**Comment by borgmanJeremy** [comment]
For the animated gif feature this is a duplicated of #172

**Comment by luzpaz** [comment]
@borgmanJeremy this isn't a dupe. This is a feature assuming animated gifs are implemented. Please keep open.

**Comment by borgmanJeremy** [comment]
Hi @luzpaz I am trying to consolidate similar feature requests so I can reference them in one place when authoring an RFC to discuss the feature. Having to cross reference all the issues from different places makes this complicated.

Now that this is linked to #172  I will include it as part of the RFC for the design proposal of the gif capture.

**Comment by luzpaz** [comment]
> Now that this is linked to #172 I will include it as part of the RFC for the design proposal of the gif capture.

Thanks for the elaboration!
