### ISSUE TITLE
README: Add Repology badge to track flameshot integration in to package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [flameshot-org/flameshot#416]
[![Packaging status](https://repology.org/badge/vertical-allrepos/flameshot.svg)](https://repology.org/metapackage/flameshot/versions)

**Comment by borgmanJeremy** [comment]
This is now present on the Readme. Thanks!

**Comment by hosiet** [comment]
@borgmanJeremy I believe the Repology badge is not in README file. This does provide some information but I am not quite sure whether we should add it in the README.

**Comment by borgmanJeremy** [comment]
I could have sworn I saw it today. Maybe it was in another repo.

**Comment by borgmanJeremy** [comment]
@hosiet It is in the readme but it is hidden by default: \https://github.com/flameshot-org/flameshot#packages-from-repository

```
Expand this section to see what distros are using an up to date version of flameshot
```
