### ISSUE TITLE
Repeat last shot

### ISSUE THREAD

**Issue by sliptonic** [flameshot-org/flameshot#417]
I make documentation for another project.  I need to be able to take multiple shots while the content of the screen changes.  I need the ability to repeat the last screenshot again without setting up the region and size over and over.  It would be nice to have an option in the main menu to 'repeat last shot' which would do exactly that.

HotShots has this feature but that project seems to be dying.

**Comment by josipjelic** [comment]
Please implement this. Should be fairly easy but extremely useful when creating documentation.

**Comment by miili** [comment]
Oh yess!

**Comment by ardydo** [comment]
+1
 This was one of my favorite feature from shutter and I really miss it.

**Comment by shelper** [comment]
Same here, please do it

**Comment by nikolayhg** [comment]
Yeah, that would save us a lot of time! Similar to the "Capture last region" shortcut of Greenshot under Windows.

**Comment by jeaye** [comment]
I came here specifically looking for a program which can do this. Flameshot has a lot of features which are enticing, but repeating the last shot (or remembering the last region) is a must have.

This is primarily because selecting a region and moving it to get it just right is finicky and should only need to be done once. I can set the region, take a shot, then change the contents of the window, then take another shot using the same exact region. There won't be any jitter when switching between the captured images, allowing the actual content difference to be more easily the focus.

**Comment by elmerehbi** [comment]
+1 for this

**Comment by lawipac** [comment]
+1 for this function.

**Comment by pglira** [comment]
+1!

**Comment by bart9h** [comment]
Just add an option to remember the last area, and start with that.

Or even make it the default, and get rid of the pink dialog for good.
Just start with rectangle with 1/2 of the screen at the center (or something like that) if there was no previous capture.

**Comment by mfilser** [comment]
+1

**Comment by alerque** [comment]
I tracked down this issue tracker to report this. Also coming from Shutter and this is a make-or-break feature.

Another way to implement this besides the ones mentioned would be to have a `flameshot region --geometry` command where X window coordinates (X origin, Y origin, Width, Height) could be used to specify a consistent region allowing multiple captures of the same coordinates.

**Comment by njminchin** [comment]
This is a must-have feature - I can't use Flameshot without it :( back to Greenshot for now

**Comment by borgmanJeremy** [comment]
This is now possible in the CLI in version 11 beta.

**Comment by jeaye** [comment]
Thanks for the update, @borgmanJeremy! I don't think this issue should be closed, though.

The original request was:

> I need the ability to repeat the last screenshot again without setting up the region and size over and over. It would be nice to have an option in the main menu to 'repeat last shot' which would do exactly that.

The new CLI rework allows for a flag to specify w, h, x, and y, which is a great starting point. It's not quite the same as repeating the last shot selected by the GUI region selection, though; it's much more manual.

Do you foresee this becoming available in the GUI, so people don't need to manually figure out the dimensions and positions?

**Comment by borgmanJeremy** [comment]
Yeah I plan to include this in the graphical launcher. I can reopen this until that is complete.

**Comment by ak2766** [comment]
How does one get to know the starting screen coordinates in order to be able to use the CLI options.  I can see lots of trial and error to get the region just right.

I've just started to use __flameshot__ and cannot find such an option to turn it on in the GUI.

In shutter, one can get this information from a popup window that shows not just the dimensions of the selected region, but also the coordinates of the mouse pointer:
<details>
<summary>Shutter coordinates popup</summary>

![image](https://user-images.githubusercontent.com/6629646/147722241-05cb7c5d-98d7-40e5-9466-912415adf34c.png)
</details>

**Comment by mmahmoudian** [comment]
@ak2766 it is less complicated as you would think. You can use the `flameshot gui --geometry` to get the coordinates. If you use the version 11 you can get the location of the screenshot you selected and immediately save it to file or copy to clipboard. For example:

```sh
flameshot gui --geometry --clipboard
```

**Comment by borgmanJeremy** [comment]
>In shutter, one can get this information from a popup window that shows not just the dimensions of the selected region, but also the coordinates of the mouse pointer:

@veracioux  has also proposed displaying this in a popup in the upper right of the screen. Believe that is tracked on another issue.

**Comment by borgmanJeremy** [comment]
Btw I think I can get the launcher change in version 11, it's almost done

**Comment by ak2766** [comment]
@mmahmoudian
> You can use the `flameshot gui --geometry` to get the coordinates.

Thanks for that.  I had to compile flameshot from source to test as Ubuntu 20.04 provides a rather ancient version and I couldn't find a PPA that provides a newer version:

<details>
<summary>apt info flameshot</summary>
<p>

```
$ apt info flameshot
Package: flameshot
Version: 0.6.0+git20191001-2
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Boyuan Yang <byang@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,220 kB
Depends: libqt5svg5, libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.10.0) | libqt5gui5-gles (>= 5.10.0), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.11.0~rc1), libstdc++6 (>= 5.2)
Suggests: ca-certificates, openssl
Homepage: https://github.com/lupoDharkael/flameshot
Download-Size: 288 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: Powerful yet simple-to-use screenshot software
 Flameshot is a powerful yet simple-to-use screenshot software.
 Notable features include customizable appearance, in-app screenshot editing,
 D-Bus interface, experimental GNOME/KDE Wayland support, integration with
 Imgur and support for both GUI and CLI interface.
```

</details>

**Comment by ak2766** [comment]
OK - I see there's a newer version as a `snap` .  I purged my previous `apt` install and installed the snap version.  However, I'm unable to save screenshots to my home directory and there's no `--classic` option to override, so out it goes.  The snap concept is good but it still leaves a sour taste...

I'm going to have to contend with the `source compilation` and manage the updates to this package myself.  The only question - "Is there a mechanism in the application - like in the snap package - that'll inform me when there's a push to the `github repo`?"

**Comment by mmahmoudian** [comment]
@ak2766 there is no such thing [yet] and I don't think it will ever be. What you can do is actually simple through a bash file. Just pull from master, compare the latest commit with the last commit you have built against, if they were not equal, build it.

I'm planning to have a dedicated repo for "helper scripts" for Flameshot. One to do what I exactly explained to you (with some extra bells and whistles to check for dependencies), and one for automatically download and "install" the latest AppImage. If you are willing to contribute with your script let me know.

**Comment by ak2766** [comment]
Awesome @mmahmoudian.  I didn't scroll far enough in the release to see the AppImage.  I'll go that route as I believe AppImages can do self updates if bundled with AppImageUpdate.

**Comment by matthias-ccri** [comment]
I also eagerly await this feature! Unfortunately I will have to continue using Shutter until then.

**Comment by borgmanJeremy** [comment]
This is included in version 12.

**Comment by sliptonic** [comment]
I just upgraded to v12.    This is fantastic!  Exactly what I needed.  Thank you.

**Comment by ayhamalharbat** [comment]
I am trying to understand how to make use of this feature in Ubuntu, but could not find anything in the docs, can anyone help? Thanks in advance!
@borgmanJeremy 
@sliptonic

**Comment by mmahmoudian** [comment]
@ayhamalharbat It is as easy as going into the settings an activate it:

![image](https://github.com/flameshot-org/flameshot/assets/390889/f15a2c6e-ab97-43c1-8bdc-0d6f329f115d)

![image](https://github.com/flameshot-org/flameshot/assets/390889/fb61b995-a7fb-45ff-990c-1b9e0822cb27)

**Comment by bmenendez** [comment]
Why on Earth I cannot see such a configuration? I'm on Ubuntu 22.04, installed with apt-get. Sorry for the Spanish text on the screenshot, do you know if something is lost in translation?

![2024-05-23_07-57](https://github.com/flameshot-org/flameshot/assets/3055619/c9bd12f5-163f-4b0f-8018-dd23eddca0e9)

**Comment by josipjelic** [comment]
![image](https://github.com/flameshot-org/flameshot/assets/91408/f280b322-74f1-437b-97b2-cb786f775570)

**Comment by josipjelic** [comment]
![image](https://github.com/flameshot-org/flameshot/assets/91408/5d53b208-36b8-4b62-bdbc-aba9a3685a10)

**Comment by bmenendez** [comment]
Ok, it seems I was using an old version that didn't support that. Now that I upgraded to the latest one I can do it. Thank you so much!
