### ISSUE TITLE
Providing another deb package for Ubuntu 18.04 to fix existing deb pkg bug (dbus activation)

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#418]
As stated in https://github.com/lupoDharkael/flameshot/issues/123#issuecomment-443442078 , current deb package provided has a bug that make dbus activation unusable.

I prepared a source tree based on Debian's official packaging guides here: https://salsa.debian.org/debian/flameshot/tree/ubuntu/bionic ...

...and I am providing the source package and the prebuilt package for Ubuntu 18.04 here. The source package and binary .changes file are signed with my pgp key.

[flameshot_0.6.0-7_ubuntu18.04.amd64.zip](https://github.com/lupoDharkael/flameshot/files/2659855/flameshot_0.6.0-7_ubuntu18.04.amd64.zip)

@lupoDharkael Since next release of flameshot seems far away, could you consider replacing the current broken .deb package on the release page with this one so that the following users will not meet any bugs?

cc @ZetaoYang eventually the build process could be fully automated and let me know if you need help for Debian- or Ubuntu- packaging.

**Comment by Creteil** [comment]
I think you can have a look to my comment here : https://github.com/lupoDharkael/flameshot/issues/123#issuecomment-445491144

**Comment by hosiet** [comment]
I saw your comment and that was indeed the root case. My package has been integra ting this configuration for quite a while but unfortunately the one on the GitHub release page didn't. That's why I'm asking for a substitution.
