### ISSUE TITLE
Extend screenshot file naming rules

### ISSUE THREAD

**Issue by QuAzI** [flameshot-org/flameshot#426]
Please add to name templates "Application name" (name of application which window is under cursor), "Autoincrement" (to enumerate all images) and "Random char" (numeric+alpha). As example you can check naming templates in ShareX.

**Comment by drupov** [comment]
Yes, these features would be very useful.

**Comment by mmahmoudian** [comment]
Other than the one about appending the name of the application under the cursor, everything else is already implemented. I'm also not sure how such naming using the application can be useful. Somehow feels like a very small niche use case.

**Comment by borgmanJeremy** [comment]
I don;t think this is possible to do in a crossplatform way unfortunately.
