### ISSUE TITLE
launch at start

### ISSUE THREAD

**Issue by maxsuelsmedeiros** [flameshot-org/flameshot#427]
**Flameshot version**

 When i put the cli command or go to the GUI and put the option start at lauch, the flameshot don't start at launch

"flameshot config -a true" doesn't work 

When i put the CLI command should start at launch.

Ubuntu 18.04 Mate.

**Comment by maxsuelsmedeiros** [comment]
I even choose the GUI option and export the data and save the flameshot.conf in the ~.conifg/Dharkael 
![flameshot](https://user-images.githubusercontent.com/22553016/50289108-94ab8000-0446-11e9-893b-ec1ec6944166.png)

**Comment by AlfredoRamos** [comment]
Explain your issue, you are not providing any useful information.

Do not ignore the issue template, add the required information.

**Comment by borgmanJeremy** [comment]
Closing as stale. If this is still an issue on a 0.8.x release of flameshot please let me know.
