### ISSUE TITLE
添加快捷键？How to add shortcuts？

### ISSUE THREAD

**Issue by zhedream** [flameshot-org/flameshot#428]
**如何添加快捷键?How to add shortcuts**

打开 设置> 设备 > 键盘
Open Settings > Devices > Keyboard

![image](https://user-images.githubusercontent.com/32092082/50329119-b6813180-0530-11e9-9fe8-1ebccc258882.png)

**Comment by vadbes46** [comment]
Great, thank you!!!

Did the same for Ubuntu 18.10 and mapped to Printscreen
Before this I disabled gnome built-in screeshotter:
![image](https://user-images.githubusercontent.com/31437063/50964606-c1503600-14e0-11e9-8ca3-89f2e2780543.png)

![image](https://user-images.githubusercontent.com/31437063/50964622-d4630600-14e0-11e9-8c1a-cf852cd4fabb.png)

**Comment by CHN-STUDENT** [comment]
@lupoDharkael  hi, lupoDharkael. Could you tell me how can set copying screenshot automatically to Clipboard after run `flameshot gui`  ? Thank you!

**Comment by borgmanJeremy** [comment]
@CHN-STUDENT No, you must hit the copy icon.

**Comment by CHN-STUDENT** [comment]
@borgmanJeremy  Would you add this function in the future version?  Copy to clip-broad by hotkey will be convenient for our users.

**Comment by borgmanJeremy** [comment]
@CHN-STUDENT I think the best we will do is add more extensive hot key support so you will be able to hit Ctrl +C and then ESC. We are also working on making hot keys configurable to users.

**Comment by CHN-STUDENT** [comment]
yeah i think so! Thanks for your contributions!
