### ISSUE TITLE
Screenshots end up being just white

### ISSUE THREAD

**Issue by Bios-Marcel** [flameshot-org/flameshot#429]
**Flameshot version**
0.6.0-5

**Describe the bug**
I am using the i3 window manager and compton. Whenever I run `flameshot screen -c`, the resulting screenshot is just a white image in the size of my screen. The command `flameshot gui` works fine though.

**To Reproduce**
Run this on your commandline:

```shell
flameshot screen -c
```

**Expected behavior**
An actual picture of my screen

**System Information**
OS: Ubuntu 18.04 Budgie x64
DE: i3 + compton
Screens: 1x 1920x1080

**Comment by Kerruba** [comment]
I have this issue too on i3, were you able to solve it @Bios-Marcel?

**Comment by Bios-Marcel** [comment]
No, i didn't try to do so though. Instead I just select an area.

**Comment by spectrapulse** [comment]
Same here

**Version:**
> ➜  ~ flameshot --version
Flameshot 0.6.0+git20190714-1(Debian)
Compiled with Qt 5.12.4
➜  ~

**System Information:**
OS: Pop!_OS 19.10 x64 (Ubuntu)
DE: GNOME 3.34.2 on Xorg
Screens: 1x 1920x1080
GPU: NVIDIA RTX 2070 Mobile (Using proprietary nvidia-driver-440 as this might be relevant)

**Comment by rwtallant13** [comment]
I have the same problem on my laptop. My desktop doesn't have this problem however, which is running the same DE and OS.


**Version:** 
```
$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.12.1
```

**Laptop Information:**
Dell Inspiron 5379 
**OS:** Arch
**DE:** bspwm
**Screens:** 1x 1920x1080

**Desktop Information:**
i7/1660ti proprietary nvidia drivers
**OS:** Arch
**DE:** bspwm
**Screens:** 2x 1920x1080

**Comment by placekowo** [comment]
I had the same issue, changed mine to flameshot full instead of screen and it works fine.

**Comment by rwtallant13** [comment]
That's only a solution on a single monitor system. Full captures all monitors and that's not what I want.

**Comment by racerxdl** [comment]
Same issue here:

System Information:
OS: Ubuntu 20.04 x64
DE: XFCE4 on Xorg
Screens: 1x 1920x1080
GPU: NVIDIA GTX 980 Mobile

**Comment by m147** [comment]
I am having the same problem, white screenshot with `flameshot screen -p ~/path/to/screenhot`
Highly annoying, don't understand the issue.

OS: Arch
WM: i3-gaps
Screens: 1920x1080 or 1920x1080 x2 

For some reason `flameshot screen -p ~/path/to/sreenshot` seems to work just fine with the TV plugged in.
Also, as placekowo mentioned `flameshot full` takes a screenshot of the current screen properly; as long as another monitor isn't present.
So I wrote a little script to take a screenshot based on if a second monitor is plugged in or not.  Hope this helps some of you: 

```
#!/bin/bash

# define variables
LOCATION='~/Pictures/Screens'

if xrandr | grep "HDMI-1 connected"; then
    flameshot screen -p ~/path/to/screenshot
else
    flameshot full -p ~/path/to/screenshot
fi

```

use `xrandr` or `xrandr |grep connected` to determine your screens

**Comment by easlice** [comment]
I'm seeing the same behavior on my laptop. `flameshot gui` works, `flameshot full` works, but `flameshot screen` only gives me a white image.

System Information:
Thinkpad L440
OS: Arch
DE: awesomewm
Screens: 1x 1366x768

**Comment by Clemens-Dautermann** [comment]
I have the same issue.
System Information:

Thinkpad X1 extreme Gen2
OS: Arch
i3wm
2 Screens, One 4k one 180p

**Comment by ixzh** [comment]
3 years still not resolved... is this app active?

**Comment by LvGuoQing** [comment]
After I added a part of the log to the project, I found that it was in：
https://github.com/flameshot-org/flameshot/blob/c84b6df7d396e03c33311908cf308e618f0c8709/src/widgets/capture/capturewidget.cpp

```
void CaptureWidget::paintEvent(QPaintEvent*)
{
    QPainter painter(this);
    painter.drawPixmap(0, 0, m_context.screenshot);
```

m_context.screenshot  is null，So I think it is possible that part of the memory is not released

**Comment by erlonbie** [comment]
I have the same issue.

OS: Ubuntu 20.04 LTS x64
WM: Qtile
Screen: 1920x1080

**Comment by erlonbie** [comment]
has anyone found a solution?

**Comment by mmahmoudian** [comment]
If you have not tried the latest version, please do so. At the moment the latest version is v0.10.2 and it is also available via Snap, Flatpak and also AppImage. We also provide the .deb package on our release page. The v0.6.x is not supported by any means.
