### ISSUE TITLE
Hotkey for uploading

### ISSUE THREAD

**Issue by DenisGorbachev** [flameshot-org/flameshot#430]
First off, thank you for making flameshot!

My workflow could be made faster with a single hotkey:
1. Select an area on screen.
2. Press Ctrl+Enter.
3. Wait until the screenshot is uploaded to Imgur & the link is copied into clipboard.
4. Send the link to my colleagues.

Is it easy to add this hotkey?

**Comment by borgmanJeremy** [comment]
A brand new hotkey system is currently merged on master (unstable).
