### ISSUE TITLE
Kubuntu 18.04 only works 0.5.1

### ISSUE THREAD

**Issue by ejabu** [flameshot-org/flameshot#438]
**Flameshot version**

0.6.0
**Describe the bug**

Icon appears on tray.
Icon is clickable.
After pressing start or click any available icon, desktop hangs. 
I can only Lock Screen then restart the OS.
**To Reproduce**

**Expected behavior**

It should normally saved the output to files or copied on clipboard
**System Information**

Kubuntu 18.04

**Comment by kanocz** [comment]
+1 has the same issue on KDE Neon

**Comment by borgmanJeremy** [comment]
This is now very an old release of flameshot. I have tested the latest version on Kubuntu 20.04. Can you test with the latest version of flameshot? I recommend installing it from the snap store on Kubuntu. 

If it is still an issue please reopen this issue.
