### ISSUE TITLE
Doesn't start on Ubuntu 18.04 KDE

### ISSUE THREAD

**Issue by HighWatersDev** [flameshot-org/flameshot#441]
**Flameshot version**
0.6.0 and 0.5.1

**Describe the bug**
I installed flameshot thru apt install as well as used .deb file. I can run flameshot gui, flameshot screen, flameshot config and it works fine. But if I just type flameshot in cli, nothing happens. I also don't see any icons or anything.

**To Reproduce**
Installed flameshot from repo, run 'flameshot' from terminal as non-root user.

**Expected behavior**
applications starts

**System Information**
Ubuntu 18.04 KDE

**Comment by hosiet** [comment]
@HighWatersDev After calling "flameshot", open the notification panel in Plasma tray (click the little triangle icon). Can you see an icon inside?

**Comment by HighWatersDev** [comment]
Yes, I do. I didn't think to look in there. But how do I use it efficiently? Every time I click on icon inside Notification panel, it takes screenshot right away.
Thanks for the help!

**Comment by hosiet** [comment]
Please configure your plasma panel to always show flameshot icon as foreground.

**Comment by hosiet** [comment]
Besides, don't forget that you can always click on the tray icon using right mouse button.

I guess this can be written into user manual (which does not exist yet).

**Comment by HighWatersDev** [comment]
@hosiet Thanks! I guess I was just overthinking it.

**Comment by k1nghat** [comment]
is the 18.04 package not going to be updated or should i just use the 6.0 deb?

**Comment by ZetaoYang** [comment]
@k1nghat try https://software.opensuse.org//download.html?project=home%3AVitzy&package=flameshot
