### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by pafri** [flameshot-org/flameshot#442]
Czech localization file. Attached, ready to be committed. Best regards. Pavel Fric
[Internationalization_cs.zip](https://github.com/lupoDharkael/flameshot/files/2732515/Internationalization_cs.zip)

**Comment by borgmanJeremy** [comment]
Can you please check the translation on the master branch? I recent merged a PR to support Czech

**Comment by pafri** [comment]
Checked.
