### ISSUE TITLE
Text Tool Focus Problem

### ISSUE THREAD

**Issue by bhelm** [flameshot-org/flameshot#450]
**Flameshot version**
0.60

**Describe the bug**
The Text tool seems to not get focus, text input goes to previously focused window. see https://www.youtube.com/watch?v=WiMUNWTt2w8&feature=youtu.be
after starting it on commandline, i called it from the KDE status bar.
it worked once for me, but im not sure what made it work.

**System Information**
Archlinux, flameshot from community repository, compiled with Qt 5.12.0.

**Comment by ZaWertun** [comment]
I have same issue, also running Flameshot in the KDE.

**Comment by rkdarst** [comment]
I was very frustrated with this problem... after several days, I did `killall flameshot` to kill whatever background processes were running.  The text tool focus problem went away!

I guess the taskbar background process was somehow interfering with it... I don't know anything other than this, just wanted to report what I found.
