### ISSUE TITLE
Monochrome systray icon (Plasma 5)

### ISSUE THREAD

**Issue by vmorenomarin** [flameshot-org/flameshot#452]
Is possible to set a monochrome icon in Plasma systray? How?
Thanks!

**Comment by AlfredoRamos** [comment]
I don't use that desktop environment but as far as I know currently you can't change it within the application, but you could use a icon theme to change it, it must be named `flameshot-tray`

See #366

**Comment by borgmanJeremy** [comment]
Monochrome icon is supported in KDE now.
