### ISSUE TITLE
Please add a keyboard shortcut for uploading to imgur

### ISSUE THREAD

**Issue by lamby** [flameshot-org/flameshot#454]
Please add a keyboard shortcut for uploading to imgur. This is my most-common task after `CTRL+S`.

**Comment by Afteroot** [comment]
Agree with you

**Comment by TolichP** [comment]
For me is also relevant

**Comment by afteroot** [comment]
Any updates for this ?

**Comment by lamby** [comment]
WIP PR at #576

**Comment by genu** [comment]
I think there should be a more generic approach to shortcuts. A shortcut for every tool available should be possible.

With the editor open, I should be able to use shortcuts to activate any of the tools available, rather than clicking on them.

**Comment by afteroot** [comment]
Any update for this ?

**Comment by lamby** [comment]
There's my PR at #576  - could you test that? :)

**Comment by afteroot** [comment]
Yep, made review, but shortcut not works as well (

**Comment by lamby** [comment]
> but shortcut not works as well

I think that might need more details. :)

**Comment by borgmanJeremy** [comment]
Custom keyboard shortcuts are added in 0.9
