### ISSUE TITLE
Add default folder for saving image

### ISSUE THREAD

**Issue by renat2985** [flameshot-org/flameshot#455]
I want to click on Save and automatically save photos to specified folder. Thanks.

**Comment by tastytea** [comment]
You can do that with `-p` or `--path`, as in: `flameshot gui -p ~/Downloads`

**Comment by renat2985** [comment]
I use this icon to create screenshots. How can I put this `flameshot gui -p ~/Downloads` there?

![2019-01-26_20-29](https://user-images.githubusercontent.com/1230815/51791271-2a0a0480-21a9-11e9-9517-a7575e489746.png)

**Comment by gcjuan** [comment]
> I use this icon to create screenshots. How can I put this `flameshot gui -p ~/Downloads` there?
> 
> ![2019-01-26_20-29](https://user-images.githubusercontent.com/1230815/51791271-2a0a0480-21a9-11e9-9517-a7575e489746.png)

Hi @renat2985!

I have resolved it not by clicking on the icon but with a keyboard shortcut, that is also really fast and handy.

Just assign the command ```flameshot gui -p ~/Pictures/Screenshots/``` as a keyboard shortcut for the _prntscr_ key. Replace the folder for whichever directory you want and that's it :smiley:

**Comment by srgpsk** [comment]
Thank you @call0fcode it helped me to get rid of all the pain with screenshots!

In addition, at least on Ubuntu 18.04 it expects the path to be absolute so `~/Pictures/Screenshots/` should be `/home/youruser/Pictures/Screenshots/`

**Comment by borgmanJeremy** [comment]
This is resolved in the master branch and will be part of the 0.9 release: 
![image](https://user-images.githubusercontent.com/46930769/107104965-aa788c80-67e9-11eb-84ef-e89df157465d.png)
