### ISSUE TITLE
Flameshot crashes on imgur upload

### ISSUE THREAD

**Issue by sterndata** [flameshot-org/flameshot#456]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1666923

Fedora 29, installed via the RPM
flameshot-0.6.0-1.fc29.x86_64

**Comment by sterndata** [comment]
Still an issue after compiling the latest pull from github.
`[sdstern@sds-desk build]$ ./flameshot
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
QSharedMemory::lock: already locked
Segmentation fault (core dumped)
`

**Comment by borgmanJeremy** [comment]
Is this still an issue on a 0.8.x release? I have tested on Fedora32 and it seems okay

**Comment by sterndata** [comment]
It's resolved.
