### ISSUE TITLE
plan to add record video and scroll capture ?

### ISSUE THREAD

**Issue by vipzrx** [flameshot-org/flameshot#461]
**Is your feature request related to a problem?**
Please, a single feature per issue.

**Comment by ZetaoYang** [comment]
I agree `scroll capture` feature, it's nice, but it's hard to make this feature perfect.

**Comment by abhimanyu003** [comment]
:100: I vote for `scroll capture` as well. Will be a super handy feature to have.

**Comment by AlexP11223** [comment]
Why not just use Peek for video/gif?

**Comment by asolopovas** [comment]
ShareX implemented it ideally using ffmpeg, they can not only record mp4 of your screen as well as gif, would be cool if same was available on linux.

**Comment by asolopovas** [comment]
sometimes its cool to have extra functionality in one place after one roof. 

⁣Sent from Blue ​

**Comment by borgmanJeremy** [comment]
Consolidating feedback on gif / animated video recording to issue #172

**Comment by airtonix** [comment]
> sometimes its cool to have extra functionality in one place under one roof. 

every linux zealot ever just rolled over in their grave.
