### ISSUE TITLE
Plan for another release (0.6.1?)

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#463]
Similar to #314 , I'm suggesting tagging another minor release again. It's already half a year since last release and that there are several important bugs fixed since v0.6.0.

Of course with the experience of the last release, this time the release should be performed more carefully. We should build binary packages for different distributions first before actually tagging in order to prevent potential bugs caused by packaging (to be more concrete, the D-bus related bug in Ubuntu 18.04 package for v0.6.0).

**Comment by ZetaoYang** [comment]
I think it's better to wait for snap and flatpak packages.

**Comment by hosiet** [comment]
Is there any progress for snap and /or flatpak packages?

**Comment by ZetaoYang** [comment]
@hosiet 
snap build successfully, but it's dirty and need @lupoDharkael  to publish to snap store.
flatpak hard to build in travis-ci docker environment.

**Comment by hosiet** [comment]
I don't think either of them could be a blocker. I know that CI is great, but we make releases less than 2 times every year and it's totally fine if we build them manually.

**Comment by ZetaoYang** [comment]
@hosiet https://github.com/flameshotapp/packages flatpak build successfully, wait someone to publish them.

**Comment by lupoDharkael** [comment]
I have a few things in mind before creating a 0.6.1:
- Finishing the numbered bullet tool: almost done.
- Update copyright year in source files: this one is a single replace command but I'm waiting for the new tool to be finished to not cause merge conflicts.
- Check and tag issues and check if I can fix more low hanging fruit bugs.
- Add the close flameshot after capture option
- Add a save path from the gui config menu (its effect would have less priority than the path defined from cli)

I'm working on a personal project and contributing to Godot engine for a free software contests but I want to start working on these tasks soon.

**Comment by magicvince** [comment]
Add the close flameshot after capture option that it could be possible to make multi-captures? If it is, should it be possible to re-edit each capture after (to insert numbered bullets for example)

**Comment by magnus-gross** [comment]
Any news on the release?

**Comment by hurricanehrndz** [comment]
@lupoDharkael 

This project and app are particularly popular on Linux. With the transition to Wayland I think your app will only gather a greater following. Perhaps, having a call out for additional maintainers is in order.

**Comment by borgmanJeremy** [comment]
Working on a new release.
