### ISSUE TITLE
enable saving with a particular filename, for scripting.

### ISSUE THREAD

**Issue by ripefig** [flameshot-org/flameshot#478]
I am not talking about the global autogenerated names option. You should be able to do something like:
```
$MYFILE=`my-generate-name-function`
flameshot gui -f  $MYFILE
do something to $MYFILE
```
Then you hit enter and it's saved to the name you defined.

**Comment by alexanderad** [comment]
I was looking into this myself few days ago and apparently you can use `--raw` option, something like this, @ripefig:
```bash
$ flameshot gui --raw > test.png
$ file test.png
test.png: PNG image data, 453 x 451, 8-bit/color RGB, non-interlaced
```

**Comment by credmp** [comment]
I would still like to vote for this issue as some tools can not process the `>` redirect in the statement. Flameshot is a superior tool, so it would be a shame not to use it because of it.

**Comment by aarohijohal** [comment]
> I was looking into this myself few days ago and apparently you can use `--raw` option, something like this, @ripefig:
> 
> ```shell
> $ flameshot gui --raw > test.png
> $ file test.png
> test.png: PNG image data, 453 x 451, 8-bit/color RGB, non-interlaced
> ```

Adding to this: the screenshot is saved into `test.png` only if I end flameshot by copying to clipboard. If I close it (using the `X` button), a console message `screenshot aborted` goes into the output file.

Ideally, I shouldn't have to copy it to the clipboard to output the raw version.

**Comment by credmp** [comment]
I solved this issue by creating a wrapper script and using that to be called from https://github.com/dfeich/org-screenshot . This was discussed in https://github.com/dfeich/org-screenshot/issues/14 .

During the screenshot pressing ENTER will save the file as required. I think the "copy" option is acceptable, else there would just be a "finished" button instead I would think.

**Comment by aarohijohal** [comment]
> I solved this issue by creating a wrapper script and using that to be called from https://github.com/dfeich/org-screenshot . This was discussed in [dfeich/org-screenshot#14](https://github.com/dfeich/org-screenshot/issues/14) .
> 
> During the screenshot pressing ENTER will save the file as required. I think the "copy" option is acceptable, else there would just be a "finished" button instead I would think.

Wonderful - works like a charm!

**Comment by veracioux** [comment]
#1784
