### ISSUE TITLE
Support position and size as input parameter

### ISSUE THREAD

**Issue by herrenP** [flameshot-org/flameshot#479]
As others have suggested (#5, #334 and #395) there is no way to capture the current focused window or any window really. Instead you have to use the GUI tool and draw a rectangle yourself.

If I understand the creator correctly they do not want to add this feature if it means that migration to another system suffer because of it.

To solve this, why no introduce new parameters where the user themselves can say what positions and size a window has and then capture that region? With these new parameters a user could easily use another tool to determine the position and size and subsequently Flameshot will support taking screenshots of a window.

I am thinking something like this:
`flameshot capture xPosition yPosition xSize ySize`

Example script (this would get all parameters without any decoration):
```shell
#!/bin/bash

# vars
windowData=$(xdotool getwindowfocus getwindowgeometry)
windowPosData=$(echo $windowData | grep -Eo "[0-9]+,[0-9]+")
windowSizeData=$(echo $windowData | grep -Eo "[0-9]+x[0-9]+")
xPosition=$(echo $windowPosData | cut -d ',' -f 1)
yPosition=$(echo $windowPosData | cut -d ',' -f 2)
xSize=$(echo $windowSizeData | cut -d 'x' -f 1)
ySize=$(echo $windowSizeData | cut -d 'x' -f 2)

# exec
flameshot capture $xPosition $yPosition $xSize $ySize
```

To get decoration info you can tinker with:
`xprop _NET_FRAME_EXTENTS -id $(xdotool getActiveWindow)`

Finally you could bind a keyboard shortcut to the above script and presto, we can now capture the current active window.

**Comment by alerque** [comment]
Also related to this is #425.

**Comment by jmandel** [comment]
I have a use case that would be well supported by this approach: screen annotation during live screencasts. I typically share the upper right quadrant of my display during a screencast, and running `flameshot gui` with a keyboard shortcut *almost* lets me just annotate without delay... but first I need to manually drag to select a region. If I could bind a keyboard shortcut to `flameshot gui 1920x1080+1920+0` (or whatever format for specifying coordinates) that'd give me a nice, simple flow.

**Comment by borgmanJeremy** [comment]
We will 100% support this feature, it just a matter of getting it prioritized against other tasks. Before we do this I want to re implement the argument parsing library #945. Likely will get to this after merging in some namecheap features and implementing upload plugins.

**Comment by Chrescht** [comment]
This would be awesome to have. We use an old CMS and the pictures need to be of a predefined pixel size.
