### ISSUE TITLE
'Enter' / 'Return' key as a quick way to save screenshot in selection mode

### ISSUE THREAD

**Issue by alexamy** [flameshot-org/flameshot#480]
Currently pressing any of these keys in gui mode copies selection to the clipboard. But I consider it is a misleading behavior, explanation below.

If I'm using `flameshot gui -p ~/Pictures` command, first of all I expect flameshot to save screenshot to `~/Pictures`. I can achieve this by clicking 'Save' button.
But I also expect a shorter way to do this by just pressing 'Enter' / 'Return' key. At this moment If I press one of these keys, selection is just copied to clipboard, but isn't saved at `~/Pictures`.

So I propose to change behavior of 'Enter' / 'Return' keys in gui mode to save screenshot in a file, if where is a `-p` flag when running flameshot.

I'm using Flameshot v0.6.0-40-gb612bdb on Ubuntu 18.04.2.

Based on comments from #362

**Comment by antoniomcr96** [comment]
I agree. The issue hasn't ever been solved but it should be simple

**Comment by mariusa** [comment]
+1 . Just switched from gnome native tool to flameshot, and kept 'saving' screenshots with Enter key. Later realized none were saved :(

**Comment by mmahmoudian** [comment]
@borgmanJeremy I think this issue can be closed as we have customisable shortcuts.

@mariusa you can right-click on the tray icon, open settings and assign enter (a.k.a Return) to the action you want.

**Comment by mariusa** [comment]
Thanks,

I couldn't find how to assign keys to actions (version 0.8.x), but I found this setting, to save after copy to clipboard, which is good:
![2021-03-14_20-24](https://user-images.githubusercontent.com/1283842/111079650-82c0c680-8503-11eb-9908-4d7b22a64515.png)

**Comment by mmahmoudian** [comment]
The custom keyboard shortcuts has been introduced in 0.9.0 and I encourage you to update to get new features and bug fixes.

**Comment by mariusa** [comment]
Will do, waiting for the update to appear in Fedora. Thanks!

**Comment by mmahmoudian** [comment]
Alternatively, you can always use Flatpak or AppImage to get the most recent version of you are not on a rolling release distro (p.s I'm not a big fan if snap but of course that's an option 😬)

**Comment by mmahmoudian** [comment]
I believe this can be closed as the user can define their custom key bindings.

**Comment by kaldown** [comment]
@mmahmoudian it won't work on `Enter` key for some reason.
Althou I can't find if it's beeng reserved.
Any other combination working correctly, `Shift-Return` is okay, while `Enter` just won't appear.

```
flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment]
@kaldown You almost have the answer in your comment:
> `Shift-Return` is okay, while `Enter` just won't appear

The phrase you should use in your config is `Return` and not `Enter`.

**Comment by kaldown** [comment]
> @kaldown You almost have the answer in your comment:
> 
> > `Shift-Return` is okay, while `Enter` just won't appear
> 
> The phrase you should use in your config is `Return` and not `Enter`.

I'm not using "phrase", I'm trying to use `flameshot config` which is wanting me to hit button. But `Return` won't appear as plain key

**Comment by kaldown** [comment]
Wow!

In order to make a shortcut, this Icon has to be set in gui mode.
Confusing a bit :)

**Comment by kaldown** [comment]
> > @kaldown You almost have the answer in your comment:
> > > `Shift-Return` is okay, while `Enter` just won't appear
> > 
> > 
> > The phrase you should use in your config is `Return` and not `Enter`.
> 
> I'm not using "phrase", I'm trying to use `flameshot config` which is wanting me to hit button. But `Return` won't appear as plain key

Althou it is working if I manually tweak `flameshot.ini`

**Comment by mmahmoudian** [comment]
@kaldown You don't need to manually change the config file. You can use the GUI:

![Peek 2021-04-22 13-56](https://user-images.githubusercontent.com/390889/115703339-af71c480-a372-11eb-9247-efe4222f1ae7.gif)

**Comment by kaldown** [comment]
> @kaldown You don't need to manually change the config file. You can use the GUI. Just clock on any item you want to change. press the key you want or press Backspace to remove keybinding:
> 
> ![Peek 2021-04-22 13-56](https://user-images.githubusercontent.com/390889/115703339-af71c480-a372-11eb-9247-efe4222f1ae7.gif)

tha'ts exactly what I'm saying.
It doesnt work for `Return`

**Comment by kaldown** [comment]
```
➜  ~ dotfiles diff

.config/flameshot/flameshot.ini

───┐
1: │
───┘
│ 1  │[General]                                                    │ 1  │[General]
│ 2  │buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x5\0\0→│ 2  │buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x6\0\0→
│ 3  │checkForUpdates=false                                        │ 3  │checkForUpdates=false
│ 4  │contrastOpacity=188                                          │ 4  │contrastOpacity=188
│ 5  │copyAndCloseAfterUpload=false                                │ 5  │copyAndCloseAfterUpload=false

────────────────────────────────┐
41: TYPE_RESIZE_DOWN=Shift+Down │
────────────────────────────────┘
│ 41 │TYPE_RESIZE_LEFT=Shift+Left                                  │ 41 │TYPE_RESIZE_LEFT=Shift+Left
│ 42 │TYPE_RESIZE_RIGHT=Shift+Right                                │ 42 │TYPE_RESIZE_RIGHT=Shift+Right
│ 43 │TYPE_RESIZE_UP=Shift+Up                                      │ 43 │TYPE_RESIZE_UP=Shift+Up
│ 44 │TYPE_SAVE=Return                                             │ 44 │TYPE_SAVE=
│ 45 │TYPE_SELECTION=S                                             │ 45 │TYPE_SELECTION=S
│ 46 │TYPE_SELECTIONINDICATOR=                                     │ 46 │TYPE_SELECTIONINDICATOR=
│ 47 │TYPE_SELECT_ALL=Ctrl+A                                       │ 47 │TYPE_SELECT_ALL=Ctrl+A
➜  ~
```

that is what happens if I put `Return` throught the `flameshot config`

**Comment by mmahmoudian** [comment]
@kaldown interesting! For me it works (as you can see in the GIF I posted) how about posting this as a bug report

**Comment by kaldown** [comment]
> @kaldown interesting! For me it works (as you can see in the GIF I posted) how about posting this as a bug report

Sure.

What about disappearing of this option when save icon is checked out https://github.com/flameshot-org/flameshot/issues/480#issuecomment-824731095?

I can do both. Or just one (if the second one was made intentionally)
