### ISSUE TITLE
Launchers not working (Lubuntu 18.04)

### ISSUE THREAD

**Issue by danielrosehilljlm** [flameshot-org/flameshot#483]
**Flameshot version**

From repo

**Describe the bug**

'Take screenshot' button has vanished and the launcher icons I have added are no longer working

**To Reproduce**

Click on a launcher icon

**Expected behavior**

**System Information**

Lubuntu 18.04

**Comment by chukrobertson** [comment]
I manually changed the command for the launcher to be "flameshot gui" saved. when I now click the launcher, the gui starts. I hope this helps.

![flameshot](https://user-images.githubusercontent.com/39580238/55266156-e3d92c00-5251-11e9-950b-8411ba91ed76.png)

**Comment by borgmanJeremy** [comment]
This is because gnome removed systray support. You must now install an extension: https://github.com/flameshot-org/flameshot#tray-icon
