### ISSUE TITLE
Flameshot info appearing on screenshot

### ISSUE THREAD

**Issue by reikdas** [flameshot-org/flameshot#488]
**Flameshot version**
Version 0.6.0-3 from community repo of Arch.

**Describe the bug**
The flameshot info box is appearing at the top right corner of my screen in my screenshots. (With the location where I saved the screenshot)

**System Information**
Manjaro with i3wm

**Comment by borgmanJeremy** [comment]
Is this still an issue in new versions of flameshot?

**Comment by reikdas** [comment]
Seems like this is fixed at HEAD.
