### ISSUE TITLE
Add Save button after upload to imgur

### ISSUE THREAD

**Issue by 4goodapp** [flameshot-org/flameshot#489]
After uploading an image it's not possible to save it easily locally, there is no button for that.

![image](https://user-images.githubusercontent.com/6249230/53842979-efaa3900-3f98-11e9-8723-39b045dea1ae.png)

**Comment by AndreaMarangoni** [comment]
Can I take this?

**Comment by AndreaMarangoni** [comment]
PR [#2237](https://github.com/flameshot-org/flameshot/pull/2237)
