### ISSUE TITLE
flatpak support [request]

### ISSUE THREAD

**Issue by Tids** [flameshot-org/flameshot#49]
Itwould be nice if you would provide flatpak support via flathub. That way, all the distros out there could use your software without the needs of building from source.

https://github.com/flathub/flathub/wiki/Submission-Guidelines

Thank you :)

**Comment by ZetaoYang** [comment]
You can try AppImage: https://transfer.sh/10wJZK/Configure_Flameshot-4a2aecd-x86_64.AppImage
and `chmod +x ./Configure_Flameshot-4a2aecd-x86_64.AppImage`

The build detail is here: https://travis-ci.org/lupoDharkael/flameshot/jobs/324320559

**Comment by axelmeunier** [comment]
Hi I tried the Appimage but it does not seem to work... I does not launch. How to debug it ?

**Comment by ManuelLR** [comment]
You can launch flameshot with the `gui` option to start the capture in the moment. If you execute flameshot without option, an icon appear in the system tray notifications

**Comment by axelmeunier** [comment]
`$ ./Configure_Flameshot-4a2aecd-x86_64.AppImage --gui
the option 'gui' is not a valid option for the argument 'flameshot'. See 'flameshot --help'.`
Am I doing something wrong ?
(I can't check the system tray option cause I'm on Gnome 3.26 and no system tray anymore)

**Comment by ManuelLR** [comment]
you only need to write 
```bash
./Configure_Flameshot-4a2aecd-x86_64.AppImage gui
```

**Comment by axelmeunier** [comment]
Oh ok great ! It works alright then.
Good job ! I'll comment and ask requests in a separate post.
Thanks for your help.

**Comment by Alexander-Wilms** [comment]
I created a manifest: https://github.com/Alexander-Wilms/flathub/tree/new-pr

I'm getting this error when running, though:

org.kde.knotifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP

**Comment by Tids** [comment]
@ZetaoYang But thats not what i'm looking for.
[Gnome Software](https://user-images.githubusercontent.com/18744080/34654319-6ed4676e-f3fa-11e7-8084-bd279422e13c.png) ([and in future(?) also KDE Discover](http://www.jgrulich.cz/2017/02/14/kde-discover-flatpak-backend/)) have native flatpak support, wich means you can package your Software once, as flatpak and its available for all the Gnome (and in future KDE Plasma) users around the world, on every distro.

Appimages are no option for me. I could use the AUR, but I really would like to have a flatpak for great "3rd Party" apps like this (:

**Comment by Alexander-Wilms** [comment]
I've update the manifest at https://github.com/Alexander-Wilms/flathub/tree/flameshot
The GUI does work, I just didn't check the system tray last time.

However, due to the sandboxing, one needs to use the portal, i.e. call a dbus method. Here's a minimal example of how to do this: https://github.com/flatpak/qt-flatpak-demo/blob/master/flatpakdemo.cpp#L88

**Comment by ZetaoYang** [comment]
@Alexander-Wilms I need your help. https://github.com/flameshotapp/packages/issues/2

**Comment by incker** [comment]
> AppImage

I use Clear Linux, and it is a pity it is a lot limited in package install ways. Only native bundles and flatpak

**Comment by borgmanJeremy** [comment]
Duplicate. Will add flatpak in next release.

**Comment by incker** [comment]
Will be cool if flatpak package will be on flathub! :)
