### ISSUE TITLE
Internalize the shortcut interface, use single-key accelerators.

### ISSUE THREAD

**Issue by ripefig** [flameshot-org/flameshot#491]
The current shortcut behavior via system settings is counter-intuitive and not very discoverable.

I propose the following change:

You have one shortcut to invoke flameshot and that's it. From there, you can use customizable single key accelerators. So you press PrtSc and then "S" to Save, "C" to copy, "R" to OCR (I know this isn't a feature, but nonetheless), "B" to blur, "H" to highlight etc. All of these should be disoverable by mousing over the various buttons in the GUI. Of course, the accelerators don't have to be single key necessarily.

That way, you don't bury the shortcuts in system settings and you don't end up with unnecessary options (if you pressed a shortcut to copy a screenshot to the clipboard, why is there a "save" button? Why do you have to press enter? etc.)

Single key accelerators (essentially composable shortcuts) are terribly underappreciated outside the world of emacs and vim, but they are far more  discoverable and efficient than regular ones.

**Comment by Cardosaum** [comment]
It would be great if this feature were to be added

**Comment by borgmanJeremy** [comment]
Its now possible to bind custom hotkeys.
