### ISSUE TITLE
[Feature request]make text draggable and selectable

### ISSUE THREAD

**Issue by doraven** [flameshot-org/flameshot#492]
for example, if I typed a text, I may want to change it laterly. Can u make it draggable to move to another positon and selectable to rewrite the text content ?

But for lines, dots, arrows, just making them deletable would be enough.

**Comment by edemir206** [comment]
I find myself always trying to rearrange text after writing within my captures. Also it would be amazing to move/edit any of the items you've added not just text. Now I can see there is a "Tool settings" maybe you could move/edit the item when clicking in the "Item toolbar" and not just disappear as it happens today, or even better by clicking the item itself.

**Comment by borgmanJeremy** [comment]
Yes this is on my radar to add but it is a very large change to the underlying code. After we finish upload plugins we can look at doing this next.

**Comment by mmahmoudian** [comment]
related to #272

**Comment by thepurple** [comment]
It is implemented in the latest master, and some other new features too, change log: https://github.com/flameshot-org/flameshot/pull/1539#issuecomment-821771523

**Comment by mmahmoudian** [comment]
@thepurple What I realized while testing is that after editing (moving, increasing size, changing color) the <kbd>Esc</kbd> does not work to cancel the screenshot.

**Comment by thepurple** [comment]
@mmahmoudian it works, but behaviour is changed a bit.
If you have an active selection, active tool or opened tool settings bar it will be closed/unchecked at first. If no active tool, selection or tool settings bar, the capture will be closed.

**Comment by prof7bit** [comment]
is there already a binary somewhere to test this, maybe even a deb package? I still have version 0.10.0 and this does not seem to have it yet.

**Comment by mmahmoudian** [comment]
I closed this as it is implemented and is available in our released versions.
