### ISSUE TITLE
 Duplicated Trayicon

### ISSUE THREAD

**Issue by doraven** [flameshot-org/flameshot#493]
**Flameshot version**
Flameshot 0.6.0-5(Debian)
Compiled with Qt 5.11.1

**Describe the bug**
If I click `show trayicon` serveral times in `flameshot config` , it will create duplicated trayicons in panel.Like this:

![image](https://user-images.githubusercontent.com/15844287/54654729-22f0da00-4afa-11e9-98dc-dfcbc42e11e7.png)

**To Reproduce**

**Expected behavior**

**System Information**
Ubuntu 18.10

**Comment by AlexP11223** [comment]
The same in  POP!_OS 19.04.

The code seems correct https://github.com/lupoDharkael/flameshot/blob/master/src/core/controller.cpp#L217

Probably a Gnome/Gnome extension bug, afaik tray menu is not supported officially in the latest Gnome versions.

**Comment by borgmanJeremy** [comment]
This is resolved for me on later versions of flameshot (0.8.x) with this gnome extension. https://github.com/flameshot-org/flameshot#tray-icon

Please re-open if you experience the issue on a new version of flameshot with the extension installed.
