### ISSUE TITLE
Setting to always save as JPG

### ISSUE THREAD

**Issue by erikdubois** [flameshot-org/flameshot#496]
Is it already possible to set flameshot to always save as JPG rather than PNG.

JPG is much better for websites than PNG regarding the size of the file.

**Comment by Neyromancer** [comment]
Hi i am new here but if it is needed i can try to do this. It seems it is possible to implement by rewriting a bit code in screenshotsaver.cpp

**Comment by magnus-gross** [comment]
JPG is literally the worst lossy image format, you need to let it die already. If you do need a lossy format, use something like BPG (or any other modern lossy format) instead.

**Comment by erikdubois** [comment]
I do not care about that. I need an image with that is low in KB for the website.
I want a fast loading webpage.

**Comment by magnus-gross** [comment]
That's literally, what I was talking about.

A BPG file has about half the size compared to a JPG file of equal quality.

**Comment by Jacalz** [comment]
I think this along with the other supported formats should have an option in the configuration tool where you can set the default format, not just for JPEG.

**Comment by erikdubois** [comment]
Any prospect on the development to have the possibility to save as jpg.

**Comment by AlexP11223** [comment]
>JPG is much better for websites than PNG regarding the size of the file.

it depends on the content, sometimes png has smaller size.

![](http://lbrandy.com/assets/jpg_vs_png2.png)

**Comment by arcolinuxz** [comment]
Has anything been done about this question?
Can we / will we be able to save as jgp?
If it is never gonna be on the agenda, please tell us and close the issue.

**Comment by AlexP11223** [comment]
@arcolinuxz it's a relatively small open source project, the best way to make something happen is to implement it yourself and send PR.

**Comment by jam-2000** [comment]
> Hi i am new here but if it is needed i can try to do this. It seems it is possible to implement by rewriting a bit code in screenshotsaver.cpp

It will be awesome!!!
A lot people need JPG very much!

**Comment by erikdubois** [comment]
Follow up post - is there any development going on on this subject?

**Comment by th317erd** [comment]
It wouldn't be hard to setup a watcher script that would watch the folder flameshot saves to and automatically generate a JPG for every PNG in the folder...

**Comment by blaueente** [comment]
Don't forget the use case with ->clipboard->chat; there, the quality loss is not important at all, but nobody wants to wait for 5MB to be transmitted.

**Comment by navigante** [comment]
Yes, lossy compression format would be strongly appreciated ...

**Comment by kirjeldus** [comment]
> Don't forget the use case with ->clipboard->chat; there, the quality loss is not important at all, but nobody wants to wait for 5MB to be transmitted.

Bump. This is one of my primary uses of this software. Format/compression settings for clipboard copy would save many many mb!

**Comment by th317erd** [comment]
I must admit I am with the developers on this one. Though I have also wished at times that JPEG was supported (for whatever various platform I am using that still lives in the dark ages and doesn't support PNG) I think JPEG is a terrible format, especially for this type of thing.

It is not at all hard for anyone of you (with a little Googling) to do one of two things (or both):
1. Make a watcher script that will automatically convert the PNG files to JPEG
2. Make a watcher script that will automatically convert the clipboard into a compressed format

Both of those would likely take a seasoned developer a day or less, and would be a fun week long project for someone who isn't even familiar with coding. Go get NodeJS, find the correct modules needed to achieve this, and git r' done. Then post your work here so other people can use it.

Or, even better, add the functionality here to Flameshot via a PR, and then maybe the developers will be happy to accept work done instead of empty (and admittedly pointless) requests.

The world is changing people. JPEG is slowly dying, and just like MP3 should never have been a mainstream format anyhow. At some point we really all do need to move away from the dark ages and embrace the light of change...

**Comment by AlexP11223** [comment]
> Or, even better, add the functionality here to Flameshot via a PR, and then maybe the developers will be happy to accept work done instead of empty (and admittedly pointless) requests.

I submitted my PRs in October and they are still not merged...

> would save many many mb!

Probably not if you are not screenshotting something like photos/movies/some games. In some cases JPG can even take more space.

**Comment by michaelskyba** [comment]
> JPG is literally the worst lossy image format, you need to let it die already. If you do need a lossy format, use something like BPG (or any other modern lossy format) instead.
@magnus-gross 

How can you save a screenshot as a .bpg? Typing in ".bpg" at the end of the screenshot name just saved it as "name.bpg.png"

**Comment by borgmanJeremy** [comment]
The version on the main branch now supports jpeg saving. This will be released as 0.8 in about 1 week. Is there more to this request other than supporting jpeg?

**Comment by blaueente** [comment]
My ideal implementation would make it possible to set "JPEG" as default for clipboard (the "IT-Support"-via-Chat quick&dirty solution), and "PNG" for saving (the: "I-bother-opening-it-from-pictures-folder")

**Comment by borgmanJeremy** [comment]
@mmahmoudian @hosiet @ZetaoYang 

Any concerns with adding an option to change the clipboard to jpeg? I would have it off by default.

**Comment by mmahmoudian** [comment]
I think PNG should be the default as the JPEG image compression might screw up the quality and we get bug reports.

But I agree that having the option is good.

**Comment by hosiet** [comment]
Having JPEG is okay but I'd like to see it turned off everywhere unless the user has changed the settings.

**Comment by borgmanJeremy** [comment]
This is how i was thinking off adding it: 
![image](https://user-images.githubusercontent.com/46930769/94179193-ca726980-fe61-11ea-8ae5-bf2d863b9635.png)

**Comment by mmahmoudian** [comment]
would it be possible to define the default format in a dropdown menu. Default for clipboard, saving, uploading,...

**Comment by borgmanJeremy** [comment]
Could so something like this: and then use whatever is selected as the default for all 3 of those items:

![image](https://user-images.githubusercontent.com/46930769/94179776-9b102c80-fe62-11ea-9659-b061822b2087.png)

**Comment by hosiet** [comment]
Maybe not piling up the "General" tab. What about opening another new tab specifically handling the Image Output? We can move all related setting into the new tab.

**Comment by borgmanJeremy** [comment]
@hosiet that sounds good to me, then we could allow a different default for clipboard, saving, and imgur which I think better solves the problems outlined in this discussion.

**Comment by andrehtgti2** [comment]
Up !

**Comment by test-account-0** [comment]
I would like TIFF format without any compression.

**Comment by borgmanJeremy** [comment]
Version 0.9 now supports jpeg on clipboard. Going to leave this open because I think there is still more work to be done to customize the format for uploads / saves.

**Comment by AdamJacobMuller** [comment]
@borgmanJeremy where does the option to select the filetype for the clipboard live? I'm on MacOS and images come onto my clipboard as tiff which is... not great.

**Comment by borgmanJeremy** [comment]
@AdamJacobMuller Around here: https://github.com/flameshot-org/flameshot/blob/71d595fbcea3eac9d1aaa51f42cb53935bd9f3a7/src/utils/screenshotsaver.cpp#L43

**Comment by mmahmoudian** [comment]
@borgmanJeremy 

> Version 0.9 now supports jpeg on clipboard. Going to leave this open because I think there is still more work to be done to customize the format for uploads / saves.

Can this issue be closed as #1790 is merged?

**Comment by krlabs** [comment]
Is it possible to add a webp format?

**Comment by razvan** [comment]
Almost 6 years later this isn't working properly.
I'm on Fedora 41 (Wayland) and  have two versions of Flameshot (see below).
The Fedora package  ignores the clipboard setting and still saves the image as PNG.
The Flatpak version just doesn't save anything in the clipboard if JPG is selected.
Don't know if it's a packaging issue or a Flameshot bug.

```
$ /usr/bin/flameshot --version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.14
                                                                                             
$ flatpak run org.flameshot.Flameshot --version
Flameshot v12.1.0 ()
Compiled with Qt 5.15.10
```

JPG is (still) better for sharing. Slack for example, renders it inline while PNGs must be downloaded first.
