### ISSUE TITLE
[flameshot] .desktop file should execute 'flameshot gui' 

### ISSUE THREAD

**Issue by jose1711** [flameshot-org/flameshot#498]
**Flameshot version**
0.6.0

**Describe the bug**
Flameshot's .desktop file defaults to run `flameshot` binary providing no user feedback. The issue has been also filed with Arch Linux: https://bugs.archlinux.org/task/61286

**To Reproduce**
- In Gnome use Application menu to find Flameshot
- click the icon
- nothing happens

**Expected behavior**
Something should happen. Warning that a user should right-click the menu or a `flameshot gui` should be run instead.

**System Information**
Arch Linux 64bit

**Comment by hosiet** [comment]
I'd support using System Notification to pop up a notice on `flameshot` startup, saying that "Flameshot is now running in the background. Use whatever-kind-of-method to start screen capture.".

Of course, we also need to handle the scenario where the system D-Bus support is absent. It would also be great if we could add a configuration to enable/disable popping notice on flameshot startup.

**Comment by zeddock** [comment]
Not sure if this is related, but just trying to help a great app...
On Linux Mint 19.1 Cinnamon and first install had an icon in Notification tray.
After reboot it was gone even though I had set load at startup checkbox.

In the end I had to:
replace the autostart Exec with 
/bin/bash -c "sleep 10; flameshot &"

I am new to linux but really wanted this for work.

Thank you!

**Comment by borgmanJeremy** [comment]
There is now a popup in the systray when flameshot starts.

**Comment by jose1711** [comment]
Thank you. While I really like the new notification it still requires `topicons` (or other compatible) extension activated for Gnome users. I wonder if `flameshot` is somehow able to detect this is the case and if it's unable to place an icon in the tray it will switch to gui mode directly.
