### ISSUE TITLE
color selection not working on Ubuntu 18.10

### ISSUE THREAD

**Issue by thygesteffensen** [flameshot-org/flameshot#502]
**Flameshot version**
0.6.0-5 (Debian)

**Describe the bug**
When taking a screenshot and selecting a drawable, e.g. a square, when right-clicking, the colour selection pop-up does not show. 

**To Reproduce**
1. Take Screenshot
2. Select e.g. a square
3. Right-click to select colour

**Expected behavior**
In step 3 when right-clicking, the colour selector should appear.

**System Information**
Ubuntu 18.10, Gnome 3.30.1

**Comment by nikolayhg** [comment]
I can select a color.

System info:
* Ubuntu 18.04 bionic
* flameshot v0.6.0 Installed from [opensuse deb](https://software.opensuse.org/package/flameshot): home:tangerine :deb9-xfce-4.12 Community 
* compiled with QT 5.7.1

**Comment by fikoborizqy** [comment]
I got a same issue here, I can't select color.

**Comment by borgmanJeremy** [comment]
Can you retest this on the 0.8 release? There were many bug fixes.

**Comment by thygesteffensen** [comment]
The color selector works now. Thanks - nice update.

However, I'm no longer running Ubuntu 18.04, but 20.04 instead. I'm closing this issue, because by problem have been solved. Maybe fiko can test it on 18.04 if possible.
