### ISSUE TITLE
shortcut 'flameshot gui -p ~/Pictures/Screenshots' not working

### ISSUE THREAD

**Issue by bingoIsCoder** [flameshot-org/flameshot#503]
**Flameshot version**

Flameshot 0.5.1-1(Debian)

**Describe the bug**

set shortcut 'flameshot gui -p ~/Pictures/Screenshots' by 'ctrl + F1', when using this shortcut, there is a flameshot info 'Invalid path, it must be a real path in the system'.
but I run the cmd 'flameshot gui -p ~/Pictures/Screenshots' in terminal, it is working well

**To Reproduce**

set shortcut 'flameshot gui -p ~/Pictures/Screenshots' by 'ctrl + F1'.

**Expected behavior**

show flameshot gui.

**System Information**
Ubuntu 18.04 Mate.

**Comment by DanielChabrowski** [comment]
@bingoIsCoder 
It happens because `$HOME` or `~` is apparently not replaced/expanded so the shortcut is literally asking to open "$HOME/...". I managed to get it working by using:
```bash
bash -c "flameshot gui -p ~/Pictures"
```

**Comment by rafaelribeiroo** [comment]
> @bingoIsCoder
> It happens because `$HOME` or `~` is apparently not replaced/expanded so the shortcut is literally asking to open "$HOME/...". I managed to get it working by using:
> 
> ```shell
> bash -c "flameshot gui -p ~/Pictures"
> ```

Can u help me? I was configuring my printscreen key to run 
`flameshot gui -p /home/ribeiro/Imagens`
But flameshot returns invalid path

**Comment by DanielChabrowski** [comment]
@rafaelribeiroo Does it work from the terminal?

**Comment by rafaelribeiroo** [comment]
> @rafaelribeiroo Does it work from the terminal?

Sorry for bad question, i just restart and works as well. Thanks very much for the reply.
