### ISSUE TITLE
[Feature request]support taking fixed-size screenshot precisely

### ISSUE THREAD

**Issue by wonderbeyond** [flameshot-org/flameshot#508]
*Chrome web store* allows uploading extension screenshots of 1280x800 or 640x400. However I found it's incredibly difficult to take the exact size using Flameshot. By dragging the border, it's always bigger or smaller.

Can you rescue me by providing an input box let me specify the right size I want?

**Comment by mmahmoudian** [comment]
Related to #479

**Comment by borgmanJeremy** [comment]
This is now possible in the version 11 beta.
