### ISSUE TITLE
Why don't you add Windows build into releases page?

### ISSUE THREAD

**Issue by xahon** [flameshot-org/flameshot#509]
I just randomly found that image https://imgur.com/a/90DK6yU and completely installed working version on windows (Not mine computer. On mine I use performance-heavy shareX instead of flameshot)

**Comment by khalil2535** [comment]
I guess i know why
![upload](https://user-images.githubusercontent.com/26520106/56865366-de4c3e80-69d5-11e9-8aa5-735dce9751f6.png)

**Comment by khalil2535** [comment]
5th most contributor (has an  attractive work too) loves GNU/Linux too.

**Comment by borgmanJeremy** [comment]
Yes most of our developers are on Linux but the project is cross platform. We are working on setting up a more robust windows CI.

Any contributions our windows users can offer are welcome :)
