### ISSUE TITLE
Screen capture shortcut

### ISSUE THREAD

**Issue by mmesnjak** [flameshot-org/flameshot#51]
Is there a way to set up a keyboard shortcut for screen capture?
I mean, when I start flameshot I get screen capture options. Once it's over I still have a tray icon through which I can set up configuration but I don't see other way to trigger screeen capture than running `flameshot gui` command from the console again.
What am I missing?

**Comment by phw** [comment]
What I did is configuring a keyboard shortcut in my desktop environment (GNOME) to launch `flameshot gui`, this works quite well. Also double clicking in the tray icon works, but I find this a bit awkward.

**Comment by ZetaoYang** [comment]
@mmesnjak Currently, you can set shortcuts/hotkeys through your own desktop environment(such as Gnome, Cinnamon, Kde).

Starting from v0.7.x of the flameshot, it will add custom global shortcuts/hotkeys.
Please see [Roadmap](https://github.com/lupoDharkael/flameshot/projects).

**Comment by lupoDharkael** [comment]
As a side note: Wayland desktops wont be able to have global shortcuts (as Fedora Gnome or Ubuntu Gnome) and they need to be configured through the global shortcuts of the desktop itself. It would be nice to have tutorials in video format as they are very helpful for new users.

**Comment by indaleto** [comment]
Hi, double-clicking it's not good enough because the desktop freezes with the menu box. Conclusion, I can't take a fullscreen screenshot, except using the command line, but it's not the same thing. Maybe a delay would help to hide the menu.
