### ISSUE TITLE
Dimmed area blinks when hover mouse over GUI button

### ISSUE THREAD

**Issue by skywtchr** [flameshot-org/flameshot#517]
**Flameshot version**
Flameshot 0.6.0-9(Debian)
Compiled with Qt 5.11.3

**Describe the bug**
After selecting area for screenshot and placing mouse pointer over one of the GUI buttons.
Dimmed area around selection blinks (which means back to normal and dim again).

**To Reproduce**

- Install app, type _flameshot gui_ in console 

- Select area to get screenshot

- Hover on any GUI button and wait until description shows up

**Expected behavior**
Dimmed area around selection stays dimmed, when button description shows up.

**System Information**
Ubuntu 19.04 - Disco Dingo

**Comment by greno4ka** [comment]
Can't reproduce it with flameshot, built from commit 4261915. System ALT Sisyphus.
