### ISSUE TITLE
Flame Shot dont work in fedora 30

### ISSUE THREAD

**Issue by oarcia** [flameshot-org/flameshot#521]
**Flameshot version**

0.6.0-2.fc30
**Describe the bug**

Hi, I'm trying the app and in Fedora 30 it does not work. I launch the app and it does not work.
**To Reproduce**

Hi, I'm trying the app  the description in that icons does not work.
**Expected behavior**

**System Information**

Fedora 30

**Comment by imabug** [comment]
Works fine for me under F30/KDE

try running it from a terminal window to see what errors pop up?

**Comment by oarcia** [comment]
dont worry man,  all its ok whit Flameshot.

 thanks.

**Comment by uacode** [comment]
Hello, on Fedora with Wayland he does not work

**Comment by markatk** [comment]
Same for me with Fedora 30 in gnome with wayland. Running in command line looks like and nothing happens afterwards, process finishes immediately.
```
$ flameshot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
$ echo $?
0

```

**Comment by fernandolcardoso** [comment]
Try install QT SVG
`dnf install qt5-qtsvg`

**Comment by slobberbone** [comment]
@fernandolcardoso already installed for me and still the trouble ...

**Comment by dlj2019** [comment]
> Try install QT SVG
> `dnf install qt5-qtsvg`

Same Here... dependencies are installed but i am still facing the same issue ...

**Comment by uacode** [comment]
Looks like the **flameshot-0.6.0-3.fc30.x86_64** update has helped :)

**Comment by luzpaz** [comment]
Maybe this merits a new release?  
#463   
#591

**Comment by borgmanJeremy** [comment]
Since we have other issues tracking more specific Wayland issues and have done a release since this issue I will close this. Please feel free to open a new issue if there is still a problem in the new release that does not have an issue open.
