### ISSUE TITLE
Flameshot snap package is missing Exec command

### ISSUE THREAD

**Issue by nettum** [flameshot-org/flameshot#522]
**Flameshot version**
v0.6.0+git37.8887b4e

**Describe the bug**
Flameshot snap desktop launcher is missing Exec command and will not start from launcher:
![image](https://user-images.githubusercontent.com/798156/57283326-31e21a80-70af-11e9-9735-6c04c99126fa.png)

**To Reproduce**
1) Install flameshot via CLI `snap install flameshot-app` or Ubuntu Software
2) Search up flameshot via launcher and try launch it
3) Flameshot will not start and give error "Desktop file didn't specify Exec field"

**Expected behavior**
Flameshot should start

**Workaround until package is updated**
I fixed this by adding `Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/flameshot-app_flameshot.desktop /snap/bin/flameshot-app.flameshot %U` to the desktop launcher file located at `/var/lib/snapd/desktop/applications/flameshot-app_flameshot.desktop`

**System Information**
Description:	Ubuntu 18.04.2 LTS  
Release:	18.04  
Codename:	bionic

**Comment by grossherr** [comment]
I can confirm this, and completed the file with `Exec` lines like shown below.

> [Desktop Entry]
> X-SnapInstanceName=flameshot-app
> Name=Flameshot
> Name[zh_CN]=火焰截图
> Exec=flameshot-app.flameshot
> GenericName=Screenshot tool
> GenericName[zh_CN]=屏幕截图工具
> GenericName[pl]=Zrzuty ekranu
> GenericName[fr]=Outil de capture d'écran
> Comment=Powerful yet simple to use screenshot software.
> Comment[zh_CN]=强大又易用的屏幕截图软件
> Comment[pl]=Proste w użyciu narzędzie do zrzutów ekranu
> Comment[fr]=Logiciel de capture d'écran puissant et simple d'utilisation.
> Keywords=flameshot;screenshot;capture;shutter;
> Keywords[zh_CN]=flameshot;screenshot;capture;shutter;截图;屏幕;
> Keywords[fr]=flameshot;capture d'écran;capter;shutter;
> Icon=/snap/flameshot-app/188/meta/gui/flameshot.png
> Terminal=false
> Type=Application
> Categories=Graphics;
> StartupNotify=false
> Actions=Configure;Capture;
> 
> [Desktop Action Configure]
> Name=Configure
> Name[zh_CN]=配置
> Name[pl]=Konfiguruj
> Name[fr]=Configurer
> Exec=flameshot-app.flameshot config
> 
> [Desktop Action Capture]
> Name=Take screenshot
> Name[zh_CN]=进行截图
> Name[pl]=Zrzut ekranu
> Name[fr]=Prendre une capture d'écran
> Exec=flameshot-app.flameshot gui

**Comment by beaukinstler** [comment]
Still an issue.  I used the above config by @grossherr, and finally got it working after being pretty confused.

**Comment by NewtMa** [comment]
I have the same issue.

**Comment by borgmanJeremy** [comment]
@grossherr Do you want to submit a PR with that fix? If not I can manually do it, I just don't want to steal your credit :)

**Comment by grossherr** [comment]
@borgmanJeremy No worries, go for it

**Comment by ZetaoYang** [comment]
@borgmanJeremy I think this was fixed via yesterday new snap pakaging on github actions.
