### ISSUE TITLE
Disable startup hint

### ISSUE THREAD

**Issue by Wangwj98** [flameshot-org/flameshot#524]
![image](https://user-images.githubusercontent.com/38370513/57446281-eeda9f80-7286-11e9-8697-7bfa0165d909.png)

Every time I run flameshot, this verbose hint will pop up. It's kind of annoying. Can I disable this functionality?

**Comment by chienphamvu** [comment]
Run command: _flameshot config_
Go to General tab, uncheck "Show help message".

**Comment by Wangwj98** [comment]
You saved my life!

Chien Pham <notifications@github.com> 于2019年5月13日周一 下午3:31写道：

**Comment by greno4ka** [comment]
Maybe you can close this issue?

**Comment by AlexP11223** [comment]
@Wangwj98  You should close this issue if it's solved.
