### ISSUE TITLE
Automatically upload image and copy URL to clipboard

### ISSUE THREAD

**Issue by Kiyuubi** [flameshot-org/flameshot#528]
Is there a way to automatically upload screenshots to IMGUR (or hopefully somewhere else) and then automatically copy the URL to clipboard?

If not, could this be added?

**Comment by teryanik** [comment]
Hi @Kiyuubi @tenten8401 @rikosage @Tom4tot
I added this option to config.
Please, vote for my pull request.
[See my pull request](https://github.com/lupoDharkael/flameshot/pull/553)
