### ISSUE TITLE
Please make release for Windows 10 too. Thanks.

### ISSUE THREAD

**Issue by omkarnathsingh** [flameshot-org/flameshot#533]
**Is your feature request related to a problem?**
Please, a single feature per issue.

**Comment by pahosler** [comment]
I would also find this useful. I use flameshot for all of my screenshots. At work I am pretty much locked into Win 10, snip is ok-ish, but it's not flameshot!

**Comment by borgmanJeremy** [comment]
We now include binaries for windows on our release page and they will soon be digitally signed!
