### ISSUE TITLE
Tooltips take too long to show and sometimes does not show at all

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [flameshot-org/flameshot#539]
**Flameshot version**
0.6.0.37-g8887b4e. Compiled with QT 5.9.5

**Describe the bug**
Once I have taken a screenshot, the program surrounds the shot with icons. Initially those icons lack labels. When I hover over any of them, a tooltip pops up. However, that seems to take two seconds, by which time the baffled user may have moved the pointer to another icon, only for the same to happen - i.e. for nothing to happen - again. Worse: sometimes _no tooltip ever appears_; for, seemingly, one needs to hover at _a particular point within_ the icon. All this matters particularly because the rest of the system becomes hard to access when Flameshot is doing its thing with the screenshot.

**To Reproduce**
Please see above.

**Expected behavior**
Tooltips should appear in fewer than two seconds (0.5 seconds might be good) and their appearance should not depend on a very precise positioning of the pointer.

**System Information**
Mint 19.1 x64 Cinnamon.

The current version of Mint (1) limits the version of Flameshot to which I have access, (2) has a bug to do with tooltips that *might* be the cause of the present problem. (On 2, see [here](https://github.com/linuxmint/nemo/issues/2060) and specifically the comment that starts 'The issue is reproducible'.)

I thought I had filed a bug report about this already, against Flameshot, but I have failed to locate that report.

**Comment by borgmanJeremy** [comment]
Can you please test this on the new version 0.8? There were many bug fixes. Please also let me know if this was tested on X11 or Wayland.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. In version 0.8, cursory testing suggests the tooltips always appear but I continue to find the delay too long. Perhaps QT-based DEs can customise that delay through some global setting? I am on Mint Cinnamon, which is GTK-based.

**Comment by borgmanJeremy** [comment]
Thanks for reporting back. Personally I am okay with the delay because I find the pop-up distracting, but I did some research and it seems most ux ui designers agree with you 😁 https://ux.stackexchange.com/questions/358/how-long-should-the-delay-be-before-a-tooltip-pops-up

If @mmahmoudian @ZetaoYang @hosiet are okay with a shorter delay I will move it to 0.5s.

**Comment by mmahmoudian** [comment]
I actually in favor of shorter delay. Long delays always bugs me as I feel the software is getting in my way and I should wait before I can immediately get the answer.

**Comment by LinuxOnTheDesktop** [comment]
I favour a shorter delay but there is a complication and the complication itself has a complication. The complication is: if there is a global and user-changeable setting then the program should respect that. The complication to the complication is: trying to respect the setting might cause a problem if the setting is QT-only.

**Comment by ZetaoYang** [comment]
I'm okay with a shorter delay, move it to 0.5s is fine.

**Comment by borgmanJeremy** [comment]
@LinuxOnTheDesktop Can you test out https://github.com/flameshot-org/flameshot/pull/976/checks?check_run_id=1161099138

I usually pull the app image for easy testing. It should have the 0.5s delay.

**Comment by mmahmoudian** [comment]
For convenience, here is the link to the AppImage: https://we.tl/t-73PIEdGRaK

**Comment by LinuxOnTheDesktop** [comment]
Dear all

Thanks. I tried the appImage. Here are the results.

1) The tooltips appeared more quickly - but I think slightly too quickly. I think they need slowing by some 20%.

2) When one starts to take a screenshot, a little box saying 'tool settings' appears on the left of the screen, opposite the bigger box that tells one how to take a screenshot. That little box seems like an artefact i.e. I don't think it should be there.

Also - call this 3) - what about my point (and this is the third time I mention it) about a _global_ setting, please?

**Comment by borgmanJeremy** [comment]
1. okay ill slow it down a bit

1. That new box is a clickable button that was added in 0.8. You can click it to bring up the side menu. It was added to make using on a tablet easier.

1. Can you describe what you mean by global setting? This is not user configurable, the delay is global for the entire application.

**Comment by mmahmoudian** [comment]
@LinuxOnTheDesktop 
About your point number 2, you can press spacebar or click that button to open settings. This is useful when you want to change font of the text you are adding to the screenshot.

And about the last point, Are you suggesting that we should have a configurable delay time? Is this what you mean by "global setting"?

**Comment by LinuxOnTheDesktop** [comment]
borgmanJeremy, mmahmoudian:

Thanks. I am saying that perhaps Linux desktop environments that are based on the QT framework have a global setting - accessible to the user, through some sort of settings application - that sets tooltip delay. Please ponder my previous comments if you still don't understand me.

**Comment by borgmanJeremy** [comment]
For now I will use the new 0.6s value. Perhaps a future improvement could be integrating with the KDE global setting, but this is low priority given our other tasks.
