### ISSUE TITLE
relocation error: /usr/lib/plugins/imageformats/libqgif.so: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference

### ISSUE THREAD

**Issue by zcqzcg** [flameshot-org/flameshot#541]
**Flameshot version**
I have installed it with `sudo apt install flameshot`
Flameshot 0.6.0-9(Debian)
Compiled with Qt 5.11.3

**Describe the bug**
Not so sure what have I done with the lib*.so or something else, it's just not working anymore. I tried to remove it and install flameshot again, not worked neither. 
Cannot use `flameshot` to do it's job.

**To Reproduce**
* I have installed another app `p4merge` and it may have changed /usr/lb/libQt5*.so.5 and so on. It's from p4v-2019.1.1797168 folder and it asked to cp all the files in lib folder to /usr/lib.
```bash
ls ./lib
libcrypto.so.1.0.0  libicuuc.so.59         libQt5DBus.so.5     libQt5PrintSupport.so.5  libQt5WebKit.so.5         libQt5XcbQpa.so.5  P4VResources
libicudata.so.59    libQt5Concurrent.so.5  libQt5Gui.so.5      libQt5Sql.so.5           libQt5WebKitWidgets.so.5  libQt5Xml.so.5     plugins
libicui18n.so.59    libQt5Core.so.5        libQt5Network.so.5  libQt5Svg.so.5           libQt5Widgets.so.5        libssl.so.1.0.0
```
* Using `flameshot`in cli is not responding and when I `ctrl + c`, it returns with `flameshot: relocation error: /usr/lib/plugins/imageformats/libqgif.so: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference`.
* Using `flameshot gui` in cli and nothing happens.
* Open `FlameShot` in App Menu and using it by click, the app Icon on the status bar of desktop  would just be disappear. 

**Expected behavior**
flameshot works.

**System Information**
Ubuntu 19.04
Linux dell 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by borgmanJeremy** [comment]
It seems this is not an issue with flameshot but with a corrupted dependency. Maybe try using the snap version of flameshot so everything is isolated from the host system? Not sure how else to help since it seems related to something with your OS installation.
