### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#542]
Using my maim script, I had it so that whenever I would save a screenshot, it would add +1 to the last screenshot in the directory, is there a possibility of implementing something like this within flameshot, basically renaming numbered screenshots? 

Maim ref;
`maim -S "/home/frank/Pictures/Screenshots/Shot_$(( $(ls $HOME/Pictures/Screenshots/Shot_* | wc -l) + 1 )).gif"`

**Comment by borgmanJeremy** [comment]
Yes, this is actually the default behavior. Let me know if you have issues getting it to work.
