### ISSUE TITLE
0x0 upload script doesn't work outside of /usr/bin/

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#543]
I have my own 0x0.st script, basically uploads the selected screenshot to 0x0.st,  it works using a .desktop file which references another script which is my-uploader, it works fine.
Apart from the fact that flameshot doesn't seem to see the script when it's outside of my /usr/bin dir. I would imagine it's something to do with dir permissions? This has worked before and used to work fine but not as of late.

The script I use is also the one here; https://github.com/lupoDharkael/flameshot/issues/178#issuecomment-379376505

**Comment by borgmanJeremy** [comment]
I don't think this could be related to flameshot right?
