### ISSUE TITLE
Imgur links

### ISSUE THREAD

**Issue by madprops** [flameshot-org/flameshot#547]
Imgur links should use the https format instead of http.
Also an option to get .jpg links instead of .png would be nice, since .png images are overall bigger in size.

**Comment by li11amy** [comment]
And anothe question about imgur links. It posible just copy link to clipboard without open window od the Upload to Imgur?

**Comment by AlexP11223** [comment]
Looks the links are https now?

> since .png images are overall bigger in size

it depends on the content, screenshots of somethings that does not contain photos and so on can be smaller in png.

**Comment by borgmanJeremy** [comment]
Please track this RFC for future discussion on this topic: https://github.com/flameshot-org/flameshot/pull/955

**Comment by mmahmoudian** [comment]
At least based on some quick tests, it is now all https. Shall we close this issue?
