### ISSUE TITLE
Defining required size while taking a screenshot

### ISSUE THREAD

**Issue by spekulatius** [flameshot-org/flameshot#558]
On several occasions I require exact screenshots (e.g. for some app stores).

It would be a dream, if I could click on the width-height bubble and set the size to the desired values (for example 1280x600) by entering numbers. Then the frame should resize and I move it to fit the exact position.

**Comment by greno4ka** [comment]
Yes, that will be a quite cool feature!

**Comment by JurisMajors** [comment]
[slop](https://github.com/naelstrof/slop) does it, by allowing to simply click on the window, which automatically makes the selection rectangle fit that window. Possibly the feature can be inspired from them.

**Comment by spekulatius** [comment]
Thanks for the suggestion @JurisMajors! I usually don't aim on taking screenshots of whole windows - there are tools for this. Just any selected part is what I'm looking for really 👍️

**Comment by MichaelTunnell** [comment]
I agree with this suggestion but I would also suggest a more precise option as well.

I would like the ability to choose the size and location via the command-line parameters that way I could create a permanent capture setup that I could adjust if need be rather than adjusting every time I create a screenshot.

For example:
`flameshot gui -d 2000 -sl 1280,720,0,0`

This would create a viewport of 1280x720 and place it at the top left part of the screen. It could then be moved to wherever needed or if they know the exact location such as via xwininfo then that would be perfect.

I have recently found that flameshot is my go to except for in cases like this . . . even the lack of GUI control of the delay, the editing tools are so useful that I typically use it but I would love to have size and location (-sl) control

**Comment by borgmanJeremy** [comment]
This is now possible in the version 11 beta.

**Comment by spekulatius** [comment]
Thank you @borgmanJeremy

**Comment by PlatonB** [comment]
> This is now possible in the version 11 beta.

@borgmanJeremy I don't see that in the current version.

**Comment by PlatonB** [comment]
Are there plans to support exact sizing of the screenshot area via frontend?

**Comment by mmahmoudian** [comment]
@PlatonB I assume by "frontend" you mean "GUI"? It has been discussed before read the following:

- #2014 
- #1509

**Comment by PlatonB** [comment]
I suppose a good solution is to make a [popover](https://docs.gtk.org/gtk4/class.PopoverMenu.html)-like menu that allows to resize on the fly.

![flameshot_proposal_popover](https://user-images.githubusercontent.com/25541767/158799936-f129568b-5ee4-40b6-9cae-5c884923a714.png)

**Comment by mmahmoudian** [comment]
I think it does not fit the current UI style of Flameshot to have a modal window, but perhaps it would fit more if right-clicking on the dimension button opens the sidebar and shows the fields. The right-clicking is currently the method to open settings for every tool.

**Comment by mariusa** [comment]
So, in order to force a screenshot size of 1000x800 px, one would launch frameshot with
```flameshot gui --region 1000x800```
and that would allow moving the fixed-size rectangle on the screen with the gui, but not resizing it, then take the screenshot?

**Comment by mmahmoudian** [comment]
@mariusa almost. You got the format wrong. You should follow the correct format. Either checkout `flameshot gui --help` or checkout the output of `flameshot gui --print-geometry` which after your selection will output your selected region in the correct format.

**Comment by mariusa** [comment]
@mmahmoudian thanks, but it still doesn't work:

`flameshot gui --region 1000x800`  or `flameshot gui --region 1000x800+0+0` simply take a screenshot, they don't allow user to move the (fixed) rectangle around and then take screenshot.

**Comment by mmahmoudian** [comment]
@mariusa As far as I've tested (even now) it works just fine. Please file a complete bug report if
- you have the latest version
- you have for sure used `flameshot gui --region 1000x800+0+0` without further arguments like `--accept-on-select`
