### ISSUE TITLE
flameshot crashes: locale related?

### ISSUE THREAD

**Issue by jarss** [flameshot-org/flameshot#563]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.12.1

**Describe the bug**
GUI application crashes when trying to save, upload to imgur, or other functions. Copy to clipboard still works. 

Running flameshot from the terminal ($ flameshot) and then trying to capture produces this input: 

QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

I assume only the last part is what's important here, from what I saw online this can be locale related, but I reset my locale to default. 

Here are my locale settings, since this might be the issue (not sure):
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

If you see an issue with the above let me know, I don't know what it is...

**To Reproduce**
Launching the app, trying any of the saving functions.

**Expected behavior**
This used to work for me, possible before locale changes (I was trying to change the date format). I used to be able to save and upload to imgur.

**System Information**
4.19.49-1-MANJARO KDE Plasma 5.15.5

**Comment by jansol** [comment]
Same here, flameshot started crashing at launch when I changed the date+time format in Plasma to something other than the system locale. Works fine now that I reverted the datetime format change and changed the system locale instead.

**Comment by spotlightishere** [comment]
Thanks for noting that important tidbit! Working through, I figured out my `LC_TIME` was `en_GB.UTF-8` for 24-hour purposes. `~/.config/plasma-localerc` read likewise to confirm.
In my case, I needed to uncomment that locale in my `/etc/locale.gen` and `locale-gen`. It appears KDE struggles to set them all if one is missing?

**Comment by luzpaz** [comment]
@spotlightishere Is this a KDE bug then ?

**Comment by jarss** [comment]
This is KDE related, but I'm not sure it's a KDE bug...

At any case, it sucks I have to change back to a time format I'm not comfortable in (think about this for a minute, the way you describe time is everywhere, it's your entire organizational system) to use an app. 

Is there a KDE solution or a link as a reference perhaps?

**Comment by dougiepunk** [comment]
I'm encountering this exact same issue in Ubuntu 20.04 LTE running Plasma KDE. Any solutions yet?

**Comment by borgmanJeremy** [comment]
Can you upload the exact step by step process to create the bug on plasma? That will help me track it down much more quickly.

**Comment by hosiet** [comment]
I have a quick test case: consider unsetting all locale-related environment variables and run "flameshot" from terminal: flameshot should crash. This may or may not share the same origin as the original report but worth trying.

**Comment by krivahtoo** [comment]
I had the same issue,
running `LC_ALL=C flameshot`  solved the issue

**Comment by dougiepunk** [comment]
Thanks krivahtoo . That works!

**Comment by luzpaz** [comment]
Maybe this should be mentioned in the README ?

**Comment by dougiepunk** [comment]
I've regalised there there is an issue with using LC_ALL=C flameshot. The saved file is locked, so you can't import it into things like Google docs (at least directly).

**Comment by jmontoyaa** [comment]
@spotlightishere solution works well in KDE

**Comment by NirmalManoj** [comment]
@borgmanJeremy I don't understand why this and similar issues from Manjaro/Arch users were closed without finding a permanent solution.

When I used Manjaro Xfce, flameshot used to work without any problems. For a while now, I have been using Manjaro KDE, and there's this issue. However, it works when I open a terminal and run `LC_ALL=C flameshot`.

**Comment by NirmalManoj** [comment]
I would love to help if flameshot developers want any details to fix this.

**Comment by borgmanJeremy** [comment]
The reason it's been closed is every time we look into it, the root cause is Arch/Manjaro users do not properly set their locales.

**Comment by NirmalManoj** [comment]
> The reason it's been closed is every time we look into it, the root cause is Arch/Manjaro users do not properly set their locales.

@borgmanJeremy I installed Manjaro KDE using the standard 'erase the disk and install'(or similar) option in Calamares. If this is a fault of the users, it would be helpful to many users if the fix for this gets added to the [Flameshot page in ArchWiki](https://wiki.archlinux.org/title/Flameshot).

Also, I couldn't find any proper fix except running Flameshot with the command in the terminal every time I reboot. Could you please share if there is a better solution(how to set locales properly)?

**Comment by NirmalManoj** [comment]
Here it is.
```
LANG=en_IN
LC_CTYPE="en_IN"
LC_NUMERIC=en_IN
LC_TIME=en_IN
LC_COLLATE="en_IN"
LC_MONETARY=en_IN
LC_MESSAGES="en_IN"
LC_PAPER=en_IN
LC_NAME=en_IN
LC_ADDRESS=en_IN
LC_TELEPHONE=en_IN
LC_MEASUREMENT=en_IN
LC_IDENTIFICATION=en_IN
LC_ALL=
```

**Comment by borgmanJeremy** [comment]
![image](https://user-images.githubusercontent.com/46930769/136039208-f6b82a87-afa7-49a3-b6b5-cf64f185f0b3.png)
I cant replicate the issue

**Comment by NirmalManoj** [comment]
@borgmanJeremy I installed flameshot from snap, would that make a difference?

**Comment by NirmalManoj** [comment]
Should I try installing from community? https://archlinux.org/packages/community/x86_64/flameshot/

**Comment by borgmanJeremy** [comment]
Yes it might. Since you are on manjaro (arch) I recommend you install via pacman. The main advantage our snap package provides is it allows users on older stable LTS distros to keep the latest version. Since you are on a rolling release there is no need for the snap.

**Comment by NirmalManoj** [comment]
@borgmanJeremy I installed the community version. It seems to work. Configuration opens, and there's no crash so far. Thank you so much for the quick help.

I tend to download from snap because I feel it's more up-to-date for most apps, generally. Definitely a good idea for Flameshot.
