### ISSUE TITLE
allow multiple actions

### ISSUE THREAD

**Issue by ngmariusz** [flameshot-org/flameshot#565]
current behaviour 
you can OR save as file OR copy to clipboard OR pin ...etc 

expected 
you can play with gui and use shortcuts until you ESC / ENTER / X 
(also you can save multiple files while progress with editing your selected area)

**Comment by halbrd** [comment]
This would be a very nice feature to have. I'd like every screenshot I take to be saved to a folder, but also have them copied to my clipboard or uploaded to imgur.

**Comment by AlexP11223** [comment]
yeah, also (or as a simple workaround) it would be good to be able to open any image in the GUI (useful even just for editing, in GIMP it's not very easy to draw arrows, etc.) + a menu item to open the last screenshot, like in Monosnap on Windows.

**Comment by bwplotka** [comment]
Hello, any update on this? (: any workaround? 

I would love to keep my screenshot in the local directory AND also have it in the clipboard..

**Comment by borgmanJeremy** [comment]
In 0.9 (and I think in 0.8), there is an option to "save image after copy" if this is selected the image will be saved when you hit copy.
