### ISSUE TITLE
Text improvement and selection tool

### ISSUE THREAD

**Issue by yorard123** [flameshot-org/flameshot#571]
Hi,

I think it would be great if the text tool could be improved. I think there are missing the basic format operations like:bold text, change the family, underline, Strikethrough and so on.

Moreover, I think it would be nice to have a kind of selection tool that allows to move the position of the additions such as arrows, text, squares, lines...

Thanks,

**Comment by AlexP11223** [comment]
Actually, you can set text font, bold, etc. in the side panel (press space bar), but it applies to the whole text element.
