### ISSUE TITLE
Ability to change blur intensity

### ISSUE THREAD

**Issue by UltraFuture7000** [flameshot-org/flameshot#575]
I find that the default blur intensity is a bit too low. Perhaps it would be nice if we could change the blur intensity?

**Comment by Tset-Noitamotua** [comment]
+1

May be with ALT + Mouse Wheel as shortcut to control blur intensity?

a pixeled blur would be nice, too. Like this one:
![image](https://user-images.githubusercontent.com/5635462/64177844-998f5300-ce60-11e9-893b-a447128c5232.png)

**Comment by AlexP11223** [comment]
Yeah, currently it is not blurry enough if you want to make sure that something is not readable, needs to be applied twice at least.

**Comment by lucgiffon** [comment]
Actually you can control the blur intensity with the mouse wheel already.

**Comment by AlexP11223** [comment]
@lucgiffon no, it controls the thickness value available to all tools, but as you can in the source code it is not used.

https://github.com/lupoDharkael/flameshot/blob/master/src/tools/blur/blurtool.cpp#L49

**Comment by lucgiffon** [comment]
Oh yes, you are right. I don't know why it felt like it has an effect on the blur intensity. Validation bias I guess ^^

**Comment by borgmanJeremy** [comment]
Added in new release with pixelate tool.
