### ISSUE TITLE
截图加水印？

### ISSUE THREAD

**Issue by omaidb** [flameshot-org/flameshot#577]
能否添加一个功能，截图加水印……盗图现象严重

**Comment by hosiet** [comment]
Hi @omaidb , please consider editing the issue and rewrite your question in English. Thanks!

**Comment by AkariMarisa** [comment]
> 能否添加一个功能，截图加水印……盗图现象严重

Can we add a feature that we can add watermark on screenshot?

Actually I don't think this is necessary.

**Comment by borgmanJeremy** [comment]
Thank you for the suggestion. This is a duplicate of #158 but it is something we will consider!
