### ISSUE TITLE
If hovering over buttons during a screenshot selection area, flameshot's background overlay will flicker in and out

### ISSUE THREAD

**Issue by adrianocr** [flameshot-org/flameshot#583]
**Flameshot version**
0.6.0

**Describe the bug**
When the capture overlay/view is open, if you hover over any of the buttons/icons to see their label and then hover over another button, flameshot develops a constant flicker of the screen about 1-2 secs apart. 

Interestingly enough I tried to use Peek to record a gif of it happening, but if Peek is recording flameshot is somehow magically fixed. If I close Peek though, the flicker issue returns. 

**To Reproduce**
Use flameshot to take screenshot of a rectangular area and then hover over the buttons to see their labels. Once a label has appeared, hover over to another button. You will notice that the translucent black overlay that flameshot applies over the rest of the screen flickers in and out every 1-2 second while you're hovering the mouse around. 

**Expected behavior**
No flicker of the black background overlay.

**System Information**
Fedora 30, latest Gnome DE.

**Comment by Victolabs** [comment]
Also having this issue on POP!_OS 19.04.

**Comment by AlexP11223** [comment]
the same issue in master too, POP!_OS 19.04.
