### ISSUE TITLE
The font of text added to the screenshot is too small

### ISSUE THREAD

**Issue by yanwenxiong** [flameshot-org/flameshot#584]
When I use flameshot, I can add text to the screenshot, but the font size of the text is too small to recognize. So I want to suggest that it should can figure the font size of the text

I can give you an example: the text on the screenshot is red, but it is so small
![image](https://user-images.githubusercontent.com/12817624/61615284-35da0d80-ac98-11e9-8d46-530e1c285262.png)

**Comment by hashratez** [comment]
You can use control+scroll with your mouse to change text size, but the next element will also get enlarged or shrank so then you need to scroll back.  Not the best answer but it works.

**Comment by Niush** [comment]
Isn't there Text available in Ubuntu ?

**Comment by DesertStars** [comment]
> Isn't there Text available in Ubuntu ?

It should be available, it was added in v0.6.0. If you installed flameshot from your distro's repository
their version might be outdated.
https://flameshot.js.org/#/changelog

**Comment by hubutui** [comment]
@hashratez Yes, it works. It would be great if we could set a default font size.

**Comment by TheLaluka** [comment]
I think this issue should be closed, it's just in the doc (help box of flameshot..)
I found this issue while trying to figure out if we can change the text size...
The answer is simple, RTFM... We're all too lazy I guess. Maybe flameshot should have a popup with the help menu displayed on first launch ?

**Comment by yanwenxiong** [comment]
Can you show me how to change the font size? I didn’t find any configuration to change the size.
I would appreciate it.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: TheLaluka <notifications@github.com>
发送时间: Thursday, September 5, 2019 7:27:09 PM
收件人: lupoDharkael/flameshot <flameshot@noreply.github.com>
抄送: tjuxiong <yanwenxiong@outlook.com>; Author <author@noreply.github.com>
主题: Re: [lupoDharkael/flameshot] The font of text added to the screenshot is too small (#584)


I think this issue should be closed, it's just in the doc (help box of flameshot..)
I found this issue while trying to figure out if we can change the text size...
The answer is simple, RTFM... We're all too lazy I guess. Maybe flameshot should have a popup with the help menu displayed on first launch ?

―

**Comment by TheLaluka** [comment]
Quoting @hashratez 
> You can use control+scroll with your mouse to change text size. 

![image](https://user-images.githubusercontent.com/7013722/64339518-8c02d600-cfe4-11e9-8e89-dfb35a8380c9.png)
![image](https://user-images.githubusercontent.com/7013722/64339552-9fae3c80-cfe4-11e9-913a-6105c028fc7e.png)

**Comment by yanwenxiong** [comment]
Thank you very much.
I think maybe flameshot should add a help instruction, or it is hard to find out how to change the font size.
Thank you again

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: TheLaluka <notifications@github.com>
发送时间: Thursday, September 5, 2019 7:54:15 PM
收件人: lupoDharkael/flameshot <flameshot@noreply.github.com>
抄送: tjuxiong <yanwenxiong@outlook.com>; Author <author@noreply.github.com>
主题: Re: [lupoDharkael/flameshot] The font of text added to the screenshot is too small (#584)


Quoting @hashratez<https://github.com/hashratez>

You can use control+scroll with your mouse to change text size.

[image]<https://user-images.githubusercontent.com/7013722/64339518-8c02d600-cfe4-11e9-8e89-dfb35a8380c9.png>
[image]<https://user-images.githubusercontent.com/7013722/64339552-9fae3c80-cfe4-11e9-913a-6105c028fc7e.png>

―

**Comment by TheLaluka** [comment]
Bruh, I just gave you the flameshot help instructions...
On the tray icon, right click, infos
![image](https://user-images.githubusercontent.com/7013722/64339964-60342000-cfe5-11e9-856b-cc3345675ad7.png)

**Comment by Yajo** [comment]
Yikes, hard to find for me too. Even more in Gnome where I don't have the tray. It would be helpful while using the screenshot tool itself to have instructions somewhere.

**Comment by AndydeCleyre** [comment]
What?! Adding text can be done as of `0.6.0`? How can I find it? I'm using Arch's official `0.6.0-3` package, and it looks like this:

![image](https://user-images.githubusercontent.com/1787385/76104866-129f6c80-5fa2-11ea-8307-de45025be5e3.png)

**Comment by reubenfirmin** [comment]
Please add configuration to the config dialog.

a) I don't have a mousewheel so can't change it on the fly
b) Pressing space for the sidebar doesn't seem to have a size adjustor, doesn't let you preview the font, is awkward to navigate with a large number of system fonts

**Comment by borgmanJeremy** [comment]
The sidebar is now more accessible on tablets (there is a discrete button). That in addition with the mousewheel scroll is sufficient for resizing the text.
