### ISSUE TITLE
Add digital tagging like shutter screenshot editor?

### ISSUE THREAD

**Issue by imaojun** [flameshot-org/flameshot#587]
**Is your feature request related to a problem?**

I need to add a comment when I need a screenshot, and I want to guide the user step by marking the number. I can use the number 12345, but this is not eye-catching. 
I want to have a digital tagging feature that will be added to the screenshot when I click and will be incremented each time.

Since the shutter has been removed from my system, I can't take a screenshot of this digital marker feature. But I found a similar picture from Google. Just like the digital sign of the blue arrow in the image below.

![image](https://user-images.githubusercontent.com/28778042/62177505-b3c4a580-b377-11e9-856f-97d522da6f5d.png)

**Comment by nestorrojas07** [comment]
This functionality would be very useful.

**Comment by rk-p2p** [comment]
@lupoDharkael please?

**Comment by borgmanJeremy** [comment]
This will be in the 0.8 release and can be tested on the master branch.
