### ISSUE TITLE
Feature request: Arrows with ordered numbers

### ISSUE THREAD

**Issue by madjoe** [flameshot-org/flameshot#594]
It would be an awesome addition to an existing arrow feature if it could include a circle with an automatically ordered number and the beginning of the arrow. This feature could be an optional selection within the config for arrows only ("Ordered numbers: YES/NO"). In case Ordered numbers is set to ON, the arrow should be thinner, as per the following image:

![Similar feature from other tools](http://crossgl.com/alshot/crossgl-asc-annotations.jpg)

The Use Case could be an easier/faster UX for bug reporting... first click here, then here, etc...

Similarly, there could be an option for the current custom Text: "Callout Annotation (YES/NO)", as per image above. Also, a zoomed detail would be also useful as an option.

**Comment by borgmanJeremy** [comment]
The upcoming release will have incrementing number bubbles like greenshot. I think that with our arrow tool can accomplish this. Thanks for the feedback!

**Comment by madjoe** [comment]
I just tested the new release and it feels so much more usable than before.
Thank you for implementing this, good job!

P.S. `Callout annotations` and `zoomed details` are not that important, but would be awesome assets if you ever decide to extend flameshot's set of features.
