### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by pafri** [flameshot-org/flameshot#596]
Hi,
as it is open for several months, I would like make a reminder, that the localization file zipped in the archive was already loaded, but remained unnoticed(?).
See the attachment.
[Flameshot_Internationalization_cs.zip](https://github.com/lupoDharkael/flameshot/files/3538531/Flameshot_Internationalization_cs.zip)

**Comment by luzpaz** [comment]
@pafri do you making a Pull Request ?

**Comment by pafri** [comment]
No.
