### ISSUE TITLE
CTRL + Mouse Wheel to browse through history (undo/redo changes)

### ISSUE THREAD

**Issue by Tset-Noitamotua** [flameshot-org/flameshot#601]
I really love the feature of using the mouse wheel to change the thickness of active tool. This makes working very efficient. 

To make work even more efficient it would be great to modify this behavior by holding CTRL key while using mouse wheel to go back in history of edits.

CTRL + Mouse Wheel UP --> undo edits/changes
CTRL + Mouse Wheel Down --> redo

**Comment by DesertStars** [comment]
I agree that an option to redo would be nice, but not sure if I agree on CTRL + Mouse Up/Down. CTRL+Y seems like a better idea since it's universally accepted and CTRL+Z is already in the key bindings. Maybe make the key bindings customizable and add that option to Configuration?

**Comment by borgmanJeremy** [comment]
custom keyboard shortcuts are now available in version 0.9
