### ISSUE TITLE
Translation to transifex or weblate

### ISSUE THREAD

**Issue by troe** [flameshot-org/flameshot#603]
Why not post files for translation to one of the translation services:

1. Transifex [transifex.com](https://www.transifex.com/)

2. Weblate [weblate.org](https://weblate.org/)

**Comment by borgmanJeremy** [comment]
Weblate looks really interesting. Do you know how it hooks into our .TS files?

**Comment by borgmanJeremy** [comment]
@ZetaoYang  and @mmahmoudian set up a weblate project!

https://hosted.weblate.org/projects/flameshot/flameshot/
