### ISSUE TITLE
Is windows build broken?  No download link at ci.appveyor.com

### ISSUE THREAD

**Issue by radoeka** [flameshot-org/flameshot#610]
**Flameshot version**
Not really applicable

**Describe the bug**
There is no download link for the windows version, at https://ci.appveyor.com/project/lupoDharkael/flameshot

**To Reproduce**
Goto https://ci.appveyor.com/project/lupoDharkael/flameshot 

Follow the link Environment: QT=C:\Qt\5.9\msvc2015, PLATFORM=x86

At the bottom of the page, there is no download link.

**Expected behavior**
At the bottom of the above mentioned page there should be a download link.

**System Information**
Windows 10

**Comment by AlexP11223** [comment]
afaik it's a Linux-only app https://github.com/lupoDharkael/flameshot/issues/29

And I don't think it makes sense to port flameshot on Windows, there are better alternatives: ShareX, Monosnap, ...

**Comment by radoeka** [comment]
It's build with QT as such it will run on Windows as well.
The issue being referred to #29 mentions that it is available for Windows :)

The current build for Windows finishes, but the zip is not downloadable :(
![image](https://user-images.githubusercontent.com/2937666/65829749-cd676800-e2a8-11e9-9556-6fbe42ec74c5.png)

Is just the link not working?
https://transfer.sh/hEFFF/flameshot_0.6.0_win_x86.zip

**Comment by HW71** [comment]
According to PR #732 the currently used sharing provider "transfer.sh" is not working anymore, and because of this all the download links won't work - even if the used build is "green" and a recent one. :-(

**Comment by MadddinTribleD** [comment]
I changed #732 to include the artifacts in the appveyor build.   
So if this is still relevant you could get if from there.

It will only be up for 6 month thought. (Artifacts retention policy)

**Comment by borgmanJeremy** [comment]
In 0.8 (coming this week) we will host .msi and zip installers on github releases.
