### ISSUE TITLE
color and thickness should be configureable on screen

### ISSUE THREAD

**Issue by fikrillah** [flameshot-org/flameshot#611]
hi, i would like to purpose a feature please.

so, if you're using a tablet, you have no access to a mouse, the only input you have is touchscreen, and it seems like an issue that you cannot set thickness and color of the tool you are using. so, maybe three's should be a contextual menu that appears when you select certain tool, for example, when we're using drawing tool, there should be an slider for thickness and color selector.
or maybe, there's more elegant way to do that...

**Comment by fikrillah** [comment]
together with #613 and #612 , we can ditch this ugly screen, so users don't have to read those text
![Screenshot from 2019-09-23 18-27-50](https://user-images.githubusercontent.com/48489341/65422177-f19df180-de2f-11e9-8ca2-f2772f10ee9f.png)

**Comment by borgmanJeremy** [comment]
There is a sidebar button now to access the menu previously only accessible with spacebar.
