### ISSUE TITLE
seperate area and whole screenshot

### ISSUE THREAD

**Issue by fikrillah** [flameshot-org/flameshot#612]
hi, i would like to purpose a feature please.

so, if you are on tablet, there's an issue if you want to take a shot of whole screen, because currently, the only way to do that is with keyboard, which is not available on tablet, that's why i purpose this issue.

here's an ui mockup to give you a clear idea
![Screenshot from 2019-09-23 17-56-42](https://user-images.githubusercontent.com/48489341/65421637-6cfea380-de2e-11e9-8cb3-1af19f7924ce.png)

**Comment by fikrillah** [comment]
together with #611 and #613 , we can ditch this ugly screen, so users don't have to read those text
![Screenshot from 2019-09-23 18-27-50](https://user-images.githubusercontent.com/48489341/65422177-f19df180-de2f-11e9-8ca2-f2772f10ee9f.png)

**Comment by AlexP11223** [comment]
What do you mean? Which OS are you using?

There is a tray icon already.

If you are on Gnome, the tray area was removed in the last versions of Gnome unless you imstall extension like https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by fikrillah** [comment]
that's gnome and the screenshot is created based on that extension. 
my point is, please give it option to take area screenshot and whole screenshot on that app-indicator menu, 

because currently we got this
![Screenshot from 2019-10-02 19-22-40](https://user-images.githubusercontent.com/48489341/66043694-0c681880-e54a-11e9-8ebc-747397b5b903.png)
and this
![Screenshot from 2019-10-02 19-23-16](https://user-images.githubusercontent.com/48489341/66043766-45a08880-e54a-11e9-83ef-909b405ddd48.png)
if you are on tablet, you don't have access to enter key, it means you cant take the whole screen on tablet...

**Comment by AlexP11223** [comment]
There is already Open Launcher menu item in the current master (not yet released) which opens this window:

![](https://i.imgur.com/9RRdkC9.png)

**Comment by borgmanJeremy** [comment]
#931
