### ISSUE TITLE
toggle button for sidepanel should be on screen

### ISSUE THREAD

**Issue by fikrillah** [flameshot-org/flameshot#613]
hi, i would like to purpose a feature please

in tablet you don't have access to keyboard.
currently to show side panel, you have to press space bar which is not available on tablet. so there's no way to have side panel on tablet.

so, to make side panel accessible to tablet user, there should be toggle button for it on screen

**Comment by fikrillah** [comment]
together with #611 and #612 , we can ditch this ugly screen, so users don't have to read those text
![Screenshot from 2019-09-23 18-27-50](https://user-images.githubusercontent.com/48489341/65422177-f19df180-de2f-11e9-8ca2-f2772f10ee9f.png)

**Comment by AlexP11223** [comment]
I submitted PR adding this feature. #631
