### ISSUE TITLE
No indicator icon shown (Ubuntu 19.04, Gnome 3.32.1, multiple indicator extensions tried)

### ISSUE THREAD

**Issue by detly** [flameshot-org/flameshot#615]
**Flameshot version**
0.6.0-9 installed via apt.

**Describe the bug**
On Ubuntu 19.04 (upgraded from 18.04)/Gnome 3.32.1, there is no indicator icon and so I can't use Flameshot (easily). Other indicator icons appear (Nextcloud, Slack).

**To Reproduce**
Install Flameshot. Install either `gnome-shell-extension-appindicator` via apt, or the [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) Gnome shell extension and activate them. Add Flameshot to the list of startup applications if it's not there already. Reboot.

**Expected behavior**
I would expect to see the Flameshot icon amongst the indicator icons.

**System Information**
Ubuntu 19.04, Gnome 3.32.1. Running under X11. Note that this was not a clean install, so maybe I removed other packages that are needed to make this work. If that's the case, I'd just suggest documenting them in the install instructions.

In the past, I have had this work sporadically - that is, Flameshot's icon would sometimes appear and sometimes not. I believe this was due to a bug in Gnome's extension re-enabling code upon screen unlock. However, this time around I've tried the Alt-F2 + R trick to restart the shell, rebooting, etc. Nothing seems to bring Flameshot back.

Running `flameshot gui` from a terminal launches the screenshot interface successfully.

**Comment by AlexP11223** [comment]
It works fine for me in PopOS 19.04 (based on Ubuntu).

**Comment by detly** [comment]
@AlexP11223 What extensions are you using for indicators?

**Comment by AlexP11223** [comment]
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by detly** [comment]
Yep, tried that one. No luck.

**Comment by solorvox** [comment]
I had similar problem on Mint 19 using cinnamon.  I noticed the process was running but I had no tray icon.  As a workaround I added a delay on the start-up of 2 seconds and that seems to have helped.  

https://i.imgur.com/BwEjyL6.png

**Comment by IAmVisco** [comment]
Can confirm that icon is missing on Ubuntu 19.10 Gnome 3.34.0 as well but everything works just fine.

**Comment by enolive** [comment]
Happens for me as well. 
@solorvox workaround with adding a delay helped, though.

I needed to edit the desktop entry under ~/.config/autostart by hand as there seems to be no visual editor for this in Ubuntu 18.04.

```
[Desktop Entry]
Name=flameshot
Icon=flameshot
Exec=flameshot
Terminal=false
Type=Application
X-GNOME-Autostart-Delay=2
X-GNOME-Autostart-enabled=true
```

**Comment by ebdavison** [comment]
Just upgraded to Fedora 31 and I can confirm same issue with to appindicator/icon.  Worked fine with Fedora 30.  I can properly run `flameshot gui` and `flameshot config`.

```
$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.12.4
```

**Comment by joebell1329** [comment]
I can confirm the same issue on Arch.

Flameshot: v0.8.3
Kernel: Linux 5.8.13-arch1-1
gnome-shell-extension-appindicator: 34
Gnome: 3.38.1

**Comment by borgmanJeremy** [comment]
@joebell1329 This worked on a fresh endeavor install for me if I installed the extensions linked in our readme https://flathub.org/builds/#/builders/12/builds/3503 

There was a change in gnome 3.38 that caused this, but it is expected behavior from gnome-shell's point of view.

![image](https://user-images.githubusercontent.com/46930769/95334536-def82e00-0873-11eb-88c1-5b7fb51fa545.png)
