### ISSUE TITLE
Sway Qt5 error: Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by patbel-pwr** [flameshot-org/flameshot#619]
**Flameshot version**
Flameshot v0.6.0

**Describe the bug**
Flameshot on Sway window manager start normally, but trying to create screenshot displays information: 
"Flameshot info
Unable to capture screen"

In journalctl:
wrz 30 13:29:23 sandworm flameshot[28606]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**To Reproduce**
Install flameshot in sway I guess, click on flameshot icon.

**Expected behavior**
See error message from flameshot and warnings in journalctl

**System Information**
EndeavourOS Linux x86_64 (arch based)
Kernel: 4.19.75-1-lts 
WM: sway

**Comment by blaggacao** [comment]
I found: https://forum.qt.io/post/461097
>>qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

>This means your window tried to grab focus in the compositor, which is not allowed in wayland. Don't create a bug for it, there's nothing we can do.

here my logs:
```log
dar@pc3:~$ flameshot
Using Wayland-EGL
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by vvrein** [comment]
I have no clue about C++, but may it be a decision in borrowing some code from 
https://wayland.emersion.fr/
Select region
https://github.com/emersion/slurp
Grab image
https://github.com/emersion/grim

But this would work only for wlroots based WM

**Comment by vvrein** [comment]
Ok, all wayland support progress seems goes here https://github.com/lupoDharkael/flameshot/issues/446

**Comment by manos-mark** [comment]
A possible workaround for this issue
 `qt.qpa.wayland: Wayland does not support QWindow::requestActivate() `
 Execute the python script using xcb platform
For example:
`python test.py -platform xcb`

**Comment by patbel-pwr** [comment]
@manos-mark thnk you for reply! 
Is this workaround for devs or users? As a user I don't see how I could implement this...

**Comment by manos-mark** [comment]
> @manos-mark thank you for reply!
> Is this workaround for devs or users? As a user I don't see how I could implement this...

Sorry i should mention that, it is for developers.

**Comment by borgmanJeremy** [comment]
Sway support was just added in #1272
