### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by AlexP11223** [flameshot-org/flameshot#623]
How about opening a Patreon page for donations as an alternative to Paypal and Bitcoin?

It would be more convenient for some people because Paypal is not available in some countries, does not accept some cards, etc. And Bitcoin is too complex.

Also it would be recurrent payments during some long period, which is usually better for the project than one-time donations because people are more willing to pay small amounts each month.

**Comment by borgmanJeremy** [comment]
Right now we are not really setup to take payments as we are a diverse distributed team.
