### ISSUE TITLE
Desktop background is copied instead of Firefox browser window

### ISSUE THREAD

**Issue by perlun** [flameshot-org/flameshot#626]
**Flameshot version**
```
$ flameshot -v
Flameshot 0.6.0+git20190714-1(Debian)
Compiled with Qt 5.11.3
```

**Describe the bug**
The desktop background is copied instead of the browser window. Only verified with Firefox.

**To Reproduce**
Run `flameshot gui`. _Sometimes_, the appearance of Firefox changes to display the desktop background instead of the browser window:

![image](https://user-images.githubusercontent.com/630613/66035260-774a2d00-e513-11e9-825c-bcfbe111fca8.png)

Running it again (perhaps after switching windows back/forth) typically works well.

I don't know if it's a Firefox-specific bug, I only use Firefox for my everyday browsing. Interestingly enough, I saw it manifest with [peek](https://github.com/phw/peek) also earlier today; some frames contained (parts of) the background instead of the browser window.

Could it be a bug in the graphics driver? Using an nVidia graphics card with `nvidia-driver` version `418.74-1`.

**Expected behavior**
The browser window should be displayed as normal.

**System Information**
Debian Buster/Bullseye, running Cinnamon as desktop environment.

**Comment by AlexP11223** [comment]
> I saw it manifest with peek also earlier today; some frames contained (parts of) the background instead of the browser window.

I had the same issue with peek several time when it was running with `-b ffmpeg`, but flameshot is fine so far.

PopOS 19.04, nvidia drivers 435.

**Comment by borgmanJeremy** [comment]
Going to close this now since I think it is outdated and peek also had the issue.

**Comment by perlun** [comment]
@borgmanJeremy @AlexP11223 I managed to find the solution to this. Posting it here in the hope that it might help others running into the same problem.

I installed the [SimpleScreenRecorder](https://www.maartenbaert.be/simplescreenrecorder/) tool a couple of month sago. Interestingly enough, it gave me this warning on startup:

![image](https://user-images.githubusercontent.com/630613/108469370-c58ad800-7290-11eb-993a-1b9015cc5e8e.png)

In my NVIDIA X Server Settings, this is the setting that should be unchecked for this to work properly:

![image](https://user-images.githubusercontent.com/630613/108469467-f2d78600-7290-11eb-8fe1-faf997a1bee9.png)

With these changes in place, **Flameshot now works flawlessly for me**. :pray: 

@borgmanJeremy - in case you are interested in adding a warning/notice in Flameshot as well, here is the code in SimpleScreenRecorder for doing this:

### Warning message

https://github.com/MaartenBaert/ssr/blob/00ebba23fb6581f9d822b79b19278ed156f21d4a/src/GUI/MainWindow.cpp#L85-L89

### Actual detection

https://github.com/MaartenBaert/ssr/blob/83a0b0b6537680f2dc17c770ffec04e03c18d965/src/common/NVidia.cpp#L22-L33

(seems to use `nvidia-settings -tq AllowFlipping` under the hood. :slightly_smiling_face:)
