### ISSUE TITLE
Duplicate Tray Icon

### ISSUE THREAD

**Issue by amagura** [flameshot-org/flameshot#628]
**Flameshot version**
0.6.0

**Describe the bug**
Tray icon can be duplicated infinitely

**To Reproduce**
1. Right click on the tray icon and select configuration.
2. Select the general tab
3. Repeatedly click on *Show Tray Icon*; for each click that checks the box, an additional tray icon will appear.  

**Expected behavior**
Unchecking the Show Tray Icon should remove/hide the icon from the system tray.  

**System Information**
Ubuntu 19.04 Gnome

**Comment by AlexP11223** [comment]
duplicate of #493

**Comment by borgmanJeremy** [comment]
This is resolved for me on later versions of flameshot (0.8.x) with this gnome extension. https://github.com/flameshot-org/flameshot#tray-icon

Please re-open if you experience the issue on a new version of flameshot with the extension installed.
