### ISSUE TITLE
Sometimes it doesn't work to select area

### ISSUE THREAD

**Issue by simonbcn** [flameshot-org/flameshot#629]
```
Arch Linux 
Flameshot v0.6.0-70-g91ba28c (installed from AUR)
Compiled with Qt 5.13.1
DE: XFCE4 4.14
WM: Xfwm4
```
I associated the `Print` key with the command `flameshot gui`.
It works but sometimes when I press that key, it runs the application and shows the cursor in selection mode (:heavy_plus_sign:) but doesn't let me select an area. It does not react to the left click of the mouse.
I have to exit capture mode and press the `Print` key again until it lets me.

**Comment by simonbcn** [comment]
Any news about this? How can I debug it?

**Comment by lixinyu1024** [comment]
Same here

Flameshot version: 
Flameshot v0.6.0 Compiled with Qt 5.12.1

Describe the bug:
`flameshot gui` doesn't allow me to select an area randomly

To Reproduce: 
hit the tray icon or run `flameshot gui` in the terminal

Expected behavior: 
area selecting should be aviliable

System Information: 
Manjaro 18.1.3 Juhraya - 5.3.12-1-MANJARO - Xfce4

**Comment by mariano-dagostino** [comment]
Same here, using manjaro xfce 4. I noticed that adding a small delay when executing `flameshot -d 100` helped. So far I haven't seen the glitch.

**Comment by simonbcn** [comment]
Unfortunately it seems that this project is abandoned. Which is a shame because it's a very good program.

**Comment by ExposedCat** [comment]
Same error

**Comment by ExposedCat** [comment]
If you enable "Side Panel button", you may hover it to see selected area when this problem occures

**Comment by Zethson** [comment]
Same here.

**Comment by mmahmoudian** [comment]
@simonbcn would it be possible for you to try with the newest version (v0.9.0) and see if it still have the same issue?

@ExposedCat & @Zethson can you confirm your Flameshot versions

**Comment by ExposedCat** [comment]
@mmahmoudian v0.8.5-1 is okay. Seems like v0.9 too

**Comment by mmahmoudian** [comment]
@ExposedCat thanks for the quick response👍🏼
I'll wait to get the confirmation from others too before closing this issue.

**Comment by ExposedCat** [comment]
@mmahmoudian thanks for support

**Comment by Zethson** [comment]
Seems to work for me as well! Every time this happened I died a little bit inside since flameshot is such a great tool, but it just didn't work.

Thanks

**Comment by Zethson** [comment]
@mmahmoudian actually not. I think I was lucky earlier. I wish I could show you, but when I recorded a gif with Peek, it got the real feed and apparently recorded the hidden selection area. Pretty interesting.

Anyways, problem persists.

OS: Arch Linux
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Comment by mmahmoudian** [comment]
Thanks for confirmation. I'll mark it as an existing bug then.

**Comment by robyte-ctrl** [comment]
I'm having a similar issue or maybe the same.
In my case the selected area is not displayed but I know I can interact with it because the cursor changes when it is inside, outside or on the borders of the selected area.
I can move it and I can resize it just fine. I just can't see it sometimes.

**Comment by Zethson** [comment]
Yes, that's exactly it.  Thursday, 01 April 2021, 07:28PM +02:00 from Roman Untilov  ***@***.*** :

**Comment by Ovsyanka83** [comment]
Same here. Manjaro 21.0.5 with xfce.

**Comment by mmahmoudian** [comment]
It worries be nice if we have a deterministic way to reproduce the bug. I cannot reproduce this on Manjaro [KDE, Awesome, DWM] or Ubuntu 20.04 [budgie, gnome].

**Comment by mariano-dagostino** [comment]
I've been doing some other tests. 

1. I see the bug either using 1 or 2 monitors. (Timestamp 10s for one monitor, 40s for two monitors)
2. I can only use the workaround provided in my previous comment only when the two monitors are connected.
3. When two monitors are connected, if the widget is not visible in one of them, it is always visible when dragging the window to the other monitor.
4. Sometimes the app works just fine and I can select regions from the two monitors (Timestamp 1.03s)

**Notes:**
- From 1 to 35 seconds. Using only one monitor plugged:
- From 35 to 1.45 two monitors connected.

https://user-images.githubusercontent.com/5313631/119983520-a6d66480-bf96-11eb-8145-ec1ba648bc0a.mp4

**Comment by mmahmoudian** [comment]
@mariano-dagostino awesome. Good work! Just one question about the two monitor setup: are they both connected to the same graphics card?

**Comment by Zethson** [comment]
Actually I have this issue on just 1 monitor and his trick of Alt tabbing to recover also works on the single monitor.  Friday, 28 May 2021, 10:18PM +02:00 from Mehrad Mahmoudian  ***@***.*** :

***@***.*** awesome. Good work! Just one question about the two monitor setup: are they both connected to the same graphics card?

**Comment by mariano-dagostino** [comment]
> @mariano-dagostino awesome. Good work! Just one question about the two monitor setup: are they both connected to the same graphics card?

@mmahmoudian Yes, same graphic card.

**Comment by Ovsyanka83** [comment]
It seems to depend on the DM. I don't see any KDE users complaining here. So XFCE seems to be the problem.

**Comment by Zethson** [comment]
Can at least confirm that I don't have this issue on arch KDE ;)  Thursday, 24 June 2021, 08:15PM +02:00 from Stanislav Zmiev  ***@***.*** :

**Comment by mmahmoudian** [comment]
I myself am on Manjaro and have used KDE, dem and also AwesomeWM with Xfce stack and never faced this problem from v0.6.0 all the way through v0.10.0 (which at the moment you can get from our AUR (`flameshot-git`).

**Comment by cosmincrihan** [comment]
I may have found the root cause. It's the **display compositor**.
I am using Debian 11 with XFCE and I tried to disable Display Compositing from Settings Manager -> Window Manager Tweaks.

Now, Flameshot works every time. The moment I enable it again, it starts not to work 50% of the times.

**Comment by mariano-dagostino** [comment]
@cosmincrihan Thanks! 

I tried your theory and narrowed it down to this feature, setting:

![Screenshot_2021-12-08_16-44-23](https://user-images.githubusercontent.com/5313631/145273937-bace7118-45d6-42ec-bc33-38ae62f35343.png)

Unchecking this checkbox makes flameshot work all the time.

**Comment by cosmincrihan** [comment]
Awesome! Thank you, @mariano-dagostino, works for me too!

**Comment by mmahmoudian** [comment]
@Zethson would you please try [what @mariano-dagostino shaed](https://github.com/flameshot-org/flameshot/issues/629#issuecomment-989141578) and see if it solves the issue for you?

**Comment by Zethson** [comment]
> @Zethson would you please try [what @mariano-dagostino shaed](https://github.com/flameshot-org/flameshot/issues/629#issuecomment-989141578) and see if it solves the issue for you?

I am very sorry, but I have since moved away from XFCE and therefore cannot help reproduce/validate anymore.

**Comment by mmahmoudian** [comment]
@simonbcn @uLxy @Ovsyanka83 Would you please try [what @mariano-dagostino shaed](https://github.com/flameshot-org/flameshot/issues/629#issuecomment-989141578) and see if it solves the issue for you?

**Comment by mariano-dagostino** [comment]
@mmahmoudian I use flameshot pretty much daily and so far since my comment https://github.com/flameshot-org/flameshot/issues/629#issuecomment-989141578 I haven't seen this issue anymore. Should we add some docs in the README and close the issue?

**Comment by mmahmoudian** [comment]
@mariano-dagostino sure, feel free to create a PR in https://github.com/flameshot-org/flameshot-org.github.io
