### ISSUE TITLE
Esc button not working for cancelling a screenshot.

### ISSUE THREAD

**Issue by omkarnathsingh** [flameshot-org/flameshot#63]
I am on Ubuntu 17.10. I cant cancel taking a screenshot after I double click on Tray icon to take a screenshot. 

Please add a configuration in GUI for adding a default delay between the double click and screenshot.

Thanks for this amazing app.

**Comment by lupoDharkael** [comment]
Why do you want to cancel the screenshot after the double click?

And yes, I'm considering adding a delay just for the trayicon because some systems show a dialog and sometimes it's not desired. A little delay could solve the problem.

**Comment by omkarnathsingh** [comment]
Thanks for considering the changes.

**Comment by omkarnathsingh** [comment]
@lupoDharkael Has delay been introduced while taking screenshots? I don't see it in settings.

**Comment by borgmanJeremy** [comment]
Delay is now introduced in the "launcher menu"
