### ISSUE TITLE
E: Unable to locate package flameshot

### ISSUE THREAD

**Issue by Yekutiel** [flameshot-org/flameshot#632]
I ran `sudo apt install flameshot` on GalliumOS 3 (which is based on Ubuntu 18.04)
I received the error message `E: Unable to locate package flameshot`

**Comment by asyba** [comment]
same issue

**Comment by borgmanJeremy** [comment]
I think this should be filed with your distro since we do not maintain the downstream packages.

That said version 0.8 will be released this weekend which will support flatpak, snap, and appimage for easier installation.

**Comment by mloic47** [comment]
i did `sudo apt-get update `and` sudo apt-get upgrade`
then `sudo apt install flameshot` it worked 
@asyba @Yekutiel I this should be mentioned in the documentation @borgmanJeremy
