### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by maheshdharhari** [flameshot-org/flameshot#633]
I am using it in Ubuntu and I am very impressed to use it. I want to use it on my widows also.
How to use it on windows?

**Comment by AlexP11223** [comment]
See #29, afaik it's possible to build but some features may not work.

I would use ShareX/Monosnap on Windows, I think they are currently better than Flameshot.

**Comment by 4sStylZ** [comment]
Hi there, 

I have used this tool 1 year ago on Windows. At this point an github issue provided a linke to download.
At this point Flameshot was perfectly usable on Windows. I am surprised that there is still no Windows version, at least a beta with some disclaimer on some features.

Pretty sure that many users wait for it. Anyway this is a very good tool and thank you for the work. 👍

**Comment by AlexP11223** [comment]
The owner seems to be not very active in the last year.

**Comment by DrunkenPoney** [comment]
See https://github.com/lupoDharkael/flameshot/issues/29#issuecomment-562179400

**Comment by ZetaoYang** [comment]
see PR https://github.com/flameshot-org/flameshot/pull/898

**Comment by borgmanJeremy** [comment]
Windows binaries are now included in 0.8. Please report any issues you find 👍
