### ISSUE TITLE
Add a flatpak softwares to can open the capture

### ISSUE THREAD

**Issue by mrpouletcurry** [flameshot-org/flameshot#636]
Hello,

Actually I try Flameshot on Ubuntu 19.10.
It would be nice if you add the option to open the capture with a Flatpak and/or Snap ? 
In a option "Choose an app to open the capture".

Or add a option to open with a custom command

**Comment by borgmanJeremy** [comment]
@mrpouletcurry Could you please explain in more detail what this request means?

**Comment by ZetaoYang** [comment]
@mrpouletcurry Are you mean flameshot need "add a option to open with **_a custom command_**"? But I cannot understand what "open the capture with a Flatpak and/or Snap" means.

**Comment by borgmanJeremy** [comment]
Closing since flameshot both supports opening with external applications and version 0.8 will support snap, flatpak, and appimage.
