### ISSUE TITLE
Steps option

### ISSUE THREAD

**Issue by mrpouletcurry** [flameshot-org/flameshot#637]
Hello,

It would be nice if you add a cool function to call "Steps option".
I use the steps option for the users guideline.
The software into the GIF is ShareX Screen capture.

Like the joined GIF : 

![steps_sharex](https://user-images.githubusercontent.com/31985048/67105409-053b3e80-f1c9-11e9-956d-5366a7ea0d63.gif)

**Comment by borgmanJeremy** [comment]
This exists on master and will be in the 0.8 release.
