### ISSUE TITLE
[Suggest] Color picker

### ISSUE THREAD

**Issue by trmdi** [flameshot-org/flameshot#64]
Thanks for a great app.

Could you use [QColorDialog](http://doc.qt.io/qt-5/qcolordialog.html#details) for the Color picker ?
![QColorDialog](http://doc.qt.io/qt-5/images/fusion-colordialog.png)

**Comment by lupoDharkael** [comment]
I think I could add it as an advanced option to choose a color. I like the actual color picker as it's elegant an compact but I understand other people could want to have extra options.
I will have to redesign the menus when I add some extra things to the config window.

**Comment by ZetaoYang** [comment]
@lupoDharkael  I think we can combine `pin capture on the dektop` and `color picker`.
After taking the color, the color info will be attached to the desktop, like this 
![image](https://user-images.githubusercontent.com/10769951/36832886-6af68234-1d68-11e8-9f2f-11f54d81babc.png)

![image](https://user-images.githubusercontent.com/10769951/36832956-bce7fce4-1d68-11e8-870f-9399f7d882b8.png)

**Comment by ustmaestro** [comment]
Add color picker for drawing tools
Take a look at joxi.net

**Comment by trmdi** [comment]
Or in the short term, can you let users customize the colors e.g. in the config file ?

**Comment by borgmanJeremy** [comment]
There is actually a color picker now. If you hit spacebar after starting a screenshot it will bring up a new window with a color picker.
