### ISSUE TITLE
"QSocketNotifier: Invalid socket 4 and type 'Read', disabling..." spam on journalctl

### ISSUE THREAD

**Issue by RodrigoLeiteF** [flameshot-org/flameshot#641]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.12.1

**Describe the bug**
At system startup, Flameshot sometimes spams `journalctl` with the following message, causing `systemd-journald` to use a lot of CPU, as well as Flameshot itself

```
out 26 15:46:46 rodrigo-laptop flameshot[4106]: QSocketNotifier: Invalid socket 4 and type 'Read', disabling...
```

**To Reproduce**
Not sure. It seems to happen at seemingly random on startup

**System Information**
Manjaro on kernel 5.2.21

**Comment by borgmanJeremy** [comment]
Is this still an issue on a 0.8.x release?

**Comment by RodrigoLeiteF** [comment]
Apparently not. I haven't run into this issue in a while (that I can tell, at least). Closing for now. Thanks for the follow-up.
