### ISSUE TITLE
Command line switch to automatically copy to clipboard after GUI selection

### ISSUE THREAD

**Issue by arigit** [flameshot-org/flameshot#642]
Please support the following syntax (or equivalent):

```
flameshot gui -c
```

This would launch flameshot in rectange selection mode and when the selection is done, instead of showing all the small buttons it would just copy the result to the clipboard and 'minimize itself to tray' as usual.

This would allow simple binding to a shortcut that allows quick area grabbing for later paste into GIMP, gmail and the like.

Same result as intended by:
```
gnome-screenshot --area --clipboard
```
...however gnome-screenshot does not work properly with the above options in wayland (the clipboard gets lost after gnome-screenshot automatically closes. flameshot resolves this wayland challenge by staying open in the tray

**Comment by mossaybo** [comment]
the shortcut you're looking for is simply Enter (Return) , I use this command to lunch flameshot
flameshot gui -p ~/Pictures/flameshot 
1- make selection
2- Enter/Return > copy  to clipboard 
Ctrl-S > save picture to ~/Pictures/flameshot

**Comment by mmahmoudian** [comment]
as @mossaybo correctly said, when you are in `flameshot gui`, either select the area and press <kbd>Enter</kbd> or even without selecting the area press <kbd>Enter</kbd> to capture the whole screen.

I close this issue now.

**Comment by arigit** [comment]
@mmahmoudian, @mossaybo sorry I didn't explain more clearly - coming from a Mac, the mac snippet grabber can be configured to launch directly into the selection tool, and when releasing the mouse button while making a rectangle selection, it automatically copies that selection to the clipboard. No need to press anything in the keyboard, or to search and click the "copy" button.

I use flameshot on gnome/linux but miss the MacOs behavior, which is also the behavior one gets with "gnome-screenshot --area --clipboard"
Could an option be added to the flameshot gui or to the command line so that the rectangle selection automatically gets copied to the clipboard?

**Comment by SathOkh** [comment]
I'm fully support this request. ENTER shortcut is only a workaround and user experience of this is very inferior comparing to MacOS

**Comment by mmahmoudian** [comment]
@SathOkh @arigit this is now implemented as far as I can recall in #1970

@veracioux am I correct or am I missing something?

**Comment by veracioux** [comment]
@mmahmoudian Ditto, except that command line flags are not available in MacOS until #2003 is merged.

**Comment by SathOkh** [comment]
@mmahmoudian I don't see it on current linux version as well and it's not mentioned in the README and help message. Is it already released or just merged so far?

**Comment by mmahmoudian** [comment]
@SathOkh comparing the times for the last release and the PR would have saved you time. It is a new feature that is merged and you can use it if you download the nightly builds (https://flameshot.org/nightly) or of you compile from source.

**Comment by SathOkh** [comment]
@mmahmoudian having proper issue description with fix version would save me time, not digging into the app release cycle and pr times.

**Comment by mmahmoudian** [comment]
@SathOkh as an OpenSource software, we are open to contributions. Therefore, if you think something can be improved, go ahead and improve it. Any contribution is most welcome.

**Comment by veracioux** [comment]
This feature is implemented in flameshot version 11 (run `flameshot gui --clipboard --accept-on-select`).
