### ISSUE TITLE
Crash when saving a screenshot

### ISSUE THREAD

**Issue by Yama-K** [flameshot-org/flameshot#643]
**Flameshot version**
0.6.0-3

**Describe the bug**
After selecting the area to screenshot flameshot crashes instead of saving the screenshot, copying the screenshot works fine

**To Reproduce**
Start flameshot, select area to screenshot, choose save. Video to show what happens: https://youtu.be/lwSn6aGSD7s

**Expected behavior**
Save dialog to open instead of flameshot closing

**System Information**
Arch Linux

**Comment by borgmanJeremy** [comment]
Can you please test this using flameshot-git from AUR?

**Comment by GoodOldBatman** [comment]
I had the same issue with `Flameshot v0.8.5-4 (Debian) - Compiled with Qt 5.15.2`

I found a solution that worked for me by running this in the terminal:  
``` 
LANG=C flameshot &
``` 

Found it here https://archived.forum.manjaro.org/t/flameshot-disappears-when-saving-or-configuring/137510/2
