### ISSUE TITLE
Flameshot on Fedora 31 : QSocketNotifier: Can only be used with threads started with QThread

### ISSUE THREAD

**Issue by Crupuk** [flameshot-org/flameshot#646]
Hello, 

I can't use Flameshot after upgrading to Fedora 31.

**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.12.4

**Describe the bug**
Flameshot doesn't start :

# flameshot
QSocketNotifier: Can only be used with threads started with QThread

**To Reproduce**
Start flameshot on fedora 31

**Expected behavior**
Start and add a icon to systray

**System Information**
Fedora 31

Thanks for your help

**Comment by andreashaerter** [comment]
Fedora 31, 64-Bit, GNOME 3.34.2, Wayland

- `flameshot` is producing the mentioned error.
- `flameshot gui` works as expected though.

**Comment by ebdavison** [comment]
I have the same error on my system after upgrade to Fedora 31 as well.  `flameshot gui` does indeed produce a screen capture gui except for the fact that the terminal is sitting on top of what I want to take a screenshot of and there is no way to then rearrange windows.  To be clear `flameshot gui` does not fix the problem of no launch and no icon.

**Comment by stanfieldr** [comment]
Same thing on Fedora 32. Falling back to X11 works as a work-around

**Comment by xionjames** [comment]
Yes, the problem is with Wayland... Disabling it and use xorg, flameshot works.

**Comment by borgmanJeremy** [comment]
I started looking into this today for another issue #1052 . However, It seems from my testing this is only an issue with users not having a proper systray setup. I do see this warning but the program works fine. 

Can anyone else on this thread to try replicate my observation by installing the same gnome extensions on wayland?
![image](https://user-images.githubusercontent.com/46930769/95794982-d443fb80-0cae-11eb-8758-646100aceae9.png)

**Comment by stanfieldr** [comment]
Seeing the same thing with your extension:
![terminal](https://user-images.githubusercontent.com/7494573/95796827-e8dac080-0cbb-11eb-8c36-9ec7536e4c79.png)

I had a similar issue to #1052 when using my old extension (appreciated flameshot that much more when I couldn't use it for this lol):
![Screenshot from 2020-10-12 18-52-31](https://user-images.githubusercontent.com/7494573/95797090-9a79f180-0cbc-11eb-801a-3f23b0ec2aef.png)

**Comment by borgmanJeremy** [comment]
Ok great! To confirm, with that systray extension flameshot "generally" is working, but copy is still broken?

**Comment by stanfieldr** [comment]
Correct tray icon appears and if I click tray icon to take screenshot I can draw rectangle and see buttons

**Comment by borgmanJeremy** [comment]
Ok great, I am going to leave this issue open for now so we can investigate why the warning is appearing, but we know the warning is unrelated to the issue. Thanks for testing!

**Comment by merrcury** [comment]
@borgmanJeremy I've also verified your observation. I ran Fedora in a Wayland environment with [this](https://extensions.gnome.org/extension/615/appindicator-support/) extension as suggested and It worked like a charm. 

I also have a thought regarding these type of issues. Do you think we should add a quick troubleshooting guide & fixes into documentation or on https://flameshot.js.org/? Non-Geek Guys & People in hurry might want to quick-fix it and keep their work going. I would love to help you out if you think its a good idea. 

![Screenshot from 2020-10-13 12-04-03](https://user-images.githubusercontent.com/35988194/95824016-3acb2700-0d4c-11eb-9ebc-f5a207ebbcd1.png)

**Comment by borgmanJeremy** [comment]
@merrcury The readme currently recommends installing this plugin on gnome, but it obviously is not very easy to find since this question arises very often. 

This is the repo the website is hosted in: https://github.com/flameshot-org/flameshot-org.github.io
The getting-started page is actually very out of date. I would 100% welcome a PR that updated the getting-started page and added these quick-fixes.

Thanks!
