### ISSUE TITLE
Issue with QR on Fedora 31

### ISSUE THREAD

**Issue by dakyskye** [flameshot-org/flameshot#647]
**Flameshot version**
```
$ flameshot -v
Flameshot v0.6.0
Compiled with Qt 5.12.4
```

**Describe the bug**
- I think application is not started correctly, thus when I type `flameshot`, I get: `QSocketNotifier: Can only be used with threads started with QThread`.
- If I start `flameshot gui`, then it seems to work nice, but actually it never copies the screenshot to the clipboard.

**To Reproduce**
```
$ flameshot
QSocketNotifier: Can only be used with threads started with QThread
```

**Expected behavior**
- It should launch without any issue
- Captured `flameshot gui` screenshot should get copied to clipboard

**System Information**
Fedora 31 (Workstation Edition) x86_64

**Comment by dakyskye** [comment]
I just entered *GNOME on Xorg* session, it now works fine. I won't close issue still.

**Comment by CosmoMyzrailGorynych** [comment]
![Screenshot from 2019-12-19 09-47-57](https://user-images.githubusercontent.com/3174357/71126047-aa63a900-2244-11ea-82bd-1048a55b1830.png)


Gnome on Wayland (flameshot worked with it prior to Fedora 31).

**Comment by mmahmoudian** [comment]
Since the 0.8 has squished many bugs, I suggest you test the [version 0.8](https://github.com/flameshot-org/flameshot/releases/latest) and comment here if the issue persists. Otherwise I will close this issue in 14 days in favor of 0.8

**Comment by dakyskye** [comment]
Sorry, I don't have Wayland any more, can't test.

**Comment by mmahmoudian** [comment]
@dakyskye try the new version. it now has Snap (under review by Canonical), Flatpak (soon will be in flathub but for now you can download the flatpak file and do `flatpak install XXXXX.flatpak`), and AppImage which you just need to download, make executable and double-click to enjoy Flameshot. Itis also available in Arch and few other distros and the other distros are gradually adopting the new version.

There are also deb and rpm files if you are on Debian based or RPM based distros.

Just remember to enjoy using it 😉 


I'll close this issue.
