### ISSUE TITLE
Activate text in the standard configuration after a clean install

### ISSUE THREAD

**Issue by arcolinuxz** [flameshot-org/flameshot#654]
![standard on](https://user-images.githubusercontent.com/36679406/68999550-f1672300-08c1-11ea-8699-8b66cca19364.png)

Kindly activate text at first bootup.

**Comment by borgmanJeremy** [comment]
This is now the default in 0.8.x, thanks for the feedback!

**Comment by arcolinuxz** [comment]
thanks
