### ISSUE TITLE
undo Incorrect effect

### ISSUE THREAD

**Issue by jankin-l** [flameshot-org/flameshot#655]
I use flameshot gui on macos 10.14.4。
Issue1: Undo Incorrect  effect, but on win10 is good. 
Issue2: The tools can operate outside selection.

step1:
<img width="740" alt="WX20191119-083831@2x" src="https://user-images.githubusercontent.com/13214569/69106567-c0e1dd80-0aa9-11ea-9acd-33ff2400d761.png">

step2:
<img width="677" alt="WX20191119-084058@2x" src="https://user-images.githubusercontent.com/13214569/69106590-d6570780-0aa9-11ea-9870-70de04cbc535.png">

**Comment by hellxz** [comment]
same to me, on debian linux

**Comment by jankin-l** [comment]
why close?

**Comment by borgmanJeremy** [comment]
I need some more information to troubleshoot it. If you can help me collect it I can look into it.

**Comment by hosiet** [comment]
I am more interested in how flameshot was made to be running on macOS.

**Comment by jankin-l** [comment]
I upgraded the macos to 10.15.6, the issues did not arise.
I try it on deeopin , the issues also did not arise.

Now, flameshot run perfectly on macos.
