### ISSUE TITLE
'--one-shot' to prevent daemonizing

### ISSUE THREAD

**Issue by fhennig** [flameshot-org/flameshot#656]
It would be great if it was possible to start this tool without it daemonizing automatically. A simple flag like `--one-shot` or `--no-daemon` would be nice for that.

And/or it would be great to hear why the decision was made to have a daemon for a screenshot tool, since to me this seems like a perfect utility to be a one-shot application.

**Comment by hosiet** [comment]
#557

**Comment by fhennig** [comment]
The option to "Close after Capture" isn't there for me

flameshot version:
```
Flameshot 0.6.0-11(Debian)
Compiled with Qt 5.11.3
```

But following that command I used 
```
flameshot gui -r | xclip -selection clipboard -t image/png && killall flameshot
```
Which works fine, but is a bit hacky. Also I don't really need the `-r` option since I have a different clipboard manager, but there is no obvious way to prevent flameshot from returning immediately from the `flameshot gui` command.

Ideally would be something like
```
flameshot gui --one-shot
```
That stays open, like it does with `-r`, until the user saves to clipboard, and then just exits, without daemonizing.

**Comment by fhennig** [comment]
I found #257 (didn't find it before, was looking for the wrong keywords), but it's weird that it's not in my version, even though it should be.

**Comment by borgmanJeremy** [comment]
We are actually moving away from this direction. The close after capture feature causes many bugs, and lead to too much maintenance overhead. You can disable the tray icon if you don't want to see it in the tray.

**Comment by igorlogius** [comment]
@veracioux  First of, thank you very much for taking note and time out of your day to reply.   

That someone is already actively fixing/developing on this is quite a suprise but a welcome one. 

Is there maybe already a branch or tag for the dbus changes i can take a look at or keep in focus?
Also if there is a way i can help out (like beta testing or code review)  just let me know.  

Thanks again.
