### ISSUE TITLE
Flameshot - set trayicon via preferences

### ISSUE THREAD

**Issue by arcolinuxz** [flameshot-org/flameshot#659]
Could you let the application use a separate tray icon that we can theme to our liking?
Alternatively provide a way to do so in the configuration.
![flameshot](https://user-images.githubusercontent.com/36679406/69521690-dbabca80-0f5f-11ea-8a76-bfa53aacb7bc.png)
It would look better in white

**Comment by tkoop** [comment]
I agree.  I came here looking to fix this same issue.  My system tray looks similar.

Or here's another idea:  In the Nextcloud app, there is a setting to "Use Monochrome Icons" in the system tray.  I don't think that would be a difficult change to make.

**Comment by borgmanJeremy** [comment]
The icons are set from your global icon set. My global icon set on KDE includes a monochrome icon for flameshot: 
![image](https://user-images.githubusercontent.com/46930769/108610603-792cbe80-739c-11eb-90b9-91c6c9f1fe63.png)

**Comment by borgmanJeremy** [comment]
I'm actually going to close this now because icons are controlled at a higher layer than flameshot, namely your system theme.
