### ISSUE TITLE
Ratio between text size and tool size

### ISSUE THREAD

**Issue by babs** [flameshot-org/flameshot#665]
It would be nice to have a ratio or a fixed value to add to text size regarding tools size.

I almost always switch between text and arrow tool and I have to constantly change the size (mouse wheel) because text is rather small when arrows are light and arrows are way to fat when text is clearly readable.

Having a factor or an offset would allow changing tools without changing size (it usually introduce inconsistencies in arrow width).

Another option, as seen in another feature request, would be to have a tool size per "tool", local vs global?, that way, arrow size, text size but also boxes, highlighter, blur and so on could be set set once per session and tools could be easily swapped.

**Comment by evandrocoan** [comment]
I was just about to open the exactly same issue.

**Comment by borgmanJeremy** [comment]
We are tracking this on #782 now. This will likely get through an RFC and into a future version, thanks for the feedback.
