### ISSUE TITLE
Flameshot GUI does not open after adding text and saving as file

### ISSUE THREAD

**Issue by nikolayhg** [flameshot-org/flameshot#667]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.7.1

**Describe the bug**
After making a screenshot, adding a text to it and saving it in a file, the next command "flameshot gui" does not start the GUI for selection.

**To Reproduce**
1. Start flameshot: `flameshot`
2. Run `flameshot gui`
3. Select area
4. Left click the text button (T)
5. Left click anywhere in the selected area
6. Enter few words with the keyboard.
7. Press `Ctrl+S` shortcut to save as file, and save it.
8. Run `flameshot gui` once again
9. The GUI does not open.

**Expected behavior**
At step 9, the GUI should open.

**IMPORTANT NOTES**: 
- After step 6, if you left click outside of the text, and then continue with the next steps, then the GUI opens once again correctly, as expected!
- The GUI opens after using every other drawing tool (line, arrow, etc) and saving as file, except text.
- The GUI opens after using the text tool and NOT saving it as file: which is uploading, copying to clipboard or canceling.

Might be related to #549.

**System Information**
Ubuntu 18.04

**Flameshot Log**
```
$ flameshot 
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
Gtk-Message: 14:08:31.965: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by nikolayhg** [comment]
I described in the important notes how to use the text drawing tool correctly, so that after saving the file the GUI can be opened again.

**Comment by Lirabeth** [comment]
bump

I encounter similar problem on version 0.6.0

**Comment by gregretkowski** [comment]
Verified on my system. Ubuntu 18.04.4 running the flameshot 0.6.0 xenial .deb.
If the last tool I use is the text tool to add some text, and then save --- clicking on the tray icon to create the screenshot does not work. nor does right-click 'take screenshot'. However selecting any other tool before saving allows the next screenshot to be taken. And selecting the text tool, not entering any text, saving the screenshot -- that also allows the next screenshot to be taken.

So something is happening whereas if the last action is to enter text, then it prevents the next screenshot to be taken.

**Comment by mmahmoudian** [comment]
Since the 0.8 has squished many bugs, I suggest you test the [version 0.8](https://github.com/flameshot-org/flameshot/releases/latest) and comment here if the issue persists. Otherwise I will close this issue in 14 days in favor of 0.8
