### ISSUE TITLE
Capturing screenshots and opening config

### ISSUE THREAD

**Issue by mkrajinovic** [flameshot-org/flameshot#67]
Using Antegros with KDE, no Wayland, installed from the AUR. When I try to open configure, either by right clicking the tray icon or through CLI, the app just closes.
Also, the screenshots aren't saved anywhere, even when capture with GUI with custom save path is used, when GUI used, they aren't uploaded to Imgur and can't be copied to clipboard.
I can provide additional information if needed.

**Comment by lupoDharkael** [comment]
Does it log something if you start flameshot from the terminal and do something causing a crash?

**Comment by mkrajinovic** [comment]
```
Icon theme "ubuntu-mono-dark" not found.
Icon theme "gnome" not found.
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

```
Is what I get when trying to configure.

**Comment by mkrajinovic** [comment]
After a bit more digging, I found out that capturing screenshots still doesn't work in some cases, and I can't find why. If I run flameshot from the terminal, everything works as it should. But if I run it from application list, it crashes upon trying to save/upload/copy to clipboard and trying to open configure.

I also tried making a simple shell script to run it. When I run that script from the terminal it works, but when I run it normally,  it crashes the program. 

`#!/usr/bin/zsh
#Trying to run flameshot


flameshot

`

I also tried making a keyboard shortcut (flameshot gui -p ~/myStuff/captures) from the KDE system settings. When flameshot is running in my terminal, everything works as intended. But when Flameshot is running without the terminal capturing and config crashes.

**Comment by lupoDharkael** [comment]
no log for this new problem?

**Comment by mkrajinovic** [comment]
Does the program write any logs when not running from terminal? If so, I can provide it.

**Comment by lupoDharkael** [comment]
I doesn't have it. 
I'll implement logs in /var/log/ so you can read it.

**Comment by mkrajinovic** [comment]
Thanks. I hope there will be something useful in them.

**Comment by mmahmoudian** [comment]
@mkrajinovic  I close this now as this was reported for a version that is now very old and hopefully it has been solved during the recent versions. feel free to re-open this with new information if you still face this issue with 0.8.x versions
