### ISSUE TITLE
Support gif creation

### ISSUE THREAD

**Issue by maireanu** [flameshot-org/flameshot#670]
It will be nice to have the possibility to make gif also

**Comment by lawzava** [comment]
Indeed.

**Comment by mmahmoudian** [comment]
I think this is out of the scope of this software. You can achieve this using [https://github.com/phw/peek](https://github.com/phw/peek) which is designed for this purpose:

![peek example](https://raw.githubusercontent.com/phw/peek/master/data/screenshots/peek-recording-itself.gif)

**Comment by borgmanJeremy** [comment]
Duplicate of #172
