### ISSUE TITLE
how to change UI languages ?

### ISSUE THREAD

**Issue by changchichung** [flameshot-org/flameshot#674]
I install flameshot using apt , but default language for me is zh_CN 
I want to change to zh_TW , but I see no language option in config
so , how to change UI languages ?

**Comment by ZetaoYang** [comment]
It's up to your system language setting.

**Comment by changchichung** [comment]
my locale config to en_US and zh_TW , no zh_CN there.
![](https://i.imgur.com/5iNJIkF.png)

**Comment by borgmanJeremy** [comment]
@ZetaoYang Can this be closed or is there a bug to track down?

**Comment by ZetaoYang** [comment]
@borgmanJeremy  I think this need to be enhanced, we can make an language setting on general tab, users can set the language to their liking. But for now, I think this issue could be closed.

**Comment by ZetaoYang** [comment]
@borgmanJeremy I don't think it's a bug in the current software, it's caused by the user switching languages incorrectly.

**Comment by changchichung** [comment]
>> it's caused by the user switching languages incorrectly.

No , I didn't change the language setting "incorrectly" !!
as you can see my locale settings , there's no such zh_CN option , then how the software determine which language file should be used ?

**Comment by ZetaoYang** [comment]
@changchichung Sorry I didn't look closely at that screenshot of yours. I need to know the steps you take to switch languages, can you tell us? I will be testing this in the ubuntu 20.04 virtual machine environment, give me some time.

**Comment by ZetaoYang** [comment]
@changchichung 
My test environment is `WSL2 Ubuntu 20.04 i3wm X11`, I switched my language from `C.UTF-8` to `zh_CN.UTF-8` to `zh_TW.UTF-8`, and the `flameshot` interface language display is normal.
  ![image](https://user-images.githubusercontent.com/10769951/92690431-98e2a400-f373-11ea-8075-4dff65b5da98.png)

The steps I took to switch to the Ubuntu system language were:
1. **First check if the Chinese language pack is installed**
  `locale -a`
  **Check to see if there are:** `zh_CN.utf8` or `zh_TW.utf8`
  ![image](https://user-images.githubusercontent.com/10769951/92691094-9df42300-f374-11ea-99a3-21df741d0269.png)
  If not, you will first need to install the Chinese language package by entering the following command.
  `sudo apt install language-pack-zh-hans language-pack-zh-hant`
  _**NOTE.**_ `language-pack-zh-hant` is translation updates for language **_Traditional Chinese_**. `language-pack-zh-hans` is translation updates for language **_Simplified Chinese_**. More details, see https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/language-pack-zh-hant_20.04+20200416_all.deb.html and https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/language-pack-zh-hans_20.04+20200416_all.deb.html
  BTW. English language pack is `language-pack-en`.
  **Then add Chinese support.**
  `locale-gen zh_CN.UTF-8`  or `locale-gen zh_TW.UTF-8`  (choose one of two)
2. **Modify locale file configuration**
  `sudo vim /etc/default/locale`
  For example, change to Traditional Chinese
    ```
    LANG=zh_TW.UTF-8
    LANGUAGE=
    LC_CTYPE="zh_TW.UTF-8"
    LC_NUMERIC="zh_TW.UTF-8"
    LC_TIME="zh_TW.UTF-8"
    LC_COLLATE="zh_TW.UTF-8"
    LC_MONETARY="zh_TW.UTF-8"
    LC_MESSAGES="zh_TW.UTF-8"
    LC_PAPER="zh_TW.UTF-8"
    LC_NAME="zh_TW.UTF-8"
    LC_ADDRESS="zh_TW.UTF-8"
    LC_TELEPHONE="zh_TW.UTF-8"
    LC_MEASUREMENT="zh_TW.UTF-8"
    LC_IDENTIFICATION="zh_TW.UTF-8"
    LC_ALL=
    ```
  3. reboot (I use WSL2, so I restart `LxssManager` service, run powershell command `Get-Service LxssManager | Restart-Service`)
  ---
  Another way, you can also write in `~/.bashrc` to.
  ```
  # Modifying local environment variables
   vim ~/.bashrc
  # additional content
  export LANG=zh_TW.UTF-8

  # put into effect
  source ~/.bashrc
  ```

@borgmanJeremy In summary, I believe this is not a bug, perhaps the user did not install the language package.

**Comment by edwinyzh** [comment]
Is it possible to allow me to select another language for the UI instead of the one detected by the app?  I prefer English because I found some translation is hard to understand. Thanks!

**Comment by ZetaoYang** [comment]
> Is it possible to allow me to select another language for the UI instead of the one detected by the app? I prefer English because I found some translation is hard to understand. Thanks!

I suggest you open a new feature request.
