### ISSUE TITLE
Thanks to you. and helpful app. I want a "hot key" preference.

### ISSUE THREAD

**Issue by mailsjb** [flameshot-org/flameshot#681]
I don't think there are any Linux programs that can be captured like this. However, I would like to be able to set the "hot key".

That's the most uncomfortable part. Run it through the hot key anywhere and capture it.

Please, and thank you.

**Comment by SonephetR2** [comment]
This must currently be done manually. See https://github.com/lupoDharkael/flameshot/issues/200 for many ways for doing so.

**Comment by Tejeev** [comment]
https://github.com/lupoDharkael/flameshot/issues/726
https://github.com/lupoDharkael/flameshot/issues/763

https://github.com/lupoDharkael/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde

**Comment by mmahmoudian** [comment]
This is not something that the Flameshot should do, this is the part that your window manager should handle (executing a software or command based on a shortcut key). @Tejeev has kindly provided some insight on how to configure it in xfce. It is almost the same in Gnome and KDE.



 I'll close this issue as it is not a feature request or bug.
