### ISSUE TITLE
Add black white (transparent) icon to tray, please :-)

### ISSUE THREAD

**Issue by sgse** [flameshot-org/flameshot#684]
First, thank you for this perfect helpful app :)

<img width="478" alt="grafik" src="https://user-images.githubusercontent.com/17575778/74760041-14ff8800-527a-11ea-9494-4dae17bd5bcb.png">
Second
Maybe you can use this

![flamshot128-bw](https://user-images.githubusercontent.com/17575778/74760210-5b54e700-527a-11ea-8edf-bb77df82e8e5.png)

![flamshot48-bw](https://user-images.githubusercontent.com/17575778/74760229-614ac800-527a-11ea-886c-529b97d8d427.png)

[flameshot-01-bw.tar.gz](https://github.com/lupoDharkael/flameshot/files/4220633/flameshot-01-bw.tar.gz)
CU ;-)

**Comment by ZetaoYang** [comment]
@sgse  [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) supports black white (transparent) icon, you can try it.

**Comment by dimitri168** [comment]
Hello, @sgse, @ZetaoYang.
My case is almost the same.
But seems some interesting issue.
I have colored icon in panel when start as "flameshot gui"
![изображение](https://user-images.githubusercontent.com/58726416/75436040-1ddd1180-597e-11ea-97a8-82735dfbdf57.png)
and b/w icon when start as "flameshot" only
![изображение](https://user-images.githubusercontent.com/58726416/75436111-377e5900-597e-11ea-8564-3bc9b117ea52.png)
System Arch
DE is XFCE4
Icons are Qogir-dark
Everything is up-to-date.

**Comment by ZetaoYang** [comment]
@dimitri168 I cannot reproduce that case when start as “flameshot  gui” .
Fedora 31 Gnome, XWayland
theme is papirus-icon-theme

**Comment by exetico** [comment]
+1. I would really like to see a black&white icon.

**Comment by borgmanJeremy** [comment]
This is in the latest release.
