### ISSUE TITLE
Flameshot imgur login

### ISSUE THREAD

**Issue by konradlu** [flameshot-org/flameshot#695]
Does flameshot allow to log in to imgur account? I don't see this option in settings.

PS. So far this is the best application for making screenshots on linux, but there are still a few options missing.

**Comment by mmahmoudian** [comment]
I think this will be solved after what explained [here](https://github.com/flameshot-org/flameshot/issues/777#issuecomment-685957085) is implemented.

If you have other suggestions for improving the application, please post them. For now, I close this issue as it is addressed elsewhere. If you think this should stay open, please comment here.
