### ISSUE TITLE
Very slow GUI start after flameshot being called

### ISSUE THREAD

**Issue by exapsy** [flameshot-org/flameshot#703]
**Flameshot version**
v0.6.0 - Compiled with Qt 5.12.1

**Describe the bug**
Flameshot has a very slow start, around 2-3 seconds. In the means of, it takes a while before the GUI shows up.

Unfortunately, I dont have quite much information about it. Starting `flameshot` via terminal didn't help debugging it either. It all seems to be working "quite normal". So, in case you might have some times for debugging this, it would be useful :)

**To Reproduce**
Not quite sure besides my system's and flameshot's version. I have to mention, that this didnt happen before, I reinstalled flameshot (for my own reasons) and then it started happening.

**Expected behavior**
To start almost in an instant after it was called.

**System Information**
GNOME Shell 3.34.4
`Linux exapsy 4.14.172-1-MANJARO #1 SMP PREEMPT Fri Feb 28 21:28:00 UTC 2020 x86_64 GNU/Linux`

**Note**
Also, just in case this might be related in any kind of way, my ability to press ESCAPE in order to cancel my screenshot was lost. I remember that this was possible before.

**Comment by mmahmoudian** [comment]
@exapsy can you confirm if the issue still persists? Also, from where did you install Flameshot (AUR or community arch repo)?

**Comment by borgmanJeremy** [comment]
Closing as stale.

**Comment by adaamz** [comment]
persists, at least i takes long to load on my machine 😁 
i installed flameshot from ubuntu apt repo

**Comment by mmahmoudian** [comment]
@adaamz please mention your Flameshot version, operating system, whether you are on Wayland or X, and finally, how you have installed it (possible Snap pr Flatpak?)

**Comment by adaamz** [comment]
```sh
$ flameshot -v
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5
```
```sh
$ echo $XDG_SESSION_TYPE
x11
```
```sh
$ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal
```

**Comment by adaamz** [comment]
i uninstalled flameshot using apt and installed new version (0.9.0) from snap and it is fast as it should be :)
thx for help

**Comment by joalcava** [comment]
I'm having this exact same issue, here is some information about my system:

```
$ flameshot -v
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

```
$ echo $XDG_SESSION_TYPE
wayland
```

I'm using Fedora 34, my system is fully updated

When I write `flameshot gui` the command returns inmediatly so a `time` will be pointless, it takes between 2 and 3 seconds to actually show de gui, `flameshot config` displays de config ui inmediatly. Also I have a 4K display.

**Comment by james-reed** [comment]
> I'm having this exact same issue, here is some information about my system:
> 
> ```
> $ flameshot -v
> Flameshot v0.9.0
> Compiled with Qt 5.15.2
> ```
> 
> ```
> $ echo $XDG_SESSION_TYPE
> wayland
> ```
> 
> I'm using Fedora 34, my system is fully updated
> 
> When I write `flameshot gui` the command returns inmediatly so a `time` will be pointless, it takes between 2 and 3 seconds to actually show de gui, `flameshot config` displays de config ui inmediatly. Also I have a 4K display.

I'm using the same environment and having the exact same issue. This only happens under Wayland and not under x11.

**Comment by waltco** [comment]
For those who are experiencing problem in ubuntu 20.04 uninstall the version from snap and install it with apt: 
`sudo apt install flameshot`
And re-run again with `flameshot gui`
