### ISSUE TITLE
Flameshot v0.6.0 does not open in Fedora: "QSocketNotifier: Can only be used with threads started with QThread"

### ISSUE THREAD

**Issue by renaldofreire** [flameshot-org/flameshot#704]
**Flameshot version**
v0.6.0

**Describe the bug**
Flameshot application does not open. The error message appears: $ flameshot
“QSocketNotifier: Can only be used with threads started with QThread”.

**To Reproduce**
Start Flameshot directly or in bash

**Expected behavior**
Flameshot should work normally. 

**System Information**
Fedora 31 (Workstation Edition).

**Comment by quasipedia** [comment]
I can confirm this bug apply also to Fedora 32 (64bit) beta.  The package itself seems not to install the recommended runtime dependencies (`qt5-qtbase qt5-qtsvg-devel`), but even after installing them manually, flameshot does not run.  It just a further line to the error message:

    QSocketNotifier: Can only be used with threads started with QThread
    QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)

**Comment by p-gonzo** [comment]
Have you tried running `flameshot gui` ?

**Comment by quasipedia** [comment]
Boom!  That fixed it.  It should be fixed, and it should be trivial to do so, in the package though. :)

**Comment by quasipedia** [comment]
Also I live this here as a temporary fix for others.  You can get it to work from shell (as in super key → type flame.. → press Enter) by manually editing the .desktop file.

    sudo vim /usr/share/applications/flameshot.desktop

Then search for the line:

    Exec=flameshot

and modify it into:

    Exec=flameshot gui

**Comment by borgmanJeremy** [comment]
I am going to close this as it is related to v0.6 If you experience this issue on a newer version feel free to reach out.

**Comment by quasipedia** [comment]
Still not working on 0.8.3 (Fedora v.32)

**Comment by quasipedia** [comment]
@borgmanJeremy - Not sure if you noticed the above, so I'm pinging just in case... :)

**Comment by borgmanJeremy** [comment]
I run this on Fedora32 and Fedora33 with no issues or changes (fractional scaling aside).

Are you sure when you run `flameshot` the program is not starting? Do you have a gnome sys-tray extension to show the icon?

**Comment by quasipedia** [comment]
Sorry for the late answer, I stopped trying to use flameshot months ago, honestly, as it was too frustrating.  ¯\_(ツ)_/¯
I'm open to try giving it a new try though, if there is a chance to make it work.

Right now, after a fresh install, all I can do is to go with `flameshot gui` in the terminal and then flameshot will work for exactly one screenshot (which is better than it ever worked so far for me, yay! :smile: ), but there is no icon shown in my panel (all icons of other applications such as Slack, Telegram or Joplin shows correctly).  My gnome extension to display the icons is:

https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

If there is a way to get the icon show, I would be golden. :raised_hands:

**Comment by quasipedia** [comment]
Idk what you did, but after an update, it started working on both my Fedora machines! :raised_hands:
