### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#705]
Hello, I was wondering if the program will be released for OS Windows 10 ....

**Comment by Mackzwellz** [comment]
there are available builds, check here for links and instructions https://github.com/lupoDharkael/flameshot/issues/29

**Comment by mmahmoudian** [comment]
It is clear that we do not have good documentation about windows builds. Flameshot works on windows, we just need to add that to readme and assets.

**Comment by mmahmoudian** [comment]
I asked @szszoke to kindly help with this issue and he kindly accepted my request. Unfortunately, I cannot assign this issue to him and as the result I have to use this comment as a form of assignment. I highly appreciate the help 👍🏼

**Comment by mmahmoudian** [comment]
@ghost We now have an automated process ( #898) to make the following Windows versions thanks to @ZetaoYang :
- portable
- windows installer
