### ISSUE TITLE
Is it possibly to turn up the resolution?

### ISSUE THREAD

**Issue by coldspark29** [flameshot-org/flameshot#706]
**Is your feature request related to a problem?**
I've been using Shutter for quite some time now. GIven it's interface is not really modern and with all the requirements it takes up to 60MB on KDE, I think your application is really awesome. It looks nice, is lightweight and easy to use.

I think the resolution of the images is not the same as the original. It looks a little blurry. Is there a ways to turn the quality up or can you provide one? I have not found a setting for it.

**Comment by borgmanJeremy** [comment]
Can you post your exact setup? I've started looking into this issue. Specifically I am wondering what distro, KDE version, and if you are using xorg or wayland.

**Comment by borgmanJeremy** [comment]
Seems to be duplicate of #506

**Comment by coldspark29** [comment]
I have xorg and KDE. Yes, it seems like duplicate. Closing.
