### ISSUE TITLE
[Feature Req] Add command for area capture from terminal

### ISSUE THREAD

**Issue by Jalopyy** [flameshot-org/flameshot#707]
Yes, I know I can get this via the flameshot gui, but it'd be cleaner and easier if I could do something like 

flameshot area -c -p ~/Pictures/Screenshots/

Instead of having to use the gui at all.

**Comment by mmahmoudian** [comment]
@Jalopyy then how do you define the area? To me this sounds similar to #752 
Also please specify how do you want to define the area? Elaborate on your idea so that devs can completely understand the usefulness of your suggestion.

**Comment by mmahmoudian** [comment]
I'm closing this in favour or #479
