### ISSUE TITLE
Flameshot spams gpaste clipboard in infinite loop

### ISSUE THREAD

**Issue by aurelijusrozenas** [flameshot-org/flameshot#710]
**Flameshot version**
Flameshot 0.6.0+git20190714-1(Debian)
Compiled with Qt 5.12.4

**Describe the bug**
Sometimes when I take print screen and copy to clipboard (select rectangle and press enter) it will spam all gpaste history with same image. It seems it just keep adding the same image in infinite loop, because CPU usage spikes and go down only when I copy something else.

**To Reproduce**
I cannot reproduce this in consistent manner. This happens at least couple times a day but I cannot pin point anything specific. Most of the it works but sometimes it does not.
I am not 100% sure this is only Flameshot related and not some bug in gpaste but _looks_ like Flameshot problem.

**System Information**
Ubuntu 19.10 but I am pretty sure same problem existed on 18.10.

I know there is not a lot information I am just hoping maybe other people also have same problem and will pitch in. Also if there are some ways for me to extract more information from my system - let me know. I will do everything to get rid of this bug because it's killing me.

**Comment by PrestanceDesign** [comment]
Same for me since multiple years on multiple differents versions Ubuntu version and lot of others users as you can see on this Gpaste issue: https://github.com/Keruspe/GPaste/issues/262

**Comment by borgmanJeremy** [comment]
From the comments on the GPaste issue it seems like this happens with shutter too? If so I think we can close it from the flameshot side.

**Comment by Rmano** [comment]
This is (almost for sure) a GPaste bug. https://github.com/Keruspe/GPaste/issues/262. I had to go back to clipboard indicator, that has no support for images.

**Comment by AndriiHaranin** [comment]
I disabled image support for GPaste and it fixed the issue. But preffer to see images in clipboard history.
