### ISSUE TITLE
[Feature] Crayon Tool

### ISSUE THREAD

**Issue by ben-kuhn** [flameshot-org/flameshot#711]
Hi. Can you please add a crayon tool to your wonderful utility here? I find it so useful, but there are many times I need to convey the simplicity of instruction with crayon to adhere to standards my work environment can process.

**Comment by borgmanJeremy** [comment]
Can you describe what you are asking for in more detail? How is Crayon different than pencil tool?

**Comment by ben-kuhn** [comment]
If you notice the date on the feature request it was mostly a lighthearted attempt at humor after a coworker suggested that if I circle things in screenshots using crayon the intended recipient might understand better.

As far as what this might look like, the crayon tool would be wider and have varying line hardness and opacity.  The pencil tool is makes precise lines (like an actual pencil) and doesn't look like it was drawn with crayon.

**Comment by Martin-Eckleben** [comment]
*chuckle

;) :))
