### ISSUE TITLE
Flameshot inaccessable if you disable the tray icon

### ISSUE THREAD

**Issue by maharvey** [flameshot-org/flameshot#712]
**Flameshot version**
Unknown, I can't launch  it
Running on Manjaro Linux and just updated a few minutes ago. so it's undoubtedly the latest version

**Describe the bug**
I disabled the tray icon in flameshot, but now there is no way to get the app to come up, or to re-enable the tray icon. I can see it is running using 'ps' and I can kill it, but I can't get it to come up.

**To Reproduce**
Go into flameshot options and disable to tray tool. Observe that  there is no way to access the application now.

**Expected behavior**
I expected flameshot to run in a normal window when not in "tray mode", or to have a configuration utility that can re-enable it. but really if the app is unusable without the tray, then it should not be possible to disable the tray tool.

**System Information**
Manjaro running standard XFCE. Up to date.

**Comment by mmahmoudian** [comment]
actually there is a way: terminal
try the following commands:
- `flameshot gui`
- `flameshot config`
- `flameshot full`
- `flameshot --help`
