### ISSUE TITLE
What is the default option of flameshot?

### ISSUE THREAD

**Issue by CMCDragonkai** [flameshot-org/flameshot#716]
When I run `flameshot` by itself, nothing happens. But there's nothing indicating what the default option is. Perhaps the default option can be `flameshot gui`?

**Comment by redxtech** [comment]
This is described in the readme (I forget where though).

It will launch the app and add an icon to your system tray.

**Comment by redxtech** [comment]
Just checked and it's at the bottom of this section:

https://github.com/lupoDharkael/flameshot#considerations

It would be nice to have it near the command options section though.

**Comment by CMCDragonkai** [comment]
I'm using xmonad, so I don't have a system tray. So the effect was 
invisible.

**Comment by Martin-Eckleben** [comment]
In my opinion should be described in

```
[martin@martin-laptop ~]$ flameshot --help
Usage: flameshot [flameshot-options] [arguments]

Options:
  -h, --help     Displays this help
  -v, --version  Displays version information

Arguments:
  gui            Start a manual capture in GUI mode.
  screen         Capture a single screen.
  full           Capture the entire desktop.
  config         Configure flameshot.
```

But would not change behavior as by far most people using it probably have system trays?

**Comment by Martin-Eckleben** [comment]
Will be improved by [https://github.com/flameshot-org/flameshot/pull/827](url).

Will close this issue.
If you think it should be discussed more in depth comment and I'll reopen it.
