### ISSUE TITLE
Crash on screenshot

### ISSUE THREAD

**Issue by redxtech** [flameshot-org/flameshot#718]
**Flameshot version**
v0.6.0

**Describe the bug**
The app launches just fine, but when I take a screenshot it crashes. Everything is fine up until I have made the selection, but when I click one of the buttons (save image, upload to imgur, etc.) it crashes without doing anything.
Whenever I run `flameshot` from the command line everything works as expected, but when I launch it through the app launcher (or autostart on boot) it doesn't work.
I have looked at the application file and have confirmed that it is being launched from the same binary as from the command line and there are no additional arguments being passed.

**To Reproduce**
Launch flameshot from the app launcher or autostart. Start taking a screenshot. Click on one of the options to save the image (upload, save to disk, etc). Observe the crash.

**Expected behavior**
I would expect it to save the selection or upload it to imgur, based on the selected button, without crashing.

**System Information**
Distro: Arch Linux
Kernel: 5.6.3
DE: KDE 5.18.4

**Comment by mmahmoudian** [comment]
@redxtech it has been a long time since this bug report, is the issue still persists? if so, please specify your current Flameshot version and also the repo you installed it from (AUR or community arch repo).

**Comment by mmahmoudian** [comment]
@redxtech Please try it with the newly released version 0.8:
https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0
