### ISSUE TITLE
Does Flameshot support Text annotation

### ISSUE THREAD

**Issue by tkumark** [flameshot-org/flameshot#719]
I do not see the option for text annotation. Can this feature be added?

**Comment by AnthonyBerisha** [comment]
Is somebody working on this ? I'd be delighted to try adding that

**Comment by Kritolan** [comment]
Enable this option in settings
![image](https://user-images.githubusercontent.com/61403394/81393197-1ee2aa00-914a-11ea-9976-20708bb2a143.png)

**Comment by Kritolan** [comment]
Just enable this option in settings

**Comment by tkumark** [comment]
@Kritolan which version do you have in the version I am looking at Flameshot 0.5.1-1(Debian) Compiled with QT 5.9.4. There is not Text option. I am using Ubuntu 18.04

I installed using `sudo apt install -y flameshot`

![image](https://user-images.githubusercontent.com/2689801/81673376-2fa46000-9469-11ea-9283-595d05404314.png)

**Comment by ca-scribner** [comment]
Yeah I don't see text either.  Seemed like a really odd omission so I'm guessing it is a bug?

**Comment by AnthonyBerisha** [comment]
Same situation as @tkumark

**Comment by neural-oD** [comment]
Same issue here. Love flameshot btw - this I think might be a bug, or if it isn't it should be implemented asap.
Thanks to all the contributors working on this!!!

**Comment by thepisu** [comment]
The Text feature has been included in release 0.6.0, that you can download here:
https://github.com/lupoDharkael/flameshot/releases

@lupoDharkael : I think that this issue can be closed as resolved.

**Comment by tkumark** [comment]
Thanks this is great! @lupoDharkael @thepisu  could some thing be done so that the latest be installed when people run apt install?

**Comment by mrnagydavid** [comment]
I cloned the repo and built the app from source. Still no text editing option. Not even in `flameshot config`.

I just downloaded 0.6.0 from `https://github.com/lupoDharkael/flameshot/releases` and I still don't have the text editing option.

```
$ flameshot -v
Flameshot v0.6.0
Compiled with Qt 5.9.5
```

On Ubuntu 18.04.

Any idea?

**Comment by neural-oD** [comment]
@mrnagydavid - have a look at my post above, just follow the steps. You have to enable it in the config....

**Comment by mrnagydavid** [comment]
Thank you!

As I said, I couldn't find the it in config panel either. I should have taken a screenshot... Anyway, it is fixed now. I'll take the blame on this one.
