### ISSUE TITLE
Choose custom colors of color wheel

### ISSUE THREAD

**Issue by TCastelein** [flameshot-org/flameshot#720]
I would like to customize the colors in the color wheel activated when right mouse clicking. I see in the code that there is a setting called `userColors` however i fail to add it correctly to the `ini` file so i don't have it working.

Can anybody help me with an example of how to edit the `userColors` or the feature request of setting the colors through the CLI just like main and contrast color.

**Comment by socketbox** [comment]
Yes, this would be nice. The code seems to indicate that a list of strings will be read in from the INI file, but none of the following work.
```
userColors={"black","white",...
userColors=@Variant(\0\0\0\x43\xff\xff\xffx\x86\x00\x00\x00\0\0)     
userColors={"#ffffff", "#000000
```
 `syslog` shows `qt5ct: custom style sheet is disabled`, apparently after the application fails to parse the file.

**Comment by nst0022** [comment]
The syntax is:

`userColors=#800000, #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080`

= default colors = darkRed, red, yellow, green,    darkGreen, cyan, blue, magenta, darkMagenta

**Comment by socketbox** [comment]
@nst0022 I'm sorry, I must be dense, but putting that exact line in my `~/.config/Dharkael/flameshot.ini` file prevents the app from opening.

That is, if I add `userColors` as you've typed...
```
[General]                                                                                                                                                      
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\xf\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\xf\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe)                                                                                                                                     
contastUiColor=@Variant(\0\0\0\x43\x2\xff\xff\x39\b\xeb\xf9\xe9\xce\0\0)                                                                                       
disabledTrayIcon=false                                                                                                                                         
drawColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)                                                                                                  
drawThickness=0                                                                                                                                                
filenamePattern=flameshot-%F-%T                                                                                                                                
savePath=/home/socketbox/Desktop/Screenshots                                                                                                                         
showHelp=true                                                                                                                                                  
uiColor=@Variant(\0\0\0\x43\x2\xff\xffx\x86\xff\xff\xff\xff\0\0)                                                                                               
userColors="=#800000", #ff0000, #ffff00, #00ff00, #008000, #00ffff, #0000ff, #ff00ff, #800080                                                                  
```
and then run `/usr/bin/flameshot gui -p /home/socketbox/Desktop/Screenshots/` no GUI is displayed. When I remove the `userColors` line, the application presents a UI.

**Comment by nst0022** [comment]
It works here with
```
Flameshot v0.6.0-70-g91ba28c
Compiled with Qt 5.11.3
```

**Comment by socketbox** [comment]
@nst0022 Thanks, I was able to compile the commit you mentioned with Qt 5.12.2 and the `userColors` option works.

**Comment by socketbox** [comment]
I cannot, however, get the compiled application to run with the `gui` argument. When I run it with no arguments whatsoever, an icon appears in the "system tray" and I can then click on that icon and I've got all the functionality (and custom colors) that I could want. But running the application with `gui` produces no output whatsoever; not on the command line, and not within the Qt Creator debugger.

**Comment by Malorn44** [comment]
How would I compile the newer version with qt. It doesn't seem to be able to update as it says the newest version for me is v0.5.xxx in Ubuntu

**Comment by socketbox** [comment]
@Malorn44 I cloned and, immediately prior to building, pulled from the repo. What version of Ubuntu are you running?
