### ISSUE TITLE
Need keyboard shortcut.

### ISSUE THREAD

**Issue by rajeshisnepali** [flameshot-org/flameshot#726]
I believe many of us have a problem changing the tool's thickness via mouse scroll. It sucks when on a laptop. It's so hard to control or make a proper thickness.

If it's possible, I'm requesting to make a shortcut `(Ctrl+plus(+))` to increase & `(Ctrl+minus(-))` to decrease the thickness or any other keys combination.

**Comment by Chudry** [comment]
Yes for linux go to settings > keyboard > + . Here you can add name of program, command which will launch on specific key press command is ( flameshot gui ) and lastly key board short cut ...  i applied this solution on Debian based linux 
For windows definitely there is keyboard shortcut setting add them with same command i believe ..

![image](https://user-images.githubusercontent.com/54190262/80147444-8234df80-8581-11ea-9b57-02040ec27df6.png)

**Comment by rajeshisnepali** [comment]
@Chudry I think you're getting it wrong. I already have assigned the keyboard shortcut for `flameshot-gui`.

![image](https://user-images.githubusercontent.com/23610013/80298339-f6060080-87aa-11ea-9b67-3f68e7426e46.png)

As you can see help (hint) in the picture below. It says scroll mouse wheel to change the thickness of your tool. 
I just want to change the thickness with the help of keyboard shortcuts rather than with mouse wheel.

![flameshot_hint](https://user-images.githubusercontent.com/23610013/80298429-07034180-87ac-11ea-979a-c6ef08ba6971.jpg)
![width](https://user-images.githubusercontent.com/23610013/80298432-0b2f5f00-87ac-11ea-9087-66fdd52c39f9.jpg)

**Comment by Chudry** [comment]
Sorry i get it wrong, i also did not find as such any thing in flameshot config

**Comment by rmakinn** [comment]
One hacky solution I tried is with an external tool to emulate input devices - you would trigger it with a custom keyboard shortcut in your window manager/desktop environment. 

I have this for general purpose use anyway. But with `flameshot` there is an irritating issue - it doesn't seem to pass keyboard input back to `flameshot` properly, so your keyboard shortcuts such as Esc or Return won't work after this. You have to click the GUI elements 😒

I use i3 as a window manager and the program I'm using is `xdotool`. The commands `xdotool click 4` and `xdotool click 5` emulate a mousewheel up/mousewheel down, respectively. You could set them to some memorable combination like Super+PgUp & Super+PgDn. 

In my i3 config I have this: 

```
bindsym $mod+Prior exec xdotool click 4
bindsym $mod+Next exec xdotool click 5
```

It seems a non-hacky solution would involve updating flameshot itself. I don't know C++ or QT, but the code in question is here and some of the neighbouring code is also relevant: https://github.com/lupoDharkael/flameshot/blob/b42f1cf01dd95c355e5fd401cac12fb0117dc25b/src/widgets/capture/capturewidget.cpp#L512

**Comment by rajeshisnepali** [comment]
Thanks, @rmakinn I really appreciate your comment.
But for me, it seemed a long  & quite tricky process.

I'm in  "Mutter" WM (20.04) and changing WM feels like a quite tricky (I don't know much about i3 & I haven't done it before)

If @lupoDharkael had implemented the same thing compiled to the app, that would have been great.

**Comment by borgmanJeremy** [comment]
Flameshot now has built in shortcut keys.

**Comment by rajeshisnepali** [comment]
Still can't configure keys for controlling **thickness** (disabled)

**Comment by borgmanJeremy** [comment]
The tools are disabled by default. First enable them:
Configuration > Buttons > Increase Tool Size, Decrease Tool Size.

Then enable the hotkeys (you might need to close and reopen the config)
Shortcuts > Increase the size of other tools
Shortcuts > Decrease the size of other tools
