### ISSUE TITLE
Capture area and save to a directory

### ISSUE THREAD

**Issue by jjnilton** [flameshot-org/flameshot#73]
Hi, is it possible to capture an area, save and copy to clipboard? I'm trying with `flameshot gui -c -p /path/` but it seems it just work with `full` command. Would be good to backup the area screenshots you take.

And I'd like to suggest the option to choose the default action after pressing enter in `gui` mode, some may want to quickly upload and get the URL to the clipboard instead of the image itself.

And thanks for this tool, it's awesome.

**Comment by lupoDharkael** [comment]
This could be solved when I implement custom shortcuts inside the app with the option to combine multiple actions to a single shortcut.

**Comment by KarlWithK** [comment]
Sorry this was two years ago, but is his resolved? I can't find documentation on it.

**Comment by ElijahLynn** [comment]
Cross linking similar issues:
* https://github.com/lupoDharkael/flameshot/issues/546
* https://github.com/lupoDharkael/flameshot/issues/394
* https://github.com/lupoDharkael/flameshot/issues/73
* https://github.com/lupoDharkael/flameshot/issues/734

**Comment by borgmanJeremy** [comment]
Custom shortcuts are now implemented in 0.9.
