### ISSUE TITLE
Copy to clipboard on select, save to file on close (by default)

### ISSUE THREAD

**Issue by spxak1** [flameshot-org/flameshot#734]
It would be great if we had two options on configuration:

1. Copy to clipboard on select. That is as soon as I select a part of the screen, it immediately puts it on the clipboard. If you do further editing, resize etc, you will then have to click the "copy to clipboard" button to replace the previous one with the edited one. This way, when you do lots of screen captures without the need of editing, you don't need the extra step of selecting to copy to clipboard. Also, if you forget to press the button on such simple screen-grabs, you then need to do it again as nothing is in the clipboard after you close. This can be a setting in the options, some people might not want to have it on by default. But it will make a huge difference to some (like myself).

2. Save to file on close. Again, this should be an option, but for me it would be a lifesaver as I sometimes forget to save (on clipboard or to file) and have to start over. So when this option is ticked, you won't need to click save to file. When you close the capture window, it saves the last version. If you want multiple versions, you just save as you modify using the button. I appreciate that if you modify, save, then modify but don't care to save the last modification, you still end up with two saved images, one of which you do not need. But you still get the one you do, and you never know, you might like the other one too. In the end, that is an option, you don't need/like, you disable.

Thank you for your work, it has certainly made a change in my life. I appreciate your time and effort and thanks for hearing me out, in advance.

**Comment by ElijahLynn** [comment]
Cross linking similar issues:
* https://github.com/lupoDharkael/flameshot/issues/546
* https://github.com/lupoDharkael/flameshot/issues/394
* https://github.com/lupoDharkael/flameshot/issues/73
* https://github.com/lupoDharkael/flameshot/issues/734

**Comment by borgmanJeremy** [comment]
The second request is now merged to master. Will leave this open for the 1st request.

**Comment by borgmanJeremy** [comment]
I do not think we will add the first request. With the new hotkey system you can map "copy" to a easy to hit key and it will close the UI.
