### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by tomberry88** [flameshot-org/flameshot#736]
Hi, and thanks for your work. This app is absolutely fantastic, but on my distro is only in english language.

I tried to translate it, but this is my first work on qt linguist (I'm usually used to po files) and I probably did something wrong.

This is a qm file of internationalization for italian language, can you see if it's okay?

I copied it to **/usr/share/flameshot/translations** , but the app always remains in English.

**Flameshot version**
0.6.0-11(Debian)
Compiled with Qt 5.11.3

System Information
Debian 10.3 (Buster) z86_64
GNOME 3.30.2
Kernel: 4.19.0-8-amd64

[Internationalization_it.zip](https://github.com/lupoDharkael/flameshot/files/4582143/Internationalization_it.zip)

**Comment by borgmanJeremy** [comment]
Italian translation is now merged.
