### ISSUE TITLE
I would like to annotate existing image files from my computer

### ISSUE THREAD

**Issue by kramer65** [flameshot-org/flameshot#737]
Often I create a screenshot, annotate it, and then save the file. If I then want to add some more text or arrows, I cannot open the same file in flameshot.

In other occasions I made a screenshot with my normal printscreen button and later realise I want to annotate the file. In this case I would also like to use flameshot as an annotation tool.

It would be really awesome if there would be a button option "Open File" under "Open Launcher" in the dropdown.

**Comment by romainreignier** [comment]
I have the same issue.
But I have just discovered ksnip that allows to open existing files: https://github.com/ksnip/ksnip
I will give it a try.

**Comment by mmahmoudian** [comment]
I will close this in favour of #1100 as it has some discussions on the topic. @kramer65 please feel free to comment if you think the #1100 is not what you suggested here (I might have misunderstood your point)
