### ISSUE TITLE
Flameshot does not launch

### ISSUE THREAD

**Issue by SuShY28** [flameshot-org/flameshot#738]
**Flameshot version**
0.6.0+git20191001-2

**Describe the bug**
Flameshot does not launch when i select in menu or in command

**System Information**
Debian bullseye/sid x86_64 Kernel 5.6.0-1-amd64

**Comment by mmahmoudian** [comment]
Can you confirm if the issue still persists? also would you please let us know the window manager you are using and also what command in terminal did you use.

**Comment by SuShY28** [comment]
Hello, it's ok.
