### ISSUE TITLE
Giant arrows. Any way to adjust size?

### ISSUE THREAD

**Issue by danielrosehilljlm** [flameshot-org/flameshot#740]
Is there any way to adjust the width and size of the drawn objects like the arrow?

Mine looks a little ridiculous!

![Arrow](https://i.imgur.com/xaMlCgi.png)

**Comment by Kritolan** [comment]
Use mouse scroll for resize elements

**Comment by danielrosehilljlm** [comment]
> Use mouse scroll for resize elements

Thank you! Mystery solved!
