### ISSUE TITLE
Add Flameshot to GitHub Sponsors

### ISSUE THREAD

**Issue by ElijahLynn** [flameshot-org/flameshot#741]
@lupoDharkael Love Flameshot, it is the best screenshot tool I've used on Linux in past 10 years! 

Not sure if GitHub sponsors is available for this project yet but if it is I would like to encourage you to sign up for it to make it easy for others to send some cash to this project. 

See if you can sign up here https://github.com/sponsors, and I'll commit to $5/month for a year ($60 USD) if you can make it happen.

**Comment by JohnPucciarelli** [comment]
I would make a similar commitment. Would love to see screencast support added.

**Comment by borgmanJeremy** [comment]
Thanks for the offer! We are now a group of people working on the project so at this time we do not have a  good way to manage financial donations. 

The best way to support is with detailed bug reports, new ideas , or translations.

Thanks for helping make this a better tool👍

**Comment by ElijahLynn** [comment]
Noted, thanks!
