### ISSUE TITLE
Changing the config file location

### ISSUE THREAD

**Issue by Borroot** [flameshot-org/flameshot#743]
## Problem
Currently the configuration file for flameshot is saved in the `$HOME/.config/Dharkael/` folder. The name of this folder is not intuitive, since the name of the program is flameshot and not Dharkael.

## Solution
A more intuitive configuration file folder would be `$HOME/.config/flameshot/`. In order to allow for even more flexibility and backward compatibility an option could be added such that the user can choose the location by specifying a command line argument. However, this could be considered bloat, so the changing of the directory name is favored.

**Comment by borgmanJeremy** [comment]
@mmahmoudian  I agree this should be done for the 0.8 release especially since all the DBus names changed to flameshot. We just need to be really clear in the release notes so users know to move their config files.

**Comment by borgmanJeremy** [comment]
Actually this is already completed due to the changes related to DBus and XDG.
