### ISSUE TITLE
Adding straight vertical line

### ISSUE THREAD

**Issue by elman22** [flameshot-org/flameshot#744]
Flameshot is perfect screenshot application and I use it daily. Great work. Thanks.

I do have a feature request. Flameshot allows me to draw straight line at 0° and 180° angle by snapping the line. Would it be possible to snap also at 90° and 270° angle?

**Comment by borgmanJeremy** [comment]
I was looking into adding this, but I don't see how to even snap at 0 or 180. Could you describe how you do this?

**Comment by elman22** [comment]
Cool. I was thinking something like this https://docs.substance3d.com/spdoc/files/182266596/182266623/1/1564743514934/straight_line_snap_optim.gif (Shift+Ctrl is snapping every 15°). So when I'm drawing an arrow or line without any key pressed, line is drawn just like now. Then I press for example Shift and line start snapping at 0°, 90°, 180° and 270°.

Main use case for me is that sometimes I comment web designs and I want to show that elements are not correctly aligned. For this straight line (horizontal or vertical) is very usable. Like this

![image](https://user-images.githubusercontent.com/9151352/86944912-aea3d500-c148-11ea-9b51-2e0baf5146fe.png)

and imagine straight line :)

**Comment by borgmanJeremy** [comment]
I went to implement this and it looks like its already there. If you hold ctrl while rotating the line it should work:

![Peek 2020-07-08 12-24](https://user-images.githubusercontent.com/46930769/86950653-09700900-c116-11ea-9f5f-5fa3d9c6ffd2.gif)

**Comment by elman22** [comment]
Hmm.. it doesn't work for me in Flameshot 0.6.0 (Qt 5.14.1) on Manjaro Linux KDE.

**Comment by borgmanJeremy** [comment]
Looking through the commit logs it looks like it was merged in after the 0.6 release. You can either build from source or since you are on Manjaro install the git version from the AUR.

https://github.com/lupoDharkael/flameshot/commit/b42f1cf01dd95c355e5fd401cac12fb0117dc25b

**Comment by elman22** [comment]
Excellent. Thanks for the info.

Interestingly on Pop OS I have version 0.6.0+git20191001-2 a this new feature already works.
