### ISSUE TITLE
add feature auto copy url when upload succesful to imgur without click "copy to url"

### ISSUE THREAD

**Issue by 3xploiton3** [flameshot-org/flameshot#745]
**Is your feature request related to a problem?**
Please, a single feature per issue.

add feature auto copy url when upload succesful to imgur without click "copy to url"

**Comment by ElijahLynn** [comment]
I saw an option for this in `master` today... K, just tested it and it is working. So it looks like this feature is on it's way to the next release. 

![image](https://user-images.githubusercontent.com/1504756/81879964-fc350480-9540-11ea-8bd8-6edd7c085fd6.png)

![image](https://user-images.githubusercontent.com/1504756/81879956-f6d7ba00-9540-11ea-822a-815820a01f7f.png)

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/81970469-cc255880-9649-11ea-87b6-90b48978a36a.png)

**Comment by ElijahLynn** [comment]
What is output of:
```
❯ flameshot --version
Flameshot v0.6.0-74-gdfde97e
Compiled with Qt 5.14.2
```

**Comment by borgmanJeremy** [comment]
Yup! This will be in the upcoming 0.8 release.
