### ISSUE TITLE
please, flameshot's flatpak

### ISSUE THREAD

**Issue by marinho8bit** [flameshot-org/flameshot#749]
please, flameshot's flatpak
if possible, published on flathub.org

**Comment by borgmanJeremy** [comment]
Flatpack support will be added in the next release

**Comment by marinho8bit** [comment]
excelent!

**Comment by mmahmoudian** [comment]
@marinho8bit do you think this issue is addressed? if so, let me know to close it as the Flatpak is on it's way as @borgmanJeremy has already took care of it in the codebase.

**Comment by marinho8bit** [comment]
resolved

Em sex., 4 de set. de 2020 às 19:36, Mehrad Mahmoudian <
notifications@github.com> escreveu:
