### ISSUE TITLE
It would be nice to add rectangle selection option  in command line

### ISSUE THREAD

**Issue by violetu** [flameshot-org/flameshot#752]
**Is your feature request related to a problem?**
No

It would be nice to add rectangle selection option  in command line, so that I can use it in backgroud mode to select rectangle area to help me in some useful aspect, such as a shell script using flameshot and tesseract to recognize what I select.

**Comment by mmahmoudian** [comment]
@violetu can you elaborate more on your idea? For example, you would like to give it the coordinates of the top-left corner and width and height or give it two coordinates (top-left, bottom-right)? Do you want it to show it in `flameshot gui` or you want it to be done and saved in a file (or clipboard) as an argument to `flameshot full`? just lay down your idea in more detail so that everyone can better understand the usefulness of the idea.

**Comment by violetu** [comment]
Yeah, I think I mean the same meaning of the issue you mentioned.
Take the screenshot software `spectacle` for instance,（`scrot` have a little this  kind of feature, too）
It provide a backgroud mode（or quiet mode） for command line usage or shell script usage.
Here is some options of `spectacle`：

```
  -a, --activewindow         Capture the active window
  -r, --region               Capture a rectangular region of the screen
  -g, --gui                  Start in GUI mode (default)
  -b, --background           Take a screenshot and exit without showing the GUI
  -o, --output <fileName>    In background mode, save image to specified file
  -d, --delay <delayMsec>    In background mode, delay before taking the shot
                             (in milliseconds)
  -c, --clipboard            In background mode, copy screenshot to clipboard
```
Features:
1. background mode which mean after the software capture the screenshot, it'll exit and don't keep itself background.
2. it's screenshot(capture result) can be save to file or clipboard following provided commands ( int here, `-o` option and `-c` option)
3. the **most** attractive feature is  what the `-r` ,`-b`,`-o or -c` option provide. It makes you capture a rectangular region of the screen without GUI and save it to clipboard or  file following your provided commands.

GIF demo:
unfortunately, the function of save  to file in backgroud mode of spectacle recently have issues, [bug link](https://bugs.kde.org/show_bug.cgi?id=425573), so I can only demostrate  the feature of capturing rectangular screenshot in background mode.

![peek 2020-09-18 21-07](https://user-images.githubusercontent.com/33022132/93602328-0edeaf00-f9f5-11ea-9592-bb3e61541ecd.gif)

**Comment by mmahmoudian** [comment]
I think the functionality is to some extent already implemented in Flameshot.

- To close/quit the Flameshot after the capture: `flameshot config` > go to General tab > enable "Close after capture"
- To save the image automatically: `flameshot config` > go to General tab > enable "Save image after copy"

Combination of these two configurations and then `flameshot gui` would give you the general setup of what you showed in the gif.
(Of course, if you are try the AppImage, you should replace the `flameshot` with `./Flameshot-0.8.0-x86_64_931.AppImage`)

Defining the area of the rectangle is not implemented (which I think s the concern of your feature request) and also screenshot from active window is not implemented either, but I'll open a feature request for it as that is something I miss from OSX.

**Comment by violetu** [comment]
Got it.
Thank you for your detailed explanation.
