### ISSUE TITLE
Is Canonical Launchpad monitored for errors?

### ISSUE THREAD

**Issue by mystiquewolf** [flameshot-org/flameshot#753]
**Flameshot version**

0.6.0+git20191001-2(Debian)
**Describe the bug**

I frequently receive flameshot crashes after login/start of Ubuntu. These are sent to launchpad, and twice i have filed error reports via Apport.
**System Information**

Ubuntu 20.04 Focal Fossa

**Comment by AlexP11223** [comment]
Sadly, even this repo is not monitored much (or at all) anymore :(
There lots of unmerged PRs, etc.

**Comment by mmahmoudian** [comment]
@mystiquewolf There will be a release soon, but at the moment try to update the Flameshot as you are getting it from a build based on git.

-------

@AlexP11223 the Flameshot now has transformed into an organization with multiple maintainers and as you can see, the number PRs and Issues are reducing and soon there will be a release. In case you want to join the community, please visit [flameshotworkspace.slack.com](https://flameshotworkspace.slack.com) 😃

**Comment by AlexP11223** [comment]
> In case you want to join the community, please visit [flameshotworkspace.slack.com](https://flameshotworkspace.slack.com) smiley

I did already :D

**Comment by mystiquewolf** [comment]
> Also, would you please mention your Desktop Environment (Gnome, KDE, Xfce, ...) or Window Manager (dwm, i3, bspwm, xmonad, ...)
Gnome 3.36 on Ubuntu 20.04. Was using x.org previously, but switched to Wayland. I have stopped sending the errors, i'll wait for the new release and then continue sending them. Just check the issues here: https://bugs.launchpad.net/ubuntu/+source/flameshot

**Comment by mmahmoudian** [comment]
I keep this issue open, but keep the label "unconfirmed bug". Please let us know if the issue persists after updating Flameshot.

**Comment by mystiquewolf** [comment]
Do you mean after you release the update that you said you were planning to release and i receive it via "Software updater"? Or i need to do something else?

**Comment by mmahmoudian** [comment]
Yes, please report back when you got the next release. you can either get it from your OS repo or Flatpak or compile it yourself. I appreciate the time you spent on this 👍

**Comment by mystiquewolf** [comment]
Are you going to release a flameshot update soon?

**Comment by borgmanJeremy** [comment]
@mystiquewolf Please install via snap for the most up to date Ubuntu releases. It is not up to me when your distro will package the new .deb.

**Comment by mmahmoudian** [comment]
@mystiquewolf As @borgmanJeremy  correctly suggested, please try either snap or `.deb`, and please report back of this issue is resolved or is still persisting.
