### ISSUE TITLE
Can't bind keyboard shortcut with sxhkd

### ISSUE THREAD

**Issue by provomeister** [flameshot-org/flameshot#759]
**Flameshot version**
Flameshot v0.6.0-70-g91ba28c
Compiled with Qt 5.14.2

from [https://aur.archlinux.org/packages/flameshot-git/](https://aur.archlinux.org/packages/flameshot-git/)

**Describe the bug**
I can launch the program by one of the three lines below, but it's impossible to launch it from my configuration file for sxhkd.

I tried to configure other programs on the Print key and I had no problems so the problem seems to come from "flameshot".

**To Reproduce**
I tried with "flameshot" from the official repos & "flameshot-git" from the AUR.

- Download the package "flameshot-git" from the AUR or "flameshot" from the official repos.
- Add a shortcut for "flameshot" in .config/sxhkd/sxhkdrc with one of these commands:

> Print
&nbsp;&nbsp;&nbsp;&nbsp;flameshot gui
&nbsp;&nbsp;&nbsp;&nbsp;/usr/bin/flameshot gui
&nbsp;&nbsp;&nbsp;&nbsp;XDG_CURRENT_DESKTOP=gnome flameshot gui

- Launch sxhkd in .xinitrc or .xprofile with the following line:
> sxhkd &
- Launch "flameshot" with "Print" key, no result.

**Expected behavior**
Launch "flameshot" with "Print" key from sxhkd config.

**System Information**
Arch 5.6.15 w/ dwm

**Comment by mmahmoudian** [comment]
Please try the following in terminal and report back:

```
flameshot &
flameshot gui
```

**Comment by SKYFOX1301** [comment]
I did set the keybind to print as mentioned above, and it WORKED for me!!
