### ISSUE TITLE
Let me run FlameShot with the Hot key.

### ISSUE THREAD

**Issue by mailsjb** [flameshot-org/flameshot#763]
I'm using Flameshot too well. Thank you very much. However, there is one function that is absolutely necessary. It needs a Hot Key to run Flameshot. It is inconvenient to click the Flameshot icon on the taskbar with your mouse every time. And sometimes you need screenshots right from the pop-up screen, but they disappear the moment you go to press the FlameShot icon. Please make one Hot Key setting that can be implemented.

**Comment by ryanerwin** [comment]
Your desktop environment should be able to take care of this.

In KDE Plasma you can edit the "Global Shortcuts"
In Gnome you can go to Settings >> Keyboard Shortcuts
If you're using another desktop, the https://wiki.archlinux.org/ probably has tips on how to configure shortcut keys.

Then setup different to work with Print Screen (probably just `flameshot gui`) or the shortcut key of your choice.

Note that Flameshot includes a list of example shortcut keys

https://github.com/lupoDharkael/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde

**Comment by Tejeev** [comment]
xfce Desktop:
![image](https://user-images.githubusercontent.com/8906089/90630532-186bd000-e219-11ea-9987-e147ae594252.png)

**Comment by mmahmoudian** [comment]
This is duplicate or #681 . I'm closing this as ut has been answered by @Tejeev and @ryanerwin .
