### ISSUE TITLE
Option to decrease picture information

### ISSUE THREAD

**Issue by andersfylling** [flameshot-org/flameshot#765]
My scenario:
Take a screenshot, blur it and use it for my lockscreen.

I wonder if decreasing the picture information by skipping pixels before taking a printscreen could speed up the performance. Example if I give a psuedo argument "flameshot screen -n 0 -scale x0.5" would it be possible to re-use the same pixel for every second pixel?

Since it's already in the cache I assume that would be a plausible speed up?

I'm asking since there is no need for me to store every pixel since I will blur the image afterwards.

**Comment by borgmanJeremy** [comment]
Since this is a very specialized use case I don't think we will implement it. There are other terminal commands that can be used to down sample the image.
