### ISSUE TITLE
Fix upcoming compatiblity issue with Plasma 5.20

### ISSUE THREAD

**Issue by meven** [flameshot-org/flameshot#766]
Kwin screenshot effect with https://phabricator.kde.org/D29407 will require to add `X-KDE-DBUS-Restricted-Interfaces=org.kde.kwin.Screenshot
` to its .desktop file to stay compatible with Plasma 5.20
In turn it will allow to take screenshot without confirmation click (i.e flameshot will be able to take immediate screenshot like spectacle https://phabricator.kde.org/D29408)
In https://github.com/lupoDharkael/flameshot/blob/91ba28c3ded7ca3314f02418761c982069cf8b33/docs/desktopEntry/package/flameshot.desktop#L30

Also FYI the screenshot effect can now take non-downscaled fullscreen screenshots in Wayland since Plasma 5.19 https://phabricator.kde.org/D29122 using `screenshotFullscreen(QDBusUnixFileDescriptor fd, bool captureCursor = false, bool shouldReturnNativeSize = false);`

**Comment by Martin-Eckleben** [comment]
@meven I don't 100% get the downscaling part.
Did Plasma < 5.19 in combination with Wayland automatically downscale the screenshots it took?
Asking instead of testing to save time.

**Comment by meven** [comment]
> @meven I don't 100% get the downscaling part.
> Did Plasma < 5.19 in combination with Wayland automatically downscale the screenshots it took?
> Asking instead of testing to save time.

Yes, when the user has a scaling factor. (https://bugs.kde.org/show_bug.cgi?id=409762)

**Comment by borgmanJeremy** [comment]
@meven Can you checkout #862 ? I think this will comply with Plasma 5.20, thanks for the heads up.
