### ISSUE TITLE
Add counter tool (Feature Request)

### ISSUE THREAD

**Issue by ztNFny** [flameshot-org/flameshot#769]
Add a tool to quickly insert an incrementing counter. This is very useful when trying to communicate someone the order of steps.

Inspired by Greenshot.

**Comment by borgmanJeremy** [comment]
I've added this on my fork. I can get a PR to mainline it if this is still an active project
https://github.com/borgmanJeremy/flameshot

**Comment by ztNFny** [comment]
@borgmanJeremy please create a PR I'd say.
Are there Windows builds of your fork?

**Comment by borgmanJeremy** [comment]
Ok, having issues building on the latest release of QT so I'll get that cleaned up and submitted in a PR. I only build on linux so I am not sure. If the mainline builds on windows none of these changes should break it. I can boot to a windows VM if you aren't set up to test it.

**Comment by borgmanJeremy** [comment]
Ok, looks like it builds on the windows appveyor. Check it out and let me know what you think. #770

**Comment by pbulteel** [comment]
Shutter could do this as well. A circle with a number inside. How's does this look in your build? Their implementation worked but wasn't customizable (it always started at 1 and the shape was always a circle.)

**Comment by borgmanJeremy** [comment]
That's how mine works as well, always starts at 1 and is in a circle. It wouldn't be hard to add more shapes if that was desired. 

I'd like to ultimately let you choose a starting number but didn't have a good way to integrate that into the existing UI.
![image](https://user-images.githubusercontent.com/46930769/84439024-1a078f00-abfd-11ea-91d0-d7754e4d1f95.png)

**Comment by pbulteel** [comment]
[Feature request] - Easter egg... make it use random numbers on April 1st. (April fools!) Disable it with --no-april-fools. 

Kidding! That looks good. I assume the colour is tweakable like with other parts.

**Comment by ztNFny** [comment]
Imho starting at 1 is ok. For my uses i gardly ever go >10 and if i dont want to start at 1 i can just delete those lower numbers, right?

**Comment by pbulteel** [comment]
The only reason for not starting at 1 is that you've already have an image with the 1. I've had to add numbers to my screenshots (when they were taken with shutter) and the only way I could do it was by putting the 1, 2, etc over the existing bubbles/numbers. Not a big deal.

**Comment by borgmanJeremy** [comment]
> Kidding! That looks good. I assume the colour is tweakable like with other parts.

Yeah the background color is tweakable through the main color wheel. 



> Imho starting at 1 is ok. For my uses i gardly ever go >10 and if i dont want to start at 1 i can just delete those lower numbers, right?

Actually the main UI doesn't support deleting or moving elements once they are placed. This might be a good separate global feature to add.

**Comment by ztNFny** [comment]
> Ok, looks like it builds on the windows appveyor. Check it out and let me know what you think. #770

Could you share the https://transfer.sh/ link please? Won't be back at my Windows Dev machine until next week.

> Actually the main UI doesn't support deleting or moving elements once they are placed. This might be a good separate global feature to add.

I thought it was possible in the sidebar but that undoes all the steps, not just single steps, my mistake. But it should be possible to just put 2 right on top of 1, thereby making it seem to start at 2, that'd good enough imho.

**Comment by borgmanJeremy** [comment]
Im not sure how to pull the transfer.sh link from the appveyor log: https://ci.appveyor.com/project/lupoDharkael/flameshot/builds/33470260/job/5eusv72qjuiwecrs

**Comment by ztNFny** [comment]
@borgmanJeremy  it should be right there at the bottom, line 600, but it seems something went wrong

**Comment by ztNFny** [comment]
Build with just number circles (by borgmanJeremy):
https://transfer.sh/12X4z8/flameshot_0.6.0_win_x86.zip
https://transfer.sh/fjhEU/flameshot_0.6.0_win_X64.zip

Build with number circles and also all the changes from DrunkenPoney/flameshot merged:
https://transfer.sh/SY4KW/flameshot_0.6.0_win_X64.zip
https://transfer.sh/if7d1/flameshot_0.6.0_win_x86.zip

**Comment by borgmanJeremy** [comment]
I just merged this. It will be present in the next release.
