### ISSUE TITLE
Keyboard shortcuts do not work

### ISSUE THREAD

**Issue by karthikiyengar** [flameshot-org/flameshot#773]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)

**Describe the bug**
None of the flameshot shortcut bindings seem to work under XMonad. However, switching to other DE/WMs works.

**To Reproduce**
Execute `flameshot gui` under xmonad

**Expected behavior**
The shortcuts should work. Please see referenced issue for additional details. The shortcuts seem to work with the AppImage.

**System Information**
Ubuntu 20.04 LTS, xmonad

**Comment by ShawnSquire** [comment]
I've experienced similar issues for some time. Changing `focusFollowsMouse` on or off does not seem to have an impact. The lack of keyboard support extends to not working for the keyboard commands for the app (Esc to exit or Spacebar to open panel) or even entering text. The latest AppImage seems to work, although icons are missing on the toolbar so it is not a sufficient replacement.

**Comment by mmahmoudian** [comment]
@karthikiyengar can you try the approach presented here:
https://github.com/flameshot-org/flameshot/issues/790#issuecomment-687416350

it seems in Ubuntu somehow one need to initiate the app (e.g via `flameshot &`) before running other flameshot commands (e.g  `flameshot gui`)

Please report back if this have worked for you.

**Comment by borgmanJeremy** [comment]
Closing stale issue

**Comment by karthikiyengar** [comment]
I'm sorry, I missed this message @mmahmoudian.

Sadly, this does not work. I can use the app perfectly fine using the mouse, but the keyboard does not work.

**Comment by mmahmoudian** [comment]
@karthikiyengar so even <kbd>spacebar</kbd> and <kbd>Ctrl</kbd>+<kbd>c</kbd> does not work when the Flameshot is open?

**Comment by karthikiyengar** [comment]
Neither does enter and escape, the only way to close flameshot is to draw a rectangle and press the close icon.

**Comment by mmahmoudian** [comment]
@karthikiyengar would you please provide the following
1. can yo confirm that you are using the latest version of Flameshot (v0.8.1)?
2. try [the AppImage](https://github.com/flameshot-org/flameshot/releases/download/v0.8.1/Flameshot-0.8.1-x86_64.AppImage) (basically, download the file, make it executable and run it as explained here: https://flameshot.js.org/#/data/appimage-snap-flatpak)
3. what is your keyboard layout?
4. what is your locale (try this in terminal: `localectl status`)

**Comment by karthikiyengar** [comment]
1. I was on 0.6 before, installed the AppImage
2. The shortcuts still don't work on the AppImage
3. I'm on the us layout
4. Find below:
```
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_DE.UTF-8
                  LC_TIME=de_DE.UTF-8
                  LC_MONETARY=de_DE.UTF-8
                  LC_PAPER=de_DE.UTF-8
                  LC_NAME=de_DE.UTF-8
                  LC_ADDRESS=de_DE.UTF-8
                  LC_TELEPHONE=de_DE.UTF-8
                  LC_MEASUREMENT=de_DE.UTF-8
                  LC_IDENTIFICATION=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
     X11 Options: terminate:ctrl_alt_bksp
```

**Comment by karthikiyengar** [comment]
@mmahmoudian - It works on Gnome though :-)

**Comment by mmahmoudian** [comment]
My hypothesis is that there is a global keyboard shortcut conflict with your Xmonad configuration. Can you double-check that.

**Comment by karthikiyengar** [comment]
Okay, I used a minimal xmonad config and the shortcuts seem to work fine:
```
import XMonad
import XMonad.Config.Desktop

main = xmonad desktopConfig
    { terminal    = "urxvt"
    , modMask     = mod4Mask
    }
```
I'll drop a comment if find anything weird from my config that was causing the clash

Thanks for your suggestions and contributions :-)

**Comment by karthikiyengar** [comment]
It was the fullscreenEventHook that was causing this:

https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-EwmhDesktops.html#v:fullscreenEventHook

I've disabled the hook as I don't need it anymore :-)

Thanks!

**Comment by mmahmoudian** [comment]
I'm glad it worked out. Also thanks for sharing the information and changing the title to be more descriptive. Perhaps this can help other Xmonad users. 👍🏼

**Comment by Axarva** [comment]
If anyone is still looking for a fix, I found a temporary fix.
For me, I had these same issues, but what I noticed was when `flameshot` is launched as a daemon, the first (and only first) time `flameshot gui` is run, it works correctly. The next time, it doesn't. 
For the next time you try to run it, this bug happens.

And flameshot sends a notification everytime a screenshot is taken.

You can probably see where this is going.
 
If we use the dbus interface to match any notification containing the string `flameshot` and then make it execute a particular command everytime the notification is sent, we technically can restart flameshot everytime and it would work.

Now that there's the theory, here are the scripts I use:

```bash
dbus-monitor "interface='org.freedesktop.Notifications'" | grep --line-buffered "string" | grep --line-buffered -e method -e ":" -e '""' -e urgency -e notify -v | grep --line-buffered '.*(?=string)|(?<=string).*' -oPi | grep --line-buffered -v '^\s*$' | xargs -I '{}' /bin/bash /path/to/script.sh {}
```
And in the specified `script.sh` :
```
#!/bin/bash
string=$1
match="flameshot"
if [[ $string == $match ]]; then
      killall flameshot
fi
```

I hope this helps! It certainly fixed my issue :)

**Comment by liskin** [comment]
> It was the fullscreenEventHook that was causing this:

Good catch. I filed this: https://github.com/xmonad/xmonad-contrib/issues/550 with an idea for a fix. Hopefully I'll get to it later but if anyone needs a quick fix, checking `isClient win` somewhere in the `fullscreenEventHook` should fix the issue while keeping the fullscreen hook operational.

**Comment by liskin** [comment]
Note that this isn't entirely xmonad's fault. We can apply the [workaround](https://github.com/xmonad/xmonad-contrib/issues/550) to make it less likely input is taken away from flameshot, but it's just a workaround, not a reliable fix. (Although it may be just fine in practice.)

Here's what the [ICCCM has to say about the issue](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.10):

> The user will not be able to move, resize, restack, or transfer the input focus to override-redirect windows, since the window manager is not managing them. If it is necessary for a client to receive keystrokes on an override-redirect window, **either the client must grab the keyboard, or the client must have another top-level window that is not override-redirect** and that has selected the Locally Active or Globally Active focus model. The client may set the focus to the override-redirect window when the other window receives a WM_TAKE_FOCUS message or one of the events listed in section 4.1.7 in the description of the Globally Active focus model.

**Comment by l29ah** [comment]
Still broken even with the workaround. Removing fullscreen support from xmonad fixes Escape and Spacebar handling, but not Enter on flameshot-0.10.1. Downgrading flameshot to 0.6.0 fixes Enter handling.

**Comment by l29ah** [comment]
I can bisect flameshot if you need.

**Comment by liskin** [comment]
These seem relevant:
* https://github.com/flameshot-org/flameshot/pull/1747
* https://github.com/flameshot-org/flameshot/pull/1753

**Comment by l29ah** [comment]
Thanks. Well, i use it with --raw, so it seems a very awkward change that improves nothing. Anyway i guess i can just keep it at 0.6.0 forever.

**Comment by borgmanJeremy** [comment]
Those PRs have nothing to do with this issue. Those only disable the Imgur hotkey.

**Comment by liskin** [comment]
> Those PRs have nothing to do with this issue. Those only disable the Imgur hotkey.

So, um, is Enter still supposed to do something even though it was the hotkey for Imgur and now it's not?

**Comment by borgmanJeremy** [comment]
It can still be mapped to any other function. It just is no longer the default key for upload.

**Comment by liskin** [comment]
In that case it seems this message:
https://github.com/flameshot-org/flameshot/blob/908d9187162f75f7f380af4fee6e151504ec2b61/src/widgets/capture/capturewidget.cpp#L1666
is misleading.

**Comment by borgmanJeremy** [comment]
Good point, Ill open a PR for that later. Overall we need to figure out what to do with hotkeys and --raw but there is already a seperate issue on that (hard to find on mobile)

**Comment by mmahmoudian** [comment]
@borgmanJeremy do you mean #1531? 😏
