### ISSUE TITLE
Hide region via pixelation

### ISSUE THREAD

**Issue by tecosaur** [flameshot-org/flameshot#774]
**Is your feature request related to a problem?**
Often screenshots can contain sensitive content. The current blur tool is insufficient for hiding said information. Increasing the blur helps, and is suggested in #127 as is another approach — pixelating/mosaicing.

Performing a quick search on the two approaches I find [this](https://www.researchgate.net/publication/305423573_On_the_Ineffectiveness_of_Mosaicing_and_Blurring_as_Tools_for_Document_Redaction) article describing the (lack of) effectiveness of these two methods. Of key interest are the following figures

**Gaussian Blur**
![image](https://user-images.githubusercontent.com/20903656/84690179-a525b380-af74-11ea-9e3e-4a37f175e9b9.png)
![image](https://user-images.githubusercontent.com/20903656/84690240-bb337400-af74-11ea-8693-2181e7dfe297.png)

**Mosaicing/pixelating**
![image](https://user-images.githubusercontent.com/20903656/84690339-ee760300-af74-11ea-885c-5ede00bf484e.png)
![image](https://user-images.githubusercontent.com/20903656/84690415-05b4f080-af75-11ea-8845-41cf7269eaa6.png)

Of note, is that at a given mosaic/blur size, mosaicing outperforms the gaussian blur. 

With a 40pt radius, reading from the graph about 3/4 of the blurred information can be recovered, but from the look of the mosaic graph, less than 1/4 from that approach with a square size of 40pt.

As a result of all this, I believe it would be beneficial to add a mosaic/pixelation option to Flameshot. While both techniques have issues, pixelation with large square sizes appears to be a safer way to go.

**Comment by borgmanJeremy** [comment]
Interesting, I really like this idea and will play with adding this on my fork and get a PR once its done. 

We can pick a good default pixel size, but I suspect people will need to adjust it based on the information needing to be censored. IE 100pt font will need a larger pixel size than 10pt font. I'm not sure yet the best way to integrate that option into the UI.

**Comment by tecosaur** [comment]
Glad to see there's interest :smiley: 

> We can pick a good default pixel size, but I suspect people will need to adjust it based on the information needing to be censored.

@borgmanJeremy I imagine that one could just use a user-variable size as with line thinkness, text size etc.

**Comment by borgmanJeremy** [comment]
@tecosaur Yeah I think the best way to integrate it is with the scroll wheel.

Do you have any objections to replacing the current blur tool with the pixelate tool?

**Comment by borgmanJeremy** [comment]
Something like this?
![pixelate](https://user-images.githubusercontent.com/46930769/85450640-96d02c80-b55e-11ea-9d8a-25107ec7c718.gif)

**Comment by Tc-001** [comment]
I think this could be a great change.
Maybe make it toggle-able with a checkbox (set to pixelise by default) if anyone prefers the old method

**Comment by tecosaur** [comment]
This is quite a late reply from me, but @borgmanJeremy that demo looks great!

**Comment by borgmanJeremy** [comment]
This is merged in and will be present in the next release.
