### ISSUE TITLE
flameshot not work on CentOS 8

### ISSUE THREAD

**Issue by kevinyuan** [flameshot-org/flameshot#775]
**Flameshot version**

~ > flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.11.1

**Describe the bug**

1. Start from application menu:  No thing show up
2. Start from terminal:
~ > flameshot
Qt: Session management error: Could not open network socket

**System Information**
~ > uname -a
Linux acx-sha 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

~ > cat /etc/redhat-release 
CentOS Linux release 8.1.1911 (Core)

**Comment by mmahmoudian** [comment]
@kevinyuan There is a [new stable version out](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0). Would you please confirm if the issue persists in the new version as well?
