### ISSUE TITLE
Pin and hide

### ISSUE THREAD

**Issue by unihon** [flameshot-org/flameshot#776]
Pin pic in all virtual window and activity.
Hide all pic by shorcuts.

**Comment by unihon** [comment]
Pin pic in all virtual window and activity:
KDE can set applications special setting.

**Comment by mmahmoudian** [comment]
This is something your window manager should do. in KDE this is how you can do it:

1. Pin the screenshot in Flameshot
2. From the application bar at the bottom of the screen, right click on Flameshot
3. Go to "Move to Desktop"
4. Select "All Desktops"

![image](https://user-images.githubusercontent.com/390889/92302709-e1b2eb00-ef76-11ea-8bce-94caded3747b.png)
