### ISSUE TITLE
Delete image from imgur

### ISSUE THREAD

**Issue by titoesteves** [flameshot-org/flameshot#777]
**Flameshot version**
0.6.0

**Describe the bug**
After uploading image to imgur, unable to delete the image. How can I delete the image from imgur?

**To Reproduce**
Screenshot > upload to imgur

**Expected behavior**
Option to delete image from imgur

**System Information**
Ubuntu 18.04.4 LTS

**Comment by parkerlreed** [comment]
This has been a thing since May of 2018...

https://github.com/lupoDharkael/flameshot/pull/210

![image](https://user-images.githubusercontent.com/841440/86060072-0435fe80-ba32-11ea-9fdf-9cb00f080ed1.png)

**Comment by titoesteves** [comment]
Does that mean it will not be fixed?

**Comment by parkerlreed** [comment]
What... I was saying it works. Click the delete button and it takes you to the deletion page

![image](https://user-images.githubusercontent.com/841440/87859296-16ed7600-c902-11ea-8805-1a706d349f7a.png)

**Comment by titoesteves** [comment]
@parkerlreed Thanks for the reply. I am trying to delete the image after I have exited out of that window. Is there a way to get back to that delete window so I can delete the image?

**Comment by parkerlreed** [comment]
The delete URL is unique so you would have to open that at the time and save the URL

**Comment by titoesteves** [comment]
Darn I didnt save the URL. I'm guessing the delete URL is not saved anywhere? If not, may I propose a feature request for that?

**Comment by borgmanJeremy** [comment]
I should be able to add that. Need to put some thought into the best place to display it in the UI.

**Comment by borgmanJeremy** [comment]
After some more thought I think it would be best to allow the user to use their own imgur token, then the images can be managed directly through the imgur interface.

**Comment by borgmanJeremy** [comment]
Please track this RFC for future discussion on this topic: https://github.com/flameshot-org/flameshot/pull/955

**Comment by borgmanJeremy** [comment]
There is now a history widget on master branch that allows you to view all uploaded images and the deletion token.

**Comment by titoesteves** [comment]
@borgmanJeremy How can an end user access the history widget?

**Comment by mmahmoudian** [comment]
@titoesteves right-click on the tray icon and you will see the option for it👍🏼

**Comment by titoesteves** [comment]
@mmahmoudian Thanks for the reply. I am not seeing the option when I right-click on the tray icon. Here is what I see: https://i.imgur.com/uMexss0.png

OS: MacOS Catalina
Flameshot version: 0.10.2

**Comment by mmahmoudian** [comment]
"Latest uploads" is the one

**Comment by titoesteves** [comment]
Ah nice. I was looking for history widget. I should've known. Thanks!

**Comment by meyverick** [comment]
Is this fixed? Because I added my client ID to Flameshot, restarted Flameshot but I can't delete my uploads like it wasn't uploaded by me. I'm on MacOS.

**Comment by mmahmoudian** [comment]
@meyverick 
> Is this fixed? Because I added my client ID to Flameshot, restarted Flameshot but I can't delete my uploads like it wasn't uploaded by me. I'm on MacOS.

You have got it all wrong. This has nothing to do with Flameshot. This is how Imgur behaves and it seems you have understood is wrong. Using the Client ID all you do is that your uploads will not use the quota of our Client ID. All uploads on Imgur regardless of which Client ID you use is "anonymous". It is not tied to your account. We also don't have access to anyone's upload if you upload it via our Client ID. 

![image](https://github.com/flameshot-org/flameshot/assets/390889/983eed4e-3461-4309-bfc7-5fe9fe32733c)


The only ways to delete the image are:
1. use the Flameshot menu
    ![image](https://github.com/flameshot-org/flameshot/assets/390889/06030445-2479-4ecb-a763-b6ec25427054)
2. contact Imgur to remove "anonymous" upload
