### ISSUE TITLE
Separate text thickness with painting tools thickness

### ISSUE THREAD

**Issue by denven** [flameshot-org/flameshot#782]
**Is your feature request related to a problem?**
Yes. The problem is: Once adjust the Text tool's active thickness, pait tools thickness changes as well.

**Details below:**

My OS is Ubuntu 20.04 LTS with Flameshot 0.6.0+git20191001-2(Debian)

**Current situation:**
I can adjust the text font size using the slider in side panel by changing "active thickness", but this thickness value is universal to all paiting tools like line, pen, square, circle etc. Once the font size is thicker, the painting tools brush become thicker.

**Unpleasant Experience:**
When I set a decent larger size font to type(as the default font is too small), I will get an unpleasant line or pen brush(too thicker) when switch to draw; so I have to adjust the thickness again. And in some cases I have to switch draw and text editing several times for specific editing job. So that's a little anoying.

 (btw: There is also bug here that the real thickness is not actually changed sometimes even when the slider is adjusted to a different place.)

**Feature Request:**
So I suggest that the thickness value of painting tools and text should be separated and stored independently after user changes them.

**Comment by borgmanJeremy** [comment]
The scroll wheel on your mouse will adjust the size really easily.

**Comment by mmahmoudian** [comment]
@denven after the comment @borgmanJeremy wrote, do you still think you want to have this feature request active? If not, i can close this.

**Comment by hosiet** [comment]
I believe there's a trend of expectation that the size of different tools should not be a global variable; they should be recorded separately. It is kind of a feature request and the rationale behind is valid, but such needs contradicts with the low-level design of flameshot. If we are to fix it, it will largely change user interaction experience as well as introducing nontrivial code refactoring.

I would recommend recording it as a separate feature request but there might be no guarantee of implementing it.

**Comment by mmahmoudian** [comment]
@hosiet  I also personally prefer to have them separately as I have to remember what size I chose for each tool and then resize every tool manually.

@borgmanJeremy what do you think? Shall I create a feature request based on this issue?

**Comment by borgmanJeremy** [comment]
Sure, I reopened the issue as I did not realize how popular it was to want different settings. We could potentially still use the scroll wheel for all tools, but store the thickness as a unique value for each tool rather than a shared value.

**Comment by mmahmoudian** [comment]
use the scroll wheel for changing size/thickness of all tools, but store the thickness as a unique value for each tool rather than a shared value. 🤘🏼

**Comment by pn2** [comment]
The scroll wheel is fine but it would be great to have UI alternatives. For example, the scroll wheel may not be (easily) accessible on certain notebooks (it isn't on mine), and I often use graphics tablets or pens instead of a mouse for teaching. And it took me a while to understand that "active thickness" meant font size. Why not call it like this? There are also other UI elements that appear/disappear depending on the selected tool.

**Comment by mmahmoudian** [comment]
It has been reported multiple times already that users with touch screens interfaces (generally no keyboard and mouse) cannot use Flameshot due to high dependency to keyboard shortcuts or mouse. I found these just by searching in issues:
#782 & #792

I think we should make Flameshot a bit more inclusive. For example by adding buttons + & - to the gui and/or <kbd>Ctrl<\kbd><kbd>+<\kbd> and <kbd>Ctrl<\kbd><kbd>-<\kbd>.

**Comment by denven** [comment]
> @denven after the comment @borgmanJeremy wrote, do you still think you want to have this feature request active? If not, i can close this.

Yes, I appreciate if you can implement this. I think this feature will provide more convenience.

**Comment by Martin-Eckleben** [comment]
Will implement + - button and Ctrl+ / Ctrl- this or tomorrow evening.

**Comment by Martin-Eckleben** [comment]
Started and had a successful compile but needs a little more work tomorrow evening :)

![image](https://user-images.githubusercontent.com/1571683/92801806-3a8ae500-f3b6-11ea-87d4-67a47d4851b2.png)

**Comment by thepisu** [comment]
+1 for saving size and color separated for each tool. 

See the usage of latest (great!) feature of circle counter tool: I want to draw red rectangles and arrows, but prefer to have orange circle counters, and more bigger that the arrows tickness. I would like to keep these settings, because I will use them in the same way for many screenshots.

If saving size and color for each tool seems to much, you can consider grouping settings storage for type of tools, for example:
- a setting for rectangle / line / arrow / circle
- a setting for text
- a setting for circle counter
- ...

Thank you

**Comment by Martin-Eckleben** [comment]
I forked from this issue as its main issue is separating tool sizes.
The CTRL+ & CTRL- and Buttons for tablets etc. seems a different issue to me.

I can get to separate tool sizes after I finally completed #1003 (sorry for the delay - had not much time lately).

**Comment by denven** [comment]
> I forked from this issue as its main issue is separating tool sizes.
> The CTRL+ & CTRL- and Buttons for tablets etc. seems a different issue to me.
> 
> I can get to separate tool sizes after I finally completed #1003 (sorry for the delay - had not much time lately).

Hi, Martin,

Thanks for implementing this feature. I saw there is a new release these days and I update flameshot and experience this feature again. As you are implementing this feature, I suggest the following user cases for better user experience:

1. As adjusting wheel can change the global thickness of all painting tools, adding new key bindings may not be necessary: just disable the global thickness adjusting by wheels, and let this thickness adjusting happen to the specific tool when user is using it(like when I click **T** for text editing, then wheel adjusting will change text size and save the text thickness, and when I click line tools, then wheel adjusting will change line thickness and keep the value);

2. Separating line tools and text thickness may be enough, it may not need to separate all tools' thickness, as I think when people draw lines/rectangles they may use the same thickness.

FYI

thanks.

**Comment by zw963** [comment]
This feature is still WIP,  right? is there any deadline for this feature?

**Comment by zw963** [comment]
Anyone know a alternative package for flameshot except `deepin-screenshot` on linux ?

**Comment by mmahmoudian** [comment]
@Martin-Eckleben @borgmanJeremy  any updates or eta on this? I'm also curious 😅

**Comment by borgmanJeremy** [comment]
The latest commit to master makes the text size seperate from the other thicknesses.

**Comment by zw963** [comment]
@borgmanJeremy , this will be a big improve!  can i know when this new feature can be available on arch linux ?

**Comment by mmahmoudian** [comment]
@zw963 if it is on master, you can get it from `flameshot-git` AUR.

**Comment by zw963** [comment]
@borgmanJeremy , @mmahmoudian , i tried it, but this new feature not available.

```
 ╰─ $ yay -S flameshot-git
resolving dependencies...
looking for conflicting packages...

Packages (1) flameshot-git-r1348.5213aaf2-1

```

**Comment by zw963** [comment]
Sorry for confusing, it works now, flameshot daemon need restart.
