### ISSUE TITLE
Window focus gets lost after flameshot exits

### ISSUE THREAD

**Issue by amosbird** [flameshot-org/flameshot#784]
**Flameshot version**
Flameshot v0.6.0

Compiled with Qt 5.14.1

**Describe the bug**
Window focus gets lost after flameshot exits.

**To Reproduce**
In bspwm, open any tiled window, invoke flameshot, press esc, the tiled window doesn't get the focus back.

**Expected behavior**
The tiled window regains focus.

**System Information**
Archlinux, bspwm

**Comment by borgmanJeremy** [comment]
This seems more like an issue with bspwm.

**Comment by mmahmoudian** [comment]
Can you confirm this on another window manager? Also just to be sure, what window would get the focus when Flameshot is done and does not have any window?

I'm not a bspwm user, but in dwm the master gets the focus (assuming you have set Flameshot to store the screenshot in clipboard or file). I agree with @borgmanJeremy that this is they way the window manager is behaving.

**Comment by sersorrel** [comment]
I experience something that seems like this bug, using i3wm: i3/i3#4141

**Comment by mmahmoudian** [comment]
Closed after 2 months of inactivity. Please open this if you still have the issue with the latest Flameshot version and provide the requested information.

**Comment by sersorrel** [comment]
I still have this issue on Flameshot 0.8.5 (Qt 5.9.5). Still using i3wm, version 4.19.

**Comment by LiterallyJohnny** [comment]
Yep, I am having the same issue on i3-gaps. Re referenced issue above me is the issue I filed.

**Comment by LiterallyJohnny** [comment]
Any info as to what we should do? Flameshot is literally the only program having this issue for me.

**Comment by LiterallyJohnny** [comment]
When will we have a fix @mmahmoudian? Borgman says it may be an issue with the WM, but Flameshot happens to be the only program doing this.

**Comment by mmahmoudian** [comment]
I'll try to reproduce this tomorrow with Regolith linux and will update this post.

**Comment by jfly** [comment]
@mmahmoudian please see my comment here: https://github.com/flameshot-org/flameshot/pull/731#issuecomment-719767364. That PR does feel like the right fix to me, but I just haven't had time to test out how it affects other window managers.

**Comment by mohad12211** [comment]
having the same issue with dwm, 
```
~ > flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

**Comment by marcozaccari** [comment]
I have this issue using Flameshot 0.9.0 (Qt 5.15.2), on i3wm (Arch) version 4.19.2

**Comment by sebw** [comment]
I've experienced this issue on i3wm for quite some time and I'm currently moving to bswpm and face the same issue.

In both desktop environment my way of getting the focus back is switching desktop/workspace.

**Comment by mohad12211** [comment]
this issue is still there and it wasn't fixed. it's not annoying. but I can notice it with certain apps. here's a video:

https://user-images.githubusercontent.com/51754973/133095865-d0b05764-b4ed-4a06-b19d-edf35e4106d3.mp4

this is dwm. and I also tested it on bspwm.

you can see that when my terminal is focused. the terminal cursor is white. when it's out of focus, it has a white outline only. 
also you can see that brave (tested on google chrome as well) will close the menu instantly when the browser is out of focus. I need to refocus the browser.

so if my mouse is on a window, and I exit flameshot with my mouse on the same window, this window will not get focused correctly.
I need to refocus the window. in dwm by moving the mouse and focusing other window and return to that window. or in bspwm by clicking on the window itself. or by switching workspace.

**Comment by mmahmoudian** [comment]
@borgmanJeremy should we reopen this issue?

**Comment by borgmanJeremy** [comment]
No I don't think we can really fix this from Flameshot

**Comment by mohad12211** [comment]
fair enough. actually I found a good workaround. 
```
focusedwindow=$(xdotool getactivewindow)
flameshot gui -g
if [ "$focusedwindow" == "$(xdotool getactivewindow)" ]
then
	xdotool windowactivate $focusedwindow
fi
```
this wrapper script should  work on all window managers, it will restore the focus to the original window if the focus didn't change after taking the screenshot. 
it should execute after taking the screenshot so I added the -g flag to make `flameshot gui` wait for the screenshot to be taken. I think this is the only way to make `flameshot gui` wait for the screenshot.

**Comment by mmahmoudian** [comment]
@mohad12211 This is definitely related to #1824. Checkout [my comment](https://github.com/flameshot-org/flameshot/issues/1824#issuecomment-920212860) there.

**Comment by jfly** [comment]
As a reminder, disabling `Qt::BypassWindowManagerHint` made this problem go away for me: https://github.com/flameshot-org/flameshot/pull/731#issuecomment-719767364, which is why this PR: https://github.com/flameshot-org/flameshot/pull/1300 closed this issue. Unfortunately, it did result in problems on multi-monitor setups, which caused @borgmanJeremy to revert it here: https://github.com/flameshot-org/flameshot/commit/40bad756ad4ca2af83f24b3b675049775578bbe3. We probably should have re-opened this issue after that revert.

**Comment by slococo** [comment]
> ```
> focusedwindow=$(xdotool getactivewindow)
> flameshot gui -g >/dev/null
> if [ "$focusedwindow" == "$(xdotool getactivewindow)" ]
> then
> 	xdotool windowactivate $focusedwindow
> fi
> ```

Thanks @mohad12211, but strangely it didn't work for me. I had to change windowactivate to windowfocus for it to work (using dwm). TY! It's a nice workaround.

**Comment by mohad12211** [comment]
actually yes. `windowactivate` worked for my custom dwm because of a patch I think. I changed it to `windowfocus` now and it works on my dwm. I tried the script with `windowfocus` on awesome and bspwm as well. worked on both of them after the change.

**Comment by sersorrel** [comment]
both `windowactivate` and `windowfocus` work for me on i3 4.19.2, thanks!

**Comment by mmahmoudian** [comment]
@borgmanJeremy can [this workaround](https://github.com/flameshot-org/flameshot/issues/784#issuecomment-918382722) be implemented using some QT functions? For example using `QApplication::activeWindow()` and `QWidget::setFocus()`?

**Comment by mohad12211** [comment]
btw this is the [code ](https://github.com/jordansissel/xdotool/blob/53d3d347e4be785829d1ec73c8efdebefa01133a/xdo.c#L413)for `windowfocus`. they use xsetinputfocus. which is an x11 function. I hope that it might help.

**Comment by Ddystopia** [comment]
> this issue is still there and it wasn't fixed. it's not annoying. but I can notice it with certain apps. here's a video:
> 
> this is dwm. and I also tested it on bspwm.
> 
> you can see that when my terminal is focused. the terminal cursor is white. when it's out of focus, it has a white outline only. also you can see that brave (tested on google chrome as well) will close the menu instantly when the browser is out of focus. I need to refocus the browser.
> 
> so if my mouse is on a window, and I exit flameshot with my mouse on the same window, this window will not get focused correctly. I need to refocus the window. in dwm by moving the mouse and focusing other window and return to that window. or in bspwm by clicking on other window and click back on the original window. or by switching workspace.
> 
> I understand that the issue is very low priority because you can just refocus the window and it only happens with standalone window managers so it only affects a small users. but maybe someone can figure out what's wrong someday and fix it.

It's exactly the same for me.
```bash
> flameshot --version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
> dwm -v
dwm-6.4```

**Comment by abobov** [comment]
I will leave my comment here as I faced the same issue with Xfce 4.16 (or 4.18) and Flameshot v12.1.0. FYI

**Comment by saygo-png** [comment]
Happens with awesome, even worse, making it so windows lose opacity when they are unfocused with picom makes it so even after gaining focus on a window, the opacity stays dimmed until you switch tags.
The script mentioned here fixes the issue, i cleaned it up a bit and changed windowactivate to windowfocus as that works for me. Recommend running this via the dash shell (point /bin/sh to dash) to make the delay after taking the screenshot and regaining focus smaller.
```#!/bin/sh
focusedwindow_before=$(xdotool getactivewindow)
flameshot gui
[ "$focusedwindow_before" = "$(xdotool getactivewindow)" ] && xdotool windowfocus $focusedwindow_before```

**Comment by adiosocelote** [comment]
Also happens to me in dwm. `flameshot --version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
`
Not doing anything special - just using `flameshot gui`

I should also add that this does not happen with all windows. It made me believe it's an issue with dwm (not the original Suckless one, my own fork), but apparently it's Flameshot. In my case, it's not a big deal, I just switch focus and I'm done.

**Comment by J-K-Tech** [comment]
same problem here, v12.1.0 and qt 5.15.14, dwm and arch.

its A SIMPLE BUG that MANY FOUND MANY OTHER FIXES and idk how the devs just are incapable of fixing this for more than 4 years.

stop blaming the window managers and go to work, only flameshot behaves like that all because WMs dont have tray icon things.

honestly thats a so basic error that just now i faced and im not even frustrated with the error bit with the fact it is going on for 4 years and yall blame on others for ur own mistake.

what abt just detect the window manager at start and add a basic if statement on wether is a WM or a DE?

**Comment by dimitur2204** [comment]
Hey, I am having the same issue on an:
MacBook Pro 16" 2021, Apple M1 Pro, macOS Sequoia 15.1.1
Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5

 I'm not sure 100% what @amosbird meant by "when Flameshot exits", but I am assuming it is the same as my case. Where after I click Cmd+C to copy and Flameshot stops my current window does not get refocused. This never happened when I was using Lightshot before. I am using Rectangle for a windows manager, I don't know if that has anything to do with it.

**Comment by AllergicMushroom** [comment]
The bug is still there with Flameshot v13.0.1 (Qt 6.9.1) and i3 4.24. I'd like for this to be fixed instead of having non-robust workarounds that add dependencies.
