### ISSUE TITLE
Clicking the taskbar button shows menu instead of taking screenshot

### ISSUE THREAD

**Issue by tawmoto** [flameshot-org/flameshot#786]
Version 0.5.1-1
I am using Xubuntu 18.04 and when I click the taskbar button to take a screenshot, I get a menu instead.
Thanks

![Peek 2020-07-05 13-45](https://user-images.githubusercontent.com/35702340/86530944-d3d4e100-bec5-11ea-881d-eef7209b5aa4.gif)

**Comment by borgmanJeremy** [comment]
This is resolved in a newer release of flameshot. I don't think the fix is backported to Xubuntu 18.04, but if you build flameshot from source it will work fine (I tested with ubuntu package manager to confirm your issues, then built from source and it works fine)

![Peek 2020-07-07 14-37](https://user-images.githubusercontent.com/46930769/86833731-8ab89480-c05f-11ea-8432-26487158babc.gif)

**Comment by tawmoto** [comment]
> This is resolved in a newer release of flameshot. I don't think the fix is backported to Xubuntu 18.04, but if you build flameshot from source it will work fine (I tested with ubuntu package manager to confirm your issues, then built from source and it works fine)
> 
> ![Peek 2020-07-07 14-37](https://user-images.githubusercontent.com/46930769/86833731-8ab89480-c05f-11ea-8432-26487158babc.gif)

thank you very much, i will try it

**Comment by mmahmoudian** [comment]
@tawmoto please report back if the issue still persists after building from source, and if it is fixed, please close this issue.

**Comment by mmahmoudian** [comment]
@tawmoto  There is a [new stable version out](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0). Would you please confirm if the issue persists in the new version as well?

**Comment by tawmoto** [comment]
> @tawmoto There is a [new stable version out](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0). Would you please confirm if the issue persists in the new version as well?

Great, is there a snap or .deb somewhere or should I compile from sources? Thanks

**Comment by mmahmoudian** [comment]
@tawmoto  There are 26 assets in that release including :
- [flameshot_0.8.0-1_amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_0.8.0-1_amd64.deb)
- [flameshot_ubuntu_0.8.0-1_amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_ubuntu_0.8.0-1_amd64.deb)
- [Flameshot-0.8.0-x86_64.AppImage](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/Flameshot-0.8.0-x86_64.AppImage)
- [flameshot_v0.8.0.rc1+git14.017578e_amd64.snap](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_v0.8.0.rc1+git14.017578e_amd64.snap)
- [ org.flameshot.flameshot_0.8.0_x86_64.flatpak](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/org.flameshot.flameshot_0.8.0_x86_64.flatpak)

**Comment by tawmoto** [comment]
> @tawmoto There are 26 assets in [that release](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0) including :
> 
> * [flameshot_0.8.0-1_amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_0.8.0-1_amd64.deb)
> * [flameshot_ubuntu_0.8.0-1_amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_ubuntu_0.8.0-1_amd64.deb)
> * [Flameshot-0.8.0-x86_64.AppImage](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/Flameshot-0.8.0-x86_64.AppImage)
> * [flameshot_v0.8.0.rc1+git14.017578e_amd64.snap](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/flameshot_v0.8.0.rc1+git14.017578e_amd64.snap)
> * [ org.flameshot.flameshot_0.8.0_x86_64.flatpak](https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/org.flameshot.flameshot_0.8.0_x86_64.flatpak)

Thanks, sorry I did not check myself, I am in vacation with poor internet.

**Comment by tawmoto** [comment]
Unfortunately I cannot install the .deb because unmet dependencies (I have the latest updates on Ubuntu 18.04)
```
flameshot depends on libqt5widgets5 (>= 5.11.0~rc1); however:
  Version of libqt5widgets5:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.
```

Also I get error on snap packages, maybe I am doing smth wrong? 
```
sudo snap install "flameshot_v0.8.0.rc1+git14.017578e_amd64.snap"
error: cannot find signatures with metadata for snap
       "flameshot_v0.8.0.rc1+git14.017578e_amd64.snap"
```

Thanks

**Comment by mmahmoudian** [comment]
@tawmoto The new flameshot is not in snap store yet (try `snap search flameshot` and you'll see) and that's why the snap instal fails.
About the .deb issue, perhaps @ZetaoYang can comment here as he knows the situation better.


But for now, you can always use the AppImage as it is distro agnostic:

1. Naviaget to the folder you would like to store the software (the following is my setup
```sh
mkdir -p ~/Applications/Flameshot
cd ~/Applications/Flameshot
```

2. Download the latest AppImage
2.1. Get it from [Release](https://github.com/flameshotapp/packages/releases) page:
https://github.com/flameshot-org/flameshot/releases/download/v0.8.0/Flameshot-0.8.0-x86_64.AppImage
OR
2.2. use the following to automatically download the latest.
 ```sh
curl -O -J -L $(curl -s https://api.github.com/repos/flameshot-org/flameshot/releases/latest \
                | grep -Po 'https://github.com/flameshot-org/flameshot/releases/download/[^}]*\.AppImage' \
                | uniq)
```
  
3. Delete older versions of Flameshot AppImage
  
4. Set it to executable:
```sh
chmod +x Flameshot-*-x86_64.AppImage
```
  
5. Run the software:
```sh
./Flameshot-*-x86_64.AppImage
```

**Comment by hosiet** [comment]
@ZetaoYang It is obvious that the ubuntu `.deb` package provided in the release page was not built against Qt5 5.9 as provided by Ubuntu 18.04 so it cannot be installed on Ubuntu 18.04 since it requires a higher Qt5 version. I consider it a bug and will open another issue for it.

**Comment by ZetaoYang** [comment]
In github actions CI/CD, the default cmake version of the distribution is used without installing cmake from other sources. The version of cmake in ubuntu 18.04 is smaller than 3.13.

**Comment by hosiet** [comment]
@ZetaoYang this issue has nothing to do with cmake.

**Comment by tawmoto** [comment]
> @ZetaoYang this issue has nothing to do with cmake.

I agree, cmake has nothing to do with this, it's a Qt problem.

**Comment by borgmanJeremy** [comment]
I think this is okay to close now? There were many issues raised but I think they are all resolved.

**Comment by tawmoto** [comment]
> I think this is okay to close now? There were many issues raised but I think they are all resolved.

Yes sure 👍
