### ISSUE TITLE
App not working Kubuntu 20.04

### ISSUE THREAD

**Issue by yildirimsertbas** [flameshot-org/flameshot#788]
app is not running.
Kubuntu 20.04
KDE Plasma 5.18.5
Kernel: 5.4.0-40-generic

**Comment by borgmanJeremy** [comment]
Try building the latest version from this repo.

**Comment by mmahmoudian** [comment]
It is almost two weeks that we haven't heard from @yildirimsertbas , therefore, I close this issue for now. comment if the issue is still there with the latest version in apt.
