### ISSUE TITLE
CLI for 0.6.0 not working

### ISSUE THREAD

**Issue by Cloud-Mak** [flameshot-org/flameshot#790]
Hello,

In repo, I could only find 0.5.1 package. When I install it and try to use CLI with arguments lile **flameshot gui** it works. Thats how I created keyboard shortcut to lauch flameshot.

I wanted to use the text feature which is only avaialbe in latest 0.6.1. I insatalled it using the .deb file (for bionic) from github releases.

```
makrand@mint-gl63:~/bin$ apt policy flameshot 
flameshot:
  Installed: 0.6.0-1
  Candidate: 0.6.0-1
  Version table:
 *** 0.6.0-1 100
        100 /var/lib/dpkg/status
     0.5.1-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

But with this the CLI with arguments stopped working. None of the cli arguments (gui, screen, full or config) are working. After I enter command with argument, absolutely nothing happens.

```
makrand@mint-gl63:~/bin$ flameshot gui
makrand@mint-gl63:~/bin$ flameshot config 
```

Any idea what might be issue?

**System Information**
OS: Linux Mint 19.3 Tricia x86_64 (Based on Ubuntu 18.04 bionic)

**Comment by Cloud-Mak** [comment]
Hello,

I was wondering if Dev can comment. It's only CLI options are failing with 0.6.0. Had there been issue with OS/else, it would have failed for 0.5.x as well

**Comment by mmahmoudian** [comment]
@Cloud-Mak do you have the flameshot open? I tested on my Ubuntu 18.04 and managed to run those commands when flameshot is running:

```
flameshot &
flameshot gui
```

**Comment by Cloud-Mak** [comment]
@mmahmoudian 
Here is how I am launcing and using flameshot 0.5. Check below screenshot
http://i.imgur.com/HYZAzBN.png

even if flameshot is not running, the shortcurt CTRL+print starts it and I can start using it. This is what I wanted to do with 0.6
But its not allowing.

**Comment by mmahmoudian** [comment]
How about you use this instead:

```
( flameshot & ) && flameshot gui
```

I know this is not a permanent fix, but it is a quick one. Let me know if it works.

**Comment by borgmanJeremy** [comment]
Can you retest on a newer release? We are published in the snap store if you want an easy method to install.
