### ISSUE TITLE
README missing libqt5svg5-dev

### ISSUE THREAD

**Issue by donpdonp** [flameshot-org/flameshot#791]
Ubuntu 20.04:
after following the readme build instructions, qmake fails with:
Project ERROR: Unknown module(s) in QT: svg

the readme should include in the list of pre-reqs to install `libqt5svg5-dev`

**Comment by ZetaoYang** [comment]
The readme already includes `libqt5svg5-dev`, please see https://github.com/flameshot-org/flameshot/blob/master/README.md#debian.
