### ISSUE TITLE
changing brush size in the UI

### ISSUE THREAD

**Issue by soundsbeard** [flameshot-org/flameshot#792]
im using graphical tablet almost all the time, and if i need to change size of the arrow, pencil or whatever i need to grab a mouse to use a scroll wheel.
please, add size changing to UI.
and thank you for a great tool!

**Comment by mmahmoudian** [comment]
@soundsbeard There has been improvements regarding this issue. Considering that you have the appropriate hardware, would you please test this:
https://github.com/flameshot-org/flameshot/issues/1003#issuecomment-700240081

**Comment by soundsbeard** [comment]
@mmahmoudian 
thank you for the reply.
i can confirm, that both gestures and tablet scroll circle work for changing size.
but its not an option for me.
im a 3d artist, and as i said previously, i use tablet all the time, and my workflow means using keyboard shortcuts all the time, so all my touch functions for the tablet are disabled bc i keep tapping somewhere by accident. so it would be great to have ui thingy for changing size. but i know that i might ask too much.
anyway, flameshot is the best screenshot tool already, thank you and your team for the hard work.

**Comment by mmahmoudian** [comment]
@Martin-Eckleben Seems your code works. Perhaps we should also add an option in the "interface" tab of the configuration window to add + and - buttons (disabled by default imho). What do you think?

**Comment by borgmanJeremy** [comment]
@mmahmoudian  @Martin-Eckleben  I think this is a good idea. Let's turn off by default but get it added in.

I had not considered the case where gestures are turned off.
