### ISSUE TITLE
Flameshot isn't showing after certain modal dialog but working (?)

### ISSUE THREAD

**Issue by Meister1593** [flameshot-org/flameshot#795]
**Flameshot version**
0.6.0-4

**Describe the bug**
Flameshot not showing sometimes when i focus on specific elements inside browser (possibly not only browser)
With that, i can see flameshot cursor, i can move selected (presumably) box, but i can't see anything related to flameshot (like, grayed screen, controls, and etc.
[Video showing this issue](https://drive.google.com/file/d/1JC1C0z51Az0o2x32-aXt9OnaweTVCsgF/view?usp=drivesdk)
Modal dialog *code* 
![image](https://user-images.githubusercontent.com/7141787/89704592-1aef3f80-d966-11ea-91c0-1153130d2cc7.png)

**To Reproduce**
Not entirely sure how, because i get consistent results with one thing for me: Group chat viewer modal dialog on vk.com

**Expected behavior**
To work properly? Details in describing the bug.

**System Information**
Browser: vivaldi-snapshot 3.2.1964.3-1
Arch KDE , Linux 5.7.12-arch1-1, XFX RX 480 4GB amdgpu driver
![image](https://user-images.githubusercontent.com/7141787/89703508-7caaac00-d95c-11ea-8582-6faac0fabc54.png)

**Comment by borgmanJeremy** [comment]
Can you try it using the flameshot-git package from the AUR? There are many commits ahead of the latest release in the standard arch repos.

**Comment by Meister1593** [comment]
> Can you try it using the flameshot-git package from the AUR? There are many commits ahead of the latest release in the standard arch repos.

It seems that either AUR package is broken or latest git version isn't building... [Log](https://gist.github.com/Meister1593/16a45a7b3139fee9c70d4cb460106514)

**Comment by mmahmoudian** [comment]
@Meister1593 do you use two or more monitors with different resolutions and even possibly connected to two different graphic cards? to me it seems that in the video you shared, it seems that you hit the printscreen button when your mouse is on another monitor and then you come back to the monitor you are recording from and start click+drag.

**Comment by Meister1593** [comment]
> @Meister1593 do you use two or more monitors with different resolutions and even possibly connected to two different graphic cards? to me it seems that in the video you shared, it seems that you hit the printscreen button when your mouse is on another monitor and then you come back to the monitor you are recording from and start click+drag.

Not sure what happened, but right now flameshot is working fine. Haven't seen such issue in like a 2-3 weeks. 
Yes, i do have multiple monitors, but with same resolution and on one GPU.
I feel like this was Chromium issue (i used Vivaldi atm), because right now my Chromium is older, `chromium 84.0.4147.135-1` (i don't upgrade because of bug in 85 release with clipboard)

**Comment by mmahmoudian** [comment]
Having nondeterministic bug behavior makes is really hard to track down the issue and fix it.
Would it possible for you to do whet I suggested (quoted below) and see if you can reproduce the bug. Also if you suspect the issue is related to Chromium, run it once with chromium and once without to test the hypothesis.

> hit the printscreen button when your mouse is on another monitor and then come back to the monitor you are recording from and start click+drag.

**Comment by Meister1593** [comment]
> Having nondeterministic bug behavior makes is really hard to track down the issue and fix it.
> Would it possible for you to do whet I suggested (quoted below) and see if you can reproduce the bug. Also if you suspect the issue is related to Chromium, run it once with chromium and once without to test the hypothesis.
> 
> > hit the printscreen button when your mouse is on another monitor and then come back to the monitor you are recording from and start click+drag.

I couldn't reproduce issue again, not even in Vivaldi. I also remember that this was issue also for Discord, but i can't reproduce it again with it.
Seems like chromium either fixed it, or something was broken->fixed in Arch with updates.

**Comment by mmahmoudian** [comment]
Thank you for trying it. Feel free to open this issue if you face it again.
