### ISSUE TITLE
Collaboration proposal from Namecheap, Inc

### ISSUE THREAD

**Issue by thepurple** [flameshot-org/flameshot#798]
**Hi Dharkael.**

My name is Yuriy Puchkov and I'm an R&D engineer at **Namecheap**.
Our customer support departure needs a cross-platform screenshot tool and a crucial requirement is to save screenshots to our own storage to be sure that sensitive information is stored securely.
After some research we have found this project which is a really good fit for us and has very most of features we need.

We forked it and developed number of missing features for our CS team and now **Namecheap** wants to push them to the upstream repo so everyone in the community can benefit from them.

Here is the list of the main improvements:
- Upload to custom storage. We plan to make it as plugins and make it configurable (imgur, s3, etc)
- Latest upload history with ability to remove items from history (including remote storage)
- Create Windows installation (not just archived binaries) based on Inno Setup
- Get OpenSSL binaries for Windows from the trusted source
- Proxy support for uploading screenshots
- Some translation updates by native speakers (Ukrainian & Russian languages).
- Make blur effect stronger as now it may cause leakage of the sensitive info in certain cases
- Make some keyboard shortcuts configurable
- Number of small bug-fixes

Before doing a big job I'd like to get an approval from your side and discuss organizational and possibly some technical aspects.
I see that you have a big number of pull-requests and some of them are older than a year. I understand that it's a time consuming task to review all of them.
Can you give us some details how can we deliver our features ASAP? From our side we'll do all what we can.

Thank your cool job and I hope that together we'll bring quite a few of new useful features to the community.

Regards,
Yuriy Puchkov
R&D Engineer at Namecheap.

**Comment by LeBaux** [comment]
It's always great to see a big company adopting open source and giving back upstream. Please read/skim #789, the development of FlameShot is being rekindled under a new organization. The process might take a while, but I think your additions and improvements benefit everyone upstream.

**Comment by alerque** [comment]
The PR #1030 seems to be directly related to this.
