### ISSUE TITLE
Capture single window

### ISSUE THREAD

**Issue by Massimo-B** [flameshot-org/flameshot#799]
flameshot is a good replacement for xfce-extra/xfce4-screenshooter as I was looking for a tool capturing single screens.
But there is no possibility to capture single sindows, which is a standard function of screen shooters.

Please add a 'flameshot window' command,, with an option for decoration or not.

**Comment by Massimo-B** [comment]
And for https://flameshot.js.org/#/key-bindings it would be very helpful to describe the exact commands that I need to configure for instance on Xfce.

**Comment by Martin-Eckleben** [comment]
Thank you for your input!

Regarding the documentation:
please only one issue per... issue :)
Agree with you though - that should and surely will be improved.

**Comment by mmahmoudian** [comment]
This is related to #5, #334 and #395. @Martin-Eckleben and @Massimo-B should this be marked as duplicated or it is different concept?

**Comment by FichteFoll** [comment]
I believe this is a duplicate of #5. The other two issues are about the active window, while it appears this request is about slecting a window as the area to shot.
