### ISSUE TITLE
Flameshot stops working after saving an image.

### ISSUE THREAD

**Issue by eancuta** [flameshot-org/flameshot#801]
**Flameshot version**
v0.6.0

**Describe the bug**
Flameshot will no longer trigger the selectable overlay when clicking on "Take Screenshot"

**To Reproduce**
1. Have a browser open (Firefox in my case)
2. Launch Flameshot
3. Click "Take Screenshot"
4. Select any screen section, then select text feature and write something (might need to enable text first)
5. Click on save image without exiting text box
6. Save image
7. Switch between multiple tabs in Firefox (perhaps relevant?)
8. After about half a minute right click on Flameshot and click "Take Screenshot"
9. Should not work

**Expected behavior**
For step 9 above, should not work should become should work.

**System Information**
Fedora 32 5.7.14-200.fc32.x86_64, KDE Plasma 5.18.5
KDE Frameworks 5.70.0
Qt 5.14.2
OS Type 64-bit

**Comment by luiq54** [comment]
I can confirm the above. When I run the app from KDE launcher (I also have it autostart at the start of the session) and try to save an image, it crashes instantly. Launching from terminal has no issues what so ever.

System: Arch Linux with KDE 5.19.4
Flameshot 0.6.0 (Compiled with Qt 5.14.1)
KDE Frameworks Version 5.73.0
Qt Version 5.15.0

**Comment by Martin-Eckleben** [comment]
Can't reproduce on

Manjaro 20.0
Xfce 4.14
Flameshot 0.6.0

Do you use Wayland or X.Org?
There seem to be issues with Wayland for other users.

**Comment by eancuta** [comment]
I think I'm using xorg. Is there a way I can check so I can let you know for certain?

**Comment by borgmanJeremy** [comment]
@luiq54 Can you test using flameshot-git from the AUR? Or build from source? I am not able to replicate it on my arch install.

**Comment by mmahmoudian** [comment]
@eancuta the version 0.8 is now realease (and I believe the AUR updated accordingly). Please try the new version and report back if the issue persists in 0.8 as well.

**Comment by eancuta** [comment]
@mmahmoudian thanks I'll give that a go. Would it be possible to get an update via fedora dnf? I tried using dnf but flameshot stays at v0.6.0

**Comment by mmahmoudian** [comment]
@eancuta The idea is to have the 0.8 in as many distros as possible, but that would take some time as the 0.8 was released less than 48 hours ago. You can always check the version status of Flameshot in the following link for majority of distros:
https://repology.org/project/flameshot/versions

For the timebeing and to enjoy the latest Flameshot, try the AppImage as explained here: https://github.com/flameshot-org/flameshot/issues/786#issuecomment-695994200

**Comment by eancuta** [comment]
@mmahmoudian I can confirm the issue is now no longer appearing on version 0.8.0
