### ISSUE TITLE
I need map shortcuts

### ISSUE THREAD

**Issue by vinsongnow** [flameshot-org/flameshot#802]
It’s close to perfection, and it lacks a texture shortcut or texture command, which can improve my work efficiency

**Comment by Martin-Eckleben** [comment]
Hey @pi-c,

what do you mean by "map shortcuts"?
You probably mean a configuration screen to configure which keyboard key does which action?

Please post only one feature per issue.
Consider creating new issues for "texture shortcut" and "texture command" but please leave us new maintainers some time to catch up with bugs and PRs before new features :)

**Comment by mmahmoudian** [comment]
@Martin-Eckleben @borgmanJeremy I'm having trouble understanding what is the requested feature. Do you have any solid idea what it is? Otherwise it should be considered as "stale" as it is over a month that we have asked for clarification and he/she have not responded.
