### ISSUE TITLE
Tray icon not changing with different packs

### ISSUE THREAD

**Issue by amithiel** [flameshot-org/flameshot#803]
**Flameshot version**
0.6.0

**Describe the bug**
The tray icon remains the default colorful icon, although i apply different packs which contain the "monochrome icon". 
In the packs, the name of the file is: flameshot-tray.svg

**To Reproduce**
install papirus icon pack, or Korla. apply, refresh cache. start flameshot, the icon is the same everytime.

**Expected behavior**
it should change to the monochromatic version

**System Information**
Linuxmint 20 - Cinnamon edition

**Comment by ZetaoYang** [comment]
@amithiel You can try install hicolor-icon-theme `sudo apt install hicolor-icon-theme`, it's the default fallback theme used by implementations of the Freedesktop.org Icon Theme specification.

**Comment by amithiel** [comment]
Hi,
thanks for the suggestion. In the mean time, i just made a fresh POP!_OS 20.04 install, and i found a different bug.
The monochromatic icon works fine, BUT, if i check the option to open flameshot on startup, after rebooting it reverts to the regular tray icon. 

Then if you close and reopen, the monochromatic version appears again. Can anyone confirm this?

**Comment by borgmanJeremy** [comment]
I have not seen this bug and I don;t think it would be related to flameshot specifically since we follow a standard for icons.

**Comment by mmahmoudian** [comment]
@amithiel would you please check if the issue is still there with version 0.9.0?

**Comment by amithiel** [comment]
> @amithiel would you please check if the issue is still there with version 0.9.0?

It's working! (currently on Manjaro).
