### ISSUE TITLE
Imgur save window never appears in the screen center

### ISSUE THREAD

**Issue by heit0r** [flameshot-org/flameshot#806]
![Captura de tela_2020-08-26_01-11-20](https://user-images.githubusercontent.com/38054654/91254661-55642500-e739-11ea-8678-a19215f4f71b.png)

The 'upload to imgur' window never appears in the center of the screen, so I have to drag it up. Is there a way to make it appear on the center or top of screen? Would be awesome to make it just upload to imgur and copy the link to clipboard without buttons or a window.

Thank you so much.

**Comment by Martin-Eckleben** [comment]
Hey @heit0r :)
Thank you for your report!

"Without buttons or window" should be a separate issue and would probably need a decision first.
You can open one for it but please consider leaving us new maintainers some time to catch up first before making controversial decisions for new "features" :)

But window not centered is a probably a bug and should be analyzed in this issue.
Will soon label it.

**Comment by borgmanJeremy** [comment]
I was able to replicate this.

**Comment by heit0r** [comment]
Thank you @Martin-Eckleben !
