### ISSUE TITLE
Support enter key on numpad for submitting selection

### ISSUE THREAD

**Issue by FichteFoll** [flameshot-org/flameshot#808]
When making a selection (in raw mode `flameshot gui -r`), the return key can be used to submit the selection, but the enter key on the numpad does not work. Please add a binding for the enter key.

**Comment by FichteFoll** [comment]
Thanks for the notice. I haven't tried whether this works nowadays but I can in fact use my keypad enter already on 0.10.1 (on Arch). I can also try with `master` if you'd like me to.

Note however that I did set "enter" as the binding for "copy to selection". This may or may not affect this issue.

**Comment by veracioux** [comment]
@FichteFoll Thanks for confirming. No need to test master, as the change I made is only a small one.

> Note however that I did set "enter" as the binding for "copy to selection". This may or may not affect this issue.

Shouldn't be relevant.
