### ISSUE TITLE
Pin image on the Desktop issue

### ISSUE THREAD

**Issue by Djavano** [flameshot-org/flameshot#809]
**Flameshot version**
v0.6.0

**Describe the bug**
If i press pin after creating the screenshot, the pin is fixed to the left of my main monitor and cannot be dragged.

**To Reproduce**
flameshot gui and select "Pin image on the desktop"

**System Information**
Fedora 32 - 3.36.5

**Comment by Martin-Eckleben** [comment]
Can't confirm on Manjaro 20.0
Seems to be Fedora related?

**Comment by Djavano** [comment]
I disabled wayland and now works properly

**Comment by AlwaysBeCalm** [comment]
when I click on pin image, the app crashes, and here's the error on terminal...

`qt5ct: using qt5ct plugin`
`qt5ct: D-Bus system tray: yes`
`qt5ct: custom style sheet is disabled`
`QPainter::begin: Paint device returned engine == 0, type: 2`
`QPainter::setRenderHint: Painter must be active to set rendering hints`
`QPainter::setCompositionMode: Painter not active`
`QPainter::translate: Painter not active`
`QPainter::setPen: Painter not active`
`QPainter::setBrush: Painter not active`
`QPainter::setBrush: Painter not active`

I'm runnig Mint 20.04 Cinnamon

**Comment by borgmanJeremy** [comment]
@AlwaysBeCalm Could you please try version 0.8 that was just released?

**Comment by AlwaysBeCalm** [comment]
@borgmanJeremy 

thanks a lot :rose: :rose: 
the new release is amazing, I liked the counter tool, I really need it :+1: 

I noticed it's because of this option in the setting
![image](https://user-images.githubusercontent.com/54927528/93694996-d1744180-fb1a-11ea-9530-ca1a44794570.png)
