### ISSUE TITLE
FR: Allow input methods (fcitx, ibus) when typing into text area

### ISSUE THREAD

**Issue by amosbird** [flameshot-org/flameshot#811]
Currently the text area cannot have IME activated, which limits its usage.

**Comment by amosbird** [comment]
It now works in v11.0.0.

**Comment by s5unty** [comment]
If it is fcitx5, you need to make sure [fcitx5-qt](https://github.com/fcitx/fcitx5-qt) is installed.
In ubuntu22.04, the corresponding one is `fcitx5-frontend-qt5`.
