### ISSUE TITLE
Hot key to commit text and image in one shot

### ISSUE THREAD

**Issue by amosbird** [flameshot-org/flameshot#812]
When typing in a text area, `<enter>` key doesn't commit but inserts a new line. I have to left-click on the image to first commit the text area, then press `<enter>` to commit the image. It would be more convenient to have a hotkey say `shift-<enter>` to insert newlines while keep `<enter>` key as the commit key.

**Comment by Martin-Eckleben** [comment]
Hi @amosbird,

thank you very much for your proposal and participation.
Right now we have a lot to catch up to. Please don't be upset that it will take a while until we get to discuss it but it will happen eventually :)

Personally I'm undecided.
I hate ```alt-<enter>``` in most spreadsheet editors. It confuses most non computer people and I really often see them not doing any newlines which often hurts the readability.
But there are prominent examples which do it i.e. Whatsapp comes to my mind first.

It needs discussion.

**Comment by amosbird** [comment]
Many IM applications uses shift-enter to insert newlines while sending messages by enter. for instance, telegram, discord, gitter, slack, etc.
