### ISSUE TITLE
can we have a RGB colour indicator?

### ISSUE THREAD

**Issue by wotmshuaisi** [flameshot-org/flameshot#813]
a RGB colour indicator can display colour information on current mouse cursor coordinate.

this is very helpful to developer.

![image](https://user-images.githubusercontent.com/16408269/92108242-f52b4e00-edde-11ea-978e-18826a2dccf5.png)

**Comment by Martin-Eckleben** [comment]
I personally would vote for it but right now we have a lot of Bugfixes to catch up first :)
Please don't be upset that it will probably take a while to get to this and thank you for your participation.

**Comment by wotmshuaisi** [comment]
Thanks a lot, it's not urgent request to me, I'm just suggesting it. a vote would a great idea.

**Comment by mmahmoudian** [comment]
@wotmshuaisi i believe what @veracioux implemented would do what you are looking for. It is not in a released version yet, and (assuming you are a Windows user based on the picture you shared) you should compile it yourself or wait for the new release (> v0.10.1)

**Comment by borgmanJeremy** [comment]
Closing this after the work @veracioux  did.

**Comment by wotmshuaisi** [comment]
> Does the color grabber coupled with the recently added hex code text box in the side panel satisfy this feature request?

It does help in most cases, except when the area you want to grab colour is covered by side panel.

**Comment by mmahmoudian** [comment]
@wotmshuaisi but the sidepanel closes when the color grabber is selected and re-opens when the color is selected by the user or cancel by Esc
