### ISSUE TITLE
org.dharkael.Flameshot.service hardcodes binary file PATH

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#816]
**Flameshot version**
git HEAD

**Describe the bug**
https://github.com/flameshot-org/flameshot/blob/master/data/dbus/package/org.dharkael.Flameshot.service#L3

```
[D-BUS Service]
Name=org.dharkael.Flameshot
Exec=/usr/bin/flameshot
```

This file hardcodes the PATH to flameshot binary. When `$prefix` is not `/usr/`, this dbus service file will not work since it cannot find the proper flameshot binary.

I guess CMake should be responsible for the path manipulation and populate a correct `.service` file at build time using the correct `PREFIX` value.

**Comment by hosiet** [comment]
I just noticed that there is a `data/dbus/other-path/service-gen.sh` file handling this issue. This solution does not look so elegant though.

I believe CMake will have to handle this problem anyway when dealing with #815 .

**Comment by borgmanJeremy** [comment]
Hrmmm. Okay, I can fix this in another PR. I know it can be done in cmake but don't know offhand how to have it modify the file. I like the idea.
