### ISSUE TITLE
Debian packaging...

### ISSUE THREAD

**Issue by Creteil** [flameshot-org/flameshot#817]
Why does since the fork the directory « debian » removed from the repository ?

Regards.

**Comment by hosiet** [comment]
I believe the `debian/` dir has been moved under the `data` directory. After #814 gets merged, you may move this directory back to top dir and do a packaging as usual.

**Comment by Creteil** [comment]
@hosiet thanks for the hint, I check the build and report...

**Comment by borgmanJeremy** [comment]
I moved it in the data directory because we also have rpm, flatpak and will add snaps and I did not want to clutter the root directory. If it is confusing or non-standard I can move it back to the root directory. I'm totally open to feedback and discussion on this.

**Comment by Creteil** [comment]
debian build broken :

http://paste.debian.net/1162688/

**Comment by borgmanJeremy** [comment]
Opened #818 to fix all the packages and add to CI.

**Comment by borgmanJeremy** [comment]
#851 fixes debian and RPM packages. I will leave #818 open for universal packages.
