### ISSUE TITLE
Could not find SHOpenWithDialog under Windows 10 using mingw64(TGM-GCC)

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#824]
After flameshot building mechanism refactoring, I try run new code under Windows 10 using JetBrains Clion with mingw64(TDM-GCC 9.2.0). found in the file `src/tools/launcher/openwithprogram.cpp`, an error appears: `error: 'SHOpenWithDialog' was not declared in this scope`, as shown in the screenshot, 
![image](https://user-images.githubusercontent.com/10769951/92306566-a50ce100-efc2-11ea-90ce-a7f788409be6.png)

In this header file `shlobj.h` line 2113 need `NTDDI_VERSION >= 0x06000000`, 
 
![image](https://user-images.githubusercontent.com/10769951/92306671-865b1a00-efc3-11ea-81b8-d87209addddf.png)

that means SHOpenWithDialog requires Windows Vista or higher, see https://docs.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers, mentioned in the document,
> If you define NTDDI_VERSION, you must also define _WIN32_WINNT.

This `windows.h` header file introduces these two headers `_mingw.h` and `sdkddkver.h`. In `_mingw.h` it define _WIN32_WINNT as 0x502 (namely Windows Server 2003), from line 233,   
![image](https://user-images.githubusercontent.com/10769951/92306825-b0610c00-efc4-11ea-8532-ec4aa8eb4f30.png)

In `sdkddkver.h`, it will choose NTDDI Version via _WIN32_WINNT, from line 164,
![image](https://user-images.githubusercontent.com/10769951/92306855-edc59980-efc4-11ea-90a0-d0f97cb5e732.png)

My workaroud is add below code after line `#include <windows.h>`:
```
#ifdef _WIN32_WINNT
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_VISTA
#endif
```
![image](https://user-images.githubusercontent.com/10769951/92306872-0e8def00-efc5-11ea-90e1-670fbbca8aec.png)

Or
remove `#include <windows.h>`, and add below code before `#include <Shlobj.h>`,
```
#define NTDDI_VERSION 0x06000000
#define _WIN32_WINNT 0x0600
```

**Comment by hosiet** [comment]
I just tried to build using a slightly different toolchain and the build was successful:

* System: Windows 10 v19041
* Mingw-w64 provided by MSYS2
* mingw-w64-Qt5 library provided by MSYS2
* Clion 2020.2

As a result I assume there might be some quirks in the mingw64 provided by TDM-GCC distribution.

**Comment by hosiet** [comment]
![图片](https://user-images.githubusercontent.com/8443926/92310280-ce098380-ef7a-11ea-85e0-9de63c162ea8.png)

Providing a screenshot of flameshot built with mingw-w64 with no special tweaks (just a plain CMake build). It looks like the major problem is that the program will always bring up a terminal. I think this should be solvable.

**Comment by ZetaoYang** [comment]
Compilation results for different compiler environments:
- MSVC 2019 64 bits: compiled successfully, because `_WIN32_WINNT > 0x0600`. `ShlObj.h` include `ShlObj_Core.h`, see 
  - https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenwithdialog
  - https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/ 
  - https://docs.microsoft.com/en-us/windows/win32/api/shlobj/
- Mingw64(GCC 9.3.0-1): compiled successfully, because `_mingw.h` define `_WIN32_WINNT 0x601`, `windows.h` include `_mingw.h`,
  ![image](https://user-images.githubusercontent.com/10769951/92317144-22bb0600-f030-11ea-9a6d-61dc7b0bacfa.png)
- Mingw64(TDM-GCC 9.2.0): compilation failure, because `_mingw.h` define `_WIN32_WINNT 0x502`,`windows.h` include `_mingw.h`,
  ![image](https://user-images.githubusercontent.com/10769951/92306825-b0610c00-efc4-11ea-8532-ec4aa8eb4f30.png)

So the root cause is `_mingw.h` header file of TDM-GCC define `_WIN32_WINNT` lower than Windows Vista.

**Comment by borgmanJeremy** [comment]
Good work on the investigation, I agree with the changes.

**Comment by ZetaoYang** [comment]
PR https://github.com/flameshot-org/flameshot/pull/849.
