### ISSUE TITLE
command line help string should be translatable

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#829]
**Flameshot version**
git HEAD

**Describe the bug**

When looking into #827 , I found that `helpText` in `CommandLineParser::printHelp` was not made to be translatable.

https://github.com/flameshot-org/flameshot/blob/8cf8cb9a652fb244246a5fca297de7a6ea31e003/src/cli/commandlineparser.cpp#L355-L358

 I believe these help texts should be made translatable to help users of different locales understand the text.

**Comment by borgmanJeremy** [comment]
Agreed. When a new string is added so you think the author should use Google translate to populate the translation? Or leave it unfinished.

**Comment by hosiet** [comment]
Perhaps we can leave it blank. When the entire code is ready for release (let's say if we will release it one or two weeks later) we can refresh all .ts files, make a translation call and accept Pull Requests for translation update.

**Comment by borgmanJeremy** [comment]
Yeah thats a good idea. With the changes will will had in #830 we can pass a cmake flag to update the ts files.

**Comment by borgmanJeremy** [comment]
Looking into this it seems none of the text printing by the CLI parser is in the translation files. I think this is a good thing to add, but will be more work than that one string.

**Comment by borgmanJeremy** [comment]
@Martin-Eckleben  fixed this in #839

**Comment by Martin-Eckleben** [comment]
Should be solved. Will close - if anybody disagrees comment and I'll reopen.
