### ISSUE TITLE
Weird snapping behavior

### ISSUE THREAD

**Issue by lucasrdrgs** [flameshot-org/flameshot#831]
**Flameshot version**
v0.8.0 compiled with Qt 5.15.0
PS: I installed it through Manjaro's GUI package manager and also tried through cloning the AUR snapshot package, it seems that only `flameshot-git` has this problem.
(EDIT: apparently I no longer have this issue with regular `flameshot`, but it lacks the text tool)

**Describe the bug**
Taking screenshots works just fine as long as I never press the Ctrl button (except Ctrl C to copy the selection to my clipboard). If I do so, it will enable snapping so all line tools will snap to angles that are multiple of 45°, and all shapes will be proportional. Snapping wont go away until I am done editing the screenshot and pressing Ctrl C or exiting through ESC. Here is an image showing what I mean: https://i.imgur.com/W7GL5WI.png

**To Reproduce**
All I have to do is press the Ctrl button and this happens.

**Expected behavior**
I expect the snapping mechanism to work as long as I hold Ctrl, and when I release it, it should go back to normal without locking tools to those angles/proportions.

**System Information**
OS: Manjaro Linux 5.8.3-2.
DE: xfce4.
WM: xfwm4.

**Comment by mmahmoudian** [comment]
@lucasrdrgs there will be a new release soon and the improvements you have seen in `flameshot-git` AUR will be also available in community version as well. 

Regarding this bug report, let see if we can reproduce it.

**Comment by borgmanJeremy** [comment]
@lucasrdrgs The new version is released. Can you update and see if it is still a problem?

**Comment by lucasrdrgs** [comment]
I have tested both Flameshot's official package in the Arch repository, and the AUR flameshot-git. Official one seems to not have this problem anymore, although snapping with Ctrl doesn't work at all. AUR one still has the problem, unfortunately. What source code file is responsible for handling the snapping behavior? If I find out how to fix it I'll happilly submit a pull request.

**Comment by mmahmoudian** [comment]
@lucasrdrgs #439 was the PR that added the feature. you can see which files were add/modified.

**Comment by mmahmoudian** [comment]
Closed after 3 months of inactivity. Please open this if you still have the issue with the latest Flameshot version.
