### ISSUE TITLE
Unexpected configuration file / path name

### ISSUE THREAD

**Issue by radoeka** [flameshot-org/flameshot#832]
**Flameshot version**
flameshot-0.6.0

**Describe the bug**
The config file name: .config/Dharkael/flameshot.ini or .config/Dharkael.ini, etc is unexpected.  

**To Reproduce**
Just install flameshot

**Expected behavior**
I would opt for, at least at linux system for: .config/flameshot/flameshot.ini or .config/flameshot.ini, etc is unexpected.
Even better might be:  .config/flameshot/flameshot.conf or .config/flameshot.conf, etc 

**System Information**
openSUSE_15.2

**Comment by borgmanJeremy** [comment]
Configuration files is something I want to look at refactoring but will not make it into the 0.8 release. I agree the behavior should be modified.

**Comment by borgmanJeremy** [comment]
This is actually resolved in the upcoming release due to general name consistency improvements. I was expecting to need to wait for a rework to the config system but it made it through in time. It will be at .config/flameshot/flameshot.ini
