### ISSUE TITLE
The size of counter bubble should be adjustable

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#840]
A new tool (autoincrement counter bubble) was added in flameshot. However, the size of this tool cannot be adjusted. This is often not friendly for HiDPI users.

![图片](https://user-images.githubusercontent.com/8443926/92335002-ccb28680-f060-11ea-8c7e-44c394e19a42.png)

(Like in this screenshot, the sizes of bubbles are all the same.)

* * *

It would be better if the counter bubble can be adjusted using the value of mouse scroll wheel.

**Comment by borgmanJeremy** [comment]
Good suggestion. While you are testing can you check if undo works? I have some issues with undo and the counter bubbles and I wonder if it is still there with HiDPI

**Comment by hosiet** [comment]
I just saw bugs related to numbering:

* Count number 1, 2, 3, 4, 5
* Make an undo
* Insert counter bubble again: the new number is supposed to be 5 but actually the number will be 6

I believe we need some sort of "hook" with undo/redo and modify the global counter value whenever an undo/redo happens. Or the action of numbering should also memorize its number when logged into the history. The final choice should be decided by the actual implementation (I did not read the source code of this part).

Besides that, I haven't seen bugs with HiDPI + counter bubble yet.

**Comment by borgmanJeremy** [comment]
I need to clean up the code but I think the bubble size feature is working. This also resolved a visual glitch related to undo on low dpi screens. Fixing the numbers will take a bit more thought. Let me know if this looks good to you and I'll get a PR submitted.

![Peek 2020-09-06 20-40](https://user-images.githubusercontent.com/46930769/92340816-58d4a600-f081-11ea-99f2-f6073ad46f1a.gif)

**Comment by hosiet** [comment]
This effect should be good enough. Glitch is actually not a big problem and at least I can't see it in the animation above.
