### ISSUE TITLE
Proposed Changelog from 0.6.0 to 0.8.0

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#844]
With v0.8.0 not too far away, I was looking back and seeing what has changed since the v0.6.0 release. This is a list of identified important changes written in GitHub markdown and I believe such list should eventually appear in https://github.com/flameshot-org/flameshot/releases .

To prevent the references to individual issues from appearing, the text is wrapped in a blockquote for now.

```markdown
# Features
* Fix capture after pressing ctrl + S during textarea input (#311)
* Add translation:
  - Japanese (#361)
  - Brazilian Portuguese (#364)
  - Serbian (#376)
  - Dutch (#440)
  - Ukrainian (#464)
  - German (#467)
  - Slovak (#525)
* Allow enter key to copy image to clipboard (#362)
* side panel: Add thickness slider (#374)
* Add support for saving as JPG and BMP files. (#436)
* Allow 45 degree adjustment for some tools (#439)
* Add option to close after capture (WARNING: this function is buggy! It may not work well if you are going to copy the image to clipboard! If you encounter problems related to clipboard, please disable this feature in the configuration and try again. This is a known bug, see #557 and #569 .)
* Add a basic launcher panel.
* Add option to auto copy URL after upload (#553) 
* Add a circle counter tool.
* Replace the blur tool with pixelate tool.
* Convert buildsystem from QMake to CMake.
* Add launcher action into .desktop file.

# Fixes
* Exit non-zero when aborting with --raw. (#424)
* Enable Pin and Text tool by default. (#443)
* Fix the problem that moving or resizing does not affect screenshot. (#459)
* Fix problem with re-enabling disabled tray icon (#495)
* Fix compilation problem against Qt 5.15.
```

**Comment by borgmanJeremy** [comment]
* The config file location changed to ~/.config/flameshot

**Comment by jandradas** [comment]
If at all possible, I would suggest not replacing the blur tool with the pixelate one... I would rather these both are offered or co-exist.  Blur could still be done as now if the "size" of the Pixelate tool is set to 0 (if set to 0, currently there is not pixelation I can appreciate now), and allow pixelating for other sizes.

**Comment by borgmanJeremy** [comment]
- Option to save to file when copied to clipboard.

**Comment by borgmanJeremy** [comment]
- Close after capture bugs should be fixed. 
- Added button for the sidebar (I am not sure what to call this tool)

**Comment by borgmanJeremy** [comment]
- Improved windows support (thanks @ZetaoYang )

**Comment by borgmanJeremy** [comment]
@jandradas Thanks for the feedback, this is now the behavior and will make it into 0.8
