### ISSUE TITLE
Naming discrepancy in the menus and window titles

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#847]
**Flameshot version**
Flameshot v0.6.0
Compiled with QT 5.9.5

**Describe the bug**
When right-clicking on the tray icon, there is an item named "Information", clicking on it will open a window named "About" which mostly contains "Shortcuts"!

**To Reproduce**
Right-clicking on the tray icon.

**Expected behavior**
Have uniform names.

**System Information**
OS: Ubuntu 18.04.5 LTS
DE: Budgie

**Comment by borgmanJeremy** [comment]
I propose changing the item to "About" to match the window title since "About" is a pretty standard menu name for bringing up hotkeys, version, etc.
