### ISSUE TITLE
"Copy information" GUI button and CLI argment

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#848]
When reporting bugs on Github, people are not using a uniform format and usually miss to report every detail about their system. I propose having a button in the "About" window and also an argument in the CLI that prints a uniform format of the system information. I've seen other software having such a button to make the dev's life much easier.

The information I can think of are :

* OS and version
* DE (Desktop Environment) or WM (Window Manager)
* System QT version
* Flameshot version
* Flameshot QT version (with which it has been compiled)
* Keyboard Layout (as some bug reports are about shortcuts not working)
* They way Flameshot was installed (OS package manager, AUR, Flatpak, AppImage, manual compile, ... ) (I'm not sure if this is technically possible.

**Comment by borgmanJeremy** [comment]
@mmahmoudian Can this be closed with the current implementation?

The missing features and why I don't think we can add them are:
Keyboard layout - Qt does not offer a way to get this. We can get locale, but not keyboard layout
Installation Method - Our app can't tell how its installed. We can try to add a "fingerprint" to the binary but this wont work when packaged by distros
Window Manager / DE - We might be able to get this by dumping a users environment variables, but sometimes this contains sensitive info so I don't really want to automate that.

**Comment by mmahmoudian** [comment]
I agree with your points. Let's close this then.
