### ISSUE TITLE
Side effect on D-Bus naming as org.flameshot-org.Flameshot

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#858]
**Flameshot version**
git HEAD

**Describe the bug**

I noticed there was a https://github.com/flameshot-org/flameshot/commit/60ef3f3e6f63be4fa2555bf810221623b2034cd6 . Compared to https://github.com/flameshot-org/flameshot/commit/18f18ce7ef319ebedf1e0adfd4a87eb4cd798e81 , the new commit forgot to tune the D-Bus name in `docs/shortcuts-config/flameshot-shortcuts-kde` , `src/core/flameshotdbusadapter.h` and ` src/utils/dbusutils.cpp`. The latter two occurrences are very important and should be fixed. We need to keep this name unified across the whole repository so that the D-Bus part does not break.

**Comment by borgmanJeremy** [comment]
Is the official dbus name org.flameshot.Flameshot? 

The reason I made the change was I noticed the cpp files were still org.Dharkael.Flameshot.
