### ISSUE TITLE
Another bug with counter circle undo/redo

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#867]
**Flameshot version**
git HEAD

**Describe the bug**
I think there are still bugs with counter circle undo/redo.

**Reproduce the bug**
* Invoke counter circle 1, 2, 3, 4, 5
* Undo
* Undo
* Redo
* Redo
* Invoke counter circle again. It is supposed to be 6 but actually gives 4.

**Comment by borgmanJeremy** [comment]
Good catch. I need to have redo emit the increments.

**Comment by borgmanJeremy** [comment]
Thanks for all the testing on this new feature. Hopefully this is the last bug :)

The fix is not as elegant as I want it to be, but the UndoStack as provided by Qt uses strings instead of any other type of ID.
