### ISSUE TITLE
Please document the uncommon necessity of D-Bus in README

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#879]
Flameshot actually needs a working D-Bus session for a considerable part of its functions. For example, if D-Bus is not working on user's computer (e.g., the user is using a custom WM), all flameshot subcommands like `flameshot gui` or `flameshot config` will not work. All desktop notification will not work as well. It is at least the partial (if not the whole) reason behind #353 and #403 .

I believe we should mention this characteristic somewhere in README.md.

**Comment by mmahmoudian** [comment]
I strongly suggest fixing this in the code in a way that when someone runs any of the subcommands (e.g`flameshot giu`), the software handles the possible missing D-Bus session and then proceed to execute the subcommand

**Comment by borgmanJeremy** [comment]
@mmahmoudian I agree this is a good solution but may take some refactoring. Can we wait untill 0.9?

**Comment by mmahmoudian** [comment]
@borgmanJeremy for sure you know best how trivial or bot it is to fix this in the code base. I'm not going to even pretend to know. If you think it should be done in 0.9 due to technical reasons, then for sure. All I'm saying is that this is an issue that a wide range of users are facing.

For now, for those who have good control over the command behind the keyboard shortcut, we can provide a one-liner in the README (as I have done in a comment #790 ):

```
( flameshot &; ) && ( sleep 0.5s && flameshot gui )
```

**Comment by borgmanJeremy** [comment]
@mmahmoudian Yeah I think to do it properly will take some time and design iteration. In my head it would be nice to solve it in such a way that at compile time you can choose to compile without DBUS.

**Comment by mmahmoudian** [comment]
I was checking out the Arch wiki of Flameshot and found the following and thought it worth quoting it here:
https://wiki.archlinux.org/index.php/Flameshot#Troubleshooting
> ## Sub-commands exit immediately with no output
> ### Option 1: Use dbus-launch
> Some X clients (dwm, i3, xmonad, possibly others) must be started with dbus-launch in order for Flameshot to start when using its sub-commands (e.g., `flameshot gui`, `flameshot config`). 
> For example, using xinit: 
> ```
> exec dbus-launch dwm
> ```
> 
> ### Option 2: Run as background process
> Alternatively, you can start Flameshot as a background process at any time during your X session:
> ```
> $ flameshot &
> ```
