### ISSUE TITLE
Duplication of translation files

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#880]
**Flameshot version**
git.HEAD

**Describe the bug**
Some translation files name isn't friendly to case-**insensitive** Operation Systems(or file system). Conflicting names of translation files. Duplication of translation files.

e. g. On Windows 10
  ![image](https://user-images.githubusercontent.com/10769951/92699034-adc53480-f37f-11ea-81b3-bf501b97a16c.png)

  The letter "i" is used in two words, one in upper and one in lower case. **I**nternationalization and **i**nternationalization.

The resulting phenomenon is "git shows unstaged files after clone",
  ![image](https://user-images.githubusercontent.com/10769951/92699143-c9c8d600-f37f-11ea-96c8-885e43425741.png)

**Comment by borgmanJeremy** [comment]
Some old translation files had a lower case "i".  When I merged in the new translation files I fixed it so each translation file used a capital "I" to be consistent.

**Comment by ZetaoYang** [comment]
@borgmanJeremy Yes, you're right.

**Comment by borgmanJeremy** [comment]
Since this cant be fixed from flameshot I will close this
