### ISSUE TITLE
Option to have tool area pinned on top of screen instead of moving around the screenshot area

### ISSUE THREAD

**Issue by DesertStars** [flameshot-org/flameshot#883]
It's nice to see flameshot finally getting some first of all, thanks to all of the developers. My issue is when I'm taking a screenshot, tool area will try to adjust to the size of area I'm taking screenshot of, and in cases where the area I'm taking a screenshot is very small (100x100 for example), it'll look very crowded. This could be improved by pinning the tool area to the top of screen the way ShareX does, example below:

![](https://getsharex.com/img/screenshots/EuWr1mL.png)

**Comment by borgmanJeremy** [comment]
Thanks for the feedback, I found an earlier duplicate on #573. I will close this issue for now but we will eventually put this feature through RFC.
