### ISSUE TITLE
remember and use last screenshot dimensions

### ISSUE THREAD

**Issue by espiritocz** [flameshot-org/flameshot#888]
hi,

after shutter disappeared, i lost possibility of a precise screenshotting on linux.
this feature would be so useful for many!!!
can you please provide the functionality, i.e. to keep track of last 1 screenshot dimensions - and allow e.g. to use a keyboard shortcut to do a screenshot of the same area?
should not be hard to do )

thank you.

**Is your feature request related to a problem?**
Please, a single feature per issue.

**Comment by borgmanJeremy** [comment]
Does the feature described in #417 meet your needs? If so, I will close this as a duplicate and we will get an RFC submitted to discuss this feature after the 0.8 release.

**Comment by espiritocz** [comment]
yes!
happy to see that not only me is missing this

pátek 11. září 2020 borgmanJeremy <notifications@github.com> napsal(a):
> Does the feature described in #417 meet your needs? If so, I will close
this as a duplicate and we will get an RFC submitted to discuss this
feature after the 0.8 release.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/84mOdDIt10xuGCUsktHEycG7IUAhNNHMK8CsV9KjFRQZ2WhzrrOCAF_uOppJ1fQgCSpE3zb_Gz6cvuCYiuo7DvHR58OTZL4A22extomRW_n__f3CVhr-uQ01ceAj8UeOqMYT_nVd4GuxgN7b5VgLHJNPQVtKB8TCBe7m_OH1Boy9JoXyfQrIwQAtx82QW3pygy8y-39hdECgUak7dZsz5WtP3GKiDckCn6YnrRUmsg=s0-d-e1-ft#https://github.com/notifications/beacon/AADYYKQWWFP2QM76XLOG4Q3SFJC3HA5CNFSM4RHJ3MZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFEZJKBA.gif>

**Comment by borgmanJeremy** [comment]
Great! after the 0.8 release we will be doing official RFC's to get feedback on the design of new features and this one will be very popular I think.
