### ISSUE TITLE
Snap build is failing: illegal version string

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#905]
**Flameshot version**
git HEAD

**Describe the bug**

The GitHub action building snap package is failing: https://github.com/flameshot-org/flameshot/pull/904/checks?check_run_id=1109573141

It looks like the version string is not valid when doing snap packaging.

> Issues while validating properties: The 'version' property does not match the required schema: 'v0.8.0_beta+git0.fa9ec7a' is not a valid snap version string. Snap versions consist of upper- and lower-case alphanumeric characters, as well as periods, colons, plus signs, tildes, and hyphens. They cannot begin with a period, colon, plus sign, tilde, or hyphen. They cannot end with a period, colon, or hyphen.
> Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
##[error]The process '/usr/bin/sg' failed with exit code 2

Perhaps our use of underscore triggered this problem.

**Comment by borgmanJeremy** [comment]
What do you think about v0.8.0.rc1

**Comment by hosiet** [comment]
Using v0.8.0.rc1 should be a good choice

**Comment by borgmanJeremy** [comment]
That seems to be working in CI now.
