### ISSUE TITLE
Counter bubble sometimes adds cropped values

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#909]
_Originally posted by @aivchen in https://github.com/flameshot-org/flameshot/issues/884#issuecomment-691821512_

> Glad to see that the project is alive again!
> An auto-incrementing counter bubble sometimes adds cropped values: https://i.imgur.com/J3Nqd3m.png

@aivchen what OS do you use, and how did you install Flameshot?

[![image](https://user-images.githubusercontent.com/390889/93060012-38f14380-f67a-11ea-951e-fcd6a1620ae9.png)](https://i.imgur.com/J3Nqd3m.png)

**Comment by mmahmoudian** [comment]
I bet in monospace font the behavior is more consistent (either consistently cropped or consistently correct). I can extrapolate that with the current system, the three-digit bubbles are impossible. For this we have the following solutions:
1. The radius of the circle gets changed by the width of the string (or alternatively we circle turn into an oval shape by elongating the horizontal axis)
2. we always use monospace font
3. we put a cap on the max of the number.

**Comment by borgmanJeremy** [comment]
@mmahmoudian 

1.) I think it would be better to scale down the font to fit in the bubble so the outer size is consistent. I think there is a way to do this without too much trouble.

3.) I thought about this when I was coding it, and I can't imagine ever using flameshot to make over 99 bubbles, Since we don't support dragging features once they are placed it would be a nightmare to try to use flameshot with that many assets.

**Comment by borgmanJeremy** [comment]
@mmahmoudian  and @aivchen  can you try the appimage from this PR #917 I think this will resolve the issue. It even fixes it over 99 because it will rescale the font to fit the bubble:
![image](https://user-images.githubusercontent.com/46930769/93093012-cf673a00-f665-11ea-97db-a5b6253a2adb.png)

**Comment by mmahmoudian** [comment]
@aivchen To save you some time, the following is the AppImage:
https://we.tl/t-9JitQFf3a1

**Comment by mmahmoudian** [comment]
@borgmanJeremy it works, but it occurred to me that the size of the bubbles should not be 0 and it should start from 6 or 7:

![image](https://user-images.githubusercontent.com/390889/93095657-0bbd8900-f6ac-11ea-917f-cb2ca3c63e50.png)

**Comment by borgmanJeremy** [comment]
@mmahmoudian The issue is all sizes in all of flameshot use one shared variable. This is something we likely will refactor in 0.9 and keep a unique thickness per tool, but until that refactoring it is not really possible.

**Comment by mmahmoudian** [comment]
But how about for now we add +6 to "counter bubble" size? no if statement is needed. This would make sure that when global size goes to 0, the bubble size would stay at 6

**Comment by borgmanJeremy** [comment]
I think it would be better to just (in pseudo code)
```
if (shared_thickness < 6)
   bubble_thickness = 6
else()
  bubble_thickess = shared_thickness
```
Then users who want a very specific thickness (for example to match the size of other tools) will not be confused.

**Comment by borgmanJeremy** [comment]
#917  Is updated with minimum bubble size if you want to check @mmahmoudian

**Comment by mmahmoudian** [comment]
@borgmanJeremy I think the minimum is still very small, also the text cropping seems to be there:
![image](https://user-images.githubusercontent.com/390889/93119226-1b4bca80-f6ca-11ea-9346-5db150206822.png)

**Comment by borgmanJeremy** [comment]
What is your font so I can test local?

**Comment by aivchen** [comment]
Yes, I still have copped numbers.
![image](https://user-images.githubusercontent.com/4580308/93125497-e6447580-f6d3-11ea-8e67-a2b30c945a26.png)

Also, I have the following output in the console (I hope this can help):
```
andrew@andrew-pc /tmp> ./Flameshot-0.8.0-x86_64.AppImage
Run experimental self-contained bundle
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

>What is your font so I can test local?

How can I find the font I'm using?

**Comment by borgmanJeremy** [comment]
@aivchen @mmahmoudian Apologies, in my rush I pushed the wrong commits. It should work now (it at least does locally).

**Comment by aivchen** [comment]
@borgmanJeremy @mmahmoudian Everything works fine now. Thank you!
