### ISSUE TITLE
[0.8 Beta] Pixelate tool

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#911]
**Flameshot version**
0.8 Beta testing, compiled from source

**Describe the bug**
I have found two things:
* Pixelate: values from 0-1 has no effect
* Pixelate: the higher the value the less precise you can select the area to pixelate, it depends on the block size.

**Expected behavior**
* Values from 0-1 should also have a visible effect when pixelating.
* The user should be able to define the area he wants to pixelate exactly and not, like now, that the area gets more and more grainy the bigger the value is set of the tool.

**System Information**
Arch Linux, Xfce, Xorg

**Comment by borgmanJeremy** [comment]
For values 0-1 we are considering have that do the old "blur" feature. @mmahmoudian How do you feel about this?

I will need to look into the best way to solve the block size issue. I can see how this could cause issues, but may take a larger rework.

**Comment by mmahmoudian** [comment]
Well, I quickly grabbed the AppImage (awesome for testing without removing the local version of Flameshot) and the following are my observations:
1. to my surprise, the default value (size/thickness) was zero and the pixelation didn't change anything. At first I tought something is not working and then I increased the size and saw the effect. For this reason I think for Pixelate, we should start fat least from 1 and not zero (size +1)
2. I increase the size in the following condisions up to 23 and I could exactly select and pixelate what I wanted:
    - choosing the size before click&drag
    - click and drag with size 0 and then scoll to change the size

Therefore, I confirm @kpcee 's first observation ("values from 0-1 has no effect"), but I could not reproduce the second one.

**Comment by kpcee** [comment]
> Therefore, I confirm @kpcee 's first observation ("values from 0-1 has no effect"), but I could not reproduce the second one.

Please try the maximum block size of 100 then the block effect should be most obvious.

> I will need to look into the best way to solve the block size issue. I can see how this could cause issues, but may take a larger rework.

Great! But I would like to point out my solution some time ago, because there is no problem with the selection and the source code was also much shorter.

**Comment by borgmanJeremy** [comment]
@kpcee That is a good point can you please remind me where you posted that solution, it got lost in the shuffle and I forgot to take a close look at it. It indeed will solve the selection issue. 

@mmahmoudian for size of 0 and 1 we have two choices, override the thickness variable that sets the pixel size when less than 1, or use the old blur tool. There was some requests to have a way to use the old blur tool so this is the direction I am leaning.

**Comment by mmahmoudian** [comment]
> try the maximum block size of 100 then the block effect should be most obvious.

@kpcee you are right, but if someone wants to have such granularity of selection with such high pixel size, using the rectangle tool is a better choice and it will produce the same effect!

>  override the thickness variable that sets the pixel size when less than 1, or use the old blur tool
@borgmanJeremy I prefer the second choice (blur tool)

**Comment by kpcee** [comment]
@borgmanJeremy I had to look for it myself first ;) The set block size is only reached with larger values if the selection is accordingly large. 0 and 1 have the same effect.
```
void
PixelateTool::process(QPainter& painter, const QPixmap& pixmap, bool recordUndo)
{
    if ( recordUndo )
    {
        updateBackup( pixmap );
    }

    QPoint &p0      = m_points.first;
    QPoint &p1      = m_points.second;
    QRect selection = QRect( p0, p1 ).normalized();

    int width = selection.width() * ( 0.5 / qMax( 1, m_thickness ));

    QPixmap t = pixmap.copy( selection );
    t         = t.scaledToWidth( qMax( width, 10 ), Qt::SmoothTransformation );
    t         = t.scaledToWidth( selection.width() );
    painter.drawImage( selection, t.toImage() );
}
```

**Comment by borgmanJeremy** [comment]
Ok PR #922 uses your simpler method which gives better selection and institutes the old blur tool for sizes 1 or less.

**Comment by kpcee** [comment]
Ah great, thanks.
