### ISSUE TITLE
[0.8 Beta] Open Launcher, take Full Screen does not work

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#912]
**Flameshot version**
0.8 Beta testing, compiled from source

**Describe the bug**
Tray Icon -> Open Launcher -> Full Screen -> Take new screenshoot
The preview image is updated, otherwise nothing happens.

**Expected behavior**
After the screenshot has been taken the image should be ready for further processing or at least a signal should sound that the image has been saved automatically. Currently it is not clear what happens, the image is not saved or I didn't found it and the editing tools are not shown.

**System Information**
Arch Linux, Xfce, Xorg

**Comment by mmahmoudian** [comment]
Confirmed! after pressing "Take new screenshot" nothing happens. The Launcher window closes and re-opens, but nothing is saved in Clipboard or in the following locations that I thought might be saved to:
- `~/Pictures`
- `~/`
- `~/Desktop`

### Setup Info
- `Flameshot-0.8.0-x86_64.AppImage`
- OS: Ubuntu 18.04
- DE: Budgie
- Two monitors both connected to the same graphics card

**Comment by borgmanJeremy** [comment]
Good catch! I did some git bisecting and it turns out this feature never worked and was never finished.
