### ISSUE TITLE
[0.8 Beta] Open Launcher allow only one instance

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#913]
**Flameshot version**
0.8 Beta testing, compiled from source

**Describe the bug**
Tray Icon -> Open Launcher, repeat this several times.
Each time a new instance of the window is created.

**Expected behavior**
If an instance already exists, it should be brought to the foreground but no new instance should be created.

**System Information**
Arch Linux, Xfce, Xorg

**Comment by mmahmoudian** [comment]
Confirmed!

![image](https://user-images.githubusercontent.com/390889/93092317-f5153300-f6a7-11ea-977d-e3658c3059e3.png)

**Comment by mmahmoudian** [comment]
I confirm that this is solved in #931
