### ISSUE TITLE
[Feature Request] Rename the config folder

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#915]
In Linux the settings are stored in the folder `~/.config/Dharkael`. But it would make much more sense and the user would know which program the folder belongs to, if the folder would have the name of the programm, so would simply be called "flameshot" or "Flameshot".

**Comment by borgmanJeremy** [comment]
This should be resolved in the 0.8 beta. Check in ~/.config/flameshot

**Comment by mmahmoudian** [comment]
@kpcee I'll close this as it is already addressed in the version you have compiled. Feel free to re-open this if it is not resolved.

**Comment by kpcee** [comment]
I did not see it, sorry.
