### ISSUE TITLE
[Feature Request] Different settings per tool

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#920]
Currently there is a global setting that is valid for all tools (thickness). But it would be nice if at least drawing tools, text (counter bubble), text marker and pixelate have their own settings and remember their value, because currently you have to change the strength more often.

**Comment by mmahmoudian** [comment]
It is already discussed before (e.g #782). 👍🏼

**Comment by kpcee** [comment]
Okay, unfortunately I did not see the other thread.

**Comment by mmahmoudian** [comment]
No worries, the issues section of this repo is cluttered and we are trying to declutter it. Please report duplicates if you stumbled upon any 👍🏼
