### ISSUE TITLE
Does flameshot have a feature to set one shortcut to activate flameshot,like 'ctrl+alt+a'

### ISSUE THREAD

**Issue by zz940522** [flameshot-org/flameshot#923]
Does flameshot have a feature to set one shortcut to activate flameshot,like 'ctrl+alt+a'

**Comment by mmahmoudian** [comment]
Assuming you are using Linux, this is something that should be handled with your Desktop Environment (Gnome, KDE, Xfce, LXDE, ...) or Window Manager (dwm, Xmonad, Awesome, i3, bspwm, ...).

Simply go to the keyboard shortcuts settings and add an item to run:

```sh
( flameshot &; ) && ( sleep 0.5s && flameshot gui )
```
