### ISSUE TITLE
Flameshot hardcodes ~/.config/autostart instead of using $XDG_CONFIG_DIRS

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#928]
I was reading the source code and found that the source code handling autostart is to hardcode `$HOME/.config/autostart/`. According to the XDG specification (https://specifications.freedesktop.org/autostart-spec/0.5/ar01s02.html), we should be using `$XDG_CONFIG_DIRS/autostart` first and fallback to `~/.config/autostart` only when `$XDG_CONFIG_DIRS` was not set.

This would require a little bit of code refactoring, including searching of both canonical and fallback locations. Maybe we can do it after 0.8.x release.

**Comment by adzimzf** [comment]
Hi, I'll try to work on this.
but since this is my first time contribute to flameshot, it may take a bit longer

**Comment by borgmanJeremy** [comment]
@adzimzf Feel free to drop in our slack group to ask for advice in the dev channel or just pm me directly. flameshotworkspace.slack.com/

**Comment by adzimzf** [comment]
thank you so much for warm welcome

**Comment by mmahmoudian** [comment]
@borgmanJeremy Shall I assign this to @adzimzf to indicate others that they should not spend time on this?

**Comment by borgmanJeremy** [comment]
Yup good idea

**Comment by adzimzf** [comment]
Hi @borgmanJeremy 
How to log in to flameshotworkspace.slack.com, do I have to be invited first?

**Comment by mmahmoudian** [comment]
@adzimzf Here you go: https://join.slack.com/t/flameshotworkspace/shared_invite/zt-hpogvgw3-MU3ODwLXe0CCzQinFRhp0g

**Comment by adzimzf** [comment]
Thank you @mmahmoudian
