### ISSUE TITLE
The escape key does not close flameshot

### ISSUE THREAD

**Issue by fraval13** [flameshot-org/flameshot#929]
**Flameshot version**
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Describe the bug**
Pressing "esc" does not exit from taking a picture.

**To Reproduce**
Open Flameshot and press "Esc".

**Expected behavior**
Flameshot closing when pressing "Esc"

**System Information**
Ubuntu 20.04 running KDE plasma.

**Comment by borgmanJeremy** [comment]
Could you please test an app image from our CI builds? If not we will have version 0.8 releasing this weekend which should fix the issue: https://we.tl/t-Xydp8BDQjn

**Comment by borgmanJeremy** [comment]
Closing as stale (and I just tested on ubuntu 20.04 for another issue).
