### ISSUE TITLE
[0.8 Beta] Generic package(Flatpak, AppImage, Snap) test reports under Linux

### ISSUE THREAD

**Issue by ZetaoYang** [flameshot-org/flameshot#933]
**Flameshot version**
0.8.0 from github actions build: https://github.com/flameshot-org/flameshot/runs/1130500353

**Flatpak**
X11:
![Screenshot from 2020-09-18 16-21-09](https://user-images.githubusercontent.com/10769951/93543783-0c496e80-f98f-11ea-9246-a18e0e232d6d.png)
![Screenshot from 2020-09-18 16-21-27](https://user-images.githubusercontent.com/10769951/93543821-1e2b1180-f98f-11ea-8337-949259377df0.png)

fameshot works well except "open with" tool.

Wayland: flameshot cannot capture! But it can run, and indicator also appears(support fallback theme). screenshots see https://github.com/flameshot-org/flameshot/pull/910. issue https://github.com/flameshot-org/flameshot/issues/918

**AppImage**
X11: flameshot works well. The "open with" tool doesn't seem to work either, sorry, I didn't test this feature carefully.

Wayland:
![Screenshot from 2020-09-18 16-31-26](https://user-images.githubusercontent.com/10769951/93544464-baa1e380-f990-11ea-89d6-354b8d12da99.png)

When system scale is 100%, The capture window view shows normally.
![Screenshot from 2020-09-18 16-33-28](https://user-images.githubusercontent.com/10769951/93544571-fb016180-f990-11ea-8f9b-aaaabd814e9c.png)

However, when system scale is more than 100%, The capture window view seems counterintuitive. I'm guessing other packages(deb, rpm) have this problem as well.
![Screenshot from 2020-09-18 16-34-33](https://user-images.githubusercontent.com/10769951/93544758-592e4480-f991-11ea-9716-2a9fa432e4bf.png)

**Snap**
X11:
![1](https://user-images.githubusercontent.com/10769951/93545035-0c973900-f992-11ea-9197-c4e3566489cf.png)
![4](https://user-images.githubusercontent.com/10769951/93545065-1b7deb80-f992-11ea-86be-415d6658bb94.png)

fameshot works well except "open with" tool. And its indicator didn't show fallback theme.

Wayland:
![Screenshot from 2020-09-18 16-24-05](https://user-images.githubusercontent.com/10769951/93545094-2d5f8e80-f992-11ea-8bd0-cf7e0540375b.png)
flameshot cannot capture! But it can run, and indicator didn't show fallback theme.

**System Information**
Manjaro Linux 2020.1 Gnome

**Comment by mmahmoudian** [comment]
My observation for Appimage in X11: in contrast to what @ZetaoYang observed, the "open with" worked fine, but it had a huge delay (something around 5 seconds) from the time I pressed the button until the time Flameshot was closed and then the "open with" window appeared. This behavior only happens the first time I click on "open with" in every run of the Flameshot AppImage app, as if the first one paves the way for the next "open with"s until I quit Flameshot.


![Peek 2020-09-18 13-00](https://user-images.githubusercontent.com/390889/93585523-9c97ab80-f9af-11ea-8f66-f5b218c73a05.gif)



Here is the terminal log:
```
❯  ./Flameshot-0.8.0-x86_64.AppImage
Run experimental self-contained bundle
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
```

**Comment by mmahmoudian** [comment]
@ZetaoYang should this be closed or do you think it still serves a purpose?

**Comment by crifan** [comment]
Finally fixed by change flameshot shortcut from:
`flameshot gui`
to
`env QT_AUTO_SCREEN_SCALE_FACTOR=1.5 flameshot gui`
in which, `1.5` --->>> `Settings`->`Display`->**Scale: 150%**
