### ISSUE TITLE
pixelate does not work

### ISSUE THREAD

**Issue by freddii** [flameshot-org/flameshot#938]
**Flameshot version**
Flameshot v0.8.0(beta1,Debian)
Compiled with Qt 5.14.2

**Describe the bug**
I choose pixelate. 
I draw a rectangle with my mouse.
But it has no effect.
Nothing gets pixelated.

**Expected behavior**
Choose pixelate. 
Draw a rectangle with mouse.
The choosen rectangle should get pixelated.

**System Information**
Linux debian 5.8.0-1-amd64 #1 SMP Debian 5.8.7-1 (2020-09-05) x86_64 GNU/Linux

**Comment by hosiet** [comment]
@freddii What was the brush size number when you are using the pixelette tool? Could you use the mouse wheel to set it to a larger number (e.g., 50) and try again?

It could be the reason that the brush size is too small that the effect cannot be seen. In this case, the problem will be solved in the official version of 0.8.0.

**Comment by freddii** [comment]
I changed the brush size number.
Now its working.
Thanks.
