### ISSUE TITLE
Boost Program Options for CLI Parsing

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#945]
**Flameshot version**
0.8.0

When testing the CLI argument parses with Clang address sanitizer enabled there are many memory leaks found. After Flameshot was originally written, new c++ CLI parsers have been introduced. I would like to refactor the command line parses with cxxopts: https://github.com/jarro2783/cxxopts

This will be a good opportunity to clean up a small portion of code, implement unit tests, and fix memory leaks.

**Comment by hosiet** [comment]
Looking into https://repology.org/project/cxxopts/versions , cxxopts is not in debian-based distributions and Arch Linux (AUR is not part of the official repo). Using it means that we will need to embed the source code.

Is there any other sane choices that sits in the standard libraries? STL or boost are also acceptable.

**Comment by xvitaly** [comment]
> Using it means that we will need to embed the source code.

It can be easy (packaged version as default and fallback to bundled if not found):

```
find_package(cxxopts 2.2.0 CONFIG QUIET)

IF (NOT cxxopts_FOUND)
    message(STATUS "Using bundled version of cxxopts library.")
    include_directories("${CMAKE_SOURCE_DIR}/external/cxxopts/include")
ENDIF()
```

**Comment by borgmanJeremy** [comment]
@hosiet thanks for the feedback. I will compare cxxopts with boost program options.

I usually use the Conan package manager to avoid bundling external libraries directly.

**Comment by borgmanJeremy** [comment]
This will also help make the cli parsing cross platform as asked for in #988

**Comment by ZetaoYang** [comment]
There are some other parsers here as well. Here is the [CLI11](https://github.com/CLIUtils/CLI11) author's opinion and comparison of other parsers.  https://github.com/CLIUtils/CLI11#other-parsers

**Comment by veracioux** [comment]
I'm coming in a little late, but have you considered using Qt's [`QCommandLineParser`](https://doc.qt.io/qt-5/qcommandlineparser.html)? I have used it only a little, but I find it pretty straightforward and I think it has all the features flameshot needs. It also has the benefit of no extra dependencies.
