### ISSUE TITLE
Ubuntu .deb package for v0.8.0 release cannot be installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#949]
**Flameshot version**
0.8.0

**Describe the bug**
* `flameshot_ubuntu_0.8.0-1_amd64.deb` as provided on the GitHub release page requires Qt 5.12 or later.
* Ubuntu 18.04 only provides Qt5 5.9.5.
* The deb package cannot be installed since the version requirement is not met.

**Comment by borgmanJeremy** [comment]
We should probably tweak the CI to build against Qt 5.9.5 then. I am not sure if we are fully compatible with that version.

**Comment by hosiet** [comment]
Or we could split the ubuntu build to be a ubuntu-18.04 one and a ubuntu-20.04 one. At least some optional features requires Qt 5.10+, like #318 .

**Comment by hosiet** [comment]
@borgmanJeremy We really need to reopen this issue as the problem described in #959 was not really fixed.

**Comment by borgmanJeremy** [comment]
Sorry it auto closed since the issues was linked. Thanks for pointing it out.

**Comment by hosiet** [comment]
![图片](https://user-images.githubusercontent.com/8443926/94027924-5f556400-fd89-11ea-9da4-90999a8fdeca.png)

I am not sure why this would ever happen; are we building the 18.04 .deb file using 20.04 environment? Reading the github action file, it does not seem to be the intended behaviour but that is what happened. Sorry but I am not familiar with github action so I can't give advice on the fix now.

**Comment by hosiet** [comment]
Could it be we are missing `env:   OS: ubuntu DIST: bionic` for the `ubuntu-18.04` build?

**Comment by ZetaoYang** [comment]
@hosiet No, I try build deb on github actions ubuntu 18.04 images(I didn't use docker images to build it.), it already has cmake installed(cmake version 3.17.0). see https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md.

**Comment by hosiet** [comment]
@ZetaoYang Then we need some further investigation since current outcome is not what we intended. This has nothing to do with cmake.

**Comment by hosiet** [comment]
Alright, I think I get the reason. Here are the output from the ubuntu-18.04 environment from https://github.com/flameshot-org/flameshot/pull/962/checks?check_run_id=1155964243 :

```
gcc-7:
  Installed: 7.5.0-3ubuntu1~18.04
  Candidate: 7.5.0-3ubuntu1~18.04
  Version table:
 *** 7.5.0-3ubuntu1~18.04 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.3.0-16ubuntu3 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
gcc-8:
  Installed: 8.4.0-1ubuntu1~18.04
  Candidate: 8.4.0-1ubuntu1~18.04
  Version table:
 *** 8.4.0-1ubuntu1~18.04 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     8-20180414-1ubuntu2 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
gcc-9:
  Installed: 9.3.0-11ubuntu0~18.04.1
  Candidate: 9.3.0-11ubuntu0~18.04.1
  Version table:
 *** 9.3.0-11ubuntu0~18.04.1 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
gcc-10:
  Installed: (none)
  Candidate: 10.1.0-2ubuntu1~18.04
  Version table:
     10.1.0-2ubuntu1~18.04 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
libcc1-0:
  Installed: 10.1.0-2ubuntu1~18.04
  Candidate: 10.1.0-2ubuntu1~18.04
  Version table:
 *** 10.1.0-2ubuntu1~18.04 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     8.4.0-1ubuntu1~18.04 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     8-20180414-1ubuntu2 500
        500 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
libgcc-s1:
  Installed: 10.1.0-2ubuntu1~18.04
  Candidate: 10.1.0-2ubuntu1~18.04
  Version table:
 *** 10.1.0-2ubuntu1~18.04 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

We have gcc-9 and gcc-10 installed by default, both uses `libgcc-s1` instead of `libgcc-1`. However, vanilla Ubuntu 18.04 only provides gcc-8 which uses libgcc-1.

On the one hand, the provider of this certain Docker image adds extra GCC tools from PPA http://ppa.launchpad.net/ubuntu-toolchain-r/test/ in hope that they might be useful for some developers. On the other hand, this makes the environment extremely toxic for packagers since the built packages can only be used for testing but not for release purposes at all.

I believe we cannot build the ubuntu-18.04 release package from current CI environment. We need to use another clean chroot environment (like what packpack does).

**Comment by borgmanJeremy** [comment]
@hosiet Can you confirm #963 fully fixed it? If so I will backport to a 0.8 branch and get new debs released.

**Comment by hosiet** [comment]
@borgmanJeremy I cannot find a 0.8 branch anywhere. I thought it hasn't branched out from master branch. If there is one, it's better to push it onto flameshot-org/flameshot repo soon.

On the other hand, I suggest cherry-picking c56bb78cf38f5bb864ea66a755c1185cadae5348 and 42f6c8d501d50c765ccec5bbfe0ffdc1fbcbc925 in the 0.8.x branch.

**Comment by hosiet** [comment]
(and I confirm that #963 properly fixes this issue.)

**Comment by borgmanJeremy** [comment]
Yes I will make the branch and cherry pick those commits. I will then upload seperate debs for ubuntu 18.04 and 20.04 and tag them 0.8.1

**Comment by hosiet** [comment]
If it's a new tag, there should be a full release including all platforms, not only Ubuntu 18.04/20.04. Also we need to bump references of 0.8.0 to 0.8.1 everywhere and update release notes. Otherwise there will be questions popping up later asking for missing release information.

That's all chore work but still necessary.

**Comment by borgmanJeremy** [comment]
Good points, I'll do a full release tonight. Since we will do a full release i will just work from master and not make a separate branch. There are only minor bug fixes at this point.
