### ISSUE TITLE
Tray icon disappears with version 0.8.0

### ISSUE THREAD

**Issue by AlexWayfer** [flameshot-org/flameshot#950]
**Flameshot version**

0.8.0

**Describe the bug**

There is no tray icon, but it was before update as I remember.

**To Reproduce**

Just install Flameshot v. 0.8.0.

**Expected behavior**

There is a tray icon.

**System Information**

Arch Linux, GNOME Shell 3.36.6.

**Comment by borgmanJeremy** [comment]
Did you install through aur or pacman?

**Comment by AlexWayfer** [comment]
> Did you install through aur or pacman?

Official package:

```
> yay -Qs flameshot
local/flameshot 0.8.0-1
    Powerful yet simple to use screenshot software
```

**Comment by borgmanJeremy** [comment]
Check your config file for 

```disabledTrayIcon=true```

```cat ~/.config/flameshot/flameshot.ini```

**Comment by AlexWayfer** [comment]
> Check your config file for
> 
> `disabledTrayIcon=true`
> 
> `cat ~/.config/flameshot/flameshot.ini`

It's `false`. This is strange. Why is it not synchronized with GUI?

![image](https://user-images.githubusercontent.com/6510020/93790770-15ab3300-fc3c-11ea-9a73-5d3f959307c3.png)

**Comment by borgmanJeremy** [comment]
Sorry its a double negative "Disabled = false" means it should be enabled. I am also on arch but using KDE and I3. Maybe it is an issue with the latest gnome-shell. I'll do some testing and report back.

**Comment by AlexWayfer** [comment]
> Sorry its a double negative "Disabled = false" means it should be enabled.

Oh, sorry, I'm inattentive.



> I am also on arch but using KDE and I3. Maybe it is an issue with the latest gnome-shell. I'll do some testing and report back.

OK, thank you, I'm also using this extension: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by borgmanJeremy** [comment]
Okay I tested in a VM with that extension on 0.6 and 0.8 and the behavior is the same. The icon actually does appear but it is very very very hard to see. 
![image](https://user-images.githubusercontent.com/46930769/93795572-31441880-fbff-11ea-89f0-da8a32e26339.png)

**Comment by borgmanJeremy** [comment]
After more digging this is not a bug. We are simply using the icon provided by the users theme. If no user theme is found we provide a fallback icon. Perhaps we can include a config setting to ignore the user theme icon.

**Comment by AlexWayfer** [comment]
> The icon actually does appear but it is very very very hard to see.

This is not my case, I think:

![image](https://user-images.githubusercontent.com/6510020/93799481-e5699180-fc47-11ea-9f4f-210978930d6a.png)


My cursor on the left from OBS icon, and there is no any menu or icon. I have a pretty good vision (eyes?).

**Comment by borgmanJeremy** [comment]
Hmmm, it seems to be something with your specific setup since I cannot replicate it on a clean EndeavorOS installation.

**Comment by AlexWayfer** [comment]
I can try to debug somehow, if you can help with this.

```
yay -U /var/cache/pacman/pkg/flameshot-0.6.0-4-x86_64.pkg.tar.zst
```

![image](https://user-images.githubusercontent.com/6510020/93800037-a7b93880-fc48-11ea-9ce0-1052809dd418.png)

```
yay -U /var/cache/pacman/pkg/flameshot-0.8.0-1-x86_64.pkg.tar.zst
```

Oh… it's here now! Wow, weird.

![image](https://user-images.githubusercontent.com/6510020/93800187-e0f1a880-fc48-11ea-921c-8efb771f86b3.png)

OK, I'm going to close this issue without a reproducing.
