### ISSUE TITLE
Text tool missing in version 0.6.0

### ISSUE THREAD

**Issue by craigstar** [flameshot-org/flameshot#957]
**flameshot version**: 
`0.6.0`

**System Information**
`Ubuntu 18.04.5 LTS`

**install package**:
`flameshot_0.6.0_bionic_x86_64.deb`

**bug**
Still don't have text tool. I know there's a very similar closed issue, but I still can not fix the problem.
![image](https://user-images.githubusercontent.com/11722003/91948231-63660700-ed32-11ea-8122-7020ebf0fccc.png)

**Comment by borgmanJeremy** [comment]
Please upgrade to version 0.8.

**Comment by mmahmoudian** [comment]
@craigstar I close this issue since the latest stable release is 0.8 and we don't investigate bug reports from old versions. Please update your Flameshot and create a new issue if the problem was also there.

**Comment by craigstar** [comment]
sorry, I didn't notice there's a new version.....my bad

**Comment by borgmanJeremy** [comment]
No problem. Let us know if there are still any issues!
