### ISSUE TITLE
Wrong D-Bus name?

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#960]
**Flameshot version**
Flameshot v0.8.0
Compiled with Qt 5.15.0
flameshot-git   r576.f34def6-1  AUR

**Describe the bug**
The D-Bus name seems to be old. This might be the reason of some of the reported issues.

**To Reproduce**
![Peek 2020-09-23 15-55](https://user-images.githubusercontent.com/390889/94015458-92155180-fdb5-11ea-94ed-d52b1fc94715.gif)

**Expected behavior**
Have the correct name

**System Information**
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.6-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4770K CPU @ 3.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by RixzZ** [comment]
My custom command (configured con D-Bus) stopped working in some moment the past week. I had to change the custom shortcut to execute the command instead.

**Comment by mmahmoudian** [comment]
@RixzZ what is the final status of your change? How does it look like?

**Comment by borgmanJeremy** [comment]
@mmahmoudian Can this be closed since it seemed to be a pamac issue?

**Comment by RixzZ** [comment]
Thanks for the solution. I'll change it back to that.

I'll leave a screenshot of the alternative with the command anyway:
![Screenshot from 2020-09-23 17-34-07](https://user-images.githubusercontent.com/1339272/94035178-17533300-fdc3-11ea-9b12-39af398e0238.png)

This kind of custom shortcut is added with the New > Global Shortcut > Command/URL option.
