### ISSUE TITLE
Pinning is impossible with "Close after capture"

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#964]
**Flameshot version**
Flameshot v0.8.0
Compiled with Qt 5.15.0
flameshot-git   r681.def8ce2-1  AUR

**Describe the bug**
When the "Close after capture" is on, pinning the screenshot is impossible as the Flameshot terminates after taking the screenshot and before displaying the pinned image.

**To Reproduce**
"Close after capture" is on and try to pin a selected area.

**Expected behavior**
I expect the Flameshot to gets terminated after I close the pinned window.

**System Information**
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.6-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4770K CPU @ 3.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by borgmanJeremy** [comment]
Is this even a bug? The feature is close after **capture** so I would expect this.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I think this is a logical bug, in the sense that it obstructs/glitches out a behavior in the software (pinning). I think there are two ways to address this:
1. not to show the tools that "close after capture" would affect them if the "close after capture" is on
2. Flameshot stays running as long as the pinned window is not closed by user

I personally vote for the latter.

**Comment by borgmanJeremy** [comment]
I want to delete th close after capture feature 😁...so many confusing interactions

**Comment by mmahmoudian** [comment]
@borgmanJeremy I don't have very strong feeling about it. _If you have doubts,_ we can have poll to have the final verdict.

But in general from the issues I have seen and personal experience, if:
1. the "close after capture" is disabled by default **and** 
2. we have a rule that add certain tools to the chain of action so that the application termination happens after them
then the "close after capture" should not be an issue anymore.

**Comment by borgmanJeremy** [comment]
Close after catpure is removed.
