### ISSUE TITLE
Window Screenshot Timer not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by stillpointx** [flameshot-org/flameshot#972]
**Flameshot version**

rt@sys76:~$ flameshot --version
Flameshot v0.8.1
Compiled with Qt 5.9.5

**Describe the bug**

Screenshot Timer not working for the window option in Ubuntu 18.04 it doesn't wait the allotted time
When typing in **flameshot gui -d 2000**  I would think it would wait 2 seconds to take the screen shot once the window is selected and you click on save.  But it doesn't

![vokoscreen-2020-09-24_02-41-34](https://user-images.githubusercontent.com/28985314/94110614-e7cb1780-fe10-11ea-943c-78ae36ca9132.gif)

**To Reproduce**

The timer doesn't seem to be working for the window option when we click save it doesn't wait.

**Expected behavior**

When typing in **flameshot gui -d 2000**  I would think it would wait 2 seconds to take the screen shot once the window is selected and you click on save.  But it doesn't
The timer doesn't seem to be working for the window option when we click save it doesn't wait.
You may want to add some sort of countdown timer.  

The thought was to be able to take timed screenshots of window menus then use the arrows to point to them.
Like this.  Is this possible?
![crop](https://user-images.githubusercontent.com/28985314/94117814-b35c5900-fe1a-11ea-9301-eee6428654bc.jpg)

**System Information**

Ubuntu 18.04 64bit

**Comment by borgmanJeremy** [comment]
The way the delay works from the cmd line is it delays the initial fullscreen screenshot. Then the window mode just allows you to crop and annotate that fullscreen screenshot.

Try with a larger number like 5000 and this is more obvious.

**Comment by mmahmoudian** [comment]
Seems I initially misunderstood the issue and thought the delay does not happen at all. @borgmanJeremy is right, you can even see two blinks of your cursor after you executed `flameshot gui -d 2000`.

**Comment by stillpointx** [comment]
It looks like the delay is for **launching** the program, **but not taking the screen shot using a window** which is strange why would I want to delay starting the program.  **I would think you would want a delay the screenshot so you can take images of different menu options.  See image.**     Can this not be done?

![im](https://user-images.githubusercontent.com/28985314/94180657-54bfcb00-fe6c-11ea-853c-7ed5e9ab2ade.jpg)

**Comment by borgmanJeremy** [comment]
It allows you to do what you want, it delays the Capture of the full screen....When it goes to window mode you are simply cropping and editing. So you can start with a delay, get the menus ready...Then when the delay is up you crop it using the window.

**Comment by mmahmoudian** [comment]
@stillpointx In other words, run the `flameshot gui -d 5000` and then you will have 5 seconds to setup the environment as you want before flameshot captures the screenshot.

Alternatively, if you don't want to use terminal for this, you can right-click on the tray icon, select "Open Launcher" and from the window select the amount of delay in GUI:
![image](https://user-images.githubusercontent.com/390889/94182314-7b502700-fea9-11ea-9b41-6a761c2d9576.png)

**Comment by stillpointx** [comment]
So what your saying it's not possible to do this with the window at this time.

Looks like others tried back 2018 but it was closed
https://github.com/flameshot-org/flameshot/issues/233

**Comment by stillpointx** [comment]
I'll make a video to demonstrate what happens and post it.  The menus go away once you focus on another window.

**Comment by mmahmoudian** [comment]
@stillpointx I think you are doing the steps in the wrong order (based on the Gif you posted). When you run Flameshot, the screen freezes and you cannot click on stuff. What you should do is to set the delay, then while Flameshot is waiting, you go to the window you wan to capture, open the menus you want and wait until the delay time finishes. Then Flameshot is getting executed and you can select the region you want to take picture from.

Making a video would help us better understand what you are after. I can perhaps then after watching your video, make a video and show how I would do.

**Comment by stillpointx** [comment]
Ok I think I got it I made a video to show how to do this for the next person.   To be honest it confused me a bit and something stills seems a little bit off about the way it's done (Must be my old days as working as a QA creeping in).  But it's still THE BEST screenshot program out there **Great Job!!**

**Launching Flameshot from the command line with a timer option to capture menus**

1) Open command window
    Execute the command "**flameshot gui -d 6000**" (wait 6 seconds before taking screenshot)

2) Setup the window with sub-menus you wish to take a screenshot of.
    Note: Flameshot will "take a temporary screenshot of the entire full-screen"

3) Then use the Flameshot cursor to crop the portion you desire.
	
![How to use timer with a window](https://user-images.githubusercontent.com/28985314/94187160-92752180-fe75-11ea-82db-8d25389d9756.gif)

**Comment by mmahmoudian** [comment]
@stillpointx I appreciet the educational video and the explanation of steps 👍🏼  I'm glad that this is solved. Please feel free to suggest features or report bugs as we, as a community, will improve Flameshot one Pull Request at a time 😉

**Comment by stillpointx** [comment]
Will do.  Thanks Again!!
