### ISSUE TITLE
zsh-completions don't uninstall correctly and therefore block upgrading latest flameshot version

### ISSUE THREAD

**Issue by luzpaz** [flameshot-org/flameshot#974]
**Flameshot version**
git version

**Describe the bug**  
This may be packaging issue specific to Arch/Manjaro only but when uninstalling and reinstalling flameshot (specifically for me was going from 0.6 to git version) I see this error on install:
```
error: failed to commit transaction (conflicting files)
flameshot-git: /usr/share/zsh/site-functions/_flameshot exists in filesystem (owned by zsh-completions)
Errors occurred, no packages were upgraded.
```
source: https://aur.archlinux.org/packages/flameshot-git/#comment-765663

Upon trying to remove said directory I see:
```
$ rm -rf _flameshot 
rm: cannot remove '_flameshot': Permission denied
```

**To Reproduce**  
Uninstall and reinstall flameshot

**Expected behavior**  
Clean uninstall with no remenents (though this may be a downstream zsh issue)

**System Information**  
System:    Kernel: 5.8.6-1-MANJARO x86_64 bits: 64 compiler: N/A Desktop: KDE Plasma 5.19.5 Distro: Manjaro Linux

**Comment by mmahmoudian** [comment]
I faced this yesterday as well, but I thought the AUR have screwed up and I fixed it with prepending `sudo` to get the job done. Now that I looked at AUR I saw this comment:
https://aur.archlinux.org/packages/flameshot-git/#comment-765663

**Comment by borgmanJeremy** [comment]
I think the PKGBUILD should just not install our ZSH completions if they want to source it from another place. It seemed other users **wanted** us to directly provide it so it seems we cannot please everyone.

If manually fixing it in the PKGBUILD will not work we can add a CMake Flag that disables installation of it.

**Comment by mmahmoudian** [comment]
If we provide an update ZSH completion, I don't see why others would like to source it from elsewhere.

**Comment by borgmanJeremy** [comment]
I am going to close this because I feel it is an Arch packaing issue not an issue with flameshot itself.
