### ISSUE TITLE
Improve contrast in circle counter tool

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#978]
This is a follow-up and improvement for #941 and #944 .

v0.8.1 provided an initial fix to the font color issue of v0.8.0 (choosing black/white font according to the color of circle tool). The current implementation is to set a threshold on the Lightness in HSL color space (threshold=75). However, this does not work well with some colors like dark blue:

![图片](https://user-images.githubusercontent.com/8443926/94180578-36f26600-fe6c-11ea-8c73-36d58c040f88.png)

Like the one in the image above, No.2 should use a white number instead of a black number.

* * *

It's a classic problem with many discussions before. What I found:

* https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color
* https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/
* https://ux.stackexchange.com/a/114955
* Use "L" from [CIELab color space](https://en.wikipedia.org/wiki/CIELAB_color_space), which better fits human perception.

**Comment by chux0519** [comment]
Hi I've done this using the algorithm in [first link you provide](https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color). And it looks better.
