### ISSUE TITLE
Allow `-c` option to work with gui call

### ISSUE THREAD

**Issue by mcp292** [flameshot-org/flameshot#981]
## Meaning

```
flameshot gui -c -p ~/downloads
```

Will copy to clipboard whether or not you choose save or copy from the clipboard. 

## Reason
Sometimes I want to do both in case the program does not allow me to copy an image in, but I'm not sure. This way I can try to copy (faster) and if it doesn't work, I'll browse and upload file.

**Comment by borgmanJeremy** [comment]
You can change the config save to a file when copy is clicked: 
![image](https://user-images.githubusercontent.com/46930769/94326804-43f67e80-ff6c-11ea-8be0-fb5426239428.png)

**Comment by mmahmoudian** [comment]
I think considering that the functionality is already there in the config, in my opinion there will be no necessity for such features as single `sed` command can alter the config file on the fly (considering that you are running the `flameshot gui` from CLI anyways and you can append/perpend the `sed`):

![image](https://user-images.githubusercontent.com/390889/94364556-da44b480-00d2-11eb-9b9e-01d99b83f032.png)

@mcp292 & @borgmanJeremy Can we assume that this feature request should be closed?

**Comment by borgmanJeremy** [comment]
Yes I think so.

**Comment by mcp292** [comment]
You are right. Since flameshot already creates a `flameshot.ini` file, it is both easy to add the `saveAfterCopy` variable to the config or to add the `sed` call to my `.xbindkeysrc` binding. 

Thanks for the clear use examples. Problem solved.
