### ISSUE TITLE
[Feature request] Let the pinned picture out of the boundary of the screen

### ISSUE THREAD

**Issue by vio1etus** [flameshot-org/flameshot#984]
**Is your feature request related to a problem?**
Yes
I'm always frustrated when I just want to make room for other application to show in the screen temporarily，I have to zoom out the pinned picture and zoom in it back when I need to see it.

Please, a single feature per issue.
For instance, your browser == the pinned picture：
![image](https://user-images.githubusercontent.com/33022132/94222023-e4be4d00-ff1e-11ea-85ff-da79c5d87f40.png)

Let the pinned picture can be out of the the boundary of the screen:
![Peek 2020-09-25 16-26](https://user-images.githubusercontent.com/33022132/94244946-2c0f0280-ff4c-11ea-8478-8506c79a18dc.gif)

**Comment by borgmanJeremy** [comment]
I will look at including this as part of the pin tool rework on #954

**Comment by Pixel48** [comment]
Isn't it actually done?
![obraz](https://user-images.githubusercontent.com/42846410/111755301-3e358200-8899-11eb-84ea-76c953160e71.png)

**Comment by mmahmoudian** [comment]
I just checked, no it doesn't.       @Pixel48 Perhaps you have a monitor on the left side of this one that you showed, or you have a monitor below or above this that is larger in width. Can you share your monitor arrangement and show where did you take the screenshot from?

**Comment by Pixel48** [comment]
@mmahmoudian Here you go

-----
![obraz](https://user-images.githubusercontent.com/42846410/111786855-8dda7480-88be-11eb-8824-6797b326ef66.png)

**Comment by Pixel48** [comment]
![gif](https://user-images.githubusercontent.com/42846410/111790011-0ee73b00-88c2-11eb-899e-f434e58943c0.gif)

**Comment by mmahmoudian** [comment]
@Pixel48 I wonder if this discrepancy is because you have tested Windows and I have tested Linux 🤔

**Comment by Pixel48** [comment]
¯\_(ツ)_/¯

**Comment by yusanshi** [comment]
I need this too (see #1511)

**My env**
System: Ubuntu 20.04
Display server: X11
Display manager: gdm3

**Comment by mmahmoudian** [comment]
For the record, it was addressed in #2520
