### ISSUE TITLE
[Feature Request] Automated Testing

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#987]
Right now there are no tests at all in flameshot. I would like to use this thread to track ideas about how to properly add testing to improve our quality.

## Unit Tests
We can slowly refactor the code to limit the scope of functions and make them smaller so they are easily unit testable. I would like to do this using the Catch2 unit testing library

## End to End tests
This is a little bit more tricky but should find many  bugs in flameshot. I would like some system that will take automated screenshots and compare them to a template. I think this could be done with VM's in qemu. This would allow us to set arbitrary resolutions and screen configurations in a headless VM. Ideally this would catch bugs like "Doesn't work on wayland hidpi etc". 

Let me know your thoughts on the best way to get higher and effective tests into flameshot!

**Comment by Tc-001** [comment]
> I would like some system that will take automated screenshots and compare them to a template.

Taking screenshots with the flameshot cli is already possible, so comparing them with a `dif` or `[$KNOWN_GOOD == $NEW_BUILD]` in a bash script or similar should be possible

I think extending the cli options with automated testing in mind (like taking screenshots of specific areas or using the tools(arrow/line/pixelation) from the cli) could do the trick. It would probably require human review either way, because even a 1 pixel difference would fail the build on it.

If that becomes a problem, maybe a scrip to check the png pixel for pixel and fails if a certain percentage of them don't match?

**Comment by AlexP11223** [comment]
> Unit Tests

I don't have much experience with automated testing of desktop software, but in other areas integration tests are usually more useful and have lower maintenance cost (no need to rewrite lots of tests after any refactoring of internal stuff).

https://kentcdodds.com/blog/write-tests
https://tyrrrz.me/blog/unit-testing-is-overrated

Unless it's just a terminology issue. Some people refer to all tests developed using libraries like CppUnit, PhpUnit etc. as unit tests even though they can be used for many types of tests.

Usually a unit test is a test of the smallest possible unit like a class or a function, with all dependencies mocked/stubbed. Can be good to test some important complex logic, pure functions (math, ...).
And an integration test is when there is less mocking and e.g. several real classes (SUT + some dependencies) can participate in one test. 

A good starting point is high-level integration tests. For example, in web it could be testing the app API (simulating HTTP requests), mocking some parts like payments/email, database. In an app that processes some files (e.g. `diff`) it could be testing of the function that accepts the data as strings (easier than testing with real files in the file system, stdin/stdout/GUI, etc.)
And then adding more low-level integration or unit tests if needed.

---

I am not sure though if there are many things in an app like this that can be tested by non-e2e tests. There is not much logic, mostly GUI, interactions with the system (capture screenshot, show notifications), drawing.
