### ISSUE TITLE
[Windows] Pass parameters via command line argument to flameshot.exe

### ISSUE THREAD

**Issue by iterating** [flameshot-org/flameshot#988]
How do I pass parameters to Flameshot.exe on Windows?  
I'm trying to bind 'flameshot gui' to <kbd>PrintScreen</kbd> with autohotkey, but I havn't found how to call 'flameshot gui' from the Windows shell.

**Comment by iterating** [comment]
Update: Flameshot already adds that behavior by default, though 'm still curious how to pass parameters to Flameshot.exe on Windows.

**Comment by hosiet** [comment]
As of v0.8.1, flameshot compiled for Windows platform does not parse command line options at all. See https://github.com/flameshot-org/flameshot/blob/0d5386edd4223dca682c0a50e53f6931af080ee9/src/main.cpp#L93-L96 for code details.

If users need parameter parsing on Windows, I suggest renaming this issue with "Parse command line parameters also on MS Windows platform".

**Comment by borgmanJeremy** [comment]
This can be fixed when #945 is done. Boost program options is cross platform.

**Comment by borgmanJeremy** [comment]
Closing since I rolled the feedback into #945

**Comment by iterating** [comment]
Okay, thank you.
