### ISSUE TITLE
Enter to save image to disk

### ISSUE THREAD

**Issue by madprops** [flameshot-org/flameshot#991]
Just an idea: I always want to save the capture to the predefined disk path, I never use the clipboard for this stuff, and I intuitively press Enter expecting it will save it to disk, but I realized I needed ctrl+s. Enter is a lot easier than ctrl+s. Do many people copy captures to clipboard? My suggestion is simply: Maybe Enter should save to disk.

**Comment by borgmanJeremy** [comment]
Thanks for the good suggestion. This is a duplicate of #480 . 

I think a rework of the hotkey / config system will be worked on after some other new features. It's not scheduled yet but its on our radar.
