### ISSUE TITLE
Different color for x

### ISSUE THREAD

**Issue by siduxdevil** [flameshot-org/flameshot#993]
Would it be possible to give the 'x' a (slightly) different color than the other options in the edit section? I find myself searching for the 'x' every time I made a mistake and want to leave the edit section. With a (slightly) different color it would be easier to spot because depending on the size of the selection, it is in a different place every time.

**Comment by mmahmoudian** [comment]
@siduxdevil Do you know that pressing <kbd>Esc</kbd> would close the "capture screen" window? Considering this keyboard shortcut, do you still want to peruse this feature request?

**Comment by siduxdevil** [comment]
No, I did not know that. I guess, that'll do. Thank you.

Mehrad Mahmoudian <notifications@github.com> schrieb am So., 27. Sept.
2020, 13:36:
