### ISSUE TITLE
Flameshot will not invert the icon colour if the background colour is close to white

### ISSUE THREAD

**Issue by Tc-001** [flameshot-org/flameshot#994]
**Flameshot version**
v0.8.1 (have tested appimage and AUR's flameshot-git)

**Describe the bug**
When setting the main or contrast color to white (or any other light color), the icon color does not invert, making the icons near impossible to see with certain colors

**To Reproduce**
- Open flameshot
- Select main color
- Set it to white

**Expected behavior**
The icon color (shown as a white circle) should change from white to black

**System Information**
Manjaro Linux 20.1 KDE

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/55956895/94363001-bfb90e00-00c7-11eb-936d-a30362d4b44a.png)

What I got:
![image](https://user-images.githubusercontent.com/55956895/94363008-ccd5fd00-00c7-11eb-9c25-c7b7ce2dff6b.png)

This is also present in the screenshot interface for every icon except the resolution
![image](https://user-images.githubusercontent.com/55956895/94363099-8fbe3a80-00c8-11eb-982d-aa8309d32cb6.png)

**Comment by mmahmoudian** [comment]
**Confirmed:**

![image](https://user-images.githubusercontent.com/390889/94364099-956b4e80-00cf-11eb-99fe-782babcf7cf8.png)

**Comment by chux0519** [comment]
I think it is a tiny typo.

`ColorUtils::colorIsDark` should return `!isWhite`

**Comment by mmahmoudian** [comment]
@chux0519 I saw your commit in your fork. Please create a PR when you confirmed that small modification has fixed the issue. 👍🏼

**Comment by chux0519** [comment]
sure, check this out: https://github.com/flameshot-org/flameshot/pull/995
